import type { RevisionSet } from "./index";

const revision: RevisionSet = {
  "cardiovascular-hypertension": {
    checked: "2026-10",
    updated: [
      "AHA/ACC 2025: US guideline keeps 130/80 for stage 1, target under 130/80 for all adults, PREVENT risk calculator - India still diagnoses at 140/90.",
      "AHA/ACC 2025: 'hypertensive urgency' renamed severe hypertension (over 180/120) without acute organ damage.",
      "AHA/ACC 2025: screen every resistant hypertensive for primary aldosteronism whatever the potassium.",
    ],
    master: {
      heading: "Master revision table - Hypertension",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Confirmed office BP **140/90 or more** (home **135/85**, 24-h ABPM **130/80**) on 2-3 visits; one visit enough if **180/110 or more** or organ damage."],
        ["Classification (ESC 2024)", "**Non-elevated under 120/70**, **elevated 120-139/70-89**, **hypertension 140/90 or more**; white-coat, masked, resistant (3 drugs incl. diuretic), emergency vs severe hypertension without organ damage."],
        ["Aetiology and risk factors", "Essential in over 90%; salt, obesity, alcohol, inactivity, age, family history; secondary - CKD, **primary aldosteronism**, renal artery stenosis, OSA, phaeo, Cushing, coarctation, drugs (NSAIDs, OCP, steroids)."],
        ["Pathophysiology", "Salt + RAAS + sympathetic drive -> raised peripheral resistance -> vascular remodelling, LVH -> **stroke, MI, HF, CKD, retinopathy**; reset autoregulation -> never drop over 25% in first hour."],
        ["Key history (OPD)", "Duration, past readings, organ symptoms (TIA, angina, orthopnoea), **drug history (NSAIDs, OCP, herbal)**, salt (pickle, papad), tobacco, alcohol, snoring, paroxysms, pregnancy plans, adherence barriers."],
        ["Key examination", "Correct technique: seated 5 min, right cuff, **3 readings average last 2**, both arms; standing BP in elderly; BMI/waist (23/25, 90/80 cm); radio-femoral delay; bruits; **fundoscopy**."],
        ["Minimal investigations", "**UACR** (30 mg/g or more = damage), creatinine/eGFR, Na/K (K over 5.5 - no ACEi), HbA1c, lipids, **ECG for LVH (Sokolow-Lyon over 35 mm)**, uric acid, TSH; aldosterone-renin ratio when indicated."],
        ["Diagnostic criteria", "Office 140/90 confirmed by home 135/85 or ABPM 130/80; **WHO/ISH SEA chart** for 10-year risk decides drugs in elevated BP (10% or more)."],
        ["Treatment - general", "**Salt under 5 g/day**, K-enriched salt if kidneys normal, DASH Indian plate, **150 min/week exercise**, weight (1 mmHg per kg), stop tobacco, minimal alcohol, home BP monitoring, NP-NCD/IHCI enrolment."],
        ["Treatment - first line (drugs)", "**Low-dose two-drug single pill**: RAS blocker + CCB or thiazide-like (telmisartan 40 + amlodipine 5 mg); IHCI: **amlodipine 5 -> +telmisartan 40 -> 10/80 -> +chlorthalidone 12.5-25 mg**, titrate every 2-4 weeks."],
        ["Escalation / second line", "Triple single pill (RAS + CCB + thiazide-like) -> resistant: **spironolactone 25 mg** (to 50), else eplerenone, amiloride, beta-blocker, alpha-blocker; renal denervation at expert centre."],
        ["Targets and how to use", "**Systolic 120-129 if tolerated** (ESC); individualise if 85+, frail, orthostatic; once daily at a time remembered (TIME trial); check creatinine/K at 1-2 weeks after RAS blocker - accept 30% rise."],
        ["Special groups", "**Pregnancy**: labetalol, nifedipine ER, methyldopa - no ACEi/ARB; diabetes/CKD with albuminuria: ACEi/ARB + SGLT2i; elderly ISH: CCB or diuretic; child: exclude renal causes and coarctation."],
        ["Emergency", "MAP down **max 20-25% in first hour**, then 160/100 over 2-6 h; **IV labetalol 20 mg then 20-80 mg q10 min**; dissection: SBP under 120 in 20 min (esmolol); **never sublingual nifedipine**."],
        ["Complications", "Stroke (commonest in India), ICH, MI, HFpEF, AF, CKD, aortic dissection, retinopathy, vascular dementia, malignant hypertension."],
        ["Red flags and referral", "BP 180/110 with organ symptoms, papilloedema/flame haemorrhages, **pregnancy 160/110**, hypokalaemia or onset under 40, creatinine rise over 30% or K over 5.5 on RAS blocker, child or radio-femoral delay."],
        ["Follow-up", "Every **2-4 weeks while titrating**, control within 3 months, then 3-6 monthly; creatinine/K yearly; UACR, lipids, HbA1c, ECG yearly; check adherence before adding a drug."],
        ["Prevention / programme", "**NP-NCD population screening at 30+**, IHCI protocol-based free drugs, India Hypertension Control Initiative treatment cards; salt reduction (Eat Right India)."],
        ["Latest guideline change", "**AHA/ACC 2025**: target under 130/80, PREVENT, 'urgency' becomes severe hypertension, screen all resistant HT for aldosteronism; ESC 2024 three categories still guide India."],
        ["Exam one-liners", "ACEi cough - switch to ARB; amlodipine oedema - not a diuretic problem; never ACEi + ARB; 4th drug = spironolactone; headache is not a guide to BP."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Raised BP in the OPD: from reading to decision",
        steps: [
          { label: "Office BP measured correctly", detail: "Seated 5 min, 3 readings, average last 2, both arms" },
          { label: "180/110 or more?", detail: "Look for acute organ damage: chest pain, deficit, papilloedema", tone: "decision" },
          { label: "Organ damage present - emergency", detail: "Admit, IV labetalol, MAP down max 25% in 1 h", tone: "warn" },
          { label: "140-179/90-109 - confirm out of office", detail: "Home 135/85 or ABPM 130/80", tone: "decision" },
          { label: "Assess risk and organ damage", detail: "UACR, creatinine, K, HbA1c, lipids, ECG, fundus" },
          { label: "Start lifestyle + two-drug single pill", detail: "Telmisartan 40 + amlodipine 5 mg; review 2-4 weeks" },
          { label: "Controlled: systolic 120-129", detail: "Review 3-6 monthly, labs yearly", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Drug escalation ladder (ESC 2024 / IHCI)",
        steps: [
          { label: "Step 1: two-drug low-dose single pill", detail: "ARB/ACEi + CCB or thiazide-like; IHCI amlodipine 5 then add telmisartan 40" },
          { label: "Step 2: full-dose dual combination", detail: "Amlodipine 10 + telmisartan 80 mg" },
          { label: "Step 3: triple therapy", detail: "Add chlorthalidone 12.5-25 or indapamide SR 1.5 mg" },
          { label: "Step 4: resistant - add spironolactone", detail: "25 mg (to 50) if K under 4.5-5.0 and eGFR over 45; check K at 1-2 and 4 weeks", tone: "warn" },
          { label: "Step 5: alternatives and specialist", detail: "Eplerenone, amiloride, beta-blocker, alpha-blocker, clonidine; renal denervation" },
        ],
      },
      {
        kind: "compare",
        heading: "Hypertensive emergency: target and drug by organ",
        columns: ["Situation", "Target", "Drug"],
        rows: [
          ["Malignant HT / encephalopathy", "MAP down 20-25% in 1 h", "IV labetalol or nicardipine"],
          ["Aortic dissection", "SBP under 120, HR under 60 in 20 min", "IV esmolol/labetalol, then vasodilator"],
          ["Pulmonary oedema / ACS", "SBP under 140", "IV nitroglycerin + loop diuretic"],
          ["Ischaemic stroke", "Treat only over 220/120; under 185/110 before lysis", "IV labetalol"],
          ["Severe pre-eclampsia", "Under 160/110 within 1 h", "Oral nifedipine, IV labetalol or hydralazine + MgSO4"],
        ],
      },
    ],
  },

  "cardiovascular-stable-angina": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - Chronic coronary syndrome",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Chronic coronary syndrome**: CAD outside an ACS - stable angina, ANOCA/INOCA, vasospasm, stable post-ACS; angina = **exertional retrosternal constriction relieved by rest or nitrate within 5 minutes**."],
        ["Classification", "Typical (3 features), atypical (2), non-anginal (0-1); **CCS class I-IV**; ESC 2024 clinical likelihood very low 5% or less, low over 5-15, moderate 15-50, high 50-85, very high over 85%."],
        ["Aetiology and risk factors", "Atherosclerosis (Indians ~10 years earlier, diffuse disease, diabetes, high Lp(a)); tobacco, HT, DM, dyslipidaemia, CKD, family history; mimics - AS, HCM, anaemia, thyrotoxicosis."],
        ["Pathophysiology", "Endothelial dysfunction -> LDL retention/oxidation -> foam cells -> fibroatheroma -> **over 70% stenosis** -> supply-demand mismatch on exertion -> **subendocardial ischaemia (ST depression)**."],
        ["Key history (OPD)", "Site, character, duration 2-10 min, trigger, relief; CCS grade; **red flags of ACS** (rest, new, crescendo, over 20 min); PDE-5 inhibitor use; risk factors; weekly nitrate count."],
        ["Key examination", "Often normal; BP both arms, pulse, BMI; pallor, thyroid, **xanthomas/arcus under 45**; **ejection systolic murmur (AS)**, HCM murmur; HF signs; bruits, peripheral pulses."],
        ["Minimal investigations", "Resting ECG, Hb, lipids (+Lp(a) once), HbA1c, creatinine, TSH; **echo for LVEF/valves**; test by likelihood - **CCTA (low-moderate)**, functional imaging (moderate-high), ICA (very high)."],
        ["Diagnostic criteria", "Clinical likelihood + test: **CCTA normal rules out**; TMT positive = **1 mm or more horizontal/downsloping ST depression 80 ms after J point**; TMT unreadable with LBBB, paced, WPW, digoxin."],
        ["Treatment - event prevention", "**Aspirin 75-100 mg** (or clopidogrel 75 mg), **atorvastatin 40-80 / rosuvastatin 20-40 mg to LDL under 55 mg/dL and 50% fall**, ACEi/ARB if HT/DM/CKD/LVEF 40% or less, **colchicine 0.5 mg**, SGLT2i/GLP-1 RA in DM."],
        ["Treatment - anti-anginal first line", "**Beta-blocker** (metoprolol succinate 25-200 mg, bisoprolol 2.5-10 mg) and/or **CCB** - target resting HR **55-60**; **SL nitroglycerin 0.4-0.5 mg** every 5 min x 3 for attacks."],
        ["Escalation / second line", "Add amlodipine to beta-blocker; **ISMN SR 30-60 mg morning (8-12 h nitrate-free)**, ranolazine, trimetazidine MR 35 mg BD, nicorandil, ivabradine (sinus rhythm only); ezetimibe -> PCSK9i for LDL."],
        ["Procedures", "**Revascularisation** for refractory angina, or prognosis in **left main, 3-vessel/proximal LAD with LVEF 35% or less**; CABG in diabetic multivessel; after elective stent **DAPT 6 months**."],
        ["Special groups", "Vasospasm: CCB + nitrate, avoid non-selective beta-blockers; women/diabetics/elderly - anginal equivalents; asthma - rate-limiting CCB; never verapamil/diltiazem with a beta-blocker."],
        ["Complications", "ACS, sudden death, ischaemic cardiomyopathy and HF, arrhythmia, stent thrombosis if DAPT stopped early."],
        ["Red flags and referral", "Rest/new/crescendo angina, pain over 20 min or not relieved by 3 nitrates, syncope, HF, dynamic ST change - **same day**; CCS III-IV despite 2 drugs - routine referral."],
        ["Follow-up", "2-4 weeks after drug change, then 3-6 monthly year 1; **lipids 4-8 weeks**, then yearly; targets LDL under 55, BP under 130/80, HbA1c under 7%, HR 55-60, no tobacco."],
        ["Prevention", "Tobacco cessation, cardiac rehab, Indian heart-healthy diet, BMI under 23, influenza vaccine, treat depression and OSA; semaglutide in obesity (SELECT)."],
        ["Exam one-liners", "Medicines prevent death, stents relieve symptoms (ISCHEMIA); ivabradine useless in AF; nitrate-free interval mandatory; no nitrate within 24 h of sildenafil, 48 h of tadalafil."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Suspected angina: likelihood decides the first test",
        steps: [
          { label: "Chest pain - any ACS red flag?", detail: "Rest, new, crescendo, over 20 min, dynamic ECG", tone: "decision" },
          { label: "Yes - treat as ACS, ambulance", tone: "warn" },
          { label: "No - ECG, bloods, echo", detail: "LVEF, AS, Hb, lipids, HbA1c, TSH" },
          { label: "Estimate clinical likelihood (ESC 2024)", detail: "Symptoms, age, sex, risk factors", tone: "decision" },
          { label: "Very low 5% or less - look elsewhere" },
          { label: "Low-moderate - CT coronary angiography", detail: "Normal CCTA rules out obstructive CAD" },
          { label: "Moderate-high - functional imaging; very high - ICA", detail: "TMT only if imaging unavailable" },
          { label: "Diagnosis made - start OMT", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Optimal medical therapy in CCS",
        steps: [
          { label: "Everyone: event-prevention drugs", detail: "Aspirin 75-100 mg, high-intensity statin to LDL under 55, ACEi/ARB if indicated" },
          { label: "Step 1: beta-blocker and/or CCB", detail: "Metoprolol succinate 25-200 mg or bisoprolol 2.5-10 mg; HR 55-60" },
          { label: "Step 2: combine beta-blocker + amlodipine 5-10 mg", detail: "Never verapamil/diltiazem with a beta-blocker", tone: "warn" },
          { label: "Step 3: add long-acting nitrate or second-line", detail: "ISMN SR 30-60 mg AM; ranolazine 375-750 mg BD; trimetazidine 35 mg BD; nicorandil" },
          { label: "Step 4: refractory - revascularise", detail: "PCI or CABG; prognostic in left main / 3-vessel with LVEF 35% or less", tone: "good" },
        ],
      },
    ],
  },

  "cardiovascular-acs": {
    checked: "2026-10",
    updated: [
      "UDMI 2026 (Fifth Universal Definition): sex-specific 99th percentile troponin; troponin rise alone is injury, not infarction.",
      "UDMI 2026: types 1-5 replaced by primary, secondary and procedure-related MI (vasospasm and SCAD now primary MI).",
      "ACC/AHA 2025: ticagrelor monotherapy from 1 month after PCI in patients tolerating ticagrelor-based DAPT; ticagrelor/prasugrel preferred over clopidogrel.",
    ],
    master: {
      heading: "Master revision table - Acute coronary syndrome",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Acute myocardial ischaemia from plaque rupture/erosion with thrombus; **MI = troponin rise/fall above sex-specific 99th percentile + ischaemia evidence** (UDMI 2026); troponin alone = injury."],
        ["Classification", "By ECG: **STEMI** vs **NSTE-ACS** (NSTEMI / unstable angina); UDMI 2026 settings: **primary, secondary, procedure-related MI**; Killip I-IV; NSTE-ACS risk very high / high (GRACE over 140) / not high."],
        ["Aetiology and risk factors", "Atherothrombosis (rupture two-thirds, erosion in young/women/smokers), SCAD, embolism, spasm; tobacco, DM, HT, lipids; Indians 5-10 years younger, more STEMI and delay."],
        ["Pathophysiology", "Rupture -> tissue factor + platelet adhesion/aggregation (GP IIb/IIIa) -> **occlusive fibrin-rich thrombus (STEMI)** or non-occlusive platelet thrombus (NSTE-ACS) -> necrosis wavefront over 3-6 h -> **time is muscle**."],
        ["Key history", "Pain over 20 min, not relieved by rest/nitrate, sweating, nausea; **exact onset time**; atypical in women, elderly, DM; mimics (dissection, PE, pericarditis); lysis contraindications; PDE-5 use."],
        ["Key examination", "Vitals, SpO2, **BP both arms**, Killip (crackles, S3), shock signs, new murmur (VSR, MR), **raised JVP + clear lungs + hypotension = RV infarct**; defibrillator at bedside."],
        ["Minimal investigations", "**ECG within 10 minutes**, repeat 15-30 min; V3R-V4R, V7-V9; **hs-troponin 0/1 h**; Hb, platelets, creatinine, K, glucose; POCUS; **never delay reperfusion for troponin**."],
        ["Diagnostic criteria (ECG)", "ST elevation at J point in 2 contiguous leads: **1 mm**; V2-V3 **2 mm men 40+, 2.5 mm men under 40, 1.5 mm women**; equivalents - posterior MI, Sgarbossa LBBB/paced, de Winter, aVR elevation + diffuse depression."],
        ["Treatment - first line", "**Aspirin 150-300 mg chewed**; PCI: **ticagrelor 180 mg** or **prasugrel 60 mg**; lysis: **clopidogrel 300 mg (75 mg if over 75)**; enoxaparin/UFH; **atorvastatin 80 mg**; oxygen only if SpO2 under 90%."],
        ["Reperfusion", "**Primary PCI if within 120 min of diagnosis**, else **tenecteplase within 10 min** (30-50 mg by weight, half dose 75+) or **streptokinase 1.5 MU over 30-60 min**; then angiography in 2-24 h (pharmacoinvasive)."],
        ["Escalation / secondary prevention", "DAPT 12 months (ticagrelor monotherapy from 1 month allowed); beta-blocker if LVEF 40% or less; ramipril; eplerenone if LVEF 40% or less + HF/DM; LDL under 55 - ezetimibe, PCSK9i; PPI."],
        ["Procedures / NSTE-ACS timing", "Angiography **under 2 h** very high risk (shock, refractory pain, arrhythmia, AHF), **within 24 h** high risk (NSTEMI, GRACE over 140); failed lysis (ST fall under 50% at 60-90 min) = **rescue PCI**."],
        ["Special groups", "RV infarct: fluids, no nitrates/diuretics; elderly: half-dose TNK, clopidogrel 75 mg; AF: triple therapy max 1 week then DOAC + clopidogrel; cocaine ACS: no beta-blocker; secondary MI: treat cause."],
        ["Complications", "VF (first hour), heart block, cardiogenic shock, LV failure, **mechanical rupture days 2-7** (free wall, VSR, papillary), LV thrombus, pericarditis, Dressler, aneurysm."],
        ["Red flags and referral", "Shock (SBP under 90 + hypoperfusion), new pansystolic murmur, failed lysis, VT/complete block, dissection signs (no lysis), bleeding on DAPT."],
        ["Follow-up", "Review in 1-2 weeks, then 1, 3, 6, 12 months; **lipids 4-6 weeks**; creatinine/K 1-2 weeks after ACEi/MRA; **echo at 6-12 weeks - LVEF 35% or less = ICD**; write DAPT stop date."],
        ["Prevention / programme", "**STEMI India hub-and-spoke** pharmacoinvasive model; cardiac rehab, tobacco cessation, influenza vaccine, SGLT2i/GLP-1 RA in DM."],
        ["Exam one-liners", "No lysis in NSTE-ACS; never repeat streptokinase; clopidogrel is the only P2Y12 with lytics; no nitrates in RV infarct or after PDE-5i; mechanical complications peak days 2-7."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "STEMI in a clinic without a cath lab",
        steps: [
          { label: "Chest pain - ECG within 10 minutes" },
          { label: "STEMI or equivalent?", detail: "Add V3R-V4R, V7-V9 if needed", tone: "decision" },
          { label: "Load: aspirin 300 chewed, statin 80", detail: "Monitor, defibrillator, IV line" },
          { label: "PCI possible within 120 min?", tone: "decision" },
          { label: "Yes - transfer for primary PCI", detail: "Ticagrelor 180 or prasugrel 60 mg" },
          { label: "No - lyse within 10 min of diagnosis", detail: "TNK 30-50 mg + clopidogrel 300 + enoxaparin; check contraindications", tone: "warn" },
          { label: "ST fall over 50% at 60-90 min?", detail: "No - rescue PCI", tone: "decision" },
          { label: "Angiography in 2-24 h for all lysed", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "After ACS: drugs every patient leaves with",
        steps: [
          { label: "Aspirin 75-100 mg lifelong" },
          { label: "P2Y12 for 12 months", detail: "Ticagrelor 90 mg BD or prasugrel 10 mg; ticagrelor alone from 1 month if tolerated; 1-3 months if high bleeding risk" },
          { label: "High-intensity statin", detail: "Atorvastatin 80 mg; LDL under 55; add ezetimibe, then PCSK9i at 4-6 weeks" },
          { label: "Beta-blocker and ACEi", detail: "Clearly indicated if LVEF 40% or less; ramipril 2.5 to 5 mg BD" },
          { label: "MRA if LVEF 40% or less with HF or DM", detail: "Eplerenone 25-50 mg; K under 5.0" },
          { label: "Rehab, tobacco stop, PPI, echo at 6-12 weeks", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "UDMI 2026: three settings of MI",
        columns: ["Setting", "Mechanism", "Management focus"],
        rows: [
          ["Primary MI", "Acute coronary pathology - atherothrombosis, SCAD, embolism, vasospasm, late stent thrombosis", "Antithrombotics, reperfusion as indicated"],
          ["Secondary MI", "Supply-demand mismatch from another acute illness (tachyarrhythmia, anaemia, hypoxia, hypotension)", "Treat the cause; no thrombolysis"],
          ["Procedure-related MI", "Within 30 days of PCI or CABG (old types 4-5)", "Interventional / surgical team"],
        ],
      },
    ],
  },

  "cardiovascular-heart-failure": {
    checked: "2026-10",
    updated: [
      "ESC 2026: HFmrEF abolished - HFrEF is LVEF under 50%, HFpEF 50% or more; HFimpEF = rise of 10 points or more to over 40%.",
      "ESC 2026: GDMT split into foundational (ARNI/ACEi/ARB, beta-blocker, MRA, SGLT2i) and additional medical therapy.",
      "ESC 2026: MRA and SGLT2 inhibitor foundational (Class I) at every LVEF, including HFpEF; GLP-1 RA (semaglutide, tirzepatide) IIa in HFpEF with obesity.",
      "ESC 2026: 'acute HF' renamed decompensated HF; SGLT2 inhibitor started in hospital after stabilisation; stages A-D adopted.",
      "ESC 2026: iron deficiency defined primarily by TSAT under 20%.",
    ],
    master: {
      heading: "Master revision table - Heart failure",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Syndrome of **breathlessness, oedema, fatigue** from structural/functional cardiac abnormality, with **raised natriuretic peptide or objective congestion**."],
        ["Classification (ESC 2026)", "**HFrEF LVEF under 50%**, **HFpEF 50% or more** - HFmrEF abolished; HFimpEF (rise 10 points to over 40%); **stages A-D**; NYHA I-IV; **decompensated HF** replaces acute HF; warm/cold, wet/dry."],
        ["Aetiology and risk factors", "IHD (~70% in India), hypertension, DCM, **rheumatic valve disease**, alcohol, peripartum, thyroid, anaemia, thiamine, constriction (TB), anthracyclines, tachycardiomyopathy."],
        ["Pathophysiology", "Index injury -> low output -> **sympathetic + RAAS + ADH activation** -> vasoconstriction, Na/water retention, remodelling -> congestion and worsening pump; natriuretic peptides counter-regulate (neprilysin breaks them)."],
        ["Key history (OPD)", "NYHA class, **orthopnoea, PND** (most specific), oedema, weight gain **2 kg in 3 days**, cause (MI, HT, RHD, alcohol, pregnancy), precipitants, **NSAIDs/pioglitazone/verapamil**, adherence."],
        ["Key examination", "Weight, pulse, BP lying/standing, **JVP + hepatojugular reflux**, displaced apex, **S3**, crackles, effusion, oedema, hepatomegaly, perfusion (cold peripheries)."],
        ["Minimal investigations", "**NT-proBNP** (chronic under 125, acute under 300 pg/mL rules out); **echo (LVEF)**; ECG (QRS width), CXR; Na, K, creatinine, Hb, HbA1c, lipids, TSH; **iron studies - TSAT under 20%**."],
        ["Diagnostic criteria", "Symptoms/signs + raised peptide + echo abnormality; Framingham (2 major or 1 major + 2 minor) for bedside exam answers."],
        ["Treatment - first line (HFrEF)", "**Four foundational therapies** at low dose within weeks: **sacubitril/valsartan 24/26-49/51 to 97/103 mg BD** (or enalapril/ramipril), **bisoprolol 1.25 to 10 mg**, **spironolactone 12.5-25 to 50 mg**, **dapagliflozin/empagliflozin 10 mg**; titrate 1-2 weekly."],
        ["Congestion and HFpEF", "**Furosemide 20-40 mg** (to 240/day) or torsemide - symptoms only; **HFpEF: SGLT2i + MRA (spironolactone or finerenone)**, diuretic, BP/AF control, **semaglutide or tirzepatide if obese**."],
        ["Escalation / additional therapy", "Ivabradine (sinus, HR 70 or more), digoxin (0.5-0.9 ng/mL), vericiguat after worsening, hydralazine-ISDN; **IV ferric carboxymaltose** for iron deficiency; ICD if LVEF 35% or less, CRT if QRS 150 ms LBBB."],
        ["How to titrate safely", "**36 h washout ACEi -> ARNI**; creatinine/K at 1-2 weeks; accept creatinine rise 50% and K up to 5.5; MRA not if K over 5.0 or eGFR under 30; SGLT2i eGFR dip up to 30% expected; beta-blocker when dry."],
        ["Special groups", "Pregnancy/peripartum: stop ACEi/ARNI/MRA/SGLT2i - metoprolol, hydralazine-nitrate, furosemide, ? bromocriptine; DM + CKD: finerenone; avoid pioglitazone, saxagliptin, NSAIDs, non-DHP CCB in HFrEF."],
        ["Decompensated HF (emergency)", "Sit up, O2 only if SpO2 under 90%, **IV furosemide 40-80 mg (1-2.5x oral dose)**, urine Na over 50-70 at 2 h, **GTN if SBP over 110**, NIV, no routine morphine; shock - noradrenaline + dobutamine; start SGLT2i before discharge."],
        ["Complications", "Arrhythmia and sudden death, AF, cardiorenal syndrome, hyperkalaemia, hyponatraemia, cachexia, thromboembolism, depression."],
        ["Red flags and referral", "Pulmonary oedema, cardiogenic shock, syncope/VT with LVEF 35% or less, K over 6.0, new murmur, peripartum breathlessness, weight gain despite doubled diuretic."],
        ["Follow-up", "1-2 weekly during titration (STRONG-HF: full doses within 2 weeks of discharge), then 3-6 monthly; **echo after 3 months OMT** for ICD/CRT; **HFimpEF - never withdraw drugs** (TRED-HF)."],
        ["Prevention", "Control HT, DM (SGLT2i), CAD, alcohol; daily weights, salt under 5 g, influenza/pneumococcal vaccine, cardiac rehab, palliative care in advanced HF."],
        ["Latest guideline change", "**ESC 2026**: two phenotypes (cut-off 50%), foundational vs additional therapy, MRA + SGLT2i Class I at any LVEF, GLP-1 RA in obese HFpEF, decompensated HF, TSAT-based iron deficiency."],
        ["Exam one-liners", "Diuretics relieve, foundational drugs prolong life; only bisoprolol, carvedilol, metoprolol succinate, nebivolol; ivabradine useless in AF; BNP (not NT-proBNP) rises on ARNI."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Suspected heart failure: diagnosis to phenotype (ESC 2026)",
        steps: [
          { label: "Breathlessness, oedema, fatigue", detail: "History, exam, ECG" },
          { label: "NT-proBNP 125 pg/mL or more?", detail: "Acute: 300 or more", tone: "decision" },
          { label: "Below cut-off - HF unlikely, look elsewhere" },
          { label: "Echocardiography: measure LVEF", tone: "decision" },
          { label: "LVEF under 50% - HFrEF", detail: "Includes old HFmrEF 41-49%", tone: "warn" },
          { label: "LVEF 50% or more + structural/diastolic change - HFpEF" },
          { label: "Find the cause and start foundational therapy", detail: "Ischaemia, valves, HT, alcohol, peripartum, thyroid", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "HFrEF: foundational then additional therapy",
        steps: [
          { label: "Start all four foundational drugs early at low dose", detail: "Sacubitril/valsartan 24/26 BD, bisoprolol 1.25 mg, spironolactone 12.5-25 mg, dapagliflozin 10 mg" },
          { label: "Titrate every 1-2 weeks to target", detail: "ARNI 97/103 BD, bisoprolol 10 mg; creatinine and K at 1-2 weeks" },
          { label: "Diuretic to dry weight", detail: "Furosemide 20-40 mg; flexible by daily weight" },
          { label: "Additional therapy if still symptomatic", detail: "Ivabradine if sinus HR 70+; IV iron if TSAT under 20%; vericiguat; digoxin; H-ISDN" },
          { label: "Devices at 3 months of OMT", detail: "LVEF 35% or less - ICD; QRS 150 ms LBBB - CRT", tone: "good" },
          { label: "Advanced HF - LVAD, transplant, palliation", tone: "warn" },
        ],
      },
      {
        kind: "compare",
        heading: "HFrEF versus HFpEF after ESC 2026",
        columns: ["Feature", "HFrEF", "HFpEF"],
        rows: [
          ["LVEF", "Under 50%", "50% or more"],
          ["Typical patient", "Post-MI, DCM, younger men", "Elderly, women, HT, obesity, DM, AF"],
          ["Foundational drugs", "ARNI/ACEi/ARB + beta-blocker + MRA + SGLT2i", "SGLT2i + MRA"],
          ["Extra options", "Ivabradine, vericiguat, digoxin, ICD/CRT", "GLP-1 RA if obese (IIa), diuretic, BP/AF control"],
        ],
      },
    ],
  },

  "cardiovascular-dyslipidaemia": {
    checked: "2026-10",
    updated: [
      "ACC/AHA 2026 dyslipidemia guideline replaces 2018: LDL goals return (under 100, under 70 high PREVENT risk, under 55 very high-risk ASCVD); PREVENT replaces pooled cohort equations.",
      "ACC/AHA 2026: Lp(a) at least once in every adult with cascade testing; over 125 nmol/L about 1.4-fold, over 250 nmol/L 2-fold risk.",
      "ACC/AHA 2026: adult lipid screening from 19 years every 5 years and universal child screening at 9-11 years.",
    ],
    master: {
      heading: "Master revision table - Dyslipidaemia",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Abnormal lipids raising ASCVD risk: **LDL 130 or more, TG 150 or more, HDL under 40 (M)/50 (F), non-HDL 160 or more mg/dL**; Indian phenotype - **atherogenic (high TG, low HDL, small dense LDL)**."],
        ["Classification", "**LAI 2023 risk categories**: low, moderate, high, very high, extreme A, extreme B; primary (FH, FCHL) vs secondary; Fredrickson I-V for short notes only."],
        ["Aetiology and risk factors", "Genetic (FH 1 in 250 - LDLR, APOB, PCSK9); secondary - **diabetes, hypothyroidism, nephrotic syndrome, cholestasis, alcohol**, drugs (thiazides, steroids, PIs, retinoids)."],
        ["Pathophysiology", "ApoB particles retained in intima -> oxidised LDL -> macrophage foam cells -> fibroatheroma -> rupture -> ACS/stroke; **PCSK9 degrades LDL receptor**; TG over 1000 -> **pancreatitis**."],
        ["Key history (OPD)", "Established ASCVD, DM, HT, CKD, tobacco; **family history of premature CAD/FH**; secondary-cause symptoms; diet (ghee, vanaspati); past statin symptoms (nocebo); pregnancy plans; interacting drugs."],
        ["Key examination", "BMI, waist 90/80 cm, BP, acanthosis; **tendon xanthomas (FH)**, arcus under 45, eruptive xanthomas (TG over 1000), palmar crease xanthomas (type III), lipaemia retinalis; ABI."],
        ["Minimal investigations", "Non-fasting lipid profile (fast if TG over 400; Friedewald invalid - Martin-Hopkins/direct LDL); **TSH, HbA1c, creatinine, ALT**; **Lp(a) once in every adult** (50 mg/dL or more = risk enhancer)."],
        ["Risk assessment", "Place in LAI category -> target; ASCVD = very high without scoring; CAC 100 or more reclassifies up; **Dutch Lipid Clinic score over 8 = definite FH**; ACC/AHA 2026 uses PREVENT."],
        ["Targets", "**LAI**: LDL under 100 (low-moderate), under 70 (high), **under 50 (very high, extreme A)**, **30 or less (extreme B)**; non-HDL = LDL + 30; ESC/ACC-AHA very high risk **under 55 + 50% fall**."],
        ["Treatment - first line", "Lifestyle (sat fat under 7%, no trans fat, fibre, exercise); **statin**: high intensity **atorvastatin 40-80 / rosuvastatin 20-40 mg**, moderate atorva 10-20 / rosuva 5-10 mg; any time (simvastatin at night)."],
        ["Escalation", "**Ezetimibe 10 mg** -> **bempedoic acid 180 mg** or **PCSK9 mAb (evolocumab 140 mg q2w)** / **inclisiran 284 mg day 0, 3 months, 6-monthly**; very high risk far from target - statin + ezetimibe together."],
        ["Triglycerides", "150-499: lifestyle, glucose, get LDL/non-HDL to target; **icosapent ethyl 2 g BD** if high risk; **500 or more: fenofibrate 145/160 mg** + omega-3, no alcohol; never gemfibrozil with statin."],
        ["Special groups", "Pregnancy: stop statins 1-3 months before conception (bile acid sequestrants only); CKD: statin +/- ezetimibe, don't start on dialysis; FH child: statin from 8-10 y; HIV: pitavastatin."],
        ["Adverse effects", "Myalgia: CK + TSH, stop 2-4 weeks, rechallenge lower/alternate-day; **CK over 10x = rhabdomyolysis**; ALT over 3x stop; slight new diabetes risk - continue; rosuvastatin start 5-10 mg in Asians."],
        ["Emergency", "**Hypertriglyceridaemic pancreatitis** (TG over 1000): NBM, fluids, **IV insulin 0.1-0.3 U/kg/h + dextrose**, plasmapheresis if refractory; statin rhabdomyolysis - stop, IV fluids."],
        ["Red flags and referral", "TG over 1000 with abdominal pain; LDL 190 or more or tendon xanthomas (FH - cascade screen); LDL over 500 in child (HoFH); dark urine on statin; above target on maximal oral therapy."],
        ["Follow-up", "Lipids **4-12 weeks** after change, then 6-12 monthly; check adherence before escalating; low LDL on treatment is safe."],
        ["Screening / prevention", "Adults from 18-20 every 5 years; **children 9-11 years universally**, from 2 years if FH/premature ASCVD in parent; cascade screening of FH relatives."],
        ["Latest guideline change", "**ACC/AHA 2026**: LDL goals return (under 55 in very high-risk ASCVD), PREVENT replaces PCE, universal Lp(a) once; ESC/EAS 2025 focused update; LAI 2023 remains the Indian standard."],
        ["Exam one-liners", "Treat the risk, not the number; each statin dose doubling adds ~6% LDL fall; Lp(a) not lowered by statins; xanthelasma is non-specific, tendon xanthoma means FH."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Abnormal lipids: from report to target",
        steps: [
          { label: "Lipid profile (non-fasting)", detail: "Fast only if TG over 400" },
          { label: "TG over 1000 mg/dL?", detail: "Pancreatitis risk - fenofibrate, no alcohol, urgent", tone: "warn" },
          { label: "Exclude secondary causes", detail: "TSH, HbA1c, creatinine, ALT, urine protein, drugs" },
          { label: "Assign LAI risk category", detail: "ASCVD = very high; DLCN for FH; Lp(a), CAC if uncertain", tone: "decision" },
          { label: "Set LDL and non-HDL target", detail: "100 / 70 / 50 / 30 mg/dL; non-HDL = LDL + 30" },
          { label: "Start statin intensity to match", detail: "Lifestyle trial 3 months only in low-moderate risk" },
          { label: "Recheck at 4-12 weeks - at target", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "LDL-lowering escalation",
        steps: [
          { label: "Maximal tolerated statin", detail: "Atorvastatin 40-80 or rosuvastatin 20-40 mg; ~50% fall" },
          { label: "Add ezetimibe 10 mg", detail: "Further 20-25%; start together if far from target" },
          { label: "Statin intolerance: bempedoic acid 180 mg", detail: "17-25% fall; gout risk" },
          { label: "PCSK9 mAb or inclisiran", detail: "Evolocumab 140 mg SC q2w / inclisiran 284 mg day 0, 3 months, then 6-monthly; 50-60% fall" },
          { label: "LDL at target - continue lifelong", tone: "good" },
        ],
      },
    ],
  },

  "cardiovascular-atrial-fibrillation": {
    checked: "2026-10",
    updated: [
      "AHA 2025 ACLS: synchronised cardioversion of AF - first shock 200 J or more biphasic (replaces 120-200 J).",
    ],
    master: {
      heading: "Master revision table - Atrial fibrillation",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Supraventricular arrhythmia with uncoordinated atrial activation: **no P waves, irregularly irregular RR**, documented on 12-lead ECG or **30 s single-lead strip**."],
        ["Classification", "**First-diagnosed, paroxysmal (under 7 days), persistent (over 7 days), long-standing persistent (12 months or more), permanent**; valvular = moderate-severe MS or mechanical valve; EHRA symptom score."],
        ["Aetiology and risk factors", "HT, IHD, HF, **rheumatic MS (India)**, thyrotoxicosis, alcohol (holiday heart), OSA, obesity, DM, age, PE, pneumonia, post-surgery."],
        ["Pathophysiology", "Pulmonary vein triggers + fibrotic atrial substrate -> re-entrant wavelets -> **AF begets AF**; loss of atrial kick; **LAA stasis -> thrombus -> cardioembolic stroke (5x risk)**."],
        ["Key history (OPD)", "Palpitations, breathlessness, syncope (tachy-brady, pre-excitation), **CHA2DS2-VA items**, rheumatic fever, thyroid symptoms, alcohol, snoring, bleeding history, interacting drugs, cost/INR access."],
        ["Key examination", "Irregularly irregular pulse, **apex-radial deficit**, absent a wave, variable S1, **MS murmur**, HF signs, thyroid signs, neuro screen, bleeding/anaemia."],
        ["Minimal investigations", "**12-lead ECG**, **echo in every new AF** (MS, LVEF, LA size), **TSH**, Hb, **Cockcroft-Gault CrCl**, LFT, electrolytes, INR; Holter for paroxysmal; TOE before early cardioversion."],
        ["Stroke risk - CHA2DS2-VA", "C HF 1, H HT 1, **A2 age 75+ 2**, D DM 1, **S2 stroke/TIA 2**, V vascular 1, A 65-74 1; **2 or more - anticoagulate; 1 - consider**; no sex point (ESC 2024)."],
        ["Treatment - first line (anticoagulation)", "**DOAC over warfarin**: apixaban 5 mg BD (2.5 if 2 of age 80+, wt 60 kg or less, creat 1.5+), rivaroxaban 20 mg OD with food, dabigatran 150 BD, edoxaban 60 OD; **warfarin INR 2-3 in MS/mechanical valve**."],
        ["Rate control", "Lenient **resting rate under 110**; beta-blocker any LVEF (metoprolol succinate 25-200 mg); diltiazem/verapamil only if **LVEF over 40%**; digoxin add-on (level under 1.2 ng/mL)."],
        ["Rhythm control / procedures", "Early rhythm control within 12 months if CV risk (EAST-AFNET 4); flecainide/propafenone in normal heart; amiodarone in structural disease; **PVI ablation** first-line option in paroxysmal; LAA occlusion if OAC impossible."],
        ["Cardioversion", "Unstable: **synchronised DC 200 J or more biphasic** now; stable under 24 h - cardiovert after anticoagulation; 24 h or more/unknown - **3 weeks OAC or TOE**; OAC **4 weeks after** all cardioversions."],
        ["Special groups", "Rheumatic MS/mechanical valve: **warfarin, never DOAC** (INVICTUS); pregnancy: LMWH; CrCl under 30 no dabigatran, under 15 no Xa inhibitor; post-stent: triple max 1 week then DOAC + clopidogrel to 12 months."],
        ["Complications", "Stroke/systemic embolism, tachycardiomyopathy, HF, bleeding on OAC, dementia; pre-excited AF -> VF."],
        ["Red flags and referral", "Haemodynamic instability, **pre-excited AF (no AV nodal blockers)**, stroke/TIA, limb or mesenteric embolism, major bleeding, rate over 150 with symptoms, MS."],
        ["Follow-up", "AF-CARE 'E': review at 6 months then yearly; DOAC - Hb, CrCl, LFT yearly (CrCl/10 months if under 60); warfarin INR 4-weekly, TTR over 70%; missed DOAC: 6 h (BD) / 12 h (OD) rule."],
        ["Prevention / comorbidity", "BP 120-129, **weight loss 10%**, alcohol 3 drinks/week or less, exercise, OSA/DM/thyroid treatment; opportunistic pulse/ECG screening at 65+."],
        ["Exam one-liners", "Aspirin is no substitute for OAC; HAS-BLED never withholds OAC; dose DOACs by Cockcroft-Gault; ivabradine and AV nodal blockers useless/dangerous in pre-excited AF; check TSH and echo in all."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "New AF in the clinic: the AF-CARE sequence",
        steps: [
          { label: "Irregular pulse - confirm on ECG", detail: "No P waves, irregular RR; 30 s strip" },
          { label: "Haemodynamically unstable?", detail: "SBP under 90, pulmonary oedema, ischaemia, confusion", tone: "decision" },
          { label: "Yes - synchronised DC cardioversion", detail: "First shock 200 J or more biphasic, heparin", tone: "warn" },
          { label: "Stable - echo, TSH, CrCl, Hb", detail: "MS or mechanical valve changes the drug" },
          { label: "CHA2DS2-VA 2 or more?", detail: "1 - consider; 0 - none", tone: "decision" },
          { label: "Anticoagulate: DOAC (warfarin in MS)", detail: "Fix modifiable bleeding risks" },
          { label: "Rate control under 110 + treat comorbidity", detail: "Consider early rhythm control" },
          { label: "Dynamic review at 6 months, then yearly", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Rate control by LVEF",
        steps: [
          { label: "Beta-blocker (any LVEF)", detail: "Metoprolol succinate 25-200 mg or bisoprolol 1.25-10 mg" },
          { label: "LVEF over 40%: diltiazem or verapamil alternative", detail: "Diltiazem SR 120-360 mg/day; avoid in LVEF 40% or less" },
          { label: "Add digoxin if still fast or sedentary/HF", detail: "0.0625-0.25 mg OD; level under 1.2 ng/mL; watch K" },
          { label: "Acute with HF: IV amiodarone or digoxin", detail: "Amiodarone 300 mg over 1 h then 900 mg/24 h", tone: "warn" },
          { label: "Refractory: ablate-and-pace or rhythm control", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "DOAC dosing at a glance",
        columns: ["DOAC", "Standard", "Reduced", "Avoid if CrCl"],
        rows: [
          ["Apixaban", "5 mg BD", "2.5 mg BD if 2 of: age 80+, wt 60 kg or less, creat 1.5+", "Under 15"],
          ["Rivaroxaban", "20 mg OD with evening meal", "15 mg OD if CrCl 15-49", "Under 15"],
          ["Dabigatran", "150 mg BD", "110 mg BD if 80+ or verapamil", "Under 30"],
          ["Edoxaban", "60 mg OD", "30 mg if CrCl 15-50, wt 60 kg or less, P-gp inhibitor", "Under 15"],
        ],
      },
    ],
  },

  "cardiovascular-ecg-interpretation": {
    checked: "2026-10",
    updated: [
      "ERC 2025: peri-arrest doses re-cited (atropine 500 microgram to 3 mg, amiodarone 300 mg over 10-20 min, procainamide 10-15 mg/kg); AF cardioversion first shock 200 J or more (AHA 2025).",
    ],
    master: {
      heading: "Master revision table - ECG interpretation",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Recording of cardiac depolarisation/repolarisation from **6 limb (frontal) + 6 chest (horizontal) leads**; standard **25 mm/s, 10 mm/mV** - small square 0.04 s, large 0.20 s."],
        ["Classification of findings", "Rate/rhythm disorders, conduction blocks (AV, BBB, fascicular), chamber enlargement, ischaemia/infarction, metabolic/drug/channelopathy patterns."],
        ["Physiology basis", "SA node (If) -> atria (P) -> **AV node delay (PR)** -> His-Purkinje (narrow QRS) -> plateau (ST isoelectric) -> repolarisation (T); subendocardial ischaemia -> ST depression; transmural injury -> ST elevation + reciprocal change."],
        ["When to record", "**Within 10 minutes** for chest pain, breathlessness, syncope, palpitations; baseline in HT, DM, CKD; suspected hyperkalaemia; overdose; before QT-prolonging drugs; note pain at time of recording."],
        ["Technique", "V1-V2 **4th ICS** (too high mimics septal MI/Brugada), V4 5th ICS MCL, V5-V6 same level; **V3R-V4R in inferior STEMI**, **V7-V9 when V1-V3 depressed**; arm reversal inverts lead I."],
        ["Systematic method", "Identity/calibration -> **rate (300/large squares; irregular x6)** -> rhythm -> **axis (I and aVF, then II)** -> PR -> QRS -> QTc -> P -> QRS voltage/Q -> ST -> T/U -> compare -> one-line conclusion."],
        ["Normal values", "Rate 60-100, **PR 0.12-0.20 s**, **QRS under 0.12 s**, **QTc under 450 (M)/460 (F) ms**, axis -30 to +90, transition V3-V4."],
        ["Ischaemia criteria", "STEMI: **1 mm in 2 contiguous leads; V2-V3 2 mm men 40+, 2.5 mm under 40, 1.5 mm women**; NSTE-ACS: ST depression 0.5 mm or new T inversion; pathological Q over 0.04 s or 25% of R."],
        ["STEMI equivalents", "**Posterior MI** (ST depression V1-V3, tall R; V7-V9 0.5 mm), **Sgarbossa** in LBBB/paced, **de Winter T**, hyperacute T, **aVR elevation + depression in 6 leads** (left main), **Wellens** (critical LAD - no stress test)."],
        ["Chamber and conduction", "LVH: **Sokolow-Lyon 35 mm**, Cornell 28/20 mm; RVH: R V1 7 mm; RBBB rSR' V1; LBBB broad S V1, notched R V6; LAFB axis -45 to -90; **Mobitz II and CHB need pacing**."],
        ["Metabolic and drug patterns", "**Hyperkalaemia**: peaked T -> flat P/long PR -> wide QRS -> sine wave; hypokalaemia U waves; hypocalcaemia long QT; digoxin reverse tick; TCA QRS over 0.10 s, R aVR over 3 mm; PE sinus tachycardia (S1Q3T3 10-20%)."],
        ["Emergency treatment", "Hyperkalaemic ECG: **calcium gluconate 10% 30 mL IV** then insulin 10 U + glucose 25 g, salbutamol 10-20 mg; torsades: **MgSO4 2 g IV**; unstable tachycardia: **synchronised DC**; bradycardia: **atropine 500 microgram to 3 mg**, pacing."],
        ["Tachycardia rules", "Narrow regular: Valsalva -> **adenosine 6-12-18 mg**; **broad complex = VT until proved otherwise** - amiodarone 300 mg over 10-20 min; **never verapamil**; pre-excited AF: no AV nodal blockers - DC or procainamide."],
        ["Special groups", "Children: right axis and T inversion V1-V3 normal; athletes: bradycardia, 1st-degree, Mobitz I, early repolarisation normal; women: lower V2-V3 threshold, longer QTc limit."],
        ["Red flags and referral", "STEMI/equivalent, Wellens, aVR pattern, hyperkalaemic changes, CHB/Mobitz II, broad-complex tachycardia, **QTc over 500 ms**, pre-excited AF, Brugada type 1 with syncope."],
        ["Follow-up", "Serial ECGs 15-30 min during pain and after lysis (50% ST resolution = success); QTc before/after QT drugs (stop if over 500 or rise over 60 ms); keep baseline tracings."],
        ["Exam one-liners", "A normal ECG never excludes ACS; reciprocal depression confirms STEMI; never treat an artefact; arm reversal keeps V6 normal, dextrocardia loses R progression; always compare with an old tracing."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Chest pain ECG: act-now pathway",
        steps: [
          { label: "12-lead ECG within 10 minutes", detail: "Note pain at time of recording" },
          { label: "ST elevation 2 contiguous leads?", detail: "Check V2-V3 sex/age thresholds", tone: "decision" },
          { label: "Reciprocal change, no PR depression - STEMI", detail: "Reperfusion decision now", tone: "warn" },
          { label: "No elevation - look for equivalents", detail: "Posterior, Sgarbossa, de Winter, aVR + diffuse depression", tone: "decision" },
          { label: "Inferior STEMI - record V4R; V1-V3 depression - V7-V9" },
          { label: "Non-diagnostic - repeat every 15-30 min + hs-troponin", detail: "Wellens: admit, no stress test" },
          { label: "Diagnosis made and documented with action", tone: "good" },
        ],
      },
      {
        kind: "branch",
        heading: "Tachycardia on the ECG: which arm?",
        root: "Tachycardia over 100 - unstable? DC cardioversion first",
        arms: [
          { label: "Narrow regular", steps: ["AVNRT/AVRT or flutter 2:1", "Valsalva", "Adenosine 6 then 12 then 18 mg"] },
          { label: "Narrow irregular", steps: ["AF / multifocal AT", "Rate control, CHA2DS2-VA", "Cardiovert 200 J or more if unstable"] },
          { label: "Broad regular", tone: "warn", steps: ["VT until proved otherwise", "Amiodarone 300 mg over 10-20 min", "Never verapamil"] },
          { label: "Broad irregular", tone: "warn", steps: ["Pre-excited AF or torsades", "No AV nodal blockers - DC or procainamide", "Torsades: MgSO4 2 g IV"] },
        ],
      },
    ],
  },

  "cardiovascular-pad-vte": {
    checked: "2026-10",
    updated: [
      "AHA/ACC 2026 PE guideline: massive/submassive replaced by clinical categories A-E; systemic lysis not for A-C1, reasonable in E1, considered in D.",
    ],
    master: {
      heading: "Master revision table - PAD and venous thromboembolism",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**PAD**: atherosclerotic limb artery stenosis, **ABI 0.90 or less**; **VTE**: DVT (proximal or distal) and PE - provoked, unprovoked or cancer-associated."],
        ["Classification", "**Fontaine I-IV** (IIa over 200 m, IIb under 200 m); CLTI = rest pain over 2 weeks/ulcer/gangrene; acute limb ischaemia Rutherford I-III; **PE: ESC high/intermediate-high/low/low risk; AHA/ACC 2026 categories A-E**."],
        ["Aetiology and risk factors", "PAD: **tobacco (all forms), diabetes**, HT, lipids, CKD, Buerger in young smokers; VTE: **Virchow triad** - surgery, immobility, cancer, pregnancy, oestrogen, thrombophilia, APS."],
        ["Pathophysiology", "PAD: fixed stenosis -> exercise supply-demand mismatch -> **claudication one level below block**; VTE: calf valve-pocket clot -> proximal extension -> embolism -> **RV pressure overload -> shock**."],
        ["Key history (OPD)", "Claudication distance and relief on standing (vs neurogenic - sitting); rest pain relieved by dependency; ulcers; ED/buttock pain; swollen leg - surgery, travel, OCP, pregnancy, cancer clues, previous VTE."],
        ["Key examination", "Trophic changes, all pulses, bruits, **Buerger angle**, capillary refill, monofilament; **measure ABI**; 6 Ps in acute ischaemia; DVT - calf 3 cm larger, pitting, tenderness; PE - RR, SpO2, HR, BP."],
        ["Minimal investigations", "ABI (over 1.40 - **toe-brachial index under 0.70**), lipids, HbA1c, duplex only if revascularising; **Wells DVT 2 or more** - ultrasound, under 2 - D-dimer (age x 10 over 50); PE: Wells over 4 - CTPA; V/Q in pregnancy/CKD."],
        ["Treatment - PAD first line", "**Stop tobacco**, **structured walking 30-60 min 3x/week for 12 weeks**, **high-intensity statin LDL under 55**, **clopidogrel 75 mg** (or aspirin), BP 120-129, foot care; cilostazol 100 mg BD if needed (never in HF)."],
        ["PAD escalation", "Rivaroxaban 2.5 mg BD + aspirin (COMPASS/VOYAGER) in high ischaemic, low bleeding risk; DAPT only 1-6 months after endovascular therapy; **revascularise if lifestyle-limiting at 3 months or CLTI**."],
        ["Treatment - VTE first line", "**Apixaban 10 mg BD x 7 days then 5 mg BD** or **rivaroxaban 15 mg BD x 21 days then 20 mg OD**; dabigatran/edoxaban after 5 days LMWH; enoxaparin 1 mg/kg BD; warfarin INR 2-3 with 5-day overlap."],
        ["Duration", "**3 months provoked**; unprovoked - 3 months then consider indefinite; **indefinite for recurrence, APS, active cancer**; extended apixaban 2.5 BD / rivaroxaban 10 mg OD."],
        ["Emergencies", "Acute limb ischaemia: **UFH 5000 U IV**, limb dependent, vascular surgeon within the hour (6-h window); high-risk PE (category E): **alteplase 100 mg over 2 h**, noradrenaline, fluids under 500 mL."],
        ["Special groups", "Pregnancy: **LMWH** to 6 weeks postpartum (min 3 months); cancer: apixaban/rivaroxaban/edoxaban or LMWH 6 months+; **APS: warfarin, not DOAC**; diabetic foot: toe pressure; Buerger: only tobacco cessation works."],
        ["Complications", "PAD: CLTI, amputation, MI/stroke (main cause of death); VTE: PE, recurrence, **post-thrombotic syndrome 20-50%**, **CTEPH 2-4%**, bleeding, HIT."],
        ["Red flags and referral", "6 Ps; rest pain/gangrene; **phlegmasia cerulea dolens**; PE with SBP under 90 or syncope; ABI over 1.40 with ulcer; unprovoked VTE with cancer clues."],
        ["Follow-up", "PAD 3 months then 6-12 monthly (walking distance, foot, ABI, LDL, tobacco); VTE review at 3 months to stop/extend, yearly bleeding/renal check; dyspnoea 3-6 months after PE - echo for CTEPH."],
        ["Prevention", "Medical inpatients Padua 4 or more - **enoxaparin 40 mg OD**; post hip/knee replacement LMWH 28-35 days; early mobilisation; travel advice; stop oestrogen after VTE."],
        ["Latest guideline change", "**AHA/ACC 2026 PE**: categories A-E (A incidental, B low score - early discharge, C raised score/RV strain, D normotensive shock, E hypotension); lysis/catheter therapy for E, consider D."],
        ["Exam one-liners", "Claudicants die of MI; ABI over 1.40 is abnormal; D-dimer only rules out; apixaban/rivaroxaban need no heparin lead-in; stockings do not prevent PTS; bed rest not needed in DVT."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Suspected PE: score, test, categorise",
        steps: [
          { label: "Breathless, pleuritic pain, tachycardia, risk factor" },
          { label: "Shock or SBP under 90?", tone: "decision" },
          { label: "Yes - bedside echo, UFH, lysis (category E)", detail: "Alteplase 100 mg over 2 h", tone: "warn" },
          { label: "Stable - Wells PE score", detail: "PERC if very low risk", tone: "decision" },
          { label: "Over 4 - CTPA; 4 or less - D-dimer first", detail: "Age-adjusted cut-off over 50; V/Q in pregnancy" },
          { label: "Confirmed - sPESI/Hestia, troponin, RV", detail: "AHA/ACC category B vs C-D" },
          { label: "Low risk (sPESI 0) - home DOAC", detail: "Apixaban 10 mg BD 7 days then 5 mg BD", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "PAD: from claudication to limb salvage",
        steps: [
          { label: "All: stop tobacco, statin, antiplatelet", detail: "Atorvastatin 40-80 mg LDL under 55; clopidogrel 75 mg" },
          { label: "Structured walking 12 weeks", detail: "30-60 min, 3x/week, walk to moderate pain" },
          { label: "Add cilostazol 100 mg BD", detail: "Before meals; stop at 3 months if no gain; never in HF", tone: "warn" },
          { label: "High-risk: rivaroxaban 2.5 mg BD + aspirin", detail: "Low bleeding risk only" },
          { label: "Lifestyle-limiting at 3 months or CLTI - revascularise", detail: "Duplex then CTA/MRA; endovascular or bypass", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Leg pain on walking: three look-alikes",
        columns: ["Feature", "Arterial claudication", "Neurogenic claudication", "Venous claudication"],
        rows: [
          ["Onset", "Fixed walking distance", "On standing or walking, variable", "Bursting pain with walking"],
          ["Relief", "Standing still within minutes", "Sitting or bending forward", "Leg elevation"],
          ["Pulses", "Reduced, ABI 0.90 or less", "Normal", "Normal; swollen leg"],
          ["Uphill/cycling", "Worse uphill", "Easier uphill, cycling tolerated", "Variable"],
        ],
      },
    ],
  },
};

export default revision;
