import type { RevisionSet } from "./index";

const revision: RevisionSet = {
  "emergency-cardiac-arrest": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - Cardiac arrest (BLS and ACLS)",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Sudden loss of effective cardiac output; bedside diagnosis by **unresponsive + absent or agonal breathing** - pulse check unreliable, max 10 s. Agonal gasps (up to 40%) = arrest."],
        ["Relevant classification", "By presenting rhythm: **shockable (VF, pulseless VT)** vs **non-shockable (asystole, PEA)** - decides shock first or adrenaline first. Peri-arrest states: brady under 40 with shock, broad-complex tachy with hypotension, hyperkalaemic ECG."],
        ["Aetiology & risk factors", "About **80% coronary artery disease**; cardiomyopathy, channelopathy (family SCD under 40); clinic causes: **hypoxia, haemorrhage, dialysis hyperkalaemia, poisoning, MI**; **4 Hs and 4 Ts**."],
        ["Pathophysiology", "No flow -> brain O2 gone in 10-20 s -> neuronal injury after **4-6 min**; compressions -> coronary perfusion pressure over 15-20 mmHg -> ROSC; every pause -> CPP falls to zero; survival falls **7-10% per minute** of VF without shock."],
        ["Key history (bystander)", "Witnessed or not, time of collapse, bystander CPR; chest pain, palpitations, exertional syncope; dialysis, insulin/sulfonylurea, recent surgery or cancer (PE), poison, pregnancy, DNACPR."],
        ["Key examination", "Rhythm every **2 min** (pause under 10 s); **ETCO2 under 10 mmHg** = poor CPR, sudden rise to **35-40** = ROSC; tension (deviated trachea, absent breath sounds), tamponade (raised JVP), toxidrome, gravid uterus; glucose and temperature."],
        ["Minimal investigations", "AED/monitor rhythm only to start; **capillary glucose**; blood gas with K+; POCUS during rhythm checks; **12-lead ECG within 10 min of ROSC**; post-ROSC troponin, electrolytes, CXR, CT head if cause unclear."],
        ["Treatment - first line (BLS)", "**30:2**, depth **5-6 cm**, rate **100-120/min**, full recoil, compression fraction over 80%; AED as soon as available - shock then **resume CPR at once**; swap compressor every 2 min; advanced airway -> continuous compressions + **1 breath every 6 s**."],
        ["Drugs (ALS)", "**Adrenaline 1 mg IV/IO (1:10,000) every 3-5 min** - at once in asystole/PEA, **after 3rd shock** in VF/pVT; **amiodarone 300 mg after 3rd shock, 150 mg after 5th** (or lidocaine 1-1.5 mg/kg); shock **150-200 J biphasic**; no atropine in arrest."],
        ["Escalation / specific causes", "Hyperkalaemia: **calcium gluconate 10% 30 mL** + insulin 10 U with 25 g glucose + bicarbonate 50 mmol; torsades: **MgSO4 2 g**; PE: alteplase 50 mg then CPR **60-90 min**; refractory VF: vector change (antero-posterior pads)."],
        ["Special groups", "**Child**: 5 rescue breaths, **15:2**, 4 J/kg, adrenaline **10 microgram/kg**, amiodarone 5 mg/kg; infant two-thumb encircling. **Pregnancy over 20 wk**: manual left uterine displacement, **hysterotomy within 5 min**. Hypothermia: not dead until warm."],
        ["Post-ROSC care", "SpO2 **94-98%**, PaCO2 **35-45**, **MAP 65 or more / SBP over 100**, glucose under 180 mg/dL, **temperature 37.7 C or below for 72 h**, prognosticate **at 72 h or later** with multimodal tests; STEMI -> primary PCI."],
        ["Red flags & referral", "Every ROSC transferred by ALS ambulance with pre-alert to cath lab + ICU; ETCO2 under 10 -> change compressor; stop after **20 min ALS** with asystole, no reversible cause, ETCO2 under 10 - team decision."],
        ["Follow-up & monitoring", "ICD if VF without reversible trigger; cardiac rehab; screen anxiety, depression, cognition; **first-degree relatives** of young SCD screened (ECG, echo, genetics); hot debrief and timed documentation."],
        ["Prevention / clinic readiness", "AED checked daily, adrenaline and amiodarone in date, backboard, BVM, full O2; **mock drill every quarter**; teach compression-only CPR to families; call **108**."],
        ["Latest guideline change", "ERC/AHA 2025: infants **two-thumb encircling (or heel of one hand)** - two-finger dropped; fever prevention **37.7 C or below for 72 h**; adrenaline timing unchanged."],
        ["Exam one-liners", "Shock first in VF, drug first in asystole; arrest adrenaline 1 mg IV 1:10,000, anaphylaxis 0.5 mg IM 1:1000; atropine has no place in arrest; bicarbonate only for hyperkalaemia or TCA."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "ALS algorithm in one line",
        caption: "Condensed exam version of the adult ALS loop. [ERC 2025, AHA 2025]",
        steps: [
          { label: "Unresponsive, not breathing normally", detail: "Call 108 + AED; start CPR 30:2 within 10 s", tone: "warn" },
          { label: "Attach pads, assess rhythm", detail: "Pause under 10 s; charge during compressions", tone: "decision" },
          { label: "Shockable: VF / pVT", detail: "1 shock 150-200 J biphasic, CPR 2 min; after 3rd shock adrenaline 1 mg + amiodarone 300 mg; 150 mg after 5th" },
          { label: "Non-shockable: asystole / PEA", detail: "CPR 2 min; adrenaline 1 mg IV/IO as soon as access, then every 3-5 min" },
          { label: "Throughout: treat 4 Hs and 4 Ts", detail: "Hypoxia, hypovolaemia, K+/metabolic, hypothermia; thrombosis, tension, tamponade, toxins", tone: "decision" },
          { label: "ROSC: ABCDE post-arrest bundle", detail: "SpO2 94-98%, MAP 65+, ECG in 10 min, temp 37.7 C or below for 72 h", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Shockable against non-shockable arrest",
        caption: "What the rhythm changes. [ERC 2025]",
        columns: ["Item", "VF / pulseless VT", "Asystole / PEA"],
        rows: [
          ["First action", "Shock 150-200 J biphasic (child 4 J/kg)", "CPR + adrenaline as soon as IV/IO"],
          ["Adrenaline", "1 mg after 3rd shock, then every 3-5 min", "1 mg immediately, then every 3-5 min"],
          ["Antiarrhythmic", "Amiodarone 300 mg (3rd shock), 150 mg (5th)", "None"],
          ["Likely cause", "Ischaemic or scarred myocardium", "Hypoxia, hypovolaemia, tamponade, tension, PE, K+"],
          ["Atropine", "No", "No"],
        ],
      },
      {
        kind: "ladder",
        heading: "Hyperkalaemic arrest ladder",
        caption: "The dialysis patient who arrests in clinic. [ERC 2025]",
        steps: [
          { label: "Calcium - stabilise membrane", detail: "Calcium gluconate 10% 30 mL IV (or chloride 10% 10 mL)" },
          { label: "Shift K+ into cells", detail: "Soluble insulin 10 U + glucose 25 g IV; monitor glucose hourly" },
          { label: "Sodium bicarbonate", detail: "8.4% 50 mL (50 mmol) IV, separate line from calcium" },
          { label: "Remove K+", detail: "Dialysis; continue CPR meanwhile", tone: "good" },
        ],
      },
    ],
  },

  "emergency-anaphylaxis": {
    checked: "2026-10",
    updated: ["GINA 2026: where features of both anaphylaxis and asthma are present, adrenaline is given first, then bronchodilators"],
    master: {
      heading: "Master revision table - Anaphylaxis",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Serious, **rapid-onset systemic hypersensitivity** reaction that can kill through **airway, breathing or circulation** failure; skin signs absent in **up to 20%**."],
        ["Relevant classification", "**WAO 2020 criteria**: (1) acute skin/mucosal signs + respiratory, circulatory or severe GI features; (2) hypotension, bronchospasm or laryngeal involvement after likely allergen **even without skin signs**. Refractory = no response to **2 IM doses**. Biphasic in about 5%, usually within 12 h."],
        ["Aetiology & risk factors", "India: **injectable antibiotics, diclofenac, iron sucrose, ASV, contrast, vaccines, stings, foods**. Severity: uncontrolled asthma, **beta-blockers, ACE inhibitors**, co-factors (exercise, alcohol, NSAIDs)."],
        ["Pathophysiology", "IgE on mast cells -> re-exposure cross-links -> **histamine, tryptase, leukotrienes, PAF** -> vasodilatation + leak (up to 35% volume in 10 min) + bronchospasm + mucosal oedema -> shock/arrest; empty-ventricle arrest on standing."],
        ["Key history (OPD)", "What was given/eaten/stung and **when** (injection 5-30 min); previous reactions; beta-blocker/ACE inhibitor; asthma; pregnancy; isolated angioedema on ACE inhibitor = bradykinin (poor adrenaline response)."],
        ["Key examination", "ABCDE: stridor, hoarse voice, tongue swelling; wheeze, SpO2; **SBP under 90 or over 30% fall**, tachycardia (bradycardia = pre-arrest); urticaria; repeat **every 5 min**."],
        ["Minimal investigations", "None before adrenaline. **Mast cell tryptase**: ASAP, **1-2 h (max 4 h)**, baseline at 24 h; rise over 1.2 x baseline + 2 supports; normal does not exclude. Allergy tests at **4-6 weeks**."],
        ["Treatment - first line", "**Adrenaline 1:1000 IM anterolateral thigh 0.01 mg/kg, max 0.5 mg**: adult/over 12 y **0.5 mg**, 6-12 y **0.3 mg**, 6 m-6 y **0.15 mg**; **repeat every 5 min**; lie flat, legs up; O2 15 L/min; crystalloid 500-1000 mL (child 10 mL/kg)."],
        ["Escalation / second line", "Refractory: **IV adrenaline infusion** 1 mg in 100 mL at 0.5-1 mL/kg/h; beta-blocked: **glucagon 1-2 mg IV**; bronchospasm: salbutamol 5 mg neb; stridor: neb adrenaline 5 mL 1:1000; antihistamine/steroid only after stabilisation."],
        ["Devices / how to use", "**Auto-injector**: blue cap off, orange tip to outer thigh, push till click, **hold 3 s**, call 108, 2nd device at 5 min. Kit: 0.5 mL of 1 mg/mL in 1 mL syringe IM. Intranasal adrenaline 2 mg (1 mg for 15-30 kg) where approved."],
        ["Special groups", "**Pregnancy**: same IM dose, left lateral. **Child**: age-band dose, 0.15 mg device 7.5-25 kg. **Elderly/cardiac**: no absolute contraindication. **Asthma + anaphylaxis**: adrenaline before bronchodilator."],
        ["Complications", "Airway obstruction, refractory shock, **Kounis syndrome**, biphasic reaction, arrest (PEA from empty ventricle); IV bolus 1:1000 error -> VT, MI, pulmonary oedema."],
        ["Red flags & referral", "Stridor/tongue swelling, SBP under 90, no response after 2 doses, bradycardia, beta-blocked non-responder, anaphylaxis during iron/ASV/contrast."],
        ["Follow-up & monitoring", "Observe **6 h after one dose**, **12 h or admit** after 2 doses/severe/asthma; discharge with **2 auto-injectors or kit**, written plan, hands-on training, **allergy referral**, labelled allergy; report to PvPI/AEFI."],
        ["Prevention", "Ask allergy before every injection; adrenaline drawn up before ASV/iron/antibiotics; **30-min observation** after vaccines and injections; venom immunotherapy after sting anaphylaxis."],
        ["Latest guideline change", "GINA 2026: mixed asthma-anaphylaxis picture -> **adrenaline first, then bronchodilators**; RCUK 2021 anaphylaxis guideline remains current (RCUK/ERC 2025 cite it unchanged)."],
        ["Exam one-liners", "No rash does not exclude anaphylaxis; never stand the patient up; steroids and antihistamines are not first-line and do not prevent biphasic reactions; beta-blocker + no response = glucagon."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Anaphylaxis: the first 10 minutes",
        caption: "Condensed exam version. [RCUK 2021, ERC 2025]",
        steps: [
          { label: "Sudden A, B or C problem after a trigger", detail: "Usually skin signs - but absent in up to 20%", tone: "warn" },
          { label: "Call for help, remove trigger, lie flat", detail: "Legs raised; sit up only if breathing is the problem and BP normal" },
          { label: "IM adrenaline 1:1000 into thigh", detail: "0.01 mg/kg, max 0.5 mg; 0.3 mg 6-12 y; 0.15 mg 6 m-6 y" },
          { label: "Improved after 5 min?", detail: "Reassess ABCDE every 5 min", tone: "decision" },
          { label: "No: repeat IM dose + fluids + O2", detail: "Crystalloid 500-1000 mL (child 10 mL/kg)", tone: "warn" },
          { label: "Still no after 2 doses: refractory", detail: "IV adrenaline infusion 0.5-1 mL/kg/h of 10 microgram/mL; glucagon if beta-blocked" },
          { label: "Yes: observe 6-12 h, discharge kit", detail: "2 auto-injectors, plan, training, allergy referral", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Drug ladder in anaphylaxis",
        caption: "Order of use - everything after adrenaline is an adjunct. [RCUK 2021]",
        steps: [
          { label: "IM adrenaline (repeat every 5 min)", detail: "Adult 0.5 mg of 1:1000 in anterolateral thigh", tone: "good" },
          { label: "Oxygen and IV fluid", detail: "15 L/min then SpO2 94-98%; 500-1000 mL crystalloid boluses" },
          { label: "IV adrenaline infusion (monitored)", detail: "1 mg in 100 mL saline at 0.5-1 mL/kg/h; never 1:1000 IV bolus", tone: "warn" },
          { label: "Glucagon if beta-blocked", detail: "1-2 mg IV over 5 min, then 5-15 microgram/min" },
          { label: "Noradrenaline or vasopressin (ICU)", detail: "For hypotension refractory to adrenaline and fluids" },
          { label: "After stabilisation only", detail: "Cetirizine 10 mg / chlorphenamine 10 mg; hydrocortisone 200 mg if refractory or asthma" },
        ],
      },
      {
        kind: "compare",
        heading: "Anaphylaxis against its look-alikes",
        caption: "Quick bedside separation. [RCUK 2021]",
        columns: ["Feature", "Anaphylaxis", "Vasovagal", "Acute asthma", "Bradykinin angioedema"],
        rows: [
          ["Pulse", "Tachycardia", "Bradycardia", "Tachycardia", "Normal"],
          ["Skin", "Urticaria, flushing (absent in 20%)", "Pale, clammy, no rash", "Normal", "Angioedema without urticaria"],
          ["BP", "Low or falling", "Low, recovers lying flat", "Normal", "Normal"],
          ["Clue", "Trigger minutes before", "Fear, needle, standing", "Known asthma, no skin/BP change", "ACE inhibitor or family history"],
          ["Treatment", "IM adrenaline", "Lie flat, legs up", "Salbutamol, steroid", "Stop ACEi; poor adrenaline response"],
        ],
      },
    ],
  },

  "emergency-shock": {
    checked: "2026-10",
    updated: [
      "SSC 2026: NEWS2, MEWS or SIRS preferred over qSOFA as a single sepsis screening tool",
      "SSC 2026: at least 30 mL/kg crystalloid in first 3 h; balanced crystalloids suggested; crystalloid alone suggested over adding albumin",
      "SSC 2026: antibiotics immediately (ideally within 1 h) for shock or probable sepsis; within 3 h after rapid assessment for possible sepsis without shock",
      "SSC 2026: initial MAP 65 mmHg, 60-65 mmHg suggested for adults aged 65 or over; vasopressors started peripherally rather than delayed",
      "SSC 2026: capillary refill time suggested as an adjunct to guide resuscitation; fluids not continued until lactate normalises; fluid removal after resuscitation",
      "SSC 2026: IV corticosteroids suggested in septic shock (hydrocortisone 200 mg/day usual); fludrocortisone optional",
      "SSC Children 2026: 10-20 mL/kg balanced crystalloid boluses, up to 40-60 mL/kg in first hour with ICU, up to 40 mL/kg only if hypotensive without ICU",
    ],
    master: {
      heading: "Master revision table - Shock and the first hour",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Acute circulatory failure with **inadequate tissue O2 delivery** -> cellular dysoxia; a perfusion problem, not a BP number. Cut-offs: **MAP under 65**, SBP under 90, **shock index over 0.9-1.0**, **lactate over 2 mmol/L**, urine under 0.5 mL/kg/h."],
        ["Relevant classification", "**Hypovolaemic, distributive** (septic, anaphylactic, neurogenic, adrenal), **cardiogenic, obstructive** (tension, tamponade, PE). **Septic shock (Sepsis-3)**: vasopressor for MAP 65 + lactate over 2 despite fluids. Stages: compensated, decompensated, irreversible."],
        ["Aetiology & risk factors", "Haemorrhage (trauma, GI, ectopic, PPH), diarrhoea, DKA, burns; sepsis (pneumonia, UTI, abdomen, malaria, **dengue day 4-6**); MI, peripartum cardiomyopathy; tension, tamponade, PE; steroid withdrawal; age over 65, CKD, CLD, HIV."],
        ["Pathophysiology", "Low DO2 -> baroreflex sympathetic surge (tachycardia, cold skin, narrow pulse pressure) -> RAAS/ADH oliguria -> anaerobic glycolysis -> **lactate** -> Na-K pump failure -> organ failure; sepsis: NO-driven vasodilatation + capillary leak."],
        ["Key history (OPD)", "Bleeding (haematemesis, melaena, **missed period**), fluid loss, fever and day of illness, chest pain, allergen exposure, **long-term steroids**, poisons/snakebite, trauma, malignancy/immobility."],
        ["Key examination", "Three windows: **skin (CRT over 3 s, mottling), brain (confusion), kidney (oliguria)**. **JVP + lungs**: flat + clear = hypovolaemic/distributive; raised + crackles = cardiogenic; raised + clear = obstructive or RV infarct. Warm + bradycardia = neurogenic. Passive leg raise for fluid responsiveness."],
        ["Minimal investigations", "At cannulation: group and cross-match, Hb, glucose, creatinine, electrolytes, **lactate (repeat at 2-4 h)**, **2 sets blood cultures** before antibiotics; **urine pregnancy test**; ECG in 10 min; gas with base deficit; POCUS/RUSH, eFAST; dengue NS1, malaria RDT."],
        ["Screening for sepsis", "**NEWS2, MEWS or SIRS rather than qSOFA** as a single screening tool; qSOFA too insensitive to rule out sepsis."],
        ["Treatment - first line", "Lie flat, O2 to 94-98%, **2 large-bore cannulae** (IO if 2 fails in 90 s), stop bleeding (pressure, tourniquet, **pelvic binder**), fluid in **500 mL boluses with reassessment** and a stop rule (JVP up, crackles, SpO2 falls), catheter."],
        ["Septic shock bundle", "**Antibiotics immediately, ideally within 1 h** (ceftriaxone 2 g; pip-taz 4.5 g or meropenem 1 g if hospital-acquired); **at least 30 mL/kg balanced crystalloid in 3 h**, crystalloid alone (no routine albumin); source control in 6-12 h; possible sepsis without shock -> antibiotics within 3 h if concern persists."],
        ["Escalation / vasopressors", "**Noradrenaline 0.05-0.5 microgram/kg/min**, start **peripherally**, target **MAP 65 (60-65 if 65 or over)**; add **vasopressin 0.03 U/min** at NE 0.25-0.5; adrenaline next; **dobutamine 2.5-20** for low output; **hydrocortisone 50 mg 6-hourly** suggested in septic shock; dopamine not first-line."],
        ["Type-specific treatment", "Haemorrhage: about 1 L crystalloid then **blood 1:1:1**, **TXA 1 g within 3 h**, permissive SBP 80-90 (not head injury). Anaphylaxis: **adrenaline 0.5 mg IM**. Cardiogenic: PCI, NE + dobutamine, 250 mL only if lungs clear. Obstructive: decompress, pericardiocentesis, alteplase 100 mg/2 h for PE. Adrenal: **hydrocortisone 100 mg IV**."],
        ["Special groups", "**Child**: 10-20 mL/kg balanced boluses, up to **40-60 mL/kg in 1 h with ICU**; without ICU only if hypotensive (max 40 mL/kg) - FEAST. **Dengue**: 10-20 mL/kg/h tapered by haematocrit. **Severe anaemia**: slow packed cells + furosemide. **Elderly**: MAP 60-65."],
        ["Complications", "AKI, ARDS, DIC, lethal triad (hypothermia, acidosis, coagulopathy + low Ca2+), fluid overload, mesenteric/digital ischaemia from vasopressors, multi-organ failure, post-sepsis syndrome."],
        ["Red flags & referral", "CRT over 3 s with mottled knees in fever; dengue pulse pressure 20 or less; shock in woman of reproductive age (ectopic); raised JVP + clear lungs; **lactate 4 or more or not falling**; shock after 30 mL/kg -> NE and ICU."],
        ["Follow-up & monitoring", "Every 15 min in first hour: HR, BP, MAP, **CRT**, sensorium, urine 0.5 mL/kg/h; repeat lactate (do not chase normal lactate with fluid); **de-resuscitate once shock resolves**; post-sepsis review, vaccines; steroid sick-day rules."],
        ["Latest guideline change", "**SSC 2026**: NEWS2/SIRS over qSOFA; at least 30 mL/kg; crystalloid alone over albumin; MAP 60-65 if 65 or over; peripheral vasopressor start; CRT-guided resuscitation; steroids suggested; fluid removal after resuscitation; **SSC Children 2026** fluid caps."],
        ["Exam one-liners", "Hypotension is late; shock index over 0.9 predicts blood loss; neurogenic is the only warm shock with bradycardia; renal-dose dopamine does nothing; after 1 L in haemorrhage the next fluid is blood."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Septic shock: first hour (SSC 2026)",
        caption: "Condensed exam version of the updated bundle. [SSC 2026]",
        steps: [
          { label: "Screen: NEWS2, MEWS or SIRS (not qSOFA alone)", detail: "Fever + CRT over 3 s, confusion, oliguria, lactate over 2", tone: "warn" },
          { label: "Shock or probable sepsis?", detail: "Possible sepsis without shock: rapid assessment, antibiotics within 3 h if concern persists", tone: "decision" },
          { label: "Cultures, then antibiotics within 1 h", detail: "Ceftriaxone 2 g IV; pip-taz 4.5 g or meropenem 1 g if hospital-acquired" },
          { label: "At least 30 mL/kg balanced crystalloid in 3 h", detail: "500 mL boluses, reassess CRT, JVP, crackles, SpO2; no routine albumin" },
          { label: "MAP still under 65?", detail: "Target 60-65 if aged 65 or over", tone: "decision" },
          { label: "Noradrenaline, started peripherally", detail: "0.05-0.5 microgram/kg/min; vasopressin 0.03 U/min at NE 0.25-0.5" },
          { label: "Persisting vasopressor need", detail: "Hydrocortisone 50 mg IV 6-hourly (200 mg/day); source control 6-12 h" },
          { label: "Shock resolved: de-resuscitate", detail: "Stop fluid, remove excess with diuretics; ICU transfer", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Four shock types at the bedside",
        caption: "JVP plus lung fields sort the type. [Harrison 22e, SSC 2026]",
        columns: ["Type", "JVP / lungs", "Skin and pulse", "First move"],
        rows: [
          ["Hypovolaemic", "Flat / clear", "Cold, narrow pulse pressure", "Stop bleeding, 1 L then blood 1:1:1, TXA"],
          ["Septic (distributive)", "Low-normal / clear or focal", "Warm early, wide pulse pressure, CRT over 3 s", "Antibiotics 1 h, 30+ mL/kg, peripheral NE"],
          ["Anaphylactic / neurogenic", "Flat / wheeze in anaphylaxis", "Urticaria; or warm + bradycardia", "IM adrenaline; or fluid, NE, atropine"],
          ["Cardiogenic", "Raised / crackles", "Cold, mottled", "PCI, NE + dobutamine, cautious 250 mL"],
          ["Obstructive", "Raised / clear", "Pulsus paradoxus or absent breath sounds", "Decompress, pericardiocentesis, thrombolysis"],
        ],
      },
      {
        kind: "ladder",
        heading: "Vasoactive ladder in septic shock",
        caption: "Escalate, do not repeat failed fluid. [SSC 2026]",
        steps: [
          { label: "Fluid: at least 30 mL/kg balanced crystalloid", detail: "In 3 h, boluses with reassessment and stop rule" },
          { label: "Noradrenaline (peripheral start)", detail: "0.05-0.5 microgram/kg/min to MAP 65 (60-65 if 65+)" },
          { label: "Add vasopressin", detail: "0.03 units/min fixed when NE 0.25-0.5 microgram/kg/min" },
          { label: "Add adrenaline", detail: "0.05-0.5 microgram/kg/min if MAP still inadequate" },
          { label: "Hydrocortisone", detail: "50 mg IV 6-hourly; fludrocortisone optional" },
          { label: "Dobutamine for low output", detail: "2.5-20 microgram/kg/min with adequate MAP and filling", tone: "warn" },
        ],
      },
    ],
  },

  "emergency-poisoning": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - Poisoning in Indian practice",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Injury from a substance by ingestion, inhalation, injection or skin contact; adults - **deliberate pesticide self-poisoning**, children - **accidental kerosene, medicines, household chemicals**. Every case is **medico-legal**."],
        ["Relevant classification", "By **toxidrome**: cholinergic, anticholinergic, opioid, sympathomimetic, sedative-hypnotic, cardiac glycoside. OP severity clinical (secretions, fasciculations, GCS, respiration); toxic paracetamol **150 mg/kg or 7.5 g** (75 mg/kg high risk)."],
        ["Aetiology (Indian poisons)", "OP/carbamates, **aluminium phosphide (Celphos)**, yellow phosphorus (Ratol), superwarfarins, **yellow oleander**, paraquat, corrosives, kerosene, paracetamol, benzodiazepines, methanol."],
        ["Pathophysiology", "OP: AChE phosphorylation -> ACh excess -> muscarinic (wet, miosis, bradycardia) + nicotinic (fasciculation -> paralysis) -> enzyme **ages** -> oxime useless. Paracetamol: glutathione depleted -> **NAPQI** -> zone 3 necrosis. Phosphide -> phosphine -> cytochrome oxidase block -> refractory shock."],
        ["Key history", "**What** (container), **how much** (mouthful 20-30 mL), **when** (charcoal 1 h, level at 4 h, NAC 8 h), why, co-ingestants, what was already given; malnutrition, alcohol, enzyme inducers; psychiatric history once stable."],
        ["Key examination", "Pupils, axillae wet or dry, **chest crackles (atropine end-point)**, RR, pulse/ECG (block in oleander, broad QRS in TCA), smell (garlic, rotten fish, kerosene), neck flexion power, oral burns (normal lips do not exclude oesophageal burn)."],
        ["Minimal investigations", "**Capillary glucose**, **ECG**, K+ (over 5.5 in oleander = Fab/pacing), **paracetamol level at 4 h or later** (line 150 mg/L at 4 h; UK 100), ALT/INR, gas with anion/osmolar gap; INR at 24-48 h for superwarfarin; no blind tox screen."],
        ["Treatment - first line", "ABCDE + glucose; decontaminate skin (soap, water); **activated charcoal 1 g/kg (50 g) within 1 h** with protected airway; **no lavage routinely**, never for corrosives/kerosene; no emesis."],
        ["Organophosphate antidotes", "**Atropine 1.8-3 mg IV, double every 5 min** to clear chest, HR over 80, SBP over 80, dry axillae, pupils not pinpoint; infusion **10-20% of loading dose/h**; **pralidoxime 30 mg/kg then 8 mg/kg/h** after atropine; avoid succinylcholine."],
        ["Other antidotes", "**NAC 150 mg/kg/1 h, 50 mg/kg/4 h, 100 mg/kg/16 h** (or 2-bag / SNAP); naloxone 0.4 mg titrated to RR over 12; **vitamin K1 10 mg IV** + FFP/PCC for superwarfarin; oleander - MDAC, atropine, **Fab or pacing**, no calcium; methanol - fomepizole 15 mg/kg; TCA - bicarbonate 1-2 mmol/kg."],
        ["Special situations", "Corrosive: NBM, PPI, early airway, endoscopy 12-48 h (Zargar). Kerosene: observe 6 h, CXR. Phosphide: no antidote - fluids, NE, bicarbonate, MgSO4, ICU. Paraquat: avoid O2 unless very low SpO2. Child: atropine 0.02-0.05 mg/kg."],
        ["Complications", "OP **intermediate syndrome (24-96 h)** - neck flexor weakness, ventilate; OPIDN at 2-3 weeks; paracetamol liver failure (King's: pH under 7.30, or INR over 6.5 + creatinine over 3.4 + grade III-IV HE); corrosive stricture 3-6 weeks; Ratol liver failure day 3-5."],
        ["Red flags & referral", "Wet chest + pinpoint pupils; cannot lift head; staggered/unknown-time paracetamol; stridor after corrosive; refractory shock with garlic smell; heart block + K+ over 5.5; bleeding days after rodenticide; well-looking Ratol."],
        ["Follow-up & monitoring", "Hourly atropine end-points, neck flexion, single breath count; transfer with **timed drug list**; **psychosocial assessment** before discharge for every self-harm; corrosive stricture surveillance; OPIDN review."],
        ["Prevention / national programme", "Locked pesticide storage, child-resistant packaging, no decanting into drink bottles, banning highly hazardous pesticides; **NPIC AIIMS 1800-116-117**; police intimation, preserve samples."],
        ["Latest guideline change", "No change needed - Eddleston atropine regimen, NICE CKS paracetamol and AIIMS NPIC protocols remain current."],
        ["Exam one-liners", "Atropine to a dry chest, not to pupils or HR 140; oxime after atropine and useless once aged; NAC reaction means slow, not stop; corrosives - no emesis, lavage, charcoal or neutralisation."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Organophosphate poisoning: atropinise fast",
        caption: "Condensed exam version. [Eddleston 2008]",
        steps: [
          { label: "Wet chest, pinpoint pupils, sweating", detail: "Decontaminate with gloves; ABC, O2, suction", tone: "warn" },
          { label: "Atropine 1.8-3 mg IV bolus", detail: "3-5 ampoules of 0.6 mg" },
          { label: "Atropinised at 5 min?", detail: "Clear chest, HR over 80, SBP over 80, dry axillae, pupils not pinpoint", tone: "decision" },
          { label: "No: double the dose", detail: "3, 6, 12, 24 mg every 5 min - no maximum" },
          { label: "Yes: infusion 10-20% of loading dose/h", detail: "Plus pralidoxime 30 mg/kg then 8 mg/kg/h" },
          { label: "Watch neck flexion and breath count", detail: "Intermediate syndrome 24-96 h needs ventilation", tone: "good" },
        ],
      },
      {
        kind: "flow",
        heading: "Paracetamol overdose to NAC",
        caption: "Decision points by time since ingestion. [NICE CKS 2024]",
        steps: [
          { label: "Dose 150 mg/kg or more (75 if high risk)?", tone: "decision" },
          { label: "Under 8 h, single known time", detail: "Level at 4 h or later; NAC if on/above line (150 mg/L at 4 h)" },
          { label: "Over 8 h, staggered or unknown time", detail: "Start NAC at once, then level, ALT, INR", tone: "warn" },
          { label: "NAC 21-hour regimen", detail: "150 mg/kg/1 h, 50 mg/kg/4 h, 100 mg/kg/16 h; reaction - slow, chlorphenamine" },
          { label: "ALT or INR rising at end?", detail: "Continue NAC; King's criteria -> liver unit", tone: "decision" },
          { label: "Normal bloods: psychosocial assessment", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Three Indian killers without a simple antidote",
        caption: "Supportive care decides survival. [AIIMS NPIC 2022]",
        columns: ["Feature", "Aluminium phosphide", "Yellow oleander", "Yellow phosphorus (Ratol)"],
        rows: [
          ["Mechanism", "Phosphine blocks cytochrome oxidase", "Cardiac glycoside blocks Na-K ATPase", "Protoplasmic hepatotoxin"],
          ["Clue", "Refractory shock, acidosis, garlic/fish smell", "Vomiting, bradycardia, AV block, high K+", "Well at first, jaundice day 3-5"],
          ["Key treatment", "Fluids, NE, bicarbonate, MgSO4, ICU", "MDAC, atropine, Fab or pacing", "Supportive, liver unit referral"],
          ["Avoid", "Delay in transfer; unventilated room", "IV calcium", "Discharging the well patient"],
        ],
      },
    ],
  },

  "emergency-burns": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - Burns",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Tissue injury from thermal, electrical, chemical, radiation or friction energy; India - **kerosene/LPG flame burns in women**, **scalds in children**."],
        ["Relevant classification", "**Depth**: superficial (not counted), superficial partial, deep partial, full thickness, fourth degree. **Extent**: %TBSA by **rule of nines** (adult), **Lund-Browder** (child), **palm 1%**. Major: **over 15% adult, over 10% child** or inhalation injury."],
        ["Aetiology & risk factors", "Kitchen fires, kerosene stoves, scalds, electrical (high voltage), chemicals (alkali worst, HF acid); enclosed-space fire (inhalation); extremes of age, epilepsy, alcohol; **dowry violence**, non-accidental injury."],
        ["Pathophysiology", "Jackson zones: coagulation / **stasis (salvageable 24-48 h)** / hyperaemia -> mediators -> capillary leak (max **8-12 h**) -> burn shock with haemoconcentration -> hypermetabolism -> infection and sepsis (late death)."],
        ["Key history", "**Time of burn** (clock starts here), mechanism, **enclosed space**, voltage/chemical, first aid given (home remedies), AMPLE, tetanus status, safeguarding (story fits?)."],
        ["Key examination", "Airway: **facial burns, singed nasal hair, soot, hoarseness, stridor**; circumferential chest/limb burns; TBSA and depth (CRT, pin-prick); electrical entry/exit, ECG, dark urine; NAI patterns (tide-mark, glove-stocking)."],
        ["Minimal investigations", "Hb/haematocrit, electrolytes, creatinine, glucose, group and cross-match; **COHb by co-oximetry** (SpO2 falsely normal); lactate over 8 suggests cyanide; ECG, CK, urine myoglobin in electrical; **hourly urine output**."],
        ["First aid", "Stop burning; **cool running water 20 min (useful up to 3 h)**; no ice, toothpaste, ghee; **warm the patient**; cling film in strips; chemical - irrigate 20-30 min (alkali 60+ min); elevate."],
        ["Fluids", "IV Ringer lactate if over 15% adult / 10% child: **Parkland 4 mL/kg/%TBSA/24 h**, half in first 8 h **from time of burn**; ATLS/ABA start **2 adult, 3 child, 4 electrical**; titrate to urine **0.5 mL/kg/h (1 mL/kg/h child under 30 kg, 1-1.5 if myoglobin)**; children add maintenance dextrose."],
        ["Escalation / airway", "**Intubate early** for stridor, hoarseness, deep facial burns, GCS 8 or less, long transfer - largest uncut tube; succinylcholine unsafe after 48 h; **escharotomy** for circumferential burns (mid-medial/lateral lines; chest along anterior axillary lines)."],
        ["Drugs", "IV morphine 0.1 mg/kg titrated (not IM); **100% O2** for CO; **hydroxocobalamin 5 g IV** for cyanide; Td + TIG; **no prophylactic systemic antibiotics**; SSD 1% (not face, near-term pregnancy, under 2 months, G6PD); PPI if over 20%; early enteral feed."],
        ["Special groups", "**Child**: Lund-Browder, 3 mL/kg/%, maintenance dextrose, urine 1 mL/kg/h, NAI. **Elderly**: high mortality (Baux). **Pregnancy**: O2 and HBO threshold COHb over 15%. **Electrical**: 4 mL/kg/%, cardiac monitor 24 h."],
        ["Complications", "Inhalation injury, CO/cyanide, **fluid creep** (abdominal/limb compartment syndrome), myoglobinuric AKI, Curling ulcer, wound sepsis, toxic shock in children, hypertrophic scar and contracture."],
        ["Red flags & referral", "**Burn-centre criteria**: partial thickness over 10%, any full thickness, face/hands/feet/genitalia/perineum/joints, circumferential, electrical, chemical, inhalation, comorbidity, trauma, suspected abuse."],
        ["Follow-up & monitoring", "Minor burns review at **48 h**; not healed by 2-3 weeks -> graft referral; pressure garments 23 h/day for 6-12 months, silicone, splints, physiotherapy; sun protection 1 year; PTSD screening."],
        ["Prevention / medico-legal", "**NPPMBI**; safer stoves/LPG (Ujjwala); community cool-water first aid; married woman burnt **within 7 years of marriage** - police intimation and **dying declaration** verbatim."],
        ["Latest guideline change", "No change needed - ATLS 11e starting rates (2/3/4 mL/kg/%) and ABA referral criteria remain current."],
        ["Exam one-liners", "Erythema is not counted; the 8-hour clock starts at the burn; early hypotension in an isolated burn means another injury; SpO2 is normal in CO poisoning."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Major burn: first hour",
        caption: "Condensed exam version. [ATLS 11e, EMSB 2021]",
        steps: [
          { label: "Stop the burning, cool 20 min", detail: "Running water up to 3 h; no ice; keep patient warm" },
          { label: "Airway threatened?", detail: "Soot, singed hair, hoarse voice, stridor, deep facial burn", tone: "decision" },
          { label: "Yes: intubate early, 100% O2", detail: "Largest uncut tube; consider CO and cyanide", tone: "warn" },
          { label: "Estimate TBSA and depth", detail: "Rule of nines / Lund-Browder / palm 1%; ignore erythema" },
          { label: "Over 15% adult or 10% child: IV RL", detail: "Start 2 mL/kg/% adult (Parkland 4); half in 8 h from burn" },
          { label: "Catheter, titrate to urine output", detail: "0.5 mL/kg/h adult, 1 mL/kg/h child; adjust rate by one-third" },
          { label: "Cling film, analgesia, transfer", detail: "Written TBSA, fluid chart and time of burn", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Parkland against ATLS 11e starting rate",
        caption: "Worked for a 60 kg adult with a 40% burn. [ATLS 11e]",
        columns: ["Item", "Parkland (classical)", "ATLS 11e / ABA"],
        rows: [
          ["Formula", "4 mL x kg x %TBSA", "2 adult, 3 child, 4 electrical mL/kg/%"],
          ["24-hour volume", "9600 mL", "4800 mL"],
          ["First 8 h", "4800 mL (600 mL/h)", "2400 mL (300 mL/h)"],
          ["Next 16 h", "4800 mL (300 mL/h)", "2400 mL (150 mL/h)"],
          ["Steering", "Urine output", "Urine output; avoid fluid creep"],
        ],
      },
      {
        kind: "branch",
        heading: "Burn depth at the bedside",
        caption: "Sensation and blanching beat colour. [ISBI 2018]",
        root: "Burn depth",
        arms: [
          { label: "Heals by itself", tone: "good", steps: ["Superficial: red, dry, painful - 5-7 days", "Superficial partial: blisters, moist, brisk blanching - 10-14 days"] },
          { label: "Needs surgery", tone: "warn", steps: ["Deep partial: blotchy, sluggish blanching - over 3 weeks, graft", "Full thickness: white/leathery, insensate - excise and graft", "Fourth degree: fat, muscle, bone"] },
        ],
      },
    ],
  },

  "emergency-trauma-primary-survey": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - Trauma primary survey and safe transfer",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Rapid structured search that **treats life threats in the order they kill** - **xABCDE** - then adjuncts, secondary survey (head-to-toe + AMPLE), definitive care or transfer."],
        ["Relevant classification", "**ATLS haemorrhagic shock classes**: I under 15%, II 15-30% (narrow pulse pressure), III 31-40% (BP falls, transfuse), IV over 40% (MTP). Trimodal death - the primary survey targets the **early (golden hour) peak**."],
        ["Aetiology & risk factors", "Road traffic injury (about 1.7 lakh deaths/year, two-wheelers, no helmet), falls, assault; anticoagulants, elderly on beta-blockers, pregnancy."],
        ["Pathophysiology", "Haemorrhage -> compensated tachycardia until **30% loss** -> BP falls; **lethal diamond** (hypothermia, acidosis, coagulopathy, low Ca2+); tension -> kinked cavae -> obstructive shock; brain: hypoxia or SBP under 90 **doubles mortality**."],
        ["Key history", "**AMPLE** once stable: allergies, medications (anticoagulants, beta-blockers), past illness/pregnancy, last meal, events (speed, ejection, fall height, helmet); **time of injury** for TXA."],
        ["Key examination (xABCDE)", "x: catastrophic bleed; A: talking = patent, jaw thrust + in-line stabilisation; B: RR, SpO2, trachea, breath sounds, percussion; C: 5 places blood hides, CRT, pulse pressure; D: **GCS E-V-M, pupils, glucose**; E: log-roll, warm."],
        ["Minimal investigations", "Cross-match, Hb, **gas with lactate/base deficit**, glucose, pregnancy test; **CXR + pelvic X-ray** in resus; **eFAST**; CT only when stable; Canadian C-spine/NEXUS, NICE NG232 for head CT."],
        ["Treatment - first line", "Direct pressure, **windlass tourniquet** (time written), pelvic binder at **greater trochanters**; O2 15 L/min; **2 large-bore cannulae** or IO; needle decompression **4th/5th ICS anterior to mid-axillary line** (child 2nd ICS MCL) then drain."],
        ["Fluids and drugs", "**1 L warm crystalloid** (child 20 mL/kg) -> response; transient/none -> **blood 1:1:1** + calcium; **TXA 1 g over 10 min within 3 h then 1 g over 8 h**; **permissive SBP 80-90** except head injury (SBP 110+); IV morphine/ketamine; cefazolin 2 g within 1 h for open fractures; Td/TIG."],
        ["Procedures", "Chest drain in **safe triangle** (5th ICS, anterior to mid-axillary line); massive haemothorax **1500 mL or 200 mL/h for 2-4 h** -> thoracotomy; three-sided dressing for open pneumothorax; traction splint for femur; pericardiocentesis as bridge."],
        ["Special groups", "**Pregnancy over 20 weeks**: manual left uterine displacement, resuscitate mother first, fetal heart. **Child**: compensates then crashes, 20 mL/kg. **Elderly / beta-blocked**: no tachycardia. **Anticoagulated**: PCC 25-50 IU/kg + vitamin K."],
        ["Complications", "Trauma coagulopathy, hypothermia, missed injuries, compartment syndrome, abdominal compartment, ARDS, sepsis, PTSD, chronic pain."],
        ["Red flags & referral", "Absent breath sounds + raised JVP + hypotension (tension); deterioration on ventilator (**DOPE**); transient response to 1 L; blood at meatus (no catheter); fixed dilated pupil; cold oozing patient; no TXA after 3 h."],
        ["Safe transfer", "Decide early on physiology not tests; doctor-to-doctor call; never transfer untreated tension, uncontrolled bleed, unprotected airway, unbound pelvis; O2 for **twice journey time**; trained escort; handover **ATMIST**."],
        ["Prevention / national programme", "Helmets, seat belts, no drink-driving; **Good Samaritan law (MoRTH 2016)**; **Cashless Treatment of Road Accident Victims Scheme 2025** (up to Rs 1.5 lakh for 7 days); medico-legal register."],
        ["Latest guideline change", "No change needed - ATLS 11e (xABCDE, 4th/5th ICS needle site) and CRASH-2/3 TXA timing remain current."],
        ["Exam one-liners", "Treat as you find; talking patient = A, B and brain perfusion intact; after 1 L the next fluid is blood; binder at trochanters; tension pneumothorax is a clinical diagnosis."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "xABCDE: treat as you find",
        caption: "Condensed exam version; reassess from A after every intervention. [ATLS 11e]",
        steps: [
          { label: "x - Exsanguinating haemorrhage", detail: "Pressure, windlass tourniquet (time it), pack junctional wounds", tone: "warn" },
          { label: "A - Airway + cervical spine", detail: "Jaw thrust, suction, in-line stabilisation; intubate if GCS 8 or less" },
          { label: "B - Breathing", detail: "O2 15 L/min; tension -> needle 4th/5th ICS anterior to MAL, then drain" },
          { label: "C - Circulation", detail: "2 large-bore lines, binder, 1 L warm crystalloid, TXA within 3 h" },
          { label: "Response to 1 L?", detail: "Rapid / transient / none", tone: "decision" },
          { label: "Transient or none: blood 1:1:1, surgery", detail: "Permissive SBP 80-90 except head injury", tone: "warn" },
          { label: "D - GCS, pupils, glucose; E - expose, warm", detail: "Log-roll; then AMPLE and secondary survey" },
          { label: "Early transfer with ATMIST handover", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Six lethal chest injuries at B and C",
        caption: "Find and treat in the primary survey. [ATLS 11e]",
        columns: ["Injury", "Clue", "Immediate action"],
        rows: [
          ["Airway obstruction", "Stridor, gurgling, no voice", "Jaw thrust, suction, adjunct, surgical airway"],
          ["Tension pneumothorax", "Absent breath sounds, raised JVP, shock", "Needle 4th/5th ICS anterior to MAL, then drain"],
          ["Open pneumothorax", "Sucking wound", "Three-sided dressing, drain away from wound"],
          ["Massive haemothorax", "Dull, absent breath sounds, 1500 mL drained", "Drain, blood, thoracotomy"],
          ["Flail chest + contusion", "Paradoxical segment, hypoxia", "O2, analgesia, ventilate if hypoxic"],
          ["Cardiac tamponade", "Beck triad, pericardial fluid on FAST", "Pericardiocentesis as bridge, thoracotomy"],
        ],
      },
      {
        kind: "ladder",
        heading: "Haemorrhagic shock classes to blood",
        caption: "Class sets the need for blood. [ATLS 11e]",
        steps: [
          { label: "Class I: under 15%", detail: "Vitals normal - monitor" },
          { label: "Class II: 15-30%", detail: "Pulse pressure narrows, anxious - crystalloid, blood possible" },
          { label: "Class III: 31-40%", detail: "BP falls, confused, oliguria - transfuse", tone: "warn" },
          { label: "Class IV: over 40%", detail: "Negligible urine, GCS down - massive transfusion 1:1:1 + TXA", tone: "warn" },
        ],
      },
    ],
  },

  "emergency-altered-sensorium": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - Altered sensorium",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Acute disturbance of **arousal (ARAS)** or **content (cortex)** of consciousness - a symptom, never a diagnosis; levels: delirium, drowsiness, stupor, coma (GCS 8 or less)."],
        ["Relevant classification", "**GCS E4 V5 M6** recorded by component: mild 13-15, moderate 9-12, severe 3-8; **AVPU** (P/U about GCS 8); causes - **structural (focal) vs metabolic/toxic/infective (symmetric)** by **AEIOU TIPS**."],
        ["Aetiology & risk factors", "Hypoglycaemia, hypoxia, sepsis, meningitis/encephalitis, **cerebral malaria**, JE, scrub typhus, stroke/SAH, trauma, poisoning, alcohol/Wernicke, uraemia, hepatic encephalopathy, hyponatraemia, status epilepticus, heat stroke."],
        ["Pathophysiology", "Coma needs **bilateral hemisphere dysfunction or ARAS lesion**; mass -> ICP rise -> CPP = MAP - ICP falls -> uncal herniation (CN III, fixed dilated pupil) -> Cushing response; metabolic coma spares pupillary reflexes."],
        ["Key history", "Three questions: drugs/alcohol/poison available, illnesses (diabetes on SU, epilepsy, liver, kidney), last 24 h (headache, fever, fall, seizure); tempo of onset; travel/monsoon; elderly - new drugs, retention."],
        ["Key examination", "**GCS by components every 15 min**, pupils, doll's eye, lateralising signs, meningism (absent in infants/elderly/deep coma), fundi, rash/eschar, breath odour, toxidrome, bladder, **temperature**."],
        ["Minimal investigations", "**Capillary glucose in every patient**; Na, K, Ca, urea, creatinine, LFT, CBC; gas and ketones; malaria RDT/smear, dengue, blood cultures, scrub IgM; **CT head** if focal/trauma/papilloedema/anticoagulated; LP after CT - never delay antibiotics; EEG for NCSE."],
        ["Treatment - general", "Airway (recovery position, suction, intubate if GCS 8 or less), O2 94-98%, correct the **four now** (hypoglycaemia, hypoxia, hypotension, temperature), head up 30 degrees, catheter, eye and pressure care; avoid sedation until glucose/hypoxia excluded."],
        ["The bedside cocktail", "**25% dextrose 100 mL IV** (child 10% 2-5 mL/kg); **thiamine 200-500 mg IV** (Wernicke 500 mg TDS); **naloxone 0.4 mg** titrated to RR; status: **lorazepam 0.1 mg/kg (max 4 mg)** or midazolam 10 mg IM/buccal, then **levetiracetam 60 mg/kg (max 4.5 g)**."],
        ["Infection and specific causes", "Meningitis: **ceftriaxone 2 g IV 12-hourly** + **dexamethasone 10 mg 6-hourly x 4 days** before LP/transfer (+ ampicillin if over 60/pregnant); HSV: **aciclovir 10 mg/kg 8-hourly**; cerebral malaria: **IV artesunate 2.4 mg/kg at 0, 12, 24 h** (3 mg/kg under 20 kg) or rectal pre-referral."],
        ["Metabolic causes", "Hepatic: lactulose to 2-3 stools + rifaximin 550 mg BD; hyponatraemia with seizures: **3% saline 100-150 mL over 10-20 min**, max rise **8-10 mmol/L in 24 h**; hypertensive encephalopathy: labetalol, MAP down **20-25% in first hour**; eclampsia: MgSO4."],
        ["Special groups", "**Child**: 10% dextrose 2-5 mL/kg, IAP; inconsistent story - inflicted injury. **Elderly**: hypoactive delirium, drugs, retention, constipation; haloperidol 0.5-1 mg only if essential. **Pregnancy/postpartum**: eclampsia until proved otherwise."],
        ["Complications", "Aspiration, herniation, status, osmotic demyelination with fast Na correction, Wernicke-Korsakoff, recurrent SU hypoglycaemia (24-72 h), pressure sores."],
        ["Red flags & referral", "GCS 8 or less or fall of 2; unilateral fixed pupil, Cushing; fever + neck stiffness/purpura; seizure after 2 benzodiazepines; malaria-endemic fever with coma; alcohol smell + head injury (subdural)."],
        ["Follow-up & monitoring", "Transfer with trained escort, timed GCS chart, drugs given; review SU after severe hypoglycaemia, epilepsy adherence, alcohol de-addiction, deprescribing; delirium survivors - cognitive screening."],
        ["Latest guideline change", "No change needed - ADA 2026 hypoglycaemia, NICE NG240 meningitis, AES 2016/ESETT status epilepticus and WHO artesunate dosing remain current."],
        ["Exam one-liners", "Glucose first, every time; thiamine with glucose in the malnourished; naloxone to breathing, not wakefulness; antibiotics before CT and LP; alcohol is an odour, not a diagnosis."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Unconscious patient: first 5 minutes",
        caption: "Condensed exam version. [Harrison 22e, NICE NG240 2024]",
        steps: [
          { label: "Airway, recovery position, O2", detail: "Spinal precautions if trauma possible; intubate if GCS 8 or less", tone: "warn" },
          { label: "Capillary glucose", detail: "Under 70 mg/dL: 25% dextrose 100 mL IV + thiamine if malnourished", tone: "decision" },
          { label: "Pinpoint pupils, RR under 12?", detail: "Naloxone 0.4 mg IV titrated to breathing", tone: "decision" },
          { label: "Seizing 5 minutes or more?", detail: "Lorazepam 0.1 mg/kg, repeat once, then levetiracetam 60 mg/kg", tone: "decision" },
          { label: "Fever, neck stiffness or rash?", detail: "Ceftriaxone 2 g + dexamethasone; artesunate if malaria-endemic", tone: "decision" },
          { label: "GCS by components, pupils, focal signs", detail: "Focal or trauma -> CT head; work through AEIOU TIPS" },
          { label: "Transfer with escort and timed chart", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Convulsive status epilepticus ladder",
        caption: "Time-based escalation. [AES 2016, ESETT]",
        steps: [
          { label: "0-5 min: ABC, glucose", detail: "Recovery position, O2, IV access" },
          { label: "5 min: benzodiazepine", detail: "Lorazepam 0.1 mg/kg IV (max 4 mg) or midazolam 10 mg IM / 0.2-0.3 mg/kg buccal" },
          { label: "10 min: repeat benzodiazepine once", detail: "Maximum two doses" },
          { label: "20 min: second-line", detail: "Levetiracetam 60 mg/kg (max 4.5 g) or valproate 40 mg/kg or fosphenytoin 20 mg PE/kg" },
          { label: "40 min: refractory - ICU", detail: "Intubate; midazolam, propofol or thiopentone infusion", tone: "warn" },
        ],
      },
      {
        kind: "branch",
        heading: "Structural against metabolic coma",
        caption: "The pupils and symmetry sort the cause. [Adams and Victor 12e]",
        root: "Coma",
        arms: [
          { label: "Structural", tone: "warn", steps: ["Focal or asymmetric signs", "Unilateral fixed dilated pupil", "Cushing response", "CT head and neurosurgery"] },
          { label: "Metabolic / toxic / infective", tone: "neutral", steps: ["Symmetric signs", "Pupillary reflexes preserved", "Glucose, Na, gas, malaria, cultures", "Treat cause; LP for meningitis"] },
        ],
      },
    ],
  },

  "emergency-tray-and-readiness": {
    checked: "2026-10",
    updated: [
      "GINA 2026: oxygen in acute asthma only if SpO2 under 92%, titrated to no higher than 95%; oral prednisolone preferred, IV hydrocortisone if unable to swallow",
      "ESC 2026: acute heart failure now termed decompensated heart failure, with early urine sodium-guided diuretic escalation",
      "ERC 2025: airway adjunct technique tag updated (insertion unchanged)",
    ],
    master: {
      heading: "Master revision table - Emergency tray and clinic readiness",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**One sealed, checklist-controlled tray in one fixed, unlocked place, reachable in 30 s**, holding only what treats conditions that **kill within minutes**."],
        ["Relevant classification", "Readiness = **tray + people + pathway**. Triage: **Manchester (red 0, orange 10, yellow 60, green 120, blue 240 min)**; Indian EDs use 3-colour red-yellow-green."],
        ["Standards", "NABH entry-level/SHCO standards (documented drugs, equipment, trained staff, referral); **IPHS 2022** PHC/AAM drug list; **AEFI 2024** - anaphylaxis kit at every session + **30-min observation**."],
        ["Rationale", "Brain injury after **4-6 min** of arrest; VF survival falls 7-10%/min without shock; iatrogenic anaphylaxis arrests in about **5 min**; status beyond 5 min self-perpetuates; adrenaline degrades in heat and light."],
        ["Drugs - arrest and anaphylaxis", "**Adrenaline 1:1000 IM 0.5/0.3/0.15 mg** by age, repeat 5 min; **adrenaline 1 mg IV (1:10,000)** every 3-5 min in arrest; amiodarone 300/150 mg; **atropine 1 mg IV every 3-5 min to 3 mg** for bradycardia (Indian ampoule 0.6 mg/mL)."],
        ["Drugs - metabolic and neuro", "**25% dextrose 100 mL** (child 10% 2-5 mL/kg) + thiamine 100 mg; glucagon 1 mg IM; **lorazepam 0.1 mg/kg** or midazolam 10 mg IM/buccal 0.2-0.3 mg/kg; **naloxone 0.4 mg** to 10 mg."],
        ["Drugs - respiratory and cardiac", "Salbutamol 5 mg neb or 4-10 puffs by spacer every 20 min + ipratropium 500 microgram; **O2 only if SpO2 under 92%, target up to 95%**; prednisolone 40-50 mg (hydrocortisone 100-200 mg IV if cannot swallow); aspirin 300 mg + clopidogrel 300 mg; GTN; furosemide 40 mg IV."],
        ["Drugs - obstetric and others", "**MgSO4 4 g IV + 10 g IM (Pritchard)**, then 5 g IM 4-hourly; calcium gluconate 10 mL antidote; **oxytocin 10 IU IM**; **TXA 1 g IV within 3 h**; NS/RL, ORS; lipid 20% 1.5 mL/kg where blocks are done; atropine 25+ ampoules in pesticide belt."],
        ["Devices / how to use", "O2 cylinder with key, NRB mask 15 L/min (reservoir pre-filled); **BVM with reservoir (90% vs 50%)** adult 1500, child 500, neonate 240 mL; C-E grip; OPA sized incisor-angle, rotate 180 in adults; **manual/foot suction**; AED (paediatric pads under 8 y); glucometer with control."],
        ["Organisation", "Arrange **by indication, not alphabet**; separate and label **1:1000 vs 1:10,000**; laminated paediatric chart in lid; numbered seal; never in vaccine fridge; **named owner**, weekly signed check, **first-expiry-first-out**, out at 3 months to expiry."],
        ["Special trays", "**Immunisation**: adrenaline ampoules, 1 mL syringes, infant masks, dose card, 30-min observation; **delivery point**: oxytocin (cold chain), MgSO4, calcium, TXA, neonatal bag; procedure room: separated LA with/without adrenaline; home-visit bag."],
        ["Drill and roles", "**Unannounced mock drill every 3 months** (anaphylaxis after injection, collapse, fitting child, PPH); 6 fixed roles (compressions, tray/AED, drugs, phone, family, scribe); time first compression, adrenaline drawn, ambulance call; blame-free debrief."],
        ["Red flags", "Adrenaline missing/expired/discoloured; 1:1000 and 1:10,000 stored together; tray locked; empty O2 or no key; BVM without reservoir; log gaps or back-dated; no paediatric chart; tray not restocked."],
        ["Follow-up & audit", "Indicators: weekly checks completed (100%), expired/missing at **unannounced** check (zero), drill times trending down, BLS currency (every 2 years for all staff), complete AEFI kits; report AEFI and review every emergency."],
        ["Latest guideline change", "**GINA 2026**: O2 only below 92%, upper target 95%; **ESC 2026**: 'decompensated heart failure', urine sodium-guided diuresis; AHA 2025 adult bradycardia atropine **1 mg** to 3 mg."],
        ["Exam one-liners", "Adrenaline is the one indefensible omission - check it first; 1:1000 IV is a ten-fold error; the commonest empty tray is the one just used; faint = bradycardia and pallor, anaphylaxis = tachycardia and urticaria."],
      ],
    },
    flows: [
      {
        kind: "cycle",
        heading: "The tray readiness cycle",
        caption: "Ownership turns a list into a working tray. [NABH 2020]",
        steps: [
          { label: "Weekly check by named owner", detail: "Seal number, drugs present, in date, not discoloured; adrenaline first" },
          { label: "Test the devices", detail: "O2 pressure, BVM valves, suction with mains off, AED self-test, glucometer control" },
          { label: "Rotate and reseal", detail: "First-expiry-first-out; out at 3 months to expiry; new numbered tag; sign log" },
          { label: "Use in emergency", detail: "Timed record sheet, fixed roles" },
          { label: "Restock before next patient", detail: "The commonest empty tray is the one just used", tone: "warn" },
          { label: "Quarterly unannounced drill and audit", detail: "Time first compression, adrenaline drawn, ambulance call; debrief", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Adrenaline 1:1000 against 1:10,000",
        caption: "The ten-fold error that kills. [RCUK 2021, AHA 2025]",
        columns: ["Item", "1:1000 (1 mg/mL)", "1:10,000 (0.1 mg/mL)"],
        rows: [
          ["Use", "Anaphylaxis", "Cardiac arrest"],
          ["Route", "IM anterolateral thigh", "IV / IO"],
          ["Adult dose", "0.5 mg (0.5 mL)", "1 mg (10 mL) every 3-5 min"],
          ["Child dose", "0.3 mg 6-12 y; 0.15 mg 6 m-6 y", "0.01 mg/kg (0.1 mL/kg), max 1 mg"],
          ["Never", "IV bolus outside monitoring", "IM for anaphylaxis"],
        ],
      },
      {
        kind: "compare",
        heading: "Atropine: bradycardia against organophosphate",
        caption: "Same ampoule, very different dose. [AHA 2025, Eddleston 2008]",
        columns: ["Item", "Symptomatic bradycardia", "Organophosphate poisoning"],
        rows: [
          ["Adult dose", "1 mg IV every 3-5 min", "1.8-3 mg IV, doubled every 5 min"],
          ["Maximum", "3 mg", "No maximum (often 50-100 mg+)"],
          ["End-point", "Heart rate and perfusion", "Clear chest, HR over 80, SBP over 80, dry axillae"],
          ["Child", "0.02 mg/kg, max single 0.5 mg", "0.02-0.05 mg/kg doubling"],
          ["Stock", "Few ampoules", "25 or more ampoules in pesticide belt"],
        ],
      },
    ],
  },

  "emergency-ards": {
    checked: "2026-10",
    updated: ["SSC 2026: antibiotics within 1 h for probable sepsis or shock, within 3 h after rapid assessment when sepsis is only possible and the patient is stable"],
    master: {
      heading: "Master revision table - ARDS",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Acute diffuse inflammatory **permeability lung injury** -> non-cardiogenic oedema, shunt, low compliance."],
        ["Relevant classification", "**Berlin 2012 (T-I-O-O)**: within 1 week, bilateral opacities, not fully cardiac/fluid, PaO2/FiO2 on **PEEP 5 or more**: **mild 201-300, moderate 101-200, severe 100 or less**. **2023 global definition**: adds HFNO 30 L/min or more, **SpO2/FiO2 315 or less** (SpO2 97% or below), lung ultrasound."],
        ["Aetiology & risk factors", "**Direct**: pneumonia (commonest direct), aspiration, contusion, drowning, inhalation. **Indirect**: **sepsis (commonest overall, about 40%)**, trauma, TRALI, pancreatitis, burns. India: **falciparum malaria, dengue, leptospirosis, scrub typhus, OP, paraquat**."],
        ["Pathophysiology", "Insult -> macrophage cytokines -> neutrophil injury of **type I pneumocytes + endothelium** -> protein-rich exudate, hyaline membranes, surfactant loss -> **shunt (refractory hypoxaemia)** + 'baby lung' -> proliferative (7-21 d) -> fibrotic phase in a minority."],
        ["Key history", "Breathlessness over hours-days after an insult; fever, aspiration, transfusion (TRALI within 6 h), pesticide, monsoon fever; cardiac history favours cardiogenic oedema; immunosuppression."],
        ["Key examination", "RR over 30, accessory muscles, cannot complete sentences, SpO2 low on 15 L/min NRB; **normal JVP, no S3**; source hunt (eschar, conjunctival suffusion, fasciculations); drowsiness or rising PaCO2 = pre-terminal."],
        ["Minimal investigations", "ABG on known FiO2/PEEP; **SpO2/FiO2 equivalents 315 / 235 / 148**; CXR (bilateral, normal heart); lung ultrasound; echo; **BNP under 100** argues against HF; cultures before antibiotics, malaria, dengue, scrub, lepto, lactate."],
        ["Diagnostic criteria", "All four Berlin components; PaO2 mmHg / FiO2 fraction (60 on 0.6 = 100 = severe); excluded: ALI term and wedge pressure 18 cut-off."],
        ["Treatment - first line", "**Treat the cause**: antibiotics within 1 h of probable sepsis (ceftriaxone 2 g + azithromycin 500 mg; pip-taz if hospital-acquired), doxycycline 100 mg BD, artesunate; O2 target **SpO2 88-95%**; HFNO preferred over standard O2; **ROX under 4.88 at 12 h** = failure."],
        ["Ventilation", "**Tidal volume 6 mL/kg predicted body weight** (men 50 + 0.91 x (cm - 152.4)), **plateau 30 or less**, **driving pressure under 15**, higher PEEP if moderate-severe, permissive hypercapnia (pH 7.20), no staircase recruitment manoeuvres."],
        ["Escalation", "**Prone 16 h or more/day** if PaO2/FiO2 under 150 (PROSEVA 16% vs 33%); NMB (cisatracurium 48 h) if dyssynchrony; **dexamethasone 20 mg x 5 d then 10 mg x 5 d** early moderate-severe (not after day 14, not influenza); **VV-ECMO** for very severe reversible ARDS."],
        ["Supportive care", "**Conservative fluids once shock resolves** (FACTT); head up 30-45; enteral feed 24-48 h; light sedation, daily SBT; Hb threshold 7 g/dL; glucose 140-180; enoxaparin 40 mg; PPI only if indicated."],
        ["Special groups", "**Paraquat**: restrict O2 (SpO2 88-92%). **Pregnancy**: left lateral tilt, fetal heart. **COVID-19**: dexamethasone 6 mg x 10 days. **OP poisoning**: atropine to clear chest."],
        ["Complications", "VILI (volu-, baro-, atelect-, biotrauma), pneumothorax, acute cor pulmonale, VAP, ICU-acquired weakness, delirium, fibrosis, **post-intensive care syndrome**."],
        ["Red flags & referral", "SpO2 under 90% on 15 L/min, RR over 30 with normal or rising PaCO2, exhaustion, new drowsiness, shock, PaO2/FiO2 under 100, ROX under 4.88 - refer every suspected ARDS to ICU while setting up oxygen."],
        ["Follow-up & monitoring", "Lung function near normal by 6-12 months (low DLCO commonest); **PICS** - weakness, cognition, PHQ-9/GAD-7, PTSD, carer strain; stop ICU-started drugs; rehab; vaccinate; spirometry + DLCO at 3-6 months."],
        ["Latest guideline change", "**SSC 2026**: antibiotics within 1 h for probable sepsis/shock (within 3 h if only possible and stable); ESICM 2023 and ATS 2024 ventilation and steroid advice unchanged."],
        ["Exam one-liners", "6 mL/kg of predicted, never actual, weight; prone needs staff not equipment; nitric oxide and recruitment improve numbers, not survival; paraquat is the one ARDS where oxygen is restricted."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Suspected ARDS at first contact",
        caption: "Condensed exam version for the clinic. [ESICM 2023, SSC 2026]",
        steps: [
          { label: "Hypoxic, tachypnoeic after an insult", detail: "Sit up, call for help, assess exhaustion", tone: "warn" },
          { label: "O2: NRB 15 L/min or HFNO", detail: "Target SpO2 88-95%; record FiO2 and SpO2 with times" },
          { label: "Cultures, then antibiotics within 1 h", detail: "If sepsis probable or shock; add doxycycline, artesunate as indicated" },
          { label: "Cardiogenic or ARDS?", detail: "JVP, S3, BNP, ultrasound, response to furosemide 40 mg + nitrate", tone: "decision" },
          { label: "No reflex fluid bolus", detail: "If shocked: 250-500 mL boluses + early noradrenaline" },
          { label: "Phone ICU and transfer early", detail: "O2 for twice the journey, trained escort, written trend", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "ARDS escalation ladder",
        caption: "Add a rung when the one below fails. [ATS 2024, ESICM 2023]",
        steps: [
          { label: "Treat cause + HFNO / CPAP", detail: "Bridge, not destination; ROX under 4.88 at 12 h = intubate" },
          { label: "Lung-protective ventilation", detail: "6 mL/kg PBW, plateau 30 or less, driving pressure under 15" },
          { label: "Higher PEEP (P/F 200 or less)", detail: "No staircase recruitment manoeuvres" },
          { label: "Prone 16 h or more/day (P/F under 150)", detail: "PROSEVA mortality 16% vs 33%", tone: "good" },
          { label: "Neuromuscular blockade + early steroid", detail: "Cisatracurium 48 h; dexamethasone 20 mg x 5 d then 10 mg x 5 d" },
          { label: "VV-ECMO at expert centre", detail: "Very severe reversible ARDS (EOLIA)", tone: "warn" },
        ],
      },
      {
        kind: "compare",
        heading: "Berlin severity with SpO2/FiO2 equivalents",
        caption: "Grade without a gas machine. [Berlin 2012, Matthay 2024]",
        columns: ["Severity", "PaO2/FiO2 (PEEP 5+)", "SpO2/FiO2", "Mortality", "Action"],
        rows: [
          ["Mild", "201-300", "236-315", "About 27-35%", "HFNO/CPAP, close watch"],
          ["Moderate", "101-200", "149-235", "About 32-40%", "Intubate, higher PEEP, prone if under 150"],
          ["Severe", "100 or less", "148 or less", "About 45%", "Prone, paralysis, ECMO call"],
        ],
      },
    ],
  },

  "emergency-head-injury": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - Head injury",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Alteration in brain function, or other evidence of brain pathology, from an **external force**; primary injury fixed at impact, **secondary injury preventable**."],
        ["Relevant classification", "**Post-resuscitation GCS**: mild 13-15, moderate 9-12, severe 3-8; morphology - **focal** (EDH, SDH, ICH, contusion) vs **diffuse** (concussion, DAI, swelling); skull fractures linear, depressed, compound, basal."],
        ["Aetiology & risk factors", "Two-wheeler crashes without helmets (about 60%), falls, assault; **age 65 or over, anticoagulants/antiplatelets**, alcohol, bleeding disorders; NAI in infants."],
        ["Pathophysiology", "Monro-Kellie: haematoma -> CSF/venous displacement -> ICP rises steeply -> **CPP = MAP - ICP** falls (target 60-70) -> uncal herniation (ipsilateral CN III, contralateral hemiparesis) -> Cushing triad -> tonsillar herniation; lost autoregulation - SBP under 90 or PaO2 under 60 doubles mortality."],
        ["Key history", "Mechanism (fall over 1 m/5 stairs, ejection, pedestrian), LOC, **amnesia over 30 min**, **lucid interval**, vomiting more than once, seizure, headache, anticoagulants, age, what caused the fall (syncope, hypoglycaemia)."],
        ["Key examination", "**GCS E-V-M + pupils** (GCS-P), lateralising signs, scalp boggy swelling/step, **basal skull signs** (raccoon eyes, Battle, CSF leak, haemotympanum), C-spine, Cushing response; obs half-hourly till GCS 15."],
        ["Minimal investigations", "**Non-contrast CT** (no skull X-ray). **NICE NG232 CT within 1 h**: GCS under 13 initially, under 15 at 2 h, open/depressed or basal fracture, seizure, focal deficit, vomiting more than once. **Within 8 h**: anticoagulated, or LOC/amnesia + age 65+, bleeding disorder, dangerous mechanism. PECARN in children."],
        ["Treatment - first line", "xABCDE with C-spine; intubate **GCS 8 or less**; **SpO2 over 94%, PaCO2 35-45**, **SBP 100+ (50-69 y) / 110+ (15-49, over 70)** - no permissive hypotension, no dextrose fluids; head up 30, neck neutral; normoglycaemia, normothermia."],
        ["Drugs", "**TXA 1 g over 10 min + 1 g over 8 h within 3 h** (GCS 9-15, CRASH-3); **steroids contraindicated** (CRASH); herniation: **mannitol 0.25-1 g/kg** or **3% saline 2-5 mL/kg**; seizure prophylaxis 7 days in severe TBI; warfarin - **PCC 25-50 IU/kg + vitamin K**; dabigatran - idarucizumab 5 g; paracetamol for pain."],
        ["Surgical lesions", "**EDH**: biconvex, does not cross sutures, evacuate if over 30 mL or GCS under 9 with anisocoria. **Acute SDH**: crescentic, crosses sutures, operate if over 10 mm or shift over 5 mm. **Chronic SDH**: burr holes; MMA embolisation cuts recurrence."],
        ["Special groups", "**Infants**: hypotension from scalp/intracranial bleed, NAI, paediatric verbal score, PECARN. **Elderly**: chronic SDH as reversible dementia, anticoagulants. **Athletes**: concussion - 24-48 h rest, graded return to learn before sport, SCAT6."],
        ["Complications", "Herniation, post-traumatic seizures, CSF leak/meningitis, DAI, hypopituitarism, post-concussion syndrome (10-30% beyond 4 weeks), chronic SDH, brainstem death."],
        ["Red flags & referral", "GCS 8 or less or fall of 2 points (or 1 motor), dilating pupil, Cushing triad, seizure, repeated vomiting, CSF leak, anticoagulated, penetrating/depressed fracture; refer neurosurgery and transfer without waiting for repeat imaging."],
        ["Follow-up & discharge", "Discharge mild TBI only to a **responsible adult for 24 h** with written return advice; review at 1-2 weeks; falls assessment in elderly; driving advice; **brainstem death** under THOT Rules 2014 - 4-member board, 2 sets 6 h apart, apnoea test."],
        ["Prevention / national programme", "Helmets (MV Amendment Act 2019), seat belts, no drink-driving; **Cashless Treatment Scheme 2025** up to Rs 1.5 lakh for 7 days."],
        ["Latest guideline change", "No change needed - NICE NG232, BTF 4th edition and CRASH-3 TXA remain current."],
        ["Exam one-liners", "Only secondary injury is treatable; only a third of EDH show a lucid interval; hypotension in head injury means bleeding elsewhere; mannitol and hyperventilation are bridges to theatre."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Adult head injury: who needs CT now",
        caption: "Condensed NICE NG232 decision. [NICE NG232 2023]",
        steps: [
          { label: "xABCDE with C-spine; GCS E-V-M, pupils", detail: "Intubate if GCS 8 or less; SBP 110+, SpO2 over 94%", tone: "warn" },
          { label: "Any 1-hour CT criterion?", detail: "GCS under 13, under 15 at 2 h, open/basal fracture, seizure, focal deficit, 2+ vomits", tone: "decision" },
          { label: "Yes: CT within 1 hour", detail: "TXA within 3 h if GCS 9-15; neurosurgery if lesion" },
          { label: "On anticoagulant, or LOC/amnesia + risk factor?", detail: "Age 65+, bleeding disorder, dangerous mechanism, amnesia over 30 min", tone: "decision" },
          { label: "Yes: CT within 8 hours", detail: "Reverse anticoagulation if bleed" },
          { label: "No criteria: discharge with responsible adult", detail: "Written return advice for 24-48 h", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Extradural against subdural haematoma",
        caption: "The CT shape and the patient tell them apart. [Bailey and Love 28e]",
        columns: ["Feature", "Extradural", "Acute subdural", "Chronic subdural"],
        rows: [
          ["Source", "Middle meningeal artery", "Bridging veins + contusion", "Bridging veins over atrophic brain"],
          ["CT shape", "Biconvex, stops at sutures", "Crescentic, crosses sutures", "Crescentic, hypodense"],
          ["Course", "Lucid interval in about one-third", "Unconscious from impact", "Weeks of confusion, falls"],
          ["Surgery", "Over 30 mL or GCS under 9 + anisocoria", "Over 10 mm or shift over 5 mm", "Burr holes; MMA embolisation"],
          ["Prognosis", "Excellent if early", "Poor", "Good; recurrence 10-20%"],
        ],
      },
      {
        kind: "ladder",
        heading: "Raised ICP: bridge to theatre",
        caption: "Each rung buys minutes, not a cure. [BTF 2016]",
        steps: [
          { label: "Head up 30, neck neutral, loosen ties", detail: "Normothermia, normoglycaemia, treat seizures" },
          { label: "Oxygenate and normoventilate", detail: "SpO2 over 94%, PaCO2 35-45 mmHg" },
          { label: "Protect SBP", detail: "100-110 mmHg or more; isotonic fluids, no dextrose" },
          { label: "Osmotherapy", detail: "Mannitol 20% 0.25-1 g/kg or 3% saline 2-5 mL/kg" },
          { label: "Brief hyperventilation", detail: "PaCO2 30-35 only for active herniation", tone: "warn" },
          { label: "Craniotomy / decompression", tone: "good" },
        ],
      },
    ],
  },

  "emergency-snake-bite-envenomation": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - Snake bite and scorpion sting",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Envenoming = clinical syndrome after venom injection; **dry bite in 20-50%** - **ASV for envenoming, never for the bite alone**."],
        ["Relevant classification", "By **syndrome**: neurotoxic (cobra, krait), haemotoxic (Russell's, saw-scaled), nephrotoxic (Russell's), myotoxic (sea snakes), local cytotoxic. **Big four** covered by polyvalent ASV; not covered: hump-nosed pit viper, king cobra, sea snakes."],
        ["Aetiology & risk factors", "India about **58,000 deaths/year**; monsoon, rural farm workers, sleeping on the floor (krait), paddy fields (vipers); delay at traditional healers."],
        ["Pathophysiology", "Cobra post-synaptic alpha-toxin (neostigmine-responsive) vs krait **presynaptic beta-bungarotoxin** (not); paralysis order: ptosis -> bulbar -> neck -> respiratory. Viper procoagulants -> **VICC** -> incoagulable blood (20WBCT); AKI, capillary leak, pituitary haemorrhage."],
        ["Key history", "**Time of bite**, circumstances, snake description (never delay), neuro symptoms (heavy lids, diplopia, dysphagia), bleeding, dark urine, **painless night bite + abdominal pain (krait)**, first aid used, tetanus status, pregnancy."],
        ["Key examination", "ABC; bite site, tender nodes, **mark swelling and measure hourly**; ptosis, ophthalmoplegia, **broken neck sign**, single breath count; bleeding sites; compartment signs; paralysed patients are conscious - **never brain dead**."],
        ["Minimal investigations", "**20WBCT**: 2 mL in new clean dry glass tube, 20 min, tilt - runs = incoagulable; normal -> hourly x 3 then 4-6 hourly to 24 h; after ASV **6 h after each dose**; observe **24 h**; PT/INR, creatinine, K+, CK, urine, ECG, hourly urine output."],
        ["First aid", "**Do it RIGHT**: Reassure, Immobilise, Go to Hospital (108), Tell doctor; remove rings; **no tourniquet, cut, suck, ice, herbs**; pressure bandage not routine; release existing tourniquet only with ASV running and adrenaline ready."],
        ["Treatment - ASV", "Indications: incoagulable 20WBCT, bleeding, neuro signs, shock, AKI, swelling over half limb in 48 h. **8-10 vials IV over 1 h** in 5-10 mL/kg saline, **same dose in children**, **no skin test**, adrenaline 0.5 mg IM drawn up."],
        ["Repeat dosing", "**Haemotoxic**: 20WBCT at 6 h, if incoagulable 5-10 vials 6-hourly until clotting (usually under 25-30). **Neurotoxic**: no better at **1-2 h** -> second 10 vials; **max 20**, then ventilate."],
        ["Escalation / adjuncts", "**Neostigmine trial**: atropine 0.6 mg then neostigmine 1.5 mg IV (child 0.04 mg/kg); response in 1 h -> 0.5 mg every 30 min x 5. BVM/intubation for paralysis; FFP only after ASV for serious bleeding; no heparin/TXA; dialysis for AKI."],
        ["ASV reactions", "Early (10-20%): stop, **adrenaline 0.5 mg IM**, hydrocortisone, chlorpheniramine, **restart slowly**; pyrogenic: paracetamol, fluids; serum sickness 5-24 days: prednisolone 5 mg 6-hourly 5-7 days."],
        ["Scorpion sting", "Indian red scorpion opens Na channels -> autonomic storm -> catecholamine myocarditis, pulmonary oedema; **prazosin 500 microgram (child 30 microgram/kg) 3-hourly then 6-hourly**; lignocaine for local pain; antivenom + prazosin; **no atropine or steroids**; NTG/dobutamine for oedema."],
        ["Special groups", "**Children**: same ASV dose. **Pregnancy**: same dose, risk of abortion/APH. **Anticoagulated**: higher bleeding risk. Hump-nosed viper: ASV ineffective - supportive."],
        ["Complications", "Respiratory paralysis, intracranial bleed, **AKI**, shock, compartment syndrome (rare - never fasciotomy before clotting corrects), necrosis, **late hypopituitarism** after Russell's viper, CKD."],
        ["Red flags & referral", "Ptosis or broken neck sign, incoagulable blood, oliguria/dark urine, shock, rapidly extending swelling, anaphylaxis to ASV, no response after 20 (neuro) or 25-30 (haemo) vials; **give first ASV dose before referral**."],
        ["Prevention / national programme", "**NAPSE 2024** - halve deaths by 2030, ASV at every PHC/CHC, helpline **15400**; snakebite **notifiable on IHIP (Nov 2024)**; cot and tucked net, torch, boots; PHC stock 10-20 vials + new glass tubes."],
        ["Latest guideline change", "No change needed - MoHFW STG 2017 dosing remains the national protocol; NAPSE 2024 and notifiability (Nov 2024) already included."],
        ["Exam one-liners", "Children get the same 8-10 vials; no skin test; 20WBCT needs a clean glass tube; neostigmine works for cobra, rarely krait; prazosin, not atropine, for scorpion sting."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Snakebite at the PHC",
        caption: "Condensed national protocol. [MoHFW STG Snakebite 2017]",
        steps: [
          { label: "Arrival: ABC, IV line in unbitten limb", detail: "20WBCT, labs, mark swelling; tourniquet off only when ready", tone: "warn" },
          { label: "Signs of envenoming?", detail: "Incoagulable 20WBCT, bleeding, ptosis, shock, AKI, swelling over half limb", tone: "decision" },
          { label: "No: observe 24 h", detail: "20WBCT hourly x 3, then 4-6 hourly; neuro checks" },
          { label: "Yes: ASV 8-10 vials IV over 1 h", detail: "Same dose in children; no skin test; adrenaline drawn up" },
          { label: "Neurotoxic: neostigmine trial, BVM ready", detail: "No better at 1-2 h -> 10 more vials; max 20, then ventilate" },
          { label: "Haemotoxic: 20WBCT 6 h after each dose", detail: "Incoagulable -> 5-10 vials; repeat until clots" },
          { label: "Refer with vials and times recorded", detail: "Ventilation, dialysis, persistent bleeding", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "The big four at a glance",
        caption: "Syndrome guides ASV and support. [WHO SEARO 2016]",
        columns: ["Snake", "Syndrome", "Local", "Key feature", "Neostigmine"],
        rows: [
          ["Spectacled cobra", "Neurotoxic (post-synaptic)", "Pain, swelling, necrosis", "Ptosis to respiratory paralysis", "Responds"],
          ["Common krait", "Neurotoxic (pre-synaptic)", "None; night floor bite", "Abdominal pain, delayed paralysis", "Poor"],
          ["Russell's viper", "Haemotoxic, nephrotoxic", "Marked swelling", "Incoagulable blood, AKI, hypopituitarism", "Not used"],
          ["Saw-scaled viper", "Haemotoxic", "Swelling, local bleed", "Prolonged coagulopathy", "Not used"],
        ],
      },
      {
        kind: "ladder",
        heading: "Scorpion sting grades",
        caption: "Grade drives care. [Bawaskar JAPI 2012]",
        steps: [
          { label: "Grade 1: local pain only", detail: "Lignocaine infiltration, paracetamol, observe 6 h" },
          { label: "Grade 2: autonomic storm", detail: "Prazosin 500 microgram (child 30 microgram/kg) 3-hourly then 6-hourly; antivenom" },
          { label: "Grade 3: myocarditis, pulmonary oedema", detail: "Prazosin, O2, NTG 5-20 microgram/min, dobutamine; ICU", tone: "warn" },
          { label: "Grade 4: multi-organ failure", detail: "ICU with ventilation", tone: "warn" },
        ],
      },
    ],
  },

  "emergency-heat-illness": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - Heat-related illness",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Heat gain exceeds loss and core temperature rises. **Heat stroke = core over 40 C + CNS dysfunction** (sweating does not exclude); heat exhaustion = 37-40 C with **normal mental state**."],
        ["Relevant classification", "Spectrum: heat rash, oedema, cramps, syncope, **exhaustion, stroke**; heat stroke **classic** (elderly, days, dry) vs **exertional** (young, hours, sweating, rhabdo/AKI/DIC). IMD heat wave: 40 C plains / 37 coast / 30 hills with departure 4.5-6.4, or 45 C actual."],
        ["Aetiology & risk factors", "Heat waves March-July, humidity (WBGT), outdoor labour 12-3 pm, no acclimatisation (7-14 days), age over 65, infants, pregnancy, CKD, HF, obesity; **anticholinergics, diuretics, SGLT2i, ACEi/ARB, beta-blockers, lithium**, stimulants, alcohol."],
        ["Pathophysiology", "Hypothalamic set point normal -> heat loss overwhelmed -> splanchnic vasoconstriction -> gut endotoxin -> **SIRS-like cytokine storm** + direct cytotoxicity over 42 C -> cerebellar Purkinje injury, rhabdomyolysis, AKI, liver injury, **DIC at 24-72 h**."],
        ["Key history", "Exposure and exertion, collapse during work vs days at home, **any behaviour change**, fluids (plain water - cramps), cola urine, drugs, vulnerability, infection clues (malaria, meningitis), toxidrome (NMS, serotonin, MH, thyroid storm)."],
        ["Key examination", "**Rectal temperature mandatory** (oral/tympanic underestimate); GCS, **ataxia**, seizures; tachycardia, hypotension; hot dry or sweating skin; muscle tenderness; crackles; jaundice; rigidity (NMS), clonus (serotonin)."],
        ["Minimal investigations", "Rectal temp every 5 min during cooling, glucose, ECG; electrolytes, Ca, phosphate, creatinine, LFT, **CK (over 5x = rhabdo)**, PT/INR, platelets (repeat 24-72 h); gas; **malaria test in every febrile confused patient**; CT/LP only after cooling starts."],
        ["Treatment - first line", "**Cool first, transport second**: **cold water immersion (1-15 C)** to **below 39 C within 30 min**, stop at **38.5-39 C**; else tarp-assisted or evaporative (spray + fan); ice packs adjunct only; ABC, O2, glucose."],
        ["Drugs and fluids", "**No antipyretics** (set point normal; NSAIDs worsen AKI); **no dantrolene**; benzodiazepine for shivering/seizures (midazolam 2-5 mg IV); NS/RL **1-2 L in first hour** (cautious in elderly); noradrenaline if still hypotensive; rhabdo - urine 200-300 mL/h."],
        ["Minor heat illness", "Rash - cotton, calamine; cramps - ORS or salted fluids; syncope - lie flat, fluids; oedema - elevate, **no diuretics**; exhaustion - cool place, **ORS 200-400 mL at a time**, IV if vomiting; any confusion = heat stroke."],
        ["Special groups", "**Elderly**: classic heat stroke, pulmonary oedema with fluids, drug review. **Children**: parked vehicles, IV 10-20 mL/kg. **Workers**: acclimatisation, work-rest, buddy system. **Pregnancy**: higher risk, cool aggressively."],
        ["Complications", "Rhabdomyolysis, hyperkalaemia, AKI, DIC, acute liver failure, ARDS, cerebral oedema, rebound hyperthermia or overshoot hypothermia, lasting cerebellar deficits (20-30%)."],
        ["Red flags & referral", "Any confusion, ataxia or seizure in heat; rectal over 40 C; exertional collapse; cola urine; bleeding/jaundice at 24-72 h; refractory hypotension; refer every heat stroke **after cooling has begun**, cooling en route."],
        ["Follow-up & monitoring", "Repeat LFT, INR, platelets, creatinine at 24-72 h; return to exertion after 1-2 weeks rest with graded re-acclimatisation; pre-summer medicine review (diuretics, SGLT2i, ACEi sick-day rules, lithium)."],
        ["Prevention / national programme", "**NPCCHH (NCDC)**: daily IHIP heat surveillance **1 March-31 July**, facility preparedness (cool room, ice, ORS corners, rectal thermometers), emergency cooling guidance; **NDMA heat action plans** (Ahmedabad 2013 first); IMD colour warnings 5 days ahead."],
        ["Latest guideline change", "No change needed - NCDC summer 2025 advisory reaffirms the 2024 NPCCHH action plan, emergency cooling guidance and IHIP reporting from 1 March; ACSM 2023 cooling targets unchanged."],
        ["Exam one-liners", "Rectal temperature or nothing; cool first, transport second; antipyretics do not work; dantrolene is for malignant hyperthermia; cerebellum is most heat-sensitive."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Suspected heat stroke: cool first",
        caption: "Condensed exam version. [ACSM Consensus 2023, NPCCHH Heat Guidelines 2024]",
        steps: [
          { label: "Hot patient with any mental change", detail: "Rectal temperature; do not wait for it after exertional collapse", tone: "warn" },
          { label: "ABC, O2, capillary glucose", detail: "Recovery position; intubate if GCS stays 8 or less" },
          { label: "Immersion possible?", detail: "Cold water tub, tarp or ice water", tone: "decision" },
          { label: "Yes: cold water immersion 1-15 C", detail: "Rectal temp every 5 min; below 39 C within 30 min" },
          { label: "No: evaporative or tarp cooling", detail: "Strip, spray lukewarm water, fan; ice packs to neck, axillae, groin" },
          { label: "Stop at 38.5-39 C", detail: "Watch rebound and overshoot; benzodiazepine for shivering" },
          { label: "Fluids, bloods, malaria test, transfer", detail: "1-2 L in first hour; CK, LFT, INR; keep cooling en route", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Heat exhaustion against heat stroke",
        caption: "Mental state, not sweating, separates them. [Harrison 22e]",
        columns: ["Feature", "Heat exhaustion", "Heat stroke"],
        rows: [
          ["Core temperature", "37-40 C", "Above 40 C"],
          ["Mental state", "Normal", "Confusion, ataxia, seizures, coma"],
          ["Sweating", "Heavy", "Absent (classic) or present (exertional)"],
          ["Organ injury", "None", "Rhabdo, AKI, liver, DIC"],
          ["Treatment", "Cool place, ORS or IV fluids, observe", "Immediate immersion, ABC, refer"],
        ],
      },
      {
        kind: "compare",
        heading: "Classic against exertional heat stroke",
        caption: "Two patients, one emergency. [ACSM Consensus 2023]",
        columns: ["Feature", "Classic", "Exertional"],
        rows: [
          ["Who", "Elderly, infants, chronically ill", "Young workers, athletes, soldiers"],
          ["Onset", "Days of heat wave", "Hours of exertion"],
          ["Skin", "Often dry", "Often sweating"],
          ["Rhabdo, AKI, DIC", "Less common", "Common"],
          ["Mortality", "Over 50% if cooling delayed", "Near zero with immediate immersion"],
        ],
      },
    ],
  },
};

export default revision;
