import type { RevisionSet } from "./index";

const revision: RevisionSet = {
  "endocrine-t2dm-diagnosis-oral-drugs": {
    checked: "2026-10",
    updated: [
      "ADA 2026: CGM now recommended from diagnosis for anyone on insulin or a hypoglycaemia-causing drug (sulfonylurea, glinide).",
      "ADA 2026 / ACIP: pneumococcal options now PCV20 or PCV21 alone, or PCV15 then PPSV23; RSV vaccine once at 75 or more (50-74 if at increased risk).",
    ],
    master: {
      heading: "Master revision table - type 2 diabetes: diagnosis and oral drugs",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Progressive beta-cell failure on insulin resistance**; diagnose by **FPG 126 or more, 2-h OGTT 200 or more, HbA1c 6.5% or more** (two abnormal results) or **random 200 or more with symptoms** (mg/dL)."],
        ["Relevant classification", "ADA aetiological: type 1, **type 2**, specific types (MODY, pancreatic, drug-induced), GDM; Indian specials - **LADA, fibrocalculous pancreatic diabetes, ketosis-prone diabetes**. **Prediabetes**: IFG 100-125, IGT 140-199, HbA1c 5.7-6.4%."],
        ["Aetiology & risk factors", "Family history, **central obesity (waist 90/80 cm)**, sedentary life, past GDM or PCOS, **thin-fat Indian phenotype**, steroids, antipsychotics; India prevalence **11.4%**, prediabetes **15.3%** (ICMR-INDIAB)."],
        ["Pathophysiology", "Visceral fat -> FFA, cytokines -> **IRS-1 serine phosphorylation** -> insulin resistance -> beta-cell hypersecretion -> glucolipotoxicity, amyloid -> **beta-cell failure (50% lost at diagnosis)** -> hyperglycaemia (**ominous octet**)."],
        ["Key history (OPD)", "Osmotic symptoms and tempo (rapid weight loss = insulin deficiency), **ketosis symptoms**, infections, **TB screen (cough 2 weeks)**, complication symptoms, drugs, diet recall, fasting practices, cost and adherence, hypoglycaemia."],
        ["Key examination", "BMI (Asian cut-offs), **waist**, BP lying/standing, **acanthosis nigricans**, feet (**10 g monofilament, 128 Hz fork, pulses**), dilated fundus, mouth, signs of Cushing/acromegaly, Kussmaul breathing if unwell."],
        ["Minimal investigations", "**Venous FPG plus HbA1c** (OGTT if discordant; never a glucometer), Hb (iron deficiency falsely raises HbA1c), lipids, **creatinine-eGFR, urine ACR**, ALT, urine ketones, ECG over 40; B12 on metformin."],
        ["Diagnostic criteria", "FPG **126 or more**, 2-h **200 or more**, HbA1c **6.5% or more**, random **200 or more with symptoms**; confirm asymptomatic results by a second test. Remission = **HbA1c under 6.5% 3 months off drugs**."],
        ["Treatment - first line", "Lifestyle (plate method, **150 min/week activity**, 5-7% weight loss) plus **metformin 500 mg OD-BD with meals -> 1 g BD** (XR up to 2 g OD); ASCVD/HF/CKD: add **SGLT2i or GLP-1 RA** from day 1."],
        ["Escalation / second line", "Choose by organ: **HF or CKD - dapagliflozin/empagliflozin 10 mg OD**; **ASCVD/obesity - semaglutide 0.25->1 mg weekly or tirzepatide 2.5->15 mg weekly**; cost - **gliclazide MR 30-120 mg or glimepiride 1-4 mg**, teneligliptin 20 mg; **HbA1c over 10% or catabolic - insulin**."],
        ["Devices / procedures", "**Oral semaglutide**: on waking, **120 mL water or less, wait 30 min**; weekly GLP-1 pens same weekday; **CGM from diagnosis if on insulin or a sulfonylurea** (ADA 2026), otherwise glucometer as needed."],
        ["Special groups", "**Pregnancy - insulin** (stop SGLT2i, GLP-1 RA, gliptins, pioglitazone); **eGFR 30-45 cap metformin 1 g, stop under 30**; elderly - avoid glibenclamide, HbA1c under 8%; **Ramadan - break fast if under 70 or over 300**."],
        ["Complications", "Hypoglycaemia (SU), **euglycaemic DKA (SGLT2i - stop 3 days pre-op)**, genital mycosis, **B12 deficiency (metformin)**, lactic acidosis (rare), pancreatitis/bullous pemphigoid (gliptins), oedema/HF (pioglitazone); micro- and macrovascular disease."],
        ["Red flags & referral", "Lean young + weight loss + ketonuria; **glucose over 300 with vomiting/drowsiness (DKA/HHS)**; euglycaemic DKA; foot sepsis; sudden visual loss; suspected LADA/MODY/FCPD, 3-drug failure, pregnancy, eGFR under 30."],
        ["Follow-up & monitoring", "Review 2-4 weeks after a change; **HbA1c 3-monthly until target, then 6-monthly**; targets **HbA1c under 7%**, FPG 80-130, PPG under 180, **BP under 130/80**, LDL under 70 (under 55 with ASCVD); yearly ACR, eGFR, fundus, feet, B12."],
        ["Prevention / national programme", "**NP-NCD**: screening over 30 at Ayushman Arogya Mandir, free metformin and glimepiride; **IDPP-1**: lifestyle cut progression **28.5%**, metformin 26.4%; vaccinate (influenza, pneumococcal, hepatitis B, zoster, RSV)."],
        ["Latest guideline change", "**ADA 2026**: **CGM from diagnosis** for insulin or hypoglycaemia-causing drugs; vaccines - **PCV20 or PCV21 alone (or PCV15 then PPSV23)**, **RSV once at 75+ or 50-74 at risk**."],
        ["Exam one-liners", "Second drug by organ, not by HbA1c; **no meal, no pill** for SU; **SGLT2i eGFR dip 3-5 is protective**; never diagnose on a glucometer; check Hb before trusting HbA1c."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "From suspicion to first prescription",
        caption: "The 10-mark answer sequence for a newly suspected type 2 diabetic.",
        steps: [
          { label: "Symptoms or screening positive (NP-NCD, over 30)", detail: "Capillary value is screening only" },
          { label: "Venous FPG plus HbA1c on one sample", detail: "FPG 126+, HbA1c 6.5%+; OGTT if discordant", tone: "decision" },
          { label: "Ketones, vomiting, glucose 300+?", detail: "DKA/HHS - admit; catabolic - start insulin", tone: "warn" },
          { label: "Phenotype check: lean, young, rapid loss?", detail: "C-peptide, GAD - LADA, type 1, FCPD", tone: "decision" },
          { label: "Baseline work-up", detail: "Hb, lipids, eGFR, urine ACR, ALT, ECG, fundus, feet" },
          { label: "Lifestyle plus metformin", detail: "500 mg OD-BD with meals, to 1 g BD" },
          { label: "Add organ-protective drug if ASCVD, HF, CKD", detail: "SGLT2i 10 mg OD or GLP-1 RA weekly", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Escalation ladder after metformin",
        caption: "Add a different class every 3 months off target, after checking adherence and cost.",
        steps: [
          { label: "Metformin plus lifestyle", detail: "Up to 2 g/day; XR if GI upset" },
          { label: "Add by comorbidity", detail: "HF/CKD: dapagliflozin 10 mg; ASCVD/obesity: semaglutide 0.5-1 mg weekly" },
          { label: "Add by cost if no comorbidity", detail: "Gliclazide MR 30-120 mg or glimepiride 1-4 mg; teneligliptin 20 mg" },
          { label: "Triple oral or GLP-1 RA / tirzepatide", detail: "Tirzepatide 2.5 mg weekly, +2.5 mg every 4 weeks to 5-15 mg" },
          { label: "Basal insulin", detail: "10 units bedtime, +2 units every 3 days to FPG 80-130", tone: "warn" },
        ],
      },
      {
        kind: "compare",
        heading: "Oral drug classes - pick in one glance",
        columns: ["Class", "HbA1c fall", "Weight", "Key harm"],
        rows: [
          ["Metformin", "1-1.5%", "Neutral", "GI upset, B12 deficiency; stop eGFR under 30"],
          ["Sulfonylurea", "1-1.5%", "Gain 2-3 kg", "Hypoglycaemia (avoid glibenclamide)"],
          ["SGLT2 inhibitor", "0.5-0.9%", "Loss 2-3 kg", "Genital mycosis, euglycaemic DKA"],
          ["DPP-4 inhibitor", "0.5-0.8%", "Neutral", "Pancreatitis, bullous pemphigoid"],
          ["Pioglitazone", "0.8-1.2%", "Gain", "Oedema, heart failure, fractures"],
        ],
      },
    ],
  },

  "endocrine-insulin-initiation": {
    checked: "2026-10",
    updated: [
      "ADA 2026: CGM recommended from diagnosis and any time thereafter for all on insulin; pump/AID no longer needs C-peptide or antibody prerequisites.",
      "Insulin icodec (once-weekly basal) launched in India July 2026 for adults with type 1 and type 2 diabetes.",
    ],
    master: {
      heading: "Master revision table - insulin initiation and titration",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Replacing **basal (about 50%)** and **prandial** insulin secretion when oral agents cannot hold glucose; in type 2 start when **HbA1c over 10%, glucose 300+, catabolic/ketotic** or **above target on 2-3 oral drugs**."],
        ["Relevant classification", "By action: **rapid** (lispro, aspart, glulisine), **short** (regular), **intermediate** (NPH), **long** (glargine U100, detemir), **ultra-long** (degludec, glargine U300, **weekly icodec**), **premix** (30/70, IDegAsp 70/30)."],
        ["Aetiology & risk factors", "Progressive beta-cell loss, glucotoxicity, pregnancy, acute illness, surgery, **high-dose steroids**, **eGFR under 30**, decompensated liver disease, LADA/type 1."],
        ["Pathophysiology", "Beta-cell failure -> loss of first phase -> fasting and postprandial rise; SC insulin -> **reversed portal gradient** -> peripheral hyperinsulinaemia -> weight gain, hypoglycaemia; **glucotoxicity reversible** with 2-4 weeks of insulin."],
        ["Key history (OPD)", "HbA1c trend on optimised orals, catabolic symptoms, **adherence and cost**, needle fear and myths, **meal pattern** (decides regimen), who will inject (vision, dexterity), fridge, occupation (driving), hypoglycaemia history."],
        ["Key examination", "**Palpate every injection site** (lipohypertrophy), weight, fundus (rapid fall worsens PDR), hand function, signs of catabolism, postural BP, feet."],
        ["Minimal investigations", "HbA1c 3-monthly; **fasting SMBG daily during titration**; **3 a.m. value** before raising evening insulin; 7-point profile; **CGM - TIR 70-180 over 70%, below 70 under 4%, below 54 under 1%**; eGFR."],
        ["Treatment - first line", "**Basal 10 units or 0.1-0.2 units/kg** (NPH at 10 p.m. or glargine fixed time); **+2 units every 3 days** to FPG **80-130**; **-4 units or 10-20%** for any value under 70; keep metformin, **halve SU**."],
        ["Escalation / second line", "Basal over **0.5 units/kg** or bedtime-to-morning drop 50+ = **over-basalisation** -> add **GLP-1 RA** or **basal plus 4 units rapid** at largest meal -> **basal-bolus 0.4-0.5 units/kg (50:50)**; or **premix 0.2-0.3 units/kg, 2/3 AM, 1/3 PM**."],
        ["Devices / procedures", "**4 mm pen needle at 90 degrees, no pinch**; roll/tip cloudy insulin 10 times; **prime 2 units**; **hold 10 s**; rotate quadrants 1 cm apart; **match U-40 syringe to U-40 vial**; clear before cloudy; store 2-8 C, in-use under 30 C for 28 days."],
        ["Special groups", "**Pregnancy** - insulin first-line (aspart, lispro, detemir, glargine); **CKD** - cut doses 25-50%; steroids - **morning NPH 0.1 units/kg per 10 mg prednisolone**; Ramadan - basal down 20-40%, main dose at iftar."],
        ["Complications", "**Hypoglycaemia**, weight gain 2-4 kg, **lipohypertrophy**, insulin oedema, hypokalaemia (IV), early retinopathy worsening, rare allergy; **Somogyi vs dawn** confusion."],
        ["Red flags & referral", "Recurrent/nocturnal/severe lows or unawareness; ketones with glucose over 250; insulin stopped for cost; falling needs (CKD, Addison, TB); pump with unexplained highs; refer type 1, pregnancy, over 1.5-2 units/kg."],
        ["Follow-up & monitoring", "Phone review **every 1-2 weeks during titration**, clinic at 4-6 weeks with site check; targets FPG 80-130, PPG under 180, HbA1c under 7% (under 8% elderly)."],
        ["Prevention / national programme", "Insulin free under **NP-NCD** at district level; teach **rule of 15**, sick-day rules (never stop basal), sharps disposal in a hard bottle, identity card."],
        ["Latest guideline change", "**ADA 2026**: **CGM from diagnosis** on any insulin; **no C-peptide/antibody prerequisites for pumps or AID** (AID Level A in type 2); **icodec weekly basal launched in India 2026**."],
        ["Exam one-liners", "**Basal 10 units at bedtime, +2 every 3 days**; never raise evening insulin without a 3 a.m. value; regular insulin 30 min before food, analogue at the plate; halve SU when basal starts."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Insulin start decision in type 2",
        steps: [
          { label: "HbA1c over 10%, glucose 300+, ketones or weight loss?", detail: "Yes - insulin now (often basal-bolus short term)", tone: "decision" },
          { label: "Above target on 2-3 optimised orals?", detail: "Check adherence, cost, technique first", tone: "decision" },
          { label: "Injectable needed: GLP-1 RA or tirzepatide first", detail: "Unless catabolic, ketotic or very high glucose" },
          { label: "Start basal 10 units or 0.1-0.2 units/kg", detail: "Keep metformin; halve sulfonylurea" },
          { label: "Patient-led titration on fasting value", detail: "+2 units every 3 days; -4 units if under 70" },
          { label: "Fasting 80-130 and HbA1c at target", detail: "Review 3-monthly", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Insulin intensification ladder",
        steps: [
          { label: "Basal only", detail: "10 units bedtime; titrate to FPG 80-130" },
          { label: "Basal plus GLP-1 RA (or fixed-ratio combination)", detail: "When basal over 0.5 units/kg and HbA1c high" },
          { label: "Basal plus one prandial dose", detail: "4 units or 10% of basal before largest meal" },
          { label: "Premix twice daily", detail: "0.2-0.3 units/kg/day; 2/3 morning, 1/3 evening" },
          { label: "Basal-bolus", detail: "0.4-0.5 units/kg/day; 50% basal, 50% over 3 meals", tone: "warn" },
        ],
      },
      {
        kind: "compare",
        heading: "High fasting glucose - three causes",
        columns: ["Cause", "3 a.m. glucose", "Action"],
        rows: [
          ["Insufficient basal", "High", "Increase basal by 2 units"],
          ["Dawn phenomenon", "Normal, rises after 4 a.m.", "Move NPH to 10 p.m. or switch to glargine"],
          ["Somogyi rebound", "Low (under 70)", "Reduce evening insulin; bedtime snack"],
        ],
      },
    ],
  },

  "endocrine-diabetes-complication-screening": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - diabetic complication screening",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Yearly structured search for **microvascular** (retinopathy, nephropathy, neuropathy) and **macrovascular** disease plus the at-risk foot - **type 2 from diagnosis, type 1 from 5 years after**."],
        ["Relevant classification", "**DR**: none, mild/moderate/severe NPDR (**4-2-1 rule**), PDR, DMO separate; **KDIGO G1-G5 and A1-A3 (ACR under 30, 30-300, over 300 mg/g)**; **IWGDF risk 0-3**; foot infection IWGDF/IDSA mild-moderate-severe."],
        ["Aetiology & risk factors", "Duration, **HbA1c**, BP, LDL, smoking, albuminuria; previous ulcer is the **strongest predictor of the next ulcer**; barefoot walking, poor footwear."],
        ["Pathophysiology", "GLUT1 tissues cannot limit glucose -> **polyol, AGE, PKC, hexosamine** -> mitochondrial superoxide -> pericyte loss, GBM thickening, axonopathy -> ischaemia, **VEGF** -> new vessels; hyperfiltration -> albuminuria -> GFR fall."],
        ["Key history (OPD)", "Visual blur or floaters, frothy urine, oedema, burning feet worse at night, autonomic symptoms (postural dizziness, gastroparesis, ED), **previous ulcer**, claudication, NSAIDs, B12 (metformin), leprosy, TB."],
        ["Key examination", "Acuity + **dilated fundus** (tropicamide + phenylephrine); **10 g monofilament** at hallux and MTH 1, 3, 5; **128 Hz fork**, ankle jerks; pulses, ABI; foot inspection; **postural BP fall 20/10**; probe-to-bone in ulcers."],
        ["Minimal investigations", "**Urine ACR (2 of 3 over 3-6 months)**, **eGFR CKD-EPI 2021**, K on RAS blockers, fasting lipids, ECG; fundus photo/AI grading, OCT for DMO; ABI (toe pressure if over 1.3); X-ray and deep culture for infected ulcer."],
        ["Diagnostic criteria", "**LOPS** = any monofilament site missed; DKD = persistent **ACR 30+ and/or eGFR under 60** for 3 months; **severe NPDR** by 4-2-1; PAD = **ABI under 0.9**; osteomyelitis supported by probe-to-bone."],
        ["Treatment - first line", "Multifactorial: **HbA1c under 7%, BP under 130/80, statin (atorvastatin 10-20 mg 40-75 yrs; 40-80 mg if risk)**, stop smoking; foot education (**never barefoot**), MCR footwear."],
        ["Escalation / second line", "DKD pillars: **max-dose ACEi/ARB** (ramipril to 10 mg) + **SGLT2i (eGFR 20+)** + **finerenone 10-20 mg (K 5.0 or less, eGFR 25+)** + **semaglutide 1 mg weekly (FLOW)**; painful DPN: **pregabalin 75-150 mg BD, duloxetine 60 mg, amitriptyline 10-75 mg**."],
        ["Devices / procedures", "**Anti-VEGF** for centre-involving DMO; **PRP** for PDR; vitrectomy for non-clearing haemorrhage; **total contact cast** for plantar ulcer; non-removable cast for acute Charcot."],
        ["Special groups", "**Pregnancy**: fundus before conception, each trimester and 1 year postpartum; stop ACEi/ARB, statins, finerenone; CKD - adjust metformin, gliptins, gabapentinoids; elderly - avoid amitriptyline."],
        ["Complications", "Blindness (DMO commonest in type 2), ESKD, **foot ulcer, Charcot, amputation**, gastroparesis, orthostatic hypotension, hypoglycaemia unawareness, silent MI."],
        ["Red flags & referral", "Sudden visual loss/floaters; foot sepsis, crepitus, probe-to-bone; **hot swollen painless foot (Charcot)**; rest pain/gangrene; K over 5.5 or creatinine rise over 30%; eGFR under 30 or heavy proteinuria without retinopathy."],
        ["Follow-up & monitoring", "Annual package: **fundus, ACR + eGFR, monofilament + pulses, lipids, B12**; eye 1-2 yearly if no DR and well controlled; kidney 3-6 monthly if eGFR under 60; **foot by IWGDF: 0 yearly, 1 6-12 mo, 2 3-6 mo, 3 1-3 mo**."],
        ["Prevention / national programme", "**NP-NCD** register and recall; NPCBVI diabetic retinopathy screening; vaccines; dental review; Steno-2 multifactorial control **halves CV events**."],
        ["Latest guideline change", "No change needed in 2026 - **ADA 2026** retains BP under 130/80, statin by risk, four-pillar DKD therapy; **KDIGO 2024** CKD and **IWGDF 2023** foot guidance current."],
        ["Exam one-liners", "**Type 2 at diagnosis, type 1 after 5 years**; DMO, not PDR, is the commonest cause of visual loss in type 2; early eGFR dip up to 30% on ACEi/SGLT2i - continue; ABI over 1.3 - use toe pressure."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "The 10-minute annual review",
        steps: [
          { label: "Eyes: acuity and dilated fundus or photograph", detail: "Beyond mild NPDR or any DMO - refer", tone: "decision" },
          { label: "Kidney: urine ACR plus eGFR", detail: "ACR 30+ on 2 of 3 samples = albuminuria", tone: "decision" },
          { label: "Feet: monofilament, fork, pulses, inspection", detail: "Assign IWGDF risk 0-3 and recall interval" },
          { label: "Heart: BP, lipids, smoking, ECG if symptoms", detail: "BP under 130/80; statin 40-75 years" },
          { label: "Ulcer, Charcot or critical ischaemia?", detail: "Same-day foot team or vascular referral", tone: "warn" },
          { label: "Record in NP-NCD card and set recall", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Diabetic kidney disease - drug ladder",
        steps: [
          { label: "BP, glucose, statin, stop smoking", detail: "BP under 130/80; protein 0.8 g/kg; salt under 5 g" },
          { label: "ACE inhibitor or ARB to maximum dose", detail: "Ramipril 2.5-10 mg OD; K and creatinine at 1-2 weeks" },
          { label: "Add SGLT2 inhibitor", detail: "Dapagliflozin or empagliflozin 10 mg OD if eGFR 20+" },
          { label: "Add finerenone if ACR 30+ persists", detail: "10 mg (eGFR 25-59) or 20 mg; K 5.0 or less" },
          { label: "Add GLP-1 RA", detail: "Semaglutide 1 mg weekly (FLOW)" },
          { label: "Nephrology referral", detail: "eGFR under 30, fall over 5/year, ACR over 300 despite treatment", tone: "warn" },
        ],
      },
      {
        kind: "compare",
        heading: "Neuropathic ulcer versus ischaemic ulcer",
        columns: ["Feature", "Neuropathic", "Ischaemic"],
        rows: [
          ["Site", "Plantar, under metatarsal heads", "Toe tips, heel, foot margins"],
          ["Foot", "Warm, pulses present, callus", "Cold, pulses absent, pale"],
          ["Pain", "Painless", "Painful, rest pain"],
          ["Key treatment", "Offloading - total contact cast", "Revascularisation before debridement"],
        ],
      },
    ],
  },

  "endocrine-hypoglycaemia": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - hypoglycaemia",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "In treated diabetes: **level 1 under 70 mg/dL**, **level 2 under 54 mg/dL**, **level 3 = needs another person's help** (any value); without diabetes: **Whipple triad** with glucose under 55."],
        ["Relevant classification", "ADA levels 1-3; non-diabetic - **fasting** (insulinoma, drugs, organ failure, adrenal/pituitary failure, IGF-2 tumour) vs **postprandial** (post-bariatric, dumping)."],
        ["Aetiology & risk factors", "**Sulfonylureas (glibenclamide worst)**, insulin excess or mistiming, missed meal, exercise, **alcohol**, **CKD**, elderly, **hypoglycaemia unawareness**, beta-blockers, interacting antibiotics, herbal products with hidden SU."],
        ["Pathophysiology", "Falling glucose -> insulin off (80-85) -> **glucagon** and **adrenaline** (65-70) -> autonomic symptoms (55-60) -> **neuroglycopenia (under 50)**; recurrent lows -> **HAAF** -> unawareness."],
        ["Key history (OPD)", "Ask **by symptom** (sweats, tremor, nightmares, morning headache), timing, help needed, **Gold/Clarke score 4+**, exact drugs and syringe type, meals, alcohol, exercise, driving, weight loss (CKD, Addison, TB)."],
        ["Key examination", "**Capillary glucose first** in any altered consciousness; airway and ability to swallow; alcohol/malnutrition; Addison pigmentation; CKD; **injection-site lipohypertrophy**; postural BP."],
        ["Minimal investigations", "Capillary glucose, lab glucose (fluoride tube); **creatinine/eGFR**, LFT, TSH, **8 a.m. cortisol** if suspected; CGM review (**time below 70 over 4%** = overtreatment); non-diabetic - **critical sample: glucose, insulin, C-peptide, BHB, SU screen**."],
        ["Diagnostic criteria", "ADA level by value or need for help; insulinoma - **high insulin + high C-peptide + negative SU screen + suppressed BHB** during glucose under 55; **72-hour fast** if not captured."],
        ["Treatment - first line", "**Rule of 15**: 15-20 g glucose (3-4 tsp sugar in water, 150 mL juice), recheck 15 min, repeat if under 70, then snack; **on acarbose give pure glucose**; child **0.3 g/kg**."],
        ["Escalation / second line", "Cannot swallow: **25% dextrose 100 mL** or **50% dextrose 50 mL IV** (child **10% 2 mL/kg**); no IV - **glucagon 1 mg IM** (0.5 mg under 25 kg) or **nasal 3 mg**; SU overdose - **10% dextrose infusion + octreotide 50-100 mcg SC 6-12 hourly**; **thiamine 100 mg IV** in alcoholics."],
        ["Devices / procedures", "**CGM with low alarms** for recurrent level 2-3 or unawareness; glucagon kit taught to family; injection-site rotation; meter check."],
        ["Special groups", "**Elderly** - falls, confusion, relax HbA1c to under 8%; **CKD** - linagliptin 5 mg, avoid glibenclamide/glimepiride; **fasting** - halve pre-dawn dose, break fast under 70; children - IV 10% only."],
        ["Complications", "Seizure, falls and fractures, road accidents, arrhythmia, **cognitive decline**, hippocampal necrosis, unawareness, death; rebound hyperglycaemia if overtreated."],
        ["Red flags & referral", "Unconscious/fitting; **SU, long-acting insulin or renal failure - admit 24-72 h**; no recovery 15-30 min after normal glucose (stroke, sepsis, co-ingestion); falling insulin need; Whipple triad without diabetes; deliberate overdose."],
        ["Follow-up & monitoring", "Review **within 1-2 weeks** of level 2-3 episode; CGM targets **below 70 under 4%, below 54 under 1%** (under 1% below 70 in older adults); annual eGFR; re-teach rule of 15 and glucagon yearly."],
        ["Prevention / national programme", "Individualise targets; **replace glibenclamide with gliclazide MR or a DPP-4i/SGLT2i/GLP-1 RA**; analogue basal for nocturnal lows; driving - test before, do not drive under 90; carry glucose and ID."],
        ["Latest guideline change", "No change needed in 2026 - **ADA 2026** keeps levels 1-3, rule of 15 and CGM targets; Endocrine Society 2023 high-risk guidance current."],
        ["Exam one-liners", "Level 3 is defined by needing help, not a number; **glucagon fails when glycogen is empty** (alcohol, starvation); high insulin + low C-peptide = exogenous insulin; **2-3 weeks of strict avoidance restores awareness**."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Treating a low at the bedside",
        steps: [
          { label: "Glucose under 70 mg/dL or symptoms", detail: "Confirm with capillary value if possible" },
          { label: "Can the patient swallow safely?", detail: "Decides oral versus parenteral", tone: "decision" },
          { label: "Yes: 15-20 g fast glucose, recheck in 15 min", detail: "Repeat until above 70; then a meal or snack" },
          { label: "No: 25% dextrose 100 mL IV or glucagon 1 mg IM", detail: "Child: 10% dextrose 2 mL/kg; thiamine first if alcoholic", tone: "warn" },
          { label: "Cause is SU, long-acting insulin or CKD?", detail: "Admit 24-72 h, 10% dextrose drip, octreotide", tone: "decision" },
          { label: "Change the regimen before discharge", detail: "Cut dose 10-20%, stop glibenclamide, teach family", tone: "good" },
        ],
      },
      {
        kind: "branch",
        heading: "Hypoglycaemia without diabetes - critical sample",
        root: "Glucose under 55 mg/dL with Whipple triad",
        arms: [
          { label: "Insulin high, C-peptide high", tone: "decision", steps: ["SU screen negative - insulinoma", "SU screen positive - sulfonylurea ingestion", "Localise: CT/MRI, EUS, GLP-1R PET"] },
          { label: "Insulin high, C-peptide suppressed", tone: "warn", steps: ["Exogenous insulin", "Accidental or factitious - psychiatric review"] },
          { label: "Insulin low, BHB raised", steps: ["Adrenal or pituitary failure", "Alcohol, starvation, liver failure"] },
          { label: "Insulin low, BHB suppressed", steps: ["Non-islet tumour secreting big IGF-2"] },
        ],
      },
    ],
  },

  "endocrine-hypothyroidism": {
    checked: "2026-10",
    updated: [
      "ATA 2026 (pregnancy): fixed TSH targets of 2.5 (first trimester) and 3.0 dropped - keep TSH within trimester-specific range; about 0.1-4.0 mIU/L in first and second trimesters if no local range.",
      "ATA 2026: confirm a mild new abnormality within 3 weeks before treating (treat at once if overt with TSH 6 or more); testing is targeted, not universal.",
      "ATA 2026: anti-TPO status alone no longer decides levothyroxine; euthyroid anti-TPO positive women with infertility or recurrent miscarriage are not given levothyroxine (check TSH 3-6 monthly preconception).",
    ],
    master: {
      heading: "Master revision table - hypothyroidism and subclinical hypothyroidism",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Overt primary: **TSH high + free T4 low**; subclinical: **TSH high + free T4 normal** - mild **4.5-9.9**, marked **10 or more** mIU/L; central: **low free T4 with low/normal TSH**."],
        ["Relevant classification", "**Primary** (Hashimoto, post-ablation, drugs, iodine), **central** (pituitary/hypothalamic), **transient** (post-partum, subacute thyroiditis), **congenital**; non-thyroidal illness as a mimic."],
        ["Aetiology & risk factors", "**Hashimoto** commonest in India (prevalence about **10.9%**), women, other autoimmunity, **amiodarone, lithium**, checkpoint inhibitors, TKIs, thyroidectomy/radioiodine, Sheehan syndrome; congenital **1 in 1000-1700**."],
        ["Pathophysiology", "Anti-TPO T-cell destruction -> falling T4 -> **TSH rises logarithmically** -> low BMR, **GAG deposition (myxoedema)**, low LDL-receptor (high LDL), raised TRH -> prolactin -> menstrual upset; pregnancy needs **25-50% more** T4."],
        ["Key history (OPD)", "Fatigue, cold intolerance, weight gain, constipation, menorrhagia, infertility, depression, hoarseness, carpal tunnel; **how levothyroxine is taken** (tea, calcium, iron, PPI); pregnancy plans; biotin; cardiac symptoms."],
        ["Key examination", "Puffy face, **loss of outer eyebrows**, **bradycardia**, diastolic hypertension, **delayed ankle-jerk relaxation**, non-pitting oedema, firm bosselated goitre; newborn - jaundice, macroglossia, umbilical hernia."],
        ["Minimal investigations", "**TSH first**, free T4 if abnormal; **anti-TPO once**; **repeat raised TSH in 6-12 weeks** before treating subclinical (in pregnancy confirm **within 3 weeks**); no T3; avoid testing in acute illness; newborn heel-prick TSH at **48-72 h**."],
        ["Diagnostic criteria", "Overt = high TSH + low FT4; subclinical marked if **TSH 10+**; central - FT4 low with inappropriate TSH; pregnancy - trimester-specific range, **about 0.1-4.0 if no local range** (ATA 2026)."],
        ["Treatment - first line", "**Levothyroxine 1.6 mcg/kg/day** (about 100 mcg for 60 kg), **empty stomach 30-60 min before breakfast**, 4 h from calcium/iron/PPI; **elderly or IHD 12.5-25 mcg**, up 12.5-25 mcg every 4-6 weeks; subclinical 25-50 mcg."],
        ["Escalation / second line", "Persistent high TSH on over 2 mcg/kg = **adherence or malabsorption** (coeliac, H. pylori) -> **supervised weekly dose**; **no routine T3 or combination**; central - titrate to FT4 upper-half, **cortisol before thyroxine**."],
        ["Devices / procedures", "Keep the same brand (recheck TSH 6-8 weeks after a switch); newborn - crush tablet in breast milk, not soy formula; myxoedema coma - IV levothyroxine or NG crushed tablets."],
        ["Special groups", "**Pregnancy**: +25-30% (**2 extra tablets/week**) once confirmed, **TSH within trimester range**, 4-weekly to 20 weeks; **TPOAb alone does not decide treatment**; over 70 - accept TSH 4-6, do not treat TSH under 10 (TRUST); **congenital 10-15 mcg/kg/day within 2 weeks**."],
        ["Complications", "**Myxoedema coma** (20-40% mortality), hyponatraemia, dyslipidaemia, infertility, low child IQ (untreated pregnancy), over-replacement - **AF and bone loss**; lymphoma in Hashimoto."],
        ["Red flags & referral", "Hypothermia + bradycardia + drowsiness (coma); new angina/AF on dose increase; **coexisting Addison** (hydrocortisone first); rapidly enlarging hard goitre; low FT4 with low TSH + visual field loss."],
        ["Follow-up & monitoring", "**TSH 6-8 weeks** after any change, then **6-12 monthly**; target **0.5-2.5** in most adults; untreated subclinical - TSH 6-12 monthly; pregnancy - **every 4 weeks to 20 weeks**, once at 30 weeks, 6 weeks postpartum."],
        ["Prevention / national programme", "**NIDDCP** - iodised salt **30 ppm at production, 15 ppm at consumer**; population sufficiency **median urinary iodine 100-199 mcg/L**; newborn TSH screening."],
        ["Latest guideline change", "**ATA 2026 pregnancy guideline**: targeted testing; **trimester-specific TSH range (0.1-4.0 default)** replaces 2.5/3.0 targets; **confirm mild abnormality within 3 weeks**; **no levothyroxine for euthyroid TPOAb-positive women with infertility or miscarriage**."],
        ["Exam one-liners", "TSH screens, FT4 confirms, T3 useless for diagnosis; **hydrocortisone before thyroxine** in coma or suspected adrenal failure; never check TSH earlier than 6 weeks after a change."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Raised TSH in the OPD - treat or watch",
        steps: [
          { label: "TSH raised: check free T4", detail: "Not during acute illness; stop biotin 48-72 h" },
          { label: "Free T4 low?", detail: "Overt - start levothyroxine 1.6 mcg/kg/day", tone: "decision" },
          { label: "Free T4 normal: repeat TSH in 6-12 weeks + anti-TPO", detail: "Up to a third normalise" },
          { label: "Persistent TSH 10 or more?", detail: "Treat - 25-50 mcg and titrate", tone: "decision" },
          { label: "TSH 4.5-9.9: pregnancy, planning, symptoms + TPOAb?", detail: "Consider treatment; over 70 - observe" },
          { label: "Recheck TSH 6-8 weeks; target 0.5-2.5", tone: "good" },
        ],
      },
      {
        kind: "flow",
        heading: "Thyroid in pregnancy - ATA 2026 condensed",
        steps: [
          { label: "Known hypothyroid: test positive pregnancy", detail: "Add 2 extra tablets a week the same day" },
          { label: "New abnormal TSH in pregnancy", detail: "Use trimester range; 0.1-4.0 if no local range", tone: "decision" },
          { label: "Overt with TSH 6 or more", detail: "Start levothyroxine without delay", tone: "warn" },
          { label: "Mild or subclinical", detail: "Confirm within 3 weeks, then consider 25-50 mcg" },
          { label: "TSH 4-weekly to 20 weeks, once at 30 weeks", detail: "Back to pre-pregnancy dose after delivery", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Myxoedema coma - order of treatment",
        steps: [
          { label: "ICU, airway, ventilate for hypercapnia", detail: "Avoid sedatives" },
          { label: "Hydrocortisone 100 mg IV 8-hourly first", detail: "Prevents precipitated adrenal crisis", tone: "warn" },
          { label: "Levothyroxine 200-400 mcg IV load", detail: "Then 50-100 mcg IV daily; lower if elderly or cardiac" },
          { label: "Passive rewarming, cautious sodium, dextrose", detail: "No active external rewarming" },
          { label: "Treat precipitant - antibiotics", tone: "good" },
        ],
      },
    ],
  },

  "endocrine-diabetic-emergencies": {
    checked: "2026-10",
    updated: [
      "Paediatric DKA fluids aligned to ISPAD 2022: 10-20 mL/kg isotonic crystalloid over 20-30 min for all, 20 mL/kg rapidly and repeated if shocked (previously stated as bolus only if shocked).",
    ],
    master: {
      heading: "Master revision table - DKA and HHS",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**DKA**: glucose **200+ or known diabetes**, **BHB 3.0+ mmol/L**, **pH under 7.3 and/or HCO3 under 18**; **HHS**: glucose **600+**, **effective osmolality over 300**, BHB under 3.0, pH 7.3+, HCO3 15+."],
        ["Relevant classification", "DKA **mild** pH 7.25-7.30 / HCO3 15-18; **moderate** 7.00-7.24 / 10-15; **severe** under 7.00 / under 10; **euglycaemic DKA** (glucose under 250, SGLT2i, pregnancy); mixed DKA-HHS in one third (ADA/EASD 2024)."],
        ["Aetiology & risk factors", "**Infection (30-50% in India)**, **insulin omission** (cost, fasting, fear), new type 1, MI, stroke, pancreatitis, steroids, **SGLT2i**, pregnancy; HHS - elderly type 2, dementia, poor fluid intake."],
        ["Pathophysiology", "Insulin lack + glucagon excess -> lipolysis -> FFA -> **CPT-1 open** -> ketoacids -> **high anion gap acidosis**; hyperglycaemia -> osmotic diuresis -> **5-7 L (DKA), 8-10 L (HHS)** loss; total body **K depleted** despite normal serum K."],
        ["Key history (OPD)", "Polyuria, thirst, weight loss; **vomiting, abdominal pain, breathlessness**; insulin omission; infection; SGLT2i/steroids; pregnancy; **facial pain, black nasal discharge** (mucormycosis); recurrent DKA - psychosocial."],
        ["Key examination", "ABC, **GCS**, dehydration, **Kussmaul breathing, fruity breath**, temperature (hypothermia = sepsis), infection source (chest, urine, feet, perineum), **nose/palate eschar**, focal signs, DVT."],
        ["Minimal investigations", "Capillary glucose, **blood BHB**, **venous gas**, Na, K, Cl, urea, creatinine; **anion gap**, **corrected Na (+1.6 per 100 mg/dL glucose over 100)**, **effective osmolality 2Na + glucose/18**; CBC, ECG, cultures, CXR; CT sinuses if mucor."],
        ["Diagnostic criteria", "As per **ADA/EASD 2024 D-K-A**; **resolution DKA: BHB under 0.6 + pH 7.3+ or HCO3 18+**; **HHS resolution: osmolality under 300, glucose under 250, urine 0.5 mL/kg/h, mentation normal**."],
        ["Treatment - first line", "**Fluid first**: 1-1.5 L crystalloid (balanced or 0.9% saline) in hour 1, then 250-500 mL/h; **K before insulin** (hold if under 3.5); **regular insulin IV 0.1 units/kg/h**; at glucose under 250 add **5-10% dextrose**, insulin 0.05 units/kg/h."],
        ["Escalation / second line", "**K under 3.5: KCl 10-20 mmol/h, no insulin**; K 3.5-5.0: 20-40 mmol/L; **bicarbonate only if pH under 7.0** (100 mmol over 2 h); phosphate only if under 1.0 mg/dL; **HHS insulin 0.05 units/kg/h** only once glucose stops falling with fluids."],
        ["Devices / procedures", "Syringe pump **50 units in 50 mL (1 unit/mL)**; no pump - **hourly IM regular insulin 0.1 units/kg**; SC rapid analogue for mild-moderate uncomplicated DKA; **basal insulin 1-2 h before stopping drip** (or early co-administration 0.15-0.3 units/kg)."],
        ["Special groups", "**Children**: 10-20 mL/kg over 20-30 min (20 mL/kg fast if shocked), deficit over 24-48 h, insulin **0.05-0.1 units/kg/h 1 h after fluids, no bolus**; elderly/HF/CKD - 250-500 mL boluses; **pregnancy** - DKA at lower glucose."],
        ["Complications", "**Hypokalaemia**, hypoglycaemia, rebound DKA (no basal overlap), fluid overload, **cerebral oedema (children, 4-12 h)**, osmotic demyelination, **thrombosis in HHS**, mucormycosis, ARDS."],
        ["Red flags & referral", "**ICU if pH under 7.0, HCO3 under 5, K under 3.5 on arrival, GCS under 12, SBP under 90, SpO2 under 92%, osmolality over 350**; headache + bradycardia + falling GCS (cerebral oedema); eschar."],
        ["Follow-up & monitoring", "Glucose and ketones **hourly**, gas and electrolytes **2-4 hourly**; review **within 1 week** of discharge; classify diabetes (C-peptide, GAD); avoid restarting SGLT2i after euglycaemic DKA."],
        ["Prevention / national programme", "**Sick-day rules**: never stop basal, ketones if glucose over 250, extra 10-20% TDD rapid insulin, 100-200 mL fluid hourly; ketone strips at home; free insulin via **NP-NCD**; counselling for recurrent omission."],
        ["Latest guideline change", "No adult change in 2026 - **ADA/EASD 2024 consensus** stands (glucose 200 or known diabetes, BHB 3.0, **hold insulin if K under 3.5**, balanced crystalloid acceptable); paediatric fluids per **ISPAD 2022** bolus over 20-30 min."],
        ["Exam one-liners", "**Fluid first, potassium before insulin, then 0.1 units/kg/h**; never stop insulin because glucose is normal; resolution is by ketones and pH; **bicarbonate only if pH under 7.0**; HHS - correct osmolality by 3-8 mOsm/kg/h."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "DKA in the first six hours - exam version",
        steps: [
          { label: "Confirm D-K-A: glucose, BHB, venous gas", detail: "BHB 3.0+, pH under 7.3 or HCO3 under 18" },
          { label: "Crystalloid 1-1.5 L in hour 1", detail: "Then 250-500 mL/h; smaller boluses if elderly or HF" },
          { label: "Potassium result?", detail: "Under 3.5: KCl 10-20 mmol/h, hold insulin", tone: "decision" },
          { label: "Fixed-rate regular insulin 0.1 units/kg/h", detail: "Glucose fall 50-75/h; ketones fall 0.5/h" },
          { label: "Glucose under 250: add dextrose", detail: "Insulin 0.05 units/kg/h; keep glucose 150-200" },
          { label: "pH under 7.0, GCS under 12 or shock?", detail: "ICU; bicarbonate only if pH under 7.0", tone: "warn" },
          { label: "BHB under 0.6 and pH 7.3+: basal SC, stop drip 1-2 h later", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "DKA, HHS and euglycaemic DKA",
        columns: ["Feature", "DKA", "HHS", "Euglycaemic DKA"],
        rows: [
          ["Glucose", "200+ or known diabetes", "600+", "Under 250"],
          ["Ketones (BHB)", "3.0+", "Under 3.0", "3.0+"],
          ["pH / HCO3", "Under 7.3 / under 18", "7.3+ / 15+", "Under 7.3 / under 18"],
          ["Typical setting", "Type 1, insulin omission", "Elderly type 2, sepsis", "SGLT2i, pregnancy, starvation"],
          ["Insulin", "0.1 units/kg/h", "0.05 units/kg/h after fluids", "Insulin plus dextrose from start"],
        ],
      },
      {
        kind: "ladder",
        heading: "Potassium replacement by level",
        steps: [
          { label: "K above 5.0", detail: "No potassium; recheck in 2 hours" },
          { label: "K 3.5-5.0", detail: "20-40 mmol KCl per litre of fluid; keep K 4-5" },
          { label: "K under 3.5", detail: "Hold insulin; KCl 10-20 mmol/h with cardiac monitor", tone: "warn" },
        ],
      },
    ],
  },

  "endocrine-hyperthyroidism-nodule": {
    checked: "2026-10",
    updated: [
      "ATA 2026 (pregnancy): women on carbimazole switch to PTU once actively trying to conceive; PTU up to about 16 weeks, after which no antithyroid drug is preferred (old advice to switch to carbimazole in the second trimester dropped); TRAb titres guide stopping.",
    ],
    master: {
      heading: "Master revision table - hyperthyroidism and thyroid nodule",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Thyrotoxicosis** = excess hormone action; **hyperthyroidism** = excess synthesis; overt - **suppressed TSH + high FT4/FT3**; subclinical - low TSH, normal FT4/FT3 (under 0.1 or 0.1-0.4); **nodule** - discrete lesion, 5-10% malignant."],
        ["Relevant classification", "**By uptake**: high - Graves, toxic MNG, toxic adenoma, hCG; low - subacute, painless, post-partum thyroiditis, exogenous, amiodarone type 2; nodule - **ACR TI-RADS TR1-5** and **Bethesda I-VI (3rd ed 2023)**."],
        ["Aetiology & risk factors", "**Graves 60-80%** (women, smoking, TRAb), toxic MNG (elderly, iodine-deficient areas), amiodarone, iodine contrast, post-partum; nodule cancer risk - **neck irradiation, family history, MEN2**, male, extremes of age."],
        ["Pathophysiology", "**TRAb stimulate TSH receptor** -> hyperplasia + hormone excess -> Na-K-ATPase, thermogenesis -> weight loss, heat intolerance; **beta-1 upregulation** -> tachycardia, AF; orbital fibroblasts (**IGF-1R**) -> GAG + fat -> proptosis."],
        ["Key history (OPD)", "**Weight loss despite good appetite**, palpitation, tremor, heat intolerance, loose stools; eye symptoms (**diplopia, dull colour vision**); neck pain/viral illness; delivery in last year; drugs (amiodarone, iodine); smoking; asthma before beta-blocker."],
        ["Key examination", "Pulse (AF, sleeping rate), **fine tremor, warm moist palms**, proximal myopathy, **lid lag (any cause) vs proptosis (Graves)**, **CAS 3+/7 = active TED**, acuity and colour vision, diffuse goitre with bruit, pretibial myxoedema, nodes, Pemberton sign."],
        ["Minimal investigations", "**TSH + FT4 + FT3**; **TRAb** (best aetiological test); Tc-99m uptake scan if TRAb negative or nodular (not in pregnancy); ESR, thyroglobulin; **baseline CBC, LFT**; ECG; nodule - **TSH first, then ultrasound TI-RADS, US-guided FNAC**."],
        ["Diagnostic criteria", "Graves - thyrotoxicosis + **TRAb positive** or diffuse uptake or orbitopathy; FNA thresholds - **TR5 1 cm+, TR4 1.5 cm+, TR3 2.5 cm+**; **hot nodule - no FNA**; Bethesda ROM - II 4%, IV 30%, VI 97%."],
        ["Treatment - first line", "**Carbimazole 15-40 mg once daily**, taper to **5-10 mg**, total **12-18 months** (remission about 50%); **propranolol 10-40 mg TDS-QDS** (diltiazem in asthma); subacute thyroiditis - **NSAID or prednisolone 40 mg**, no thionamide."],
        ["Escalation / second line", "Relapse, toxic MNG/adenoma - **radioiodine 10-15 mCi** (stop carbimazole 3-5 days before; steroid cover if mild eye disease) or **thyroidectomy** (Lugol 5-7 drops TDS for 10 days pre-op); **PTU 50-150 mg TDS** only in early pregnancy, storm or carbimazole intolerance."],
        ["Devices / procedures", "**US-guided FNAC** reported by Bethesda; **radioiodine** single oral dose; moderate-severe active TED - **IV methylprednisolone 0.5 g weekly x6 then 0.25 g x6 (4.5 g)** + mycophenolate; optic neuropathy - 0.5-1 g x3 days then decompression."],
        ["Special groups", "**Pregnancy (ATA 2026)**: GTT needs no drug; **switch carbimazole to PTU when trying to conceive**, **PTU to about 16 weeks, no preferred drug after**; FT4 at upper normal; no radioiodine; lactation - carbimazole up to 30 mg; elderly - apathetic thyrotoxicosis, AF."],
        ["Complications", "**Thyroid storm**, AF and high-output HF, osteoporosis, **agranulocytosis (0.2-0.5%)**, PTU hepatic necrosis, carbimazole embryopathy, **sight-threatening TED**, periodic paralysis, post-ablation hypothyroidism."],
        ["Red flags & referral", "Fever + delirium + tachycardia (storm - **Burch-Wartofsky 45+**); **sore throat on thionamide - same-day count**; jaundice on PTU; dull colour vision (optic neuropathy); stridor or rapidly growing hard mass; nodule in child or MEN2."],
        ["Follow-up & monitoring", "**FT4/FT3 4-6 weeks** after each change (**TSH stays suppressed for months**), then 2-3 monthly; **TRAb before stopping** (normal predicts remission); Bethesda II - ultrasound at 12-24 months."],
        ["Prevention / national programme", "**Stop smoking** (orbitopathy); written agranulocytosis warning; avoid iodine loads; iodised salt under NIDDCP (iodine-induced thyrotoxicosis in old MNG after iodisation)."],
        ["Latest guideline change", "**ATA 2026 pregnancy guideline**: PTU from preconception (trying to conceive) to about 16 weeks; **no preferred ATD after 16 weeks**; TRAb titres guide discontinuation; ATA 2025 DTC guideline adopts DATA framework for cancer care."],
        ["Exam one-liners", "Lid lag in any thyrotoxicosis, proptosis only in Graves; **storm - thionamide first, iodine 1 h later, paracetamol not aspirin**; hot nodule almost never cancer; follicular carcinoma needs histology (Bethesda IV to lobectomy)."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Low TSH - find the cause in three steps",
        steps: [
          { label: "Suppressed TSH: measure FT4 and FT3", detail: "Raised FT3 alone = T3 toxicosis" },
          { label: "TRAb positive or orbitopathy?", detail: "Graves - carbimazole + propranolol", tone: "decision" },
          { label: "TRAb negative: uptake scan", detail: "Not in pregnancy or lactation", tone: "decision" },
          { label: "High or patchy uptake", detail: "Toxic MNG or adenoma - radioiodine or surgery" },
          { label: "Low uptake", detail: "Thyroiditis or exogenous - beta-blocker, NSAID; no thionamide", tone: "warn" },
          { label: "Euthyroid on treatment; plan definitive therapy if relapse", tone: "good" },
        ],
      },
      {
        kind: "flow",
        heading: "Thyroid nodule - TSH, ultrasound, FNAC",
        steps: [
          { label: "Palpable or incidental nodule: TSH first", detail: "Low TSH - uptake scan; hot nodule needs no FNA", tone: "decision" },
          { label: "Normal or high TSH: ultrasound with TI-RADS", detail: "Echogenicity, shape, margins, foci" },
          { label: "Size above TI-RADS threshold?", detail: "TR5 1 cm, TR4 1.5 cm, TR3 2.5 cm", tone: "decision" },
          { label: "US-guided FNAC - Bethesda report", detail: "I repeat; II follow-up; III-IV molecular or lobectomy" },
          { label: "Bethesda V-VI", detail: "Surgery - lobectomy or total thyroidectomy", tone: "warn" },
        ],
      },
      {
        kind: "ladder",
        heading: "Thyroid storm - drug order",
        steps: [
          { label: "Block synthesis: PTU 500-1000 mg then 250 mg 4-hourly", detail: "Or methimazole 60-80 mg/day" },
          { label: "Block release 1 h later: SSKI 5 drops 6-hourly", detail: "Or Lugol 8-10 drops 6-8 hourly", tone: "warn" },
          { label: "Block adrenergic effect: propranolol 60-80 mg 4-hourly", detail: "Esmolol infusion in heart failure" },
          { label: "Hydrocortisone 300 mg IV then 100 mg 8-hourly", detail: "Plus cholestyramine 4 g QDS" },
          { label: "ICU, cooling, paracetamol, treat precipitant", detail: "Never aspirin", tone: "good" },
        ],
      },
    ],
  },

  "endocrine-obesity-metabolic-syndrome": {
    checked: "2026-10",
    updated: [
      "2025 Indian redefinition (Misra, Diabetes Metab Syndr 2025): BMI above 23 = obesity; stage 1 (no functional or metabolic effect) and stage 2 (plus waist 90/80 cm or WHtR above 0.5 plus comorbidity or functional limitation); citation corrected from Lancet D and E.",
      "Multisociety 2024 GLP-1 RA peri-operative guidance: shared decision-making, most continue; hold weekly agents 1 week only when aspiration risk is high; 24-hour liquid diet when delayed emptying is a concern.",
    ],
    master: {
      heading: "Master revision table - obesity and metabolic syndrome",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Excess adiposity impairing health; **Asian Indian 2025 redefinition: BMI above 23 = obesity** (2009: overweight 23-24.9, obesity 25+); abdominal obesity **waist 90 cm men, 80 cm women**, WHtR over 0.5."],
        ["Relevant classification", "**Indian stage 1** (BMI over 23, no dysfunction) vs **stage 2** (BMI over 23 + waist/WHtR + comorbidity or functional limitation); **Lancet Commission 2025**: preclinical vs clinical obesity; **metabolic syndrome - any 3 of 5** (harmonised) or IDF (waist mandatory + 2)."],
        ["Aetiology & risk factors", "Energy-dense diet, sedentary life, short sleep, **thin-fat phenotype**, drugs (olanzapine, valproate, steroids, insulin, SU, pioglitazone), hypothyroidism, Cushing, PCOS, **MC4R** mutations; 30-35% urban metabolic syndrome."],
        ["Pathophysiology", "Positive energy balance -> **visceral fat** -> portal FFA -> hepatic and muscle **insulin resistance** -> hyperinsulinaemia -> high TG, low HDL, small dense LDL, BP rise; adipose inflammation (TNF-alpha, IL-6, low adiponectin); **leptin resistance**."],
        ["Key history (OPD)", "Weight history, **24-h diet recall** (cereal, oil, sugar), activity and sitting time, sleep/snoring, binge eating and mood, **weight-gaining drugs**, endocrine symptoms, comorbidities, herbal fat-cutters, readiness to change."],
        ["Key examination", "Weight, height, **BMI**, **waist midway rib-iliac crest**, WHtR, **BP with large cuff**, acanthosis nigricans, skin tags, hirsutism, Cushing signs (striae over 1 cm), neck circumference over 40 cm, **STOP-BANG**, liver, knees."],
        ["Minimal investigations", "**FPG or HbA1c**, fasting lipids, **ALT + FIB-4 (over 1.3 - elastography)**, eGFR + ACR if HTN/DM, TSH if symptoms; 1 mg DST only with Cushing features; sleep study if OSA suspected."],
        ["Diagnostic criteria", "Metabolic syndrome any 3: **waist 90/80**, **TG 150+**, **HDL under 40 (M) / 50 (F)**, **BP 130/85+**, **FPG 100+** (or treated); obesity stage 2 requires BMI over 23 + abdominal marker + comorbidity/limitation."],
        ["Treatment - first line", "**5-10% loss over 6 months**; deficit **500-750 kcal/day**; ICMR-NIN My Plate, oil 3-4 tsp, sugar under 25 g; **150-300 min/week aerobic + resistance 2-3 days**; protein 0.8-1.2 g/kg; behavioural programme."],
        ["Escalation / second line", "Drugs at **BMI 25+ with comorbidity or 27+** (Asian): **semaglutide 0.25 -> 2.4 mg weekly** (about 15% loss, SELECT -20% MACE), **tirzepatide 2.5 -> 5-15 mg weekly** (about 20%), liraglutide 3 mg daily, **orlistat 120 mg TDS**; stop if under 5% at 3 months on full dose."],
        ["Devices / procedures", "Weekly pens - same day, 90 degrees, hold 6-10 s; **metabolic surgery from BMI 27.5 in Asians** (35+ any, 30-34.9 with disease) - sleeve 25-30%, RYGB 30-35% loss; **peri-op GLP-1 - shared decision, 24-h liquid diet if risk**."],
        ["Special groups", "**Pregnancy** - no anti-obesity drugs, stop semaglutide 2 months before conception; children - family lifestyle, semaglutide/liraglutide from 12, IAP 2015 BMI charts; older adults - **sarcopenic obesity**, protect muscle."],
        ["Complications", "Type 2 diabetes, HTN, dyslipidaemia, **MASLD/MASH**, OSA, PCOS, knee OA, GERD, CVD, cancers; drug - GI upset, gallstones, pancreatitis, lean-mass loss; surgery - leak, dumping, deficiencies, **Wernicke**."],
        ["Red flags & referral", "Cushing features; severe OSA; post-bariatric tachycardia/fever (leak); confusion after vomiting (thiamine first); pancreatitis on GLP-1 RA; hidden sibutramine/thyroxine in herbal products; severe early-onset childhood obesity."],
        ["Follow-up & monitoring", "**Monthly for 3-6 months**, then 3-monthly - weight, waist, BP; yearly glucose, lipids, ALT; on GLP-1 RA watch GI, gallbladder, hypoglycaemia (reduce SU/insulin); maintenance **200-300 min/week** activity; long-term drug plan."],
        ["Prevention / national programme", "**NP-NCD** screening at Ayushman Arogya Mandir, **Fit India**, **Eat Right India**, ICMR-NIN dietary guidelines 2024; non-stigmatising language."],
        ["Latest guideline change", "**2025 Indian redefinition - BMI above 23 is obesity, staged 1-2** with waist/WHtR and comorbidity; **Multisociety 2024** peri-operative GLP-1 RA guidance (continue in most, liquid diet 24 h if risk); ADA 2026 - individualise obesity drug doses."],
        ["Exam one-liners", "Quote Asian cut-offs, not 25/30; **waist beats BMI in Indians**; no single drug for metabolic syndrome - treat each component; 5% loss improves glucose, BP, TG and liver fat; thiamine before glucose after bariatric vomiting."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Diagnosing and staging obesity in an Indian adult",
        steps: [
          { label: "Measure BMI, waist and waist-height ratio", detail: "Every visit; large BP cuff" },
          { label: "BMI above 23?", detail: "Obesity (2025 redefinition)", tone: "decision" },
          { label: "Waist 90/80 cm or WHtR over 0.5?", detail: "Abdominal adiposity marker", tone: "decision" },
          { label: "Comorbidity or functional limitation?", detail: "Diabetes, HTN, dyslipidaemia, OSA, MASLD, knee OA" },
          { label: "Yes - stage 2: intensive lifestyle plus drugs", detail: "Consider surgery at Asian thresholds", tone: "warn" },
          { label: "No - stage 1: lifestyle and yearly screening", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Treatment intensity by Asian BMI",
        steps: [
          { label: "Lifestyle for all with BMI over 23 or high waist", detail: "500-750 kcal deficit; 150-300 min/week" },
          { label: "Add drug: BMI 25+ with comorbidity or 27+", detail: "Semaglutide to 2.4 mg or tirzepatide 5-15 mg weekly; orlistat 120 mg TDS" },
          { label: "Stop or switch if under 5% loss at 3 months", detail: "At full maintenance dose" },
          { label: "Metabolic surgery from BMI 27.5 (Asian)", detail: "Sleeve or Roux-en-Y bypass; lifelong supplements", tone: "warn" },
        ],
      },
      {
        kind: "compare",
        heading: "Metabolic syndrome definitions",
        columns: ["Criterion", "Harmonised 2009 (any 3 of 5)", "IDF 2006"],
        rows: [
          ["Waist (South Asian)", "90 cm men, 80 cm women", "Mandatory"],
          ["Triglyceride", "150 mg/dL or more", "Any 2 of the 4"],
          ["HDL", "Under 40 men, under 50 women", "Any 2 of the 4"],
          ["BP", "130/85 or more", "Any 2 of the 4"],
          ["Fasting glucose", "100 mg/dL or more", "Any 2 of the 4"],
        ],
      },
    ],
  },

  "endocrine-vitamin-d-calcium": {
    checked: "2026-10",
    updated: [
      "Endocrine Society 2023 hypercalcaemia of malignancy guideline: denosumab (slight preference) or IV bisphosphonate; for calcium above 14 mg/dL start calcitonin together with bisphosphonate or denosumab.",
    ],
    master: {
      heading: "Master revision table - vitamin D deficiency and calcium disorders",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**25(OH)D under 20 ng/mL = deficiency**, **under 12 severe**, 20-29 insufficiency, 30-100 sufficient; hypocalcaemia **corrected Ca under 8.5**, hypercalcaemia **over 10.5** (mild under 12, moderate 12-14, **severe over 14 mg/dL**)."],
        ["Relevant classification", "Rickets (growth plate) vs **osteomalacia** (mature bone); calcium-deficiency vs vitamin D-deficiency rickets; hypercalcaemia **PTH-dependent** (PHPT, FHH) vs **PTH-independent** (malignancy, vitamin D, granuloma, milk-alkali)."],
        ["Aetiology & risk factors", "Indoor life, pigmented skin, veiling, vegetarian diet, **calcium intake 300-500 mg/day**, obesity, malabsorption, **enzyme inducers**, CKD, liver disease; PHPT - **single adenoma 80-85%**; repeated mega-dose injections (toxicity)."],
        ["Pathophysiology", "Low D -> low gut Ca absorption -> **PTH rises first** -> phosphaturia (low PO4) -> high ALP -> **unmineralised osteoid** -> bone pain, Looser zones; Ca falls late; **low Mg blocks PTH secretion and action**."],
        ["Key history (OPD)", "Diffuse bone pain, **proximal weakness**, sun and diet, drugs (antiepileptics, rifampicin, steroids, PPIs, thiazides, lithium), malabsorption, CKD; hypocalcaemia - **perioral tingling, spasm, recent thyroidectomy**; hypercalcaemia - **stones, bones, groans, moans**."],
        ["Key examination", "Bone tenderness, **waddling gait**, chair rise; child - wrist widening, **rachitic rosary**, bow legs, craniotabes; **Trousseau sign (specific) over Chvostek**; thyroidectomy scar; band keratopathy; neck mass, breast lump, nodes."],
        ["Minimal investigations", "**Ca + albumin, PO4, ALP, creatinine, Mg**; **25(OH)D (not 1,25)** only if symptomatic or high risk (**no routine testing - ES 2024**); **PTH on same sample as Ca**; 24-h urine Ca (**Ca/Cr clearance under 0.01 = FHH**); wrist X-ray; ECG; SPEP if PTH suppressed."],
        ["Diagnostic criteria", "**Corrected Ca = Ca + 0.8 x (4 - albumin)**; PHPT - high Ca with **high or inappropriately normal PTH**; malignancy/vitamin D - **PTH suppressed**; osteomalacia - low/normal Ca, low PO4, high ALP, high PTH."],
        ["Treatment - first line", "**Cholecalciferol 60,000 IU weekly x 8 weeks** with fatty meal, then **60,000 IU monthly or 1000-2000 IU daily** (ES 2024 prefers daily); **elemental calcium 500 mg once-twice daily** (carbonate with meals, citrate on PPI); sun 15-30 min."],
        ["Escalation / second line", "Symptomatic hypocalcaemia - **10% calcium gluconate 10-20 mL over 10-20 min**, then 100 mL in 1 L D5 at 50-100 mL/h; **MgSO4 2 g IV** if low; hypercalcaemia - **saline 200-300 mL/h**, **denosumab or zoledronic acid 4 mg**, calcitonin 4 IU/kg 12-hourly if over 14."],
        ["Devices / procedures", "Neck ultrasound + **sestamibi/4D-CT** only after biochemical PHPT and decision to operate; **parathyroidectomy** criteria (Ca 1+ above ULN, T-score -2.5, eGFR under 60, stones, age under 50); haemodialysis for crisis with renal failure."],
        ["Special groups", "Infants **400 IU daily from birth**; rickets **2000-6000 IU daily x 12 weeks + calcium 500 mg**; pregnancy - **calcium 500 mg BD from 14 weeks** (national programme); hypoparathyroidism - calcium + **calcitriol 0.25-1 mcg BD**, Ca low-normal; CKD - calcitriol."],
        ["Complications", "Fractures, deformity, myopathy, **hypocalcaemic seizures/laryngospasm, long QT**; hypercalcaemia - nephrogenic DI, AKI, stones, **short QT**, coma; **vitamin D toxicity** from mega-dose injections; hypocalcaemia after zoledronic acid if D-deficient."],
        ["Red flags & referral", "Tetany, stridor, seizure; hypocalcaemia refractory (check Mg); **Ca over 14 or confusion - admit**; PTH-suppressed hypercalcaemia (myeloma, cancer); post-thyroidectomy tingling within 72 h; rickets not healing in 3 months."],
        ["Follow-up & monitoring", "Ca at 1 month on high doses; **25(OH)D and ALP at 3 months**, no routine rechecks; calcitriol - Ca weekly then 3-6 monthly; asymptomatic PHPT - **Ca, creatinine yearly, DXA 1-2 yearly**."],
        ["Prevention / national programme", "Sun exposure, dietary calcium (milk, curd, **ragi**, sesame), **ICMR-NIN 1000 mg/day**; infant vitamin D; **calcium in pregnancy under MoHFW**; avoid 6 lakh IU injections."],
        ["Latest guideline change", "**ES 2024**: no routine testing or target level in healthy adults; empiric D for ages 1-18, over 75, pregnancy, prediabetes; **ES 2023 hypercalcaemia of malignancy**: denosumab slightly preferred, add calcitonin if Ca over 14."],
        ["Exam one-liners", "Measure 25(OH)D not 1,25; normal Ca does not exclude deficiency; **Indian rickets is often calcium-deficiency**; refractory hypocalcaemia - check Mg; FHH never operated; saline first, furosemide only for overload."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "High calcium - the PTH fork",
        steps: [
          { label: "Correct calcium for albumin; repeat", detail: "Ca + 0.8 x (4 - albumin)" },
          { label: "Ca over 14 or confused, vomiting, dehydrated?", detail: "Admit: saline, calcitonin, denosumab or zoledronic acid", tone: "warn" },
          { label: "Intact PTH on the same sample", detail: "The single deciding test", tone: "decision" },
          { label: "PTH high or inappropriately normal", detail: "PHPT - check 24-h urine Ca to exclude FHH" },
          { label: "PTH suppressed", detail: "Malignancy (PTHrP, myeloma), vitamin D, granuloma", tone: "decision" },
          { label: "Treat cause; surgery for PHPT meeting criteria", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Vitamin D and calcium replacement ladder",
        steps: [
          { label: "Prevention", detail: "Sun 15-30 min; dietary calcium 1000 mg; infants 400 IU daily" },
          { label: "Maintenance / insufficiency", detail: "1000-2000 IU daily or 60,000 IU monthly" },
          { label: "Deficiency", detail: "60,000 IU weekly x 8 weeks + elemental Ca 500 mg OD-BD" },
          { label: "Malabsorption, obesity, enzyme inducers", detail: "6000-10,000 IU daily initially" },
          { label: "Failed renal activation (hypopara, CKD)", detail: "Calcitriol 0.25-1 mcg OD-BD; weekly Ca at start", tone: "warn" },
        ],
      },
      {
        kind: "compare",
        heading: "Biochemistry of bone disease at a glance",
        columns: ["Condition", "Ca", "PO4", "ALP", "PTH"],
        rows: [
          ["Vitamin D deficiency", "Low/normal", "Low", "High", "High"],
          ["Primary hyperparathyroidism", "High", "Low/normal", "Normal/high", "High"],
          ["Hypoparathyroidism", "Low", "High", "Normal", "Low"],
          ["Malignancy", "High", "Variable", "High if bone mets", "Suppressed"],
          ["Osteoporosis", "Normal", "Normal", "Normal", "Normal"],
        ],
      },
    ],
  },

  "endocrine-adrenal-disorders": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - Cushing syndrome and adrenal insufficiency",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Cushing syndrome** = chronic glucocorticoid excess (mostly **iatrogenic**); **adrenal insufficiency** = deficient cortisol; **adrenal crisis** = shock in AI resolving within 1-2 h of parenteral hydrocortisone."],
        ["Relevant classification", "Cushing: exogenous vs endogenous - **ACTH-dependent** (pituitary 70%, ectopic 10%) or **ACTH-independent** (adenoma, carcinoma); AI: **primary** (Addison), **secondary** (pituitary), **tertiary** (commonest - **steroid withdrawal**)."],
        ["Aetiology & risk factors", "Depot steroid injections, herbal powders, potent topical steroids; Addison in India - **TB** and autoimmunity, HIV; GI-AI after **prednisolone 5 mg+ for 4 weeks+**; rifampicin and other CYP3A4 inducers."],
        ["Pathophysiology", "Exogenous steroid -> CRH/ACTH suppressed -> **fasciculata atrophy** -> AI on withdrawal; primary AI -> low cortisol -> **high ACTH/MSH -> pigmentation** + aldosterone loss -> **low Na, high K**; Cushing - catabolism -> **striae, bruising, myopathy**."],
        ["Key history (OPD)", "**Full steroid history** (oral, depot, inhaled, topical, herbal); Cushing - weight gain, bruising, weakness, fractures, new DM/HTN; AI - fatigue, anorexia, weight loss, vomiting, **salt craving**, postural dizziness; TB; autoimmunity; Sheehan."],
        ["Key examination", "Cushing discriminators - **purple striae over 1 cm, easy bruising, facial plethora, proximal myopathy**; AI - **postural BP fall over 20**, **pigmentation of creases and buccal mucosa (primary only)**, vitiligo; child - falling height, rising weight."],
        ["Minimal investigations", "Cushing: exclude exogenous, then **two of - 1 mg DST (8 a.m. cortisol over 1.8 mcg/dL), late-night salivary cortisol x2, 24-h UFC x2**, then ACTH; AI: **8-9 a.m. cortisol + ACTH** - under 3-5 diagnostic, over 15-18 excludes; electrolytes, glucose."],
        ["Diagnostic criteria", "**Short synacthen 250 mcg - peak under 18 mcg/dL (500 nmol/L)** confirms AI (14-15 with newer assays); **high ACTH = primary**, low/normal = secondary/tertiary; GI-AI recovery - **morning cortisol over 10 mcg/dL** after 24-h hold."],
        ["Treatment - first line", "**Hydrocortisone 15-25 mg/day in 2-3 doses (10-5-5)** or **prednisolone 3-5 mg** daily; **fludrocortisone 50-100 mcg** in primary only; **steroid card, emergency 100 mg IM kit, sick-day rules**."],
        ["Escalation / second line", "Sick day - **double/triple dose** for fever; vomiting - **hydrocortisone 100 mg IM** and hospital; major surgery - **100 mg IV at induction then 200 mg/24 h**; rifampicin - **double hydrocortisone**; Cushing - **surgery**, metyrapone/ketoconazole/osilodrostat bridge."],
        ["Devices / procedures", "Short synacthen test (0, 30/60 min); **transsphenoidal surgery** or adrenalectomy for Cushing; **adrenal vein sampling** for primary aldosteronism; pheochromocytoma - **alpha blockade 10-14 days before surgery**."],
        ["Special groups", "**Pregnancy** - increase hydrocortisone **20-40% in third trimester**, stress cover in labour; **children** 8 mg/m2/day; **CAH** - hydrocortisone 10-15 mg/m2/day + fludrocortisone + salt; neonatal salt-wasting crisis - **hydrocortisone 25 mg IV**."],
        ["Complications", "**Adrenal crisis**, hypoglycaemia, hyponatraemia; Cushing - diabetes, hypertension, osteoporosis, infections, VTE; over-replacement - weight gain, diabetes, bone loss; HPA suppression after Cushing cure (6-18 months)."],
        ["Red flags & referral", "**Shock unresponsive to fluids in a steroid user - hydrocortisone 100 mg IV now**; vomiting on replacement; acute-abdomen mimic in Addison; abrupt stop of long-term steroid; ectopic ACTH (rapid hypokalaemia); adrenal mass over 4 cm or over 20 HU."],
        ["Follow-up & monitoring", "Replacement review **6-12 monthly** - weight, lying/standing BP, electrolytes, glucose, kit expiry (**clinical titration - no blood test**); autoimmune Addison - yearly TSH, glucose, B12, coeliac; post-Cushing - recurrence screen yearly."],
        ["Prevention / national programme", "Lowest effective steroid dose, **never stop abruptly**, taper to physiological dose; educate against unregulated steroids and skin-lightening creams; screen TB before long steroids; bone protection at 7.5 mg for 3 months+."],
        ["Latest guideline change", "No change needed in 2026 - **ESE/ES 2024** glucocorticoid-induced AI (taper to physiological dose, morning cortisol over 10 = recovered, under 5 = continue) and **ES 2025** primary aldosteronism (screen all hypertensives) already reflected."],
        ["Exam one-liners", "**Treat crisis first, test later**; pigmentation and hyperkalaemia = primary AI (only primary needs fludrocortisone); Cushing needs **two abnormal tests**; rifampicin doubles hydrocortisone need; alpha before beta in phaeochromocytoma."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Suspected adrenal insufficiency in the OPD",
        steps: [
          { label: "Fatigue, weight loss, postural fall, low Na", detail: "Ask every steroid exposure first" },
          { label: "Unwell, hypotensive or vomiting?", detail: "Hydrocortisone 100 mg IV/IM now - test later", tone: "warn" },
          { label: "Stable: 8-9 a.m. cortisol with paired ACTH", detail: "Under 3-5 diagnostic; over 15-18 excludes", tone: "decision" },
          { label: "Indeterminate: short synacthen 250 mcg", detail: "Peak under 18 mcg/dL confirms" },
          { label: "ACTH high: primary - renin, TB work-up, CT", detail: "Add fludrocortisone 50-100 mcg" },
          { label: "Hydrocortisone 15-25 mg/day, card, kit, sick-day rules", tone: "good" },
        ],
      },
      {
        kind: "flow",
        heading: "Suspected Cushing syndrome",
        steps: [
          { label: "Discriminating signs: striae over 1 cm, bruising, myopathy", detail: "Obesity and HTN alone do not discriminate" },
          { label: "Exogenous steroid excluded?", detail: "Depot, topical, herbal - if yes, no tests; taper", tone: "decision" },
          { label: "Two different screening tests", detail: "1 mg DST over 1.8 mcg/dL, LNSC x2, UFC x2" },
          { label: "8-9 a.m. ACTH", detail: "Suppressed - adrenal CT; normal/high - pituitary MRI, IPSS", tone: "decision" },
          { label: "Surgery; hydrocortisone cover after cure", detail: "Metyrapone or osilodrostat as bridge", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Primary versus secondary adrenal insufficiency",
        columns: ["Feature", "Primary (Addison)", "Secondary / tertiary"],
        rows: [
          ["ACTH", "High", "Low or normal"],
          ["Pigmentation", "Present", "Absent (pale)"],
          ["Potassium", "High", "Normal"],
          ["Aldosterone", "Low (high renin)", "Preserved"],
          ["Fludrocortisone", "Needed", "Not needed"],
          ["Commonest cause in India", "TB, autoimmune", "Steroid withdrawal"],
        ],
      },
    ],
  },
};

export default revision;
