import type { RevisionSet } from "./index";

const revision: RevisionSet = {
  "eye-ent-red-eye": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - The red eye",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Visible dilatation of **conjunctival, episcleral or ciliary vessels**; the layer that is dilated names the diagnosis. Split: **red eye with normal vision and no true pain** (OPD) versus **red eye with reduced vision, pain or photophobia** (refer)."],
        ["Relevant classification", "By injection: **conjunctival** (fornices, blanches), **ciliary/circumcorneal** (limbus - cornea, iris, ciliary body), mixed. Conjunctivitis by cause (bacterial, viral, chlamydial, allergic, toxic); uveitis by **SUN** anatomy; ophthalmia neonatorum = first 28 days; trachoma WHO simplified grading (India **eliminated 2024**)."],
        ["Aetiology and risk factors", "About **80% of GP red eyes are conjunctivitis**; contact lens wear (Pseudomonas, Acanthamoeba), **vegetative trauma** (fungal), OTC **steroid-antibiotic drops**, hypermetropic elderly eye + dim light/anticholinergic/topiramate (angle closure), HLA-B27, RA/GPA (scleritis), recent surgery (endophthalmitis)."],
        ["Pathophysiology", "Surface inflammation -> conjunctival vessels, grittiness, discharge; corneal epithelial loss -> **trigeminal pain, fluorescein uptake**; iris/ciliary inflammation -> **trigemino-ciliary photophobia**, flare, KPs, synechiae; pupil block -> iris bombe -> **IOP 40-80 mmHg** -> corneal oedema, fixed mid-dilated pupil, vomiting."],
        ["Key history (OPD)", "**Five questions**: blurred vision, true pain vs grittiness, discharge type, photophobia, one or both eyes. Itch = allergy; purulent stuck lids = bacterial; watery + URTI + node = adenovirus. Ask contact lens, vegetative trauma, drops used, haloes/vomiting, back pain, recent surgery, neonate day of onset."],
        ["Key examination", "**Visual acuity first** with pinhole; torch exam; **oblique shadow test** before dilating; evert upper lid; **fluorescein + cobalt blue** (dendrite = HSV); pupil shape/RAPD; **digital tension**; preauricular node; **phenylephrine 2.5% blanching** (episcleritis vs scleritis); red reflex; BP, joints, skin."],
        ["Minimal investigations", "**Simple conjunctivitis - no test**. Swab Gram stain/culture/chlamydia NAAT in neonates (**Gram-negative intracellular diplococci** = treat same day); corneal scrape + **KOH** before drops; tonometry (**over 40 mmHg** in attack); recurrent uveitis: HLA-B27, CXR, IGRA, VDRL; scleritis: RF, anti-CCP, ANCA."],
        ["Treatment - first line", "Bacterial: **chloramphenicol 0.5% 2-hourly x 48 h then QID + 1% ointment at night, 5 days**; lens wearer: **moxifloxacin 0.5% TDS 7 days**. Adenovirus: preservative-free lubricant, cold compress, no antibiotic. Allergic: **olopatadine 0.1% BD** or ketotifen; cromoglicate 2% QID started before season."],
        ["Escalation / second line", "Gonococcal: **ceftriaxone 1 g IM** (neonate 25-50 mg/kg, max 125 mg). Chlamydia: **azithromycin 1 g** adult; neonate erythromycin 50 mg/kg/day x 14 d. HSV: **acyclovir 3% ointment 5x/day x 14 d** or ganciclovir 0.15% gel. Uveitis (ophthalmologist): **prednisolone acetate 1% 1-2 hourly**, taper 4-6 weeks + cyclopentolate/homatropine."],
        ["Devices / how to use", "**One drop** (drop 30-50 microlitre, sac holds 7-10); pull lower lid, close eye 1-2 min, **punctal occlusion**; **5 min between drops**, ointment last (1 cm ribbon); discard bottle **4 weeks after opening**; never touch tip to eye."],
        ["Special groups", "Neonate: day 1 chemical, **2-5 gonococcal, 5-14 chlamydial** - systemic treatment, treat both parents. Children: fusidic acid BD. Pregnancy: chloramphenicol, fusidic acid, erythromycin acceptable. **Brimonidine contraindicated under 2 years**; punctal occlusion in infants."],
        ["Complications", "Corneal ulcer/perforation (gonococcus in 24-48 h), **steroid glaucoma** (1 in 3 responders) and cataract, geographic HSV ulcer with steroid, synechiae, secondary glaucoma, fellow-eye angle closure (**40-80%**), endophthalmitis, scleral melt."],
        ["Red flags and referral", "**Same day**: reduced acuity, true pain, photophobia, corneal opacity/staining, abnormal pupil, hard globe, hypopyon/hyphaema, painful lens-wearer eye, red eye within 6 weeks of surgery. **Within hours**: angle closure, chemical injury after irrigation, endophthalmitis, penetrating injury, neonatal gonococcus."],
        ["Emergency - angle closure", "Supine, analgesia, antiemetic, **acetazolamide 500 mg IV/oral**, timolol 0.5%, brimonidine 0.2%, prednisolone acetate 1%, **pilocarpine 2% once IOP falls**, mannitol 1-2 g/kg IV if needed -> **laser peripheral iridotomy both eyes**."],
        ["Follow-up and monitoring", "Return if bacterial not better in **5-7 days**, adenoviral **2-3 weeks**; adenovirus contagious **10-14 days**; anyone on topical steroid over 2 weeks needs **IOP and lens check**; record acuity every visit."],
        ["Prevention", "Hand hygiene, separate towels, no shared drops; stop lens wear, never tap water; no OTC steroid drops or home remedies; SAFE strategy and trichiasis surveillance (trachoma); ocular prophylaxis and maternal STI care for neonates."],
        ["Exam one-liners", "**Acuity before anything**; itch = allergy; photophobia = cornea or iris; **never steroid drops without a slit lamp**; never prescribe topical anaesthetic; vomiting + unilateral headache in elderly - look at the pupil; one drop is enough."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Red eye in the OPD - triage in five steps",
        caption: "Condensed bedside algorithm; any 'yes' at a decision point means refer.",
        steps: [
          { label: "Measure acuity each eye, with pinhole", detail: "Unexplained drop in acuity = sight-threatening until proved otherwise", tone: "decision" },
          { label: "True pain, photophobia or ciliary flush?", detail: "Points to keratitis, uveitis, scleritis or angle closure", tone: "decision" },
          { label: "Fluorescein, pupil, digital tension", detail: "Stain/infiltrate, irregular or fixed mid-dilated pupil, stony hard eye", tone: "warn" },
          { label: "Normal vision, gritty, conjunctival injection", detail: "Itch = allergy; pus = bacterial; watery + node = adenovirus" },
          { label: "Treat in OPD, no steroid", detail: "Chloramphenicol 0.5% (5 days) or lubricants or olopatadine 0.1% BD" },
          { label: "Safety-net and review", detail: "Return same day for pain, light sensitivity, blur; review 5-7 days", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Five causes of red eye at a glance",
        columns: ["Feature", "Conjunctivitis", "Keratitis", "Anterior uveitis", "Angle closure"],
        rows: [
          ["Vision", "Normal", "Reduced", "Mildly reduced", "Markedly reduced, haloes"],
          ["Injection", "Conjunctival", "Ciliary", "Ciliary", "Mixed"],
          ["Cornea", "Clear", "Infiltrate, stains", "KPs", "Hazy, oedematous"],
          ["Pupil", "Normal", "Normal or small", "Small, irregular", "Mid-dilated, oval, fixed"],
          ["Tension", "Normal", "Normal", "Normal or low", "Stony hard"],
          ["Action", "Treat in OPD", "Refer same day, no drops", "Refer same day", "Treat and refer within hours"],
        ],
      },
      {
        kind: "ladder",
        heading: "Acute angle closure - first aid while transferring",
        steps: [
          { label: "Lie supine, analgesia, antiemetic", detail: "Vomiting is trigemino-vagal, not gastritis" },
          { label: "Acetazolamide 500 mg IV or oral", detail: "Then 250 mg 6-hourly; avoid in sulpha allergy, sickle cell, renal failure" },
          { label: "Timolol 0.5% + brimonidine 0.2% + prednisolone 1%", detail: "One drop each; timolol not in asthma, COPD, heart block", tone: "warn" },
          { label: "Pilocarpine 2% once IOP starts to fall", detail: "Ischaemic sphincter will not respond above 40-50 mmHg" },
          { label: "Mannitol 20% 1-2 g/kg IV if IOP stays high", detail: "Over 30-45 min; caution heart and renal failure" },
          { label: "Laser peripheral iridotomy both eyes", detail: "Fellow eye has 40-80% risk without it", tone: "good" },
        ],
      },
    ],
  },

  "eye-ent-otitis": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - AOM, otitis externa, OME and CSOM",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**AOM**: rapid-onset middle ear inflammation with effusion - **moderate/severe bulging drum**, new otorrhoea, or mild bulging + pain under 48 h. **OME**: fluid behind intact drum, no inflammation. **OE**: canal inflammation under 6 weeks with **tragal pain**. **CSOM**: perforation discharging **over 2 weeks** (WHO)."],
        ["Relevant classification", "CSOM **mucosal (tubotympanic, safe, central perforation)** vs **squamous (atticoantral, unsafe, cholesteatoma, attic/marginal)**, active or inactive. **Recurrent AOM**: 3 in 6 months or 4 in 12 months. Malignant OE = skull-base osteomyelitis."],
        ["Aetiology and risk factors", "AOM: **S. pneumoniae, NTHi, Moraxella**; age 6-24 months, **supine bottle feeding**, no breastfeeding, day care, smoke/biomass, cleft palate, Down syndrome, adenoids. OE: **Pseudomonas, S. aureus**; water, cotton buds, eczema. Malignant OE: **elderly diabetic**."],
        ["Pathophysiology", "URTI -> **Eustachian tube block** (infant tube short, wide, horizontal) -> negative pressure -> effusion -> bacterial suppuration -> bulging -> perforation (pain eases, discharge). Cholesteatoma: retraction pocket -> keratin -> **RANKL/collagenase bone erosion** -> ossicles, facial canal, lateral canal, tegmen."],
        ["Key history (OPD)", "Otalgia (chewing/tragal pain = OE), ear tugging in infants, **discharge character** (profuse mucoid = safe; **scanty foul** = unsafe), duration, hearing/speech, **complication questions** (vertigo, facial weakness, headache, neck stiffness, postaural swelling), antibiotic in last 30 days, diabetes."],
        ["Key examination", "Postaural region, **tragal pressure**, mastoid tenderness; otoscopy (pinna up-back adult, **down-back infant**), drum colour/position, **attic last**; **pneumatic otoscopy** (immobile = effusion); 512 Hz Rinne/Weber; fistula test; facial nerve; nose and postnasal space."],
        ["Minimal investigations", "AOM/uncomplicated OE - **clinical**. Tympanometry: **Type B** effusion, C tube dysfunction. PTA if OME 3 months or pre-surgery. Swab only in non-responding CSOM. **HbA1c** in recurrent OE. **HRCT temporal bone** for unsafe CSOM; malignant OE: ESR/CRP, CT + MRI."],
        ["Treatment - first line", "**Analgesia first**: paracetamol 15 mg/kg 6-hourly or ibuprofen 10 mg/kg 8-hourly. **Antibiotic immediately if under 6 months, 6-23 months bilateral, otorrhoea, severe (39 C or more, pain over 48 h)**; else observe 48-72 h / delayed script. **Amoxicillin 80-90 mg/kg/day in 2 doses**: 10 days under 2 y, 7 days 2-5 y, 5-7 days 6 y+."],
        ["Escalation / second line", "**Co-amoxiclav 90/6.4 mg/kg/day** if amoxicillin in last 30 days, otitis-conjunctivitis or failure at 48-72 h; non-anaphylactic allergy **cefuroxime 30 mg/kg/day**; anaphylaxis azithromycin 10 mg/kg x 3 d; two failures **ceftriaxone 50 mg/kg IM x 1-3 days**; myringotomy."],
        ["OE and CSOM drugs", "OE: aural toilet + **ciprofloxacin 0.3%-dexamethasone 0.1% 4 drops BD x 7 days** or ofloxacin 10 drops OD; wick if canal shut; **no oral antibiotic**. Otomycosis: clotrimazole 1%. Mucosal CSOM: dry mopping + **quinolone drops BD 10-14 days**. **No aminoglycoside drops through a perforation**."],
        ["Devices / how to use", "Ear drops: **warm bottle in palm**, ear up, pull pinna, drops along wall, **tragal pumping**, lie 3-5 min; clean canal first; ear wick changed 2-3 days; **dry mopping** with cotton wisp; autoinflation balloon for OME from 3-4 years."],
        ["Special groups", "Infant under 3 months with fever = febrile young infant work-up. **Down syndrome and cleft palate** - early referral (aids often preferred). Pregnancy: amoxicillin, co-amoxiclav, cefuroxime, topical quinolone; no systemic quinolone. Diabetic elderly: malignant OE."],
        ["Complications", "Mastoiditis, **meningitis (commonest intracranial)**, brain abscess, lateral sinus thrombosis (picket-fence fever), facial palsy, labyrinthine fistula, Gradenigo, Bezold abscess, conductive hearing loss and speech delay."],
        ["Red flags and referral", "Postaural swelling with pinna pushed forward; fever + headache + neck stiffness; **facial weakness**; vertigo/positive fistula test; foul scanty discharge with attic perforation; **night otalgia + canal-floor granulation in diabetic**; unilateral OME in adult (**exclude nasopharyngeal carcinoma**)."],
        ["Malignant OE", "Admit, glycaemic control, **IV ceftazidime 2 g 8-hourly or piperacillin-tazobactam**, or oral ciprofloxacin 750 mg BD early, **6-8 weeks**, monitor ESR/CRP; facial palsy first, then IX-XI."],
        ["Follow-up and monitoring", "AOM review 48-72 h if not improving and **6-12 weeks** for effusion/perforation; **OME: test hearing at 3 months**, grommets if bilateral loss worse than **25-30 dB** or speech/learning issues; OE review 7 days; perforation over 6 weeks refer."],
        ["Prevention / national programme", "**Exclusive breastfeeding**, upright feeding, smoke-free home, **PCV and influenza vaccine**, dry-ear care, no cotton buds/oil; **NPPCD** school screening; treat the nose (AR, adenoids)."],
        ["Exam one-liners", "Red drum in a crying child proves nothing - **bulging/immobile drum** proves AOM; tragal pain = OE; **high-dose amoxicillin beats resistance**; OE needs drops not tablets; central perforation safe, attic/marginal unsafe; look at the attic last and always."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Acute otitis media - antibiotic or wait",
        caption: "AAP 2013 rule, still current; analgesia for everyone.",
        steps: [
          { label: "Confirm AOM: bulging or immobile drum", detail: "Pneumatic otoscopy; red drum alone is not AOM", tone: "decision" },
          { label: "Regular analgesia by the clock 48-72 h", detail: "Paracetamol 15 mg/kg 6-hourly or ibuprofen 10 mg/kg 8-hourly" },
          { label: "Immediate antibiotic criteria?", detail: "Under 6 months; 6-23 months bilateral; otorrhoea; 39 C or more; pain over 48 h", tone: "decision" },
          { label: "Amoxicillin 80-90 mg/kg/day in 2 doses", detail: "10 days under 2 y; 7 days 2-5 y; 5-7 days 6 y and over" },
          { label: "No better at 48-72 h", detail: "Co-amoxiclav 90/6.4 mg/kg/day; then ceftriaxone 50 mg/kg IM 1-3 days", tone: "warn" },
          { label: "Review drum at 6-12 weeks", detail: "Persistent effusion = OME pathway; hearing test at 3 months", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "The painful or discharging ear",
        columns: ["Feature", "AOM", "Otitis externa", "CSOM safe", "CSOM unsafe"],
        rows: [
          ["Pain", "Severe, eases on perforation", "Severe, tragal", "Painless", "Painless; pain = complication"],
          ["Discharge", "Mucopurulent after perforation", "Scanty, no mucus", "Profuse mucoid odourless", "Scanty foul, blood-stained"],
          ["Drum", "Red, bulging, immobile", "Intact, hidden by oedema", "Central perforation", "Attic/marginal, keratin, polyp"],
          ["Treatment", "Analgesia; amoxicillin by rule", "Aural toilet, steroid-quinolone drops", "Dry ear, quinolone drops, tympanoplasty", "HRCT, mastoidectomy"],
        ],
      },
      {
        kind: "branch",
        heading: "Complications of otitis media - where the pus goes",
        root: "Discharging ear with a new symptom",
        arms: [
          { label: "Intratemporal", tone: "warn", steps: ["Mastoiditis - pinna pushed forward", "Facial palsy", "Labyrinthine fistula - vertigo", "Petrous apicitis (Gradenigo)"] },
          { label: "Intracranial", tone: "warn", steps: ["Meningitis (commonest)", "Temporal lobe or cerebellar abscess", "Lateral sinus thrombosis - picket-fence fever", "Extradural abscess"] },
          { label: "Extracranial", steps: ["Subperiosteal abscess", "Bezold abscess in sternomastoid", "Admit, IV ceftriaxone + metronidazole, CT/MRI"] },
        ],
      },
    ],
  },

  "eye-ent-sore-throat": {
    checked: "2026-10",
    updated: [
      "IDSA 2025 guideline update (Part 1): a clinical score (Centor or McIsaac) is now recommended in children and adults to decide who needs a GAS test; treatment advice of IDSA 2012 unchanged pending Part 2",
    ],
    master: {
      heading: "Master revision table - Sore throat and streptococcal tonsillitis",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Acute pharyngitis/tonsillopharyngitis: pharyngeal and tonsillar inflammation with sore throat and odynophagia, usually under 1 week; **70-85% adult and 60-70% child cases viral**."],
        ["Relevant classification", "**Viral vs GABHS** (15-30% at 5-15 years, 5-15% adults, rare under 3). **McIsaac**: exudate/swelling, tender anterior nodes, fever over 38 C, no cough, **age 3-14 +1, 45+ -1**. FeverPAIN (NICE). Recurrent tonsillitis: **Paradise 7-5-3**."],
        ["Aetiology and risk factors", "Viruses (rhino, adeno, corona, influenza, **EBV**); S. pyogenes (M protein, streptolysins, superantigens); Fusobacterium (Lemierre); C. diphtheriae in unimmunised; drug agranulocytosis (**carbimazole, clozapine, methotrexate**)."],
        ["Pathophysiology", "GABHS adhesion -> M protein resists phagocytosis -> exudative tonsillitis -> **molecular mimicry (M protein vs cardiac myosin, valves, basal ganglia)** -> rheumatic fever 2-4 weeks later; **treatment within 9 days prevents ARF**; PSGN (immune complex) **not prevented**."],
        ["Key history (OPD)", "Cough, coryza, hoarseness, conjunctivitis = viral; sudden onset, headache, abdominal pain, rash = GABHS; **drooling, trismus, hot potato voice, stridor** = deep space/airway; immunisation (diphtheria); past RF; drugs causing agranulocytosis; adult smoker with unilateral symptoms = cancer."],
        ["Key examination", "**Airway first - no spatula if drooling or stridor**; hydration, SpO2; tonsils (exudate, membrane), **tender anterior nodes** (GABHS) vs posterior nodes + spleen (EBV); **uvula deviated** (quinsy); grey bleeding membrane, bull neck (diphtheria); scarlatiniform rash, strawberry tongue; heart murmur."],
        ["Minimal investigations", "**Score first, then test (IDSA 2025)**: McIsaac 0-1 no test. **RADT** specificity 90-95%, sensitivity 70-90% - **negative in a child needs culture**; culture gold standard. **No ASO** for acute pharyngitis; no test of cure. CBC/monospot for EBV; urgent neutrophils on agranulocytosis drugs; Albert stain for diphtheria."],
        ["Diagnostic criteria / scoring action", "**0-1**: no test, no antibiotic. **2-3**: RADT/culture, treat if positive (delayed script if no test). **4-5 (about 50%)**: test, or **treat empirically in India** (high RF setting)."],
        ["Treatment - first line", "Analgesia by the clock (paracetamol 15 mg/kg, ibuprofen 10 mg/kg). **Penicillin V: under 27 kg 250 mg BD-TDS; adult 500 mg BD x 10 days**, 1 h before food; or **amoxicillin 50 mg/kg once daily (max 1 g) x 10 days**; **benzathine penicillin 0.6 MU (under 27 kg) / 1.2 MU deep IM** if adherence doubtful."],
        ["Escalation / second line", "Non-anaphylactic allergy: **cephalexin 20 mg/kg BD x 10 days**; anaphylaxis: **azithromycin 12 mg/kg OD x 5 days** or clindamycin 7 mg/kg TDS x 10 days. No 3rd-gen cephalosporin, quinolone or co-amoxiclav for simple pharyngitis. Failure = adherence or wrong diagnosis."],
        ["Deep space and special infections", "**Quinsy**: aspirate/drain + IV co-amoxiclav 1.2 g 8-hourly or penicillin + metronidazole. **Epiglottitis**: secure airway, ceftriaxone. **Diphtheria**: antitoxin 20,000-100,000 U by extent + erythromycin, isolate, notify. **Lemierre**: anaerobic cover 4-6 weeks."],
        ["Special groups", "Under 3 years - no routine testing. **EBV (teenager)** - never amoxicillin (80-90% rash), no contact sport 4-6 weeks. Pregnancy: penicillin V, amoxicillin, cephalexin, azithromycin. Past RF: treat any GAS throat; **secondary prophylaxis BPG 1.2 MU every 3 weeks**."],
        ["Complications", "Suppurative: quinsy, parapharyngeal/retropharyngeal abscess, Lemierre. Non-suppurative: **acute rheumatic fever (2-4 weeks)**, **PSGN (1-2 weeks)**, scarlet fever, streptococcal toxic shock."],
        ["Red flags and referral", "Stridor, drooling, tripod, inability to swallow saliva; trismus + uvular deviation; neck stiffness/torticollis in toddler; grey membrane; rigors + neck tenderness; fever on carbimazole/clozapine; **persistent unilateral tonsil ulcer in adult - urgent biopsy (NICE NG12)**."],
        ["Follow-up and monitoring", "Review 48-72 h if not improving; **document every episode** (Paradise needs documented episodes); watch for ARF and PSGN; RF register, trace defaulters; prophylaxis 5 years or to 21 (no carditis), 10 years or to 21 (mild), to 40 or lifelong (severe)."],
        ["Tonsillectomy indications", "**Paradise: 7 in 1 year, 5/year for 2 years, 3/year for 3 years** (documented); 2 episodes of quinsy; obstructive sleep-disordered breathing with large tonsils; suspected malignancy."],
        ["Latest guideline change", "**IDSA 2025 (Part 1)**: use Centor/McIsaac in children and adults before testing - reduces needless swabs and antibiotics; penicillin/amoxicillin 10 days unchanged."],
        ["Exam one-liners", "Cough and coryza argue against strep; **S. pyogenes never penicillin-resistant**; antibiotics prevent ARF not PSGN; treatment within 9 days still prevents ARF; ASO has no role in acute pharyngitis; quinsy = trismus + uvula pushed away."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Sore throat in primary care (IDSA 2025 score-first)",
        steps: [
          { label: "Airway check: drooling, stridor, trismus?", detail: "Yes = no spatula; deep space or epiglottitis; admit", tone: "warn" },
          { label: "Calculate McIsaac score", detail: "Exudate, tender anterior nodes, fever, no cough; age 3-14 +1, 45+ -1", tone: "decision" },
          { label: "Score 0-1: no test, no antibiotic", detail: "Analgesia, fluids, gargles, safety-net" },
          { label: "Score 2-3: RADT or culture", detail: "Treat only if positive; negative RADT in child - culture", tone: "decision" },
          { label: "Score 4-5: test or treat empirically in India", detail: "Rheumatic fever prevention is the goal" },
          { label: "Penicillin V or amoxicillin for 10 days", detail: "Amoxicillin 50 mg/kg OD max 1 g; BPG once if adherence doubtful", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Antibiotic choice for GAS pharyngitis",
        steps: [
          { label: "Penicillin V 10 days", detail: "Under 27 kg 250 mg BD-TDS; adult 500 mg BD; 1 h before food", tone: "good" },
          { label: "Amoxicillin 10 days", detail: "50 mg/kg once daily (max 1 g) or 25 mg/kg BD" },
          { label: "Benzathine penicillin G deep IM once", detail: "600,000 U under 27 kg; 1.2 MU at 27 kg or more; observe 30 min" },
          { label: "Non-anaphylactic allergy: cephalexin", detail: "20 mg/kg BD (max 500 mg) x 10 days" },
          { label: "Anaphylaxis: azithromycin or clindamycin", detail: "Azithro 12 mg/kg OD x 5 d; clinda 7 mg/kg TDS x 10 d", tone: "warn" },
        ],
      },
      {
        kind: "compare",
        heading: "Dangerous sore throats - clue and action",
        columns: ["Condition", "Clue", "Action"],
        rows: [
          ["Quinsy", "Trismus, hot potato voice, uvula pushed away", "Aspirate or drain + IV antibiotics today"],
          ["Epiglottitis", "Drooling, stridor, tripod, normal oropharynx", "No spatula; secure airway; ceftriaxone"],
          ["Diphtheria", "Grey membrane bleeds on removal, bull neck", "Antitoxin without waiting, erythromycin, notify"],
          ["Infectious mononucleosis", "Membranous tonsils, posterior nodes, spleen", "No amoxicillin; monospot; no contact sport"],
          ["Agranulocytosis", "Fever + sore throat on carbimazole or clozapine", "Stop drug, urgent CBC, febrile neutropenia care"],
        ],
      },
    ],
  },

  "eye-ent-rhinitis-sinusitis": {
    checked: "2026-10",
    updated: [
      "ARIA 2025 (ARIA-EAACI 2024-2025 revision): INCS strongly recommended over oral H1-antihistamines; conditional recommendation for INCS plus intranasal antihistamine over INCS alone when monotherapy is insufficient",
      "ARIA 2025: azelastine-fluticasone preferred over olopatadine-mometasone in adults; either in children; fluticasone furoate or propionate conditionally favoured among INCS",
      "ARIA 2025: intranasal decongestants - suggest against long-term (over 5 days) use and against routinely adding to an INCS (reversal of 2010/2016); regular oral decongestants suggested against",
    ],
    master: {
      heading: "Master revision table - Allergic rhinitis and sinusitis",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**AR**: IgE-mediated nasal inflammation with 2 or more of watery rhinorrhoea, sneezing, blockage, **itch** over 1 h on most days. **Rhinosinusitis**: blockage or discharge + facial pain or reduced smell (cough in children); **acute under 12 weeks, chronic 12 weeks or more** (EPOS 2020)."],
        ["Relevant classification", "**ARIA**: intermittent (under 4 days/week or under 4 weeks) vs persistent; **mild vs moderate-severe** (sleep, school, work, sport impaired). ARS: viral (under 10 days), post-viral, **ABRS** (over 10 days, double sickening, fever over 39 C + pus 3-4 days). CRS with/without polyps."],
        ["Aetiology and risk factors", "House dust mite, cockroach, moulds, pets, pollens (Parthenium, Prosopis); atopy; smoke and biomass; occupational dusts. ABRS: **pneumococcus, H. influenzae, Moraxella**; dental roots (2nd premolar, 1st molar). Mucormycosis: **DKA, steroids, post-COVID**."],
        ["Pathophysiology", "Allergen -> dendritic cells -> **Th2 (IL-4, IL-5, IL-13) -> IgE** on mast cells -> early phase histamine (itch, sneeze, rhinorrhoea) -> late phase eosinophils (**blockage, priming**). Sinus: viral oedema -> **OMC block** -> stasis -> bacterial superinfection (0.5-2% of colds)."],
        ["Key history (OPD)", "Dominant symptom (sneezer-runner vs blocker), pattern (perennial/seasonal/occupational), **impact on sleep and school**, asthma screen, **decongestant use over 5-7 days**, aspirin sensitivity, sinusitis time course, **unilateral symptoms**, eye and brain symptoms, diabetes/steroids."],
        ["Key examination", "Allergic shiners, nasal crease, adenoid facies; anterior rhinoscopy (pale boggy turbinates, polyp vs turbinate - polyp insensitive, grape-like); middle meatal pus; **eyes in every sinusitis** (proptosis, movements, acuity, RAPD); palatal eschar; peak flow; level II nodes."],
        ["Minimal investigations", "AR - **clinical**; **skin prick or specific IgE** only if uncertain or before immunotherapy; **no total IgE/AEC**. ARS - **no imaging**; **contrast CT** for complications, unilateral disease or failed therapy; endoscopy for CRS; KOH + biopsy for mucormycosis; beta-2 transferrin for CSF leak."],
        ["Treatment - first line (AR)", "Avoidance + saline. Mild intermittent: **oral non-sedating antihistamine as needed** (levocetirizine 5 mg, fexofenadine 120-180 mg). Persistent/moderate-severe: **INCS - strongly preferred over oral antihistamine (ARIA 2025)**: mometasone or fluticasone 2 sprays each nostril OD, full effect 1-2 weeks."],
        ["Escalation / second line", "**INCS + intranasal antihistamine (fixed azelastine-fluticasone 1 spray BD)** - conditional over INCS alone (ARIA 2025); montelukast 10 mg only with asthma (neuropsychiatric warning); ipratropium for watery rhinorrhoea; **allergen immunotherapy 3 years** (only disease-modifying). No depot steroid."],
        ["Decongestants (ARIA 2025)", "Oxymetazoline/xylometazoline **maximum 5 days** (rhinitis medicamentosa); **suggest against long-term use and routine add-on to INCS**; brief course only while INCS starts; **no regular oral decongestants** (BP, glaucoma, prostatism, under 6)."],
        ["Sinusitis treatment", "Viral/post-viral: saline, paracetamol, **mometasone 200 microgram BD x 14 days** if over 10 days. **ABRS**: watchful waiting acceptable; **amoxicillin 500 mg TDS or co-amoxiclav 625 mg TDS x 5-7 days**; child amoxicillin 45-90 mg/kg/day 10-14 days; allergy doxycycline 100 mg BD. CRSwNP: INCS, short prednisolone, FESS, biologics."],
        ["Devices / how to use", "Spray: blow nose, prime, **head slightly forward, opposite hand, aim to outer eye away from septum**, gentle breath, no hard sniff. Polyps: **head-down drops**. Irrigation: **boiled-cooled or bottled water**, 150-240 mL per side; saline first, then steroid."],
        ["Special groups", "Pregnancy: **budesonide INCS**, loratadine or cetirizine, saline. Children: mometasone from 3 y, fluticasone furoate from 6 y, check height yearly; no first-generation antihistamines. AERD: avoid NSAIDs. Diabetics on steroids: mucormycosis watch."],
        ["Complications", "Asthma (united airway), OME, sleep disturbance, CRS/polyps; sinusitis -> **preseptal/orbital cellulitis (Chandler I-V)**, cavernous sinus thrombosis, meningitis, frontal abscess, **Pott puffy tumour**; mucormycosis."],
        ["Red flags and referral", "**Proptosis, painful restricted eye movement, diplopia, falling vision** - admit, IV ceftriaxone + metronidazole, CT; black eschar in diabetic - same-day debridement + **liposomal amphotericin 5 mg/kg/day**; **unilateral blockage, blood-stained discharge, mass - urgent ENT** (tumour)."],
        ["Follow-up and monitoring", "Review AR at **2-4 weeks** - check **spray technique and adherence before adding a drug**; step down off-season; record sleep, school days, asthma control, epistaxis, child height. ABRS reassess 3-7 days."],
        ["Latest guideline change", "**ARIA 2025**: INCS over oral antihistamine (strong); INAH + INCS over INCS alone (conditional); azelastine-fluticasone preferred in adults; decongestants - against long-term and routine add-on."],
        ["Exam one-liners", "Itch separates AR from a cold; **blockers need INCS**; check technique before changing drug; colour of discharge does not mean bacteria - time course does; any unilateral nasal sign = tumour (adult) or foreign body (child); one airway, one disease."],
      ],
    },
    flows: [
      {
        kind: "ladder",
        heading: "Allergic rhinitis ladder (ARIA 2025)",
        caption: "Check technique and adherence before every step up; review 2-4 weeks.",
        steps: [
          { label: "Avoidance and saline irrigation", detail: "Mite covers, wash bedding at 60 C; saline 5-10 mL per nostril OD-BD", tone: "good" },
          { label: "Mild intermittent: oral antihistamine as needed", detail: "Levocetirizine 5 mg or fexofenadine 120-180 mg; never chlorpheniramine" },
          { label: "Persistent or moderate-severe: INCS daily", detail: "Strongly preferred over oral antihistamine; 2 sprays each nostril OD; 1-2 weeks" },
          { label: "Not controlled: add intranasal antihistamine", detail: "Fixed azelastine-fluticasone 1 spray each nostril BD (12 y+)" },
          { label: "Still uncontrolled: allergy referral", detail: "Skin prick test, allergen immunotherapy SCIT/SLIT for 3 years" },
          { label: "Decongestant only briefly", detail: "Max 5 days while INCS starts; never long term; no depot steroid", tone: "warn" },
        ],
      },
      {
        kind: "flow",
        heading: "Acute rhinosinusitis - antibiotic or not",
        steps: [
          { label: "Nasal blockage/discharge + facial pain or smell loss", detail: "Viral in over 98%; no X-ray", tone: "decision" },
          { label: "Any orbital or intracranial sign?", detail: "Proptosis, painful eye movement, diplopia, headache, meningism - admit, CT", tone: "warn" },
          { label: "Under 10 days and improving: viral", detail: "Saline, paracetamol, fluids; colour of mucus irrelevant" },
          { label: "Over 10 days: post-viral", detail: "Mometasone 200 microgram BD x 14 days" },
          { label: "ABRS criteria met: over 10 days, double sickening, severe", detail: "Severe = fever 39 C + pus 3-4 days; amoxicillin 500 mg TDS or co-amoxiclav 625 mg TDS 5-7 days", tone: "decision" },
          { label: "Reassess at 3-7 days", detail: "Failure: high-dose co-amoxiclav or doxycycline; think dental, polyp, tumour", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Preseptal versus orbital cellulitis",
        columns: ["Feature", "Preseptal", "Orbital"],
        rows: [
          ["Vision and colour", "Normal", "Reduced; RAPD possible"],
          ["Eye movements", "Full, painless", "Painful, restricted; diplopia"],
          ["Proptosis, chemosis", "Absent", "Present"],
          ["Management", "Oral co-amoxiclav, review 24 h", "Admit, IV ceftriaxone + metronidazole, contrast CT, drain abscess"],
        ],
      },
    ],
  },

  "eye-ent-refractive-error": {
    checked: "2026-10",
    updated: [
      "IMI 2025 Digest: delaying myopia onset in pre-myopic children made a priority (each year of delay worth about 2-3 years of progression control); outdoor time remains the strongest protective factor",
      "EGS 2025 (6th edition) replaces EGS 2020 for the glaucoma check from 40 years",
    ],
    master: {
      heading: "Master revision table - Refractive error, presbyopia and NPCBVI",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Failure to focus parallel rays on the retina with accommodation relaxed - **axial length vs refractive power mismatch**; **uncorrected refractive error is the leading cause of visual impairment** and fully correctable."],
        ["Relevant classification", "**Myopia** (minus lens; high = -6 D or more or axial length over 26 mm), **hypermetropia** (plus lens), **astigmatism** (cylinder; irregular - rigid lens), **presbyopia** (near add +1.00 D at 40-45 to +2.50-3.00 after 60), **anisometropia 2 D or more**. WHO: blindness **presenting acuity worse than 3/60** (India since 2017); near impairment worse than N6."],
        ["Aetiology and risk factors", "Myopia: **near work, under 2 h outdoors**, parental myopia, urban schooling. Hypermetropia: short eye -> accommodative esotropia. Keratoconus: rubbing, allergy. Drugs: **topiramate** (myopic shift + angle closure); diabetes (glucose swings)."],
        ["Pathophysiology", "Peripheral hyperopic defocus -> **scleral remodelling -> axial elongation** (1 mm = about 3 D); bright light -> **retinal dopamine** inhibits growth; atropine acts on retinal/scleral muscarinic receptors. Amblyopia: blurred/deviated eye suppressed in **critical period to 7-8 years**."],
        ["Key history (OPD)", "Distance vs near blur, gradual vs **sudden (never refractive)**, strain/frontal headache after reading, child sitting close to board, squint, family history, **screen and outdoor time**, flashes/floaters in myopes, diabetes, drugs, existing glasses, occupation and driving."],
        ["Key examination", "**Snellen at 6 m, each eye, with own glasses (presenting acuity)**; **pinhole** (improves = refractive); near N chart at 40 cm; children - Lea, tumbling E; **Bruckner red reflex**, Hirschberg, cover test; RAPD; torch and fundus."],
        ["Minimal investigations", "Refraction (retinoscopy + subjective); **cycloplegic refraction mandatory in children**; dilated fundus yearly in high myopia; IOP/disc from 40; topography for keratoconus; **axial length 6-12 monthly** in myopia control; HbA1c if refraction fluctuates."],
        ["Treatment - first line", "**Spectacles** (worn constantly); ready-made readers for presbyopia with equal eyes; contact lenses with strict hygiene; myopia prevention **2 h outdoors daily**, near-work breaks, 20-20-20 rule."],
        ["Myopia control", "**Atropine 0.01-0.05% 1 drop at bedtime for at least 2 years** (0.05% most effective), review 6-monthly, **taper not stop**; **defocus spectacles (DIMS/HAL), dual-focus soft lenses, orthokeratology** slow progression 30-60%; under-correction does not help."],
        ["Amblyopia", "Full-time glasses first (16-18 weeks), then **patching 2 h/day moderate, 6 h/day severe** or **atropine 1% penalisation** of better eye; must start **before 7-8 years**."],
        ["Cycloplegics", "**Cyclopentolate 1% (0.5% infants) 1 drop x 2, refract at 30-45 min**; atropine 1% ointment BD x 3 days before refraction (7-14 days effect); toxicity - hallucinations, ataxia, fever; **punctal pressure**; tropicamide 1% for adult fundus."],
        ["Special groups", "Preterm under 34 weeks or 2000 g - **ROP screen by 4 weeks or 31 weeks PMA**; diabetic - defer refraction until glucose stable; elderly - avoid bifocals on stairs (falls); topiramate users - sudden blur + pain = emergency."],
        ["Complications", "Amblyopia, strabismus, **retinal detachment, myopic maculopathy, glaucoma** in high myopia, keratitis from lens misuse, school failure, falls."],
        ["Red flags and referral", "**Leukocoria/absent red reflex** (same week), sudden vision loss, flashes + curtain, no pinhole improvement, new squint/diplopia, two-line acuity difference in child, red painful lens-wearer eye, topiramate blur."],
        ["Follow-up and monitoring", "Children with glasses **6-12 monthly** (6-monthly on myopia control); adults every 2 years; high myopes yearly dilated fundus; amblyopia to equal or best acuity then maintenance."],
        ["National programme", "**NPCBVI** (1976; renamed 2017): free cataract surgery, **school screening (6/9 cut-off) with free spectacles**, free presbyopic spectacles, Vision Centres, eye donation; goal **blindness 0.25% by 2025** (last survey 0.36%); RBSK 4Ds; vitamin A 1 lakh IU at 9 months then 2 lakh 6-monthly to 5 years."],
        ["Latest guideline change", "**IMI 2025**: prevent or delay myopia onset in pre-myopes - outdoor time strongest, low-dose atropine, red-light therapy and novel spectacles emerging."],
        ["Exam one-liners", "Presenting acuity reveals uncorrected error; **pinhole improvement = refractive**; never refract a child without cycloplegia; 2 h outdoors delays onset; atropine 0.05% slows progression; second sight = nuclear cataract; glasses do not weaken eyes."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Blurred vision in the OPD - is it refractive?",
        steps: [
          { label: "Sudden loss or pain?", detail: "Yes = not refractive; vascular, detachment, optic neuritis - refer same day", tone: "warn" },
          { label: "Presenting acuity each eye at 6 m", detail: "With own glasses; then near N chart at 40 cm", tone: "decision" },
          { label: "Pinhole improves acuity?", detail: "Yes = refractive error; no = media, retina or optic nerve - refer", tone: "decision" },
          { label: "Child: cycloplegic refraction", detail: "Cyclopentolate 1% (0.5% infant); check red reflex and squint" },
          { label: "Adult over 40 with near blur", detail: "Presbyopia - readers; check IOP and disc" },
          { label: "Prescribe and link to free spectacles", detail: "NPCBVI school and presbyopia schemes; review 6-24 months", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Childhood myopia - prevent, then control",
        steps: [
          { label: "Pre-myopia: delay onset (IMI 2025)", detail: "2 h outdoors daily, near-work breaks, reading over 30 cm", tone: "good" },
          { label: "Full single-vision correction", detail: "Under-correction does not slow myopia" },
          { label: "Progressing 0.5 D or more a year: low-dose atropine", detail: "0.01-0.05% at bedtime at least 2 years; 0.05% most effective" },
          { label: "Optical control", detail: "DIMS/HAL defocus spectacles, dual-focus soft lenses, ortho-k" },
          { label: "Combine and monitor axial length", detail: "6-monthly refraction and biometry; taper atropine on stopping", tone: "decision" },
        ],
      },
      {
        kind: "compare",
        heading: "WHO visual impairment by presenting acuity (better eye)",
        columns: ["Category", "Acuity", "Action"],
        rows: [
          ["Mild", "Worse than 6/12 to 6/18", "Pinhole, refraction"],
          ["Moderate", "Worse than 6/18 to 6/60", "Refract, find cause"],
          ["Severe", "Worse than 6/60 to 3/60", "Refer, low vision"],
          ["Blindness", "Worse than 3/60 or field under 10 degrees", "Refer, disability certificate"],
          ["Near impairment", "Worse than N6 at 40 cm", "Near addition"],
        ],
      },
    ],
  },

  "eye-ent-cataract-dr-glaucoma": {
    checked: "2026-10",
    updated: [
      "EGS 2025 (6th edition) and AAO POAG PPP 2026: SLT is a first-line option on a par with prostaglandin drops in POAG and ocular hypertension; trabeculectomy remains the benchmark for low targets",
      "Citations moved from EGS 2020 (5th edition) to EGS 2025 (6th edition); AAO POAG PPP 2026 replaces 2020",
    ],
    master: {
      heading: "Master revision table - Cataract, diabetic retinopathy and glaucoma",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Cataract**: any lens opacity (about **66% of blindness at 50+**, NBVIS 2015-19). **DR**: microvascular retinal damage from hyperglycaemia. **Glaucoma**: progressive optic neuropathy with cupping and matching field loss; **IOP is the main modifiable risk, not a criterion**."],
        ["Relevant classification", "Cataract: nuclear, cortical, posterior subcapsular; immature to hypermature. **DR International scale**: none, mild/moderate/severe NPDR (**4-2-1 rule**), PDR + DME (centre-involving or not). Glaucoma: **POAG (incl. NTG) vs primary angle-closure disease**, secondary (steroid, neovascular, lens-induced) - by gonioscopy; OHT over 21 mmHg."],
        ["Aetiology and risk factors", "Cataract: age, UV, smoking, **diabetes, steroids**. DR: **duration, HbA1c, BP**, lipids, nephropathy, anaemia, pregnancy, puberty, rapid HbA1c fall. Glaucoma: **age over 40, first-degree relative (4-10x)**, myopia (POAG), hypermetropia (angle closure), steroids, diabetes."],
        ["Pathophysiology", "Lens: oxidative crystallin aggregation; diabetic **sorbitol** osmotic swelling. DR: hyperglycaemia -> **pericyte loss** -> microaneurysms, leakage (DME) -> capillary closure -> **VEGF** -> new vessels -> haemorrhage, traction. Glaucoma: IOP/lamina strain -> **axoplasmic block -> ganglion apoptosis** -> superior/inferior rim loss -> arcuate scotoma, nasal step."],
        ["Key history (OPD)", "Gradual painless blur, glare, **second sight**, monocular diplopia; **function (reading, faces, driving, falls)**; diabetes duration and **last retinal screen**; floaters/curtain; glaucoma family history, steroid use (incl. creams, inhalers); intermittent haloes; **tamsulosin** (floppy iris); asthma before timolol; leukocoria in child."],
        ["Key examination", "Acuity + **pinhole (no improvement)**; **red reflex** (black shadows on red); oblique shadow test before dilating; **tropicamide 1%** dilation; disc: **CDR 0.6 or more, asymmetry over 0.2**, ISNT rule, disc haemorrhage; DR lesions; confrontation fields; RAPD; BP, feet, urine albumin."],
        ["Minimal investigations", "DR screen: **dilated fundus exam or retinal photography** (undilated direct ophthalmoscopy inadequate); HbA1c, lipids, eGFR, **UACR**, Hb. Glaucoma (eye team): applanation (10-21 mmHg), **pachymetry, gonioscopy**, OCT RNFL, **Humphrey 24-2**. Pre-cataract: biometry, sugar, BP - no routine ECG/CXR."],
        ["DR screening schedule (ADA 2026)", "**Type 2 at diagnosis; type 1 within 5 years**; then **yearly** (1-2 yearly if repeatedly normal and well controlled); **pregnancy with pre-existing diabetes** - pre-conception/first trimester, each trimester, 1 year postpartum; **GDM - no screen**."],
        ["Treatment - first line", "**Cataract: surgery only** (phaco or MSICS + PCIOL) when vision limits daily life. **DR: systemic control** - individualised HbA1c about 7%, **BP under 130/80**, statin, stop smoking. **Glaucoma: target 20-30% IOP fall**; **latanoprost 0.005% at night** or **SLT first-line (EGS 2025, AAO 2026)**."],
        ["Escalation / second line", "Glaucoma: switch if under 15-20% fall at 4-6 weeks, or add **timolol 0.5% BD, brimonidine 0.2% BD-TDS, dorzolamide 2% TDS**, fixed combinations; laser/trabeculectomy after 2-3 drugs. **Angle closure: laser peripheral iridotomy** or lens extraction. DR: **anti-VEGF for centre-involving DME**; **PRP** for PDR; vitrectomy; fenofibrate may slow DR."],
        ["Devices / how to use", "One drop, close eye, **punctal occlusion 1-2 min** (cuts systemic timolol/brimonidine), **5 min between drops**, prostaglandin at bedtime, wipe lids, discard 4 weeks after opening; drop-guide aids; preservative-free if surface disease."],
        ["Special groups", "**Timolol contraindicated in asthma, COPD, bradycardia, heart block**; brimonidine under 2 years contraindicated; acetazolamide - avoid sulpha allergy, renal failure, sickle cell; pregnancy - avoid prostaglandins if possible, anti-VEGF avoided; **congenital cataract surgery within 6-8 weeks**."],
        ["Complications", "Cataract: phacomorphic/phacolytic glaucoma; post-op **endophthalmitis**, PCO (10-30%, YAG). DR: vitreous haemorrhage, tractional RD, **neovascular glaucoma**. Glaucoma: irreversible field loss; drug effects - iris darkening, bronchospasm, allergy."],
        ["Red flags and referral", "Sudden painless loss/curtain - same day; **PDR or centre-involving DME - urgent**; severe NPDR within weeks; moderate NPDR 3-6 months; acute angle closure - treat and refer within hours; pain after surgery or injection - endophthalmitis; **leukocoria**; disc haemorrhage or cup asymmetry."],
        ["Follow-up and monitoring", "IOP **4-6 weeks** after new drop, then 3-12 monthly; fields and OCT 6-12 monthly; ask adherence, technique, pulse, wheeze; retinal review before and 3-6 months after intensifying glucose control in moderate+ NPDR; post-cataract day 1, week 1, 4-6 weeks."],
        ["Prevention / national programme", "**NPCBVI**: free cataract surgery with IOL, DR and glaucoma screening in Vision Centres, Ayushman Arogya Mandirs, tele-ophthalmology; **CSR target above 6000/million/year**; diabetic and glaucoma-family registers; examine first-degree relatives from 40."],
        ["Latest guideline change", "**EGS 2025 (6th edition) and AAO POAG PPP 2026**: SLT first-line alongside prostaglandins (LiGHT); MIGS for selected patients; more intensive monitoring for fast progressors."],
        ["Exam one-liners", "Refer cataract on function, not Snellen line; **half of POAG have normal single IOP**; glaucoma loss is permanent; undilated ophthalmoscopy is not DR screening; DME at any grade; timolol drops can kill an asthmatic; look at the chamber before dilating; tell surgeon about tamsulosin."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Diabetic retinopathy - screen, grade, act",
        caption: "ADA 2026 schedule with AAO PPP referral intervals.",
        steps: [
          { label: "Screen: type 2 at diagnosis, type 1 within 5 years", detail: "Dilated exam or retinal photograph; not undilated direct ophthalmoscopy" },
          { label: "Grade by International scale", detail: "None, mild, moderate, severe NPDR (4-2-1), PDR; DME separately", tone: "decision" },
          { label: "No DR or mild NPDR", detail: "Rescreen 12 months (1-2 years if repeatedly normal); mild 6-12 months" },
          { label: "Moderate NPDR", detail: "Ophthalmology within 3-6 months; tighten HbA1c, BP, lipids" },
          { label: "Severe NPDR, PDR or centre-involving DME", detail: "Urgent: PRP or anti-VEGF; vitrectomy if haemorrhage or traction", tone: "warn" },
          { label: "Systemic control at every stage", detail: "HbA1c about 7%, BP under 130/80, statin, UACR, Hb", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "POAG treatment ladder (EGS 2025)",
        caption: "Target IOP set by the ophthalmologist; check response at 4-6 weeks.",
        steps: [
          { label: "First line: prostaglandin or SLT", detail: "Latanoprost 0.005% 1 drop at night (25-35% fall) or selective laser trabeculoplasty", tone: "good" },
          { label: "Under 15-20% fall: switch, then add", detail: "Timolol 0.5% BD, brimonidine 0.2%, dorzolamide 2% TDS" },
          { label: "Fixed combinations to cut drops", detail: "Latanoprost-timolol OD, timolol-dorzolamide BD; preservative-free if surface disease" },
          { label: "Not at target on 2-3 drugs", detail: "Repeat laser, MIGS in selected cases", tone: "decision" },
          { label: "Advanced or fast progression", detail: "Trabeculectomy - benchmark for low target pressures", tone: "warn" },
        ],
      },
      {
        kind: "compare",
        heading: "Cataract, DR and glaucoma at the bedside",
        columns: ["Feature", "Cataract", "Diabetic retinopathy", "POAG"],
        rows: [
          ["Symptom", "Gradual blur, glare, second sight", "Often none; distortion with DME", "None until late field loss"],
          ["Key sign", "Dull red reflex, no pinhole gain", "Microaneurysms, exudates, new vessels", "CDR 0.6+, asymmetry over 0.2, notch"],
          ["Primary care role", "Refer on function", "Screen yearly, control risk factors", "Detect, refer, support adherence"],
          ["Definitive care", "Phaco or MSICS + IOL", "Anti-VEGF, PRP, vitrectomy", "Drops or SLT, surgery"],
        ],
      },
    ],
  },

  "eye-ent-hearing-loss": {
    checked: "2026-10",
    updated: [
      "AAO-HNS Age-Related Hearing Loss guideline 2024: screen adults aged 50 and over, refer a positive screen to audiology, fit hearing aids, cochlear implant evaluation when aids give limited benefit",
    ],
    master: {
      heading: "Master revision table - Hearing loss across ages",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Conductive** (pinna to stapes footplate, maximum about 60 dB) vs **sensorineural** (cochlea or nerve, often irreversible) vs mixed. **SSNHL: 30 dB or more over 3 contiguous frequencies within 72 hours**. Asymmetric SNHL: about 15 dB or more at 2+ frequencies."],
        ["Relevant classification", "**WHO PTA (500-4000 Hz, better ear)**: normal under 20, mild 20-34, moderate 35-49, moderately severe 50-64, severe 65-79, profound 80-94, complete 95+; **disabling over 35 dB**. RPwD Act: deaf 70 dB+, hard of hearing 60-70 dB; benchmark disability 40%."],
        ["Aetiology and risk factors", "Conductive: wax, OME, CSOM, otosclerosis. SNHL: **presbycusis, noise (85 dB(A) 8 h), ototoxins** (aminoglycosides, cisplatin, loop diuretics), Meniere, vestibular schwannoma, SSNHL, congenital (**GJB2, congenital CMV**, rubella, prematurity, jaundice, meningitis)."],
        ["Pathophysiology", "Middle ear transformer (17:1 area, 1.3:1 lever) lost -> conductive loss; **basal hair cells (high frequency) die first** with age, noise, drugs -> consonant loss; outer hair cells amplify (OAE), inner transduce; **4 kHz noise notch**; otosclerosis fixes stapes (**Carhart notch 2 kHz**); hydrops in Meniere."],
        ["Key history (OPD)", "Onset (sudden = refer today), one or both ears, tinnitus (unilateral = red flag), vertigo, discharge, **noise and drug history** (past TB injections), family history, perinatal risks and **speech milestones**, **parental concern**, neurological symptoms."],
        ["Key examination", "Otoscopy after wax removal; free-field voice at 60 cm; **512 Hz fork**: Rinne negative = conductive (15-20 dB+); **Weber to conductive ear, away from SNHL**; ABC reduced in SNHL; dead ear - false negative Rinne (Weber to good ear, Barany box); corneal reflex, VII, cerebellar signs; postnasal space."],
        ["Minimal investigations", "**PTA** (air-bone gap over 10 dB = conductive); speech audiometry (retrocochlear); tympanometry (A, As, Ad, B, C); newborn **OAE + AABR**; BERA/ASSR; **gadolinium MRI IAM** for asymmetric SNHL, unilateral tinnitus, SSNHL; HRCT for cholesteatoma/implant; child SNHL: **CMV PCR within 3 weeks**, GJB2, ECG (JLN)."],
        ["Treatment - first line", "Treat cause of conductive loss (wax softening **sodium bicarbonate 5% 3-4 drops 2-3x/day 3-5 days**, OME pathway, tympanoplasty, **stapedotomy or aid** in otosclerosis); **hearing aids from moderate loss**, binaural for bilateral; communication tactics - speak clearly, do not shout."],
        ["SSNHL treatment", "**Prednisolone 1 mg/kg/day (max 60 mg) single morning dose x 7-14 days then taper**, ideally within 72 h (up to 2 weeks); check glucose, BP; **intratympanic dexamethasone** salvage within 2-6 weeks or if systemic steroid unsafe; audiometry and **MRI**; no antivirals or vasodilators."],
        ["Escalation / second line", "**Cochlear implant** for bilateral severe-profound loss with little aid benefit (congenital by 12-24 months); bone-anchored/CROS aids for discharging ears and single-sided deafness. Meniere: salt 1.5-2 g Na/day, **betahistine 16 mg TDS or 24 mg BD**, vestibular sedative max 3 days, diuretic, intratympanic steroid/gentamicin."],
        ["Devices / how to use", "Aid: activate battery 1 min, insert mould, set volume in quiet, **2-4 h/day building over 2-4 weeks**, remove for bath/sleep, dry box; whistling = poor fit or wax; **button batteries away from children**; FM systems in classrooms."],
        ["Special groups", "Newborns: **1-3-6 rule** (screen by 1 month, diagnose by 3, intervene by 6); NICU babies need AABR (auditory neuropathy); symptomatic cCMV - **valganciclovir 16 mg/kg BD x 6 months**; elderly - **screen from 50 (AAO-HNS 2024)**, dementia risk; diabetics on steroids - prefer intratympanic."],
        ["Complications", "Speech and language delay, school failure, social isolation, depression, **dementia (largest modifiable risk factor)**, falls; ototoxic loss progresses after stopping aminoglycosides."],
        ["Red flags and referral", "SSNHL (start steroid, refer this week); **asymmetric SNHL or unilateral tinnitus - MRI**; unilateral effusion in adult - postnasal space; loss + vertigo/facial weakness/ataxia - stroke or CPA lesion; head injury with CSF/blood; parent says child does not hear; new tinnitus on aminoglycoside or cisplatin."],
        ["Follow-up and monitoring", "Audiometry baseline and during ototoxic therapy; yearly in noise-exposed workers; after SSNHL at end of treatment and 6 months (two-thirds recover partly or fully); **adults 50+ screened, positive to audiology**."],
        ["Prevention / national programme", "**NPPCD** (screening, district audiology, free aids), **RBSK** (hearing among 4Ds), **ADIP** (aids, cochlear implants), RPwD certification and UDID; MR, PCV, Hib vaccines; 60/60 rule for earphones; ear plugs above 85 dB(A); all-oral MDR-TB regimens removed injectable ototoxins."],
        ["Latest guideline change", "**AAO-HNS ARHL 2024**: screen adults 50 and over; refer to audiology; hearing aids; cochlear implant evaluation; asymmetric, conductive, mixed loss or poor word recognition are not simple ageing."],
        ["Exam one-liners", "Use 512 Hz fork; Rinne negative = conductive 15-20 dB+; false negative Rinne exposed by Weber; **conductive never over 60 dB**; 4 kHz notch = noise; **SSNHL = stroke of the ear**; asymmetric SNHL needs MRI; OAE misses auditory neuropathy; 1-3-6."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Hearing loss at the bedside - type and urgency",
        steps: [
          { label: "Otoscopy: wax, effusion, perforation?", detail: "Treat the visible cause first", tone: "decision" },
          { label: "512 Hz Rinne and Weber", detail: "Rinne negative + Weber to same ear = conductive; Weber to other ear = SNHL", tone: "decision" },
          { label: "Sudden SNHL within 72 h?", detail: "Prednisolone 1 mg/kg (max 60 mg); audiometry and MRI; ENT this week", tone: "warn" },
          { label: "Asymmetric SNHL or unilateral tinnitus", detail: "Gadolinium MRI IAM - vestibular schwannoma", tone: "warn" },
          { label: "Bilateral symmetric SNHL in older adult", detail: "Presbycusis or noise; audiology referral; screen all 50+" },
          { label: "Rehabilitate", detail: "Hearing aids from 35 dB; implant if severe-profound; NPPCD/ADIP support", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Tuning fork patterns (512 Hz)",
        columns: ["Type", "Rinne (affected ear)", "Weber", "ABC"],
        rows: [
          ["Normal", "Positive", "Central", "Normal"],
          ["Conductive", "Negative", "To affected ear", "Normal"],
          ["Sensorineural", "Positive (both reduced)", "To better ear", "Reduced"],
          ["Dead ear", "False negative", "To better ear", "Reduced; mask good ear"],
        ],
      },
      {
        kind: "flow",
        heading: "Newborn hearing - the 1-3-6 rule",
        steps: [
          { label: "Screen by 1 month", detail: "OAE for well babies; AABR for NICU over 5 days and all high-risk" },
          { label: "Refer or fail - diagnostic ABR/ASSR by 3 months", detail: "CMV PCR on urine or saliva within 3 weeks of birth", tone: "decision" },
          { label: "Intervene by 6 months", detail: "Hearing aids, early intervention, speech therapy" },
          { label: "Severe-profound bilateral loss", detail: "Cochlear implant by 12-24 months (ADIP)", tone: "good" },
          { label: "Passed but high risk", detail: "Repeat testing - late-onset loss (CMV, meningitis)", tone: "warn" },
        ],
      },
    ],
  },

  "eye-ent-epistaxis-foreign-bodies": {
    checked: "2026-10",
    updated: [
      "ERC 2025 replaces ERC 2021 as the citation for choking first aid; sequence unchanged (back blows then abdominal thrusts over 1 year, chest thrusts in infants, no blind finger sweep)",
    ],
    master: {
      heading: "Master revision table - Epistaxis and ENT foreign bodies",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Epistaxis**: bleeding from nasal cavity or nasopharynx - **anterior (about 90%, Little's area)** vs **posterior (5-10%, sphenopalatine branches, Woodruff plexus)**. **Foreign bodies**: by site (ear, nose, pharynx, oesophagus, airway) and nature (inorganic, organic - swell, animate)."],
        ["Relevant classification", "Epistaxis anterior/posterior; local vs systemic causes. Foreign bodies: **button batteries and paired magnets = emergencies anywhere**; airway partial (check-valve, emphysema) vs complete (stop-valve, collapse)."],
        ["Aetiology and risk factors", "Picking, dry air, rhinitis, misdirected steroid spray, septal spur, **anticoagulants/antiplatelets**, thrombocytopenia (dengue), liver/renal disease, HHT, angiofibroma, tumour; hypertension **prolongs rather than starts** bleeding. FB: **children 1-3 years**, nuts, seeds, beads, batteries."],
        ["Pathophysiology", "Little's area = **anterior ethmoidal + sphenopalatine (septal) + greater palatine + superior labial**; dry air -> crust -> picking -> tear. Elderly: rigid vessels + anticoagulant -> posterior heavy bleed. Battery: current -> **hydroxide at negative pole** -> liquefactive necrosis in 15 min, oesophageal perforation within 2 h."],
        ["Key history (OPD)", "Amount, side, blood **down the throat** (posterior), dizziness, recurrence, **drugs (warfarin, DOAC, aspirin, clopidogrel)**, bleeding elsewhere, fever (dengue), family history (HHT). FB: what, when, which side, previous attempts; **unilateral foul discharge**; choking episode then quiet interval."],
        ["Key examination", "**Resuscitation first** (pulse, BP, postural drop, blood in oropharynx); blow clots, vasoconstrictor pledget, headlight + Thudichum - find point on Little's area; telangiectasia, petechiae. FB: check other ear and both nostrils; drooling, crepitus (oesophagus); **unilateral wheeze or reduced air entry** (bronchus)."],
        ["Minimal investigations", "Single minor anterior bleed - **no tests**; severe/recurrent/anticoagulated: Hb, platelets, **INR**, group and save, NS1 in fever. Endoscopy for recurrent/unilateral; **contrast CT/MRI, never clinic biopsy** for angiofibroma. FB: visible ear/nose - no X-ray; **battery - AP + lateral neck, chest, abdomen (halo sign)**; inhaled FB - CXR may be normal, **bronchoscopy on history**."],
        ["Treatment - first line", "**Sit up, lean forward, pinch soft nose 10-15 min by clock**, spit blood, ice; then **oxymetazoline 0.05% or lidocaine 4% + adrenaline pledget 5-10 min**; **silver nitrate 75% cautery 5-10 s, one side only** (other after 4-6 weeks); naseptin (not in peanut allergy) or mupirocin cream."],
        ["Escalation / second line", "Anterior **expandable tampon along the floor** (24-48 h) or balloon; posterior: balloon or **Foley pack** + admit, oxygen, ECG; **tranexamic acid** topical 500 mg/5 mL, oral 1 g TDS, IV 1 g; refractory - **endoscopic sphenopalatine artery ligation** (first choice), anterior ethmoidal ligation, embolisation."],
        ["Anticoagulant management", "**Do not stop reflexively** - local measures first; life-threatening warfarin bleed: **vitamin K 5 mg IV + 4-factor PCC 25-50 IU/kg**; dabigatran - **idarucizumab 5 g IV**; Xa inhibitors - PCC 50 IU/kg if no specific reversal; platelets for active bleeding, not a number."],
        ["Devices / how to use", "Tampon horizontal along floor, expand with 10 mL saline; **packs out at 24-48 h**; anti-staphylococcal cover for posterior packs or over 48 h (toxic shock). FB: **hook behind round objects** (forceps push deeper), crocodile forceps for soft; **mother's kiss** for nasal FB; syringe only non-vegetable with intact drum."],
        ["Special groups", "Children: retrocolumellar vein, nose picking, nail trimming, petroleum jelly BD x 2 weeks. **Adolescent boy with unilateral bleed + obstruction = angiofibroma**. Elderly anticoagulated - posterior. Dengue - check platelets before instrumentation. HHT - avoid repeated cautery."],
        ["Complications", "Hypovolaemia, aspiration, myocardial ischaemia, **septal perforation** (bilateral cautery), alar necrosis, sinusitis, toxic shock; battery - **aorto-oesophageal or tracheo-oesophageal fistula**, septal perforation; retained bronchial FB - pneumonia, **bronchiectasis**; magnets - bowel necrosis."],
        ["Emergency - choking (ERC 2025)", "Effective cough - encourage; **ineffective, over 1 year: 5 back blows then 5 abdominal thrusts**; **infant: 5 back blows then 5 chest thrusts**; unconscious - CPR, look in mouth, **no blind finger sweep**; stable child - keep upright, rigid bronchoscopy."],
        ["Emergency - battery", "Swallowed within 12 h, over 1 year: **honey 10 mL every 10 min up to 6 doses** en route; hospital **sucralfate 1 g x 3**; **oesophageal removal within 2 hours**; nose/ear battery - remove same hour, no drops or irrigation. **Two magnets** - urgent removal."],
        ["Red flags and referral", "Tachycardia, hypotension, blood pouring into pharynx; recurrent unilateral bleed + obstruction (adolescent or adult - tumour); bleed with fever, petechiae; any battery or magnet; drooling, inability to swallow saliva; convincing choking history even with normal X-ray."],
        ["Follow-up and monitoring", "No blowing, straining, hot drinks for **7 days**; pack removal 24-48 h; recheck Hb; review BP and anticoagulant indication; investigate recurrent bleeders (FBC, INR, vWD); after FB removal document side, attempts and drum/septum state."],
        ["Prevention", "Humidify, saline gel, **aim steroid sprays away from septum**; no peanuts, whole grapes, hard sweets or popcorn under 4-5 years; secure battery compartments; no eating while running."],
        ["Exam one-liners", "Sit forward, pinch soft nose, 10-15 min, no peeping; **cauterise one side only**; hypertension prolongs not starts epistaxis; never syringe vegetable FB, battery, or perforated ear; **hook behind round objects**; coin in oesophagus lies flat on AP film; battery shows halo."],
      ],
    },
    flows: [
      {
        kind: "ladder",
        heading: "Epistaxis - stepwise control",
        steps: [
          { label: "First aid: lean forward, pinch soft nose 10-15 min", detail: "Spit blood, ice pack; resuscitate if shocked", tone: "good" },
          { label: "Vasoconstrictor and anaesthetic pledget", detail: "Oxymetazoline 0.05% or lidocaine 4% + adrenaline 5-10 min; lidocaine under 3 mg/kg" },
          { label: "Silver nitrate cautery, one side only", detail: "Around then on the point 5-10 s; antiseptic cream afterwards" },
          { label: "Anterior pack or balloon", detail: "Along the floor, remove at 24-48 h; topical tranexamic acid 500 mg" },
          { label: "Posterior bleed: balloon or Foley pack, admit", detail: "Oxygen, ECG, IV access, cross-match, antibiotic cover", tone: "warn" },
          { label: "Refractory: sphenopalatine artery ligation", detail: "Anterior ethmoidal ligation or embolisation as alternatives", tone: "decision" },
        ],
      },
      {
        kind: "flow",
        heading: "Choking first aid (ERC 2025)",
        steps: [
          { label: "Is the cough effective?", detail: "Yes - encourage coughing and watch closely", tone: "decision" },
          { label: "Ineffective cough, conscious, over 1 year", detail: "5 back blows, then 5 abdominal thrusts; repeat" },
          { label: "Infant under 1 year", detail: "5 back blows, then 5 chest thrusts; never abdominal thrusts", tone: "warn" },
          { label: "Becomes unconscious", detail: "Start CPR; look in mouth each cycle; no blind finger sweep", tone: "warn" },
          { label: "Object out or child stable", detail: "Hospital review; rigid bronchoscopy if history convincing", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Foreign bodies - the site decides the rule",
        columns: ["Site", "Rule", "Urgency"],
        rows: [
          ["Ear", "Hook behind round object; drown live insect first; no syringing of seeds", "Battery same hour; others after 1-2 attempts refer"],
          ["Nose", "Mother's kiss or hook; never push back; unilateral foul discharge = FB", "Battery same hour"],
          ["Oesophagus", "AP + lateral X-ray; honey en route for battery", "Battery within 2 h; food bolus 6-24 h"],
          ["Airway", "Back blows and thrusts; keep stable child upright", "Rigid bronchoscopy on history"],
        ],
      },
    ],
  },

  "eye-ent-eyelid-lacrimal-disorders": {
    checked: "2026-10",
    updated: [
      "TFOS DEWS III 2025: dry eye redefined as a symptomatic, multifactorial disease with loss of homeostasis of the tear film and/or ocular surface",
      "TFOS DEWS III 2025: diagnosis = OSDI-6 score 4 or more plus one sign (non-invasive break-up time under 10 s, osmolarity 308 mOsm/L or more or inter-eye difference over 8, or ocular surface staining) after excluding mimics",
    ],
    master: {
      heading: "Master revision table - Eyelid and lacrimal disorders, dry eye",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Stye (hordeolum)**: acute S. aureus abscess - external (Zeis/Moll, lash line) or internal (meibomian). **Chalazion**: chronic **sterile lipogranuloma** of a blocked meibomian gland - **painless**. **Blepharitis**: chronic lid-margin inflammation. **Dry eye (TFOS DEWS III)**: **symptomatic** loss of tear film and/or ocular surface homeostasis. **Dacryocystitis**: infected sac behind NLDO."],
        ["Relevant classification", "Blepharitis **anterior** (staphylococcal, seborrhoeic, Demodex) vs **posterior (MGD)**; dry eye **aqueous-deficient vs evaporative** (MGD commonest); NLDO congenital/acquired; **Chandler I-V** orbital infection; lid malpositions (entropion, ectropion, trichiasis, ptosis)."],
        ["Aetiology and risk factors", "Seborrhoea, **rosacea**, Demodex, diabetes, refractive error, screens (**blink rate 15 -> 5/min**), AC, contact lenses, drugs (antihistamines, antidepressants, beta-blockers, isotretinoin, **preserved glaucoma drops**), Sjogren, trachoma/SJS scarring, facial palsy."],
        ["Pathophysiology", "MGD: duct keratinisation -> thick meibum -> **bacterial lipases -> free fatty acids** -> unstable film -> **hyperosmolarity -> IL-1, TNF, MMP-9** -> goblet loss -> vicious circle. Chalazion: lipid leak -> granuloma. NLDO: Hasner valve (congenital) or fibrosis -> stasis -> infection (pneumococcal reservoir -> post-cataract endophthalmitis)."],
        ["Key history (OPD)", "Lump: pain and duration (painful days = stye; painless weeks = chalazion); **vision, diplopia, painful eye movement, fever** (orbital); burning, grittiness, morning crusts, **paradoxical watering**, screen hours; dry mouth (Sjogren); watering + sticky discharge; infant watering + photophobia (glaucoma); fatigable ptosis."],
        ["Key examination", "**Acuity and RAPD in every swollen eye**; eye movements and proptosis; palpate lump, evert lid; lid margin (collarettes, cylindrical sleeves, capped orifices); **express meibomian glands**; fluorescein staining, **NIBUT**; **ROPLAS** on sac pressure; lid position, lagophthalmos, Bell; levator function; lesions with lash loss."],
        ["Minimal investigations", "Stye/chalazion/blepharitis - **clinical**. Dry eye (DEWS III): **OSDI-6 4+ plus one sign** - NIBUT under 10 s, osmolarity 308+ (or difference over 8), or staining; **Schirmer under 5 mm/5 min** = aqueous deficiency; anti-Ro/La if Sjogren; **lacrimal syringing** before cataract surgery; contrast CT orbit; **biopsy recurrent chalazion over 50**."],
        ["Treatment - first line", "**Warm compress 5-10 min 3-4x/day**; never squeeze a stye, epilate the lash; chalazion compress + massage **4-6 weeks**; **lid hygiene** (diluted baby shampoo 1:10) BD then daily - lifelong; dry eye: **preservative-free carboxymethylcellulose 0.5% or hyaluronate 0.1% 4-6x/day**, gel at night; 20-20-20 rule."],
        ["Escalation / second line", "Chalazion: **triamcinolone 40 mg/mL 0.1-0.2 mL** via conjunctiva or **vertical incision and curettage**. Blepharitis: azithromycin 1% drops or chloramphenicol ointment to margin; **doxycycline 100 mg OD 6-12 weeks** (anti-lipase/MMP); Demodex - tea tree oil, ivermectin, lotilaner. Dry eye: **ciclosporin 0.05% BD 3-6 months**, loteprednol pulse, punctal plugs."],
        ["Infections", "Stye spreading as **preseptal cellulitis: co-amoxiclav 625 mg TDS x 7 days**, review 24-48 h; acute dacryocystitis - co-amoxiclav, **no probing in acute phase**, later **DCR**; orbital cellulitis - **admit, IV ceftriaxone** + vancomycin/metronidazole, CT; mucormycosis - liposomal amphotericin 5 mg/kg/day + debridement."],
        ["Devices / how to use", "One drop in lower lid pocket, close eye 1-2 min, **punctal occlusion**, 5 min between drops, ointment last (1 cm ribbon, bedtime); preservative-free if over 4 times a day; discard bottle 4 weeks after opening; lid-margin ointment rubbed into lash line."],
        ["Special groups", "**Congenital NLDO: Crigler massage 10 strokes QID**, antibiotic only for pus, **probe at about 12 months** (over 90% resolve by 1 year); preseptal cellulitis **under 1 year - admit**; doxycycline not in pregnancy or under 8 - **azithromycin** instead; triamcinolone via conjunctiva in dark skin (depigmentation)."],
        ["Complications", "Preseptal -> orbital cellulitis -> abscess -> **cavernous sinus thrombosis**; chalazion astigmatism; corneal ulcer from trichiasis/exposure; post-cataract endophthalmitis from untreated dacryocystitis; **missed sebaceous gland carcinoma**."],
        ["Red flags and referral", "Proptosis, painful restricted movement, reduced vision, RAPD - admit; black eschar in diabetic; **recurrent chalazion same site or unilateral chronic blepharitis over 50 - biopsy**; lash loss, ulceration, bleeding; ptosis + dilated pupil (aneurysm); infant watering + large hazy cornea (congenital glaucoma)."],
        ["Follow-up and monitoring", "Preseptal cellulitis 24-48 h; chalazion not resolved at 6 weeks - refer; dry eye and blepharitis 4-6 weeks for adherence; **lacrimal syringing before every cataract referral**; NPCBVI school screening for children with screen strain."],
        ["Latest guideline change", "**TFOS DEWS III 2025**: dry eye is always symptomatic; tear film and/or ocular surface; diagnosis by OSDI-6 4+ plus one sign (NIBUT under 10 s, osmolarity, staining) after excluding mimics; subtype the drivers."],
        ["Exam one-liners", "Stye painful at lash line, chalazion painless away from margin; **vertical conjunctival incision** for chalazion; recurrent chalazion in elderly = sebaceous carcinoma until histology; ROPLAS = NLDO; probe at 12 months; doxycycline works on lipase not bacteria; blepharitis is controlled, not cured."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Swollen eyelid - lid problem or orbit?",
        steps: [
          { label: "Acuity, pupils, eye movements, proptosis", detail: "Any abnormality = orbital cellulitis; admit, IV ceftriaxone, CT", tone: "warn" },
          { label: "Painful lump at lash line", detail: "External stye - warm compress, epilate lash, never squeeze", tone: "decision" },
          { label: "Painless firm nodule away from margin", detail: "Chalazion - compress and massage 4-6 weeks", tone: "decision" },
          { label: "Spreading lid redness, normal eye", detail: "Preseptal cellulitis - co-amoxiclav 625 mg TDS 7 days; admit if under 1 year" },
          { label: "Recurrent at same site, age over 50", detail: "Biopsy - sebaceous gland carcinoma", tone: "warn" },
          { label: "Persistent chalazion", detail: "Triamcinolone 0.1-0.2 mL or incision and curettage", tone: "good" },
        ],
      },
      {
        kind: "flow",
        heading: "Dry eye - diagnose and step up (TFOS DEWS III)",
        steps: [
          { label: "Exclude mimics", detail: "Allergy, infection, lid malposition, drug toxicity", tone: "decision" },
          { label: "Symptom screen: OSDI-6 score 4 or more", detail: "Grittiness, burning, fluctuating vision, paradoxical watering" },
          { label: "One sign confirms", detail: "NIBUT under 10 s, osmolarity 308+ or difference over 8, or staining", tone: "decision" },
          { label: "Step 1: education, environment, lid hygiene", detail: "Preservative-free lubricant 4-6x/day; gel at night; 20-20-20 rule" },
          { label: "Step 2 (ophthalmologist)", detail: "Ciclosporin 0.05% BD 3-6 months, loteprednol pulse, plugs, doxycycline for MGD", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Lid lumps compared",
        columns: ["Feature", "Stye", "Chalazion", "Sebaceous carcinoma"],
        rows: [
          ["Pain", "Painful", "Painless", "Painless"],
          ["Site", "Lash line or conjunctival point", "Away from margin, firm", "Recurrent at same site, lash loss"],
          ["Patient", "Any age", "Any age", "Elderly"],
          ["Action", "Warm compress, epilate lash", "Compress, then steroid or I and C", "Biopsy, urgent referral"],
        ],
      },
    ],
  },

  "eye-ent-corneal-ulcer-ocular-trauma": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - Corneal ulcer and ocular trauma",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Infective keratitis**: epithelial defect that **stains with fluorescein over a white stromal infiltrate**, with pain, photophobia, reduced vision, ciliary flush. **Ocular trauma**: mechanical (closed or open globe), chemical, thermal."],
        ["Relevant classification", "By organism - **bacterial, fungal (Fusarium, Aspergillus), HSV, Acanthamoeba**. **BETT**: closed globe (contusion, lamellar) vs open globe (rupture, penetrating, perforating, IOFB). **Roper-Hall I-IV** chemical injury by corneal haze and **limbal ischaemia**. Hyphaema grades I-IV."],
        ["Aetiology and risk factors", "**Vegetative trauma at harvest** (fungal 40-50% of culture-positive ulcers in South India); **contact lens** wear, tap water (Pseudomonas, Acanthamoeba); OTC steroid drops, home remedies, topical anaesthetic abuse; diabetes, dry eye, exposure; **lime (chuna) alkali**, firecrackers, hammering metal."],
        ["Pathophysiology", "Epithelial breach -> invasion (gonococcus, diphtheria, Listeria penetrate intact epithelium) -> **Pseudomonas proteases + MMPs melt stroma** in 48 h; fungus grows along lamellae (feathery edge, satellites, endothelial plaque); HSV latent in trigeminal ganglion; **alkali saponifies and penetrates**, acid coagulates; limbal stem cell loss -> conjunctivalisation."],
        ["Key history (OPD)", "Time, place, **mechanism** (vegetative, metal on metal, chemical type); **irrigate chemical before history**; contact lens habits; drops and remedies used; speed (hours = bacterial, days = fungal, recurrent = HSV, weeks + severe pain = Acanthamoeba); cold sores, zoster rash; tetanus status; medicolegal details."],
        ["Key examination", "**Acuity first** (medicolegal baseline); infiltrate size, hypopyon height; **fluorescein** (dendrite with terminal bulbs; vertical linear scratches = subtarsal FB); evert/double-evert lids; **corneal sensation** before anaesthetic; **open globe signs** - peaked pupil, uveal prolapse, **Seidel positive**, hypotony - stop and shield; RAPD; upgaze diplopia, infraorbital numbness."],
        ["Minimal investigations", "**Corneal scraping before treatment**: Gram stain, **10% KOH** (hyphae in minutes), culture (blood, chocolate, Sabouraud; non-nutrient agar + E. coli for Acanthamoeba); **litmus pH until 7.0-7.2**; **X-ray or CT for IOFB - never MRI**; B-scan if no open globe; glucose, HIV in severe ulcers."],
        ["Treatment - first line", "Abrasion: **chloramphenicol 1% ointment QID 3-5 days**; lens wearer - **moxifloxacin 0.5%**, stop lenses. **Fungal: natamycin 5% hourly day and night 48-72 h, then 2-hourly, 3-4 weeks** (MUTT I). Bacterial severe: **fortified cefazolin 5% + tobramycin 1.3%**, loading q5 min x 5 then hourly; small peripheral - moxifloxacin hourly."],
        ["Escalation / second line", "Add **topical voriconazole 1%** for Aspergillus/deep ulcers - **oral voriconazole adds nothing (MUTT II)**; HSV - **ganciclovir 0.15% gel 5x/day** or oral aciclovir 400 mg 5x/day; recurrent HSV aciclovir 400 mg BD 12 months; zoster - aciclovir 800 mg 5x/day 7 days; Acanthamoeba - PHMB/chlorhexidine 0.02% for 6-12 months; glue or therapeutic keratoplasty for perforation."],
        ["Adjuncts", "**Cycloplegic** (atropine 1% BD or homatropine 2% TDS); timolol/acetazolamide for raised IOP (**no acetazolamide in sickle cell**); **adjunct steroid only by specialist after 48 h of effective antibiotic - SCUT no overall benefit; never in fungal or HSV epithelial**; paracetamol analgesia."],
        ["Chemical injury", "**Irrigate 1-2 litres over 15-30 min** (any clean water first), topical anaesthetic, speculum, sweep fornices, **pH 7.0-7.2**; then preservative-free antibiotic, cycloplegic, **prednisolone 1% for first 7-10 days only**, **ascorbate 10% drops + oral vitamin C 1-2 g + doxycycline 100 mg BD**; amniotic membrane graft in severe burns."],
        ["Devices / how to use", "Hourly drops with alarm, night doses essential first 48 h; **5 min between drops**, shake natamycin; **fortified drops refrigerated, discard after 7 days**; **rigid shield on bony rim, never on the globe**; irrigation via IV set; clinic kit - fluorescein, anaesthetic, litmus, shield, cobalt-blue torch."],
        ["Open globe", "**Shield without pressure, no drops/ointment, nil by mouth**, antiemetic, analgesia, **oral moxifloxacin 400 mg OD** or IV vancomycin + ceftazidime, **Td 0.5 mL (+ TIG 250 IU if unimmunised)**, repair within 24 h; warn about sympathetic ophthalmia."],
        ["Special groups", "Farmers - examine any harvest injury within 24 h; remote setting - **natamycin + moxifloxacin + atropine** after KOH and refer within 24 h; hyphaema in **sickle cell** - urgent; children - atropine toxicity; contact lens wearers - Pseudomonas and Acanthamoeba."],
        ["Complications", "Perforation, **endophthalmitis**, corneal scar (nebula, macula, leucoma, adherent leucoma), staphyloma, **limbal stem cell failure**, symblepharon, secondary glaucoma, angle recession glaucoma, rebleed at 2-5 days in hyphaema, **sympathetic ophthalmia**, siderosis."],
        ["Red flags and referral", "**Any infiltrate or hypopyon - scrape and refer same day**; painful lens-wearer eye; chemical injury after irrigation; open globe/IOFB; hyphaema with raised IOP or sickle cell; **orbital compartment syndrome - lateral canthotomy within 90 min**; upgaze diplopia + enophthalmos (blow-out); new RAPD."],
        ["Follow-up and monitoring", "Abrasion 24-48 h; ulcer daily - infiltrate size, epithelial defect, hypopyon, vision; worsening - rescrape; post-hyphaema gonioscopy (angle recession); keratoplasty assessment for scars; medicolegal note."],
        ["Prevention / national programme", "Protective eyewear (farm, industry, welding), safe Diwali, lens hygiene (no sleeping, swimming or tap water); **no OTC steroid drops or home remedies**; **eye donation fortnight 25 August-8 September**; corneal opacity is the 2nd commonest cause of blindness at 50+ (NBVIS)."],
        ["Exam one-liners", "Feathery margins + satellites after vegetative trauma = fungus, do KOH; **natamycin first-line (MUTT I)**; dendrite + reduced sensation = HSV, no steroid; pain out of proportion in lens wearer = Acanthamoeba; **irrigate before anything** in chemical injury; never MRI for metallic FB; never send home anaesthetic drops."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Corneal ulcer - diagnose before you treat",
        steps: [
          { label: "Painful red eye with white infiltrate", detail: "Fluorescein stains defect; record acuity and hypopyon height", tone: "decision" },
          { label: "Stop steroids, remedies, anaesthetic drops", detail: "Never pad an infected eye", tone: "warn" },
          { label: "Scrape before first drop", detail: "Gram stain, 10% KOH, culture; non-nutrient agar if lens wearer" },
          { label: "Hyphae on KOH: natamycin 5% hourly", detail: "Add topical voriconazole for deep or Aspergillus; no oral voriconazole", tone: "decision" },
          { label: "Bacterial: fortified cefazolin + tobramycin", detail: "q5 min x 5 then hourly 24-48 h; small peripheral - moxifloxacin" },
          { label: "Daily review, taper by response", detail: "Worsening at 48-72 h - rescrape, cornea specialist", tone: "good" },
        ],
      },
      {
        kind: "flow",
        heading: "Chemical injury - first hour",
        steps: [
          { label: "Irrigate immediately with any clean water", detail: "Before history; alkali (lime, cement) worse than acid", tone: "warn" },
          { label: "Topical anaesthetic, speculum, saline or RL", detail: "1-2 litres over 15-30 min; double-evert lids, sweep fornices" },
          { label: "Check pH after 5-10 min pause", detail: "Continue until 7.0-7.2", tone: "decision" },
          { label: "Grade by limbal ischaemia (Roper-Hall)", detail: "Over half limbal ischaemia = grade IV, poor prognosis" },
          { label: "Same-day ophthalmology", detail: "Steroid first 7-10 days, ascorbate, doxycycline, cycloplegic", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Infective keratitis - telling the organisms apart",
        columns: ["Type", "Setting", "Lesion", "First drug"],
        rows: [
          ["Bacterial", "Contact lens, hours", "Dense infiltrate, mobile sterile hypopyon", "Fortified cefazolin + tobramycin or moxifloxacin"],
          ["Fungal", "Vegetative trauma, days", "Dry slough, feathery edge, satellites, immobile hypopyon", "Natamycin 5%"],
          ["Herpes simplex", "Recurrent, reduced sensation", "Dendrite with terminal bulbs", "Ganciclovir gel or oral aciclovir"],
          ["Acanthamoeba", "Lens + tap water, weeks", "Pain out of proportion, ring infiltrate", "PHMB or chlorhexidine 0.02%"],
        ],
      },
    ],
  },
};

export default revision;
