import type { RevisionSet } from "./index";

const revision: RevisionSet = {
  "gastro-hepatology-acid-peptic-gerd": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - acid peptic disease, GERD and H. pylori",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Dyspepsia** - epigastric pain/burning, fullness or early satiety for **4 weeks or more**; **peptic ulcer** - mucosal break **5 mm or more through muscularis mucosae**; **GERD** - reflux causing **troublesome symptoms (2 or more days a week) or oesophagitis**."],
        ["Relevant classification", "**Los Angeles A-D** for oesophagitis (**Lyon 2.0**: LA B-D, long-segment Barrett or stricture = conclusive GERD; LA A borderline); **Rome IV functional dyspepsia** - epigastric pain syndrome vs postprandial distress syndrome."],
        ["Aetiology & risk factors", "**H. pylori (90% DU, 70% GU) and NSAIDs/low-dose aspirin**; steroids, SSRIs, anticoagulants add bleed risk; smoking, alcohol; GERD - **obesity, hiatus hernia**, late heavy meals; Indian H. pylori seroprevalence **60-80%**."],
        ["Pathophysiology", "Antral H. pylori -> **low somatostatin -> high gastrin and acid** -> duodenal gastric metaplasia -> **DU**; corpus gastritis -> atrophy -> **Correa cascade** -> GU, cancer, MALToma; NSAID -> **COX-1 block -> loss of PGE2/PGI2**; GERD -> **TLESRs** + acid pocket."],
        ["Key history (OPD)", "Pain timing (DU **2 am, relieved by food**; GU worse with food), heartburn/regurgitation frequency, **alarm features (dysphagia, weight loss, vomiting, bleeding, anaemia)**, NSAIDs incl. ayurvedic powders, past eradication, family history of gastric cancer, cardiac symptoms."],
        ["Key examination", "Usually normal; **pallor, weight, postural drop**, Virchow node, epigastric mass, **succussion splash** (outlet obstruction), rigidity with absent liver dullness (perforation), PR for melaena."],
        ["Minimal investigations", "**UBT or stool antigen** (off PPI **2 weeks**, antibiotics/bismuth **4 weeks**); **no serology**; Hb +/- ferritin; **endoscopy for alarm features or new dyspepsia at 40-45+ (India)**; biopsy every GU; pH-impedance only for refractory/pre-surgery."],
        ["Diagnostic criteria", "GERD - typical symptoms 2+ days/week or **LA B-D** on endoscopy; functional dyspepsia - **3 months symptoms, onset 6 months earlier, normal endoscopy**; ulcer - endoscopic mucosal break 5 mm or more."],
        ["Treatment - first line", "**PPI 30-60 min before breakfast** (omeprazole 20, pantoprazole 40, esomeprazole 40 mg): DU 4 weeks, GU/GERD 8 weeks; **H. pylori - bismuth quadruple 14 days**: PPI BD + bismuth 120 mg QID + **tetracycline 500 mg QID + metronidazole 400-500 mg TDS**."],
        ["Escalation / second line", "Twice-daily PPI for LA C-D, Barrett, extra-oesophageal; **vonoprazan 20 mg** (erosive); **vonoprazan 20 mg BD + amoxicillin 1 g TDS 14 days** (ACG 2024); failed bismuth -> **levofloxacin 500 mg OD + amoxicillin 1 g BD + PPI BD 14 days**; 2 failures -> culture-guided."],
        ["Devices / procedures", "Raise **head end of bed 15-20 cm on blocks**, left lateral sleep, no meal within 3 h of lying; endoscopic dual therapy for bleeding; dilatation for outlet obstruction; fundoplication for PPI-uncontrolled regurgitation."],
        ["Special groups", "**Pregnancy - alginate first**, then PPI (omeprazole); **no misoprostol or tetracycline**; child omeprazole **10 mg (10-19 kg), 20 mg (20 kg+)**; clopidogrel - **pantoprazole**; elderly on NSAID - PPI cover; famotidine halve dose if CrCl under 50."],
        ["Complications", "**Bleeding** (posterior DU -> gastroduodenal artery), **perforation** (free gas in 75%), **gastric outlet obstruction** (hypochloraemic hypokalaemic alkalosis, paradoxical aciduria), stricture, **Barrett -> adenocarcinoma**, long-term PPI harms (low Mg, B12, C. difficile, fractures)."],
        ["Red flags & referral", "Haematemesis/melaena, progressive dysphagia, weight loss, persistent vomiting, mass, **iron deficiency**, new dyspepsia at 40-45+, exertional epigastric pain (**do ECG**); refer after 2 eradication failures or 8 weeks of BD PPI failure."],
        ["Follow-up & monitoring", "Review **4-8 weeks** and step down; **test of cure 4 weeks after antibiotics, 2 weeks off PPI**; re-scope GU at **8-12 weeks** and LA C-D after healing; Barrett surveillance **5 years (under 3 cm) / 3 years (3 cm+)**; review every PPI at 8 weeks."],
        ["Prevention / national programme", "PPI gastroprotection with NSAIDs if **age 65+, past ulcer, aspirin/anticoagulant/steroid/SSRI**; test-and-treat before long-term aspirin; screen and eradicate in first-degree relatives of gastric cancer; safe water and hygiene."],
        ["Latest guideline change", "No change needed in this pass - Maastricht VI 2022, ACG H. pylori 2024, ACG GERD 2022 and Lyon 2.0 remain current; **7-day clarithromycin triple is obsolete**."],
        ["Exam one-liners", "PPI before food, not after dinner; **black stools on bismuth are not melaena**; ranitidine withdrawn (NDMA) - write famotidine; serology useless in India; every GU biopsied; pantoprazole with clopidogrel."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Dyspepsia in the OPD - the exam algorithm",
        caption: "Alarm features and age decide endoscopy; otherwise test and treat.",
        steps: [
          { label: "Dyspepsia 4 weeks or more", detail: "Check drugs (NSAID, aspirin), ECG if cardiac risk" },
          { label: "Alarm feature or age 40-45+?", detail: "Dysphagia, weight loss, bleeding, anaemia, vomiting, mass", tone: "decision" },
          { label: "Yes - urgent endoscopy with biopsy", detail: "Biopsy every gastric ulcer; RUT plus histology", tone: "warn" },
          { label: "No - test and treat H. pylori", detail: "UBT or stool antigen; off PPI 2 weeks, antibiotics 4 weeks" },
          { label: "Positive - bismuth quadruple 14 days", detail: "PPI BD + bismuth + tetracycline + metronidazole" },
          { label: "Negative - PPI 4-8 weeks", detail: "Prokinetic if postprandial distress" },
          { label: "Confirm cure and step down", detail: "Test of cure at 4 weeks; PPI review at 8 weeks", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "H. pylori eradication ladder (India)",
        caption: "Always 14 days; always confirm cure.",
        steps: [
          { label: "First line: bismuth quadruple", detail: "PPI BD, bismuth 120 mg QID, tetracycline 500 mg QID, metronidazole 400-500 mg TDS x 14 d" },
          { label: "Alternative first line", detail: "Vonoprazan 20 mg BD + amoxicillin 1 g TDS x 14 d; or concomitant quadruple if no bismuth" },
          { label: "Second line: levofloxacin triple", detail: "Levofloxacin 500 mg OD + amoxicillin 1 g BD + PPI BD x 14 d" },
          { label: "Two failures: culture-guided", detail: "Endoscopy, culture or molecular resistance testing", tone: "warn" },
          { label: "Proven cure", detail: "UBT/stool antigen 4 weeks after therapy, 2 weeks off PPI", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "GERD vs functional dyspepsia vs cardiac pain",
        columns: ["Feature", "GERD", "Functional dyspepsia", "Cardiac (inferior MI/angina)"],
        rows: [
          ["Site", "Retrosternal burning rising up", "Epigastric pain or fullness", "Epigastric or retrosternal pressure"],
          ["Trigger", "Large meals, bending, lying", "Meals (PDS), fasting (EPS)", "Exertion, stress"],
          ["Associated", "Regurgitation, cough, hoarseness", "Early satiety, bloating", "Sweating, breathlessness"],
          ["Key test", "PPI trial; endoscopy LA grade", "Normal endoscopy, H. pylori negative", "ECG, troponin"],
          ["Treatment", "Lifestyle + PPI 8 weeks", "PPI or prokinetic, amitriptyline", "Emergency referral"],
        ],
      },
    ],
  },

  "gastro-hepatology-acute-diarrhoea": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - acute diarrhoea and dysentery",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**3 or more loose/watery stools in 24 h, under 14 days**; **persistent** 14 days or more; **chronic** 4 weeks or more; **dysentery = visible blood** in stool."],
        ["Relevant classification", "**IMNCI: no / some / severe dehydration -> Plan A / B / C**; clinical type - acute watery, dysentery, persistent, diarrhoea with SAM; weight loss under 5% mild, 5-10% moderate, over 10% severe."],
        ["Aetiology & risk factors", "Rotavirus, norovirus, **ETEC**, V. cholerae, **Shigella**, Campylobacter, Salmonella, **E. histolytica**, Giardia, preformed toxins (S. aureus, B. cereus); unsafe water, no handwashing, malnutrition, no rotavirus/measles vaccine."],
        ["Pathophysiology", "Cholera toxin -> **Gs-alpha ADP-ribosylation -> cAMP -> CFTR chloride secretion** -> rice-water stool; **SGLT1 (2 Na + 1 glucose) intact -> ORS works**; Shigella invasion -> ulcers, Shiga toxin -> **HUS**; stool loss -> ECF depletion, **NAGMA, hypokalaemia**."],
        ["Key history (OPD)", "Stool number, volume, **blood**, vomiting, **urine output (none 6-8 h)**, fever, food 1-6 h earlier (toxin), cluster and water source, drugs (antibiotics - C. difficile), feeding, vaccines, sick-day drugs in adults."],
        ["Key examination", "**General condition, eyes, thirst, skin pinch (over 2 s = very slow)**, pulse, CRT, Kussmaul breathing, weight, **MUAC under 11.5 cm / oedema (SAM)**, abdomen for ileus or surgical cause."],
        ["Minimal investigations", "**None for most watery diarrhoea**; stool microscopy for dysentery (**trophozoites with ingested RBCs**), hanging drop/culture for cholera; electrolytes, creatinine, glucose if severe; CBC, smear, creatinine if HUS suspected."],
        ["Diagnostic criteria", "Some dehydration = **2 or more of**: restless, sunken eyes, drinks eagerly, skin pinch slow; severe = **2 or more of**: lethargic, sunken eyes, drinks poorly, pinch very slow."],
        ["Treatment - first line", "**Low-osmolarity ORS 245 mOsm/L**: Plan A after each stool (**50-100 mL under 2 y, 100-200 mL 2-10 y**); Plan B **75 mL/kg over 4 h**; **zinc 10 mg (2-6 months) / 20 mg (over 6 months) for 14 days**; continue feeding."],
        ["Escalation / second line", "Plan C **RL 100 mL/kg**: under 12 m **30 mL/kg in 1 h then 70 in 5 h**; older **30 in 30 min then 70 in 2.5 h**; NG 20 mL/kg/h if no IV; dysentery **azithromycin 10 mg/kg x 3 d** (or cipro 15 mg/kg BD x 3 d, IMNCI); cholera **doxycycline 300 mg single / azithromycin 20 mg/kg**."],
        ["Devices / procedures", "ORS: **1 sachet in 1 L clean water, discard after 24 h**, cup and spoon; intraosseous line if IV fails in 90 s; cholera cot to measure output; **chlorinate to residual 0.5 mg/L** in outbreaks."],
        ["Special groups", "**SAM - ReSoMal 5 mL/kg every 30 min x 2 h, then 5-10 mL/kg/h**; pregnancy - azithromycin, avoid tetracyclines and quinolones; adults - **hold metformin, SGLT2i, ACEi/ARB, diuretics, NSAIDs**; single-dose ondansetron 0.15 mg/kg in vomiting child over 6 months."],
        ["Complications", "Shock, **AKI**, hypo/hypernatraemia (seizures), **hypokalaemia (ileus)**, NAGMA, hypoglycaemia, **HUS** after STEC/Shigella, toxic megacolon, GBS after Campylobacter, malnutrition."],
        ["Red flags & referral", "Lethargy, cannot drink, weak pulse, no urine 6-8 h, convulsions, **blood in stool under 2 months**, SAM, suspected HUS, surgical abdomen, persistent diarrhoea, adult over 50 with weight loss or nocturnal stools."],
        ["Follow-up & monitoring", "Plan A review in **5 days**, dysentery in **2 days** (change antibiotic, think amoebiasis); reassess every 1-2 h in Plan B and 15-30 min in Plan C; zinc adherence 14 days; extra meal a day for 2 weeks."],
        ["Prevention / national programme", "**STOP Diarrhoea Campaign** (ORS-zinc co-pack, ORS-zinc corners), **rotavirus vaccine 6, 10, 14 weeks (UIP)**, measles-rubella, vitamin A, exclusive breastfeeding, WASH; **notify clusters via IDSP-IHIP**."],
        ["Latest guideline change", "No change needed in this pass - WHO 2024 diarrhoea guideline, IMNCI and STOP Diarrhoea remain current."],
        ["Exam one-liners", "Death is from dehydration, not the bug; **ORS Na 75, Cl 65, glucose 75, K 20, citrate 10**; no antibiotics for watery diarrhoea; **loperamide never under 12 or in dysentery**; follow metronidazole with a luminal amoebicide."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Diarrhoea: assess, classify, plan",
        caption: "IMNCI sequence written as an answer.",
        steps: [
          { label: "Assess general condition, eyes, thirst, skin pinch", detail: "Plus weight, MUAC, blood in stool, duration" },
          { label: "2+ severe signs?", detail: "Lethargic, drinks poorly, pinch over 2 s", tone: "decision" },
          { label: "Plan C - IV Ringer lactate 100 mL/kg", detail: "Under 12 m: 30 in 1 h, 70 in 5 h; older 30 in 30 min, 70 in 2.5 h", tone: "warn" },
          { label: "2+ some signs - Plan B", detail: "ORS 75 mL/kg over 4 h, then reassess" },
          { label: "No dehydration - Plan A at home", detail: "ORS per stool, zinc 14 days, feed, danger signs" },
          { label: "Blood, cholera or SAM?", detail: "Azithromycin / doxycycline / ReSoMal", tone: "decision" },
          { label: "Rehydrated, feeding, zinc completed", detail: "Review 5 days (2 days for dysentery)", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Watery diarrhoea vs cholera vs bacillary vs amoebic dysentery",
        columns: ["Feature", "Viral/ETEC watery", "Cholera", "Shigella", "Amoebic"],
        rows: [
          ["Stool", "Watery", "Rice-water, huge volume", "Small, blood and pus", "Bloody mucoid, offensive"],
          ["Fever", "Low or none", "None", "High", "Little"],
          ["Key test", "None", "Hanging drop, culture", "Pus cells, culture", "Trophozoites with RBCs"],
          ["Drug", "ORS + zinc only", "Doxycycline 300 mg single", "Azithromycin 3 days", "Metronidazole then diloxanide"],
          ["Danger", "Dehydration", "Rapid shock", "HUS, toxic megacolon", "Liver abscess"],
        ],
      },
    ],
  },

  "gastro-hepatology-jaundice": {
    checked: "2026-10",
    updated: [
      "AASLD DILI 2023: causality supported by RUCAM or its evidence-based electronic revision RECAM.",
    ],
    master: {
      heading: "Master revision table - approach to jaundice and DILI",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Yellow sclerae/skin from bilirubin; normal **under 1.2 mg/dL**, clinically visible at **2.5-3 mg/dL**; **conjugated** if direct over 15-20% of total (or over 1 mg/dL); **ALF = INR 1.5+ with encephalopathy within 26 weeks**."],
        ["Relevant classification", "**Prehepatic, hepatocellular, cholestatic** (intra/extrahepatic); **R factor = (ALT/ULN)/(ALP/ULN): 5+ hepatocellular, 2 or less cholestatic, 2-5 mixed**; O'Grady hyperacute / acute / subacute ALF."],
        ["Aetiology & risk factors", "India: **hepatitis E and A, alcohol, drugs (ATT, herbal - giloy, ashwagandha), malaria, leptospirosis, gallstones, malignant obstruction**; haemolysis, G6PD, Gilbert; pregnancy (ICP, AFLP, HELLP)."],
        ["Pathophysiology", "Haem -> biliverdin -> **unconjugated bilirubin (albumin-bound, not in urine)** -> **UGT1A1 conjugation** -> **MRP2 excretion (rate-limiting)** -> gut urobilinogen; obstruction -> **dark urine, pale stool, itch, vitamin K malabsorption**."],
        ["Key history (OPD)", "**Urine and stool colour first**, prodrome, pain/fever (**Charcot triad**), itch, weight loss, **6-month drug and herbal history**, alcohol (AUDIT-C), faeco-oral vs parenteral risk, monsoon fever exposures, pregnancy, family history."],
        ["Key examination", "Icterus in daylight, scratch marks, **asterixis, fetor**, bruising, CLD stigmata, liver size/shrinking span, **Courvoisier gallbladder**, Murphy sign, splenomegaly, ascites, KF rings, eschar, calf tenderness."],
        ["Minimal investigations", "Bilirubin (total/direct), **ALT, AST, ALP, GGT, albumin, INR**, CBC with smear and retics, urine bilirubin/urobilinogen, **USG for duct dilatation (CBD over 6 mm)**; IgM HAV, IgM HEV, HBsAg + IgM anti-HBc, anti-HCV; febrile panel."],
        ["Diagnostic criteria", "**DILI: ALT 5x ULN, or ALP 2x ULN, or ALT 3x + bilirubin over 2x ULN**; temporal relation 5-90 days, exclusion, dechallenge; **RUCAM or RECAM** for causality; **Hy's law** - hepatocellular injury with jaundice ~10% mortality."],
        ["Treatment - first line", "Treat the cause; **stop the drug and all herbals**, normal diet, no alcohol; itch - **cholestyramine 4 g before and after breakfast (max 16 g)**; vitamin K **10 mg slow IV x 3 days** if INR high; paracetamol **max 2-3 g/day**."],
        ["Escalation / second line", "Itch ladder: **rifampicin 150-300 mg -> naltrexone 12.5->50 mg -> sertraline 75-100 mg**; paracetamol overdose **NAC 150 mg/kg/1 h, 50 mg/kg/4 h, 100 mg/kg/16 h**; NAC in early non-paracetamol ALF; cholangitis **pip-taz 4.5 g + ERCP**."],
        ["Devices / procedures", "Dilated ducts -> **MRCP/EUS, ERCP for therapy**; urgent biliary drainage in severe cholangitis; neonatal **Kasai before 45-60 days**; avoid FFP to correct INR in ALF."],
        ["Special groups", "**ATT hepatitis**: stop H, R, Z if **ALT over 5x ULN (asymptomatic) or 3x with symptoms/jaundice**; reintroduce at ALT under 2x - **rifampicin first, isoniazid after 3-7 days, usually no pyrazinamide**; pregnancy - ICP bile acids 10+ (100+ = stillbirth risk); neonate jaundice under 24 h pathological."],
        ["Complications", "**Acute liver failure** (cerebral oedema, hypoglycaemia, sepsis), cholangitis, coagulopathy, fat-soluble vitamin deficiency, kernicterus (neonate), ACLF from herbal DILI."],
        ["Red flags & referral", "**Encephalopathy, INR 1.5+**, rising INR with falling ALT, hypoglycaemia, persistent vomiting, cholangitis, jaundice in pregnancy, painless jaundice with weight loss, pale stools beyond 14 days in a baby."],
        ["Follow-up & monitoring", "Bilirubin, ALT, **INR weekly** till falling; enzymes normal by 8-12 weeks, persistence over 6 months -> chronic work-up; ATT LFT if symptoms, 2-4 weekly in high risk; G6PD assay **2-3 months after haemolysis**."],
        ["Prevention / national programme", "Safe water (HAV/HEV), hepatitis B vaccine, **report DILI to PvPI**, NTEP baseline LFT in high risk, notify jaundice clusters via **IDSP-IHIP**."],
        ["Latest guideline change", "**AASLD DILI 2023**: causality by **RUCAM or the electronic revision RECAM**; other thresholds unchanged."],
        ["Exam one-liners", "Urine and stool colour sort the box; **INR and albumin measure function, ALT measures injury**; AST:ALT over 2 = alcohol; ALT over 1000 = virus, drug, ischaemia; INR corrected by vitamin K = cholestasis."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Jaundice work-up in five moves",
        caption: "History box -> LFT pattern -> ultrasound -> targeted tests -> severity.",
        steps: [
          { label: "Urine and stool colour", detail: "Normal urine = prehepatic; dark urine + pale stool = cholestatic" },
          { label: "LFT pattern and R factor", detail: "R 5+ hepatocellular, 2 or less cholestatic", tone: "decision" },
          { label: "Ultrasound: ducts dilated?", detail: "CBD over 6 mm -> MRCP/EUS, ERCP for therapy", tone: "decision" },
          { label: "Non-dilated: serology and drug history", detail: "IgM HAV/HEV, HBsAg, anti-HCV, febrile panel, RUCAM/RECAM" },
          { label: "INR 1.5+ or encephalopathy?", detail: "ALF - refer same day to transplant centre", tone: "warn" },
          { label: "Treat cause, stop drugs, review weekly", detail: "INR, bilirubin, ALT until falling", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "ATT-induced hepatitis: stop and reintroduce (NTEP)",
        steps: [
          { label: "ALT over 5x ULN, or 3x with symptoms/jaundice", detail: "Stop isoniazid, rifampicin, pyrazinamide together", tone: "warn" },
          { label: "Severe TB: holding regimen", detail: "Levofloxacin + ethambutol + streptomycin/amikacin" },
          { label: "ALT under 2x ULN, bilirubin normal", detail: "Restart rifampicin (with ethambutol)" },
          { label: "After 3-7 days add isoniazid", detail: "Check ALT before each addition" },
          { label: "Usually omit pyrazinamide", detail: "Extend regimen duration accordingly", tone: "good" },
        ],
      },
    ],
  },

  "gastro-hepatology-viral-hepatitis": {
    checked: "2026-10",
    updated: [
      "AASLD-IDSA HBV 2025: treat immune-tolerant patients over 40 or with inflammation/fibrosis; shared decision-making for grey zone; stop NA only after HBsAg loss.",
      "AASLD-IDSA HBV 2025: strong recommendation for TDF or TAF from 28 weeks of pregnancy when HBV DNA over 200000 IU/mL regardless of HBeAg.",
    ],
    master: {
      heading: "Master revision table - viral hepatitis A to E and NVHCP",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Hepatocellular inflammation by hepatotropic viruses A-E; **chronic = HBsAg or HCV RNA positive beyond 6 months**; ALF = **INR 1.5+ plus encephalopathy**."],
        ["Relevant classification", "**Enteric A, E (never chronic) vs parenteral B, C, D (chronic)**; chronic HBV phases (EASL 2025) - HBeAg+/- chronic infection vs chronic hepatitis, occult; incubation A 15-50, E 15-60, B 45-180, C 15-150 days."],
        ["Aetiology & risk factors", "A, E - contaminated water, monsoon outbreaks; B - **perinatal (90% chronic)**, sexual, unsafe injections, dialysis; C - unsafe injections, transfusion (Punjab, Haryana); D - superinfection of HBsAg carrier; HBsAg India **1-2%**."],
        ["Pathophysiology", "**CD8 T-cell killing** of infected hepatocytes -> necrosis -> conjugated bilirubin reflux; HBV **cccDNA in nucleus** (NA suppress, rarely cure); HCV cytoplasmic, no reservoir -> **DAA cure**; HEV pregnancy -> ALF."],
        ["Key history (OPD)", "Prodrome, dark urine, water source and clusters, injections, transfusion, tattoos, sex, family HBV/HCC, pregnancy, herbal drugs, alcohol, **planned immunosuppression (rituximab, chemo)**, danger symptoms."],
        ["Key examination", "Icterus, hydration, **capillary glucose**, tender liver, **shrinking liver span**, asterixis, fetor, bleeding, CLD stigmata (acute-on-chronic), extrahepatic signs (purpura, PCT)."],
        ["Minimal investigations", "LFT + **INR**; **IgM anti-HAV, IgM anti-HEV, HBsAg + IgM anti-HBc, anti-HCV -> HCV RNA**; new HBsAg+: HBeAg, **HBV DNA, ALT, platelets, APRI/elastography**, anti-HDV, HIV, creatinine."],
        ["Diagnostic criteria", "**IgM anti-HBc = acute/window**; anti-HBs alone = vaccinated; anti-HBs + anti-HBc = resolved; **APRI over 2 cirrhosis, over 0.5 significant fibrosis**; elastography **over 12.5 kPa cirrhosis**; **SVR12 = HCV cure**."],
        ["Treatment - first line", "Acute A/E supportive (normal diet, **ondansetron 4 mg**, paracetamol **max 2 g**); HBV **TDF 300 mg OD** (TAF 25 mg, entecavir 0.5 mg empty stomach); HCV **sofosbuvir 400 + velpatasvir 100 mg OD x 12 weeks**."],
        ["Escalation / second line", "WHO 2024 treat: **fibrosis (APRI over 0.5)**, or **DNA over 2000 + ALT high** (ULN **30 men / 19 women**), co-infection, FHx HCC; **AASLD-IDSA 2025 adds immune-tolerant over 40**; decompensated HCV - **SOF-VEL + ribavirin 12 weeks**; HDV - peginterferon, bulevirtide."],
        ["Devices / procedures", "HBV vaccine **20 microgram deltoid 0, 1, 6 months** (never buttock), anti-HBs **10 mIU/mL+** protective; HBIG **0.06 mL/kg within 24 h** after needle-stick; ICU and transplant centre for ALF."],
        ["Special groups", "**Pregnancy HBsAg+: TDF from 24-28 weeks if DNA 200000+ or HBeAg+** (AASLD 2025: TDF/TAF from 28 weeks if DNA over 200000); newborn **HBIG 100 IU + birth dose within 12 h**; HEV third trimester **15-25% maternal mortality**; children 3+ get DAAs."],
        ["Complications", "ALF, cholestatic/relapsing HAV, chronic HBV/HCV -> **cirrhosis, HCC (even without cirrhosis in HBV)**, **HBV reactivation under rituximab**, extrahepatic (PAN, MGN, cryoglobulinaemia), amiodarone-sofosbuvir bradycardia."],
        ["Red flags & referral", "Encephalopathy, **INR 1.5+**, hypoglycaemia, persistent vomiting, bleeding, pregnancy with jaundice, shrinking liver; HBsAg+ before chemo/rituximab; patient who stopped tenofovir; refer decompensation, co-infection, DAA failure."],
        ["Follow-up & monitoring", "Acute: weekly bilirubin, ALT, INR; **HBsAg at 6 months**; on NA - DNA 3 then 6-12 monthly, **creatinine/phosphate on TDF**; **HCC USG 6-monthly** in cirrhosis and high-risk HBV; HCV RNA 12 weeks after therapy."],
        ["Prevention / national programme", "**NVHCP (28 July 2018)** - free tests and drugs, HCV elimination by 2030; **birth dose within 24 h + pentavalent 6, 10, 14 weeks**; antenatal HBsAg screening; safe injections, blood screening; no HEV vaccine in India."],
        ["Latest guideline change", "**AASLD-IDSA HBV 2025**: treat immune-tolerant over 40 or with inflammation/fibrosis, shared decision in grey zone, **stop NA only after HBsAg loss**, **TDF/TAF from 28 weeks if DNA over 200000** (strong)."],
        ["Exam one-liners", "A and E never chronic; **prognosis from INR and sensorium, not ALT**; anti-HCV stays positive after cure; HBeAg-negative is not inactive (precore mutants); never amiodarone with sofosbuvir; check HBsAg before DAAs."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "New HBsAg-positive patient: who gets tenofovir",
        caption: "WHO 2024 expanded criteria with AASLD-IDSA 2025 additions.",
        steps: [
          { label: "HBsAg positive", detail: "HBeAg, HBV DNA, ALT, platelets, APRI/elastography, anti-HDV, HIV, HCV" },
          { label: "Cirrhosis or APRI over 0.5 / LSM over 7 kPa?", detail: "Treat regardless of DNA and ALT", tone: "decision" },
          { label: "DNA over 2000 IU/mL with raised ALT?", detail: "ALT ULN 30 men, 19 women", tone: "decision" },
          { label: "Co-infection, FHx HCC, immunosuppression, age over 40", detail: "Treat (AASLD 2025: immune-tolerant over 40)" },
          { label: "Not meeting criteria", detail: "ALT 6-12 monthly, DNA yearly; shared decision in grey zone" },
          { label: "TDF 300 mg OD long-term", detail: "Never stop without specialist; stop only after HBsAg loss", tone: "good" },
        ],
      },
      {
        kind: "flow",
        heading: "Preventing mother-to-child HBV - exam version",
        steps: [
          { label: "Antenatal HBsAg in every pregnancy", detail: "NVHCP universal screening" },
          { label: "HBsAg positive: check DNA/HBeAg", detail: "DNA 200000+ or HBeAg+ (or test unavailable)", tone: "decision" },
          { label: "Tenofovir from 24-28 weeks", detail: "TDF 300 mg OD till delivery; ALT 3 months after stopping" },
          { label: "Newborn within 12 hours", detail: "HBIG 0.5 mL (100 IU) + birth-dose vaccine, different sites" },
          { label: "Complete pentavalent, test at 9-12 months", detail: "HBsAg and anti-HBs; breastfeeding allowed", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Hepatitis B serology at a glance",
        columns: ["State", "HBsAg", "IgM anti-HBc", "Total anti-HBc", "Anti-HBs"],
        rows: [
          ["Acute", "+", "+", "+", "-"],
          ["Chronic", "+ over 6 months", "-", "+", "-"],
          ["Window", "-", "+", "+", "-"],
          ["Resolved", "-", "-", "+", "+"],
          ["Vaccinated", "-", "-", "-", "+ (10 mIU/mL or more)"],
        ],
      },
    ],
  },

  "gastro-hepatology-chronic-liver-disease": {
    checked: "2026-10",
    updated: [
      "Baveno VIII 2026: CSPH ruled in by LSM 25 kPa or more (viral, alcohol, non-obese MASLD) or spleen stiffness over 55 kPa; not reliable in obese MASLD.",
      "Baveno VIII 2026: NSBB (preferably carvedilol) for CSPH upgraded to a strong recommendation; no NSBB without CSPH; no TIPS to prevent decompensation.",
      "ACG HE 2026: rifaximin added to lactulose in acute overt HE and for recurrence on lactulose; start 14 days before elective TIPS for 6 months.",
      "ACG HE 2026: titrate lactulose with Bristol scale to 2-3 soft stools; high-volume PEG an inpatient alternative; lactulose for covert HE.",
      "EASL-EASD-EASO MASLD 2024 / US FDA 2025: resmetirom and semaglutide 2.4 mg approved for non-cirrhotic MASH F2-F3.",
    ],
    master: {
      heading: "Master revision table - chronic liver disease and cirrhosis",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Diffuse **fibrosis with regenerative nodules** -> portal hypertension + hepatocellular failure; **cACLD = LSM over 15 kPa**; **decompensation = ascites, variceal bleed, overt HE or jaundice** (median survival **over 12 years -> about 2 years**)."],
        ["Relevant classification", "**Child-Pugh A 5-6, B 7-9, C 10-15**; **MELD-Na 15+ -> transplant referral**; **West Haven HE grades**; **CSPH (Baveno VIII): LSM 25 kPa+ or spleen stiffness over 55 kPa**; APASL ACLF."],
        ["Aetiology & risk factors", "India: **alcohol 30-50%**, HBV, HCV, rising **MASLD**; Wilson (under 40), autoimmune, Budd-Chiari, cryptogenic; alcohol over **40-60 g/day men, 20 g/day women for 10 years**."],
        ["Pathophysiology", "Injury -> **TGF-beta -> stellate cell -> collagen** -> nodules -> **HVPG 10+ (CSPH), 12+ bleeds** -> splanchnic NO vasodilation -> low effective volume -> **RAAS/ADH -> ascites, hyponatraemia, HRS**; gut ammonia -> astrocyte glutamine -> HE."],
        ["Key history (OPD)", "Alcohol in grams and last drink, viral and metabolic risks, drugs (NSAIDs, sedatives, herbals), distension, melaena, **sleep reversal/confusion (family)**, fever with ascites, cramps, transplant support."],
        ["Key examination", "Asterixis, palmar erythema, spider naevi (5+), gynaecomastia, **splenomegaly**, shifting dullness, caput medusae (flow away from umbilicus), oedema, wasting, KF rings, BP (SBP under 90 limits NSBB)."],
        ["Minimal investigations", "CBC (**platelets under 150000**), LFT, INR, creatinine, Na, K; HBsAg, anti-HCV; **USG with portal Doppler**; **diagnostic tap every new ascites/admission - SAAG 1.1+ = portal HTN, PMN 250+ = SBP**; elastography/FIB-4; endoscopy unless LSM under 20 + platelets over 150000 or on NSBB."],
        ["Diagnostic criteria", "Clinical/imaging/LSM over 15 kPa (cACLD); **CSPH LSM 25 kPa+ (not in obese MASLD) or SSM over 55 kPa**; SBP PMN 250/mm3; AKI creatinine rise 0.3 mg/dL in 48 h or 50% in 7 days."],
        ["Treatment - first line", "**Stop cause (abstinence, antivirals)**; salt **5 g/day**, no fluid restriction unless Na under 125; protein **1.2-1.5 g/kg + late-evening snack**; **spironolactone 100 mg + furosemide 40 mg (100:40)** up to 400/160; **carvedilol 6.25 mg -> 6.25 mg BD for CSPH (strong, Baveno VIII)**."],
        ["Escalation / second line", "Tense ascites - **LVP + albumin 6-8 g/L removed** (over 5 L); SBP - **cefotaxime 2 g 8-hourly + albumin 1.5 g/kg day 1, 1 g/kg day 3**; HRS - **terlipressin 1 mg 4-6-hourly + albumin**; HE - **lactulose to 2-3 soft stools + rifaximin 550 mg BD**; AH - prednisolone 40 mg if DF 32+."],
        ["Devices / procedures", "Paracentesis at any INR; **band ligation**; TIPS for refractory ascites/bleeding (**not to prevent first decompensation**); rifaximin **14 days before elective TIPS for 6 months**; transplant at MELD 15+."],
        ["Special groups", "Alcohol use disorder - **baclofen 5->10-25 mg TDS**, acamprosate if renal OK, avoid disulfiram/naltrexone; withdrawal - **lorazepam**; MASH F2-F3 - **resmetirom or semaglutide 2.4 mg weekly**; paracetamol **2-3 g/day** safe; avoid NSAIDs, aminoglycosides, benzodiazepines."],
        ["Complications", "Ascites, **SBP**, **HRS-AKI**, variceal bleed, **HE**, hyponatraemia, HCC (1-6%/year), PVT, hepatopulmonary syndrome, portopulmonary HTN, sarcopenia, ACLF."],
        ["Red flags & referral", "Fever/pain/confusion with ascites (tap today), melaena, oliguria, **Na under 125 or K over 6**, grade 3-4 HE, ACLF after binge or HBV flare, new liver mass, cirrhosis under 40."],
        ["Follow-up & monitoring", "3-6 monthly CBC, LFT, INR, creatinine, Child-Pugh/MELD-Na; electrolytes **within 1 week of diuretic change**; **USG +/- AFP 6-monthly for HCC**; endoscopy 2-yearly (no varices) if not on NSBB; depression and relapse screen."],
        ["Prevention / national programme", "**NVHCP** free HBV/HCV treatment, HBV vaccine, **NP-NCD** metabolic screening, alcohol brief interventions; vaccinate hepatitis A/B, influenza, pneumococcal."],
        ["Latest guideline change", "**Baveno VIII 2026**: CSPH by LSM 25+ or **SSM over 55 kPa**, NSBB/carvedilol a **strong** recommendation, no TIPS for prevention; **ACG HE 2026**: rifaximin with lactulose in acute OHE, Bristol-guided lactulose, PEG alternative; **semaglutide FDA-approved for MASH (2025)**."],
        ["Exam one-liners", "Tap every new ascites; **SAAG 1.1+ = portal HTN**; PMN 250+ = SBP; **never restrict protein**; ammonia does not diagnose HE - find the precipitant; Child A 5-6 / B 7-9 / C 10-15; MELD 15 = refer."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Compensated cirrhosis: Baveno VIII risk pathway",
        caption: "Non-invasive tests decide beta-blocker and endoscopy.",
        steps: [
          { label: "Chronic liver disease: elastography + platelets", detail: "LSM under 10 rules out cACLD; over 15 kPa = cACLD" },
          { label: "CSPH present?", detail: "LSM 25+ (not obese MASLD) or spleen stiffness over 55 kPa", tone: "decision" },
          { label: "CSPH - start carvedilol", detail: "6.25 mg OD -> 6.25 mg BD; strong recommendation; no screening EGD needed" },
          { label: "No CSPH - no beta-blocker", detail: "Treat cause; repeat NITs at 12 months if indeterminate" },
          { label: "Stop/hold NSBB if", detail: "SBP under 90, Na under 130, AKI, SBP or HRS", tone: "warn" },
          { label: "Decompensation prevented", detail: "6-monthly USG for HCC; remove the cause", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Ascites management ladder",
        steps: [
          { label: "Salt 5 g/day, stop NSAIDs/ACEi", detail: "No fluid restriction unless Na under 125" },
          { label: "Spironolactone 100 mg (+ furosemide 40 mg)", detail: "Weight loss 0.5 kg/day (1 kg with oedema)" },
          { label: "Step up 100:40 every 3-5 days", detail: "Max spironolactone 400 mg, furosemide 160 mg" },
          { label: "Tense ascites: LVP + albumin", detail: "6-8 g albumin per litre removed if over 5 L" },
          { label: "Refractory ascites", detail: "Serial LVP, TIPS referral, transplant assessment", tone: "warn" },
        ],
      },
      {
        kind: "ladder",
        heading: "Hepatic encephalopathy (ACG 2026)",
        steps: [
          { label: "Find and correct the precipitant", detail: "Bleed, infection/SBP, constipation, over-diuresis, low K/Na, sedatives", tone: "warn" },
          { label: "Lactulose 25 mL every 1-2 h until stool", detail: "Then titrate to 2-3 soft stools (Bristol scale); enema if comatose" },
          { label: "Add rifaximin 550 mg BD", detail: "Suggested in acute OHE; recommended for recurrence on lactulose" },
          { label: "Inpatient alternative: high-volume PEG", detail: "Instead of lactulose in overt HE" },
          { label: "Protein 1.2-1.5 g/kg + late snack", detail: "No ammonia-guided therapy; refer for transplant", tone: "good" },
        ],
      },
    ],
  },

  "gastro-hepatology-gi-bleeding": {
    checked: "2026-10",
    updated: [
      "ESGE 2026: no emergent (6 h) or urgent (12 h) endoscopy for non-variceal bleeding unless unstable despite resuscitation; GBS 1 or less outpatient.",
      "ESGE 2026: IV metoclopramide when erythromycin unavailable before endoscopy in severe bleeding.",
      "ESGE 2026: OTS clip or haemostatic forceps monotherapy acceptable for high-risk stigmata; haemostatic powder not first-line monotherapy; OTS clip for rebleeding, then embolisation.",
    ],
    master: {
      heading: "Master revision table - upper and lower GI bleeding",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**UGIB** proximal to **ligament of Treitz** - haematemesis, coffee grounds, melaena; **LGIB** distal - haematochezia; **shock index (HR/SBP) over 1** = instability."],
        ["Relevant classification", "**Variceal vs non-variceal**; **Glasgow-Blatchford** pre-endoscopy (0-1 outpatient, 2+ admit, 7+ needs intervention); **Forrest Ia, Ib, IIa, IIb, IIc, III**; Oakland 8 or less for LGIB discharge."],
        ["Aetiology & risk factors", "India: **peptic ulcer 40-50%, varices 20-30%**, erosions, Mallory-Weiss, cancer, Dieulafoy; LGIB - piles, fissure, **diverticula**, angiodysplasia, cancer, IBD, amoebic/TB colitis, Meckel in children; NSAIDs, aspirin, anticoagulants, SSRIs."],
        ["Pathophysiology", "Posterior DU erodes **gastroduodenal artery**; platelets fail **below pH 6**, pepsin lyses clot below pH 5 -> PPI; HVPG 12+ -> variceal rupture; over-transfusion raises portal pressure; blood digestion -> **urea up, creatinine normal**."],
        ["Key history (OPD)", "Volume and colour, syncope, **liver disease, anticoagulant/antiplatelet, heart disease**, NSAIDs and powders, retching first (Mallory-Weiss), weight loss, bowel habit change over 40, aortic graft."],
        ["Key examination", "Pulse, BP **lying and standing**, CRT, urine output, **shock index**, pallor, CLD stigmata and splenomegaly, abdominal mass, **DRE in every patient** + proctoscopy, emphysema (Boerhaave)."],
        ["Minimal investigations", "CBC, group and crossmatch, **urea, creatinine**, LFT, INR, glucose; **GBS** at bedside; endoscopy **within 12 h (varices/unstable) or 24 h**; **CT angiography first in unstable LGIB**; colonoscopy for stable LGIB; ECG/troponin in elderly."],
        ["Diagnostic criteria", "Upper source likely with melaena, **urea:creatinine over 30**, haematemesis; GBS 0-1 very low risk; Forrest Ia-IIa high-risk stigmata needing endoscopic therapy."],
        ["Treatment - first line", "Two 16-18G cannulae, crystalloid, **transfuse at Hb under 7 (target 7-9; 8 in IHD)**; non-variceal - **pantoprazole 80 mg IV**; variceal - **terlipressin 2 mg 4-hourly + ceftriaxone 1 g OD up to 7 days**; no tranexamic acid."],
        ["Escalation / second line", "Post-therapy **PPI 80 mg then 8 mg/h x 72 h (or 40 mg IV BD)**, oral BD to day 14; rebleed -> **repeat endoscopy (OTS clip) -> TAE -> surgery**; variceal - **pre-emptive TIPS within 72 h (Child C 10-13, B over 7 active)**, rescue TIPS, balloon/stent bridge 24 h."],
        ["Devices / procedures", "**Erythromycin 250 mg IV 30-120 min before EGD** (metoclopramide if unavailable); **band ligation** oesophageal varices, **cyanoacrylate** fundal; ulcer - **adrenaline + clip/thermal, or OTS clip / forceps monotherapy**; powder only as rescue."],
        ["Special groups", "Warfarin - **vitamin K 5-10 mg IV + 4F-PCC 25-50 IU/kg**; DOAC - PCC 50 IU/kg, **idarucizumab 5 g** (dabigatran), andexanet; **secondary-prevention aspirin continue/restart in 3-5 days**; DAPT - discuss P2Y12 with cardiologist; child - Meckel, intussusception."],
        ["Complications", "Hypovolaemic shock, demand ischaemia, rebleeding, aspiration, **HE and infection in cirrhotics**, AKI, transfusion overload, iron deficiency."],
        ["Red flags & referral", "Pulse over 100, **SBP under 100**, syncope, cirrhosis signs, anticoagulants, brisk red bleeding with shock (upper source), rectal bleeding over 40 with habit change or IDA, Boerhaave, aorto-enteric fistula."],
        ["Follow-up & monitoring", "Hb at 2-4 weeks and 3 months, **iron 3 months after Hb normal**, **confirm H. pylori cure**, re-scope GU at 8-12 weeks; post-variceal - **NSBB + EVL every 1-4 weeks to obliteration**, then 3-6 then 6-12 monthly EGD."],
        ["Prevention / national programme", "PPI with high-risk NSAID use, H. pylori test-and-treat before long-term aspirin, **carvedilol for CSPH (Baveno VIII)**, variceal screening, NG12-style colorectal referral."],
        ["Latest guideline change", "**ESGE 2026**: avoid urgent (12 h or less) endoscopy unless unstable after resuscitation; **OTS clip/forceps monotherapy allowed**; powder not first-line; **IV metoclopramide** if no erythromycin; OTS clip for rebleeding."],
        ["Exam one-liners", "Resuscitate before diagnosis; **Hb 7 trigger**; every cirrhotic bleeder gets **ceftriaxone + terlipressin**; pre-endoscopy PPI never delays endoscopy; adrenaline alone is never enough; **no tranexamic acid (HALT-IT)**; no FFP to correct INR."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Upper GI bleed: first hour to endoscopy",
        caption: "What the family physician does before the ambulance leaves.",
        steps: [
          { label: "ABC, two large-bore lines, bloods", detail: "CBC, crossmatch, urea, creatinine, INR, LFT" },
          { label: "Calculate Glasgow-Blatchford", detail: "0-1 outpatient early EGD; 2+ admit", tone: "decision" },
          { label: "Cirrhosis known or suspected?", detail: "Ascites, splenomegaly, jaundice, alcohol", tone: "decision" },
          { label: "Variceal: terlipressin + ceftriaxone", detail: "Terlipressin 2 mg IV 4-hourly; ceftriaxone 1 g OD; EGD within 12 h", tone: "warn" },
          { label: "Non-variceal: pantoprazole 80 mg IV", detail: "EGD within 24 h; urgent only if unstable after resuscitation" },
          { label: "Restrictive transfusion, reverse anticoagulants", detail: "Hb under 7; PCC for warfarin/DOAC" },
          { label: "Endoscopic haemostasis", detail: "EVL / glue; ulcer dual or OTS clip therapy", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Variceal vs peptic ulcer bleed",
        columns: ["Feature", "Variceal", "Peptic ulcer"],
        rows: [
          ["Clue", "CLD stigmata, alcohol, HBV/HCV", "NSAIDs, epigastric pain, H. pylori"],
          ["Drug before EGD", "Terlipressin or octreotide + ceftriaxone", "Pantoprazole 80 mg IV"],
          ["Endoscopy timing", "Within 12 h", "Within 24 h"],
          ["Endoscopic therapy", "Band ligation; glue for fundal", "Adrenaline + clip/thermal, or OTS clip"],
          ["Failure", "Pre-emptive or rescue TIPS", "Repeat EGD, embolisation, surgery"],
          ["Secondary prevention", "NSBB + EVL to obliteration", "Eradicate H. pylori, stop NSAID, PPI"],
        ],
      },
      {
        kind: "ladder",
        heading: "Rebleeding after ulcer haemostasis",
        steps: [
          { label: "High-dose PPI 72 h", detail: "80 mg bolus + 8 mg/h, or 40 mg IV BD" },
          { label: "Clinical rebleed: repeat endoscopy", detail: "OTS clip preferred" },
          { label: "Fails: transcatheter arterial embolisation", detail: "Interventional radiology", tone: "warn" },
          { label: "Unavailable or fails: surgery", detail: "Under-run the vessel" },
          { label: "Then oral PPI BD to day 14, eradicate H. pylori", detail: "Test of cure 4 weeks later", tone: "good" },
        ],
      },
    ],
  },

  "gastro-hepatology-ibs-constipation": {
    checked: "2026-10",
    updated: [
      "Rome V 2026: IBS = abdominal pain or discomfort on at least 3 days a month for 3 months, not continuous, linked to defecation or change in stool frequency/form (Rome IV needed pain 1 day a week).",
      "Rome V 2026: separate short clinical criteria from research criteria; functional constipation criteria unchanged.",
    ],
    master: {
      heading: "Master revision table - IBS and chronic constipation",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**IBS** - disorder of gut-brain interaction; **positive diagnosis, not exclusion**; **functional constipation** - 2+ of straining, hard stools, incomplete evacuation, blockage, manual manoeuvres, **under 3 SBM/week**."],
        ["Relevant classification", "**Rome V (2026)**: pain or **discomfort 3+ days a month for 3 months**, not continuous, linked to defecation or stool change; subtypes by **Bristol on abnormal days - IBS-C, IBS-D, IBS-M, IBS-U**; constipation - normal, slow transit, **dyssynergia**."],
        ["Aetiology & risk factors", "Post-infectious (10% after bacterial gastroenteritis), stress, anxiety, FODMAPs, lactose, bile acid diarrhoea (25-30% IBS-D); constipation - **drugs (opioids, iron, CCBs, anticholinergics)**, hypothyroidism, hypercalcaemia, low fibre/fluid."],
        ["Pathophysiology", "Gut-brain axis -> **visceral hypersensitivity** (mast cells, TRPV1) + central amplification -> altered motility; FODMAP -> osmotic water + gas; dyssynergia -> **paradoxical puborectalis contraction**."],
        ["Key history (OPD)", "Pain/discomfort relation to defecation, **Bristol chart**, **alarm features (onset over 45-50, bleeding, weight loss, nocturnal symptoms, anaemia, FHx CRC/IBD/coeliac)**, diet diary, drugs, manual manoeuvres, PHQ-2/GAD-2."],
        ["Key examination", "Weight, pallor, thyroid, abdominal mass, **Carnett sign**, perianal inspection, **DRE with push manoeuvre** for dyssynergia, neurological signs, child's spine."],
        ["Minimal investigations", "**CBC, CRP, tTG-IgA + total IgA**; **faecal calprotectin under 50 microgram/g excludes IBD** (over 200 colonoscopy); stool for Giardia/Entamoeba in India; constipation - **TSH, calcium, glucose**; manometry + balloon expulsion if refractory."],
        ["Diagnostic criteria", "Rome V clinical criteria + no alarm features + normal minimal tests; IBS-C over 25% Bristol 1-2 and under 25% 6-7 (IBS-D reverse); balloon not expelled in 1-2 min = dyssynergia; transit over 20% markers at day 5 = slow transit."],
        ["Treatment - first line", "Explain and reassure; regular meals, fluid **1.5-2 L**, **soluble fibre (ispaghula 3.5 g OD-BD)**, avoid bran; pain - **mebeverine 135 mg TDS** or **peppermint oil 0.2 mL TDS**; IBS-D - **loperamide 2 mg**; constipation - **macrogol 13.8-17 g OD**."],
        ["Escalation / second line", "**Low-FODMAP 4-6 weeks then reintroduction**; **amitriptyline 10 mg -> 30-50 mg at night**; **rifaximin 550 mg TDS x 14 days** (IBS-D); stimulant **senna 7.5-15 mg / bisacodyl 5-10 mg**; **linaclotide 290 microgram** (IBS-C), **prucalopride 2 mg** (1 mg if over 65)."],
        ["Devices / procedures", "**Footstool posture (knees above hips)**, toilet 15-30 min after breakfast; **biofeedback for dyssynergia**; gut-directed CBT/hypnotherapy; disimpaction with **macrogol 8 sachets/day up to 3 days** or enemas."],
        ["Special groups", "Child - **macrogol 1-1.5 g/kg/day x 3-6 days then 0.4-0.8 g/kg/day for 2+ months**; pregnancy - ispaghula, lactulose, macrogol, short senna; elderly - macrogol + senna, avoid Mg and phosphate enemas in CKD; opioids - **naloxegol 25 mg**; linaclotide not under 2 years."],
        ["Complications", "Impaction with overflow, fissure, haemorrhoids, rectal prolapse, poor quality of life, doctor-shopping, missed organic disease (TB, coeliac, cancer)."],
        ["Red flags & referral", "**Onset over 45-50**, rectal bleeding, IDA, weight loss, nocturnal symptoms, mass, **calprotectin over 200**, absolute constipation with vomiting (obstruction); refer refractory constipation after 3-6 months."],
        ["Follow-up & monitoring", "Review **4-6 weeks**, one change at a time; laxatives/antispasmodics 4-week trial, neuromodulators 3 months (continue 6-12 months); **re-evaluate, do not re-label** when pattern changes."],
        ["Prevention / national programme", "Fibre 25-30 g/day with fluids, activity 150 min/week (yoga), early treatment of dysentery, avoid unnecessary constipating drugs."],
        ["Latest guideline change", "**Rome V 2026**: **discomfort returns, frequency 3 days a month** (not weekly), pain must not be continuous, **clinical vs research criteria** separated; functional constipation unchanged."],
        ["Exam one-liners", "IBS is a positive diagnosis; **nocturnal symptoms are never IBS**; lactulose bloats IBS; **cathartic colon is a myth**; DRE push test finds dyssynergia; low-dose amitriptyline is for gut pain - say so."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "IBS: making the positive diagnosis (Rome V)",
        steps: [
          { label: "Pain or discomfort 3+ days a month x 3 months", detail: "Not continuous; linked to defecation or stool change" },
          { label: "Alarm features?", detail: "Over 45-50, bleeding, weight loss, nocturnal, anaemia, FHx", tone: "decision" },
          { label: "Yes - colonoscopy / investigate", detail: "Not an IBS label", tone: "warn" },
          { label: "No - minimal tests", detail: "CBC, CRP, tTG-IgA, calprotectin, stool for Giardia" },
          { label: "Subtype by Bristol on abnormal days", detail: "IBS-C, IBS-D, IBS-M, IBS-U" },
          { label: "Name it, explain, treat dominant symptom", detail: "Review 4-6 weeks", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Chronic constipation ladder",
        steps: [
          { label: "Stop constipating drugs; fibre + fluid + posture", detail: "Fibre 25-30 g, footstool, toilet after breakfast" },
          { label: "Bulk: ispaghula 3.5 g OD-BD", detail: "In 200-250 mL water; not in impaction or opioids" },
          { label: "Osmotic: macrogol 13.8-17 g OD (to 3 sachets)", detail: "Lactulose 15-30 mL cheaper but bloats" },
          { label: "Stimulant: senna 7.5-15 mg / bisacodyl 5-10 mg", detail: "At night; safe long-term" },
          { label: "Secretagogue/prokinetic", detail: "Linaclotide 145-290 microgram, prucalopride 2 mg" },
          { label: "Refractory: manometry, biofeedback", detail: "Dyssynergia needs biofeedback, not laxatives", tone: "warn" },
        ],
      },
      {
        kind: "branch",
        heading: "IBS drug by subtype",
        root: "Dominant symptom",
        arms: [
          { label: "Pain", steps: ["Mebeverine 135 mg TDS", "Peppermint oil 0.2 mL TDS", "Amitriptyline 10-50 mg at night"] },
          { label: "IBS-D", steps: ["Loperamide 2 mg", "Rifaximin 550 mg TDS x 14 days", "Ondansetron 4-8 mg", "Bile acid sequestrant"] },
          { label: "IBS-C", steps: ["Ispaghula", "Macrogol", "Linaclotide 290 microgram", "SSRI if anxiety"] },
        ],
      },
    ],
  },

  "gastro-hepatology-acute-abdomen-pancreatitis": {
    checked: "2026-10",
    updated: [
      "WSES 2025 (JAMA Surg 2026): clinical scores recommended for risk stratification - AIR score or Adult Appendicitis Score preferred over Alvarado.",
      "WSES 2025: antibiotics-first for imaging-confirmed uncomplicated appendicitis (appendicolith or diameter 7 mm or more predicts failure); post-operative antibiotics 2-3 days in complicated appendicitis.",
      "WSES 2025: after non-operative treatment of appendiceal abscess, colonoscopy/CT for neoplasm; no routine interval appendicectomy.",
    ],
    master: {
      heading: "Master revision table - acute abdomen and acute pancreatitis",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Acute abdomen** - pain under 1 week needing urgent decision on surgery/admission; **acute pancreatitis = 2 of 3**: typical pain, **lipase/amylase 3x ULN or more**, imaging."],
        ["Relevant classification", "Mechanism - inflammation, perforation, obstruction, vascular, colic, gynaecological, medical mimics; **revised Atlanta: mild, moderately severe (organ failure under 48 h or local complications), severe (over 48 h)**; **AIR/Adult Appendicitis Score, Alvarado 7+**; Tokyo 2018 cholangitis."],
        ["Aetiology & risk factors", "Pancreatitis - **gallstones 40-50%, alcohol 30-35%**, TG over 1000 mg/dL, hypercalcaemia, drugs (azathioprine, valproate, GLP-1 RA), post-ERCP, scorpion sting; appendicitis - faecolith; elderly, diabetic, pregnant present atypically."],
        ["Pathophysiology", "Pancreas: **intra-acinar trypsinogen -> trypsin** -> autodigestion -> IL-6/TNF -> **SIRS, capillary leak, haemoconcentration** -> hypoperfusion -> necrosis; appendix: obstruction -> ischaemia -> **visceral (umbilical) -> parietal (RIF) pain** -> perforation 24-72 h."],
        ["Key history (OPD)", "SOCRATES, sudden vs gradual, migration to RIF, vomiting/distension/absolute constipation order, **LMP and pregnancy in every woman**, alcohol and gallstones, drugs, previous surgery, AF, diabetes, last meal."],
        ["Key examination", "Vitals + **NEWS2/qSOFA**, restless (colic) vs still (peritonitis), guarding, rigidity, McBurney/Rovsing/psoas/obturator, Murphy, **all hernial orifices**, pulsatile mass, bowel sounds, PR/PV, testes; Grey Turner, Cullen."],
        ["Minimal investigations", "**UPT, glucose/ketones, urine dipstick, ECG over 40**; CBC, urea, creatinine, **lipase**, LFT, calcium, TG, CRP, lactate; **erect CXR** (free gas 70-80%); **USG first** (gallstones in every pancreatitis); **CT at 72-96 h** only if doubt or not improving."],
        ["Diagnostic criteria", "Pancreatitis 2 of 3; severity - **SIRS over 48 h, Hct over 44%, BUN over 20 rising, CRP over 150 at 48 h, BISAP 3+**; organ failure **modified Marshall 2+**; appendicitis - AIR/AAS or Alvarado 7+ refer, 5-6 image/observe."],
        ["Treatment - first line", "Resuscitate, **analgesia never withheld** (paracetamol 1 g 6-hourly, **morphine 0.1 mg/kg titrated**, diclofenac 75 mg for colic); pancreatitis **RL 10 mL/kg bolus if hypovolaemic then 1.5 mL/kg/h**, reassess, **oral low-fat diet in 24-48 h**, **no prophylactic antibiotics**."],
        ["Escalation / second line", "Infected necrosis - **meropenem 1 g 8-hourly** + **step-up drainage after 4 weeks**; cholangitis - pip-taz + **ERCP within 24 h**; HTG - **insulin 0.1-0.3 U/kg/h + dextrose**; appendicitis - laparoscopic appendicectomy or **antibiotics-first if uncomplicated** (WSES 2025)."],
        ["Devices / procedures", "NG tube for vomiting/obstruction, catheter in shock, **same-admission cholecystectomy** after mild gallstone pancreatitis, ERCP only with cholangitis, early lap cholecystectomy within 72 h for cholecystitis, post-op antibiotics **2-3 days** in complicated appendicitis."],
        ["Special groups", "Pregnancy - **UPT, ectopic**, appendix displaced upward, no NSAIDs after 20 weeks; elderly/diabetic - blunted signs, ECG, mesenteric ischaemia; child - intussusception, malrotation, torsion; HTG pancreatitis - fenofibrate after."],
        ["Complications", "Pancreatitis: **ARDS, AKI, hypocalcaemia**, necrosis, infected necrosis, pseudocyst/WON, abdominal compartment syndrome, diabetes, exocrine insufficiency; appendicitis: perforation, abscess; obstruction: strangulation."],
        ["Red flags & referral", "Shock, rigidity, free gas, **positive UPT with pain or faint**, pain out of proportion (ischaemia), Charcot/Reynolds, irreducible hernia, pulsatile mass, pancreatitis with persistent SIRS or rising urea."],
        ["Follow-up & monitoring", "Undiagnosed but well - review 4-6 h or next morning with safety-netting; post-pancreatitis **4-6 weeks**, HbA1c yearly, faecal elastase; idiopathic over 40 - EUS/MRCP; after NOM of appendiceal abscess - **colonoscopy/CT**."],
        ["Prevention / national programme", "Alcohol brief intervention, smoking cessation, cholecystectomy for symptomatic stones, TG control under 500 mg/dL, low threshold referral in elderly and pregnant."],
        ["Latest guideline change", "**WSES 2025 appendicitis**: **AIR or Adult Appendicitis Score** for risk stratification, antibiotics-first for uncomplicated disease (appendicolith/7 mm+ predicts failure), **2-3 day post-op antibiotics** in complicated, colonoscopy after abscess NOM."],
        ["Exam one-liners", "Triage, not diagnosis; **UPT in every woman, ECG over 40**; enzyme height does not predict severity; **moderate fluids (WATERFALL)**; feed early; no prophylactic antibiotics; ERCP only with cholangitis."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Acute abdomen at first contact",
        steps: [
          { label: "Vitals, NEWS2, analgesia", detail: "Paracetamol 1 g + titrated morphine; never withhold" },
          { label: "Shock, peritonitis, free gas?", detail: "Or positive UPT with faint, pulsatile mass, ischaemia", tone: "decision" },
          { label: "Yes - transfer now, resuscitate en route", detail: "Two lines, O2, NG, antibiotics if septic", tone: "warn" },
          { label: "Bedside: UPT, glucose/ketones, dipstick, ECG", detail: "Lipase, CBC, CRP, USG" },
          { label: "Specific surgical diagnosis?", detail: "Appendicitis (AIR/AAS), cholecystitis, pancreatitis - same-day transfer", tone: "decision" },
          { label: "Well and undiagnosed", detail: "Review in 4-6 h with written safety-net", tone: "good" },
        ],
      },
      {
        kind: "flow",
        heading: "Acute pancreatitis: first 72 hours",
        steps: [
          { label: "2 of 3: pain, lipase 3x, imaging", detail: "No CT needed if pain + enzyme" },
          { label: "Severity markers", detail: "SIRS, Hct over 44%, BUN rising, BISAP 3+", tone: "decision" },
          { label: "Moderate goal-directed Ringer lactate", detail: "10 mL/kg if hypovolaemic, then 1.5 mL/kg/h; avoid over 4 L/24 h" },
          { label: "Analgesia + oral low-fat diet in 24-48 h", detail: "No prophylactic antibiotics, no octreotide" },
          { label: "Cholangitis?", detail: "ERCP within 24 h; otherwise no ERCP", tone: "warn" },
          { label: "Find cause, same-admission cholecystectomy", detail: "USG, TG, calcium; CT at 72-96 h if not improving", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Revised Atlanta severity",
        columns: ["Grade", "Organ failure", "Complications", "Mortality / care"],
        rows: [
          ["Mild", "None", "None", "Under 1%; ward"],
          ["Moderately severe", "Transient, under 48 h", "Local or systemic may be present", "Low; HDU"],
          ["Severe", "Persistent, over 48 h", "Usually present", "20-30%; ICU tertiary"],
        ],
      },
    ],
  },

  "gastro-hepatology-liver-abscess": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - amoebic and pyogenic liver abscess",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Localised collection of necrotic material or pus in the liver; **amoebic (commonest in India) vs pyogenic** decides drugs alone vs drainage."],
        ["Relevant classification", "**Amoebic** - single, posterosuperior right lobe, sterile anchovy-sauce pus; **pyogenic** - biliary (commonest, multiple), portal, arterial, direct, cryptogenic."],
        ["Aetiology & risk factors", "ALA - **E. histolytica, men 20-50, alcohol (toddy, country liquor)**; PLA - **E. coli, Klebsiella (hypervirulent K1/K2 in diabetics)**, Strep milleri, anaerobes; biliary stones, stents, malignancy, appendicitis."],
        ["Pathophysiology", "Cysts (resist chlorination) -> colonic trophozoites (**Gal/GalNAc lectin, amoebapores**) -> **portal vein -> right lobe** -> liquefactive necrosis; trophozoites only in the wall; capsule stretch -> RUQ pain, diaphragm -> shoulder tip."],
        ["Key history (OPD)", "Fever, **RUQ pain to right shoulder worse on breathing**, subacute 1-2 weeks (ALA) vs rigors (PLA), alcohol, diabetes, biliary disease, cough/anchovy sputum, chest pain (left lobe), visual symptoms (Klebsiella)."],
        ["Key examination", "**Tender hepatomegaly**, **intercostal tenderness**, right basal dullness, jaundice (biliary PLA), epigastric mass (left lobe), pericardial rub, peritonism, fundi in diabetics."],
        ["Minimal investigations", "CBC (leucocytosis), **raised ALP**, glucose, **USG - hypoechoic lesion abutting capsule**, CXR (**raised right hemidiaphragm**), **amoebic IgG over 90% sensitive**, blood cultures in PLA, CT for complicated/multiple, hydatid serology before aspirating septate cyst."],
        ["Diagnostic criteria", "Clinical + USG lesion + **amoebic serology/antigen/PCR** (ALA) or **positive blood/aspirate culture** (PLA); negative amoebic serology argues strongly against ALA."],
        ["Treatment - first line", "ALA - **metronidazole 750 mg TDS x 7-10 days** (500 mg IV 8-hourly if toxic; child 35-50 mg/kg/day) or **tinidazole 2 g OD x 3-5 days**, then **paromomycin 25-35 mg/kg/day x 7 days or diloxanide 500 mg TDS x 10 days**."],
        ["Escalation / second line", "Uncertain type - **ceftriaxone 2 g OD + metronidazole 500 mg 8-hourly**; ESBL risk - **pip-taz 4.5 g or meropenem 1 g**; PLA **4-6 weeks total (2-3 IV)**, oral amoxiclav or cipro + metronidazole; **source control (ERCP)**."],
        ["Devices / procedures", "Drain ALA if **no response in 72-96 h, over 5-10 cm, left lobe, impending rupture, secondary infection**; **needle aspiration under 5 cm, catheter drainage larger/PLA**; surgery for rupture with peritonitis or failed drainage; chest drain for empyema."],
        ["Special groups", "Pregnancy - metronidazole after first trimester (or earlier if benefit outweighs); severe hepatic impairment - reduce metronidazole; **diabetic Klebsiella - eye check, intravitreal antibiotics** for endophthalmitis; no alcohol 72 h after metronidazole."],
        ["Complications", "**Pleuropulmonary (commonest)** - effusion, empyema, hepatobronchial fistula; peritoneal rupture; **pericardial rupture from left lobe (deadliest)**; septic shock, metastatic Klebsiella, IVC thrombosis."],
        ["Red flags & referral", "Sudden abdominal pain with shock, breathlessness/anchovy sputum, left-lobe abscess with chest pain or raised JVP, rigors with jaundice, no improvement at 72-96 h, abscess over 5-10 cm, visual symptoms, septic shock."],
        ["Follow-up & monitoring", "Review at **72 h**, then weekly; **do not treat the ultrasound** - cavity resolves in 3-12 months; confirm luminal course; **colonoscopy after Klebsiella/Strep milleri abscess**; control diabetes."],
        ["Prevention / national programme", "**Boil or filter water** (cysts resist chlorination), handwashing, sanitation, treat cyst passers and food handlers with luminal agent, notify clusters via **IDSP-IHIP**."],
        ["Latest guideline change", "No change needed in this pass - management by Harrison 22e, Sabiston 22e and ICMR STW 2022 remains current."],
        ["Exam one-liners", "Young alcohol-using man + fever + tender liver + intercostal tenderness = ALA; **anchovy-sauce pus is sterile**; never stop at metronidazole alone; pyogenic needs **drainage + 4-6 weeks + source control**; pericardial rupture deadliest."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Liver abscess: diagnose and decide drainage",
        steps: [
          { label: "Fever + RUQ pain + tender liver", detail: "Intercostal tenderness, raised right hemidiaphragm" },
          { label: "USG + amoebic serology + blood cultures", detail: "Glucose, LFT (ALP), CBC", tone: "decision" },
          { label: "Unclear type or septic", detail: "Ceftriaxone 2 g OD + metronidazole 500 mg IV 8-hourly", tone: "warn" },
          { label: "Amoebic: metronidazole 750 mg TDS 7-10 d", detail: "Expect response in 72-96 h" },
          { label: "No response, over 5-10 cm, left lobe, rupture risk", detail: "Aspirate (under 5 cm) or catheter drainage", tone: "decision" },
          { label: "Luminal agent after the course", detail: "Paromomycin 7 days or diloxanide 10 days", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Amoebic vs pyogenic liver abscess",
        columns: ["Feature", "Amoebic", "Pyogenic"],
        rows: [
          ["Patient", "Young man, alcohol", "Older, diabetic, biliary disease"],
          ["Number", "Single, right lobe", "Often multiple (biliary)"],
          ["Pus", "Sterile anchovy sauce", "Foul, culture positive"],
          ["Key test", "Amoebic IgG, antigen/PCR", "Blood and aspirate culture, CT for source"],
          ["Treatment", "Metronidazole then luminal agent", "Drainage + 4-6 weeks antibiotics + source control"],
        ],
      },
    ],
  },
};

export default revision;
