import type { RevisionSet } from "./index";

const revision: RevisionSet = {
  "infectious-fever-acute-undifferentiated-fever": {
    checked: "2026-10",
    updated: [
      "SSC 2026: screen for sepsis with NEWS2, MEWS or SIRS rather than qSOFA as a single tool.",
      "SSC 2026: at least 30 mL/kg balanced crystalloid (Ringer lactate over saline) guided by dynamic measures; MAP 65 (60-65 acceptable at 65 years or older); lactate repeated to guide resuscitation.",
    ],
    master: {
      heading: "Master revision table - Acute undifferentiated fever",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Fever (oral **38.0 C or more**) of **under 14 days with no localising focus** after history, examination and bedside tests - a working label to be replaced by a cause in 5-7 days."],
        ["Relevant classification", "**Syndromic - fever plus what**: alone, thrombocytopenia, rash, jaundice, altered sensorium, ARDS, AKI; by duration - acute under 2 weeks, prolonged 2-3 weeks, **PUO over 3 weeks**."],
        ["Aetiology and risk factors", "**Malaria, dengue, scrub typhus, enteric fever, leptospirosis** (plus influenza) - 60-70% of diagnosed cases; peaks July-November; 30-40% stay undiagnosed (mostly viral)."],
        ["Pathophysiology", "PAMPs -> TLRs -> **IL-1, IL-6, TNF** -> OVLT COX-2 -> **PGE2 -> EP3** -> raised hypothalamic set-point -> vasoconstriction, rigors -> fever; paracetamol lowers PGE2 without platelet effect."],
        ["Key history (OPD)", "**Day of illness**, fever pattern, focus symptoms, exposure (grass - scrub; floodwater - lepto; travel - malaria), cluster cases, drugs (NSAIDs, antibiotics), LMP, immune status, warning symptoms."],
        ["Key examination", "Vitals with pulse pressure, SpO2, capillary refill; **undress and hunt the eschar**; conjunctival suffusion, calf tenderness, rash, nodes, spleen, hidden foci; **relative bradycardia**; repeat daily."],
        ["Minimal investigations", "Day 1-3: **CBC with haematocrit, malaria RDT plus smear, dengue NS1, urine**; **2 blood cultures before antibiotic**; **IgM ELISA from day 5**; lactate 2 or more abnormal, 4 or more high risk; **no single Widal**."],
        ["Treatment - general", "Oral fluids 2.5-3 L/day, urine at least 6-hourly, tepid sponging, **no IM injections**, written safety-net, **review in 24-48 h** especially at defervescence."],
        ["Treatment - first line", "**Paracetamol 500-1000 mg 6-hourly, max 4 g/day** (child 15 mg/kg); **no NSAIDs**; no antibiotic for 3 days if well; then **doxycycline 100 mg BD x 7 days** (child 2.2 mg/kg BD) or **azithromycin 500 mg OD x 5 days** in pregnancy."],
        ["Escalation / second line", "Enteric suspected: **azithromycin 1 g OD x 7 days** or cefixime 20 mg/kg/day x 14 days; sepsis: **ceftriaxone 2 g IV + doxycycline** within 1 h; **meropenem 1 g 8-hourly** only for hospital-onset, ESBL or failure."],
        ["Emergency", "Sepsis: lactate, cultures, antibiotics within 1 h, **at least 30 mL/kg balanced crystalloid**, noradrenaline for **MAP 65**; dengue shock - titrated 5-10 or 20 mL/kg, not the sepsis block; drowsy - **check glucose**."],
        ["Special groups", "Pregnancy: paracetamol, azithromycin not doxycycline, admit dengue or malaria; child: doxycycline short course safe; febrile neutropenia (MASCC under 21) - **piperacillin-tazobactam 4.5 g 6-hourly** within 1 h."],
        ["Complications", "Shock, bleeding, ARDS, AKI, encephalopathy, hepatitis, DIC - each points to a specific tropical fever (lepto AKI with low K; scrub ARDS; falciparum coma)."],
        ["Red flags and referral", "SBP under 90 or pulse pressure 20 or less, bleeding, SpO2 under 94%, altered sensorium, oliguria, jaundice, purpura, pregnancy, infancy, neutropenia, **fever beyond 7 days without diagnosis**."],
        ["Follow-up", "Review daily or 48-hourly; CBC daily from day 3 if dengue possible; **scrub settles within 48 h of doxycycline**, enteric in 5-7 days - non-response means wrong diagnosis or complication."],
        ["Prevention / programme", "Mosquito protection, weekly dry day, safe water, TCV; **notify malaria, dengue, scrub, lepto, enteric clusters, JE/AES on IDSP-IHIP**."],
        ["Latest guideline change", "**SSC 2026**: NEWS2/MEWS/SIRS over qSOFA for screening, balanced crystalloids and dynamic measures, MAP 65 (60-65 in older adults), prolonged beta-lactam infusion."],
        ["Exam one-liners", "Write the day of illness; IgM before day 5 is a wasted negative; ceftriaxone covers none of scrub, malaria or dengue; Faget sign - enteric, lepto, rickettsia; paracetamol only till dengue excluded."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "AUF in the OPD: day-of-illness work-up",
        steps: [
          { label: "Fix the day of illness; vitals and red flags", detail: "Shock, bleeding, SpO2 under 94%, drowsy, oliguria, jaundice", tone: "decision" },
          { label: "Any red flag - sepsis or severe tropical fever", detail: "Cultures, antibiotics in 1 h, admit; NEWS2 not qSOFA", tone: "warn" },
          { label: "Undress, search eschar and focus", detail: "Axilla, groin, waist, under breasts; calves, eyes, spleen" },
          { label: "Day 1-3 panel", detail: "CBC + haematocrit, malaria RDT + smear, NS1, urine" },
          { label: "Day 5 onwards add IgM ELISA", detail: "Dengue MAC, scrub, leptospira; blood culture before antibiotic" },
          { label: "Well, no focus - paracetamol and review 24-48 h", detail: "No antibiotic for 3 days; no NSAID, no IM injection" },
          { label: "Day 3-5 still febrile, tests negative", detail: "Doxycycline 100 mg BD x 7 days (azithromycin if pregnant)", tone: "decision" },
          { label: "Afebrile within 48 h - cause treated", detail: "Narrow therapy; notify on IHIP", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Empirical treatment ladder in AUF",
        steps: [
          { label: "Paracetamol only", detail: "500-1000 mg 6-hourly, max 4 g/day; child 15 mg/kg" },
          { label: "Doxycycline for scrub/lepto/rickettsia", detail: "100 mg BD x 7 days; child 2.2 mg/kg BD" },
          { label: "Azithromycin - pregnancy or suspected enteric", detail: "500 mg OD x 5 days (scrub); 1 g OD x 7 days (enteric)" },
          { label: "Sepsis with no focus", detail: "Ceftriaxone 2 g IV OD + doxycycline 100 mg BD within 1 hour", tone: "warn" },
          { label: "Hospital-onset, ESBL or failure at 72 h", detail: "Meropenem 1 g IV 8-hourly; re-culture", tone: "warn" },
        ],
      },
      {
        kind: "compare",
        heading: "Haemogram clues in Indian fever",
        columns: ["Pattern", "Think of", "Discriminator"],
        rows: [
          ["Leucopenia + low platelets", "Dengue, malaria, enteric", "NS1, smear, blood culture"],
          ["Neutrophilia + low platelets", "Leptospirosis, scrub, sepsis", "Eschar, calf tenderness, low K AKI"],
          ["Bilirubin far above transaminases", "Leptospirosis, falciparum", "MAT/IgM, smear"],
          ["Transaminases 100-500, little jaundice", "Dengue, scrub, typhoid", "Day of illness, eschar"],
        ],
      },
    ],
  },

  "infectious-fever-dengue": {
    checked: "2026-10",
    updated: [
      "CDSCO July 2026: TAK-003 (Qdenga) approved as India's first dengue vaccine, ages 4-60, two doses 3 months apart (private sector).",
      "WHO 2025 arboviral guideline: crystalloid rather than colloid for IV fluid; capillary refill time to guide fluid; colloid kept only for refractory shock.",
      "WHO 2025: suggests against prophylactic platelets in severe dengue with count under 50,000 and no bleeding (NCVBDC threshold under 10,000 retained).",
    ],
    master: {
      heading: "Master revision table - Dengue",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Acute febrile illness from **dengue virus (flavivirus, DENV 1-4)** spread by day-biting **Aedes aegypti**; incubation **4-10 days**; confirmed by **NS1, IgM seroconversion or RT-PCR**."],
        ["Classification", "**WHO 2009 (retained 2025)**: dengue without warning signs, with warning signs, **severe dengue**; disposal **Group A home, B admit, C emergency**; old DHF I-IV still in programme documents."],
        ["Warning signs (7)", "**Abdominal pain, persistent vomiting, fluid accumulation, mucosal bleeding, lethargy/restlessness, liver over 2 cm, rising haematocrit with rapid platelet fall**."],
        ["Pathophysiology", "Secondary infection -> **ADE via Fc-gamma receptors** -> cytokines + **NS1 sheds glycocalyx** -> capillary leak at **defervescence (day 3-7)** for 24-48 h -> haemoconcentration -> narrow pulse pressure -> shock -> bleeding/DIC."],
        ["Key history (OPD)", "**Day of illness**, retro-orbital pain, myalgia, warning-sign questions, oral intake and **urine in last 6 h**, NSAID or IM injection use, comorbidity, pregnancy, social risk, past dengue."],
        ["Key examination", "Pulse, **pulse pressure (20 or less = compensated shock)**, capillary refill over 2 s, tender liver, effusion, ascites, bleeding; tourniquet test 10 petechiae per sq inch; weight for fluid."],
        ["Minimal investigations", "**CBC + haematocrit baseline, daily from day 3** (4-6-hourly in B and C); **NS1 day 1-5, IgM MAC-ELISA from day 5**; no IgG or combo cards; USG for effusion, GB wall over 3 mm."],
        ["Treatment - Group A", "Oral fluids **2.5-3 L/day**, **paracetamol 500-1000 mg 6-hourly (max 4 g)**, child 10-15 mg/kg; **no NSAIDs, steroids, IM injections, papaya leaf**; daily review from day 3."],
        ["Treatment - Group B fluids", "Crystalloid **5-7 mL/kg/h x 1-2 h, then 3-5 x 2-4 h, then 2-3 mL/kg/h**, titrated to haematocrit; stop by 24-48 h."],
        ["Escalation - shock", "Compensated: **5-10 mL/kg over 1 h**; hypotensive: **20 mL/kg over 15-30 min**; rising Hct - another crystalloid bolus (colloid only refractory); **falling Hct - blood (whole blood 10-20 or PRBC 5-10 mL/kg)**."],
        ["Blood products", "**Platelets not for a number**: bleeding, or prophylactic under 10,000 (NCVBDC); WHO 2025 against prophylaxis under 50,000 without bleeding; FFP for coagulopathy with bleeding."],
        ["Special groups", "**Pregnancy - admit**, compare with own baseline Hct; infants, over 60, diabetes, CKD, heart disease, obesity = Group B; use **ideal body weight** in the obese."],
        ["Complications", "Shock, severe bleeding, **AST/ALT 1000 or more**, encephalopathy, myocarditis, AKI, HLH; **fluid overload in recovery** (stop fluids, furosemide only after leak ends)."],
        ["Red flags and referral", "Any warning sign, pulse pressure 20 or less, SBP under 90, Hct rise 20% or more, bleeding, SpO2 under 94%, pregnancy - admit or refer after first bolus."],
        ["Follow-up and discharge", "Discharge: **afebrile 48 h without antipyretic**, stable Hct off fluids 24 h, good urine, **platelets rising above 50,000**; post-dengue fatigue for weeks."],
        ["Prevention / programme", "**Weekly dry day**, source reduction, day-time repellent, bed net in viraemic first 5 days; notify on IHIP; **Qdenga 2 doses 3 months apart, 4-60 years** (CDSCO 2026, not in UIP)."],
        ["Latest guideline change", "**WHO 2025** arboviral guideline: crystalloid over colloid, CRT-guided fluids, no steroids or immunoglobulin, no prophylactic platelets; **Qdenga approved in India July 2026**."],
        ["Exam one-liners", "Worsening at defervescence = leak, not recovery; people die of leak, not platelets; shocked with falling Hct = bleeding, give blood; NS1 early, IgM after day 5."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Dengue: from first visit to disposal",
        steps: [
          { label: "Probable dengue - fix day of illness", detail: "NS1 day 1-5, CBC + Hct baseline" },
          { label: "Warning sign, comorbidity or social risk?", detail: "7 warning signs; pregnancy, infant, over 60, CKD", tone: "decision" },
          { label: "No - Group A home care", detail: "ORS 2.5-3 L/day, paracetamol; daily CBC from day 3", tone: "good" },
          { label: "Yes - Group B admit", detail: "Crystalloid 5-7 -> 3-5 -> 2-3 mL/kg/h; Hct 4-6-hourly" },
          { label: "Shock, severe bleeding or organ failure?", detail: "Pulse pressure 20 or less, CRT over 2 s, SBP under 90", tone: "decision" },
          { label: "Group C - resuscitate", detail: "5-10 mL/kg/h compensated; 20 mL/kg in 15-30 min hypotensive", tone: "warn" },
          { label: "Recovery: stop fluids by 48 h", detail: "Discharge: afebrile 48 h, stable Hct, platelets over 50,000", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Persisting dengue shock - read the haematocrit",
        steps: [
          { label: "First crystalloid bolus", detail: "20 mL/kg over 15-30 min (hypotensive); oxygen" },
          { label: "Improved - step down", detail: "10 mL/kg/h x 1 h, then 5-7, 3-5, 2-3 mL/kg/h", tone: "good" },
          { label: "Still shocked, Hct rising", detail: "Second 10-20 mL/kg crystalloid; colloid only if refractory", tone: "decision" },
          { label: "Still shocked, Hct falling", detail: "Occult bleeding: whole blood 10-20 or PRBC 5-10 mL/kg", tone: "warn" },
          { label: "Refractory - correct ABCS, ICU", detail: "Acidosis, bleeding, calcium, sugar; inotrope after volume", tone: "warn" },
        ],
      },
    ],
  },

  "infectious-fever-malaria": {
    checked: "2026-10",
    updated: [
      "WHO 2024-2025 malaria guideline: after a near-patient G6PD test, high-dose primaquine (1 mg/kg/day x 7 days) or single-dose tafenoquine 300 mg with chloroquine are radical-cure options (not yet NCVBDC policy).",
    ],
    master: {
      heading: "Master revision table - Malaria",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Infection with **Plasmodium** spread by the **female Anopheles**; India has mainly **P. vivax and P. falciparum**; **test before treat** (bivalent RDT or smear)."],
        ["Classification", "**Uncomplicated vs severe** (any one WHO criterion, falciparum or vivax); cases classed **indigenous, imported, introduced, induced, relapsing**; goal zero indigenous cases 2027, elimination 2030."],
        ["Aetiology and risk factors", "Falciparum belt - Odisha, Chhattisgarh, Jharkhand, MP, North-East; vectors An. culicifacies (rural), **An. stephensi (urban)**, fluviatilis/minimus (forest); migrants, forest and mine workers, pregnancy, under 5."],
        ["Pathophysiology", "Sporozoite -> liver (vivax **hypnozoites** -> relapse) -> RBC cycle 48 h -> haemozoin, TNF -> paroxysm; falciparum **PfEMP1 cytoadherence** -> sequestration -> cerebral, renal, placental malaria; artesunate kills rings before sequestration."],
        ["Key history (OPD)", "Fever with rigors, travel or residence in last month (1 year for vivax), past malaria and **primaquine completion**, pregnancy (LMP), G6PD history, danger symptoms (drowsy, prostration, dark urine, breathlessness)."],
        ["Key examination", "Pallor, icterus, splenomegaly, **prostration**, GCS/Blantyre, acidotic breathing, SpO2, urine colour, bleeding, shock; **no neck stiffness** in cerebral malaria."],
        ["Minimal investigations", "**Bivalent RDT** (HRP2 + pan-pLDH) or **thick and thin smear** (gold standard); repeat 12-hourly x 48 h if negative; Hb, platelets, glucose, creatinine, bilirubin, lactate; **G6PD before 14-day primaquine**."],
        ["Severe malaria criteria", "GCS under 11 / Blantyre under 3, prostration, 2+ convulsions, **glucose under 40**, lactate 5 or more, **Hb under 7 (child under 5)**, creatinine over 3, bilirubin over 3 with high parasitaemia, pulmonary oedema, SBP under 80, **parasitaemia over 10%**."],
        ["Treatment - vivax", "**Chloroquine 25 mg/kg over 3 days (10-10-5)**, adult 600-600-300 mg; **primaquine 0.25 mg/kg daily x 14 days** (adult 15 mg); G6PD deficient **0.75 mg/kg weekly x 8 weeks**."],
        ["Treatment - falciparum", "**ACT-SP**: artesunate 4 mg/kg x 3 days + SP 25/1.25 mg/kg day 1 (adult AS 200 mg + SP 1500/75); **North-East: AL 20/120 BD x 3 days with fatty food**; + **single-dose primaquine 0.75 mg/kg (45 mg)** day 2."],
        ["Severe malaria", "**IV/IM artesunate 2.4 mg/kg (3 mg/kg if under 20 kg) at 0, 12, 24 h then daily**, minimum 24 h, then **full oral ACT**; alternatives artemether, arteether, quinine 20 mg/kg load; pre-referral rectal artesunate 10 mg/kg."],
        ["Supportive care", "Glucose 4-hourly (**25% dextrose 2 mL/kg** child), restrictive fluids (FEAST), transfuse Hb under 7 adult / under 5 child, dialysis for AKI, ceftriaxone in shock; **no steroids, mannitol, heparin**."],
        ["Special groups", "Pregnancy: **first trimester quinine (NCVBDC) or AL (WHO 2022)**, ACT in 2nd-3rd; chloroquine safe; **no primaquine in pregnancy, lactation, infants under 1 year**; IV artesunate in all trimesters."],
        ["Complications", "Cerebral malaria, hypoglycaemia, lactic acidosis, AKI, **blackwater fever**, ARDS, severe anaemia, **post-artesunate delayed haemolysis (1-3 weeks)**, splenic rupture (vivax)."],
        ["Red flags and referral", "Any severity criterion, vomiting all doses, pregnancy with falciparum, infant, high parasitaemia, no response by 48-72 h - IV artesunate and refer."],
        ["Follow-up", "Smear **day 3** (positivity suggests artemisinin partial resistance), days 7, 14, 28 (42 for AL); **Hb day 7, 14, 28** after IV artesunate; ASHA-supervised primaquine."],
        ["Prevention / programme", "**LLIN**, IRS, larvivorous fish, source reduction; **NFME 2016-2030, NSP 2023-27**; traveller prophylaxis doxycycline 100 mg daily (2 days before to 4 weeks after) or mefloquine 250 mg weekly."],
        ["Latest guideline change", "**WHO 2024-25**: G6PD near-patient tests, **7-day high-dose primaquine (1 mg/kg/day)** and **tafenoquine 300 mg single dose** for vivax radical cure; single low-dose primaquine 0.25 mg/kg for falciparum."],
        ["Exam one-liners", "HRP2 RDT stays positive 2-4 weeks - not a test of cure; AL needs fat; never finish with artesunate monotherapy; skipping primaquine guarantees relapse."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Fever in an endemic area: test, treat, track",
        steps: [
          { label: "Bivalent RDT or smear before any drug", detail: "Negative but suspicious - repeat smear 12-hourly x 48 h" },
          { label: "Any severity criterion?", detail: "Prostration, GCS under 11, glucose under 40, Hb under 7, SBP under 80", tone: "decision" },
          { label: "Severe - IV artesunate now", detail: "2.4 mg/kg at 0, 12, 24 h then daily; then full ACT", tone: "warn" },
          { label: "Uncomplicated vivax", detail: "Chloroquine 10-10-5 mg/kg + primaquine 0.25 mg/kg x 14 days" },
          { label: "Uncomplicated falciparum", detail: "ACT-SP (AL in North-East) + primaquine 0.75 mg/kg day 2" },
          { label: "Smear day 3, 7, 14, 28; notify", detail: "Active fever survey around the case", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Vivax vs falciparum - what changes the treatment",
        columns: ["Feature", "P. vivax", "P. falciparum"],
        rows: [
          ["Hypnozoites", "Yes - relapse", "No"],
          ["Primaquine", "0.25 mg/kg x 14 days (radical cure)", "0.75 mg/kg single dose (gametocytes)"],
          ["Blood-stage drug", "Chloroquine 3 days", "ACT-SP; AL in North-East"],
          ["Sequestration", "Minimal", "PfEMP1 - cerebral, placental"],
          ["Parasitaemia", "Under 2% (reticulocytes)", "Can exceed 10%"],
        ],
      },
      {
        kind: "ladder",
        heading: "Severe malaria: drug ladder by availability",
        steps: [
          { label: "IV or IM artesunate (first choice)", detail: "2.4 mg/kg 0, 12, 24 h then daily; 3 mg/kg under 20 kg", tone: "good" },
          { label: "Pre-referral at PHC", detail: "IM artesunate, or rectal artesunate 10 mg/kg under 6 years" },
          { label: "Artemether or arteether IM", detail: "Artemether 3.2 then 1.6 mg/kg; arteether 150 mg x 3 days" },
          { label: "Quinine if nothing else", detail: "20 mg/kg over 4 h then 10 mg/kg 8-hourly; glucose checks", tone: "warn" },
          { label: "Always complete with oral ACT", detail: "Full 3-day course once able to swallow" },
        ],
      },
    ],
  },

  "infectious-fever-enteric-fever": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - Enteric fever",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Systemic infection with **Salmonella Typhi or Paratyphi A/B/C**, human-restricted, faeco-oral via water and food; **confirmed by culture** of blood, marrow, stool, urine."],
        ["Classification", "**Uncomplicated vs complicated** (bleeding, perforation, encephalopathy, shock, myocarditis, jaundice); resistance types **MDR, FQ non-susceptible (near universal in India), XDR** (Pakistan H58)."],
        ["Aetiology and risk factors", "Unsafe water, street food, carrier cooks; peak **2-15 years**; Paratyphi A 20-25%; antacids/PPIs; gallstones for carriage; NSSEFI - hundreds to over 1000 per 100,000 child-years."],
        ["Pathophysiology", "Ingestion -> M cells over **Peyer patches** (SPI-1) -> macrophage survival (SPI-2) -> RES -> secondary bacteraemia -> fever; **Vi capsule** masks LPS; week 3 longitudinal **antimesenteric ileal ulcers** bleed or perforate."],
        ["Key history (OPD)", "**Step-ladder fever** week 1, headache, dry cough, constipation (adults), source/cluster, antibiotics taken, **Pakistan travel (XDR)**, vaccination, complication symptoms, food-handler occupation."],
        ["Key examination", "Toxic apathetic look, **coated tongue with clean edges**, **relative bradycardia**, rose spots (5-30%), soft splenomegaly, doughy abdomen; daily check for peritonism, melaena, delirium."],
        ["Minimal investigations", "**Blood culture before antibiotic (10-15 mL adult), 60-80% positive week 1**; marrow culture 80-95% even after antibiotics; leucopenia, aneosinophilia; **no single Widal**; Typhidot only where culture unavailable."],
        ["Treatment - general", "Paracetamol, fluids, soft high-calorie diet; **no NSAIDs, purgatives, enemas**; enteric precautions; **food handlers off work until 3 negative stool cultures**."],
        ["Treatment - first line", "Uncomplicated: **azithromycin 1 g OD x 7 days** (child 20 mg/kg, max 1 g) or **cefixime 20 mg/kg/day in 2 doses x 14 days**; **no empirical fluoroquinolone**."],
        ["Escalation / second line", "Complicated: **ceftriaxone 2 g IV OD-BD (child 75-100 mg/kg/day, max 4 g) x 10-14 days**; slow response - add azithromycin; **XDR - meropenem 1 g 8-hourly + azithromycin**."],
        ["Severe typhoid", "Delirium, coma or shock: **dexamethasone 3 mg/kg IV then 1 mg/kg 6-hourly x 48 h (8 doses)** (Hoffman)."],
        ["Special groups", "Pregnancy - ceftriaxone or azithromycin, no FQ; children - azithromycin/cefixime by weight; renal - reduce meropenem only."],
        ["Complications", "Week 3 **ileal haemorrhage and perforation** (terminal ileum, within 60 cm of ICV), encephalopathy, myocarditis, hepatitis, cholecystitis, osteomyelitis; relapse 5-10%; **carriage 1-4%**."],
        ["Red flags and referral", "Peritonism or loss of liver dullness, melaena, delirium or shock, fever over 7 days on correct drug, XDR suspicion, infant or pregnancy."],
        ["Follow-up", "Expect **defervescence in 3-5 days - do not switch on day 2**; relapse at 1-3 weeks - re-culture; stool culture at 1 month in food handlers."],
        ["Carrier", "Excretion over 12 months: **ciprofloxacin 750 mg BD x 28 days** if susceptible (or azithromycin/amoxicillin by sensitivity); **cholecystectomy** if gallstones."],
        ["Prevention / programme", "Safe water and sanitation; **TCV single 0.5 mL IM from 6 months** (IAP 6-9 months; private only, not yet in UIP); Vi-PS from 2 years, 3-yearly; no vaccine for Paratyphi A."],
        ["Exam one-liners", "Culture, not Widal; azithromycin for uncomplicated, ceftriaxone for complicated; typhoid ulcers longitudinal, TB ulcers transverse; marrow culture rescues the pretreated case."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Suspected enteric fever: culture, severity, drug",
        steps: [
          { label: "Fever over 3-5 days, step-ladder, toxic", detail: "Relative bradycardia, leucopenia, aneosinophilia" },
          { label: "Blood culture 10-15 mL before antibiotic", detail: "Marrow culture if pretreated; no single Widal" },
          { label: "Complicated or cannot take orally?", detail: "Bleeding, peritonism, delirium, shock, jaundice", tone: "decision" },
          { label: "No - azithromycin 1 g OD x 7 days", detail: "Or cefixime 20 mg/kg/day x 14 days", tone: "good" },
          { label: "Yes - ceftriaxone 2 g IV x 10-14 days", detail: "Dexamethasone if delirium or shock; surgery if perforated", tone: "warn" },
          { label: "Afebrile by day 3-5; else re-culture", detail: "Abscess, cholecystitis, XDR - meropenem + azithromycin", tone: "decision" },
        ],
      },
      {
        kind: "compare",
        heading: "Diagnostic tests by week of illness",
        columns: ["Week", "Best test", "Note"],
        rows: [
          ["1", "Blood culture (60-80%)", "Before first antibiotic"],
          ["2", "Blood and marrow culture", "Widal only as fourfold rise in paired sera"],
          ["3", "Marrow culture; erect CXR if perforation", "Perforation and bleeding week"],
          ["4+", "Stool and urine culture", "Detect carriers, clear food handlers"],
        ],
      },
    ],
  },

  "infectious-fever-scrub-typhus": {
    checked: "2026-10",
    updated: [
      "SSC 2026: shock in severe scrub typhus - balanced crystalloid guided by dynamic measures, then noradrenaline for MAP 65.",
    ],
    master: {
      heading: "Master revision table - Scrub typhus",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Acute febrile illness from **Orientia tsutsugamushi** (obligate intracellular), transmitted by **larval trombiculid mite (chigger)** - vector and reservoir; incubation 6-21 days."],
        ["Classification", "DHR-ICMR **suspected / probable (eschar or IgM above cut-off or Weil-Felix OX-K 1:80) / confirmed** (seroconversion, IFA, PCR); clinically **uncomplicated vs severe** (organ dysfunction)."],
        ["Aetiology and risk factors", "Tsutsugamushi triangle; TN, Kerala, Karnataka, Himachal, Uttarakhand, NE, Rajasthan; **August-January**; farm, plantation, grass, picnics, army field duty."],
        ["Pathophysiology", "Painless chigger bite -> dermal replication -> **eschar** -> nodes -> blood -> **endothelial invasion -> disseminated vasculitis** -> pneumonitis/ARDS, meningoencephalitis, AKI, myocarditis, hepatitis; no peptidoglycan -> **beta-lactams useless**."],
        ["Key history (OPD)", "Abrupt fever, severe headache, myalgia, red eyes; cough in week 2; exposure 1-3 weeks earlier; **fever persisting on ceftriaxone**; pregnancy; danger symptoms."],
        ["Key examination", "**Undress fully - eschar** (axilla, groin, perineum, under breasts, waistband, behind ears; 10-50%), regional nodes, rash day 5-7, hepatosplenomegaly, SpO2, crackles, meningism."],
        ["Minimal investigations", "Neutrophilia, thrombocytopenia, **transaminases 2-5x**, low albumin, low Na; **IgM ELISA from day 5-7**; **eschar PCR (56 kDa)** in week 1; Weil-Felix 30-50% sensitive; malaria and dengue alongside."],
        ["Treatment - general", "**Do not wait for serology**; OPD for uncomplicated, daily review; fluids, paracetamol; first dose before referral."],
        ["Treatment - first line", "**Doxycycline 100 mg BD x 7 days**; child **2.2 mg/kg BD** (max 100 mg) - short courses do not stain teeth; with water and food, upright, 2-3 h from milk and iron."],
        ["Escalation / second line", "Pregnancy or intolerance: **azithromycin 500 mg OD x 5 days** (child 10 mg/kg); **severe: IV doxycycline 100 mg 12-hourly + IV azithromycin 500 mg OD x 7 days (INTREST, NEJM 2025)**; chloramphenicol third line."],
        ["Severe disease care", "ARDS - oxygen, lung-protective ventilation, **conservative fluids**; shock - balanced crystalloid then **noradrenaline MAP 65**; AKI - early dialysis; HLH - specialist."],
        ["Special groups", "Pregnancy - **azithromycin** (fetal loss risk); children - doxycycline safe short course; no FQ or beta-lactams."],
        ["Complications", "**ARDS (main killer)**, meningoencephalitis (lymphocytic CSF), myocarditis, AKI, hepatitis, DIC, HLH, hyponatraemia."],
        ["Red flags and referral", "RR over 24 or SpO2 under 94%, altered sensorium, SBP under 90, **creatinine over 2**, jaundice, **platelets under 50,000**, pregnancy, unable to take oral drugs."],
        ["Follow-up", "**Defervescence within 48 h is a therapeutic test**; fever over 72 h on doxycycline - wrong diagnosis or complication; reinfection possible (strain-specific immunity)."],
        ["Prevention / programme", "Full clothing, **permethrin-treated clothes, DEET**, bathe after field work, clear scrub; **no vaccine**; doxycycline **200 mg weekly** prophylaxis for intense exposure; notify on IHIP."],
        ["Exam one-liners", "Post-monsoon fever + neutrophilia + low platelets + transaminases = scrub; ceftriaxone does nothing; negative Weil-Felix excludes nothing; severe = doxy + azithro IV."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Suspected scrub typhus: eschar to cure",
        steps: [
          { label: "Post-monsoon fever with grass or farm exposure", detail: "Headache, myalgia; fever not settling on beta-lactam" },
          { label: "Undress and search for eschar", detail: "Axilla, groin, perineum, waistband, under breasts" },
          { label: "Organ dysfunction present?", detail: "SpO2 under 94%, confusion, SBP under 90, creatinine over 2", tone: "decision" },
          { label: "No - oral doxycycline 100 mg BD x 7 d", detail: "Azithromycin 500 mg x 5 d in pregnancy", tone: "good" },
          { label: "Yes - IV doxycycline + IV azithromycin", detail: "INTREST; ARDS care, conservative fluids", tone: "warn" },
          { label: "Afebrile in 48 h confirms", detail: "IgM ELISA day 5-7 or eschar PCR for record", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Rickettsial fevers of India",
        columns: ["Disease", "Vector", "Clue", "Weil-Felix"],
        rows: [
          ["Scrub typhus", "Chigger mite", "Eschar, ARDS", "OX-K"],
          ["Indian tick typhus", "Dog/cattle ticks", "Palm-sole rash", "OX-2, OX-19"],
          ["Murine typhus", "Rat flea", "Mild, rat contact", "OX-19"],
          ["Epidemic typhus", "Body louse", "Overcrowding, Brill-Zinsser", "OX-19"],
        ],
      },
    ],
  },

  "infectious-fever-urinary-tract-infection": {
    checked: "2026-10",
    updated: [
      "IDSA 2025 cUTI: complicated UTI defined by site (beyond the bladder), not sex - afebrile cystitis in men may be treated as uncomplicated.",
      "IDSA 2025 cUTI: 5-7 days of a fluoroquinolone or 7 days of a non-fluoroquinolone for pyelonephritis/cUTI that is improving, instead of 10-14 days; 7 days also for Gram-negative bacteraemia; 10-14 days if prostatitis suspected.",
      "SSC 2026: NEWS2 or SIRS rather than qSOFA to screen for urosepsis; balanced crystalloid and prolonged beta-lactam infusion in urosepsis.",
    ],
    master: {
      heading: "Master revision table - Urinary tract infection",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Symptomatic infection with significant bacteriuria: **cystitis** (lower) or **acute pyelonephritis** (upper); Kass **10^5 CFU/mL**, 10^3 in symptomatic woman, any growth on SPA."],
        ["Classification", "**Uncomplicated** (non-pregnant pre-menopausal woman, normal tract) vs **complicated** (men, pregnancy, child, diabetes, catheter, stones, obstruction); **IDSA 2025: complicated = beyond the bladder**; recurrent = 2 in 6 months or 3 in 12."],
        ["Aetiology and risk factors", "**E. coli 70-80%**, Klebsiella, Proteus, Enterococcus, S. saprophyticus; India: **ESBL over 60%, FQ resistance over 70%**, nitrofurantoin and fosfomycin over 90% active."],
        ["Pathophysiology", "Gut E. coli -> perineum -> short urethra -> **type 1 fimbriae** (bladder) / **P fimbriae** (kidney) -> intracellular communities (recurrence); obstruction -> **pyonephrosis needs drainage**; catheter biofilm."],
        ["Key history (OPD)", "Dysuria + frequency **without discharge** (over 90% probability), fever, flank pain, vomiting, pregnancy, men - discharge/perineal pain, diabetes, catheter, recurrences, recent antibiotics."],
        ["Key examination", "Vitals, **NEWS2/SIRS** for urosepsis, suprapubic tenderness, palpable bladder, **renal angle tenderness**, gentle DRE (boggy tender prostate), speculum if discharge."],
        ["Minimal investigations", "Uncomplicated cystitis - **no culture**; dipstick nitrite specific, LE sensitive; **culture before first dose** in pyelonephritis, men, pregnancy, child, catheter, recurrence; USG if febrile at 48-72 h."],
        ["Treatment - cystitis", "**Nitrofurantoin 100 mg BD x 5 days** (not eGFR under 30, not after 36 weeks) or **fosfomycin 3 g single dose at bedtime**; **no empirical cipro, cefixime, cotrimoxazole**."],
        ["Treatment - pyelonephritis (OPD)", "**Ceftriaxone 1-2 g or amikacin 15 mg/kg stat**, then culture-guided oral: **5-7 days FQ or 7 days non-FQ** total if improving (IDSA 2025); nitrofurantoin never for kidney."],
        ["Escalation / second line", "Admit: **piperacillin-tazobactam 4.5 g 6-8-hourly** (mild ESBL) or **meropenem 1 g 8-hourly / ertapenem 1 g OD**; oral switch afebrile 48 h; **7 days total if improving**, prostatitis 2-4 weeks."],
        ["Devices / procedures", "Pyonephrosis or obstructed infected stone - **same-day nephrostomy or stent**; CAUTI - change catheter before culture, treat 7 days (10-14 if slow); emphysematous - drainage."],
        ["Special groups", "**Pregnancy**: screen and treat ASB, nitrofurantoin/cephalexin/amox-clav/fosfomycin 5-7 days, test of cure, pyelonephritis admitted; **child**: USG after first febrile UTI, MCU if abnormal, DMSA at 4-6 months; elderly - don't treat dipstick."],
        ["Complications", "Urosepsis, pyonephrosis, perinephric abscess, **emphysematous pyelonephritis** (diabetics), papillary necrosis, renal scarring (children), preterm labour."],
        ["Red flags and referral", "Urosepsis, hydronephrosis with fever, pregnancy pyelonephritis, infant under 3 months, diabetic not better at 48 h, carbapenem-resistant isolate, sterile pyuria (TB)."],
        ["Follow-up", "No test of cure in well non-pregnant women; **pyelonephritis review at 48-72 h - persistent fever means image, not a second antibiotic**; every man with febrile UTI - look for obstruction."],
        ["Prevention", "Fluids 1.5 L extra/day (halves recurrence), post-coital voiding, stop spermicides; **vaginal oestrogen** post-menopause; **methenamine hippurate 1 g BD** (ALTAR); nitrofurantoin 50-100 mg nightly x 6-12 months."],
        ["Latest guideline change", "**IDSA 2025**: site-based cUTI definition, **7-day courses** for improving cUTI and bacteraemia; **SSC 2026**: NEWS2/SIRS not qSOFA; **EAU 2026** limited update - non-antibiotic cystitis options, fungal UTI chapter."],
        ["Exam one-liners", "Treat ASB only in pregnancy and before mucosa-breaching urology; fever + hydronephrosis = drainage; sterile pyuria in India = GU TB; confused elderly + positive dipstick usually ASB."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Dysuria in the OPD: which UTI and what to do",
        steps: [
          { label: "Dysuria/frequency without discharge", detail: "Vaginal discharge - think vaginitis, PID, urethritis" },
          { label: "Fever, flank pain or vomiting?", detail: "Beyond the bladder = complicated (IDSA 2025)", tone: "decision" },
          { label: "No - cystitis: no culture if uncomplicated", detail: "Nitrofurantoin 100 mg BD x 5 d or fosfomycin 3 g once", tone: "good" },
          { label: "Yes - culture, ceftriaxone or amikacin stat", detail: "Oral by culture: 5-7 d FQ or 7 d other" },
          { label: "Sepsis or obstruction?", detail: "NEWS2/SIRS, USG; hydronephrosis = drain same day", tone: "warn" },
          { label: "Still febrile at 48-72 h - image", detail: "Abscess, emphysematous pyelonephritis, stone", tone: "decision" },
        ],
      },
      {
        kind: "ladder",
        heading: "UTI antibiotic ladder for India (ESBL era)",
        steps: [
          { label: "Cystitis", detail: "Nitrofurantoin 100 mg BD x 5 d; fosfomycin 3 g single dose", tone: "good" },
          { label: "Mild pyelonephritis", detail: "Ceftriaxone 1-2 g or amikacin 15 mg/kg stat; 7 days total" },
          { label: "Severe or mild ESBL", detail: "Piperacillin-tazobactam 4.5 g IV 6-8-hourly" },
          { label: "Urosepsis or severe ESBL", detail: "Meropenem 1 g 8-hourly or ertapenem 1 g OD; drain", tone: "warn" },
          { label: "Duration if improving", detail: "7 days cUTI (incl. men, bacteraemia); 10-14 if prostatitis" },
        ],
      },
      {
        kind: "compare",
        heading: "Special groups in UTI",
        columns: ["Group", "Key rule", "Drug"],
        rows: [
          ["Pregnancy", "Screen and treat ASB; test of cure", "Nitrofurantoin (not after 36 wk), cephalexin, fosfomycin"],
          ["Child", "USG after first febrile UTI", "Ceftriaxone 50-75 mg/kg or oral cefixime 8 mg/kg/day"],
          ["Elderly", "Do not treat a dipstick", "Culture only with symptoms or fever"],
          ["Catheter", "Change catheter before culture", "7 days if prompt response"],
        ],
      },
    ],
  },

  "infectious-fever-skin-soft-tissue-infection": {
    checked: "2026-10",
    updated: [
      "SSC 2026: sepsis from cellulitis - at least 30 mL/kg balanced crystalloid and prolonged beta-lactam infusion after the loading dose.",
    ],
    master: {
      heading: "Master revision table - Skin and soft tissue infection",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Microbial invasion of epidermis to muscle - impetigo, folliculitis, erysipelas, cellulitis, abscess, **necrotising fasciitis**; classified by depth and **pus**."],
        ["Classification", "**IDSA purulent vs non-purulent, mild/moderate/severe** (moderate = SIRS signs; severe = hypotension, failed oral, immunocompromise, bullae); NSTI **type I polymicrobial, II GAS/S. aureus, III clostridial/Vibrio**."],
        ["Aetiology and risk factors", "**Purulent = S. aureus (about 40% MRSA in India)**, non-purulent = **S. pyogenes**; tinea pedis, lymphoedema (filarial), venous disease, diabetes, obesity; bites - Pasteurella, Eikenella."],
        ["Pathophysiology", "Barrier breach -> strep hyaluronidase spreads (diffuse cellulitis) / staph coagulase walls off (abscess); NSTI spreads along fascia -> perforator thrombosis -> **pain out of proportion -> anaesthetic, dusky, crepitant skin**."],
        ["Key history (OPD)", "Speed of spread, **pain out of proportion**, pus, systemic symptoms, portal (toe webs, bites, injection), diabetes, previous episodes, recurrent boils in household, tetanus status, allergy."],
        ["Key examination", "**Mark the margin with date and time**, fluctuation (bedside USG), lymphangitis, necrotising signs (oedema beyond erythema, bullae, crepitus), toe webs, Kanavel signs, probe-to-bone and pulses in diabetic foot."],
        ["Minimal investigations", "Clinical diagnosis; **culture pus** after drainage; blood cultures in moderate/severe; glucose/HbA1c in recurrent boils; **LRINEC 6-7 intermediate, 8+ high - low score never excludes**; imaging never delays surgery."],
        ["Treatment - general", "**Incision and drainage** is the cure for abscess; elevate limb; treat tinea pedis and lymphoedema; never squeeze facial danger-area boils; tetanus Td/TIG."],
        ["Treatment - first line", "Non-purulent mild: **amoxicillin 500 mg TDS or cephalexin 500 mg QID x 5 days**; impetigo limited - **mupirocin 2% TDS x 5 days**; extensive - cephalexin or cloxacillin 5-7 days; allergy - clindamycin 300-450 mg TDS."],
        ["Escalation / second line", "Purulent needing antibiotic: **cotrimoxazole DS 1-2 BD or doxycycline 100 mg BD x 5-7 days**; moderate: IV cefazolin 1-2 g 8-hourly or ceftriaxone; MRSA sepsis: **vancomycin 15-20 mg/kg 8-12-hourly** or linezolid 600 mg BD."],
        ["Necrotising fasciitis", "**Immediate debridement** (re-look 24-48 h) + **piperacillin-tazobactam or meropenem + clindamycin 600-900 mg 8-hourly + vancomycin/linezolid**; GAS - penicillin + clindamycin; mortality 20-30%."],
        ["Special groups", "Bites: **amoxicillin-clavulanate 3-5 days prophylaxis** (hand, face, cat, human), 7-14 if infected; diabetic foot (IWGDF/IDSA 2023): 1-2 weeks mild, 2-3 weeks moderate-severe, osteomyelitis 6 weeks."],
        ["Complications", "NSTI, streptococcal toxic shock, orbital cellulitis, cavernous sinus thrombosis, flexor tenosynovitis, osteomyelitis, **post-streptococcal GN** (not rheumatic fever)."],
        ["Red flags and referral", "Pain out of proportion, bullae, crepitus, rapid spread, sepsis, proptosis, danger-area boil with headache, Kanavel signs, Fournier gangrene, diabetic foot with systemic signs."],
        ["Follow-up", "Review at **48-72 h against the pen mark**; slight spread in 24 h is expected; oral switch afebrile 48 h; recurrent boils - glucose, HIV, **mupirocin nasal + chlorhexidine 5-7 days** for household."],
        ["Prevention", "Recurrent cellulitis: **penicillin V 250 mg BD x 12 months (PATCH I)** or benzathine penicillin; filarial MMDP limb hygiene; compression once settled."],
        ["Exam one-liners", "Purulent = staph = drain; non-purulent = strep = 5 days; clindamycin switches off toxin (Eagle effect); probe to bone = osteomyelitis; never suture bites."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Red, hot limb: decide in one look",
        steps: [
          { label: "Pain out of proportion, bullae, crepitus?", detail: "Oedema beyond erythema, anaesthetic dusky skin", tone: "decision" },
          { label: "Yes - necrotising fasciitis", detail: "Fluids, cultures, pip-taz + clindamycin; surgeon tonight", tone: "warn" },
          { label: "Pus or fluctuation?", detail: "Bedside USG if unsure", tone: "decision" },
          { label: "Purulent - incision and drainage", detail: "Culture; cotrimoxazole or doxycycline if risk features" },
          { label: "Non-purulent cellulitis", detail: "Amoxicillin or cephalexin x 5 days; mark margin, elevate" },
          { label: "Review 48-72 h against pen mark", detail: "Treat tinea pedis and lymphoedema", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "SSTI antibiotic ladder",
        steps: [
          { label: "Limited impetigo", detail: "Mupirocin or fusidic acid 2% TDS x 5 days" },
          { label: "Mild cellulitis", detail: "Amoxicillin 500 mg TDS or cephalexin 500 mg QID x 5 days" },
          { label: "Purulent with risk / MRSA", detail: "Cotrimoxazole DS 1-2 BD or doxycycline 100 mg BD x 5-7 d" },
          { label: "Moderate - IV", detail: "Cefazolin 1-2 g 8-hourly or ceftriaxone 1-2 g OD" },
          { label: "Severe / NSTI", detail: "Pip-taz or meropenem + clindamycin + vancomycin; debride", tone: "warn" },
        ],
      },
    ],
  },

  "infectious-fever-rabies-animal-bite": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - Animal bite and rabies PEP",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Almost always fatal **Lyssavirus (Rhabdoviridae) encephalomyelitis** from infected saliva; **dogs cause 96-97%** of Indian cases; India has about 36% of world rabies deaths."],
        ["Classification", "**WHO category I** (touch, lick on intact skin) - none; **II** (nibble, minor scratch without bleeding) - wash + vaccine; **III** (transdermal bite, bleeding, lick on broken skin, mucosa, bat) - wash + vaccine + **RIG**."],
        ["Aetiology and risk factors", "Dog, cat, monkey, mongoose, jackal; children under 15 about 40%; **rodents, squirrels, rabbits, birds need no PEP**; immunocompromised category II treated as III."],
        ["Pathophysiology", "Saliva -> muscle replication at wound (window for washing and RIG) -> **nAChR binding** -> retrograde axonal spread 50-100 mm/day -> brain (limbic, brainstem, **Negri bodies**) -> centrifugal to salivary glands; incubation 20-90 days."],
        ["Key history (OPD)", "Animal, what happened (**did it bleed**), when, site (face, hand = short incubation), animal's fate, past cell-culture vaccination, wound applications, immunosuppression, tetanus status."],
        ["Key examination", "Undress, count and grade each wound, deep structure injury, infection; **weight for RIG dose**; clinical rabies - hydrophobia, aerophobia, hypersalivation, ascending flaccid paralysis."],
        ["Minimal investigations", "**None needed to start PEP**; RFFIT titre (0.5 IU/mL protective) only in immunocompromised; animal brain dFAT; human ante-mortem - nuchal biopsy, saliva RT-PCR, corneal smear."],
        ["Treatment - wound care", "**Soap and running water 15 minutes**, then povidone iodine or alcohol; **no suturing** (if unavoidable, RIG first and loose sutures); no chilli, turmeric, cautery."],
        ["Treatment - vaccine", "Cell-culture vaccine, **full vial IM at any age**, deltoid or anterolateral thigh, **never gluteal**: **Essen 0-3-7-14-28**, **Zagreb 2-1-1 (0, 7, 21)**, **ID 0.1 mL x 2 sites days 0-3-7-28** (raise a bleb)."],
        ["Passive immunisation", "**ERIG 40 IU/kg (max 3000), HRIG 20 IU/kg (max 1500)**, Rabishield 3.33 IU/kg, Twinrab 40 IU/kg - **infiltrate into every wound**, once, day 0 to 7; no skin test; never in previously vaccinated."],
        ["Re-exposure and PrEP", "After complete course: **2 doses days 0 and 3, no RIG** (any interval); PrEP days 0, 7, 21/28 (NRCP) or 0 and 7 (WHO)."],
        ["Special groups", "**Pregnancy, infancy, lactation - no contraindication**; immunocompromised - RIG for category II and III, full course, titre at 2-4 weeks; missed dose - **resume, do not restart**."],
        ["Adjuncts", "Amoxicillin-clavulanate 3-5 days for deep, hand, face, cat bites; **Td 0.5 mL** if no dose in 5 years, TIG 250 IU if under 3 doses."],
        ["Clinical rabies", "Virtually 100% fatal; **palliative care** in quiet dim room, sedation, analgesia, barrier precautions; Milwaukee protocol not recommended; staff exposed get PEP."],
        ["Red flags and referral", "Category III face/hand/genital or multiple bites, no RIG available (refer same day, within 7 days), wild animal or bat, immunocompromised, tingling at healed bite site."],
        ["Follow-up", "Written dose card, trace defaulters; observe dog/cat 10 days (healthy - course may be modified) but **never delay PEP**; serum sickness watch 7-14 days after ERIG."],
        ["Prevention / programme", "**NAPRE 2021 - dog-mediated rabies elimination by 2030**: 70% dog vaccination, animal birth control, PEP in every PHC; notify bites on IHIP."],
        ["Exam one-liners", "Blood at the wound = category III; whole vial whatever the age; RIG into the wound not the buttock; no time limit and no contraindication; resume, never restart."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Animal bite: category to complete PEP",
        steps: [
          { label: "Wash 15 min with soap and running water", detail: "Then povidone iodine; do not suture" },
          { label: "Which WHO category?", detail: "Bleeding, transdermal, mucosa, bat = III", tone: "decision" },
          { label: "Category I - reassure", detail: "Licks on intact skin; no vaccine", tone: "good" },
          { label: "Category II - vaccine", detail: "Essen, Zagreb or ID 2-2-2-0-2; RIG if immunocompromised" },
          { label: "Category III - vaccine + RIG", detail: "ERIG 40 or HRIG 20 IU/kg into every wound, day 0-7", tone: "warn" },
          { label: "Previously fully vaccinated?", detail: "Days 0 and 3 only, no RIG", tone: "decision" },
          { label: "Complete schedule; Td; antibiotic if deep", detail: "Card, reminders, notify on IHIP", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Rabies vaccine regimens at a glance",
        columns: ["Regimen", "Dose", "Days"],
        rows: [
          ["Essen IM", "1 vial", "0, 3, 7, 14, 28"],
          ["Zagreb IM", "1 vial per site", "0 (x2), 7, 21"],
          ["Updated TRC ID", "0.1 mL at 2 sites", "0, 3, 7, 28"],
          ["Re-exposure", "1 vial IM or 0.1 mL ID", "0, 3 - no RIG"],
          ["PrEP (NRCP)", "1 vial IM or 0.1 mL ID", "0, 7, 21 or 28"],
        ],
      },
    ],
  },

  "infectious-fever-hiv-art": {
    checked: "2026-10",
    updated: [
      "WHO 2023: viral load classed as undetectable (zero sexual transmission), suppressed but detectable up to 1000 copies/mL (almost zero) and unsuppressed over 1000.",
      "WHO 2025: long-acting cabotegravir plus rilpivirine injections recommended as a switch option for virally suppressed adults and adolescents (not yet NACO).",
    ],
    master: {
      heading: "Master revision table - HIV and ART",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Chronic **HIV-1 (rarely HIV-2)** lentivirus infection depleting CD4 cells; **AIDS = WHO stage 4 or CD4 under 200**; **AHD = CD4 under 200 or stage 3-4, or any child under 5**."],
        ["Diagnosis", "Over 18 months: **NACO Strategy III - three tests of different principles, all reactive**; discordant = indeterminate (retest 14-28 days); infants **DNA-PCR on DBS at 6 weeks, 6 and 12 months**, antibody at 18 months."],
        ["Classification", "**WHO clinical stages 1-4** (no moving back down); window period 3-12 weeks (3rd gen), **2-4 weeks (4th gen p24)**, 10-14 days NAT."],
        ["Pathophysiology", "gp120 -> CD4 + **CCR5/CXCR4** -> gp41 fusion -> reverse transcription (error-prone) -> **integrase** -> protease maturation; GALT depletion -> immune activation; latent reservoir -> **ART lifelong**."],
        ["Key history (OPD)", "Risk exposures, weight loss, chronic diarrhoea/fever, **4-symptom TB screen every visit**, headache (crypto), visual floaters (CMV), drug interactions, adherence, pregnancy plans, HBV/HCV, renal disease."],
        ["Key examination", "Weight/BMI, oral thrush, hairy leukoplakia, PGL, zoster scars, skin rashes, chest and SpO2 on walking, meningism, **dilated fundoscopy if CD4 under 50**, genital ulcers."],
        ["Minimal investigations", "Baseline **CD4**, CBC, creatinine, LFT, glucose, lipids, HBsAg, anti-HCV, VDRL; CD4 under 200 - **serum CrAg and urine TB-LAM**; CBNAAT if TB screen positive; **viral load at 6, 12 months then yearly**."],
        ["Treatment - first line", "**Treat all, same day or within 7 days**: **TLD - TDF 300 + 3TC 300 + DTG 50 mg once daily**; separate antacids/iron (2 h before, 6 h after); alternative TLE (efavirenz 400 mg)."],
        ["Escalation / second line", "Failure = **VL 1000 or more twice, 3 months apart, after enhanced adherence counselling**; second line **boosted PI (ATV/r or LPV/r) + optimised NRTIs (AZT + 3TC)**; third line by expert committee after genotyping."],
        ["Key interactions", "**Rifampicin - extra DTG 50 mg 12 h later** (continue 2 weeks after); PI with rifabutin; carbamazepine/phenytoin lower DTG; **cap metformin at 1000 mg/day** with DTG."],
        ["OI prophylaxis and timing", "**CPT 1 DS daily** if CD4 under 350/stage 3-4/HIV-TB; TPT 6H or 3HP; CrAg+ - fluconazole 800 -> 400 -> 200 mg; ART within 2 weeks of ATT; **defer 4-8 weeks in TB meningitis, 4-6 weeks in crypto meningitis**."],
        ["Special groups", "**Pregnancy - lifelong TLD (Option B+)**, VL at 34-36 weeks, vaginal delivery if under 1000; infant **nevirapine 6 weeks (12 + AZT if high risk)**, CPT from 6 weeks; exclusive breastfeeding 6 months; children ABC/3TC + DTG by weight band."],
        ["PEP and PrEP", "**PEP: TLD x 28 days within 2 h (max 72 h)**, HIV test at 6 weeks, 3 and 6 months; PrEP daily TDF/FTC (90% protection), **injectable cabotegravir 2-monthly and lenacapavir 6-monthly (WHO 2025)**."],
        ["Toxicities", "TDF - tubulopathy (avoid CrCl under 50); DTG - weight gain, insomnia, hyperglycaemia; EFV - vivid dreams; AZT - anaemia; ABC - hypersensitivity (HLA-B*5701, never rechallenge); ATV - harmless jaundice."],
        ["Red flags and referral", "Meningitis features, PCP with hypoxia, visual loss, focal deficit, SJS rash, hepatitis flare after stopping TDF/3TC in HBV, positive infant DNA-PCR (start ART same day)."],
        ["Follow-up", "Review 2 and 4 weeks, monthly till stable, then multi-month dispensing; yearly VL, creatinine, glucose, lipids; cervical screen at diagnosis then 3-yearly."],
        ["Law and programme", "**HIV/AIDS Act 2017** - consent, confidentiality, anti-discrimination, Ombudsman; **NACP-V, 95-95-95**; about 2.5 million PLHIV in India."],
        ["Latest guideline change", "**WHO 2025**: lenacapavir twice-yearly PrEP, **CAB/RPV long-acting switch** for suppressed patients; **WHO 2023**: undetectable = zero risk, under 1000 = almost zero risk."],
        ["Exam one-liners", "U=U; one high VL is non-adherence until proved otherwise; never stop TDF/3TC abruptly in HBV; IRIS - continue ART; TB is the commonest OI and killer."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "From positive test to suppressed viral load",
        steps: [
          { label: "Three reactive tests (Strategy III)", detail: "Consent and counselling; link to ART centre" },
          { label: "Baseline CD4, labs, TB screen", detail: "CD4 under 200: CrAg and TB-LAM", tone: "decision" },
          { label: "Meningitis? defer ART", detail: "Crypto 4-6 weeks, TB meningitis 4-8 weeks", tone: "warn" },
          { label: "Start TLD same day or within 7 days", detail: "CPT if CD4 under 350; TPT once TB excluded" },
          { label: "Viral load at 6 and 12 months", detail: "1000 or more: 3 months adherence counselling, repeat", tone: "decision" },
          { label: "Suppressed - yearly VL, MMD", detail: "Undetectable = untransmittable", tone: "good" },
        ],
      },
      {
        kind: "flow",
        heading: "Occupational exposure: PEP in 4 steps",
        steps: [
          { label: "First aid", detail: "Wash with soap and water; flush mucosa; no squeezing" },
          { label: "Assess exposure and source", detail: "Intact skin or no visible blood - no PEP", tone: "decision" },
          { label: "TLD x 28 days, ideally within 2 h", detail: "Not beyond 72 h; baseline HIV, HBV, HCV", tone: "warn" },
          { label: "Follow-up tests", detail: "HIV at 6 weeks, 3 and 6 months; HBIG + vaccine if needed", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "ART drugs: the toxicity to remember",
        columns: ["Drug", "Toxicity", "Action"],
        rows: [
          ["Tenofovir DF", "Renal tubulopathy, bone loss", "Avoid if CrCl under 50"],
          ["Dolutegravir", "Weight gain, insomnia, hyperglycaemia", "Double dose with rifampicin"],
          ["Zidovudine", "Anaemia, neutropenia", "Avoid if Hb under 8"],
          ["Abacavir", "Hypersensitivity (HLA-B*5701)", "Never rechallenge"],
          ["Efavirenz", "Vivid dreams, depression", "Bedtime, empty stomach"],
        ],
      },
    ],
  },

  "infectious-fever-antimicrobial-resistance": {
    checked: "2026-10",
    updated: [
      "NAP-AMR 2.0 (2025-2029) launched 18 November 2025: ministry-wise budgeted plans, private-sector engagement, wastewater surveillance of AMR and residues.",
      "WHO AWaRe 2025 (with EML 2025): 268 antibiotics classified; EML lists 50 antibiotics, 10 Reserve.",
    ],
    master: {
      heading: "Master revision table - AMR and stewardship",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Ability of a microbe to **survive and multiply despite a drug that once killed it**; **stewardship** = right drug, dose, route, duration, timing; IPC prevents spread."],
        ["Classification", "**MDR** - non-susceptible to 1+ agent in **3 or more categories**; **XDR** - susceptible in only 1-2; **PDR** - all; TB: MDR (H+R), pre-XDR (+FQ), XDR (+bedaquiline or linezolid); **AWaRe - Access, Watch, Reserve**."],
        ["Burden", "1.27 million deaths attributable, 4.95 million associated (2019); **GRAM forecasts 39 million attributable deaths 2025-2050**; India highest toll; **ESBL E. coli over 60%, MRSA about 40%**."],
        ["Mechanisms", "Selection pressure -> mutation (gyrA, rpoB) or **plasmid transfer (conjugation)** -> beta-lactamases (**ESBL CTX-M, NDM, OXA-48**), altered target (**mecA PBP2a**, vanA), porin loss, efflux, **mcr-1 colistin**, biofilm."],
        ["Drivers in India", "**OTC sale**, self-medication, informal providers, antibiotics for viral illness, irrational FDCs, patient pressure, veterinary growth promoters, pharma effluent, poor WASH and IPC, weak labs."],
        ["Priority pathogens (WHO BPPL 2024)", "**Critical**: carbapenem-resistant Acinetobacter, CR and 3GC-resistant Enterobacterales, **rifampicin-resistant TB**; high: FQ-resistant Typhi and Shigella, CR Pseudomonas, VRE, MRSA, resistant gonococcus."],
        ["National strategy", "**NAP-AMR 2017** - 6 priorities on One Health; **NAP-AMR 2.0 (2025-29)** launched 18 Nov 2025; KARSAP 2018 first state plan; NARS-Net, AMRSN, GLASS."],
        ["Regulation", "**Schedule H1** (2014) - separate register 3 years; **Red Line** campaign 2016; colistin growth-promoter ban 2019; DGHS 2024 - **write the indication** on antibiotic prescriptions."],
        ["Rational prescribing - first line", "4 questions: bacterial? needs antibiotic? **narrowest Access drug**? **shortest duration**? - cystitis nitrofurantoin 5 d; CAP amoxicillin 1 g TDS x 5 d; cellulitis cephalexin 5 d; strep throat amoxicillin 10 d."],
        ["No-antibiotic and delayed strategies", "Common cold, bronchitis, most sore throats, sinusitis under 10 days, AOM over 2 years; **back-up prescription** (use if worse at 3-5 days); watery diarrhoea - ORS and zinc."],
        ["Escalation / Reserve", "Reserve drugs (colistin, ceftazidime-avibactam, tigecycline, linezolid for MDR) **hospital-only, pre-authorised**; NDM - ceftazidime-avibactam **plus aztreonam**."],
        ["Hospital stewardship (ICMR AMSP 2018)", "AMS committee, local antibiogram, prescription audit, pre-authorisation, IV-to-oral switch, de-escalation; **surgical prophylaxis cefazolin 2 g single dose within 60 min**."],
        ["Infection control", "**Hand hygiene at 5 moments** (alcohol rub 20-30 s), device bundles, early device removal, biomedical waste segregation, Kayakalp/NQAS."],
        ["Indicators", "OPD encounters with antibiotic **under 30%**, **Access share 60% now, 70% by 2030**, DOT/DDD per 1000 patient-days, HAI rates."],
        ["Red flags and referral", "Sepsis after several courses (MDR - culture first), UTI not better at 48 h, typhoid not settling by day 5, suspected DR-TB, neonatal or post-op infection clusters."],
        ["Latest guideline change", "**NAP-AMR 2.0** launched Nov 2025 (20+ ministries, wastewater surveillance); **WHO AWaRe 2025** (268 antibiotics); **UNGA 2024** - 10% fewer AMR deaths by 2030, 70% Access."],
        ["Exam one-liners", "Antibiotics do not treat fever - diagnosis does; WAAW 18-24 November; Chennai Declaration 2012; NDM not inhibited by avibactam; vaccines cut antibiotic use."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Before writing any antibiotic in the OPD",
        steps: [
          { label: "Is it bacterial?", detail: "Cold, bronchitis, most sore throats, watery diarrhoea - no", tone: "decision" },
          { label: "Self-limiting - no or back-up prescription", detail: "Safety-net; use only if worse at 3-5 days", tone: "good" },
          { label: "Needs antibiotic - narrowest Access drug", detail: "Amoxicillin, cephalexin, nitrofurantoin, doxycycline" },
          { label: "Shortest effective course", detail: "5 days CAP and cellulitis; 5 days cystitis" },
          { label: "Culture first if complicated or failing", detail: "De-escalate when result returns; write the indication" },
          { label: "Audit: antibiotic rate under 30%, Access 70%", detail: "Compare with peers yearly", tone: "good" },
        ],
      },
      {
        kind: "branch",
        heading: "WHO AWaRe groups",
        root: "Antibiotic classification for stewardship",
        arms: [
          { label: "Access", tone: "good", steps: ["Amoxicillin, cephalexin, cloxacillin", "Doxycycline, nitrofurantoin, cotrimoxazole", "First choice; 70% of use by 2030"] },
          { label: "Watch", tone: "decision", steps: ["Azithromycin, cefixime, ceftriaxone", "Ciprofloxacin, pip-taz, meropenem", "Specific indications only"] },
          { label: "Reserve", tone: "warn", steps: ["Colistin, polymyxin B", "Ceftazidime-avibactam, tigecycline, linezolid", "Hospital, pre-authorised, confirmed MDR"] },
        ],
      },
    ],
  },

  "infectious-fever-tropical-fevers-zoonoses": {
    checked: "2026-10",
    updated: [
      "WHO 2025 arboviral guideline: no NSAIDs while dengue is possible and no corticosteroids in acute chikungunya; prednisolone kept only for disabling subacute tenosynovitis.",
      "FDA 2025: live chikungunya vaccine Ixchiq licence suspended (August 2025); VLP vaccine Vimkunya approved for 12 years and over; none in India's programme.",
    ],
    master: {
      heading: "Master revision table - Leptospirosis, chikungunya, JE/AES, zoonoses",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Zoonoses** - infections naturally transmitted between vertebrate animals and humans (60% of known, 75% of emerging); **AES** = fever + altered mental status or new seizures."],
        ["Classification", "By cycle: **direct** (rabies, brucellosis, anthrax), **cyclozoonoses** (hydatid, Taenia), **metazoonoses** (plague, JE, KFD, scrub), **saprozoonoses** (larva migrans); by direction - anthropozoonoses, zooanthroponoses, amphixenoses."],
        ["Aetiology and risk factors", "Floodwater, rats (lepto), raw milk (brucella), dead animals (anthrax), pigs and paddy (JE), **monkey deaths in forest (KFD)**, bat-bitten fruit and palm sap (Nipah), rat falls (plague), Aedes (chikungunya)."],
        ["Pathophysiology", "Leptospira via abraded skin -> **capillary vasculitis** -> suffusion, calf myositis -> Weil (jaundice, **non-oliguric hypokalaemic AKI**, pulmonary haemorrhage); chikungunya alphavirus -> synovitis -> chronic arthritis; JE - pigs amplify, humans dead-end."],
        ["Key history (OPD)", "Occupation, floodwater 2-4 weeks, animal contact, forest visits, fever pattern (disabling joint pain, red eyes, undulant fever), clusters, JE vaccination, pregnancy, litchi and missed meals (AES child)."],
        ["Key examination", "**Conjunctival suffusion + calf tenderness** (lepto), eschar (scrub; anthrax with massive oedema), icterus, oliguria, SpO2, symmetric small-joint swelling, bubo, sacroiliac tenderness, GCS and **glucose in AES**."],
        ["Minimal investigations", "Malaria and dengue first; lepto - low K, high bilirubin, raised CK, **IgM ELISA after day 5, MAT gold standard (1:400)**; chikungunya RT-PCR day 1-5, IgM after; **JE IgM in CSF**; Nipah/KFD RT-PCR at NIV."],
        ["Treatment - first line", "Mild lepto: **doxycycline 100 mg BD x 7 days** (amoxicillin or azithromycin 500 mg x 3 days in pregnancy); chikungunya: **paracetamol, no NSAID till dengue excluded, no acute steroids**; empirical AUFI - doxycycline."],
        ["Escalation / second line", "Severe lepto: **penicillin G 1.5 MU 6-hourly or ceftriaxone 1-2 g x 7 days** (Jarisch-Herxheimer), dialysis, ventilation; chronic chikungunya - **HCQ 200-400 mg** or methotrexate."],
        ["Other zoonoses", "**Brucellosis**: doxycycline 6 weeks + gentamicin 5 mg/kg x 7 days (or rifampicin); **anthrax**: cipro or doxy 7-10 days, never incise; **plague**: gentamicin or streptomycin 10 days, contacts doxycycline 7 days."],
        ["AES management", "ABC, **glucose (10% dextrose 2-5 mL/kg)**, seizures (midazolam then levetiracetam), raised ICP, **empirical doxycycline/azithromycin + acyclovir + ceftriaxone**; refer to AES centre."],
        ["Special groups", "Pregnancy - azithromycin or amoxicillin not doxycycline; children under 8 with brucellosis - cotrimoxazole + rifampicin; Nipah - strict isolation, PPE."],
        ["Complications", "Weil disease, **leptospiral pulmonary haemorrhage (over 50% mortality)**, JE sequelae (one-third), KFD haemorrhage and meningoencephalitis, chronic chikungunya arthritis, brucella spondylitis."],
        ["Red flags and referral", "Jaundice + oliguria or bleeding after floodwater, haemoptysis, AES, encephalitis/respiratory cluster with bat exposure (Nipah), monkey deaths + fever (KFD), bubo, black eschar with oedema."],
        ["Follow-up", "Review at 48-72 h on doxycycline; lepto creatinine and K every 24-48 h; brucellosis for 1 year (relapse); chikungunya arthritis at 1 and 3 months; JE survivors - rehabilitation."],
        ["Prevention / programme", "**Doxycycline 200 mg weekly** lepto prophylaxis; rodent control (kill fleas before rats in plague); **JE SA 14-14-2 at 9-12 and 16-24 months (UIP)**; KFD - DMP oil; Nipah - 21-day contact monitoring; IHIP S-P-L forms; One Health."],
        ["Latest guideline change", "**WHO 2025** arboviral guideline - no NSAIDs or steroids in acute chikungunya; **2025** Ixchiq licence suspended (US), Vimkunya approved; no chikungunya vaccine in India's programme."],
        ["Exam one-liners", "Suffusion + calf tenderness = lepto; pigs amplify JE; KFD Shimoga 1957; kill fleas before rats; AES - always check sugar and cover scrub."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Monsoon fever after floodwater: leptospirosis pathway",
        steps: [
          { label: "Fever, myalgia, red eyes after floodwater", detail: "Calf tenderness, conjunctival suffusion" },
          { label: "Exclude malaria and dengue", detail: "RDT/smear, NS1; CBC, creatinine, K, bilirubin, CK" },
          { label: "Jaundice, oliguria, bleeding or hypoxia?", detail: "Weil disease or pulmonary haemorrhage", tone: "decision" },
          { label: "No - doxycycline 100 mg BD x 7 days", detail: "Azithromycin in pregnancy; review 48-72 h", tone: "good" },
          { label: "Yes - IV penicillin G or ceftriaxone", detail: "K replacement, early dialysis, ventilation", tone: "warn" },
          { label: "Confirm and notify", detail: "IgM after day 5, MAT; report on IHIP", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Tropical fever look-alikes",
        columns: ["Disease", "Clue", "Test", "Treatment"],
        rows: [
          ["Leptospirosis", "Floodwater, calves, low K AKI", "IgM, MAT", "Doxycycline; severe penicillin G"],
          ["Scrub typhus", "Eschar, nodes", "IgM, eschar PCR", "Doxycycline 7 days"],
          ["Chikungunya", "Disabling symmetric arthralgia", "RT-PCR, IgM", "Paracetamol; HCQ if chronic"],
          ["Dengue", "Rising Hct, falling platelets", "NS1, IgM", "Fluids; no NSAID"],
          ["Brucellosis", "Raw milk, sacroiliitis", "Culture, SAT 1:160", "Doxycycline 6 wk + gentamicin"],
        ],
      },
      {
        kind: "flow",
        heading: "Child with fever and altered sensorium (AES)",
        steps: [
          { label: "Airway, breathing, circulation", detail: "Oxygen, position, IV access" },
          { label: "Capillary glucose within minutes", detail: "Correct hypoglycaemia with 10% dextrose 2-5 mL/kg", tone: "warn" },
          { label: "Control seizures", detail: "Midazolam, then levetiracetam or phenytoin" },
          { label: "Empirical cover", detail: "Doxycycline/azithromycin + acyclovir + ceftriaxone", tone: "decision" },
          { label: "CSF and serum JE IgM, scrub IgM", detail: "Refer to district AES centre; notify", tone: "good" },
        ],
      },
    ],
  },
};

export default revision;
