import type { RevisionSet } from "./index";

const revision: RevisionSet = {
  "neurology-headache": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - headache and migraine",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Pain above the orbitomeatal line or nuchal ridge; **ICHD-3**: **primary** (the headache is the disease), **secondary** (symptom of another disorder), **painful cranial neuropathies** (trigeminal neuralgia)."],
        ["Relevant classification", "**Migraine without aura** (5 or more attacks, 4-72 h, 2 of 4 pain features, 1 of 2 associations); **with aura** (5-60 min reversible aura); **chronic migraine** 15 or more days/month for over 3 months; **tension-type**; **cluster** (TACs); **medication overuse headache**."],
        ["Aetiology & risk factors", "Migraine: genetic, **female 3:1**, 25-45 years; triggers - sleep change, missed meals, menses, stress, alcohol; **analgesic overuse** chronifies; cluster - male smoker; secondary - SAH, meningitis, GCA, IIH, CVT, mass."],
        ["Pathophysiology", "Cortical spreading depression (aura) -> **trigeminovascular activation -> CGRP, substance P, PACAP release** -> meningeal vasodilatation and neurogenic inflammation -> peripheral then **central sensitisation (allodynia)** -> triptans fail late, so **treat early**."],
        ["Key history (OPD)", "Pattern, onset (**thunderclap peaks within 1 min**), duration, frequency, aura, autonomic features, **headache diary**, **analgesic days per month**, triggers, **MIDAS** disability, contraception, pregnancy, mood, sleep apnoea."],
        ["Key examination", "BP, temperature, **fundus for papilloedema**, neck stiffness, focal signs, **temporal artery tenderness over 50**, pericranial tenderness; exam is normal in primary headache."],
        ["Minimal investigations", "**None for primary headache**; **ESR/CRP** if over 50 (GCA); **CT within 6 h of thunderclap** (then LP for xanthochromia at 12 h if negative); MRI/MRV for papilloedema or focal deficit."],
        ["Diagnostic criteria", "Diagnosis is clinical by **ICHD-3**; exclude secondary headache with **SNNOOP10** red flags; MOH = 15 or more headache days with **simple analgesics 15+ or triptans/opioids 10+ days a month** for over 3 months."],
        ["Treatment - first line", "Acute migraine: **aspirin 900 mg, ibuprofen 400-600 mg or naproxen 500 mg** plus **metoclopramide 10 mg**, early; or **sumatriptan 50-100 mg** (6 mg SC); **sumatriptan plus naproxen** if either alone fails."],
        ["Escalation / second line", "Prevent if **4 or more headache days/month**: **propranolol 80-160 mg/day**, **amitriptyline 10-75 mg**, **topiramate 50 mg BD**, flunarizine 5-10 mg, candesartan; then **CGRP antibodies** (erenumab 70-140 mg monthly) or **atogepant 60 mg OD**; **onabotulinumtoxinA 155 U every 12 weeks** for chronic migraine."],
        ["Devices / procedures", "Cluster attack: **100% oxygen 12-15 L/min via non-rebreather for 15-20 min** and **sumatriptan 6 mg SC**; prevention **verapamil 80 mg TDS up to 480-960 mg with ECG**; acute severe migraine - **metoclopramide 10 mg IV, ketorolac 30 mg IV, dexamethasone 10 mg IV**."],
        ["Special groups", "**Pregnancy**: paracetamol, short NSAID before 20 weeks, sumatriptan acceptable; prevention low-dose propranolol or amitriptyline; **stop topiramate, valproate, candesartan, CGRP antibodies**; **valproate not started under 55** (MHRA 2024); aura - **no combined hormonal pill**."],
        ["Complications", "**Medication overuse headache**, chronic migraine, status migrainosus over 72 h, migrainous infarction, depression; triptan vasospasm in IHD; topiramate glaucoma and teratogenicity."],
        ["Red flags & referral", "**SNNOOP10**: fever, cancer, deficit, **thunderclap**, **new after 50**, pattern change, positional, Valsalva, **papilloedema**, pregnancy, painful red eye, trauma, HIV; refer cluster (first), chronic migraine failing 3 preventives, trigeminal neuralgia failing carbamazepine."],
        ["Follow-up & monitoring", "Diary; judge a preventive after **8-12 weeks** at target dose (CGRP at 3 months - **50% fewer days episodic, 30% chronic**); continue 6-12 months then taper; limit acute drugs to **under 10-15 days a month**."],
        ["Latest guideline change", "No change at this update; **AHS 2024**: CGRP-targeting therapies are a **first-line preventive option**; NICE CG150 update in progress (candesartan, CGRP switching) - not yet published."],
        ["Exam one-liners", "**Treat early, limit days, prevent at 4 days a month**; triptans contraindicated in IHD and stroke; **oxygen and SC sumatriptan for cluster**; **indomethacin-responsive** = paroxysmal hemicrania, hemicrania continua; **ESR in every new headache over 50**."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "New headache in the OPD - triage",
        steps: [
          { label: "Any SNNOOP10 red flag?", detail: "Fever, cancer, deficit, thunderclap, new after 50, papilloedema, pregnancy, HIV", tone: "decision" },
          { label: "Thunderclap or deficit - refer same day", detail: "CT within 6 h for SAH; then LP at 12 h if CT normal", tone: "warn" },
          { label: "Over 50 with jaw claudication or scalp tenderness", detail: "ESR/CRP, prednisolone 40-60 mg today, temporal artery biopsy", tone: "warn" },
          { label: "No red flag - classify by ICHD-3", detail: "Migraine, tension-type, cluster, medication overuse", tone: "decision" },
          { label: "Count analgesic days per month", detail: "Simple analgesic 15+ or triptan/opioid 10+ days = MOH - withdraw" },
          { label: "Treat and give a headache diary", detail: "Acute plan plus prevention if 4 or more headache days a month", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Migraine treatment ladder",
        steps: [
          { label: "Lifestyle and trigger diary", detail: "Regular sleep and meals, hydration, exercise; riboflavin 400 mg, magnesium 400-600 mg" },
          { label: "Acute: NSAID plus antiemetic", detail: "Aspirin 900 mg or ibuprofen 400-600 mg or naproxen 500 mg + metoclopramide 10 mg" },
          { label: "Acute: triptan, then triptan plus naproxen", detail: "Sumatriptan 50-100 mg (max 300 mg/day); gepant or lasmiditan if triptan contraindicated" },
          { label: "Prevention: oral preventive", detail: "Propranolol 80-160 mg, amitriptyline 10-75 mg, topiramate 50 mg BD, flunarizine 5-10 mg; trial 8-12 weeks" },
          { label: "Prevention: CGRP pathway", detail: "Erenumab 70-140 mg, fremanezumab 225 mg monthly; atogepant 60 mg OD (AHS 2024 first-line option)" },
          { label: "Chronic migraine: botulinum toxin", detail: "OnabotulinumtoxinA 155 U, 31 sites, every 12 weeks; stop if under 30% benefit after 2 cycles", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Migraine, tension-type and cluster",
        columns: ["Feature", "Migraine", "Tension-type", "Cluster"],
        rows: [
          ["Duration", "4-72 h", "30 min - 7 days", "15-180 min, in bouts"],
          ["Site and quality", "Unilateral, pulsating", "Bilateral, pressing band", "Strictly unilateral orbital, excruciating"],
          ["Associations", "Nausea, photophobia, phonophobia", "None (at most one of photo/phono)", "Lacrimation, rhinorrhoea, ptosis, miosis"],
          ["Behaviour", "Lies still in the dark", "Carries on working", "Restless, paces"],
          ["Acute drug", "NSAID or triptan + antiemetic", "Aspirin or ibuprofen", "100% oxygen, sumatriptan 6 mg SC"],
          ["Prevention", "Propranolol, amitriptyline, topiramate, CGRP", "Amitriptyline", "Verapamil with ECG"],
        ],
      },
    ],
  },

  "neurology-stroke-acute": {
    checked: "2026-10",
    updated: [
      "AHA/ASA 2026 (replaces 2019): tenecteplase 0.25 mg/kg (max 25 mg) and alteplase 0.9 mg/kg now equally recommended; lyse any disabling deficit whatever the NIHSS; non-disabling deficit gets DAPT, not lysis.",
      "AHA/ASA 2026: thrombectomy for large core (ASPECTS 3-5, age under 80, NIHSS 6 or more, no mass effect) up to 24 h and for basilar occlusion with NIHSS 10 or more up to 24 h.",
      "AHA/ASA 2026: perfusion-mismatch thrombolysis extended to 4.5-9 h or unknown onset in selected patients.",
      "AHA/ASA 2026: after thrombectomy keep BP under 180/105; intensive systolic under 140 is harmful.",
      "AHA/ASA 2026: glucose target 140-180 mg/dL; intensive 80-130 mg/dL not recommended.",
      "AHA/ASA 2026: DAPT extended to minor stroke NIHSS 5 or less (or high-risk TIA) up to 72 h in those not lysed (INSPIRES).",
    ],
    master: {
      heading: "Master revision table - acute stroke, the first hour",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Acute focal neurological deficit from **infarction or haemorrhage** of brain, cord or retina; **tissue-based** - infarct on imaging is a stroke even if symptoms resolve within 24 h."],
        ["Relevant classification", "Pathological: **ischaemic about 80%**, **haemorrhagic about 20%** (ICH, SAH); **TOAST** mechanism; **OCSP** (TACS, PACS, LACS, POCS); severity **NIHSS 0-42** (0-4 minor, 21+ severe)."],
        ["Aetiology & risk factors", "**Hypertension** (biggest), diabetes, smoking, dyslipidaemia, **AF**, rheumatic heart disease, alcohol, carotid stenosis; young - dissection, CVT, vasculitis, drugs, PFO."],
        ["Pathophysiology", "Arterial occlusion -> **core** (irreversible) plus **penumbra** (salvageable) -> lost autoregulation -> flow follows BP -> **1.9 million neurons a minute** lost -> reperfusion salvages penumbra; BBB damage -> haemorrhagic transformation."],
        ["Key history (OPD)", "**Time last seen well** (wake-up = bedtime), BE-FAST symptoms, seizure at onset, insulin/sulfonylurea, **anticoagulant and last DOAC dose**, lysis contraindications, pre-stroke mRS."],
        ["Key examination", "**Capillary glucose first**, ABC, SpO2 (O2 only if under 94%), pulse (AF), **BP both arms** (dissection), rapid **NIHSS**, GCS, pupils, **swallow screen** before anything by mouth."],
        ["Minimal investigations", "**Non-contrast CT immediately**; **CTA arch to vertex** if thrombectomy candidate (do not wait for creatinine); MRI DWI/FLAIR or perfusion for unknown onset; only **glucose** needed before lysis; then CBC, INR, lipids, HbA1c, ECG, troponin."],
        ["Diagnostic criteria", "Sudden focal deficit plus imaging; **lysis**: disabling deficit, no blood on CT, **within 4.5 h** (4.5-9 h with perfusion mismatch); **EVT**: ICA/M1 occlusion, NIHSS 6+, 0-24 h by imaging selection."],
        ["Treatment - first line", "**Tenecteplase 0.25 mg/kg single bolus (max 25 mg)** = **alteplase 0.9 mg/kg (max 90 mg), 10% bolus, rest over 60 min**; BP **under 185/110** first (labetalol 10-20 mg IV); door-to-needle **under 60 min**."],
        ["Escalation / second line", "**Thrombectomy** 0-6 h ASPECTS 6+; 6-24 h with mismatch; **large core ASPECTS 3-5** (under 80, NIHSS 6+); **basilar NIHSS 10+ to 24 h**; lyse first if eligible; **hemicraniectomy within 48 h** for malignant MCA infarct (60 or under)."],
        ["Devices / procedures", "Not lysed: aspirin **300 mg** at 24-48 h (rectal if swallow fails), then 75-150 mg; **DAPT 21 days** for NIHSS 3 or less within 24 h (**NIHSS 5 or less up to 72 h**); IPC stockings for DVT; NG tube within 24 h if swallow fails."],
        ["Special groups", "**ICH**: SBP **about 140 (130-150)** within 1 h, reverse anticoagulation (PCC + vitamin K 10 mg; idarucizumab 5 g); **SAH**: nimodipine 60 mg 4-hourly 21 days; **CVT**: LMWH even with haemorrhage; **AF**: DOAC by ELAN timing (48 h minor, day 6-7 major)."],
        ["Complications", "Haemorrhagic transformation (**sICH about 6%** after lysis), cerebral oedema, **aspiration pneumonia**, DVT/PE, seizures, depression, falls, contractures, shoulder pain, pressure sores."],
        ["Red flags & referral", "**Any sudden focal deficit = send now via 108** with a pre-alert; falling GCS or new dilated pupil; vertigo with inability to stand; fever plus murmur (endocarditis - no lysis); puerperal headache with seizures (CVT)."],
        ["Follow-up & monitoring", "Neuro-obs every 15 min for 2 h after lysis; **CT at 24 h** before antithrombotic; **BP under 180/105 for 24 h** (SBP under 140 harmful after EVT); **glucose 140-180**; then secondary prevention - **BP under 130/80, LDL under 70, statin**."],
        ["Prevention / national programme", "**NP-NCD** screening of BP, diabetes over 30; AF detection; stroke-ready hospitals under **ICMR stroke registry / Ayushman Bharat**; tenecteplase available in public hospitals."],
        ["Latest guideline change", "**AHA/ASA 2026**: TNK = alteplase; **non-disabling deficit -> DAPT not lysis**; EVT for **large core** and **basilar (NIHSS 10+)**; **no SBP under 140 after EVT**; **glucose 140-180, not 80-130**; DAPT up to **72 h, NIHSS 5 or less**."],
        ["Exam one-liners", "**Glucose before everything**; **no aspirin before CT**; no BP lowering unless **over 220/120** (or before lysis); never sublingual nifedipine or IM injections; **stroke unit care NNT about 20**; **forehead sparing = UMN**."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Suspected stroke - the first hour",
        steps: [
          { label: "BE-FAST positive - note time last seen well", detail: "Wake-up stroke = time went to sleep", tone: "decision" },
          { label: "Capillary glucose, ABC, SpO2", detail: "Glucose under 70: 25% dextrose 50-100 mL IV; O2 only if SpO2 under 94%", tone: "warn" },
          { label: "Pre-alert and transfer to stroke-ready CT centre", detail: "No aspirin, no BP drugs, no IM injection, no dextrose fluids", tone: "warn" },
          { label: "Non-contrast CT +/- CTA", detail: "Blood -> ICH pathway; no blood -> reperfusion", tone: "decision" },
          { label: "Disabling deficit within 4.5 h -> lyse", detail: "TNK 0.25 mg/kg (max 25 mg) or alteplase 0.9 mg/kg; BP under 185/110 first" },
          { label: "LVO on CTA -> thrombectomy up to 24 h", detail: "Large core ASPECTS 3-5 and basilar NIHSS 10+ included" },
          { label: "Stroke unit", detail: "BP under 180/105, glucose 140-180, swallow screen, CT at 24 h then aspirin", tone: "good" },
        ],
      },
      {
        kind: "branch",
        heading: "Reperfusion eligibility (AHA/ASA 2026)",
        root: "CT shows no haemorrhage",
        arms: [
          { label: "IV thrombolysis", tone: "good", steps: ["Disabling deficit, any NIHSS", "Within 4.5 h; 4.5-9 h or unknown onset with DWI-FLAIR or perfusion mismatch", "TNK 0.25 mg/kg = alteplase 0.9 mg/kg"] },
          { label: "Thrombectomy", tone: "good", steps: ["ICA/M1, NIHSS 6+, ASPECTS 6+: 0-6 h", "6-24 h with clinical-core or perfusion mismatch", "Large core ASPECTS 3-5 (under 80, NIHSS 6+); basilar NIHSS 10+ to 24 h"] },
          { label: "Non-disabling minor stroke", tone: "decision", steps: ["No lysis - no proven benefit", "Aspirin + clopidogrel 21 days", "NIHSS 3 or less within 24 h; NIHSS 5 or less up to 72 h"] },
          { label: "Contraindicated", tone: "warn", steps: ["Prior ICH, stroke or head injury within 3 months", "Platelets under 100 000, INR over 1.7, DOAC within 48 h", "BP over 185/110 not controllable, glucose under 50, dissection, endocarditis"] },
        ],
      },
      {
        kind: "compare",
        heading: "Blood pressure targets in acute stroke",
        columns: ["Situation", "Target", "Drug or action"],
        rows: [
          ["Before lysis or EVT", "Under 185/110", "Labetalol 10-20 mg IV or nicardipine 5-15 mg/h"],
          ["After lysis or EVT, 24 h", "Under 180/105 (SBP under 140 harmful after EVT)", "Same drugs; neuro-obs"],
          ["Ischaemic, not reperfused", "Treat only over 220/120", "Lower about 15% in 24 h; restart home drugs at 24-72 h"],
          ["Intracerebral haemorrhage", "SBP about 140 (130-150) within 1 h", "Avoid drops under 130"],
        ],
      },
    ],
  },

  "neurology-tia": {
    checked: "2026-10",
    updated: [
      "AHA/ASA 2026: DAPT (aspirin plus clopidogrel 21 days) now reasonable for high-risk TIA or minor stroke (NIHSS 5 or less) presenting 24-72 h after onset (INSPIRES).",
    ],
    master: {
      heading: "Master revision table - TIA and secondary prevention",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Transient focal brain, cord or retinal ischaemia **without infarction on DWI-MRI**; usually **5-20 min, under 1 h**; any persisting deficit = **stroke**."],
        ["Relevant classification", "By territory - **anterior (carotid)** vs **posterior (vertebrobasilar)**; mechanism **TOAST** (large artery, cardioembolic, small vessel, other, undetermined); **crescendo TIA** = 2 or more in a week."],
        ["Aetiology & risk factors", "Carotid plaque, **AF**, small-vessel disease, rheumatic MS; hypertension, diabetes, smoking, LDL; young - dissection, PFO, vasculitis, OCP, cocaine."],
        ["Pathophysiology", "Ulcerated plaque -> **platelet-rich thrombus** -> artery-to-artery embolus -> lodges and lyses -> transient deficit; AF -> red fibrin clot (anticoagulate); critical stenosis + low BP -> **limb-shaking TIA**."],
        ["Key history (OPD)", "Exact onset (**negative symptoms maximal at onset**), what and which side, **duration**, number of episodes, amaurosis fugax, neck pain/Horner (dissection), drugs (event on aspirin), driving job."],
        ["Key examination", "**Glucose**, pulse 1 full minute (AF), **BP both arms**, full neuro exam (residual sign = stroke), fields, fundus (**Hollenhorst plaques**), carotid bruit, heart murmurs."],
        ["Minimal investigations", "**ECG** (AF), **MRI DWI within 24 h** (CT if unavailable), **carotid Doppler within 24 h** in anterior events, CTA/MRA to confirm 50-99%, CBC, glucose, HbA1c, lipids, creatinine, ESR if over 50; Holter for occult AF."],
        ["Diagnostic criteria", "Focal, sudden, negative symptoms in a vascular territory, fully resolved, **normal DWI**; **ABCD2** (Age 60+, BP 140/90+, unilateral weakness 2 / speech 1, duration 60+ min 2 / 10-59 min 1, diabetes) - **4 or more = high risk**."],
        ["Treatment - first line", "**Aspirin 300 mg stat in OPD**, specialist review **within 24 h**; high-risk TIA or minor stroke: **clopidogrel 300 mg + aspirin 300 mg load, then 75 mg each for 21 days**, then single agent (**clopidogrel 75 mg** long-term)."],
        ["Escalation / second line", "**AF: DOAC from day 0-1** (apixaban 5 mg BD; 2.5 mg BD if 2 of age 80+, 60 kg or less, creatinine 1.5+); **warfarin INR 2-3** for rheumatic MS or mechanical valve; ticagrelor + aspirin 30 days in CYP2C19 poor metabolisers."],
        ["Devices / procedures", "**Carotid endarterectomy within 2 weeks** for symptomatic **70-99%** (consider 50-69%), stenting if surgical risk high; PFO closure in selected young cryptogenic stroke."],
        ["Special groups", "Elderly - DOAC still preferred to aspirin in AF; CKD - apixaban; pregnancy - LMWH/aspirin, no statin or DOAC; young - look for dissection, PFO, APS."],
        ["Complications", "**Stroke about 5% at 2 days, 10% at 7 days** untreated (half in 48 h); MI; DAPT beyond 21-30 days -> major bleeding."],
        ["Red flags & referral", "**Crescendo TIA**, TIA on anticoagulant, **AF**, symptoms not resolved (stroke pathway), dissection features, amaurosis over 50 with headache (GCA) - admit or same-day."],
        ["Follow-up & monitoring", "**BP under 130/80**, **high-intensity statin (atorvastatin 40-80 mg), LDL under 70 mg/dL**, HbA1c under 7%, smoking cessation; **no driving 1 month**; DAPT stop date written."],
        ["Prevention / national programme", "**NP-NCD** screening for hypertension and diabetes; teach **BE-FAST**; Mediterranean diet, exercise 150 min/week, salt under 5 g."],
        ["Latest guideline change", "**AHA/ASA 2026**: DAPT window extended - **NIHSS 5 or less or high-risk TIA up to 72 h** if not lysed (INSPIRES)."],
        ["Exam one-liners", "**Aspirin 300 mg now, specialist in 24 h**; **DAPT 21 days, not longer**; **AF gets a DOAC, not aspirin**; **CEA within 2 weeks for 70-99%**; global symptoms (syncope, dizziness alone) are **not TIA**."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Suspected TIA in the OPD",
        steps: [
          { label: "Still a deficit?", detail: "Yes = stroke - acute stroke pathway, no aspirin", tone: "decision" },
          { label: "Resolved: glucose, ECG, BP", detail: "Exclude mimics - hypoglycaemia, migraine aura, seizure, syncope" },
          { label: "Aspirin 300 mg now", detail: "Unless bleeding risk or on anticoagulant" },
          { label: "Crescendo, on anticoagulant or AF?", detail: "Admit / same-day specialist", tone: "warn" },
          { label: "Specialist within 24 h", detail: "MRI DWI, carotid Doppler, Holter" },
          { label: "Mechanism-based secondary prevention", detail: "DAPT 21 days, DOAC for AF, statin, BP under 130/80, CEA within 2 weeks", tone: "good" },
        ],
      },
      {
        kind: "branch",
        heading: "Antithrombotic choice after TIA by mechanism",
        root: "Cause of the TIA",
        arms: [
          { label: "High-risk non-cardioembolic", tone: "good", steps: ["ABCD2 4+ or NIHSS 5 or less", "Clopidogrel 300 mg + aspirin 300 mg load within 24 h (to 72 h)", "75 mg each for 21 days, then clopidogrel 75 mg"] },
          { label: "Low-risk non-cardioembolic", steps: ["Single antiplatelet", "Clopidogrel 75 mg or aspirin 75-150 mg lifelong"] },
          { label: "Atrial fibrillation", tone: "warn", steps: ["DOAC from day 0-1 after TIA", "Apixaban 5 mg BD, rivaroxaban 20 mg OD with food", "No added aspirin"] },
          { label: "Rheumatic MS or mechanical valve", tone: "warn", steps: ["Warfarin only - DOAC contraindicated", "INR 2-3 (2.5-3.5 mechanical mitral)"] },
        ],
      },
    ],
  },

  "neurology-vertigo": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - vertigo and dizziness",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Vertigo** = illusion of self or environment moving; dizziness is sorted by **timing and triggers (TiTrATE)**, not the patient's word."],
        ["Relevant classification", "**Triggered episodic** (BPPV, orthostatic), **spontaneous episodic** (vestibular migraine, Meniere, posterior TIA), **acute vestibular syndrome** (neuritis vs stroke), chronic (PPPD); Barany criteria."],
        ["Aetiology & risk factors", "BPPV commonest (otoconia in **posterior canal**, after head injury, elderly); neuritis after viral illness; migraine history; Meniere; **vascular risk factors -> posterior circulation stroke**; drugs."],
        ["Pathophysiology", "Loose otoconia (canalithiasis) -> endolymph drag on head turn -> **brief positional vertigo**; unilateral vestibular loss -> tone asymmetry -> **continuous vertigo, nystagmus away from lesion** -> central compensation."],
        ["Key history (OPD)", "**Timing** (seconds, minutes, hours, days), **trigger** (head position, standing), hearing loss, tinnitus, aural fullness, headache/photophobia, **diplopia, dysarthria, numbness, inability to walk**, vascular risk, drugs."],
        ["Key examination", "Spontaneous and gaze nystagmus, **HINTS** (head impulse, nystagmus, test of skew) **plus hearing**, **gait (can they walk unaided)**, cerebellar signs, cranial nerves, **lying-standing BP**, **Dix-Hallpike** and supine roll test."],
        ["Minimal investigations", "Mostly none; **ECG and glucose** in dizziness; **audiometry** for Meniere/sudden deafness (SSNHL); **MRI with DWI** for central signs (CT misses posterior fossa infarct; early MRI can be false negative)."],
        ["Diagnostic criteria", "**BPPV**: positional vertigo under 1 min + **torsional upbeating nystagmus on Dix-Hallpike**; **Meniere**: 2+ attacks 20 min-12 h + documented **low-frequency SNHL** + fluctuating aural symptoms; vestibular migraine - Barany/ICHD-3."],
        ["Treatment - first line", "**BPPV: Epley manoeuvre** (no drugs, no imaging); neuritis: **vestibular suppressant max 3 days** (prochlorperazine 5-10 mg TDS or 3-6 mg buccal) + early **vestibular rehabilitation**; prednisolone within 72 h optional."],
        ["Escalation / second line", "Meniere: **salt under 2 g**, betahistine 16 mg TDS or 24 mg BD, diuretic, then intratympanic steroid/gentamicin (ENT); vestibular migraine: propranolol, flunarizine 5-10 mg, amitriptyline; **SSNHL - oral steroid within 2 weeks, ENT**."],
        ["Devices / procedures", "**Dix-Hallpike**: head 45 degrees to the side, lie back with head 20 degrees extended - watch 30 s; **Epley**: 4 positions 30-60 s each; **Lempert (BBQ) roll** for horizontal canal; Brandt-Daroff home exercises."],
        ["Special groups", "**Elderly**: falls risk, avoid long-term cinnarizine/flunarizine (parkinsonism), postural hypotension from drugs; pregnancy - promethazine; children - benign paroxysmal vertigo of childhood (migraine equivalent)."],
        ["Complications", "Falls and fractures, chronic dizziness (**PPPD**) from prolonged suppressants, missed **cerebellar stroke** with oedema and hydrocephalus."],
        ["Red flags & referral", "**Normal head impulse in continuous vertigo**, direction-changing or vertical nystagmus, skew, **cannot walk**, new deafness (AICA), headache/neck pain, any brainstem sign -> **stroke pathway / MRI**."],
        ["Follow-up & monitoring", "Re-test Dix-Hallpike at 1 week; stop suppressants by day 3; vestibular rehabilitation for persisting imbalance; audiogram follow-up in Meniere."],
        ["Latest guideline change", "No change at this update; **GRACE-3 2023** (HINTS by trained clinicians over CT) and **AAO-HNS 2017** BPPV remain current."],
        ["Exam one-liners", "**Abnormal head impulse is reassuring, normal is dangerous**; **BPPV needs a manoeuvre, not a pill**; suppressants **no more than 3 days**; **CT does not exclude posterior fossa stroke**; HINTS + hearing = HINTS-plus."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Acute continuous vertigo - HINTS-plus",
        steps: [
          { label: "Continuous vertigo for hours to days", detail: "Acute vestibular syndrome", tone: "decision" },
          { label: "Can the patient walk unaided?", detail: "No = truncal ataxia - central until proved otherwise", tone: "warn" },
          { label: "Head impulse test", detail: "Abnormal (catch-up saccade) = peripheral; normal = dangerous", tone: "decision" },
          { label: "Nystagmus and test of skew", detail: "Direction-changing, vertical or skew = central", tone: "decision" },
          { label: "New hearing loss?", detail: "AICA infarct - stroke pathway", tone: "warn" },
          { label: "All peripheral: vestibular neuritis", detail: "Prochlorperazine max 3 days, early vestibular rehabilitation", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Common vertigo causes at a glance",
        columns: ["Feature", "BPPV", "Vestibular neuritis", "Meniere", "Posterior stroke"],
        rows: [
          ["Duration", "Seconds, positional", "Continuous, days", "20 min - 12 h, recurrent", "Continuous or sudden"],
          ["Hearing", "Normal", "Normal", "Low-frequency SNHL, tinnitus, fullness", "May be lost (AICA)"],
          ["Key test", "Dix-Hallpike torsional upbeat", "Abnormal head impulse", "Audiogram", "Normal head impulse, skew, cannot walk"],
          ["Treatment", "Epley", "Short suppressant + rehab", "Salt restriction, betahistine", "Stroke pathway, MRI DWI"],
        ],
      },
    ],
  },

  "neurology-peripheral-neuropathy": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - peripheral neuropathy (diabetic)",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Disease of peripheral nerves; **distal symmetric polyneuropathy (DSPN)** = length-dependent **glove-and-stocking** loss with **absent ankle jerks**, the commonest diabetic complication."],
        ["Relevant classification", "Pattern first: **distal symmetric**, **small-fibre**, **mononeuropathy**, **mononeuritis multiplex**, **acute ascending (GBS: AIDP, AMAN, Miller Fisher)**, chronic demyelinating (CIDP, CMT); diabetic also autonomic, radiculoplexus (amyotrophy)."],
        ["Aetiology & risk factors", "India: **diabetes, alcohol, B12 deficiency (metformin, vegetarian), isoniazid, leprosy**, uraemia, hypothyroidism, HIV, chemotherapy, paraprotein; GBS after **Campylobacter** diarrhoea."],
        ["Pathophysiology", "Hyperglycaemia -> **polyol pathway, AGEs, oxidative stress, PKC** -> axonal and **vasa nervorum** damage -> small then large fibres -> loss of protective sensation + motor + autonomic -> **callus -> ulcer -> Charcot**."],
        ["Key history (OPD)", "Positive (burning, allodynia) vs negative (numbness, imbalance) symptoms, **tempo**, weakness, autonomic (postural dizziness, gastroparesis, ED, bladder), alcohol, diet, drugs (INH, metformin), leprosy patches, family history."],
        ["Key examination", "**10 g monofilament** (4 sites), **128 Hz tuning fork**, pinprick, ankle reflexes, Romberg, wasting, **foot inspection**, pulses/ABI, lying-standing BP; thickened nerves (leprosy); in acute weakness **single-breath count / FVC**."],
        ["Minimal investigations", "**HbA1c/FPG (OGTT), B12, TSH, creatinine, CBC with MCV, LFT, ESR, SPEP over 50**; NCS for atypical, asymmetric, motor-predominant or rapid; slit-skin smear; GBS - CSF **albuminocytological dissociation**, NCS."],
        ["Diagnostic criteria", "Typical symptoms + signs (reduced vibration, pinprick, ankle jerks) in diabetes = DSPN after excluding B12, thyroid, renal, drugs; **screen at diagnosis of T2DM, 5 years after T1DM, then yearly** (ADA 2026)."],
        ["Treatment - first line", "Glycaemic control, B12 replacement; painful DPN: **amitriptyline 10 -> 25-75 mg at night**, **duloxetine 30 -> 60 mg**, **pregabalin 75 -> 150-300 mg BD** or **gabapentin up to 1800-3600 mg/day**; review at 4-6 weeks."],
        ["Escalation / second line", "Switch or combine first-line agents; topical **capsaicin 8% patch** or lidocaine for focal pain; **avoid opioids** (tramadol short-term only); pain clinic."],
        ["Devices / procedures", "**Annual foot screen**, protective footwear and offloading, nail and callus care; **GBS unable to walk 10 m: IVIG 0.4 g/kg/day for 5 days** (2 g/kg) or plasma exchange within 2 weeks; ICU if **FVC under 20 mL/kg**."],
        ["Special groups", "Elderly - nortriptyline over amitriptyline, lower gabapentinoid doses (falls); **CKD - reduce pregabalin/gabapentin**; INH - **pyridoxine 10 mg daily**; leprosy - **MDT 6 months PB, 12 months MB**."],
        ["Complications", "**Foot ulcer, infection, amputation**, Charcot foot, falls, painful neuropathy, autonomic - postural hypotension, gastroparesis, silent MI; GBS - respiratory failure, dysautonomia."],
        ["Red flags & referral", "**Rapidly ascending weakness, breathlessness, bulbar signs** (GBS - admit); asymmetric or motor-predominant; mononeuritis multiplex (vasculitis); hot swollen foot (Charcot); ulcer with ischaemia."],
        ["Follow-up & monitoring", "Yearly monofilament + vibration; **high-risk foot every 1-3 months**; B12 on long-term metformin; pain score and side effects 4-6 weekly; FVC 4-6 hourly in GBS."],
        ["Prevention / national programme", "**NP-NCD** diabetes care, foot-care education; **National Leprosy Eradication Programme** case finding; pyridoxine with TB treatment (**NTEP**)."],
        ["Latest guideline change", "No change at this update; **ADA 2026** screening and treatment, **IWGDF 2023** foot, **EAN/PNS 2023** GBS remain current."],
        ["Exam one-liners", "**Pattern before cause**; **monofilament not felt = at-risk foot**; **B12 on metformin**; **no steroids in GBS**; **IVIG 2 g/kg over 5 days**; painful DPN first line = **amitriptyline, duloxetine, pregabalin, gabapentin**."],
      ],
    },
    flows: [
      {
        kind: "ladder",
        heading: "Painful diabetic neuropathy ladder",
        steps: [
          { label: "Confirm DSPN, exclude B12, thyroid, alcohol", detail: "Optimise glucose; B12 on metformin" },
          { label: "First-line drug", detail: "Amitriptyline 10 mg -> 25-75 mg nocte, or duloxetine 30 -> 60 mg, or pregabalin 75 mg BD -> 150-300 mg BD" },
          { label: "Review at 4-6 weeks", detail: "Under 30% relief or side effects -> switch class", tone: "decision" },
          { label: "Combine two classes", detail: "E.g. duloxetine + pregabalin; reduce gabapentinoids in CKD" },
          { label: "Topical or specialist", detail: "Capsaicin 8% patch, lidocaine; avoid long-term opioids", tone: "good" },
        ],
      },
      {
        kind: "flow",
        heading: "Guillain-Barre syndrome - what to do",
        steps: [
          { label: "Ascending weakness over days, areflexia", detail: "Recent diarrhoea or URI", tone: "decision" },
          { label: "Admit - single-breath count, FVC, swallow", detail: "FVC under 20 mL/kg, bulbar weakness -> ICU", tone: "warn" },
          { label: "CSF and NCS", detail: "Albuminocytological dissociation after week 1" },
          { label: "Unable to walk 10 m within 2 weeks", detail: "IVIG 0.4 g/kg/day x 5 days or plasma exchange; no steroids", tone: "decision" },
          { label: "Supportive", detail: "DVT prophylaxis, BP/HR for dysautonomia, pain, rehabilitation", tone: "good" },
        ],
      },
    ],
  },

  "neurology-cns-infection": {
    checked: "2026-10",
    updated: [
      "WHO 2025 (first meningitis guideline): empirical IV ceftriaxone or cefotaxime (ceftriaxone in epidemics), ampicillin/amoxicillin for Listeria risk, dexamethasone with first dose, stop at 7 days if no pathogen and recovered, ceftriaxone 5 days in meningococcal epidemics, no glycerol.",
      "WHO 2022 (added): 6-month intensive TBM regimen (6HRZEto) as an option in children and adolescents.",
    ],
    master: {
      heading: "Master revision table - CNS infection (bacterial, TB meningitis, NCC)",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Inflammation of meninges (**meningitis**) or brain (**encephalitis**) from infection; India's four faces: **acute bacterial meningitis, viral encephalitis/AES, TB meningitis, neurocysticercosis**; cryptococcal in HIV."],
        ["Relevant classification", "By tempo - **acute (hours), subacute/chronic (weeks: TB, cryptococcal)**; **TBM modified BMRC stage I (GCS 15, no deficit), II (11-14 or deficit), III (10 or less)**; NCC by cyst stage - viable, degenerating, calcified."],
        ["Aetiology & risk factors", "Adults **pneumococcus, meningococcus**; **Listeria** over 50, pregnancy, alcohol, immunosuppression; infants GBS, E. coli, Hib; TB contact, HIV, diabetes; **pork tapeworm (Taenia solium)** faeco-oral; JE in AES."],
        ["Pathophysiology", "Bacterial lysis -> **IL-1, TNF** -> BBB breakdown, oedema, vasculitis -> raised ICP; **dexamethasone blunts this**; TBM - **Rich focus** ruptures -> **basal exudate** -> cranial nerve palsies, hydrocephalus, infarcts."],
        ["Key history (OPD)", "Fever, headache, vomiting, photophobia, **rash**, seizures, altered behaviour, duration (hours vs weeks), TB contact and symptoms, HIV, immunosuppression, ear/sinus infection, travel, pig rearing."],
        ["Key examination", "**Neck stiffness, Kernig, Brudzinski**, GCS, **non-blanching purpura**, papilloedema, **cranial nerve palsies (VI, III)**, focal signs, fundus for ocular cysticercus/choroid tubercles, shock."],
        ["Minimal investigations", "**Blood cultures first**; CT before LP only if GCS under 10 or falling, focal deficit, papilloedema, new seizures, immunocompromise; CSF cells, protein, **CSF/blood glucose**, Gram, culture, **Xpert Ultra**, ADA (over 10), PCR, CrAg; MRI for NCC."],
        ["Diagnostic criteria", "Bacterial: **neutrophils, protein high, glucose ratio under 0.4**; TB: **lymphocytes, protein 1-5 g/L, ratio under 0.5**, basal enhancement, hydrocephalus; NCC: **cyst with scolex (dot-in-cyst)**, Del Brutto criteria."],
        ["Treatment - first line", "Bacterial: **dexamethasone 10 mg (0.15 mg/kg) 6-hourly for 4 days with/before first antibiotic + ceftriaxone 2 g IV 12-hourly** (child 100 mg/kg/day, max 4 g) within 1 hour; add **ampicillin 2 g 4-hourly** for Listeria risk; vancomycin if resistant pneumococcus."],
        ["Escalation / second line", "TBM: **2HRZE + 10HR(E) = 12 months daily** + **dexamethasone 0.3-0.4 mg/kg/day tapered over 6-8 weeks**; children option **6HRZEto**; HSV - **acyclovir 10 mg/kg 8-hourly 14-21 days**; cryptococcal - **liposomal AmB 10 mg/kg single + flucytosine + fluconazole 14 days**."],
        ["Devices / procedures", "Pre-referral **ceftriaxone 2 g IV/IM** or benzylpenicillin 2.4 g; **therapeutic LP** in cryptococcal (pressure under 20 cm H2O); **VP shunt/ETV** for TBM hydrocephalus; NCC - **albendazole 15 mg/kg/day 10-14 days** (+ praziquantel 50 mg/kg if over 2 cysts) under **steroid cover**."],
        ["Special groups", "**Pregnancy**: ceftriaxone + ampicillin, HRZE safe, avoid streptomycin, albendazole in first trimester; neonates - cefotaxime + ampicillin; **HIV-TBM - defer ART 4-8 weeks**; cryptococcal - ART after 4-6 weeks."],
        ["Complications", "**Deafness** (hearing test), seizures, hydrocephalus, SIADH, infarcts, cognitive impairment, visual loss; TBM paradoxical reaction; NCC encephalitis; ATT hepatitis, ethambutol optic neuritis."],
        ["Red flags & referral", "**Purpuric rash, shock, GCS falling, seizures, papilloedema, focal deficit** -> antibiotic now, transfer; deteriorating TBM - hydrocephalus, hyponatraemia, infarction, resistance; **multiple cysts with oedema - no albendazole**."],
        ["Follow-up & monitoring", "**Hearing test** after bacterial meningitis; monthly ATT review - weight, adherence (Nikshay, 99DOTS), LFT, vision; NCC MRI at 6 months, taper ASM after 2 years seizure-free with lesion resolved."],
        ["Prevention / national programme", "**UIP**: Hib (pentavalent), **PCV**, **JE vaccine**, BCG; meningococcal contacts - **ciprofloxacin 500 mg single dose** or rifampicin 600 mg BD 2 days or **ceftriaxone 250 mg IM** (pregnancy); **NTEP** notification, TPT for contacts; deworming, sanitation."],
        ["Latest guideline change", "**WHO 2025** first meningitis guideline: **ceftriaxone or cefotaxime** empirical, **dexamethasone with first dose**, **stop at 7 days** if no pathogen and recovered, **5 days ceftriaxone in meningococcal epidemics**, **no glycerol**."],
        ["Exam one-liners", "**Antibiotics before imaging**; **dexamethasone with the first dose**; **Listeria needs ampicillin**; **TBM = 12 months ATT + steroids**; **calcified NCC needs no albendazole**; **Xpert-negative does not exclude TBM**."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Suspected bacterial meningitis - the first hour",
        steps: [
          { label: "Fever, headache, neck stiffness, rash", detail: "Purpura or shock = meningococcal sepsis", tone: "warn" },
          { label: "Pre-referral dose if delayed", detail: "Ceftriaxone 2 g IV/IM (child 80-100 mg/kg) or benzylpenicillin 2.4 g" },
          { label: "Blood cultures, then dexamethasone", detail: "10 mg IV (0.15 mg/kg) 6-hourly for 4 days" },
          { label: "Ceftriaxone 2 g IV 12-hourly within 1 h", detail: "+ ampicillin 2 g 4-hourly if over 50, pregnant, immunosuppressed" },
          { label: "CT first only if indicated", detail: "GCS under 10 or falling, focal deficit, papilloedema, new seizures, immunocompromised", tone: "decision" },
          { label: "LP and tailor therapy", detail: "Meningococcus 5-7 d, pneumococcus 10-14 d, Listeria 21 d; no pathogen - stop at 7 d (WHO 2025)", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "CSF patterns",
        columns: ["CSF", "Bacterial", "Tuberculous", "Viral"],
        rows: [
          ["Cells", "Neutrophils, often over 1000", "Lymphocytes 50-500", "Lymphocytes under 500"],
          ["Protein", "High, over 1 g/L", "Very high, 1-5 g/L", "Normal or mildly high"],
          ["CSF/blood glucose", "Under 0.4", "Under 0.5", "Normal, over 0.6"],
          ["Specific test", "Gram stain, culture, antigen", "Xpert Ultra, ADA over 10", "HSV and enterovirus PCR"],
        ],
      },
      {
        kind: "branch",
        heading: "Neurocysticercosis - treat by cyst stage",
        root: "MRI/CT lesion type",
        arms: [
          { label: "Single enhancing lesion", tone: "good", steps: ["Albendazole 15 mg/kg/day 7-14 days", "Steroid cover from 1-3 days before", "Antiseizure drug"] },
          { label: "Multiple viable cysts", steps: ["Albendazole 10-14 days", "+ praziquantel 50 mg/kg/day if more than 2 cysts", "Fundus check first"] },
          { label: "Calcified only", steps: ["No antiparasitic", "Antiseizure drug alone"] },
          { label: "Cysticercal encephalitis or hydrocephalus", tone: "warn", steps: ["No albendazole", "Steroids, mannitol; shunt for hydrocephalus"] },
        ],
      },
    ],
  },

  "neurology-bell-palsy": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - Bell palsy",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Acute (**onset under 72 h**) **idiopathic unilateral lower motor neurone facial palsy** involving the **forehead**; a diagnosis of exclusion."],
        ["Relevant classification", "**UMN (forehead spared - stroke)** vs **LMN (forehead involved)**; severity by **House-Brackmann I-VI** (VI total); complete vs incomplete palsy."],
        ["Aetiology & risk factors", "Probable **HSV-1 reactivation**; risk - **pregnancy (third trimester, puerperium)**, diabetes, hypertension, obesity, URI; mimics - Ramsay Hunt (VZV), otitis media, parotid tumour, Lyme, GBS, leprosy, sarcoid."],
        ["Pathophysiology", "Viral inflammation -> **nerve oedema in the narrow labyrinthine segment of the facial canal** -> compression and ischaemia -> neuropraxia (full recovery) or axonotmesis (aberrant regrowth -> **synkinesis, crocodile tears**)."],
        ["Key history (OPD)", "Onset and progression (**peak within 72 h**; slow over weeks = tumour), ear pain, **vesicles**, hyperacusis, taste loss, dry eye, ear discharge, recurrence, bilateral, other neurological symptoms, diabetes, pregnancy."],
        ["Key examination", "**Forehead wrinkling**, eye closure and **Bell phenomenon**, smile, cheek puff; ear canal and pinna (**vesicles**), **parotid mass**, other cranial nerves, limbs (hemiparesis = stroke), BP, glucose."],
        ["Minimal investigations", "**None for typical Bell palsy**; **glucose/HbA1c**, BP; imaging (MRI with gadolinium) only for atypical - **no recovery at 3 weeks-4 months**, recurrent, other cranial nerves; **electrodiagnostics not routine**."],
        ["Diagnostic criteria", "Acute unilateral LMN palsy of all branches, onset under 72 h, no other cause (no vesicles, otitis, mass, other neurology) - **clinical diagnosis**."],
        ["Treatment - first line", "**Prednisolone 50 mg OD for 10 days or 60 mg for 5 days then taper**, **within 72 h**, in all over 16; **eye protection**: tear drops hourly (CMC 0.5%), **ointment and taping at night**, sunglasses."],
        ["Escalation / second line", "**Severe/complete palsy**: may add **valacyclovir 1 g TDS 7 days** (or acyclovir 400 mg 5 times daily) - **never antiviral alone**; Ramsay Hunt - **acyclovir 800 mg 5 times daily 7 days** + steroid."],
        ["Devices / procedures", "Eyelid taping horizontally, moisture chamber; late - **botulinum toxin** for synkinesis, gold weight for lagophthalmos, facial retraining physiotherapy; surgical decompression not recommended."],
        ["Special groups", "**Pregnancy** - steroids still advised, check BP (pre-eclampsia association); **children** - steroid benefit uncertain, look harder for otitis and Lyme; **diabetes** - monitor glucose on steroid."],
        ["Complications", "**Exposure keratitis and corneal ulcer**, incomplete recovery (about 30% without treatment), **synkinesis**, crocodile tears, hemifacial spasm, psychological distress."],
        ["Red flags & referral", "**Forehead sparing** (stroke), **vesicles** (Ramsay Hunt), bilateral (GBS, sarcoid, Lyme), **parotid mass**, ear discharge/cholesteatoma, other cranial nerves, slow progression, **no recovery by 3 weeks**; painful red eye -> ophthalmology."],
        ["Follow-up & monitoring", "Review at **1 week and 3 weeks**; most recover within **3 weeks to 3 months**, **70-85% fully**; refer to ENT/neurology if no improvement by 3 weeks or incomplete at 3 months."],
        ["Latest guideline change", "No change at this update; **AAO-HNS 2013** remains current."],
        ["Exam one-liners", "**Forehead involved = LMN**; **steroid within 72 h**; **antiviral only with steroid and only in severe**; **protect the eye**; **vesicles = Ramsay Hunt**; **no imaging for typical Bell palsy**."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Acute facial weakness - first visit",
        steps: [
          { label: "Can the forehead wrinkle?", detail: "Spared = UMN - stroke pathway", tone: "decision" },
          { label: "Look for another cause", detail: "Vesicles, otitis, parotid mass, bilateral, other nerves, limbs", tone: "warn" },
          { label: "Typical Bell palsy, under 72 h", detail: "Prednisolone 50 mg x 10 days or 60 mg x 5 days then taper" },
          { label: "Severe or complete?", detail: "Consider valacyclovir 1 g TDS 7 days with the steroid", tone: "decision" },
          { label: "Eye care", detail: "Drops hourly, ointment and taping at night, sunglasses" },
          { label: "Review at 3 weeks", detail: "No recovery -> ENT/neurology and imaging", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Bell palsy versus look-alikes",
        columns: ["Feature", "Bell palsy", "Ramsay Hunt", "Stroke (UMN)"],
        rows: [
          ["Forehead", "Paralysed", "Paralysed", "Spared"],
          ["Ear", "Mild ache", "Vesicles, severe pain, deafness, vertigo", "Normal"],
          ["Other signs", "None", "VIII involvement", "Hemiparesis, dysarthria"],
          ["Treatment", "Steroid within 72 h", "Acyclovir 800 mg 5x/day + steroid", "Stroke pathway"],
        ],
      },
    ],
  },

  "neurology-low-back-pain-neuro": {
    checked: "2026-10",
    updated: [
      "NICE NG59 (July 2026): recommendations on psychological therapy (CBT approach) and combined physical and psychological programmes withdrawn; psychological references removed from risk stratification and manual therapy.",
    ],
    master: {
      heading: "Master revision table - low back pain with neurological signs",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Pain between **costal margins and gluteal folds**; **acute under 6 weeks, subacute 6-12, chronic over 12 weeks**; sciatica = radicular leg pain below the knee in a dermatome."],
        ["Relevant classification", "**Diagnostic triage**: **non-specific (about 90%)**, **radicular (5-10%)**, **serious pathology (under 1-2%)** - cauda equina, cancer, infection/TB, fracture, axial SpA; **STarT Back** low/medium/high risk."],
        ["Aetiology & risk factors", "Manual labour, lifting, driving, obesity, smoking, low mood; disc prolapse **L4-5, L5-S1**; canal stenosis in elderly; red flags - cancer history, TB, steroids, IV drug use, trauma."],
        ["Pathophysiology", "Disc degeneration -> annular tear -> **nucleus prolapse** -> root compression + inflammation -> radicular pain; large central prolapse -> **cauda equina compression** -> sphincter and saddle loss; chronic pain -> **central sensitisation**."],
        ["Key history (OPD)", "Site, radiation **below knee**, onset, **night pain, fever, weight loss**, **saddle anaesthesia, bladder (retention, loss of sensation), bowel, sexual dysfunction**, leg weakness, claudication, steroid/osteoporosis, yellow flags."],
        ["Key examination", "Gait, heel/toe walk, **SLR (L5/S1) and femoral stretch (L3/4)**, power, reflexes, dermatomes - **L4 knee jerk, L5 big toe extension, S1 ankle jerk**; **perianal sensation**, PR if CES suspected; spine tenderness; pulses, hips."],
        ["Minimal investigations", "**No imaging for non-specific LBP**; **same-day MRI for suspected CES**; MRI for red flags or radicular pain over 6-12 weeks when intervention considered; ESR, CRP, CBC, SPEP, PSA when cancer/infection suspected; bladder scan (PVR)."],
        ["Diagnostic criteria", "Clinical triage; **CES**: bilateral sciatica, saddle anaesthesia, bladder/bowel/sexual change - **CES-S (suspected), CES-I (incomplete), CES-R (retention)**; radiculopathy confirmed by **MRI concordant with signs**."],
        ["Treatment - first line", "Reassure, **stay active, no bed rest**; **NSAID** - ibuprofen 400 mg TDS or naproxen 250-500 mg BD after food, 1-2 weeks, with PPI if over 65; **paracetamol alone not recommended**; group exercise programme."],
        ["Escalation / second line", "Weak opioid (tramadol 50 mg) only short-term if NSAID fails; **no gabapentinoids, oral steroids or benzodiazepines for sciatica**; **epidural steroid** for acute severe sciatica; **discectomy** for persistent radicular pain; RF denervation for facet pain."],
        ["Devices / procedures", "**Manual therapy only with exercise**; **do not offer** belts, corsets, orthotics, traction, TENS, ultrasound, acupuncture; **emergency decompression** for CES (within 24-48 h, ideally before retention)."],
        ["Special groups", "**Pregnancy** - paracetamol, physiotherapy, pelvic belt for girdle pain, no NSAIDs after 20 weeks; **elderly** - osteoporotic fracture, metastasis, canal stenosis; **young** - inflammatory back pain (HLA-B27, MRI SIJ)."],
        ["Complications", "Chronic disability, opioid dependence, **permanent sphincter and sexual dysfunction** after delayed CES surgery, foot drop, metastatic cord compression paraplegia."],
        ["Red flags & referral", "**Saddle anaesthesia, bladder/bowel change, bilateral sciatica -> same-day MRI and spinal surgery**; progressive weakness; cancer history (cord compression - **dexamethasone 16 mg**, MRI within 24 h); fever, TB, fracture."],
        ["Follow-up & monitoring", "Review at **2-4 weeks**; sciatica - refer if not settling at **6-12 weeks** or earlier for disabling pain or weakness; give **CES safety-net card**; monitor NSAID - BP, renal, GI."],
        ["Latest guideline change", "**NICE NG59 July 2026**: **psychological therapy and combined physical-psychological programme recommendations withdrawn** (partly retracted evidence); risk stratification and manual therapy no longer mention psychological care."],
        ["Exam one-liners", "**No imaging, no bed rest, stay active**; **paracetamol alone does not work**; **no pregabalin for sciatica**; **L5 = big toe, S1 = ankle jerk**; **CES = same-day MRI**; manual therapy only with exercise."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Low back pain triage at first visit",
        steps: [
          { label: "Any cauda equina symptom?", detail: "Saddle numbness, bladder/bowel/sexual change, bilateral sciatica", tone: "decision" },
          { label: "Yes - same-day MRI and spinal surgeon", detail: "Do not wait for retention", tone: "warn" },
          { label: "Other red flags?", detail: "Cancer, fever/TB, trauma or steroids, weight loss, night pain", tone: "decision" },
          { label: "Radicular pain below knee?", detail: "Dermatomal signs; conservative 6-12 weeks, MRI if persisting" },
          { label: "Non-specific: stay active, NSAID, exercise", detail: "No imaging; STarT Back risk; review 2-4 weeks", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Lumbosacral root localisation",
        columns: ["Root", "Weakness", "Sensory loss", "Reflex"],
        rows: [
          ["L4", "Knee extension, ankle inversion", "Medial leg", "Knee jerk"],
          ["L5", "Big toe extension, foot dorsiflexion", "Dorsum of foot, lateral leg", "None reliable"],
          ["S1", "Plantar flexion, eversion", "Lateral foot, sole", "Ankle jerk"],
          ["Cauda equina", "Bilateral, variable", "Saddle (S2-S5)", "Ankle jerks lost, anal tone reduced"],
        ],
      },
    ],
  },

  "neurology-parkinsonism": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - parkinsonism and Parkinson disease",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Parkinsonism** = **bradykinesia (with decrement)** plus **rest tremor and/or rigidity**; **Parkinson disease** = its commonest cause, from nigral dopaminergic loss with **Lewy bodies**."],
        ["Relevant classification", "**Idiopathic PD**; **drug-induced**; **atypical** - PSP, MSA, DLB, CBD; **vascular**, NPH; Wilson (young); **Hoehn and Yahr 1-5**; **MDS 2015 criteria** (clinically established / probable)."],
        ["Aetiology & risk factors", "Age, male, genes (LRRK2, GBA, parkin in young onset), pesticides; **drugs - levosulpiride, metoclopramide, flunarizine, cinnarizine, antipsychotics, valproate**; smoking and coffee inversely associated."],
        ["Pathophysiology", "Alpha-synuclein aggregation -> **loss of substantia nigra pars compacta neurons** (60-80% before symptoms) -> striatal dopamine deficit -> **indirect pathway overactive** -> excess GPi inhibition of thalamus -> bradykinesia."],
        ["Key history (OPD)", "Asymmetric onset, slowness, small handwriting, **rest tremor**, falls, **full drug history**, prodrome (**hyposmia, constipation, REM sleep behaviour disorder, depression**), hallucinations, cognition, autonomic symptoms."],
        ["Key examination", "**Finger tapping with decrement**, **4-6 Hz pill-rolling rest tremor**, lead-pipe/**cogwheel rigidity**, hypomimia, gait (shuffling, reduced arm swing), **pull test**; **vertical gaze** (PSP), **lying-standing BP** (MSA), cerebellar signs."],
        ["Minimal investigations", "**Clinical diagnosis**; MRI only for atypical features (PSP hummingbird, MSA hot cross bun, vascular); **DaT-SPECT** if tremor doubtful; under 50 - **ceruloplasmin, slit-lamp KF ring**; B12, TSH."],
        ["Diagnostic criteria", "**MDS 2015**: parkinsonism + supportive criteria (**clear levodopa response**, rest tremor, levodopa dyskinesia, olfactory loss) and **no absolute exclusions or red flags** (early falls, early autonomic failure, vertical gaze palsy)."],
        ["Treatment - first line", "**Levodopa-carbidopa 100/25 half tablet TDS -> 300-600 mg/day**, **30-60 min before meals** (protein competes); young mild - **pramipexole 0.125 mg TDS** or ropinirole, or **rasagiline 1 mg OD**; exercise and physiotherapy."],
        ["Escalation / second line", "Wearing-off - **entacapone 200 mg with each dose**, opicapone 50 mg, MAO-B, agonist; dyskinesia - **amantadine 100 mg BD-TDS**; advanced - **DBS (STN/GPi)**, apomorphine, levodopa-carbidopa intestinal gel."],
        ["Devices / procedures", "**Domperidone 10 mg TDS** for levodopa nausea (never metoclopramide); deep brain stimulation for motor fluctuations; physiotherapy cues for freezing; speech and swallow therapy (LSVT)."],
        ["Special groups", "**Elderly/cognitive impairment** - levodopa, avoid anticholinergics and agonists; hallucinations - reduce drugs, **quetiapine or clozapine** (never haloperidol); **nil by mouth/surgery - never stop levodopa** (dispersible via NG)."],
        ["Complications", "Motor fluctuations, **dyskinesia**, freezing, falls, **impulse control disorders (agonists)**, hallucinations, dementia, depression, orthostatic hypotension, constipation, aspiration; **parkinsonism-hyperpyrexia on abrupt withdrawal**."],
        ["Red flags & referral", "**Early falls (PSP)**, early autonomic failure (MSA), early dementia/hallucinations (DLB), symmetric onset, poor levodopa response, **under 50 (Wilson)**, **acute rigidity and fever on stopping levodopa**."],
        ["Follow-up & monitoring", "Review **every 6-12 months**; ask about **impulse control** at every agonist visit, sleep attacks (driving), mood, cognition, swallowing, falls, BP; medication timing card."],
        ["Latest guideline change", "No change at this update; **NICE NG71 (2017, reviewed 2024)** and **MDS 2015** criteria remain current."],
        ["Exam one-liners", "**Bradykinesia is essential**; **asymmetric onset and levodopa response = PD**; **exclude drug-induced first (levosulpiride, flunarizine)**; **levodopa before meals**; **never stop abruptly**; **domperidone, not metoclopramide**."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "New parkinsonism in the OPD",
        steps: [
          { label: "Bradykinesia with decrement present?", detail: "Plus rest tremor and/or rigidity", tone: "decision" },
          { label: "Culprit drug?", detail: "Levosulpiride, metoclopramide, flunarizine, antipsychotics - stop, review 3-6 months", tone: "warn" },
          { label: "Under 50?", detail: "Ceruloplasmin, KF rings - Wilson", tone: "decision" },
          { label: "Atypical red flags?", detail: "Early falls, gaze palsy, autonomic failure, early dementia - refer", tone: "warn" },
          { label: "Probable PD - start treatment when function affected", detail: "Levodopa-carbidopa 30-60 min before meals", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Parkinson disease drug ladder",
        steps: [
          { label: "Exercise, physiotherapy, education", detail: "From diagnosis" },
          { label: "Levodopa-carbidopa", detail: "100/25 half tablet TDS -> 300-600 mg levodopa/day; best motor effect" },
          { label: "Alternatives in young mild disease", detail: "Pramipexole 0.125 mg TDS -> 0.5-1 mg TDS; rasagiline 1 mg OD" },
          { label: "Wearing-off", detail: "Entacapone 200 mg each dose, opicapone 50 mg nocte, add agonist or MAO-B" },
          { label: "Dyskinesia", detail: "Amantadine 100 mg BD-TDS (max 300 mg)" },
          { label: "Advanced", detail: "DBS, apomorphine, intestinal levodopa gel", tone: "good" },
        ],
      },
    ],
  },

  "neurology-seizures-epilepsy": {
    checked: "2026-10",
    updated: [
      "ILAE 2025 seizure classification replaces ILAE 2017: 4 classes (focal, generalised, unknown, unclassified), 'onset' dropped, 'consciousness' replaces 'awareness' (FPC, FIC, FBTC), generalised grouped as absence, tonic-clonic and other, negative myoclonus added.",
    ],
    master: {
      heading: "Master revision table - seizures and epilepsy",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Seizure = transient symptoms from **abnormal excessive or synchronous neuronal activity**; **epilepsy (ILAE 2014)** = **2 unprovoked seizures over 24 h apart**, or **1 with recurrence risk 60% or more**, or an epilepsy syndrome."],
        ["Relevant classification", "**ILAE 2025**: **focal** (**preserved consciousness FPC, impaired consciousness FIC, focal to bilateral tonic-clonic FBTC**), **generalised** (absence, tonic-clonic, other), **unknown**, **unclassified**; epilepsy type and aetiology per ILAE 2017."],
        ["Aetiology & risk factors", "Structural (stroke, tumour, **neurocysticercosis, tuberculoma**), genetic (CAE, JME), infectious, metabolic, immune; provoked - **glucose, sodium under 115, calcium, alcohol withdrawal, drugs (tramadol, INH)**; sleep deprivation."],
        ["Pathophysiology", "Excitation-inhibition imbalance -> hypersynchronous discharge -> spread; absence = **thalamocortical T-type calcium 3 Hz spike-wave**; in status **GABA-A internalised, NMDA up** -> benzodiazepines fail with time."],
        ["Key history (OPD)", "**Eyewitness account and phone video**; before (aura, posture, trigger), during (eyes open, jerking, duration), **after (postictal confusion, lateral tongue bite)**; myoclonic jerks, staring spells, family history, **contraception and pregnancy plans**."],
        ["Key examination", "Glucose, BP lying/standing, pulse, **focal neurological deficit**, neurocutaneous stigmata, injuries, heart murmur; drug toxicity (nystagmus, ataxia, gum hypertrophy)."],
        ["Minimal investigations", "**Glucose, sodium, calcium, magnesium, creatinine, CBC, pregnancy test**; **ECG in every adult**; **EEG within 72 h** (normal EEG does not exclude); **MRI** for focal or adult onset; **HLA-B*1502** before carbamazepine."],
        ["Diagnostic criteria", "Clinical, supported by EEG/MRI; **absence: 3 Hz spike-wave on hyperventilation**; **JME: morning myoclonus, 4-6 Hz polyspike-wave**; status = **over 5 min (t1)** convulsive, damage after 30 min (t2)."],
        ["Treatment - first line", "Monotherapy by type: **focal - lamotrigine or levetiracetam** (carbamazepine cheap); **GTCS - valproate** (males/no childbearing potential) else lamotrigine/levetiracetam; **absence - ethosuximide**; **JME - valproate, levetiracetam in women**."],
        ["Escalation / second line", "Switch if first drug fails; **drug-resistant = 2 drugs failed** -> refer for video-EEG and **surgery** (temporal lobectomy 60-70% seizure-free), VNS, ketogenic diet; clobazam add-on."],
        ["Devices / procedures", "**Status**: lorazepam 0.1 mg/kg IV (max 4 mg) or **midazolam 10 mg IM / buccal**, repeat once; at 20 min **levetiracetam 60 mg/kg (max 4.5 g)**, **valproate 40 mg/kg** or **fosphenytoin 20 mg PE/kg**; 40 min - ICU anaesthesia."],
        ["Special groups", "**Women**: no valproate unless PPP signed, **folic acid 5 mg** pre-conception, lamotrigine/levetiracetam (levels fall 30-60% in pregnancy); **valproate not started in men under 55** without 2 specialists; elderly - low-dose lamotrigine/levetiracetam."],
        ["Complications", "**SUDEP (1 per 1000 a year)**, injury, drowning, status, depression, **lamotrigine SJS**, valproate hepatotoxicity/teratogenicity, carbamazepine hyponatraemia, levetiracetam mood change."],
        ["Red flags & referral", "Seizure **over 5 min** or clusters, first seizure (specialist **within 2 weeks**), focal deficit, pregnancy, child under 2, **drug resistance**, rash with fever on lamotrigine, **carbamazepine in JME** (worsens)."],
        ["Follow-up & monitoring", "Review 2-4 weeks after start, then 3-monthly, then yearly; seizure diary, adherence, side effects; **no routine levels**; **driving restriction**; consider withdrawal after **2 years seizure-free** (relapse 30-40%)."],
        ["Prevention / national programme", "Treat NCC and perinatal causes, helmets, **first-aid teaching**; **NMHP/District Mental Health Programme** and **mhGAP** for community epilepsy care; free ASMs at health and wellness centres."],
        ["Latest guideline change", "**ILAE 2025 classification**: **focal, generalised, unknown, unclassified**; 'onset' dropped; **'consciousness' replaces 'awareness'** (FPC, FIC, FBTC); **negative myoclonus** added; neonatal seizures excluded."],
        ["Exam one-liners", "**ECG in every first fit**; **no valproate in women who could conceive**; **ethosuximide for absence**; **carbamazepine worsens absence and myoclonus**; **2 benzodiazepine doses, then levetiracetam 60 mg/kg**; folic acid 5 mg."],
      ],
    },
    flows: [
      {
        kind: "ladder",
        heading: "Convulsive status epilepticus by the clock",
        steps: [
          { label: "0-5 min: ABC, oxygen, glucose", detail: "Dextrose 25% 50 mL adult (10% 2 mL/kg child); thiamine first if malnourished/alcohol" },
          { label: "5 min: benzodiazepine", detail: "Lorazepam 0.1 mg/kg IV (max 4 mg) or midazolam 10 mg IM/buccal; repeat once at 5-10 min", tone: "decision" },
          { label: "20 min: second line", detail: "Levetiracetam 60 mg/kg (max 4.5 g) or valproate 40 mg/kg or fosphenytoin 20 mg PE/kg" },
          { label: "Never a third benzodiazepine", detail: "Respiratory depression without benefit", tone: "warn" },
          { label: "40 min: refractory - ICU", detail: "Midazolam infusion, propofol or thiopentone with EEG", tone: "good" },
        ],
      },
      {
        kind: "branch",
        heading: "ILAE 2025 seizure classes and first drug",
        root: "Seizure class",
        arms: [
          { label: "Focal (FPC, FIC, FBTC)", steps: ["Lamotrigine or levetiracetam", "Carbamazepine cheap alternative (HLA-B*1502)"] },
          { label: "Generalised tonic-clonic", steps: ["Valproate if no childbearing potential", "Otherwise lamotrigine or levetiracetam"] },
          { label: "Absence", tone: "good", steps: ["Ethosuximide 10-15 -> 20-30 mg/kg/day", "Valproate or lamotrigine if GTCS coexist"] },
          { label: "Myoclonic / JME", tone: "warn", steps: ["Valproate; levetiracetam in women", "Avoid carbamazepine, phenytoin, gabapentin"] },
        ],
      },
      {
        kind: "compare",
        heading: "Seizure versus syncope",
        columns: ["Feature", "Seizure", "Syncope"],
        rows: [
          ["Trigger", "Sleep deprivation, flashing lights", "Standing, pain, micturition"],
          ["Jerks", "Rhythmic, over 30 s", "Few, brief"],
          ["Tongue bite", "Lateral", "Tip, rare"],
          ["Recovery", "Confusion minutes-hours", "Seconds to a minute"],
          ["Key test", "EEG, MRI", "ECG, lying-standing BP"],
        ],
      },
    ],
  },
};

export default revision;
