import type { RevisionSet } from "./index";

const revision: RevisionSet = {
  "renal-urology-chronic-kidney-disease": {
    checked: "2026-10",
    updated: [
      "KDIGO 2026 anaemia: non-dialysis iron start - ferritin under 100 ng/mL with TSAT under 40%, or ferritin 100-299 with TSAT under 25%; withhold if ferritin over 700 or TSAT 40% or more (replaces TSAT 30% or less and ferritin 500 or less)",
      "KDIGO 2026 anaemia: ESA start individualised in non-dialysis CKD (no fixed Hb 10 trigger); keep Hb below 11.5 g/dL on ESA",
      "KDIGO 2026 anaemia: ESA preferred over HIF-PHI (desidustat, daprodustat) as first-line; IV rather than oral iron in haemodialysis",
      "ERC 2025: hyperkalaemia with ECG change - calcium gluconate 10% 30 mL over 10 min or calcium chloride 10% 10 mL over 5 min (was 10-30 mL)",
    ],
    master: {
      heading: "Master revision table - Chronic kidney disease (KDIGO 2024)",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Abnormal kidney structure or function **for more than 3 months** - **eGFR under 60 mL/min/1.73 m2** or a damage marker (**ACR 30 mg/g or more**, haematuria/casts, imaging, histology, transplant). One abnormal creatinine is never CKD."],
        ["Relevant classification", "**KDIGO CGA**: Cause; **G1 90+, G2 60-89, G3a 45-59, G3b 30-44, G4 15-29, G5 under 15**; **A1 under 30, A2 30-300, A3 over 300 mg/g**; risk on heat map (**G3a A3 worse than G3b A1**); **KFRE 5-year risk 3-5%+ = refer**, 2-year over 40% = plan KRT."],
        ["Aetiology and risk factors", "**Diabetes (commonest)**, hypertension, chronic GN, **CKDu** (Uddanam, heat stress, agrochemicals), obstruction/stones, ADPKD, NSAIDs, herbal heavy metals, past AKI (dengue, lepto, snakebite, obstetric), HIV."],
        ["Pathophysiology", "Nephron loss -> **hyperfiltration** -> glomerular hypertension (angiotensin II efferent constriction) -> podocyte loss -> **albuminuria** -> tubular TGF-beta -> **interstitial fibrosis** -> falling eGFR -> anaemia, CKD-MBD, acidosis, hyperkalaemia, uraemia."],
        ["Key history (OPD)", "Usually silent - **nocturia, frothy urine, puffiness**; uraemic symptoms (anorexia, pruritus, hiccups); diabetes/HTN duration, retinopathy; **NSAID and ayurvedic use**; glomerular clues; LUTS/stones; occupation (farm heat); family history; pregnancy plans."],
        ["Key examination", "**Seated BP** with right cuff and postural BP; weight and oedema; pallor, uraemic fetor, asterixis, rub; JVP and crackles; **ballotable kidneys (ADPKD)**, palpable bladder, renal bruit; **fundus**; feet; protect non-dominant arm veins."],
        ["Minimal investigations", "**Creatinine with eGFR CKD-EPI 2021 (race-free)**; **early-morning ACR, repeat to confirm**; repeat both at 3 months; urine microscopy; **USG KUB** (small echogenic = chronic; large in DKD, amyloid, ADPKD, HIV); Na, K, HCO3, Ca, PO4, Hb, HbA1c, lipids; HBsAg, HCV, HIV; **cystatin C** if creatinine unreliable."],
        ["Diagnostic criteria", "eGFR under 60 or damage marker **persisting over 3 months**; write in full - **'CKD G3b A2 due to diabetic kidney disease'**; rapid progression = **sustained fall over 5 mL/min/year**."],
        ["Treatment - first line", "**Four pillars**: BP **systolic under 120** if tolerated; **ACEi/ARB to maximum dose** (ramipril 2.5-10 mg, telmisartan 40-80 mg; accept creatinine rise under 30%); **SGLT2i dapagliflozin/empagliflozin 10 mg OD if eGFR 20+**, continue to dialysis; **statin** (atorvastatin 20 mg) if 50+."],
        ["Escalation / second line", "T2DM with ACR 30+ on max RASi and **K 4.8 or less: finerenone 10 mg (eGFR 25-59) or 20 mg**, K at 4 weeks; **semaglutide 0.25 -> 0.5 -> 1 mg SC weekly** (FLOW); chlorthalidone 12.5-25 mg; K binder (SZC 10 g TDS 48 h then 5 g OD) to keep RASi; **NaHCO3 if bicarbonate under 18**."],
        ["Anaemia and CKD-MBD", "**Iron first: start if ferritin under 100 + TSAT under 40%, or ferritin 100-299 + TSAT under 25%**; IV if oral fails at 1-3 months; **ESA start individualised, keep Hb below 11.5 g/dL**; ESA before HIF-PHI. Phosphate binders with meals; cholecalciferol for low vitamin D."],
        ["Special groups", "**Pregnancy: stop ACEi/ARB, finerenone, SGLT2i, statin** - labetalol/nifedipine, aspirin 150 mg from 12 weeks; **metformin max 1000 mg at eGFR 30-44, stop under 30**; elderly - relax BP target, deprescribe; hepatitis B **40 microgram 0-1-2-6 months** while eGFR over 30."],
        ["Complications", "**CVD - commonest cause of death**; hyperkalaemia, acidosis, fluid overload, renal anaemia, **CKD-MBD** (FGF23 up, calcitriol down, PTH up), uraemic pericarditis, bleeding, neuropathy, drug toxicity."],
        ["Red flags and referral", "**eGFR under 30**, **ACR 300+**, KFRE 3-5%+, rapid progression, **red cell casts**, resistant HTN (4 drugs), K over 5.5 persistent; urgent: **K over 6.0 or ECG change, pulmonary oedema, pericarditis, encephalopathy** - dialysis."],
        ["Follow-up and monitoring", "eGFR + ACR **1/year (low-moderate risk), 2/year (high), 3-4/year (very high)**; K and creatinine **2-4 weeks** after RASi/finerenone; **AV fistula about 6 months before dialysis**, refer around eGFR 30; sick-day rules (SADMANS)."],
        ["Prevention / national programme", "**Annual ACR + eGFR screening** in diabetes, HTN, CVD, obesity, family history, age over 60; salt under 5 g, no NSAIDs; **PM National Dialysis Programme** and PM-JAY; CKDu belts - water, shade, rest."],
        ["Latest guideline change", "**KDIGO 2026 anaemia**: new iron start thresholds, ESA start individualised, **Hb below 11.5 g/dL on ESA**, ESA preferred over HIF-PHI; **ERC 2025** calcium for hyperkalaemia 30 mL gluconate or 10 mL chloride."],
        ["Exam one-liners", "Stage with eGFR, dose with Cockcroft-Gault; **eGFR dip up to 30% on RASi/SGLT2i = drug working**; SGLT2i continue below 20; **low-sodium salt = KCl**; small kidneys = chronic except DKD, amyloid, ADPKD, HIV."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "CKD in the OPD - confirm, stage, protect",
        caption: "Condensed KDIGO 2024 pathway from first abnormal result to the drug list.",
        steps: [
          { label: "Abnormal eGFR or ACR found", detail: "eGFR under 60 or ACR 30 mg/g or more on early-morning sample" },
          { label: "Repeat at 3 months - still abnormal?", detail: "Rising over days-weeks = AKI, not CKD", tone: "decision" },
          { label: "Stage G and A, find the cause", detail: "Microscopy, USG KUB, glucose, serology if active sediment" },
          { label: "Red cell casts, eGFR under 30 or ACR 300+?", detail: "Refer nephrology; same day if K over 6.0 or overload", tone: "warn" },
          { label: "Start the four pillars", detail: "Max ACEi/ARB, SGLT2i if eGFR 20+, statin if 50+, finerenone in T2DM with ACR 30+ and K 4.8 or less" },
          { label: "Monitor by heat-map risk", detail: "1-4 times a year; K and creatinine 2-4 weeks after any RASi change", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Anaemia of CKD - KDIGO 2026 ladder",
        caption: "Iron before any stimulating agent; never chase a normal Hb.",
        steps: [
          { label: "Exclude blood loss, B12, folate, thyroid", detail: "Ferritin under 45 or microcytosis - look for GI or gynae loss" },
          { label: "Iron if deficient", detail: "Ferritin under 100 + TSAT under 40%, or ferritin 100-299 + TSAT under 25%; withhold if ferritin over 700 or TSAT 40%+" },
          { label: "Oral, then IV iron", detail: "Ferrous sulfate 200 mg OD/alternate days; IV iron sucrose or FCM 20 mg/kg if no response in 1-3 months; IV first on HD" },
          { label: "ESA by shared decision", detail: "Epoetin 50-100 IU/kg SC thrice weekly; dialysis usually at Hb 9-10; ESA before HIF-PHI", tone: "decision" },
          { label: "Keep Hb below 11.5 g/dL", detail: "Targeting 13 raised stroke and death (CHOIR, CREATE, TREAT)", tone: "warn" },
        ],
      },
    ],
  },
  "renal-urology-acute-kidney-injury": {
    checked: "2026-10",
    updated: [
      "Surviving Sepsis 2026: start noradrenaline peripherally rather than waiting for a central line; initial MAP 65 mmHg (60-65 acceptable at 65 years or older); balanced crystalloid over 0.9% saline",
      "ERC 2025: hyperkalaemia with ECG change - calcium gluconate 10% 30 mL over 10 min or calcium chloride 10% 10 mL over 5 min",
    ],
    master: {
      heading: "Master revision table - Acute kidney injury (KDIGO)",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Abrupt fall in GFR: **creatinine rise 0.3 mg/dL or more in 48 h**, or **1.5 times baseline in 7 days**, or **urine under 0.5 mL/kg/h for 6 h**. AKD = 7-90 days; beyond 90 days = CKD."],
        ["Relevant classification", "**KDIGO stage 1** (1.5-1.9x or +0.3; UO under 0.5 for 6-12 h), **stage 2** (2-2.9x; under 0.5 for 12 h+), **stage 3** (3x, creatinine 4.0+, dialysis; UO under 0.3 for 24 h or anuria 12 h); stage by **worse criterion**. Aetiology: prerenal, intrinsic (ATN), postrenal."],
        ["Aetiology and risk factors", "India: **diarrhoea, malaria, leptospirosis, scrub typhus, dengue, viper bite**, obstetric (septic abortion, PPH, HELLP), herbal/hair-dye; sepsis, contrast, **NSAID + ACEi + diuretic ('triple whammy')**, obstruction; CKD is the strongest risk factor."],
        ["Pathophysiology", "Hypoperfusion -> loss of autoregulation -> prerenal (intact tubules, FeNa under 1%) -> prolonged ischaemia/toxin -> **S3 tubule and mTAL necrosis** -> casts, backleak, TGF afferent constriction -> **ATN** -> recovery with polyuric phase."],
        ["Key history (OPD)", "Urine volume; fluid loss; **drugs in last 2 weeks (NSAIDs, ACEi/ARB, aminoglycoside, PPIs, herbal)**; contrast; fever with rural exposure; bites, poisons; crush/immobility (dark urine); LUTS/colic; haemoptysis, rash (GN); pregnancy."],
        ["Key examination", "**Volume status** (postural BP, JVP, CRT, weight); **palpable bladder and DRE**; overload (crackles, S3); uraemic signs (asterixis, rub); **eschar, conjunctival suffusion, calf tenderness**, purpura, fang marks; compartment tension."],
        ["Minimal investigations", "Creatinine vs old value, daily; **K and VBG + ECG at once**; dipstick + microscopy (**muddy brown casts = ATN, RBC casts = GN, blood without RBC = myoglobin**); **USG KUB within 24 h**; FeNa (under 1% prerenal, over 2% ATN; FeUrea under 35% on diuretics); CBC, smear, CK, malaria/dengue/lepto/scrub tests, 20WBCT."],
        ["Diagnostic criteria", "KDIGO creatinine or UO criteria; **baseline = lowest recent value**; creatinine lags GFR by 24-48 h, so trend and urine output matter more."],
        ["Treatment - first line", "**Relieve obstruction (catheter)**, stop **SADMANS** and nephrotoxins, **balanced crystalloid 250-500 mL boluses with reassessment**, no starch; **noradrenaline (peripheral start allowed) to MAP 65** (60-65 if 65+); dose drugs by CrCl but **full first dose**."],
        ["Escalation / second line", "Overload only: **furosemide 40-80 mg IV** (1-1.5 mg/kg stress test - under 200 mL in 2 h predicts dialysis); **AEIOU dialysis**: pH under 7.1, K 6.5+ refractory, toxins (methanol, lithium), refractory oedema, uraemic pericarditis/encephalopathy. No benefit from early-by-numbers dialysis."],
        ["Hyperkalaemia sequence", "**Calcium gluconate 10% 30 mL over 10 min or chloride 10 mL** -> **insulin 10 units + glucose 25 g** (glucose hourly for 6 h) + salbutamol 10-20 mg neb -> **SZC 10 g TDS** / binder, diuretic -> dialysis."],
        ["Special causes", "**Rhabdomyolysis**: crystalloid to UO 200-300 mL/h; **AIN**: stop drug, prednisolone 1 mg/kg; **HRS-AKI**: albumin 1 g/kg then terlipressin 1 mg 4-6 hourly; **lepto**: penicillin G or ceftriaxone; **malaria**: IV artesunate 2.4 mg/kg; **viper**: ASV 8-10 vials."],
        ["Special groups", "Pregnancy: septic abortion, PPH, HELLP -> cortical necrosis; child: stage 3 includes eGFR under 35; elderly: low muscle mass masks rise; CKD: smaller rises matter."],
        ["Complications", "Hyperkalaemia, pulmonary oedema, **high anion gap acidosis**, uraemic pericarditis/encephalopathy/bleeding, infection, drug toxicity, **post-obstructive diuresis**, later CKD (risk tripled) and CVD."],
        ["Red flags and referral", "**Same-day nephrology**: stage 3, any dialysis indication, **active sediment / pulmonary-renal syndrome**, TMA, transplant AKI, no improvement in 5-7 days; urology for obstruction; infected obstructed kidney = urgent drainage."],
        ["Follow-up and monitoring", "Daily creatinine, electrolytes, fluid chart, weight; recovery phase - K, Mg, PO4 losses; **review every survivor at 3 months with creatinine and ACR**; restart drugs one at a time; record AKI episode."],
        ["Prevention", "Creatinine before and 2-4 weeks after RASi; avoid NSAIDs in CKD/elderly/HF; **ORS early in diarrhoea**; least contrast, isotonic saline 1 mL/kg/h if eGFR under 30; sick-day card."],
        ["Latest guideline change", "**SSC 2026**: peripheral noradrenaline start, MAP 65 (60-65 at 65+), balanced crystalloids; **ERC 2025** calcium dosing; KDIGO AKI/AKD 2026 update still a public-review draft (KDIGO 2012 stands)."],
        ["Exam one-liners", "Stage on the worse criterion; **catheter before blaming anything else**; diuretics treat overload not AKI; **NAC and bicarbonate do not prevent contrast AKI**; calcium protects, insulin shifts, only binders/dialysis remove K."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "AKI in the first hour - the exam sequence",
        caption: "Condensed version: threats first, then cause, then protect the kidney.",
        steps: [
          { label: "K, VBG and ECG now", detail: "ECG change or K 6.5+ - calcium gluconate 10% 30 mL or chloride 10 mL IV", tone: "warn" },
          { label: "Bladder scan or catheter, USG KUB in 24 h", detail: "Hydronephrosis with fever - nephrostomy or stent within hours", tone: "decision" },
          { label: "Assess volume - dry, euvolaemic or overloaded?", detail: "Postural BP, JVP, CRT, crackles, weight", tone: "decision" },
          { label: "Dry: balanced crystalloid 250-500 mL boluses", detail: "Reassess after each; noradrenaline to MAP 65 if still shocked" },
          { label: "Overloaded: furosemide 40-80 mg IV", detail: "No response to 1-1.5 mg/kg in 2 h - plan dialysis" },
          { label: "Stop SADMANS and nephrotoxins", detail: "Dose all drugs by CrCl; full first antibiotic dose" },
          { label: "Recovery - review at 3 months", detail: "Creatinine and ACR; no-NSAID card", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Prerenal azotaemia vs ATN vs obstruction - one look",
        columns: ["Feature", "Prerenal", "ATN", "Postrenal"],
        rows: [
          ["Urine sediment", "Bland, hyaline casts", "Muddy brown granular casts", "Bland, may have blood"],
          ["Urine Na / FeNa", "Under 20 / under 1%", "Over 40 / over 2%", "Variable"],
          ["Urine osmolality", "Over 500", "Under 350", "Isosthenuric late"],
          ["Ultrasound", "Normal", "Normal or swollen kidneys", "Hydronephrosis, full bladder"],
          ["First action", "Fluid challenge", "Supportive, remove toxin", "Catheter, nephrostomy or stent"],
        ],
      },
      {
        kind: "branch",
        heading: "AEIOU - when AKI needs dialysis",
        root: "Refractory to medical treatment",
        arms: [
          { label: "A - Acidosis", tone: "warn", steps: ["pH under 7.1", "Not overloaded enough to give bicarbonate"] },
          { label: "E - Electrolytes", tone: "warn", steps: ["K 6.5 or more", "Or ECG change despite treatment"] },
          { label: "I - Intoxication", steps: ["Methanol, ethylene glycol", "Lithium, salicylate, metformin acidosis"] },
          { label: "O - Overload", steps: ["Pulmonary oedema", "No response to diuretic"] },
          { label: "U - Uraemia", tone: "warn", steps: ["Pericarditis, encephalopathy", "Seizures, uraemic bleeding"] },
        ],
      },
    ],
  },
  "renal-urology-urinary-tract-infection": {
    checked: "2026-10",
    updated: [
      "IDSA 2025: complicated UTI and pyelonephritis with prompt response - 5-7 days of a fluoroquinolone or 7 days of another active agent (was 10-14 days for beta-lactams); 7 days for urinary-source Gram-negative bacteraemia",
      "IDSA 2025: oral beta-lactams - optimised dosing, individualised duration; febrile UTI in men with suspected prostatitis 10-14 days",
      "Surviving Sepsis 2026: qSOFA not to be used alone for screening (use NEWS2); at least 30 mL/kg balanced crystalloid in 3 h; MAP 65 mmHg",
    ],
    master: {
      heading: "Master revision table - Urinary tract infection in adults",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Symptomatic infection with **significant bacteriuria**: **10^3 CFU/mL** of one uropathogen in a woman with cystitis, **10^4** in pyelonephritis and men, **10^5** classic; catheter specimen 10^3 with symptoms; SPA any growth."],
        ["Relevant classification", "**Uncomplicated** (non-pregnant woman, normal tract) vs **complicated** (men, pregnancy, obstruction, stones, catheter, diabetes, CKD, immunosuppression); cystitis vs pyelonephritis vs urosepsis; **recurrent = 2 in 6 months or 3 in 12 months**; relapse vs reinfection; ASB; CAUTI."],
        ["Aetiology and risk factors", "**E. coli (75-80%)**, Klebsiella, Proteus, Enterococcus, Staph saprophyticus; short female urethra, intercourse, spermicide, menopause, obstruction, catheter (**3-7% per day**), diabetes, pregnancy; **ESBL over 50% in India**."],
        ["Pathophysiology", "Faecal flora colonise introitus -> ascend urethra -> **FimH type 1 fimbriae** bind uroplakins (cystitis) -> **P fimbriae** -> kidney (pyelonephritis) -> intracellular reservoirs -> recurrence; stasis and biofilm make it complicated."],
        ["Key history (OPD)", "Dysuria, frequency, urgency, **no vaginal discharge** (over 90% probability); fever, flank pain, vomiting = pyelonephritis; LMP/pregnancy; previous episodes and antibiotics in 3 months (ESBL); men - LUTS; sterile pyuria - TB symptoms."],
        ["Key examination", "Temperature, pulse, BP, RR, mental state (**NEWS2**); suprapubic and **renal angle tenderness**; palpable bladder; men - gentle DRE (**never massage acute prostate**); speculum if discharge."],
        ["Minimal investigations", "**Dipstick** (nitrite specific, LE sensitive; unreliable over 65 and catheterised); **no culture for first simple cystitis**; MSU culture before antibiotics in pyelonephritis, men, pregnancy, recurrence, catheter; USG if men, relapse, no response at 72 h; **CT** for gas/abscess; sterile pyuria - 3 AFB + CBNAAT."],
        ["Treatment - first line", "Cystitis: **nitrofurantoin 100 mg BD x 5 days** or **fosfomycin 3 g single dose** (pivmecillinam 400 mg TDS 3-5 days); **no empirical FQ or co-trimoxazole in India**. Outpatient pyelonephritis: **ceftriaxone 1 g IV once, then cefixime 200 mg BD - 7 days if prompt response**."],
        ["Escalation / second line", "Admitted pyelonephritis: **ceftriaxone 1-2 g IV OD**, pip-taz 4.5 g 6-8 hourly or amikacin 15 mg/kg OD; ESBL sepsis **meropenem 1 g 8-hourly / ertapenem 1 g OD**; step down at 48-72 h afebrile; **cUTI 5-7 days FQ or 7 days other agent** (IDSA 2025)."],
        ["Special groups", "**Pregnancy**: treat ASB and cystitis 5-7 days (nitrofurantoin not at term, cefalexin 500 mg BD), test of cure; no FQ/tetracycline. **Men**: cystitis 7 days, febrile with prostatitis 10-14 days, acute prostatitis 2-4 weeks. **Child**: cefixime 8 mg/kg/day 7-10 days. **Elderly**: no treatment of ASB."],
        ["Recurrent UTI prevention", "Extra **1.5 L water/day**, post-coital voiding, stop spermicide; **vaginal estriol 0.5 mg nightly 2 weeks then twice weekly** postmenopause; **methenamine hippurate 1 g BD**; prophylaxis nitrofurantoin 50-100 mg or cefalexin 125-250 mg at night for 6 months, or post-coital."],
        ["CAUTI", "Symptomatic only; **replace catheter in place over 2 weeks before culture and antibiotics**; 7 days (10-14 if slow); no prophylaxis for insertion; remove catheter early; CISC preferred."],
        ["Complications", "Urosepsis, **infected obstructed kidney (pyonephrosis)**, **emphysematous pyelonephritis** (diabetics), renal/perinephric abscess, papillary necrosis, preterm labour, renal scarring in children."],
        ["Red flags and referral", "Sepsis signs - cultures, **antibiotics within 1 hour**, 30 mL/kg crystalloid; stone or hydronephrosis with fever - **emergency nephrostomy/stent**; diabetic not improving at 72 h - CT; pneumaturia - fistula; persistent haematuria over 40 - cystoscopy."],
        ["Follow-up and monitoring", "Pyelonephritis review at **48-72 h**; no test of cure except pregnancy; repeat dipstick for haematuria after treatment in over 40s; review prophylaxis every 6 months."],
        ["Prevention / programme", "**Antibiotic stewardship** (ICMR AMRSN, NAP-AMR): no treatment of ASB, culture-guided therapy, reserve carbapenems; catheter bundles."],
        ["Latest guideline change", "**IDSA 2025**: shorter cUTI courses (5-7 days FQ, 7 days other), 7 days for urinary Gram-negative bacteraemia; **SSC 2026**: NEWS2 not qSOFA alone, balanced crystalloid 30 mL/kg, MAP 65."],
        ["Exam one-liners", "Nitrofurantoin and fosfomycin are **bladder-only drugs**; negative nitrite does not exclude UTI; every UTI in a man is complicated; **sterile pyuria in India = TB until proved otherwise**; change the catheter before the first dose."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Dysuria in the OPD - which UTI and which drug",
        caption: "Condensed algorithm for the commonest question in family practice.",
        steps: [
          { label: "Dysuria and frequency - vaginal discharge?", detail: "Discharge or itch - vaginitis or STI, not UTI", tone: "decision" },
          { label: "Fever, flank pain, vomiting or sepsis?", detail: "Yes - pyelonephritis or urosepsis: culture, NEWS2, admit if unwell", tone: "decision" },
          { label: "Complicating factor? Man, pregnant, catheter, stone", detail: "Complicated - culture first, tissue-penetrating drug", tone: "decision" },
          { label: "Uncomplicated cystitis: nitrofurantoin 100 mg BD x 5 d", detail: "Or fosfomycin 3 g single dose; no culture for a first episode" },
          { label: "Pyelonephritis: ceftriaxone 1 g IV then cefixime 200 mg BD", detail: "7 days if prompt response (IDSA 2025); FQ only if sensitive, 5-7 days" },
          { label: "No better at 72 h - image", detail: "USG or CT for obstruction, abscess, gas; drain if obstructed", tone: "warn" },
          { label: "Cured - no test of cure unless pregnant", detail: "Recheck haematuria in over 40s", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Recurrent UTI in women - prevention ladder",
        steps: [
          { label: "Confirm by culture and exclude a cause", detail: "2 in 6 months or 3 in 12 months; USG + PVR, glucose" },
          { label: "Behaviour and fluids", detail: "Extra 1.5 L water/day, post-coital voiding, stop spermicide, treat constipation" },
          { label: "Vaginal oestrogen if postmenopausal", detail: "Estriol 0.5 mg nightly 2 weeks, then twice weekly long term" },
          { label: "Non-antibiotic prophylaxis", detail: "Methenamine hippurate 1 g BD; cranberry or D-mannose optional" },
          { label: "Antibiotic prophylaxis 6 months", detail: "Nitrofurantoin 50-100 mg or cefalexin 125-250 mg at night, or single post-coital dose; review at 6 months", tone: "warn" },
        ],
      },
    ],
  },
  "renal-urology-luts-bph": {
    checked: "2026-10",
    updated: [
      "Reference updated to the AUA 2026 three-part BPH guideline; EAU 2025 recommendations retained (no change to doses or thresholds confirmed)",
    ],
    master: {
      heading: "Master revision table - LUTS and BPH",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**BPH** = histological stromal-epithelial hyperplasia of the **transition zone**; BPE = enlarged gland; **BPO** = proven obstruction; male LUTS is the umbrella term."],
        ["Relevant classification", "Symptoms: **storage, voiding, post-micturition**; **IPSS 0-35: mild 0-7, moderate 8-19, severe 20-35** plus QoL 0-6; complicated BPH = retention, UTI, stones, haematuria, hydronephrosis."],
        ["Aetiology and risk factors", "Age (50% in 60s, 80-90% in 80s), **DHT via 5-alpha reductase type 2**, metabolic syndrome, obesity, family history; drugs precipitating retention - decongestants, anticholinergics, opioids."],
        ["Pathophysiology", "DHT -> transition-zone nodules -> **static (bulk) + dynamic (alpha-1A tone)** obstruction -> detrusor hypertrophy, trabeculation -> **overactivity (storage)** -> decompensation -> residual urine -> UTI, stones, **chronic retention -> hydronephrosis**."],
        ["Key history (OPD)", "IPSS + bother; which symptom is worst; haematuria, dysuria, bone pain; **drug list (cold remedies)**; polyuria, oedema, OSA (nocturnal polyuria); neurological symptoms; sexual function; **planned cataract surgery**."],
        ["Key examination", "Palpable bladder; genitalia (meatal stenosis, phimosis); **DRE: smooth, rubbery, sulcus preserved = BPH; hard, nodular, sulcus lost = cancer**; perineal sensation, anal tone; BP, oedema."],
        ["Minimal investigations", "**Urinalysis**; creatinine if retention suspected; **3-day frequency-volume chart** (nocturnal polyuria over 33% at night); **PVR under 50 normal, over 100-150 significant, over 300 chronic retention**; uroflow **Qmax under 10 mL/s obstructed**; PSA after counselling (**over 1.5 = gland over 30 g**)."],
        ["Treatment - first line", "Mild/non-bothersome: **watchful waiting** + evening fluid cut, less caffeine/alcohol, double voiding, bladder training. Bothersome: **tamsulosin 0.4 mg OD after same meal** (silodosin 8 mg, alfuzosin 10 mg)."],
        ["Escalation / second line", "Gland over 30-40 g or PSA over 1.5: **add finasteride 5 mg or dutasteride 0.5 mg** (halves retention and surgery; 6-12 months to act); storage with **PVR under 150**: solifenacin 5 mg or **mirabegron 25-50 mg**; ED: **tadalafil 5 mg**; nocturnal polyuria: desmopressin with sodium checks."],
        ["Devices / procedures", "Retention: **14-16 Fr Foley**, start tamsulosin, **TWOC after 2-3 days**; CISC for chronic retention; surgery - **TURP 30-80 g, HoLEP any size, TUIP under 30 g**, simple prostatectomy over 80 g; Rezum, urethral lift preserve ejaculation."],
        ["Special groups", "Elderly: antimuscarinic cognitive harm - prefer mirabegron; **alpha blocker - floppy iris, tell eye surgeon**; 5-ARI - PSA halves (double it), women of child-bearing age must not handle; CKD - silodosin avoid under CrCl 30."],
        ["Complications", "**Acute and chronic retention**, UTI, bladder stones, diverticula, haematuria, **obstructive uropathy and CKD**, post-obstructive diuresis; drug side effects - postural hypotension, retrograde ejaculation, sexual dysfunction."],
        ["Red flags and referral", "**Suspicious DRE or raised age-specific PSA**, visible haematuria, retention with raised creatinine or hydronephrosis, neurological signs, men under 45, flat flow (stricture), failed maximal medical therapy."],
        ["Follow-up and monitoring", "Alpha blocker **4-6 weeks**, 5-ARI **3-6 months**, then 6-12 monthly: IPSS (**fall of 3+ = response**), PVR, creatinine; PSA on 5-ARI doubled."],
        ["Absolute indications for surgery", "**Refractory retention, recurrent UTI, bladder stones, recurrent gross haematuria, renal impairment from BPO**, large diverticula."],
        ["Exam one-liners", "Size correlates poorly with symptoms; **alpha blockers act in days, 5-ARIs in months and alone reduce retention**; check PVR before antimuscarinic; replace **half to two-thirds** of post-obstructive diuresis; saw palmetto = placebo."],
      ],
    },
    flows: [
      {
        kind: "ladder",
        heading: "BPH drug ladder by problem",
        caption: "Step by the dominant problem, not the PSA alone.",
        steps: [
          { label: "Mild or non-bothersome: watchful waiting", detail: "Evening fluids, caffeine, double voiding, bladder training; review 6-12 months" },
          { label: "Bothersome voiding: alpha-1 blocker", detail: "Tamsulosin 0.4 mg OD after the same meal; acts in days" },
          { label: "Gland over 30-40 g or PSA over 1.5: add 5-ARI", detail: "Finasteride 5 mg or dutasteride 0.5 mg; 6-12 months; halves retention and surgery" },
          { label: "Storage symptoms, PVR under 150 mL", detail: "Add mirabegron 25-50 mg or solifenacin 5 mg; recheck PVR at 4-6 weeks", tone: "decision" },
          { label: "Complicated or failed medical therapy: surgery", detail: "TURP 30-80 g, HoLEP any size, TUIP under 30 g", tone: "warn" },
        ],
      },
      {
        kind: "flow",
        heading: "Acute urinary retention - catheter to trial without catheter",
        steps: [
          { label: "Painful, palpable, dull bladder", detail: "Painless with large volume = chronic retention", tone: "decision" },
          { label: "Catheterise 14-16 Fr, record volume", detail: "Over 1 L = acute-on-chronic; check creatinine, culture" },
          { label: "Watch post-obstructive diuresis", detail: "Over 200 mL/h for 2 h - replace half to two-thirds", tone: "warn" },
          { label: "Start tamsulosin 0.4 mg, remove precipitant", detail: "Decongestant, anticholinergic, constipation, UTI, alcohol" },
          { label: "Trial without catheter at 2-3 days", detail: "Success roughly doubled by the alpha blocker", tone: "good" },
          { label: "Failed TWOC, raised creatinine, hydronephrosis", detail: "CISC or catheter, add 5-ARI, refer for surgery", tone: "warn" },
        ],
      },
    ],
  },
  "renal-urology-renal-stones": {
    checked: "2026-10",
    updated: [
      "AUA 2026 medical management of kidney stones: water for urine volume 2.5 L/day or more; thiazide offered for recurrent calcium stones with high or relatively high urinary calcium (targeted, not universal); alkali (potassium citrate) for recurrent calcium oxalate stones and calcium stones in children (replaces AUA 2014/2019)",
    ],
    master: {
      heading: "Master revision table - Renal and ureteric stones",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Crystalline concretions in the urinary tract (nephrolithiasis, ureterolithiasis); ureteric stone causes **renal colic**; recurrence **about 50% in 5-10 years**."],
        ["Relevant classification", "By composition: **calcium oxalate 70-80%**, calcium phosphate 5-10%, **uric acid 5-10% (radiolucent)**, **struvite 5-10% (staghorn, urease)**, cystine 1-2%; by size/site: **5 mm or less pass 70%, 5-10 mm 50%**, over 10 mm rarely; high-risk formers."],
        ["Aetiology and risk factors", "**Low urine volume (heat, Indian stone belt)**, high salt and animal protein, low dietary calcium, hypercalciuria, hyperoxaluria (bowel disease), hypocitraturia, gout/metabolic syndrome, dRTA, hyperparathyroidism, UTI with Proteus, topiramate."],
        ["Pathophysiology", "Low volume + high solute -> **supersaturation** -> nucleation on **Randall's plaque** -> growth (low citrate) -> impaction at **PUJ, pelvic brim, VUJ** -> proximal distension + prostaglandin spasm -> colic; obstruction + infection -> **pyonephrosis**."],
        ["Key history (OPD)", "Sudden **loin-to-groin colic, restless**, nausea; VUJ - strangury, testicular/labial pain; **fever with colic = emergency**; anuria (solitary kidney); previous stones, analysis; diet, fluids, drugs; **LMP**; man over 50 - think AAA."],
        ["Key examination", "Vitals and urine output; writhing vs still (peritonitis); renal angle tenderness; **pulsatile mass and femoral pulses**; testes and hernial orifices; zoster vesicles; distended bladder."],
        ["Minimal investigations", "Dipstick: **haematuria 85%**, pH over 7 struvite, under 5.5 uric acid; CBC, creatinine, Ca, uric acid, CRP; **non-contrast low-dose CT KUB gold standard**; **USG first in pregnancy and children**; strain urine, **stone analysis**; 24-h urine x2 in high-risk formers 4-6 weeks later."],
        ["Treatment - first line", "**NSAID first: diclofenac 75 mg IM or ketorolac 30 mg IV**; paracetamol 1 g IV if NSAID contraindicated or pregnant; opioid second line; no antispasmodics; **MET: tamsulosin 0.4 mg OD up to 4 weeks for distal 5-10 mm**."],
        ["Escalation / interventions", "**Ureteric over 10 mm: URS + laser**; renal under 20 mm: SWL or RIRS; **renal over 20 mm or staghorn: PCNL**; SWL fails over 1000 HU, skin-to-stone over 10 cm; complete clearance for struvite."],
        ["Emergency decompression", "**Infected obstructed kidney**: cultures, IV antibiotics within 1 hour (ceftriaxone; meropenem if ESBL/shock) and **nephrostomy or JJ stent within hours**; also solitary kidney, bilateral obstruction, AKI, intractable pain."],
        ["Prevention (AUA 2026)", "**Water for urine 2.5 L/day or more**; **normal calcium 1000-1200 mg/day**; sodium under 2.3 g/day; less animal protein; **thiazide for recurrent calcium stones with high urinary calcium** (HCTZ 25 mg BD / chlorthalidone 25 mg) + **potassium citrate 30-60 mEq/day**; allopurinol for hyperuricosuria."],
        ["Special groups", "**Pregnancy**: USG, paracetamol, **no NSAIDs after 20 weeks**, no tamsulosin, stent/nephrostomy if obstructed; children - USG, metabolic work-up always; **uric acid - alkalinise to pH 6.5-7.0** (dissolves); cystine - 3-4 L fluid, pH 7.0-7.5, tiopronin."],
        ["Complications", "Pyonephrosis and urosepsis, AKI, **loss of renal function after 2-6 weeks of complete obstruction**, steinstrasse after SWL, **forgotten encrusted JJ stent**, recurrence."],
        ["Red flags and referral", "Fever + hydronephrosis; solitary/transplant kidney; anuria; rising creatinine; **pain that suddenly stops** (complete obstruction); man over 50 with pulsatile mass; woman of reproductive age without pregnancy test."],
        ["Follow-up and monitoring", "Review **2-4 weeks** with imaging; **do not watch an obstructing stone beyond 4-6 weeks**; on prevention drugs repeat 24-h urine at 3-6 months; K, uric acid, glucose on thiazide; home pH strips for uric acid/cystine."],
        ["Latest guideline change", "**AUA 2026** medical management: thiazide targeted to recurrent calcium stones with high urinary calcium; alkali for recurrent calcium oxalate; water for 2.5 L urine/day."],
        ["Exam one-liners", "Colic writhes, peritonitis lies still; **NSAIDs beat opioids; forced IV fluids do not flush stones**; never restrict dietary calcium; **E. coli does not make struvite**; send every stone for analysis."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Renal colic - emergency room to discharge",
        caption: "Exam version: analgesia, exclude the dangerous, then size and site decide.",
        steps: [
          { label: "Loin-to-groin colic, restless", detail: "Pregnancy test in women; AAA in men over 50", tone: "decision" },
          { label: "Analgesia: diclofenac 75 mg IM", detail: "Paracetamol 1 g IV if NSAID contraindicated; opioid second line" },
          { label: "Fever, solitary kidney, anuria or AKI?", detail: "IV antibiotics within 1 h + nephrostomy or JJ stent within hours", tone: "warn" },
          { label: "Low-dose non-contrast CT KUB", detail: "USG first in pregnancy and children", tone: "decision" },
          { label: "Distal 5-10 mm: tamsulosin 0.4 mg up to 4 weeks", detail: "Under 5 mm usually passes; over 10 mm - ureteroscopy" },
          { label: "Review at 2-4 weeks with imaging", detail: "Strain urine, analyse stone; never watch beyond 4-6 weeks", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Preventing the next stone - AUA 2026 ladder",
        steps: [
          { label: "Water for urine 2.5 L/day or more", detail: "Pale urine; glass at bedtime; 3-3.5 L intake in Indian summers" },
          { label: "Diet", detail: "Normal calcium 1000-1200 mg; sodium under 2.3 g; less animal protein; more fruit and vegetables" },
          { label: "Stone analysis and metabolic work-up", detail: "High-risk or recurrent formers: two 24-h urines 4-6 weeks after the episode", tone: "decision" },
          { label: "Targeted drugs", detail: "Thiazide if recurrent calcium stones with high urinary calcium; potassium citrate 30-60 mEq/day for recurrent CaOx/hypocitraturia; allopurinol 100-300 mg for hyperuricosuria" },
          { label: "Recheck 24-h urine at 3-6 months", detail: "K, uric acid, glucose on thiazide; yearly thereafter", tone: "good" },
        ],
      },
    ],
  },
  "renal-urology-hyponatraemia-hyperkalaemia": {
    checked: "2026-10",
    updated: [
      "ERC 2025: membrane stabilisation - calcium chloride 10% 10 mL IV over 5 min first, or calcium gluconate 10% 30 mL over 10 min",
      "ERC 2025: no routine IV sodium bicarbonate for hyperkalaemia outside cardiac arrest; in hyperkalaemic arrest give calcium chloride 10 mL and sodium bicarbonate 50 mmol",
      "KDIGO 2024: oral bicarbonate threshold for CKD acidosis corrected to bicarbonate under 18 mmol/L (was under 22) to match the CKD topic",
    ],
    master: {
      heading: "Master revision table - Hyponatraemia and hyperkalaemia",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Hyponatraemia: Na under 135** (mild 130-134, moderate 125-129, **profound under 125**); **hyperkalaemia: K over 5.5** (mild 5.5-5.9, moderate 6.0-6.4, **severe 6.5+**; **any ECG change = emergency**)."],
        ["Relevant classification", "Hyponatraemia: acute (under 48 h) vs **chronic (48 h+ or unknown)**; moderately severe vs **severe symptoms**; **hypotonic by volume + urine Osm + urine Na**. Hyperkalaemia: pseudo, reduced excretion, shift, load."],
        ["Aetiology and risk factors", "Na: **thiazides (elderly thin women)**, SSRIs, carbamazepine, SIADH (pneumonia, TB, CNS, SCLC), GI loss with hypotonic fluid, HF, cirrhosis, hypothyroid, adrenal insufficiency, beer potomania. K: **CKD/AKI + ACEi/ARB/MRA**, trimethoprim, NSAIDs, **KCl salt substitute**, DKA, rhabdo, type 4 RTA."],
        ["Pathophysiology", "Na: ADH (V2 -> aquaporin-2) retains water -> dilution -> **cerebral oedema** -> brain adapts in 48 h -> fast correction -> **osmotic demyelination**. K: high ECF K -> less negative RMP -> Na channel inactivation -> **peaked T, wide QRS, sine wave, VF**."],
        ["Key history (OPD)", "Na: headache, vomiting, confusion, seizures; falls, attention in chronic; drugs; fluids; cough, TB, smoking; Addison features. K: palpitations, weakness; **drug list**, salt substitute, coconut water, CKD, intercurrent vomiting."],
        ["Key examination", "**Volume status** (postural BP, JVP, oedema, ascites) - pivot of the algorithm; GCS; pigmentation (Addison); hypothyroid signs; chest. K: pulse rhythm, power, uraemic signs, urine output."],
        ["Minimal investigations", "Na: **serum Osm** (exclude pseudo and hyperglycaemia - add 1.6-2.4 per 100 mg/dL glucose) -> **urine Osm (100 or less = polydipsia/low solute)** -> **urine Na (30 or less = low effective volume)**; TSH, 8 am cortisol before SIADH. K: **ECG now**, repeat clean sample/VBG, creatinine, bicarbonate, glucose, CK."],
        ["Diagnostic criteria", "**SIADH**: hypotonic, euvolaemic, urine Osm over 100, urine Na over 30, normal thyroid, adrenal, kidney, no diuretic; low urea and uric acid support."],
        ["Treatment - first line (Na)", "**Severe symptoms: 3% saline 150 mL over 20 min, repeat up to 2 more times until Na up 5**; moderately severe: single 150 mL bolus; hypovolaemic: 0.9% saline; SIADH: **fluid restriction 500-1000 mL/day**; stop offending drug; **limit rise to 10 in 24 h (8 if high risk, aim 4-6)**."],
        ["Escalation / second line (Na)", "SIADH failing restriction: **oral urea 15-30 g/day**, salt 2-3 g + furosemide 20-40 mg, **tolvaptan 15 mg (hospital start, under 30 days)**; overcorrection: **5% dextrose 3 mL/kg/h + desmopressin 2 microgram IV 6-8 hourly**; adrenal: hydrocortisone 100 mg IV."],
        ["Treatment - hyperkalaemia", "**Protect: calcium chloride 10% 10 mL over 5 min or gluconate 10% 30 mL over 10 min** -> **shift: insulin 10 units + glucose 25 g** (10% glucose 50 mL/h x 5 h if glucose under 7 mmol/L) + **salbutamol 10-20 mg neb** -> **remove: SZC 10 g TDS up to 72 h**, patiromer, furosemide, **dialysis**; no routine IV bicarbonate outside arrest."],
        ["Special groups", "Elderly: thiazide hyponatraemia, desmopressin risk; alcoholics, malnourished, hypokalaemic - highest ODS risk; **cerebral salt wasting after SAH - do not restrict fluids**; CKD - keep RASi with binder; digoxin - give calcium slowly."],
        ["Complications", "Seizures, coma, herniation; **osmotic demyelination 2-6 days after overcorrection** (dysarthria, quadriparesis, locked-in); falls and fractures; hyperkalaemic arrhythmia, arrest; insulin hypoglycaemia."],
        ["Red flags and referral", "Na with seizures/coma; **rise over 10 in 24 h or brisk dilute diuresis**; Na under 120; Addisonian features; K 6.5+ or ECG change; K with oliguria; bradycardia on beta-blocker/digoxin."],
        ["Follow-up and monitoring", "Na during boluses every 20 min, then 4-6 hourly; **write the 24-h target on the chart**; Na 1-2 weeks after thiazide/SSRI in elderly; **K and creatinine 1-2 weeks after RASi, MRA, finerenone**; repeat K at 1, 2, 4, 6 h after acute treatment."],
        ["Latest guideline change", "**ERC 2025**: calcium chloride 10 mL (or gluconate 30 mL) first; **no routine bicarbonate outside arrest**; arrest - calcium chloride + bicarbonate 50 mmol; hyponatraemia still ESE 2014."],
        ["Exam one-liners", "Hyponatraemia is a **water problem**; **saline worsens SIADH**; never rechallenge a thiazide; **calcium protects, insulin shifts, only binders or dialysis remove**; normal ECG does not exclude dangerous K; low-sodium salt = KCl."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Hyponatraemia - symptoms first, then the three tests",
        caption: "Condensed ESE pathway: severe symptoms are treated before any test result.",
        steps: [
          { label: "Severe symptoms? Seizure, coma, vomiting", detail: "3% saline 150 mL over 20 min, up to 3 times until Na up 5", tone: "warn" },
          { label: "Serum osmolality under 275?", detail: "Normal - pseudo; high - glucose or mannitol", tone: "decision" },
          { label: "Urine osmolality 100 or less?", detail: "Polydipsia, beer potomania, tea-and-toast", tone: "decision" },
          { label: "Urine Na 30 or less?", detail: "GI loss, HF, cirrhosis - low effective volume", tone: "decision" },
          { label: "Urine Na over 30: diuretic, adrenal, SIADH", detail: "TSH and 8 am cortisol before calling it SIADH" },
          { label: "Correct no more than 10 mmol/L in 24 h", detail: "8 if high risk; overcorrection - dextrose + desmopressin", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Hyperkalaemia - protect, shift, remove (ERC 2025)",
        steps: [
          { label: "Confirm and ECG", detail: "Clean sample or VBG K; ECG change at any level = emergency", tone: "decision" },
          { label: "Protect the heart", detail: "Calcium chloride 10% 10 mL over 5 min or gluconate 10% 30 mL over 10 min; repeat if ECG unchanged", tone: "warn" },
          { label: "Shift into cells", detail: "Insulin 10 units + glucose 25 g IV; salbutamol 10-20 mg neb; glucose hourly for 6 h" },
          { label: "Remove from the body", detail: "SZC 10 g TDS up to 72 h, patiromer 8.4 g, furosemide 40-80 mg; dialysis if refractory or oliguric" },
          { label: "Prevent recurrence", detail: "Stop KCl salt, NSAIDs, trimethoprim; keep RASi with binder; recheck in 1 week", tone: "good" },
        ],
      },
    ],
  },
  "renal-urology-drug-dosing-renal-impairment": {
    checked: "2026-10",
    updated: [
      "DOAC renal dose criteria re-checked against ESC 2024 AF guideline (unchanged doses; citation updated from EHRA 2021)",
    ],
    master: {
      heading: "Master revision table - Drug dosing in renal impairment",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Prescribing for reduced clearance of active drug or metabolite; drugs with **over 30% renal elimination** need adjustment; **stage with eGFR, dose with Cockcroft-Gault CrCl (mL/min)**."],
        ["Relevant classification", "KDIGO G1-G5 bands (G3a 45-59, G3b 30-44, G4 15-29, G5 under 15); the **four actions: reduce dose, lengthen interval, avoid, monitor levels**; is it nephrotoxic, is it dialysed?"],
        ["Key formula", "**CrCl = (140 - age) x weight / (72 x creatinine mg/dL), x 0.85 female**; ideal or adjusted weight in obesity; **de-index eGFR = eGFR x BSA / 1.73**; cystatin C for narrow-index drugs."],
        ["Pathophysiology", "Falling GFR -> longer half-life -> higher steady state after 4-5 half-lives -> toxicity days later; **loading dose depends on Vd (unchanged)**; metabolites accumulate (**morphine-6-glucuronide, norpethidine, glibenclamide**); low albumin raises free phenytoin."],
        ["Key history (OPD)", "Full list incl. **OTC NSAIDs, combination 'body pain' tablets, ayurvedic tonics**; last creatinine; intercurrent vomiting/diarrhoea; dialysis type and days; transplant drugs; toxicity symptoms (drowsiness, myoclonus, hypoglycaemia, bleeding)."],
        ["Key examination", "**Weight every visit**; volume status; postural BP; toxicity signs (asterixis, lithium tremor, digoxin bradycardia); muscle wasting (creatinine overestimates GFR)."],
        ["Minimal investigations", "Creatinine + eGFR + calculated CrCl **written on the prescription**; K 1-2 weeks after RASi/MRA/trimethoprim; **TDM**: gentamicin trough under 1 mg/L, **vancomycin AUC 400-600**, digoxin 0.5-0.9 ng/mL, lithium 0.4-0.8."],
        ["Diabetes drugs", "**Metformin full at 45+, max 1000 mg at 30-44, stop under 30**; **SGLT2i start if eGFR 20+, continue to dialysis**; sitagliptin 100/50/25 mg; **linagliptin and teneligliptin no change**; avoid glibenclamide; insulin -25% at GFR 10-50."],
        ["Analgesics and CNS drugs", "**Paracetamol safe; no NSAIDs under eGFR 30**; avoid morphine and pethidine - fentanyl/buprenorphine; tramadol max 200 mg/day 12-hourly if CrCl under 30; **gabapentin/pregabalin reduce by CrCl**; baclofen avoid in G4-5; lithium avoid in G4-5."],
        ["Cardiovascular drugs", "**Apixaban 2.5 mg BD if CrCl 15-29 or 2 of age 80+, weight 60 kg or less, creatinine 1.5+**; rivaroxaban 15 mg if CrCl 15-49; **dabigatran avoid under 30**; enoxaparin 1 mg/kg OD if CrCl under 30; digoxin 62.5-125 microgram with levels; rosuvastatin max 10 mg if CrCl under 30."],
        ["Antimicrobials", "**Full first dose always**; no change - azithromycin, doxycycline, ceftriaxone, moxifloxacin, rifampicin, isoniazid; reduce - beta-lactams, carbapenems, cipro/levo, co-trimoxazole, acyclovir; **avoid nitrofurantoin under eGFR 45**, aminoglycosides; TB - **PZA and EMB thrice weekly if CrCl under 30**; TDF -> TAF."],
        ["Special groups", "**Haemodialysis: dose as CrCl under 10, give dialysable drugs after the session**; CAPD - IP antibiotics; CRRT - higher doses; **transplant - CYP3A4 interactions with tacrolimus**; elderly - 'normal' creatinine hides CrCl 25; AKI - assume CrCl under 10-20 while rising."],
        ["Complications", "Lactic acidosis (metformin), hypoglycaemia, opioid and gabapentinoid encephalopathy, carbapenem/acyclovir seizures, bleeding on DOAC/LMWH, aminoglycoside oto-nephrotoxicity, lithium toxicity, **'triple whammy' AKI**."],
        ["Red flags and referral", "OTC diclofenac in CKD; metformin in sepsis or eGFR under 30; tinnitus on aminoglycoside; **transplant patient started on rifampicin or clarithromycin**; lithium toxicity after thiazide/ACEi/NSAID; bleeding with falling CrCl."],
        ["Follow-up and monitoring", "Recalculate CrCl and **review every renally dosed drug at each visit and after any AKI or admission**; creatinine and K 3-6 monthly in G3-4; yearly structured medication review; report ADRs to **PvPI**."],
        ["Prevention", "**No-NSAID card, written sick-day rules (SADMANS)**, deprescribe PPIs, avoid nephrotoxic combinations (vancomycin + pip-taz), polyethylene glycol not phosphate enemas, group II gadolinium."],
        ["Exam one-liners", "Loading dose never changes (except digoxin); **aminoglycosides keep the dose, lengthen the interval; beta-lactams keep the interval, reduce the dose**; trimethoprim, cimetidine, dolutegravir raise creatinine without harm; in evolving AKI every equation overestimates."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Prescribing for a patient with CKD - five questions",
        caption: "Run every new drug through this before signing the prescription.",
        steps: [
          { label: "Is kidney function stable?", detail: "Rising creatinine (AKI) - assume CrCl under 10-20 for toxic drugs", tone: "decision" },
          { label: "Calculate Cockcroft-Gault CrCl", detail: "Ideal or adjusted weight in obesity; cystatin C for narrow-index drugs" },
          { label: "Give the full loading dose", detail: "Never reduce the first antibiotic dose in sepsis", tone: "warn" },
          { label: "Reduce dose, lengthen interval, avoid or monitor", detail: "Concentration-dependent: lengthen interval; time-dependent: reduce dose", tone: "decision" },
          { label: "Nephrotoxic or dialysed?", detail: "Avoid NSAIDs; dialysable drugs after the session" },
          { label: "Write CrCl and date on the prescription", detail: "Review at each visit and after any AKI", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Common OPD drugs at eGFR 30-44 vs under 30",
        columns: ["Drug", "eGFR 30-44", "Under 30"],
        rows: [
          ["Metformin", "Max 1000 mg/day; do not start", "Stop"],
          ["SGLT2 inhibitor", "Continue 10 mg (kidney protection)", "Start if 20+; continue to dialysis"],
          ["Nitrofurantoin", "Avoid (under 45)", "Contraindicated"],
          ["Apixaban (AF)", "5 mg BD unless 2 criteria", "2.5 mg BD at CrCl 15-29"],
          ["Gabapentin", "200-700 mg BD", "200-700 mg OD (15-29)"],
          ["NSAIDs", "Avoid", "Contraindicated"],
        ],
      },
    ],
  },
  "renal-urology-proteinuria-nephrotic-nephritic": {
    checked: "2026-10",
    updated: [
      "KDIGO 2025 IgA nephropathy: proteinuria 0.5 g/day or more defines risk; treat immune process and nephron loss together (not 90 days of supportive care first); target proteinuria under 0.5 g/day (ideally under 0.3) and eGFR loss under 1 mL/min/year",
      "KDIGO 2025 nephrotic syndrome in children: total first-episode steroid course 8-12 weeks retained (longer courses not adopted); ISPN 6 + 6 week schedule fits",
    ],
    master: {
      heading: "Master revision table - Proteinuria, nephrotic and nephritic syndromes",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Proteinuria over **150 mg/day**; **nephrotic = proteinuria over 3.5 g/day (PCR over 3000 mg/g; child over 40 mg/m2/h or UPCR 2+ mg/mg) + albumin under 3.0 g/dL + oedema + hyperlipidaemia**; **nephritic = haematuria with RBC casts, HTN, oliguria, rising creatinine**."],
        ["Relevant classification", "Albuminuria **A1 under 30, A2 30-300, A3 over 300 mg/g**; RPGN types **1 anti-GBM (linear), 2 immune complex (granular), 3 pauci-immune (ANCA)**; childhood NS by steroid response - sensitive, **frequently relapsing, dependent, resistant**."],
        ["Aetiology", "Nephrotic: **MCD (90% under 10 y)**, **FSGS (commonest in Indian adults)**, **membranous (anti-PLA2R)**, diabetes, amyloid, lupus, HBV/HCV/HIV, **mercury skin creams**. Nephritic: **PSGN**, **IgA nephropathy**, lupus, ANCA, anti-GBM, IgA vasculitis."],
        ["Pathophysiology", "Nephrotic: **podocyte effacement** -> albumin leak, bland sediment -> low oncotic pressure + **ENaC activation** -> oedema; losses of ATIII (thrombosis), IgG (infection). Nephritic: immune complexes -> complement -> **proliferation** -> low GFR, HTN, RBC casts -> crescents (RPGN)."],
        ["Key history (OPD)", "Morning facial puffiness, frothy urine; cola urine, oliguria, headache; **latency - throat 1-3 weeks / skin 3-6 weeks (PSGN) vs 1-3 days (IgA)**; rash, arthritis, haemoptysis; drugs, skin creams; diabetes with retinopathy; relapse diary in children."],
        ["Key examination", "Weight, height centile, BP; oedema, ascites, effusion; **hypovolaemia despite oedema in children**; peritonitis, cellulitis, scabies scars; lupus/vasculitis signs; fundus; thrombosis signs."],
        ["Minimal investigations", "**First-morning ACR or PCR** (dipstick misses A2 and light chains); confirm 2 of 3; **fresh urine microscopy** - RBC casts vs oval fat bodies; creatinine, albumin, lipids, USG; **C3/C4, ASO, ANA/dsDNA, ANCA, anti-GBM, anti-PLA2R**, HBsAg, HCV, HIV, SFLC over 40."],
        ["Biopsy rules", "**All adult nephrotic** (except typical DKD or PLA2R-positive membranous), **child under 1 or over 12**, steroid-resistant or atypical child, **any RPGN urgently**, C3 still low at 8-12 weeks; **no biopsy for typical child 1-12**."],
        ["Treatment - first line", "Child first episode: **prednisolone 60 mg/m2/day (max 60) 6 weeks then 40 mg/m2 alternate days 6 weeks** (KDIGO 2025: 8-12 weeks total); relapse 60 mg/m2 until remission 3 days then 40 mg/m2 AD 4 weeks; adult MCD 1 mg/kg (max 80) up to 16 weeks; **salt under 5 g**, furosemide, max ACEi/ARB + SGLT2i."],
        ["Escalation / second line", "FRNS/SDNS: **levamisole 2-2.5 mg/kg AD**, MMF, cyclophosphamide 2 mg/kg x 12 weeks, tacrolimus, **rituximab**; SRNS: biopsy, genetics, CNI + ACEi; membranous moderate-high risk: **rituximab 1 g x 2** or modified Ponticelli; **IgAN at 0.5+ g/day: RASi/sparsentan + SGLT2i with TRF-budesonide 16 mg x 9 months together**."],
        ["Systemic GN", "Lupus III-IV: **MMF 2-3 g/day or Euro-Lupus cyclophosphamide** + steroids + belimumab/voclosporin + **HCQ for all**; ANCA/anti-GBM: **IV methylprednisolone 500-1000 mg x 3**, rituximab or cyclophosphamide, **plasma exchange in anti-GBM**."],
        ["Special groups", "Children - home dipstick, vaccinate (PCV then PPSV23), **live vaccines only off high-dose steroid 4 weeks**, VZIG within 10 days; pregnancy - stop ACEi/ARB, MMF, SGLT2i; adults over 50 - screen for malignancy and myeloma."],
        ["Complications", "**Peritonitis (pneumococcal)**, cellulitis, **renal vein thrombosis/PE** (membranous, albumin under 2.5), hypovolaemic crisis, AKI, hyperlipidaemia; nephritic - **hypertensive encephalopathy, pulmonary oedema**, RPGN to ESKD; steroid toxicity."],
        ["Red flags and referral", "**Pulmonary-renal syndrome**, eGFR falling 50% in days-weeks (RPGN) - same day; child with fever + abdominal pain (SBP); cold peripheries + tachycardia (hypovolaemia); **all adult nephrotic**; proteinuria over 1 g/day."],
        ["Follow-up and monitoring", "Weight, BP, PCR, creatinine, albumin each visit; **complete remission under 0.3 g/day**; PSGN - **C3 normal by 6-8 weeks**; steroid toxicity (growth, eyes, bone); anticoagulate if albumin under 2.0-2.5 with risk."],
        ["Latest guideline change", "**KDIGO 2025 IgAN**: risk at proteinuria 0.5 g/day, **simultaneous** immune + supportive therapy, target under 0.5 (ideally 0.3); **KDIGO 2025 paediatric NS**: 8-12 weeks first-episode course kept."],
        ["Exam one-liners", "**RBC cast = glomerular**; low C3 normal C4 = PSGN/C3G, both low = lupus/cryo, normal = IgA/ANCA/anti-GBM; **PLA2R can spare biopsy, never the malignancy screen**; adaptive FSGS - no steroids; relapse = 3+ for 3 days."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Proteinuria found on a dipstick - exam work-up",
        caption: "From a dipstick to the right referral in five decisions.",
        steps: [
          { label: "Quantify: first-morning ACR or PCR", detail: "Exclude UTI, fever, exercise, heart failure; repeat 2 of 3 over 3 months" },
          { label: "First-morning sample normal?", detail: "Yes - orthostatic proteinuria; reassure", tone: "decision" },
          { label: "RBC casts or dysmorphic RBC?", detail: "Nephritic - C3/C4, ASO, ANA, ANCA, anti-GBM; RPGN same day", tone: "warn" },
          { label: "PCR over 3000 with low albumin, oedema?", detail: "Nephrotic - child 1-12 steroids; adult biopsy (PLA2R first)", tone: "decision" },
          { label: "Sub-nephrotic, bland sediment", detail: "Max ACEi/ARB + SGLT2i; refer if over 1 g/day or eGFR falling", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Childhood steroid-sensitive nephrotic syndrome ladder",
        steps: [
          { label: "First episode", detail: "Prednisolone 60 mg/m2/day x 6 weeks, then 40 mg/m2 alternate days x 6 weeks (KDIGO 2025: 8-12 weeks total)" },
          { label: "Relapse (3+ for 3 days)", detail: "60 mg/m2/day until nil/trace 3 days, then 40 mg/m2 alternate days x 4 weeks" },
          { label: "Frequently relapsing or steroid-dependent", detail: "Levamisole 2-2.5 mg/kg AD 12-24 months, MMF, cyclophosphamide 2 mg/kg x 12 weeks", tone: "decision" },
          { label: "Still dependent", detail: "Tacrolimus 0.1-0.2 mg/kg/day or rituximab 375 mg/m2" },
          { label: "Steroid-resistant (no remission at 4 weeks)", detail: "Biopsy, genetic testing, CNI + ACE inhibitor - paediatric nephrologist", tone: "warn" },
        ],
      },
      {
        kind: "ladder",
        heading: "IgA nephropathy - KDIGO 2025 dual approach",
        steps: [
          { label: "Confirm by biopsy", detail: "Adults with suspected IgAN and proteinuria 0.5 g/day or more" },
          { label: "Treat nephron loss", detail: "Maximal ACEi/ARB or sparsentan, BP control, SGLT2 inhibitor, lifestyle" },
          { label: "Treat the immune process at the same time", detail: "Targeted-release budesonide 16 mg OD x 9 months, or guarded steroids with PJP prophylaxis", tone: "decision" },
          { label: "Target", detail: "Proteinuria under 0.5 g/day (ideally under 0.3); eGFR loss under 1 mL/min/year", tone: "good" },
        ],
      },
    ],
  },
  "renal-urology-urinary-incontinence": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - Urinary incontinence",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Any involuntary loss of urine**; 25-45% of adult women, a third of over-65s; OAB = urgency with frequency and nocturia, with or without urgency incontinence."],
        ["Relevant classification", "**Stress** (effort), **urgency** (detrusor overactivity), **mixed** (treat predominant), **overflow** (retention), **functional** (cognition/mobility), **continuous** (fistula, ectopic ureter)."],
        ["Aetiology and risk factors", "**Parity and vaginal delivery**, obesity, chronic cough, menopause, age, prostatectomy; neurological disease (stroke, PD, MS, cord), diabetes; drugs; **obstructed labour (fistula)**; **DIAPPERS** reversible causes."],
        ["Pathophysiology", "Continence = urethral pressure over bladder pressure; **SUI: loss of hammock support / intrinsic sphincter deficiency**; **UUI: involuntary M3-driven detrusor contraction**; overflow: obstruction or underactive detrusor -> residual -> dribble; fistula: pressure necrosis -> slough day 3-10."],
        ["Key history (OPD)", "**Ask routinely**; leak with cough/lift vs urge, key-in-door; pads/day, **ICIQ-UI SF**; voiding symptoms; **continuous leak after obstructed labour/hysterectomy**; haematuria, pain, recurrent UTI; obstetric history, prolapse; drugs; neuro symptoms; cognition."],
        ["Key examination", "BMI, cognition, mobility; **palpable bladder**; pelvic exam - atrophy, **prolapse (POP-Q)**, fistula; **Modified Oxford 0-5** pelvic floor squeeze; **cough stress test** (simultaneous leak = SUI); S2-S4 sensation, anal tone; rectal for impaction, prostate."],
        ["Minimal investigations", "**3-day bladder diary**; urine dipstick (do not treat ASB); **PVR - under 50 normal, over 200 refer**; glucose, creatinine; **urodynamics not needed before conservative care or surgery for pure SUI**; three-swab dye test for fistula."],
        ["Treatment - first line", "Treat DIAPPERS; weight loss if BMI over 30, caffeine down, fluids 1.5-2 L; **SUI: supervised PFMT 3 months, 8 contractions x 3/day, 'the knack'**; **UUI: bladder training 6 weeks** (+15 min/week, urge suppression); timed/prompted voiding for functional."],
        ["Escalation / second line - drugs", "OAB: **mirabegron 25-50 mg OD** (preferred in frail/cognitive risk; check BP) or **solifenacin 5-10 mg**, trospium 20 mg BD; **no oxybutynin in frail elderly**; review at 4 weeks; **vaginal estriol 0.5 mg nightly 2 weeks then twice weekly**; duloxetine 40 mg BD second-line SUI."],
        ["Devices / procedures", "**Pessary** (review 3-6 monthly with vaginal oestrogen); **CISC 4-6 times/day, volume under 400-500 mL**; indwelling catheter last resort; sheath for men; refractory OAB - **botulinum toxin 100 U** (must accept CISC), PTNS, SNM; SUI surgery - **midurethral sling, colposuspension, fascial sling, bulking**."],
        ["Special groups", "**Elderly: anticholinergic burden -> cognitive decline**, DHIC - check PVR; men - BPH, post-prostatectomy (PFMT then sling/AUS); pregnancy - PFMT, no drugs; **PFMT in first pregnancy prevents postnatal UI**."],
        ["Complications", "Incontinence-associated dermatitis, UTI, falls at night, depression, social isolation, carer strain; antimuscarinic retention and confusion; mesh exposure and pain after slings."],
        ["Red flags and referral", "**Haematuria**, **continuous leakage (fistula)**, PVR over 200 or palpable bladder, **cauda equina features**, rising creatinine/hydronephrosis, recurrent UTI, prolapse beyond introitus, failed PFMT wanting surgery, OAB failing 2 drugs."],
        ["Follow-up and monitoring", "PFMT at **3 months**, bladder training at **6 weeks**, drugs at **4 weeks** (efficacy, dry mouth, BP, cognition) with repeat diary and ICIQ-UI; PVR 4-6 weeks after OAB drug in older men and diabetics."],
        ["Prevention / programme", "Antenatal PFMT, timely caesarean and **WHO Labour Care Guide** to prevent obstetric fistula; catheter avoidance; weight control."],
        ["Exam one-liners", "Stress leaks with effort, urge leaks after the urge; **diary is the cheapest test**; systemic HRT does not help, vaginal oestrogen does; **continuous leak after obstructed labour = fistula**; check PVR before antimuscarinic."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Incontinence in primary care - type then treat",
        caption: "Condensed NICE NG123 pathway.",
        steps: [
          { label: "Screen DIAPPERS, dipstick, PVR, 3-day diary", detail: "Treat UTI, atrophy, impaction, drugs, polyuria first" },
          { label: "Red flag? Haematuria, PVR over 200, fistula, cauda equina", detail: "Refer - not primary care treatment", tone: "warn" },
          { label: "Leak with effort or after urgency?", detail: "Cough stress test; mixed - treat predominant", tone: "decision" },
          { label: "Stress: supervised PFMT for 3 months", detail: "8 contractions three times a day; 'the knack'" },
          { label: "Urgency: bladder training 6 weeks, then drug", detail: "Mirabegron 25-50 mg (frail) or solifenacin 5 mg; review at 4 weeks" },
          { label: "Failed conservative care", detail: "SUI - sling or colposuspension; OAB - botulinum toxin, PTNS, SNM", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Stress vs urgency vs overflow incontinence",
        columns: ["Feature", "Stress", "Urgency", "Overflow"],
        rows: [
          ["Leak trigger", "Cough, sneeze, lift", "Sudden urge, key-in-door", "Constant dribble, no warning"],
          ["Mechanism", "Hypermobility, sphincter weakness", "Detrusor overactivity", "Obstruction or underactive detrusor"],
          ["PVR", "Normal", "Normal (check in elderly)", "High - over 200 mL"],
          ["First line", "PFMT 3 months", "Bladder training 6 weeks", "Treat cause, CISC, alpha blocker in men"],
          ["Drug or procedure", "Sling, colposuspension; duloxetine", "Mirabegron, antimuscarinic, botulinum", "Avoid antimuscarinics"],
        ],
      },
      {
        kind: "branch",
        heading: "DIAPPERS - reversible causes in the elderly",
        root: "New or worse incontinence in an older person",
        arms: [
          { label: "D, I, A", steps: ["Delirium", "Infection (symptomatic UTI)", "Atrophic vaginitis - vaginal oestrogen"] },
          { label: "P, P", tone: "decision", steps: ["Pharmaceuticals - diuretics, sedatives, anticholinergics", "Psychological - depression"] },
          { label: "E, R, S", tone: "warn", steps: ["Excess urine output - glucose, HF, calcium", "Restricted mobility", "Stool impaction"] },
        ],
      },
    ],
  },
};

export default revision;
