import type { RevisionSet } from "./index";

const revision: RevisionSet = {
  "surgery-office-wound-suturing": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - wounds, local anaesthesia and suturing",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Break in continuity of skin or mucosa; type by mechanism - **incised, lacerated, abrasion, puncture, crush, avulsion, bite** - predicts contamination and dead tissue."],
        ["Relevant classification", "**CDC wound class I-IV** (clean under 2% SSI to dirty over 27%; any fresh traumatic wound = III); healing by **primary, secondary, tertiary (delayed primary) intention**; **WHO rabies category I-III**; tetanus-prone vs clean."],
        ["Aetiology & risk factors", "Road, farm, glass, knife, animal and human bites; delayed healing with **diabetes, steroids, PAD, smoking**, retained foreign body, dead tissue."],
        ["Pathophysiology", "Haemostasis -> inflammation (days 1-4, macrophage key) -> proliferation (type III collagen, granulation, epithelial seal 48 h) -> remodelling (type I collagen; **20% strength at 3 weeks, max 80%**)."],
        ["Key history (OPD)", "**Exact time of injury**, mechanism (high-pressure injection = emergency), foreign body, animal status, clenched-fist, numbness or weakness, **tetanus doses**, diabetes, anticoagulants, keloid, MLC."],
        ["Key examination", "ABC, pressure and elevation for bleeding; **distal neurovascular and tendon check before LA** (2-point discrimination under 6 mm; FDP and FDS tests); explore through full range of movement in a bloodless field."],
        ["Minimal investigations", "Usually none; **X-ray two views** for glass or metal, **ultrasound for wood or thorn**; capillary glucose in slow or infected wounds; pus culture only if infected."],
        ["Treatment - first line", "**Irrigate 50-100 mL saline per cm** (20 mL syringe, 18 G); debride; close primarily if clean and **under 6 h (face up to 24 h)**; **lignocaine 3 mg/kg plain, 7 mg/kg with adrenaline** (1% = 10 mg/mL); bupivacaine 2 mg/kg."],
        ["Escalation / second line", "Contaminated, puncture, crush, cat or human bite, cat III rabies - **delayed primary closure day 3-5**; bites - **amoxicillin-clavulanate 625 mg TDS 3-5 days** (allergy: doxycycline or co-trimoxazole plus metronidazole)."],
        ["Devices / procedures", "Needle at 90 degrees, equal bites wider at base; **simple interrupted**, vertical mattress (eversion), horizontal mattress, subcuticular; nylon 5-0/6-0 face, 4-0 hand, 3-0 trunk; tissue adhesive for low-tension child wounds."],
        ["Special groups", "Children - LAT gel 20-30 min or EMLA; calculate LA by weight; check story for NAI; reduce LA by a third in elderly, heart failure, liver disease."],
        ["Complications", "Infection, dehiscence, hypertrophic scar or keloid, missed tendon or nerve, retained FB, **LAST**, tetanus, rabies."],
        ["Red flags & referral", "Tendon, nerve or vessel injury, open joint or fracture, clenched-fist injury, high-pressure injection, eyelid margin or vermilion, necrotising signs, established tetanus."],
        ["Follow-up & monitoring", "Bites and contaminated wounds at **24-48 h**; sutures out face 4-5 d, scalp and trunk 7-10, upper limb 10, palm, sole, joints 12-14, lower limb 10-14; complete rabies and Td dates."],
        ["Prevention / national programme", "**Td 0.5 mL IM**: clean wound booster if 10 years or more, tetanus-prone if **5 years or more**; **TIG 250 IU** only if under 3 or unknown doses; rabies **Essen IM 0, 3, 7, 14, 28 or ID 2-2-2-0-2**, **hRIG 20 IU/kg or eRIG 40 IU/kg** into wounds (NRCP)."],
        ["Exam one-liners", "**Irrigation, not antibiotics, prevents infection**; examine before injecting; never inject LA into pus; **lipid 20% 1.5 mL/kg** for LAST; wash bites 15 minutes."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Fresh laceration - decide closure in the OPD",
        steps: [
          { label: "ABC, pressure, note time of injury", detail: "Elevate; never clamp blindly" },
          { label: "Distal neurovascular and tendon check", detail: "Before any local anaesthetic", tone: "decision" },
          { label: "Deep structure, open joint, fist bite?", detail: "Yes - refer for exploration", tone: "warn" },
          { label: "Anaesthetise, explore, irrigate, debride", detail: "Lignocaine max 3 mg/kg (7 with adrenaline); 50-100 mL/cm" },
          { label: "Clean and under 6 h (face 24 h)?", detail: "Yes - primary closure; no - delayed primary day 3-5", tone: "decision" },
          { label: "Td, TIG, rabies PEP, antibiotic if indicated", detail: "Bites: co-amoxiclav 625 mg TDS 3-5 d", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Tetanus and rabies prophylaxis at a glance",
        columns: ["Situation", "Vaccine", "Immunoglobulin"],
        rows: [
          ["Clean wound, 3 or more Td doses", "Booster if 10 years or more", "No"],
          ["Tetanus-prone, 3 or more doses", "Booster if 5 years or more", "No"],
          ["Tetanus-prone, under 3 or unknown", "Start full Td course", "TIG 250 IU (500 IU if over 24 h)"],
          ["Rabies category II", "ARV IM days 0, 3, 7, 14, 28 or ID 0, 3, 7, 28", "No"],
          ["Rabies category III", "ARV as above", "hRIG 20 IU/kg or eRIG 40 IU/kg into wounds"],
        ],
      },
    ],
  },
  "surgery-office-abscess-ssti": {
    checked: "2026-10",
    updated: [
      "SSC 2026: necrotising infection with sepsis - at least 30 mL/kg crystalloid in 3 h, balanced crystalloid preferred over 0.9% saline, antibiotic within 1 hour.",
    ],
    master: {
      heading: "Master revision table - abscess and SSTI",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Abscess** = walled-off pus within a pyogenic membrane; **cellulitis** = spreading deep dermal and fat infection; **erysipelas** = upper dermis and lymphatics with raised sharp edge."],
        ["Relevant classification", "**IDSA 2014: purulent vs non-purulent**, then **mild, moderate (SIRS), severe**; NSTI type I polymicrobial, II group A strep, III clostridial or Vibrio."],
        ["Aetiology & risk factors", "**S. aureus (incl. CA-MRSA, PVL)** in purulent; **S. pyogenes** in non-purulent; diabetes, immunosuppression, tinea pedis, lymphoedema, injections."],
        ["Pathophysiology", "Coagulase walls off -> neutrophil death liquefies tissue -> avascular pyogenic membrane -> **antibiotics cannot penetrate -> drainage cures**; strep enzymes spread diffusely."],
        ["Key history (OPD)", "Tempo of spread, **pain out of proportion**, portal of entry, fever and rigors, diabetes, recurrence and family clusters, prior antibiotics, site-specific clues (lactation, perianal, face)."],
        ["Key examination", "Vitals and glucose first; pointing, **Paget fluctuation in two planes**, **pulsatility (never incise an aneurysm)**, mark cellulitis margin with time; necrotising signs - woody oedema, bullae, anaesthesia, crepitus."],
        ["Minimal investigations", "**Glucose and HbA1c**; bedside ultrasound for collection; pus culture in recurrent, diabetic, face or hand; **LRINEC 6 or more suspicious, 8 or more likely**; CBNAAT for cold abscess."],
        ["Treatment - first line", "**Incision, deroofing, Hilton method**, loose pack; no antibiotic for simple drained abscess; cellulitis - **amoxicillin 500 mg TDS or penicillin V 500 mg QID 5 days**, elevate; cloxacillin or cephalexin **500 mg QID** if staph."],
        ["Escalation / second line", "MRSA - **co-trimoxazole DS 1-2 BD, doxycycline 100 mg BD, clindamycin 300-450 mg TDS**; IV cefazolin 1-2 g 8-hourly; severe - **vancomycin 15-20 mg/kg** or linezolid 600 mg BD."],
        ["Devices / procedures", "Field block 1-2 cm outside redness, No. 11 blade along Langer lines, cruciate deroofing, finger breaks loculi, culture from depth, review 24-48 h; **decolonise** with mupirocin nasal BD 5 d plus chlorhexidine wash."],
        ["Special groups", "**Lactational abscess - ultrasound-guided aspiration, continue breastfeeding**; perianal - drain close to verge, one third form fistula; danger-area face boil - never squeeze; neonate - treat as sepsis."],
        ["Complications", "Recurrence, sinus or fistula, lymphangitis, bacteraemia, cavernous sinus thrombosis, **necrotising fasciitis, Fournier gangrene**, toxic shock."],
        ["Red flags & referral", "Pain out of proportion, crepitus, bullae, sepsis, Kanavel signs, periorbital swelling, Ludwig angina, deep neck, ischiorectal or breast abscess, pulsatile mass."],
        ["Follow-up & monitoring", "Review **24-48 h**; cellulitis margin should retreat by 48-72 h; chronic sinus - look for FB, TB, osteomyelitis, malignancy; recurrent boils - HbA1c, HIV, MRSA screen."],
        ["Latest guideline change", "**SSC 2026**: in NSTI with sepsis give **at least 30 mL/kg crystalloid, balanced preferred**, antibiotics within 1 h, then **radical debridement** (piperacillin-tazobactam plus clindamycin plus MRSA cover)."],
        ["Exam one-liners", "**Ubi pus, ibi evacua**; purulent = staph and knife, non-purulent = strep and antibiotic; co-trimoxazole and doxycycline miss strep; never inject LA into pus."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Red swollen skin - knife or antibiotic?",
        steps: [
          { label: "Vitals, glucose, sepsis screen", detail: "SIRS = moderate; hypotension = severe" },
          { label: "Necrotising signs?", detail: "Pain out of proportion, crepitus, bullae, anaesthesia", tone: "warn" },
          { label: "Collection on palpation or ultrasound?", tone: "decision", detail: "Purulent vs non-purulent" },
          { label: "Purulent - incise, deroof, Hilton, culture", detail: "Antibiotic only if cellulitis over 2 cm, systemic, high risk" },
          { label: "Non-purulent - antibiotic, elevate, mark edge", detail: "Amoxicillin 500 mg TDS or penicillin V 5 days" },
          { label: "Review 24-48 h", detail: "Failure: missed loculus, MRSA, NSTI", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Necrotising soft tissue infection - escalation",
        steps: [
          { label: "Recognise and do not incise in clinic", detail: "LRINEC 6 or more supports; low score never excludes", tone: "warn" },
          { label: "Resuscitate", detail: "At least 30 mL/kg balanced crystalloid in 3 h (SSC 2026)" },
          { label: "Antibiotic within 1 hour", detail: "Pip-taz 4.5 g IV + clindamycin 600-900 mg IV + vancomycin/linezolid" },
          { label: "Phone surgeon - radical debridement", detail: "Finger test; repeat look at 24-48 h", tone: "good" },
        ],
      },
    ],
  },
  "surgery-office-diabetic-foot": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - diabetic foot ulcer",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Full-thickness skin break **distal to the malleoli** in a person with diabetes; diabetes-related foot disease includes infection, ischaemia, Charcot and gangrene."],
        ["Relevant classification", "**Meggitt-Wagner 0-5**; **IWGDF/IDSA infection 1-4 (+O for osteomyelitis)**; University of Texas (A-D); **SINBAD 0-6** (3 or more - foot team); IWGDF risk 0-3 for screening frequency."],
        ["Aetiology & risk factors", "**Neuropathy + PAD + unperceived trauma**; previous ulcer or amputation (strongest), deformity, barefoot walking, ESRD, smoking, poor vision."],
        ["Pathophysiology", "Polyol, AGEs -> sensory loss + motor claw toes + autonomic dry skin -> callus -> haematoma -> ulcer -> infection spreads along plantar compartments; **Monckeberg calcification falsely raises ABI**."],
        ["Key history (OPD)", "Painless walking on ulcer, claudication and **rest pain**, fever or **sudden loss of glycaemic control**, footwear and habits, previous ulcer, SGLT2i, Charcot (hot swollen foot after twist)."],
        ["Key examination", "Shoes off; **10 g monofilament** at hallux and 1st, 3rd, 5th MT heads; 128 Hz fork; pulses; **ABI under 0.9 PAD, over 1.3 unreliable - toe pressure under 30 mmHg**; **probe-to-bone**; describe ulcer after paring callus."],
        ["Minimal investigations", "Glucose, HbA1c, ketones, creatinine; CBC, **ESR over 70** supports OM; **deep tissue culture, never swab**; foot X-ray; MRI if X-ray inconclusive; arterial duplex."],
        ["Treatment - first line", "**Offload (TCC gold standard)**, sharp debridement, moist dressing by exudate, glycaemic control; mild infection - **amoxicillin-clavulanate 625 mg TDS 1-2 weeks** (or cephalexin, clindamycin)."],
        ["Escalation / second line", "Moderate - IV co-amoxiclav 1.2 g or ceftriaxone plus metronidazole 1-3 weeks; severe - **pip-taz 4.5 g or meropenem + vancomycin/linezolid** with surgery; OM **6 weeks if bone retained, 2-5 days if resected**."],
        ["Devices / procedures", "Offloading ladder: non-removable knee-high TCC -> removable walker (made irremovable) -> ankle walker -> forefoot shoe -> felted foam; TCC contraindicated in infection, OM, critical ischaemia, heel ulcer."],
        ["Special groups", "CKD - renal dosing, avoid NSAIDs; ischaemic dry eschar - **do not debride, revascularise**; Charcot - TCC till temperature difference under 2 C."],
        ["Complications", "Abscess, wet gangrene, osteomyelitis, Charcot collapse, amputation, **5-year mortality worse than many cancers**."],
        ["Red flags & referral", "Crepitus or gas, wet gangrene, plantar abscess, SIRS, **rest pain or toe pressure under 30**, hot painless red foot (Charcot), exposed bone - same-day."],
        ["Follow-up & monitoring", "Measure area weekly; **not 50% smaller in 4 weeks - reassess**; healed = remission (recurrence 40% at 1 year); IWGDF risk 3 review every 1-3 months."],
        ["Prevention / national programme", "Annual foot screen in every diabetic (NP-NCD), education - inspect daily, no barefoot walking, nails straight; therapeutic footwear worn over 80% of day; statin, antiplatelet, stop smoking."],
        ["Exam one-liners", "**Offloading heals, not dressing**; pare callus before grading; probe-to-bone near-diagnostic; no antibiotic for uninfected ulcer."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Diabetic foot ulcer - OPD sequence",
        steps: [
          { label: "Systemic toxicity, gas, wet gangrene?", detail: "Yes - same-day admission and surgery", tone: "warn" },
          { label: "Perfusion: pulses, ABI, toe pressure", detail: "Toe pressure under 30 or ABI under 0.5 - vascular referral", tone: "decision" },
          { label: "Infection grade (IWGDF 1-4) and probe-to-bone", detail: "Deep tissue culture, X-ray; ESR over 70" },
          { label: "Debride callus and slough", detail: "Not a dry eschar on an ischaemic foot" },
          { label: "Offload", detail: "Total contact cast unless infected or ischaemic" },
          { label: "Weekly measurement", detail: "50% smaller in 4 weeks = on track", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Antibiotic by IWGDF/IDSA grade",
        steps: [
          { label: "Grade 1 uninfected", detail: "No antibiotic" },
          { label: "Grade 2 mild - oral 1-2 weeks", detail: "Co-amoxiclav 625 mg TDS or cephalexin 500 mg QID or clindamycin" },
          { label: "Grade 3 moderate - IV then oral 1-3 weeks", detail: "Co-amoxiclav 1.2 g IV or ceftriaxone + metronidazole; pip-taz if Pseudomonas" },
          { label: "Grade 4 severe - admit, surgery, 2-4 weeks", detail: "Pip-taz or meropenem + vancomycin/linezolid", tone: "warn" },
          { label: "Osteomyelitis", detail: "6 weeks if bone retained; 2-5 days if all resected", tone: "decision" },
        ],
      },
    ],
  },
  "surgery-office-minor-procedures": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - office minor procedures",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Procedures under LA on superficial clinically benign lesions - **lipoma, epidermoid cyst, ingrown toenail, skin tag, wart, skin biopsy**."],
        ["Relevant classification", "**Office vs refer** (over 5 cm, deep to fascia, fast-growing, painful, recurrent - sarcoma pathway); biopsy types punch, shave, incisional, excisional; **Heifetz 1-3** ingrown toenail; **Glasgow 7-point** (3 or more refer)."],
        ["Aetiology & risk factors", "Lipoma - mature fat; epidermoid cyst - occluded follicle infundibulum (never palms or soles); ingrown nail - curved cutting, tight shoes; warts - HPV."],
        ["Pathophysiology", "Retained capsule, cyst wall or nail-matrix horn -> **recurrence**; melanoma depth (**Breslow**) lost by shave or curettage."],
        ["Key history (OPD)", "Duration and growth, pain, discharge, multiplicity, pigmented lesion change, diabetes or PAD before nail surgery, anticoagulants, pacemaker (bipolar only), keloid."],
        ["Key examination", "**Slip sign + pinchable skin = lipoma**; **punctum + tethered skin = cyst**; fluctuation, transillumination, deep fixity; ABCDE and ugly duckling; pedal pulses before toe surgery."],
        ["Minimal investigations", "**Histopathology of every specimen** in 10% formalin (10x volume); MRI and sarcoma referral before biopsy of suspicious lumps; imaging before midline scalp or lumbosacral lesions."],
        ["Treatment - first line", "Lipoma - incise two-thirds diameter, deliver capsule in avascular plane; cyst - elliptical incision with punctum, intact wall; **infected cyst - drain, excise 6-8 weeks later**."],
        ["Escalation / second line", "Ingrown nail stage 2-3 - **partial avulsion with phenol 80-88%, 30 s x 3** (recurrence under 5%); Zadik for recurrent; warts - salicylic acid 12-26% up to 12 weeks, then cryotherapy every 2-3 weeks x 3-4."],
        ["Devices / procedures", "Ring block 2-3 mL plain lignocaine each side, glove tourniquet with time recorded; punch 3-4 mm, lift with needle; suspected melanoma - **excision with 1-3 mm margin**, never shave."],
        ["Special groups", "Diabetic or ischaemic toe - check perfusion, plain LA; children - EMLA 60 min; pregnancy - TCA for genital warts, no imiquimod or podophyllotoxin."],
        ["Complications", "Haematoma, seroma, infection, recurrence, **forgotten digital tourniquet**, keloid, hypopigmentation after cryotherapy, unexpected malignancy on histology."],
        ["Red flags & referral", "Lump over 5 cm or deep, **Glasgow 3 or more**, ulcer with everted edge (SCC, Marjolin), midline lumbosacral or scalp lesion, pulsatile or cough impulse, parotid, neck, groin lumps."],
        ["Follow-up & monitoring", "Nail at 48 h then weekly; sutures per site; **chase every histology report**."],
        ["Exam one-liners", "Recurrence means residual tissue; never excise an infected cyst; never shave a possible melanoma; wart plume carries HPV - N95 and evacuator."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Lump on the skin - office or refer?",
        steps: [
          { label: "Size, depth, growth, pain, recurrence", detail: "Over 5 cm, deep or growing - MRI and sarcoma pathway", tone: "warn" },
          { label: "Pigmented lesion?", detail: "Glasgow 3 or more - urgent referral; excise 1-3 mm margin, never shave", tone: "decision" },
          { label: "Site check", detail: "Parotid, anterior neck, groin, midline scalp or spine - image or refer", tone: "warn" },
          { label: "Infected?", detail: "Drain now, excise after 6-8 weeks", tone: "decision" },
          { label: "Consent, mark sitting, LA dose in mg", detail: "Lignocaine with adrenaline max 7 mg/kg" },
          { label: "Excise completely, histology, chase report", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Ingrown toenail by Heifetz stage",
        steps: [
          { label: "Stage 1 - pain, erythema", detail: "Cut straight, cotton or floss under corner, warm soaks" },
          { label: "Stage 2 - infection, discharge", detail: "Partial avulsion + phenol 80-88% 30 s x 3; cephalexin if cellulitis" },
          { label: "Stage 3 - granulation, fold hypertrophy", detail: "Partial avulsion, curette granulation, phenol matricectomy" },
          { label: "Recurrent or deformed nail", detail: "Zadik total matrix excision", tone: "decision" },
        ],
      },
    ],
  },
  "surgery-office-hernia": {
    checked: "2026-10",
    updated: [
      "HerniaSurge 2023: antibiotic prophylaxis for open mesh repair is risk-tiered - not for average-risk patients in low-infection settings, suggested in high-risk patients, recommended for all in high-infection-risk environments.",
      "HerniaSurge 2023: with expertise, laparo-endoscopic (TEP/TAPP) repair is also an option for primary unilateral hernia - quicker recovery, less chronic pain.",
    ],
    master: {
      heading: "Master revision table - hernia",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Protrusion of a viscus or part of a viscus through an abnormal opening in the wall of its containing cavity; **sac, coverings, contents**."],
        ["Relevant classification", "By site (indirect commonest in both sexes), by **state - reducible, irreducible, obstructed, strangulated**; **EHS groin: P/R, L/M/F, size 1-3**; Richter, Littre, Maydl, Amyand, de Garengeot, sliding."],
        ["Aetiology & risk factors", "Patent processus vaginalis, ageing, smoking, collagen defect + raised pressure - **chronic cough, constipation, prostatism, ascites, pregnancy, heavy lifting**."],
        ["Pathophysiology", "Tight neck -> venous and lymphatic block -> oedema -> arterial block -> **gangrene, perforation**; cough impulse lost when neck occluded; Richter strangulates without obstructing."],
        ["Key history (OPD)", "Lump reducing on lying, dragging pain, **sudden constant pain + irreducible = strangulation**, obstruction symptoms, cough, LUTS, bowel change in elderly, previous surgery, fitness."],
        ["Key examination", "Stand then lie; **neck relative to pubic tubercle - inguinal above and medial, femoral below and lateral**; get above it?; deep ring occlusion; Zieman; signs of strangulation; DRE, chest, other groin."],
        ["Minimal investigations", "Clinical diagnosis; dynamic ultrasound for occult or uncertain lump; CT for obturator, Spigelian, complex incisional; look for cause (PSA, chest X-ray, colonoscopy if indicated)."],
        ["Treatment - first line", "**Every femoral hernia - operate** (40% present as emergency); symptomatic inguinal - **Lichtenstein tension-free mesh** (day case, LA possible); minimally symptomatic men - watchful waiting acceptable."],
        ["Escalation / second line", "**TEP/TAPP** for bilateral, recurrent after open, women, and **primary unilateral where expertise exists (HerniaSurge 2023)**; tissue repair (Shouldice) if mesh unavailable or contaminated."],
        ["Devices / procedures", "Lichtenstein: polypropylene mesh ~15 x 7.5 cm overlapping pubic tubercle 2 cm, sutured to shelving edge and internal oblique, tails around cord; ilioinguinal block 2 cm medial to ASIS; **truss obsolete**."],
        ["Special groups", "**Child - herniotomy alone**, prompt (preterm, girls sooner); infant umbilical hernia closes by 4-5 years - no strapping; women - laparoscopic (many are femoral); divarication is not a hernia."],
        ["Complications", "Strangulation, obstruction, reduction en masse; post-op haematoma, mesh infection, ischaemic orchitis, **chronic groin pain 10-12%**, recurrence 1-5%."],
        ["Red flags & referral", "Tense tender irreducible lump, **no cough impulse**, obstruction - same hour, **never taxis**; any femoral hernia; elderly woman with obstruction and Howship-Romberg (obturator)."],
        ["Follow-up & monitoring", "Walk same day, sedentary work 1-2 weeks, heavy lifting 4-6 weeks; report fever, scrotal swelling, retention, testicular pain."],
        ["Latest guideline change", "**HerniaSurge 2023**: antibiotic prophylaxis tiered by patient risk and setting (**recommended for all in high-infection-risk environments** - cefazolin 2 g within 60 min); laparo-endoscopic repair for primary unilateral hernia where expertise exists."],
        ["Exam one-liners", "Judge the neck not the fundus; loss of cough impulse in a tender lump = strangulation; Richter does not obstruct; children herniotomy, adults mesh."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Groin lump - decide the urgency",
        steps: [
          { label: "Tender, tense, irreducible, no cough impulse?", detail: "Strangulation - NBM, IV fluids, NG tube, refer now; never taxis", tone: "warn" },
          { label: "Neck relative to pubic tubercle", detail: "Below and lateral = femoral - urgent surgery", tone: "decision" },
          { label: "Can you get above it?", detail: "No - inguinoscrotal hernia; yes - scrotal lesion", tone: "decision" },
          { label: "Symptomatic inguinal hernia", detail: "Elective mesh repair; treat cough, constipation, prostatism" },
          { label: "Minimally symptomatic man", detail: "Watchful waiting with safety-net (most cross over)", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Choosing the repair",
        columns: ["Patient", "Repair", "Note"],
        rows: [
          ["Child", "Herniotomy only", "Wall normal; preterm and girls sooner"],
          ["Adult primary unilateral", "Lichtenstein or TEP/TAPP", "Laparo-endoscopic if expertise (HerniaSurge 2023)"],
          ["Bilateral or recurrent after open", "TEP/TAPP", "Opposite approach to the previous one"],
          ["Woman", "Laparo-endoscopic", "Detects occult femoral hernia"],
          ["Strangulated femoral", "McEvedy (high) or laparoscopic", "Allows bowel resection"],
        ],
      },
    ],
  },
  "surgery-office-breast-lump": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - breast lump and triple assessment",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Discrete palpable swelling distinct from surrounding nodularity; benign only when **clinical, imaging and pathology are all concordantly benign**."],
        ["Relevant classification", "**Triple assessment P1-5, U/M1-5 (BI-RADS 0-6), B1-5 (B3 excise, B5a in situ, B5b invasive)**; ANDI for benign disease; AJCC 8e TNM (T4b peau d'orange, T4d inflammatory)."],
        ["Aetiology & risk factors", "Unopposed oestrogen exposure (early menarche, late menopause, nulliparity, HRT, obesity, alcohol), **BRCA1/2**, chest irradiation, atypical hyperplasia."],
        ["Pathophysiology", "TDLU origin; Cooper ligament shortening -> dimpling; dermal lymphatic block -> **peau d'orange**; 75% drainage to axilla; Paget = intraepidermal spread starting on the nipple."],
        ["Key history (OPD)", "Duration and growth, relation to cycle, pain, **spontaneous single-duct bloody discharge**, nipple change, axillary lump, metastatic symptoms, family history, drugs (galactorrhoea, gynaecomastia)."],
        ["Key examination", "Chaperone; inspect arms down, raised, hands on hips; flat-hand palpation of quadrants and tail; fixity to skin and pectoralis; axilla and supraclavicular fossa; **score P1-P5**."],
        ["Minimal investigations", "**Ultrasound under 40 and in pregnancy; mammography + ultrasound at 40 and over**; **image-guided 14 G core biopsy** (ER, PR, HER2); cyst aspiration rules; prolactin and TSH for milky discharge."],
        ["Diagnostic criteria", "Concordant benign = discharge with plan; **any discordance = excision biopsy**; a normal mammogram never overrules a suspicious lump (10-15% occult)."],
        ["Treatment - first line", "Fibroadenoma under 3 cm, under 30 - observe; cyst - aspirate; cyclical mastalgia - supportive bra, **topical diclofenac**; lactational mastitis - continue feeding, **cloxacillin 500 mg QID 10-14 days**."],
        ["Escalation / second line", "Cancer (MDT): breast-conserving surgery + RT or mastectomy, SLNB; **tamoxifen 20 mg premenopausal, letrozole 2.5 mg or anastrozole 1 mg postmenopausal 5-10 y**; trastuzumab for HER2 (echo 3-monthly)."],
        ["Special groups", "Pregnancy - ultrasound and core biopsy; male - eccentric hard lump = cancer (BRCA2, Klinefelter); **TB mastitis** in India - core, CBNAAT, ATT."],
        ["Complications", "Delayed diagnosis, lymphoedema, tamoxifen VTE and endometrial cancer, AI osteoporosis, trastuzumab cardiotoxicity, febrile neutropenia."],
        ["Red flags & referral", "Unexplained lump at **30 or over**, nipple change or unilateral discharge at 50 or over, skin change any age, bloody single-duct discharge, nipple eczema starting on nipple, non-settling mastitis."],
        ["Follow-up & monitoring", "Fibroadenoma 3-6 months; after cancer **annual mammography**, endocrine adherence, bone health (DEXA, calcium, vitamin D, zoledronic acid)."],
        ["Prevention / national programme", "**NP-NCD: clinical breast examination every 5 years at 30-65** at Ayushman Arogya Mandir; breast awareness; breastfeeding, activity, avoid alcohol."],
        ["Exam one-liners", "Benign only if all three benign; core beats FNAC; B3 is excised; Paget starts on the nipple; fat necrosis mimics cancer."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Triple assessment in one line each",
        steps: [
          { label: "Clinical examination - score P1-P5", detail: "P4-P5 = cancer pathway whatever imaging shows" },
          { label: "Imaging by age", detail: "Under 40 or pregnant: ultrasound; 40+: mammography + ultrasound", tone: "decision" },
          { label: "Core biopsy (14 G, 3-4 cores)", detail: "Gives invasion, grade, ER, PR, HER2" },
          { label: "Concordant?", detail: "Discordant = excision biopsy", tone: "decision" },
          { label: "Concordant benign - reassure and review", tone: "good" },
          { label: "Concordant malignant - MDT", tone: "warn" },
        ],
      },
      {
        kind: "compare",
        heading: "Nipple discharge - what it means",
        columns: ["Discharge", "Likely cause", "Action"],
        rows: [
          ["Bilateral multi-duct milky", "Galactorrhoea", "Pregnancy test, prolactin, TSH, drug review"],
          ["Multi-duct green-brown", "Duct ectasia", "Triple assessment, stop smoking"],
          ["Spontaneous single-duct bloody", "Papilloma or DCIS/carcinoma", "Imaging, biopsy, microdochectomy"],
          ["Purulent, lactating", "Mastitis or abscess", "Continue feeding, cloxacillin, aspirate abscess"],
        ],
      },
    ],
  },
  "surgery-office-catheter-ngt-injection": {
    checked: "2026-10",
    updated: [
      "IDSA cUTI 2025: symptomatic CAUTI (a complicated UTI) - once improving, 7 days of a non-fluoroquinolone or 5-7 days of a fluoroquinolone, not the old 10-14 days.",
    ],
    master: {
      heading: "Master revision table - catheter, NG tube and injections",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Three bedside procedures with one sequence - **indication, contraindication, consent and chaperone, asepsis, correct size, anatomy, objective confirmation, documentation**."],
        ["Relevant classification", "Catheter **Fr = circumference mm (diameter = Fr/3)** - 14-16 adult, 20-24 three-way for clots; short vs long-term vs **intermittent self-catheterisation**; NG wide-bore Ryle/Salem vs fine-bore feeding; ID, SC, IM, IV routes."],
        ["Pathophysiology", "Male urethra 18-20 cm, two curves, membranous narrowest after meatus; **CAUTI risk 3-7% per catheter-day** via biofilm; gastric pH under 5.5; sciatic nerve near dorsogluteal site."],
        ["Key history (OPD)", "Retention history and drugs, **urethral injury, stricture, prostate surgery**, latex allergy; base-of-skull fracture, corrosives; anticoagulants before IM; needle-stick details and source status."],
        ["Key examination", "Palpable bladder; **blood at meatus, butterfly haematoma, high-riding prostate - no catheter**; Battle sign or raccoon eyes - no nasal tube; ventrogluteal V landmark."],
        ["Minimal investigations", "Bladder scan; creatinine after chronic retention; **NG aspirate pH 5.5 or less, else X-ray**; urine culture from sampling port only if symptomatic; PEP baseline serology."],
        ["Devices / procedures", "Male: lignocaine gel 10-20 mL wait 3-5 min, penis at 90 degrees, **advance to hilt and see urine before inflating 10 mL water, replace foreskin**; NG: NEX measure, floor of nose, swallow; IM: 23 G 25-38 mm at 90 degrees, no routine aspiration."],
        ["Treatment - first line", "Remove catheter early, closed drainage, bag below bladder; **tamsulosin 0.4 mg 2-3 days before TWOC**; no antibiotic for asymptomatic bacteriuria or catheter change."],
        ["Escalation / second line", "**Symptomatic CAUTI**: change catheter if over 2 weeks, culture, then **7 days (5-7 days if fluoroquinolone) once improving** (IDSA 2025); failed catheter or false passage - urology, suprapubic."],
        ["Special groups", "Anaphylaxis doses: **adrenaline 1:1000 IM thigh 0.5 mg adult and over 12, 0.3 mg 6-12 y, 0.15 mg under 6 y**, repeat every 5 min; anticoagulated - avoid IM; malnourished NG feeding - thiamine, start 10 kcal/kg/day."],
        ["Complications", "False passage, paraphimosis, post-obstructive diuresis (over 200 mL/h), CAUTI, encrustation; NG in airway; sciatic injury, injection abscess; needle-stick BBV (HIV 0.3%, HCV 1.8%, HBV 6-30%)."],
        ["Red flags & referral", "Pain on balloon inflation, no urine; cough, voice change or desaturation passing NG; pH over 5.5; foot drop after gluteal injection; urticaria, stridor, hypotension."],
        ["Follow-up & monitoring", "Daily review of catheter indication; NG external length before every use; PEP adherence and serology at 6 weeks, 3 and 6 months; observe 30 min after vaccines."],
        ["Prevention / national programme", "Auto-disable syringes, no recapping, BMW rules (sharps white, plastics red, soiled yellow, glass blue); **PEP TLD 28 days within 2 h (max 72 h)** (NACO); HBIG plus vaccine if non-immune."],
        ["Latest guideline change", "**IDSA cUTI 2025**: CAUTI is a complicated UTI; once improving give **7 days of a non-fluoroquinolone or 5-7 days of a fluoroquinolone** instead of 10-14 days."],
        ["Exam one-liners", "Urine before inflating; sterile water not saline; NG pH 5.5 or X-ray, never whoosh test; ventrogluteal safest; adrenaline IM thigh first."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Fever in a catheterised patient",
        steps: [
          { label: "Symptoms beyond cloudy urine?", detail: "Fever, loin pain, rigors, delirium - else no antibiotic", tone: "decision" },
          { label: "Catheter in over 2 weeks?", detail: "Replace, then culture from the new catheter" },
          { label: "Septic?", detail: "Ceftriaxone 1-2 g IV, admit", tone: "warn" },
          { label: "Treat by culture", detail: "7 days non-fluoroquinolone or 5-7 days fluoroquinolone once improving (IDSA 2025)" },
          { label: "Remove catheter as early as possible", tone: "good" },
        ],
      },
      {
        kind: "flow",
        heading: "Anaphylaxis after an injection",
        steps: [
          { label: "Airway, breathing, circulation, skin", detail: "Distinguish from vasovagal (slow pulse, recovers lying flat)", tone: "decision" },
          { label: "Adrenaline 1:1000 IM anterolateral thigh", detail: "0.5 mg adult; 0.3 mg 6-12 y; 0.15 mg under 6 y", tone: "warn" },
          { label: "Lie flat, legs up; oxygen, IV fluids", detail: "500-1000 mL adult, 10 mL/kg child" },
          { label: "No improvement in 5 min - repeat", detail: "After 2 doses - refractory pathway, adrenaline infusion" },
          { label: "Observe 6-12 h, auto-injector, allergy referral", tone: "good" },
        ],
      },
    ],
  },
  "surgery-office-preop-postop": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - pre-operative fitness and post-operative care",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Structured judgement of **physiological reserve and comorbidity against the magnitude of the operation**, with drug, fasting and prophylaxis plans and informed consent."],
        ["Relevant classification", "**ASA I-VI (+E)**; ESC surgical risk low under 1%, intermediate 1-5%, high over 5%; **RCRI 6 items** (0 = 0.4%, 3+ = 11%); **4 METs (two flights) or DASI over 34**; Clavien-Dindo; CDC SSI."],
        ["Pathophysiology", "Stress response -> cortisol, catecholamines -> **hyperglycaemia, catabolism**; ADH -> water retention, hyponatraemia; Virchow triad complete; leak day 5-7 in lag phase."],
        ["Key history (OPD)", "Angina, dyspnoea, **stent type and date**, exercise tolerance, STOP-BANG, recent chest infection, bleeding history, anaesthetic and MH family history, all drugs incl. **SGLT2i, GLP-1 RA**, herbals, pregnancy."],
        ["Key examination", "BP (defer if **180/110 or more**), murmur of **aortic stenosis**, heart failure, airway (Mallampati, thyromental under 6 cm), frailty (CFS 5+), post-op wound and calves."],
        ["Minimal investigations", "**Directed, not routine** (NICE NG45); Hb (treat Hb under 13 with iron), creatinine, **HbA1c under 8.5%**, ECG at 65+ or cardiac disease, NT-proBNP in high risk, INR only if indicated."],
        ["Treatment - first line", "**Continue beta-blocker, statin, aspirin**; omit **ACEi/ARB and metformin** on the day; **SGLT2i stop 3 days (ertugliflozin 4)**; fasting **6 h solids, 4 h breast milk, 2 h clear**; cefazolin 2 g within 60 min, stop within 24 h."],
        ["Escalation / second line", "**Warfarin stop 5 days** (bridge only high risk), **DOAC 24-48 h**, clopidogrel 5 d, ticagrelor 3-5 d, prasugrel 7 d; **insulin 80% basal**, VRIII if more than one meal missed; GLP-1 RA - 24 h clear liquids, hold weekly agent 1 week if high risk."],
        ["Devices / procedures", "WHO checklist, ERAS (carbohydrate drink, opioid-sparing analgesia, early feeding and mobilisation), VTE - stockings or IPC + **enoxaparin 40 mg SC daily**, 28 days after abdominopelvic cancer surgery."],
        ["Special groups", "Steroid users (prednisolone 5 mg+ over 4 weeks) - **hydrocortisone 100 mg at induction then 200 mg/24 h**; recent MI 60 days, DES 6 months, stroke 3-9 months - defer elective surgery; frail - delirium prevention."],
        ["Complications", "**Fever timetable - wind (0-2), water (3-5), walking (4-6), wound (5-7), wonder drugs (7+)**; leak, burst abdomen, PE, retention, ileus, delirium, haemorrhage."],
        ["Red flags & referral", "Persistent tachycardia day 5-7 (leak), **pink serosanguinous discharge** (dehiscence), sudden dyspnoea (PE), early necrotising wound, euglycaemic DKA on SGLT2i."],
        ["Follow-up & monitoring", "Medicine reconciliation (restart ACEi, metformin, anticoagulants on stated day), wound check, suture removal by site, **chase histology**, resume chronic disease targets."],
        ["Exam one-liners", "Fitness is relative to the operation; tests are directed; one antibiotic dose within 60 min; persistent tachycardia after bowel surgery is a leak until proved otherwise."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Is this patient fit for elective surgery?",
        steps: [
          { label: "Active cardiac condition?", detail: "Unstable angina, decompensated HF, arrhythmia, severe AS - postpone", tone: "warn" },
          { label: "Surgical risk low?", detail: "Yes - proceed with directed tests", tone: "decision" },
          { label: "Functional capacity 4 METs or DASI over 34?", detail: "Yes - proceed", tone: "decision" },
          { label: "RCRI 2 or more with poor capacity", detail: "NT-proBNP/troponin, cardiology opinion" },
          { label: "Optimise and write drug plan", detail: "BP, glucose (HbA1c under 8.5%), anaemia, stop/continue list", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Peri-operative drug plan",
        columns: ["Drug", "Before surgery", "Restart"],
        rows: [
          ["Beta-blocker, statin, aspirin", "Continue", "Continue"],
          ["ACEi or ARB", "Omit morning of surgery", "When eating and creatinine stable"],
          ["Metformin, sulfonylurea", "Omit on the day", "When eating normally"],
          ["SGLT2 inhibitor", "Stop 3 days before (ertugliflozin 4)", "When eating and drinking normally"],
          ["Warfarin", "Stop 5 days; INR under 1.5", "Evening of surgery or next day"],
          ["Apixaban, rivaroxaban", "Stop 24 h (low) or 48 h (high bleed risk)", "24-72 h after"],
          ["Prednisolone 5 mg+ over 4 weeks", "Usual dose + hydrocortisone 100 mg at induction", "Double oral dose 48 h to 1 week"],
        ],
      },
    ],
  },
  "surgery-office-procedural-sedation-ketamine": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - procedural sedation and ketamine",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Drug-induced depression of consciousness allowing a procedure while **airway, breathing and circulation are maintained**; must be able to **rescue one level deeper than intended**."],
        ["Relevant classification", "**ASA continuum: minimal, moderate (purposeful response to voice or light touch), deep, GA**; withdrawal from pain is not purposeful; **dissociative (ketamine) sits outside**."],
        ["Pathophysiology", "Ketamine = **non-competitive NMDA antagonist** -> thalamocortical-limbic dissociation; sympathomimetic (BP and HR up), bronchodilator, reflexes preserved but not protective; hypersalivation -> laryngospasm (0.3%)."],
        ["Key history (OPD)", "AMPLE, cardiorespiratory disease, OSA and snoring, recent URI, **psychosis**, age, fasting (not absolute in emergencies), escort."],
        ["Key examination", "Vitals and weight, **ASA I-II only in office**, airway (Mallampati, mouth opening, thyromental), tonsils, chest; monitor SpO2, **capnography**, HR, BP every 5 min."],
        ["Minimal investigations", "None routine; glucose in diabetics; pregnancy test if relevant; equipment check (SOAPME) is the essential test."],
        ["Treatment - first line", "**Ketamine IV 1-1.5 mg/kg adult, 1.5-2 mg/kg child over 30-60 s**, top-up 0.5-1 mg/kg; **IM 4-5 mg/kg**, top-up 2-2.5 mg/kg; sub-dissociative analgesia 0.1-0.3 mg/kg slow infusion."],
        ["Escalation / second line", "Midazolam 0.5-1 mg IV steps (to 2.5-5 mg) or 0.03-0.05 mg/kg with ketamine in adults; fentanyl 1-1.5 microgram/kg; reversal naloxone 0.1-0.4 mg, flumazenil 0.2 mg; **no antidote for ketamine or propofol**."],
        ["Devices / procedures", "Two trained people; suction, oxygen, airways, BVM, SGA, capnography, defibrillator, drugs; lateral recovery in quiet room; discharge 30 min after last dose with escort, no driving 24 h."],
        ["Special groups", "**Absolute contraindications: under 3 months, schizophrenia**; relative - pharyngeal procedures, URI, cardiovascular disease, raised ICP/IOP (now minor), porphyria, thyroid; children - no routine midazolam or anticholinergic."],
        ["Complications", "**Laryngospasm**, apnoea with rapid push, vomiting 8-12% (recovery), emergence reactions (adults 10-30%), hypertension, hypersalivation."],
        ["Red flags & referral", "ASA III+, difficult airway, severe OSA or big tonsils, under 1 year, frail elderly, full stomach elective, deep sedation needed - anaesthetist."],
        ["Follow-up & monitoring", "Record drug, dose, depth every 5 min, adverse events, recovery; audit desaturation, laryngospasm, vomiting, rescue."],
        ["Prevention / national programme", "Ketamine is an NDPS-controlled drug - locked storage and register."],
        ["Exam one-liners", "Rescue one level deeper; give IV ketamine over 30-60 s; capnography detects apnoea before oximetry; warn parents about nystagmus and vacant stare."],
      ],
    },
    flows: [
      {
        kind: "ladder",
        heading: "Laryngospasm during ketamine sedation",
        steps: [
          { label: "Stop procedure, suction, 100% oxygen", detail: "Stridor or silent obstruction with falling SpO2", tone: "warn" },
          { label: "Jaw thrust + Larson manoeuvre", detail: "Firm pressure in the notch behind the earlobe" },
          { label: "Bag-mask with CPAP/PEEP" },
          { label: "Succinylcholine", detail: "0.5-1 mg/kg IV or 3-4 mg/kg IM, with atropine in children" },
          { label: "Ventilate or intubate, transfer", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Ketamine dose by route",
        columns: ["Route or use", "Dose", "Onset and duration"],
        rows: [
          ["IV dissociation - adult", "1-1.5 mg/kg over 30-60 s; top-up 0.5 mg/kg", "30 s; 5-10 min"],
          ["IV dissociation - child", "1.5-2 mg/kg; top-up 0.5-1 mg/kg", "30 s; 5-10 min"],
          ["IM dissociation", "4-5 mg/kg; top-up 2-2.5 mg/kg", "3-5 min; 15-30 min"],
          ["Sub-dissociative analgesia", "0.1-0.3 mg/kg IV over 10-15 min", "Minutes"],
          ["Intranasal", "Analgesia 0.5-1 mg/kg; sedation 3-6 mg/kg", "Unreliable"],
        ],
      },
    ],
  },
  "surgery-office-spinal-anaesthesia": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - spinal anaesthesia",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Single small dose of LA (usually **0.5% hyperbaric bupivacaine 10-15 mg**) into lumbar CSF **below the conus (L3-L4 or L4-L5)** for surgery below the umbilicus."],
        ["Relevant classification", "Neuraxial types - spinal, epidural, CSE, caudal; baricity hyper-, iso-, hypobaric; level - **saddle S2-S5, T10 TURP/hip, T6-T8 hernia/appendix, T4 caesarean**; Bromage 0-3."],
        ["Pathophysiology", "Sodium-channel block of roots; **sympathetic level 2-6 segments above sensory, motor 2 below**; T5-L1 block -> venodilation -> **hypotension**; T1-T4 + Bezold-Jarisch -> bradycardia; diaphragm spared."],
        ["Key history (OPD)", "Operation and duration, **exact antithrombotic and last dose time**, bleeding history, fixed cardiac output (AS, HOCM), raised ICP, back infection, neurological disease, refusal (absolute)."],
        ["Key examination", "BP, pulse (under 60 predicts bradycardia), hydration, airway, murmur, back skin and landmarks (Tuffier line L4), baseline lower-limb neurology, fundi if ICP suspected."],
        ["Minimal investigations", "No routine coagulation; **platelets 70,000 or more acceptable in obstetrics**; **INR 1.4 or less** after warfarin; creatinine for dabigatran or therapeutic LMWH."],
        ["Treatment - first line", "Caesarean **2-2.5 mL heavy bupivacaine (10-12.5 mg) + fentanyl 10-25 microgram**; lower limb 12.5-17.5 mg; saddle 5-7.5 mg sitting 3-5 min; onset 2-5 min, fixed by 15-20 min, lasts 1.5-3 h."],
        ["Escalation / second line", "Hypotension: **phenylephrine 50-100 microgram boluses or 25-50 microgram/min** (target 90% of baseline); ephedrine 6 mg if bradycardic; atropine 0.6 mg; adrenaline 10-100 microgram early if HR falling."],
        ["Devices / procedures", "Full asepsis with mask, chlorhexidine 0.5% fully dry, **25-27 G pencil-point**, free CSF before injecting, withdraw for paraesthesia; co-load 10-15 mL/kg; test cold to T4 and touch to T5 for CS."],
        ["Special groups", "Pregnancy - one-third less drug, left uterine displacement; **ASRA 2025 intervals: prophylactic LMWH 12 h, therapeutic 24 h, DOACs 72 h, clopidogrel 5-7 d, warfarin 5 d with INR 1.4 or less**; aspirin and NSAIDs fine."],
        ["Complications", "Hypotension, bradycardia, **high or total spinal**, PDPH (0.5-2% with pencil-point), retention, TNS, haematoma (1 in 150,000+), meningitis, abscess, cauda equina, nerve injury 1 in 20,000-50,000."],
        ["Red flags & referral", "Hand tingling or weak voice (rising block), block lasting too long or returning with back pain (**haematoma - MRI and decompression within 8-12 h**), fever with back pain, non-postural headache."],
        ["Follow-up & monitoring", "Bromage 0 and voiding before discharge; intrathecal morphine - RR and sedation hourly 12 h then 2-hourly 12 h; PDPH - analgesia, caffeine up to 48 h, **epidural blood patch 15-20 mL**."],
        ["Exam one-liners", "Cord ends L1-L2 (L3 neonate); nausea on table = hypotension; phenylephrine first line at CS; posture steers a heavy block only for 15-20 min; the family physician does not give the spinal."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Hypotension after a spinal",
        steps: [
          { label: "Nausea or SBP under 80% of baseline", detail: "Treat BP before giving an antiemetic", tone: "decision" },
          { label: "Left uterine displacement, fast crystalloid", detail: "Co-load 10-15 mL/kg" },
          { label: "Heart rate normal or high", detail: "Phenylephrine 50-100 microgram IV" },
          { label: "Bradycardia", detail: "Ephedrine 6 mg + atropine 0.6 mg; adrenaline 10-100 microgram if falling", tone: "warn" },
          { label: "Target SBP 90-100% of baseline", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Antithrombotics and neuraxial block (ASRA 2025)",
        columns: ["Drug", "Stop before puncture", "Restart after"],
        rows: [
          ["Aspirin, NSAID alone", "No need", "-"],
          ["SC heparin 5000 units", "4-6 h", "After block"],
          ["Prophylactic LMWH", "12 h", "12 h"],
          ["Therapeutic LMWH", "24 h", "24 h"],
          ["Warfarin", "5 days, INR 1.4 or less", "-"],
          ["Clopidogrel / prasugrel", "5-7 days / 7-10 days", "-"],
          ["Rivaroxaban, apixaban, edoxaban", "72 h", "At least 6 h"],
        ],
      },
    ],
  },
  "surgery-office-blood-transfusion": {
    checked: "2026-10",
    updated: [
      "AABB 2025 (international AMI guideline) and ACC/AHA 2025 ACS: in acute myocardial infarction a liberal strategy - transfuse when Hb is under 10 g/dL - replaces the restrictive threshold.",
    ],
    master: {
      heading: "Master revision table - blood transfusion and reactions",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "IV administration of a **specific blood component** prescribed like a drug for a defined indication, dose and rate; **component therapy** is the rule."],
        ["Relevant classification", "Components - PRBC, FFP, platelets, cryo; reactions **acute (under 24 h) vs delayed, immune vs non-immune**; massive transfusion = 1 blood volume/24 h, 10 units/24 h or 4 units/1 h; ABC score 2+."],
        ["Pathophysiology", "ABO IgM + complement -> intravascular haemolysis -> DIC, AKI; delayed = anamnestic IgG (Kidd); TRALI = donor anti-HLA/HNA; **TACO = volume overload (commonest transfusion death)**; storage lesion - K up, citrate binds Ca."],
        ["Key history (OPD)", "Why transfuse (symptoms, bleeding, surgery), cause of anaemia (iron deficiency = iron, not blood), previous reactions and antibodies, pregnancies and anti-D, heart or renal failure (TACO), immunosuppression, objection."],
        ["Key examination", "Pallor, shock class, heart failure; **baseline obs, then at 15 min, hourly, end and 4 h after**; watch the first 15 min directly."],
        ["Minimal investigations", "Hb, **ABO/RhD forward + reverse grouping**, antibody screen (IAT), major crossmatch; DAT in haemolysis; reaction work-up - repeat group, DAT, LDH, bilirubin, haptoglobin, urine Hb, cultures of patient and pack."],
        ["Diagnostic criteria", "**Restrictive threshold Hb 7 g/dL; 8 g/dL with cardiovascular disease or orthopaedic/cardiac surgery; under 10 g/dL in acute MI (AABB 2025)**; symptomatic anaemia at any Hb; clinical decision in acute bleeding."],
        ["Treatment - first line", "**One unit at a time** (raises Hb about 1 g/dL; child 10-15 mL/kg), 16-18 G, 170-200 micron filter, **saline only in the line**, start within 30 min, finish within 4 h (90-120 min)."],
        ["Escalation / second line", "FFP 10-15 mL/kg if PT/APTT over 1.5x with bleeding; platelets under 10,000 prophylactic, 50,000 surgery, 100,000 neuro; **cryo when fibrinogen under 1.5 g/L (2 in obstetrics)**; MTP 1:1:1 + **TXA 1 g within 3 h**; PCC + vitamin K for warfarin."],
        ["Devices / procedures", "Bedside sample labelling; **patient states name and DOB** at identity check; blood warmer only for rapid infusion; irradiated for immunosuppressed and relatives, washed for IgA deficiency."],
        ["Special groups", "D-negative girls and women - D-negative red cells; anti-D 300 microgram at 28 weeks and within 72 h; thalassaemia pre-transfusion Hb 9-10.5, chelate at ferritin over 1000; Jehovah's Witness - iron, TXA, cell salvage."],
        ["Complications", "Acute haemolysis, FNHTR, urticaria, anaphylaxis, TRALI, TACO, bacterial sepsis (platelets), delayed haemolysis, PTP, **TA-GVHD (over 90% fatal)**, iron overload, hyperkalaemia, hypocalcaemia."],
        ["Red flags & referral", "Fever with rigors or hypotension, **drip-site or loin pain in first 15 min**, dark urine, new dyspnoea within 6 h, wheeze or angioedema, oozing under anaesthesia."],
        ["Follow-up & monitoring", "Hb after each unit; delayed haemolysis at 3-14 days; antibody card; report every reaction to **Haemovigilance Programme of India**."],
        ["Prevention / national programme", "**Five mandatory tests - HIV, HBsAg, HCV, syphilis, malaria**; voluntary non-remunerated donation (paid donation illegal); donor Hb 12.5, 45 kg for 350 mL; patient blood management - treat anaemia with iron first."],
        ["Latest guideline change", "**AABB 2025 / ACC/AHA 2025**: after MINT, acute MI is managed with a **liberal threshold - transfuse under 10 g/dL** (non-bleeding anaemia)."],
        ["Exam one-liners", "Most fatal reactions are clerical; Ringer lactate clots, dextrose haemolyses; TRALI no diuretic, TACO furosemide; always irradiate a relative's blood."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Reaction during transfusion",
        steps: [
          { label: "Stop transfusion, keep vein open with saline via new set", tone: "warn" },
          { label: "ABC and recheck patient and pack identity" },
          { label: "Which picture?", detail: "Urticaria only / fever only / shock, dyspnoea, loin pain", tone: "decision" },
          { label: "Urticaria only - antihistamine, restart slowly", tone: "good" },
          { label: "Fever 1 C rise, stable - paracetamol", detail: "Exclude haemolysis and sepsis first" },
          { label: "Shock, haemoglobinuria, wheeze, hypoxia", detail: "Adrenaline 0.5 mg IM if anaphylaxis; fluids for urine 1-1.5 mL/kg/h; cultures; report HvPI", tone: "warn" },
        ],
      },
      {
        kind: "compare",
        heading: "Breathless within 6 hours - TRALI or TACO?",
        columns: ["Feature", "TRALI", "TACO"],
        rows: [
          ["Cause", "Donor anti-HLA/HNA antibodies", "Volume overload"],
          ["BP", "Low", "High"],
          ["JVP and BNP", "Normal", "Raised"],
          ["Fever", "Common", "Uncommon"],
          ["Treatment", "Oxygen, ventilation, no diuretic", "Sit up, oxygen, furosemide 40 mg IV"],
        ],
      },
    ],
  },
  "surgery-office-tracheostomy": {
    checked: "2026-10",
    updated: [
      "DAS 2025 (unanticipated difficult intubation): scalpel-bougie-tube cricothyroidotomy remains the preferred Plan D emergency front-of-neck airway.",
    ],
    master: {
      heading: "Master revision table - tracheostomy",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Opening in the **anterior tracheal wall at the 2nd-3rd rings** brought to skin as a stoma; emergency surgical airway is **cricothyroidotomy**, converted within 3-7 days."],
        ["Relevant classification", "Site - high (1st ring, condemned), **mid (2nd-3rd, standard)**, low (4th+); emergency vs elective; temporary vs permanent; open vs **percutaneous dilatational**; indications in **four groups**."],
        ["Aetiology & risk factors", "Indications: **upper airway obstruction, prolonged ventilation (commonest), bronchial toilet, elective cover for head and neck surgery**; TracMan - early (under 4 days) gives no survival benefit."],
        ["Pathophysiology", "Dead space falls 70-100 mL; resistance falls; **nose bypassed - humidification essential**; weak cough and voice loss; cuff over 30 cmH2O ischaemia, under 20 leak and VAP; tract matures in 5-7 days."],
        ["Key history (OPD)", "Indication and whether resolved, **laryngectomy or patent upper airway**, tube type and last change, secretions and suction frequency, bleeding after 48 h, aspiration, voice, home skills."],
        ["Key examination", "Agitation and desaturation = blocked or displaced tube; flange position, tapes one finger, airflow and capnography, **suction catheter passes?**, cuff by manometer 20-30 cmH2O, emphysema, pulsating tube."],
        ["Minimal investigations", "SpO2 and **waveform capnography**; chest X-ray after every new tracheostomy; coagulation before elective; laryngoscopy before decannulation; no routine surveillance cultures."],
        ["Treatment - first line", "Humidify (HME, heated humidifier, saline nebulisation 3-5 mL 4-6 hourly), suction on demand (catheter under half tube ID, 100-150 mmHg, 10-15 s), inner cannula cleaned 4-8 hourly, two-person tape change."],
        ["Escalation / second line", "Thick secretions - **3% hypertonic saline (salbutamol first)**, N-acetylcysteine; stomal cellulitis only - co-amoxiclav 625 mg TDS 5-7 d; granulation - silver nitrate; first tube change day 5-7 (7-10 after PDT)."],
        ["Devices / procedures", "Metal Jackson tube (no ventilation), cuffed PVC (ventilated, aspiration), double-lumen with inner cannula (ward and home), fenestrated, **speaking valve only with cuff fully deflated**; bedside spare same size and one smaller."],
        ["Special groups", "Child - vertical slit, stay sutures, uncuffed, no cartilage excised, **needle cricothyroidotomy under 12 years**; laryngectomee - **oxygenate and ventilate via stoma only**."],
        ["Complications", "Immediate - haemorrhage, pneumothorax, false passage; early - **blocked tube (commonest killer)**, displacement, emphysema; late - stenosis, granuloma, **tracheo-innominate fistula**, TOF."],
        ["Red flags & referral", "**Any bleed after 48 h (sentinel bleed)**, pulsating tube, food or dye in secretions, emphysema, stridor on capping, early displacement."],
        ["Follow-up & monitoring", "Decannulation readiness - indication resolved, FiO2 40% or less, suction no more than 3-4 hourly, safe swallow; deflate cuff, downsize, cap 24 h incl. night, remove; stoma closes 5-7 days."],
        ["Latest guideline change", "**DAS 2025**: in CICO, **scalpel-bougie-tube cricothyroidotomy** stays the preferred Plan D; 2nd-generation SGA is Plan B."],
        ["Exam one-liners", "2nd-3rd ring window; remove inner cannula first in an emergency; cuff 20-30 cmH2O; tracheostomy is not the emergency airway - cricothyroidotomy is."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Breathless tracheostomy patient - condensed NTSP",
        steps: [
          { label: "Call help; oxygen to face AND stoma", detail: "Check bed-head sign - laryngectomy?", tone: "warn" },
          { label: "Remove speaking valve or cap, then inner cannula" },
          { label: "Does a suction catheter pass?", detail: "Yes - suction and ventilate via tube", tone: "decision" },
          { label: "No - deflate cuff, reassess" },
          { label: "Still not improving - remove the tube", detail: "Reassess at mouth and stoma" },
          { label: "Oxygenate by patent route; secondary airway", detail: "Oral intubation past stoma or 6.0 cuffed tube via stoma over bougie", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Emergency surgical airway options",
        columns: ["Option", "Where", "Use"],
        rows: [
          ["Scalpel cricothyroidotomy", "Cricothyroid membrane; scalpel-bougie-6.0 tube", "Adult CICO - DAS 2025 Plan D"],
          ["Needle cricothyroidotomy", "14 G cannula, jet O2 15 L/min, 1 s on 4 s off", "Child under 12; bridge 30-45 min"],
          ["Tracheostomy", "2nd-3rd tracheal rings", "Elective or semi-elective over a secured airway"],
        ],
      },
    ],
  },
  "surgery-office-neck-swellings-thyroid": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - neck swellings, goitre and thyroid nodule",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Goitre = any thyroid enlargement (WHO grade 0-2); neck lump sorted by **triangle, movement with swallowing or tongue protrusion, and age**."],
        ["Relevant classification", "Goitre - simple, toxic, inflammatory, neoplastic; node levels I-VI; **ACR TI-RADS TR1-5** (FNAC TR3 2.5 cm, TR4 1.5 cm, TR5 1 cm); **Bethesda 2023 I-VI**."],
        ["Aetiology & risk factors", "Iodine deficiency, goitrogens, autoimmunity (Graves TRAb, Hashimoto anti-TPO); cancer risk - childhood irradiation, family history, MEN 2, extremes of age, male; India - **TB nodes**, tobacco - SCC nodes."],
        ["Pathophysiology", "Thyroglossal duct from foramen caecum loops behind hyoid (Sistrunk); TSH-driven hyperplasia -> MNG; papillary BRAF/lymphatic, follicular RAS/blood (**needs capsular invasion - FNAC cannot diagnose**); RLN in TO groove."],
        ["Key history (OPD)", "Duration and growth, pain (de Quervain, haemorrhage), pressure symptoms, **hoarseness**, thyroid status, B symptoms, tobacco and ENT symptoms, irradiation, drugs (amiodarone, lithium, biotin), pregnancy."],
        ["Key examination", "Swallow and tongue protrusion, palpate from behind, retrosternal extension and **Pemberton**, trachea, **Berry sign**, bruit, eye signs, carotid body tumour (side-to-side only), full ENT exam for any hard node."],
        ["Minimal investigations", "**TSH first** (low - scan, hot nodule not needled); **ultrasound with TI-RADS**; **US-guided FNAC by Bethesda**; nodes - FNAC + ZN + **CBNAAT**; lymphoma - core or excision; pre-op laryngoscopy and calcium."],
        ["Treatment - first line", "Iodised salt (30 ppm production, 15 ppm household); benign nodule - **US at 12-24 months, no T4 suppression**; Graves - **carbimazole 15-40 mg -> 5-15 mg for 12-18 months** + propranolol 40 mg TDS."],
        ["Escalation / second line", "PTU 100-150 mg TDS in first trimester and storm; radioiodine (not in pregnancy); thyroidectomy for pressure, Bethesda V-VI, retrosternal, failed medical; DTC - lobectomy or total by risk (ATA 2025)."],
        ["Devices / procedures", "Pre-op Graves: euthyroid + **Lugol's iodine 0.1-0.3 mL TDS for 10 days**; post-thyroidectomy - check Chvostek and Trousseau; tension haematoma - **SCOOP at bedside**."],
        ["Special groups", "Pregnancy - PTU first trimester, raise levothyroxine 30% at confirmation; elderly - start T4 25-50 microgram; child with nodule - urgent referral."],
        ["Complications", "RLN palsy (unilateral hoarse, bilateral stridor), EBSLN pitch loss, hypocalcaemia 24-72 h, haematoma, storm, agranulocytosis on thionamides, hypothyroidism."],
        ["Red flags & referral", "Stridor, rapid growth, hard fixed mass, **hoarseness with nodule**, child nodule, hard node in tobacco user, Virchow node, sight-threatening Graves eye disease."],
        ["Follow-up & monitoring", "Thionamides - FT4/T3 4-6 weekly; T4 - TSH 6-8 weeks after change, yearly when stable; DTC - thyroglobulin + antibody + US."],
        ["Prevention / national programme", "**NIDDCP iodised salt**; 150 microgram/day adult, 250 in pregnancy; TB - Ni-kshay notification, nutrition support, **6-month HRZE/HRE**; never start ATT without proof."],
        ["Exam one-liners", "Tongue protrusion = thyroglossal cyst; TSH first; never open-biopsy a metastatic node - FNAC and panendoscopy; agranulocytosis - stop drug, check neutrophils."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Thyroid nodule work-up",
        steps: [
          { label: "TSH", detail: "Low - FT4/T3 and scan; hot nodule not needled", tone: "decision" },
          { label: "Ultrasound - TI-RADS score and neck nodes" },
          { label: "Meets size threshold?", detail: "TR3 2.5 cm, TR4 1.5 cm, TR5 1 cm", tone: "decision" },
          { label: "US-guided FNAC - Bethesda", detail: "I repeat; II follow-up; III-IV repeat/molecular/lobectomy; V-VI surgery" },
          { label: "Benign - US at 12-24 months, no suppression", tone: "good" },
        ],
      },
      {
        kind: "branch",
        heading: "Lateral neck lump by age",
        root: "Lateral neck lump",
        arms: [
          { label: "Under 20", steps: ["Reactive node", "Branchial cyst", "Cystic hygroma", "TB node"] },
          { label: "20-40", steps: ["TB lymphadenitis (FNAC + CBNAAT)", "Thyroid nodule", "Lymphoma"] },
          { label: "Over 40", tone: "warn", steps: ["Metastatic SCC until proved otherwise", "Panendoscopy, never excision first", "Lymphoma - core or excision"] },
        ],
      },
    ],
  },
  "surgery-office-anorectal-disorders": {
    checked: "2026-10",
    updated: [
      "WHO STI 2024: STI proctitis regimen re-cited to the 2024 WHO update - ceftriaxone 1 g IM single dose (gonorrhoea) plus doxycycline 100 mg BD 7 days (21 days for LGV); syphilis benzathine penicillin 2.4 MU.",
    ],
    master: {
      heading: "Master revision table - anorectal disorders",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Haemorrhoids = enlarged displaced **anal cushions**; fissure = anoderm tear distal to dentate line; abscess-fistula = cryptoglandular sepsis; pilonidal = acquired hair sinus."],
        ["Relevant classification", "**Goligher I-IV**; fissure acute vs **chronic (over 6 weeks, sentinel pile, papilla, exposed IAS)**; abscess perianal, ischiorectal, intersphincteric, supralevator; **Parks fistula** 4 types; simple vs complex."],
        ["Aetiology & risk factors", "Low fibre, straining, prolonged toilet sitting, pregnancy; fissure - hard stool; fistula - anal glands, Crohn, TB, HIV; pilonidal - hair, sitting, deep cleft."],
        ["Pathophysiology", "Dentate line - above painless (band here), below somatic and painful; cushions at **3, 7, 11 o'clock**; fissure = IAS spasm -> posterior midline ischaemia; Goodsall rule for fistula."],
        ["Key history (OPD)", "Bleeding (bright on paper vs mixed), pain with stool (fissure) or constant throbbing (abscess), lump grade, discharge, itch; **red flags - 50+, weight loss, anaemia, habit change, family history**; sexual history; Crohn or TB clues."],
        ["Key examination", "Left lateral, chaperone, inspect (most fissures seen), strain (radial clefts vs concentric prolapse), **DRE**, proctoscopy, sigmoidoscopy if over 40; no DRE on acute fissure."],
        ["Minimal investigations", "Clinical; Hb and ferritin; **colonoscopy for bleeding at 50+ or red flags, FIT 10 microgram Hb/g or more**; HbA1c and HIV in perianal sepsis; **MRI pelvis for complex fistula**; biopsy atypical fissure."],
        ["Treatment - first line", "**Fibre 25-30 g, 2-3 L fluid, short toilet time, footstool, sitz baths**; ispaghula 3.5 g BD; PEG 17 g; fissure - **diltiazem 2% BD 6-8 weeks** (GTN 0.2-0.4% if not, headache, never with sildenafil)."],
        ["Escalation / second line", "**Rubber band ligation grade I-III** (1 cm above dentate line), sclerotherapy 5% phenol in almond oil; haemorrhoidectomy grade III-IV; botulinum 20-25 units or **lateral internal sphincterotomy**; fistulotomy for simple, seton/LIFT for complex."],
        ["Devices / procedures", "Thrombosed external pile within 72 h - **excise not incise**; perianal abscess - **drain same day**, close to verge, deroof; pilonidal abscess off midline, Karydakis or Bascom definitive."],
        ["Special groups", "Pregnancy - conservative; Crohn - seton + anti-TNF, **never lay open**; STI proctitis - **ceftriaxone 1 g IM + doxycycline 100 mg BD 7 d (21 d LGV)**; threadworm - albendazole 400 mg repeat at 2 weeks, whole household."],
        ["Complications", "Fistula after one third of abscesses, incontinence (sphincter injury), stenosis (quack injections), post-banding pelvic sepsis, Fournier gangrene."],
        ["Red flags & referral", "Bleeding at 50+ or with red flags, rectal mass, **IDA - scope both ends**, Fournier, massive bleed (treat as upper GI first), lateral or multiple fissures, severe pain or retention after banding."],
        ["Follow-up & monitoring", "Review piles and fissure at 6-8 weeks; abscess wound at 48-72 h; constipation step-up fibre -> osmotic -> stimulant -> manometry/biofeedback."],
        ["Latest guideline change", "**WHO STI 2024**: ceftriaxone **1 g IM** single dose for anorectal gonorrhoea, doxycycline 7 days for chlamydia (azithromycin 1 g in pregnancy)."],
        ["Exam one-liners", "No DRE, no diagnosis; band above the dentate line; diltiazem before GTN; lateral fissure is never idiopathic; drain abscess the day it is seen."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Bleeding per rectum in the OPD",
        steps: [
          { label: "Shock or massive bleed?", detail: "Resuscitate; exclude upper GI bleed first", tone: "warn" },
          { label: "Red flags?", detail: "50+, weight loss, anaemia, habit change, mass, family history - colonoscopy", tone: "decision" },
          { label: "Inspect, DRE, proctoscopy", detail: "Fissure, piles, prolapse, tumour" },
          { label: "Treat cause", detail: "Fibre, sitz baths; banding or diltiazem as indicated" },
          { label: "Review 6-8 weeks; scope if persists", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Chronic anal fissure ladder",
        steps: [
          { label: "Fibre, fluids, sitz baths, topical lignocaine" },
          { label: "Diltiazem 2% BD for 6-8 weeks", detail: "First choice - fewer headaches" },
          { label: "GTN 0.2-0.4% BD 6-8 weeks", detail: "Headache; never with PDE-5 inhibitors" },
          { label: "Botulinum toxin 20-25 units", detail: "Transient flatus incontinence" },
          { label: "Lateral internal sphincterotomy", detail: "Heals over 90%", tone: "good" },
        ],
      },
    ],
  },
  "surgery-office-varicose-veins-leg-ulcers": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - varicose veins and chronic leg ulcer",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "**Dilated tortuous superficial veins 3 mm or more standing** with reflux; venous ulcer = break between knee and ankle for 2 weeks+ with venous disease (70% of leg ulcers)."],
        ["Relevant classification", "**CEAP 2020 C0-C6** (C4a pigmentation/eczema, C4b LDS/atrophie blanche, C4c corona); primary vs secondary vs congenital; **ABPI 0.8-1.3 full compression, 0.5-0.8 reduced, under 0.5 none, over 1.3 calcified**."],
        ["Aetiology & risk factors", "Standing occupations, pregnancy, obesity, family history, previous DVT (post-thrombotic), Klippel-Trenaunay."],
        ["Pathophysiology", "Valve failure -> **ambulatory venous hypertension** (stays near 90 mmHg) -> leucocyte trapping, fibrin cuff -> haemosiderin, eczema, LDS -> ulcer in gaiter area (Cockett perforators)."],
        ["Key history (OPD)", "Aching, heaviness, cramps worse evening, relieved by elevation; occupation; previous DVT; claudication or rest pain; diabetes or leprosy; ulcer pain and duration; nicorandil, CCBs."],
        ["Key examination", "Standing exam, saphena varix, tap and cough tests, Trendelenburg I (SFJ) and II (perforators), **Perthes (deep obstruction)**, hand-held Doppler; ulcer edge, pulses, **ABPI in every ulcer**, monofilament."],
        ["Minimal investigations", "**ABPI before compression**; **duplex** - reflux over 0.5 s superficial, over 1 s deep; glucose, Hb, albumin; swab only if infected; **biopsy if atypical or not healed at 12 weeks**."],
        ["Treatment - first line", "Elevation, walking, calf exercises, weight loss, emollients; **class 1-2 graduated compression**; ulcer - **four-layer bandage about 40 mmHg** if ABPI 0.8+; MPFF 1000 mg daily."],
        ["Escalation / second line", "**Endovenous thermal ablation first line for truncal reflux**; cyanoacrylate or MOCA; foam sclerotherapy; high tie and strip to knee if no endovenous; **early ablation within 2 weeks for ulcers (EVRA)**; pentoxifylline 400 mg TDS."],
        ["Devices / procedures", "Stockings measured in the morning, replaced every 3-6 months, rolled on not folded; tumescent 0.1% lignocaine (35 mg/kg dilute limit)."],
        ["Special groups", "Mixed ulcer ABPI 0.5-0.8 - reduced compression under specialist; diabetic or neuropathic - offloading; superficial vein thrombosis 5 cm+ - **fondaparinux 2.5 mg daily 45 days**; within 3 cm of SFJ - treat as DVT."],
        ["Complications", "Bleeding varix, thrombophlebitis, DVT, eczema, LDS, ulcer, **Marjolin ulcer**; after intervention - EHIT, nerve injury (saphenous, sural), recurrence."],
        ["Red flags & referral", "Bleeding varix (elevate and press), suspected DVT, SVT near SFJ, ABPI under 0.5 or rest pain, rolled everted edge, cellulitis with sepsis, blue toes under bandage."],
        ["Follow-up & monitoring", "Ulcer weekly; **not 40% smaller in 4 weeks - reassess**; ABPI every 3-6 months; **lifelong class 2 compression after healing** (recurrence up to two-thirds)."],
        ["Exam one-liners", "No compression without ABPI; venous ulcers above medial malleolus, arterial on toes, heel, lateral malleolus; Perthes positive - do not strip; ablation halves recurrence (ESCHAR)."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Chronic leg ulcer - first visit",
        steps: [
          { label: "Pulses and ABPI", detail: "Under 0.5 - no compression, urgent vascular", tone: "warn" },
          { label: "Classify by site, edge, pain", detail: "Venous, arterial, neuropathic, malignant", tone: "decision" },
          { label: "Venous with ABPI 0.8+", detail: "Four-layer compression about 40 mmHg, weekly" },
          { label: "Refer for duplex and early ablation", detail: "Within 2 weeks (EVRA)" },
          { label: "Not 40% smaller at 4 weeks or unhealed at 12", detail: "Reassess and biopsy edge", tone: "decision" },
          { label: "Healed - lifelong class 2 stockings", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Venous vs arterial vs neuropathic ulcer",
        columns: ["Feature", "Venous", "Arterial", "Neuropathic"],
        rows: [
          ["Site", "Gaiter, above medial malleolus", "Toes, heel, lateral malleolus", "Sole, metatarsal heads"],
          ["Edge", "Sloping", "Punched out", "Punched out with callus"],
          ["Pain", "Mild, eased by elevation", "Severe, rest pain eased by dependency", "Painless"],
          ["ABPI", "0.8 or more", "Under 0.8", "May exceed 1.3"],
          ["Treatment", "Compression, ablation", "Revascularise, no compression", "Offloading"],
        ],
      },
    ],
  },
  "surgery-office-scrotal-swelling-acute-scrotum": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - scrotal swelling and acute scrotum",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Acute scrotum = acute pain or swelling of scrotal contents; **torsion until explored** in a boy or young man."],
        ["Relevant classification", "Acute - **torsion (intravaginal bell-clapper; extravaginal neonatal), appendage torsion, epididymo-orchitis**; painless - 3 questions (get above? testis separate? transilluminates?); varicocele grade I-III; UDT palpable vs impalpable."],
        ["Aetiology & risk factors", "Bell-clapper (bilateral), cold, sleep, exercise; epididymitis - **chlamydia/gonorrhoea under 35**, E. coli older or after instrumentation; mumps; TB; filariasis; tumour risk - cryptorchidism."],
        ["Pathophysiology", "Twist blocks veins then arteries -> infarction; **salvage over 90% within 6 h, under 10% after 24 h**; testis drains to para-aortic nodes, scrotum to inguinal; left varicocele - right-angle entry to renal vein."],
        ["Key history (OPD)", "Sudden pain from sleep or sport, **vomiting**, previous self-resolving episodes, dysuria and discharge, sexual history, mumps, painless heavy testis, infertility, filarial district."],
        ["Key examination", "**High-riding horizontal testis, absent cremasteric reflex**; blue dot (appendage); tender epididymis with reflex present; transillumination; bag of worms; testes in every boy with abdominal pain."],
        ["Minimal investigations", "**TWIST 5+ - theatre without imaging**, 3-4 urgent Doppler; first-void NAAT, MSU; scrotal US for masses; **AFP, beta-hCG, LDH before orchidectomy**; no US before UDT referral."],
        ["Treatment - first line", "Torsion - NBM, analgesia, **immediate exploration, bilateral fixation**; manual detorsion outward (open book) as bridge; epididymitis under 35 - **ceftriaxone 500 mg IM + doxycycline 100 mg BD 10 days**; enteric - levofloxacin 500 mg OD 10 days."],
        ["Escalation / second line", "Tumour - **radical inguinal orchidectomy**, never scrotal; adult hydrocele - Jaboulay or Lord; varicocele surgery only for infertility, hypotrophy or pain; phimosis - **betamethasone 0.05% BD 4-8 weeks**; circumcision for BXO."],
        ["Devices / procedures", "Dorsal penile block **plain lignocaine** at 10 and 2 o'clock; paraphimosis - ice, compression, sugar, reduce, dorsal slit if fails."],
        ["Special groups", "**UDT - refer at 6 months, orchidopexy 6-12 months (by 18)**, no hCG; bilateral impalpable testes in newborn - DSD, 17-OHP; communicating hydrocele - observe to 2 years; infant hernia - prompt herniotomy."],
        ["Complications", "Testicular loss or atrophy, infertility, abscess, chronic orchialgia, Fournier gangrene, missed tumour."],
        ["Red flags & referral", "Sudden testicular pain, vomiting with lower abdominal pain in adolescent, hard intratesticular mass, Fournier, dusky paraphimosis, right or non-decompressing varicocele."],
        ["Follow-up & monitoring", "Epididymitis review day 3, swelling over 4-6 weeks - ultrasound; retractile testis yearly to puberty; testicular self-examination."],
        ["Prevention / national programme", "MMR (IAP 9 m, 15 m, 4-6 y; UIP MR lacks mumps); filariasis **IDA MDA** (ivermectin, DEC, albendazole) and MMDP hydrocele surgery (NCVBDC)."],
        ["Exam one-liners", "Time is testis; Doppler never delays exploration; fix both sides; Prehn sign cannot exclude torsion; never approach a testicular tumour through the scrotum."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Acute painful scrotum",
        steps: [
          { label: "Sudden pain, vomiting, high horizontal testis?", detail: "Absent cremasteric reflex - score TWIST", tone: "decision" },
          { label: "TWIST 5-7", detail: "Straight to theatre - explore and fix both", tone: "warn" },
          { label: "TWIST 3-4", detail: "Urgent Doppler; low threshold to explore", tone: "decision" },
          { label: "Upper pole nodule, blue dot, reflex present", detail: "Appendage torsion - analgesia, rest" },
          { label: "Gradual, fever, dysuria, tender epididymis", detail: "Epididymo-orchitis - antibiotics by age and risk", tone: "good" },
        ],
      },
      {
        kind: "branch",
        heading: "Painless scrotal swelling - three questions",
        root: "Scrotal swelling",
        arms: [
          { label: "Cannot get above", steps: ["Inguinoscrotal hernia", "Infantile hydrocele"] },
          { label: "Above, testis not separate", steps: ["Hydrocele - transilluminates", "Tumour - does not; inguinal orchidectomy"] },
          { label: "Above, testis separate", steps: ["Epididymal cyst - brilliant", "Varicocele - bag of worms, empties lying"] },
        ],
      },
    ],
  },
  "surgery-office-rif-pain-appendicitis": {
    checked: "2026-10",
    updated: [
      "SSC 2026: perforated appendicitis with sepsis - at least 30 mL/kg balanced crystalloid, antibiotic within 1 hour.",
      "WSES 2025 (Jerusalem update, JAMA Surg 2026): post-operative antibiotics for complicated appendicitis shortened to 2-3 days after adequate source control.",
      "WSES 2025: interval appendicectomy not routine - advised for adults aged 35 or more managed non-operatively for an appendicular abscess (missed neoplasm).",
    ],
    master: {
      heading: "Master revision table - RIF pain and acute appendicitis",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Acute inflammation of the appendix, usually from **luminal obstruction**; commonest emergency abdominal operation (lifetime 7-8%)."],
        ["Relevant classification", "**Uncomplicated vs complicated** (gangrene, perforation, mass, abscess, peritonitis); **Alvarado 4 or less unlikely, 5-6 equivocal, 7+ probable**; **AIR 0-4, 5-8, 9-12**; AAS; PAS 6+."],
        ["Aetiology & risk factors", "Appendicolith, lymphoid hyperplasia (post-viral, children), parasites, carcinoid; perforation high under 5 and in elderly."],
        ["Pathophysiology", "Obstruction -> mucus, rising pressure -> venous then arterial block (**end artery - tip gangrene**) -> perforation; **visceral T10 periumbilical pain -> parietal RIF pain**; position decides signs."],
        ["Key history (OPD)", "**Murphy sequence - pain, anorexia/vomiting, migration to RIF, fever**; LMP and discharge in women; children - sore throat, intussusception, torsion; India - typhoid, ileocaecal TB, amoebiasis."],
        ["Key examination", "**McBurney tenderness and guarding**, Rovsing, rebound or percussion tenderness, psoas (retrocaecal), obturator (pelvic), RIF mass; **testes in every boy**, pelvic exam when PID possible."],
        ["Minimal investigations", "**Urine beta-hCG first in every woman of reproductive age**; TLC and CRP (both normal - unlikely); **graded-compression US first in children, young women, pregnancy**; low-dose CT in equivocal adults and elderly; MRI in pregnancy."],
        ["Treatment - first line", "NBM, IV fluids, **early analgesia (does not mask)**, **ceftriaxone + metronidazole or co-amoxiclav 1.2 g IV**; **laparoscopic appendicectomy**, within 24 h acceptable once antibiotics started."],
        ["Escalation / second line", "Antibiotics-first for CT-proven uncomplicated without appendicolith (about 3 in 10 operated by 90 days); mass - **Ochsner-Sherren**; abscess over 3-4 cm - percutaneous drainage; complicated - **post-op antibiotics 2-3 days (WSES 2025)**."],
        ["Devices / procedures", "Lanz or gridiron incision, muscle-splitting, find base at taeniae convergence, ligate appendicular artery, inspect 60 cm ileum for Meckel if normal; laparoscopy safe in all trimesters."],
        ["Special groups", "Pregnancy - appendix displaced up, perforation raises fetal loss to 20-35%, no NSAIDs after 20 weeks; children - omentum fails to wall off; elderly - early perforation, caecal carcinoma mimic."],
        ["Complications", "Perforation, peritonitis, pelvic or subphrenic abscess, **pylephlebitis**, SSI, adhesive obstruction, stump appendicitis, faecal fistula."],
        ["Red flags & referral", "Generalised peritonitis, shock, **positive pregnancy test with RIF pain**, child under 5, pregnancy, elderly, RIF mass with weight loss over 40, swinging fever days 5-10."],
        ["Follow-up & monitoring", "Safety-net low-risk discharges (review 12-24 h); wound 7-10 days; **read histology** (NET over 2 cm or at base, mucinous neoplasm - oncology); interval appendicectomy only selected (35+ after abscess)."],
        ["Latest guideline change", "**WSES 2025**: complicated appendicitis - **2-3 days** post-op antibiotics; interval appendicectomy for **adults 35+ after non-operative management of abscess**; **SSC 2026** - 30 mL/kg balanced crystalloid in septic peritonitis."],
        ["Exam one-liners", "Pregnancy test first; a hungry patient rarely has appendicitis; psoas = retrocaecal, obturator = pelvic; analgesia does not mask; no purgatives or enemas."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Right iliac fossa pain - OPD pathway",
        steps: [
          { label: "Woman of reproductive age - urine hCG", detail: "Positive with pain - ectopic until proved otherwise", tone: "warn" },
          { label: "Peritonitis or shock?", detail: "Resuscitate, antibiotic within 1 h, refer now", tone: "warn" },
          { label: "Score: AIR or Alvarado", tone: "decision", detail: "Low / intermediate / high" },
          { label: "Low - safety-net, review 12-24 h", tone: "good" },
          { label: "Intermediate - ultrasound or CT, serial exam" },
          { label: "High - surgical referral, laparoscopic appendicectomy", tone: "good" },
        ],
      },
      {
        kind: "ladder",
        heading: "Management by severity",
        steps: [
          { label: "Uncomplicated", detail: "Lap appendicectomy; no post-op antibiotics; or antibiotics-first if CT-proven, no appendicolith" },
          { label: "Gangrenous or perforated", detail: "Surgery + 2-3 days post-op antibiotics (WSES 2025)" },
          { label: "Appendicular mass", detail: "Ochsner-Sherren; abandon if pulse rises or peritonitis" },
          { label: "Abscess over 3-4 cm", detail: "Percutaneous drainage + antibiotics; interval surgery if 35+" },
          { label: "Generalised peritonitis", detail: "30 mL/kg balanced crystalloid, pip-taz, emergency source control", tone: "warn" },
        ],
      },
    ],
  },
  "surgery-office-hand-infections": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - hand infections",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Infections of the hand spreading along **closed compartments** - nail fold, pulp, flexor sheath, web and deep palmar spaces; **pus needs a knife**."],
        ["Relevant classification", "Superficial - acute and chronic paronychia, felon; deep - **pyogenic flexor tenosynovitis**, web, thenar, midpalmar, radial/ulnar bursae, Parona; septic arthritis, osteomyelitis; bites (WHO rabies I-III)."],
        ["Aetiology & risk factors", "**S. aureus (MRSA rising)**, strep; human bite - Eikenella, anaerobes; cat and dog - Pasteurella; diabetes (tropical diabetic hand), wet work (chronic paronychia), HSV (whitlow)."],
        ["Pathophysiology", "Pulp septa -> pressure ischaemia -> **diaphysis sequestrates, base spared**; sheath pus destroys tendon in hours; thumb and little finger sheaths -> radial and ulnar bursae -> horseshoe and Parona; palmar infection swells the dorsum."],
        ["Key history (OPD)", "Mechanism (thorn, lancet, manicure, bite, **fight**), throbbing night pain, occupation, diabetes and immunosuppression, prior antibiotics, tetanus and rabies status, hand dominance."],
        ["Key examination", "Localise by point of maximal tenderness; **Kanavel - flexed posture, fusiform swelling, sheath tenderness, pain on passive extension**; abducted fingers (web), thenar ballooning, lost palmar concavity; fight bite with fist clenched."],
        ["Minimal investigations", "**Glucose and HbA1c in every case**; pus Gram stain and culture; X-ray for fight bite, FB, gas, osteomyelitis; US for collections; Tzanck or HSV PCR for whitlow."],
        ["Treatment - first line", "Cellulitis - antibiotic, **elevation in high sling, splint in position of safety**, review 24-48 h; **cephalexin or cloxacillin 500 mg QID 5-7 days**; bites - **co-amoxiclav 625 mg TDS 5 days prophylaxis**."],
        ["Escalation / second line", "MRSA - co-trimoxazole DS BD, clindamycin, doxycycline; deep or sheath - **IV cefazolin 2 g 8-hourly + vancomycin if MRSA**, theatre drainage, total 10-14 days; OM 4-6 weeks."],
        ["Devices / procedures", "Digital block plain lignocaine 4-6 mL total; paronychia - lift fold, remove nail strip; **felon - high lateral incision on non-pinch side or volar midline if pointing, no fish-mouth**; sheath - catheter irrigation A1 to A5."],
        ["Special groups", "Herpetic whitlow - **acyclovir 400 mg TDS 7 days, never incise**; chronic paronychia - keep dry, potent topical steroid plus azole; diabetic hand - admit, insulin, early debridement."],
        ["Complications", "Tendon necrosis, stiffness, osteomyelitis, septic arthritis, spread to forearm, necrotising fasciitis, amputation."],
        ["Red flags & referral", "Kanavel signs, deep space signs, Parona swelling, **fight bite**, cat bite with swelling, lymphangitis with sepsis, necrotising signs, diabetic hand, no improvement in 24-48 h."],
        ["Follow-up & monitoring", "Review drained infections 24-48 h; hand therapy and early active movement; X-ray at 2-3 weeks if pain persists; complete rabies schedule."],
        ["Prevention / national programme", "Td per wound type; rabies PEP (IM Essen or ID 2-2-2-0-2; RIG into wounds for category III) under NRCP; gloves for wet work and farm work."],
        ["Exam one-liners", "Kanavel's four signs; palmar pus swells the dorsum; never suture a fight bite; never incise a herpetic whitlow; splint MCP flexed, IP straight."],
      ],
    },
    flows: [
      {
        kind: "flow",
        heading: "Swollen painful finger or hand",
        steps: [
          { label: "Bite or knuckle laceration?", detail: "Fight bite - X-ray, co-amoxiclav, same-day washout", tone: "warn" },
          { label: "Kanavel signs or deep space signs?", detail: "Admit, IV cefazolin (+ vancomycin), theatre", tone: "warn" },
          { label: "Localised pus in fold or pulp?", detail: "Drain under digital block", tone: "decision" },
          { label: "Vesicles?", detail: "Herpetic whitlow - acyclovir, do not incise", tone: "decision" },
          { label: "Cellulitis only", detail: "Cephalexin, elevate, splint, review 24-48 h", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Felon vs paronychia vs flexor tenosynovitis",
        columns: ["Feature", "Paronychia", "Felon", "Flexor tenosynovitis"],
        rows: [
          ["Space", "Nail fold", "Pulp septa", "Flexor sheath"],
          ["Key sign", "Red fold, pus at margin", "Tense pulp stopping at DIP crease", "Four Kanavel signs"],
          ["Where treated", "Clinic", "Clinic", "Theatre - emergency"],
          ["Drainage", "Lift fold, remove nail strip", "High lateral non-pinch side", "Catheter irrigation A1-A5"],
        ],
      },
    ],
  },
  "surgery-office-local-anaesthesia-nerve-blocks": {
    checked: "2026-10",
    master: {
      heading: "Master revision table - local anaesthetics and nerve blocks",
      columns: ["Aspect", "High-yield points"],
      rows: [
        ["Definition", "Drugs that **reversibly block voltage-gated sodium channels from inside the axon**, abolishing conduction without loss of consciousness."],
        ["Relevant classification", "**Esters** (procaine, chloroprocaine, tetracaine, benzocaine, cocaine - pseudocholinesterase, PABA allergy) vs **amides** ('i' before -caine, hepatic); short, intermediate, long acting; topical to neuraxial."],
        ["Pathophysiology", "Unionised base crosses membrane, cation blocks channel; **pKa - onset, lipid solubility - potency, protein binding - duration**; acid pus ionises drug; B and C fibres first, motor last; bupivacaine **fast in, slow out**."],
        ["Key history (OPD)", "Previous reaction (mostly vasovagal or adrenaline), weight (lean), heart, liver, pregnancy, beta-blockers or tricyclics, PAD or Raynaud (no adrenaline), G6PD and infants (prilocaine), neuropathy."],
        ["Key examination", "Vitals and weight; site free of infection; circulation of digit; **baseline two-point discrimination and power**; palpate landmarks (palmaris longus, FCU, EHL, malleoli)."],
        ["Minimal investigations", "None for simple blocks; SpO2 and ECG for large volumes; co-oximetry for methaemoglobinaemia; INR before deep blocks on warfarin."],
        ["Treatment - first line", "**Lignocaine 3 mg/kg plain (200 mg), 7 mg/kg with adrenaline (500 mg)**; **bupivacaine 2 mg/kg (150 mg)**; prilocaine 6 mg/kg (Bier's 0.5% 3 mg/kg); 1% = 10 mg/mL; adrenaline 1:200,000 = 5 microgram/mL."],
        ["Escalation / second line", "Mixtures additive (fractions under 1); levobupivacaine or ropivacaine for large volumes; buffer 1 mL 8.4% bicarbonate per 10 mL lignocaine; topical EMLA 60 min, LAT 20-30 min."],
        ["Devices / procedures", "Digital ring 4-6 mL or single volar 2-3 mL; wrist - median between PL and FCR, ulnar deep to FCU, radial subcutaneous; **ankle - 5 nerves, only posterior tibial and deep peroneal deep**; Bier's cuff 20 min minimum; intercostal below rib."],
        ["Special groups", "Adrenaline safe in healthy digits (WALANT) - **never penile or Bier's**; reduce dose in elderly, heart failure, liver disease, pregnancy; infants - EMLA max 1 g for 1 h."],
        ["Complications", "**LAST**, vasovagal, allergy, methaemoglobinaemia (prilocaine, benzocaine), digital ischaemia (phentolamine 1 mg), nerve injury, pneumothorax after intercostal."],
        ["Red flags & referral", "Perioral numbness, tinnitus, metallic taste; seizure, broad QRS, arrhythmia; SpO2 near 85% on oxygen; persistent numbness over 48 h."],
        ["Follow-up & monitoring", "Observe 30 min after large blocks; LAST - 2 h after CNS event, 4-6 h after cardiac; protect numb part; analgesia before bupivacaine wears off."],
        ["Exam one-liners", "**LAST: stop, airway, oxygen, benzodiazepine, 20% lipid 1.5 mL/kg then 0.25 mL/kg/min, max 12 mL/kg; adrenaline 1 microgram/kg or less; CPR an hour**; methylene blue not in G6PD deficiency."],
      ],
    },
    flows: [
      {
        kind: "ladder",
        heading: "Local anaesthetic systemic toxicity",
        steps: [
          { label: "Stop injecting, call help", detail: "Perioral numbness, tinnitus, twitching", tone: "warn" },
          { label: "Airway, 100% oxygen, ventilate", detail: "Hypoxia and acidosis worsen toxicity" },
          { label: "Seizures - benzodiazepine", detail: "Midazolam 0.05-0.1 mg/kg IV" },
          { label: "20% lipid emulsion", detail: "1.5 mL/kg over 2-3 min, then 0.25 mL/kg/min; repeat bolus x2; max 12 mL/kg" },
          { label: "Arrest - prolonged CPR", detail: "Adrenaline 1 microgram/kg or less; amiodarone; no lignocaine, vasopressin, CCB, beta-blocker", tone: "good" },
        ],
      },
      {
        kind: "compare",
        heading: "Maximum doses at a glance",
        columns: ["Agent", "Plain", "With adrenaline", "Note"],
        rows: [
          ["Lignocaine", "3 mg/kg (200 mg)", "7 mg/kg (500 mg)", "Onset 2-5 min"],
          ["Bupivacaine", "2 mg/kg (150 mg)", "2 mg/kg", "Most cardiotoxic; never Bier's"],
          ["Prilocaine", "6 mg/kg (400 mg)", "8 mg/kg with felypressin", "Bier's 0.5% 3 mg/kg; MetHb"],
          ["Ropivacaine", "3 mg/kg (200 mg)", "-", "Less cardiotoxic, less motor block"],
          ["Chloroprocaine", "11 mg/kg", "14 mg/kg", "Ester, very short"],
        ],
      },
    ],
  },
};

export default revision;
