import type { NoteTable } from "../../lib/types";

const scores: Record<string, NoteTable[]> = {
  "emergency-shock": [
    {
      heading: "ATLS classes of haemorrhagic shock (ATLS 11e 2025)",
      columns: ["Class", "Blood loss (% of volume)", "Physiology", "Base deficit", "Blood products"],
      rows: [
        ["Class I", "Under 15%", "HR, BP, pulse pressure, RR, urine output and GCS all normal", "0 to -2 mEq/L", "Monitor"],
        ["Class II", "15-30%", "HR normal or slightly up, BP normal, pulse pressure narrowed, RR and urine normal", "-2 to -6 mEq/L", "Possible"],
        ["Class III", "31-40%", "HR up, BP normal or falling, RR up, urine output down, GCS falling", "-6 to -10 mEq/L", "Yes - transfuse"],
        ["Class IV", "Over 40%", "Marked tachycardia, hypotension, narrow pulse pressure, oliguria, GCS down", "-10 mEq/L or worse", "Massive transfusion protocol"],
      ],
    },
    {
      heading: "Shock index grading in trauma haemorrhage - Mutschler groups (Rosen 10e 2022)",
      columns: ["Group", "Shock index (HR / SBP)", "Meaning", "Action"],
      rows: [
        ["Group I", "Under 0.6", "No shock", "Low transfusion need; observe and reassess"],
        ["Group II", "0.6 to under 1.0", "Mild shock", "Crystalloid-sparing resuscitation, crossmatch, find the bleeding"],
        ["Group III", "1.0 to under 1.4", "Moderate shock", "Likely to need blood; activate haemorrhage control"],
        ["Group IV", "1.4 or more", "Severe shock", "High chance of massive transfusion; MTP and immediate haemostasis"],
      ],
    },
    {
      heading: "qSOFA score for sepsis risk outside the ICU (Sepsis-3)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Respiratory rate", "22/min or more", "1"],
        ["Mentation", "Altered (GCS under 15)", "1"],
        ["Systolic BP", "100 mmHg or less", "1"],
      ],
    },
    {
      heading: "qSOFA score - interpretation (Surviving Sepsis Campaign 2021)",
      columns: ["qSOFA", "Meaning", "Action"],
      rows: [
        ["0-1", "Lower risk of poor outcome, but does not exclude sepsis", "Reassess; use clinical judgement and NEWS2"],
        ["2-3", "High risk of death or prolonged ICU stay if infection present", "Assess organ dysfunction (SOFA), lactate, cultures, antibiotics"],
        ["Limitation", "Poor sensitivity; SSC 2021 advises against qSOFA alone as a screening tool", "Screen with NEWS2 or SIRS alongside"],
      ],
    },
    {
      heading: "SOFA score for organ dysfunction (Sepsis-3, Harrison 22e 2025)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Respiration - PaO2/FiO2 (mmHg)", "400 or more", "0"],
        ["Respiration - PaO2/FiO2 (mmHg)", "Under 400", "1"],
        ["Respiration - PaO2/FiO2 (mmHg)", "Under 300", "2"],
        ["Respiration - PaO2/FiO2 (mmHg)", "Under 200 with respiratory support", "3"],
        ["Respiration - PaO2/FiO2 (mmHg)", "Under 100 with respiratory support", "4"],
        ["Coagulation - platelets (x10^3/microL)", "150 or more", "0"],
        ["Coagulation - platelets (x10^3/microL)", "Under 150", "1"],
        ["Coagulation - platelets (x10^3/microL)", "Under 100", "2"],
        ["Coagulation - platelets (x10^3/microL)", "Under 50", "3"],
        ["Coagulation - platelets (x10^3/microL)", "Under 20", "4"],
        ["Liver - bilirubin (mg/dL)", "Under 1.2", "0"],
        ["Liver - bilirubin (mg/dL)", "1.2-1.9", "1"],
        ["Liver - bilirubin (mg/dL)", "2.0-5.9", "2"],
        ["Liver - bilirubin (mg/dL)", "6.0-11.9", "3"],
        ["Liver - bilirubin (mg/dL)", "12.0 or more", "4"],
        ["Cardiovascular (doses in microgram/kg/min)", "MAP 70 mmHg or more", "0"],
        ["Cardiovascular (doses in microgram/kg/min)", "MAP under 70 mmHg", "1"],
        ["Cardiovascular (doses in microgram/kg/min)", "Dopamine under 5 or any dobutamine", "2"],
        ["Cardiovascular (doses in microgram/kg/min)", "Dopamine 5.1-15, or adrenaline or noradrenaline 0.1 or less", "3"],
        ["Cardiovascular (doses in microgram/kg/min)", "Dopamine over 15, or adrenaline or noradrenaline over 0.1", "4"],
        ["CNS - Glasgow Coma Scale", "15", "0"],
        ["CNS - Glasgow Coma Scale", "13-14", "1"],
        ["CNS - Glasgow Coma Scale", "10-12", "2"],
        ["CNS - Glasgow Coma Scale", "6-9", "3"],
        ["CNS - Glasgow Coma Scale", "Under 6", "4"],
        ["Renal - creatinine (mg/dL) or urine output", "Under 1.2", "0"],
        ["Renal - creatinine (mg/dL) or urine output", "1.2-1.9", "1"],
        ["Renal - creatinine (mg/dL) or urine output", "2.0-3.4", "2"],
        ["Renal - creatinine (mg/dL) or urine output", "3.5-4.9 or urine under 500 mL/day", "3"],
        ["Renal - creatinine (mg/dL) or urine output", "5.0 or more or urine under 200 mL/day", "4"],
      ],
    },
    {
      heading: "Sepsis-3 definitions using the SOFA score (Surviving Sepsis Campaign 2021)",
      columns: ["Category", "Definition", "Meaning"],
      rows: [
        ["Sepsis", "Suspected or proven infection plus acute rise in SOFA of 2 or more (baseline 0 if unknown)", "Life-threatening organ dysfunction; about 10% hospital mortality"],
        ["Septic shock", "Sepsis needing vasopressor for MAP 65 mmHg or more and lactate over 2 mmol/L despite adequate fluid", "Hospital mortality over 40%"],
        ["Hour-1 bundle", "Lactate, blood cultures, broad-spectrum antibiotics, 30 mL/kg crystalloid if hypotensive or lactate 4+", "Start vasopressor (noradrenaline) if MAP stays under 65 mmHg"],
        ["SOFA-2 (2025)", "Updated version with revised organ cut-offs and support categories", "Sepsis-3 criteria were derived with the original SOFA above"],
      ],
    },
    {
      heading: "NEWS2 score for acute illness severity (Royal College of Physicians 2017)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Respiratory rate (/min)", "8 or less", "3"],
        ["Respiratory rate (/min)", "9-11", "1"],
        ["Respiratory rate (/min)", "12-20", "0"],
        ["Respiratory rate (/min)", "21-24", "2"],
        ["Respiratory rate (/min)", "25 or more", "3"],
        ["SpO2 scale 1 (%)", "91 or less", "3"],
        ["SpO2 scale 1 (%)", "92-93", "2"],
        ["SpO2 scale 1 (%)", "94-95", "1"],
        ["SpO2 scale 1 (%)", "96 or more", "0"],
        ["SpO2 scale 2 (%) - hypercapnic target 88-92", "83 or less", "3"],
        ["SpO2 scale 2 (%) - hypercapnic target 88-92", "84-85", "2"],
        ["SpO2 scale 2 (%) - hypercapnic target 88-92", "86-87", "1"],
        ["SpO2 scale 2 (%) - hypercapnic target 88-92", "88-92, or 93 or more on air", "0"],
        ["SpO2 scale 2 (%) - hypercapnic target 88-92", "93-94 on oxygen", "1"],
        ["SpO2 scale 2 (%) - hypercapnic target 88-92", "95-96 on oxygen", "2"],
        ["SpO2 scale 2 (%) - hypercapnic target 88-92", "97 or more on oxygen", "3"],
        ["Air or oxygen", "Air", "0"],
        ["Air or oxygen", "Oxygen", "2"],
        ["Systolic BP (mmHg)", "90 or less", "3"],
        ["Systolic BP (mmHg)", "91-100", "2"],
        ["Systolic BP (mmHg)", "101-110", "1"],
        ["Systolic BP (mmHg)", "111-219", "0"],
        ["Systolic BP (mmHg)", "220 or more", "3"],
        ["Pulse (/min)", "40 or less", "3"],
        ["Pulse (/min)", "41-50", "1"],
        ["Pulse (/min)", "51-90", "0"],
        ["Pulse (/min)", "91-110", "1"],
        ["Pulse (/min)", "111-130", "2"],
        ["Pulse (/min)", "131 or more", "3"],
        ["Consciousness (ACVPU)", "Alert", "0"],
        ["Consciousness (ACVPU)", "New confusion, or responds to voice or pain, or unresponsive", "3"],
        ["Temperature (C)", "35.0 or less", "3"],
        ["Temperature (C)", "35.1-36.0", "1"],
        ["Temperature (C)", "36.1-38.0", "0"],
        ["Temperature (C)", "38.1-39.0", "1"],
        ["Temperature (C)", "39.1 or more", "2"],
      ],
    },
    {
      heading: "NEWS2 score bands and clinical response (Royal College of Physicians 2017)",
      columns: ["NEWS2", "Clinical risk", "Response"],
      rows: [
        ["0", "Low", "Monitor at least 12-hourly"],
        ["1-4", "Low", "At least 4-6 hourly; registered nurse decides if more is needed"],
        ["3 in any single parameter", "Low-medium", "Urgent ward-based review by a clinician; at least hourly observations"],
        ["5-6", "Medium", "Urgent response by a clinician competent in acute illness; at least hourly"],
        ["7 or more", "High", "Emergency response by critical care team; continuous monitoring, consider ICU transfer"],
      ],
    },
  ],
  "emergency-trauma-primary-survey": [
    {
      heading: "Revised Trauma Score - triage version (Bailey and Love 28e 2023)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Glasgow Coma Scale", "13-15", "4"],
        ["Glasgow Coma Scale", "9-12", "3"],
        ["Glasgow Coma Scale", "6-8", "2"],
        ["Glasgow Coma Scale", "4-5", "1"],
        ["Glasgow Coma Scale", "3", "0"],
        ["Systolic BP (mmHg)", "Over 89", "4"],
        ["Systolic BP (mmHg)", "76-89", "3"],
        ["Systolic BP (mmHg)", "50-75", "2"],
        ["Systolic BP (mmHg)", "1-49", "1"],
        ["Systolic BP (mmHg)", "0", "0"],
        ["Respiratory rate (/min)", "10-29", "4"],
        ["Respiratory rate (/min)", "Over 29", "3"],
        ["Respiratory rate (/min)", "6-9", "2"],
        ["Respiratory rate (/min)", "1-5", "1"],
        ["Respiratory rate (/min)", "0", "0"],
      ],
    },
    {
      heading: "Revised Trauma Score - interpretation (Bailey and Love 28e 2023)",
      columns: ["RTS", "Meaning", "Use"],
      rows: [
        ["Triage RTS 12", "Physiologically normal", "Routine trauma assessment"],
        ["Triage RTS 11 or less", "Physiologically compromised", "Field triage to a trauma centre"],
        ["Weighted RTS", "0.9368 GCS + 0.7326 SBP + 0.2908 RR (coded values); range 0-7.84", "Outcome prediction; combined with ISS and age in TRISS"],
      ],
    },
    {
      heading: "Abbreviated Injury Scale and Injury Severity Score (Bailey and Love 28e 2023)",
      columns: ["Grade", "Definition", "Meaning"],
      rows: [
        ["AIS 1", "Minor injury", "Each injury is coded 1-6 in one of six ISS body regions"],
        ["AIS 2", "Moderate injury", "Regions: head/neck, face, chest, abdomen, extremities/pelvis, external"],
        ["AIS 3", "Serious injury", "Not immediately life-threatening"],
        ["AIS 4", "Severe injury", "Life-threatening, survival probable"],
        ["AIS 5", "Critical injury", "Survival uncertain"],
        ["AIS 6", "Maximal injury", "Currently untreatable; ISS set at 75 automatically"],
        ["ISS calculation", "Sum of squares of the highest AIS in the three most severely injured regions", "Range 0-75"],
        ["ISS over 15", "Major trauma (polytrauma threshold)", "Trauma centre care; used for audit and registries"],
      ],
    },
    {
      heading: "Canadian CT head rule criteria for minor head injury (Tintinalli 9e 2020)",
      columns: ["Criterion", "Definition", "Meaning"],
      rows: [
        ["Applies to", "GCS 13-15 with witnessed LOC, amnesia or disorientation, age 16 or more", "Not for anticoagulated, seizure after injury, or obvious open fracture"],
        ["High risk 1", "GCS under 15 at 2 hours after injury", "Predicts need for neurosurgical intervention - CT"],
        ["High risk 2", "Suspected open or depressed skull fracture", "CT"],
        ["High risk 3", "Any sign of basal skull fracture", "Haemotympanum, raccoon eyes, CSF oto/rhinorrhoea, Battle sign - CT"],
        ["High risk 4", "Vomiting 2 or more episodes", "CT"],
        ["High risk 5", "Age 65 years or more", "CT"],
        ["Medium risk 1", "Amnesia before impact 30 minutes or more", "Predicts brain injury on CT - CT"],
        ["Medium risk 2", "Dangerous mechanism", "Pedestrian struck, ejected occupant, fall over 3 feet or 5 stairs - CT"],
      ],
    },
    {
      heading: "Canadian C-spine rule criteria for alert stable trauma patients (Tintinalli 9e 2020)",
      columns: ["Step", "Criteria", "Action"],
      rows: [
        ["Applies to", "GCS 15, stable vitals, age 16 or more, neck injury concern within 48 hours", "Not for penetrating trauma, paralysis or known spinal disease"],
        ["Step 1 - high-risk factor", "Age 65 or more, dangerous mechanism, or limb paraesthesias", "Any present - image the cervical spine"],
        ["Dangerous mechanism", "Fall 3 feet or 5 stairs, axial load, high-speed/rollover/ejection crash, bicycle collision", "Counts as high risk"],
        ["Step 2 - low-risk factor", "Simple rear-end crash, sitting in ED, ambulatory, delayed neck pain, no midline tenderness", "None present - image; any present - go to step 3"],
        ["Step 3 - rotation", "Able to actively rotate neck 45 degrees left and right", "Able - no imaging; unable - image"],
      ],
    },
    {
      heading: "NEXUS low-risk criteria for cervical spine imaging (Rosen 10e 2022)",
      columns: ["Criterion", "Requirement", "Meaning"],
      rows: [
        ["Midline tenderness", "No posterior midline cervical tenderness", "All five must be met to clear clinically without imaging"],
        ["Intoxication", "No evidence of intoxication", "Any one failed - image (CT in adults)"],
        ["Alertness", "Normal level of alertness", "Sensitivity about 99% for significant injury"],
        ["Focal deficit", "No focal neurological deficit", "Canadian C-spine rule is more specific"],
        ["Distracting injury", "No painful distracting injury", "E.g. long-bone fracture, large burn"],
      ],
    },
    {
      heading: "Ottawa ankle and foot rule criteria for radiography (Rosen 10e 2022)",
      columns: ["Criterion", "Finding", "Action"],
      rows: [
        ["Ankle - lateral malleolus", "Bone tenderness at posterior edge or tip of distal 6 cm of fibula", "Ankle X-ray if pain in malleolar zone plus any ankle criterion"],
        ["Ankle - medial malleolus", "Bone tenderness at posterior edge or tip of distal 6 cm of tibia", "Ankle X-ray"],
        ["Ankle - weight bearing", "Unable to take 4 steps both immediately and in the ED", "Ankle X-ray"],
        ["Foot - fifth metatarsal", "Bone tenderness at base of fifth metatarsal", "Foot X-ray if pain in midfoot zone plus any foot criterion"],
        ["Foot - navicular", "Bone tenderness at navicular", "Foot X-ray"],
        ["Foot - weight bearing", "Unable to take 4 steps both immediately and in the ED", "Foot X-ray"],
      ],
    },
    {
      heading: "Ottawa knee rule criteria for radiography after knee injury (Rosen 10e 2022)",
      columns: ["Criterion", "Finding", "Action"],
      rows: [
        ["Age", "55 years or more", "Any one criterion - knee X-ray"],
        ["Patella", "Isolated tenderness of patella (no other bone tenderness)", "Knee X-ray"],
        ["Fibula", "Tenderness at head of fibula", "Knee X-ray"],
        ["Flexion", "Unable to flex knee to 90 degrees", "Knee X-ray"],
        ["Weight bearing", "Unable to take 4 steps both immediately and in the ED", "Knee X-ray"],
      ],
    },
    {
      heading: "Gustilo-Anderson classification of open fractures (Rockwood 10e 2024)",
      columns: ["Type", "Wound and soft tissue", "Management and risk"],
      rows: [
        ["Type I", "Wound under 1 cm, clean, minimal soft tissue damage, simple fracture", "IV antibiotic within 1 hour, debridement, fixation; infection up to 2%"],
        ["Type II", "Wound 1-10 cm, moderate soft tissue damage, no flaps or avulsion", "As type I; infection about 2-10%"],
        ["Type IIIA", "Over 10 cm or high energy, extensive damage but adequate bone cover", "Includes farmyard, segmental and gunshot fractures; local cover"],
        ["Type IIIB", "Extensive soft tissue loss, periosteal stripping, bone exposed", "Needs flap cover (orthoplastic care); high infection risk"],
        ["Type IIIC", "Open fracture with arterial injury needing repair", "Vascular repair or shunt; highest amputation risk"],
      ],
    },
    {
      heading: "Tscherne classification of soft tissue injury in closed fractures (Rockwood 10e 2024)",
      columns: ["Grade", "Soft tissue", "Fracture pattern"],
      rows: [
        ["Grade C0", "Minimal soft tissue damage", "Indirect force, simple fracture"],
        ["Grade C1", "Superficial abrasion or contusion from fragment pressure within", "Mild to moderate fracture pattern"],
        ["Grade C2", "Deep contaminated abrasion, local skin or muscle contusion, impending compartment syndrome", "Direct force, severe fracture pattern"],
        ["Grade C3", "Extensive contusion or crush, degloving, muscle destruction, compartment syndrome or vascular injury", "Severe or comminuted fracture"],
      ],
    },
    {
      heading: "Salter-Harris classification of physeal injuries (Rockwood 10e 2024)",
      columns: ["Type", "Fracture line", "Prognosis and management"],
      rows: [
        ["Type I (S - straight)", "Through the physis only", "Good prognosis; closed reduction and cast"],
        ["Type II (A - above)", "Through physis and exits the metaphysis (Thurston-Holland fragment)", "Commonest (about 75%); good prognosis"],
        ["Type III (L - lower)", "Through physis and exits the epiphysis - intra-articular", "Needs anatomical reduction, often ORIF"],
        ["Type IV (T - through)", "Through metaphysis, physis and epiphysis", "ORIF; risk of growth arrest and angular deformity"],
        ["Type V (R - rammed)", "Crush of the physis", "Often diagnosed late; worst prognosis for growth arrest"],
      ],
    },
    {
      heading: "Garden classification of intracapsular femoral neck fractures (Rockwood 10e 2024)",
      columns: ["Grade", "Radiograph", "Usual management"],
      rows: [
        ["Garden I", "Incomplete or valgus-impacted fracture", "Undisplaced - internal fixation (cannulated screws)"],
        ["Garden II", "Complete fracture, undisplaced", "Undisplaced - internal fixation"],
        ["Garden III", "Complete, partially displaced; trabeculae out of alignment", "Displaced - arthroplasty in elderly; urgent reduction and fixation if young"],
        ["Garden IV", "Complete, fully displaced; trabeculae parallel again", "Displaced - hemiarthroplasty or total hip replacement; highest AVN risk"],
      ],
    },
    {
      heading: "Weber classification of lateral malleolus fractures (Rockwood 10e 2024)",
      columns: ["Type", "Level of fibular fracture", "Stability and management"],
      rows: [
        ["Weber A", "Below the syndesmosis (infra-syndesmotic)", "Usually stable - boot or cast, early weight bearing"],
        ["Weber B", "At the level of the syndesmosis (trans-syndesmotic)", "May be unstable - check medial side and stress views; ORIF if unstable"],
        ["Weber C", "Above the syndesmosis (supra-syndesmotic)", "Syndesmosis disrupted - unstable, ORIF with syndesmotic fixation"],
        ["Maisonneuve", "Proximal fibular fracture with medial ankle injury", "Variant of Weber C; unstable syndesmosis"],
      ],
    },
    {
      heading: "Mangled Extremity Severity Score (MESS) (Rockwood 10e 2024)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Skeletal and soft tissue injury", "Low energy (stab, simple fracture, civilian gunshot)", "1"],
        ["Skeletal and soft tissue injury", "Medium energy (open or multiple fractures, dislocation)", "2"],
        ["Skeletal and soft tissue injury", "High energy (close-range shotgun, military gunshot, crush)", "3"],
        ["Skeletal and soft tissue injury", "Very high energy plus gross contamination or avulsion", "4"],
        ["Limb ischaemia (double if over 6 hours)", "Pulse reduced or absent, perfusion normal", "1"],
        ["Limb ischaemia (double if over 6 hours)", "Pulseless, paraesthesias, slow capillary refill", "2"],
        ["Limb ischaemia (double if over 6 hours)", "Cool, paralysed, insensate, numb", "3"],
        ["Shock", "Systolic BP always over 90 mmHg", "0"],
        ["Shock", "Transient hypotension", "1"],
        ["Shock", "Persistent hypotension", "2"],
        ["Age (years)", "Under 30", "0"],
        ["Age (years)", "30-50", "1"],
        ["Age (years)", "Over 50", "2"],
      ],
    },
    {
      heading: "Mangled Extremity Severity Score - interpretation (Rockwood 10e 2024)",
      columns: ["MESS", "Meaning", "Action"],
      rows: [
        ["Under 7", "Limb salvage usually feasible", "Revascularise, debride, stabilise"],
        ["7 or more", "Predicts amputation in the original series", "Senior orthoplastic decision; never use the score alone"],
      ],
    },
    {
      heading: "START triage classification for mass casualty incidents (Tintinalli 9e 2020)",
      columns: ["Category", "Criteria", "Priority"],
      rows: [
        ["Green - minor", "Walking wounded", "Delayed care; move to a collection point"],
        ["Black - expectant/dead", "Not breathing even after airway repositioning", "No resuscitation in the field"],
        ["Red - immediate", "Breathes only after repositioning, RR over 30, radial pulse absent or CRT over 2 s, or cannot obey commands", "First priority for treatment and transport"],
        ["Yellow - delayed", "Non-ambulant but breathing under 30, perfusion adequate, obeys commands", "Treat after red; reassess often"],
      ],
    },
  ],
  "emergency-altered-sensorium": [
    {
      heading: "FOUR score (Full Outline of UnResponsiveness) coma scale (Harrison 22e 2025)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Eye response", "Eyelids open or opened, tracking or blinking to command", "4"],
        ["Eye response", "Eyelids open but not tracking", "3"],
        ["Eye response", "Eyelids closed, open to loud voice", "2"],
        ["Eye response", "Eyelids closed, open to pain", "1"],
        ["Eye response", "Eyelids remain closed with pain", "0"],
        ["Motor response", "Thumbs-up, fist or peace sign to command", "4"],
        ["Motor response", "Localising to pain", "3"],
        ["Motor response", "Flexion response to pain", "2"],
        ["Motor response", "Extension response to pain", "1"],
        ["Motor response", "No response to pain or generalised myoclonus status", "0"],
        ["Brainstem reflexes", "Pupil and corneal reflexes present", "4"],
        ["Brainstem reflexes", "One pupil wide and fixed", "3"],
        ["Brainstem reflexes", "Pupil or corneal reflexes absent", "2"],
        ["Brainstem reflexes", "Pupil and corneal reflexes absent", "1"],
        ["Brainstem reflexes", "Pupil, corneal and cough reflexes absent", "0"],
        ["Respiration", "Not intubated, regular breathing pattern", "4"],
        ["Respiration", "Not intubated, Cheyne-Stokes pattern", "3"],
        ["Respiration", "Not intubated, irregular breathing", "2"],
        ["Respiration", "Breathes above ventilator rate", "1"],
        ["Respiration", "Breathes at ventilator rate or apnoea", "0"],
      ],
    },
    {
      heading: "FOUR score - interpretation (Harrison 22e 2025)",
      columns: ["Total", "Meaning", "Note"],
      rows: [
        ["16", "Fully responsive", "Range 0-16; lower totals carry higher mortality"],
        ["0", "No eye, motor, brainstem or respiratory response", "Prompts formal brain death assessment"],
        ["Advantage over GCS", "Scores intubated patients and tests brainstem and breathing", "Detects locked-in state (eye tracking) and uncal herniation"],
      ],
    },
    {
      heading: "AVPU and ACVPU scale for rapid consciousness assessment (ATLS 11e 2025)",
      columns: ["Level", "Definition", "Meaning"],
      rows: [
        ["A - Alert", "Eyes open spontaneously, aware", "Roughly GCS 14-15"],
        ["C - New confusion", "New disorientation or confusion (ACVPU, used in NEWS2)", "Scores 3 on NEWS2 - look for sepsis, hypoxia, hypoglycaemia"],
        ["V - Voice", "Responds only to voice", "Reduced consciousness"],
        ["P - Pain", "Responds only to painful stimulus", "Roughly GCS 8 or less - airway at risk"],
        ["U - Unresponsive", "No response to voice or pain", "Protect airway; full GCS and cause-finding"],
      ],
    },
    {
      heading: "Modified Fisher scale for vasospasm risk after SAH (Harrison 22e 2025)",
      columns: ["Grade", "CT findings", "Symptomatic vasospasm risk"],
      rows: [
        ["Grade 0", "No SAH, no intraventricular haemorrhage", "Very low"],
        ["Grade 1", "Thin (focal or diffuse) SAH, no IVH", "About 24%"],
        ["Grade 2", "Thin SAH with IVH", "About 33%"],
        ["Grade 3", "Thick SAH (fills a cistern or fissure), no IVH", "About 33%"],
        ["Grade 4", "Thick SAH with IVH", "About 40%"],
      ],
    },
  ],
  "emergency-poisoning": [
    {
      heading: "Peradeniya Organophosphorus Poisoning (POP) scale (Senanayake, Park 28e 2025)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Pupil size", "Over 2 mm", "0"],
        ["Pupil size", "Under 2 mm", "1"],
        ["Pupil size", "Pinpoint", "2"],
        ["Fasciculations", "None", "0"],
        ["Fasciculations", "Present but not generalised or continuous", "1"],
        ["Fasciculations", "Generalised and continuous", "2"],
        ["Respiration", "Under 20/min", "0"],
        ["Respiration", "Over 20/min", "1"],
        ["Respiration", "Over 20/min with central cyanosis", "2"],
        ["Heart rate", "Over 60/min", "0"],
        ["Heart rate", "41-60/min", "1"],
        ["Heart rate", "Under 40/min", "2"],
        ["Level of consciousness", "Conscious and rational", "0"],
        ["Level of consciousness", "Impaired, responds to verbal commands", "1"],
        ["Level of consciousness", "Impaired, no response to verbal commands", "2"],
        ["Seizures", "Absent", "0"],
        ["Seizures", "Present", "1"],
      ],
    },
    {
      heading: "POP scale severity bands (Park 28e 2025)",
      columns: ["POP score", "Severity", "Action"],
      rows: [
        ["0-3", "Mild poisoning", "Atropine to atropinisation, decontaminate, observe for intermediate syndrome"],
        ["4-7", "Moderate poisoning", "Admit, titrated atropine, close monitoring of respiration"],
        ["8-11", "Severe poisoning", "ICU, early intubation and ventilation likely, high atropine needs"],
      ],
    },
    {
      heading: "Poisoning Severity Score grading (IPCS/EAPCCT, Tintinalli 9e 2020)",
      columns: ["Grade", "Definition", "Example"],
      rows: [
        ["Grade 0 - None", "No symptoms or signs related to poisoning", "Asymptomatic after ingestion"],
        ["Grade 1 - Minor", "Mild, transient, spontaneously resolving symptoms", "Nausea, mild drowsiness"],
        ["Grade 2 - Moderate", "Pronounced or prolonged symptoms", "Persistent vomiting, confusion, bradycardia needing treatment"],
        ["Grade 3 - Severe", "Severe or life-threatening symptoms", "Coma, shock, respiratory failure, seizures"],
        ["Grade 4 - Fatal", "Death", "-"],
      ],
    },
    {
      heading: "Stages of paracetamol (acetaminophen) toxicity (Tintinalli 9e 2020)",
      columns: ["Stage", "Timing after ingestion", "Features"],
      rows: [
        ["Stage I", "0-24 hours", "Asymptomatic or nausea, vomiting, malaise; LFTs usually normal"],
        ["Stage II", "24-72 hours", "Right upper quadrant pain, rising ALT/AST and INR, possible oliguria"],
        ["Stage III", "72-96 hours", "Peak hepatotoxicity - jaundice, encephalopathy, coagulopathy, AKI, lactic acidosis"],
        ["Stage IV", "4 days to 2 weeks", "Recovery with normal liver, or death or transplant"],
      ],
    },
    {
      heading: "Paracetamol overdose risk classification and NAC action (OHCM 11e 2024)",
      columns: ["Category", "Definition", "Action"],
      rows: [
        ["Toxic dose", "150 mg/kg or more (or 7.5 g or more in an adult) in 24 hours", "Assess with timed level; lower amounts rarely hepatotoxic"],
        ["Below treatment line", "4-hour or later level below the nomogram line", "No NAC if LFTs normal; psychiatric review"],
        ["On or above treatment line", "Rumack-Matthew line 150 mg/L at 4 h; UK uses 100 mg/L at 4 h", "Give NAC"],
        ["Late presentation", "Over 8 hours after a toxic dose", "Start NAC immediately; do not wait for the level"],
        ["Staggered or unknown time", "Nomogram cannot be used", "Treat with NAC; check ALT and INR"],
        ["21-hour NAC regimen", "150 mg/kg over 1 h, then 50 mg/kg over 4 h, then 100 mg/kg over 16 h", "Standard three-bag regimen"],
        ["12-hour SNAP regimen", "100 mg/kg over 2 h, then 200 mg/kg over 10 h", "Fewer anaphylactoid reactions"],
      ],
    },
    {
      heading: "King's College criteria for transplant in acute liver failure (Sleisenger 11e 2021)",
      columns: ["Criterion", "Definition", "Meaning"],
      rows: [
        ["Paracetamol - pH", "Arterial pH under 7.30 after fluid resuscitation", "Alone meets criteria - list for transplant"],
        ["Paracetamol - triad", "INR over 6.5 and creatinine over 3.4 mg/dL and grade III-IV encephalopathy within 24 h", "All three together meet criteria"],
        ["Paracetamol - lactate", "Lactate over 3.5 mmol/L at 4 h or over 3.0 after resuscitation", "Modified criteria add sensitivity"],
        ["Non-paracetamol - INR", "INR over 6.5", "Alone meets criteria"],
        ["Non-paracetamol - any 3", "Age under 10 or over 40, drug or indeterminate cause, jaundice to HE over 7 days", "Any three of these five meet criteria"],
        ["Non-paracetamol - labs", "INR over 3.5, bilirubin over 17.5 mg/dL", "Count towards the three"],
      ],
    },
    {
      heading: "Snakebite envenomation - syndromic classification (India national protocol 2017)",
      columns: ["Syndrome", "Likely snake", "Features", "Key treatment"],
      rows: [
        ["Haemotoxic (vasculotoxic)", "Russell's viper, saw-scaled viper", "Progressive swelling, bleeding gums, 20WBCT non-clotting", "ASV; repeat 20WBCT 6-hourly and repeat ASV if non-clotting"],
        ["Haemotoxic with AKI", "Russell's viper", "Oliguria, haemoglobinuria, rising creatinine", "ASV plus early dialysis"],
        ["Neuroparalytic with local swelling", "Cobra", "Painful swelling, ptosis, ophthalmoplegia, bulbar palsy", "ASV; neostigmine with atropine trial; ventilate if needed"],
        ["Neuroparalytic, minimal local signs", "Common krait", "Night bite while sleeping on floor, abdominal pain, descending paralysis", "ASV and ventilation; neostigmine less effective"],
        ["Haemotoxic, not covered by ASV", "Hump-nosed pit viper (Western Ghats)", "Local swelling, coagulopathy, AKI", "Polyvalent ASV ineffective; supportive care, FFP, dialysis"],
        ["Dry bite", "Any", "No local or systemic signs after 24 h observation", "No ASV"],
      ],
    },
    {
      heading: "Criteria for antisnake venom in snakebite (WHO SEARO 2016, India protocol 2017)",
      columns: ["Criterion", "Definition", "Note"],
      rows: [
        ["Systemic - haemostatic", "Spontaneous bleeding or 20WBCT non-clotting", "Initial ASV 8-10 vials IV over 1 hour; same dose in children"],
        ["Systemic - neurotoxic", "Ptosis, ophthalmoplegia, bulbar or respiratory paralysis", "Airway and ventilation first"],
        ["Systemic - cardiovascular", "Hypotension, shock, arrhythmia or abnormal ECG", "Treat shock alongside ASV"],
        ["Systemic - renal", "Oliguria or anuria, rising creatinine, dark urine", "Monitor urine output hourly"],
        ["Local - extent", "Swelling over half the bitten limb within 48 h, or rapid extension", "Without tourniquet"],
        ["Local - digits and nodes", "Swelling after bites on digits, or enlarged tender draining lymph node", "Indicates spreading venom"],
      ],
    },
    {
      heading: "Zargar endoscopic grading of corrosive injury (Sleisenger 11e 2021)",
      columns: ["Grade", "Endoscopic finding", "Prognosis and management"],
      rows: [
        ["Grade 0", "Normal mucosa", "Discharge when eating"],
        ["Grade 1", "Oedema and hyperaemia", "Oral feeding in 24-48 h; no stricture"],
        ["Grade 2a", "Friability, haemorrhage, erosions, blisters, exudate, superficial ulcers", "Excellent recovery; stricture uncommon"],
        ["Grade 2b", "Grade 2a plus deep discrete or circumferential ulceration", "High stricture risk; nasogastric tube feeding, dilatation later"],
        ["Grade 3a", "Small scattered areas of necrosis (brown-black or grey)", "High stricture risk; ICU observation"],
        ["Grade 3b", "Extensive necrosis", "Perforation and death risk; consider emergency surgery"],
      ],
    },
  ],
  "emergency-burns": [
    {
      heading: "Burn depth classification (Bailey and Love 28e 2023)",
      columns: ["Depth", "Appearance", "Sensation and blanching", "Healing"],
      rows: [
        ["Superficial (epidermal)", "Red, dry, no blisters", "Painful; blanches", "5-7 days, no scar; not counted in TBSA"],
        ["Superficial partial thickness", "Pink, moist, blisters", "Very painful; brisk blanching", "Within 2 weeks, minimal scarring"],
        ["Deep partial thickness", "Blotchy red and white, fixed staining", "Reduced sensation; sluggish or no blanching", "Over 3 weeks with hypertrophic scar; usually excise and graft"],
        ["Full thickness", "White, waxy, leathery or charred", "Insensate; no blanching", "Only from edges; excision and grafting"],
        ["Fourth degree", "Extends to fat, muscle or bone", "Insensate", "Reconstruction or amputation"],
      ],
    },
    {
      heading: "Wallace rule of nines scale for TBSA in adults and infants (Bailey and Love 28e 2023)",
      columns: ["Region", "Adult (% TBSA)", "Infant (% TBSA)"],
      rows: [
        ["Head and neck", "9", "18"],
        ["Each upper limb", "9", "9"],
        ["Front of trunk", "18", "18"],
        ["Back of trunk", "18", "18"],
        ["Each lower limb", "18", "14"],
        ["Perineum", "1", "-"],
        ["Age adjustment", "-", "After age 1, head minus 1% and each leg plus 0.5% per year until adult values"],
        ["Palm with fingers", "About 1%", "About 1% - for small or patchy burns"],
      ],
    },
    {
      heading: "Lund and Browder chart - age-varying areas scale (% TBSA) (Bailey and Love 28e 2023)",
      columns: ["Age", "Half of head (A)", "Half of one thigh (B)", "Half of one lower leg (C)"],
      rows: [
        ["Birth", "9.5", "2.75", "2.5"],
        ["1 year", "8.5", "3.25", "2.5"],
        ["5 years", "6.5", "4", "2.75"],
        ["10 years", "5.5", "4.5", "3"],
        ["15 years", "4.5", "4.5", "3.25"],
        ["Adult", "3.5", "4.75", "3.5"],
      ],
    },
    {
      heading: "Burn resuscitation formula types and targets (ATLS 11e 2025)",
      columns: ["Formula", "Fluid in first 24 hours", "Rate", "Target urine output"],
      rows: [
        ["ATLS adult thermal", "Ringer lactate 2 mL x kg x % TBSA (partial plus full thickness)", "Half in first 8 h from time of burn, half over next 16 h", "0.5 mL/kg/h (30-50 mL/h)"],
        ["ATLS child (14 years or under)", "Ringer lactate 3 mL x kg x % TBSA plus dextrose maintenance if small", "Half in first 8 h, half over next 16 h", "1 mL/kg/h if under 30 kg"],
        ["ATLS electrical injury", "Ringer lactate 4 mL x kg x % TBSA", "Half in first 8 h", "1-1.5 mL/kg/h until urine clears"],
        ["Parkland", "Ringer lactate 4 mL x kg x % TBSA", "Half in first 8 h, half over next 16 h", "0.5-1 mL/kg/h"],
        ["Modified Brooke", "Ringer lactate 2 mL x kg x % TBSA", "Half in first 8 h", "0.5 mL/kg/h"],
        ["Muir and Barclay (colloid)", "0.5 mL x kg x % TBSA per period", "Periods of 4, 4, 4, 6, 6 and 12 h", "0.5 mL/kg/h"],
      ],
    },
    {
      heading: "Burn centre referral criteria (ABA, ATLS 11e 2025)",
      columns: ["Criterion", "Definition", "Note"],
      rows: [
        ["Extent", "Partial thickness burns over 10% TBSA", "Formal IV resuscitation above 15% adult, 10% child"],
        ["Special areas", "Face, hands, feet, genitalia, perineum or major joints", "Function and cosmesis at stake"],
        ["Depth", "Full thickness burns in any age group", "Will need excision and grafting"],
        ["Mechanism - electrical", "Electrical burns including lightning", "Deep injury, arrhythmia, rhabdomyolysis"],
        ["Mechanism - chemical", "Chemical burns", "Copious irrigation first"],
        ["Inhalation injury", "Suspected or proven smoke or airway burn", "Early intubation if stridor, hoarseness, soot"],
        ["Comorbidity", "Pre-existing disease that may complicate care or recovery", "E.g. diabetes, cardiac, renal disease"],
        ["Concomitant trauma", "Burn with fractures or other injury where burn poses greatest risk", "Stabilise trauma first if it is the bigger threat"],
        ["Children and social", "Children in centres without paediatric burn care; abuse; rehabilitation needs", "Consider non-accidental injury"],
      ],
    },
  ],
  "emergency-anaphylaxis": [
    {
      heading: "WAO 2020 clinical criteria for diagnosing anaphylaxis (World Allergy Organization)",
      columns: ["Criterion", "Definition", "Note"],
      rows: [
        ["Criterion 1", "Acute onset (minutes to hours) of skin and/or mucosal involvement plus at least one of the below", "Hives, itch, flush, swollen lips-tongue-uvula"],
        ["1a - respiratory", "Dyspnoea, wheeze, stridor, reduced PEF, hypoxaemia", "Respiratory compromise"],
        ["1b - circulatory", "Reduced BP or end-organ dysfunction (collapse, syncope, incontinence)", "Cardiovascular compromise"],
        ["1c - gastrointestinal", "Severe cramping abdominal pain or repetitive vomiting", "Especially after non-food allergens"],
        ["Criterion 2", "Acute hypotension, bronchospasm or laryngeal involvement after a known or likely allergen", "Skin involvement not required"],
        ["Hypotension definition", "Adult SBP under 90 mmHg or over 30% fall; child low age-specific SBP", "Treat with IM adrenaline 0.01 mg/kg (max 0.5 mg)"],
      ],
    },
    {
      heading: "Brown grading of severity of generalised hypersensitivity reactions (Tintinalli 9e 2020)",
      columns: ["Grade", "Defined by", "Features"],
      rows: [
        ["Mild (skin only)", "Skin and subcutaneous tissue only", "Generalised erythema, urticaria, periorbital oedema, angioedema"],
        ["Moderate", "Respiratory, cardiovascular or gut involvement", "Dyspnoea, stridor, wheeze, vomiting, presyncope, sweating, chest or throat tightness"],
        ["Severe", "Hypoxia, hypotension or neurological compromise", "Cyanosis or SpO2 92% or less, SBP under 90 mmHg, confusion, collapse, incontinence"],
      ],
    },
  ],
  "emergency-cardiac-arrest": [
    {
      heading: "Cerebral Performance Category scale after cardiac arrest (ERC/ILCOR 2025)",
      columns: ["Category", "Definition", "Outcome group"],
      rows: [
        ["CPC 1", "Good cerebral performance; conscious, able to work, may have mild deficit", "Good outcome"],
        ["CPC 2", "Moderate disability; conscious, independent in daily activities", "Good outcome"],
        ["CPC 3", "Severe disability; conscious but dependent on others", "Poor outcome"],
        ["CPC 4", "Coma or vegetative state", "Poor outcome"],
        ["CPC 5", "Brain death (or death)", "Poor outcome"],
      ],
    },
  ],
  "emergency-tray-and-readiness": [
    {
      heading: "Manchester Triage System priority classification (Tintinalli 9e 2020)",
      columns: ["Category", "Name", "Maximum time to doctor", "Example"],
      rows: [
        ["Red (1)", "Immediate", "0 minutes", "Airway compromise, shock, unresponsive child, active seizure"],
        ["Orange (2)", "Very urgent", "10 minutes", "Severe pain, cardiac chest pain, altered consciousness"],
        ["Yellow (3)", "Urgent", "60 minutes", "Moderate pain, persistent vomiting, hot adult"],
        ["Green (4)", "Standard", "120 minutes", "Mild pain, minor injury, recent problem"],
        ["Blue (5)", "Non-urgent", "240 minutes", "Chronic problem, no acute features"],
      ],
    },
    {
      heading: "Emergency Severity Index (ESI) five-level triage (Tintinalli 9e 2020)",
      columns: ["Level", "Decision point", "Example"],
      rows: [
        ["ESI 1", "Needs immediate life-saving intervention", "Cardiac arrest, intubation needed, severe shock"],
        ["ESI 2", "High-risk situation, new confusion or lethargy, or severe pain or distress", "Chest pain suggesting ACS, stroke symptoms"],
        ["ESI 3", "Needs two or more resources (labs, imaging, IV fluids, specialist)", "Abdominal pain needing bloods and CT; up-triage if danger-zone vitals"],
        ["ESI 4", "Needs one resource", "Simple laceration needing sutures, ankle X-ray"],
        ["ESI 5", "Needs no resources", "Prescription refill, minor rash"],
      ],
    },
  ],
  "emergency-ards": [
    {
      heading: "Murray Lung Injury Score (ELSO, Harrison 22e 2025)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Chest X-ray consolidation", "None", "0"],
        ["Chest X-ray consolidation", "One quadrant", "1"],
        ["Chest X-ray consolidation", "Two quadrants", "2"],
        ["Chest X-ray consolidation", "Three quadrants", "3"],
        ["Chest X-ray consolidation", "Four quadrants", "4"],
        ["PaO2/FiO2 (mmHg)", "300 or more", "0"],
        ["PaO2/FiO2 (mmHg)", "225-299", "1"],
        ["PaO2/FiO2 (mmHg)", "175-224", "2"],
        ["PaO2/FiO2 (mmHg)", "100-174", "3"],
        ["PaO2/FiO2 (mmHg)", "Under 100", "4"],
        ["PEEP (cm H2O)", "5 or less", "0"],
        ["PEEP (cm H2O)", "6-8", "1"],
        ["PEEP (cm H2O)", "9-11", "2"],
        ["PEEP (cm H2O)", "12-14", "3"],
        ["PEEP (cm H2O)", "15 or more", "4"],
        ["Static compliance (mL/cm H2O)", "80 or more", "0"],
        ["Static compliance (mL/cm H2O)", "60-79", "1"],
        ["Static compliance (mL/cm H2O)", "40-59", "2"],
        ["Static compliance (mL/cm H2O)", "20-39", "3"],
        ["Static compliance (mL/cm H2O)", "19 or less", "4"],
      ],
    },
    {
      heading: "Murray Lung Injury Score - interpretation (ELSO, Harrison 22e 2025)",
      columns: ["Final score", "Meaning", "Action"],
      rows: [
        ["Calculation", "Sum of points divided by the number of components used", "Range 0-4"],
        ["0", "No lung injury", "-"],
        ["0.1-2.5", "Mild to moderate lung injury", "Lung-protective ventilation"],
        ["Over 2.5", "Severe lung injury (ARDS)", "Prone position, consider neuromuscular blockade"],
        ["3 or more", "Severe refractory hypoxaemia", "Refer for ECMO consideration (CESAR criterion)"],
      ],
    },
  ],
};

export default scores;
