import type { NoteTable } from "../../lib/types";

const scores: Record<string, NoteTable[]> = {
  "gastro-hepatology-acid-peptic-gerd": [
    {
      heading: "Los Angeles classification of reflux oesophagitis (Lyon consensus 2.0, 2023)",
      columns: ["Grade", "Endoscopic finding", "Meaning"],
      rows: [
        ["LA grade A", "One or more mucosal breaks 5 mm or less, not extending between the tops of two folds", "Not conclusive for GERD on its own - needs pH study if doubt"],
        ["LA grade B", "One or more mucosal breaks longer than 5 mm, not continuous between the tops of two folds", "Conclusive evidence of GERD (Lyon 2.0)"],
        ["LA grade C", "Mucosal breaks continuous between the tops of two or more folds, less than 75 percent of circumference", "Conclusive GERD; heal with 8 weeks double-dose PPI, repeat scope"],
        ["LA grade D", "Mucosal breaks involving 75 percent or more of the oesophageal circumference", "Conclusive GERD; repeat scope after healing to exclude Barrett"],
      ],
    },
    {
      heading: "Prague C and M criteria for grading Barrett oesophagus (ACG 2022)",
      columns: ["Element", "Definition", "Clinical use"],
      rows: [
        ["Landmark - GOJ", "Proximal end of the gastric folds", "All lengths are measured from this point"],
        ["C value", "Circumferential extent of columnar mucosa above the GOJ in cm", "Written first, e.g. C2M5"],
        ["M value", "Maximum extent of columnar mucosa including tongues, in cm", "Always equal to or longer than C"],
        ["Minimum length", "Columnar lining at least 1 cm with intestinal metaplasia on biopsy", "Less than 1 cm is irregular Z-line - no surveillance"],
        ["Short-segment Barrett", "Maximum extent less than 3 cm", "Non-dysplastic: surveillance endoscopy every 5 years"],
        ["Long-segment Barrett", "Maximum extent 3 cm or more", "Non-dysplastic: surveillance endoscopy every 3 years"],
      ],
    },
    {
      heading: "Hiatus hernia types I to IV (Bailey and Love 28e 2023)",
      columns: ["Type", "Anatomy", "Clinical point"],
      rows: [
        ["Type I - sliding", "GOJ slides up into the chest through the hiatus", "About 95 percent; causes reflux; PPI, surgery rarely"],
        ["Type II - para-oesophageal", "GOJ stays in place; fundus herniates alongside the oesophagus", "Risk of volvulus and strangulation; repair if symptomatic"],
        ["Type III - mixed", "Both GOJ and fundus herniate into the chest", "Commonest para-oesophageal form; same risks as type II"],
        ["Type IV - complex", "Another organ (colon, spleen, small bowel) herniates as well", "Large defect; elective surgical repair"],
      ],
    },
    {
      heading: "Johnson classification of gastric ulcer types (Sabiston 22e 2025)",
      columns: ["Type", "Site", "Acid secretion", "Surgical note"],
      rows: [
        ["Type I", "Lesser curve at the incisura (body)", "Normal or low", "Commonest; distal gastrectomy with ulcer if refractory"],
        ["Type II", "Gastric body ulcer with a duodenal ulcer", "High", "Behaves like duodenal ulcer disease"],
        ["Type III", "Prepyloric", "High", "Behaves like duodenal ulcer disease"],
        ["Type IV", "High on the lesser curve near the GOJ", "Normal or low", "Difficult resection; biopsy to exclude cancer"],
        ["Type V", "Anywhere in the stomach", "Variable", "Drug induced - NSAID or aspirin"],
      ],
    },
  ],
  "gastro-hepatology-acute-diarrhoea": [
    {
      heading: "Travellers' diarrhoea severity grading (ISTM expert consensus 2017)",
      columns: ["Severity", "Definition", "Treatment"],
      rows: [
        ["Mild", "Tolerable, not distressing, does not interfere with planned activities", "Fluids; loperamide or bismuth subsalicylate; no antibiotic"],
        ["Moderate", "Distressing or interferes with planned activities", "Loperamide; antibiotic may be used (azithromycin or a quinolone)"],
        ["Severe", "Incapacitating or completely prevents planned activities; all dysentery", "Antibiotic - azithromycin preferred; loperamide as adjunct"],
      ],
    },
    {
      heading: "Clostridioides difficile infection severity (IDSA/SHEA 2021)",
      columns: ["Severity", "Criteria", "First-line treatment"],
      rows: [
        ["Non-severe", "WBC 15,000/mm3 or less and creatinine below 1.5 mg/dL", "Fidaxomicin 200 mg twice daily 10 days, or oral vancomycin 125 mg four times daily"],
        ["Severe", "WBC above 15,000/mm3 or creatinine above 1.5 mg/dL", "Fidaxomicin or oral vancomycin 125 mg four times daily for 10 days"],
        ["Fulminant", "Hypotension or shock, ileus or megacolon", "Oral vancomycin 500 mg four times daily plus IV metronidazole; surgical review"],
      ],
    },
  ],
  "gastro-hepatology-viral-hepatitis": [
    {
      heading: "Chronic hepatitis B phases - classification (EASL 2017 nomenclature)",
      columns: ["Phase", "HBeAg and HBV DNA", "ALT and liver disease", "Old term"],
      rows: [
        ["HBeAg-positive chronic infection", "HBeAg positive; DNA very high, often above 10^7 IU/mL", "Persistently normal ALT; none or minimal", "Immune tolerant"],
        ["HBeAg-positive chronic hepatitis", "HBeAg positive; DNA high, 10^4 to 10^7 IU/mL", "Raised ALT; moderate or severe inflammation", "Immune reactive"],
        ["HBeAg-negative chronic infection", "Anti-HBe positive; DNA below 2000 IU/mL", "Normal ALT; none", "Inactive carrier"],
        ["HBeAg-negative chronic hepatitis", "Anti-HBe positive; DNA above 2000 IU/mL, fluctuating", "Raised or fluctuating ALT; moderate or severe", "HBeAg-negative CHB"],
        ["HBsAg-negative phase", "HBsAg negative, anti-HBc positive; DNA usually undetectable", "Normal ALT; reactivation risk on immunosuppression", "Occult HBV infection"],
      ],
    },
    {
      heading: "O'Grady classification of acute liver failure (EASL 2017 ALF CPG)",
      columns: ["Class", "Jaundice to encephalopathy interval", "Typical cause and prognosis"],
      rows: [
        ["Hyperacute", "7 days or less", "Paracetamol, hepatitis A or E; cerebral oedema common but best spontaneous survival"],
        ["Acute", "8 to 28 days", "Hepatitis B; intermediate prognosis"],
        ["Subacute", "29 days to 12 weeks", "Drug-induced, seronegative; little cerebral oedema but worst spontaneous survival"],
      ],
    },
    {
      heading: "King's College criteria for liver transplant in acute liver failure (EASL 2017)",
      columns: ["Criterion", "Paracetamol-induced ALF", "Non-paracetamol ALF"],
      rows: [
        ["Stand-alone criterion", "Arterial pH below 7.30 after resuscitation, or lactate above 3.0 mmol/L after fluids", "INR above 6.5 (PT above 100 s) irrespective of HE grade"],
        ["Combined criterion", "All three in 24 h: INR above 6.5, creatinine above 3.4 mg/dL, grade III-IV encephalopathy", "Any 3 of the 5 features listed below"],
        ["Feature - age", "Not applicable", "Age below 10 or above 40 years"],
        ["Feature - aetiology", "Not applicable", "Non-A non-B hepatitis, halothane or idiosyncratic drug reaction"],
        ["Feature - tempo", "Not applicable", "Jaundice to encephalopathy more than 7 days"],
        ["Feature - INR", "Not applicable", "INR above 3.5 (PT above 50 s)"],
        ["Feature - bilirubin", "Not applicable", "Serum bilirubin above 17.5 mg/dL (300 micromol/L)"],
      ],
    },
  ],
  "gastro-hepatology-chronic-liver-disease": [
    {
      heading: "MELD 3.0 score variables and bounds for transplant listing (OPTN 2023)",
      columns: ["Variable", "How it enters the score", "Bounds and notes"],
      rows: [
        ["Female sex", "Adds 1.33 points", "Corrects the under-ranking of women by creatinine"],
        ["Bilirubin (mg/dL)", "4.56 x ln(bilirubin)", "Values below 1.0 are set to 1.0"],
        ["Sodium (mmol/L)", "0.82 x (137 - Na), minus an interaction with bilirubin", "Capped between 125 and 137"],
        ["INR", "9.09 x ln(INR)", "Values below 1.0 are set to 1.0"],
        ["Creatinine (mg/dL)", "11.14 x ln(creatinine)", "Range 1.0 to 3.0; set to 3.0 if dialysed twice in the past week"],
        ["Albumin (g/dL)", "1.85 x (3.5 - albumin), minus an interaction with creatinine", "Capped between 1.5 and 3.5"],
        ["Constant", "Plus 6; score rounded, range 6 to 40", "Used in the US since 2023; MELD-Na elsewhere"],
      ],
    },
    {
      heading: "MELD score bands and 90-day mortality (Sleisenger 11e 2021)",
      columns: ["MELD band", "Approximate 3-month mortality", "Action"],
      rows: [
        ["Below 10", "About 2 percent", "Outpatient care; elective surgery possible with caution"],
        ["10 to 14", "About 6 percent", "Consider hepatology referral"],
        ["15 or more", "Rising - survival benefit from transplant begins", "Refer for liver transplant evaluation"],
        ["20 to 29", "About 20 percent", "Transplant listing; alcoholic hepatitis above 20 is severe"],
        ["30 to 39", "About 50 percent", "High priority on the waiting list"],
        ["40", "About 70 percent", "Highest priority; often ICU care"],
      ],
    },
    {
      heading: "West Haven criteria for grading hepatic encephalopathy (EASL 2022 HE CPG)",
      columns: ["Grade", "Clinical features", "ISHEN category"],
      rows: [
        ["Unimpaired", "No encephalopathy, no history of HE", "None"],
        ["Minimal", "Only psychometric or neurophysiological abnormality; no clinical change", "Covert HE"],
        ["Grade 1", "Trivial lack of awareness, euphoria or anxiety, short attention, impaired arithmetic, sleep reversal", "Covert HE"],
        ["Grade 2", "Lethargy, disorientation for time, personality change, inappropriate behaviour, asterixis", "Overt HE"],
        ["Grade 3", "Somnolence to semi-stupor, responds to stimuli, confused, gross disorientation, bizarre behaviour", "Overt HE"],
        ["Grade 4", "Coma - no response to pain", "Overt HE"],
      ],
    },
    {
      heading: "Types of hepatic encephalopathy by underlying disease (EASL 2022 HE CPG)",
      columns: ["Type", "Underlying disease", "Comment"],
      rows: [
        ["Type A", "Acute liver failure", "Cerebral oedema and raised ICP are the threat"],
        ["Type B", "Portosystemic bypass or shunt without intrinsic liver disease", "Congenital or TIPS-like shunts, normal liver"],
        ["Type C", "Cirrhosis with or without portosystemic shunts", "Commonest; episodic, recurrent or persistent"],
      ],
    },
    {
      heading: "International Club of Ascites grading of ascites (EASL 2018 decompensated cirrhosis)",
      columns: ["Grade", "Definition", "Treatment"],
      rows: [
        ["Grade 1 - mild", "Detectable only by ultrasound", "No specific treatment"],
        ["Grade 2 - moderate", "Moderate symmetrical distension of the abdomen", "Salt restriction 80 to 120 mmol/day and diuretics"],
        ["Grade 3 - large", "Marked abdominal distension", "Large-volume paracentesis with albumin 8 g/L removed, then diuretics"],
        ["Refractory - diuretic resistant", "No response to maximal diuretics (spironolactone 400, furosemide 160 mg) and salt restriction", "Serial LVP, TIPS, transplant assessment"],
        ["Refractory - diuretic intractable", "Diuretic complications prevent effective dosing", "Serial LVP, TIPS, transplant assessment"],
      ],
    },
    {
      heading: "SAAG classification of ascites (AASLD 2021 ascites guidance)",
      columns: ["Class", "Ascitic fluid findings", "Causes"],
      rows: [
        ["High SAAG, protein below 2.5 g/dL", "SAAG 1.1 g/dL or more - portal hypertension", "Cirrhosis, late Budd-Chiari, massive liver metastases"],
        ["High SAAG, protein 2.5 g/dL or more", "SAAG 1.1 g/dL or more - portal hypertension", "Cardiac ascites, early Budd-Chiari, sinusoidal obstruction syndrome"],
        ["Low SAAG - malignant or infective", "SAAG below 1.1 g/dL - no portal hypertension", "Peritoneal carcinomatosis, tuberculous peritonitis, pancreatic ascites"],
        ["Low SAAG - other causes", "SAAG below 1.1 g/dL - no portal hypertension", "Nephrotic syndrome, serositis, bowel obstruction or infarction"],
      ],
    },
    {
      heading: "Classification of ascitic fluid infection (AASLD 2021 ascites guidance)",
      columns: ["Type", "PMN count and culture", "Management"],
      rows: [
        ["Spontaneous bacterial peritonitis", "PMN 250/mm3 or more; single organism on culture", "Cefotaxime or ceftriaxone plus albumin 1.5 g/kg day 1, 1 g/kg day 3"],
        ["Culture-negative neutrocytic ascites", "PMN 250/mm3 or more; culture negative", "Treat exactly as SBP"],
        ["Monomicrobial bacterascites", "PMN below 250/mm3; single organism grows", "Treat if symptomatic; otherwise repeat tap"],
        ["Secondary bacterial peritonitis", "PMN 250 or more, polymicrobial, 2 of: protein above 1 g/dL, glucose below 50, high LDH", "Urgent CT; broad-spectrum antibiotics and surgical source control"],
      ],
    },
    {
      heading: "ICA-AKI staging of acute kidney injury in cirrhosis (EASL 2018)",
      columns: ["Stage", "Serum creatinine criterion", "Action"],
      rows: [
        ["Stage 1A", "Rise 0.3 mg/dL or more in 48 h, or 1.5 to 2 times baseline; creatinine below 1.5 mg/dL", "Stop diuretics, NSAIDs, nephrotoxins; treat triggers; monitor"],
        ["Stage 1B", "As stage 1 but creatinine 1.5 mg/dL or more", "Albumin 1 g/kg for 2 days after withdrawing diuretics"],
        ["Stage 2", "Creatinine 2 to 3 times baseline", "Albumin 1 g/kg for 2 days; assess for HRS-AKI"],
        ["Stage 3", "Above 3 times baseline, or 4.0 mg/dL or more with acute rise 0.3, or on RRT", "Albumin challenge; if HRS-AKI terlipressin plus albumin"],
      ],
    },
    {
      heading: "HRS-AKI diagnostic criteria in cirrhosis (EASL 2018 decompensated cirrhosis)",
      columns: ["Criterion", "Requirement"],
      rows: [
        ["Criterion 1", "Cirrhosis with ascites"],
        ["Criterion 2", "AKI by ICA-AKI criteria"],
        ["Criterion 3", "No response after 2 consecutive days of diuretic withdrawal and albumin 1 g/kg"],
        ["Criterion 4", "Absence of shock"],
        ["Criterion 5", "No current or recent nephrotoxic drugs (NSAIDs, aminoglycosides, iodinated contrast)"],
        ["Criterion 6", "No structural kidney injury: proteinuria below 500 mg/day, below 50 RBC/hpf, normal renal ultrasound"],
      ],
    },
    {
      heading: "Baveno VII elastography criteria for cACLD and CSPH (Baveno VII 2022)",
      columns: ["Finding", "Meaning", "Action"],
      rows: [
        ["LSM below 10 kPa", "Rules out compensated advanced chronic liver disease", "Repeat periodically; treat cause"],
        ["LSM 10 to 15 kPa", "Suggestive of cACLD", "Refer to hepatology; further tests"],
        ["LSM above 15 kPa", "Highly suggestive of cACLD", "Hepatology care; HCC surveillance if cirrhosis"],
        ["LSM 25 kPa or more", "Rules in clinically significant portal hypertension", "Non-selective beta-blocker (carvedilol) to prevent decompensation"],
        ["LSM below 20 kPa, platelets above 150k", "Platelets above 150,000/mm3 - very low risk of varices needing treatment", "Screening endoscopy can be avoided"],
      ],
    },
    {
      heading: "Sarin classification of gastric varices (Sleisenger 11e 2021)",
      columns: ["Type", "Location", "Treatment point"],
      rows: [
        ["GOV1", "Oesophageal varices extending 2 to 5 cm below the GOJ along the lesser curve", "Commonest; managed like oesophageal varices (band ligation)"],
        ["GOV2", "Oesophageal varices extending towards the fundus", "Cyanoacrylate glue injection"],
        ["IGV1", "Isolated gastric varices in the fundus", "High bleed risk; glue, exclude splenic vein thrombosis"],
        ["IGV2", "Isolated ectopic varices in body, antrum or pylorus", "Rare; endoscopic or radiological therapy"],
      ],
    },
    {
      heading: "Glasgow alcoholic hepatitis score (ACG 2024 alcohol-associated liver disease)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Age", "Below 50 years", "1"],
        ["Age", "50 years or more", "2"],
        ["WBC (x10^9/L)", "Below 15", "1"],
        ["WBC (x10^9/L)", "15 or more", "2"],
        ["Urea (mmol/L)", "Below 5", "1"],
        ["Urea (mmol/L)", "5 or more", "2"],
        ["INR", "Below 1.5", "1"],
        ["INR", "1.5 to 2.0", "2"],
        ["INR", "Above 2.0", "3"],
        ["Bilirubin (micromol/L)", "Below 125", "1"],
        ["Bilirubin (micromol/L)", "125 to 250", "2"],
        ["Bilirubin (micromol/L)", "Above 250", "3"],
      ],
    },
    {
      heading: "Glasgow alcoholic hepatitis score - interpretation",
      columns: ["GAHS", "Meaning", "Action"],
      rows: [
        ["5 to 8", "Better prognosis", "Steroids give no survival benefit"],
        ["9 to 12", "Poor prognosis", "Prednisolone benefits if Maddrey DF is 32 or more"],
      ],
    },
    {
      heading: "Severity scores in alcohol-associated hepatitis (ACG 2024)",
      columns: ["Score", "Calculation", "Threshold and action"],
      rows: [
        ["Maddrey discriminant function", "4.6 x (patient PT - control PT, seconds) + bilirubin (mg/dL)", "32 or more is severe - prednisolone 40 mg daily for 28 days"],
        ["MELD", "Bilirubin, INR, creatinine", "Above 20 is severe - consider prednisolone"],
        ["Glasgow alcoholic hepatitis score", "Age, WBC, urea, INR, bilirubin (5 to 12)", "9 or more - poor prognosis, steroid benefit"],
        ["Lille score at day 7", "Age, albumin, creatinine, PT, bilirubin day 0 and day 7", "0.45 or more means non-response - stop steroids"],
      ],
    },
    {
      heading: "EASL-CLIF grades of acute-on-chronic liver failure (EASL 2023 ACLF CPG)",
      columns: ["Grade", "Organ failures (CLIF-C OF)", "28-day mortality"],
      rows: [
        ["No ACLF", "No organ failure, or single non-kidney failure with creatinine below 1.5 and no HE", "About 5 percent"],
        ["ACLF grade 1", "Single kidney failure, or single other failure with creatinine 1.5 to 1.9 or grade 1-2 HE", "About 22 percent"],
        ["ACLF grade 2", "Two organ failures", "About 32 percent"],
        ["ACLF grade 3", "Three or more organ failures", "About 77 percent - consider transplant or futility"],
      ],
    },
    {
      heading: "AARC score for ACLF severity (APASL ACLF consensus 2019)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Bilirubin (mg/dL)", "Below 15", "1"],
        ["Bilirubin (mg/dL)", "15 to 25", "2"],
        ["Bilirubin (mg/dL)", "Above 25", "3"],
        ["Hepatic encephalopathy", "None", "1"],
        ["Hepatic encephalopathy", "Grade I-II", "2"],
        ["Hepatic encephalopathy", "Grade III-IV", "3"],
        ["INR", "Below 1.8", "1"],
        ["INR", "1.8 to 2.5", "2"],
        ["INR", "Above 2.5", "3"],
        ["Lactate (mmol/L)", "Below 1.5", "1"],
        ["Lactate (mmol/L)", "1.5 to 2.5", "2"],
        ["Lactate (mmol/L)", "Above 2.5", "3"],
        ["Creatinine (mg/dL)", "Below 0.7", "1"],
        ["Creatinine (mg/dL)", "0.7 to 1.5", "2"],
        ["Creatinine (mg/dL)", "Above 1.5", "3"],
      ],
    },
    {
      heading: "AARC score grades of ACLF",
      columns: ["AARC score", "ACLF grade", "Meaning"],
      rows: [
        ["5 to 7", "Grade I", "Lowest mortality; standard medical therapy"],
        ["8 to 10", "Grade II", "Intermediate mortality; early transplant assessment"],
        ["11 to 15", "Grade III", "Highest mortality; transplant within the golden window if eligible"],
      ],
    },
  ],
  "gastro-hepatology-gi-bleeding": [
    {
      heading: "Rockall score for upper GI bleeding (Sleisenger 11e 2021)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Age", "Below 60 years", "0"],
        ["Age", "60 to 79 years", "1"],
        ["Age", "80 years or more", "2"],
        ["Shock", "No shock - SBP 100 mmHg or more, pulse below 100", "0"],
        ["Shock", "Tachycardia - pulse 100 or more, SBP 100 mmHg or more", "1"],
        ["Shock", "Hypotension - SBP below 100 mmHg", "2"],
        ["Comorbidity", "No major comorbidity", "0"],
        ["Comorbidity", "Cardiac failure, ischaemic heart disease, any major comorbidity", "2"],
        ["Comorbidity", "Renal failure, liver failure, disseminated malignancy", "3"],
        ["Endoscopic diagnosis", "Mallory-Weiss tear, or no lesion and no stigmata", "0"],
        ["Endoscopic diagnosis", "All other diagnoses", "1"],
        ["Endoscopic diagnosis", "Malignancy of the upper GI tract", "2"],
        ["Stigmata of recent haemorrhage", "None, or dark spot only", "0"],
        ["Stigmata of recent haemorrhage", "Blood in upper GI tract, adherent clot, visible or spurting vessel", "2"],
      ],
    },
    {
      heading: "Rockall score bands (pre-endoscopy 0-7, complete 0-11)",
      columns: ["Complete score", "Risk", "Action"],
      rows: [
        ["0 to 2", "Low - mortality about 0.2 percent or less, low rebleeding", "Early discharge after endoscopy"],
        ["3 to 4", "Intermediate - mortality about 3 to 5 percent", "Inpatient observation"],
        ["5 to 7", "High - mortality about 10 to 27 percent", "Close monitoring, HDU if unstable"],
        ["8 or more", "Very high - mortality about 40 percent, rebleeding about 40 percent", "HDU or ICU care"],
        ["Pre-endoscopy score 0", "Very low risk before endoscopy", "Consider outpatient management"],
      ],
    },
    {
      heading: "AIMS65 score for upper GI bleeding mortality (ACG 2021)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Albumin", "Below 3.0 g/dL", "1"],
        ["INR", "Above 1.5", "1"],
        ["Mental status", "Altered (GCS below 14, disorientation, lethargy)", "1"],
        ["Systolic BP", "90 mmHg or less", "1"],
        ["Age", "65 years or more", "1"],
      ],
    },
    {
      heading: "AIMS65 score bands and in-hospital mortality",
      columns: ["AIMS65", "Mortality", "Meaning"],
      rows: [
        ["0", "About 0.3 percent", "Low risk"],
        ["1", "About 1 percent", "Low risk"],
        ["2", "About 5 percent", "High risk - 2 or more flags high risk"],
        ["3", "About 10 percent", "High risk"],
        ["4", "About 16 percent", "High risk"],
        ["5", "About 25 percent", "Very high risk"],
      ],
    },
    {
      heading: "Oakland score for lower GI bleeding (BSG 2019 acute LGIB guideline)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Age", "Below 40 years", "0"],
        ["Age", "40 to 69 years", "1"],
        ["Age", "70 years or more", "2"],
        ["Sex", "Female", "0"],
        ["Sex", "Male", "1"],
        ["Previous LGIB admission", "No", "0"],
        ["Previous LGIB admission", "Yes", "1"],
        ["Digital rectal examination", "No blood", "0"],
        ["Digital rectal examination", "Blood", "1"],
        ["Heart rate (per minute)", "Below 70", "0"],
        ["Heart rate (per minute)", "70 to 89", "1"],
        ["Heart rate (per minute)", "90 to 109", "2"],
        ["Heart rate (per minute)", "110 or more", "3"],
        ["Systolic BP (mmHg)", "50 to 89", "5"],
        ["Systolic BP (mmHg)", "90 to 119", "4"],
        ["Systolic BP (mmHg)", "120 to 129", "3"],
        ["Systolic BP (mmHg)", "130 to 159", "2"],
        ["Systolic BP (mmHg)", "160 or more", "0"],
        ["Haemoglobin (g/L)", "36 to 69", "22"],
        ["Haemoglobin (g/L)", "70 to 89", "17"],
        ["Haemoglobin (g/L)", "90 to 109", "13"],
        ["Haemoglobin (g/L)", "110 to 129", "8"],
        ["Haemoglobin (g/L)", "130 to 159", "4"],
        ["Haemoglobin (g/L)", "160 or more", "0"],
      ],
    },
    {
      heading: "Oakland score interpretation",
      columns: ["Oakland score", "Meaning", "Action"],
      rows: [
        ["8 or less", "Minor bleed - about 95 percent chance of safe discharge", "Discharge for urgent outpatient colonoscopy if no other reason to admit"],
        ["Above 8", "Major bleed", "Admit; if unstable (shock index above 1) CT angiography first"],
      ],
    },
  ],
  "gastro-hepatology-ibs-constipation": [
    {
      heading: "Boston Bowel Preparation Scale for colonoscopy (ESGE 2019 bowel prep)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Right colon", "Unprepared - mucosa not seen due to solid stool that cannot be cleared", "0"],
        ["Right colon", "Part of mucosa seen; other areas obscured by staining, residual stool or opaque liquid", "1"],
        ["Right colon", "Minor residual staining or small stool fragments; mucosa well seen", "2"],
        ["Right colon", "Entire mucosa well seen, no residual staining or stool", "3"],
        ["Transverse colon", "Unprepared - mucosa not seen due to solid stool that cannot be cleared", "0"],
        ["Transverse colon", "Part of mucosa seen; other areas obscured by staining, residual stool or opaque liquid", "1"],
        ["Transverse colon", "Minor residual staining or small stool fragments; mucosa well seen", "2"],
        ["Transverse colon", "Entire mucosa well seen, no residual staining or stool", "3"],
        ["Left colon and rectum", "Unprepared - mucosa not seen due to solid stool that cannot be cleared", "0"],
        ["Left colon and rectum", "Part of mucosa seen; other areas obscured by staining, residual stool or opaque liquid", "1"],
        ["Left colon and rectum", "Minor residual staining or small stool fragments; mucosa well seen", "2"],
        ["Left colon and rectum", "Entire mucosa well seen, no residual staining or stool", "3"],
      ],
    },
    {
      heading: "Boston Bowel Preparation Scale - interpretation",
      columns: ["Total BBPS", "Meaning", "Action"],
      rows: [
        ["6 to 9 with every segment 2 or more", "Adequate preparation", "Follow the standard surveillance interval"],
        ["Below 6, or any segment below 2", "Inadequate preparation", "Repeat colonoscopy within 1 year with intensified preparation"],
      ],
    },
    {
      heading: "Mayo score for ulcerative colitis activity (ACG 2025 UC guideline)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Stool frequency", "Normal number for the patient", "0"],
        ["Stool frequency", "1 to 2 stools more than normal", "1"],
        ["Stool frequency", "3 to 4 stools more than normal", "2"],
        ["Stool frequency", "5 or more stools more than normal", "3"],
        ["Rectal bleeding", "None", "0"],
        ["Rectal bleeding", "Streaks of blood with stool less than half the time", "1"],
        ["Rectal bleeding", "Obvious blood with stool most of the time", "2"],
        ["Rectal bleeding", "Blood alone passed", "3"],
        ["Endoscopic findings", "Normal or inactive disease", "0"],
        ["Endoscopic findings", "Mild - erythema, decreased vascular pattern, mild friability", "1"],
        ["Endoscopic findings", "Moderate - marked erythema, absent vascular pattern, friability, erosions", "2"],
        ["Endoscopic findings", "Severe - spontaneous bleeding, ulceration", "3"],
        ["Physician global assessment", "Normal", "0"],
        ["Physician global assessment", "Mild disease", "1"],
        ["Physician global assessment", "Moderate disease", "2"],
        ["Physician global assessment", "Severe disease", "3"],
      ],
    },
    {
      heading: "Mayo score bands for ulcerative colitis",
      columns: ["Total Mayo (0-12)", "Activity", "Note"],
      rows: [
        ["0 to 2, no subscore above 1", "Clinical remission", "Mucosal healing if endoscopic subscore 0 or 1"],
        ["3 to 5", "Mild activity", "Oral and topical 5-ASA"],
        ["6 to 10", "Moderate activity", "Steroids, then advanced therapy if dependent"],
        ["11 to 12", "Severe activity", "Admit if Truelove-Witts criteria met"],
      ],
    },
    {
      heading: "Truelove and Witts severity criteria for ulcerative colitis (BSG 2019 IBD)",
      columns: ["Severity", "Stool and blood", "Systemic features"],
      rows: [
        ["Mild", "Fewer than 4 stools a day, small amounts of blood", "No fever, pulse below 90, no anaemia, normal ESR"],
        ["Moderate", "4 to 6 stools a day, moderate blood", "Between mild and severe; minimal toxicity"],
        ["Acute severe", "6 or more bloody stools a day", "Plus one of: pulse above 90, temp above 37.8 C, Hb below 10.5 g/dL, ESR above 30 or CRP above 30"],
      ],
    },
    {
      heading: "Montreal classification of Crohn disease (ECCO 2024 Crohn guideline)",
      columns: ["Class", "Definition", "Group"],
      rows: [
        ["A1", "Diagnosed at 16 years or younger", "Age at diagnosis"],
        ["A2", "Diagnosed at 17 to 40 years", "Age at diagnosis"],
        ["A3", "Diagnosed above 40 years", "Age at diagnosis"],
        ["L1", "Terminal ileum", "Location"],
        ["L2", "Colon", "Location"],
        ["L3", "Ileocolon", "Location"],
        ["L4", "Isolated upper GI disease - modifier added to L1-L3", "Location"],
        ["B1", "Non-stricturing, non-penetrating (inflammatory)", "Behaviour"],
        ["B2", "Stricturing", "Behaviour"],
        ["B3", "Penetrating (fistulising)", "Behaviour"],
        ["p", "Perianal disease modifier, added to B1-B3", "Behaviour"],
      ],
    },
    {
      heading: "Montreal classification of ulcerative colitis extent and severity (ECCO 2022)",
      columns: ["Class", "Definition", "Group"],
      rows: [
        ["E1 - proctitis", "Involvement limited to the rectum", "Extent"],
        ["E2 - left-sided", "Distal to the splenic flexure", "Extent"],
        ["E3 - extensive", "Proximal to the splenic flexure (pancolitis)", "Extent"],
        ["S0", "Clinical remission - asymptomatic", "Severity"],
        ["S1 - mild", "4 or fewer stools a day with or without blood, no systemic illness, normal markers", "Severity"],
        ["S2 - moderate", "More than 4 stools a day but minimal signs of systemic toxicity", "Severity"],
        ["S3 - severe", "6 or more bloody stools, pulse 90 or more, temp 37.5 C or more, Hb below 10.5, ESR 30 or more", "Severity"],
      ],
    },
    {
      heading: "Harvey-Bradshaw index for Crohn disease activity (ECCO 2024)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["General well-being (previous day)", "Very well", "0"],
        ["General well-being (previous day)", "Slightly below par", "1"],
        ["General well-being (previous day)", "Poor", "2"],
        ["General well-being (previous day)", "Very poor", "3"],
        ["General well-being (previous day)", "Terrible", "4"],
        ["Abdominal pain", "None", "0"],
        ["Abdominal pain", "Mild", "1"],
        ["Abdominal pain", "Moderate", "2"],
        ["Abdominal pain", "Severe", "3"],
        ["Liquid or soft stools (previous day)", "Each stool", "1"],
        ["Abdominal mass", "None", "0"],
        ["Abdominal mass", "Dubious", "1"],
        ["Abdominal mass", "Definite", "2"],
        ["Abdominal mass", "Definite and tender", "3"],
        ["Complications", "Each of: arthralgia, uveitis, erythema nodosum, aphthous ulcers", "1"],
        ["Complications", "Each of: pyoderma gangrenosum, anal fissure, new fistula, abscess", "1"],
      ],
    },
    {
      heading: "Harvey-Bradshaw index bands",
      columns: ["HBI", "Activity", "Note"],
      rows: [
        ["Below 5", "Remission", "Continue maintenance"],
        ["5 to 7", "Mild disease", "Review therapy"],
        ["8 to 16", "Moderate disease", "Steroids or escalate to advanced therapy"],
        ["Above 16", "Severe disease", "Admit; exclude abscess and obstruction"],
      ],
    },
  ],
  "gastro-hepatology-acute-abdomen-pancreatitis": [
    {
      heading: "Ranson criteria for acute pancreatitis (Bailey and Love 28e 2023)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["On admission - age", "Above 55 years", "1"],
        ["On admission - WBC", "Above 16,000/mm3", "1"],
        ["On admission - glucose", "Above 200 mg/dL (11 mmol/L)", "1"],
        ["On admission - LDH", "Above 350 IU/L", "1"],
        ["On admission - AST", "Above 250 IU/L", "1"],
        ["Within 48 h - haematocrit", "Fall of more than 10 percentage points", "1"],
        ["Within 48 h - BUN", "Rise of more than 5 mg/dL", "1"],
        ["Within 48 h - calcium", "Below 8 mg/dL (2 mmol/L)", "1"],
        ["Within 48 h - PaO2", "Below 60 mmHg", "1"],
        ["Within 48 h - base deficit", "More than 4 mEq/L", "1"],
        ["Within 48 h - fluid sequestration", "More than 6 L", "1"],
      ],
    },
    {
      heading: "Ranson score bands and mortality",
      columns: ["Ranson total", "Approximate mortality", "Meaning"],
      rows: [
        ["0 to 2", "About 1 to 2 percent", "Mild"],
        ["3 to 4", "About 15 percent", "Severe - HDU care"],
        ["5 to 6", "About 40 percent", "Severe - ICU care"],
        ["7 or more", "Approaching 100 percent", "Very severe"],
      ],
    },
    {
      heading: "BISAP score for acute pancreatitis within 24 hours (ACG 2024 pancreatitis)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["BUN", "Above 25 mg/dL", "1"],
        ["Impaired mental status", "GCS below 15 or disorientation", "1"],
        ["SIRS", "2 or more SIRS criteria", "1"],
        ["Age", "Above 60 years", "1"],
        ["Pleural effusion", "Present on imaging", "1"],
      ],
    },
    {
      heading: "BISAP score bands and mortality",
      columns: ["BISAP", "Approximate mortality", "Meaning"],
      rows: [
        ["0", "Below 1 percent", "Low risk"],
        ["1 to 2", "About 0.5 to 2 percent", "Low risk"],
        ["3", "About 5 percent", "High risk of severe pancreatitis"],
        ["4 to 5", "About 7 to 20 percent", "High risk - HDU or ICU"],
      ],
    },
    {
      heading: "Modified Glasgow-Imrie score (PANCREAS) at 48 hours (Bailey and Love 28e 2023)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["P - PaO2", "Below 8 kPa (60 mmHg)", "1"],
        ["A - Age", "Above 55 years", "1"],
        ["N - Neutrophils (WBC)", "Above 15 x10^9/L", "1"],
        ["C - Calcium", "Below 2 mmol/L", "1"],
        ["R - Renal (urea)", "Above 16 mmol/L", "1"],
        ["E - Enzymes", "LDH above 600 IU/L or AST above 200 IU/L", "1"],
        ["A - Albumin", "Below 32 g/L", "1"],
        ["S - Sugar (glucose)", "Above 10 mmol/L", "1"],
      ],
    },
    {
      heading: "Glasgow-Imrie score interpretation",
      columns: ["Total", "Meaning", "Action"],
      rows: [
        ["0 to 2", "Mild pancreatitis likely", "Ward care, fluids, early feeding"],
        ["3 or more", "Severe pancreatitis predicted", "HDU or ICU; CT at 72 to 96 h if not improving"],
      ],
    },
    {
      heading: "CT severity index (Balthazar) for acute pancreatitis (Sleisenger 11e 2021)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Balthazar grade", "A - normal pancreas", "0"],
        ["Balthazar grade", "B - focal or diffuse enlargement", "1"],
        ["Balthazar grade", "C - pancreatic changes with peripancreatic inflammation", "2"],
        ["Balthazar grade", "D - single peripancreatic fluid collection", "3"],
        ["Balthazar grade", "E - two or more collections or retroperitoneal gas", "4"],
        ["Pancreatic necrosis", "None", "0"],
        ["Pancreatic necrosis", "30 percent or less", "2"],
        ["Pancreatic necrosis", "30 to 50 percent", "4"],
        ["Pancreatic necrosis", "More than 50 percent", "6"],
      ],
    },
    {
      heading: "CT severity index bands",
      columns: ["CTSI (0-10)", "Severity", "Approximate mortality"],
      rows: [
        ["0 to 3", "Mild", "About 3 percent"],
        ["4 to 6", "Moderate", "About 6 percent"],
        ["7 to 10", "Severe", "About 17 percent; high morbidity"],
      ],
    },
    {
      heading: "Modified Marshall organ failure score (Revised Atlanta 2012)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Respiratory - PaO2/FiO2", "Above 400", "0"],
        ["Respiratory - PaO2/FiO2", "301 to 400", "1"],
        ["Respiratory - PaO2/FiO2", "201 to 300", "2"],
        ["Respiratory - PaO2/FiO2", "101 to 200", "3"],
        ["Respiratory - PaO2/FiO2", "100 or less", "4"],
        ["Renal - creatinine (mg/dL)", "Below 1.4", "0"],
        ["Renal - creatinine (mg/dL)", "1.4 to 1.8", "1"],
        ["Renal - creatinine (mg/dL)", "1.9 to 3.6", "2"],
        ["Renal - creatinine (mg/dL)", "3.6 to 4.9", "3"],
        ["Renal - creatinine (mg/dL)", "Above 4.9", "4"],
        ["Cardiovascular - SBP (off inotropes)", "Above 90 mmHg", "0"],
        ["Cardiovascular - SBP (off inotropes)", "Below 90 mmHg, fluid responsive", "1"],
        ["Cardiovascular - SBP (off inotropes)", "Below 90 mmHg, not fluid responsive", "2"],
        ["Cardiovascular - SBP (off inotropes)", "Below 90 mmHg, pH below 7.3", "3"],
        ["Cardiovascular - SBP (off inotropes)", "Below 90 mmHg, pH below 7.2", "4"],
      ],
    },
    {
      heading: "Modified Marshall score - interpretation",
      columns: ["Result", "Meaning", "Revised Atlanta consequence"],
      rows: [
        ["2 or more in any one system", "Organ failure", "Defines moderately severe or severe pancreatitis"],
        ["Organ failure resolving within 48 h", "Transient organ failure", "Moderately severe acute pancreatitis"],
        ["Organ failure lasting beyond 48 h", "Persistent organ failure", "Severe acute pancreatitis - mortality 15 to 30 percent"],
      ],
    },
    {
      heading: "Tokyo Guidelines TG18 severity grading of acute cholangitis",
      columns: ["Grade", "Criteria", "Management"],
      rows: [
        ["Grade III - severe", "Organ dysfunction: vasopressor, confusion, P/F below 300, creatinine above 2.0, INR above 1.5, platelets below 100k", "Organ support and urgent biliary drainage (ERCP)"],
        ["Grade II - moderate", "Any 2: WBC above 12,000 or below 4000, fever 39 C or more, age 75+, bilirubin 5 mg/dL or more, low albumin", "Early biliary drainage within 24 to 48 h"],
        ["Grade I - mild", "Neither grade II nor grade III criteria", "Antibiotics; drainage if no response in 24 h"],
      ],
    },
    {
      heading: "Tokyo Guidelines TG18 severity grading of acute cholecystitis",
      columns: ["Grade", "Criteria", "Management"],
      rows: [
        ["Grade III - severe", "Organ dysfunction (cardiovascular, neurological, respiratory, renal, hepatic or haematological)", "Organ support; early cholecystectomy only in expert centres, else drainage"],
        ["Grade II - moderate", "Any of: WBC above 18,000, tender RUQ mass, symptoms beyond 72 h, marked local inflammation", "Early laparoscopic cholecystectomy in experienced hands"],
        ["Grade I - mild", "Healthy patient, mild gallbladder inflammation, no organ dysfunction", "Early laparoscopic cholecystectomy"],
      ],
    },
  ],
};

export default scores;
