import type { NoteTable } from "../../lib/types";

const scores: Record<string, NoteTable[]> = {
  "geriatrics-ethics-cga": [
    {
      heading: "Katz index of independence in activities of daily living (Harrison 22e 2025)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Bathing", "Independent, or help with one body part only", "1"],
        ["Bathing", "Needs help with more than one part, or getting in or out", "0"],
        ["Dressing", "Gets clothes and dresses without help (may need help tying shoes)", "1"],
        ["Dressing", "Needs help dressing", "0"],
        ["Toileting", "Goes to toilet, cleans self, arranges clothes unaided", "1"],
        ["Toileting", "Needs help", "0"],
        ["Transferring", "Moves in and out of bed or chair unaided (aids allowed)", "1"],
        ["Transferring", "Needs help", "0"],
        ["Continence", "Complete control of bladder and bowel", "1"],
        ["Continence", "Partly or totally incontinent", "0"],
        ["Feeding", "Gets food from plate to mouth unaided", "1"],
        ["Feeding", "Needs partial or total help, or parenteral feeding", "0"],
      ],
    },
    {
      heading: "Katz ADL score bands (total 0-6)",
      columns: ["Katz total", "Function", "Implication"],
      rows: [
        ["6", "Full function", "Independent in basic ADLs"],
        ["3-5", "Moderate impairment (4 classically)", "Targeted help; ADLs lost in reverse order of childhood acquisition"],
        ["0-2", "Severe functional impairment", "Needs daily care; carer support and care-home discussion"],
      ],
    },
    {
      heading: "Lawton instrumental activities of daily living (IADL) scale (Harrison 22e 2025)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Telephone", "Uses on own initiative, dials a few known numbers, or answers only", "1"],
        ["Telephone", "Does not use telephone at all", "0"],
        ["Shopping", "Takes care of all shopping independently", "1"],
        ["Shopping", "Small purchases only, needs accompaniment, or unable", "0"],
        ["Food preparation", "Plans, prepares and serves adequate meals independently", "1"],
        ["Food preparation", "Needs ingredients supplied, heats only, or needs meals served", "0"],
        ["Housekeeping", "Maintains house alone or with help for heavy work, or does light tasks", "1"],
        ["Housekeeping", "Does not participate in any housekeeping", "0"],
        ["Laundry", "Does all personal laundry, or small items", "1"],
        ["Laundry", "All laundry done by others", "0"],
        ["Transport", "Travels alone by public transport or drives; arranges taxi; or travels when assisted", "1"],
        ["Transport", "Travel limited to taxi or car with help, or does not travel", "0"],
        ["Own medications", "Takes correct doses at correct times independently", "1"],
        ["Own medications", "Needs doses prepared in advance, or cannot", "0"],
        ["Finances", "Manages independently, or day-to-day with help for banking", "1"],
        ["Finances", "Incapable of handling money", "0"],
      ],
    },
    {
      heading: "Lawton IADL score - interpretation (total 0-8)",
      columns: ["Lawton total", "Meaning", "Note"],
      rows: [
        ["8", "High function, independent", "Historically men scored on 5 items (no food, housekeeping, laundry)"],
        ["Falling score", "Increasing dependence", "No fixed cut-off - track change over time"],
        ["Early IADL loss", "Finances, medicines, transport", "Early marker of dementia before basic ADLs fail"],
      ],
    },
    {
      heading: "Barthel Index of activities of daily living (Mahoney and Barthel, in use 2026)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Feeding", "Unable", "0"],
        ["Feeding", "Needs help cutting, spreading, or modified diet", "5"],
        ["Feeding", "Independent", "10"],
        ["Bathing", "Dependent", "0"],
        ["Bathing", "Independent (or in shower)", "5"],
        ["Grooming", "Needs help with personal care", "0"],
        ["Grooming", "Independent - face, hair, teeth, shaving", "5"],
        ["Dressing", "Dependent", "0"],
        ["Dressing", "Needs help but does about half unaided", "5"],
        ["Dressing", "Independent including buttons, zips, laces", "10"],
        ["Bowels", "Incontinent (or needs enemas)", "0"],
        ["Bowels", "Occasional accident", "5"],
        ["Bowels", "Continent", "10"],
        ["Bladder", "Incontinent, or catheterised and unable to manage", "0"],
        ["Bladder", "Occasional accident", "5"],
        ["Bladder", "Continent", "10"],
        ["Toilet use", "Dependent", "0"],
        ["Toilet use", "Needs some help, can do something alone", "5"],
        ["Toilet use", "Independent - on, off, dressing, wiping", "10"],
        ["Transfers (bed to chair and back)", "Unable, no sitting balance", "0"],
        ["Transfers (bed to chair and back)", "Major help (1-2 people, physical), can sit", "5"],
        ["Transfers (bed to chair and back)", "Minor help (verbal or physical)", "10"],
        ["Transfers (bed to chair and back)", "Independent", "15"],
        ["Mobility on level surfaces", "Immobile or under 50 yards", "0"],
        ["Mobility on level surfaces", "Wheelchair independent, including corners, over 50 yards", "5"],
        ["Mobility on level surfaces", "Walks with help of one person over 50 yards", "10"],
        ["Mobility on level surfaces", "Independent (may use aid such as stick) over 50 yards", "15"],
        ["Stairs", "Unable", "0"],
        ["Stairs", "Needs help (verbal, physical, carrying aid)", "5"],
        ["Stairs", "Independent", "10"],
      ],
    },
    {
      heading: "Barthel Index dependency bands (total 0-100)",
      columns: ["Barthel total", "Dependency", "Implication"],
      rows: [
        ["0-20", "Total dependency", "24-hour care"],
        ["21-60", "Severe dependency", "Substantial daily help"],
        ["61-90", "Moderate dependency", "Help with some ADLs"],
        ["91-99", "Slight dependency", "Mostly independent"],
        ["100", "Independent", "Does not mean able to live alone - IADLs not tested"],
      ],
    },
    {
      heading: "Geriatric Depression Scale (GDS-15) score bands (Harrison 22e 2025)",
      columns: ["GDS-15 total", "Meaning", "Action"],
      rows: [
        ["0-4", "Normal", "Rescreen if circumstances change"],
        ["5-8", "Mild depression", "Clinical assessment; psychosocial support"],
        ["9-11", "Moderate depression", "Treat - psychotherapy and/or SSRI (sertraline, escitalopram)"],
        ["12-15", "Severe depression", "Treat and assess suicide risk; refer"],
      ],
    },
    {
      heading: "Charlson Comorbidity Index, age-adjusted (Harrison 22e 2025)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["1-point conditions (each)", "Myocardial infarction", "1"],
        ["1-point conditions (each)", "Congestive heart failure", "1"],
        ["1-point conditions (each)", "Peripheral vascular disease", "1"],
        ["1-point conditions (each)", "Cerebrovascular disease or TIA", "1"],
        ["1-point conditions (each)", "Dementia", "1"],
        ["1-point conditions (each)", "Chronic pulmonary disease", "1"],
        ["1-point conditions (each)", "Connective tissue disease", "1"],
        ["1-point conditions (each)", "Peptic ulcer disease", "1"],
        ["1-point conditions (each)", "Mild liver disease", "1"],
        ["1-point conditions (each)", "Diabetes without end-organ damage", "1"],
        ["2-point conditions (each)", "Hemiplegia", "2"],
        ["2-point conditions (each)", "Moderate or severe renal disease", "2"],
        ["2-point conditions (each)", "Diabetes with end-organ damage", "2"],
        ["2-point conditions (each)", "Any solid tumour without metastasis (within 5 years)", "2"],
        ["2-point conditions (each)", "Leukaemia", "2"],
        ["2-point conditions (each)", "Lymphoma", "2"],
        ["3-point condition", "Moderate or severe liver disease", "3"],
        ["6-point conditions (each)", "Metastatic solid tumour", "6"],
        ["6-point conditions (each)", "AIDS", "6"],
        ["Age (age-adjusted version)", "Under 50 years", "0"],
        ["Age (age-adjusted version)", "50-59 years", "1"],
        ["Age (age-adjusted version)", "60-69 years", "2"],
        ["Age (age-adjusted version)", "70-79 years", "3"],
        ["Age (age-adjusted version)", "80 years or more", "4"],
      ],
    },
    {
      heading: "Charlson Comorbidity Index - burden bands",
      columns: ["CCI total", "Comorbidity burden", "Implication"],
      rows: [
        ["0", "None", "Best 10-year survival"],
        ["1-2", "Mild", "-"],
        ["3-4", "Moderate", "Weigh benefit of screening and aggressive treatment"],
        ["5 or more", "Severe", "Markedly reduced 10-year survival - consider limited life expectancy in decisions"],
      ],
    },
  ],
  "geriatrics-ethics-falls": [
    {
      heading: "Fall risk stratification by risk class (World Falls Guidelines 2022)",
      columns: ["Risk group", "Who", "Intervention"],
      rows: [
        ["Low risk", "No fall in 12 months, or a non-severe fall with no gait or balance problem", "Education and exercise for fall prevention and general health"],
        ["Intermediate risk", "Non-severe fall with gait or balance impairment", "Strength and balance exercise programme; education"],
        ["High risk", "Fall with injury, 2 or more falls, frailty, long lie, or suspected syncope", "Multifactorial falls risk assessment and tailored intervention"],
        ["Opportunistic case finding", "Ask all over 65 about falls in past 12 months", "Gait speed under 0.8 m/s or TUG over 15 s supports intermediate risk"],
      ],
    },
    {
      heading: "Morse Fall Scale for inpatient fall risk (Morse 2009, in use 2026)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["History of falling (index or past 3 months)", "No", "0"],
        ["History of falling (index or past 3 months)", "Yes", "25"],
        ["Secondary diagnosis", "No", "0"],
        ["Secondary diagnosis", "Yes", "15"],
        ["Ambulatory aid", "None, bed rest, or nurse assists", "0"],
        ["Ambulatory aid", "Crutches, cane or walker", "15"],
        ["Ambulatory aid", "Clutches furniture", "30"],
        ["IV therapy or heparin lock", "No", "0"],
        ["IV therapy or heparin lock", "Yes", "20"],
        ["Gait", "Normal, bed rest, or wheelchair", "0"],
        ["Gait", "Weak", "10"],
        ["Gait", "Impaired", "20"],
        ["Mental status", "Oriented to own ability", "0"],
        ["Mental status", "Overestimates or forgets limitations", "15"],
      ],
    },
    {
      heading: "Morse Fall Scale risk bands (total 0-125)",
      columns: ["Morse total", "Risk", "Action"],
      rows: [
        ["0-24", "Low", "Standard fall precautions"],
        ["25-44", "Moderate", "Fall-prevention interventions"],
        ["45 or more", "High", "High-risk fall-prevention bundle; cut-offs are set locally"],
      ],
    },
    {
      heading: "Timed Up and Go and gait speed cut-off criteria (World Falls Guidelines 2022)",
      columns: ["Measure", "Result", "Meaning"],
      rows: [
        ["TUG under 10 s", "Freely mobile", "Normal for community-dwelling older adults"],
        ["TUG 12 s or more", "Increased fall risk", "CDC STEADI threshold"],
        ["TUG over 15 s", "Impaired mobility", "World Falls Guidelines 2022 marker of gait and balance problem"],
        ["TUG 20 s or more", "Low physical performance", "EWGSOP2 severity marker"],
        ["Gait speed 1.0 m/s or more", "Normal community ambulation", "AWGS 2019 low performance is under 1.0 m/s (6 m walk)"],
        ["Gait speed 0.8 m/s or less", "Low physical performance", "Frailty, falls and mortality risk rise (EWGSOP2)"],
      ],
    },
  ],
  "geriatrics-ethics-polypharmacy": [
    {
      heading: "Polypharmacy classification by number of regular medicines (WHO 2019)",
      columns: ["Class", "Number of regular medicines", "Action"],
      rows: [
        ["No polypharmacy", "0-4", "Annual medication review"],
        ["Polypharmacy", "5-9", "Structured review with Beers or STOPP/START"],
        ["Hyperpolypharmacy (excessive)", "10 or more", "Priority deprescribing review; high risk of falls and ADRs"],
      ],
    },
  ],
  "geriatrics-ethics-palliative-symptom-control": [
    {
      heading: "ECOG performance status scale (ESMO 2023; Harrison 22e 2025)",
      columns: ["Grade", "Function", "Implication"],
      rows: [
        ["ECOG 0", "Fully active, no restriction", "Fit for all treatment"],
        ["ECOG 1", "Restricted in strenuous activity, ambulatory, light work possible", "Fit for most chemotherapy"],
        ["ECOG 2", "Ambulatory, self-caring, cannot work; up over 50% of waking hours", "Selective chemotherapy"],
        ["ECOG 3", "Limited self-care; in bed or chair over 50% of waking hours", "Usually best supportive care"],
        ["ECOG 4", "Completely disabled; no self-care; totally bed or chair bound", "Best supportive care"],
        ["ECOG 5", "Dead", "-"],
      ],
    },
    {
      heading: "Karnofsky Performance Status scale (Harrison 22e 2025)",
      columns: ["KPS", "Function", "Group"],
      rows: [
        ["100", "Normal, no complaints, no evidence of disease", "Normal activity, no special care"],
        ["90", "Normal activity, minor signs or symptoms", "Normal activity, no special care"],
        ["80", "Normal activity with effort, some signs or symptoms", "Normal activity, no special care"],
        ["70", "Cares for self, unable to do normal activity or active work", "Unable to work, lives at home"],
        ["60", "Needs occasional help, cares for most needs", "Unable to work, lives at home"],
        ["50", "Needs considerable help and frequent medical care", "Unable to work, lives at home"],
        ["40", "Disabled, needs special care and help", "Unable to self-care"],
        ["30", "Severely disabled, hospital admission indicated, death not imminent", "Unable to self-care"],
        ["20", "Very sick, active supportive treatment needed", "Unable to self-care"],
        ["10", "Moribund, fatal processes progressing rapidly", "Unable to self-care"],
        ["0", "Dead", "-"],
      ],
    },
    {
      heading: "Palliative Performance Scale (PPSv2) (Victoria Hospice 2001, in use 2026)",
      columns: ["PPS level", "Ambulation", "Activity and disease evidence", "Self-care", "Intake and consciousness"],
      rows: [
        ["100%", "Full", "Normal activity and work, no disease evidence", "Full", "Normal; full"],
        ["90%", "Full", "Normal activity and work, some disease", "Full", "Normal; full"],
        ["80%", "Full", "Normal activity with effort, some disease", "Full", "Normal or reduced; full"],
        ["70%", "Reduced", "Unable to do normal job, significant disease", "Full", "Normal or reduced; full"],
        ["60%", "Reduced", "Unable to do hobbies or housework, significant disease", "Occasional assistance", "Normal or reduced; full or confusion"],
        ["50%", "Mainly sit or lie", "Unable to do any work, extensive disease", "Considerable assistance", "Normal or reduced; full or confusion"],
        ["40%", "Mainly in bed", "Unable to do most activity, extensive disease", "Mainly assistance", "Normal or reduced; full, drowsy or confused"],
        ["30%", "Totally bed bound", "Unable to do any activity, extensive disease", "Total care", "Normal or reduced; full, drowsy or confused"],
        ["20%", "Totally bed bound", "Unable to do any activity, extensive disease", "Total care", "Minimal sips; full, drowsy or confused"],
        ["10%", "Totally bed bound", "Unable to do any activity, extensive disease", "Total care", "Mouth care only; drowsy or coma"],
        ["0%", "Death", "-", "-", "-"],
      ],
    },
    {
      heading: "Palliative Prognostic Index (PPI) for survival in advanced cancer (OTPM 6e 2021)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Palliative Performance Scale", "60% or more", "0"],
        ["Palliative Performance Scale", "30-50%", "2.5"],
        ["Palliative Performance Scale", "10-20%", "4"],
        ["Oral intake", "Normal", "0"],
        ["Oral intake", "Moderately reduced (more than mouthfuls)", "1"],
        ["Oral intake", "Severely reduced (mouthfuls or less)", "2.5"],
        ["Oedema", "Present", "1"],
        ["Dyspnoea at rest", "Present", "3.5"],
        ["Delirium (not drug-induced alone)", "Present", "4"],
      ],
    },
    {
      heading: "Palliative Prognostic Index - survival bands (total 0-15)",
      columns: ["PPI total", "Predicted survival", "Use"],
      rows: [
        ["4 or less", "More than 6 weeks likely", "Plan care at home, advance care planning"],
        ["Over 4 to 6", "Under 6 weeks likely", "Discuss preferred place of care and death"],
        ["Over 6", "Under 3 weeks likely", "End-of-life care planning, anticipatory medicines"],
      ],
    },
    {
      heading: "ESAS-r Edmonton symptom severity scale (Oxford Textbook Palliative Med 6e 2021)",
      columns: ["Rating (each symptom 0-10)", "Severity", "Action"],
      rows: [
        ["0", "Absent", "-"],
        ["1-3", "Mild", "Monitor"],
        ["4-6", "Moderate", "Targeted assessment and treatment"],
        ["7-10", "Severe", "Urgent symptom control"],
        ["Symptoms rated (9 + other)", "Pain, tiredness, drowsiness, nausea, appetite, breathlessness", "Also depression, anxiety, wellbeing"],
      ],
    },
    {
      heading: "WHO analgesic ladder - pain severity scale and step (WHO cancer pain 2018)",
      columns: ["Step", "Pain severity (NRS 0-10)", "Drugs"],
      rows: [
        ["Step 1", "Mild (1-3)", "Non-opioid - paracetamol, NSAID +/- adjuvant"],
        ["Step 2", "Moderate (4-6)", "Weak opioid (codeine, tramadol) or low-dose morphine +/- non-opioid, adjuvant"],
        ["Step 3", "Severe (7-10)", "Strong opioid (morphine, oxycodone, fentanyl) +/- non-opioid, adjuvant"],
        ["Step 4 (proposed)", "Refractory pain", "Interventional - nerve blocks, neurolysis, intrathecal"],
        ["WHO 2018 principles", "By mouth, by the clock, for the individual, attention to detail", "Ladder now a guide, not a rigid sequence; oral morphine in NLEM India"],
      ],
    },
    {
      heading: "Opioid equianalgesic conversion scale to oral morphine (Palliative Care Formulary 7e 2020)",
      columns: ["Opioid and route", "Equivalence", "Practical note"],
      rows: [
        ["Codeine oral", "Divide by 10 (60 mg = 6 mg oral morphine)", "Ceiling 240 mg/day; poor CYP2D6 metabolisers get no effect"],
        ["Tramadol oral", "Divide by 10 (100 mg = 10 mg oral morphine)", "Ceiling 400 mg/day; serotonergic, lowers seizure threshold"],
        ["Tapentadol oral", "Divide by 2.5 (50 mg = 20 mg oral morphine)", "-"],
        ["Oxycodone oral", "Multiply by 1.5 (10 mg = 15 mg oral morphine)", "Useful in mild renal impairment"],
        ["Hydromorphone oral", "Multiply by 5 to 7.5 (tables vary)", "Use the local table; titrate carefully"],
        ["Morphine SC or IV", "Multiply by 2 (5 mg SC = 10 mg oral)", "Syringe driver dose = half the 24 h oral dose"],
        ["Fentanyl transdermal", "12 microgram/h patch = about 30-45 mg oral morphine/24 h", "Only for stable pain; 72-hourly; not in opioid-naive"],
        ["Buprenorphine transdermal", "5 microgram/h = about 12 mg oral morphine/24 h", "7-day patches for low-dose needs"],
        ["Switching opioids", "Reduce calculated dose by 25-50%", "Incomplete cross-tolerance"],
        ["Breakthrough dose", "One-sixth to one-tenth of 24 h regular dose", "Immediate-release, up to hourly as needed"],
      ],
    },
    {
      heading: "Braden scale for pressure ulcer risk (NPIAP/EPUAP 2019)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Sensory perception", "Completely limited", "1"],
        ["Sensory perception", "Very limited", "2"],
        ["Sensory perception", "Slightly limited", "3"],
        ["Sensory perception", "No impairment", "4"],
        ["Moisture", "Constantly moist", "1"],
        ["Moisture", "Very moist", "2"],
        ["Moisture", "Occasionally moist", "3"],
        ["Moisture", "Rarely moist", "4"],
        ["Activity", "Bedfast", "1"],
        ["Activity", "Chairfast", "2"],
        ["Activity", "Walks occasionally", "3"],
        ["Activity", "Walks frequently", "4"],
        ["Mobility", "Completely immobile", "1"],
        ["Mobility", "Very limited", "2"],
        ["Mobility", "Slightly limited", "3"],
        ["Mobility", "No limitation", "4"],
        ["Nutrition", "Very poor", "1"],
        ["Nutrition", "Probably inadequate", "2"],
        ["Nutrition", "Adequate", "3"],
        ["Nutrition", "Excellent", "4"],
        ["Friction and shear", "Problem", "1"],
        ["Friction and shear", "Potential problem", "2"],
        ["Friction and shear", "No apparent problem", "3"],
      ],
    },
    {
      heading: "Braden scale risk bands (total 6-23, lower = higher risk)",
      columns: ["Braden total", "Risk", "Action"],
      rows: [
        ["19-23", "Not at risk", "Reassess on change in condition"],
        ["15-18", "Mild risk", "Turning schedule, maximise mobility, protect heels"],
        ["13-14", "Moderate risk", "Add 30-degree tilt, pressure-redistributing foam mattress"],
        ["10-12", "High risk", "More frequent turning, manage moisture and nutrition"],
        ["9 or less", "Very high risk", "Active support surface (alternating air), all measures"],
      ],
    },
    {
      heading: "Norton scale for pressure ulcer risk (Bailey and Love 28e 2023)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Physical condition", "Good", "4"],
        ["Physical condition", "Fair", "3"],
        ["Physical condition", "Poor", "2"],
        ["Physical condition", "Very bad", "1"],
        ["Mental condition", "Alert", "4"],
        ["Mental condition", "Apathetic", "3"],
        ["Mental condition", "Confused", "2"],
        ["Mental condition", "Stuporous", "1"],
        ["Activity", "Ambulant", "4"],
        ["Activity", "Walks with help", "3"],
        ["Activity", "Chairbound", "2"],
        ["Activity", "Bedfast", "1"],
        ["Mobility", "Full", "4"],
        ["Mobility", "Slightly limited", "3"],
        ["Mobility", "Very limited", "2"],
        ["Mobility", "Immobile", "1"],
        ["Incontinence", "None", "4"],
        ["Incontinence", "Occasional", "3"],
        ["Incontinence", "Usually urinary", "2"],
        ["Incontinence", "Doubly incontinent", "1"],
      ],
    },
    {
      heading: "Norton scale risk bands (total 5-20)",
      columns: ["Norton total", "Risk", "Action"],
      rows: [
        ["15-20", "Low risk", "Routine skin care"],
        ["12-14", "At risk", "Pressure-relief plan"],
        ["Under 12", "High risk", "Pressure-redistributing surface, 2-hourly repositioning"],
      ],
    },
  ],
  "geriatrics-ethics-frailty-sarcopenia-nutrition": [
    {
      heading: "Clinical Frailty Scale version 2.0 (Rockwood 2020)",
      columns: ["Level", "Category", "Description"],
      rows: [
        ["CFS 1", "Very fit", "Robust, active, energetic, motivated; exercise regularly"],
        ["CFS 2", "Fit", "No active disease symptoms but less fit than 1; occasionally active"],
        ["CFS 3", "Managing well", "Medical problems well controlled; not regularly active beyond walking"],
        ["CFS 4", "Living with very mild frailty", "Not dependent, but symptoms limit activities; slowed up, tired"],
        ["CFS 5", "Living with mild frailty", "Needs help with high-order IADLs - finances, transport, heavy housework"],
        ["CFS 6", "Living with moderate frailty", "Needs help with all outside activities, housekeeping, stairs, bathing"],
        ["CFS 7", "Living with severe frailty", "Completely dependent for personal care, but stable; not likely to die within 6 months"],
        ["CFS 8", "Living with very severe frailty", "Completely dependent, approaching end of life; may not recover from minor illness"],
        ["CFS 9", "Terminally ill", "Life expectancy under 6 months, not otherwise severely frail"],
      ],
    },
    {
      heading: "Fried frailty phenotype criteria (Harrison 22e 2025)",
      columns: ["Criterion", "Definition", "Note"],
      rows: [
        ["1 - Weight loss", "Unintentional loss of 4.5 kg (10 lb) or 5% or more in past year", "Shrinking"],
        ["2 - Exhaustion", "Self-reported (2 CES-D items) on 3 or more days a week", "-"],
        ["3 - Weakness", "Grip strength in lowest 20%, adjusted for sex and BMI", "-"],
        ["4 - Slowness", "Walking time over 15 feet in slowest 20%, adjusted for sex and height", "-"],
        ["5 - Low activity", "Lowest 20% of kcal/week (men under 383, women under 270)", "-"],
        ["Robust", "0 criteria", "-"],
        ["Pre-frail", "1-2 criteria", "Target exercise and protein - reversible"],
        ["Frail", "3 or more criteria", "Higher risk of falls, disability, hospitalisation, death"],
      ],
    },
    {
      heading: "EWGSOP2 sarcopenia diagnostic criteria and severity (EWGSOP2 2019)",
      columns: ["Step", "Measure and cut-off", "Meaning"],
      rows: [
        ["Find cases", "SARC-F 4 or more, or clinical suspicion", "-"],
        ["Low muscle strength", "Grip under 27 kg men, under 16 kg women; or 5 chair stands over 15 s", "Probable sarcopenia - start treatment"],
        ["Low muscle quantity", "ASM under 20 kg men, under 15 kg women; or ASM/height2 under 7.0 and 5.5 kg/m2", "Confirmed sarcopenia (with low strength)"],
        ["Low physical performance", "Gait speed 0.8 m/s or less; SPPB 8 or less; TUG 20 s or more; 400 m walk 6 min or more", "Severe sarcopenia (all three present)"],
      ],
    },
    {
      heading: "AWGS 2019 sarcopenia criteria for Asian populations (AWGS 2019)",
      columns: ["Domain", "Cut-off", "Note"],
      rows: [
        ["Case finding (primary care)", "Calf circumference under 34 cm men, under 33 cm women; or SARC-F 4 or more", "Or SARC-CalF 11 or more"],
        ["Low muscle strength", "Handgrip under 28 kg men, under 18 kg women", "-"],
        ["Low physical performance", "6 m gait speed under 1.0 m/s; SPPB 9 or less; 5 chair stands 12 s or more", "-"],
        ["Low muscle mass", "DXA under 7.0 men, under 5.4 women; BIA under 7.0 men, under 5.7 women (kg/m2)", "Appendicular skeletal muscle mass/height2"],
        ["Possible sarcopenia", "Low strength or low performance, in primary care", "Start lifestyle intervention; refer to confirm"],
        ["Sarcopenia", "Low mass plus low strength or low performance", "-"],
        ["Severe sarcopenia", "Low mass plus low strength plus low performance", "Resistance exercise, protein 1.0-1.2 g/kg/day"],
      ],
    },
    {
      heading: "SARC-F screening questionnaire for sarcopenia (EWGSOP2 2019)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Strength - lifting and carrying 4.5 kg", "No difficulty", "0"],
        ["Strength - lifting and carrying 4.5 kg", "Some difficulty", "1"],
        ["Strength - lifting and carrying 4.5 kg", "A lot or unable", "2"],
        ["Assistance walking across a room", "None", "0"],
        ["Assistance walking across a room", "Some", "1"],
        ["Assistance walking across a room", "A lot, uses aids, or unable", "2"],
        ["Rise from a chair or bed", "None", "0"],
        ["Rise from a chair or bed", "Some", "1"],
        ["Rise from a chair or bed", "A lot or unable without help", "2"],
        ["Climb a flight of 10 stairs", "None", "0"],
        ["Climb a flight of 10 stairs", "Some", "1"],
        ["Climb a flight of 10 stairs", "A lot or unable", "2"],
        ["Falls in past year", "None", "0"],
        ["Falls in past year", "1-3 falls", "1"],
        ["Falls in past year", "4 or more falls", "2"],
      ],
    },
    {
      heading: "SARC-F score interpretation (total 0-10)",
      columns: ["SARC-F total", "Meaning", "Action"],
      rows: [
        ["0-3", "Sarcopenia unlikely", "Rescreen annually or after acute illness"],
        ["4 or more", "Predictive of sarcopenia", "Measure grip strength and chair stands"],
      ],
    },
    {
      heading: "Mini Nutritional Assessment - Short Form (MNA-SF) (ESPEN 2019)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["A Food intake fall in past 3 months", "Severe decrease", "0"],
        ["A Food intake fall in past 3 months", "Moderate decrease", "1"],
        ["A Food intake fall in past 3 months", "No decrease", "2"],
        ["B Weight loss in past 3 months", "Over 3 kg", "0"],
        ["B Weight loss in past 3 months", "Does not know", "1"],
        ["B Weight loss in past 3 months", "1-3 kg", "2"],
        ["B Weight loss in past 3 months", "None", "3"],
        ["C Mobility", "Bed or chair bound", "0"],
        ["C Mobility", "Out of bed or chair but does not go out", "1"],
        ["C Mobility", "Goes out", "2"],
        ["D Psychological stress or acute disease (3 months)", "Yes", "0"],
        ["D Psychological stress or acute disease (3 months)", "No", "2"],
        ["E Neuropsychological problems", "Severe dementia or depression", "0"],
        ["E Neuropsychological problems", "Mild dementia", "1"],
        ["E Neuropsychological problems", "None", "2"],
        ["F1 BMI (kg/m2)", "Under 19", "0"],
        ["F1 BMI (kg/m2)", "19 to under 21", "1"],
        ["F1 BMI (kg/m2)", "21 to under 23", "2"],
        ["F1 BMI (kg/m2)", "23 or more", "3"],
        ["F2 Calf circumference (only if no BMI)", "Under 31 cm", "0"],
        ["F2 Calf circumference (only if no BMI)", "31 cm or more", "3"],
      ],
    },
    {
      heading: "MNA-SF score bands for nutritional status (total 0-14)",
      columns: ["MNA-SF total", "Status", "Action"],
      rows: [
        ["12-14", "Normal nutritional status", "Rescreen yearly, or 3-monthly in institutions"],
        ["8-11", "At risk of malnutrition", "Dietary advice, monitor weight, full MNA"],
        ["0-7", "Malnourished", "Full nutritional assessment, supplements, treat cause"],
      ],
    },
    {
      heading: "MUST - Malnutrition Universal Screening Tool (BAPEN 2024)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Step 1 BMI (kg/m2)", "Over 20 (over 30 obese)", "0"],
        ["Step 1 BMI (kg/m2)", "18.5-20", "1"],
        ["Step 1 BMI (kg/m2)", "Under 18.5", "2"],
        ["Step 2 Unplanned weight loss in 3-6 months", "Under 5%", "0"],
        ["Step 2 Unplanned weight loss in 3-6 months", "5-10%", "1"],
        ["Step 2 Unplanned weight loss in 3-6 months", "Over 10%", "2"],
        ["Step 3 Acute disease effect", "Acutely ill with no intake for over 5 days likely", "2"],
      ],
    },
    {
      heading: "MUST score risk categories and management (BAPEN 2024)",
      columns: ["MUST total", "Risk", "Management"],
      rows: [
        ["0", "Low", "Routine care; rescreen weekly in hospital, monthly in care home, yearly if over 75 in community"],
        ["1", "Medium", "Observe - document 3-day intake; rescreen"],
        ["2 or more", "High", "Treat - refer dietitian, improve intake, monitor care plan"],
      ],
    },
  ],
  "geriatrics-ethics-consent-capacity-records": [
    {
      heading: "Criteria for decision-making capacity (MHCA 2017 India; MCA 2005 UK)",
      columns: ["Criterion", "Patient must be able to", "Note"],
      rows: [
        ["Understand", "Understand the information relevant to the decision", "Use simple language, aids, interpreter"],
        ["Retain (MCA)", "Retain it long enough to decide", "Short retention is enough"],
        ["Appreciate and weigh", "Appreciate foreseeable consequences of deciding or not deciding", "MHCA 2017 section 4(b)"],
        ["Communicate", "Communicate the decision by speech, expression, gesture or other means", "MHCA 2017 section 4(c)"],
        ["Presumption", "Capacity is presumed; decision-specific and time-specific", "An unwise decision alone does not mean incapacity"],
      ],
    },
    {
      heading: "Types of consent in clinical practice (Samira Kohli 2008; IMC Regulations 2002)",
      columns: ["Type", "Description", "Example"],
      rows: [
        ["Implied", "Inferred from conduct", "Holding out an arm for BP measurement"],
        ["Expressed - oral", "Spoken agreement, documented in notes", "Simple examination, minor procedures"],
        ["Expressed - written", "Signed after explanation", "Surgery, anaesthesia, invasive procedures, research"],
        ["Informed", "Nature, purpose, risks, benefits, alternatives understood (Samira Kohli 2008)", "Required for every intervention - specific, not blanket"],
        ["Proxy or surrogate", "By guardian or nominated representative when patient lacks capacity", "Child under 18, MHCA nominated representative"],
        ["Emergency exception", "Treat in best interests when no one can consent", "Life-saving treatment; document reasons"],
      ],
    },
  ],
  "geriatrics-ethics-dementia-caregiver": [
    {
      heading: "Zarit caregiver burden (ZBI-22) score bands (Kaplan and Sadock 12e 2021)",
      columns: ["ZBI-22 total (0-88)", "Burden", "Action"],
      rows: [
        ["0-20", "Little or no burden", "Information and routine support"],
        ["21-40", "Mild to moderate burden", "Carer education, support groups, respite options"],
        ["41-60", "Moderate to severe burden", "Respite care, screen carer for depression"],
        ["61-88", "Severe burden", "Urgent care package, day care or residential care discussion"],
      ],
    },
  ],
  "geriatrics-ethics-end-of-life-death-certification": [
    {
      heading: "Types of euthanasia and legal status in India (Common Cause v Union of India 2018, 2023)",
      columns: ["Type", "Definition", "Status in India"],
      rows: [
        ["Active euthanasia", "Deliberate act (e.g. lethal injection) to end life", "Illegal - culpable homicide"],
        ["Passive euthanasia", "Withholding or withdrawing life-sustaining treatment", "Legal under Supreme Court guidelines (2018, simplified 2023)"],
        ["Voluntary", "At the competent patient's request", "Allowed only as passive, including via advance directive"],
        ["Non-voluntary", "Patient cannot express wish (coma, PVS)", "Passive allowed with medical boards' approval"],
        ["Involuntary", "Against the patient's expressed wish", "Illegal - homicide"],
        ["Physician-assisted suicide", "Doctor provides means, patient self-administers", "Illegal (abetment of suicide)"],
      ],
    },
    {
      heading: "Kubler-Ross stages of grief (Kaplan and Sadock 12e 2021)",
      columns: ["Stage", "Typical expression", "Clinician response"],
      rows: [
        ["Denial", "This cannot be happening; seeks other opinions", "Allow time; do not force acceptance"],
        ["Anger", "Why me? Directed at staff or family", "Do not take personally; acknowledge feelings"],
        ["Bargaining", "Promises in exchange for more time", "Listen; explore hopes and fears"],
        ["Depression", "Sadness, withdrawal, anticipatory grief", "Support; treat major depression if present"],
        ["Acceptance", "Calm, preparing for death", "Advance care planning, family involvement"],
        ["Caveat", "Stages are not linear or universal", "Prolonged grief disorder (ICD-11) if over 6 months with impairment"],
      ],
    },
    {
      heading: "Cause-of-death classification on MCCD Form 4 (RBD Act 1969; ICD-11)",
      columns: ["Part", "What to write", "Example"],
      rows: [
        ["Part I (a)", "Immediate cause - disease or condition directly leading to death", "Bronchopneumonia"],
        ["Part I (b)", "Antecedent cause giving rise to (a)", "Cerebral infarction"],
        ["Part I (c)", "Underlying cause - disease that started the chain", "Hypertension"],
        ["Part II", "Other significant conditions contributing but not in the chain", "Type 2 diabetes"],
        ["Not acceptable alone", "Mode of dying - cardiac arrest, respiratory failure, old age", "Always name the disease; add interval from onset to death"],
      ],
    },
  ],
};

export default scores;
