import type { NoteTable } from "../../lib/types";

const scores: Record<string, NoteTable[]> = {
  "gynaecology-abnormal-uterine-bleeding": [
    {
      heading: "FIGO PALM-COEIN classification of AUB (FIGO 2018, Berek and Novak 16e)",
      columns: ["Category", "Cause", "Note"],
      rows: [
        ["P - Polyp", "Endometrial or endocervical polyp", "Structural; seen on USG or hysteroscopy"],
        ["A - Adenomyosis", "Endometrial tissue within myometrium", "Structural; USG or MRI features"],
        ["L - Leiomyoma", "Fibroid; subclassified submucous (LSM) or other (LO)", "Use FIGO types 0-8"],
        ["M - Malignancy and hyperplasia", "Endometrial hyperplasia, carcinoma, sarcoma", "Sample endometrium if 45 years or more or risk factors"],
        ["C - Coagulopathy", "Systemic disorders of haemostasis, e.g. von Willebrand disease", "Screen if heavy since menarche"],
        ["O - Ovulatory dysfunction", "PCOS, thyroid, hyperprolactinaemia, extremes of reproductive age", "Irregular unpredictable bleeding"],
        ["E - Endometrial", "Primary endometrial disorder, e.g. local haemostasis defect, endometritis", "Diagnosis of exclusion"],
        ["I - Iatrogenic", "Hormones, IUDs, anticoagulants (moved here in 2018)", "Unscheduled bleeding on medication"],
        ["N - Not otherwise classified", "AV malformation, isthmocele (CS niche)", "Rare or poorly defined"],
      ],
    },
    {
      heading: "FIGO normal menstruation parameters and AUB terminology criteria (FIGO 2018)",
      columns: ["Parameter", "Normal", "Abnormal term"],
      rows: [
        ["Frequency", "24-38 days", "Frequent below 24 days; infrequent above 38 days; absent = amenorrhoea"],
        ["Duration", "8 days or less", "Prolonged: more than 8 days"],
        ["Regularity (shortest to longest cycle)", "Variation 7-9 days or less", "Irregular: variation 10 days or more"],
        ["Volume", "Patient-defined normal", "Heavy menstrual bleeding: interferes with quality of life"],
        ["Intermenstrual bleeding", "None", "Cyclic or random bleeding between periods"],
      ],
    },
    {
      heading: "FIGO 2018 staging of cervical cancer (Berek and Novak 16e, FIGO 2018)",
      columns: ["Stage", "Extent", "Usual primary treatment"],
      rows: [
        ["IA1", "Microscopic invasion, depth below 3 mm", "Conisation or simple hysterectomy"],
        ["IA2", "Microscopic invasion, depth 3 to below 5 mm", "Modified radical hysterectomy plus pelvic nodes"],
        ["IB1", "Invasion 5 mm or more, tumour 2 cm or less", "Radical hysterectomy plus pelvic nodes"],
        ["IB2", "Tumour above 2 cm to 4 cm", "Radical hysterectomy or chemoradiation"],
        ["IB3", "Tumour above 4 cm, confined to cervix", "Concurrent chemoradiation"],
        ["IIA1", "Upper two-thirds of vagina, no parametrium, 4 cm or less", "Radical hysterectomy or chemoradiation"],
        ["IIA2", "Upper two-thirds of vagina, no parametrium, above 4 cm", "Concurrent chemoradiation"],
        ["IIB", "Parametrial invasion, not to pelvic wall", "Concurrent chemoradiation"],
        ["IIIA", "Lower third of vagina, not to pelvic wall", "Concurrent chemoradiation"],
        ["IIIB", "Pelvic wall and/or hydronephrosis or non-functioning kidney", "Concurrent chemoradiation"],
        ["IIIC1", "Pelvic lymph nodes (r = imaging, p = pathology)", "Chemoradiation"],
        ["IIIC2", "Para-aortic lymph nodes", "Extended-field chemoradiation"],
        ["IVA", "Mucosa of bladder or rectum (biopsy proven)", "Chemoradiation"],
        ["IVB", "Distant organs", "Systemic therapy, palliation"],
      ],
    },
    {
      heading: "FIGO 2023 staging of endometrial cancer, simplified (FIGO 2023)",
      columns: ["Stage", "Extent", "Note"],
      rows: [
        ["IA1", "Non-aggressive type limited to polyp or endometrium", "Non-aggressive = low-grade (G1-2) endometrioid"],
        ["IA2", "Non-aggressive, under 50% myometrial invasion, no or focal LVSI", "-"],
        ["IA3", "Low-grade endometrioid in uterus and ovary together", "Treated as two primaries, good prognosis"],
        ["IB", "Non-aggressive, 50% or more myometrial invasion, no or focal LVSI", "-"],
        ["IC", "Aggressive type limited to polyp or endometrium", "Aggressive = G3 endometrioid, serous, clear cell, carcinosarcoma etc"],
        ["IIA", "Non-aggressive, cervical stromal invasion", "-"],
        ["IIB", "Non-aggressive with substantial LVSI", "LVSI now upstages"],
        ["IIC", "Aggressive type with any myometrial invasion", "-"],
        ["IIIA1", "Spread to ovary or fallopian tube (except IA3)", "-"],
        ["IIIA2", "Uterine subserosa or through the serosa", "-"],
        ["IIIB1", "Vagina and/or parametria", "-"],
        ["IIIB2", "Pelvic peritoneum", "-"],
        ["IIIC1", "Pelvic nodes (i micrometastasis, ii macrometastasis)", "-"],
        ["IIIC2", "Para-aortic nodes up to renal vessels, with or without pelvic", "-"],
        ["IVA", "Bladder and/or bowel mucosa", "-"],
        ["IVB", "Abdominal peritoneum beyond pelvis", "-"],
        ["IVC", "Distant metastasis incl. extra-abdominal or inguinal nodes, lung, liver, bone", "-"],
        ["IAm POLEmut", "POLE-mutated, stage I-II, any histology", "Molecular downstaging; excellent prognosis"],
        ["IICm p53abn", "p53-abnormal, stage I-II with myometrial invasion", "Molecular upstaging; poor prognosis"],
      ],
    },
  ],
  "gynaecology-dysmenorrhoea-endometriosis-fibroids": [
    {
      heading: "FIGO leiomyoma subclassification types 0-8 (FIGO 2018)",
      columns: ["Type", "Location", "Usual approach"],
      rows: [
        ["Type 0", "Pedunculated intracavitary", "Hysteroscopic resection"],
        ["Type 1", "Submucous, less than 50% intramural", "Hysteroscopic resection"],
        ["Type 2", "Submucous, 50% or more intramural", "Hysteroscopic (may need two stages) or abdominal"],
        ["Type 3", "Contacts endometrium, 100% intramural", "Myomectomy (laparoscopic or open)"],
        ["Type 4", "Intramural", "Myomectomy if symptomatic"],
        ["Type 5", "Subserous, 50% or more intramural", "Laparoscopic myomectomy"],
        ["Type 6", "Subserous, less than 50% intramural", "Laparoscopic myomectomy"],
        ["Type 7", "Subserous pedunculated", "Laparoscopic removal; risk of torsion"],
        ["Type 8", "Other: cervical, parasitic, broad ligament", "Individualised"],
        ["Hybrid (e.g. 2-5)", "Touches both endometrium and serosa", "Two numbers: submucous then subserous"],
      ],
    },
    {
      heading: "Revised ASRM staging of endometriosis (ASRM 1996, Berek and Novak 16e)",
      columns: ["Stage", "Points", "Typical findings"],
      rows: [
        ["Stage I (minimal)", "1-5", "Few superficial implants"],
        ["Stage II (mild)", "6-15", "More and deeper implants"],
        ["Stage III (moderate)", "16-40", "Many deep implants, small endometrioma, filmy adhesions"],
        ["Stage IV (severe)", "Above 40", "Large endometriomas, dense adhesions, cul-de-sac obliteration"],
        ["Caveat", "Stage correlates poorly with pain", "Better predicts fertility; Enzian or #Enzian describes deep disease"],
      ],
    },
    {
      heading: "Andersch and Milsom grading of dysmenorrhoea severity (Berek and Novak 16e)",
      columns: ["Grade", "Effect on activity", "Analgesic need and systemic symptoms"],
      rows: [
        ["Grade 0", "Not painful; activity unaffected", "No analgesics"],
        ["Grade 1 (mild)", "Painful, rarely inhibits normal activity", "Analgesics rarely needed; no systemic symptoms"],
        ["Grade 2 (moderate)", "Daily activity affected; absence from school or work unusual", "Analgesics needed and effective; few systemic symptoms"],
        ["Grade 3 (severe)", "Activity clearly inhibited", "Poor analgesic response; headache, fatigue, vomiting, diarrhoea"],
      ],
    },
    {
      heading: "IOTA simple rules for adnexal masses - classification (IOTA, RCOG GTG 62)",
      columns: ["Feature", "Description", "Type"],
      rows: [
        ["B1", "Unilocular cyst", "Benign feature"],
        ["B2", "Solid components, largest under 7 mm", "Benign feature"],
        ["B3", "Acoustic shadows", "Benign feature"],
        ["B4", "Smooth multilocular tumour, largest diameter under 100 mm", "Benign feature"],
        ["B5", "No blood flow (colour score 1)", "Benign feature"],
        ["M1", "Irregular solid tumour", "Malignant feature"],
        ["M2", "Ascites", "Malignant feature"],
        ["M3", "At least 4 papillary structures", "Malignant feature"],
        ["M4", "Irregular multilocular solid tumour, largest diameter 100 mm or more", "Malignant feature"],
        ["M5", "Very strong blood flow (colour score 4)", "Malignant feature"],
        ["Rule", "Only B = benign; only M = malignant; both or none = inconclusive", "Inconclusive: expert scan, ADNEX or MRI"],
      ],
    },
    {
      heading: "O-RADS US risk stratification categories - classification (ACR O-RADS US v2022)",
      columns: ["Category", "Risk of malignancy", "Management"],
      rows: [
        ["O-RADS 0", "Incomplete evaluation", "Repeat or alternative imaging"],
        ["O-RADS 1", "Normal premenopausal ovary (follicle or corpus luteum 3 cm or less)", "None"],
        ["O-RADS 2", "Almost certainly benign, below 1%", "None or follow-up USG depending on size and menopause"],
        ["O-RADS 3", "Low risk, 1 to below 10%", "Ultrasound specialist or MRI; gynaecologist"],
        ["O-RADS 4", "Intermediate risk, 10 to below 50%", "MRI or specialist USG; gynae-oncologist involvement"],
        ["O-RADS 5", "High risk, 50% or more", "Gynae-oncologist"],
      ],
    },
    {
      heading: "Risk of Malignancy Index (RMI I) components and risk class (RCOG GTG 34 2016)",
      columns: ["Item", "Definition", "Value or meaning"],
      rows: [
        ["Formula", "RMI = U x M x serum CA-125 (IU/mL)", "Used for postmenopausal ovarian cysts"],
        ["U (ultrasound score)", "1 point each: multilocular, solid areas, metastases, ascites, bilateral", "0 features U=0; 1 feature U=1; 2-5 features U=3"],
        ["M (menopausal status)", "Premenopausal 1; postmenopausal 3", "Postmenopausal: 1 year amenorrhoea or age over 50 after hysterectomy"],
        ["Low risk", "RMI below 25", "About 3% cancer risk; may follow up in primary care"],
        ["Moderate risk", "RMI 25-250", "About 20% risk; manage in gynaecology unit"],
        ["High risk", "RMI above 250", "About 75% risk; refer to gynae-oncology MDT (NICE: 250 or more)"],
      ],
    },
    {
      heading: "FIGO 2014 staging of ovarian, tubal and peritoneal cancer (Berek and Novak 16e)",
      columns: ["Stage", "Extent", "Note"],
      rows: [
        ["IA", "One ovary or tube, capsule intact, no surface tumour, washings negative", "-"],
        ["IB", "Both ovaries or tubes, otherwise as IA", "-"],
        ["IC1", "Surgical spill", "-"],
        ["IC2", "Capsule ruptured before surgery or tumour on surface", "-"],
        ["IC3", "Malignant cells in ascites or peritoneal washings", "-"],
        ["IIA", "Extension to uterus and/or tubes or ovaries", "-"],
        ["IIB", "Extension to other pelvic intraperitoneal tissues", "-"],
        ["IIIA1", "Positive retroperitoneal nodes only (i 10 mm or less, ii above 10 mm)", "-"],
        ["IIIA2", "Microscopic extrapelvic peritoneal involvement", "With or without positive nodes"],
        ["IIIB", "Macroscopic peritoneal metastasis beyond pelvis, 2 cm or less", "-"],
        ["IIIC", "Peritoneal metastasis above 2 cm, incl. liver or spleen capsule", "Most common stage at diagnosis"],
        ["IVA", "Pleural effusion with positive cytology", "-"],
        ["IVB", "Parenchymal and extra-abdominal metastasis, incl. inguinal nodes", "-"],
      ],
    },
  ],
  "gynaecology-cervical-cancer-screening": [
    {
      heading: "Bethesda 2014 classification of cervical cytology with next step (ASCCP 2019)",
      columns: ["Category", "Meaning", "Usual next step"],
      rows: [
        ["Unsatisfactory", "Inadequate cellularity or obscured", "Repeat in 2-4 months"],
        ["NILM", "Negative for intraepithelial lesion or malignancy", "Routine screening"],
        ["ASC-US", "Atypical squamous cells of undetermined significance", "Reflex HPV test; colposcopy if positive"],
        ["ASC-H", "Atypical squamous cells, cannot exclude HSIL", "Colposcopy regardless of HPV"],
        ["LSIL", "Low-grade SIL (HPV effect, CIN 1)", "Colposcopy, or HPV-based follow-up if low risk"],
        ["HSIL", "High-grade SIL (CIN 2, CIN 3)", "Colposcopy or expedited excision (LEEP) if 25 or older"],
        ["SCC", "Squamous cell carcinoma", "Colposcopy, biopsy, oncology referral"],
        ["AGC", "Atypical glandular cells (NOS or favour neoplastic)", "Colposcopy, endocervical sampling; endometrial sampling if 35 or older"],
        ["AIS", "Endocervical adenocarcinoma in situ", "Diagnostic excision (cold knife cone preferred)"],
        ["Adenocarcinoma", "Endocervical, endometrial or extrauterine", "Oncology referral"],
      ],
    },
    {
      heading: "Swede score for colposcopic assessment (IFCPC, Strander 2005)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Acetowhite uptake", "None or transparent", "0"],
        ["Acetowhite uptake", "Shady, milky (not transparent, not opaque)", "1"],
        ["Acetowhite uptake", "Distinct, opaque white", "2"],
        ["Margins and surface", "None or diffuse", "0"],
        ["Margins and surface", "Sharp but irregular, jagged, satellite lesions", "1"],
        ["Margins and surface", "Sharp and even, difference in surface level (cuffing)", "2"],
        ["Vessels", "Fine, regular", "0"],
        ["Vessels", "Absent", "1"],
        ["Vessels", "Coarse or atypical", "2"],
        ["Lesion size", "Below 5 mm", "0"],
        ["Lesion size", "5-15 mm or 2 quadrants", "1"],
        ["Lesion size", "Above 15 mm, 3-4 quadrants, or endocervically undefined", "2"],
        ["Iodine staining", "Brown", "0"],
        ["Iodine staining", "Faintly or patchy yellow", "1"],
        ["Iodine staining", "Distinct yellow", "2"],
      ],
    },
    {
      heading: "Swede score - interpretation",
      columns: ["Total (max 10)", "Likely lesion", "Action"],
      rows: [
        ["0-4", "Low grade or normal", "Biopsy if doubt; follow-up"],
        ["5-7", "Possible high grade", "Directed biopsy"],
        ["8-10", "High-grade lesion (CIN 2+) likely", "See-and-treat excision acceptable"],
      ],
    },
    {
      heading: "Reid colposcopic index (modified) for grading lesions (Berek and Novak 16e)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Margin", "Condylomatous, micropapillary, indistinct or feathered, satellite lesions", "0"],
        ["Margin", "Regular smooth straight outline, sharp margins", "1"],
        ["Margin", "Rolled peeling edges, internal demarcation", "2"],
        ["Colour", "Shiny snow-white or faint acetowhitening", "0"],
        ["Colour", "Intermediate shiny grey-white", "1"],
        ["Colour", "Dull oyster white", "2"],
        ["Vessels", "Fine calibre, uniform", "0"],
        ["Vessels", "Absent", "1"],
        ["Vessels", "Definite coarse punctation or mosaic", "2"],
        ["Iodine", "Positive mahogany brown", "0"],
        ["Iodine", "Partial uptake, mottled", "1"],
        ["Iodine", "Negative, mustard yellow in a significant lesion", "2"],
      ],
    },
    {
      heading: "Reid colposcopic index - interpretation",
      columns: ["Total (max 8)", "Predicted histology", "Action"],
      rows: [
        ["0-2", "Likely CIN 1 or HPV change", "Follow-up or biopsy if doubt"],
        ["3-4", "Overlapping, CIN 1-2", "Biopsy"],
        ["5-8", "Likely CIN 2-3", "Biopsy and treat"],
      ],
    },
    {
      heading: "IFCPC 2011 transformation zone types and excision types",
      columns: ["Type", "Transformation zone", "Matching excision"],
      rows: [
        ["Type 1", "Completely ectocervical, fully visible", "Type 1 excision, 7-10 mm length"],
        ["Type 2", "Has endocervical component, fully visible", "Type 2 excision, 10-15 mm length"],
        ["Type 3", "Endocervical component not fully visible", "Type 3 excision, 15-25 mm; colposcopy unsatisfactory"],
      ],
    },
  ],
  "gynaecology-infertility-workup": [
    {
      heading: "WHO 2021 semen analysis lower reference limits criteria (WHO manual 6e 2021)",
      columns: ["Parameter", "Lower reference limit (5th centile)", "Term if below"],
      rows: [
        ["Semen volume", "1.4 mL", "Hypospermia"],
        ["Total sperm number", "39 million per ejaculate", "Oligozoospermia (none = azoospermia)"],
        ["Sperm concentration", "16 million per mL", "Oligozoospermia"],
        ["Total motility (PR + NP)", "42%", "Asthenozoospermia"],
        ["Progressive motility (PR)", "30%", "Asthenozoospermia"],
        ["Vitality (live forms)", "54%", "Necrozoospermia"],
        ["Normal morphology", "4%", "Teratozoospermia"],
        ["pH", "7.2 or more", "Low pH with low volume suggests duct obstruction"],
      ],
    },
    {
      heading: "WHO classification of ovulatory disorders (ESHRE, Berek and Novak 16e)",
      columns: ["Group", "Hormone profile", "Examples and treatment"],
      rows: [
        ["WHO Group I", "Hypogonadotropic hypogonadism: low FSH, LH, oestradiol", "Hypothalamic amenorrhoea; pulsatile GnRH or gonadotropins"],
        ["WHO Group II", "Normogonadotropic normo-oestrogenic anovulation", "PCOS (about 85%); letrozole first line"],
        ["WHO Group III", "Hypergonadotropic hypo-oestrogenic: high FSH", "Premature ovarian insufficiency; donor oocytes"],
        ["Hyperprolactinaemia", "Raised prolactin (sometimes listed as group IV)", "Dopamine agonist"],
      ],
    },
    {
      heading: "OHSS severity classification (RCOG GTG 5 2016)",
      columns: ["Grade", "Clinical features", "Laboratory and USG", "Care"],
      rows: [
        ["Mild", "Abdominal bloating, mild pain", "Ovaries usually below 8 cm", "Outpatient, oral fluids, analgesia"],
        ["Moderate", "Moderate pain, nausea with or without vomiting", "Ascites on USG; ovaries 8-12 cm", "Outpatient with close review"],
        ["Severe", "Clinical ascites, oliguria, occasional hydrothorax", "Hct above 45%, Na below 135, K above 5, albumin below 35 g/L", "Admit; thromboprophylaxis, fluid balance"],
        ["Critical", "Tense ascites, large hydrothorax, oligo-anuria, VTE, ARDS", "Hct above 55%, WBC above 25,000", "ICU care"],
      ],
    },
    {
      heading: "AFS classification of intrauterine adhesions (Asherman) (AFS 1988)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Extent of cavity involved", "Less than one-third", "1"],
        ["Extent of cavity involved", "One-third to two-thirds", "2"],
        ["Extent of cavity involved", "More than two-thirds", "4"],
        ["Type of adhesions", "Filmy", "1"],
        ["Type of adhesions", "Filmy and dense", "2"],
        ["Type of adhesions", "Dense", "4"],
        ["Menstrual pattern", "Normal", "0"],
        ["Menstrual pattern", "Hypomenorrhoea", "2"],
        ["Menstrual pattern", "Amenorrhoea", "4"],
      ],
    },
    {
      heading: "AFS intrauterine adhesion score stages",
      columns: ["Total", "Stage", "Prognosis"],
      rows: [
        ["1-4", "Stage I (mild)", "Good after hysteroscopic adhesiolysis"],
        ["5-8", "Stage II (moderate)", "Fair"],
        ["9-12", "Stage III (severe)", "Poor; recurrence common"],
      ],
    },
  ],
  "gynaecology-pcos": [
    {
      heading: "Ferriman-Gallwey grading of hair at each body area (2023 PCOS guideline)",
      columns: ["Grade", "Terminal hair at the area", "Example: upper lip"],
      rows: [
        ["Grade 0", "No terminal hair", "None"],
        ["Grade 1", "Minimal", "Few hairs at outer margin"],
        ["Grade 2", "Mild", "Small moustache at outer margin"],
        ["Grade 3", "Moderate", "Moustache extending halfway from outer margin"],
        ["Grade 4", "Marked, male pattern", "Moustache extending to midline"],
      ],
    },
    {
      heading: "Modified Ferriman-Gallwey score use and cut-off criteria (2023 PCOS guideline)",
      columns: ["Item", "Detail", "Meaning"],
      rows: [
        ["Areas scored (9)", "Upper lip, chin, chest, upper and lower abdomen, upper arm, thigh, upper and lower back", "Each 0-4; total 0-36"],
        ["Hirsutism cut-off", "4-6 or more, depending on ethnicity", "2023 international PCOS guideline"],
        ["Traditional cut-off", "8 or more", "Older Western threshold; underdiagnoses in South Asians"],
        ["Caveat", "Self-treated hair removal lowers score", "Ask about shaving, waxing, threading"],
      ],
    },
  ],
  "gynaecology-vaginal-discharge-pid": [
    {
      heading: "Amsel criteria for bacterial vaginosis (CDC STI 2021, BASHH)",
      columns: ["Criterion", "Finding", "Note"],
      rows: [
        ["Criterion 1", "Thin, homogeneous grey-white discharge coating vaginal walls", "3 of 4 criteria needed"],
        ["Criterion 2", "Vaginal pH above 4.5", "Most sensitive, least specific"],
        ["Criterion 3", "Positive whiff test: fishy amine odour with 10% KOH", "-"],
        ["Criterion 4", "Clue cells over 20% of epithelial cells on wet mount", "Most specific"],
      ],
    },
    {
      heading: "Nugent score for bacterial vaginosis on Gram stain (CDC STI 2021)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Lactobacillus morphotypes (per oil field)", "4+ (more than 30)", "0"],
        ["Lactobacillus morphotypes (per oil field)", "3+ (5-30)", "1"],
        ["Lactobacillus morphotypes (per oil field)", "2+ (1-4)", "2"],
        ["Lactobacillus morphotypes (per oil field)", "1+ (less than 1)", "3"],
        ["Lactobacillus morphotypes (per oil field)", "0 (none)", "4"],
        ["Gardnerella and Bacteroides morphotypes", "0 (none)", "0"],
        ["Gardnerella and Bacteroides morphotypes", "1+ (less than 1)", "1"],
        ["Gardnerella and Bacteroides morphotypes", "2+ (1-4)", "2"],
        ["Gardnerella and Bacteroides morphotypes", "3+ (5-30)", "3"],
        ["Gardnerella and Bacteroides morphotypes", "4+ (more than 30)", "4"],
        ["Curved gram-variable rods (Mobiluncus)", "0 (none)", "0"],
        ["Curved gram-variable rods (Mobiluncus)", "1+ or 2+", "1"],
        ["Curved gram-variable rods (Mobiluncus)", "3+ or 4+", "2"],
      ],
    },
    {
      heading: "Nugent score - interpretation",
      columns: ["Total (max 10)", "Meaning", "Note"],
      rows: [
        ["0-3", "Normal lactobacillary flora", "-"],
        ["4-6", "Intermediate flora", "Interpret with Amsel criteria"],
        ["7-10", "Bacterial vaginosis", "Gold standard in research"],
      ],
    },
    {
      heading: "Hay-Ison grading of vaginal flora on Gram stain (BASHH 2012)",
      columns: ["Grade", "Smear appearance", "Meaning"],
      rows: [
        ["Grade 0", "Epithelial cells only, no lactobacilli", "Often after antibiotics"],
        ["Grade 1", "Lactobacilli predominate", "Normal"],
        ["Grade 2", "Mixed flora, some lactobacilli with Gardnerella or Mobiluncus", "Intermediate"],
        ["Grade 3", "Mainly Gardnerella and/or Mobiluncus, few or no lactobacilli", "Bacterial vaginosis"],
        ["Grade 4", "Gram-positive cocci only, no lactobacilli", "Not BV; e.g. aerobic vaginitis"],
      ],
    },
    {
      heading: "CDC diagnostic criteria for pelvic inflammatory disease (CDC STI 2021)",
      columns: ["Level", "Criteria", "Use"],
      rows: [
        ["Minimum criteria", "Cervical motion tenderness, or uterine tenderness, or adnexal tenderness", "Start empirical treatment in sexually active women with pelvic pain"],
        ["Supportive 1", "Oral temperature above 38.3 C", "Raises specificity"],
        ["Supportive 2", "Mucopurulent cervical discharge or cervical friability", "-"],
        ["Supportive 3", "Abundant WBC on saline microscopy of vaginal fluid", "Absence makes PID unlikely"],
        ["Supportive 4", "Raised ESR or CRP", "-"],
        ["Supportive 5", "Lab-confirmed gonorrhoea or chlamydia", "-"],
        ["Definitive", "Endometritis on biopsy, thick fluid-filled tubes or TOA on imaging, laparoscopic findings", "Only in selected cases"],
        ["Admit if", "Surgical emergency not excluded, TOA, pregnancy, severe illness, oral failure", "Parenteral regimen"],
      ],
    },
    {
      heading: "NACO colour-coded STI/RTI syndromic kit classification (NACO STI/RTI technical guidelines)",
      columns: ["Kit", "Syndrome", "Drugs in kit"],
      rows: [
        ["Kit 1 - Grey", "Urethral discharge, cervicitis, painful scrotal swelling", "Azithromycin plus cefixime"],
        ["Kit 2 - Green", "Vaginal discharge (vaginitis)", "Secnidazole plus fluconazole"],
        ["Kit 3 - White", "Genital ulcer disease, non-herpetic", "Benzathine penicillin plus azithromycin"],
        ["Kit 4 - Blue", "Genital ulcer disease, non-herpetic, penicillin allergy", "Doxycycline plus azithromycin"],
        ["Kit 5 - Red", "Genital ulcer disease, herpetic", "Acyclovir"],
        ["Kit 6 - Yellow", "Lower abdominal pain (PID)", "Cefixime, metronidazole plus doxycycline"],
        ["Kit 7 - Black", "Inguinal bubo", "Doxycycline plus azithromycin"],
      ],
    },
  ],
  "gynaecology-contraception": [
    {
      heading: "Contraceptive effectiveness tiers classification (WHO FP handbook 2022)",
      columns: ["Tier", "Methods", "Pregnancies per 100 women in first year, typical use"],
      rows: [
        ["Tier 1 - most effective", "Implant, LNG-IUS, copper IUD, female and male sterilisation", "Less than 1"],
        ["Tier 2 - effective", "Injectables (DMPA), combined and progestogen-only pills, patch, ring, LAM", "About 4-7 (injectable about 4, pill about 7)"],
        ["Tier 3 - less effective", "Male and female condom, diaphragm, fertility awareness, withdrawal", "About 13-20 or more"],
        ["Tier 4 - least effective", "Spermicides", "About 21"],
        ["Pearl index", "Failures x 1200 / total months of exposure (or x 1300 / cycles)", "Pregnancies per 100 woman-years"],
      ],
    },
  ],
  "gynaecology-menopause-hormone-therapy": [
    {
      heading: "STRAW+10 staging of reproductive ageing (STRAW+10 2012, Berek and Novak 16e)",
      columns: ["Stage", "Phase", "Defining criteria"],
      rows: [
        ["-5, -4, -3b", "Reproductive: early, peak, late", "Regular cycles; late stage FSH still normal, AMH low"],
        ["-3a", "Late reproductive", "Subtle changes in flow or length; variable FSH"],
        ["-2", "Early menopausal transition", "Persistent 7-day or more difference in consecutive cycle length"],
        ["-1", "Late menopausal transition", "Amenorrhoea of 60 days or more; FSH above 25 IU/L; vasomotor symptoms"],
        ["0", "Final menstrual period", "Confirmed after 12 months of amenorrhoea"],
        ["+1a, +1b", "Early postmenopause (first 2 years)", "FSH rising, vasomotor symptoms most likely"],
        ["+1c", "Early postmenopause (3-6 years)", "Stabilised high FSH, low AMH"],
        ["+2", "Late postmenopause", "Urogenital atrophy symptoms increase"],
      ],
    },
    {
      heading: "Menopause Rating Scale items (MRS, Heinemann 2004)",
      columns: ["Subscale", "Items (each 0-4)", "Subscale range"],
      rows: [
        ["Somatic", "Hot flushes and sweating, heart discomfort, sleep problems, joint and muscle discomfort", "0-16"],
        ["Psychological", "Depressive mood, irritability, anxiety, physical and mental exhaustion", "0-16"],
        ["Urogenital", "Sexual problems, bladder problems, vaginal dryness", "0-12"],
      ],
    },
    {
      heading: "Menopause Rating Scale total score severity (MRS, Heinemann 2004)",
      columns: ["Total (0-44)", "Severity", "Implication"],
      rows: [
        ["0-4", "None or little", "Reassure, lifestyle"],
        ["5-8", "Mild", "Lifestyle, non-hormonal options"],
        ["9-16", "Moderate", "Consider MHT if no contraindication"],
        ["17 or more", "Severe", "MHT usually indicated if eligible"],
      ],
    },
  ],
  "gynaecology-uterine-prolapse": [
    {
      heading: "Baden-Walker halfway grading of pelvic organ prolapse (Berek and Novak 16e)",
      columns: ["Grade", "Most dependent point at maximum strain", "Note"],
      rows: [
        ["Grade 0", "Normal position", "-"],
        ["Grade 1", "Descent halfway to the hymen", "-"],
        ["Grade 2", "Descent to the hymen", "-"],
        ["Grade 3", "Descent halfway past the hymen", "-"],
        ["Grade 4", "Maximum possible descent (procidentia)", "Replaced by POP-Q for research"],
      ],
    },
    {
      heading: "Shaw clinical grading of uterine prolapse by degree (Shaw's Gynaecology 17e 2018)",
      columns: ["Degree", "Position of cervix", "Usual management"],
      rows: [
        ["First degree", "Cervix descends but stays within the vagina", "Pelvic floor exercises, pessary"],
        ["Second degree", "Cervix reaches or protrudes through the introitus, body inside", "Pessary or surgery by age and wishes"],
        ["Third degree (procidentia)", "Whole uterus outside the introitus, with vaginal eversion", "Surgery; heal decubitus ulcer first (packing, oestrogen)"],
      ],
    },
  ],
};

export default scores;
