import type { NoteTable } from "../../lib/types";

const scores: Record<string, NoteTable[]> = {
  "neurology-headache": [
    {
      heading: "ICHD-3 criteria for tension-type headache (ICHD-3 2018)",
      columns: ["Criterion", "Requirement", "Note"],
      rows: [
        ["A - frequency (infrequent episodic)", "At least 10 episodes on under 1 day/month on average (under 12 days/year)", "Frequent episodic: 1-14 days/month for over 3 months (12 to under 180 days/year)"],
        ["A - frequency (chronic)", "15 or more days/month on average for over 3 months (180 or more days/year)", "Chronic TTH: hours to days, or unremitting; think medication overuse"],
        ["B - duration", "Episode lasts 30 minutes to 7 days", "Chronic form: hours to days or continuous"],
        ["C - character (2 of 4)", "Bilateral; pressing or tightening (non-pulsating); mild or moderate; not worsened by routine activity", "Contrast migraine: unilateral, pulsating, moderate-severe, worse with activity"],
        ["D - associated (both)", "No nausea or vomiting; no more than one of photophobia or phonophobia", "Chronic TTH allows one of photophobia, phonophobia or mild nausea only"],
        ["E - exclusion", "Not better accounted for by another ICHD-3 diagnosis", "Pericranial tenderness on palpation is a supportive subtype marker"],
      ],
    },
    {
      heading: "ICHD-3 criteria for cluster headache (ICHD-3 2018)",
      columns: ["Criterion", "Requirement", "Note"],
      rows: [
        ["A - number", "At least 5 attacks fulfilling B-D", "Commoner in men, smokers; circadian and circannual periodicity"],
        ["B - pain", "Severe or very severe unilateral orbital, supraorbital and/or temporal pain for 15-180 minutes untreated", "Strictly side-locked in most patients"],
        ["C1 - ipsilateral autonomic", "At least one: conjunctival injection or lacrimation; nasal congestion or rhinorrhoea; eyelid oedema", "Also: forehead and facial sweating; miosis and/or ptosis (partial Horner)"],
        ["C2 - behaviour", "A sense of restlessness or agitation (either C1 or C2 or both suffices)", "Patient paces or rocks - migraineurs lie still"],
        ["D - frequency", "From one every other day to 8 per day", "Acute: 100% oxygen 12-15 L/min, SC sumatriptan 6 mg; prevention verapamil"],
        ["E - exclusion", "Not better accounted for by another ICHD-3 diagnosis", "Episodic: bouts 7 days-1 year, remission 3 months or more; chronic: remission under 3 months"],
      ],
    },
    {
      heading: "ICHD-3 criteria for medication-overuse headache (ICHD-3 2018)",
      columns: ["Criterion", "Requirement", "Note"],
      rows: [
        ["A - headache days", "Headache on 15 or more days/month in a patient with a pre-existing headache disorder", "Usually migraine or tension-type headache"],
        ["B - overuse for over 3 months", "Regular overuse of one or more acute or symptomatic headache drugs", "Thresholds below are days of use per month"],
        ["Simple analgesics", "Paracetamol, aspirin or other NSAID on 15 or more days/month", "Total of all non-opioid simple analgesics"],
        ["Triptans, ergots, opioids", "10 or more days/month", "Also combination analgesics and any combination of drug classes"],
        ["C - exclusion", "Not better accounted for by another ICHD-3 diagnosis", "Treat by withdrawal of the overused drug plus starting prophylaxis"],
      ],
    },
    {
      heading: "MIDAS grading of migraine disability (AHS consensus 2021)",
      columns: ["Grade", "MIDAS total (days lost in 3 months)", "Meaning and action"],
      rows: [
        ["Grade I", "0-5", "Little or no disability - simple analgesics or NSAID for attacks"],
        ["Grade II", "6-10", "Mild disability - NSAID or triptan; consider preventive if frequent"],
        ["Grade III", "11-20", "Moderate disability - triptan for attacks; preventive therapy indicated"],
        ["Grade IV", "21 or more", "Severe disability - triptan plus preventive therapy; review medication overuse"],
      ],
    },
  ],
  "neurology-stroke-acute": [
    {
      heading: "NIH Stroke Scale (NIHSS) for acute stroke severity (AHA/ASA 2019)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["1a Level of consciousness", "Alert, keenly responsive", "0"],
        ["1a Level of consciousness", "Not alert, rousable by minor stimulation", "1"],
        ["1a Level of consciousness", "Not alert, needs repeated or painful stimulation", "2"],
        ["1a Level of consciousness", "Reflex responses only or unresponsive", "3"],
        ["1b LOC questions (month, age)", "Both correct", "0"],
        ["1b LOC questions (month, age)", "One correct (or intubated, dysarthric)", "1"],
        ["1b LOC questions (month, age)", "Neither correct", "2"],
        ["1c LOC commands (eyes, grip)", "Performs both", "0"],
        ["1c LOC commands (eyes, grip)", "Performs one", "1"],
        ["1c LOC commands (eyes, grip)", "Performs neither", "2"],
        ["2 Best gaze", "Normal", "0"],
        ["2 Best gaze", "Partial gaze palsy", "1"],
        ["2 Best gaze", "Forced deviation or total gaze paresis", "2"],
        ["3 Visual fields", "No visual loss", "0"],
        ["3 Visual fields", "Partial hemianopia", "1"],
        ["3 Visual fields", "Complete hemianopia", "2"],
        ["3 Visual fields", "Bilateral hemianopia (including cortical blindness)", "3"],
        ["4 Facial palsy", "Normal symmetrical movement", "0"],
        ["4 Facial palsy", "Minor (flattened nasolabial fold, asymmetric smile)", "1"],
        ["4 Facial palsy", "Partial (near-total lower face paralysis)", "2"],
        ["4 Facial palsy", "Complete (upper and lower face) on one or both sides", "3"],
        ["5 Motor arm (each arm, 10 s)", "No drift", "0"],
        ["5 Motor arm (each arm, 10 s)", "Drift but does not hit bed", "1"],
        ["5 Motor arm (each arm, 10 s)", "Some effort against gravity", "2"],
        ["5 Motor arm (each arm, 10 s)", "No effort against gravity, limb falls", "3"],
        ["5 Motor arm (each arm, 10 s)", "No movement", "4"],
        ["6 Motor leg (each leg, 5 s)", "No drift", "0"],
        ["6 Motor leg (each leg, 5 s)", "Drift but does not hit bed", "1"],
        ["6 Motor leg (each leg, 5 s)", "Some effort against gravity", "2"],
        ["6 Motor leg (each leg, 5 s)", "No effort against gravity", "3"],
        ["6 Motor leg (each leg, 5 s)", "No movement", "4"],
        ["7 Limb ataxia", "Absent (also scored 0 if paralysed or cannot understand)", "0"],
        ["7 Limb ataxia", "Present in one limb", "1"],
        ["7 Limb ataxia", "Present in two limbs", "2"],
        ["8 Sensory", "Normal", "0"],
        ["8 Sensory", "Mild to moderate loss", "1"],
        ["8 Sensory", "Severe to total loss", "2"],
        ["9 Best language", "No aphasia", "0"],
        ["9 Best language", "Mild to moderate aphasia", "1"],
        ["9 Best language", "Severe aphasia", "2"],
        ["9 Best language", "Mute, global aphasia (or coma)", "3"],
        ["10 Dysarthria", "Normal", "0"],
        ["10 Dysarthria", "Mild to moderate, slurred but understood", "1"],
        ["10 Dysarthria", "Severe, unintelligible or mute", "2"],
        ["11 Extinction and inattention", "No abnormality", "0"],
        ["11 Extinction and inattention", "Inattention or extinction in one modality", "1"],
        ["11 Extinction and inattention", "Profound hemi-inattention or in more than one modality", "2"],
      ],
    },
    {
      heading: "NIHSS severity bands (total 0-42)",
      columns: ["NIHSS total", "Severity", "Implication"],
      rows: [
        ["0", "No measurable deficit", "Still treat as stroke or TIA if clinical picture fits"],
        ["1-4", "Minor stroke", "Thrombolyse only if deficit is disabling; else dual antiplatelet (CHANCE/POINT)"],
        ["5-15", "Moderate stroke", "Thrombolysis within 4.5 h if eligible; NIHSS 6+ with LVO - thrombectomy"],
        ["16-20", "Moderate to severe stroke", "Thrombolysis plus CTA for thrombectomy; aspiration and oedema risk"],
        ["21-42", "Severe stroke", "High mortality; watch malignant oedema, early goals-of-care discussion"],
      ],
    },
    {
      heading: "Modified Rankin Scale (mRS) of disability after stroke (AHA/ASA 2019)",
      columns: ["Grade", "Description", "Use"],
      rows: [
        ["mRS 0", "No symptoms at all", "Excellent outcome"],
        ["mRS 1", "No significant disability despite symptoms; carries out all usual duties and activities", "Excellent outcome (mRS 0-1)"],
        ["mRS 2", "Slight disability; cannot do all previous activities but looks after own affairs unaided", "Functional independence (mRS 0-2) - usual trial endpoint"],
        ["mRS 3", "Moderate disability; needs some help but walks without assistance", "Pre-stroke mRS 3 or more often excluded from thrombectomy trials"],
        ["mRS 4", "Moderately severe; cannot walk or attend to bodily needs without assistance", "Dependent"],
        ["mRS 5", "Severe; bedridden, incontinent, needs constant nursing care and attention", "Dependent"],
        ["mRS 6", "Dead", "Mortality endpoint"],
      ],
    },
    {
      heading: "Oxford (Bamford) OCSP classification of ischaemic stroke (OHCM 11e 2024)",
      columns: ["Class", "Clinical features", "Territory and prognosis"],
      rows: [
        ["TACS - total anterior circulation", "All 3: higher cortical dysfunction; homonymous hemianopia; motor/sensory deficit in 2 of face, arm, leg", "Large MCA or ICA; worst - about 60% dead at 1 year, most survivors dependent"],
        ["PACS - partial anterior circulation", "2 of the 3 TACS features, or higher cortical dysfunction alone", "Branch MCA; high early recurrence risk"],
        ["LACS - lacunar", "Pure motor, pure sensory, sensorimotor, or ataxic hemiparesis; no cortical signs, no field defect", "Small perforating arteries; lowest mortality"],
        ["POCS - posterior circulation", "CN palsy with contralateral long tract signs; bilateral deficit; gaze palsy; cerebellar; isolated hemianopia", "Vertebrobasilar; best functional recovery"],
      ],
    },
    {
      heading: "TOAST classification of ischaemic stroke subtype (Harrison 22e 2025)",
      columns: ["Subtype", "Definition", "Typical work-up clue and prevention"],
      rows: [
        ["Large-artery atherosclerosis", "Over 50% stenosis or occlusion of a relevant extracranial or intracranial artery", "Carotid Doppler/CTA; endarterectomy if symptomatic 50-99% stenosis"],
        ["Cardioembolism", "At least one high-risk cardiac source (AF, LV thrombus, mechanical valve, recent MI, endocarditis)", "ECG, Holter, echo; anticoagulation for AF"],
        ["Small-vessel occlusion (lacunar)", "Lacunar syndrome with infarct under 1.5 cm in deep perforator territory", "Hypertension, diabetes; antiplatelet and strict BP control"],
        ["Other determined aetiology", "Dissection, vasculitis, hypercoagulable state, CVT, drugs, genetic arteriopathy", "Think in the young stroke patient"],
        ["Undetermined aetiology", "Two or more competing causes, negative work-up, or incomplete work-up", "Embolic stroke of undetermined source (ESUS) sits here"],
      ],
    },
    {
      heading: "ROSIER scale for recognising stroke in the emergency room (NICE NG128 2022)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Loss of consciousness or syncope", "Present", "-1"],
        ["Seizure activity", "Present", "-1"],
        ["Asymmetric facial weakness", "Present", "1"],
        ["Asymmetric arm weakness", "Present", "1"],
        ["Asymmetric leg weakness", "Present", "1"],
        ["Speech disturbance", "Present", "1"],
        ["Visual field defect", "Present", "1"],
      ],
    },
    {
      heading: "ROSIER score - interpretation (range -2 to +5)",
      columns: ["ROSIER total", "Meaning", "Action"],
      rows: [
        ["1 to 5", "Stroke likely", "Stroke pathway, urgent CT, consider thrombolysis window"],
        ["0 or below", "Stroke unlikely but not excluded", "Seek mimics; check capillary glucose first (below 3.5 mmol/L treat and reassess)"],
      ],
    },
    {
      heading: "BE-FAST criteria for prehospital stroke recognition (AHA/ASA 2019)",
      columns: ["Letter", "Check", "Positive finding"],
      rows: [
        ["B - Balance", "Sudden loss of balance or coordination", "Adds posterior circulation strokes missed by FAST"],
        ["E - Eyes", "Sudden loss of vision in one or both eyes, or double vision", "Field loss or diplopia"],
        ["F - Face", "Ask to smile", "One side droops"],
        ["A - Arm", "Raise both arms for 10 seconds", "One arm drifts down"],
        ["S - Speech", "Repeat a simple sentence", "Slurred, strange or absent speech"],
        ["T - Time", "Note the time last known well", "Call ambulance (108 in India) - time is brain"],
      ],
    },
    {
      heading: "ICH score for 30-day mortality in intracerebral haemorrhage (AHA/ASA 2022)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Glasgow Coma Scale", "13-15", "0"],
        ["Glasgow Coma Scale", "5-12", "1"],
        ["Glasgow Coma Scale", "3-4", "2"],
        ["ICH volume (ABC/2)", "Under 30 mL", "0"],
        ["ICH volume (ABC/2)", "30 mL or more", "1"],
        ["Intraventricular extension", "No", "0"],
        ["Intraventricular extension", "Yes", "1"],
        ["Infratentorial origin", "No", "0"],
        ["Infratentorial origin", "Yes", "1"],
        ["Age", "Under 80 years", "0"],
        ["Age", "80 years or more", "1"],
      ],
    },
    {
      heading: "ICH score - 30-day mortality bands",
      columns: ["ICH score", "30-day mortality", "Comment"],
      rows: [
        ["0", "About 0%", "Full active care"],
        ["1", "About 13%", "Full active care"],
        ["2", "About 26%", "Full active care"],
        ["3", "About 72%", "Discuss goals; avoid early DNAR self-fulfilling prophecy"],
        ["4", "About 97%", "AHA 2022: do not use the score alone to limit care"],
        ["5-6", "About 100%", "Palliative focus usually appropriate"],
      ],
    },
    {
      heading: "Hunt and Hess grading of subarachnoid haemorrhage (AHA/ASA 2023 aSAH)",
      columns: ["Grade", "Clinical picture", "Implication"],
      rows: [
        ["Grade I", "Asymptomatic, or minimal headache and slight neck stiffness", "Good grade - early aneurysm securing"],
        ["Grade II", "Moderate to severe headache, neck stiffness, no deficit other than cranial nerve palsy", "Good grade"],
        ["Grade III", "Drowsiness, confusion or mild focal deficit", "Intermediate grade"],
        ["Grade IV", "Stupor, moderate to severe hemiparesis, possible early decerebrate rigidity", "Poor grade"],
        ["Grade V", "Deep coma, decerebrate rigidity, moribund appearance", "Poor grade - highest mortality"],
      ],
    },
    {
      heading: "WFNS grading of subarachnoid haemorrhage (AHA/ASA 2023 aSAH)",
      columns: ["Grade", "GCS", "Motor deficit"],
      rows: [
        ["WFNS I", "15", "Absent"],
        ["WFNS II", "13-14", "Absent"],
        ["WFNS III", "13-14", "Present"],
        ["WFNS IV", "7-12", "Present or absent"],
        ["WFNS V", "3-6", "Present or absent"],
      ],
    },
    {
      heading: "Modified Fisher CT grading of SAH for vasospasm risk (AHA/ASA 2023 aSAH)",
      columns: ["Grade", "CT appearance", "Delayed cerebral ischaemia risk"],
      rows: [
        ["Grade 0", "No SAH, no intraventricular haemorrhage (IVH)", "Lowest"],
        ["Grade 1", "Thin (focal or diffuse) SAH, no IVH", "Low"],
        ["Grade 2", "Thin SAH with IVH", "Moderate"],
        ["Grade 3", "Thick SAH, no IVH", "Moderate to high"],
        ["Grade 4", "Thick SAH with IVH", "Highest - nimodipine 60 mg 4-hourly for 21 days in all"],
      ],
    },
    {
      heading: "Spetzler-Martin grading of brain arteriovenous malformations (Harrison 22e 2025)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Nidus size", "Small, under 3 cm", "1"],
        ["Nidus size", "Medium, 3-6 cm", "2"],
        ["Nidus size", "Large, over 6 cm", "3"],
        ["Eloquence of adjacent brain", "Non-eloquent", "0"],
        ["Eloquence of adjacent brain", "Eloquent (sensorimotor, language, visual, thalamus, brainstem)", "1"],
        ["Venous drainage", "Superficial only", "0"],
        ["Venous drainage", "Any deep drainage", "1"],
      ],
    },
    {
      heading: "Spetzler-Martin grade - interpretation",
      columns: ["Grade (sum)", "Surgical risk", "Usual management"],
      rows: [
        ["Grade I-II", "Low", "Microsurgical resection"],
        ["Grade III", "Intermediate", "Individualised - surgery, radiosurgery, embolisation or combination"],
        ["Grade IV-V", "High", "Usually conservative unless haemorrhage recurs or progressive deficit"],
        ["Grade VI", "Inoperable", "Diffuse or brainstem-involving lesion"],
      ],
    },
    {
      heading: "Modified Ashworth Scale for spasticity (Harrison 22e 2025)",
      columns: ["Grade", "Muscle tone on passive movement", "Note"],
      rows: [
        ["0", "No increase in tone", "Normal"],
        ["1", "Slight increase - catch and release, or minimal resistance at end of range", "Mild"],
        ["1+", "Slight increase - catch, then minimal resistance through less than half the range", "Mild"],
        ["2", "More marked increase through most of the range, but limb easily moved", "Moderate"],
        ["3", "Considerable increase; passive movement difficult", "Severe - consider botulinum toxin, baclofen"],
        ["4", "Affected part rigid in flexion or extension", "Contracture risk"],
      ],
    },
  ],
  "neurology-vertigo": [
    {
      heading: "HINTS criteria - peripheral vs central acute vestibular syndrome (Tintinalli 9e 2020)",
      columns: ["Test", "Reassuring (peripheral, vestibular neuritis)", "Dangerous (central, stroke) - INFARCT"],
      rows: [
        ["Head Impulse", "Abnormal - corrective catch-up saccade to the affected side", "Normal head impulse in an acutely vertiginous patient"],
        ["Nystagmus", "Unidirectional, horizontal-torsional, fast phase away from lesion", "Direction-changing on eccentric gaze, or pure vertical or torsional"],
        ["Test of Skew", "No vertical refixation on alternate cover", "Skew deviation present"],
        ["Plus - hearing", "Hearing preserved (labyrinthitis may reduce it)", "New unilateral hearing loss can mean AICA infarct"],
        ["Who it applies to", "Continuous vertigo, nystagmus present, for hours to days", "Not for episodic positional vertigo (use Dix-Hallpike) - needs trained examiner"],
      ],
    },
    {
      heading: "Types of BPPV by canal with positional test findings (Tintinalli 9e 2020)",
      columns: ["Canal", "Diagnostic test and nystagmus", "Repositioning manoeuvre"],
      rows: [
        ["Posterior canal (80-90%)", "Dix-Hallpike: latency 1-5 s, upbeat-torsional toward the lower ear, fatigues within 60 s", "Epley (or Semont)"],
        ["Horizontal canal - geotropic", "Supine roll: horizontal nystagmus beating toward the ground; stronger on affected side", "Barbecue (Lempert) roll or Gufoni"],
        ["Horizontal canal - apogeotropic", "Supine roll: beats away from the ground (cupulolithiasis); weaker on affected side", "Gufoni or head-shaking to convert to geotropic"],
        ["Anterior canal (rare)", "Dix-Hallpike (either side): downbeat nystagmus with small torsional component", "Deep head-hanging (Yacovino); exclude central downbeat"],
      ],
    },
  ],
  "neurology-peripheral-neuropathy": [
    {
      heading: "MRC grading of muscle power (Harrison 22e 2025)",
      columns: ["Grade", "Finding", "Note"],
      rows: [
        ["0", "No contraction", "Complete paralysis"],
        ["1", "Flicker or trace of contraction, no movement", "Palpable or visible"],
        ["2", "Active movement with gravity eliminated", "Moves across the bed"],
        ["3", "Active movement against gravity", "Not against resistance"],
        ["4", "Active movement against gravity and some resistance", "Often split 4-, 4, 4+"],
        ["5", "Normal power", "Compare with the other side and age"],
      ],
    },
    {
      heading: "Grading of deep tendon reflexes (Harrison 22e 2025)",
      columns: ["Grade", "Response", "Meaning"],
      rows: [
        ["0", "Absent, even with reinforcement", "Lower motor neuron, neuropathy, root lesion (may be normal in elderly ankles)"],
        ["1+", "Present but diminished, or only with reinforcement (Jendrassik)", "Can be normal; else hyporeflexia"],
        ["2+", "Normal", "-"],
        ["3+", "Brisker than normal, may spread to adjacent muscles", "Upper motor neuron if asymmetric or with other signs"],
        ["4+", "Very brisk with clonus", "Upper motor neuron lesion"],
      ],
    },
    {
      heading: "Seddon and Sunderland classification of nerve injury (Campbell 13e 2025)",
      columns: ["Sunderland degree", "Seddon", "Structure disrupted", "Recovery"],
      rows: [
        ["First degree", "Neurapraxia", "Focal demyelination; axon intact, no Wallerian degeneration", "Complete within days to 3 months; no advancing Tinel"],
        ["Second degree", "Axonotmesis", "Axon; endoneurium intact", "Complete, regrowth about 1 mm/day; advancing Tinel sign"],
        ["Third degree", "Axonotmesis", "Axon and endoneurium; perineurium intact", "Incomplete, misdirected regrowth"],
        ["Fourth degree", "Axonotmesis", "Axon, endoneurium and perineurium; only epineurium intact", "Neuroma in continuity - needs excision and repair or graft"],
        ["Fifth degree", "Neurotmesis", "Complete transection including epineurium", "None without surgical repair"],
        ["Sixth degree (Mackinnon)", "Mixed", "Different fascicles at different degrees", "Mixed; selective surgery"],
      ],
    },
    {
      heading: "Hughes GBS disability scale (EAN/PNS GBS guideline 2023)",
      columns: ["Grade", "Function", "Implication"],
      rows: [
        ["0", "Healthy", "-"],
        ["1", "Minor symptoms, able to run", "Observe; mild GBS"],
        ["2", "Walks 10 m or more unaided but unable to run", "IVIG/PLEX benefit uncertain; treat if worsening"],
        ["3", "Walks 10 m across open space only with help", "Treat: IVIG 2 g/kg over 5 days within 2 weeks, or PLEX within 4 weeks"],
        ["4", "Bedbound or chairbound", "Treat; monitor FVC (20-30-40 rule)"],
        ["5", "Requires assisted ventilation for at least part of the day", "ICU"],
        ["6", "Dead", "-"],
      ],
    },
    {
      heading: "Brighton criteria levels of diagnostic certainty for GBS (EAN/PNS 2023)",
      columns: ["Level", "Required features", "Note"],
      rows: [
        ["Level 1 (highest)", "Flaccid bilateral weakness, low reflexes, nadir 12 h-28 days, CSF cells under 50 with high protein, NCS fit", "Plus no alternative diagnosis"],
        ["Level 2", "Clinical features plus CSF cells under 50/microL (protein raised or not), or NCS consistent if CSF not done", "Albuminocytological dissociation may be absent in week 1"],
        ["Level 3", "Clinical features only, without CSF or NCS support", "Still GBS if no alternative"],
        ["Level 4", "Reported as GBS but insufficient data to meet level 3, or alternative not excluded", "Not confirmed"],
        ["Level 5", "Not a case of GBS", "-"],
      ],
    },
  ],
  "neurology-low-back-pain-neuro": [
    {
      heading: "ASIA Impairment Scale for spinal cord injury (ISNCSCI 2019)",
      columns: ["Grade", "Definition", "Note"],
      rows: [
        ["AIS A - complete", "No sensory or motor function preserved in sacral segments S4-S5", "Includes absent deep anal pressure and no voluntary anal contraction"],
        ["AIS B - sensory incomplete", "Sensory but no motor function below the neurological level, including S4-S5", "No motor function more than 3 levels below motor level on either side"],
        ["AIS C - motor incomplete", "Motor function preserved below the neurological level; under half of key muscles below it grade 3 or more", "Voluntary anal contraction, or sensory incomplete with sparing over 3 levels below"],
        ["AIS D - motor incomplete", "As C, but at least half of key muscles below the neurological level grade 3 or more", "Most walk with aids"],
        ["AIS E - normal", "Sensation and motor function normal in all segments in a patient who had prior deficits", "Not used if no initial SCI"],
      ],
    },
  ],
  "neurology-parkinsonism": [
    {
      heading: "MDS clinical diagnostic criteria for Parkinson disease (MDS 2015)",
      columns: ["Step", "Requirement", "Examples"],
      rows: [
        ["Step 1 - parkinsonism", "Bradykinesia plus rest tremor or rigidity (or both)", "Bradykinesia = slowness with decrement in speed or amplitude"],
        ["Absolute exclusion criteria", "Any one excludes PD", "Cerebellar signs, downgaze palsy, bvFTD, dopamine-blocker cause, normal DAT scan, no levodopa response"],
        ["Red flags", "Count them; must be counterbalanced by supportive criteria", "Early falls, early severe autonomic failure, rapid wheelchair use, bilateral symmetry, stridor"],
        ["Supportive criteria (4)", "Dramatic levodopa response; levodopa dyskinesia; limb rest tremor; olfactory loss or MIBG denervation", "-"],
        ["Clinically established PD", "No absolute exclusions, at least 2 supportive criteria, no red flags", "Specificity over 90%"],
        ["Clinically probable PD", "No absolute exclusions; red flags (max 2) each matched by a supportive criterion", "Sensitivity over 90%"],
      ],
    },
  ],
};

export default scores;
