import type { NoteTable } from "../../lib/types";

const scores: Record<string, NoteTable[]> = {
  "obstetrics-antenatal-care": [
    {
      heading: "WHO 2016 ANC model - eight contact stages by gestation (WHO 2016)",
      columns: ["Contact", "Gestation", "Note"],
      rows: [
        ["Contact 1", "Up to 12 weeks", "Booking: dating scan, Hb, blood group, HIV, syphilis, HBsAg, urine, BP"],
        ["Contact 2", "20 weeks", "Anomaly scan window; start IFA and calcium as per programme"],
        ["Contact 3", "26 weeks", "Screen for GDM (India: OGTT at booking and 24-28 weeks)"],
        ["Contact 4", "30 weeks", "BP, fetal growth, anaemia"],
        ["Contact 5", "34 weeks", "BP, presentation, birth preparedness"],
        ["Contact 6", "36 weeks", "Presentation; plan place of birth"],
        ["Contact 7", "38 weeks", "Signs of labour, danger signs"],
        ["Contact 8", "40 weeks", "Plan induction by 41 weeks"],
        ["India minimum", "4 ANC visits", "Up to 12, 14-26, 28-34 and 36 weeks-term; PMSMA check on the 9th of each month"],
      ],
    },
    {
      heading: "Placenta praevia types and RCOG classification (RCOG GTG 27a 2018)",
      columns: ["Type", "Relation of placenta to internal os", "Implication"],
      rows: [
        ["Type I (low-lying)", "Encroaches on lower segment, does not reach os", "Vaginal birth usually possible"],
        ["Type II (marginal)", "Reaches the margin of the internal os", "Posterior type II is dangerous: reduces AP diameter of inlet"],
        ["Type III (partial)", "Covers os when closed, not fully when dilated", "Caesarean section"],
        ["Type IV (complete)", "Covers os completely even when dilated", "Caesarean section; highest bleeding risk"],
        ["RCOG - placenta praevia", "Placenta lies directly over the internal os", "Confirm by TVS; plan CS at 36+0 to 37+0 weeks"],
        ["RCOG - low-lying placenta", "Placental edge less than 20 mm from internal os after 16 weeks", "Rescan at 32 weeks and 36 weeks if persists"],
      ],
    },
    {
      heading: "Manning biophysical profile score (Williams Obstetrics 26e 2022)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Non-stress test", "Reactive: 2 or more accelerations of 15 bpm for 15 s in 20-40 min", "2"],
        ["Non-stress test", "Non-reactive", "0"],
        ["Fetal breathing movements", "1 or more episodes of 30 s or more in 30 min", "2"],
        ["Fetal breathing movements", "Absent or less than 30 s", "0"],
        ["Gross body movements", "3 or more discrete body or limb movements in 30 min", "2"],
        ["Gross body movements", "2 or fewer movements", "0"],
        ["Fetal tone", "1 or more episodes of extension with return to flexion, or hand opening and closing", "2"],
        ["Fetal tone", "Absent or slow extension", "0"],
        ["Amniotic fluid volume", "Single deepest pocket more than 2 cm", "2"],
        ["Amniotic fluid volume", "Deepest pocket 2 cm or less", "0"],
      ],
    },
    {
      heading: "Biophysical profile score - interpretation (Williams Obstetrics 26e 2022)",
      columns: ["Total", "Meaning", "Management"],
      rows: [
        ["10/10 or 8/10 with normal fluid", "Normal; asphyxia unlikely", "Repeat per protocol (weekly or twice weekly)"],
        ["8/10 with oligohydramnios", "Chronic compromise possible", "Deliver if term; otherwise close surveillance"],
        ["6/10", "Equivocal", "Deliver if term; else repeat within 24 h"],
        ["4/10", "Probable asphyxia", "Repeat same day; deliver if persists"],
        ["0-2/10", "Asphyxia almost certain", "Deliver"],
        ["Modified BPP", "NST plus amniotic fluid index above 5 cm", "Normal if both reactive and fluid adequate"],
      ],
    },
  ],
  "obstetrics-hypertensive-disorders": [
    {
      heading: "Severe features criteria of preeclampsia (ACOG 2020 PB 222, Williams 26e)",
      columns: ["Feature", "Definition", "Note"],
      rows: [
        ["Severe-range BP", "SBP 160 mmHg or more or DBP 110 mmHg or more, twice 4 h apart", "Treat within 30-60 min; confirm sooner if on treatment"],
        ["Thrombocytopenia", "Platelets below 100,000 per microlitre", "Consider HELLP"],
        ["Liver involvement", "Transaminases twice upper limit, or severe persistent RUQ or epigastric pain", "Not explained by another diagnosis"],
        ["Renal insufficiency", "Creatinine above 1.1 mg/dL or doubling without other renal disease", "Proteinuria not needed for severity"],
        ["Pulmonary oedema", "Clinical or radiological", "Restrict fluids"],
        ["Cerebral symptoms", "New headache unresponsive to medication", "Magnesium sulphate for seizure prophylaxis"],
        ["Visual disturbance", "Blurring, scotomata, photopsia", "Any severe feature means delivery at 34 weeks or beyond"],
      ],
    },
    {
      heading: "Mississippi and Tennessee classification of HELLP syndrome (Williams 26e 2022)",
      columns: ["Class", "Platelet count", "Other laboratory criteria"],
      rows: [
        ["Mississippi class 1", "50,000 per microlitre or less", "AST or ALT 70 IU/L or more and LDH 600 IU/L or more"],
        ["Mississippi class 2", "Above 50,000 to 100,000", "AST or ALT 70 IU/L or more and LDH 600 IU/L or more"],
        ["Mississippi class 3", "Above 100,000 to 150,000", "AST or ALT 40 IU/L or more and LDH 600 IU/L or more"],
        ["Tennessee (complete HELLP)", "100,000 per microlitre or less", "AST 70 IU/L or more and LDH 600 IU/L or more"],
      ],
    },
    {
      heading: "Page grading of placental abruption (Williams 26e 2022)",
      columns: ["Grade", "Clinical picture", "Fetus and mother"],
      rows: [
        ["Grade 0", "No symptoms; retroplacental clot found after delivery", "Diagnosed retrospectively"],
        ["Grade 1", "Mild vaginal bleeding, slight uterine tenderness", "Fetus alive, no distress; BP normal, no coagulopathy"],
        ["Grade 2", "Moderate revealed or concealed bleed, tender tense uterus", "Fetal distress; mother not shocked"],
        ["Grade 3", "Severe bleed, tetanic woody uterus", "Fetal death, maternal shock; 3a without, 3b with coagulopathy"],
      ],
    },
  ],
  "obstetrics-labour-partograph": [
    {
      heading: "Bishop score for cervical favourability before induction (Williams 26e 2022)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Dilatation", "Closed (0 cm)", "0"],
        ["Dilatation", "1-2 cm", "1"],
        ["Dilatation", "3-4 cm", "2"],
        ["Dilatation", "5 cm or more", "3"],
        ["Effacement", "0-30%", "0"],
        ["Effacement", "40-50%", "1"],
        ["Effacement", "60-70%", "2"],
        ["Effacement", "80% or more", "3"],
        ["Station", "-3", "0"],
        ["Station", "-2", "1"],
        ["Station", "-1 or 0", "2"],
        ["Station", "+1 or +2", "3"],
        ["Consistency", "Firm", "0"],
        ["Consistency", "Medium", "1"],
        ["Consistency", "Soft", "2"],
        ["Position", "Posterior", "0"],
        ["Position", "Mid", "1"],
        ["Position", "Anterior", "2"],
      ],
    },
    {
      heading: "Bishop score bands and induction method",
      columns: ["Total (max 13)", "Cervix", "Action"],
      rows: [
        ["8 or more", "Favourable", "Induction as likely to succeed as spontaneous labour; ARM and oxytocin"],
        ["7", "Borderline", "Ripening often chosen, especially in nulliparas"],
        ["6 or less", "Unfavourable", "Cervical ripening: dinoprostone, misoprostol or Foley balloon"],
      ],
    },
    {
      heading: "Stages of labour and expected duration (WHO 2018 intrapartum care)",
      columns: ["Stage", "Definition", "Expected duration"],
      rows: [
        ["Latent first stage", "Painful contractions, cervical change up to 5 cm", "Variable; not an indication to intervene if mother and baby well"],
        ["Active first stage", "Regular painful contractions, from 5 cm to full dilatation", "Usually up to 12 h in first labour, 10 h in later labours"],
        ["Second stage", "Full dilatation to birth of baby", "Up to 3 h in nulliparas, 2 h in multiparas"],
        ["Third stage", "Birth of baby to delivery of placenta", "AMTSL; prolonged if over 30 min"],
        ["Old cut-off", "Rate of 1 cm/h (alert line) is no longer used alone", "WHO 2018 rejected 1 cm/h as a trigger"],
      ],
    },
    {
      heading: "WHO Labour Care Guide alert criteria by parameter (WHO LCG 2020)",
      columns: ["Parameter", "Alert threshold", "Section"],
      rows: [
        ["Companion, pain relief, oral fluid", "Recorded as N (not provided)", "Supportive care"],
        ["Posture", "SP (supine)", "Supportive care"],
        ["Baseline FHR", "Below 110 or 160 bpm or more", "Care of baby"],
        ["FHR deceleration", "L (late)", "Care of baby"],
        ["Amniotic fluid", "M+++ (thick meconium) or B (blood)", "Care of baby"],
        ["Fetal position", "Posterior or transverse occiput", "Care of baby"],
        ["Caput or moulding", "+++", "Care of baby"],
        ["Maternal pulse", "Below 60 or 120/min or more", "Care of woman"],
        ["Systolic BP", "Below 80 or 140 mmHg or more", "Care of woman"],
        ["Diastolic BP", "90 mmHg or more", "Care of woman"],
        ["Temperature", "Below 35.0 C or 37.5 C or more", "Care of woman"],
        ["Urine", "Protein ++ or acetone ++", "Care of woman"],
        ["Contractions", "2 or fewer, or more than 5, per 10 min; duration below 20 s or over 60 s", "Labour progress"],
        ["Time at one dilatation", "5 cm 6 h, 6 cm 5 h, 7 cm 3 h, 8 cm 2.5 h, 9 cm 2 h or more", "Labour progress"],
        ["Second stage", "3 h or more nullipara, 2 h or more multipara", "Labour progress"],
      ],
    },
    {
      heading: "FIGO 2015 CTG classification (FIGO intrapartum fetal monitoring consensus)",
      columns: ["Class", "Features", "Interpretation", "Action"],
      rows: [
        ["Normal", "Baseline 110-160 bpm, variability 5-25 bpm, no repetitive decelerations", "No hypoxia or acidosis", "No intervention"],
        ["Suspicious", "Lacks at least one normal feature, no pathological feature", "Low probability of hypoxia", "Correct reversible causes, close monitoring"],
        ["Pathological", "Baseline below 100; reduced or increased variability; sinusoidal pattern", "High probability of hypoxia", "Correct causes, adjunct tests, or expedite birth"],
        ["Pathological decelerations", "Repetitive late or prolonged decelerations over 30 min, or one over 5 min", "High probability of hypoxia", "Over 20 min if variability reduced counts too"],
      ],
    },
    {
      heading: "Types of FHR decelerations on CTG (FIGO 2015, Williams 26e 2022)",
      columns: ["Type", "Shape and timing", "Mechanism", "Significance"],
      rows: [
        ["Early", "Gradual, mirrors contraction; nadir at peak", "Head compression", "Benign"],
        ["Variable", "V-shaped, rapid fall and recovery, variable timing", "Cord compression", "Usually benign; worrying if over 60 s or reduced variability"],
        ["Late", "U-shaped, gradual; begins or recovers after contraction peak", "Uteroplacental insufficiency", "Repetitive late decelerations suggest hypoxia"],
        ["Prolonged", "Lasting over 3 min", "Hypoxaemia, hypotension, hyperstimulation", "Over 5 min with FHR below 80 needs urgent action"],
      ],
    },
    {
      heading: "Robson ten-group classification of caesarean sections (WHO 2017)",
      columns: ["Group", "Women included", "Note"],
      rows: [
        ["Group 1", "Nullipara, single cephalic, 37 weeks or more, spontaneous labour", "Key target group for reducing CS"],
        ["Group 2", "Nullipara, single cephalic, 37 weeks or more, induced (2a) or CS before labour (2b)", "Reflects induction practice"],
        ["Group 3", "Multipara without scar, single cephalic, 37 weeks or more, spontaneous labour", "Lowest CS rate expected"],
        ["Group 4", "Multipara without scar, single cephalic, 37 weeks or more, induced (4a) or CS before labour (4b)", "-"],
        ["Group 5", "All multiparas with at least one uterine scar, single cephalic, 37 weeks or more", "Largest contributor; reflects TOLAC use"],
        ["Group 6", "All nulliparas with a single breech", "-"],
        ["Group 7", "All multiparas with a single breech, including scarred uterus", "-"],
        ["Group 8", "All multiple pregnancies, including scarred uterus", "-"],
        ["Group 9", "All single transverse or oblique lie, including scarred uterus", "Nearly 100% CS"],
        ["Group 10", "All single cephalic below 37 weeks, including scarred uterus", "Preterm births"],
      ],
    },
    {
      heading: "RCOG classification of perineal tears (RCOG GTG 29 2015)",
      columns: ["Degree", "Structures injured", "Management"],
      rows: [
        ["First degree", "Perineal skin and/or vaginal mucosa only", "Suture if bleeding or edges not apposed"],
        ["Second degree", "Perineal muscles, not the anal sphincter", "Repair in labour room, continuous suture"],
        ["Third degree 3a", "Less than 50% of external anal sphincter thickness torn", "Repair in theatre; overlap or end-to-end"],
        ["Third degree 3b", "More than 50% of external anal sphincter torn", "Theatre repair, antibiotics, laxatives"],
        ["Third degree 3c", "Both external and internal anal sphincter torn", "Theatre repair; separate IAS repair"],
        ["Fourth degree", "Anal sphincter complex and anorectal mucosa", "Theatre repair; physiotherapy, follow-up at 6-12 weeks"],
        ["Rectal buttonhole", "Rectal mucosa torn with sphincter intact", "Not a fourth degree tear; repair and follow up"],
      ],
    },
    {
      heading: "Modified Early Obstetric Warning Score trigger criteria (Singh 2012, RCOG)",
      columns: ["Parameter", "Yellow (amber) trigger", "Red trigger"],
      rows: [
        ["Systolic BP", "150-160 or 90-100 mmHg", "Above 160 or below 90 mmHg"],
        ["Diastolic BP", "90-100 mmHg", "Above 100 mmHg"],
        ["Heart rate", "100-120 or 40-50/min", "Above 120 or below 40/min"],
        ["Respiratory rate", "21-30/min", "Above 30 or below 10/min"],
        ["SpO2", "-", "Below 95%"],
        ["Temperature", "35-36 C", "Above 38 or below 35 C"],
        ["Consciousness", "Responds to voice", "Responds to pain or unresponsive"],
        ["Escalation rule", "Two yellow triggers at once", "One red trigger: urgent medical review"],
      ],
    },
  ],
  "obstetrics-pph": [
    {
      heading: "PPH definition and severity classification (RCOG GTG 52 2016, WHO)",
      columns: ["Class", "Blood loss", "Response"],
      rows: [
        ["Primary PPH (WHO)", "500 mL or more within 24 h of birth", "Newer WHO/FIGO guidance: act at 300 mL or more if vital signs abnormal"],
        ["Minor PPH", "500-1000 mL, no shock", "Basic measures, IV access, observations"],
        ["Major PPH - moderate", "1001-2000 mL", "Full protocol, call senior help"],
        ["Major PPH - severe", "Over 2000 mL or continuing with shock", "Massive haemorrhage protocol, blood products"],
        ["Secondary PPH", "Abnormal bleeding 24 h to 12 weeks after birth", "Look for retained tissue and endometritis"],
      ],
    },
    {
      heading: "Clinical classification of PPH shock by blood loss (Williams 26e, FOGSI)",
      columns: ["Class", "Blood loss", "Signs", "Degree of shock"],
      rows: [
        ["Class 1", "500-1000 mL (10-15%)", "BP normal; palpitations, dizziness, mild tachycardia", "Compensated"],
        ["Class 2", "1000-1500 mL (15-25%)", "SBP 80-100 mmHg, pulse 100-120, weakness, sweating", "Mild"],
        ["Class 3", "1500-2000 mL (25-35%)", "SBP 70-80 mmHg, pulse over 120, restless, pale, oliguria", "Moderate"],
        ["Class 4", "2000-3000 mL (35-45%)", "SBP 50-70 mmHg, collapse, air hunger, anuria", "Severe"],
      ],
    },
    {
      heading: "Obstetric shock index grading (HR / SBP) in PPH (FIGO 2022)",
      columns: ["Shock index", "Meaning", "Action"],
      rows: [
        ["0.7-0.9", "Normal range in pregnancy", "Continue observation"],
        ["0.9 or more", "Increased risk of adverse outcome", "Escalate, prepare transfusion"],
        ["1.4 or more", "Needs urgent intervention", "Massive haemorrhage protocol"],
        ["1.7 or more", "High risk of maternal death", "Resuscitate, definitive haemostasis"],
      ],
    },
    {
      heading: "Four Ts classification of PPH causes (Williams 26e 2022)",
      columns: ["Cause", "Share", "Examples and first step"],
      rows: [
        ["Tone", "About 70%", "Atony: uterine massage, oxytocin, ergometrine, carboprost, misoprostol"],
        ["Trauma", "About 20%", "Tears, haematoma, rupture, inversion: examine and repair"],
        ["Tissue", "About 10%", "Retained placenta or clots: manual removal, evacuation"],
        ["Thrombin", "Under 1%", "Coagulopathy (abruption, sepsis, AFE): blood products, tranexamic acid"],
      ],
    },
  ],
  "obstetrics-early-pregnancy-bleeding": [
    {
      heading: "PUQE-24 score for nausea and vomiting of pregnancy (RCOG GTG 69)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Hours of nausea in 24 h", "None", "1"],
        ["Hours of nausea in 24 h", "1 h or less", "2"],
        ["Hours of nausea in 24 h", "2-3 h", "3"],
        ["Hours of nausea in 24 h", "4-6 h", "4"],
        ["Hours of nausea in 24 h", "More than 6 h", "5"],
        ["Vomiting episodes in 24 h", "None", "1"],
        ["Vomiting episodes in 24 h", "1-2", "2"],
        ["Vomiting episodes in 24 h", "3-4", "3"],
        ["Vomiting episodes in 24 h", "5-6", "4"],
        ["Vomiting episodes in 24 h", "7 or more", "5"],
        ["Retching episodes in 24 h", "None", "1"],
        ["Retching episodes in 24 h", "1-2", "2"],
        ["Retching episodes in 24 h", "3-4", "3"],
        ["Retching episodes in 24 h", "5-6", "4"],
        ["Retching episodes in 24 h", "7 or more", "5"],
      ],
    },
    {
      heading: "PUQE score bands",
      columns: ["Total (3-15)", "Severity", "Care"],
      rows: [
        ["6 or less", "Mild", "Diet advice, oral antiemetic (doxylamine-pyridoxine)"],
        ["7-11", "Moderate", "Ambulatory IV fluids and antiemetics if oral fails"],
        ["12 or more", "Severe", "Admit if ketonuria, weight loss or unable to keep fluids"],
      ],
    },
    {
      heading: "Types of hydatidiform mole (Williams 26e 2022, FIGO 2021)",
      columns: ["Type", "Karyotype and pathology", "Clinical features", "Risk of GTN"],
      rows: [
        ["Complete mole", "46,XX (mostly) androgenetic; no fetal tissue; p57 negative", "Large-for-dates, very high hCG, theca-lutein cysts", "15-20%"],
        ["Partial mole", "69,XXY triploid; fetal parts present; p57 positive", "Often missed miscarriage, modest hCG", "0.5-5%"],
      ],
    },
    {
      heading: "FIGO 2000 prognostic score for gestational trophoblastic neoplasia (FIGO 2021)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Age", "Below 40 years", "0"],
        ["Age", "40 years or more", "1"],
        ["Antecedent pregnancy", "Mole", "0"],
        ["Antecedent pregnancy", "Abortion", "1"],
        ["Antecedent pregnancy", "Term pregnancy", "2"],
        ["Interval from index pregnancy", "Below 4 months", "0"],
        ["Interval from index pregnancy", "4-6 months", "1"],
        ["Interval from index pregnancy", "7-12 months", "2"],
        ["Interval from index pregnancy", "More than 12 months", "4"],
        ["Pre-treatment serum hCG (IU/L)", "Below 1,000", "0"],
        ["Pre-treatment serum hCG (IU/L)", "1,000 to below 10,000", "1"],
        ["Pre-treatment serum hCG (IU/L)", "10,000 to below 100,000", "2"],
        ["Pre-treatment serum hCG (IU/L)", "100,000 or more", "4"],
        ["Largest tumour size, including uterus", "Below 3 cm", "0"],
        ["Largest tumour size, including uterus", "3-4 cm", "1"],
        ["Largest tumour size, including uterus", "5 cm or more", "2"],
        ["Site of metastases", "Lung", "0"],
        ["Site of metastases", "Spleen or kidney", "1"],
        ["Site of metastases", "Gastrointestinal tract", "2"],
        ["Site of metastases", "Liver or brain", "4"],
        ["Number of metastases", "None", "0"],
        ["Number of metastases", "1-4", "1"],
        ["Number of metastases", "5-8", "2"],
        ["Number of metastases", "More than 8", "4"],
        ["Previous failed chemotherapy", "None", "0"],
        ["Previous failed chemotherapy", "Single drug", "2"],
        ["Previous failed chemotherapy", "Two or more drugs", "4"],
      ],
    },
    {
      heading: "FIGO GTN risk score bands and treatment (FIGO 2021)",
      columns: ["Total", "Risk group", "Treatment"],
      rows: [
        ["0-6", "Low risk", "Single-agent methotrexate or actinomycin D"],
        ["5-6 with hCG above 410,000 IU/L", "Low risk but likely to fail single agent", "Consider multi-agent chemotherapy"],
        ["7 or more", "High risk", "Multi-agent chemotherapy (EMA-CO)"],
        ["13 or more", "Ultra-high risk", "Induction low-dose EP, then EMA-EP; specialist centre"],
      ],
    },
    {
      heading: "FIGO anatomical staging of gestational trophoblastic neoplasia (FIGO 2021)",
      columns: ["Stage", "Extent", "Note"],
      rows: [
        ["Stage I", "Confined to the uterus", "Reported as stage plus score, e.g. II:4"],
        ["Stage II", "Outside uterus but limited to genital structures (adnexa, vagina, broad ligament)", "-"],
        ["Stage III", "Lung metastases, with or without genital tract involvement", "Chest X-ray used to count lung metastases"],
        ["Stage IV", "All other metastatic sites (liver, brain, kidney, gut)", "High risk regardless of score in practice"],
      ],
    },
  ],
  "obstetrics-postnatal-care": [
    {
      heading: "Edinburgh Postnatal Depression Scale item scoring (NICE CG192, Cox 1987)",
      columns: ["Item", "Content", "Scoring"],
      rows: [
        ["Item 1", "Able to laugh and see the funny side", "0-3, lower score for usual ability"],
        ["Item 2", "Looked forward with enjoyment", "0-3, lower score for usual ability"],
        ["Item 3", "Blamed myself unnecessarily", "Reverse scored 3-0"],
        ["Item 4", "Anxious or worried for no good reason", "0-3"],
        ["Item 5", "Scared or panicky for no good reason", "Reverse scored 3-0"],
        ["Item 6", "Things getting on top of me", "Reverse scored 3-0"],
        ["Item 7", "So unhappy I have had difficulty sleeping", "Reverse scored 3-0"],
        ["Item 8", "Felt sad or miserable", "Reverse scored 3-0"],
        ["Item 9", "So unhappy I have been crying", "Reverse scored 3-0"],
        ["Item 10", "Thought of harming myself", "Reverse scored 3-0; any positive answer needs same-day review"],
      ],
    },
    {
      heading: "EPDS score bands and action (NICE CG192)",
      columns: ["Total (max 30)", "Meaning", "Action"],
      rows: [
        ["Below 10", "Depression unlikely", "Repeat if concern persists"],
        ["10-12", "Possible depression", "Clinical assessment, repeat in 2 weeks"],
        ["13 or more", "Probable depression", "Full assessment, treatment or referral"],
        ["Item 10 positive", "Self-harm thoughts", "Urgent same-day mental health assessment"],
      ],
    },
    {
      heading: "LATCH breastfeeding assessment score (Jensen 1994)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Latch", "Too sleepy or reluctant, no latch achieved", "0"],
        ["Latch", "Repeated attempts, holds nipple in mouth, stimulate to suck", "1"],
        ["Latch", "Grasps breast, tongue down, lips flanged, rhythmic sucking", "2"],
        ["Audible swallowing", "None", "0"],
        ["Audible swallowing", "A few with stimulation", "1"],
        ["Audible swallowing", "Spontaneous and intermittent (under 24 h) or frequent (over 24 h)", "2"],
        ["Type of nipple", "Inverted", "0"],
        ["Type of nipple", "Flat", "1"],
        ["Type of nipple", "Everted after stimulation", "2"],
        ["Comfort (breast and nipple)", "Engorged, cracked, bleeding, severe discomfort", "0"],
        ["Comfort (breast and nipple)", "Filling, reddened, small blisters or bruises, mild-moderate discomfort", "1"],
        ["Comfort (breast and nipple)", "Soft, non-tender", "2"],
        ["Hold (positioning)", "Full assistance, staff holds baby at breast", "0"],
        ["Hold (positioning)", "Minimal assistance; staff helps, mother takes over", "1"],
        ["Hold (positioning)", "No assistance; mother positions and holds baby", "2"],
      ],
    },
    {
      heading: "LATCH score bands",
      columns: ["Total (max 10)", "Breastfeeding", "Action"],
      rows: [
        ["8-10", "Effective", "Routine support"],
        ["4-7", "Moderate difficulty", "Observe a feed, correct position and attachment"],
        ["0-3", "Poor", "Skilled lactation support, check baby weight and output"],
      ],
    },
  ],
};

export default scores;
