import type { NoteTable } from "../../lib/types";

const scores: Record<string, NoteTable[]> = {
  "pediatrics-newborn-care": [
    {
      heading: "APGAR score at 1 and 5 minutes (Nelson 22e 2024, AAP/ACOG)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Appearance (colour)", "Blue or pale all over", "0"],
        ["Appearance (colour)", "Body pink, extremities blue (acrocyanosis)", "1"],
        ["Appearance (colour)", "Completely pink", "2"],
        ["Pulse (heart rate)", "Absent", "0"],
        ["Pulse (heart rate)", "Below 100/min", "1"],
        ["Pulse (heart rate)", "100/min or more", "2"],
        ["Grimace (reflex irritability)", "No response to stimulation", "0"],
        ["Grimace (reflex irritability)", "Grimace", "1"],
        ["Grimace (reflex irritability)", "Cry or active withdrawal", "2"],
        ["Activity (muscle tone)", "Limp", "0"],
        ["Activity (muscle tone)", "Some flexion of extremities", "1"],
        ["Activity (muscle tone)", "Active motion, well flexed", "2"],
        ["Respiration", "Absent", "0"],
        ["Respiration", "Slow, weak or irregular", "1"],
        ["Respiration", "Good, crying", "2"],
      ],
    },
    {
      heading: "APGAR score bands and use (Nelson 22e 2024, AAP/ACOG)",
      columns: ["Total", "Meaning", "What it is used for"],
      rows: [
        ["7-10", "Reassuring", "Routine care; record at 1 and 5 minutes"],
        ["4-6", "Moderately abnormal", "If 5-minute score below 7, repeat every 5 minutes up to 20 minutes"],
        ["0-3", "Low", "Low 5-minute score alone does not prove asphyxia or predict palsy"],
        ["Key point", "Resuscitation is not delayed for the score", "NRP steps are driven by breathing, heart rate and tone, not the APGAR"],
      ],
    },
    {
      heading: "Silverman-Anderson retraction score for preterm respiratory distress (Nelson 22e 2024)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Upper chest movement", "Synchronised with abdomen", "0"],
        ["Upper chest movement", "Lag on inspiration", "1"],
        ["Upper chest movement", "See-saw movement", "2"],
        ["Lower chest (intercostal) retraction", "None", "0"],
        ["Lower chest (intercostal) retraction", "Just visible", "1"],
        ["Lower chest (intercostal) retraction", "Marked", "2"],
        ["Xiphoid retraction", "None", "0"],
        ["Xiphoid retraction", "Just visible", "1"],
        ["Xiphoid retraction", "Marked", "2"],
        ["Nasal flaring", "None", "0"],
        ["Nasal flaring", "Minimal", "1"],
        ["Nasal flaring", "Marked", "2"],
        ["Expiratory grunt", "None", "0"],
        ["Expiratory grunt", "Audible with stethoscope only", "1"],
        ["Expiratory grunt", "Audible with naked ear", "2"],
      ],
    },
    {
      heading: "Silverman-Anderson score - interpretation",
      columns: ["Total", "Severity", "Usual action"],
      rows: [
        ["0", "No respiratory distress", "Routine care"],
        ["1-3", "Mild distress", "Oxygen, monitor SpO2, observe closely"],
        ["4-6", "Moderate distress", "CPAP, blood gas, consider surfactant in preterm"],
        ["7-10", "Severe distress, impending respiratory failure", "Intubate and ventilate"],
      ],
    },
    {
      heading: "Downes score for neonatal respiratory distress (Nelson 22e 2024)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Respiratory rate", "Below 60/min", "0"],
        ["Respiratory rate", "60-80/min", "1"],
        ["Respiratory rate", "Above 80/min", "2"],
        ["Retractions", "None", "0"],
        ["Retractions", "Mild", "1"],
        ["Retractions", "Moderate to severe", "2"],
        ["Cyanosis", "None", "0"],
        ["Cyanosis", "Relieved by up to 40% oxygen", "1"],
        ["Cyanosis", "Persists on 40% oxygen", "2"],
        ["Air entry", "Good bilaterally", "0"],
        ["Air entry", "Mildly decreased", "1"],
        ["Air entry", "Markedly decreased or absent", "2"],
        ["Grunting", "None", "0"],
        ["Grunting", "Audible with stethoscope", "1"],
        ["Grunting", "Audible with naked ear", "2"],
      ],
    },
    {
      heading: "Downes score - interpretation",
      columns: ["Total", "Severity", "Usual action"],
      rows: [
        ["0-3", "Mild respiratory distress", "Oxygen by hood or nasal prongs, monitor"],
        ["4-6", "Moderate respiratory distress", "CPAP; blood gas"],
        ["7-10", "Severe, impending respiratory failure", "Blood gas, intubation and mechanical ventilation"],
      ],
    },
    {
      heading: "Sarnat and Sarnat staging of hypoxic-ischaemic encephalopathy (Nelson 22e 2024)",
      columns: ["Stage", "Clinical features", "Seizures and EEG", "Outcome and action"],
      rows: [
        ["Stage 1 (mild)", "Hyperalert, irritable; normal tone, brisk reflexes, strong Moro, dilated pupils", "No seizures; EEG normal", "Lasts under 24 h; usually normal outcome"],
        ["Stage 2 (moderate)", "Lethargic; mild hypotonia, weak suck and Moro, constricted pupils, bradycardia", "Seizures common; low-voltage or periodic EEG", "About 20-40% abnormal outcome; therapeutic hypothermia if 36 wk or more, within 6 h"],
        ["Stage 3 (severe)", "Stupor or coma; flaccid, absent suck and Moro, poor pupillary reflex, apnoea", "Seizures less frequent; suppressed or isoelectric EEG", "About 50% die, most survivors disabled; hypothermia, intensive care"],
      ],
    },
    {
      heading: "Thompson HIE score for encephalopathy after birth asphyxia (Nelson 22e 2024)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Tone", "Normal", "0"],
        ["Tone", "Hypertonia", "1"],
        ["Tone", "Hypotonia", "2"],
        ["Tone", "Flaccid", "3"],
        ["Level of consciousness", "Normal", "0"],
        ["Level of consciousness", "Hyperalert, staring", "1"],
        ["Level of consciousness", "Lethargic", "2"],
        ["Level of consciousness", "Comatose", "3"],
        ["Fits", "None", "0"],
        ["Fits", "Infrequent, fewer than 3 per day", "1"],
        ["Fits", "Frequent, more than 2 per day", "2"],
        ["Posture", "Normal", "0"],
        ["Posture", "Fisting, cycling", "1"],
        ["Posture", "Strong distal flexion", "2"],
        ["Posture", "Decerebrate", "3"],
        ["Moro reflex", "Normal", "0"],
        ["Moro reflex", "Partial", "1"],
        ["Moro reflex", "Absent", "2"],
        ["Grasp", "Normal", "0"],
        ["Grasp", "Poor", "1"],
        ["Grasp", "Absent", "2"],
        ["Suck", "Normal", "0"],
        ["Suck", "Poor", "1"],
        ["Suck", "Absent, with or without biting", "2"],
        ["Respiration", "Normal", "0"],
        ["Respiration", "Hyperventilation", "1"],
        ["Respiration", "Brief apnoea", "2"],
        ["Respiration", "Apnoea needing ventilation (IPPV)", "3"],
        ["Fontanelle", "Normal", "0"],
        ["Fontanelle", "Full, not tense", "1"],
        ["Fontanelle", "Tense", "2"],
      ],
    },
    {
      heading: "Thompson HIE score bands",
      columns: ["Total (max 22)", "Grade of HIE", "Implication"],
      rows: [
        ["0", "Normal", "No encephalopathy"],
        ["1-10", "Mild HIE", "Usually good outcome; observe"],
        ["11-14", "Moderate HIE", "Candidate for therapeutic hypothermia within 6 h"],
        ["15-22", "Severe HIE", "Peak score 15 or more strongly predicts death or disability"],
      ],
    },
    {
      heading: "Kramer dermal zone grading of neonatal jaundice (Nelson 22e 2024)",
      columns: ["Zone", "Skin area stained", "Approximate serum bilirubin", "Note"],
      rows: [
        ["Zone 1", "Head and neck", "About 5-6 mg/dL (range 4-8)", "Jaundice spreads cephalocaudally"],
        ["Zone 2", "Upper trunk, down to umbilicus", "About 9 mg/dL (range 5-12)", "Visual estimate is unreliable in dark skin"],
        ["Zone 3", "Lower trunk and thighs, umbilicus to knees", "About 12 mg/dL (range 8-16)", "Measure TcB or TSB"],
        ["Zone 4", "Arms and legs below the knees", "About 15 mg/dL (range 11-18)", "Measure TSB urgently"],
        ["Zone 5", "Palms and soles", "Above 15 mg/dL", "Measure TSB urgently; likely treatment range"],
      ],
    },
    {
      heading: "Bhutani nomogram risk zone classification of hour-specific bilirubin (Nelson 22e 2024)",
      columns: ["Zone", "Hour-specific TSB centile", "Risk of later significant hyperbilirubinaemia", "Use"],
      rows: [
        ["High-risk zone", "Above 95th centile", "About 40%", "Treat per AAP 2022 thresholds, close repeat TSB"],
        ["High-intermediate zone", "76th to 95th centile", "About 13%", "Repeat bilirubin, early follow-up"],
        ["Low-intermediate zone", "40th to 75th centile", "About 2%", "Follow-up within 48 h of discharge"],
        ["Low-risk zone", "Below 40th centile", "Near 0%", "Routine follow-up"],
        ["Note", "Valid for well newborns 35 wk or more", "Predicts, does not set treatment", "AAP 2022 uses GA- and risk-specific phototherapy lines"],
      ],
    },
    {
      heading: "New Ballard Score components for gestational age (Nelson 22e 2024)",
      columns: ["Domain", "Items scored (each -1 to 5)", "Note"],
      rows: [
        ["Neuromuscular maturity", "Posture, square window, arm recoil, popliteal angle, scarf sign, heel to ear", "Six items; best after 12 h of age"],
        ["Physical maturity", "Skin, lanugo, plantar surface, breast, eye and ear, genitals", "Six items; valid 20-44 weeks"],
        ["Total", "Sum of 12 items, range -10 to 50", "Accurate to about 2 weeks; best within 96 h"],
      ],
    },
    {
      heading: "New Ballard Score maturity rating (Nelson 22e 2024)",
      columns: ["Total score", "Gestational age", "Rule of thumb"],
      rows: [
        ["-10", "20 weeks", "Each 5 points adds 2 weeks"],
        ["0", "24 weeks", "GA (weeks) = (2 x score + 120) / 5"],
        ["10", "28 weeks", "Extremely to very preterm boundary"],
        ["20", "32 weeks", "Very preterm to moderate preterm"],
        ["30", "36 weeks", "Late preterm"],
        ["35", "38 weeks", "Term"],
        ["40", "40 weeks", "Term"],
        ["50", "44 weeks", "Post-term"],
      ],
    },
  ],
  "pediatrics-imnci": [
    {
      heading: "IMNCI classification of cough or difficult breathing, 2 months-5 years (WHO 2014)",
      columns: ["Classification", "Signs", "Treatment"],
      rows: [
        ["Severe pneumonia or very severe disease", "Any general danger sign or stridor in a calm child", "First dose injectable antibiotic, keep warm, urgent referral"],
        ["Pneumonia", "Fast breathing and/or chest indrawing", "Oral amoxicillin 5 days; follow up in 3 days"],
        ["No pneumonia: cough or cold", "No signs of pneumonia or very severe disease", "Home care, soothe throat; refer if cough over 14 days or recurrent wheeze"],
        ["Fast breathing cut-off", "50/min or more at 2-12 months; 40/min or more at 12 months-5 years", "Count for a full minute in a calm child"],
        ["India note", "Older IMNCI charts class chest indrawing as severe pneumonia", "Follow the state chart in use"],
      ],
    },
    {
      heading: "Possible serious bacterial infection classification, 0-59 days (WHO PSBI 2015)",
      columns: ["Classification", "Signs", "Management"],
      rows: [
        ["Critical illness", "Unconscious or no movement, unable to feed at all, convulsions", "Urgent referral and inpatient care; do not treat as outpatient"],
        ["Clinical severe infection", "Not feeding well, movement only on stimulation, temp 38 C or more or below 35.5 C, severe chest indrawing", "Refer; if refused, IM gentamicin 7 days plus oral amoxicillin 7 days"],
        ["Fast breathing pneumonia, 7-59 days", "Respiratory rate 60/min or more, no other sign", "Oral amoxicillin 7 days at home"],
        ["Fast breathing, 0-6 days", "Respiratory rate 60/min or more", "Treat as clinical severe infection; refer"],
        ["Local bacterial infection", "Umbilicus red or draining pus, skin pustules", "Oral amoxicillin 5 days, local care, follow up in 2 days"],
      ],
    },
  ],
  "pediatrics-diarrhoea-dehydration": [
    {
      heading: "Clinical Dehydration Scale for children 1-36 months (Friedman 2004, Nelson 22e)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["General appearance", "Normal", "0"],
        ["General appearance", "Thirsty, restless, or lethargic but irritable when touched", "1"],
        ["General appearance", "Drowsy, limp, cold or sweaty, with or without coma", "2"],
        ["Eyes", "Normal", "0"],
        ["Eyes", "Slightly sunken", "1"],
        ["Eyes", "Very sunken", "2"],
        ["Mucous membranes (tongue)", "Moist", "0"],
        ["Mucous membranes (tongue)", "Sticky", "1"],
        ["Mucous membranes (tongue)", "Dry", "2"],
        ["Tears", "Present", "0"],
        ["Tears", "Decreased", "1"],
        ["Tears", "Absent", "2"],
      ],
    },
    {
      heading: "Clinical Dehydration Scale - interpretation",
      columns: ["Total", "Degree", "Plan"],
      rows: [
        ["0", "No dehydration (below 3%)", "Oral fluids, ORS for losses, continue feeds"],
        ["1-4", "Some dehydration (3-6%)", "ORS 75 mL/kg over 4 h, reassess"],
        ["5-8", "Moderate to severe dehydration (6% or more)", "IV Ringer lactate, admit"],
      ],
    },
    {
      heading: "Vesikari (Ruuska-Vesikari) gastroenteritis severity score (Nelson 22e 2024)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Diarrhoea duration", "1-4 days", "1"],
        ["Diarrhoea duration", "5 days", "2"],
        ["Diarrhoea duration", "6 days or more", "3"],
        ["Maximum stools per 24 h", "1-3", "1"],
        ["Maximum stools per 24 h", "4-5", "2"],
        ["Maximum stools per 24 h", "6 or more", "3"],
        ["Vomiting duration", "1 day", "1"],
        ["Vomiting duration", "2 days", "2"],
        ["Vomiting duration", "3 days or more", "3"],
        ["Maximum vomits per 24 h", "1", "1"],
        ["Maximum vomits per 24 h", "2-4", "2"],
        ["Maximum vomits per 24 h", "5 or more", "3"],
        ["Maximum temperature", "37.1-38.4 C", "1"],
        ["Maximum temperature", "38.5-38.9 C", "2"],
        ["Maximum temperature", "39.0 C or more", "3"],
        ["Dehydration", "None", "0"],
        ["Dehydration", "1-5%", "2"],
        ["Dehydration", "6% or more", "3"],
        ["Treatment", "None", "0"],
        ["Treatment", "Rehydration", "1"],
        ["Treatment", "Hospitalisation", "2"],
      ],
    },
    {
      heading: "Vesikari score severity bands",
      columns: ["Total (max 20)", "Severity", "Use"],
      rows: [
        ["Below 7", "Mild episode", "Outcome measure in rotavirus vaccine trials"],
        ["7-10", "Moderate episode", "Compare episode severity"],
        ["11 or more", "Severe episode", "Primary endpoint for vaccine efficacy against severe disease"],
      ],
    },
    {
      heading: "IMNCI classification of persistent diarrhoea and dysentery (WHO IMCI 2014)",
      columns: ["Classification", "Signs", "Treatment"],
      rows: [
        ["Severe persistent diarrhoea", "Diarrhoea 14 days or more with some or severe dehydration", "Treat dehydration first, then refer"],
        ["Persistent diarrhoea", "Diarrhoea 14 days or more, no dehydration", "Feeding advice, zinc 14 days, multivitamins, follow up in 5 days"],
        ["Dysentery", "Blood in the stool", "Oral ciprofloxacin 3 days, zinc; follow up in 2-3 days"],
      ],
    },
  ],
  "pediatrics-growth-monitoring": [
    {
      heading: "IAP classification of undernutrition by weight for age (Nelson/IAP)",
      columns: ["Grade", "Weight as % of expected for age", "Note"],
      rows: [
        ["Normal", "Above 80%", "Reference: 50th centile of standard"],
        ["Grade I", "71-80%", "Mild undernutrition"],
        ["Grade II", "61-70%", "Moderate undernutrition"],
        ["Grade III", "51-60%", "Severe undernutrition"],
        ["Grade IV", "50% or less", "Very severe; add suffix K if oedema (kwashiorkor)"],
      ],
    },
    {
      heading: "Gomez classification of malnutrition by weight for age",
      columns: ["Grade", "Weight as % of median for age", "Limitation"],
      rows: [
        ["Normal", "Above 90%", "Reference: Harvard 50th centile"],
        ["Grade I (mild)", "75-90%", "Cannot separate acute from chronic malnutrition"],
        ["Grade II (moderate)", "60-74%", "Ignores height"],
        ["Grade III (severe)", "Below 60%", "Oedema masks true weight"],
      ],
    },
    {
      heading: "Waterlow classification of wasting and stunting",
      columns: ["Grade", "Weight for height (wasting)", "Height for age (stunting)"],
      rows: [
        ["Normal (grade 0)", "Above 90%", "Above 95%"],
        ["Mild (grade 1)", "80-90%", "90-95%"],
        ["Moderate (grade 2)", "70-80%", "85-90%"],
        ["Severe (grade 3)", "Below 70%", "Below 85%"],
      ],
    },
    {
      heading: "Wellcome Trust classification of severe malnutrition",
      columns: ["Weight for age", "No oedema", "Oedema present"],
      rows: [
        ["60-80% of expected", "Underweight", "Kwashiorkor"],
        ["Below 60% of expected", "Marasmus", "Marasmic kwashiorkor"],
      ],
    },
    {
      heading: "Tanner stages of sexual maturity rating (Nelson 22e 2024)",
      columns: ["Stage", "Girls - breast", "Boys - genitalia", "Both - pubic hair"],
      rows: [
        ["Stage 1", "Prepubertal, papilla elevation only", "Prepubertal; testes below 4 mL", "None (vellus only)"],
        ["Stage 2", "Breast bud; areola widens", "Testes 4 mL or more, scrotum enlarges and reddens", "Sparse, long, slightly pigmented at base"],
        ["Stage 3", "Breast and areola enlarge, no contour separation", "Penis lengthens, testes grow further", "Darker, coarser, curled, over pubis"],
        ["Stage 4", "Areola and papilla form a secondary mound", "Penis broadens, glans develops, scrotum darkens", "Adult type, not on thighs"],
        ["Stage 5", "Mature; areola recedes to breast contour", "Adult size and shape; testes 15-25 mL", "Adult, spreads to medial thighs"],
      ],
    },
  ],
  "pediatrics-severe-acute-malnutrition": [
    {
      heading: "Grading of bilateral pitting oedema in SAM (WHO 2013, IAP)",
      columns: ["Grade", "Extent of pitting oedema", "Implication"],
      rows: [
        ["Grade + (mild)", "Both feet or ankles", "SAM by definition; outpatient if appetite good and no complication"],
        ["Grade ++ (moderate)", "Feet, lower legs, hands or lower arms", "SAM; outpatient only if appetite test passed and no complication"],
        ["Grade +++ (severe)", "Generalised, including face and eyes", "Complicated SAM; inpatient care (NRC)"],
      ],
    },
  ],
  "pediatrics-fever-febrile-seizure": [
    {
      heading: "NICE traffic light risk classification for fever in under-5s (NICE NG143 2021)",
      columns: ["Domain", "Green - low risk", "Amber - intermediate risk", "Red - high risk"],
      rows: [
        ["Colour", "Normal skin, lips, tongue", "Pallor reported by parent or carer", "Pale, mottled, ashen or blue"],
        ["Activity", "Responds normally, content or smiles, strong cry", "Reduced response, no smile, wakes only with prolonged stimulation", "Appears ill, does not stay awake, weak high-pitched or continuous cry"],
        ["Respiratory", "Normal", "Nasal flaring, RR over 50 (6-12 mo) or over 40 (above 12 mo), SpO2 95% or less, crackles", "Grunting, RR over 60, moderate or severe chest indrawing"],
        ["Circulation and hydration", "Normal skin and eyes, moist mucous membranes", "Tachycardia for age, CRT 3 s or more, dry mucosa, poor feeding, less urine", "Reduced skin turgor"],
        ["Other", "None of amber or red", "Age 3-6 mo with temp 39 C or more, fever 5 days or more, rigors, limb or joint swelling, not weight bearing", "Under 3 mo with temp 38 C or more, non-blanching rash, bulging fontanelle, stiff neck, focal signs or fits"],
        ["Action", "Home care with safety-net advice", "Safety net or face-to-face assessment by paediatrician", "Urgent referral to paediatric specialist care"],
      ],
    },
    {
      heading: "Yale Observation Scale for febrile children 3-36 months (Nelson 22e 2024)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Quality of cry", "Strong with normal tone, or content and not crying", "1"],
        ["Quality of cry", "Whimpering or sobbing", "3"],
        ["Quality of cry", "Weak, moaning or high-pitched", "5"],
        ["Reaction to parent stimulation", "Cries briefly then stops, or content", "1"],
        ["Reaction to parent stimulation", "Cries off and on", "3"],
        ["Reaction to parent stimulation", "Continual cry or hardly responds", "5"],
        ["State variation", "Stays awake, or wakes quickly if asleep", "1"],
        ["State variation", "Eyes close briefly then wakes, or needs prolonged stimulation", "3"],
        ["State variation", "Falls asleep or will not rouse", "5"],
        ["Colour", "Pink", "1"],
        ["Colour", "Pale extremities or acrocyanosis", "3"],
        ["Colour", "Pale, cyanotic, mottled or ashen", "5"],
        ["Hydration", "Skin and eyes normal, mucous membranes moist", "1"],
        ["Hydration", "Skin and eyes normal, mouth slightly dry", "3"],
        ["Hydration", "Skin doughy or tented, dry mucosa and/or sunken eyes", "5"],
        ["Response to social overtures", "Smiles or alerts", "1"],
        ["Response to social overtures", "Brief smile or alerts briefly", "3"],
        ["Response to social overtures", "No smile, anxious or dull face, no alerting", "5"],
      ],
    },
    {
      heading: "Yale Observation Scale - interpretation",
      columns: ["Total (6-30)", "Risk of serious illness", "Action"],
      rows: [
        ["10 or less", "Low (about 3%)", "Observe; investigate as per age and source"],
        ["11-15", "Intermediate (about 25%)", "Careful evaluation, investigations"],
        ["16 or more", "High (about 90%)", "Treat as seriously ill; admit"],
      ],
    },
    {
      heading: "Rochester criteria for low-risk febrile infant 60 days or less (Nelson 22e 2024)",
      columns: ["Criterion", "Requirement", "Note"],
      rows: [
        ["Criterion 1", "Infant appears well", "All criteria must be met to be low risk"],
        ["Criterion 2", "Previously healthy: term, no prior antibiotics, admission or chronic illness", "No treatment for unexplained jaundice"],
        ["Criterion 3", "No focal infection of skin, soft tissue, bone, joint or ear", "Focus excludes low-risk status"],
        ["Criterion 4", "WBC 5,000-15,000 per cubic mm", "Band count 1,500 per cubic mm or less"],
        ["Criterion 5", "Urine 10 WBC or fewer per high-power field", "Or negative dipstick per local protocol"],
        ["Criterion 6", "Stool 5 WBC or fewer per high-power field if diarrhoea", "Only if diarrhoea present"],
        ["Performance", "Negative predictive value about 99% for serious bacterial infection", "AAP 2021 febrile infant guideline adds procalcitonin and ANC"],
      ],
    },
    {
      heading: "Febrile seizure types (AAP 2011, Nelson 22e 2024)",
      columns: ["Type", "Definition", "Implication"],
      rows: [
        ["Simple febrile seizure", "Generalised, under 15 min, once in 24 h, age 6-60 months, no neuro deficit", "No routine EEG, imaging or bloods; LP only if meningitis suspected"],
        ["Complex febrile seizure", "Focal, or over 15 min, or recurs within 24 h", "Evaluate for cause; epilepsy risk higher"],
        ["Febrile status epilepticus", "Seizure 30 min or more, or series without recovery", "Treat as status; higher risk of hippocampal injury"],
      ],
    },
    {
      heading: "Westley croup severity score (Nelson 22e 2024, Alberta 2021)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Level of consciousness", "Normal, including sleep", "0"],
        ["Level of consciousness", "Disoriented", "5"],
        ["Cyanosis", "None", "0"],
        ["Cyanosis", "With agitation", "4"],
        ["Cyanosis", "At rest", "5"],
        ["Stridor", "None", "0"],
        ["Stridor", "With agitation", "1"],
        ["Stridor", "At rest", "2"],
        ["Air entry", "Normal", "0"],
        ["Air entry", "Decreased", "1"],
        ["Air entry", "Markedly decreased", "2"],
        ["Retractions", "None", "0"],
        ["Retractions", "Mild", "1"],
        ["Retractions", "Moderate", "2"],
        ["Retractions", "Severe", "3"],
      ],
    },
    {
      heading: "Westley croup score severity bands",
      columns: ["Total (max 17)", "Severity", "Management"],
      rows: [
        ["2 or less", "Mild croup", "Single dose oral dexamethasone 0.15-0.6 mg/kg; home"],
        ["3-5", "Moderate croup", "Dexamethasone; observe; nebulised adrenaline if stridor at rest"],
        ["6-11", "Severe croup", "Nebulised adrenaline plus dexamethasone; admit"],
        ["12 or more", "Impending respiratory failure", "Adrenaline, oxygen, airway team, ICU"],
      ],
    },
    {
      heading: "Paediatric Glasgow Coma Scale for preverbal children (Nelson 22e 2024)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Eye opening", "Spontaneous", "4"],
        ["Eye opening", "To voice", "3"],
        ["Eye opening", "To pain", "2"],
        ["Eye opening", "None", "1"],
        ["Verbal (infant)", "Coos, babbles, alert", "5"],
        ["Verbal (infant)", "Irritable, consolable cry", "4"],
        ["Verbal (infant)", "Cries to pain", "3"],
        ["Verbal (infant)", "Moans to pain", "2"],
        ["Verbal (infant)", "None", "1"],
        ["Motor", "Moves spontaneously and purposefully", "6"],
        ["Motor", "Withdraws to touch", "5"],
        ["Motor", "Withdraws to pain", "4"],
        ["Motor", "Abnormal flexion (decorticate)", "3"],
        ["Motor", "Extension (decerebrate)", "2"],
        ["Motor", "None", "1"],
      ],
    },
    {
      heading: "Paediatric GCS severity bands",
      columns: ["Total", "Severity of brain injury", "Action"],
      rows: [
        ["13-15", "Mild", "Observe; CT per PECARN rules"],
        ["9-12", "Moderate", "CT head, admit"],
        ["8 or less", "Severe", "Secure airway, CT, neurosurgical referral"],
      ],
    },
    {
      heading: "AVPU scale for rapid consciousness check in children (Nelson 22e 2024)",
      columns: ["Level", "Response", "Approximate GCS and action"],
      rows: [
        ["A - Alert", "Awake and responsive", "GCS about 15"],
        ["V - Voice", "Responds only to voice", "GCS about 12-13; reassess frequently"],
        ["P - Pain", "Responds only to painful stimulus", "GCS 8 or less; airway at risk, call anaesthetist"],
        ["U - Unresponsive", "No response", "GCS 3-6; secure airway"],
      ],
    },
    {
      heading: "Pediatric Appendicitis Score (Samuel 2002, Nelson 22e 2024)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Cough, percussion or hopping tenderness", "Right lower quadrant pain", "2"],
        ["Right lower quadrant tenderness", "Present", "2"],
        ["Anorexia", "Present", "1"],
        ["Fever", "38 C or more", "1"],
        ["Nausea or vomiting", "Present", "1"],
        ["Migration of pain", "To right lower quadrant", "1"],
        ["Leucocytosis", "WBC above 10,000 per cubic mm", "1"],
        ["Neutrophilia", "Absolute neutrophil count above 7,500 per cubic mm", "1"],
      ],
    },
    {
      heading: "Pediatric Appendicitis Score bands",
      columns: ["Total (max 10)", "Risk", "Action"],
      rows: [
        ["3 or less", "Low risk", "Discharge with safety net or observe"],
        ["4-6", "Intermediate", "Ultrasound, serial examination"],
        ["7 or more", "High risk", "Surgical consultation"],
      ],
    },
    {
      heading: "Kawasaki disease diagnostic criteria (AHA 2024 scientific statement)",
      columns: ["Criterion", "Definition", "Note"],
      rows: [
        ["Fever", "5 days or more (4 days if 4 or more principal features)", "Plus 4 of 5 principal features for complete KD"],
        ["Conjunctival change", "Bilateral bulbar non-exudative injection, limbal sparing", "Principal feature"],
        ["Oral changes", "Red cracked lips, strawberry tongue, diffuse oropharyngeal erythema", "Principal feature"],
        ["Rash", "Polymorphous; not vesicular or bullous", "Principal feature; perineal accentuation"],
        ["Extremity changes", "Erythema and oedema of palms and soles; periungual peeling in weeks 2-3", "Principal feature"],
        ["Cervical lymphadenopathy", "1.5 cm or more, usually unilateral", "Least frequent principal feature"],
        ["Incomplete KD", "Fever 5 days or more with 2-3 features; CRP 3 mg/dL or more and/or ESR 40 or more", "Then 3 or more supplementary labs or abnormal echo means treat"],
        ["Supplementary labs", "Anaemia, platelets 450,000 or more after day 7, albumin 3 g/dL or less, raised ALT", "Also WBC 15,000 or more, urine 10 or more WBC/hpf"],
        ["Infant rule", "Infants 6 months or under with fever 7 days or more unexplained", "Evaluate for incomplete KD"],
      ],
    },
    {
      heading: "AHA coronary artery Z-score classification in Kawasaki disease (AHA 2024)",
      columns: ["Class", "Z-score", "Implication"],
      rows: [
        ["No involvement", "Below 2", "Low-dose aspirin until 4-6 weeks"],
        ["Dilation only", "2 to below 2.5", "Repeat echo; often regresses"],
        ["Small aneurysm", "2.5 to below 5", "Aspirin long term, periodic review"],
        ["Medium aneurysm", "5 to below 10, and absolute diameter below 8 mm", "Aspirin; consider added antiplatelet"],
        ["Large or giant aneurysm", "10 or more, or absolute diameter 8 mm or more", "Aspirin plus anticoagulation, stress testing"],
      ],
    },
  ],
  "pediatrics-anaemia-deworming": [
    {
      heading: "IMNCI classification of anaemia by palmar pallor, 2 months-5 years (WHO 2014)",
      columns: ["Classification", "Sign", "Treatment"],
      rows: [
        ["Severe anaemia", "Severe palmar pallor", "Urgent referral"],
        ["Anaemia", "Some palmar pallor", "Iron, albendazole if 1 year or more and none in 6 months, test for malaria; follow up in 14 days"],
        ["No anaemia", "No palmar pallor", "Feeding advice; IFA prophylaxis as per Anemia Mukt Bharat"],
      ],
    },
  ],
  "pediatrics-congenital-heart-disease": [
    {
      heading: "Ross classification of heart failure in infants and children (Nelson 22e 2024)",
      columns: ["Class", "Features", "Implication"],
      rows: [
        ["Class I", "No limitation or symptoms", "Monitor"],
        ["Class II", "Mild tachypnoea or sweating with feeds in infants; exertional dyspnoea in older children", "Mild heart failure; diuretics may be needed"],
        ["Class III", "Marked tachypnoea or sweating with feeds, prolonged feeds, growth failure", "Moderate failure; optimise therapy, plan repair"],
        ["Class IV", "Tachypnoea, retractions, grunting or sweating at rest", "Severe failure; admit"],
      ],
    },
  ],
  "pediatrics-nocturnal-enuresis": [
    {
      heading: "ICCS classification of enuresis (ICCS 2020, Nelson 22e 2024)",
      columns: ["Type", "Definition", "Implication"],
      rows: [
        ["Enuresis", "Intermittent wetting in sleep at age 5 years or more", "At least once a month for 3 months"],
        ["Monosymptomatic enuresis", "No daytime lower urinary tract symptoms", "Alarm or desmopressin"],
        ["Non-monosymptomatic enuresis", "With daytime symptoms: urgency, frequency, daytime wetting", "Treat daytime symptoms and constipation first"],
        ["Primary enuresis", "Never dry for 6 continuous months", "Usually maturational"],
        ["Secondary enuresis", "Relapse after 6 or more months dry", "Look for UTI, diabetes, constipation, stress, abuse"],
        ["Frequent enuresis", "4 or more wet nights per week", "Less likely to resolve spontaneously"],
      ],
    },
  ],
};

export default scores;
