import type { NoteTable } from "../../lib/types";

const scores: Record<string, NoteTable[]> = {
  "preventive-health-information-gis": [
    {
      heading: "Modified Kuppuswamy socioeconomic scale (updated, Park 28e 2025)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Education of head of family", "Profession or honours", "7"],
        ["Education of head of family", "Graduate", "6"],
        ["Education of head of family", "Intermediate or diploma", "5"],
        ["Education of head of family", "High school certificate", "4"],
        ["Education of head of family", "Middle school certificate", "3"],
        ["Education of head of family", "Primary school certificate", "2"],
        ["Education of head of family", "Illiterate", "1"],
        ["Occupation of head of family", "Legislators, senior officials and managers", "10"],
        ["Occupation of head of family", "Professionals", "9"],
        ["Occupation of head of family", "Technicians and associate professionals", "8"],
        ["Occupation of head of family", "Clerks", "7"],
        ["Occupation of head of family", "Skilled workers and shop and market sales workers", "6"],
        ["Occupation of head of family", "Skilled agricultural and fishery workers", "5"],
        ["Occupation of head of family", "Craft and related trade workers", "4"],
        ["Occupation of head of family", "Plant and machine operators and assemblers", "3"],
        ["Occupation of head of family", "Elementary occupation", "2"],
        ["Occupation of head of family", "Unemployed", "1"],
        ["Monthly family income (CPI-IW revised)", "Band 1 - highest (1976 base: Rs 2000 or more)", "12"],
        ["Monthly family income (CPI-IW revised)", "Band 2 (1976 base: Rs 1000-1999)", "10"],
        ["Monthly family income (CPI-IW revised)", "Band 3 (1976 base: Rs 750-999)", "6"],
        ["Monthly family income (CPI-IW revised)", "Band 4 (1976 base: Rs 500-749)", "4"],
        ["Monthly family income (CPI-IW revised)", "Band 5 (1976 base: Rs 300-499)", "3"],
        ["Monthly family income (CPI-IW revised)", "Band 6 (1976 base: Rs 101-299)", "2"],
        ["Monthly family income (CPI-IW revised)", "Band 7 - lowest (1976 base: Rs 100 or less)", "1"],
      ],
    },
    {
      heading: "Kuppuswamy socioeconomic class by total score",
      columns: ["Total (3-29)", "Socioeconomic class", "Note"],
      rows: [
        ["26-29", "Upper (I)", "Income bands are revised yearly using CPI-IW (Labour Bureau)"],
        ["16-25", "Upper middle (II)", "Occupation uses NCO 2004 groups"],
        ["11-15", "Lower middle (III)", "Mainly urban use"],
        ["5-10", "Upper lower (IV)", "-"],
        ["Below 5", "Lower (V)", "-"],
      ],
    },
    {
      heading: "Modified BG Prasad socioeconomic classification (Park 28e 2025)",
      columns: ["Class", "Per capita monthly income (1961 base)", "Note"],
      rows: [
        ["Class I (upper)", "Rs 100 or more", "Base values multiplied by a CPI-IW factor, updated yearly"],
        ["Class II (upper middle)", "Rs 50-99", "Uses per capita income only"],
        ["Class III (middle)", "Rs 30-49", "Usable in rural and urban areas"],
        ["Class IV (lower middle)", "Rs 15-29", "-"],
        ["Class V (lower)", "Below Rs 15", "-"],
      ],
    },
    {
      heading: "Demographic transition stages (Park 28e 2025)",
      columns: ["Stage", "Birth and death rates", "Example"],
      rows: [
        ["Stage 1 - high stationary", "High birth rate, high death rate; population static", "India till about 1920"],
        ["Stage 2 - early expanding", "Death rate falls, birth rate stays high", "Many countries of South Asia and Africa"],
        ["Stage 3 - late expanding", "Death rate falls further, birth rate starts to fall", "India now (with regional variation)"],
        ["Stage 4 - low stationary", "Low birth rate, low death rate; zero growth", "Denmark, most of Europe"],
        ["Stage 5 - declining", "Birth rate below death rate", "Germany, Hungary, Japan"],
      ],
    },
  ],
  "preventive-nutrition-programmes": [
    {
      heading: "WHO 2024 haemoglobin cut-offs for anaemia severity by age and sex (WHO 2024)",
      columns: ["Group", "Anaemia below", "Mild", "Moderate", "Severe"],
      rows: [
        ["Infants 2-6 months", "9.5 g/dL", "8.5-9.4", "7.0-8.4", "Below 7.0"],
        ["Children 6-23 months", "10.5 g/dL", "9.5-10.4", "7.0-9.4", "Below 7.0"],
        ["Children 24-59 months", "11.0 g/dL", "10.0-10.9", "7.0-9.9", "Below 7.0"],
        ["Children 5-11 years", "11.5 g/dL", "11.0-11.4", "8.0-10.9", "Below 8.0"],
        ["Adolescents 12-14 years", "12.0 g/dL", "11.0-11.9", "8.0-10.9", "Below 8.0"],
        ["Non-pregnant women 15 years and over", "12.0 g/dL", "11.0-11.9", "8.0-10.9", "Below 8.0"],
        ["Men 15 years and over", "13.0 g/dL", "11.0-12.9", "8.0-10.9", "Below 8.0"],
        ["Pregnant - 1st trimester", "11.0 g/dL", "10.0-10.9", "7.0-9.9", "Below 7.0"],
        ["Pregnant - 2nd trimester", "10.5 g/dL", "9.5-10.4", "7.0-9.4", "Below 7.0"],
        ["Pregnant - 3rd trimester", "11.0 g/dL", "10.0-10.9", "7.0-9.9", "Below 7.0"],
      ],
    },
    {
      heading: "Waist circumference and waist-hip ratio risk criteria (WHO; ICMR-INDIAB 2023; Park 28e 2025)",
      columns: ["Measure", "Men", "Women", "Meaning"],
      rows: [
        ["Waist - Asian Indian cut-off", "90 cm or more", "80 cm or more", "Abdominal obesity (Indian consensus, IDF South Asian)"],
        ["Waist - WHO increased risk", "94 cm or more", "80 cm or more", "Europid populations"],
        ["Waist - WHO substantially increased", "102 cm or more", "88 cm or more", "Europid populations"],
        ["Waist-hip ratio", "0.90 or more", "0.85 or more", "Substantially increased metabolic risk (WHO)"],
        ["Waist-height ratio", "0.5 or more", "0.5 or more", "Increased risk at any age or ethnicity"],
      ],
    },
    {
      heading: "WHO iodine status classification by median urinary iodine (WHO 2013)",
      columns: ["Median UIC", "Iodine intake", "Iodine status"],
      rows: [
        ["Below 20 mcg/L", "Insufficient", "Severe iodine deficiency (school-age children)"],
        ["20-49 mcg/L", "Insufficient", "Moderate iodine deficiency"],
        ["50-99 mcg/L", "Insufficient", "Mild iodine deficiency"],
        ["100-199 mcg/L", "Adequate", "Adequate iodine nutrition"],
        ["200-299 mcg/L", "Above requirements", "May pose slight risk in susceptible groups"],
        ["300 mcg/L or more", "Excessive", "Risk of iodine-induced hyperthyroidism, autoimmune thyroid disease"],
        ["Pregnancy: below 150", "Insufficient", "Pregnant women; 150-249 adequate, 250-499 above requirements, 500 or more excessive"],
      ],
    },
    {
      heading: "WHO goitre grading and total goitre rate severity (WHO; Park 28e 2025)",
      columns: ["Grade or rate", "Definition", "Meaning"],
      rows: [
        ["Grade 0", "No goitre palpable or visible", "-"],
        ["Grade 1", "Palpable but not visible with neck in normal position", "Moves up on swallowing"],
        ["Grade 2", "Visible with neck in normal position", "Consistent with enlarged thyroid on palpation"],
        ["TGR below 5%", "Total goitre rate in school-age children", "No public health problem"],
        ["TGR 5.0-19.9%", "Total goitre rate", "Mild iodine deficiency"],
        ["TGR 20.0-29.9%", "Total goitre rate", "Moderate iodine deficiency"],
        ["TGR 30% or more", "Total goitre rate", "Severe iodine deficiency"],
      ],
    },
    {
      heading: "WHO classification of xerophthalmia and public health criteria (WHO, Park 28e)",
      columns: ["Sign", "Description", "Public health problem if prevalence (6-71 months)"],
      rows: [
        ["XN", "Night blindness", "More than 1%"],
        ["X1A", "Conjunctival xerosis", "-"],
        ["X1B", "Bitot's spots", "More than 0.5%"],
        ["X2", "Corneal xerosis", "X2 + X3A + X3B more than 0.01%"],
        ["X3A", "Corneal ulceration or keratomalacia, less than one-third of cornea", "Counted with X2"],
        ["X3B", "Corneal ulceration or keratomalacia, one-third or more of cornea", "Counted with X2"],
        ["XS", "Corneal scar", "More than 0.05%"],
        ["XF", "Xerophthalmic fundus", "-"],
        ["Serum retinol", "Below 10 mcg/dL", "More than 5% of children"],
      ],
    },
  ],
  "preventive-water-sanitation-vector": [
    {
      heading: "Dean's fluorosis index classification of dental fluorosis (Park 28e 2025)",
      columns: ["Class (weight)", "Enamel appearance", "Note"],
      rows: [
        ["Normal (0)", "Smooth, glossy, pale creamy-white translucent", "-"],
        ["Questionable (0.5)", "Few white flecks or occasional white spots", "-"],
        ["Very mild (1)", "Small opaque paper-white areas, under 25% of tooth surface", "-"],
        ["Mild (2)", "White opaque areas, under 50% of surface", "-"],
        ["Moderate (3)", "All surfaces affected, marked wear, brown stain frequent", "-"],
        ["Severe (4)", "Pitting discrete or confluent, widespread brown stain, corroded look", "-"],
        ["Water fluoride (BIS 10500)", "Acceptable 1.0 mg/L; permissible 1.5 mg/L", "Above 1.5 mg/L causes fluorosis"],
      ],
    },
    {
      heading: "Community fluorosis index grading of public health significance (Dean)",
      columns: ["CFI value", "Public health significance", "Action"],
      rows: [
        ["0.0-0.4", "Negative", "None"],
        ["0.4-0.6", "Borderline", "Monitor"],
        ["0.6-1.0", "Slight", "Public health problem begins above 0.6; defluoridate"],
        ["1.0-2.0", "Medium", "Defluoridation (Nalgonda), alternate source"],
        ["2.0-3.0", "Marked", "Defluoridation, alternate source"],
        ["3.0-4.0", "Very marked", "Urgent alternate water source"],
      ],
    },
    {
      heading: "Biomedical waste colour classification (BMW Rules 2016, amended 2018-19)",
      columns: ["Colour", "Waste", "Treatment and disposal"],
      rows: [
        ["Yellow", "Anatomical, soiled dressings, expired medicines, chemical, lab and microbiology waste", "Incineration, plasma pyrolysis or deep burial; lab waste pre-treated on site"],
        ["Red", "Contaminated recyclable plastics: tubing, bottles, IV sets, catheters, gloves, syringes without needle", "Autoclave or microwave, shred, send to registered recycler"],
        ["White (translucent)", "Sharps incl. needles, syringes with fixed needles, scalpels, blades", "Puncture-proof container; autoclave, shred, encapsulate or foundry"],
        ["Blue", "Glassware: broken or discarded glass, vials, ampoules; metallic body implants", "Cardboard box with blue marking; disinfect and recycle"],
        ["Rules", "Untreated waste stored under 48 h; chlorinated plastic bags phased out; bar coding", "2018 amendment set deadlines for phase-out and bar codes"],
      ],
    },
    {
      heading: "Aedes larval index definitions and thresholds (NCVBDC, Park 28e 2025)",
      columns: ["Index", "Formula", "Threshold"],
      rows: [
        ["House index", "Houses positive for larvae or pupae / houses inspected x 100", "1% or more: risk of transmission"],
        ["Container index", "Positive containers / water-holding containers inspected x 100", "Shows breeding intensity"],
        ["Breteau index", "Positive containers per 100 houses inspected", "5 or more: transmission risk; 50 or more: high risk"],
        ["Pupal index", "Pupae per 100 houses", "Best proxy for adult density"],
      ],
    },
    {
      heading: "Malaria surveillance index definitions (NCVBDC, Park 28e 2025)",
      columns: ["Index", "Formula", "Use"],
      rows: [
        ["Annual parasite incidence (API)", "Confirmed cases in a year / population x 1000", "Main index for stratification"],
        ["Annual blood examination rate (ABER)", "Slides or RDTs examined in a year / population x 100", "Surveillance adequacy; target 10% or more"],
        ["Slide positivity rate (SPR)", "Positive slides / slides examined x 100", "Trend of transmission"],
        ["Slide falciparum rate (SFR)", "P. falciparum positive / slides examined x 100", "Falciparum burden"],
        ["Annual falciparum incidence (AFI)", "P. falciparum cases in a year / population x 1000", "Falciparum burden"],
      ],
    },
    {
      heading: "NFME 2016-2030 malaria classification of states by API (NCVBDC)",
      columns: ["Category", "Criteria", "Programme phase"],
      rows: [
        ["Category 0", "No indigenous case (zero transmission)", "Prevention of re-establishment"],
        ["Category 1", "API below 1 in the state and all its districts", "Elimination phase"],
        ["Category 2", "API below 1 in the state, but some districts API 1 or more", "Pre-elimination phase"],
        ["Category 3", "API 1 or more", "Intensified control phase"],
        ["Goal", "Zero indigenous cases nationally by 2027, elimination by 2030", "Sustain malaria-free status"],
      ],
    },
    {
      heading: "JMP drinking water service ladder classification (WHO/UNICEF JMP 2017)",
      columns: ["Level", "Definition", "Note"],
      rows: [
        ["Safely managed", "Improved source on premises, available when needed, free of contamination", "SDG 6.1 indicator"],
        ["Basic", "Improved source, collection 30 min or less round trip", "-"],
        ["Limited", "Improved source, collection over 30 min round trip", "-"],
        ["Unimproved", "Unprotected dug well or unprotected spring", "-"],
        ["Surface water", "River, dam, lake, pond, stream, canal", "Lowest rung"],
      ],
    },
    {
      heading: "JMP sanitation service ladder classification (WHO/UNICEF JMP 2017)",
      columns: ["Level", "Definition", "Note"],
      rows: [
        ["Safely managed", "Improved facility, not shared; excreta disposed in situ or treated off site", "SDG 6.2 indicator"],
        ["Basic", "Improved facility not shared with other households", "-"],
        ["Limited", "Improved facility shared with other households", "-"],
        ["Unimproved", "Pit latrine without slab, hanging latrine, bucket latrine", "-"],
        ["Open defecation", "Fields, forests, bushes, water bodies, beaches", "Target of Swachh Bharat Mission"],
      ],
    },
    {
      heading: "JMP hygiene service ladder classification (WHO/UNICEF JMP 2017)",
      columns: ["Level", "Definition", "Note"],
      rows: [
        ["Basic", "Handwashing facility with soap and water at home", "SDG 6.2 indicator"],
        ["Limited", "Handwashing facility lacking soap and/or water", "-"],
        ["No facility", "No handwashing facility at home", "-"],
      ],
    },
  ],
  "preventive-immunisation": [
    {
      heading: "Vaccine vial monitor stages - classification (WHO, UIP cold chain 2016)",
      columns: ["Stage", "Inner square vs outer circle", "Action"],
      rows: [
        ["Stage 1", "Inner square lighter than outer circle", "Use if not expired"],
        ["Stage 2", "Inner square still lighter, but darkening", "Use this vial first"],
        ["Stage 3 (discard point)", "Inner square matches outer circle", "Do not use; discard"],
        ["Stage 4", "Inner square darker than outer circle", "Do not use; discard"],
        ["VVM types", "VVM2, VVM7, VVM14, VVM30", "Days to discard point at 37 C; OPV carries VVM2"],
      ],
    },
  ],
  "preventive-outbreak-investigation": [
    {
      heading: "Types of epidemic by epidemic curve (Park 28e 2025)",
      columns: ["Type", "Curve shape", "Example"],
      rows: [
        ["Common source, single exposure", "Sharp rise and fall, all cases within one incubation period", "Food poisoning, Bhopal gas tragedy"],
        ["Common source, continuous or repeated", "Plateau; cases continue while exposure lasts", "Contaminated well, Legionnaires disease"],
        ["Propagated (person to person)", "Gradual rise, successive peaks one incubation period apart", "Hepatitis A, measles, COVID-19"],
        ["Mixed", "Common source followed by secondary spread", "Cholera or typhoid from water then contacts"],
        ["Slow (modern) epidemic", "Rise over years or decades", "Coronary heart disease, lung cancer"],
      ],
    },
    {
      heading: "IDSP case definition classification - S, P and L forms (IDSP/IHIP 2021)",
      columns: ["Class", "Who reports", "Basis"],
      rows: [
        ["S - Syndromic (suspected)", "Health worker (ASHA, ANM, MPW)", "Syndrome: fever, cough, loose stools, jaundice, AFP etc"],
        ["P - Presumptive (probable)", "Medical officer", "Clinical diagnosis with typical features"],
        ["L - Laboratory confirmed", "Laboratory", "Confirmed by laboratory test"],
        ["Trigger", "Unusual rise in cases, clustering or deaths", "Rapid Response Team investigates within 24-48 h"],
      ],
    },
  ],
  "preventive-disaster-management": [
    {
      heading: "JumpSTART paediatric triage criteria, 1-8 years (Tintinalli 9e 2020)",
      columns: ["Category", "Criteria", "Note"],
      rows: [
        ["Green - minor", "Able to walk", "Infants carried: assess separately"],
        ["Black - deceased", "Apnoeic after airway opening and 5 rescue breaths, or no pulse", "Give 5 breaths only if pulse present"],
        ["Red - immediate (breathing)", "Starts breathing after rescue breaths, or RR below 15 or above 45", "Apnoea is often respiratory in children"],
        ["Red - immediate (perfusion)", "No palpable peripheral pulse", "-"],
        ["Red - immediate (mental)", "AVPU: inappropriate response to pain, or unresponsive", "-"],
        ["Yellow - delayed", "RR 15-45, pulse present, A, V or appropriate P", "Not walking"],
      ],
    },
  ],
  "preventive-prevention-screening": [
    {
      heading: "Leavell and Clark modes of intervention - classification (Park 28e 2025)",
      columns: ["Mode", "Level of prevention", "Examples"],
      rows: [
        ["Health promotion", "Primary", "Health education, nutrition, housing, lifestyle change"],
        ["Specific protection", "Primary", "Immunisation, iodised salt, helmets, chemoprophylaxis"],
        ["Early diagnosis and treatment", "Secondary", "Screening, case finding, Pap smear, NCD screening"],
        ["Disability limitation", "Tertiary", "Treatment to arrest disease and prevent complications"],
        ["Rehabilitation", "Tertiary", "Medical, vocational, social and psychological rehabilitation"],
      ],
    },
  ],
  "preventive-climate-change-health": [
    {
      heading: "Indian National Air Quality Index categories (CPCB 2014)",
      columns: ["Category", "AQI", "PM2.5 / PM10 (24 h, microgram per cubic m)", "Health impact"],
      rows: [
        ["Good", "0-50", "0-30 / 0-50", "Minimal impact"],
        ["Satisfactory", "51-100", "31-60 / 51-100", "Minor breathing discomfort to sensitive people"],
        ["Moderately polluted", "101-200", "61-90 / 101-250", "Discomfort in lung disease, asthma, heart disease, children, elderly"],
        ["Poor", "201-300", "91-120 / 251-350", "Breathing discomfort to most people on prolonged exposure"],
        ["Very poor", "301-400", "121-250 / 351-430", "Respiratory illness on prolonged exposure"],
        ["Severe", "401-500", "Above 250 / above 430", "Affects healthy people; serious in existing disease"],
      ],
    },
    {
      heading: "IMD heat wave criteria (IMD, NPCCHH heat action plan 2021)",
      columns: ["Condition", "Criteria", "Note"],
      rows: [
        ["Basic requirement", "Maximum temperature 40 C or more in plains, 37 C coastal, 30 C hills", "Must be met first"],
        ["Heat wave (departure)", "Departure from normal 4.5-6.4 C", "-"],
        ["Severe heat wave (departure)", "Departure from normal above 6.4 C", "-"],
        ["Heat wave (actual)", "Actual maximum 45 C or more", "Regardless of normal"],
        ["Severe heat wave (actual)", "Actual maximum 47 C or more", "Regardless of normal"],
      ],
    },
    {
      heading: "Classification of heat-related illness (NPCCHH 2021, Tintinalli 9e)",
      columns: ["Type", "Features", "Management"],
      rows: [
        ["Heat rash (prickly heat)", "Itchy papules in sweat-covered areas", "Cool environment, loose clothes"],
        ["Heat oedema", "Swelling of feet and ankles", "Elevate legs; no diuretics"],
        ["Heat cramps", "Painful muscle spasms after exertion, core temp normal", "Rest, oral ORS"],
        ["Heat syncope", "Brief fainting from vasodilation and pooling", "Lie flat, legs raised, fluids"],
        ["Heat exhaustion", "Weakness, headache, nausea, sweating; core temp below 40 C; mind normal", "Cool, ORS or IV fluids; observe"],
        ["Heat stroke", "Core temp above 40 C with altered sensorium; skin may be dry", "Emergency: cool first (ice-water immersion), transport second"],
      ],
    },
  ],
  "preventive-occupational-health": [
    {
      heading: "Ambient noise standards by zone classification (CPCB; Park 28e 2025)",
      columns: ["Zone", "Day limit, dB(A) Leq (6 am-10 pm)", "Night limit, dB(A) Leq (10 pm-6 am)"],
      rows: [
        ["Industrial area", "75", "70"],
        ["Commercial area", "65", "55"],
        ["Residential area", "55", "45"],
        ["Silence zone", "50", "40"],
      ],
    },
    {
      heading: "Permissible occupational noise exposure criteria (Factories Act model rules)",
      columns: ["Sound level, dB(A)", "Permissible hours per day", "Note"],
      rows: [
        ["90", "8", "5 dB exchange rate"],
        ["92", "6", "-"],
        ["95", "4", "-"],
        ["97", "3", "-"],
        ["100", "2", "-"],
        ["102", "1.5", "-"],
        ["105", "1", "-"],
        ["110", "0.5", "-"],
        ["115", "0.25", "No exposure above 115 dB(A); impulse peak above 140 dB not allowed"],
      ],
    },
    {
      heading: "Schilling grading of byssinosis (Park 28e 2025)",
      columns: ["Grade", "Symptoms", "Note"],
      rows: [
        ["Grade 0", "No symptoms", "-"],
        ["Grade 1/2", "Occasional chest tightness or cough on first day of the working week", "Monday fever pattern"],
        ["Grade 1", "Chest tightness and/or breathlessness on every first working day", "-"],
        ["Grade 2", "Chest tightness and/or breathlessness on first and other working days", "-"],
        ["Grade 3", "Grade 2 plus permanent incapacity from reduced effort tolerance or lung function", "Notifiable occupational disease"],
      ],
    },
    {
      heading: "ILO classification of chest radiographs for pneumoconiosis (ILO 2022)",
      columns: ["Feature", "Categories", "Meaning"],
      rows: [
        ["Profusion of small opacities", "Major categories 0, 1, 2, 3; 12-point scale 0/- to 3/+", "1/0 or more usually taken as positive"],
        ["Small rounded opacities", "p below 1.5 mm; q 1.5-3 mm; r 3-10 mm", "Silicosis, coal workers pneumoconiosis"],
        ["Small irregular opacities", "s fine; t medium; u coarse", "Asbestosis"],
        ["Large opacity A", "One or more over 10 mm, combined diameter up to 50 mm", "Progressive massive fibrosis"],
        ["Large opacity B", "Combined above 50 mm but less than right upper zone area", "-"],
        ["Large opacity C", "Combined area larger than right upper zone", "-"],
        ["Pleural abnormality", "Plaques, calcification, diffuse thickening, obliterated angle", "Asbestos exposure"],
      ],
    },
  ],
  "preventive-national-health-programmes": [
    {
      heading: "NTEP treatment outcome classification (NTEP 2021, WHO 2022)",
      columns: ["Outcome", "Definition", "Note"],
      rows: [
        ["Cured", "Bacteriologically confirmed at start, completed treatment with bacteriological response, no failure", "-"],
        ["Treatment completed", "Completed treatment, no failure, but cure not documented", "-"],
        ["Treatment failed", "Regimen stopped or permanently changed for poor response, adverse event or resistance", "-"],
        ["Died", "Died for any reason before or during treatment", "-"],
        ["Lost to follow-up", "Did not start, or interrupted for 2 or more consecutive months", "Earlier: 1 month"],
        ["Not evaluated", "No outcome assigned, incl. transferred out with unknown outcome", "-"],
        ["Treatment success", "Cured plus treatment completed", "Programme target 90% or more"],
      ],
    },
  ],
  "preventive-health-planning-management": [
    {
      heading: "Population norms for rural public health facility classification (IPHS 2022)",
      columns: ["Facility", "Plain areas", "Hilly, tribal or difficult areas"],
      rows: [
        ["Sub Health Centre (AAM-SHC)", "5,000", "3,000"],
        ["Primary Health Centre", "30,000", "20,000"],
        ["Community Health Centre", "1,20,000", "80,000"],
        ["Note", "SHC and PHC function as Ayushman Arogya Mandir", "CHC is the FRU with 30 beds and 4 specialists"],
      ],
    },
  ],
  "preventive-iec-social-marketing": [
    {
      heading: "Stages of adoption of a new idea (Park 28e 2025)",
      columns: ["Stage", "What happens", "IEC approach"],
      rows: [
        ["Awareness", "Knows of the idea, little detail", "Mass media"],
        ["Interest", "Seeks more information", "Mass media, group talks"],
        ["Evaluation", "Weighs advantages and disadvantages", "Interpersonal communication, opinion leaders"],
        ["Trial", "Tries the practice", "Demonstration, support"],
        ["Adoption", "Accepts and continues", "Reinforcement, follow-up"],
      ],
    },
  ],
};

export default scores;
