import type { NoteTable } from "../../lib/types";

const scores: Record<string, NoteTable[]> = {
  "psychiatry-depression": [
    {
      heading: "DSM-5-TR criteria for a major depressive episode (DSM-5-TR 2022)",
      columns: ["Criterion", "Requirement", "Note"],
      rows: [
        ["A - symptoms", "5 or more of 9 symptoms in the same 2 weeks, one being depressed mood or loss of interest", "Mood, anhedonia, weight/appetite, sleep, psychomotor, fatigue, worthlessness, concentration, suicidality"],
        ["B - impairment", "Clinically significant distress or impairment in social, occupational or other areas", "-"],
        ["C - exclusion", "Not due to a substance or another medical condition", "Check thyroid, anaemia, drugs (steroids, beta-blockers debated)"],
        ["D - not psychotic disorder", "Not better explained by schizoaffective, schizophrenia or other psychotic disorders", "-"],
        ["E - never manic", "No manic or hypomanic episode ever", "If present, diagnosis is bipolar disorder"],
      ],
    },
    {
      heading: "ICD-11 depressive episode severity grading (ICD-11 CDDR 2024)",
      columns: ["Severity", "Features", "Management pointer"],
      rows: [
        ["Mild", "No symptom to an intense degree; some difficulty in work, social or domestic life", "Guided self-help, CBT, activity scheduling; antidepressant not routine"],
        ["Moderate", "Several symptoms to a marked degree, or many milder ones; considerable difficulty in several domains", "Antidepressant (SSRI) and/or psychotherapy"],
        ["Severe", "Many or most symptoms to a marked degree, or fewer to an intense degree; functions only minimally", "Combined drug plus psychotherapy; assess suicide risk; refer"],
        ["With psychotic symptoms", "Delusions or hallucinations in a moderate or severe episode", "Antidepressant plus antipsychotic, or ECT; psychiatric referral"],
        ["Episode requirement", "At least 5 of 10 symptoms most of the day, nearly every day, for 2 weeks or more", "At least one from the affective cluster (low mood or anhedonia)"],
      ],
    },
    {
      heading: "Hamilton Depression Rating Scale (HAM-D17) severity bands (Kaplan and Sadock 12e 2021)",
      columns: ["HAM-D17 total", "Severity", "Use"],
      rows: [
        ["0-7", "Normal or remission", "Remission target in trials"],
        ["8-13", "Mild depression", "-"],
        ["14-18", "Moderate depression", "-"],
        ["19-22", "Severe depression", "-"],
        ["23 or more", "Very severe depression", "Response = 50% or greater fall from baseline"],
      ],
    },
    {
      heading: "Modified SAD PERSONS scale for suicide risk (Rosen 10e 2022)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Sex", "Male", "1"],
        ["Age", "Under 19 or over 45 years", "1"],
        ["Depression or hopelessness", "Present", "2"],
        ["Previous attempt or psychiatric care", "Present", "1"],
        ["Excessive alcohol or drug use", "Present", "1"],
        ["Rational thinking loss (psychosis, organic)", "Present", "2"],
        ["Separated, divorced or widowed", "Yes", "1"],
        ["Organised or serious attempt", "Yes", "2"],
        ["No social support", "Yes", "1"],
        ["Stated future intent", "Determined or ambivalent", "2"],
      ],
    },
    {
      heading: "Modified SAD PERSONS score bands (total 0-14)",
      columns: ["Total", "Meaning", "Action"],
      rows: [
        ["0-5", "Lower risk", "May be discharged with follow-up and safety plan"],
        ["6-8", "Intermediate risk", "Psychiatric consultation"],
        ["9 or more", "High risk", "Admission (under MHCA 2017 if needed)"],
        ["Caveat", "NICE NG225 2022: risk scales do not predict suicide", "Never base discharge on a score alone - do a needs-based assessment"],
      ],
    },
    {
      heading: "Columbia (C-SSRS) screener risk triage criteria (Columbia Lighthouse 2016)",
      columns: ["Positive answer", "Question (past month unless stated)", "Risk and response"],
      rows: [
        ["Q1 - wish to be dead", "Wished you were dead or could go to sleep and not wake up?", "Low - mental health follow-up"],
        ["Q2 - suicidal thoughts", "Actually had any thoughts of killing yourself?", "Low - if no, skip to Q6"],
        ["Q3 - method", "Thought about how you might do this?", "Moderate - mental health referral, safety plan"],
        ["Q4 - intent", "Had any intention of acting on these thoughts?", "High - immediate safety, psychiatric evaluation"],
        ["Q5 - plan", "Started to work out details and intend to carry out the plan?", "High - immediate safety, psychiatric evaluation"],
        ["Q6 - behaviour", "Done or prepared anything to end your life (lifetime; flag past 3 months)?", "Past 3 months = high; over 3 months ago = moderate"],
      ],
    },
  ],
  "psychiatry-alcohol-use-disorder": [
    {
      heading: "CAGE questionnaire for alcohol problems (Kaplan and Sadock 12e 2021)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["C - Cut down", "Ever felt you should cut down on your drinking?", "1"],
        ["A - Annoyed", "Annoyed by people criticising your drinking?", "1"],
        ["G - Guilty", "Ever felt bad or guilty about your drinking?", "1"],
        ["E - Eye-opener", "Ever had a drink first thing in the morning to steady nerves or get rid of a hangover?", "1"],
      ],
    },
    {
      heading: "CAGE score interpretation",
      columns: ["Total", "Meaning", "Action"],
      rows: [
        ["0-1", "Screen negative", "Does not exclude hazardous drinking - use AUDIT-C"],
        ["2-4", "Clinically significant - likely alcohol use disorder", "Full assessment with AUDIT and DSM-5-TR criteria"],
        ["Eye-opener alone", "Suggests physical dependence", "Assess withdrawal risk before advising abrupt stop"],
      ],
    },
    {
      heading: "AUDIT - Alcohol Use Disorders Identification Test (WHO 2001, in use 2026)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Q1 How often do you drink", "Never", "0"],
        ["Q1 How often do you drink", "Monthly or less", "1"],
        ["Q1 How often do you drink", "2-4 times a month", "2"],
        ["Q1 How often do you drink", "2-3 times a week", "3"],
        ["Q1 How often do you drink", "4 or more times a week", "4"],
        ["Q2 Standard drinks on a typical day", "1 or 2", "0"],
        ["Q2 Standard drinks on a typical day", "3 or 4", "1"],
        ["Q2 Standard drinks on a typical day", "5 or 6", "2"],
        ["Q2 Standard drinks on a typical day", "7 to 9", "3"],
        ["Q2 Standard drinks on a typical day", "10 or more", "4"],
        ["Q3 How often 6 or more drinks at once", "Never", "0"],
        ["Q3 How often 6 or more drinks at once", "Less than monthly", "1"],
        ["Q3 How often 6 or more drinks at once", "Monthly", "2"],
        ["Q3 How often 6 or more drinks at once", "Weekly", "3"],
        ["Q3 How often 6 or more drinks at once", "Daily or almost daily", "4"],
        ["Q4-Q8 each, in the last year", "Never", "0"],
        ["Q4-Q8 each, in the last year", "Less than monthly", "1"],
        ["Q4-Q8 each, in the last year", "Monthly", "2"],
        ["Q4-Q8 each, in the last year", "Weekly", "3"],
        ["Q4-Q8 each, in the last year", "Daily or almost daily", "4"],
        ["Q9-Q10 each (injury; others concerned)", "No", "0"],
        ["Q9-Q10 each (injury; others concerned)", "Yes, but not in the last year", "2"],
        ["Q9-Q10 each (injury; others concerned)", "Yes, during the last year", "4"],
      ],
    },
    {
      heading: "AUDIT score risk zones and intervention (WHO; total 0-40)",
      columns: ["AUDIT total", "Zone", "Intervention"],
      rows: [
        ["0-7", "Zone I - low risk", "Alcohol education"],
        ["8-15", "Zone II - hazardous use", "Simple advice (brief intervention)"],
        ["16-19", "Zone III - harmful use", "Simple advice plus brief counselling and continued monitoring"],
        ["20-40", "Zone IV - possible dependence", "Referral to specialist for diagnostic evaluation and treatment"],
        ["Q4-Q8 items", "What they probe", "Q4 cannot stop, Q5 failed duties, Q6 morning drink, Q7 guilt, Q8 blackout"],
      ],
    },
    {
      heading: "AUDIT-C screening criteria (first 3 AUDIT items, total 0-12)",
      columns: ["Group", "Positive screen", "Note"],
      rows: [
        ["Men", "4 or more", "Higher score = more likely harmful drinking"],
        ["Women", "3 or more", "Also over-65s in many guidelines"],
        ["All", "Positive AUDIT-C", "Complete the full 10-item AUDIT"],
      ],
    },
    {
      heading: "DSM-5-TR criteria for alcohol use disorder (DSM-5-TR 2022)",
      columns: ["Criterion", "Feature (within a 12-month period)", "Domain"],
      rows: [
        ["Criterion 1", "Taken in larger amounts or over a longer period than intended", "Impaired control"],
        ["Criterion 2", "Persistent desire or unsuccessful efforts to cut down", "Impaired control"],
        ["Criterion 3", "Great deal of time obtaining, using or recovering", "Impaired control"],
        ["Criterion 4", "Craving or strong urge to use", "Impaired control"],
        ["Criterion 5", "Recurrent use causing failure at work, school or home", "Social impairment"],
        ["Criterion 6", "Continued use despite social or interpersonal problems", "Social impairment"],
        ["Criterion 7", "Important activities given up or reduced", "Social impairment"],
        ["Criterion 8", "Recurrent use in physically hazardous situations", "Risky use"],
        ["Criterion 9", "Continued use despite known physical or psychological harm", "Risky use"],
        ["Criterion 10", "Tolerance", "Pharmacological"],
        ["Criterion 11", "Withdrawal, or drinking to relieve withdrawal", "Pharmacological"],
      ],
    },
    {
      heading: "DSM-5-TR alcohol use disorder severity (DSM-5-TR 2022)",
      columns: ["Severity", "Criteria met", "Specifier note"],
      rows: [
        ["Mild", "2-3 of 11", "-"],
        ["Moderate", "4-5 of 11", "-"],
        ["Severe", "6 or more of 11", "Roughly equals ICD-11 alcohol dependence"],
        ["In early remission", "No criteria (except craving) for 3 to under 12 months", "-"],
        ["In sustained remission", "No criteria (except craving) for 12 months or more", "Add in a controlled environment if applicable"],
      ],
    },
    {
      heading: "CIWA-Ar alcohol withdrawal scale - anchor points (ASAM 2020)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Nausea and vomiting", "None", "0"],
        ["Nausea and vomiting", "Mild nausea, no vomiting", "1"],
        ["Nausea and vomiting", "Intermittent nausea with dry heaves", "4"],
        ["Nausea and vomiting", "Constant nausea, frequent dry heaves and vomiting", "7"],
        ["Tremor (arms extended)", "No tremor", "0"],
        ["Tremor (arms extended)", "Not visible, felt fingertip to fingertip", "1"],
        ["Tremor (arms extended)", "Moderate with arms extended", "4"],
        ["Tremor (arms extended)", "Severe, even with arms not extended", "7"],
        ["Paroxysmal sweats", "None visible", "0"],
        ["Paroxysmal sweats", "Barely perceptible, palms moist", "1"],
        ["Paroxysmal sweats", "Beads of sweat on forehead", "4"],
        ["Paroxysmal sweats", "Drenching sweats", "7"],
        ["Anxiety", "At ease", "0"],
        ["Anxiety", "Mildly anxious", "1"],
        ["Anxiety", "Moderately anxious or guarded", "4"],
        ["Anxiety", "Equivalent to acute panic state", "7"],
        ["Agitation", "Normal activity", "0"],
        ["Agitation", "Somewhat more than normal", "1"],
        ["Agitation", "Moderately fidgety and restless", "4"],
        ["Agitation", "Paces or thrashes about constantly", "7"],
        ["Tactile disturbances", "None", "0"],
        ["Tactile disturbances", "Very mild itching, pins and needles, burning or numbness", "1"],
        ["Tactile disturbances", "Moderately severe hallucinations", "4"],
        ["Tactile disturbances", "Continuous hallucinations", "7"],
        ["Auditory disturbances", "None", "0"],
        ["Auditory disturbances", "Very mild harshness or ability to frighten", "1"],
        ["Auditory disturbances", "Moderately severe hallucinations", "4"],
        ["Auditory disturbances", "Continuous hallucinations", "7"],
        ["Visual disturbances", "None", "0"],
        ["Visual disturbances", "Very mild sensitivity to light", "1"],
        ["Visual disturbances", "Moderately severe hallucinations", "4"],
        ["Visual disturbances", "Continuous hallucinations", "7"],
        ["Headache, fullness in head", "None", "0"],
        ["Headache, fullness in head", "Very mild", "1"],
        ["Headache, fullness in head", "Moderately severe", "4"],
        ["Headache, fullness in head", "Extremely severe", "7"],
        ["Orientation and clouding", "Oriented, can do serial additions", "0"],
        ["Orientation and clouding", "Cannot do serial additions or unsure of date", "1"],
        ["Orientation and clouding", "Disoriented for date by up to 2 days", "2"],
        ["Orientation and clouding", "Disoriented for date by over 2 days", "3"],
        ["Orientation and clouding", "Disoriented for place and/or person", "4"],
      ],
    },
    {
      heading: "CIWA-Ar severity bands (total 0-67; intermediate item scores allowed)",
      columns: ["CIWA-Ar total", "Withdrawal severity", "Management (ASAM 2020)"],
      rows: [
        ["Under 10", "Mild", "Supportive care; outpatient if no seizure/DT history; symptom-triggered benzodiazepine"],
        ["10-18", "Moderate", "Benzodiazepine (chlordiazepoxide or diazepam; lorazepam if liver disease)"],
        ["19 or more", "Severe", "Inpatient, high risk of seizures and delirium tremens; thiamine before glucose"],
      ],
    },
    {
      heading: "Clinical Opiate Withdrawal Scale (COWS) severity bands (ASAM 2020)",
      columns: ["COWS total", "Severity", "Action"],
      rows: [
        ["5-12", "Mild", "Symptomatic care (clonidine, loperamide, NSAID)"],
        ["13-24", "Moderate", "Buprenorphine induction usually started at COWS 8-12 or more"],
        ["25-36", "Moderately severe", "Buprenorphine or methadone; admit if unable to cope"],
        ["Over 36", "Severe", "Admit; exclude co-ingestion"],
        ["Items (11)", "Pulse, sweating, restlessness, pupils, aches, rhinorrhoea", "Also GI upset, tremor, yawning, anxiety, gooseflesh"],
      ],
    },
    {
      heading: "ASSIST v3.1 risk level scoring for substance involvement (WHO 2010, in use 2026)",
      columns: ["Risk level", "Alcohol score", "Other substances score", "Intervention"],
      rows: [
        ["Lower risk", "0-10", "0-3", "General health advice"],
        ["Moderate risk", "11-26", "4-26", "Brief intervention; take-home information"],
        ["High risk", "27 or more", "27 or more", "Brief intervention plus referral to specialist treatment"],
        ["Injecting (Q8)", "-", "Any injecting in past 3 months", "Risk-reduction advice, HIV/HCV testing, needle exchange"],
      ],
    },
    {
      heading: "Caine criteria for Wernicke encephalopathy in alcohol use (EFNS; OHCM 11e 2024)",
      columns: ["Criterion", "Features", "Note"],
      rows: [
        ["1 - Dietary deficiency", "Undernutrition, BMI low, poor intake, vomiting", "Diagnosis needs 2 of the 4 criteria"],
        ["2 - Eye signs", "Nystagmus, ophthalmoplegia (lateral rectus), gaze palsy", "Classic triad present in only about 10-20%"],
        ["3 - Cerebellar dysfunction", "Gait ataxia, truncal unsteadiness", "-"],
        ["4 - Mental change", "Confusion or mild memory impairment", "Treat on suspicion: IV thiamine 200-500 mg thrice daily"],
      ],
    },
  ],
  "psychiatry-tobacco-cessation": [
    {
      heading: "Fagerstrom Test for Nicotine Dependence (FTND) (Kaplan and Sadock 12e 2021)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Time to first cigarette after waking", "Within 5 minutes", "3"],
        ["Time to first cigarette after waking", "6-30 minutes", "2"],
        ["Time to first cigarette after waking", "31-60 minutes", "1"],
        ["Time to first cigarette after waking", "After 60 minutes", "0"],
        ["Difficult to refrain where forbidden", "Yes", "1"],
        ["Difficult to refrain where forbidden", "No", "0"],
        ["Cigarette you would hate most to give up", "First one in the morning", "1"],
        ["Cigarette you would hate most to give up", "Any other", "0"],
        ["Cigarettes per day", "10 or fewer", "0"],
        ["Cigarettes per day", "11-20", "1"],
        ["Cigarettes per day", "21-30", "2"],
        ["Cigarettes per day", "31 or more", "3"],
        ["Smoke more in first hours after waking", "Yes", "1"],
        ["Smoke more in first hours after waking", "No", "0"],
        ["Smoke when so ill you are in bed", "Yes", "1"],
        ["Smoke when so ill you are in bed", "No", "0"],
      ],
    },
    {
      heading: "FTND score dependence bands (total 0-10)",
      columns: ["FTND total", "Nicotine dependence", "Pharmacotherapy pointer"],
      rows: [
        ["0-2", "Very low", "Behavioural support; NRT if wanted"],
        ["3-4", "Low", "NRT (patch) plus counselling"],
        ["5", "Medium", "Combination NRT or varenicline"],
        ["6-7", "High", "Varenicline or combination NRT; higher NRT dose"],
        ["8-10", "Very high", "Varenicline plus NRT; close follow-up (quitline 1800-112-356 in India)"],
      ],
    },
    {
      heading: "Heaviness of Smoking Index (HSI) scoring (NCSCT; WHO 2024 cessation)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Time to first cigarette", "Within 5 minutes", "3"],
        ["Time to first cigarette", "6-30 minutes", "2"],
        ["Time to first cigarette", "31-60 minutes", "1"],
        ["Time to first cigarette", "After 60 minutes", "0"],
        ["Cigarettes per day", "31 or more", "3"],
        ["Cigarettes per day", "21-30", "2"],
        ["Cigarettes per day", "11-20", "1"],
        ["Cigarettes per day", "10 or fewer", "0"],
      ],
    },
    {
      heading: "HSI score bands (total 0-6)",
      columns: ["HSI total", "Dependence", "Note"],
      rows: [
        ["0-1", "Low", "Two-question quick version of FTND"],
        ["2-4", "Moderate", "Pharmacotherapy recommended"],
        ["5-6", "High", "Combination therapy, higher NRT dose"],
      ],
    },
  ],
  "psychiatry-insomnia-sleep": [
    {
      heading: "DSM-5-TR criteria for insomnia disorder (DSM-5-TR 2022)",
      columns: ["Criterion", "Requirement", "Note"],
      rows: [
        ["A - complaint", "Dissatisfaction with sleep quantity or quality: difficulty initiating, maintaining, or early waking", "At least one of the three"],
        ["B - impact", "Clinically significant distress or daytime impairment", "Fatigue, mood, concentration, work"],
        ["C - frequency", "At least 3 nights per week", "-"],
        ["D - duration", "At least 3 months", "Episodic 1-3 months; persistent 3 months or more"],
        ["E - opportunity", "Occurs despite adequate opportunity for sleep", "Distinguishes from sleep deprivation"],
        ["F-H - exclusion", "Not explained by another sleep disorder, substance, or coexisting mental/medical disorder", "CBT-I is first-line treatment"],
      ],
    },
    {
      heading: "Insomnia Severity Index (ISI) score bands (AASM 2021)",
      columns: ["ISI total (7 items, 0-4 each)", "Category", "Action"],
      rows: [
        ["0-7", "No clinically significant insomnia", "Sleep hygiene advice"],
        ["8-14", "Subthreshold insomnia", "Sleep hygiene, stimulus control"],
        ["15-21", "Clinical insomnia, moderate", "CBT-I; short-term hypnotic only if needed"],
        ["22-28", "Clinical insomnia, severe", "CBT-I; screen for depression, OSA, substance use"],
      ],
    },
  ],
  "psychiatry-psychosis-schizophrenia": [
    {
      heading: "DSM-5-TR criteria for schizophrenia (DSM-5-TR 2022)",
      columns: ["Criterion", "Requirement", "Note"],
      rows: [
        ["A - characteristic symptoms", "2 or more for 1 month: delusions, hallucinations, disorganised speech or behaviour, catatonia, negative symptoms", "At least one must be delusions, hallucinations or disorganised speech"],
        ["B - dysfunction", "Work, relationships or self-care markedly below prior level", "-"],
        ["C - duration", "Continuous signs for at least 6 months, including 1 month of active symptoms", "Prodromal or residual phases count"],
        ["D - mood excluded", "Schizoaffective and mood disorder with psychotic features ruled out", "-"],
        ["E - organic excluded", "Not due to a substance or medical condition", "Check drugs (cannabis), thyroid, HIV, syphilis"],
        ["F - autism or communication disorder", "Prominent delusions or hallucinations also needed for 1 month", "-"],
      ],
    },
    {
      heading: "Types of primary psychotic disorder by duration (DSM-5-TR 2022)",
      columns: ["Disorder", "Duration of symptoms", "Note"],
      rows: [
        ["Brief psychotic disorder", "1 day to under 1 month, full return to baseline", "Often after a stressor or postpartum"],
        ["Schizophreniform disorder", "1 month to under 6 months", "About two-thirds progress to schizophrenia"],
        ["Schizophrenia", "6 months or more", "Includes prodromal and residual phases"],
        ["Delusional disorder", "1 month or more of delusions only", "Functioning otherwise preserved"],
        ["Schizoaffective disorder", "Mood episode plus psychosis, and 2 weeks of psychosis without mood episode", "-"],
      ],
    },
  ],
  "psychiatry-delirium-dementia": [
    {
      heading: "Confusion Assessment Method (CAM) diagnostic criteria for delirium (NICE CG103 2023)",
      columns: ["Feature", "Assessment", "Requirement"],
      rows: [
        ["1 - Acute onset, fluctuating course", "Change from baseline; fluctuates during the day (ask carer)", "Required"],
        ["2 - Inattention", "Easily distracted, cannot keep track (months backwards)", "Required"],
        ["3 - Disorganised thinking", "Rambling, irrelevant, illogical flow of ideas", "Either 3 or 4"],
        ["4 - Altered level of consciousness", "Anything other than alert - vigilant, lethargic, stupor, coma", "Either 3 or 4"],
        ["Diagnosis", "Delirium = 1 AND 2 AND (3 OR 4)", "Then search for cause: drugs, infection, retention, pain, electrolytes"],
      ],
    },
    {
      heading: "4AT rapid assessment test for delirium (SIGN 157 2019)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["1 Alertness", "Normal, or mild sleepiness under 10 s after waking", "0"],
        ["1 Alertness", "Clearly abnormal", "4"],
        ["2 AMT4 (age, date of birth, place, year)", "No mistakes", "0"],
        ["2 AMT4 (age, date of birth, place, year)", "1 mistake", "1"],
        ["2 AMT4 (age, date of birth, place, year)", "2 or more mistakes or untestable", "2"],
        ["3 Attention (months backwards)", "7 or more months correctly", "0"],
        ["3 Attention (months backwards)", "Starts but under 7 months, or refuses", "1"],
        ["3 Attention (months backwards)", "Untestable - unwell, drowsy, inattentive", "2"],
        ["4 Acute change or fluctuating course", "No", "0"],
        ["4 Acute change or fluctuating course", "Yes (in past 2 weeks, still evident in last 24 h)", "4"],
      ],
    },
    {
      heading: "4AT score interpretation (total 0-12)",
      columns: ["4AT total", "Meaning", "Action"],
      rows: [
        ["0", "Delirium or severe cognitive impairment unlikely", "Delirium still possible if item 4 information incomplete"],
        ["1-3", "Possible cognitive impairment", "Further cognitive testing when well"],
        ["4 or more", "Possible delirium with or without cognitive impairment", "Full clinical assessment and cause search"],
      ],
    },
    {
      heading: "Richmond Agitation-Sedation Scale (RASS) (SCCM PADIS 2018)",
      columns: ["Level", "Term", "Description"],
      rows: [
        ["+4", "Combative", "Overtly combative, violent, immediate danger to staff"],
        ["+3", "Very agitated", "Pulls or removes tubes or catheters; aggressive"],
        ["+2", "Agitated", "Frequent non-purposeful movement; fights ventilator"],
        ["+1", "Restless", "Anxious but movements not aggressive or vigorous"],
        ["0", "Alert and calm", "-"],
        ["-1", "Drowsy", "Not fully alert; sustained eye opening and contact to voice over 10 s"],
        ["-2", "Light sedation", "Briefly awakens with eye contact to voice under 10 s"],
        ["-3", "Moderate sedation", "Movement or eye opening to voice, but no eye contact"],
        ["-4", "Deep sedation", "No response to voice; movement or eye opening to physical stimulation"],
        ["-5", "Unrousable", "No response to voice or physical stimulation"],
      ],
    },
    {
      heading: "Mini-Cog screening for cognitive impairment (Alzheimer's Association 2023)",
      columns: ["Component", "Finding", "Points"],
      rows: [
        ["Three-word recall", "3 words recalled", "3"],
        ["Three-word recall", "2 words recalled", "2"],
        ["Three-word recall", "1 word recalled", "1"],
        ["Three-word recall", "None recalled", "0"],
        ["Clock drawing (11:10)", "Normal - all numbers correct, hands to 11 and 2", "2"],
        ["Clock drawing (11:10)", "Abnormal or refused", "0"],
      ],
    },
    {
      heading: "Mini-Cog score interpretation (total 0-5)",
      columns: ["Mini-Cog total", "Meaning", "Action"],
      rows: [
        ["0-2", "Screen positive", "Full cognitive assessment (MoCA), bloods, consider imaging"],
        ["3-5", "Screen negative", "Cut-off under 4 used by some for higher sensitivity"],
      ],
    },
    {
      heading: "MMSE and MoCA cut-offs for cognitive impairment severity (NICE TA217 2018)",
      columns: ["Band", "Meaning", "Note"],
      rows: [
        ["MMSE 27-30", "Normal", "Adjust for education - low literacy lowers scores (use HMSE in Hindi)"],
        ["MMSE 21-26", "Mild Alzheimer disease (NICE)", "Traditional impairment cut-off under 24"],
        ["MMSE 10-20", "Moderate", "NICE: moderately severe 10-14"],
        ["MMSE under 10", "Severe", "Memantine alone at this stage"],
        ["MoCA 26-30", "Normal", "Add 1 point if 12 years or less of education"],
        ["MoCA under 26", "Cognitive impairment (MCI or dementia)", "More sensitive than MMSE for MCI and executive deficits"],
      ],
    },
    {
      heading: "Clinical Dementia Rating (CDR) global stages (Kaplan and Sadock 12e 2021)",
      columns: ["CDR", "Stage", "Features"],
      rows: [
        ["CDR 0", "Normal", "No memory loss or only slight inconsistent forgetfulness"],
        ["CDR 0.5", "Questionable or very mild", "Consistent slight forgetfulness; partial recall; MCI range"],
        ["CDR 1", "Mild dementia", "Moderate memory loss for recent events; cannot function independently in community affairs"],
        ["CDR 2", "Moderate dementia", "Severe memory loss; only simple chores; needs help with personal care"],
        ["CDR 3", "Severe dementia", "Only fragments of memory; needs much help with personal care, often incontinent"],
        ["Domains (6)", "Memory, orientation, judgement, community affairs, home and hobbies, personal care", "Memory is the primary domain"],
      ],
    },
    {
      heading: "Reisberg Global Deterioration Scale and FAST stages (Kaplan and Sadock 12e 2021)",
      columns: ["Stage", "Clinical phase", "Typical function"],
      rows: [
        ["Stage 1", "No cognitive decline", "Normal"],
        ["Stage 2", "Very mild - subjective complaints", "Misplaces objects; normal to others"],
        ["Stage 3", "Mild cognitive decline (MCI)", "Deficits noticed at work or in demanding tasks"],
        ["Stage 4", "Moderate decline - mild dementia", "Needs help with complex tasks: finances, travel, meal planning"],
        ["Stage 5", "Moderately severe - moderate dementia", "Needs help choosing clothes; forgets address or phone number"],
        ["Stage 6", "Severe decline (6a-6e)", "Needs help dressing, bathing, toileting; then urinary and faecal incontinence"],
        ["Stage 7", "Very severe (7a-7f)", "Speech to few words, loses walking, sitting, smiling, head control; 7a = hospice marker"],
      ],
    },
  ],
};

export default scores;
