import type { Topic } from "../src/lib/types";

const topics: Topic[] = [];

topics.push({
  id: "pediatrics-oral-thrush",
  title: "Oral thrush and oral candidiasis",
  oneLiner:
    "Oral thrush is an opportunistic fungal infection of the oral mucosa caused most often by Candida albicans, a normal commensal of the mouth, and it presents classically as creamy-white curd-like pseudomembranous plaques on the tongue, palate and buccal mucosa that can be scraped off to leave a raw or erythematous, sometimes bleeding, base - so its appearance always signals a change in the host or in the local oral environment rather than the arrival of a new organism.",
  frequency: "less-common",
  keywords: [
    "oral thrush",
    "oral candidiasis",
    "Candida albicans",
    "pseudomembranous candidiasis",
    "denture stomatitis",
    "angular cheilitis",
    "median rhomboid glossitis",
    "chronic hyperplastic candidiasis",
    "candidal leukoplakia",
    "nystatin",
    "clotrimazole troche",
    "fluconazole",
    "miconazole oral gel",
    "potassium hydroxide mount",
    "oral hairy leukoplakia",
    "oesophageal candidiasis",
    "germ tube test",
    "nipple candidiasis",
  ],
  sections: [
    {
      heading: "What it is: the organism, the commensal state and the clinical variants",
      points: [
        "**Oral candidiasis is an opportunistic infection of the oral mucosa by yeasts of the genus Candida**, of which **Candida albicans accounts for 50-90% of isolates**; the rest are non-albicans species - **C. glabrata, C. tropicalis, C. krusei, C. parapsilosis and, in HIV, C. dubliniensis** - which matter because several of them are less susceptible or intrinsically resistant to fluconazole.",
        "**Candida is a normal commensal, carried asymptomatically in the mouth of 30-60% of healthy adults and up to 45% of newborns.** It follows that thrush is never simply an infection acquired from outside: **disease means that something has changed in the host or in the local environment** - immunity, saliva, mucosal integrity, the competing bacterial flora, or the surface the yeast is growing on. The single most useful clinical habit in this topic is to treat the fungus and then go looking for that change.",
        "The transition from commensal to pathogen depends on **adhesion to epithelium, germ tube and hyphal formation (the invasive form), secreted aspartyl proteinases and phospholipases, and biofilm formation** on denture acrylic and on the mucosa itself - the biofilm is why a denture that is not disinfected re-infects a cured palate within days.",
        "**Acute pseudomembranous candidiasis (thrush proper)** is the form the exam means: **creamy-white or yellowish, curd-like, slightly raised plaques on the buccal mucosa, tongue, palate, gingiva and oropharynx which can be wiped or scraped off with a spatula or gauze to leave an erythematous, raw and sometimes bleeding base.** The infant may be irritable, refuse the breast or feed slowly; the adult complains of a bad or metallic taste, soreness and a burning mouth. **A chronic pseudomembranous form, persisting for months, is seen in HIV and in patients on long-term inhaled or systemic steroids.**",
        "**Acute erythematous (atrophic) candidiasis - 'antibiotic sore mouth'** - is a **flat, red, painful, often glazed and depapillated area, most often on the dorsum of the tongue and the palate, with no white plaque at all**, following a course of broad-spectrum antibiotics or the use of inhaled corticosteroids. It is the **one painful form** of oral candidiasis and the one most often missed, because the clinician is looking for white and finds only red.",
        "**Chronic erythematous candidiasis (denture stomatitis)** is **erythema and oedema sharply limited to the mucosa covered by an upper denture**, characteristically **asymptomatic**, and graded by **Newton: type I pinpoint hyperaemia, type II diffuse erythema of the whole denture-bearing area, type III granular or papillary hyperplasia of the central palate**. It affects **up to 65% of complete denture wearers** and is a chief geriatric presentation, commonly with angular cheilitis alongside it.",
        "**Chronic hyperplastic candidiasis (candidal leukoplakia)** is a **firm, adherent white plaque, usually bilateral behind the commissures of the buccal mucosa, in a middle-aged male smoker, which does NOT rub off**; it is **the only variant with recognised malignant potential** - dysplasia is found in a substantial minority and reported transformation rates run higher than for other leukoplakias - so **it must be biopsied, treated with a prolonged systemic antifungal, and re-assessed, with excision if dysplasia persists.**",
        "**Two Candida-associated lesions complete the list. Angular cheilitis (perleche)** - fissured, crusted, sore erythema at one or both angles of the mouth, usually a **mixed Candida and Staphylococcus aureus infection**, driven by a reduced vertical dimension in the edentulous or ill-fitting denture, drooling, and by **iron, folate or B12 deficiency**. **Median rhomboid glossitis** - a **well-demarcated, rhomboid, depapillated red or nodular area in the midline dorsum of the tongue just in front of the circumvallate papillae**, painless, linked to smoking and inhaled steroids, sometimes with a matching 'kissing lesion' on the palate. **Linear gingival erythema**, a red band along the free gingival margin unresponsive to plaque control, is an HIV-associated variant.",
      ],
    },
    {
      heading: "Causes and risk factors - grouped as they should be written in the answer book",
      points: [
        "**Age extremes - the neonate and the infant.** An **immature cell-mediated immunity and an undeveloped oral flora**, a **milk-fed mouth** whose residue is a carbohydrate substrate and whose low salivary flow during sleep favours the yeast, **acquisition during passage through a colonised birth canal** (maternal vaginal candidiasis in pregnancy), and **cross-infection from contaminated teats, feeding bottles, dummies, unwashed hands and maternal nipple candidiasis**. **Thrush occurs in about 5% of normal newborns and in up to 10% of infants in the first month**, and in the healthy term infant it is a trivial, self-limiting nuisance - it is thrush in the **unwell, febrile, preterm or persistently affected** infant that matters.",
        "**Age extremes - the elderly.** **Dentures worn continuously, poor denture hygiene and an ill-fitting denture**, **xerostomia**, **poor nutrition with iron, folate, B12 or protein deficiency**, polypharmacy, reduced manual dexterity for oral hygiene, institutional care, and coexisting chronic disease. **Denture stomatitis and angular cheilitis are the geriatric face of this topic.**",
        "**Local factors.** **Inhaled corticosteroids used without rinsing the mouth or a spacer** (the commonest iatrogenic cause in general practice - about 5% of regular users); **dentures worn overnight**; **xerostomia** from anticholinergics, tricyclic antidepressants, antihistamines, diuretics, antipsychotics and opioids, from **Sjogren syndrome**, or from **head and neck radiotherapy**, which is the most severe dry mouth of all; **smoking**; a **high-carbohydrate or high-sugar diet and frequent sugary drinks**; **orthodontic appliances and any intraoral prosthesis**; mucosal trauma, a sharp tooth, and a pre-existing lichen planus or leukoplakia.",
        "**Drugs.** **Broad-spectrum antibiotics** (they remove the competing bacterial flora - the classic 'antibiotic sore mouth'); **corticosteroids, inhaled, topical, oral or intravenous**; **cytotoxic chemotherapy**, which combines mucositis with neutropenia; **immunosuppressants after transplantation**; and any drug causing a dry mouth.",
        "**Systemic disease and immunosuppression.** **Uncontrolled diabetes mellitus** - hyperglycaemia raises the salivary glucose, impairs neutrophil function and increases candidal adhesion, and **new-onset or recurrent thrush in an adult is an indication to check a fasting glucose or HbA1c**. **HIV infection** - oral candidiasis is one of the earliest and commonest HIV-associated oral lesions and a **WHO clinical stage 3 condition**, so **oropharyngeal thrush in an adult or adolescent with no other explanation must prompt an HIV test after counselling**; oesophageal candidiasis is stage 4.",
        "**Continuing the systemic list:** **malignancy, especially haematological, and its chemotherapy or radiotherapy**; **iron, folate and vitamin B12 deficiency** (also the reason for the atrophic tongue and the angular cheilitis beside it); **endocrinopathies - hypothyroidism, hypoparathyroidism, hypoadrenalism and Cushing syndrome**; **chronic mucocutaneous candidiasis** and the **autoimmune polyendocrinopathy-candidiasis-ectodermal dystrophy (APECED, AIRE gene)** syndrome, in which persistent candidiasis of mouth, nails and skin from infancy precedes hypoparathyroidism and Addison disease; **primary immunodeficiency (SCID, DiGeorge, chronic granulomatous disease)**; **protein-energy malnutrition and severe acute malnutrition**; and **advanced age with frailty, end-stage renal or liver disease and terminal illness**.",
        "**The single most examinable statement in this section:** oral thrush in a **healthy neonate or a young infant, or after an antibiotic course, or in an inhaled-steroid user who does not rinse, needs no work-up beyond treatment and advice** - whereas **oral thrush in an otherwise healthy adult, or thrush that is recurrent, extensive, or fails topical treatment, is never a diagnosis in itself: it is a sign, and the diagnosis is diabetes, HIV, malignancy, a nutritional deficiency or an unrecognised drug, until proved otherwise.**",
      ],
    },
    {
      heading: "Diagnosis: the bedside test, the laboratory and the differential",
      points: [
        "**The diagnosis is clinical.** In a symptomatic patient with the appropriate risk factor, **a white plaque that can be scraped off with a wooden spatula or gauze to reveal an erythematous, raw or bleeding base is diagnostic of pseudomembranous candidiasis** - this single manoeuvre is the discriminator the examiner is listening for, and it separates thrush at once from milk curds (which come off leaving normal pink mucosa), from leukoplakia, lichen planus and oral hairy leukoplakia (which do not come off at all).",
        "**Take a history for the cause in every case:** antibiotics, inhaled or systemic steroids and inhaler technique, denture wear and denture hygiene, dry mouth and its drugs, smoking, diabetes, HIV risk, weight loss, chemotherapy, and in the infant, the feeding method, the mother's nipple pain and the sterilisation practice. **Examine the whole mouth with a good light and a spatula, including under the denture** - the denture must be taken out, or type II denture stomatitis is simply not seen - and look at the angles of the mouth, the tongue, the pharynx and the cervical nodes.",
        "**A bedside potassium hydroxide (KOH) mount is the confirmatory test where it is available:** scrape the plaque, place it on a slide with a drop of **10-20% KOH**, and look for **budding yeast cells with pseudohyphae**. **A Gram stain of the same smear shows Gram-positive oval budding yeasts with pseudohyphae**, and a **periodic acid-Schiff (PAS) stain** demonstrates them best. **The presence of pseudohyphae, not yeasts alone, indicates invasion** - yeasts alone may be commensal carriage.",
        "**Swab and culture are not needed for routine thrush**, because Candida grows from a normal mouth. **Culture on Sabouraud dextrose agar is indicated when treatment has failed, in recurrent disease, in the immunosuppressed, and before starting an azole in a patient who has had azoles before** - it identifies the species and allows susceptibility testing. **The germ tube test (Reynolds-Braude phenomenon) at 2-3 hours in serum identifies C. albicans and C. dubliniensis**; CHROMagar and biochemical panels speciate the rest. A **quantitative oral rinse or imprint culture** distinguishes carriage from infection in research settings.",
        "**Biopsy is mandatory for a white lesion that does not scrape off** - that is, for suspected **chronic hyperplastic candidiasis, leukoplakia, lichen planus or carcinoma** - and for **any oral lesion that has not resolved after adequate antifungal treatment**. The PAS stain shows hyphae invading the parakeratin, and the report also grades dysplasia, which is the reason the biopsy was taken.",
        "**Look for the underlying cause with targeted tests, not a shotgun panel:** **random or fasting blood glucose and HbA1c**; **HIV testing after pre-test counselling in every adult with unexplained thrush**; **haemoglobin, peripheral smear, serum ferritin, vitamin B12 and folate**, especially with angular cheilitis or a smooth tongue; **thyroid function and, in the child with persistent candidiasis, serum calcium** for hypoparathyroidism; and a **CD4 count and viral load** in the known HIV-positive patient.",
        "**The differential diagnosis of the white or red oral lesion**, which is asked as a short note in its own right: **milk curds** in an infant (wipe off leaving normal mucosa, no erythema, related to the last feed); **leukoplakia** (adherent, cannot be rubbed off, a diagnosis of exclusion, premalignant); **oral lichen planus** (bilateral lacy **Wickham striae** on the buccal mucosa, may be erosive and painful); **oral hairy leukoplakia** (corrugated vertical white streaks on the **lateral border of the tongue**, EBV, does not scrape off, an HIV marker); **aphthous ulceration** (painful, punched-out, yellow-grey floor with an erythematous halo, recurrent); **primary herpetic gingivostomatitis** (a febrile toddler with vesicles becoming ulcers, an intensely inflamed bleeding gingiva and cervical nodes); **geographic tongue** (benign migratory glossitis - red patches with white serpiginous borders that move from day to day); **a chemical or thermal burn** (aspirin held against the mucosa, a hot drink - history is everything); and **Koplik spots** (bluish-white 1 mm grains on an erythematous buccal mucosa opposite the second molars, in the prodrome of measles, disappearing as the rash appears).",
      ],
    },
    {
      heading: "Treatment: treat the cause, then the fungus - topical first, systemic when it is earned",
      points: [
        "**Correct the predisposing factor first, or the thrush comes straight back:** stop the unnecessary antibiotic, teach rinsing and spitting after the inhaler and add a spacer, take the denture out at night and disinfect it, control the diabetes, treat the iron or B12 deficiency, manage the dry mouth, stop smoking, sterilise the teats and the dummy, and start antiretroviral therapy in HIV - **ART is the definitive treatment of recurrent oral candidiasis in HIV**, and no antifungal course substitutes for it.",
        "**Topical therapy is first line for mild to moderate disease in an immunocompetent patient. Nystatin oral suspension 100,000 units/mL** - **neonate: 1 mL (100,000 units) four times daily, dropped into each side of the mouth; infant and child: 1-2 mL (100,000-200,000 units) four times daily; older child and adult: 4-6 mL (400,000-600,000 units) four times daily, swished and held in the mouth for several minutes before swallowing.** **Give it after feeds or after food, not before**, so it is not washed away; in the infant, apply it with a clean finger or a swab to the whole mucosa including under the tongue. Continue for **7-14 days and for at least 48 hours after the mouth looks clear.** Nystatin is not absorbed, is safe in the neonate, tastes unpleasant, and its sucrose content makes prolonged unsupervised use a caries risk.",
        "**Clotrimazole troches (lozenges) 10 mg dissolved slowly in the mouth five times daily for 7-14 days** are the IDSA first-line topical agent in adults and older children and are more effective than nystatin in most comparisons - but **troches are not reliably available in India**, where the practical equivalent is **1% clotrimazole mouth paint applied to the lesions three to four times daily**. Troches must not be chewed or swallowed whole, and are unsuitable for a child too young to hold a lozenge safely.",
        "**Miconazole oral gel 2% (24 mg/mL)** is highly effective and, being a mucoadhesive, outperforms nystatin in several trials: **infant 1 month to 1 year, 1.25 mL four times daily; child 2 years and over and adult, 2.5 mL four times daily**, smeared onto the lesions after food and held in the mouth, continued for **7 days after healing**. **Two cautions must be stated. First, the interaction with warfarin: even the oral gel is absorbed enough to inhibit CYP2C9 and has caused dangerous rises in INR and bleeding - avoid it in a patient on warfarin, or if it is unavoidable, monitor the INR closely; it also interacts with statins, sulfonylureas and phenytoin. Second, choking: regulatory guidance in the UK and EU contraindicates the gel under 4 months of age and in anyone with impaired swallowing, because the gel can obstruct the pharynx, while Indian and many other practice guidelines still use it in younger infants applied in small amounts to the mucosa with a finger. Guidance genuinely differs here** - the safe course is nystatin under 4 months, and miconazole gel above that, applied in small aliquots and never as a bolus at the back of the mouth.",
        "**Gentian violet 0.5-1% aqueous solution painted once or twice daily for up to 3 days** is cheap, effective and still recommended by the WHO where nothing else is available. **Its place is genuinely contested:** it stains the mouth, the clothes and the mother's blouse a violet that alarms families, **stronger or prolonged application causes mucosal irritation, ulceration and necrosis**, and animal carcinogenicity data have led several regulators to withdraw it for oral use. **Reserve it for resource-limited settings, use the 0.5% strength, and limit it to a few days.**",
        "**Systemic therapy - oral fluconazole - is indicated for moderate to severe disease, immunosuppression (HIV, chemotherapy, transplantation), oesophageal involvement, and any case that has failed adequate topical treatment. Adult: 100-200 mg once daily for 7-14 days** (a 200 mg loading dose on day 1 is common practice). **Child: 6 mg/kg on day 1 then 3 mg/kg once daily, maximum 400 mg/day, for 7-14 days.** **Neonate: 6 mg/kg, but the dosing interval is extended for renal immaturity - every 72 hours in the first 2 weeks of life and every 48 hours from 2 to 4 weeks.** **Oesophageal candidiasis needs 200-400 mg (3-6 mg/kg) daily for 14-21 days and always a systemic drug** - topical agents do not treat it. Fluconazole is well absorbed, cheap and widely available in India as 50, 100, 150 and 200 mg tablets and a 50 mg/5 mL suspension; check for hepatotoxicity, QT prolongation and interactions (warfarin, phenytoin, rifampicin, statins) and avoid it in the first trimester at repeated doses.",
        "**In the breastfed infant, treat the mother's nipples at the same time or the infection ping-pongs between mouth and breast.** Apply **miconazole 2% cream or nystatin cream to both nipples and areolae after every feed** for 14 days, wiping off the excess before the next feed; persistent, deep, burning, radiating breast pain may need **oral fluconazole for the mother, 150-400 mg as a loading dose then 100 mg daily for 10-14 days**, which is compatible with breastfeeding. **How routinely to do this is disputed:** the Academy of Breastfeeding Medicine points out that nipple candidiasis is over-diagnosed, and that most sore nipples are due to a poor latch, tongue-tie, vasospasm or a bacterial infection - so **check the latch and examine the nipple before assuming thrush**, and always treat the pair together when the infant genuinely has thrush and the mother has nipple pain.",
        "**The denture wearer needs denture treatment, not just mouth treatment:** **remove the denture at night and every night**, brush it inside and out with soap and a denture brush after meals, and **soak it overnight in a chlorhexidine 0.2% solution, a sodium hypochlorite solution (dilute household bleach, for acrylic dentures only, not for metal ones), or an alkaline peroxide denture cleanser**; apply the antifungal (nystatin or miconazole gel) **to the fitting surface of the denture as well as to the palate**; and refer for relining or remaking an ill-fitting denture. **Newton type III papillary hyperplasia may need surgical reduction.**",
        "**Refractory and recurrent disease.** First **check adherence, technique and the persisting cause** (is the denture still worn at night, is the diabetes still uncontrolled, is the inhaler still unrinsed, is HIV untreated). Then **culture and speciate: C. krusei is intrinsically fluconazole-resistant and C. glabrata is often resistant**, and fluconazole-refractory disease is treated with **itraconazole oral solution 200 mg daily**, **posaconazole suspension 400 mg twice daily for 3 days then 400 mg daily**, or **voriconazole 200 mg twice daily**, for up to 28 days; an **intravenous echinocandin or amphotericin B deoxycholate 0.3 mg/kg daily** is reserved for the failed or severely ill patient. **Chronic suppressive fluconazole 100 mg three times a week** is an option for the patient with disabling recurrences whose immunosuppression cannot be corrected.",
      ],
    },
    {
      heading: "Prevention",
      points: [
        "**In the infant: sterilise everything that goes into the mouth.** Boil teats, bottles, nipple shields, pacifiers and breast-pump parts for **at least 5-10 minutes daily, or use a proper steam or chemical steriliser**, discard and replace teats and dummies after an episode of thrush (or after 7 days of treatment, since the yeast survives on the rubber), do not share bottles or spoons between infants, wash hands before feeding, and avoid dipping the dummy in honey or sugar. **Do not leave the infant to sleep with a bottle in the mouth.**",
        "**Breastfeeding hygiene and treatment of maternal candidiasis:** treat vaginal candidiasis in the third trimester of pregnancy to reduce colonisation of the newborn at delivery, keep the nipples clean and dry between feeds, change breast pads frequently, air-dry the nipples, and **treat the mother's nipples whenever the infant is treated for thrush** so that reinfection does not occur. Exclusive breastfeeding itself is protective; wipe the infant's mouth with clean water after formula feeds.",
        "**After every dose of an inhaled corticosteroid, rinse the mouth with water, gargle and spit it out, and brush the teeth or at least drink water; use a spacer with a metered-dose inhaler, take the inhaler before brushing at night, and use the lowest effective dose.** This one instruction, given at the time the inhaler is first prescribed and checked at each review, prevents almost all steroid-related thrush - and the same advice covers the child on a nebulised or inhaled steroid and the patient using a steroid mouthwash.",
        "**Denture hygiene and taking the dentures out at night.** Clean the denture after every meal, brush it mechanically (which removes the biofilm that soaking alone will not), **soak it overnight in a disinfectant solution and never sleep in it**, keep it in water when out, have it checked for fit annually and relined when it becomes loose, and clean the palate and tongue with a soft brush before reinserting it in the morning.",
        "**General oral hygiene and hydration:** brush twice daily with a soft brush including the tongue, use dental floss, treat caries and periodontal disease, keep the mouth wet with frequent sips of water, sugar-free chewing gum or a saliva substitute in xerostomia, avoid frequent sugary drinks, and stop smoking - smoking cessation alone clears a proportion of median rhomboid glossitis and chronic hyperplastic lesions. **A chlorhexidine 0.2% mouthwash reduces candidal load, but should not be used within 30 minutes of nystatin, which it inactivates.**",
        "**Control the systemic driver:** tight **glycaemic control** in diabetes, correction of **iron, folate and B12 deficiency and of protein-energy malnutrition**, treatment of hypothyroidism and hypoparathyroidism, and **antiretroviral therapy in HIV** - the incidence of oral candidiasis falls dramatically once the CD4 count recovers, which is why ART, and not repeated fluconazole, is the preventive strategy in HIV.",
        "**Prudent antibiotic use** - avoid unnecessary and unnecessarily broad antibiotics, keep courses short, and warn the patient starting a broad-spectrum agent that a sore mouth may follow. **Good oral care during chemotherapy and head and neck radiotherapy** - a soft brush, saline or bicarbonate rinses, dental clearance before treatment - reduces mucositis and superinfection.",
        "**Chemoprophylaxis is for defined high-risk groups only, not for the general patient: fluconazole prophylaxis for neutropenic patients undergoing induction chemotherapy or stem-cell transplantation, and fluconazole 3-6 mg/kg twice weekly for 6 weeks for very low birth weight neonates (under 1000 g) in neonatal units with a high incidence of invasive candidiasis** (nystatin prophylaxis is an alternative where fluconazole is not feasible). **Routine primary antifungal prophylaxis is NOT recommended in HIV** because of the risk of resistance; ART and treatment of episodes as they occur is the policy.",
      ],
    },
    {
      heading: "Follow-up, complications and referral",
      points: [
        "**Review at 7-14 days.** Most thrush in an immunocompetent patient clears within a week of correct topical treatment. **Failure to clear means one of four things: the wrong diagnosis, poor adherence or poor technique, an uncorrected predisposing cause, or a resistant or non-albicans species** - work through them in that order before escalating the drug.",
        "**Oesophageal candidiasis** is the commonest complication and is almost always a marker of significant immunosuppression. It presents with **odynophagia, retrosternal burning or pain on swallowing, and dysphagia**, and **oral thrush is present in most but not all cases**. In an HIV-positive patient with thrush plus odynophagia, **treat empirically with systemic fluconazole 200-400 mg daily and endoscope only if there is no improvement within 72 hours**; the endoscopic appearance is white plaques on a friable mucosa, and biopsy or brushing excludes CMV and herpes oesophagitis, which cause discrete ulcers.",
        "**Invasive and systemic candidiasis** - candidaemia, renal, cardiac, ocular and CNS involvement - occurs in the **very low birth weight neonate** (a leading cause of late-onset neonatal sepsis, with a high mortality and a real risk of neurodevelopmental impairment) and in the **profoundly neutropenic or ICU patient with a central line**. Oral thrush is not itself the portal in most cases, but **thrush in an unwell, febrile, lethargic or poorly feeding neonate should trigger a full septic screen, blood culture and admission, not a bottle of nystatin.**",
        "**In the infant, the complications are mechanical and nutritional:** pain on sucking leading to **feeding refusal, reduced intake, poor weight gain and failure to thrive**, dehydration in a young infant who will not feed, an unsettled irritable baby, and - in the mother - severe nipple pain that leads to **premature weaning**, which is itself the most important preventable outcome. Weigh every infant with persistent thrush and plot it. **Coexisting candidal napkin dermatitis** (beefy-red confluent erythema with satellite pustules involving the skin creases) is common and needs a topical imidazole cream.",
        "**Investigate for an underlying condition when the picture is not simple: test for HIV in any adult or adolescent with unexplained oral candidiasis, and in any infant with persistent or recurrent thrush beyond 6-12 months of age; check blood glucose and HbA1c; check haemoglobin, ferritin, B12 and folate; and think of malignancy in an older smoker with a lesion that will not clear.** In a child with candidiasis of mouth, nails and skin from infancy, think of **chronic mucocutaneous candidiasis and APECED**, and check serum calcium and morning cortisol.",
        "**Refer to a physician or paediatrician** for a neonate who is systemically unwell, an infant failing to thrive, a newly diagnosed HIV infection, suspected oesophageal candidiasis, or thrush refractory to systemic fluconazole. **Refer to a dentist or prosthodontist** for denture stomatitis with an ill-fitting or unhygienic denture, Newton type III papillary hyperplasia, and angular cheilitis with a lost vertical dimension.",
        "**Refer to an oral medicine or maxillofacial surgeon urgently for biopsy** any **white or red patch that does not scrape off, any lesion persisting beyond 2-3 weeks of adequate treatment, any indurated, ulcerated or fixed lesion, and any suspected chronic hyperplastic candidiasis** - and follow the treated hyperplastic lesion long term, because its malignant potential does not disappear when the fungus does.",
      ],
    },
  ],
  tables: [
    {
      heading: "The clinical variants of oral candidiasis",
      columns: ["Variant", "Appearance", "Typical patient", "Scrapes off?", "Treatment"],
      rows: [
        [
          "Acute pseudomembranous (thrush)",
          "Creamy-white curd-like plaques on tongue, palate, buccal mucosa; erythematous raw base beneath",
          "Neonate and infant; after antibiotics; inhaled steroids; HIV; chemotherapy",
          "Yes - leaves a raw, sometimes bleeding base",
          "Nystatin suspension or miconazole gel 7-14 days; fluconazole if moderate to severe or immunosuppressed",
        ],
        [
          "Acute erythematous (antibiotic sore mouth)",
          "Flat red, glazed, painful, depapillated area, usually dorsum of tongue and palate; NO white plaque",
          "After a broad-spectrum antibiotic course; inhaled steroid user",
          "No plaque to scrape",
          "Stop or complete the antibiotic; topical nystatin or miconazole; correct inhaler technique",
        ],
        [
          "Chronic erythematous (denture stomatitis)",
          "Erythema and oedema confined exactly to the denture-bearing palate; Newton I pinpoint, II diffuse, III papillary",
          "Elderly complete-denture wearer, denture worn at night; usually asymptomatic",
          "No",
          "Denture out at night, brush and overnight disinfection, antifungal to the fitting surface and the palate; reline or remake; surgery for type III",
        ],
        [
          "Chronic hyperplastic (candidal leukoplakia)",
          "Firm adherent white plaque, often bilateral post-commissural buccal mucosa; homogeneous or speckled",
          "Middle-aged male smoker",
          "NO - and that is the point",
          "BIOPSY mandatory; stop smoking; systemic fluconazole or itraconazole for several weeks; re-assess; excise if dysplasia persists",
        ],
        [
          "Angular cheilitis (perleche)",
          "Sore, fissured, crusted erythema at one or both angles of the mouth",
          "Denture wearer with lost vertical dimension; iron, folate or B12 deficiency; drooling child; HIV",
          "Not applicable",
          "Miconazole cream (also covers Staph aureus) or nystatin with hydrocortisone; fusidic acid if staphylococcal; correct denture height and the haematinic deficiency",
        ],
        [
          "Median rhomboid glossitis",
          "Well-defined rhomboid depapillated red or nodular area in the midline dorsum of tongue in front of the circumvallate papillae; may have a palatal kissing lesion",
          "Smoker; inhaled steroid user; diabetic; HIV",
          "No",
          "Stop smoking, correct the cause, topical antifungal; biopsy only if nodular and not settling",
        ],
        [
          "Linear gingival erythema",
          "A 2-3 mm fiery red band along the free gingival margin, out of proportion to the plaque and not responding to scaling",
          "HIV infection",
          "No",
          "Scaling and chlorhexidine, topical antifungal, and above all antiretroviral therapy",
        ],
      ],
    },
    {
      heading: "Antifungal agents for oral candidiasis - formulation, dose by age and cautions",
      columns: ["Agent and formulation", "Dose", "Duration", "Cautions and notes"],
      rows: [
        [
          "Nystatin oral suspension 100,000 units/mL (topical, not absorbed)",
          "Neonate 1 mL (100,000 units) QID; infant and child 1-2 mL (100,000-200,000 units) QID; older child and adult 4-6 mL (400,000-600,000 units) QID, held in the mouth then swallowed",
          "7-14 days, and at least 48 hours after the mouth is clear",
          "First line in the neonate and young infant. Give AFTER feeds or food. Apply to the whole mucosa with a finger or swab in an infant. Bitter taste; sucrose content is a caries risk on prolonged use; inactivated by chlorhexidine within 30 minutes",
        ],
        [
          "Clotrimazole troche 10 mg (or 1% mouth paint in India)",
          "One 10 mg troche dissolved slowly in the mouth 5 times daily; mouth paint applied to lesions 3-4 times daily",
          "7-14 days",
          "IDSA first-line topical agent in adults; troches not reliably available in India. Not for a child too young to hold a lozenge. Do not chew or swallow whole. Mild transaminase rise reported",
        ],
        [
          "Miconazole oral gel 2% (24 mg/mL), mucoadhesive",
          "Infant 1 month to 1 year 1.25 mL QID; child 2 years and over and adult 2.5 mL QID, smeared on the lesions after food",
          "7-14 days, continuing 7 days after healing",
          "AVOID with warfarin - inhibits CYP2C9 and has caused dangerous INR rises and bleeding even from the gel; also interacts with statins, sulfonylureas and phenytoin. UK and EU guidance contraindicates it under 4 months and with impaired swallowing (choking risk); Indian practice still uses small applied amounts - guidance differs, so prefer nystatin under 4 months",
        ],
        [
          "Gentian violet 0.5-1% aqueous paint",
          "Painted on the lesions once or twice daily",
          "Up to 3 days only",
          "Cheap and effective; place genuinely contested - stains everything violet, causes mucosal irritation, ulceration and necrosis at higher strengths or with prolonged use, and animal carcinogenicity data have led several regulators to withdraw it. Reserve for settings with no alternative",
        ],
        [
          "Fluconazole (systemic) - tablets 50/100/150/200 mg, suspension 50 mg/5 mL",
          "Adult 100-200 mg once daily (200 mg loading dose day 1 is usual); child 6 mg/kg day 1 then 3 mg/kg once daily, max 400 mg/day; neonate 6 mg/kg every 72 hours in the first 2 weeks, every 48 hours from 2-4 weeks; OESOPHAGEAL disease 200-400 mg (3-6 mg/kg) daily",
          "7-14 days for oropharyngeal; 14-21 days for oesophageal",
          "For moderate to severe disease, immunosuppression, oesophageal involvement, or failed topical therapy. Hepatotoxicity, QT prolongation; interacts with warfarin, phenytoin, rifampicin, statins, sulfonylureas; avoid repeated doses in the first trimester",
        ],
        [
          "Itraconazole oral solution 10 mg/mL",
          "200 mg (20 mL) once daily, swished and swallowed, on an empty stomach",
          "Up to 28 days",
          "For fluconazole-refractory disease. Solution absorbs better than capsules and is less available in India. Negative inotrope - avoid in heart failure; many CYP3A4 interactions",
        ],
        [
          "Posaconazole suspension / voriconazole / echinocandin / amphotericin B",
          "Posaconazole 400 mg BD for 3 days then 400 mg daily; voriconazole 200 mg BD; IV echinocandin; amphotericin B deoxycholate 0.3 mg/kg daily or 100 mg/mL oral suspension QID",
          "Up to 28 days, or as directed",
          "Specialist-level rescue for azole-refractory or non-albicans disease (C. krusei is intrinsically fluconazole-resistant, C. glabrata often resistant). Speciate and test susceptibility before committing",
        ],
      ],
    },
    {
      heading: "Telling the oral white lesions apart",
      columns: ["Lesion", "Site and look", "Scrapes off?", "Key clue", "What to do"],
      rows: [
        [
          "Pseudomembranous candidiasis",
          "Creamy-white curd-like plaques anywhere in the mouth",
          "Yes, leaving a raw erythematous base",
          "A predisposing factor is always present",
          "Topical antifungal; find and correct the cause",
        ],
        [
          "Milk curds (infant)",
          "White films on the tongue and palate only, related to the last feed",
          "Yes, leaving NORMAL pink mucosa",
          "No erythema, no soreness, infant feeds happily",
          "Reassure; wipe the mouth with clean water after feeds",
        ],
        [
          "Leukoplakia",
          "Adherent white patch, often floor of mouth, lateral tongue, buccal mucosa; homogeneous or speckled",
          "No",
          "A clinical diagnosis of exclusion in a smoker or tobacco chewer; premalignant",
          "BIOPSY; stop tobacco; long-term surveillance",
        ],
        [
          "Oral lichen planus",
          "Bilateral symmetrical lacy white Wickham striae on the buccal mucosa; may be erosive and painful",
          "No",
          "Bilateral, chronic, may have skin, nail and genital lesions; check for hepatitis C",
          "Biopsy if atypical or erosive; topical steroids; periodic review",
        ],
        [
          "Oral hairy leukoplakia",
          "Corrugated vertical white streaks on the LATERAL border of the tongue, often bilateral",
          "No",
          "EBV; a WHO stage 3 HIV marker; asymptomatic",
          "Test for HIV; start ART - it resolves with immune recovery",
        ],
        [
          "Chronic hyperplastic candidiasis",
          "Firm white plaque behind the commissure, buccal mucosa, usually bilateral",
          "No",
          "Male smoker; PAS shows hyphae invading the parakeratin; the only candidal lesion with malignant potential",
          "BIOPSY; systemic antifungal for weeks; excise if dysplasia persists",
        ],
        [
          "Koplik spots",
          "Bluish-white 1 mm grains on an intensely erythematous buccal mucosa opposite the second molars",
          "Not applicable",
          "Fever, cough, coryza and conjunctivitis in the measles prodrome; gone by the time the rash is out",
          "Diagnose measles; vitamin A, isolation, notify, look for complications",
        ],
        [
          "Chemical or thermal burn",
          "A white sloughy patch corresponding exactly to the site of contact",
          "The slough peels",
          "History of an aspirin tablet held against the gum, a hot drink, or a caustic",
          "Remove the cause; symptomatic care; it heals in days",
        ],
      ],
    },
  ],
  redFlags: [
    "**Oral thrush in an adult or adolescent with no obvious cause** - no antibiotics, no inhaled steroid, no denture, no diabetes. Offer an HIV test after counselling, and check blood glucose; unexplained thrush is a WHO clinical stage 3 event.",
    "**Odynophagia, retrosternal burning or dysphagia with thrush** - this is oesophageal candidiasis (WHO stage 4) until proved otherwise; it needs a systemic azole, not a topical one, and endoscopy if it does not improve within 72 hours.",
    "**An unwell, febrile, lethargic or apnoeic neonate with thrush** - suspect systemic sepsis or invasive candidiasis, especially in a preterm or very low birth weight baby with a central line; septic screen, blood culture and admission, not a bottle of nystatin.",
    "**Failure to thrive, poor feeding or dehydration in an infant with thrush** - weigh and plot; pain on sucking that reduces intake is an admission-level problem in a young infant, and it also drives premature weaning.",
    "**A white patch that does NOT scrape off** - it is not thrush. Leukoplakia, lichen planus, oral hairy leukoplakia, chronic hyperplastic candidiasis or carcinoma; it needs biopsy, not another antifungal.",
    "**Recurrence after an adequate and completed course of treatment** - look for an uncorrected cause (denture worn at night, unrinsed inhaler, uncontrolled diabetes, untreated HIV) and culture for a resistant or non-albicans species before escalating.",
    "**Thrush with weight loss, night sweats, fever, lymphadenopathy, chronic diarrhoea or oral hairy leukoplakia** - this is advanced HIV or a haematological malignancy presenting through the mouth; test, stage and refer the same day.",
  ],
  pearls: [
    "**Candida is a commensal in 30-60% of normal mouths, so thrush is never just an infection - it is a marker that the host or the local environment has changed.** Say this sentence first and the rest of the answer writes itself.",
    "**The discriminating physical sign is that the pseudomembrane scrapes off with a spatula to leave a raw, erythematous, sometimes bleeding base.** Milk curds come off leaving normal pink mucosa; leukoplakia, lichen planus and hairy leukoplakia do not come off at all.",
    "**Oral thrush in an otherwise healthy adult is an HIV test until proved otherwise** - oropharyngeal candidiasis is WHO clinical stage 3, oesophageal candidiasis is stage 4, and it is one of the earliest and commonest HIV-associated oral lesions.",
    "**Not all oral candidiasis is white.** Acute erythematous candidiasis - the antibiotic sore mouth - is a flat, red, painful, depapillated tongue with no plaque at all, and it is the form most often missed.",
    "**You cannot diagnose denture stomatitis with the denture in the mouth.** Take it out at every examination, and remember that treating the palate without disinfecting the denture guarantees relapse - the acrylic carries a biofilm.",
    "**Chronic hyperplastic candidiasis is the one variant with malignant potential**, so a white plaque that will not rub off in a middle-aged smoker is a biopsy, a prolonged systemic antifungal and long-term follow-up, not a week of nystatin.",
    "**Give nystatin after feeds, not before, and continue for 48 hours beyond clinical cure.** Treatment that stops the day the mouth looks clean is the commonest reason for a recurrence attributed to resistance.",
    "**Treat the infant's mouth and the mother's nipples together in a breastfed pair, or the infection ping-pongs** - but check the latch first, because most sore nipples are not thrush.",
    "**Miconazole oral gel and warfarin is a real and dangerous interaction** - even the gel is absorbed enough to inhibit CYP2C9 and push the INR into the bleeding range. Ask about warfarin before prescribing it.",
    "**Rinse, gargle and spit after every inhaled steroid dose, and use a spacer.** One sentence at the time of prescribing prevents almost all steroid-related thrush, and its absence is the commonest iatrogenic cause in general practice.",
    "**Topical for mild disease, systemic for moderate to severe, immunosuppressed, oesophageal or topical-failure disease** - and oesophageal candidiasis is always systemic, because nystatin and clotrimazole never reach the oesophagus in therapeutic concentration.",
  ],
  theory: [
    {
      id: "pediatrics-oral-thrush-t1",
      paper: "III",
      kind: "long",
      marks: 10,
      minutes: 18,
      frequency: "less-common",
      question: "What is oral thrush? What are its causes? How it should be treated? How it can be prevented?",
      openingLines: [
        "Oral thrush (acute pseudomembranous candidiasis) is an opportunistic fungal infection of the oral mucosa caused most often by Candida albicans, characterised by creamy-white, curd-like, slightly raised plaques on the tongue, palate, buccal mucosa and oropharynx which can be scraped off to leave an erythematous, raw and sometimes bleeding base.",
        "Candida is a normal commensal of the mouth, carried asymptomatically by 30-60% of healthy people, so the appearance of thrush always signifies a change in the host's immunity or in the local oral environment - which is why treatment has two halves: an antifungal for the fungus, and the correction of the predisposing cause without which it will simply return.",
      ],
      answer: [
        {
          heading: "What is oral thrush - definition, organism and clinical forms [2]",
          points: [
            "**Definition.** Oral thrush is an opportunistic infection of the oral mucosa by Candida species, presenting as **white, curd-like, adherent pseudomembranous plaques that can be wiped or scraped off to leave a raw, erythematous, sometimes bleeding base** - the plaque being a mat of fungal hyphae, desquamated epithelium, fibrin, food debris and inflammatory cells.",
            "**Organism.** **Candida albicans in 50-90% of cases**; the remainder are non-albicans species - C. glabrata, C. tropicalis, C. krusei, C. parapsilosis and, in HIV, C. dubliniensis - which are important because **C. krusei is intrinsically resistant to fluconazole and C. glabrata is often resistant.** Virulence depends on adhesion, germ tube and hyphal formation, secreted proteinases and biofilm formation.",
            "**Candida is a commensal.** It is carried in 30-60% of healthy mouths and in up to 45% of newborns, so **disease requires a defect in the host (immaturity, immunosuppression, systemic disease) or a change in the local environment (dry mouth, a denture, steroids, loss of the competing bacterial flora).**",
            "**Epidemiology.** Thrush affects **about 5% of normal newborns and up to 10% of infants in the first month of life**, and is common at the other extreme of life in denture-wearing elderly people; in between, it usually means an identifiable drug, disease or local factor.",
            "**Clinical forms (classification of Lehner, as modified by Axell).** **Primary oral candidiasis** - acute pseudomembranous (thrush), acute erythematous or antibiotic sore mouth, chronic pseudomembranous, chronic erythematous or denture stomatitis, and chronic hyperplastic or candidal leukoplakia; plus the **Candida-associated lesions** - angular cheilitis, median rhomboid glossitis and linear gingival erythema. **Secondary oral candidiasis** is the oral component of systemic mucocutaneous candidiasis, such as chronic mucocutaneous candidiasis and APECED.",
            "**Symptoms.** The infant is irritable, feeds slowly, releases the breast and cries; the adult reports a **bad or metallic taste, a burning or sore mouth, and discomfort with hot or spicy food**. Many cases, especially denture stomatitis, are entirely asymptomatic and found only on examination.",
            "**The diagnosis is clinical**, confirmed if needed by a **10-20% potassium hydroxide mount or Gram stain of a scraping showing budding yeasts with pseudohyphae**; culture on Sabouraud dextrose agar and speciation are reserved for refractory, recurrent or immunosuppressed cases, and **a white lesion that does not scrape off is biopsied, not treated as thrush.**",
          ],
        },
        {
          heading: "Causes and predisposing factors [3]",
          points: [
            "**Age extremes - the neonate and infant:** immature cell-mediated immunity and an undeveloped oral flora; a **milk-fed mouth** whose residue is a carbohydrate substrate; **acquisition from a colonised birth canal** (maternal vaginal candidiasis in pregnancy); and cross-infection from **contaminated teats, feeding bottles, dummies, unwashed hands and maternal nipple candidiasis**. Prematurity, low birth weight, and prolonged antibiotics in the nursery add to the risk.",
            "**Age extremes - the elderly:** **dentures, especially worn overnight, and poor denture hygiene**; xerostomia; **poor nutrition** with iron, folate, B12 or protein deficiency; polypharmacy; reduced dexterity for oral hygiene; institutional care; and coexisting chronic disease.",
            "**Local factors:** **inhaled corticosteroids used without rinsing or a spacer** (the commonest iatrogenic cause in general practice); **xerostomia** from anticholinergics, tricyclics, antihistamines, diuretics, antipsychotics and opioids, from **Sjogren syndrome**, or from **head and neck radiotherapy**; **smoking**; a **high-carbohydrate, high-sugar diet**; **orthodontic appliances and intraoral prostheses**; mucosal trauma and pre-existing mucosal disease such as lichen planus.",
            "**Drugs:** **broad-spectrum antibiotics** (they remove the competing bacterial flora - hence the 'antibiotic sore mouth'); **corticosteroids by any route - inhaled, topical, oral or intravenous**; **cytotoxic chemotherapy**, combining mucositis with neutropenia; and **immunosuppressants after transplantation**.",
            "**Systemic disease and immunosuppression:** **uncontrolled diabetes mellitus** (high salivary glucose, impaired neutrophil function, increased candidal adhesion); **HIV infection - oropharyngeal candidiasis is a WHO clinical stage 3 condition and oesophageal candidiasis is stage 4, so unexplained thrush in an adult mandates an HIV test after counselling**; **malignancy, especially haematological, with its chemotherapy and radiotherapy**; and **iron, folate and vitamin B12 deficiency**.",
            "**Endocrine and immunological causes:** **hypothyroidism, hypoparathyroidism, hypoadrenalism and Cushing syndrome**; **chronic mucocutaneous candidiasis and APECED (autoimmune polyendocrinopathy-candidiasis-ectodermal dystrophy, AIRE gene)**, in which candidiasis of mouth, nails and skin from infancy precedes hypoparathyroidism and Addison disease; and **primary immunodeficiencies** such as severe combined immunodeficiency and DiGeorge syndrome.",
            "**Nutritional and general:** **protein-energy malnutrition and severe acute malnutrition**, frailty, end-stage renal or liver disease, terminal illness, and any prolonged hospital stay with a nasogastric tube or a ventilator.",
            "**State the rule that earns the mark:** thrush in a **healthy neonate, after antibiotics, or in an unrinsed inhaled-steroid user** needs treatment and advice only, whereas thrush that is **unexplained in an adult, extensive, recurrent, or unresponsive to treatment is a sign of underlying disease - diabetes, HIV, malignancy, nutritional deficiency or an unrecognised drug - until proved otherwise.**",
          ],
        },
        {
          heading: "Treatment [3]",
          points: [
            "**Principle: treat the cause and the fungus together.** Stop or shorten the unnecessary antibiotic; teach rinsing and spitting and add a spacer for the inhaled steroid; take the denture out at night and disinfect it; control the diabetes; correct the iron or B12 deficiency; manage the dry mouth; stop smoking; sterilise teats and dummies; and **start antiretroviral therapy in HIV, which is the definitive treatment of recurrent oral candidiasis in that setting.**",
            "**Topical therapy - first line in mild to moderate disease in an immunocompetent host. Nystatin oral suspension 100,000 units/mL: neonate 1 mL (100,000 units) four times daily; infant and child 1-2 mL (100,000-200,000 units) four times daily; older child and adult 4-6 mL (400,000-600,000 units) four times daily, held in the mouth for several minutes before swallowing. Give it after feeds or after food, apply it to the whole mucosa in an infant with a clean finger or swab, and continue for 7-14 days and for at least 48 hours after clinical cure.**",
            "**Other topical options. Clotrimazole troche 10 mg dissolved slowly in the mouth five times daily for 7-14 days** is the IDSA first-line topical agent in adults, but troches are **not reliably available in India, where 1% clotrimazole mouth paint applied three to four times daily is the practical substitute**. **Miconazole oral gel 2%: 1.25 mL four times daily from 1 month to 1 year, 2.5 mL four times daily above 2 years and in adults**, smeared on the lesions after food - **but avoid it in a patient on warfarin, because even the gel inhibits CYP2C9 and has caused dangerous INR rises**, and note that **UK and EU guidance contraindicates it under 4 months and in impaired swallowing because of a choking risk while Indian practice still uses small applied amounts, so guidance genuinely differs; prefer nystatin under 4 months.** **Gentian violet 0.5-1% paint** remains a WHO option where nothing else exists, but its value is contested - it stains, it can ulcerate the mucosa, and several regulators have withdrawn it for oral use.",
            "**Systemic therapy - oral fluconazole - for moderate to severe disease, the immunosuppressed (HIV, chemotherapy, transplant), oesophageal involvement, and failure of adequate topical treatment. Adult 100-200 mg once daily for 7-14 days (200 mg loading dose on day 1 is usual). Child 6 mg/kg on day 1 then 3 mg/kg once daily, maximum 400 mg/day. Neonate 6 mg/kg with an extended interval - every 72 hours in the first 2 weeks of life and every 48 hours from 2 to 4 weeks. Oesophageal candidiasis: 200-400 mg (3-6 mg/kg) daily for 14-21 days, and always systemically.** Watch for hepatotoxicity, QT prolongation and interactions with warfarin, phenytoin, rifampicin and statins.",
            "**In the breastfed infant, treat the mother's nipples simultaneously or the infection ping-pongs: miconazole 2% or nystatin cream to both nipples and areolae after every feed for 14 days**, with **oral fluconazole for the mother (150-400 mg loading then 100 mg daily for 10-14 days)** for deep persistent breast pain. **How routinely to do this is disputed** - nipple candidiasis is over-diagnosed and most sore nipples are due to a poor latch, tongue-tie, vasospasm or bacterial infection - **so assess the latch and examine the nipple first, and treat the pair together when the infant genuinely has thrush.**",
            "**In the denture wearer, treat the denture:** **remove it at night, every night**; brush it with soap and a denture brush after meals; **soak it overnight in chlorhexidine 0.2%, dilute sodium hypochlorite (acrylic dentures only) or an alkaline peroxide cleanser**; apply the antifungal to the **fitting surface of the denture as well as to the palate**; and refer for relining or remaking if it is loose. Newton type III papillary hyperplasia may need surgical reduction.",
            "**Duration, refractory and recurrent disease.** Treat for **7-14 days and 48 hours past clinical cure**. If it fails, check **adherence and technique, then the uncorrected cause, then the species** - culture and speciate, because **C. krusei is intrinsically fluconazole-resistant and C. glabrata is often resistant**. Fluconazole-refractory disease is treated with **itraconazole oral solution 200 mg daily, posaconazole suspension 400 mg twice daily for 3 days then 400 mg daily, or voriconazole 200 mg twice daily for up to 28 days**, with an intravenous echinocandin or amphotericin B for the severely ill; **chronic suppression with fluconazole 100 mg three times weekly** is reserved for disabling recurrence in irreversible immunosuppression.",
            "**Supportive care:** analgesia and a soft, bland, non-acidic diet for a sore mouth; adequate hydration; frequent small feeds and, in the infant, expressed breast milk by spoon or cup if sucking is too painful; treatment of coexisting **candidal napkin dermatitis** with a topical imidazole cream; and good oral and denture hygiene throughout.",
          ],
        },
        {
          heading: "Prevention [2]",
          points: [
            "**In the infant:** **sterilise teats, bottles, nipple shields, breast-pump parts and dummies by boiling for 5-10 minutes or with a steam or chemical steriliser, daily**; **discard and replace teats and dummies after an episode of thrush**; wash hands before feeding; do not share bottles or spoons; do not dip the dummy in honey or sugar; and do not let the infant sleep with a bottle in the mouth.",
            "**Breastfeeding and maternal care:** **treat vaginal candidiasis in the third trimester** to reduce colonisation of the newborn at delivery; keep the nipples clean, dry and aired, change breast pads often, and **treat the mother's nipples whenever the infant is treated**; encourage exclusive breastfeeding, and wipe the infant's mouth with clean water after formula feeds.",
            "**Inhaled corticosteroids:** **rinse the mouth with water, gargle and spit after every dose, use a spacer with a metered-dose inhaler, brush the teeth or drink water afterwards, and use the lowest effective dose.** Give this instruction when the inhaler is first prescribed and check it at every review - it prevents almost all steroid-related thrush.",
            "**Denture care:** **clean the denture after every meal, brush it mechanically to remove the biofilm, soak it overnight in a disinfectant, and never sleep in it**; keep it in water when out; have the fit checked annually and relined when loose; and brush the palate and tongue before reinserting it.",
            "**Oral hygiene and hydration:** brush twice daily including the tongue, floss, treat caries and periodontal disease, keep the mouth moist with frequent sips of water, sugar-free gum or a saliva substitute in xerostomia, limit sugary drinks and snacks, and **stop smoking**. A **chlorhexidine 0.2% mouthwash** reduces candidal load - but not within 30 minutes of nystatin, which it inactivates.",
            "**Control the systemic driver:** **glycaemic control in diabetes**; correction of **iron, folate, B12 and protein-energy deficiency**; treatment of hypothyroidism and hypoparathyroidism; and **antiretroviral therapy in HIV**, which reduces the incidence of oral candidiasis far more effectively than repeated antifungal courses.",
            "**Prudent antibiotic use** - avoid unnecessary and unnecessarily broad-spectrum antibiotics and keep courses short; and **good oral care during chemotherapy and head and neck radiotherapy** with a soft brush, saline or bicarbonate rinses and dental clearance beforehand.",
            "**Chemoprophylaxis for defined high-risk groups only: fluconazole for neutropenic patients during induction chemotherapy or stem-cell transplantation, and fluconazole 3-6 mg/kg twice weekly for 6 weeks in very low birth weight neonates under 1000 g in units with a high incidence of invasive candidiasis** (nystatin as an alternative). **Routine primary antifungal prophylaxis is NOT recommended in HIV**, because of the risk of azole resistance - ART and treatment of episodes is the policy.",
          ],
        },
      ],
      mustDraw: [
        "A table of the clinical variants of oral candidiasis - acute pseudomembranous, acute erythematous, chronic erythematous (denture stomatitis, Newton I-III), chronic hyperplastic, angular cheilitis and median rhomboid glossitis - with appearance, typical patient, whether it scrapes off, and treatment.",
        "A boxed table of antifungal doses by age: nystatin suspension (neonate, infant, child, adult), clotrimazole troche or mouth paint, miconazole oral gel with its warfarin and choking cautions, and fluconazole (adult, child, neonate, oesophageal).",
        "A simple flow chart: white plaque in the mouth - does it scrape off? YES leaving a raw base, so it is thrush - assess severity and immune status - mild goes to topical (nystatin, clotrimazole, miconazole) and moderate to severe, immunosuppressed or oesophageal goes to systemic fluconazole; NO, so biopsy it (leukoplakia, lichen planus, oral hairy leukoplakia, chronic hyperplastic candidiasis, carcinoma). A parallel box lists the predisposing factors to be corrected in every case.",
      ],
      markSplit: [
        { part: "Definition, organism and clinical forms", marks: 2 },
        { part: "Causes and predisposing factors", marks: 3 },
        { part: "Treatment", marks: 3 },
        { part: "Prevention", marks: 2 },
      ],
      keywords: [
        "oral thrush",
        "Candida albicans",
        "pseudomembranous candidiasis",
        "nystatin",
        "fluconazole",
        "miconazole oral gel",
        "inhaled corticosteroid rinsing",
        "denture stomatitis",
        "HIV testing",
        "nipple candidiasis",
      ],
    },
    {
      id: "pediatrics-oral-thrush-t2",
      paper: "III",
      kind: "short-note",
      marks: 5,
      minutes: 9,
      frequency: "less-common",
      question: "Write a short note on the differential diagnosis of white lesions of the oral mucosa, and outline how you would evaluate a 55-year-old male smoker with a white patch on the buccal mucosa that does not scrape off.",
      openingLines: [
        "A white lesion of the oral mucosa is any patch that appears white because the epithelium is thickened by hyperkeratosis or acanthosis, is oedematous, is covered by a pseudomembrane of fungus and debris, or is necrotic - and the single most useful bedside manoeuvre in sorting them out is to try to wipe or scrape the lesion off with a gauze or spatula.",
        "Lesions that come off (candidal pseudomembrane, milk curds, a chemical or thermal slough) are treated; lesions that do not come off (leukoplakia, lichen planus, oral hairy leukoplakia, chronic hyperplastic candidiasis, carcinoma) are investigated, and in a middle-aged smoker with an adherent white patch, biopsy is mandatory because leukoplakia and chronic hyperplastic candidiasis are both potentially malignant disorders.",
      ],
      answer: [
        {
          heading: "Classify the white lesions by whether they can be scraped off",
          points: [
            "**Lesions that CAN be scraped or wiped off.** **Acute pseudomembranous candidiasis (thrush)** - creamy curd-like plaques leaving a raw, erythematous, sometimes bleeding base, with a predisposing factor always present. **Milk curds** in an infant - white films on the tongue and palate related to the last feed, coming off to leave **normal pink mucosa** with no erythema and no soreness. **Chemical or thermal burn slough** - a white patch corresponding exactly to the site of an aspirin tablet held against the gum or a hot drink, which peels within days. **Necrotic slough** of acute necrotising ulcerative gingivitis - punched-out interdental ulcers with a grey slough, halitosis and pain, in a smoker or an immunosuppressed patient.",
            "**Lesions that do NOT scrape off - the important group.** **Leukoplakia** - a predominantly white patch that cannot be characterised clinically or pathologically as any other disease; a **potentially malignant disorder**, commonest on the floor of the mouth, ventrolateral tongue and buccal mucosa, homogeneous or the higher-risk speckled and nodular form, in a smoker or tobacco chewer.",
            "**Oral lichen planus** - **bilateral, symmetrical, lacy white Wickham striae** on the buccal mucosa, with reticular, plaque, atrophic, erosive and bullous forms; the erosive form is painful and has a small malignant potential; look for the skin, nail and genital lesions and check for hepatitis C.",
            "**Oral hairy leukoplakia** - **corrugated vertical white streaks on the lateral border of the tongue**, often bilateral, asymptomatic, caused by **Epstein-Barr virus**, and a **WHO clinical stage 3 marker of HIV** that resolves with antiretroviral therapy. It does not rub off, and no antifungal will touch it.",
            "**Chronic hyperplastic candidiasis (candidal leukoplakia)** - a firm adherent white plaque, characteristically **bilateral behind the commissures of the buccal mucosa in a middle-aged male smoker**; PAS staining shows candidal hyphae invading the parakeratin, and it carries a **recognised malignant potential**, higher than most other leukoplakias.",
            "**Other adherent white lesions:** **oral submucous fibrosis** (blanched, marble-like mucosa with palpable fibrous bands and progressive trismus, from areca nut chewing - a major potentially malignant disorder in India); **frictional keratosis** (along the occlusal line, from a sharp tooth or cheek biting, and it resolves when the cause is removed); **nicotinic stomatitis** (a grey-white palate studded with red dots, the inflamed openings of the minor salivary glands, in a pipe or reverse smoker); **leukoedema** (a diffuse greyish-white filmy mucosa that **disappears on stretching**, a normal variant in dark-skinned people); **white sponge naevus** (a familial, bilateral, thick, folded white mucosa present from childhood); **lupus erythematosus** (a central atrophic area with radiating white striae); **syphilitic mucous patch or leukoplakia**; and **squamous cell carcinoma**, which may present as a white, red, mixed, ulcerated or indurated lesion.",
            "**Do not forget the red lesions in the same breath:** **erythroplakia** - a velvety red patch that cannot be attributed to any other cause - carries a far higher risk of dysplasia and carcinoma than leukoplakia, and a **speckled leukoplakia (erythroleukoplakia) is the highest-risk appearance of all.**",
          ],
        },
        {
          heading: "Evaluating the 55-year-old male smoker with an adherent buccal white patch",
          points: [
            "**History:** duration and change in size, colour or texture; **pain, burning, numbness, bleeding, loosening teeth, trismus, dysphagia or a neck lump**; **quantify the tobacco - cigarettes, bidis, gutkha, khaini, paan, areca nut, reverse smoking - in years and daily amount**; alcohol; occupational sun exposure for the lip; **denture wear, a sharp tooth or a habit of cheek biting**; drugs including inhaled steroids; diabetes; HIV risk; weight loss; and any previous oral lesion or head and neck malignancy.",
            "**Examination:** good light, gloves, gauze and a mirror. **Try to scrape it** - record that it does not come off. Note **site, size, exact borders, colour (homogeneous white, speckled, mixed red and white), surface (smooth, wrinkled, nodular, verrucous, ulcerated) and above all INDURATION on palpation**, which is the sign of invasion. Examine the **whole mucosa including the floor of the mouth, ventral and lateral tongue, retromolar trigone, soft palate and oropharynx**, since field change is the rule; check **mouth opening** for submucous fibrosis; examine the **teeth and dentures for a traumatic cause**; and **palpate the cervical lymph nodes** systematically.",
            "**Bedside and simple tests:** a **KOH mount or Gram-stained smear** of a scraping - candidal hyphae would support chronic hyperplastic candidiasis; **blood glucose and HbA1c**; **haemoglobin, ferritin, B12 and folate**; and **HIV testing after counselling** where the picture suggests it.",
            "**The definitive investigation is an incisional biopsy** taken from the **most suspicious area - the red, speckled, nodular, indurated or ulcerated part, not the innocuous white centre** - with adequate depth, stained with haematoxylin and eosin and with **PAS for candidal hyphae**. The report gives the diagnosis and, crucially, the **grade of epithelial dysplasia**. Toluidine blue staining and brush cytology may guide site selection but never replace the biopsy.",
            "**A therapeutic trial has a defined place:** if candidal hyphae are found, give a **systemic antifungal (fluconazole or itraconazole) for 2-4 weeks together with complete tobacco cessation, and then re-examine**; the homogeneous plaque of chronic hyperplastic candidiasis often regresses substantially, and **any residual lesion is biopsied or re-biopsied**. A traumatic keratosis should resolve within 2 weeks of removing the sharp cusp or the ill-fitting denture - **a lesion that persists beyond 2-3 weeks after the cause is removed must be biopsied.**",
            "**Management by result:** **no dysplasia** - tobacco and areca nut cessation with counselling and pharmacotherapy, treat the candidiasis, remove local trauma, and review 3-monthly for the first year with photographs; **mild to moderate dysplasia** - as above plus close surveillance, with excision considered for a high-risk site or a speckled lesion; **severe dysplasia, carcinoma in situ or carcinoma** - refer urgently to the head and neck or maxillofacial oncology service for surgical excision (scalpel, laser or cryotherapy) and staging.",
            "**Counsel and follow up for life.** Explain that the patch is a **potentially malignant disorder**, that **stopping all tobacco and areca nut is the single most effective treatment**, and that the risk of a second lesion elsewhere in the mouth persists. Teach **oral self-examination monthly** and the symptoms that mean an immediate visit - a non-healing ulcer of over 2 weeks, a lump, bleeding, numbness, a change in colour or texture, loose teeth or difficulty swallowing. **Screening the household for tobacco use, and opportunistic oral examination of every tobacco user attending the clinic, is the family physician's contribution to oral cancer control.**",
          ],
        },
      ],
      mustDraw: [
        "A two-column table: white lesions that SCRAPE OFF (pseudomembranous candidiasis, milk curds, chemical or thermal slough, necrotising gingivitis slough) versus those that DO NOT (leukoplakia, lichen planus, oral hairy leukoplakia, chronic hyperplastic candidiasis, submucous fibrosis, frictional keratosis, leukoedema, white sponge naevus, carcinoma), with the key clue for each.",
        "A labelled diagram of the oral cavity marking the high-risk sites for malignancy - floor of mouth, ventrolateral tongue, retromolar trigone and soft palate complex - with the biopsy site marked at the speckled or indurated edge of the lesion, not its centre.",
        "A flow chart: adherent white patch - history and examination, then KOH or smear, then INCISIONAL BIOPSY with dysplasia grading, branching to no dysplasia (cessation and 3-monthly review), mild to moderate dysplasia (cessation, surveillance, consider excision) and severe dysplasia or carcinoma (urgent oncology referral).",
      ],
      markSplit: [
        { part: "Classification and differential diagnosis of oral white lesions", marks: 2 },
        { part: "History, examination and investigation including biopsy", marks: 2 },
        { part: "Management by biopsy result, counselling and follow-up", marks: 1 },
      ],
      keywords: [
        "oral white lesion",
        "leukoplakia",
        "oral lichen planus",
        "Wickham striae",
        "oral hairy leukoplakia",
        "chronic hyperplastic candidiasis",
        "oral submucous fibrosis",
        "erythroplakia",
        "incisional biopsy",
        "epithelial dysplasia",
      ],
    },
  ],
  mcqs: [
    {
      id: "pediatrics-oral-thrush-q1",
      stem: "A 3-week-old term, exclusively breastfed, thriving infant has white curd-like plaques on the tongue and buccal mucosa for 4 days. The plaques come off on gentle scraping leaving a red, slightly bleeding base. He is afebrile, active and gaining weight, and his mother has no nipple pain. What is the most appropriate first-line treatment?",
      options: [
        "Nystatin oral suspension 100,000 units (1 mL) four times daily after feeds for 7-14 days",
        "Oral fluconazole 6 mg/kg on day 1 then 3 mg/kg daily for 14 days",
        "Reassurance only, as these are milk curds in a thriving infant",
        "Miconazole oral gel 2.5 mL four times daily for 7 days",
        "Gentian violet 2% painted twice daily for 7 days",
      ],
      answer: 0,
      explanation:
        "A plaque that scrapes off to leave a raw, bleeding base is pseudomembranous candidiasis, not milk curds - milk curds wipe away leaving normal pink mucosa with no erythema, so option 3 is wrong. In a well, immunocompetent infant the first-line agent is a topical polyene: nystatin oral suspension 100,000 units/mL, 1 mL four times daily, given after feeds and applied to the whole mucosa, for 7-14 days and at least 48 hours beyond clinical cure. Systemic fluconazole is reserved for moderate to severe disease, immunosuppression, oesophageal involvement or failure of topical therapy, so option 2 over-treats. Miconazole oral gel is effective but the adult or over-2-years dose is 2.5 mL; the dose from 1 month to 1 year is 1.25 mL, and UK and EU guidance contraindicates the gel under 4 months because of the choking risk, so option 4 is both the wrong dose and the wrong age. Gentian violet is at most a last-resort agent in a setting with no alternative, is used at 0.5-1% and not 2%, and stronger solutions ulcerate the mucosa.",
      difficulty: "easy",
    },
    {
      id: "pediatrics-oral-thrush-q2",
      stem: "A 68-year-old woman who has worn a complete upper denture for 12 years, including at night, is found on routine examination to have bright erythema and oedema of the palate that stops exactly at the outline of her denture. She has no pain and no white plaques, but she has fissuring at both angles of her mouth. Which single measure is most important in preventing relapse after treatment?",
      options: [
        "A 6-week course of oral fluconazole 100 mg daily",
        "Removing the denture at night and disinfecting it overnight, with antifungal applied to its fitting surface",
        "Chlorhexidine 0.2% mouthwash used immediately after each dose of nystatin",
        "Replacing the upper denture with a partial denture",
        "Oral iron supplementation for the angular cheilitis",
      ],
      answer: 1,
      explanation:
        "This is chronic erythematous candidiasis, or denture stomatitis - characteristically asymptomatic, sharply confined to the denture-bearing mucosa, and frequently accompanied by angular cheilitis. The acrylic fitting surface carries a Candida biofilm that acts as a permanent reservoir, so treating the palate while the patient continues to wear an uncleaned denture overnight guarantees relapse: removing the denture at night, brushing it mechanically, soaking it overnight in a disinfectant and applying the antifungal to the fitting surface is the decisive intervention. A prolonged systemic azole treats the mucosa but not the biofilm and courts resistance and toxicity. Chlorhexidine is a useful adjunct but must NOT be used within 30 minutes of nystatin, which it inactivates. Changing the type of denture is not indicated - a reline or remake for an ill-fitting denture might be, but that is not what option 4 says. Iron deficiency is a genuine contributor to angular cheilitis and should be looked for, but supplementing iron will not stop palatal recolonisation from the denture.",
      difficulty: "moderate",
    },
    {
      id: "pediatrics-oral-thrush-q3",
      stem: "A 34-year-old man presents with a sore mouth and extensive white plaques over the palate, buccal mucosa and oropharynx that scrape off leaving a raw base. He takes no medicines, has had no antibiotics, does not use an inhaler, wears no denture, and his random blood sugar is 96 mg/dL. What is the single most important next step?",
      options: [
        "Start oral fluconazole 200 mg on day 1 then 100 mg daily and review in 2 weeks",
        "Send a swab for fungal culture and speciation before starting treatment",
        "Offer HIV testing after pre-test counselling",
        "Arrange an upper gastrointestinal endoscopy",
        "Repeat the blood sugar fasting and check HbA1c",
      ],
      answer: 2,
      explanation:
        "Extensive oropharyngeal candidiasis in an otherwise healthy adult with no antibiotic, steroid, denture, dry-mouth or diabetic explanation is a WHO clinical stage 3 event and one of the earliest and commonest markers of HIV infection, so HIV testing with counselling is the single most important step - it changes staging, prognosis and long-term management, since antiretroviral therapy, and not repeated antifungal courses, is the definitive treatment of recurrent candidiasis in HIV. Fluconazole is certainly indicated for disease of this extent, but starting it without looking for the cause leaves the patient with an undiagnosed and progressive infection. Culture and speciation are for refractory or recurrent disease, not for a first presentation. Endoscopy would be considered only if there were odynophagia or retrosternal pain, and even then only after 72 hours of failed empirical fluconazole. Confirming euglycaemia with an HbA1c is reasonable and should be done, but a normal random sugar already makes diabetes an unlikely explanation for disease this extensive, and it does not carry the weight of an HIV diagnosis.",
      difficulty: "easy",
    },
    {
      id: "pediatrics-oral-thrush-q4",
      stem: "A 72-year-old man with atrial fibrillation on warfarin, with a stable INR of 2.4, develops a sore mouth with white plaques after a course of co-amoxiclav for pneumonia. Which prescription carries the greatest risk of harm?",
      options: [
        "Nystatin oral suspension 5 mL four times daily for 14 days",
        "Miconazole oral gel 2% 2.5 mL four times daily for 14 days",
        "Clotrimazole troche 10 mg five times daily for 14 days",
        "Chlorhexidine 0.2% mouthwash twice daily as an adjunct",
        "Denture disinfection with dilute sodium hypochlorite overnight",
      ],
      answer: 1,
      explanation:
        "Miconazole oral gel is absorbed in sufficient quantity to inhibit CYP2C9, the enzyme that clears S-warfarin, and this interaction is a well-documented cause of dangerous rises in INR and of serious bleeding - regulators have issued specific warnings about it, and the gel should be avoided in a warfarinised patient or, if unavoidable, used only with close INR monitoring. Nystatin is a polyene that is not absorbed from the gut at all and has no such interaction, making it the safe first choice here. Clotrimazole troches are largely topical, with only minor systemic absorption and occasional transaminase elevation; they are not a significant warfarin hazard at usual doses. Chlorhexidine has no anticoagulant interaction, though it should not be used within 30 minutes of nystatin because it inactivates it. Denture disinfection is a mechanical measure with no systemic effect. The wider lesson is to ask about warfarin before writing for any azole, systemic or topical - fluconazole raises the INR even more powerfully than miconazole.",
      difficulty: "hard",
    },
    {
      id: "pediatrics-oral-thrush-q5",
      stem: "A 56-year-old man who has smoked 20 bidis a day for 30 years has a firm white plaque on the buccal mucosa just behind the left commissure. It has been present for 5 months and does not come off on scraping. A KOH mount from the surface shows budding yeasts with pseudohyphae. What is the correct management?",
      options: [
        "Nystatin suspension for 14 days and review, since the KOH mount confirms candidiasis",
        "Incisional biopsy from the most suspicious part of the lesion, with tobacco cessation and a systemic antifungal, and re-assessment",
        "Reassure and review in 6 months, as post-commissural plaques in smokers are benign frictional keratosis",
        "Excise the entire lesion immediately without a prior biopsy",
        "Topical steroid ointment, since the appearance is that of oral lichen planus",
      ],
      answer: 1,
      explanation:
        "A firm, adherent, post-commissural white plaque in a middle-aged male smoker with candidal hyphae on the smear is chronic hyperplastic candidiasis, or candidal leukoplakia - the one variant of oral candidiasis with recognised malignant potential, in which dysplasia is found in a substantial minority. The presence of Candida does not exclude dysplasia or carcinoma, so an incisional biopsy taken from the most suspicious (red, speckled, nodular or indurated) area, with PAS staining and dysplasia grading, is mandatory; alongside it, complete tobacco cessation and a systemic antifungal for several weeks often shrink the lesion, and any residual patch is re-assessed and excised if dysplasia persists. A 14-day course of topical nystatin treats neither the keratosis nor the dysplasia and delays diagnosis. Calling it frictional keratosis is unsafe: frictional keratosis lies along the occlusal line, has an identifiable mechanical cause, and resolves within 2 weeks of removing it. Immediate wide excision without histology is neither necessary nor appropriate before the grade is known. Lichen planus is bilateral, lacy and striated rather than a solitary firm plaque, and treating it blindly with a steroid would suppress inflammation over a possible malignancy.",
      difficulty: "hard",
    },
    {
      id: "pediatrics-oral-thrush-q6",
      stem: "A 29-year-old woman newly diagnosed with HIV, CD4 count 84 cells/microlitre, has oral thrush together with pain on swallowing and a retrosternal burning that has worsened over 10 days. She can swallow tablets. What is the most appropriate initial management?",
      options: [
        "Nystatin suspension 5 mL four times daily and clotrimazole troches for 14 days",
        "Upper gastrointestinal endoscopy with biopsy before any antifungal is started",
        "Oral fluconazole 200-400 mg daily for 14-21 days, with endoscopy only if there is no improvement in 72 hours",
        "Intravenous amphotericin B deoxycholate 0.7 mg/kg daily for 14 days",
        "Oral fluconazole 150 mg as a single dose, repeated after 1 week",
      ],
      answer: 2,
      explanation:
        "Oral thrush plus odynophagia and retrosternal pain in a patient with a CD4 count under 100 is presumptive oesophageal candidiasis, a WHO clinical stage 4 condition. The standard of care is an empirical systemic azole - fluconazole 200-400 mg (3-6 mg/kg) daily for 14-21 days - with endoscopy reserved for the patient who has not improved after about 72 hours, when CMV and herpes oesophagitis, which cause discrete ulcers, must be excluded. Topical agents never achieve therapeutic concentrations in the oesophagus, so option 1 will fail. Endoscoping everyone first delays effective treatment and is unnecessary when the response rate to empirical fluconazole is high. Intravenous amphotericin B is reserved for azole-refractory disease or a patient who cannot take anything orally, and carries needless nephrotoxicity here. A single 150 mg dose is the regimen for uncomplicated vulvovaginal candidiasis and is grossly inadequate for oesophageal disease. Antiretroviral therapy should be started as part of the same episode of care.",
      difficulty: "moderate",
    },
    {
      id: "pediatrics-oral-thrush-q7",
      stem: "A 7-year-old boy with persistent asthma on budesonide 200 microgram twice daily by metered-dose inhaler has had three episodes of oral thrush in 6 months, each clearing with nystatin. His asthma is well controlled, his growth is normal and his blood sugar is normal. What should be done first?",
      options: [
        "Change budesonide to an oral leukotriene receptor antagonist to avoid steroid exposure",
        "Start prophylactic fluconazole 3 mg/kg once weekly",
        "Check inhaler technique, add a spacer, and teach rinsing, gargling and spitting after every dose",
        "Test for HIV and check serum immunoglobulins and neutrophil function",
        "Halve the budesonide dose and continue without a spacer",
      ],
      answer: 2,
      explanation:
        "Recurrent thrush in a child on an inhaled corticosteroid whose asthma is otherwise well controlled and who is systemically well is almost always a technique problem: oropharyngeal deposition of the drug. A large-volume spacer markedly reduces that deposition, and rinsing the mouth, gargling and spitting after every dose removes what does deposit - this pair of measures prevents the great majority of steroid-related thrush and should be checked at every asthma review. Abandoning an effective inhaled steroid for a leukotriene antagonist trades good asthma control for a preventable oral problem. Antifungal prophylaxis exposes the child to azole toxicity and resistance for a problem that behavioural correction solves. An immunological work-up is not warranted in a well, growing child with an obvious local explanation - it becomes appropriate only if thrush persists after technique is corrected, or if there is failure to thrive, other infections, or candidiasis of the nails and skin suggesting chronic mucocutaneous candidiasis. Reducing the dose without a spacer neither controls the asthma optimally nor removes the oropharyngeal deposition.",
      difficulty: "moderate",
    },
  ],
  cards: [
    {
      id: "pediatrics-oral-thrush-c1",
      front: "Define oral thrush and name the organism.",
      back: "An opportunistic fungal infection of the oral mucosa, most often by Candida albicans (50-90% of isolates), presenting as creamy-white, curd-like, adherent plaques on the tongue, palate, buccal mucosa and oropharynx that scrape off to leave an erythematous, raw, sometimes bleeding base. Candida is a normal commensal carried by 30-60% of healthy mouths, so disease always signals a change in the host or the local environment. Non-albicans species matter for resistance: C. krusei is intrinsically fluconazole-resistant and C. glabrata often is.",
    },
    {
      id: "pediatrics-oral-thrush-c2",
      front: "List the clinical variants of oral candidiasis.",
      back: "PRIMARY: acute pseudomembranous (thrush); acute erythematous (antibiotic sore mouth) - flat, red, painful, no plaque; chronic pseudomembranous (HIV, long-term steroids); chronic erythematous (denture stomatitis, Newton I pinpoint, II diffuse, III papillary); chronic hyperplastic (candidal leukoplakia - does not rub off, malignant potential). CANDIDA-ASSOCIATED: angular cheilitis, median rhomboid glossitis, linear gingival erythema. SECONDARY: oral component of chronic mucocutaneous candidiasis and APECED.",
    },
    {
      id: "pediatrics-oral-thrush-c3",
      front: "What is the bedside discriminator, and what does the KOH mount show?",
      back: "Scrape the plaque with a spatula or gauze: thrush comes off leaving a RAW, erythematous, sometimes bleeding base; milk curds come off leaving NORMAL pink mucosa; leukoplakia, lichen planus, oral hairy leukoplakia and chronic hyperplastic candidiasis do not come off at all. KOH 10-20% mount of the scraping shows budding yeasts with PSEUDOHYPHAE - pseudohyphae, not yeasts alone, indicate invasion rather than carriage. Gram stain shows Gram-positive budding yeasts; PAS shows them best; germ tube test at 2-3 hours in serum identifies C. albicans.",
    },
    {
      id: "pediatrics-oral-thrush-c4",
      front: "Causes of oral thrush, grouped for the answer book.",
      back: "AGE EXTREMES: neonate and infant (immature immunity, milk-fed mouth, birth canal, contaminated teats and dummies, maternal nipple candidiasis); elderly (dentures, dry mouth, poor nutrition). LOCAL: inhaled steroids without rinsing, dentures worn overnight, xerostomia (drugs, Sjogren, head and neck radiotherapy), smoking, high-sugar diet, orthodontic appliances. DRUGS: broad-spectrum antibiotics, corticosteroids, cytotoxics, immunosuppressants. SYSTEMIC: uncontrolled diabetes, HIV, malignancy and chemotherapy, iron/folate/B12 deficiency, hypothyroidism, hypoparathyroidism, chronic mucocutaneous candidiasis, malnutrition.",
    },
    {
      id: "pediatrics-oral-thrush-c5",
      front: "Nystatin oral suspension - dose by age.",
      back: "Nystatin 100,000 units/mL. Neonate 1 mL (100,000 units) four times daily. Infant and child 1-2 mL (100,000-200,000 units) four times daily. Older child and adult 4-6 mL (400,000-600,000 units) four times daily, held in the mouth for several minutes then swallowed. Give AFTER feeds or food; in an infant apply to the whole mucosa with a clean finger or swab. Continue 7-14 days and at least 48 HOURS BEYOND clinical cure. Not absorbed, safe in neonates; bitter; sucrose content is a caries risk on prolonged use; inactivated by chlorhexidine within 30 minutes.",
    },
    {
      id: "pediatrics-oral-thrush-c6",
      front: "Fluconazole - when and at what dose?",
      back: "Indications: moderate to severe disease, immunosuppression (HIV, chemotherapy, transplant), oesophageal involvement, or failure of adequate topical therapy. Adult 100-200 mg once daily for 7-14 days (200 mg loading on day 1). Child 6 mg/kg day 1 then 3 mg/kg once daily, max 400 mg/day. Neonate 6 mg/kg with an EXTENDED interval - every 72 hours in the first 2 weeks of life, every 48 hours from 2-4 weeks. OESOPHAGEAL: 200-400 mg (3-6 mg/kg) daily for 14-21 days, always systemic. Watch hepatotoxicity, QT prolongation, and interactions with warfarin, phenytoin, rifampicin and statins.",
    },
    {
      id: "pediatrics-oral-thrush-c7",
      front: "Miconazole oral gel - dose and the two cautions.",
      back: "2% gel (24 mg/mL): 1.25 mL four times daily from 1 month to 1 year; 2.5 mL four times daily from 2 years and in adults; smear on the lesions after food, continue 7 days after healing. CAUTION 1 - WARFARIN: even the gel inhibits CYP2C9 enough to cause dangerous INR rises and bleeding; avoid it, or monitor the INR closely. It also interacts with statins, sulfonylureas and phenytoin. CAUTION 2 - CHOKING: UK and EU guidance contraindicates it under 4 months and in impaired swallowing, while Indian practice still uses small applied amounts. Guidance genuinely differs - use nystatin under 4 months.",
    },
    {
      id: "pediatrics-oral-thrush-c8",
      front: "Clotrimazole and gentian violet - where do they stand?",
      back: "CLOTRIMAZOLE troche 10 mg dissolved slowly in the mouth 5 times daily for 7-14 days is the IDSA first-line topical agent in adults and older children, but troches are not reliably available in India - the practical substitute is 1% clotrimazole mouth paint applied to the lesions 3-4 times daily. Not for a child too young to hold a lozenge. GENTIAN VIOLET 0.5-1% paint once or twice daily for up to 3 days is cheap, effective and a WHO option where nothing else exists, but its place is genuinely contested - it stains, causes mucosal irritation, ulceration and necrosis at higher strengths or with prolonged use, and several regulators have withdrawn it for oral use.",
    },
    {
      id: "pediatrics-oral-thrush-c9",
      front: "Breastfed infant with thrush - what about the mother?",
      back: "Treat the pair or the infection ping-pongs between mouth and breast. Miconazole 2% or nystatin cream to both nipples and areolae after EVERY feed for 14 days, wiping off the excess before the next feed; for deep, burning, radiating breast pain, oral fluconazole for the mother 150-400 mg loading then 100 mg daily for 10-14 days, compatible with breastfeeding. But this is disputed: nipple candidiasis is over-diagnosed and most sore nipples are due to a poor latch, tongue-tie, vasospasm or bacterial infection - so check the latch and examine the nipple first, and never stop breastfeeding for thrush.",
    },
    {
      id: "pediatrics-oral-thrush-c10",
      front: "Denture stomatitis - recognition and management.",
      back: "Erythema and oedema confined EXACTLY to the denture-bearing palate, usually asymptomatic, in up to 65% of complete denture wearers; often with angular cheilitis. Newton I pinpoint hyperaemia, II diffuse erythema, III granular or papillary hyperplasia. You cannot see it with the denture in - take it out. Management: remove the denture at night EVERY night; brush it with soap and a denture brush after meals; soak it overnight in chlorhexidine 0.2%, dilute sodium hypochlorite (acrylic only) or alkaline peroxide; apply the antifungal to the FITTING SURFACE as well as the palate; reline or remake if loose; surgical reduction for type III.",
    },
    {
      id: "pediatrics-oral-thrush-c11",
      front: "Chronic hyperplastic candidiasis - why does it matter?",
      back: "A firm, adherent white plaque, usually bilateral behind the commissures of the buccal mucosa, in a middle-aged male smoker, which does NOT rub off. PAS shows candidal hyphae invading the parakeratin. It is the ONLY variant of oral candidiasis with recognised malignant potential, with dysplasia in a substantial minority and reported transformation rates higher than for other leukoplakias. So: incisional BIOPSY from the most suspicious (red, speckled, nodular, indurated) area with dysplasia grading; complete tobacco cessation; a systemic antifungal (fluconazole or itraconazole) for several weeks; re-assess, excise if dysplasia persists, and follow up for life.",
    },
    {
      id: "pediatrics-oral-thrush-c12",
      front: "Oral candidiasis and HIV - the staging, the testing and the prophylaxis.",
      back: "Oropharyngeal candidiasis is a WHO CLINICAL STAGE 3 condition; oesophageal candidiasis is STAGE 4. It is among the earliest and commonest HIV-associated oral lesions, so unexplained thrush in any adult or adolescent mandates HIV testing after counselling, and persistent or recurrent thrush beyond 6-12 months in an infant should do the same. Thrush plus odynophagia and retrosternal pain = presumptive oesophageal candidiasis: treat empirically with fluconazole 200-400 mg daily for 14-21 days and endoscope only if there is no improvement in 72 hours. ROUTINE primary antifungal prophylaxis is NOT recommended in HIV - antiretroviral therapy is the preventive strategy.",
    },
  ],
  references: [
    "Nelson Textbook of Pediatrics, 21st edition, 2020 - Candida (candidiasis), oral candidiasis in the neonate and infant, and neonatal invasive candidiasis",
    "Pappas PG et al. Clinical Practice Guideline for the Management of Candidiasis: 2016 Update by the Infectious Diseases Society of America, Clinical Infectious Diseases 2016;62(4):e1-e50 - oropharyngeal, oesophageal and neonatal candidiasis",
    "Burket's Oral Medicine, 13th edition, 2021 - fungal infections of the oral cavity, red and white lesions of the oral mucosa, and the potentially malignant disorders",
    "National AIDS Control Organisation (NACO), National Guidelines for HIV Care and Treatment, 2021, with the WHO Consolidated Guidelines on HIV (2021) clinical staging of oral candidiasis and the WHO guidance on oral lesions in HIV",
    "Fitzpatrick's Dermatology, 9th edition, 2019 - superficial candidiasis, mucosal candidiasis and chronic mucocutaneous candidiasis, with the British National Formulary and BNF for Children 2024 antifungal dosing",
  ],
});

export default topics;
