import type { Topic } from "../src/lib/types";

const topics: Topic[] = [];

topics.push({
  id: "preventive-health-planning-management",
  title: "Health planning and management: the planning cycle, SWOT and network analysis",
  oneLiner:
    "Health planning is the orderly process of defining community health problems, identifying unmet needs, surveying the resources available to meet them, establishing priority goals that are realistic and feasible, and projecting administrative action to accomplish the purpose of the proposed programme, while management is the process of getting that plan executed through and with people - the two joined in a repeating planning cycle of situation analysis, objectives, resource assessment, priorities, plan write-up, programming and implementation, monitoring and evaluation, supported by quantitative techniques such as cost-benefit and cost-effectiveness analysis, system analysis, network analysis (PERT and CPM) and SWOT analysis.",
  frequency: "common",
  keywords: [
    "health planning",
    "planning cycle",
    "health management",
    "POSDCORB",
    "SWOT analysis",
    "strengths weaknesses opportunities threats",
    "TOWS matrix",
    "network analysis",
    "PERT",
    "CPM",
    "critical path",
    "float and slack",
    "Gantt chart",
    "decision making",
    "cost-benefit analysis",
    "cost-effectiveness analysis",
    "cost-utility analysis QALY DALY",
    "input process output",
    "system analysis",
    "management by objectives",
    "work sampling",
    "organisation and methods",
    "operational research",
    "five-year plan",
    "NITI Aayog",
    "National Health Policy 2017",
    "programme implementation plan",
    "District Health Action Plan",
    "Donabedian structure process outcome",
    "NQAS Kayakalp LaQshya",
  ],
  sections: [
    {
      heading: "Planning and management defined, and the levels at which they work",
      points: [
        "**Planning** is the process of determining in advance what is to be accomplished, when, by whom, how and at what cost; the WHO definition used in the exam is that **health planning is the orderly process of defining community health problems, identifying unmet needs and surveying the resources to meet them, establishing priority goals that are realistic and feasible, and projecting administrative action to accomplish the purpose of the proposed programme**.",
        "**Management** is the process of getting things done through and with people - more fully, the process of planning, organising, staffing, directing, coordinating and controlling the available resources (the **five Ms: men, money, material, machines and minutes**, to which methods and market are often added) so that stated objectives are achieved efficiently; planning decides *what* is to be done, management makes it *happen*.",
        "Health services need planning because **needs are unlimited while resources are finite**, because health problems change (demographic and epidemiological transition), because health technology and its cost keep rising, because services grow piecemeal and unevenly unless directed, and because the state has accepted health as a right - planning is simply the rational allocation of scarce resources to competing ends.",
        "Planning operates at three **levels**: **strategic** (top level - policy, direction and 5 to 20 year horizon; Ministry of Health and Family Welfare, NITI Aayog, National Health Policy), **tactical or managerial** (middle level - 1 to 5 years, translating policy into programmes; state and district health administration, the District Health Action Plan) and **operational** (frontline - days to a year; the medical officer of the PHC, the monthly session plan, the drug indent, the duty roster).",
        "The classical functions of management are remembered as **POSDCORB** (**Luther Gulick and Lyndall Urwick, 1937**): **P**lanning, **O**rganising, **S**taffing, **D**irecting, **CO**ordinating, **R**eporting and **B**udgeting - the single most-quoted mnemonic in this chapter and worth writing out in full in any answer on management.",
        "**Henri Fayol (1916)** gave the parent scheme - five functions (planning, organising, commanding, coordinating, controlling) and **14 principles of management** including division of work, authority with matching responsibility, **unity of command** (one worker, one boss), unity of direction, **scalar chain**, discipline, equity, stability of tenure, initiative and esprit de corps; **F. W. Taylor** gave scientific management (time and motion study, the ancestor of work study) and **Elton Mayo** the Hawthorne studies and the human relations school.",
        "The difference to state in one line: **planning is a function of management, not a synonym for it** - management includes planning, but also organising the structure, staffing it, directing and motivating people, coordinating the parts, reporting through an information system and budgeting the money; a good plan badly managed and a bad plan well managed both fail, and the examiner wants both halves defined before any steps are described.",
      ],
    },
    {
      heading: "The planning cycle, step by step",
      points: [
        "**Step 1 - analysis of the health situation.** The starting point and the step most often skipped. It covers **health status** (mortality, morbidity, nutrition, demographic and vital statistics from SRS, NFHS, HMIS, IDSP and the local survey), **health services** (what facilities, staff, coverage, utilisation and quality exist against IPHS norms), **resources** (manpower, money, material, time) and the **environment** (physical, social, economic, political and cultural setting, including the private sector and traditional practitioners); the product is a written problem statement with baseline numbers.",
        "**Step 2 - establishment of objectives and goals.** A **goal** is the broad, distant, often unquantified end (reduce maternal deaths); an **objective** is specific and measurable; a **target** is the quantified objective with a date attached. Objectives must be **SMART** - specific, measurable, achievable, relevant, time-bound - and must be written as an outcome (reduce the maternal mortality ratio in the block from 130 to 90 per 100,000 live births by 2028), never as an activity (conduct meetings).",
        "**Step 3 - assessment of resources.** Count what is actually available: **manpower** (sanctioned versus in position, skills, training needs), **money** (budget heads, untied funds, Rogi Kalyan Samiti or Jan Arogya Samiti balance, NHM flexipool, PMJAY reimbursement), **material** (building, equipment, cold chain, drugs, diagnostics, transport) and **time**. A plan whose targets exceed its resources is a wish list; a resource assessment that comes after the targets have been fixed is the commonest cause of failure.",
        "**Step 4 - fixing priorities.** Problems are ranked by **magnitude** (how many are affected - prevalence, incidence, mortality), **seriousness** (case fatality, disability, cost to the family, epidemic potential), **feasibility or vulnerability** (does an effective, affordable, acceptable technology exist), **community concern or felt need**, and **cost with political and legal acceptability**. Two formal aids are examined: **Hanlon's Basic Priority Rating System, BPRS = [(A + 2B) x C] / 3** where A is size, B is seriousness and C is effectiveness of the intervention, each scored 0 to 10, followed by the **PEARL** feasibility filter (Propriety, Economics, Acceptability, Resources, Legality).",
        "**Step 5 - write-up of the formulated plan, with targets and a plan of operation.** The written plan states the objectives and targets, the strategy chosen from the alternatives considered, the activities with a time schedule (a **Gantt chart** or a network), the person responsible for each activity, the resources allotted to each, the line-item budget, and the indicators by which progress will be judged - it must be specific enough that a stranger could implement it.",
        "**Step 6 - programming and implementation.** Convert the plan into an activity schedule: who does what, where, when, with what and to whom. This is where organising, staffing, training, procurement, supply chain, supervision and community mobilisation happen; **intersectoral coordination** (ICDS, panchayat, education, water and sanitation, PWD) and **community participation** through the Village Health Sanitation and Nutrition Committee and the Jan Arogya Samiti belong here and, in truth, at every step of the cycle.",
        "**Step 7 - monitoring, and Step 8 - evaluation.** Monitoring is the continuous day-to-day tracking of inputs, activities and outputs against the schedule, using routine records, HMIS, supervisory checklists and review meetings, so that deviations are corrected while the programme is running. Evaluation is the periodic, systematic judgement of **relevance, adequacy, progress, efficiency, effectiveness and impact** against the original objectives. Because the evaluation feeds straight back into a fresh situation analysis, **planning is a cycle and not a line** - and that circularity, drawn as a circle with arrows, is itself worth marks.",
      ],
    },
    {
      heading: "Management techniques based on quantitative methods",
      points: [
        "**Cost-benefit analysis (CBA)** values both the costs and the consequences in money and answers *is this programme worth doing at all?*; the outputs are the **benefit-cost ratio** and the net present value, and its difficulty is that health benefits and lives have to be given a money value (human capital or willingness-to-pay methods). **Cost-effectiveness analysis (CEA)** costs in money but measures effects in natural units - deaths averted, cases prevented, life-years gained - and answers *which of these ways of achieving the same objective is cheapest?*; the output is the cost per unit of effect or the incremental cost-effectiveness ratio, and it cannot compare programmes with different objectives.",
        "**Cost-utility analysis (CUA)** solves that by expressing effects as **QALYs gained or DALYs averted**, so that a cataract programme and a hypertension programme can be compared on one scale; the WHO-CHOICE rule of thumb still asked in vivas is that an intervention costing less than one times GDP per capita per DALY averted is highly cost-effective and less than three times GDP per capita is cost-effective, and India now does this formally through **HTAIn**, the Health Technology Assessment body set up under the Department of Health Research in 2017. **Cost-minimisation analysis** applies only when the outcomes of the alternatives are known to be identical, and **cost accounting** gives the unit cost of a service (cost per delivery, cost per outpatient visit).",
        "**Input-output analysis** studies the flow between the parts of a system, relating the inputs consumed (staff hours, drugs, beds, money) to the outputs produced (deliveries conducted, children immunised, patients treated), and exposes imbalance and bottlenecks - a labour room with two staff nurses and no functional new-born corner cannot convert its input into the intended output. It is the arithmetic behind the **input - process - output - outcome - impact** chain on which every health indicator set is built.",
        "**Model building and simulation** replace reality with a simplified representation - physical, mathematical or computer - so that alternatives can be tested without risk or cost: SIR and other epidemic models, queuing models to fix the number of OPD counters and the waiting time, inventory models for vaccine stock, and tools such as the Lives Saved Tool. **System analysis** looks at the whole system - inputs, process, outputs, feedback and the environment - identifies the alternative combinations of resources that could reach the objective, sets out the cost and the consequence of each, and hands the choice to the decision maker.",
        "**Network analysis (PERT and CPM)** schedules the interdependent activities of a project, finds the **critical path** and shows where slack exists; **the planning-programming-budgeting system (PPBS)** budgets by objective and programme rather than by line item - define the objectives, list the programmes that could achieve them, cost each over several years, compare and choose (introduced in the United States Department of Defense in the 1960s and the parent of today's outcome budgeting).",
        "**Work study** has two halves - **method study**, which examines how a job is done in order to simplify it, and **work measurement**, which finds how long it should take; **work sampling** is its practical form, a large number of random instantaneous observations of what staff are actually doing, from which the proportion of working time spent on each activity is estimated and staffing norms are fixed (the modern WHO version is **WISN**, Workload Indicators of Staffing Need). **Organisation and methods (O&M)** is the systematic review of the organisational structure, procedures, forms, registers and paperwork to remove duplication and delay.",
        "**Decision making** is choosing between alternatives, made explicit by the **decision tree** - square decision nodes, circular chance nodes, probabilities on the branches, utilities or costs at the tips, and the expected value obtained by rolling back from right to left. **Management by objectives (MBO, Peter Drucker, 1954)** has the superior and the subordinate jointly set measurable objectives with a time frame, agree the action plan, review periodically and appraise performance against those objectives rather than against personality. **Operational research** applies mathematical method - linear programming, queuing theory, inventory and transport models, simulation - to find the optimum, and the **health management information system (HMIS, now the IHIP platform)** supplies the data without which none of the above can run.",
      ],
    },
    {
      heading: "Network analysis: PERT, CPM and the critical path",
      points: [
        "A **network** is a diagram of a project drawn as **activities and events**: an **activity** is a task that consumes time and resources and is drawn as an **arrow**; an **event** is a point in time marking the start or finish of activities, consumes nothing, and is drawn as a **circle or node**. A **dummy activity** (broken arrow, zero time, zero resource) is used only to show a dependency or to keep two activities from sharing the same pair of events. The rules: the network has one start and one end event, no activity may begin until its preceding event is reached, **no looping is allowed**, and events are numbered so that the tail number is always smaller than the head number (Fulkerson's rule).",
        "To draw one: list every activity, decide its immediate predecessors, estimate its duration, draw the arrows in logical sequence, number the events, then make a **forward pass** to get the **earliest event time** (take the largest value where paths merge) and a **backward pass** to get the **latest event time** (take the smallest value where paths burst). The **critical path** is the **longest path through the network**, and therefore the shortest time in which the project can possibly be finished; every activity on it has **zero float**, so any delay in a critical activity delays the whole project by the same amount.",
        "**Float or slack** is the time an activity may be delayed without harm. **Total float = latest start minus earliest start = latest finish minus earliest finish**, and it is the delay possible without pushing back the project end; **free float** is the delay possible without disturbing the earliest start of the following activity; **independent float** is the delay possible without disturbing either neighbour. Float is where resources may safely be borrowed from - a manager moves staff from a floating activity to a critical one, never the reverse.",
        "**PERT (Programme Evaluation and Review Technique)** was developed in **1958** for the United States Navy Polaris missile programme; it is **probabilistic, event-oriented and time-based**, used for research and development or for any project done for the first time where durations are uncertain. It takes **three time estimates - optimistic (to), most likely (tm) and pessimistic (tp)** - and computes the **expected time te = (to + 4tm + tp) / 6**, with **standard deviation = (tp - to) / 6** and **variance = [(tp - to) / 6] squared**. Along the critical path the variances are added, the square root gives the project standard deviation, and **Z = (scheduled time minus expected time) / project standard deviation** read against the normal table gives the probability of finishing by any chosen date.",
        "**CPM (Critical Path Method)** was developed in **1957** by DuPont and Remington Rand for plant maintenance and construction; it is **deterministic, activity-oriented and both time- and cost-based**, used for repetitive projects whose durations are known from experience. Its distinctive contribution is the **time-cost trade-off**: the **normal time** and normal cost of an activity are compared with the **crash time** and crash cost, the **cost slope = (crash cost - normal cost) / (normal time - crash time)** is computed, and the project is shortened by **crashing the critical activity with the lowest cost slope first**, re-identifying the critical path after each crash because it can shift.",
        "**Steps in carrying out a network analysis:** define the project and its objective; break it into a complete list of activities (the work breakdown); fix the logical sequence and the immediate predecessor of each; estimate the duration of each (three estimates for PERT, one for CPM); draw and number the network; carry out the forward and backward passes; identify the critical path and calculate the float on every other activity; allot resources, crash where necessary, and then **use the network to monitor** the project, updating it whenever an activity finishes early or late.",
        "**Advantages:** it forces a complete listing of activities and their interdependence, which a **Gantt chart (Henry Gantt, 1917)** does not show; it identifies the few activities on which the whole project depends so that supervision is concentrated there; it shows where slack exists so resources can be redeployed; it permits realistic scheduling, costing and monitoring, and answers *what happens if this step is delayed*. **Limitations:** it depends entirely on the quality of the time estimates, which are subjective; it assumes activities are independent and that resources are unconstrained; the network becomes unwieldy for very large projects without software; it needs trained staff; PERT's assumption of a beta distribution and independent paths makes it under-estimate project duration when near-critical parallel paths exist (merge event bias); and a network that is not updated is a decoration rather than a management tool.",
      ],
    },
    {
      heading: "SWOT analysis: the frame, the method and its limits",
      points: [
        "**SWOT analysis** is a structured situational analysis in which an organisation or a programme lists its **Strengths, Weaknesses, Opportunities and Threats** in relation to a stated objective, in order to build a strategy that uses what it has and defends what it lacks. It grew out of the SOFT analysis of **Albert Humphrey and colleagues at the Stanford Research Institute in the 1960s** and became a standard step of the situation-analysis stage of the planning cycle - the qualitative counterpart of the quantitative techniques.",
        "The frame is a **two-by-two matrix** with one axis **internal against external** and the other **helpful against harmful**. **Strengths** are internal and favourable (what we have and do well - staff, skills, location, reputation, funds, systems). **Weaknesses** are internal and unfavourable (what we lack or do badly - vacancies, stock-outs, no protocols, poor records). **Opportunities** are external and favourable (new schemes, funds, partnerships, policy, technology, demand). **Threats** are external and unfavourable (competition, transfers, epidemics, funding cuts, political interference, disasters). The single commonest error in an answer book is putting an external item inside the internal boxes: **shortage of drugs at the PHC is a weakness; delay in state supply of drugs is a threat**.",
        "**Who should be in the room:** the analysis is done as a group, not by the medical officer alone. For a health facility that means the medical officer, staff nurses and the ANM, the pharmacist and laboratory technician, the block or district programme manager, the accountant, the ASHA facilitator, a member of the Jan Arogya Samiti or panchayat, and ideally a user representative - because staff see internal reality, managers see the system, and the community sees demand and acceptability. A neutral facilitator and a rule that no item is criticised while it is being generated keep the exercise honest.",
        "**Steps of conducting it:** (1) **define the objective** precisely and in writing, because SWOT is meaningless in the abstract - not *how is our PHC doing* but *can this PHC obtain NQAS certification within twelve months*; (2) **assemble the team and the data** - HMIS and IHIP output, drug and equipment stock position, staff in position against sanction, last Kayakalp or internal assessment score, patient feedback and the block map; (3) **brainstorm each quadrant**, internal boxes first, one item per card, no debate at this stage; (4) **verify each item against evidence** and delete opinion that no number supports; (5) **prioritise within each quadrant** by importance and by the likelihood of the external items occurring, keeping the top five or six; (6) **convert the matrix into strategy** through the four pairings; (7) **write an action plan** with a responsible person, a date and an indicator for each strategy, and set a review date.",
        "**Converting the matrix into strategy** is the step that separates a pass from a good answer, and it uses the **TOWS matrix (Heinz Weihrich, 1982)**: **SO (maxi-maxi)** - use strengths to seize opportunities, the aggressive or growth strategy; **WO (mini-maxi)** - use opportunities to overcome weaknesses, the turnaround strategy; **ST (maxi-mini)** - use strengths to blunt threats, the defensive or diversification strategy; **WT (mini-mini)** - minimise both, the survival or damage-limitation strategy. A SWOT that stops at four lists has done half the work.",
        "**Uses in health:** situation analysis within the planning cycle, preparation of a District Health Action Plan or a facility annual plan, readiness assessment before quality certification, appraisal of a new service such as telemedicine or a dialysis unit, review of a national programme in a district, team building and problem solving in a practice, and even personal career planning. It is quick, cheap, needs no software, and gives the staff who must implement the plan a stake in it.",
        "**Limitations:** it is subjective and dominated by whoever speaks loudest unless facilitated; it produces long unprioritised lists; it gives no weight or score to items so a trivial strength sits beside a fatal weakness; the internal and external boundary is often argued about; it is a snapshot that dates quickly and needs repeating; and it describes rather than analyses causes - it must be followed by root-cause tools (fishbone or Ishikawa diagram, the five whys, Pareto analysis) and by an action plan, or it becomes a wall chart. It complements, and does not replace, quantitative situation analysis.",
      ],
    },
    {
      heading: "Health planning in India: the committees, the plans and the present architecture",
      points: [
        "**Bhore Committee, 1946** (Health Survey and Development Committee, Sir Joseph Bhore) - the foundation document: integration of preventive and curative services at all levels, development of **primary health centres** in two stages (short-term, one PHC per 40,000 population with 2 doctors, a nurse, 4 public health nurses, 4 trained dais, 2 sanitary inspectors, 2 health assistants and a pharmacist, with a secondary health centre for every 30 PHCs; long-term or **three-million plan** with a 75-bedded primary unit per 10,000 to 20,000), three months of training in preventive and social medicine for every graduate so that he becomes a **social physician**, no more licentiates, and no individual should be denied care for inability to pay.",
        "**Mudaliar Committee, 1962** (Health Survey and Planning Committee, Dr A. L. Mudaliar) - consolidate and improve what exists rather than open more PHCs, limit each PHC to 40,000 population, strengthen subdivisional and district hospitals as the referral tier, improve the quality of care and training, and constitute an All India Health Service. **Chadha Committee, 1963** - malaria vigilance in the maintenance phase to be done by **basic health workers, one per 10,000 population**, doing multipurpose duty including surveillance, vital statistics and family planning, supervised by family planning health assistants (one per four workers) - and it failed because the workers were overloaded.",
        "**Mukherjee Committee, 1965** - separate the staff again: family planning assistants to do family planning only, and malaria work to be given back to separate workers. **Mukherjee Committee, 1966** (second, under the Union Health Secretary) worked out the delinking of mass programmes - malaria, smallpox, trachoma, leprosy and family planning - at block level. **Jungalwalla Committee, 1967** (Committee on Integration of Health Services) defined an **integrated health service** - a unified cadre with common seniority, recognition of extra qualifications, equal pay for equal work, special pay for special work, no private practice and good service conditions.",
        "**Kartar Singh Committee, 1973** (Committee on Multipurpose Workers) - the male and female **multipurpose health worker, one per 5,000 population** (3,000 in hilly and tribal areas), a health supervisor for every four workers, and a PHC for every 50,000; the ANM became the female health worker and the malaria, smallpox and vaccination workers became the male health worker. **Shrivastav Committee, 1975** (Group on Medical Education and Support Manpower) - create bands of paraprofessional and semi-professional workers from within the community, a **referral services complex**, and a Medical and Health Education Commission; it produced the Rural Health Scheme of 1977 and the community health worker (later Village Health Guide) scheme. **Bajaj Committee, 1986** (Expert Committee on Health Manpower Planning, Production and Management, Dr J. S. Bajaj) - a National Medical and Health Education Policy and a Health Manpower Policy, an Educational Commission for Health Sciences on the lines of the UGC, health science universities in the states, and health manpower cells at centre and state.",
        "**From five-year plans to NITI Aayog:** the **Planning Commission**, set up by a Cabinet resolution in **March 1950** with the Prime Minister as chairman, drew the five-year plans (First 1951-56 onwards) and the health chapter within them. It was **replaced by NITI Aayog (National Institution for Transforming India) on 1 January 2015**; the **Twelfth Five-Year Plan (2012-17) was the last**, and central planning now runs through NITI Aayog's vision, strategy and action-agenda documents, the Fifteenth Finance Commission's health recommendations and the annual union budget rather than through plan periods - say this with the date, because describing a live Planning Commission is a dated answer.",
        "**National Health Policy 2017** (the third, after 1983 and 2002) sets an assurance-based approach with two-thirds of resources to primary care and these examinable targets: government health expenditure from about 1.15 to **2.5 per cent of GDP by 2025** and state health spending above 8 per cent of the state budget by 2020; life expectancy 67.5 to **70 years by 2025**; total fertility rate 2.1 by 2025; **under-five mortality 23 by 2025**, **maternal mortality ratio 100 by 2020**, **infant mortality rate 28 by 2019** and neonatal mortality 16 with single-digit stillbirth rate by 2025; more than 90 per cent full immunisation by one year of age by 2025; elimination of kala-azar and lymphatic filariasis in endemic pockets by 2017, leprosy by 2018 and **tuberculosis by 2025**; a 25 per cent relative reduction in premature mortality from cardiovascular disease, cancer, diabetes and chronic respiratory disease by 2025; and a 30 per cent relative reduction in tobacco use by 2025.",
        "**How money and plans actually move:** under the **National Health Mission** (NRHM from 12 April 2005, NUHM added in 2013), village and block plans feed the **District Health Action Plan (DHAP)**, the district plans are consolidated into the **State Programme Implementation Plan (PIP)**, which is appraised on the NHM PIP portal by the National Programme Coordination Committee with technical support from the NHSRC, and approvals are conveyed to the state as the **Record of Proceedings (RoP)**; funds flow in flexible pools (RCH, health system strengthening, communicable disease, non-communicable disease) with a centre-to-state share of **60:40 (90:10 for the north-eastern and Himalayan states)**. The **National Health Accounts** track where the money finally comes from: out-of-pocket expenditure has fallen from **62.6 per cent of total health expenditure in 2014-15 to 47.1 per cent in 2019-20 and to about 39 per cent in the latest estimates**, with government health expenditure still near 1.8 per cent of GDP against the 2.5 per cent target.",
      ],
    },
    {
      heading: "Monitoring, evaluation, quality assurance and the family physician's part",
      points: [
        "**Monitoring** is the continuous, day-to-day, internal tracking of whether activities are being carried out as planned - it watches **inputs and process**, uses routine records, HMIS or IHIP returns, supervisory checklists, stock registers and monthly review meetings, is done by the manager who is running the programme, and its purpose is **mid-course correction while the programme is still running**. **Evaluation** is the periodic, systematic, in-depth judgement of whether the objectives were achieved and whether the effort was worth it - it watches **outcome and impact**, may be internal or external, and its purpose is a decision about continuing, modifying, expanding or stopping.",
        "The WHO components of evaluation, worth listing by name, are **relevance** (does the service meet a real need), **adequacy** (is enough attention given to the problem), **progress** (are activities on schedule), **efficiency** (result per unit of resource), **effectiveness** (were the objectives achieved) and **impact** (the overall effect on health status and development). Evaluation is also classified as **formative or process** (during, to improve) versus **summative or outcome** (at the end, to judge), and as **concurrent** versus **terminal**.",
        "**Donabedian's framework (Avedis Donabedian, 1966)** is the standard way to organise any quality or evaluation answer: **structure** - the buildings, equipment, drugs, staff, money and organisation (a functional labour room, an ILR with a temperature log, two staff nurses in position); **process** - what is actually done to and for the patient (partograph filled, active management of the third stage, blood pressure recorded at every antenatal visit, referral made); and **outcome** - what happens as a result (case fatality, maternal deaths, blood pressure control rate, patient satisfaction). Structure is the easiest to measure and the weakest proxy for quality; outcome is what matters but is slow, rare and confounded, so **process indicators are usually the most useful for management**.",
        "**Indicators** follow the same chain - **input** (funds released, staff trained), **process** (sessions held, proportion of ANC visits with haemoglobin done), **output** (children fully immunised, deliveries conducted), **outcome** (immunisation coverage, proportion of hypertensives controlled) and **impact** (infant mortality rate, maternal mortality ratio) - and a usable indicator must be **valid, reliable, sensitive, specific, feasible to collect and relevant**, with the numerator and denominator both defined in writing. Every objective in the plan should have named its indicator before implementation began.",
        "**Supportive supervision** replaces inspection: a structured checklist, on-site observation of a clinical task, feedback given the same day, joint problem solving with the staff, on-the-job mentoring, and a written action point carried forward to the next visit - the NHM model, and much more effective than fault-finding at the monthly meeting. It is the practical link between monitoring and improvement.",
        "**Quality assurance** in Indian public health has four named schemes to quote: the **National Quality Assurance Standards (NQAS, 2013)**, assessed over eight areas of concern (service provision, patient rights, inputs, support services, clinical services, infection control, quality management and outcome), with district, state and national assessment and a pass mark of **70 per cent**, certification valid for three years with annual surveillance; **Kayakalp (launched 15 May 2015)** for cleanliness, hygiene, waste management and infection control, scored over seven thematic areas; **LaQshya (December 2017)** for labour rooms and maternity operation theatres; and **MusQan (2021)** for child-friendly services, alongside the **Mera Aspataal** patient-feedback system. Quality improvement runs on the **PDCA or PDSA cycle** (plan, do, check or study, act) with root-cause analysis by fishbone diagram and the five whys.",
        "**The family physician's role in planning is at facility level and is examinable in its own right:** conduct the annual situation analysis of the practice or PHC area, set two or three SMART objectives for the year, prepare the drug and consumable indent from consumption data with a buffer, make the duty roster and the outreach session plan, chair the Jan Arogya Samiti and use untied funds, contribute the facility's needs to the District Health Action Plan and the PIP, run a clinical audit cycle, hold a monthly review of HMIS indicators with the team, and maintain the registers on which every one of the above depends. Planning at this level is not administration separate from medicine - it is the reason the drug is in the cupboard when the patient arrives.",
      ],
    },
  ],
  tables: [
    {
      heading: "The planning cycle: the eight steps, the question each answers and what it produces",
      columns: ["Step", "The question it answers", "Methods and sources used", "The product on paper"],
      rows: [
        [
          "1. Analysis of the health situation",
          "Where are we now, and what is wrong?",
          "Census, SRS, NFHS, HMIS and IHIP, IDSP, facility survey against IPHS, community needs assessment, SWOT",
          "A written problem statement with baseline figures and a resource inventory",
        ],
        [
          "2. Establishment of objectives and goals",
          "Where do we want to be, and by when?",
          "SMART objective writing; goals broken into objectives and then into dated targets",
          "A numbered list of measurable objectives with baselines and end-line targets",
        ],
        [
          "3. Assessment of resources",
          "What have we actually got to do it with?",
          "Staff in position against sanction, budget heads and flexipool, untied funds, equipment and drug stock, transport, time",
          "A resource statement and an explicit gap list",
        ],
        [
          "4. Fixing priorities",
          "Which problem do we tackle first?",
          "Magnitude, seriousness, feasibility, community concern, cost; Hanlon BPRS = [(A + 2B) x C] / 3 with the PEARL filter",
          "A ranked list of problems with the reason for the rank",
        ],
        [
          "5. Write-up of the formulated plan",
          "What exactly will be done, by whom, when and at what cost?",
          "Strategy chosen from alternatives; Gantt chart or network; line-item budget; named responsibility",
          "The plan document with plan of operation, budget and indicators",
        ],
        [
          "6. Programming and implementation",
          "How is it put into action on the ground?",
          "Organising, staffing, training, procurement and supply chain, intersectoral coordination, community mobilisation",
          "Activity schedule, training calendar, indents, VHSNC and Jan Arogya Samiti minutes",
        ],
        [
          "7. Monitoring",
          "Is it happening as planned, and what needs correcting now?",
          "Routine returns, supervisory checklists, stock registers, monthly review, supportive supervision visits",
          "Monthly progress report with variance against schedule and corrective action",
        ],
        [
          "8. Evaluation",
          "Did it work, was it worth it, and what next?",
          "Relevance, adequacy, progress, efficiency, effectiveness, impact; Donabedian structure-process-outcome; coverage surveys",
          "Evaluation report whose findings become the next situation analysis - the cycle closes",
        ],
      ],
    },
    {
      heading: "PERT compared with CPM",
      columns: ["Feature", "PERT", "CPM"],
      rows: [
        ["Full form and origin", "Programme Evaluation and Review Technique; US Navy Polaris missile programme, 1958", "Critical Path Method; DuPont with Remington Rand for plant maintenance, 1957"],
        ["Nature of time estimates", "Probabilistic - three estimates: optimistic (to), most likely (tm), pessimistic (tp)", "Deterministic - a single time estimate based on past experience"],
        ["Key formula", "te = (to + 4tm + tp) / 6; standard deviation = (tp - to) / 6; variance = [(tp - to) / 6] squared", "Cost slope = (crash cost - normal cost) / (normal time - crash time)"],
        ["Orientation", "Event-oriented - attention on the milestones or nodes", "Activity-oriented - attention on the tasks or arrows"],
        ["What it controls", "Time only; no cost dimension in the classical form", "Time and cost together, with an explicit time-cost trade-off"],
        ["Crashing", "Not a feature of the classical method", "Central feature - shorten the critical activity with the lowest cost slope first, then re-identify the critical path"],
        ["Best suited to", "Novel, one-off, research and development projects with uncertain durations - a new programme launch, a first campaign, a research study", "Repetitive projects of known duration - construction, maintenance, a routine annual round of a campaign"],
        ["Probability statement possible", "Yes - Z = (scheduled time - expected time) / project standard deviation, read against the normal table", "No - the completion time is treated as fixed"],
        ["Health service example", "Planning a first mass measles-rubella campaign in a district", "Construction and commissioning of a new primary health centre building"],
      ],
    },
    {
      heading: "Worked SWOT and TOWS: Rampur PHC, objective - obtain NQAS certification within 12 months",
      columns: ["Cell", "What belongs here", "Worked content for Rampur PHC", "What it is used for"],
      rows: [
        [
          "Strengths",
          "Internal and favourable - what we have and do well",
          "90 per cent of sanctioned posts filled, including 2 medical officers and 3 staff nurses; 2019 building to IPHS layout with a 24x7 labour room; ILR and deep freezer functional with complete temperature logging; institutional deliveries up from 40 to 78 a month in two years; active Jan Arogya Samiti with Rs 1.75 lakh untied funds unspent; Kayakalp score of 68 per cent last year",
          "Feeds the SO and ST strategies - the assets to build on and to defend with",
        ],
        [
          "Weaknesses",
          "Internal and unfavourable - what we lack or do badly",
          "No written standard operating procedures, no departmental quality teams and no internal assessment ever done; biomedical waste segregation erratic with only 3 of 6 staff trained; six-week stock-out of iron-folic acid and haemoglobin reagent last quarter; laboratory has no external quality assurance link and no calibration records; citizen's charter, grievance box and examination-room privacy screen absent; HMIS entry running 2 to 3 weeks late",
          "Feeds the WO and WT strategies - the gaps that the score will be lost on",
        ],
        [
          "Opportunities",
          "External and favourable - what the environment offers",
          "NHM programme implementation plan carries a quality assurance budget line and a quality incentive paid against the certification score; District Quality Assurance Unit consultant available for mock assessment and hand-holding; Collector reviews certification progress monthly; Ayushman Arogya Mandir upgradation brings a Community Health Officer and infrastructure funds; free drugs and free diagnostics initiatives already funded at state level; nursing college 8 km away willing to depute students for hygiene promotion",
          "Feeds the SO and WO strategies - the outside help that can be pulled in",
        ],
        [
          "Threats",
          "External and unfavourable - what the environment can do to us",
          "One medical officer post likely to be pulled for district duty and mid-cycle transfers possible; two private nursing homes drawing away deliveries; erratic power supply and monsoon flooding of the approach road for 3 to 4 weeks a year; irregular supply of consumables from the central medical store; local pressure to retain an untrained contractual attendant",
          "Feeds the ST and WT strategies - what the plan must be defended against",
        ],
        [
          "SO strategy (maxi-maxi)",
          "Use strengths to seize opportunities",
          "Constitute the quality team from the full staff complement in week 1 and invite the District Quality Assurance Unit for a baseline gap assessment in month 1; use the Kayakalp score of 68 per cent as the starting point for the areas of concern that NQAS scores in common; present the rising delivery load to the Collector's monthly review to secure the quality incentive money early",
          "The growth strategy - the fastest route to the target",
        ],
        [
          "WO strategy (mini-maxi)",
          "Use opportunities to overcome weaknesses",
          "Use the NHM quality budget line and the DQAU consultant to write all standard operating procedures and to train all 6 staff in biomedical waste segregation; use the free diagnostics initiative to end the reagent stock-out and to link the laboratory to district external quality assurance; spend the untied Jan Arogya Samiti funds on the privacy screen, citizen's charter board and grievance box; put HMIS entry on a fixed weekly slot with a named person",
          "The turnaround strategy - the largest single gain in score",
        ],
        [
          "ST strategy (maxi-mini)",
          "Use strengths to blunt threats",
          "Advertise the 24x7 labour room, the clean cold chain and JSY payment within 7 days through the panchayat and ASHAs to hold the delivery load against the private nursing homes; use Jan Arogya Samiti funds for a solar or generator back-up so power cuts do not stop services; cross-train a second person for every critical task so that one transfer does not stop the effort",
          "The defensive strategy - protect what already works",
        ],
        [
          "WT strategy (mini-mini)",
          "Minimise weakness and threat together",
          "Keep a two-month buffer stock with an indent calendar so that supply delays never become stock-outs; fix the internal assessment date before the monsoon; put the untrained attendant on a defined non-clinical role in writing; write the certification action plan with named owners and dates so that it survives a transfer",
          "The survival strategy - stop the avoidable failure",
        ],
      ],
    },
  ],
  redFlags: [
    "**Objectives that are not measurable** - a plan whose objective is to improve maternal health has no baseline, no target and no way of ever being declared a success or a failure; if the objective cannot be written as a number with a date, it is a slogan.",
    "**Targets fixed before the resources were assessed** - the commonest failure of district plans, where the coverage target is copied from the state letter and the staff, vehicles, cold chain and money to achieve it were never counted; the plan then fails in the second month and demoralises the team.",
    "**No baseline data, or data that nobody believes** - denominators taken from a decade-old census, coverage figures above 100 per cent, HMIS entered from memory at the end of the quarter; without a trustworthy baseline the evaluation at the end can prove nothing.",
    "**No community involvement** - a plan written in the block office without the VHSNC, the Jan Arogya Samiti, the panchayat or the ASHAs will fail on acceptability and utilisation however sound its arithmetic; community participation belongs at every step of the cycle, not at the inauguration.",
    "**No monitoring indicators and no review rhythm** - if nobody has defined what will be counted monthly, by whom and against what schedule, deviation is discovered only at the end of the year when nothing can be corrected.",
    "**A plan written for the report rather than for use** - the document that exists to be submitted upward, is filed on approval and is never opened again; the test is whether the person responsible for an activity can state, without the document, what he is to do this month.",
    "**No evaluation loop** - the plan ends with implementation and its findings never re-enter a fresh situation analysis, so the same problems are re-planned next year; a planning cycle drawn as a straight line is a planning cycle that has already failed.",
  ],
  pearls: [
    "Write the WHO definition of health planning verbatim in the first line: the orderly process of defining community health problems, identifying unmet needs, surveying the resources to meet them, establishing priority goals that are realistic and feasible, and projecting administrative action to accomplish the purpose of the proposed programme.",
    "**POSDCORB** - Planning, Organising, Staffing, Directing, COordinating, Reporting, Budgeting (Gulick and Urwick, 1937). Expand every letter; the mark is for the expansion, not the mnemonic.",
    "Goal, objective, target: a goal is broad and distant, an objective is specific and measurable, a target is the objective with a number and a date. Say which is which before listing any of them.",
    "The examiner is looking for the **circle**: draw the planning cycle with evaluation feeding back into situation analysis. A straight-line flow chart loses the mark that the word cycle was put there to earn.",
    "**te = (to + 4tm + tp) / 6**, standard deviation **= (tp - to) / 6**. Both are one-line marks and both are lost by candidates who remember only the first.",
    "The **critical path is the longest path through the network** and therefore the **shortest time in which the project can be completed**; activities on it have **zero float**. Say both halves of that sentence - the apparent contradiction is the point being tested.",
    "PERT is **probabilistic, event-oriented and time-based**, for novel projects; CPM is **deterministic, activity-oriented and time-cost-based**, for repetitive projects and it alone allows **crashing**. Three contrasts, three marks.",
    "In SWOT, strengths and weaknesses are **internal and present**, opportunities and threats are **external and future**. Drug shortage in my PHC is a weakness; delay in the state supply chain is a threat. Misfiling items across that line is the commonest error in the answer book.",
    "A SWOT that stops at four lists is half an answer - finish it with the **TOWS pairings, SO, WO, ST and WT** (Weihrich, 1982), each converted into an action with an owner, a date and an indicator.",
    "Committee one-liners: **Bhore 1946** - PHC and the social physician; **Mudaliar 1962** - consolidate, do not multiply; **Chadha 1963** - basic health worker per 10,000 for malaria vigilance; **Kartar Singh 1973** - multipurpose worker per 5,000; **Shrivastav 1975** - community health workers and the referral complex; **Bajaj 1986** - health manpower planning and an educational commission for health sciences.",
    "Date the changes: the **Planning Commission was replaced by NITI Aayog on 1 January 2015** and the **Twelfth Five-Year Plan (2012-17) was the last**. Describing five-year plans as the current instrument of health planning dates the whole answer.",
    "Monitoring watches **inputs and process continuously and internally to correct now**; evaluation judges **outcome and impact periodically against the original objectives to decide what next**. One sentence, two marks, asked as a differentiate question in its own right.",
  ],
  theory: [
    {
      id: "preventive-health-planning-management-t1",
      paper: "I",
      kind: "long",
      marks: 10,
      minutes: 20,
      frequency: "common",
      question:
        "What is planning and management? Describe briefly the various steps involved in planning cycle. Enumerate management techniques based on quantitative methods. Describe briefly the network analysis.",
      openingLines: [
        "Planning is the process of determining in advance what is to be accomplished, when, by whom, how and at what cost; health planning, in the WHO definition, is the orderly process of defining community health problems, identifying unmet needs and surveying the resources to meet them, establishing priority goals that are realistic and feasible, and projecting administrative action to accomplish the purpose of the proposed programme.",
        "Management is the process of getting things done through and with people - the planning, organising, staffing, directing, coordinating, reporting and budgeting of men, money, material, machines and minutes so that the stated objectives are achieved; planning is thus one function of management, and the two are joined in a repeating planning cycle that runs from situation analysis through implementation to evaluation and back again.",
      ],
      answer: [
        {
          heading: "1. Planning and management defined, with their levels",
          points: [
            "**Planning:** deciding in advance what to do, how, when, by whom and at what cost, on the basis of a systematic analysis of the situation. It is needed because needs are unlimited and resources finite, because the disease pattern is shifting, because technology and its cost are rising, and because services grow unevenly unless directed.",
            "**Management:** the process of getting things done through and with people, by planning, organising, staffing, directing, coordinating and controlling the **five Ms - men, money, material, machines and minutes** - to achieve the objective efficiently. Planning is one of its functions; execution, supervision and control are the rest.",
            "**Levels of planning:** **strategic** (top level, policy, 5 to 20 years - Ministry of Health and Family Welfare, NITI Aayog, National Health Policy 2017); **tactical or managerial** (middle level, 1 to 5 years - state and district, the District Health Action Plan and the NHM Programme Implementation Plan); **operational** (frontline, days to a year - the PHC medical officer's session plan, indent and duty roster).",
            "**Functions of management - POSDCORB (Gulick and Urwick, 1937):** Planning, Organising, Staffing, Directing, COordinating, Reporting, Budgeting.",
            "**Henri Fayol (1916)** gave five functions - planning, organising, commanding, coordinating and controlling - and 14 principles, of which unity of command, scalar chain, division of work, equity and esprit de corps are the ones usually quoted.",
          ],
        },
        {
          heading: "2. Steps of the planning cycle (the section carrying the most marks)",
          points: [
            "**Step 1 - Analysis of the health situation:** health status (mortality, morbidity, nutrition, demography from SRS, NFHS, HMIS and IDSP), health services (facilities, staff, coverage, utilisation, quality against IPHS), resources, and the environment (physical, social, economic, political, and the private sector). Product: a written problem statement with baseline figures.",
            "**Step 2 - Establishment of objectives and goals:** a goal is broad and distant, an objective is specific and measurable, a target is the objective with a number and a date. Objectives must be **SMART** and written as outcomes, for example to reduce the maternal mortality ratio in the block from 130 to 90 per 100,000 live births by 2028.",
            "**Step 3 - Assessment of resources:** manpower (in position against sanction, skills, training needs), money (budget heads, NHM flexipool, untied and Jan Arogya Samiti funds), material (building, equipment, cold chain, drugs, diagnostics, transport) and time. A gap list is drawn up here, before targets are finalised.",
            "**Step 4 - Fixing priorities:** by **magnitude**, **seriousness**, **feasibility or vulnerability of the problem to intervention**, **community concern or felt need**, and **cost with political and legal acceptability**; formalised by **Hanlon's Basic Priority Rating System, BPRS = [(A + 2B) x C] / 3** (A = size, B = seriousness, C = effectiveness, each 0 to 10) followed by the **PEARL** feasibility filter - Propriety, Economics, Acceptability, Resources, Legality.",
            "**Step 5 - Write-up of the formulated plan, with targets and a plan of operation:** the objectives and targets, the strategy chosen from among the alternatives, the activity schedule shown as a Gantt chart or a network, the person responsible for each activity, the resources allotted, the line-item budget and the indicators for monitoring.",
            "**Step 6 - Programming and implementation:** organising, staffing, training, procurement and supply, intersectoral coordination with ICDS, panchayat, education and water and sanitation, and community mobilisation through the VHSNC and Jan Arogya Samiti. Community participation belongs at every step, not only here.",
            "**Step 7 - Monitoring:** continuous internal tracking of inputs, activities and outputs against the schedule using routine returns, HMIS or IHIP, supervisory checklists and monthly review, so that deviations are corrected while the programme runs.",
            "**Step 8 - Evaluation:** periodic systematic judgement of **relevance, adequacy, progress, efficiency, effectiveness and impact** against the original objectives, whose findings become the situation analysis of the next round - which is why this is a **cycle and not a line**.",
          ],
        },
        {
          heading: "3. Management techniques based on quantitative methods (enumerate, then one line each)",
          points: [
            "**Cost-benefit analysis** - costs and consequences both valued in money; answers whether the programme is worth doing at all; output is the benefit-cost ratio. **Cost-effectiveness analysis** - cost in money, effect in natural units (deaths averted, cases prevented); compares different ways of reaching the same objective; output is cost per unit of effect. **Cost-utility analysis** - effect as QALYs gained or DALYs averted, so that unlike programmes can be compared. **Cost accounting** - the unit cost of a service.",
            "**Input-output analysis** - relates the inputs consumed to the outputs produced and exposes imbalance and bottlenecks. **Model building and simulation** - a simplified representation of reality (epidemic models, queuing models for OPD waiting time, inventory models) allowing alternatives to be tested without risk.",
            "**System analysis** - examines the whole system of inputs, process, outputs, feedback and environment, sets out the alternative combinations of resources with their costs and consequences, and presents the choice to the decision maker.",
            "**Network analysis (PERT and CPM)** - schedules interdependent activities, identifies the critical path and the float. **Planning-programming-budgeting system (PPBS)** - budgeting by objective and programme rather than by line item.",
            "**Work study and work sampling** - method study (how the job is done) plus work measurement (how long it takes), with random instantaneous observations used to fix staffing norms; the modern form is WHO's WISN. **Organisation and methods (O and M)** - systematic review of structure, procedures, forms and registers to remove duplication and delay.",
            "**Decision making and decision trees** - square decision nodes, round chance nodes, probabilities on branches, expected value obtained by rolling back. **Management by objectives (MBO, Drucker 1954)** - superior and subordinate jointly set measurable objectives, review periodically and appraise against them.",
            "**Operational research** - linear programming, queuing theory, inventory and transport models and simulation applied to find the optimum; and the **health management information system (HMIS or IHIP)** which supplies the data on which all the above depend.",
          ],
        },
        {
          heading: "4. Network analysis described",
          points: [
            "**What it is:** a project is drawn as a network of **activities** (tasks consuming time and resources, drawn as arrows) and **events** (points in time, drawn as circles or nodes), with a **dummy activity** (broken arrow, zero time) used only to show dependency. Rules: one start and one end event, no looping, and event numbers increasing from tail to head.",
            "**Method:** list all activities and their immediate predecessors, estimate durations, draw and number the network, make a **forward pass** for earliest event times and a **backward pass** for latest event times, identify the critical path and compute the float of every other activity.",
            "**Critical path:** the **longest path through the network**, and therefore the **shortest possible project duration**; its activities have **zero float**, so any delay on it delays the whole project equally. **Total float = latest start - earliest start = latest finish - earliest finish**; free float is the delay that does not disturb the next activity. Resources are moved from floating activities to critical ones.",
            "**PERT** (US Navy Polaris, 1958) is **probabilistic, event-oriented, time-based**, for novel projects: three time estimates give **te = (to + 4tm + tp) / 6**, **standard deviation = (tp - to) / 6**, **variance = [(tp - to) / 6] squared**; variances along the critical path are summed and **Z = (scheduled time - expected time) / project standard deviation** gives the probability of finishing by a chosen date.",
            "**CPM** (DuPont, 1957) is **deterministic, activity-oriented, time-and-cost-based**, for repetitive projects, and adds the **time-cost trade-off**: **cost slope = (crash cost - normal cost) / (normal time - crash time)**, crashing the critical activity of lowest cost slope first and re-identifying the critical path after each crash.",
            "**Advantages:** forces a complete listing of activities and their interdependence (which a Gantt chart does not show), concentrates supervision on the few critical activities, reveals slack for redeployment of resources, permits realistic scheduling, costing and monitoring. **Limitations:** entirely dependent on subjective time estimates, assumes independent activities and unlimited resources, becomes unwieldy without software, needs trained staff, and PERT under-estimates duration when near-critical parallel paths exist.",
          ],
        },
        {
          heading: "5. Worked example - a block measles-rubella campaign as a network",
          points: [
            "Activities and durations: **A** administrative approval and task force, 3 days; **B** microplanning with headcount survey and session site listing (after A), 10 days; **C** vaccine, syringe and cold chain indent and receipt (after A), 7 days; **D** training of vaccinators and supervisors (after B), 4 days; **E** social mobilisation, IEC, school and panchayat meetings (after B), 6 days; **F** conduct of sessions (after C, D and E), 12 days; **G** mop-up of left-outs and dropouts (after F), 4 days; **H** rapid convenience monitoring and report (after G), 3 days.",
            "Paths: A-B-D-F-G-H = 3+10+4+12+4+3 = **36 days**; A-B-E-F-G-H = 3+10+6+12+4+3 = **38 days**; A-C-F-G-H = 3+7+12+4+3 = **29 days**.",
            "The **critical path is A-B-E-F-G-H, 38 days** - the shortest time in which this campaign can be completed. Training (D) has a float of 38 - 36 = **2 days** and the vaccine and cold chain chain (C) has a float of 38 - 29 = **9 days**.",
            "**Managerial reading:** supervision and any additional manpower go to social mobilisation, session conduct and mop-up, not to the vaccine indent, which has nine days of slack; if the campaign must be finished in 34 days, the critical activities alone are crashed - more mobilisation teams, more session sites per day.",
            "A **PERT estimate for social mobilisation** with to = 4, tm = 5 and tp = 12 days gives te = (4 + 20 + 12) / 6 = **6 days** with a standard deviation of (12 - 4) / 6 = **1.33 days**; if the variances along the critical path sum to 4, the project standard deviation is 2 days and the probability of finishing within 40 days is Z = (40 - 38) / 2 = 1.0, about **84 per cent**.",
          ],
        },
        {
          heading: "6. Conclusion",
          points: [
            "Planning without management produces documents, and management without planning produces activity without direction; the planning cycle joins them, and its last step feeds the first.",
            "The quantitative techniques exist to make the choices at steps 2 to 5 explicit and defensible, and network analysis is the one that turns the written plan into a dated, supervisable schedule.",
            "At the level of the family physician the same cycle runs on a small scale every year - analyse the practice, set two or three SMART objectives, count the resources, prioritise, write the plan, implement, monitor monthly and evaluate at twelve months.",
          ],
        },
      ],
      mustDraw: [
        "**The planning cycle as a closed circle**, not a straight flow chart: eight boxes on the circumference in order - analysis of health situation, establishment of objectives and goals, assessment of resources, fixing priorities, write-up of the formulated plan, programming and implementation, monitoring, evaluation - with the arrow from evaluation returning to analysis of the health situation, and community participation written in the centre with spokes to every step.",
        "**A small network diagram** for the measles-rubella campaign: circles numbered 1 to 7 as events, arrows labelled A to H with their durations, the three paths visible, and the **critical path A-B-E-F-G-H marked in bold or double lines with the total of 38 days written beside it**; put the float of 2 days on D and 9 days on C.",
        "**A two-column table of PERT against CPM** with at least the rows probabilistic versus deterministic, event-oriented versus activity-oriented, three time estimates versus one, time only versus time and cost with crashing, and one health example each.",
        "**A boxed list of the quantitative techniques** in the enumeration section - cost-benefit, cost-effectiveness, cost-utility, input-output, model and simulation, system analysis, network analysis, PPBS, work sampling and work study, organisation and methods, decision making, MBO, operational research - because enumerate means a list, and a list scores faster than prose.",
      ],
      markSplit: [
        { part: "Definitions of planning and management, levels and POSDCORB", marks: 2 },
        { part: "Steps of the planning cycle in order, with the circle diagram", marks: 4 },
        { part: "Enumeration of management techniques based on quantitative methods, one line each", marks: 2 },
        { part: "Network analysis: activities and events, critical path and float, PERT versus CPM with the te formula and a worked example", marks: 2 },
      ],
      keywords: [
        "planning cycle",
        "POSDCORB",
        "SMART objectives",
        "Hanlon BPRS",
        "PEARL",
        "cost-benefit analysis",
        "cost-effectiveness analysis",
        "system analysis",
        "PPBS",
        "work sampling",
        "management by objectives",
        "network analysis",
        "PERT",
        "CPM",
        "critical path",
        "float",
      ],
    },
    {
      id: "preventive-health-planning-management-t2",
      paper: "I",
      kind: "long",
      marks: 10,
      minutes: 20,
      frequency: "common",
      question:
        "What is SWOT analysis? Explain with the help of an example the steps of conducting SWOT analysis in health.",
      openingLines: [
        "SWOT analysis is a structured situational analysis in which an organisation or a programme, in relation to one clearly stated objective, lists its internal Strengths and Weaknesses against the external Opportunities and Threats in its environment, so that a strategy can be built that uses what it has and defends what it lacks.",
        "It originated as the SOFT analysis of Albert Humphrey and colleagues at the Stanford Research Institute in the 1960s, and in health it is used at the situation-analysis step of the planning cycle - for a District Health Action Plan, a facility annual plan, a readiness assessment before quality certification, or the appraisal of a new service.",
      ],
      answer: [
        {
          heading: "1. Definition and the two-by-two frame",
          points: [
            "**SWOT** = **S**trengths, **W**eaknesses, **O**pportunities, **T**hreats. One axis of the matrix is **internal against external**, the other is **helpful against harmful**.",
            "**Strengths** - internal and favourable: what we have and do well (staff in position, skills, building, equipment, funds, reputation, systems, location).",
            "**Weaknesses** - internal and unfavourable: what we lack or do badly (vacancies, stock-outs, absent protocols, poor records, untrained staff, no privacy).",
            "**Opportunities** - external and favourable: what the environment offers (new schemes and funds, partnerships, policy support, technology, unmet demand, a willing panchayat).",
            "**Threats** - external and unfavourable: what the environment can do to us (competition, transfers, epidemics, funding cuts, supply-chain failure, floods, political interference).",
            "The boundary that must not be blurred: **an internal item is one we control, an external item is one we can only respond to**. Drug shortage in my PHC is a weakness; delay in the state supply chain that causes it is a threat.",
          ],
        },
        {
          heading: "2. Steps of conducting a SWOT analysis",
          points: [
            "**Step 1 - Define the objective in writing.** SWOT is meaningless in the abstract; it must be anchored to one decision or goal, for example *can Rampur PHC obtain National Quality Assurance Standards certification within twelve months*.",
            "**Step 2 - Assemble the team and the data.** The medical officer, staff nurses and ANM, pharmacist and laboratory technician, block programme manager, accountant, ASHA facilitator, a Jan Arogya Samiti or panchayat member and a user representative, with a neutral facilitator. Bring the HMIS and IHIP output, stock position, staff in position against sanction, the last Kayakalp or internal assessment score, patient feedback and the block map.",
            "**Step 3 - Brainstorm each quadrant**, internal boxes first, one item per card, no criticism or debate while items are being generated, so that junior staff contribute.",
            "**Step 4 - Verify each item against evidence** and delete opinion that no number, record or observation supports; a strength that cannot be demonstrated is a hope.",
            "**Step 5 - Prioritise within each quadrant** by importance and, for external items, by likelihood of occurring; retain the top five or six in each box, since an unprioritised list of thirty items cannot be acted on.",
            "**Step 6 - Convert the matrix into strategy** using the four **TOWS pairings (Weihrich, 1982)** - SO, WO, ST and WT - described below.",
            "**Step 7 - Write the action plan and fix the review.** Each strategy becomes an action with a named person, a date and an indicator, and a date is fixed to repeat the analysis; without this step SWOT is a wall chart.",
          ],
        },
        {
          heading: "3. Worked example - Rampur PHC, objective: NQAS certification within 12 months",
          points: [
            "**Strengths:** 90 per cent of sanctioned posts filled, including 2 medical officers and 3 staff nurses; a 2019 building built to IPHS layout with a 24 x 7 labour room; ILR and deep freezer functional with 100 per cent temperature logging and a clean cold-chain audit; institutional deliveries risen from 40 to 78 a month over two years with JSY paid within 7 days; an active Jan Arogya Samiti holding Rs 1.75 lakh of unspent untied funds; a Kayakalp score of 68 per cent last year showing a quality culture already exists.",
            "**Weaknesses:** no written standard operating procedures, no departmental quality teams and no internal assessment ever conducted; erratic biomedical waste segregation with only 3 of 6 staff trained and a sharps pit not as per rules; a six-week stock-out of iron-folic acid and of haemoglobin reagent last quarter; a laboratory with no external quality assurance linkage and no calibration record for the semi-autoanalyser; no citizen's charter, grievance box or examination-room privacy screen; HMIS entry running two to three weeks late.",
            "**Opportunities:** a dedicated quality assurance budget line in the NHM Programme Implementation Plan and a quality incentive paid annually against the certification score; a District Quality Assurance Unit consultant available for mock assessment and hand-holding; the Collector reviewing certification progress monthly, so escalation is easy; Ayushman Arogya Mandir upgradation bringing a Community Health Officer and infrastructure funds; state-funded free drugs and free diagnostics initiatives; a nursing college 8 km away willing to depute students for hygiene promotion.",
            "**Threats:** one medical officer post likely to be withdrawn for district duty and transfers possible mid-cycle; two private nursing homes in the town drawing away institutional deliveries; erratic power supply and monsoon flooding of the approach road for three to four weeks a year; irregular supply of consumables from the central medical store; local pressure to retain an untrained contractual attendant in a clinical role.",
          ],
        },
        {
          heading: "4. Converting the example into strategy - the TOWS pairings",
          points: [
            "**SO (maxi-maxi, use strengths to seize opportunities):** constitute the quality team from the full staff complement in week 1 and call the District Quality Assurance Unit for a baseline gap assessment in month 1; use the existing Kayakalp score as the starting platform for the NQAS areas of concern that overlap; take the rising delivery figures to the Collector's monthly review to release the quality incentive early. *Owner: medical officer. Indicator: gap assessment report by day 30.*",
            "**WO (mini-maxi, use opportunities to overcome weaknesses):** use the NHM quality budget and the DQAU consultant to write all standard operating procedures and to train all six staff in biomedical waste segregation; use the free diagnostics initiative to end the reagent stock-out and to link the laboratory to district external quality assurance; spend the untied Jan Arogya Samiti funds on the privacy screen, citizen's charter board and grievance box; fix a weekly named slot for HMIS entry. *Indicator: all SOPs signed by month 4; internal assessment score above 70 per cent by month 8.*",
            "**ST (maxi-mini, use strengths to blunt threats):** publicise the 24 x 7 labour room, the clean cold chain and prompt JSY payment through the panchayat and ASHAs to hold the delivery load against the private nursing homes; buy a solar or generator back-up from Jan Arogya Samiti funds so power cuts do not stop services; cross-train a second person for every critical task so that one transfer does not stop the effort.",
            "**WT (mini-mini, minimise both):** maintain a two-month buffer stock with a written indent calendar so that supply delays never become stock-outs; hold the internal assessment before the monsoon; place the untrained attendant in a defined non-clinical role in writing; write the whole certification action plan with named owners and dates so that it survives a transfer.",
            "**The output of the exercise is therefore not four lists but a twelve-month action plan** with about a dozen dated tasks, an internal assessment in month 8, a state assessment in month 10 and the national assessment in month 12.",
          ],
        },
        {
          heading: "5. Uses and limitations of SWOT in health",
          points: [
            "**Uses:** the situation-analysis step of the planning cycle; District Health Action Plan and facility annual plan preparation; readiness assessment before NQAS, Kayakalp or LaQshya certification; appraisal of a new service such as telemedicine at a CHC or a dialysis unit; district review of a national programme such as the TB elimination programme; team building and problem solving in a group practice.",
            "**Advantages:** quick, cheap, needs no software or statistician, uses the knowledge of the people who will implement the plan and therefore builds ownership, and produces a picture on a single sheet that a mixed group can argue over.",
            "**Limitations:** subjective and dominated by the loudest voice unless facilitated; produces long unprioritised lists; assigns no weight or score, so a trivial strength sits beside a fatal weakness; the internal-external boundary is often disputed; it is a snapshot that dates quickly; and it describes rather than explains, so it must be followed by root-cause analysis (fishbone or Ishikawa diagram, the five whys, Pareto analysis) and by a written action plan.",
            "**Related tools worth naming:** PEST or PESTLE analysis for the external environment alone (political, economic, social, technological, legal, environmental); force field analysis for driving and restraining forces; the TOWS matrix for the strategy conversion; and the PDCA or PDSA cycle for carrying the resulting actions through.",
          ],
        },
      ],
      mustDraw: [
        "**The SWOT two-by-two matrix**, drawn large and labelled on both axes - the left column headed *Internal (attributes of the organisation)* and the right column *External (attributes of the environment)*, the top row *Helpful to the objective* and the bottom row *Harmful to the objective* - giving Strengths (top left), Weaknesses (bottom left), Opportunities (top right), Threats (bottom right). Write the objective in a box above the matrix.",
        "**The same matrix filled with the worked example**, at least three concrete entries in each box for Rampur PHC and its NQAS objective - the examiner has asked for an example, so the boxes must contain facts and figures, not adjectives.",
        "**The TOWS strategy matrix beneath it** - a second two-by-two with Strengths and Weaknesses as the rows, Opportunities and Threats as the columns, and SO, WO, ST and WT written in the four cells with one worked strategy in each.",
        "**A one-line flow of the seven steps** across the bottom of the page: define objective - assemble team and data - brainstorm quadrants - verify - prioritise - pair into SO, WO, ST, WT strategies - action plan with owner, date and indicator, and a return arrow to the review.",
      ],
      markSplit: [
        { part: "Definition of SWOT, its origin, the two-by-two internal-external frame and where it sits in the planning cycle", marks: 3 },
        { part: "The seven steps of conducting it, the worked health example filled into all four quadrants, and the TOWS conversion into an action plan with limitations", marks: 7 },
      ],
      keywords: [
        "SWOT analysis",
        "strengths weaknesses opportunities threats",
        "TOWS matrix",
        "Weihrich",
        "situation analysis",
        "NQAS certification",
        "Kayakalp",
        "District Health Action Plan",
        "PESTLE",
        "action plan",
      ],
    },
  ],
  mcqs: [
    {
      id: "preventive-health-planning-management-q1",
      stem: "While planning a district immunisation campaign, the time estimates for the training activity are: optimistic 2 days, most likely 5 days and pessimistic 14 days. Using PERT, the expected time for this activity is:",
      options: ["5 days", "6 days", "7 days", "7.5 days", "8 days"],
      answer: 1,
      difficulty: "moderate",
      explanation:
        "PERT weights the most likely estimate four times: te = (to + 4tm + tp) / 6 = (2 + 20 + 14) / 6 = 36 / 6 = 6 days. The option 7 days is the simple arithmetic mean of the three estimates (2 + 5 + 14) / 3, the commonest error, and 5 days is the most likely estimate taken alone, which is what PERT was designed to improve on. The standard deviation of this activity is (tp - to) / 6 = (14 - 2) / 6 = 2 days and its variance is 4; summing the variances along the critical path and taking the square root gives the project standard deviation, from which Z = (scheduled time - expected time) / project standard deviation gives the probability of completing by a chosen date.",
    },
    {
      id: "preventive-health-planning-management-q2",
      stem: "A measles-rubella campaign network has three paths: A-B-D-F-G-H = 36 days, A-B-E-F-G-H = 38 days and A-C-F-G-H = 29 days. What is the project duration and the total float on activity C?",
      options: [
        "29 days, with 9 days float on C",
        "38 days, with 9 days float on C",
        "38 days, with zero float on C",
        "36 days, with 2 days float on C",
        "103 days, with 9 days float on C",
      ],
      answer: 1,
      difficulty: "hard",
      explanation:
        "The critical path is the longest path through the network, and it therefore defines the shortest time in which the project can possibly be completed - here 38 days along A-B-E-F-G-H. Total float on a non-critical path is the difference between the critical path duration and that path's duration, so the path through C has 38 - 29 = 9 days of float. Taking the shortest path (29 days) as the project duration is the classic trap, and zero float belongs only to activities on the critical path. Adding the three paths (103) double-counts the shared activities. Managerially the answer means supervision and any extra manpower go to B, E, F, G and H, while the vaccine and cold-chain activity C has nine days of slack from which resources may safely be borrowed.",
    },
    {
      id: "preventive-health-planning-management-q3",
      stem: "Which statement about the critical path in network analysis is correct?",
      options: [
        "It is the shortest path through the network and its activities have maximum float",
        "It is the longest path through the network and its activities have zero float",
        "It is the path containing the largest number of activities regardless of their duration",
        "It is the path with the lowest cost slope and is the first to be crashed in PERT",
      ],
      answer: 1,
      difficulty: "easy",
      explanation:
        "The critical path is the longest path through the network and therefore the shortest possible project duration; every activity on it has zero total float, so a one-day delay on any of them delays the whole project by one day. It is not defined by the number of activities but by the sum of their durations. The reference to cost slope belongs to CPM, not PERT - crashing (shortening an activity by spending more) is a CPM feature, and the activity crashed first is the critical activity with the lowest cost slope, after which the critical path must be re-identified because it can shift to another path.",
    },
    {
      id: "preventive-health-planning-management-q4",
      stem: "A district wants to decide whether home-based newborn care by ASHAs or facility-based special newborn care units give more neonatal deaths averted per rupee spent. The appropriate technique is:",
      options: [
        "Cost-benefit analysis",
        "Cost-effectiveness analysis",
        "Cost-minimisation analysis",
        "Input-output analysis",
        "Work sampling",
      ],
      answer: 1,
      difficulty: "moderate",
      explanation:
        "Cost-effectiveness analysis costs the alternatives in money but measures their effects in natural units - here neonatal deaths averted - and compares two different ways of achieving the same objective, giving a cost per death averted or an incremental cost-effectiveness ratio. Cost-benefit analysis would require the deaths averted to be converted into money, which answers a different question (is the programme worth doing at all) and raises the problem of valuing life. Cost-minimisation applies only when the outcomes of the alternatives are known to be identical, which is not the case here. Input-output analysis relates resources consumed to services produced but does not compare alternatives, and work sampling is a work-study method for fixing staffing norms. If the district also wanted to compare this with a cataract programme it would need cost-utility analysis using DALYs averted or QALYs gained.",
    },
    {
      id: "preventive-health-planning-management-q5",
      stem: "The committee that recommended the multipurpose health worker, one for every 5,000 population, with a health supervisor for every four workers, was:",
      options: [
        "Chadha Committee, 1963",
        "Mukherjee Committee, 1965",
        "Jungalwalla Committee, 1967",
        "Kartar Singh Committee, 1973",
        "Shrivastav Committee, 1975",
      ],
      answer: 3,
      difficulty: "easy",
      explanation:
        "The Kartar Singh Committee (Committee on Multipurpose Workers under Health and Family Planning, 1973) recommended converting the single-purpose workers into male and female multipurpose health workers, one per 5,000 population (3,000 in hilly and tribal areas), with one health supervisor per four workers and a PHC for every 50,000. The Chadha Committee (1963) had earlier proposed basic health workers, one per 10,000, for malaria vigilance in the maintenance phase, and it failed from overload; the Mukherjee Committee (1965) reversed that by separating family planning staff again. The Jungalwalla Committee (1967) defined integrated health services with a unified cadre and no private practice, and the Shrivastav Committee (1975) recommended community health workers drawn from the community and a referral services complex, leading to the Rural Health Scheme of 1977.",
    },
    {
      id: "preventive-health-planning-management-q6",
      stem: "In a SWOT analysis carried out by a PHC medical officer, the item 'two private nursing homes have opened in the town and are taking away deliveries' is correctly placed under:",
      options: ["Strength", "Weakness", "Opportunity", "Threat"],
      answer: 3,
      difficulty: "easy",
      explanation:
        "Strengths and weaknesses are internal - attributes of the facility itself, which it controls. Opportunities and threats are external - features of the environment, which it can only respond to. Competition from private nursing homes is external and unfavourable, and is therefore a threat; it is not a weakness, because the PHC did not create it. The corresponding internal weakness might be that the labour room lacks privacy or that JSY payments are delayed. The distinction is the commonest source of lost marks: drug shortage in my PHC is a weakness, delay in the state supply chain is a threat. Threats are handled through the ST (use strengths to blunt threats) and WT (minimise both) pairings of the TOWS matrix.",
    },
    {
      id: "preventive-health-planning-management-q7",
      stem: "Regarding health planning machinery in India, which statement is correct as of today?",
      options: [
        "The Planning Commission continues to draw five-year plans, the current one being the fourteenth",
        "The Planning Commission was replaced by NITI Aayog on 1 January 2015 and the Twelfth Five-Year Plan (2012-17) was the last",
        "NITI Aayog replaced the National Development Council in 2017 and prepares the National Health Policy",
        "Five-year plans were discontinued after the Tenth Plan, and health planning is now done only by the states",
      ],
      answer: 1,
      difficulty: "moderate",
      explanation:
        "The Planning Commission, created by a Cabinet resolution in March 1950 with the Prime Minister as chairman, was replaced by NITI Aayog (National Institution for Transforming India) on 1 January 2015; the Twelfth Five-Year Plan (2012-17) was the last, and central planning now runs through NITI Aayog's vision, strategy and action-agenda documents, Finance Commission recommendations and the annual budget. NITI Aayog replaced the Planning Commission, not the National Development Council, and the National Health Policy is issued by the Ministry of Health and Family Welfare (the current one is the National Health Policy 2017, which targets government health expenditure of 2.5 per cent of GDP by 2025). Health planning continues centrally through the National Health Mission, whose funds flow to states against a Programme Implementation Plan built up from District Health Action Plans, so it is not a state-only activity.",
    },
  ],
  cards: [
    {
      id: "preventive-health-planning-management-c1",
      front: "WHO definition of health planning.",
      back: "The orderly process of defining community health problems, identifying unmet needs and surveying the resources to meet them, establishing priority goals that are realistic and feasible, and projecting administrative action to accomplish the purpose of the proposed programme.",
    },
    {
      id: "preventive-health-planning-management-c2",
      front: "POSDCORB - expand it and name the authors.",
      back: "Planning, Organising, Staffing, Directing, COordinating, Reporting, Budgeting. Luther Gulick and Lyndall Urwick, 1937. Fayol (1916) gave the parent five - planning, organising, commanding, coordinating, controlling - plus 14 principles.",
    },
    {
      id: "preventive-health-planning-management-c3",
      front: "The eight steps of the planning cycle, in order.",
      back: "1 Analysis of the health situation, 2 establishment of objectives and goals, 3 assessment of resources, 4 fixing priorities, 5 write-up of the formulated plan, 6 programming and implementation, 7 monitoring, 8 evaluation - which feeds back into step 1. Draw it as a circle.",
    },
    {
      id: "preventive-health-planning-management-c4",
      front: "How are priorities set in health planning?",
      back: "Magnitude, seriousness, feasibility or vulnerability to intervention, community concern or felt need, and cost with political and legal acceptability. Formalised as Hanlon's BPRS = [(A + 2B) x C] / 3 (A size, B seriousness, C effectiveness, each 0-10) with the PEARL filter - Propriety, Economics, Acceptability, Resources, Legality.",
    },
    {
      id: "preventive-health-planning-management-c5",
      front: "PERT expected time, standard deviation and variance.",
      back: "te = (to + 4tm + tp) / 6; standard deviation = (tp - to) / 6; variance = [(tp - to) / 6] squared. Sum variances along the critical path, take the square root for the project SD, then Z = (scheduled time - expected time) / project SD.",
    },
    {
      id: "preventive-health-planning-management-c6",
      front: "Critical path and total float - define both.",
      back: "Critical path = the longest path through the network, and therefore the shortest possible project duration; its activities have zero float. Total float = latest start - earliest start = latest finish - earliest finish, the delay possible without pushing back the project end. Move resources from floating to critical activities.",
    },
    {
      id: "preventive-health-planning-management-c7",
      front: "PERT versus CPM in three contrasts.",
      back: "PERT - probabilistic (three time estimates), event-oriented, time only, for novel projects; US Navy Polaris 1958. CPM - deterministic (one estimate), activity-oriented, time and cost with crashing (cost slope = (crash cost - normal cost) / (normal time - crash time)), for repetitive projects; DuPont 1957.",
    },
    {
      id: "preventive-health-planning-management-c8",
      front: "Management techniques based on quantitative methods - the enumeration.",
      back: "Cost-benefit, cost-effectiveness, cost-utility and cost accounting; input-output analysis; model building and simulation; system analysis; network analysis (PERT/CPM); PPBS; work study and work sampling; organisation and methods; decision making and decision trees; management by objectives; operational research; health management information system.",
    },
    {
      id: "preventive-health-planning-management-c9",
      front: "Cost-benefit versus cost-effectiveness versus cost-utility.",
      back: "CBA - costs and consequences both in money; is it worth doing at all (benefit-cost ratio). CEA - cost in money, effect in natural units (deaths averted); which way of reaching the same objective is cheapest. CUA - effect as QALYs gained or DALYs averted; allows unlike programmes to be compared.",
    },
    {
      id: "preventive-health-planning-management-c10",
      front: "SWOT - the internal-external rule and the TOWS pairings.",
      back: "Strengths and weaknesses are internal and present; opportunities and threats are external and future. TOWS (Weihrich 1982): SO maxi-maxi (strengths to seize opportunities), WO mini-maxi (opportunities to fix weaknesses), ST maxi-mini (strengths to blunt threats), WT mini-mini (minimise both).",
    },
    {
      id: "preventive-health-planning-management-c11",
      front: "Monitoring versus evaluation.",
      back: "Monitoring - continuous, internal, day-to-day, watches inputs and process against the schedule, corrects while the programme runs. Evaluation - periodic, systematic, internal or external, judges outcome and impact against the original objectives on relevance, adequacy, progress, efficiency, effectiveness and impact, and decides what next.",
    },
    {
      id: "preventive-health-planning-management-c12",
      front: "Committee one-liners: Bhore, Mudaliar, Chadha, Kartar Singh, Shrivastav, Bajaj.",
      back: "Bhore 1946 - PHC, integration of preventive and curative, three-million plan, the social physician. Mudaliar 1962 - consolidate existing PHCs, strengthen district hospitals. Chadha 1963 - basic health worker per 10,000 for malaria vigilance. Kartar Singh 1973 - multipurpose worker per 5,000, supervisor per 4 workers. Shrivastav 1975 - community health workers, referral services complex. Bajaj 1986 - health manpower planning, Educational Commission for Health Sciences.",
    },
  ],
  references: [
    "Park K. Park's Textbook of Preventive and Social Medicine, 27th edition, 2023 - chapters on Health Planning and Management, and Health Care of the Community (planning cycle, management techniques, network analysis, the health committees)",
    "National Health Policy 2017, Ministry of Health and Family Welfare, Government of India - goals, targets and the assurance-based approach",
    "WHO. Health service planning and policy-making: a toolkit for nurses and midwives, WHO Regional Office for the Western Pacific, 2005; and WHO District Health Planning guidance - situation analysis, priority setting, SWOT and monitoring",
    "Goel SL. Health Care Management and Administration (Deep and Deep Publications) and Kunders GD, Hospital Planning, Design and Management - PERT, CPM, work study, PPBS and management by objectives applied to health services",
    "National Health Mission Programme Implementation Plan guidelines and the Framework for Implementation, MoHFW - District Health Action Plan, PIP appraisal, Record of Proceedings, flexible pools and the 60:40 funding pattern; with the National Quality Assurance Standards (2013, operational guidelines) and the Kayakalp (2015) and LaQshya (2017) guidelines",
  ],
});

export default topics;
