import type { Topic } from "../../lib/types";

const topics: Topic[] = [
  {
    id: "dermatology-sti-genital-ulcer-urethral-discharge",
    title: "Genital ulcer disease, urethral discharge and syndromic STI management",
    oneLiner:
      "Genital ulcer disease (syphilis, chancroid, herpes, LGV, donovanosis) and urethral discharge (gonococcal and non-gonococcal urethritis) are the two commonest male STI syndromes, managed in India by **syndromic case management with NACO colour-coded kits** at Suraksha clinics - treating on the day of the visit for all likely organisms, backed by RPR/TPHA and HIV testing and the **4 Cs: compliance, condoms, counselling and contact tracing**.",
    frequency: "core",
    keywords: [
      "STI",
      "RTI",
      "syndromic management",
      "genital ulcer disease",
      "GUD",
      "urethral discharge",
      "syphilis",
      "chancroid",
      "herpes genitalis",
      "LGV",
      "donovanosis",
      "gonorrhoea",
      "non-gonococcal urethritis",
      "VDRL",
      "RPR",
      "TPHA",
      "benzathine penicillin",
      "NACO kits",
      "Suraksha clinic",
      "partner notification",
      "inguinal bubo",
      "MSM",
    ],
    sections: [
      {
        heading: "Burden and programme framework in India",
        points: [
          "NACO estimates **3-3.5 crore episodes of STI/RTI a year** in India, and an STI raises the risk of acquiring HIV two- to five-fold. [NACP-V 2021]",
          "India had an estimated **25 lakh people living with HIV in 2023** with adult prevalence about 0.2 per cent, concentrated in key populations. [NACO HIV Estimates 2023]",
          "**Herpes genitalis is now the commonest cause of genital ulcer** in Indian STI clinics, while chancroid and donovanosis have declined sharply. [Rook 10e]",
          "Syphilis is resurgent among **men who have sex with men, transgender people and female sex workers**, and remains a target of elimination of vertical transmission. [NACO 2024]",
          "STI/RTI services are delivered at **Designated STI/RTI Clinics branded as Suraksha Clinics** in district hospitals and medical colleges, and through targeted interventions for key populations. [NACP-V 2021]",
          "**Pre-packed colour-coded kits** are supplied free, so the patient leaves the first visit fully treated. [NACP-V 2021]",
          "**Syndromic case management** treats the syndrome for all common organisms at the first visit, without waiting for a laboratory - WHO recommends it where etiological testing is unavailable. [WHO STI 2021]",
          "Advantages are **same-day treatment, no loss to follow-up, and usability by trained non-specialists**; the drawbacks are over-treatment and missing asymptomatic infection, especially in women. [WHO STI 2021]",
          "NACP-V aims for **syndromic management with laboratory support** - Gram stain, RPR and wet mount at Suraksha clinics - to reduce overtreatment. [NACP-V 2021]",
        ],
      },
      {
        heading: "Genital ulcer: causes and clinical differentiation",
        points: [
          "**Primary syphilis (Treponema pallidum)** gives a single, painless, indurated, clean-based ulcer (chancre) about 3 weeks after exposure, with rubbery non-tender bilateral nodes. [Rook 10e]",
          "**Chancroid (Haemophilus ducreyi)** gives multiple painful, soft, ragged ulcers with undermined edges and a purulent base after 3-7 days, with a painful unilateral bubo that may suppurate. [Rook 10e]",
          "**Genital herpes (HSV-2 and increasingly HSV-1)** starts as grouped painful vesicles that break into shallow multiple erosions, with fever and tender nodes in the first episode. [Rook 10e]",
          "**Lymphogranuloma venereum (Chlamydia trachomatis L1-L3)** has a transient painless papule, followed weeks later by painful matted inguinal nodes and the **groove sign** above and below the inguinal ligament. [Rook 10e]",
          "**Donovanosis (Klebsiella granulomatis)** is a painless, beefy-red, friable ulcer that bleeds on touch, with a subcutaneous **pseudobubo** but no true lymphadenitis. [Rook 10e]",
          "Donovanosis is confirmed by **Donovan bodies** (safety-pin, bipolar-staining organisms in macrophages) on a Giemsa or Leishman stained tissue smear. [Rook 10e]",
          "Pain favours herpes and chancroid; **painless induration** favours syphilis; bleeding beefy granulation favours donovanosis. [Harrison 22e]",
          "**Mixed infections are common** - clinical diagnosis alone is wrong in about a third of ulcers, which is why the syndromic kit covers both syphilis and chancroid. [WHO STI 2021]",
          "Non-STI causes of genital ulcer include **fixed drug eruption** (commonly from cotrimoxazole, fluconazole, NSAIDs), Behcet disease, trauma, scabies nodules and squamous cell carcinoma. [Rook 10e]",
          "An ulcer persisting beyond **4-6 weeks despite treatment** needs a biopsy to exclude carcinoma and donovanosis. [Rook 10e]",
        ],
      },
      {
        heading: "Syphilis: stages, serology and benzathine penicillin",
        points: [
          "**Primary syphilis** (chancre) appears 9-90 days after exposure and heals in 3-6 weeks even without treatment. [Harrison 22e]",
          "**Secondary syphilis** at 6-12 weeks gives a non-itchy papulosquamous rash including **palms and soles**, condylomata lata, mucous patches, snail-track ulcers and generalised lymphadenopathy. [Harrison 22e]",
          "**Latent syphilis** is seropositive without signs - early latent within 1 year (WHO uses 2 years) and late latent beyond that. [WHO STI 2024]",
          "**Tertiary syphilis** - gummas, aortitis and neurosyphilis (tabes dorsalis, general paresis) - appears years later; neurosyphilis can occur at any stage, especially with HIV. [Harrison 22e]",
          "**Non-treponemal tests (VDRL, RPR)** detect anti-cardiolipin antibody, are quantitative, fall with treatment and are used to **monitor response**. [Harrison 22e]",
          "**Treponemal tests (TPHA, TPPA, FTA-ABS, EIA/CLIA, rapid point-of-care)** are specific and **remain positive for life**, so they confirm but cannot show cure. [Harrison 22e]",
          "**Biological false-positive VDRL** occurs in pregnancy, SLE and antiphospholipid syndrome, malaria, leprosy, TB, HIV, injecting drug use and old age - usually at low titres. [Harrison 22e]",
          "A negative VDRL in florid secondary syphilis may be the **prozone phenomenon** - ask the lab to test diluted serum. [Harrison 22e]",
          "**Early syphilis (primary, secondary, early latent): benzathine penicillin G 2.4 million units IM as a single dose** (1.2 MU in each buttock). [WHO STI 2024]",
          "**Late latent or unknown duration: benzathine penicillin G 2.4 MU IM once weekly for 3 weeks.** [WHO STI 2024]",
          "**Neurosyphilis: aqueous crystalline penicillin G 18-24 MU a day IV (3-4 MU every 4 hours) for 10-14 days.** [CDC STI 2021]",
          "Penicillin allergy (non-pregnant): **doxycycline 100 mg twice daily for 14 days** in early syphilis and **28 days** in late latent; in pregnancy desensitise and use penicillin. [WHO STI 2024]",
          "Keep **adrenaline and an anaphylaxis kit ready** when giving benzathine penicillin, and warn about the **Jarisch-Herxheimer reaction** (fever, myalgia within 24 hours). [CDC STI 2021]",
          "Follow up with **quantitative RPR at 6 and 12 months** - a fourfold (two-dilution) fall means adequate response. [CDC STI 2021]",
        ],
      },
      {
        heading: "Treatment of other genital ulcers",
        points: [
          "**Chancroid:** azithromycin 1 g orally single dose, or ceftriaxone 250 mg IM single dose, or ciprofloxacin 500 mg twice daily for 3 days. [CDC STI 2021]",
          "**First-episode herpes:** aciclovir 400 mg three times daily for 7-10 days, or valaciclovir 1 g twice daily for 7-10 days. [CDC STI 2021]",
          "**Recurrent herpes:** aciclovir 400 mg three times daily for 5 days started within a day of prodrome; **suppression with aciclovir 400 mg twice daily** if six or more episodes a year. [CDC STI 2021]",
          "**LGV:** doxycycline 100 mg twice daily for **21 days**; azithromycin 1 g weekly for 3 weeks is the alternative in pregnancy. [CDC STI 2021]",
          "**Donovanosis:** azithromycin 1 g weekly or 500 mg daily for **at least 3 weeks and until all lesions heal**; doxycycline 100 mg twice daily is the alternative. [CDC STI 2021]",
          "Counsel herpes patients that **transmission occurs during asymptomatic shedding**, so condoms are needed even without lesions. [Rook 10e]",
        ],
      },
      {
        heading: "Urethral discharge: gonococcal and non-gonococcal",
        points: [
          "**Gonococcal urethritis** has an incubation of 2-5 days with profuse purulent discharge and dysuria; **non-gonococcal urethritis** (Chlamydia, Mycoplasma genitalium, Trichomonas) is scantier and mucoid, after 1-3 weeks. [Harrison 22e]",
          "**Milk the urethra** if no discharge is visible - asking the patient not to pass urine for 2-4 hours before examination improves yield. [NACP-V 2021]",
          "**Gram stain** showing **Gram-negative intracellular diplococci** in polymorphs is over 95 per cent sensitive for gonorrhoea in symptomatic men. [Harrison 22e]",
          "**Urethritis without diplococci** - 2 or more polymorphs per oil-immersion field - means NGU. [CDC STI 2021]",
          "NAAT on first-void urine is the most sensitive test for gonorrhoea and chlamydia, but **culture with sensitivity** is needed for resistance surveillance. [WHO STI 2024]",
          "**NACO Kit 1 (grey): cefixime 400 mg orally plus azithromycin 1 g orally, both single dose**, covers gonorrhoea and chlamydia in urethral discharge and cervicitis. [NACP-V 2021]",
          "Because of rising resistance, **WHO 2024 recommends ceftriaxone 1 g IM single dose** for gonorrhoea, and **doxycycline 100 mg twice daily for 7 days** as first choice for chlamydia. [WHO STI 2024]",
          "Persistent discharge after proper treatment and no re-exposure: **metronidazole 2 g single dose for Trichomonas**, and cover Mycoplasma genitalium. [CDC STI 2021]",
          "Complications of untreated gonorrhoea include **epididymo-orchitis, urethral stricture**, disseminated gonococcal infection with arthritis-dermatitis, and neonatal ophthalmia. [Harrison 22e]",
          "Reiter-type **reactive arthritis** follows chlamydial urethritis - urethritis, conjunctivitis and arthritis. [Harrison 22e]",
        ],
      },
      {
        heading: "Inguinal bubo, scrotal swelling and anorectal STIs",
        points: [
          "**Inguinal bubo** without an ulcer is treated with **NACO Kit 7 (black): doxycycline 100 mg twice daily for 21 days plus azithromycin 1 g single dose**. [NACP-V 2021]",
          "If an ulcer is present with the bubo, **treat the ulcer syndrome as well** with the genital ulcer kit. [NACP-V 2021]",
          "**Aspirate a fluctuant bubo through healthy skin** with a wide-bore needle, repeatedly if needed - incision leads to sinus formation. [WHO STI 2021]",
          "Exclude an **inguinal or femoral hernia**, and consider TB, filarial and malignant nodes when a bubo does not respond. [Bailey and Love 28e]",
          "**Scrotal swelling:** first exclude **testicular torsion** (sudden pain, high-riding testis, absent cremasteric reflex, age under 20) - it is a surgical emergency. [Bailey and Love 28e]",
          "Epididymo-orchitis in a sexually active man under 35 is usually **gonococcal or chlamydial** - ceftriaxone 500 mg IM single dose plus doxycycline 100 mg twice daily for 10 days. [CDC STI 2021]",
          "In men over 35 or after instrumentation, epididymo-orchitis is usually **enteric** and is treated as a UTI with a fluoroquinolone. [CDC STI 2021]",
          "**Anorectal STIs in MSM** present with discharge, tenesmus, bleeding or pain on defecation, and may be caused by gonorrhoea, chlamydia including LGV, herpes and syphilis. [CDC STI 2021]",
          "Treat **proctitis** with ceftriaxone plus **doxycycline 100 mg twice daily for 7 days**, extended to 21 days if LGV is suspected (bloody discharge, ulcers, HIV). [CDC STI 2021]",
          "Take a **sexual history of anal and oral exposure without judgement** - MSM often attend with a genital complaint and are not asked about rectal or pharyngeal sites. [NACO 2024]",
          "Offer MSM **hepatitis A and B vaccination** and look for anal warts; high-risk HPV is linked to anal cancer. [CDC STI 2021]",
        ],
      },
      {
        heading: "HIV, hepatitis, PEP, PrEP and the 4 Cs",
        points: [
          "**Every STI patient is offered HIV testing** at the linked ICTC, and RPR for syphilis, as a routine and not an optional test. [NACP-V 2021]",
          "Screen for **HBsAg and anti-HCV** under the National Viral Hepatitis Control Programme, and give hepatitis B vaccine (0, 1, 6 months) if non-immune. [NVHCP 2018]",
          "**HIV post-exposure prophylaxis** after a high-risk sexual exposure: tenofovir-lamivudine-dolutegravir (TLD) one tablet daily for 28 days, started ideally within 2 hours and **no later than 72 hours**. [NACO ART 2021]",
          "**Oral PrEP** with tenofovir-emtricitabine daily is recommended by WHO for people at substantial risk, and is being offered to key populations through targeted interventions. [WHO 2022]",
          "**Doxycycline PEP** (200 mg within 72 hours of condomless sex) reduces syphilis and chlamydia in MSM and transgender women with a recent STI. [CDC Doxy-PEP 2024]",
          "**Compliance:** give the first dose under observation and explain the full course; single-dose kits exist to make compliance automatic. [NACP-V 2021]",
          "**Condoms:** demonstrate use, supply them free, and advise abstinence until 7 days after both partners complete treatment. [NACP-V 2021]",
          "**Counselling:** risk reduction, HIV testing, the nature of the infection and the need for partner treatment. [NACP-V 2021]",
          "**Contact tracing:** treat every sexual partner of the past 60 days (discharge) or 90 days (ulcer) with the same kit, whether or not they have symptoms. [WHO STI 2024]",
          "Partner notification may be **patient-referral** with a contact slip or **provider-referral** with consent - WHO 2024 recommends assisted partner services. [WHO STI 2024]",
          "Review at **7 days** for syndrome resolution, and look for STI-associated conditions such as syphilis in the partner of a pregnant woman. [NACP-V 2021]",
        ],
      },
      {
        heading: "Family physician role and referral",
        points: [
          "Take a **confidential sexual history (the 5 Ps: partners, practices, protection, past STI, pregnancy intention)** in private, without judgement. [CDC STI 2021]",
          "Examine the whole genital area, **inguinal nodes, perianal area, mouth and skin** including palms and soles for secondary syphilis. [Rook 10e]",
          "Start the **syndromic kit on the same day**, and document the syndrome and the kit given for NACO reporting. [NACP-V 2021]",
          "Refer to the Suraksha clinic or dermatology-venereology for **non-healing ulcers, suspected neurosyphilis, disseminated gonococcal infection** or treatment failure. [NACP-V 2021]",
          "Refer to ICTC and ART centre for **HIV confirmation and linkage**, and to obstetrics for syphilis in pregnancy. [NACO 2024]",
          "**Genital ulcer in a child** raises child sexual abuse - it must be reported under the POCSO Act 2012, which makes non-reporting an offence. [POCSO Act 2012]",
          "Keep the record confidential - disclosure without consent is barred by the **HIV and AIDS (Prevention and Control) Act 2017**. [HIV AIDS Act 2017]",
        ],
      },
    ],
    tables: [
      {
        heading: "Differentiating the causes of genital ulcer",
        columns: ["Feature", "Syphilis", "Chancroid", "Herpes", "LGV", "Donovanosis"],
        rows: [
          ["Organism", "Treponema pallidum", "Haemophilus ducreyi", "HSV-2, HSV-1", "C. trachomatis L1-L3", "Klebsiella granulomatis"],
          ["Incubation", "9-90 days (3 weeks)", "3-7 days", "2-12 days", "3-30 days", "1-12 weeks"],
          ["Ulcer", "Single, clean, indurated", "Multiple, ragged, undermined, purulent", "Grouped vesicles, shallow erosions", "Transient painless papule", "Beefy red, friable, bleeds on touch"],
          ["Pain", "Painless", "Painful", "Painful", "Painless ulcer", "Painless"],
          ["Nodes", "Bilateral, rubbery, non-tender", "Unilateral painful bubo, suppurates", "Bilateral tender", "Painful matted, groove sign", "Pseudobubo (subcutaneous)"],
          ["Confirmation", "Dark-ground, RPR plus TPHA", "Gram stain, culture", "Tzanck, PCR", "NAAT with serovar typing", "Donovan bodies on tissue smear"],
          ["Treatment", "Benzathine penicillin 2.4 MU IM", "Azithromycin 1 g single dose", "Aciclovir 400 mg TDS 7-10 days", "Doxycycline 100 mg BD 21 days", "Azithromycin 1 g weekly at least 3 weeks"],
        ],
      },
      {
        heading: "NACO colour-coded STI/RTI kits",
        columns: ["Kit", "Colour", "Syndrome", "Contents"],
        rows: [
          ["Kit 1", "Grey", "Urethral discharge, cervicitis, anorectal discharge", "Cefixime 400 mg plus azithromycin 1 g, single dose"],
          ["Kit 2", "Green", "Vaginitis", "Secnidazole 2 g plus fluconazole 150 mg, single dose"],
          ["Kit 3", "White", "Genital ulcer, non-herpetic", "Benzathine penicillin 2.4 MU IM plus azithromycin 1 g"],
          ["Kit 4", "Blue", "Genital ulcer, non-herpetic, penicillin allergy", "Doxycycline 100 mg BD 15 days plus azithromycin 1 g"],
          ["Kit 5", "Red", "Genital ulcer, herpetic", "Aciclovir 400 mg TDS 7 days"],
          ["Kit 6", "Yellow", "Lower abdominal pain (PID)", "Cefixime 400 mg stat, metronidazole 400 mg BD and doxycycline 100 mg BD for 14 days"],
          ["Kit 7", "Black", "Inguinal bubo", "Doxycycline 100 mg BD 21 days plus azithromycin 1 g"],
        ],
      },
      {
        heading: "Interpretation of syphilis serology",
        columns: ["VDRL or RPR", "TPHA or treponemal test", "Interpretation", "Action"],
        rows: [
          ["Reactive", "Reactive", "Active or recently treated syphilis", "Treat by stage unless adequately treated; follow RPR titre"],
          ["Non-reactive", "Reactive", "Past treated, very early or late latent syphilis", "Treat if no documented treatment; check history"],
          ["Reactive", "Non-reactive", "Biological false positive", "Look for pregnancy, SLE, APLA, malaria, leprosy, HIV"],
          ["Non-reactive", "Non-reactive", "No syphilis, or window period", "Repeat in 2-4 weeks if recent exposure or chancre"],
        ],
      },
    ],
    redFlags: [
      "Genital ulcer in a child - suspect sexual abuse and report under the POCSO Act 2012.",
      "Acute painful scrotal swelling in a young man with a high-riding testis - torsion until proved otherwise.",
      "Syphilis with headache, visual loss, hearing loss or cranial nerve palsy - neurosyphilis.",
      "Fever, arthritis and pustular skin lesions after urethritis - disseminated gonococcal infection.",
      "Genital ulcer not healing after 4-6 weeks of treatment - biopsy for carcinoma or donovanosis.",
      "Reactive syphilis serology in a pregnant woman - treat the same day and treat the partner.",
      "Rectal bleeding with ulcers and pain in an MSM with HIV - LGV proctitis.",
    ],
    pearls: [
      "Painless indurated ulcer with rubbery nodes is syphilis; painful soft undermined ulcer with a suppurating bubo is chancroid.",
      "Groove sign equals LGV; Donovan bodies equal donovanosis; terminal bulb dendrites belong to the eye, not the genitals.",
      "VDRL is for screening and follow-up; TPHA is for confirmation and stays positive for life.",
      "One injection of benzathine penicillin 2.4 MU cures early syphilis; three weekly injections for late latent.",
      "Gram-negative intracellular diplococci in polymorphs clinch gonorrhoea in a symptomatic man.",
      "Grey kit for discharge, white for ulcer, red for herpes, black for bubo, yellow for PID.",
      "Aspirate a bubo through healthy skin - never incise it.",
      "The 4 Cs - compliance, condoms, counselling, contact tracing - are where syndromic management succeeds or fails.",
      "Every STI is an HIV test indication.",
    ],
    mcqs: [
      {
        id: "dermatology-sti-genital-ulcer-urethral-discharge-q1",
        stem: "A 26-year-old migrant worker has a single painless ulcer on the coronal sulcus for 10 days. The base is clean and the edge feels like a button; there are bilateral rubbery non-tender inguinal nodes. What is the treatment of choice?",
        options: [
          "Aciclovir 400 mg three times daily for 7 days",
          "Azithromycin 1 g weekly for 3 weeks",
          "Benzathine penicillin G 2.4 million units IM single dose",
          "Doxycycline 100 mg twice daily for 21 days",
        ],
        answer: 2,
        explanation:
          "A single painless indurated clean ulcer with rubbery non-tender nodes is a primary chancre, and early syphilis is cured by one dose of benzathine penicillin 2.4 MU IM. Aciclovir treats painful grouped herpetic erosions, weekly azithromycin treats donovanosis, and 21 days of doxycycline is the regimen for LGV.",
        difficulty: "easy",
      },
      {
        id: "dermatology-sti-genital-ulcer-urethral-discharge-q2",
        stem: "A 30-year-old woman with SLE, 12 weeks pregnant, has a VDRL reactive at 1:2 dilution. TPHA is non-reactive and she has no symptoms. What is the most likely interpretation?",
        options: [
          "Biological false-positive reaction",
          "Early latent syphilis",
          "Late latent syphilis",
          "Adequately treated past syphilis",
        ],
        answer: 0,
        explanation:
          "A low-titre reactive non-treponemal test with a non-reactive treponemal test is a biological false positive, common in SLE, antiphospholipid syndrome and pregnancy. Any true syphilis, whether early latent, late latent or treated in the past, would give a reactive TPHA, which stays positive for life.",
        difficulty: "moderate",
      },
      {
        id: "dermatology-sti-genital-ulcer-urethral-discharge-q3",
        stem: "A 24-year-old man has had purulent urethral discharge and burning micturition for 3 days after unprotected sex. Under the NACO syndromic approach, which kit is given?",
        options: [
          "Kit 3 (white): benzathine penicillin plus azithromycin",
          "Kit 7 (black): doxycycline 21 days plus azithromycin",
          "Kit 2 (green): secnidazole plus fluconazole",
          "Kit 1 (grey): cefixime 400 mg plus azithromycin 1 g single dose",
        ],
        answer: 3,
        explanation:
          "Urethral discharge is treated with the grey Kit 1, covering both gonorrhoea (cefixime) and chlamydia (azithromycin) because mixed infection is common. The white kit is for non-herpetic genital ulcer, the black kit for inguinal bubo, and the green kit for vaginitis.",
        difficulty: "easy",
      },
      {
        id: "dermatology-sti-genital-ulcer-urethral-discharge-q4",
        stem: "A 32-year-old man had a small painless genital papule that healed a month ago. He now has painful matted inguinal nodes with a cleft along the inguinal ligament. What is the appropriate treatment?",
        options: [
          "Incision and drainage of the nodes",
          "Doxycycline 100 mg twice daily for 21 days",
          "Ciprofloxacin 500 mg twice daily for 3 days",
          "Benzathine penicillin 2.4 MU weekly for 3 weeks",
        ],
        answer: 1,
        explanation:
          "A transient painless primary lesion followed by painful matted nodes above and below the inguinal ligament (groove sign) is lymphogranuloma venereum, treated with doxycycline for 21 days. Incision causes sinuses (aspirate instead), ciprofloxacin is a chancroid regimen, and weekly penicillin is for late latent syphilis.",
        difficulty: "moderate",
      },
      {
        id: "dermatology-sti-genital-ulcer-urethral-discharge-q5",
        stem: "A 40-year-old man has a slowly enlarging, painless, beefy-red genital ulcer that bleeds easily on touch, with a soft groin swelling but no true lymphadenopathy. Which finding confirms the diagnosis?",
        options: [
          "Gram-negative coccobacilli in a school-of-fish pattern",
          "Multinucleated giant cells on Tzanck smear",
          "Donovan bodies in macrophages on a tissue smear",
          "Motile spirochaetes on dark-ground microscopy",
        ],
        answer: 2,
        explanation:
          "A painless friable beefy-red ulcer with a pseudobubo is donovanosis, confirmed by Donovan bodies (bipolar safety-pin organisms inside macrophages) on a Giemsa-stained crush smear. School-of-fish rods suggest chancroid, giant cells suggest herpes, and dark-ground spirochaetes suggest primary syphilis.",
        difficulty: "hard",
      },
    ],
    theory: [
      {
        id: "dermatology-sti-genital-ulcer-urethral-discharge-t1",
        paper: "III",
        kind: "long",
        marks: 10,
        minutes: 18,
        frequency: "core",
        question:
          "A 28-year-old truck driver presents with a genital ulcer and urethral discharge. Discuss the differential diagnosis of genital ulcer, the investigations, and the management as per the national syndromic approach. [4+2+4]",
        openingLines: [
          "Genital ulcer disease and urethral discharge are the two commonest STI syndromes in men, and a long-distance driver is a bridge population at high risk of both and of HIV.",
          "NACO manages them by syndromic case management with colour-coded kits, so the patient is treated for all likely organisms at the first visit.",
        ],
        answer: [
          {
            heading: "Differential diagnosis of genital ulcer",
            points: [
              "Syphilis: single painless indurated ulcer, rubbery nodes.",
              "Chancroid: multiple painful soft undermined ulcers, suppurating bubo.",
              "Herpes: grouped vesicles, painful erosions, recurrent.",
              "LGV: transient papule, painful nodes, groove sign; donovanosis: beefy red bleeding ulcer, pseudobubo.",
              "Non-STI: fixed drug eruption, Behcet, trauma, squamous cell carcinoma.",
            ],
          },
          {
            heading: "Investigations",
            points: [
              "Dark-ground microscopy, RPR with TPHA; Tzanck smear; Gram stain of ulcer and urethral discharge.",
              "Gram-negative intracellular diplococci for gonorrhoea; polymorphs without diplococci for NGU.",
              "HIV at ICTC, HBsAg, anti-HCV; biopsy for ulcers over 4-6 weeks.",
            ],
          },
          {
            heading: "Syndromic management",
            points: [
              "Urethral discharge: Kit 1 grey - cefixime 400 mg plus azithromycin 1 g single dose.",
              "Non-herpetic ulcer: Kit 3 white - benzathine penicillin 2.4 MU IM plus azithromycin 1 g; Kit 4 blue if penicillin-allergic.",
              "Herpetic ulcer: Kit 5 red - aciclovir 400 mg TDS for 7 days.",
              "4 Cs: compliance, condoms, counselling, contact tracing of partners in the last 60-90 days.",
              "Review at 7 days; refer non-healing ulcers; HIV PEP counselling if a recent exposure.",
            ],
          },
        ],
        mustDraw: ["NACO flow chart for genital ulcer syndrome", "Table differentiating syphilis, chancroid, herpes, LGV and donovanosis"],
        markSplit: [
          { part: "Differential diagnosis", marks: 4 },
          { part: "Investigations", marks: 2 },
          { part: "Syndromic management", marks: 4 },
        ],
        keywords: ["genital ulcer", "urethral discharge", "syndromic management", "NACO kit", "syphilis"],
      },
      {
        id: "dermatology-sti-genital-ulcer-urethral-discharge-t2",
        paper: "I",
        kind: "short-note",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question:
          "Write a short note on syndromic management of STI/RTI in India: rationale, advantages and disadvantages, colour-coded kits and the role of Suraksha clinics. [2+3+3+2]",
        openingLines: [
          "Syndromic case management identifies an STI syndrome from consistent symptoms and signs and treats it for all the organisms that commonly cause it, at the first visit.",
          "It is the national approach under NACP-V, delivered through Designated STI/RTI Clinics (Suraksha Clinics) with free pre-packed kits.",
        ],
        answer: [
          {
            heading: "Rationale",
            points: [
              "Mixed infections are common and clinical diagnosis is often wrong.",
              "Laboratories are not available in most primary settings; patients may not return for results.",
            ],
          },
          {
            heading: "Advantages and disadvantages",
            points: [
              "Advantages: same-day treatment, simple flow charts for non-specialists, cost-effective, breaks transmission early.",
              "Disadvantages: overtreatment and antimicrobial resistance, misses asymptomatic infection, poor for vaginal discharge in predicting cervicitis.",
            ],
          },
          {
            heading: "Colour-coded kits",
            points: [
              "Grey (Kit 1) urethral discharge; green (Kit 2) vaginitis; white (Kit 3) non-herpetic ulcer; blue (Kit 4) ulcer with penicillin allergy.",
              "Red (Kit 5) herpetic ulcer; yellow (Kit 6) PID; black (Kit 7) inguinal bubo.",
            ],
          },
          {
            heading: "Suraksha clinics and the 4 Cs",
            points: [
              "Free STI/RTI care, RPR and HIV testing linkage, counselling, condoms, partner treatment and reporting.",
              "4 Cs: compliance, condom promotion, counselling, contact tracing.",
            ],
          },
        ],
        mustDraw: ["Table of NACO colour-coded kits with syndrome and contents"],
        markSplit: [
          { part: "Rationale", marks: 2 },
          { part: "Advantages and disadvantages", marks: 3 },
          { part: "Kits", marks: 3 },
          { part: "Suraksha clinics and 4 Cs", marks: 2 },
        ],
        keywords: ["syndromic management", "Suraksha clinic", "NACO kits", "4 Cs", "NACP-V"],
      },
    ],
    references: [
      "National AIDS and STD Control Programme Phase V (2021-26) operational guidelines, NACO, MoHFW 2021",
      "India HIV Estimates 2023 technical report, NACO and ICMR-NIMS 2024",
      "WHO Guidelines for the management of symptomatic sexually transmitted infections, 2021",
      "WHO Updated recommendations for the treatment of Neisseria gonorrhoeae, Chlamydia trachomatis and Treponema pallidum, 2024",
      "CDC Sexually Transmitted Infections Treatment Guidelines, 2021",
      "Rook's Textbook of Dermatology, 10th edition, 2024",
      "Harrison's Principles of Internal Medicine, 22nd edition",
      "National Guidelines for HIV Care and Treatment, NACO 2021",
    ],
  },
];

export default topics;
