import type { Topic } from "../../lib/types";

const topics: Topic[] = [
  {
    id: "eye-ent-eyelid-lacrimal-disorders",
    title: "Eyelid and lacrimal disorders: stye, chalazion, blepharitis, dacryocystitis, dry eye",
    oneLiner:
      "Eyelid and lacrimal disorders are the commonest external eye problems in primary care - acute infection of the lash-follicle glands (**stye**), chronic granulomatous blockage of a meibomian gland (**chalazion**), chronic lid-margin inflammation (**blepharitis**), infection of an obstructed lacrimal sac (**dacryocystitis**) and tear-film failure (**dry eye**) - almost all managed with warm compresses, lid hygiene and lubricants, with referral reserved for orbital signs, recurrent lesions in the elderly and surgical correction.",
    frequency: "common",
    keywords: [
      "stye",
      "hordeolum externum",
      "hordeolum internum",
      "chalazion",
      "meibomian cyst",
      "blepharitis",
      "meibomian gland dysfunction",
      "dacryocystitis",
      "nasolacrimal duct obstruction",
      "Crigler massage",
      "DCR",
      "dacryocystorhinostomy",
      "preseptal cellulitis",
      "orbital cellulitis",
      "entropion",
      "ectropion",
      "trichiasis",
      "ptosis",
      "xanthelasma",
      "dry eye",
      "computer vision syndrome",
      "sebaceous gland carcinoma",
    ],
    sections: [
      {
        heading: "Applied anatomy: lid glands and lacrimal drainage",
        points: [
          "The lid has two lamellae - the **anterior lamella** (skin and orbicularis) and the **posterior lamella** (tarsal plate and conjunctiva) - separated at the margin by the grey line. [Kanski 10e]",
          "**Glands of Zeis** are sebaceous glands and **glands of Moll** are modified sweat glands, both opening into the lash follicles - infection here is the external stye. [Kanski 10e]",
          "**Meibomian glands** are 25-30 vertical sebaceous glands in the upper tarsus and about 20 in the lower, secreting the lipid layer that stops tear evaporation. [Kanski 10e]",
          "The **tear film** has a lipid layer (meibomian), an aqueous layer (main and accessory lacrimal glands) and a mucin layer (goblet cells) - failure of any layer causes dry eye. [TFOS DEWS II 2017]",
          "Tears drain through the **puncta and canaliculi** into the lacrimal sac, then down the nasolacrimal duct to open into the **inferior meatus** under the valve of Hasner. [Kanski 10e]",
          "The **valve of Hasner** is the last part of the duct to canalise, so a persistent membrane here causes congenital nasolacrimal duct obstruction. [Kanski 10e]",
          "The **orbital septum** runs from the orbital rim to the tarsus and is the barrier that separates preseptal from orbital cellulitis. [Kanski 10e]",
          "The **levator palpebrae superioris** (third nerve) lifts the lid and **Muller muscle** (sympathetic) adds 2 mm - which is why Horner syndrome gives only mild ptosis. [Kanski 10e]",
          "The orbicularis is supplied by the **facial nerve**, so Bell palsy causes lagophthalmos, paralytic ectropion and exposure keratopathy. [Kanski 10e]",
        ],
      },
      {
        heading: "Burden in India and programme context",
        points: [
          "Lid and adnexal disease make up roughly **one in ten** general ophthalmology outpatient visits, with stye, chalazion and blepharitis leading the list. [Kanski 10e]",
          "Hospital-based Indian studies report **dry eye in about 20-30 per cent of adults**, higher in north India with dry climate, dust and air pollution. [TFOS DEWS II 2017]",
          "Screen time after the COVID-19 lockdowns pushed **digital eye strain** symptoms above 50 per cent in Indian students and IT workers in several surveys. [AAO PPP Dry Eye 2023]",
          "WHO validated **India as having eliminated trachoma as a public health problem in 2024**, but trachomatous trichiasis surveillance and surgery continue under the programme. [WHO 2024]",
          "Under the **National Programme for Control of Blindness and Visual Impairment (NPCBVI)**, syringing of the lacrimal passage is mandatory before every cataract operation. [NPCBVI 2023]",
          "Untreated **chronic dacryocystitis is a reservoir for pneumococcus** and a recognised cause of post-cataract endophthalmitis in camp surgery. [Kanski 10e]",
          "In Indian series **sebaceous gland carcinoma forms about a third of eyelid malignancies**, far more than the 1-5 per cent seen in Western series. [Kanski 10e]",
          "**Congenital nasolacrimal duct obstruction** is symptomatic in about 5-20 per cent of newborns, and over 90 per cent resolve spontaneously by 12 months. [AAO PPP 2022]",
        ],
      },
      {
        heading: "Hordeolum (stye) and chalazion",
        points: [
          "**Hordeolum externum** is an acute staphylococcal abscess of a lash follicle with its Zeis or Moll gland - a tender red swelling that points on the skin at the lid margin. [Kanski 10e]",
          "**Hordeolum internum** is acute suppurative infection of a meibomian gland - more painful, deeper, and points on the conjunctival side of the tarsus. [Kanski 10e]",
          "Treat a stye with **warm compresses for 5-10 minutes three to four times a day** - most discharge spontaneously within a week. [Kanski 10e]",
          "**Epilation of the involved lash** lets a pointing external stye drain - never squeeze a stye, as facial veins drain to the cavernous sinus. [Kanski 10e]",
          "Topical **chloramphenicol 1 per cent eye ointment twice daily for 5-7 days** is reserved for associated blepharitis or conjunctivitis, and does not speed resolution of the stye itself. [Kanski 10e]",
          "Give **oral amoxicillin-clavulanate 625 mg thrice daily for 5-7 days** only when a stye spreads as preseptal cellulitis. [Kanski 10e]",
          "**Recurrent styes** call for a refraction, a check for diabetes, and treatment of underlying blepharitis and seborrhoea. [Kanski 10e]",
          "**Chalazion** is a chronic sterile lipogranulomatous inflammation of a blocked meibomian gland - a painless, firm, non-tender nodule away from the lid margin. [Kanski 10e]",
          "Conservative care of chalazion - **warm compress and lid massage twice daily for 4-6 weeks** - resolves about half, especially small recent lesions. [AAO PPP Blepharitis 2023]",
          "**Intralesional triamcinolone 40 mg/mL, 0.1-0.2 mL**, flattens a chalazion in most cases, but can leave skin depigmentation in dark skin, so inject via the conjunctiva. [Kanski 10e]",
          "**Incision and curettage** is done under local anaesthesia with a chalazion clamp through a **vertical conjunctival incision**, parallel to the meibomian glands. [Kanski 10e]",
          "A **recurrent chalazion at the same site in an elderly patient** must be biopsied - sebaceous gland carcinoma masquerades as chalazion and as unilateral chronic blepharitis. [Kanski 10e]",
          "In a child a large chalazion or haemangioma that **covers the visual axis or induces astigmatism** can cause amblyopia and needs early removal. [Nelson 22e]",
        ],
      },
      {
        heading: "Blepharitis and meibomian gland dysfunction",
        points: [
          "**Anterior blepharitis** involves the lash base - staphylococcal (hard crusts, collarettes, madarosis) or seborrhoeic (greasy scales with scalp dandruff). [AAO PPP Blepharitis 2023]",
          "**Demodex blepharitis** shows cylindrical dandruff (sleeves) around the lashes and is commoner with age, rosacea and diabetes. [AAO PPP Blepharitis 2023]",
          "**Posterior blepharitis (meibomian gland dysfunction)** shows capped gland orifices, frothy tears and toothpaste-like expressed secretions, and is the commonest cause of evaporative dry eye. [TFOS DEWS II 2017]",
          "Tell the patient blepharitis is **chronic and controlled, not cured** - stopping lid hygiene brings symptoms back within weeks. [AAO PPP Blepharitis 2023]",
          "**Lid hygiene:** warm compress for 5-10 minutes, lid massage, then scrub the lid margin with diluted baby shampoo (1:10) or lid wipes, twice daily for a month, then daily. [AAO PPP Blepharitis 2023]",
          "Apply **azithromycin 1 per cent or chloramphenicol ointment to the lid margin at night for 2-4 weeks** when lid hygiene alone fails in anterior blepharitis. [AAO PPP Blepharitis 2023]",
          "For moderate MGD or ocular rosacea give **oral doxycycline 100 mg once daily for 6-12 weeks** (or 40-50 mg sub-antimicrobial dose) - it acts by reducing meibum lipase activity. [AAO PPP Blepharitis 2023]",
          "Avoid tetracyclines in **pregnancy and children under 8 years** - use oral erythromycin or azithromycin instead. [AAO PPP Blepharitis 2023]",
          "**Tea tree oil lid scrubs** reduce Demodex, and **lotilaner 0.25 per cent drops** twice daily for 6 weeks were approved in 2023 for Demodex blepharitis. [AAO PPP Blepharitis 2023]",
          "Treat associated **seborrhoeic dermatitis and rosacea** at the same time, or the lid disease keeps relapsing. [Rook 10e]",
        ],
      },
      {
        heading: "Dacryocystitis and nasolacrimal duct obstruction",
        points: [
          "**Epiphora** is overflow of tears from failed drainage, while lacrimation is overproduction - the regurgitation test separates them. [Kanski 10e]",
          "**ROPLAS (regurgitation on pressure over the lacrimal sac)** of mucopus is diagnostic of chronic dacryocystitis with nasolacrimal duct block. [Kanski 10e]",
          "**Syringing** with saline through the lower punctum confirms patency - fluid in the throat means patent, regurgitation through the upper punctum means duct block. [Kanski 10e]",
          "**Acute dacryocystitis** is a tense, red, very tender swelling below the medial canthal tendon, usually on a background of chronic obstruction. [Kanski 10e]",
          "Treat acute dacryocystitis with **warm compresses and oral amoxicillin-clavulanate 625 mg thrice daily for 7-10 days**, or IV cefuroxime if systemically unwell. [Kanski 10e]",
          "**Avoid incision** unless an abscess is pointing, because a skin incision can leave a **lacrimal fistula**; never syringe or probe in the acute phase. [Kanski 10e]",
          "Definitive care after the infection settles is **dacryocystorhinostomy (DCR)**, external or endoscopic, which bypasses the blocked duct into the middle meatus. [Kanski 10e]",
          "**Dacryocystectomy** is reserved for the elderly or unfit, and for suspected sac tumours, since it leaves permanent watering. [Kanski 10e]",
          "**Congenital NLDO** presents with watering and sticky discharge from the first weeks of life, with a quiet white eye and no photophobia. [Nelson 22e]",
          "Teach **Crigler (lacrimal sac) massage** - firm downward pressure over the sac with the index finger, 10 strokes four times a day - and clean the lids with boiled cooled water. [AAO PPP 2022]",
          "Give topical antibiotic drops only for episodes of **purulent discharge**, not continuously. [AAO PPP 2022]",
          "Refer for **probing at about 12 months** if watering persists; probing succeeds in about 90 per cent at this age, with intubation or balloon dacryoplasty for failures. [AAO PPP 2022]",
          "A **bluish swelling below the medial canthus at birth** is a dacryocystocele - refer early, as it can become infected or obstruct the nasal airway. [Nelson 22e]",
          "**Watering with photophobia and a large cornea in an infant** is congenital glaucoma until proved otherwise, not NLDO - refer the same week. [Nelson 22e]",
        ],
      },
      {
        heading: "Preseptal versus orbital cellulitis",
        points: [
          "**Preseptal (periorbital) cellulitis** is infection anterior to the orbital septum, usually from a stye, insect bite, skin wound or dacryocystitis. [Kanski 10e]",
          "**Orbital cellulitis** lies behind the septum and in children arises mostly from **ethmoid sinusitis** - it threatens vision and life. [Kanski 10e]",
          "The four signs of orbital involvement are **proptosis, painful restricted eye movements, reduced vision and a relative afferent pupillary defect**. [Kanski 10e]",
          "Chemosis, fever and systemic toxicity favour orbital disease, while a white eye with full painless movement favours preseptal cellulitis. [Kanski 10e]",
          "Treat mild preseptal cellulitis in an older child or adult with **oral amoxicillin-clavulanate (adult 625 mg thrice daily; child 25-45 mg/kg/day in divided doses) for 7-10 days** with review at 24-48 hours. [NICE CKS Cellulitis 2024]",
          "**Admit preseptal cellulitis** in children under 1 year, in the systemically unwell, and when it fails to improve in 48 hours. [Nelson 22e]",
          "Orbital cellulitis needs admission, **IV ceftriaxone plus vancomycin (add metronidazole if intracranial or dental source)**, and contrast CT of orbits and sinuses. [Kanski 10e]",
          "**Subperiosteal or orbital abscess**, worsening vision or no response in 48 hours needs surgical drainage with ENT. [Scott-Brown 8e]",
          "Bilateral signs, third, fourth and sixth nerve palsies and reduced sensation over V1 suggest **cavernous sinus thrombosis** - a neurosurgical emergency. [Kanski 10e]",
          "In diabetics with ketoacidosis and in post-COVID patients, black nasal crusts with orbital signs mean **rhino-orbital mucormycosis** - start amphotericin and refer immediately. [ICMR 2021]",
        ],
      },
      {
        heading: "Lid malposition, ptosis, xanthelasma and lid tumours",
        points: [
          "**Entropion** is in-turning of the lid margin - involutional in the elderly lower lid, cicatricial in the upper lid after trachoma, chemical burns or Stevens-Johnson syndrome. [Kanski 10e]",
          "**Trichiasis** is misdirected lashes from a normal lid position - it abrades the cornea and needs epilation, electrolysis or **bilamellar tarsal rotation** for trachomatous trichiasis. [WHO 2024]",
          "**Ectropion** is out-turning of the lid - involutional, paralytic (Bell palsy), cicatricial (burns) or mechanical - and presents with epiphora and exposure. [Kanski 10e]",
          "Temporise entropion with **lid taping and lubricants**, but the definitive treatment of both entropion and ectropion is surgical lid tightening. [Kanski 10e]",
          "In **Bell palsy with lagophthalmos**, give lubricating drops by day, ointment and lid taping at night, and refer if the cornea stains. [NICE CKS Bell palsy 2024]",
          "**Congenital ptosis** from levator dystrophy needs early surgery if the lid covers the pupil, to prevent **deprivation amblyopia**. [Nelson 22e]",
          "**Aponeurotic (involutional) ptosis** is the commonest acquired type in the elderly, with a high lid crease and good levator function. [Kanski 10e]",
          "**Variable, fatigable ptosis** worse in the evening with diplopia suggests ocular myasthenia - do the ice-pack test and check acetylcholine receptor antibodies. [Harrison 22e]",
          "**Ptosis with a dilated pupil and a down-and-out eye** is a third nerve palsy from a posterior communicating aneurysm until proved otherwise - emergency CT angiography. [Harrison 22e]",
          "**Xanthelasma** are soft yellow plaques on the medial lids; about half of patients have dyslipidaemia, so check a fasting lipid profile and cardiovascular risk. [Rook 10e]",
          "Xanthelasma removal (excision, trichloroacetic acid, laser) is cosmetic and **recurs in about 40 per cent**. [Rook 10e]",
          "**Basal cell carcinoma** is the commonest lid malignancy - a pearly nodule with rolled edges and telangiectasia on the lower lid or medial canthus. [Kanski 10e]",
          "Suspect malignancy when a lid lesion shows **loss of lashes, ulceration, bleeding or destruction of the lid margin**, and refer for biopsy. [Kanski 10e]",
        ],
      },
      {
        heading: "Dry eye and computer vision syndrome",
        points: [
          "**TFOS DEWS II (2017)** defines dry eye as a multifactorial disease of the ocular surface with loss of tear-film homeostasis, tear hyperosmolarity, inflammation and neurosensory abnormality. [TFOS DEWS II 2017]",
          "Dry eye is **aqueous-deficient** (Sjogren and non-Sjogren) or **evaporative** (meibomian gland dysfunction, low blink rate), and most patients have both. [TFOS DEWS II 2017]",
          "Risk factors: **age, female sex, screen use, air conditioning, contact lenses, diabetes, refractive surgery** and drugs - antihistamines, antidepressants, beta blockers, isotretinoin and preserved glaucoma drops. [TFOS DEWS II 2017]",
          "Symptoms are **grittiness, burning, fluctuating vision and paradoxical watering**, worse in the evening and with reading or screens. [AAO PPP Dry Eye 2023]",
          "Tests: **tear break-up time under 10 seconds**, Schirmer I without anaesthesia **under 5 mm in 5 minutes**, and punctate fluorescein staining of the inferior cornea. [TFOS DEWS II 2017]",
          "Step 1: education, environmental change, lid hygiene and **preservative-free carboxymethylcellulose 0.5 per cent or sodium hyaluronate 0.1 per cent drops four to six times a day**. [TFOS DEWS II 2017]",
          "Use **preservative-free drops if instilling more than four times a day**, since benzalkonium chloride itself damages the epithelium. [AAO PPP Dry Eye 2023]",
          "Step 2 (by ophthalmologist): **topical cyclosporine 0.05 per cent twice daily**, a short course of loteprednol, punctal plugs, and oral doxycycline for MGD. [TFOS DEWS II 2017]",
          "Dry mouth, joint pain and dry eye together warrant **anti-Ro/La antibodies** for Sjogren syndrome. [Harrison 22e]",
          "**Computer vision syndrome (digital eye strain)** comes from a blink rate that falls from about 15 to about 5 per minute at screens, plus uncorrected refractive error and poor posture. [AAO PPP Dry Eye 2023]",
          "Teach the **20-20-20 rule** - every 20 minutes look at something 20 feet away for 20 seconds - and conscious full blinking. [AAO PPP Dry Eye 2023]",
          "Ergonomics: screen **50-70 cm away with its top at or just below eye level**, glare reduced, and room humidity maintained. [AAO PPP Dry Eye 2023]",
          "Correct **presbyopia and small refractive errors** in screen workers - uncorrected astigmatism is a common hidden cause of asthenopia. [Kanski 10e]",
        ],
      },
      {
        heading: "Family physician role and referral",
        points: [
          "Evert the upper lid, check **visual acuity and pupils in every red or swollen eye** - these two findings separate a lid problem from an orbital one. [Kanski 10e]",
          "Manage stye, chalazion, blepharitis, congenital NLDO, mild preseptal cellulitis and mild dry eye in primary care with **a written lid-hygiene plan**. [Kanski 10e]",
          "**Never prescribe topical steroid drops** for a red or swollen eye without slit-lamp examination - they worsen herpes and fungal keratitis and raise pressure. [Kanski 10e]",
          "Refer the **same day** for orbital signs, reduced vision, RAPD, suspected mucormycosis or a painful ptosis with pupil involvement. [Kanski 10e]",
          "Refer **routinely** for chalazion not resolving after 6 weeks, chronic dacryocystitis for DCR, NLDO persisting beyond 12 months, and lid malposition for surgery. [AAO PPP 2022]",
          "Refer **urgently for biopsy** any recurrent chalazion or unilateral persistent blepharitis in an adult over 50, and any lid lesion with lash loss or ulceration. [Kanski 10e]",
          "Before a cataract referral, **do or arrange lacrimal syringing** and treat any chronic dacryocystitis first. [NPCBVI 2023]",
          "Use school and workplace visits to teach **screen ergonomics and the 20-20-20 rule**, and link children to NPCBVI school eye screening for free spectacles. [NPCBVI 2023]",
        ],
      },
    ],
    tables: [
      {
        heading: "Differential diagnosis of a lid swelling",
        columns: ["Condition", "Site and gland", "Pain", "Distinguishing sign", "First-line care"],
        rows: [
          ["Hordeolum externum", "Lash follicle - Zeis or Moll gland", "Painful, tender", "Points at lid margin around a lash", "Warm compress, epilate lash"],
          ["Hordeolum internum", "Meibomian gland, acute infection", "Very painful", "Points on the conjunctival side", "Warm compress; oral antibiotic if cellulitis"],
          ["Chalazion", "Meibomian gland, sterile granuloma", "Painless", "Firm nodule away from margin", "Compress and massage 4-6 weeks, then I and C"],
          ["Acute dacryocystitis", "Lacrimal sac below medial canthal tendon", "Very tender", "ROPLAS once settled; epiphora", "Oral co-amoxiclav, later DCR"],
          ["Preseptal cellulitis", "Lid tissue in front of the septum", "Tender", "Full eye movement, normal vision", "Oral co-amoxiclav, review 48 h"],
          ["Orbital cellulitis", "Behind the septum", "Pain on eye movement", "Proptosis, restricted movement, RAPD", "Admit, IV antibiotics, CT"],
          ["Sebaceous gland carcinoma", "Meibomian or Zeis gland", "Painless", "Recurrent chalazion, lash loss in elderly", "Biopsy - urgent referral"],
        ],
      },
      {
        heading: "Chandler classification of orbital infection",
        columns: ["Stage", "Name", "Key findings", "Management"],
        rows: [
          ["I", "Preseptal cellulitis", "Lid oedema, normal vision and eye movement", "Oral antibiotics; admit if under 1 year or unwell"],
          ["II", "Orbital cellulitis", "Proptosis, chemosis, painful restricted movement", "Admit, IV antibiotics, contrast CT"],
          ["III", "Subperiosteal abscess", "Globe displaced away from the abscess", "IV antibiotics; drainage if large or vision falls"],
          ["IV", "Orbital abscess", "Severe proptosis, ophthalmoplegia, vision loss", "Urgent surgical drainage"],
          ["V", "Cavernous sinus thrombosis", "Bilateral signs, cranial nerve palsies, sepsis", "ICU, IV antibiotics, neurosurgery input"],
        ],
      },
    ],
    redFlags: [
      "Lid swelling with proptosis, painful or restricted eye movement, reduced vision or RAPD - orbital cellulitis.",
      "Preseptal cellulitis in a child under 1 year, or any lid infection with systemic toxicity.",
      "Black eschar on the nose or palate with lid swelling in a diabetic - rhino-orbital mucormycosis.",
      "Recurrent chalazion at the same site or unilateral chronic blepharitis in an adult over 50 - exclude sebaceous carcinoma.",
      "Lid lesion with loss of lashes, ulceration, bleeding or distortion of the lid margin.",
      "Ptosis with a dilated pupil and diplopia, or with headache - third nerve palsy from aneurysm.",
      "Watering eye in an infant with photophobia, a hazy or large cornea - congenital glaucoma.",
      "Lagophthalmos with corneal staining or reduced vision after facial palsy.",
    ],
    pearls: [
      "Stye points on the skin at the lash line; chalazion is painless and sits away from the margin - pain is the single best clinical discriminator.",
      "Chalazion incision is vertical on the conjunctival side (parallel to the meibomian glands); stye drainage is horizontal on the skin side.",
      "A recurrent chalazion in the elderly is sebaceous gland carcinoma until the histopathology says otherwise.",
      "ROPLAS positive plus syringing regurgitation equals nasolacrimal duct block - and it must be fixed before cataract surgery.",
      "Crigler massage is downward pressure over the sac to rupture the membrane at the valve of Hasner; probing at about 12 months if it fails.",
      "Proptosis, painful ophthalmoplegia, reduced vision and RAPD - any one moves the diagnosis from preseptal to orbital cellulitis.",
      "Blepharitis is controlled, not cured - lid hygiene is lifelong.",
      "Use preservative-free lubricants when drops are needed more than four times a day.",
      "The 20-20-20 rule and a screen top at eye level are the two sentences that cover computer vision syndrome.",
      "Half of patients with xanthelasma have normal lipids, but all deserve a lipid profile and CVD risk assessment.",
    ],
    mcqs: [
      {
        id: "eye-ent-eyelid-lacrimal-disorders-q1",
        stem: "A 68-year-old woman has had a painless nodule on the left upper lid excised as a chalazion twice in the past year; it has recurred at the same site and she has lost some lashes over it. What is the most appropriate next step?",
        options: [
          "Intralesional triamcinolone injection",
          "Repeat incision and curettage with warm compresses",
          "Full-thickness biopsy for histopathology",
          "Oral doxycycline for 12 weeks",
        ],
        answer: 2,
        explanation:
          "A recurrent chalazion at the same site in an elderly patient, especially with madarosis, must be biopsied to exclude sebaceous gland carcinoma, which forms about a third of lid malignancies in India. Steroid injection, repeat curettage or doxycycline would all delay diagnosis of a potentially lethal tumour.",
        difficulty: "moderate",
      },
      {
        id: "eye-ent-eyelid-lacrimal-disorders-q2",
        stem: "A 6-week-old baby has had a watering left eye with sticky discharge since birth. The cornea is clear, of normal size, and there is no photophobia. What is the best initial management?",
        options: [
          "Lacrimal sac massage with lid hygiene and review",
          "Immediate probing of the nasolacrimal duct",
          "Continuous topical antibiotic drops for 6 weeks",
          "Dacryocystorhinostomy",
        ],
        answer: 0,
        explanation:
          "Congenital nasolacrimal duct obstruction resolves spontaneously in over 90 per cent by 12 months, so Crigler massage and lid cleaning are first line. Probing is kept for persistence around 12 months, continuous antibiotics are unnecessary, and DCR is not a first procedure in infancy.",
        difficulty: "easy",
      },
      {
        id: "eye-ent-eyelid-lacrimal-disorders-q3",
        stem: "A 7-year-old with a week of cold develops fever and a swollen right upper lid. Examination shows proptosis, chemosis and pain on looking up, with visual acuity 6/18. Which is the most appropriate management?",
        options: [
          "Oral amoxicillin-clavulanate and review in 48 hours",
          "Warm compresses and topical chloramphenicol",
          "Oral antihistamine and cold compress",
          "Admission, IV ceftriaxone with vancomycin, and contrast CT orbit and sinuses",
        ],
        answer: 3,
        explanation:
          "Proptosis, painful restricted movement and reduced vision mean orbital (postseptal) cellulitis, usually from ethmoid sinusitis, needing admission, IV antibiotics and CT to look for an abscess. Oral antibiotics suit only mild preseptal cellulitis; topical treatment and antihistamines ignore a vision- and life-threatening infection.",
        difficulty: "moderate",
      },
      {
        id: "eye-ent-eyelid-lacrimal-disorders-q4",
        stem: "In which direction should the incision be made when a chalazion is treated by incision and curettage from the conjunctival side?",
        options: [
          "Horizontal, parallel to the lid margin",
          "Vertical, perpendicular to the lid margin",
          "Oblique, along the lid crease",
          "Circumferential around the lesion",
        ],
        answer: 1,
        explanation:
          "Meibomian glands run vertically in the tarsal plate, so a vertical conjunctival incision avoids cutting neighbouring glands and notching the lid. A horizontal incision is used on the skin side for an external stye; oblique and circumferential incisions damage more glands.",
        difficulty: "easy",
      },
      {
        id: "eye-ent-eyelid-lacrimal-disorders-q5",
        stem: "A 26-year-old software engineer complains of burning, gritty eyes that worsen by evening. Tear break-up time is 6 seconds and Schirmer test is 12 mm in 5 minutes. Which initial measure is most appropriate?",
        options: [
          "Topical dexamethasone drops four times a day",
          "Punctal occlusion with silicone plugs",
          "Oral pilocarpine 5 mg three times daily",
          "Blink training, 20-20-20 rule, screen ergonomics and preservative-free lubricants",
        ],
        answer: 3,
        explanation:
          "A short break-up time with normal Schirmer points to evaporative dry eye from a low blink rate at screens, so first-line care is education, the 20-20-20 rule, ergonomics and lubricants. Topical steroids risk glaucoma and infection, punctal plugs are step 2, and pilocarpine is for Sjogren aqueous deficiency.",
        difficulty: "moderate",
      },
    ],
    theory: [
      {
        id: "eye-ent-eyelid-lacrimal-disorders-t1",
        paper: "II",
        kind: "long",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question:
          "Enumerate the causes of a swelling of the eyelid. Differentiate hordeolum externum, hordeolum internum and chalazion. Outline the management of chalazion, including a recurrent chalazion in an elderly patient. [3+3+4]",
        openingLines: [
          "Eyelid swellings are the commonest external eye complaint in family practice and arise from the lid glands, the lacrimal sac, the orbit or systemic oedema.",
          "Chalazion is a chronic sterile lipogranulomatous inflammation of a blocked meibomian gland, whereas a hordeolum is an acute staphylococcal abscess of a lid gland.",
        ],
        answer: [
          {
            heading: "Causes of lid swelling",
            points: [
              "Inflammatory: hordeolum externum and internum, chalazion, blepharitis, insect bite, allergic and contact dermatitis, angioedema.",
              "Infective spread: preseptal and orbital cellulitis, acute dacryocystitis, herpes zoster ophthalmicus.",
              "Systemic oedema: nephrotic syndrome, acute nephritis, hypothyroidism, SVC obstruction.",
              "Neoplastic: xanthelasma, papilloma, BCC, sebaceous gland carcinoma, haemangioma in infants.",
              "Traumatic: lid haematoma, orbital fracture with emphysema.",
            ],
          },
          {
            heading: "Differentiating features",
            points: [
              "Hordeolum externum: Zeis or Moll gland, painful, points at the lash line on the skin.",
              "Hordeolum internum: meibomian gland, acute, very painful, points on the conjunctival side.",
              "Chalazion: meibomian gland, chronic, painless, firm, away from the margin, sterile lipogranuloma.",
            ],
          },
          {
            heading: "Management of chalazion",
            points: [
              "Warm compress and lid massage twice daily for 4-6 weeks; treat blepharitis and rosacea.",
              "Intralesional triamcinolone 40 mg/mL, 0.1-0.2 mL via the conjunctiva for small persistent lesions.",
              "Incision and curettage under local anaesthesia with a chalazion clamp, vertical conjunctival incision; pad for a few hours.",
              "Oral doxycycline 100 mg daily for 6-12 weeks for multiple recurrent chalazia with MGD.",
            ],
          },
          {
            heading: "Recurrent chalazion in the elderly",
            points: [
              "Recurrence at the same site, madarosis or yellowish tarsal thickening suggests sebaceous gland carcinoma.",
              "Send all curetted material for histopathology; full-thickness biopsy with map biopsies of the conjunctiva.",
              "Refer to an oculoplastic surgeon; wide excision with frozen-section control.",
            ],
          },
        ],
        mustDraw: ["Sagittal section of the eyelid showing Zeis, Moll and meibomian glands with the sites of stye and chalazion"],
        markSplit: [
          { part: "Causes of lid swelling", marks: 3 },
          { part: "Differentiation of stye and chalazion", marks: 3 },
          { part: "Management including recurrent chalazion", marks: 4 },
        ],
        keywords: ["chalazion", "hordeolum", "stye", "sebaceous gland carcinoma", "incision and curettage"],
      },
      {
        id: "eye-ent-eyelid-lacrimal-disorders-t2",
        paper: "II",
        kind: "short-note",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question:
          "Write a short note on dacryocystitis: clinical features and diagnosis, management of acute and chronic dacryocystitis, and congenital nasolacrimal duct obstruction. [3+4+3]",
        openingLines: [
          "Dacryocystitis is infection of the lacrimal sac secondary to obstruction of the nasolacrimal duct.",
          "It matters in India because chronic dacryocystitis is a source of post-cataract endophthalmitis, so NPCBVI mandates lacrimal syringing before cataract surgery.",
        ],
        answer: [
          {
            heading: "Clinical features and diagnosis",
            points: [
              "Chronic: epiphora, mucopurulent discharge, swelling below the medial canthal tendon, ROPLAS positive.",
              "Acute: tense, red, very tender swelling over the sac with fever; may point as an abscess or fistula.",
              "Syringing: regurgitation through the opposite punctum confirms duct block; dacryocystography or CT for tumour or trauma.",
            ],
          },
          {
            heading: "Management of acute dacryocystitis",
            points: [
              "Warm compresses, analgesics and oral amoxicillin-clavulanate 625 mg thrice daily for 7-10 days; IV cefuroxime if toxic.",
              "No syringing or probing in the acute phase; incise only a pointing abscess.",
            ],
          },
          {
            heading: "Management of chronic dacryocystitis",
            points: [
              "Dacryocystorhinostomy (external or endoscopic) - treatment of choice.",
              "Dacryocystectomy in the elderly, unfit or with suspected tumour.",
              "Complete treatment before any intraocular surgery.",
            ],
          },
          {
            heading: "Congenital nasolacrimal duct obstruction",
            points: [
              "Membrane at the valve of Hasner; watering and discharge in a white eye from the first weeks.",
              "Crigler massage 10 strokes four times daily, lid hygiene, antibiotic drops only for purulent episodes.",
              "Probing at about 12 months if persistent; intubation or balloon dacryoplasty for failure.",
              "Exclude congenital glaucoma (photophobia, large hazy cornea) and dacryocystocele.",
            ],
          },
        ],
        mustDraw: ["Diagram of the lacrimal drainage system from puncta to inferior meatus with the valve of Hasner marked"],
        markSplit: [
          { part: "Clinical features and diagnosis", marks: 3 },
          { part: "Acute and chronic management", marks: 4 },
          { part: "Congenital NLDO", marks: 3 },
        ],
        keywords: ["dacryocystitis", "ROPLAS", "syringing", "DCR", "Crigler massage", "NLDO"],
      },
    ],
    references: [
      "Kanski's Clinical Ophthalmology, 10th edition, 2024",
      "TFOS DEWS II Report, Ocular Surface 2017",
      "American Academy of Ophthalmology Preferred Practice Pattern: Blepharitis 2023 and Dry Eye Syndrome 2023",
      "American Academy of Ophthalmology Preferred Practice Pattern: Pediatric Eye Evaluations 2022",
      "NICE Clinical Knowledge Summaries: Cellulitis - acute, and Bell palsy, 2024",
      "National Programme for Control of Blindness and Visual Impairment operational guidelines, MoHFW 2023",
      "Nelson Textbook of Pediatrics, 22nd edition",
    ],
  },
  {
    id: "eye-ent-corneal-ulcer-ocular-trauma",
    title: "Corneal ulcer and ocular trauma",
    oneLiner:
      "A **corneal ulcer (infective keratitis)** is an epithelial defect with underlying stromal infiltrate caused by bacteria, fungi, herpes simplex or acanthamoeba - in India most often **fungal after vegetative trauma in farmers** - and together with ocular trauma (mechanical, chemical, thermal) it is the leading cause of **monocular corneal blindness**, preventable by prompt fluorescein diagnosis, the right antimicrobial, avoidance of steroids and home remedies, immediate irrigation of chemical injuries and shielding of an open globe.",
    frequency: "common",
    keywords: [
      "corneal ulcer",
      "infective keratitis",
      "microbial keratitis",
      "fungal keratitis",
      "natamycin",
      "voriconazole",
      "fortified antibiotics",
      "herpes simplex keratitis",
      "dendritic ulcer",
      "acanthamoeba keratitis",
      "fluorescein staining",
      "hypopyon",
      "ocular trauma",
      "BETT",
      "open globe",
      "chemical injury",
      "Roper-Hall",
      "hyphaema",
      "corneal foreign body",
      "Seidel test",
    ],
    sections: [
      {
        heading: "Definitions and burden in India",
        points: [
          "**Infective keratitis** is inflammation of the cornea from microbial invasion, seen as an epithelial defect staining with fluorescein over a white stromal infiltrate. [Kanski 10e]",
          "In the **National Blindness and Visual Impairment Survey 2015-19**, corneal opacity was the second commonest cause of blindness in people aged 50 and above, after cataract. [NPCBVI 2019]",
          "India records an estimated **over two lakh new corneal ulcers every year**, and corneal blindness falls mostly on young working-age adults in agriculture. [Kanski 10e]",
          "In South India **fungal keratitis makes up about 40-50 per cent** of culture-positive ulcers, mainly **Fusarium and Aspergillus**, against under 5 per cent in temperate countries. [Kanski 10e]",
          "The classic story is **injury with a paddy leaf, sugarcane or twig** during harvest, followed by self-treatment and delay. [Kanski 10e]",
          "**Contact lens wear** is now the leading risk factor for bacterial (Pseudomonas) and acanthamoeba keratitis in urban India. [AAO PPP Keratitis 2023]",
          "Eye injuries cause an estimated **one in five cases of monocular blindness** in India, with peaks during harvest, Diwali (firecrackers) and Holi (colours). [NPCBVI 2023]",
          "**Alkali injury from lime (chuna)** is a characteristic Indian chemical injury, from lime packets, whitewash and construction work. [Kanski 10e]",
          "India depends on **corneal donation through eye banks** for keratoplasty, and demand far exceeds supply despite the National Eye Donation Fortnight each August-September. [NPCBVI 2023]",
        ],
      },
      {
        heading: "Types of infective keratitis and their clues",
        points: [
          "**Bacterial keratitis** (Staphylococcus, Streptococcus pneumoniae, Pseudomonas) progresses in hours, with a well-defined dense infiltrate, lid oedema, mucopurulent discharge and a mobile hypopyon. [Kanski 10e]",
          "**Pseudomonas** in contact lens wearers gives a rapidly enlarging ring ulcer with greenish discharge that can perforate within 48 hours. [Kanski 10e]",
          "**Fungal keratitis** follows vegetative trauma and progresses over days, with a dry raised greyish-white slough, **feathery margins and satellite lesions**. [Kanski 10e]",
          "Other fungal signs are an **immune ring, endothelial plaque and a thick immobile hypopyon**, often with symptoms milder than the signs. [Kanski 10e]",
          "**Herpes simplex epithelial keratitis** produces a branching **dendritic ulcer with terminal bulbs** and reduced corneal sensation, often after fever or stress. [Kanski 10e]",
          "HSV **stromal and endothelial keratitis** (disciform) are immune-mediated and recur, each attack scarring the cornea further. [AAO PPP Keratitis 2023]",
          "**Herpes zoster ophthalmicus** with a vesicle on the tip of the nose (**Hutchinson sign**, nasociliary nerve) predicts eye involvement and needs oral antivirals and an eye referral. [Kanski 10e]",
          "**Acanthamoeba keratitis** occurs in contact lens wearers exposed to tap, swimming-pool or well water, with **pain out of proportion** to the signs and radial perineuritis. [AAO PPP Keratitis 2023]",
          "A late acanthamoeba ring infiltrate is easily misdiagnosed as herpes or fungus, so a lens wearer with a non-healing ulcer must be scraped for cysts. [Kanski 10e]",
          "Non-infective differentials are **neurotrophic ulcer** (diabetes, post-zoster), **exposure keratopathy** (facial palsy, ICU) and marginal keratitis from staphylococcal hypersensitivity. [Kanski 10e]",
        ],
      },
      {
        heading: "Evaluation: fluorescein and microbiology",
        points: [
          "Record **visual acuity in each eye first** - it is the medicolegal baseline and the best prognostic marker. [Kanski 10e]",
          "**Fluorescein 2 per cent** (or a moistened strip) stains any epithelial defect bright green under cobalt-blue light, outlining abrasions, dendrites and ulcers. [Kanski 10e]",
          "**Seidel test:** concentrated fluorescein over a wound turns dilute green in a stream if aqueous is leaking - a positive test means an open globe or perforation. [Kanski 10e]",
          "Record the **size and depth of the infiltrate, hypopyon height and corneal sensation** at each visit to judge response. [AAO PPP Keratitis 2023]",
          "**Corneal scraping** with a sterile 15 blade or 26G needle under topical anaesthesia goes for Gram stain, **10 per cent KOH mount** and culture before treatment starts. [AAO PPP Keratitis 2023]",
          "The **KOH mount or calcofluor white** shows fungal hyphae within minutes and lets the right antifungal be started the same day. [Kanski 10e]",
          "Culture on **blood agar, chocolate agar and Sabouraud dextrose agar**, and on non-nutrient agar with E. coli overlay when acanthamoeba is suspected. [AAO PPP Keratitis 2023]",
          "Scraping is indicated for ulcers that are **central, larger than 2 mm, deep, with hypopyon, atypical or not responding** to empirical therapy. [AAO PPP Keratitis 2023]",
          "Do a **B-scan ultrasound** when a dense hypopyon hides the posterior segment, to exclude endophthalmitis. [Kanski 10e]",
          "Check **blood sugar and HIV status** in recurrent or severe keratitis - both predispose to fungal and aggressive infection. [Kanski 10e]",
        ],
      },
      {
        heading: "Management of corneal ulcer",
        points: [
          "**Fungal keratitis:** natamycin 5 per cent suspension one drop hourly day and night for the first 48-72 hours, then two-hourly, continued for 3-4 weeks after healing. [Kanski 10e]",
          "**MUTT I showed natamycin better than voriconazole** for filamentous fungal ulcers, especially Fusarium, with less perforation. [Kanski 10e]",
          "Add **voriconazole 1 per cent drops hourly** for Aspergillus or deep ulcers not responding; **MUTT II found no benefit from adding oral voriconazole**. [Kanski 10e]",
          "**Bacterial keratitis:** fortified cefazolin 5 per cent (50 mg/mL) plus fortified tobramycin 1.3 per cent (14 mg/mL) hourly around the clock for 48 hours, then taper by response. [AAO PPP Keratitis 2023]",
          "For small peripheral bacterial ulcers, **moxifloxacin 0.5 per cent monotherapy hourly** is an acceptable alternative to fortified drops. [AAO PPP Keratitis 2023]",
          "**HSV epithelial keratitis:** ganciclovir 0.15 per cent gel five times a day until healed, then three times a day for 7 days, or aciclovir 3 per cent ointment five times a day for 14 days. [Kanski 10e]",
          "Oral **aciclovir 400 mg five times daily for 7-10 days** is an effective alternative, and **400 mg twice daily for a year** cuts recurrence by about half. [AAO PPP Keratitis 2023]",
          "**Acanthamoeba keratitis:** polyhexamethylene biguanide 0.02 per cent or chlorhexidine 0.02 per cent hourly, tapered over 6-12 months, under a cornea specialist. [AAO PPP Keratitis 2023]",
          "Add a cycloplegic - **atropine 1 per cent twice daily or homatropine 2 per cent three times daily** - to relieve ciliary spasm and prevent synechiae. [Kanski 10e]",
          "Give **oral analgesics** and, for a deep ulcer, oral acetazolamide 250 mg three times daily if pressure is high; **never pad an infected eye**. [Kanski 10e]",
          "For impending or actual perforation use **cyanoacrylate glue with a bandage lens**, or therapeutic penetrating keratoplasty. [Kanski 10e]",
          "Where same-day specialist review is impossible and vegetative trauma is the history, the family physician may start **natamycin 5 per cent hourly plus moxifloxacin and atropine** after a KOH smear, and refer within 24 hours. [NPCBVI 2023]",
        ],
      },
      {
        heading: "Why topical steroids and home remedies are dangerous",
        points: [
          "**Topical steroids enhance fungal growth**, and in HSV epithelial disease convert a dendrite into a large geographic ulcer. [Kanski 10e]",
          "Steroids also **suppress stromal repair**, promote melting and perforation, and raise intraocular pressure. [Kanski 10e]",
          "Steroid-antibiotic combination drops are **sold over the counter in India** and are a leading cause of worsened fungal ulcers seen at tertiary centres. [NPCBVI 2023]",
          "**SCUT showed no overall benefit of adjunctive steroids** in bacterial keratitis, and any steroid use is a specialist decision after 48 hours of effective antibiotic. [AAO PPP Keratitis 2023]",
          "**Traditional eye medicines** - herbal juices, breast milk, ghee, crushed leaves - introduce fungi and bacteria and delay proper treatment by days. [Kanski 10e]",
          "**Topical anaesthetic drops must never be given home** - repeated use causes toxic keratopathy, non-healing ulcers and blindness. [AAO PPP Keratitis 2023]",
          "Eye-patching an infected eye raises temperature and moisture and favours microbial growth. [Kanski 10e]",
        ],
      },
      {
        heading: "Classification of ocular trauma",
        points: [
          "The **Birmingham Eye Trauma Terminology (BETT)** divides mechanical injury into **closed globe** (no full-thickness wound) and **open globe** (full-thickness wound of cornea or sclera). [Kanski 10e]",
          "Closed globe injuries are **contusion** (no wound) and **lamellar laceration** (partial thickness), including superficial foreign body. [Kanski 10e]",
          "Open globe injuries are **rupture** (blunt force, inside-out at the weakest point) and **laceration** - penetrating (entry only), perforating (entry and exit) and intraocular foreign body. [Kanski 10e]",
          "The **Ocular Trauma Score** combines initial vision, rupture, endophthalmitis, perforating injury, retinal detachment and RAPD to predict final vision. [Kanski 10e]",
          "Non-mechanical injuries are **chemical** (alkali, acid), **thermal**, and **radiational** (UV keratitis of welders and snow blindness, solar retinopathy). [Kanski 10e]",
          "**Blow-out fracture of the orbital floor** gives diplopia on upgaze, enophthalmos and infraorbital numbness - avoid nose blowing and refer to maxillofacial or oculoplastics. [Bailey and Love 28e]",
        ],
      },
      {
        heading: "Chemical injury: irrigate first",
        points: [
          "**Alkali injuries are more severe than acid** because alkali saponifies membranes and penetrates deep, while acid coagulates surface proteins and limits its own spread. [Kanski 10e]",
          "**Irrigate immediately** at the scene with any clean water, then with normal saline or Ringer lactate - at least 1-2 litres over 15-30 minutes - before taking any history. [Kanski 10e]",
          "Instil a topical anaesthetic, hold the lids open with a speculum or retractor, and **double-evert the upper lid** to sweep out particles of lime with a moist cotton bud. [Kanski 10e]",
          "Check the **tear pH with litmus paper 5-10 minutes after stopping** and continue irrigation until it is 7.0-7.2. [Kanski 10e]",
          "Grade the injury by corneal clarity and **limbal ischaemia** (Roper-Hall or Dua) - the extent of limbal stem-cell loss decides the prognosis. [Kanski 10e]",
          "Specialist care: topical antibiotic, cycloplegic, **topical steroid for the first 7-10 days**, ascorbate 10 per cent drops, oral vitamin C 1 g and oral doxycycline 100 mg twice daily. [Kanski 10e]",
          "**Amniotic membrane grafting** is done early in severe burns, and limbal stem cell transplantation later for conjunctivalised corneas. [Kanski 10e]",
          "**Superglue on the lids** is not a chemical burn - soak with warm water, trim lashes, and let it release; never force the lids apart. [Rosen 10e]",
        ],
      },
      {
        heading: "Foreign body, hyphaema and open globe",
        points: [
          "**Subtarsal foreign body** causes multiple **linear vertical corneal abrasions** on fluorescein - evert the upper lid and sweep it out with a moist cotton bud. [Kanski 10e]",
          "Remove a **corneal foreign body** under topical proparacaine 0.5 per cent at the slit lamp with a moist cotton bud or the bevel of a 26G needle held tangentially. [Kanski 10e]",
          "Remove the **rust ring** with a burr or needle the same day or after 24 hours, then give chloramphenicol ointment four times a day for 5 days. [Kanski 10e]",
          "**Hammering metal on metal** with a sudden blur means an **intraocular foreign body** - get an X-ray orbit or CT and never an MRI for a possibly ferrous body. [Kanski 10e]",
          "**Hyphaema** is blood in the anterior chamber, graded from microhyphaema through grade I (under one-third) to grade IV (total, eight-ball). [Kanski 10e]",
          "Manage hyphaema with **head elevation to 30-45 degrees, rest, a shield, atropine and topical steroid**, and daily pressure checks for 5 days. [Kanski 10e]",
          "Avoid **aspirin and NSAIDs** in hyphaema, and watch for rebleeding at **2-5 days**, raised pressure and corneal blood staining; screen for sickle cell trait where prevalent. [Kanski 10e]",
          "**Open globe signs:** a peaked or teardrop pupil, uveal tissue prolapse, very shallow or deep anterior chamber, positive Seidel, hypotony and a bullous 360-degree subconjunctival haemorrhage. [Kanski 10e]",
          "For suspected open globe, **apply a rigid shield without pressure**, give no drops or ointment, keep nil by mouth, give antiemetic and analgesia, and transfer supine. [Rosen 10e]",
          "Start **systemic antibiotic (oral moxifloxacin 400 mg once daily or IV vancomycin with ceftazidime)** to prevent post-traumatic endophthalmitis, and repair within 24 hours. [Kanski 10e]",
          "Any **eye injury with a stick, thorn or soil** is both a fungal keratitis risk and a tetanus-prone wound. [Kanski 10e]",
          "Give **Td 0.5 mL IM** if the last dose was over 5 years ago for a tetanus-prone wound, and add **tetanus immunoglobulin 250 IU IM** if the patient is unimmunised or unsure. [MoHFW Td 2018]",
        ],
      },
      {
        heading: "Prevention, family physician role and referral",
        points: [
          "Teach farmers that **any eye injury during harvest needs examination within 24 hours** - antimicrobial prophylaxis after abrasion prevents most ulcers. [Kanski 10e]",
          "Promote **protective eyewear** for agricultural, construction and industrial workers and welders, and safe firecracker practice during Diwali. [NPCBVI 2023]",
          "Teach contact lens users: **no sleeping, swimming or showering in lenses, no tap water on lenses**, and replacement cases every month. [AAO PPP Keratitis 2023]",
          "Keep **fluorescein strips, topical anaesthetic, a shield and litmus paper** in every primary care clinic - these four equip the family physician for most eye trauma. [Rosen 10e]",
          "A simple corneal abrasion is treated with **chloramphenicol ointment four times a day for 3-5 days** and review at 24-48 hours; patching is not needed. [Rosen 10e]",
          "**Same-day referral** for any corneal infiltrate, hypopyon, suspected open globe or IOFB, chemical injury after irrigation, hyphaema and any drop in vision. [Rosen 10e]",
          "Write a **medicolegal note** for assaults and workplace injuries, with time, mechanism, visual acuity and findings. [Kanski 10e]",
          "Promote **eye donation** and counsel families after a death - the family physician is often the first person asked. [NPCBVI 2023]",
        ],
      },
    ],
    tables: [
      {
        heading: "Differentiating infective keratitis",
        columns: ["Feature", "Bacterial", "Fungal", "Herpes simplex", "Acanthamoeba"],
        rows: [
          ["Typical setting", "Contact lens, ocular surface disease", "Vegetative trauma, farmer, steroid misuse", "Recurrent, after fever or stress", "Contact lens with tap or pool water"],
          ["Course", "Hours to 1-2 days", "Days, indolent", "Recurrent attacks", "Weeks, relapsing"],
          ["Lesion", "Dense infiltrate, defined edge", "Dry raised slough, feathery edge, satellites", "Dendrite with terminal bulbs", "Ring infiltrate, radial perineuritis"],
          ["Hypopyon", "Mobile, common", "Thick, immobile, endothelial plaque", "Rare", "Late"],
          ["Corneal sensation", "Normal", "Normal", "Reduced", "Normal, pain out of proportion"],
          ["Key test", "Gram stain, culture", "KOH mount, SDA culture", "Clinical, PCR", "Non-nutrient agar, confocal microscopy"],
          ["First-line drug", "Fortified cefazolin plus tobramycin, or moxifloxacin", "Natamycin 5 per cent", "Ganciclovir gel or aciclovir", "PHMB or chlorhexidine 0.02 per cent"],
        ],
      },
      {
        heading: "BETT classification of mechanical eye injury",
        columns: ["Type", "Subtype", "Mechanism", "Example"],
        rows: [
          ["Closed globe", "Contusion", "Blunt force, no wound", "Cricket ball, fist - hyphaema, commotio retinae"],
          ["Closed globe", "Lamellar laceration", "Partial-thickness wound", "Corneal abrasion, superficial foreign body"],
          ["Open globe", "Rupture", "Blunt force, inside-out tear", "Bull horn, fall on a stick end"],
          ["Open globe", "Penetrating", "Sharp object, entry wound only", "Knife, glass, arrow"],
          ["Open globe", "Perforating", "Entry and exit wounds", "Pellet gun, high-velocity missile"],
          ["Open globe", "Intraocular foreign body", "Retained fragment", "Hammer and chisel, firecracker"],
        ],
      },
      {
        heading: "Roper-Hall grading of chemical injury",
        columns: ["Grade", "Cornea", "Limbal ischaemia", "Prognosis"],
        rows: [
          ["I", "Epithelial damage only", "None", "Good"],
          ["II", "Haze, iris details visible", "Less than one-third", "Good"],
          ["III", "Total epithelial loss, stromal haze hides iris detail", "One-third to one-half", "Guarded"],
          ["IV", "Opaque, iris and pupil obscured", "More than one-half", "Poor"],
        ],
      },
    ],
    redFlags: [
      "Any corneal infiltrate or white spot on the cornea, especially with hypopyon.",
      "Eye pain and redness in a contact lens wearer.",
      "Chemical splash - irrigate first, then refer the same day.",
      "Peaked pupil, uveal prolapse, positive Seidel test or hypotony after injury - open globe.",
      "History of hammering metal or high-velocity injury with blurred vision - intraocular foreign body.",
      "Hyphaema, especially with raised pressure, rebleeding or sickle cell disease.",
      "Diplopia with enophthalmos or infraorbital numbness after blunt trauma - orbital floor fracture.",
      "Sudden drop in vision or new RAPD after any eye injury.",
    ],
    pearls: [
      "Feathery margins, satellite lesions and a dry raised slough after vegetative trauma - think fungus and do a KOH mount.",
      "Natamycin 5 per cent is the drug of choice for filamentous fungal keratitis (MUTT I); oral voriconazole adds nothing (MUTT II).",
      "Dendrite with terminal bulbs and reduced sensation equals HSV - and topical steroid is contraindicated.",
      "Pain out of proportion in a lens wearer is acanthamoeba until proved otherwise.",
      "In a chemical injury, irrigation comes before history, examination or referral - check pH until it is 7.0-7.2.",
      "Alkali is worse than acid; limbal ischaemia decides the prognosis.",
      "Multiple vertical linear abrasions on fluorescein mean a subtarsal foreign body - evert the lid.",
      "Suspected open globe: shield, no pressure, no drops, nil by mouth, antibiotic, tetanus, refer.",
      "Never send a patient home with topical anaesthetic drops.",
      "Hammering metal on metal plus a blur is an IOFB until an X-ray or CT says otherwise - never MRI.",
    ],
    mcqs: [
      {
        id: "eye-ent-corneal-ulcer-ocular-trauma-q1",
        stem: "A 42-year-old farmer from Tamil Nadu presents 6 days after being hit in the eye by a paddy leaf. There is a dry, raised greyish ulcer with feathery margins, satellite lesions and a thick hypopyon. KOH mount shows septate hyphae. What is the drug of choice?",
        options: [
          "Fortified cefazolin with tobramycin",
          "Natamycin 5 per cent suspension",
          "Ganciclovir 0.15 per cent gel",
          "Prednisolone acetate 1 per cent with moxifloxacin",
        ],
        answer: 1,
        explanation:
          "The picture of filamentous fungal keratitis after vegetative trauma with hyphae on KOH calls for natamycin 5 per cent, which MUTT I showed superior to voriconazole, especially for Fusarium. Fortified antibiotics treat bacteria, ganciclovir treats herpes, and a steroid-antibiotic combination would make a fungal ulcer spread.",
        difficulty: "easy",
      },
      {
        id: "eye-ent-corneal-ulcer-ocular-trauma-q2",
        stem: "A 30-year-old has a red, watering eye after a febrile illness. Fluorescein shows a branching ulcer with bulbous ends and corneal sensation is reduced. He has been using a steroid-antibiotic drop bought from a pharmacy. What is the most appropriate step?",
        options: [
          "Continue the combination drop and add artificial tears",
          "Switch to natamycin drops hourly",
          "Pad the eye for 24 hours",
          "Stop the steroid and start topical ganciclovir gel five times a day",
        ],
        answer: 3,
        explanation:
          "A dendritic ulcer with terminal bulbs and reduced sensation is HSV epithelial keratitis; steroids convert it into a geographic ulcer and must be stopped, with topical ganciclovir or aciclovir started. Natamycin is for fungus, continuing the steroid is harmful, and padding does nothing for viral replication.",
        difficulty: "moderate",
      },
      {
        id: "eye-ent-corneal-ulcer-ocular-trauma-q3",
        stem: "A construction worker is brought to the PHC five minutes after wet lime splashed into his right eye. What should be done first?",
        options: [
          "Copious irrigation with clean water or saline, removing lime particles",
          "Measure visual acuity and document the injury",
          "Instil antibiotic ointment and pad the eye",
          "Refer immediately to the district hospital",
        ],
        answer: 0,
        explanation:
          "In a chemical injury, especially alkali such as lime, immediate copious irrigation with lid eversion to remove particles comes before acuity, history or transfer, because every minute of contact deepens stromal and limbal damage. Padding traps the alkali, and referral without irrigation loses the critical first minutes.",
        difficulty: "easy",
      },
      {
        id: "eye-ent-corneal-ulcer-ocular-trauma-q4",
        stem: "After being hit with a stick, a boy has a teardrop-shaped pupil pointing towards a 3 mm limbal wound with dark tissue in it. What is the correct immediate management in primary care?",
        options: [
          "Remove the prolapsed tissue and pad firmly",
          "Instil antibiotic drops and review next day",
          "Rigid shield without pressure, nil by mouth, systemic antibiotic, tetanus prophylaxis and urgent referral",
          "Apply topical steroid to reduce inflammation",
        ],
        answer: 2,
        explanation:
          "A peaked pupil with uveal prolapse means an open globe; a rigid shield without pressure, fasting for surgery, systemic antibiotic and tetanus cover precede urgent repair. Pressure or padding extrudes contents, drops can enter the eye, and steroid or delay invites endophthalmitis, especially after a stick injury.",
        difficulty: "moderate",
      },
      {
        id: "eye-ent-corneal-ulcer-ocular-trauma-q5",
        stem: "A 25-year-old welder has a gritty eye after grinding. Fluorescein shows several fine vertical linear abrasions on the upper cornea. What is the most likely cause?",
        options: [
          "Ultraviolet keratitis",
          "Subtarsal foreign body",
          "Herpes simplex keratitis",
          "Dry eye",
        ],
        answer: 1,
        explanation:
          "Vertical linear abrasions are scratched onto the cornea by a foreign body lodged under the upper lid with each blink, so the lid must be everted and swept. UV keratitis gives diffuse punctate staining, herpes a dendrite, and dry eye inferior punctate staining.",
        difficulty: "easy",
      },
    ],
    theory: [
      {
        id: "eye-ent-corneal-ulcer-ocular-trauma-t1",
        paper: "II",
        kind: "long",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question:
          "A 45-year-old farmer presents with a painful red eye one week after injury with a paddy leaf. Discuss the differential diagnosis of corneal ulcer, its investigation and management. Why are topical steroids contraindicated? [3+2+3+2]",
        openingLines: [
          "Corneal ulcer is a break in the corneal epithelium with underlying stromal infiltrate; after vegetative trauma in an Indian farmer it is fungal until proved otherwise.",
          "Corneal opacity is the second commonest cause of blindness in Indians over 50 (NBVIS 2015-19), and most of it is preventable.",
        ],
        answer: [
          {
            heading: "Differential diagnosis",
            points: [
              "Fungal: feathery margins, satellites, dry slough, immune ring, endothelial plaque, immobile hypopyon.",
              "Bacterial: rapid, dense defined infiltrate, mucopurulent discharge, mobile hypopyon; Pseudomonas in lens wearers.",
              "HSV: dendrite with terminal bulbs, reduced sensation; acanthamoeba: lens wearer, pain out of proportion, ring infiltrate.",
              "Non-infective: neurotrophic, exposure, marginal keratitis.",
            ],
          },
          {
            heading: "Investigations",
            points: [
              "Visual acuity; fluorescein under cobalt blue; slit-lamp size, depth, hypopyon; Seidel test.",
              "Corneal scraping: Gram stain, 10 per cent KOH, calcofluor white; culture on blood, chocolate and SDA agar.",
              "Blood sugar, HIV; B-scan if posterior view is hidden.",
            ],
          },
          {
            heading: "Management",
            points: [
              "Fungal: natamycin 5 per cent hourly 48-72 hours then two-hourly, continued 3-4 weeks after healing; add voriconazole 1 per cent if deep or Aspergillus.",
              "Bacterial: fortified cefazolin 50 mg/mL plus tobramycin 14 mg/mL hourly, or moxifloxacin 0.5 per cent for small peripheral ulcers.",
              "Supportive: atropine 1 per cent twice daily, oral analgesics, acetazolamide if pressure raised, no patching.",
              "Surgical: glue and bandage lens for perforation, therapeutic keratoplasty; refer same day.",
            ],
          },
          {
            heading: "Why steroids are contraindicated",
            points: [
              "Enhance fungal growth and HSV replication; convert dendrite to geographic ulcer.",
              "Delay stromal repair, promote melting and perforation; raise intraocular pressure.",
              "Also avoid traditional eye medicines and home use of topical anaesthetics.",
            ],
          },
        ],
        mustDraw: ["Table differentiating bacterial, fungal, viral and acanthamoeba keratitis", "Diagram of a fungal ulcer showing feathery margin, satellite lesion and hypopyon"],
        markSplit: [
          { part: "Differential diagnosis", marks: 3 },
          { part: "Investigations", marks: 2 },
          { part: "Management", marks: 3 },
          { part: "Steroid contraindication", marks: 2 },
        ],
        keywords: ["fungal keratitis", "natamycin", "KOH mount", "corneal ulcer", "steroid"],
      },
      {
        id: "eye-ent-corneal-ulcer-ocular-trauma-t2",
        paper: "II",
        kind: "short-note",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question:
          "Classify ocular injuries. Describe the primary care management of chemical injury of the eye and of a suspected open globe injury. [3+4+3]",
        openingLines: [
          "Ocular trauma is classified by the Birmingham Eye Trauma Terminology into closed and open globe injuries, with chemical, thermal and radiation injuries as non-mechanical types.",
          "Eye injury causes about one in five cases of monocular blindness in India, and the first 30 minutes in primary care often decide the outcome.",
        ],
        answer: [
          {
            heading: "Classification",
            points: [
              "Mechanical closed globe: contusion, lamellar laceration, superficial foreign body.",
              "Mechanical open globe: rupture; laceration - penetrating, perforating, intraocular foreign body.",
              "Non-mechanical: chemical (alkali, acid), thermal, radiation (UV, solar).",
            ],
          },
          {
            heading: "Chemical injury",
            points: [
              "Irrigate immediately with 1-2 litres of saline or clean water for 15-30 minutes under topical anaesthesia.",
              "Double-evert the upper lid and remove particles; check pH to 7.0-7.2.",
              "Grade by Roper-Hall; start antibiotic ointment and cycloplegic; refer same day for steroid, ascorbate, doxycycline and amniotic membrane.",
            ],
          },
          {
            heading: "Suspected open globe",
            points: [
              "Signs: peaked pupil, uveal prolapse, Seidel positive, abnormal chamber depth, hypotony.",
              "Rigid shield without pressure, no drops, nil by mouth, antiemetic, analgesia.",
              "Oral moxifloxacin 400 mg or IV antibiotics, Td with or without TIG, CT orbit (no MRI if metallic), refer for repair within 24 hours.",
            ],
          },
        ],
        mustDraw: ["BETT classification flow chart of mechanical eye injury"],
        markSplit: [
          { part: "Classification", marks: 3 },
          { part: "Chemical injury", marks: 4 },
          { part: "Open globe", marks: 3 },
        ],
        keywords: ["BETT", "chemical injury", "irrigation", "open globe", "Roper-Hall", "shield"],
      },
    ],
    references: [
      "Kanski's Clinical Ophthalmology, 10th edition, 2024",
      "American Academy of Ophthalmology Preferred Practice Pattern: Bacterial Keratitis 2023",
      "Krachmer, Mannis and Holland. Cornea, 5th edition, 2021",
      "Rosen's Emergency Medicine, 10th edition, 2022",
      "National Blindness and Visual Impairment Survey India 2015-19, NPCBVI, MoHFW 2019",
      "MoHFW Operational guidelines for introduction of Td vaccine 2018",
    ],
  },
];

export default topics;
