import type { Topic } from "../../lib/types";

const topics: Topic[] = [
  {
    id: "geriatrics-ethics-elderly-community-health",
    title: "Health problems of the elderly, elder abuse and social support in India",
    oneLiner:
      "India's population aged 60 and above - **about 10.5% (149 million) in 2022, projected to reach 20.8% by 2050** - carries a heavy load of chronic disease, disability, depression, dependency and elder abuse, addressed by NPHCE, the MWPSC Act 2007, pensions, PM-JAY cover for all aged 70+ and a family physician who practises comprehensive geriatric assessment and active-ageing advice.",
    frequency: "core",
    keywords: [
      "geriatrics",
      "elderly",
      "senior citizens",
      "LASI",
      "India Ageing Report",
      "NPHCE",
      "elder abuse",
      "EASI",
      "MWPSC Act 2007",
      "Maintenance and Welfare of Parents and Senior Citizens Act",
      "Elderline 14567",
      "IGNOAPS",
      "Ayushman Vay Vandana",
      "PM-JAY 70+",
      "RPwD Act 2016",
      "UDID",
      "CBR",
      "ICOPE",
      "healthy ageing",
      "retirement",
    ],
    sections: [
      {
        heading: "Demographic ageing in India",
        points: [
          "**Elderly** in India are persons aged **60 years and above** (National Policy on Older Persons 1999; MWPSC Act 2007). [Park 28e]",
          "The elderly were **8.6% (104 million) in Census 2011**, rose to about **10.5% (149 million) in 2022**, and will be **20.8% (347 million) by 2050**. [UNFPA India Ageing Report 2023]",
          "**LASI Wave 1 (2017-18)** is India's largest ageing survey - over 72,000 adults aged 45 and above in all states. [LASI Wave 1 2020]",
          "**Feminisation of ageing** - women outlive men, and more than half of women aged 60+ are widowed, often without income. [LASI Wave 1 2020]",
          "**Ruralisation** - about 70% of elderly live in rural areas with limited access to specialist care. [UNFPA India Ageing Report 2023]",
          "**Old-age dependency ratio** is rising; southern states (Kerala, Tamil Nadu) and Himachal Pradesh have the oldest populations. [UNFPA India Ageing Report 2023]",
          "Life expectancy at 60 is **about 18 years**, and higher for women. [UNFPA India Ageing Report 2023]",
          "**Breakdown of the joint family**, migration of children and urbanisation leave many elderly living alone or as couples. [Park 28e]",
          "Around **three-quarters of the elderly have at least one chronic disease** and about 40% have some disability. [LASI Wave 1 2020]",
        ],
      },
      {
        heading: "Medical, psychological, social and economic problems",
        points: [
          "**Medical - chronic NCDs**: hypertension (about one-third), diabetes, COPD, IHD, stroke, CKD, cancers, osteoarthritis. [LASI Wave 1 2020]",
          "**Geriatric giants (Isaacs)**: immobility, instability (falls), incontinence, intellectual impairment and iatrogenesis. [Brocklehurst 8e]",
          "**Sensory loss** - cataract and presbyopia, presbycusis - is the commonest disability and among the most treatable. [LASI Wave 1 2020]",
          "**Multimorbidity and polypharmacy** (5 or more drugs) cause falls, delirium and admissions - review with Beers and STOPP/START criteria. [AGS Beers 2023]",
          "Other medical problems: **osteoporosis and fractures, malnutrition and sarcopenia, oral disease, constipation, sleep disorders, BPH**. [Harrison 22e]",
          "**Psychological**: depression (about 1 in 5 elderly has depressive symptoms), dementia (estimated 7-8% prevalence in 60+), anxiety, loneliness, bereavement. [LASI-DAD 2023]",
          "Depression in the elderly often presents with **somatic complaints, poor sleep, memory complaints or weight loss** - screen with GDS-15. [NPHCE 2021]",
          "**Social**: loss of spouse, isolation, change of role, dependence on children, neglect, abuse and migration of children. [Park 28e]",
          "**Economic**: only a minority have a pension; many depend on children or keep working; **out-of-pocket health spending** pushes families into poverty. [LASI Wave 1 2020]",
          "Elderly women face a **double disadvantage** - widowhood, no property in their name and lower literacy. [UNFPA India Ageing Report 2023]",
        ],
      },
      {
        heading: "Healthy and active ageing and retirement",
        points: [
          "**Healthy ageing** (WHO) is developing and maintaining the **functional ability** that enables well-being in older age - built on intrinsic capacity and environment. [WHO ICOPE 2024]",
          "WHO **ICOPE** screens six domains of intrinsic capacity: **cognition, mobility, nutrition, vision, hearing and depressive symptoms**. [WHO ICOPE 2024]",
          "The **UN Decade of Healthy Ageing 2021-2030** is the global framework India subscribes to. [WHO ICOPE 2024]",
          "**Physical activity**: 150 minutes of moderate activity a week plus **balance and strength training on 3 or more days** to prevent falls (yoga, tai chi). [WHO Physical Activity Guidelines 2020]",
          "**Diet**: protein 1-1.2 g/kg/day, calcium 1200 mg, vitamin D, fibre, adequate fluids; avoid excess salt. [ICMR-NIN 2024]",
          "**Vaccination**: annual influenza, pneumococcal (PCV then PPSV23), Td booster every 10 years, recombinant zoster vaccine. [API Adult Immunization 2024]",
          "Stop **tobacco and alcohol**; keep mentally and socially active - volunteering, senior citizens' clubs, religious and community groups. [Park 28e]",
          "**Retirement - anticipated problems**: loss of role and identity, reduced income, loss of workplace social network, boredom, depression, increased alcohol use, marital friction. [Park 28e]",
          "**Pre-retirement counselling** - financial planning, hobbies, part-time or voluntary work, health insurance before the employer cover ends. [Park 28e]",
          "**Pre-retirement health check**: BP, glucose, lipids, BMI, cancer screening (oral, breast, cervix, colorectal as indicated), vision, hearing, bone health, cognition, mood. [NPHCE 2021]",
        ],
      },
      {
        heading: "Elder abuse: types, warning signs, screening and remedies",
        points: [
          "**Elder abuse (WHO)** is a single or repeated act, or lack of appropriate action, within a relationship with an expectation of trust, which causes harm or distress to an older person. [WHO 2022]",
          "Types: **physical, psychological (verbal), financial (material), sexual, neglect** (active or passive), **abandonment** and self-neglect. [Brocklehurst 8e]",
          "About **5% of Indian elderly reported abuse** in LASI; NGO surveys report much higher rates - verbal abuse and disrespect are commonest, usually by sons and daughters-in-law. [LASI Wave 1 2020]",
          "**Warning signs**: unexplained bruises or fractures, delay in seeking care, poor hygiene, malnutrition, pressure ulcers, fearfulness, sudden change in finances or will. [Brocklehurst 8e]",
          "Risk factors: **dependency, dementia, caregiver stress, caregiver substance use, financial dependence of the abuser, social isolation**. [Harrison 22e]",
          "Screen with the **Elder Abuse Suspicion Index (EASI)** - six questions asked of the older person alone. [Brocklehurst 8e]",
          "**Interview the elder alone**, document injuries with body diagrams, assess capacity and immediate safety. [Harrison 22e]",
          "Remedies: counselling and caregiver support, respite, **Elderline 14567**, police senior-citizen cells, Maintenance Tribunal, old-age homes, legal aid. [MoSJE 2023]",
          "Physical or sexual abuse is a **criminal offence under BNS 2023** - police intimation and MLC documentation are required. [BNS 2023]",
          "**World Elder Abuse Awareness Day is 15 June**. [WHO 2022]",
        ],
      },
      {
        heading: "Legal protection and national programmes",
        points: [
          "**Maintenance and Welfare of Parents and Senior Citizens (MWPSC) Act 2007** obliges children and relatives who inherit property to maintain senior citizens. [MWPSC Act 2007]",
          "A **Maintenance Tribunal** (headed by the SDM) can order maintenance **up to Rs 10,000 per month**, and must decide within **90 days**. [MWPSC Act 2007]",
          "**Abandonment** of a senior citizen by a person responsible for care is punishable with up to **3 months' imprisonment or Rs 5000 fine, or both**. [MWPSC Act 2007]",
          "Property transferred on condition of care can be **declared void** by the tribunal if care is not provided. [MWPSC Act 2007]",
          "The Act also asks states to run **at least one old-age home per district** and to reserve beds and queues for seniors in government hospitals. [MWPSC Act 2007]",
          "**National Policy on Older Persons 1999** set the framework - financial security, health care, shelter, welfare and protection. [Park 28e]",
          "**NPHCE (National Programme for Health Care of the Elderly, 2010)** provides services from SC-HWC (home care, screening) to PHC, CHC (rehabilitation), district geriatric wards and Regional Geriatric Centres, and two National Centres of Ageing (AIIMS Delhi, MMC Chennai). [NPHCE 2021]",
          "**Elderline 14567** is the national toll-free helpline for senior citizens (information, legal guidance, emotional support, rescue). [MoSJE 2023]",
          "**Rashtriya Vayoshri Yojana** gives free aids - spectacles, hearing aids, walking sticks, dentures, wheelchairs - to BPL and low-income seniors. [MoSJE 2023]",
          "Concessions: **Senior Citizens Savings Scheme, higher FD interest, income-tax benefits** and priority in public services. [Park 28e]",
        ],
      },
      {
        heading: "Social security and health cover",
        points: [
          "**IGNOAPS** (Indira Gandhi National Old Age Pension Scheme, under NSAP) pays **Rs 200 per month for BPL persons aged 60-79 and Rs 500 from age 80**, topped up by states. [MoRD NSAP 2024]",
          "**Pradhan Mantri Vaya Vandana Yojana** was an LIC pension scheme for those 60+; it closed to new subscribers on **31 March 2023**. [Park 28e]",
          "**PM-JAY for all aged 70+ (October 2024)** covers every senior citizen aged 70 and above irrespective of income, with the **Ayushman Vay Vandana card** and up to **Rs 5 lakh per year**. [NHA 2024]",
          "Seniors already in an eligible PM-JAY family get an **additional Rs 5 lakh top-up** for themselves. [NHA 2024]",
          "**Atal Vayo Abhyuday Yojana (AVYAY)** is the umbrella scheme of the Ministry of Social Justice for old-age homes, day care and mobile medicare units. [MoSJE 2023]",
          "**CGHS, ECHS and ESIC** cover retired government employees, ex-servicemen and insured workers respectively. [Park 28e]",
        ],
      },
      {
        heading: "Disability: RPwD Act 2016, certification and CBR",
        points: [
          "The **Rights of Persons with Disabilities Act 2016** recognises **21 disabilities** (up from 7 in the 1995 Act), including locomotor, visual, hearing, intellectual, mental illness, autism, thalassaemia, haemophilia, sickle cell disease and acid-attack survivors. [RPwD Act 2016]",
          "**Benchmark disability** is 40% or more - it confers reservation of **4% in government jobs and 5% in higher education**. [RPwD Act 2016]",
          "A **disability certificate** is issued by a notified medical authority (medical board) and linked to the **UDID (Unique Disability ID) card**, applied for online. [RPwD Act 2016]",
          "Discrimination against persons with disability is an offence; **Sugamya Bharat Abhiyan** mandates accessible public buildings, transport and websites. [RPwD Act 2016]",
          "**Community-based rehabilitation (CBR)** uses community resources to deliver rehabilitation - the WHO CBR matrix has health, education, livelihood, social and empowerment components. [Park 28e]",
          "Family physician's role in disability: **early detection, certification guidance, aids, physiotherapy, linkage to schemes and caregiver support**. [NPHCE 2021]",
        ],
      },
      {
        heading: "Elder- and disabled-friendly home and the family physician's role",
        points: [
          "**Lighting**: bright light in corridors and stairs, **night lights** on the way to the toilet, switches at room entry. [Brocklehurst 8e]",
          "**Floors**: remove loose rugs and clutter, non-slip tiles or mats, no trailing wires, avoid polished floors. [NICE CG161 2019]",
          "**Bathroom**: **grab bars** near the toilet and in the shower, raised Western toilet seat or commode chair, shower stool, non-slip mat. [NICE CG161 2019]",
          "**Stairs and entry**: handrails on both sides, contrasting step edges, **ramps** of gradient 1:12 for wheelchairs. [RPwD Act 2016]",
          "**Bedroom**: bed at knee height, phone and torch within reach, ground-floor room if mobility is poor. [Brocklehurst 8e]",
          "**Kitchen**: items at waist-to-shoulder height, gas safety devices, avoid step stools. [Brocklehurst 8e]",
          "**Safety**: emergency numbers displayed (108, 14567), medical alert device, a neighbour or relative checking daily. [MoSJE 2023]",
          "Family physician: **comprehensive geriatric assessment** (medical, functional - ADL/IADL, cognitive, mood, social, environmental), annual review and medication reconciliation. [Brocklehurst 8e]",
          "Home visits, advance care planning, caregiver training and linkage to NPHCE, PM-JAY and pension schemes complete the role. [NPHCE 2021]",
        ],
      },
    ],
    tables: [
      {
        heading: "Types of elder abuse - classification with warning signs",
        columns: ["Type", "Examples", "Warning signs"],
        rows: [
          ["Physical", "Hitting, restraint, over-sedation", "Unexplained bruises, fractures, burns"],
          ["Psychological", "Insults, threats, isolation", "Fearfulness, withdrawal, depression"],
          ["Financial", "Taking pension, forced will or property transfer", "Unpaid bills despite income, sudden transfer of assets"],
          ["Sexual", "Non-consensual contact", "Genital injury, STI, fear of a caregiver"],
          ["Neglect", "Withholding food, medicines, hygiene", "Malnutrition, pressure ulcers, dehydration, soiled clothes"],
          ["Abandonment", "Deserting in hospital, pilgrimage site or home", "Elder left alone without means"],
        ],
      },
      {
        heading: "Schemes and laws for senior citizens",
        columns: ["Measure", "Key provision"],
        rows: [
          ["MWPSC Act 2007", "Maintenance up to Rs 10,000/month; tribunal decides in 90 days; abandonment punishable"],
          ["NPHCE 2010", "Geriatric care from HWC to Regional Geriatric Centres and National Centres of Ageing"],
          ["IGNOAPS", "Rs 200/month (60-79), Rs 500/month (80+) for BPL"],
          ["PM-JAY 70+ (2024)", "Rs 5 lakh cover for every person aged 70+, Ayushman Vay Vandana card"],
          ["Rashtriya Vayoshri Yojana", "Free assistive devices for low-income seniors"],
          ["Elderline 14567", "National toll-free helpline"],
          ["RPwD Act 2016", "21 disabilities, benchmark 40%, UDID card, reservations"],
        ],
      },
    ],
    redFlags: [
      "Unexplained injuries, fractures or burns in an elderly person, especially with delay in seeking care - suspect abuse; examine alone and document.",
      "Acute confusion (delirium) - search for infection, drugs, dehydration, retention; admit if cause is not quickly reversible.",
      "Recurrent falls or a fall with inability to get up - full falls assessment; exclude fracture and syncope.",
      "Rapid unintentional weight loss over 5% in 6 months - malignancy, depression, neglect or dementia.",
      "Suicidal ideation in an elderly man living alone - the highest-risk group; urgent psychiatric referral.",
      "Pressure ulcers, dehydration or starvation in a dependent elder - neglect; safeguarding action and police intimation if criminal.",
      "Abandoned elder without means - Elderline 14567, police and Maintenance Tribunal.",
    ],
    pearls: [
      "India's elderly will double from about 10% to over 20% of the population by 2050 - the demographic transition is now a geriatric one.",
      "The geriatric giants are immobility, instability, incontinence, intellectual impairment and iatrogenesis.",
      "ICOPE screens six domains of intrinsic capacity: cognition, mobility, nutrition, vision, hearing and mood.",
      "MWPSC Act 2007: up to Rs 10,000 per month, decided in 90 days, and abandonment is a punishable offence.",
      "Since October 2024 every Indian aged 70 and above is covered under PM-JAY regardless of income.",
      "Elderline is 14567 - quote it.",
      "Always interview a suspected abused elder alone.",
      "RPwD Act 2016: 21 disabilities, benchmark 40%, UDID card.",
      "A grab bar and a night light prevent more fractures than most drugs.",
    ],
    mcqs: [
      {
        id: "geriatrics-ethics-elderly-community-health-q1",
        stem: "Under the Maintenance and Welfare of Parents and Senior Citizens Act 2007, the maximum monthly maintenance that a Maintenance Tribunal can order is:",
        options: ["Rs 2000", "Rs 5000", "Rs 10,000", "No upper limit"],
        answer: 2,
        explanation:
          "The Act caps maintenance at Rs 10,000 per month, and the tribunal should decide within 90 days. Rs 2000 and Rs 5000 are below the statutory ceiling, and the proposal to remove the cap in the 2019 amendment bill has not become law.",
        difficulty: "moderate",
      },
      {
        id: "geriatrics-ethics-elderly-community-health-q2",
        stem: "A 76-year-old widow brought by her son has a healing forearm fracture, poor hygiene and weight loss. She looks at her son before answering each question. What is the most appropriate next step?",
        options: [
          "Accept the history of a fall and discharge with analgesics",
          "Interview her alone, screen for abuse and document injuries",
          "Ask the son to sign an undertaking to take better care",
          "Refer her to an old-age home immediately",
        ],
        answer: 1,
        explanation:
          "Injury with delay, neglect and fearfulness towards a caregiver are warning signs of elder abuse, so she must be interviewed alone, screened (EASI) and documented. Accepting the history misses abuse, asking the suspected abuser to sign an undertaking does not ensure safety, and placement is premature before assessing her wishes and capacity.",
        difficulty: "moderate",
      },
      {
        id: "geriatrics-ethics-elderly-community-health-q3",
        stem: "Which of the following is NOT one of the six domains of intrinsic capacity screened under WHO ICOPE?",
        options: ["Hearing", "Nutrition", "Blood pressure", "Depressive symptoms"],
        answer: 2,
        explanation:
          "ICOPE screens cognition, mobility, nutrition, vision, hearing and depressive symptoms. Blood pressure is a disease risk factor measured in NCD screening, not a domain of intrinsic capacity.",
        difficulty: "easy",
      },
      {
        id: "geriatrics-ethics-elderly-community-health-q4",
        stem: "Under the Rights of Persons with Disabilities Act 2016, benchmark disability that makes a person eligible for reservation is defined as:",
        options: ["20% or more", "30% or more", "40% or more", "50% or more"],
        answer: 2,
        explanation:
          "Benchmark disability is 40% or more of a specified disability as certified by the medical authority. Lower thresholds do not confer reservation benefits, and 50% is not the statutory benchmark.",
        difficulty: "easy",
      },
      {
        id: "geriatrics-ethics-elderly-community-health-q5",
        stem: "An 81-year-old man from a BPL family asks about a monthly central pension. Under IGNOAPS, the central contribution he is entitled to is:",
        options: ["Rs 200 per month", "Rs 500 per month", "Rs 1000 per month", "Rs 3000 per month"],
        answer: 1,
        explanation:
          "IGNOAPS pays Rs 500 per month from age 80, and Rs 200 per month between 60 and 79; states add their own top-ups. Rs 1000 and Rs 3000 are not the central IGNOAPS rates.",
        difficulty: "moderate",
      },
    ],
    theory: [
      {
        id: "geriatrics-ethics-elderly-community-health-t1",
        paper: "I",
        kind: "long",
        marks: 10,
        minutes: 18,
        frequency: "core",
        question:
          "Enumerate the health problems of the elderly in India. Describe the role of the family physician and the government measures for their welfare. [4+3+3]",
        openingLines: [
          "The elderly (60 years and above) form about 10.5% of India's population, projected to exceed 20% by 2050 (India Ageing Report 2023).",
          "Three-quarters have at least one chronic disease, and their problems are medical, psychological, social and economic.",
        ],
        answer: [
          {
            heading: "Health problems",
            points: [
              "Medical: NCDs, geriatric giants, sensory loss, osteoporosis, malnutrition, polypharmacy.",
              "Psychological: depression, dementia, loneliness, bereavement.",
              "Social: isolation, loss of role, abuse, migration of children.",
              "Economic: no pension, dependency, out-of-pocket spending.",
            ],
          },
          {
            heading: "Role of family physician",
            points: [
              "Comprehensive geriatric assessment; ICOPE screening; medication review.",
              "Vaccination, falls prevention, home modification, nutrition.",
              "Home visits, caregiver support, abuse screening, advance care planning, palliative care.",
            ],
          },
          {
            heading: "Government measures",
            points: [
              "NPHCE; National Policy on Older Persons 1999; MWPSC Act 2007.",
              "IGNOAPS, PM-JAY 70+, Rashtriya Vayoshri Yojana, AVYAY, Elderline 14567.",
              "Tax and travel concessions, senior citizens' savings scheme.",
            ],
          },
        ],
        mustDraw: ["NPHCE service pyramid: SC-HWC - PHC - CHC - district geriatric ward - Regional Geriatric Centre - National Centre of Ageing"],
        markSplit: [
          { part: "Health problems", marks: 4 },
          { part: "Role of family physician", marks: 3 },
          { part: "Government measures", marks: 3 },
        ],
        keywords: ["elderly", "NPHCE", "MWPSC", "geriatric giants"],
      },
      {
        id: "geriatrics-ethics-elderly-community-health-t2",
        paper: "I",
        kind: "short-note",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question: "Write a short note on elder abuse - types, identification and legal remedies in India. [3+4+3]",
        openingLines: [
          "Elder abuse is a single or repeated act, or lack of appropriate action, within a relationship of trust that causes harm or distress to an older person (WHO).",
          "It is under-reported in India because victims depend on the abuser, usually a son or daughter-in-law.",
        ],
        answer: [
          {
            heading: "Types",
            points: ["Physical, psychological, financial, sexual, neglect, abandonment, self-neglect."],
          },
          {
            heading: "Identification",
            points: [
              "Risk factors: dependency, dementia, caregiver stress and substance use.",
              "Warning signs: unexplained injuries, delay, neglect, fearfulness, financial change.",
              "EASI screening; interview alone; document with body diagram; capacity and safety assessment.",
            ],
          },
          {
            heading: "Remedies",
            points: [
              "MWPSC Act 2007 - maintenance tribunal, abandonment offence, voiding property transfer.",
              "BNS 2023 offences, police senior-citizen cells, Elderline 14567.",
              "Counselling, respite care, old-age homes, legal aid.",
            ],
          },
        ],
        mustDraw: ["Table of abuse types with warning signs"],
        markSplit: [
          { part: "Types", marks: 3 },
          { part: "Identification", marks: 4 },
          { part: "Legal remedies", marks: 3 },
        ],
        keywords: ["elder abuse", "EASI", "MWPSC", "neglect"],
      },
    ],
    references: [
      "Longitudinal Ageing Study in India (LASI) Wave 1 Report, 2020",
      "UNFPA India Ageing Report, 2023",
      "NPHCE Operational Guidelines, MoHFW, 2021",
      "Maintenance and Welfare of Parents and Senior Citizens Act, 2007",
      "Rights of Persons with Disabilities Act, 2016",
      "WHO ICOPE Handbook, 2nd ed, 2024",
      "Brocklehurst's Textbook of Geriatric Medicine and Gerontology, 8th ed, 2017",
      "Park's Textbook of Preventive and Social Medicine, 28th ed, 2025",
    ],
  },
  {
    id: "geriatrics-ethics-pressure-ulcers",
    title: "Pressure ulcers (bed sores): staging, prevention and home management",
    oneLiner:
      "A pressure injury (pressure ulcer, bed sore) is **localised damage to skin and underlying soft tissue, usually over a bony prominence, caused by sustained pressure or pressure combined with shear**, staged by the NPIAP system from stage 1 (non-blanchable erythema) to stage 4 (full-thickness loss exposing bone), and is largely preventable by risk scoring, 2-hourly repositioning, support surfaces, skin care and nutrition.",
    frequency: "core",
    keywords: [
      "pressure ulcer",
      "pressure injury",
      "bed sore",
      "decubitus ulcer",
      "NPIAP",
      "EPUAP",
      "Braden scale",
      "Norton scale",
      "Waterlow score",
      "deep tissue pressure injury",
      "unstageable",
      "shear",
      "repositioning",
      "air mattress",
      "debridement",
      "negative pressure wound therapy",
      "flap cover",
      "osteomyelitis",
      "PUSH tool",
      "hemiplegia home care",
    ],
    sections: [
      {
        heading: "Definition, burden and sites of predilection",
        points: [
          "**Pressure injury** is localised damage to skin and underlying soft tissue over a bony prominence or under a medical device, from intense or prolonged pressure or pressure plus shear. [NPIAP/EPUAP/PPPIA 2019]",
          "The NPIAP replaced the word ulcer with **injury** in 2016 because stage 1 and deep tissue injury have intact skin. [NPIAP 2016]",
          "Prevalence in Indian hospital inpatients is reported at **about 4-10 per cent**, higher in ICU, spinal injury and orthopaedic wards. [Bailey and Love 28e]",
          "In home-bound elderly after stroke, hip fracture or dementia, **up to one in five** develops a pressure injury in the first months without caregiver training. [Brocklehurst 8e]",
          "**Sacrum and coccyx** are the commonest sites in the supine patient, followed by the **heels**. [Bailey and Love 28e]",
          "Other supine sites: occiput, scapulae, spinous processes and elbows - check all at every home visit. [NPIAP 2019]",
          "In the lateral position: **greater trochanter, lateral malleolus**, lateral knee and the ear. [NPIAP 2019]",
          "In the sitting or wheelchair-bound patient: **ischial tuberosities** carry the load. [Sabiston 22e]",
          "Prone patients and those with devices develop injuries at the **knees, chest, nose and under catheters, NG tubes, oxygen masks and splints**. [NPIAP 2019]",
          "A pressure injury is a **nursing-care quality indicator** - most are regarded as preventable. [NPIAP 2019]",
        ],
      },
      {
        heading: "Pathophysiology: pressure, shear, friction and moisture",
        points: [
          "Capillary closing pressure is **about 32 mmHg**, while lying on a standard mattress generates 70-100 mmHg over the sacrum. [Sabiston 22e]",
          "Pressure-time relationship is inverse - **high pressure for a short time or low pressure for a long time** both cause ischaemia; 2 hours is the classic limit. [Bailey and Love 28e]",
          "Muscle and fat are more sensitive to ischaemia than skin, so damage starts **deep at the bone-muscle interface** - the cone or iceberg effect. [Rook 10e]",
          "**Shear** occurs when the skeleton slides while skin stays fixed, as when the head of the bed is raised above 30 degrees, kinking perforating vessels. [NPIAP 2019]",
          "**Friction** from dragging a patient up the bed strips the stratum corneum and adds superficial abrasion. [NPIAP 2019]",
          "**Moisture** from urine, faeces or sweat macerates skin and multiplies friction damage - incontinence-associated dermatitis is a close mimic. [NPIAP 2019]",
          "Reperfusion injury after relief of pressure adds free-radical damage, which is why a stage 1 can evolve over 48-72 hours. [Rook 10e]",
          "Intrinsic factors: **immobility, sensory loss, malnutrition (albumin under 3 g/dL), anaemia, diabetes, PAD, advanced age, dementia**. [Brocklehurst 8e]",
          "Extrinsic factors: hard surfaces, wrinkled sheets, poor lifting technique, long waits on stretchers and prolonged sitting. [NPIAP 2019]",
        ],
      },
      {
        heading: "NPIAP staging and risk assessment",
        points: [
          "**Stage 1:** intact skin with non-blanchable erythema; in dark skin look for warmth, induration, pain or purplish discolouration. [NPIAP 2019]",
          "**Stage 2:** partial-thickness loss with exposed dermis - a shallow pink wound bed or intact or ruptured serum blister, no slough. [NPIAP 2019]",
          "**Stage 3:** full-thickness skin loss with visible fat; slough, rolled edges (epibole), undermining and tunnelling may occur, no bone or tendon. [NPIAP 2019]",
          "**Stage 4:** full-thickness skin and tissue loss with exposed or palpable **fascia, muscle, tendon, ligament, cartilage or bone**. [NPIAP 2019]",
          "**Unstageable:** base obscured by slough or eschar - once removed it will be stage 3 or 4; stable dry eschar on the heel should not be removed. [NPIAP 2019]",
          "**Deep tissue pressure injury:** intact or non-intact skin with persistent non-blanchable deep red, maroon or purple discolouration or a blood blister. [NPIAP 2019]",
          "Staging is never reversed - a healing stage 4 is called a **healing stage 4**, not stage 3. [NPIAP 2019]",
          "**Braden scale** has six items: sensory perception, moisture, activity, mobility, nutrition, friction and shear, scored 6-23. [NPIAP 2019]",
          "**Braden 18 or less = at risk**, 13-14 moderate, 10-12 high and **9 or less very high risk**. [NPIAP 2019]",
          "Norton scale (5-20, 14 or less at risk) and Waterlow score are alternatives - the tool matters less than doing it on admission and at every change. [NPIAP 2019]",
          "Monitor healing with the **PUSH tool** (area, exudate, tissue type) and a photograph with a ruler at every dressing change. [NPIAP 2019]",
        ],
      },
      {
        heading: "Prevention: the SSKIN bundle",
        points: [
          "Use the **SSKIN bundle**: Surface, Skin inspection, Keep moving, Incontinence and moisture, Nutrition. [NHS Stop the Pressure 2018]",
          "**Reposition at least every 2 hours** in bed and every hour in a chair; the 30-degree tilted side-lying position off-loads both sacrum and trochanter. [NPIAP 2019]",
          "Keep the **head of bed at 30 degrees or less** unless contraindicated, to reduce shear. [NPIAP 2019]",
          "**Heels must float** - a pillow under the calves, not under the heels, with knees slightly flexed. [NPIAP 2019]",
          "Use a **high-specification foam mattress** for all at-risk patients and an **alternating-pressure air mattress** for high risk or existing stage 3-4 ulcers. [NPIAP 2019]",
          "Do not use ring cushions, water-filled gloves or donut devices - they concentrate pressure on the surrounding ring. [NPIAP 2019]",
          "**Do not massage** bony prominences or rub reddened skin - it causes deep tissue damage. [NPIAP 2019]",
          "Clean incontinence promptly with a pH-balanced cleanser and apply a **barrier cream (zinc oxide or dimethicone)**; catheterise only if the ulcer is being soiled. [NPIAP 2019]",
          "Nutrition: **30-35 kcal/kg/day and protein 1.25-1.5 g/kg/day** with 1 mL/kg/day of fluid for at-risk malnourished adults. [NPIAP 2019]",
          "Correct anaemia, control blood sugar and treat pain, which otherwise keeps the patient immobile. [Brocklehurst 8e]",
          "Lift with a **draw sheet** by two people - never drag. [NPIAP 2019]",
        ],
      },
      {
        heading: "Wound care: debridement, dressings and infection",
        points: [
          "Principles of **TIME**: Tissue debridement, Infection or inflammation control, Moisture balance, Edge advancement. [EWMA 2018]",
          "Clean with **normal saline or potable water** at each change; avoid routine povidone-iodine or hydrogen peroxide on granulating tissue. [NPIAP 2019]",
          "**Stage 1:** off-load, protect with a transparent film or silicone foam; no dressing heals it - pressure relief does. [NPIAP 2019]",
          "**Stage 2:** hydrocolloid or thin foam dressing changed every 3-5 days, or paraffin gauze where cost matters. [NPIAP 2019]",
          "**Stage 3-4:** fill dead space loosely; use **foam or alginate for heavy exudate** and **hydrogel for dry wounds**, changed daily to alternate days. [NPIAP 2019]",
          "**Sharp debridement** removes slough and necrosis at the bedside; enzymatic (collagenase) or autolytic (hydrogel under film) debridement suits frail home patients. [Bailey and Love 28e]",
          "Do not debride a **stable dry heel eschar** without vascular assessment - check pulses and ABPI first. [NPIAP 2019]",
          "Suspect infection when there is **increasing pain, spreading erythema, foul odour, purulent exudate, friable granulation or delayed healing**. [NPIAP 2019]",
          "Local infection: topical silver or cadexomer iodine for 2 weeks; spreading cellulitis needs systemic antibiotics after a **deep tissue culture**, not a surface swab. [NPIAP 2019]",
          "Empirical oral choice for cellulitis around an ulcer: **amoxicillin-clavulanate 625 mg TDS for 7 days**, adjusted to culture. [NICE NG141 2019]",
          "**Negative pressure wound therapy** at -125 mmHg speeds granulation in clean stage 3-4 ulcers and is available in district hospitals. [Bailey and Love 28e]",
          "Treat pain before dressing changes with **paracetamol 1 g** or topical lignocaine gel. [NPIAP 2019]",
        ],
      },
      {
        heading: "Surgical options, complications and referral",
        points: [
          "**Surgical debridement** is needed for extensive necrosis, abscess, undermining or sepsis. [Sabiston 22e]",
          "Definitive closure of chronic stage 3-4 ulcers uses **myocutaneous or fasciocutaneous flaps** - gluteal rotation for sacral, tensor fascia lata for trochanteric, hamstring for ischial. [Bailey and Love 28e]",
          "Flap surgery succeeds only after **nutrition is corrected, spasticity controlled, faecal diversion if needed and a home off-loading plan in place** - recurrence reaches 30-60 per cent otherwise. [Sabiston 22e]",
          "**Osteomyelitis** complicates about a quarter of non-healing stage 4 ulcers - suspect if bone is probed or healing stalls; confirm with MRI or bone biopsy. [Harrison 22e]",
          "Other complications: **cellulitis, abscess, sepsis, septic arthritis, sinus tracts, heterotopic calcification and Marjolin ulcer** (squamous carcinoma in a chronic ulcer). [Bailey and Love 28e]",
          "Protein loss through a large exudating ulcer worsens **hypoalbuminaemia** and anaemia, creating a vicious cycle. [Brocklehurst 8e]",
          "Pressure-ulcer sepsis is a leading cause of death in paraplegics and bedridden elderly. [Harrison 22e]",
          "Refer to a surgeon or plastic surgeon for **stage 3-4 ulcers, undermining, suspected osteomyelitis, abscess or no improvement in 2 weeks**. [NPIAP 2019]",
          "Refer for admission if there is **fever with rigors, hypotension, confusion or rapidly spreading cellulitis**. [NICE NG51 2024]",
        ],
      },
      {
        heading: "Caregiver training and the family physician at home visits",
        points: [
          "Teach the caregiver a **turning chart** with times and positions, pinned beside the bed. [NPIAP 2019]",
          "Train the caregiver to **inspect the skin twice daily** with a mirror or torch, especially sacrum and heels, and report any redness that persists 30 minutes after repositioning. [NPIAP 2019]",
          "Demonstrate draw-sheet lifting, 30-degree tilt, heel floating and keeping sheets dry and wrinkle-free. [NPIAP 2019]",
          "In low-resource homes, a **foam mattress with a cotton cover** and pillows are acceptable when air mattresses are unaffordable; ask about ASHA and NPHCE support for home aids. [NPHCE 2021]",
          "At each home visit the family physician **stages and measures** the wound, reviews nutrition, pain, continence, blood sugar and caregiver fatigue. [Brocklehurst 8e]",
          "Screen the caregiver for **burnout and depression** - neglect is often exhaustion, not abuse, but consider elder abuse if ulcers are severe and unexplained. [Brocklehurst 8e]",
          "Discharge planning after stroke or hip fracture should start **before** the patient leaves hospital with a Braden score and home-equipment plan. [NPIAP 2019]",
          "Involve **physiotherapy for mobilisation and spasticity**, a dietitian and the palliative care team where the goal is comfort. [NPHCE 2021]",
          "In end-of-life care, a **Kennedy terminal ulcer** may appear suddenly on the sacrum in the last days - explain it to the family to prevent blame. [Brocklehurst 8e]",
          "Document stage, size and photographs - pressure injuries in institutions are a **common source of negligence complaints**. [NMC RMP Regulations 2023]",
        ],
      },
    ],
    tables: [
      {
        heading: "NPIAP staging classification of pressure injury",
        columns: ["Stage", "Depth", "Appearance", "Dressing and action"],
        rows: [
          ["Stage 1", "Intact skin", "Non-blanchable erythema; warmth or purple hue in dark skin", "Off-load, film or silicone foam, barrier cream"],
          ["Stage 2", "Partial thickness", "Pink moist dermis or serum blister, no slough", "Hydrocolloid or thin foam, change 3-5 days"],
          ["Stage 3", "Full thickness skin", "Fat visible, slough, undermining possible", "Debride, alginate or foam, fill cavity, consider NPWT"],
          ["Stage 4", "Full thickness tissue", "Bone, tendon or muscle exposed or palpable", "Debride, exclude osteomyelitis, surgical referral for flap"],
          ["Unstageable", "Obscured", "Base covered by slough or eschar", "Debride to stage, but leave stable dry heel eschar"],
          ["DTPI", "Deep", "Persistent maroon or purple area or blood blister", "Off-load urgently, watch for evolution over 72 hours"],
        ],
      },
      {
        heading: "Braden scale risk score bands",
        columns: ["Score", "Risk", "Surface", "Repositioning"],
        rows: [
          ["19-23", "No risk", "Standard mattress", "Encourage mobility"],
          ["15-18", "Mild", "High-spec foam", "2-4 hourly turns"],
          ["13-14", "Moderate", "High-spec foam, heel off-loading", "2 hourly with 30-degree tilt"],
          ["10-12", "High", "Alternating-pressure air mattress", "2 hourly plus small shifts"],
          ["9 or less", "Very high", "Dynamic air mattress, specialist review", "2 hourly, dietitian, continence plan"],
        ],
      },
    ],
    redFlags: [
      "Fever, rigors, hypotension or new confusion in a patient with a pressure ulcer - sepsis.",
      "Rapidly spreading erythema, crepitus or foul-smelling necrosis - necrotising infection.",
      "Bone palpable on probing or a non-healing stage 4 ulcer - osteomyelitis.",
      "Black heel eschar with absent foot pulses - critical limb ischaemia.",
      "Heaped, everted or bleeding edge in a long-standing ulcer - Marjolin ulcer, biopsy.",
      "Multiple severe ulcers with poor hygiene and unexplained injuries - consider elder neglect.",
      "Stage 3-4 ulcer failing to improve after 2 weeks of optimal care.",
    ],
    pearls: [
      "Pressure injury starts deep at bone and muscle - the skin shows only the tip of the iceberg.",
      "Capillary closing pressure is 32 mmHg; a standard mattress generates two to three times that over the sacrum.",
      "Staging never goes backwards - a healing stage 4 stays a healing stage 4.",
      "A Braden score of 18 or less means at risk; 9 or less means very high risk.",
      "Head end at 30 degrees or less, heels floating and 2-hourly turns are the core of prevention.",
      "No donut rings and no massage of reddened skin.",
      "Leave stable dry heel eschar alone and check the pulses.",
      "Deep tissue culture, not a surface swab, guides antibiotics.",
      "Flaps fail without nutrition, continence control and a home off-loading plan.",
      "A Kennedy terminal ulcer in the dying patient should be explained to the family in advance.",
    ],
    mcqs: [
      {
        id: "geriatrics-ethics-pressure-ulcers-q1",
        stem: "A 78-year-old bedridden woman after hip fracture has a sacral wound with full-thickness skin loss, visible subcutaneous fat and yellow slough at the base, but no bone or tendon is seen. What is the NPIAP stage?",
        options: [
          "Stage 2",
          "Stage 3",
          "Stage 4",
          "Deep tissue pressure injury",
        ],
        answer: 1,
        explanation:
          "Visible fat with slough but no exposed bone, tendon or muscle is stage 3. Stage 2 is partial thickness without slough, stage 4 needs exposed or palpable bone, tendon or muscle, and deep tissue injury refers to intact or blistered maroon discolouration.",
        difficulty: "easy",
      },
      {
        id: "geriatrics-ethics-pressure-ulcers-q2",
        stem: "A caregiver of a hemiplegic man asks how to protect his heels in bed. Which advice is correct?",
        options: [
          "Place a water-filled glove under each heel",
          "Massage the heels with oil twice daily",
          "Place a pillow under the calves so the heels float free of the mattress",
          "Keep the head end raised at 60 degrees",
        ],
        answer: 2,
        explanation:
          "Heel off-loading by floating the heels with support under the calves is recommended by NPIAP. Water gloves and ring devices concentrate pressure, massage damages deep tissue, and raising the head end above 30 degrees increases sacral shear.",
        difficulty: "easy",
      },
      {
        id: "geriatrics-ethics-pressure-ulcers-q3",
        stem: "Which Braden score identifies a patient at very high risk of pressure injury?",
        options: [
          "20",
          "16",
          "13",
          "9",
        ],
        answer: 3,
        explanation:
          "Braden scores range from 6 to 23, and a lower score means higher risk: 9 or less is very high risk, 10-12 high, 13-14 moderate and 15-18 mild. A score of 20 carries no risk and 16 only mild risk.",
        difficulty: "moderate",
      },
      {
        id: "geriatrics-ethics-pressure-ulcers-q4",
        stem: "A paraplegic man has a sacral stage 4 ulcer that has not healed for 3 months despite good care; bone is felt on probing and ESR is 90 mm/h. What is the most likely complication?",
        options: [
          "Osteomyelitis of the sacrum",
          "Marjolin ulcer",
          "Heterotopic ossification",
          "Incontinence-associated dermatitis",
        ],
        answer: 0,
        explanation:
          "A positive probe-to-bone test, high ESR and a non-healing stage 4 ulcer strongly suggest osteomyelitis, confirmed by MRI or bone biopsy. Marjolin ulcer needs years and an everted edge, heterotopic ossification does not raise ESR this way, and dermatitis is superficial.",
        difficulty: "moderate",
      },
      {
        id: "geriatrics-ethics-pressure-ulcers-q5",
        stem: "An elderly man has a dry, stable black eschar over the heel with no erythema, fluctuance or drainage. Dorsalis pedis pulse is absent. What is the best next step?",
        options: [
          "Sharp debridement of the eschar at the bedside",
          "Apply hydrogel under film to soften the eschar",
          "Leave the eschar intact, off-load and assess arterial supply",
          "Start oral ciprofloxacin for 6 weeks",
        ],
        answer: 2,
        explanation:
          "Stable dry heel eschar acts as a natural biological cover and should not be debrided, especially when perfusion is doubtful; ABPI or Doppler is needed. Debridement or softening risks converting it to an open ischaemic wound, and antibiotics are not indicated without infection.",
        difficulty: "hard",
      },
    ],
    theory: [
      {
        id: "geriatrics-ethics-pressure-ulcers-t1",
        paper: "III",
        kind: "long",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question:
          "A 70-year-old hemiplegic man is being discharged home after a stroke. Describe the pathogenesis and staging of pressure ulcers and outline a home-based prevention plan. [3+3+4]",
        openingLines: [
          "A pressure injury is localised damage to skin and underlying tissue over a bony prominence caused by sustained pressure or pressure with shear (NPIAP 2019).",
          "It affects up to one in five home-bound elderly after stroke and is largely preventable by caregiver-led repositioning, support surfaces and nutrition.",
        ],
        answer: [
          {
            heading: "Pathogenesis",
            points: [
              "Pressure above capillary closing pressure (32 mmHg) for over 2 hours causes ischaemia, deepest at the bone-muscle interface.",
              "Shear (head end above 30 degrees), friction (dragging) and moisture (incontinence) add damage.",
              "Intrinsic factors: immobility, sensory loss, malnutrition, anaemia, diabetes, age.",
            ],
          },
          {
            heading: "NPIAP staging",
            points: [
              "Stage 1 non-blanchable erythema; stage 2 partial thickness; stage 3 full-thickness with fat; stage 4 bone or tendon exposed.",
              "Unstageable - base obscured by slough or eschar; deep tissue pressure injury - maroon discolouration or blood blister.",
            ],
          },
          {
            heading: "Risk assessment",
            points: [
              "Braden scale on discharge and at each visit; 18 or less at risk.",
              "Sites: sacrum, heels, trochanters, occiput, scapulae, ischial tuberosities when sitting.",
            ],
          },
          {
            heading: "Home prevention plan (SSKIN)",
            points: [
              "Surface: high-spec foam or alternating-pressure air mattress; no donut rings.",
              "Skin inspection twice daily; Keep moving - turning chart every 2 hours, 30-degree tilt, heels floating.",
              "Incontinence care with barrier cream; Nutrition 30-35 kcal/kg and protein 1.25-1.5 g/kg.",
              "Caregiver training, physiotherapy, caregiver burnout screening, family physician review of wound and nutrition.",
            ],
          },
        ],
        mustDraw: ["Diagram of pressure-prone sites in supine, lateral and sitting positions", "NPIAP staging table"],
        markSplit: [
          { part: "Pathogenesis", marks: 3 },
          { part: "Staging", marks: 3 },
          { part: "Home prevention plan", marks: 4 },
        ],
        keywords: ["pressure ulcer", "Braden", "SSKIN", "NPIAP", "hemiplegia"],
      },
      {
        id: "geriatrics-ethics-pressure-ulcers-t2",
        paper: "III",
        kind: "short-note",
        marks: 10,
        minutes: 18,
        frequency: "less-common",
        question:
          "Management of a sacral stage 4 pressure ulcer: wound care, complications and indications for surgery. [4+3+3]",
        openingLines: [
          "A stage 4 pressure injury is full-thickness tissue loss with exposed or palpable bone, tendon or muscle (NPIAP 2019).",
          "Management combines off-loading, debridement, moist wound healing, infection control and nutrition, with flap closure for selected patients.",
        ],
        answer: [
          {
            heading: "Wound care",
            points: [
              "Off-load with air mattress and 2-hourly turns; correct nutrition and anaemia.",
              "Sharp or surgical debridement of necrosis; saline cleansing; alginate or foam to fill cavity; NPWT at -125 mmHg.",
              "Deep tissue culture and systemic antibiotics for spreading infection.",
            ],
          },
          {
            heading: "Complications",
            points: [
              "Cellulitis, abscess, osteomyelitis, sepsis, septic arthritis, sinus, Marjolin ulcer, hypoalbuminaemia.",
            ],
          },
          {
            heading: "Surgery",
            points: [
              "Indications: extensive necrosis, abscess, osteomyelitis, failure to heal with optimal care.",
              "Gluteal rotation or myocutaneous flap after nutrition, continence and spasticity are optimised.",
            ],
          },
        ],
        mustDraw: ["TIME wound-bed preparation flow"],
        markSplit: [
          { part: "Wound care", marks: 4 },
          { part: "Complications", marks: 3 },
          { part: "Surgery", marks: 3 },
        ],
        keywords: ["stage 4 pressure ulcer", "debridement", "NPWT", "flap"],
      },
    ],
    references: [
      "NPIAP/EPUAP/PPPIA Prevention and Treatment of Pressure Ulcers/Injuries: Clinical Practice Guideline, 3rd ed, 2019",
      "NICE CG179 Pressure ulcers: prevention and management, 2014 (reviewed 2024)",
      "Bailey and Love's Short Practice of Surgery, 28th ed, 2023",
      "Sabiston Textbook of Surgery, 22nd ed, 2025",
      "Brocklehurst's Textbook of Geriatric Medicine and Gerontology, 8th ed, 2017",
      "Harrison's Principles of Internal Medicine, 22nd ed, 2025",
      "NPHCE Operational Guidelines, MoHFW, 2021",
    ],
  },
  {
    id: "geriatrics-ethics-medicolegal-negligence-ethics",
    title: "Medical ethics, NMC regulations, medical negligence and the medico-legal case",
    oneLiner:
      "Medical negligence is **breach of a legal duty of care by a doctor, judged against the standard of a reasonably competent practitioner (Bolam test), that directly causes damage to the patient**; in India it is actionable in civil courts and Consumer Commissions under the Consumer Protection Act 2019, as professional misconduct under the NMC Registered Medical Practitioner (Professional Conduct) Regulations 2023, and as a crime under **section 106(1) of the Bharatiya Nyaya Sanhita 2023** only when it is gross, as laid down in Jacob Mathew (2005).",
    frequency: "core",
    keywords: [
      "medical ethics",
      "autonomy beneficence non-maleficence justice",
      "NMC Professional Conduct Regulations 2023",
      "medical negligence",
      "Bolam test",
      "Jacob Mathew",
      "BNS 106",
      "Bharatiya Nyaya Sanhita",
      "BNSS",
      "Bharatiya Sakshya Adhiniyam",
      "Consumer Protection Act 2019",
      "V P Shantha",
      "medico-legal case",
      "MLC",
      "New Drugs and Clinical Trials Rules 2019",
      "ICMR ethical guidelines 2017",
      "UCPMP 2024",
      "indemnity insurance",
      "violence against doctors",
      "informed consent",
    ],
    sections: [
      {
        heading: "Four principles of ethics in family practice",
        points: [
          "Beauchamp and Childress describe four **prima facie principles**: autonomy, beneficence, non-maleficence and justice - none automatically overrides another. [Beauchamp and Childress 8e 2019]",
          "**Autonomy:** a competent adult may refuse treatment, e.g. a diabetic refusing insulin after full explanation - document the counselling, do not coerce. [Beauchamp and Childress 8e 2019]",
          "Autonomy requires **informed consent** - nature of procedure, material risks, alternatives and the option of no treatment, in a language the patient understands. [Samira Kohli v Prabha Manchanda SC 2008]",
          "**Beneficence:** acting in the patient's best interest, e.g. advising an elderly driver with dementia to stop driving. [Beauchamp and Childress 8e 2019]",
          "**Non-maleficence** (primum non nocere): avoiding harm, e.g. not prescribing antibiotics for viral URI or benzodiazepines long-term to the elderly. [Beauchamp and Childress 8e 2019]",
          "**Justice:** fair allocation of resources, e.g. triage in a busy OPD or equitable use of PM-JAY beds regardless of caste or ability to pay. [Park 28e]",
          "**Confidentiality** may be breached only when required by law (notifiable disease, court order, POCSO), or to protect an identifiable third party at serious risk. [NMC RMP Regulations 2023]",
          "Consent of a minor under 18 for treatment is taken from the guardian; in emergencies the doctor may act in good faith without consent under **BNS 2023 s.30**. [BNS 2023]",
          "Good-faith acts with consent for the patient's benefit are protected by **BNS 2023 s.26**, and with guardian consent for a child under 12 by **s.27**. [BNS 2023]",
          "Mental Healthcare Act 2017 allows **advance directives** and nominated representatives, extending autonomy to future incapacity. [MHCA 2017]",
          "Passive euthanasia and living wills are lawful under **Common Cause v Union of India 2018**, with the procedure simplified in 2023. [Common Cause v UoI SC 2018/2023]",
        ],
      },
      {
        heading: "NMC Professional Conduct Regulations 2023",
        points: [
          "The **NMC Registered Medical Practitioner (Professional Conduct) Regulations 2023** were notified in August 2023 to replace the IMC (Professional Conduct, Etiquette and Ethics) Regulations 2002, then placed in abeyance pending review, so exam answers should quote both. [NMC RMP Regulations 2023]",
          "Every doctor should **prescribe drugs by generic name, legibly, preferably in capital letters**, and avoid unnecessary or irrational fixed-dose combinations. [NMC RMP Regulations 2023]",
          "The doctor must display the **NMC unique registration number** on prescriptions, certificates and receipts. [NMC RMP Regulations 2023]",
          "Doctors and their families **must not accept gifts, travel, hospitality, cash or monetary grants** from pharmaceutical companies or the allied health sector. [NMC RMP Regulations 2023]",
          "Doctors should not attend **pharma-sponsored seminars, workshops or CPD events** except as transparent, disclosed participation not involving a direct or indirect benefit. [NMC RMP Regulations 2023]",
          "Licence renewal requires **Continuing Professional Development - 50 credit hours in every 5-year cycle**. [NMC RMP Regulations 2023]",
          "A doctor may **decline to treat** an abusive or violent patient or relative (reported and documented), but **never in an emergency**. [NMC RMP Regulations 2023]",
          "Medical records must be maintained for **3 years** from the start of treatment, and the IMC 2002 standard is supply of records on request within **72 hours**. [IMC Regulations 2002]",
          "Telemedicine consultations must follow the **Telemedicine Practice Guidelines 2020**, with the same standard of care as in-person practice. [MoHFW/NMC 2020]",
          "Advertisement is restricted to name, qualifications, specialty and address; **patient testimonials, before-after photos and paid promotion** on social media are prohibited. [NMC RMP Regulations 2023]",
          "Complaints go first to the **State Medical Council**, with appeal to the **Ethics and Medical Registration Board** of NMC under the NMC Act 2019. [NMC Act 2019]",
          "Penalties range from warning and fine to **suspension of the licence** for a defined period. [NMC RMP Regulations 2023]",
        ],
      },
      {
        heading: "Medical negligence: civil standard, Bolam and Jacob Mathew",
        points: [
          "Negligence has four elements - **Duty, Dereliction (breach), Direct causation and Damage** - all must be proved by the complainant. [Reddy 35e]",
          "**Bolam test** (UK 1957): a doctor is not negligent if he acted in accordance with a practice accepted as proper by a responsible body of medical opinion. [Bolam v Friern HMC 1957]",
          "**Bolitho** (UK 1997) adds that the professional opinion must itself withstand logical analysis. [Bolitho v City and Hackney HA 1997]",
          "**Jacob Mathew v State of Punjab (2005)** held that criminal liability needs **gross negligence or recklessness**, not a mere error of judgement. [Jacob Mathew SC 2005]",
          "Jacob Mathew: a private criminal complaint must be supported by **credible opinion of another competent doctor**, and the investigating officer should obtain an independent medical opinion before proceeding. [Jacob Mathew SC 2005]",
          "Jacob Mathew: a doctor should **not be arrested routinely** merely because a charge is levelled, unless arrest is needed for investigation. [Jacob Mathew SC 2005]",
          "**Kusum Sharma v Batra Hospital (2010)** summarised the principles - a doctor is not liable for choosing one of two accepted methods. [Kusum Sharma SC 2010]",
          "**Res ipsa loquitur** (the thing speaks for itself), e.g. a swab left in the abdomen or wrong-side surgery, shifts the burden to the doctor. [Reddy 35e]",
          "Hospitals carry **vicarious liability** for employees and a non-delegable duty for systems failure. [Reddy 35e]",
          "**Contributory negligence** - a patient ignoring advice or leaving against medical advice - reduces compensation. [Reddy 35e]",
          "Commonest negligence claims in primary care: **failure to refer in time, missed diagnosis, drug reactions without test dose or history, and no consent**. [Reddy 35e]",
        ],
      },
      {
        heading: "Criminal law: BNS, BNSS and BSA 2023",
        points: [
          "From **1 July 2024** the Bharatiya Nyaya Sanhita (BNS), Bharatiya Nagarik Suraksha Sanhita (BNSS) and Bharatiya Sakshya Adhiniyam (BSA) 2023 replaced the IPC, CrPC and Indian Evidence Act. [MHA Notification 2024]",
          "**BNS s.106(1)** (old IPC 304A): death by a rash or negligent act - up to **5 years** and fine. [BNS 2023]",
          "BNS s.106(1) proviso: if done by a **registered medical practitioner while performing a medical procedure**, punishment is up to **2 years** and fine - a lighter band for doctors. [BNS 2023]",
          "The Jacob Mathew requirement of **gross negligence** and prior independent medical opinion continues to govern prosecution under BNS s.106. [Jacob Mathew SC 2005]",
          "**Grievous hurt** under BNS s.116 now includes inability to follow ordinary pursuits for **15 days** (20 days under IPC) - relevant when writing the MLC opinion. [BNS 2023]",
          "BNSS s.173 governs registration of an **FIR** including Zero FIR and e-FIR (old CrPC 154). [BNSS 2023]",
          "**BNSS s.397** (old CrPC 357C): every public or private hospital must give **free first aid or treatment** to victims of rape and acid attack and inform the police. [BNSS 2023]",
          "BNSS s.184 (old CrPC 164A) mandates medical examination of a rape survivor with **consent within 24 hours** and report forwarded to the investigating officer within **7 days**. [BNSS 2023]",
          "BNSS s.194 (old CrPC 174) covers police inquest and s.196 (old CrPC 176) magistrate inquest, e.g. custodial death or dowry death. [BNSS 2023]",
          "**BSA s.39** (old IEA 45) makes the doctor's opinion admissible as expert evidence; **s.26** covers dying declarations. [BSA 2023]",
          "**BSA s.63** (old IEA 65B) governs electronic records - electronic health records and CCTV need a certificate to be admissible. [BSA 2023]",
        ],
      },
      {
        heading: "Consumer Protection Act 2019 and medical services",
        points: [
          "**Indian Medical Association v V P Shantha (1995)** brought paid medical services within the definition of service under consumer law. [V P Shantha SC 1995]",
          "Services rendered **free of charge to all** in government hospitals are excluded; free treatment of some patients in a paying hospital is covered. [V P Shantha SC 1995]",
          "In **Bar of Indian Lawyers v D K Gandhi (2024)** the Supreme Court excluded advocates and referred V P Shantha to a larger bench, but medical services remain covered until decided. [SC 2024]",
          "Pecuniary jurisdiction under the 2021 rules: **District Commission up to Rs 50 lakh, State Rs 50 lakh-2 crore, National Commission above Rs 2 crore**. [CPA Jurisdiction Rules 2021]",
          "Complaints must be filed within **2 years** of the cause of action, can be filed where the complainant lives, and online via **e-Daakhil**. [CPA 2019]",
          "No court fee barrier and no lawyer needed - which is why most negligence litigation against doctors in India is before Consumer Commissions. [CPA 2019]",
          "**V Kishan Rao (2010)** held that expert opinion is not mandatory in every consumer case, especially where res ipsa loquitur applies. [V Kishan Rao SC 2010]",
          "Mediation is encouraged under CPA 2019, and commissions can award **compensation plus costs** but cannot imprison for negligence. [CPA 2019]",
        ],
      },
      {
        heading: "The medico-legal case: when, how and police intimation",
        points: [
          "Register an **MLC** for injuries of any kind with suspicion of foul play, road traffic accidents, burns, poisoning, suspected homicide or suicide, and assault. [Reddy 35e]",
          "Also register MLC for **sexual assault, suspected criminal abortion, unconscious patient of unknown cause, brought-dead cases and custodial injuries**. [Reddy 35e]",
          "**Treat first, paperwork later** - Parmanand Katara (1989) makes emergency treatment an obligation that cannot wait for police. [Parmanand Katara SC 1989]",
          "**Good Samaritan** bystanders who bring accident victims cannot be detained or forced to be witnesses (Motor Vehicles Amendment Act 2019, s.134A). [MV Amendment Act 2019]",
          "Intimate the police in writing through the hospital police post or the nearest police station and record the **name, time and acknowledgement**. [Reddy 35e]",
          "Record **date and time, identification marks, informed consent, history in the patient's own words**, and each injury with type, site, size, age and weapon. [Reddy 35e]",
          "State nature as **simple or grievous** (BNS s.116), and keep samples sealed with a maintained chain of custody. [BNS 2023]",
          "Under **POCSO Act 2012 s.19**, any doctor who suspects sexual abuse of a child must report to the police or SJPU; failure is an offence. [POCSO Act 2012]",
          "Preserve MLC records **permanently or until the case concludes**, with signed carbon copies or electronic backup. [Reddy 35e]",
          "When referring a medico-legal patient, write a **referral note** with findings and treatment, and inform police of the transfer. [Reddy 35e]",
        ],
      },
      {
        heading: "Clinical trial ethics and relationships with industry",
        points: [
          "Clinical trials in India are governed by the **New Drugs and Clinical Trials Rules 2019** under the Drugs and Cosmetics Act, with CDSCO as Central Licensing Authority. [NDCT Rules 2019]",
          "Every trial needs approval of a **CDSCO-registered Ethics Committee** and prospective registration on **CTRI** before the first participant is enrolled. [NDCT Rules 2019]",
          "Approval timeline is **30 working days** for drugs discovered in India and **90 working days** for others. [NDCT Rules 2019]",
          "Serious adverse events must be reported by the investigator **within 24 hours**; the sponsor must give free medical management for as long as needed. [NDCT Rules 2019]",
          "**Compensation** is mandatory for trial-related injury or death, calculated by the formula in the Seventh Schedule. [NDCT Rules 2019]",
          "**Audio-visual recording of informed consent** is required for vulnerable participants in new chemical entity trials. [NDCT Rules 2019]",
          "The **ICMR National Ethical Guidelines for Biomedical and Health Research Involving Human Participants 2017** set principles: essentiality, voluntariness, non-exploitation, privacy, risk minimisation and accountability. [ICMR 2017]",
          "Vaccine trials in emergencies (e.g. COVID-19) still require informed consent, DSMB oversight and EC approval - accelerated review, not reduced ethics. [ICMR 2017]",
          "The **Uniform Code for Pharmaceutical Marketing Practices 2024** bars companies from giving gifts, travel, hospitality or cash to doctors and their families. [UCPMP 2024]",
          "A family physician should **declare conflicts of interest**, refuse sponsored holidays and base prescribing on evidence and the National List of Essential Medicines. [NMC RMP Regulations 2023]",
        ],
      },
      {
        heading: "Defensive practice, indemnity and violence against doctors",
        points: [
          "**Defensive medicine** - unnecessary tests and referrals out of fear - raises costs and harm; good documentation and communication are the better protection. [Reddy 35e]",
          "Keep **contemporaneous, legible, dated and signed notes**; notes altered later destroy credibility. [Reddy 35e]",
          "**Professional indemnity insurance** covers legal costs and compensation for civil claims; clinics should also hold establishment cover. [Reddy 35e]",
          "Most disputes arise from **poor communication**, unmet expectations and cost - explain prognosis, costs and risks before starting. [Reddy 35e]",
          "The **Epidemic Diseases (Amendment) Act 2020** makes violence against healthcare workers during epidemics cognisable and non-bailable, **3 months-5 years**, and 6 months-7 years for grievous hurt. [Epidemic Diseases Amendment Act 2020]",
          "About 20 states have **Medicare Service Persons (Prevention of Violence) Acts**, making attacks on doctors and hospital property cognisable offences. [State Acts]",
          "After the 2024 Kolkata incident, the Supreme Court set up a **National Task Force** on safety of health workers, and NMC advised an **institutional FIR within 6 hours** of violence. [SC suo motu 2024; NMC 2024]",
          "Assault on a doctor is also punishable under **BNS s.115 and s.117** (hurt and grievous hurt), and s.121 when the doctor is a public servant on duty. [BNS 2023]",
          "Prevention: triage signage, a trained security desk, CCTV, **breaking bad news in a private room with a senior present**, and a grievance officer. [Reddy 35e]",
        ],
      },
    ],
    tables: [
      {
        heading: "Old versus new criminal law sections for doctors",
        columns: ["Subject", "Old law", "New law (from 1 July 2024)"],
        rows: [
          ["Death by negligence", "IPC 304A", "BNS 106(1) - up to 2 years for registered medical practitioner"],
          ["Good-faith act with consent", "IPC 88", "BNS 26"],
          ["Consent of guardian for child", "IPC 89", "BNS 27"],
          ["Emergency act without consent", "IPC 92", "BNS 30"],
          ["Grievous hurt", "IPC 320 (20 days)", "BNS 116 (15 days)"],
          ["FIR", "CrPC 154", "BNSS 173"],
          ["Free treatment of rape or acid victims", "CrPC 357C", "BNSS 397"],
          ["Examination of rape survivor", "CrPC 164A", "BNSS 184"],
          ["Police inquest", "CrPC 174", "BNSS 194"],
          ["Expert opinion", "IEA 45", "BSA 39"],
          ["Electronic records", "IEA 65B", "BSA 63"],
        ],
      },
      {
        heading: "Types of negligence liability",
        columns: ["Type", "Forum", "Standard of proof", "Outcome"],
        rows: [
          ["Civil", "Civil court or Consumer Commission", "Balance of probabilities; Bolam test", "Compensation"],
          ["Criminal", "Criminal court (BNS 106)", "Beyond reasonable doubt; gross negligence (Jacob Mathew)", "Imprisonment or fine"],
          ["Professional misconduct", "State Medical Council, NMC EMRB", "Breach of NMC regulations", "Warning, fine, licence suspension"],
        ],
      },
    ],
    redFlags: [
      "Any injury, burn, poisoning or assault presenting to the clinic - register an MLC and inform police, but treat first.",
      "Suspected child sexual abuse - mandatory report under POCSO s.19.",
      "Patient deteriorating beyond your facility's capability - refer in writing without delay; delay is the commonest negligence finding.",
      "Relatives becoming aggressive - de-escalate, call security, document, and file an institutional FIR if violence occurs.",
      "Patient leaving against medical advice - document the risks explained and obtain a signed LAMA form.",
      "Serious adverse event in a trial participant - report within 24 hours to CDSCO, sponsor and EC.",
      "Request to alter notes after an adverse event - never do so; add a dated addendum.",
    ],
    pearls: [
      "Four Ds of negligence: Duty, Dereliction, Direct causation, Damage.",
      "Civil negligence needs Bolam; criminal negligence needs gross recklessness (Jacob Mathew 2005).",
      "BNS 106(1): up to 5 years generally but up to 2 years for a registered medical practitioner during a medical procedure.",
      "Grievous hurt threshold fell from 20 to 15 days under BNS s.116.",
      "V P Shantha 1995 brought paid medical services under consumer law; District Commission jurisdiction is up to Rs 50 lakh.",
      "Treat first, inform police next - Parmanand Katara 1989.",
      "BNSS s.397: no hospital may refuse free first aid to rape or acid-attack victims.",
      "Generic names in capitals, no pharma gifts, 50 CPD hours in 5 years - the NMC 2023 headlines.",
      "No trial before EC approval and CTRI registration; SAE report in 24 hours.",
      "Good notes are the best indemnity.",
    ],
    mcqs: [
      {
        id: "geriatrics-ethics-medicolegal-negligence-ethics-q1",
        stem: "A patient dies after a surgical procedure and relatives file a criminal complaint against the surgeon. Under the Bharatiya Nyaya Sanhita 2023, which section applies and what is the maximum imprisonment for a registered medical practitioner?",
        options: [
          "Section 106(1), up to 2 years and fine",
          "Section 105, up to 10 years",
          "Section 106(2), up to 10 years",
          "Section 115, up to 1 year",
        ],
        answer: 0,
        explanation:
          "BNS s.106(1), which replaced IPC 304A, punishes death by negligence with up to 5 years, but its proviso limits it to 2 years and fine for a registered medical practitioner performing a medical procedure. Section 105 is culpable homicide, s.106(2) is hit-and-run, and s.115 is voluntarily causing hurt.",
        difficulty: "moderate",
      },
      {
        id: "geriatrics-ethics-medicolegal-negligence-ethics-q2",
        stem: "According to Jacob Mathew v State of Punjab (2005), what is required before a doctor can be prosecuted for criminal negligence on a private complaint?",
        options: [
          "A post-mortem report showing any deviation from textbook practice",
          "Proof of civil negligence on a balance of probabilities",
          "A prima facie case supported by credible opinion of another competent doctor",
          "Prior approval of the National Medical Commission",
        ],
        answer: 2,
        explanation:
          "Jacob Mathew requires gross negligence and a complaint supported by credible opinion from another competent doctor, with the investigator seeking independent medical opinion. A mere deviation or civil standard is insufficient for criminal liability, and NMC approval is not a legal precondition.",
        difficulty: "moderate",
      },
      {
        id: "geriatrics-ethics-medicolegal-negligence-ethics-q3",
        stem: "A man claims compensation of Rs 1.2 crore for alleged negligence in a private hospital. Under the Consumer Protection Act 2019 and its 2021 jurisdiction rules, where should he file?",
        options: [
          "District Consumer Commission",
          "State Consumer Commission",
          "National Consumer Commission",
          "State Medical Council",
        ],
        answer: 1,
        explanation:
          "Since the 2021 rules, the District Commission handles claims up to Rs 50 lakh, the State Commission Rs 50 lakh to Rs 2 crore, and the National Commission above Rs 2 crore, so Rs 1.2 crore goes to the State Commission. A medical council deals with misconduct, not compensation.",
        difficulty: "hard",
      },
      {
        id: "geriatrics-ethics-medicolegal-negligence-ethics-q4",
        stem: "A 22-year-old woman reporting sexual assault arrives at a private nursing home at night. What is the legal obligation of the hospital?",
        options: [
          "Refer her to a government hospital because only government doctors can examine rape survivors",
          "Wait for police before any examination or treatment",
          "Examine only after a magistrate's order",
          "Provide free first aid and treatment and inform the police",
        ],
        answer: 3,
        explanation:
          "BNSS s.397 (old CrPC 357C) obliges every public and private hospital to give free first aid or treatment to rape and acid-attack victims and inform the police. Refusing, delaying for police or insisting on a magistrate's order are unlawful; any registered doctor may examine with consent under BNSS s.184.",
        difficulty: "moderate",
      },
      {
        id: "geriatrics-ethics-medicolegal-negligence-ethics-q5",
        stem: "A family physician is invited by a drug company to present at a sponsored conference in Thailand with family air tickets. Which statement is correct under the NMC 2023 regulations and UCPMP 2024?",
        options: [
          "Acceptable if the physician prescribes other brands too",
          "Not permitted - travel and hospitality from pharmaceutical companies to doctors and families is prohibited",
          "Acceptable if declared in the income tax return",
          "Acceptable only for doctors with over 10 years of practice",
        ],
        answer: 1,
        explanation:
          "The NMC Professional Conduct Regulations 2023 and the Uniform Code for Pharmaceutical Marketing Practices 2024 both prohibit gifts, travel and hospitality from pharmaceutical companies to doctors or their families. Declaring it, prescribing other brands or seniority does not make it ethical.",
        difficulty: "easy",
      },
    ],
    theory: [
      {
        id: "geriatrics-ethics-medicolegal-negligence-ethics-t1",
        paper: "I",
        kind: "long",
        marks: 10,
        minutes: 18,
        frequency: "core",
        question:
          "Define medical negligence. Discuss civil and criminal liability of a family physician in India with reference to the Bharatiya Nyaya Sanhita 2023, the Consumer Protection Act 2019 and landmark judgements. Add a note on how to prevent litigation. [2+5+3]",
        openingLines: [
          "Medical negligence is breach of a duty of care owed by a doctor, judged against a reasonably competent practitioner, that directly causes damage to the patient.",
          "In India it attracts civil liability (courts and Consumer Commissions), criminal liability under BNS s.106(1) when gross, and disciplinary action under NMC regulations.",
        ],
        answer: [
          {
            heading: "Definition and elements",
            points: [
              "Four Ds: Duty, Dereliction, Direct causation, Damage.",
              "Bolam test (responsible body of opinion) with Bolitho logic; res ipsa loquitur in obvious cases.",
            ],
          },
          {
            heading: "Civil liability",
            points: [
              "CPA 2019 - V P Shantha 1995; District up to Rs 50 lakh, State to Rs 2 crore, National above; limitation 2 years.",
              "Vicarious liability of hospitals; contributory negligence reduces award.",
            ],
          },
          {
            heading: "Criminal liability",
            points: [
              "BNS s.106(1) (old IPC 304A): up to 2 years and fine for a registered medical practitioner during a procedure.",
              "Jacob Mathew 2005: gross negligence, credible independent medical opinion, no routine arrest.",
              "Protection for good-faith acts: BNS s.26, 27, 30.",
            ],
          },
          {
            heading: "Disciplinary liability",
            points: [
              "State Medical Council and NMC EMRB under NMC Professional Conduct Regulations 2023 - warning to licence suspension.",
            ],
          },
          {
            heading: "Prevention of litigation",
            points: [
              "Informed written consent, clear communication and cost estimates.",
              "Contemporaneous notes, timely written referral, adherence to guidelines, CPD.",
              "Indemnity insurance; avoid defensive medicine; grievance redressal.",
            ],
          },
        ],
        mustDraw: ["Table comparing civil, criminal and disciplinary liability", "Old IPC versus BNS section table"],
        markSplit: [
          { part: "Definition and elements", marks: 2 },
          { part: "Civil and criminal liability", marks: 5 },
          { part: "Prevention", marks: 3 },
        ],
        keywords: ["negligence", "BNS 106", "Jacob Mathew", "CPA 2019"],
      },
      {
        id: "geriatrics-ethics-medicolegal-negligence-ethics-t2",
        paper: "I",
        kind: "short-note",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question:
          "Ethical issues in conducting a clinical drug trial in India: regulatory framework, informed consent and compensation for trial-related injury. [4+3+3]",
        openingLines: [
          "Clinical trials in India are regulated by the New Drugs and Clinical Trials Rules 2019 and guided by the ICMR National Ethical Guidelines 2017.",
          "Their core is respect for persons, independent ethics review, informed consent and mandatory compensation for trial-related harm.",
        ],
        answer: [
          {
            heading: "Regulatory framework",
            points: [
              "CDSCO as Central Licensing Authority; EC registered with CDSCO; CTRI registration before enrolment.",
              "Approval in 30 working days (Indian-discovered drugs) or 90 days; DSMB for high-risk trials.",
              "ICMR 2017 principles: essentiality, voluntariness, non-exploitation, privacy, accountability.",
            ],
          },
          {
            heading: "Informed consent",
            points: [
              "Written, in local language, with purpose, risks, benefits, alternatives, right to withdraw.",
              "Audio-visual recording for vulnerable participants in NCE trials; LAR consent for incapable; assent for children.",
            ],
          },
          {
            heading: "Safety and compensation",
            points: [
              "SAE reported within 24 hours; free medical management as long as required.",
              "Compensation by the Seventh Schedule formula for trial-related injury or death.",
            ],
          },
        ],
        mustDraw: ["Flow chart from protocol to EC approval, CTRI registration, consent and SAE reporting"],
        markSplit: [
          { part: "Regulatory framework", marks: 4 },
          { part: "Informed consent", marks: 3 },
          { part: "Compensation", marks: 3 },
        ],
        keywords: ["NDCT Rules 2019", "ICMR 2017", "ethics committee", "CTRI"],
      },
    ],
    references: [
      "NMC Registered Medical Practitioner (Professional Conduct) Regulations, 2023",
      "Bharatiya Nyaya Sanhita, Bharatiya Nagarik Suraksha Sanhita and Bharatiya Sakshya Adhiniyam, 2023 (in force 1 July 2024)",
      "Consumer Protection Act, 2019 and Consumer Protection (Jurisdiction) Rules, 2021",
      "Jacob Mathew v State of Punjab, (2005) 6 SCC 1",
      "New Drugs and Clinical Trials Rules, 2019, CDSCO",
      "ICMR National Ethical Guidelines for Biomedical and Health Research Involving Human Participants, 2017",
      "Uniform Code for Pharmaceutical Marketing Practices, Department of Pharmaceuticals, 2024",
      "Reddy KSN, The Essentials of Forensic Medicine and Toxicology, 35th ed",
    ],
  },
  // END-TOPICS
];

export default topics;
