import type { Topic } from "../../lib/types";

const topics: Topic[] = [
  {
    id: "gynaecology-amenorrhoea-menstrual-irregularity",
    title: "Amenorrhoea and menstrual irregularity",
    oneLiner:
      "**Primary amenorrhoea** is no menses by 15 years with normal secondary sexual characters (or by 13 years with none), and **secondary amenorrhoea** is cessation for 3 months after regular cycles or 6 months after irregular ones; after **excluding pregnancy**, causes are sorted by the **compartment approach** (outflow tract and uterus, ovary, pituitary, hypothalamus) using **TSH, prolactin, FSH/LH and pelvic ultrasound**, with **PCOS** the commonest cause of oligomenorrhoea.",
    frequency: "common",
    keywords: [
      "primary amenorrhoea",
      "secondary amenorrhoea",
      "oligomenorrhoea",
      "PCOS",
      "Rotterdam criteria",
      "hyperprolactinaemia",
      "premature ovarian insufficiency",
      "POI",
      "Turner syndrome",
      "MRKH syndrome",
      "imperforate hymen",
      "Asherman syndrome",
      "genital tuberculosis",
      "Sheehan syndrome",
      "functional hypothalamic amenorrhoea",
      "RED-S",
      "progesterone challenge test",
      "FIGO AUB",
      "cabergoline",
      "medroxyprogesterone",
    ],
    sections: [
      {
        heading: "Definitions and normal menstrual parameters",
        points: [
          "**Primary amenorrhoea** = no menarche by **15 years with normal growth and secondary sexual characteristics**, by **13 years with no breast development**, or **3 years after thelarche**. [ACOG CO 651 2015 reaffirmed 2024]",
          "**Secondary amenorrhoea** = absence of menses for **3 months in a woman with previously regular cycles, or 6 months** with previously irregular cycles. [Berek and Novak 16e]",
          "**FIGO 2018 normal cycle**: frequency **24-38 days**, cycle-to-cycle variation **7-9 days or less**, duration **8 days or less** and a volume that does not interfere with quality of life. [FIGO 2018]",
          "**Infrequent menstruation (oligomenorrhoea)** = cycles **longer than 38 days**; frequent = shorter than 24 days; the older terms polymenorrhoea and menorrhagia are discouraged. [FIGO 2018]",
          "Irregular cycles in the **first year after menarche** are a normal transition; **1-3 years after menarche**, cycles under 21 or over 45 days are irregular; **over 3 years after menarche**, under 21 or over 35 days, or fewer than 8 cycles a year. [PCOS Guideline 2023]",
          "Irregular menstruation from **ovulatory dysfunction is the 'O' of FIGO PALM-COEIN** for abnormal uterine bleeding, and it is the commonest non-structural cause. [FIGO 2018]",
          "Amenorrhoea is **physiological** before puberty, in **pregnancy and lactation**, and after menopause; the first step in every woman of reproductive age is to **exclude pregnancy**. [Berek and Novak 16e]",
          "Secondary amenorrhoea affects about **3-5 per cent** of women in a year; primary amenorrhoea is uncommon (under 1 per cent). [Berek and Novak 16e]",
          "**NFHS-5** shows **77 per cent of women aged 15-24 use a hygienic method of menstrual protection** and **59 per cent of girls aged 15-19 are anaemic** - both shape adolescent menstrual health in India. [NFHS-5]",
        ],
      },
      {
        heading: "Compartment approach and causes of primary amenorrhoea",
        points: [
          "The **compartment approach** locates the defect: **I - outflow tract and uterus; II - ovary; III - anterior pituitary; IV - hypothalamus and CNS**; plus general endocrine causes (thyroid, adrenal, PCOS). [Speroff 9e]",
          "The commonest causes of primary amenorrhoea are **gonadal dysgenesis (about 40-50 per cent, mostly Turner syndrome)**, **Mullerian agenesis (MRKH, about 15 per cent)**, and **constitutional delay or hypothalamic causes**. [Berek and Novak 16e]",
          "**Imperforate hymen / transverse vaginal septum** - a girl with normal secondary sexual characters, **cyclical lower abdominal pain, urinary retention** and a **bulging bluish membrane** (haematocolpos); treated by **cruciate hymenotomy** under anaesthesia. [Berek and Novak 16e]",
          "**MRKH syndrome** - **46,XX**, normal ovaries, normal breasts and pubic hair, **absent uterus and upper two-thirds of vagina**; associated **renal (30-40 per cent) and skeletal anomalies**, so do a renal ultrasound. [Berek and Novak 16e]",
          "MRKH management: **vaginal dilator therapy (Frank method) as first line**, vaginoplasty (McIndoe, Vecchietti, laparoscopic Davydov) if dilators fail, psychological support, and **gestational surrogacy**, which the **Surrogacy (Regulation) Act 2021** permits for absent uterus. [Berek and Novak 16e]",
          "**Complete androgen insensitivity syndrome** - **46,XY**, normal breasts, **scanty or absent pubic and axillary hair**, blind short vagina, testes in the abdomen or inguinal canal, male-range testosterone; **gonadectomy after puberty** because of malignancy risk. [Berek and Novak 16e]",
          "**Turner syndrome** (45,X or mosaic) - **short stature, webbed neck, shield chest, cubitus valgus, lymphoedema at birth, coarctation or bicuspid aortic valve, horseshoe kidney**, streak gonads and **high FSH**. [Turner Guideline 2024]",
          "Turner care: **growth hormone** from early childhood, **low-dose transdermal oestradiol from 11-12 years** to induce puberty, cardiac MRI and echo, renal ultrasound, hearing, thyroid and coeliac screening. [Turner Guideline 2024]",
          "**Swyer syndrome (46,XY pure gonadal dysgenesis)** - female phenotype with a uterus and streak gonads - needs **gonadectomy** because of a high risk of **gonadoblastoma/dysgerminoma**. [Berek and Novak 16e]",
          "**Constitutional delay** - family history of late puberty, short stature with **delayed bone age**, low-normal gonadotrophins, and spontaneous puberty later; **Kallmann syndrome** is GnRH deficiency with **anosmia**. [Speroff 9e]",
          "**Congenital adrenal hyperplasia (21-hydroxylase deficiency)** presents with ambiguous genitalia at birth or with hirsutism and irregular cycles later (non-classic); screen with **early-morning 17-hydroxyprogesterone**. [Berek and Novak 16e]",
        ],
      },
      {
        heading: "Causes of secondary amenorrhoea and oligomenorrhoea",
        points: [
          "**Pregnancy** is the commonest cause of secondary amenorrhoea - do a **urine pregnancy test** even when the woman says she is not sexually active. [Berek and Novak 16e]",
          "**PCOS** is the commonest pathological cause of oligomenorrhoea; Indian community studies report prevalence of about **6-10 per cent by NIH criteria** and higher by Rotterdam criteria. [PCOS Guideline 2023]",
          "**PCOS (Rotterdam, 2 of 3)**: **oligo- or anovulation, clinical or biochemical hyperandrogenism, polycystic ovarian morphology (20 or more follicles per ovary or volume 10 mL or more)** or raised AMH, after excluding other causes. [PCOS Guideline 2023]",
          "In **adolescents** PCOS needs **both ovulatory dysfunction and hyperandrogenism**; ultrasound and AMH are **not used within 8 years of menarche**. [PCOS Guideline 2023]",
          "**Hyperprolactinaemia** causes amenorrhoea and **galactorrhoea**; causes include **prolactinoma, drugs (risperidone, haloperidol, metoclopramide, domperidone, SSRIs)**, primary hypothyroidism, CKD and stalk compression. [Harrison 22e]",
          "**Hypothyroidism** (menorrhagia or oligomenorrhoea) and **hyperthyroidism** (oligomenorrhoea) both disturb cycles; TSH is a first-line test. [Berek and Novak 16e]",
          "**Premature ovarian insufficiency (POI)** - amenorrhoea or oligomenorrhoea for 4 months or more **before 40 years with FSH above 25 IU/L** (repeat in 4-6 weeks if in doubt); causes are idiopathic, **autoimmune, Turner mosaic, FMR1 premutation, chemotherapy, pelvic radiotherapy and surgery**. [ESHRE POI 2024]",
          "**Asherman syndrome** - intrauterine adhesions after **postpartum or post-abortal curettage** or infection; in India **genital tuberculosis** is an important cause of adhesions and amenorrhoea. [Berek and Novak 16e]",
          "**Sheehan syndrome** - pituitary necrosis after **severe postpartum haemorrhage**, presenting with **failure of lactation**, amenorrhoea, fatigue, hypothyroidism and adrenal insufficiency. [Williams 26e]",
          "**Iatrogenic** - **DMPA, LNG-IUS, continuous COC**, post-pill amenorrhoea (usually under 6 months), antipsychotics and chemotherapy. [Berek and Novak 16e]",
          "**Pituitary tumours and chronic illness** (CKD, liver disease, uncontrolled diabetes, TB, HIV) cause hypogonadotropic amenorrhoea. [Harrison 22e]",
          "**Perimenopause** - STRAW+10 defines the early transition by a **persistent 7 or more day difference in consecutive cycle length**, and the late transition by **60 days or more of amenorrhoea**. [Berek and Novak 16e]",
        ],
      },
      {
        heading: "Stress, weight loss, exercise and occupational factors",
        points: [
          "**Functional hypothalamic amenorrhoea (FHA)** results from suppressed GnRH pulsatility due to **stress, weight loss, excessive exercise or low energy availability**, with **low or normal LH/FSH and low oestradiol**. [Endocrine Society FHA 2017]",
          "**Relative Energy Deficiency in Sport (RED-S)**, which replaced the female athlete triad, links **low energy availability, menstrual dysfunction and low bone mineral density** with wider effects on health and performance. [IOC REDs 2023]",
          "**Anorexia nervosa** (BMI under 17.5, fear of weight gain, distorted body image) causes amenorrhoea, bradycardia, hypotension, lanugo and osteoporosis - a psychiatric and medical emergency when severe. [Kaplan and Sadock 12e]",
          "**Weight loss of 10-15 per cent** of body weight, or **BMI under 18.5**, is often enough to stop menstruation; **obesity** causes anovulation through insulin resistance and hyperandrogenism. [Speroff 9e]",
          "FHA management: **restore energy balance** (increase intake, reduce training), **CBT for stress**, and treat the eating disorder; menses return in most once weight and energy recover. [Endocrine Society FHA 2017]",
          "If FHA lasts **over 6 months** with low bone density, give **transdermal oestradiol 100 microgram/day with cyclic oral progestogen**, not COC, which does not protect bone as well. [Endocrine Society FHA 2017]",
          "**Night-shift and rotating-shift work** disturbs circadian rhythm and is linked to irregular cycles, dysmenorrhoea and subfertility. [Park 28e]",
          "**Occupational exposures** - organic solvents, pesticides, **lead and other heavy metals**, and endocrine disruptors such as **bisphenol A and phthalates** in plastics and factory work - are associated with menstrual irregularity. [Park 28e]",
          "Heavy manual labour, long working hours, **lack of toilets and menstrual hygiene facilities at work**, and reduced fluid intake to avoid using them affect menstrual health of Indian women workers. [Park 28e]",
          "The **Occupational Safety, Health and Working Conditions Code 2020** permits women's night work only with consent and safety provisions, and the family physician can advise on shift adjustment. [OSH Code 2020]",
          "Other lifestyle factors: **sleep deprivation, smoking, high caffeine, sedentary life and psychological stress** (examinations, bereavement, migration). [Berek and Novak 16e]",
        ],
      },
      {
        heading: "History and examination",
        points: [
          "**History**: age at **thelarche and menarche**, cycle pattern, last menstrual period, **sexual activity and contraception**, pregnancy, breastfeeding. [Berek and Novak 16e]",
          "Ask about **weight change, diet, exercise, stress, eating disorder symptoms**, shift work and occupational exposures. [Endocrine Society FHA 2017]",
          "Ask about **galactorrhoea, headache and visual disturbance** (pituitary), **hot flushes and vaginal dryness** (oestrogen deficiency), **hirsutism, acne and hair loss** (hyperandrogenism). [Berek and Novak 16e]",
          "Ask about **cyclical pelvic pain** (outflow obstruction), **previous D&C, postpartum or post-abortal infection, and tuberculosis** (Asherman), **PPH with failure of lactation** (Sheehan), chemotherapy or radiotherapy. [Berek and Novak 16e]",
          "Ask about **drugs** - antipsychotics, antiemetics, opioids, DMPA - and chronic illness, and a **family history** of delayed puberty, early menopause or infertility. [Berek and Novak 16e]",
          "**Examination**: height, weight, **BMI, waist**, BP, **Tanner staging** of breast and pubic hair, **Turner stigmata**, thyroid, **acanthosis nigricans** and signs of Cushing syndrome. [Berek and Novak 16e]",
          "Score **hirsutism by the modified Ferriman-Gallwey score** (4-6 or more is abnormal, lower cut-offs in some ethnic groups), and look for **virilisation - clitoromegaly, deep voice, male-pattern baldness** - which suggests a tumour. [PCOS Guideline 2023]",
          "Check **visual fields** (bitemporal hemianopia), **sense of smell** (Kallmann) and **expressible galactorrhoea**. [Harrison 22e]",
          "Inspect the **external genitalia and hymen**, and assess **vaginal length** gently; a speculum or bimanual examination is done only if the woman is sexually active and consents. [Berek and Novak 16e]",
          "Look for **inguinal or labial masses** (testes in AIS) and signs of chronic illness or eating disorder (lanugo, bradycardia, parotid enlargement). [Berek and Novak 16e]",
        ],
      },
      {
        heading: "Investigations",
        points: [
          "**Step 1**: **urine or serum hCG** in every case, then **TSH, prolactin, FSH, LH and oestradiol**. [Berek and Novak 16e]",
          "**Prolactin above 25 ng/mL** should be repeated fasting and unstressed; exclude **macroprolactin**, hypothyroidism and drugs; **MRI pituitary** if persistently raised without an obvious cause. [Harrison 22e]",
          "**High FSH (above 25 IU/L)** with low oestradiol indicates **ovarian failure** - order a **karyotype** in all women with POI or primary amenorrhoea with raised FSH, and **FMR1 premutation testing**. [ESHRE POI 2024]",
          "**Low or normal FSH/LH with low oestradiol** indicates a **hypothalamic or pituitary cause** - MRI brain if there is no clear functional explanation, headache or visual symptoms. [Speroff 9e]",
          "**Pelvic ultrasound (transabdominal in virgins)** shows presence of the uterus, endometrial thickness, haematocolpos, ovarian morphology and adnexal masses. [Berek and Novak 16e]",
          "**Progestogen challenge test**: **medroxyprogesterone acetate 10 mg daily for 7-10 days**; a withdrawal bleed within 2-7 days of stopping means **adequate oestrogen (oestradiol above about 40 pg/mL) and a patent outflow tract**. [Speroff 9e]",
          "No withdrawal bleed - give **oestrogen plus progestogen** (oestradiol valerate 2 mg or conjugated oestrogen 1.25 mg daily for 21 days with MPA 10 mg for the last 5-10 days); no bleed now means an **outflow or endometrial defect**. [Speroff 9e]",
          "The challenge test correlates imperfectly with oestrogen status, so many clinicians rely on **oestradiol and endometrial thickness** instead. [Berek and Novak 16e]",
          "**Hyperandrogenism**: **total testosterone** (above about 150 ng/dL or twice the upper limit suggests an ovarian or adrenal tumour), DHEAS, **17-OH progesterone**; **75 g OGTT and lipids** in PCOS. [PCOS Guideline 2023]",
          "**Asherman or genital TB**: **hysteroscopy or HSG**, and **premenstrual endometrial biopsy for CBNAAT, TB culture and histology**. [NTEP 2022]",
          "**DXA bone density** after **6 months or more of hypo-oestrogenic amenorrhoea**; karyotype for DSD; renal ultrasound in MRKH. [ESHRE POI 2024]",
        ],
      },
      {
        heading: "Management and referral",
        points: [
          "**Treat the cause** - levothyroxine for hypothyroidism, stop or change the offending drug, weight restoration in FHA, hymenotomy for imperforate hymen. [Berek and Novak 16e]",
          "**Hyperprolactinaemia / prolactinoma**: **cabergoline 0.25-0.5 mg twice weekly** (first choice), or **bromocriptine 1.25 mg at night increased to 2.5 mg two to three times daily**, preferred when pregnancy is planned. [Harrison 22e]",
          "**PCOS - lifestyle first**: **5-10 per cent weight loss** restores ovulation in many; diet and at least **150 minutes of moderate exercise a week**. [PCOS Guideline 2023]",
          "**PCOS - cycle control and hirsutism**: **combined oral contraceptive** (ethinylestradiol 20-30 microgram with levonorgestrel or desogestrel) is first-line; add **metformin 500 mg increasing to 1500-2000 mg/day** for metabolic features or BMI 25 or more. [PCOS Guideline 2023]",
          "**Endometrial protection** in chronic anovulation: at least **one withdrawal bleed every 3 months** with **MPA 10 mg daily for 12-14 days**, or an LNG-IUS, to prevent hyperplasia. [PCOS Guideline 2023]",
          "**PCOS infertility**: **letrozole 2.5-7.5 mg daily on days 3-7** is first-line for ovulation induction, ahead of clomiphene. [PCOS Guideline 2023]",
          "**POI and Turner**: **hormone replacement** (oestradiol 1-2 mg oral or 50-100 microgram transdermal daily with cyclic progestogen) **until the natural age of menopause (about 51 years)** for bone, heart and brain; fertility is by **donor oocyte IVF**. [ESHRE POI 2024]",
          "**Asherman**: **hysteroscopic adhesiolysis** followed by oestrogen and early second-look hysteroscopy; **genital TB**: six-month **anti-TB treatment (2HRZE/4HRE)** under NTEP. [NTEP 2022]",
          "**Adolescents**: irregular cycles in the first 2 years are usually anovulatory and need reassurance, a menstrual calendar, iron-folic acid and follow-up; **heavy bleeding at menarche** needs Hb and a screen for **von Willebrand disease** (present in up to 1 in 5 such girls). [Berek and Novak 16e]",
          "**Primary dysmenorrhoea** in adolescents: **mefenamic acid 500 mg three times daily** or ibuprofen 400 mg three times daily from the day before or first day of menses for 2-3 days; COC if needed. [Berek and Novak 16e]",
          "Use **RKSK adolescent friendly health clinics** and the **Menstrual Hygiene Scheme** for counselling, sanitary pads, IFA (weekly WIFS) and screening. [MoHFW RKSK 2024]",
          "**Refer** all **primary amenorrhoea** after initial work-up, and **suspected pituitary tumour (visual loss, headache), POI, virilisation, DSD, Asherman or genital TB, and severe eating disorders** (BMI under 15, bradycardia under 40, electrolyte disturbance). [Berek and Novak 16e]",
          "Give **psychological support and careful disclosure** in MRKH, Turner and AIS - the diagnosis affects identity, sexuality and fertility. [Berek and Novak 16e]",
        ],
      },
    ],
    tables: [
      {
        heading: "Compartment classification of amenorrhoea",
        columns: ["Compartment", "Examples", "Key finding"],
        rows: [
          ["I - Outflow tract and uterus", "Imperforate hymen, transverse septum, MRKH, AIS, Asherman, genital TB", "Normal FSH and E2; no bleed after oestrogen-progestogen"],
          ["II - Ovary", "Turner, Swyer, POI, chemotherapy or radiotherapy", "High FSH (above 25 IU/L), low E2"],
          ["III - Anterior pituitary", "Prolactinoma, Sheehan, pituitary tumour, empty sella", "High prolactin or low FSH/LH; abnormal MRI"],
          ["IV - Hypothalamus/CNS", "Stress, weight loss, exercise, anorexia, Kallmann, craniopharyngioma", "Low or normal FSH/LH, low E2"],
          ["Other endocrine", "PCOS, thyroid disease, CAH, Cushing", "High LH:FSH, androgens, TSH or 17-OHP abnormal"],
        ],
      },
      {
        heading: "Primary amenorrhoea - differentiating common causes",
        columns: ["Condition", "Karyotype", "Breasts", "Uterus", "Pubic hair", "FSH"],
        rows: [
          ["Turner syndrome", "45,X or mosaic", "Absent", "Present (small)", "Sparse", "High"],
          ["MRKH", "46,XX", "Normal", "Absent", "Normal", "Normal"],
          ["Complete AIS", "46,XY", "Normal", "Absent", "Absent or scanty", "Normal or high"],
          ["Swyer syndrome", "46,XY", "Absent", "Present", "Sparse", "High"],
          ["Imperforate hymen", "46,XX", "Normal", "Present, haematometra", "Normal", "Normal"],
          ["Constitutional delay / Kallmann", "46,XX", "Absent or early", "Present", "Sparse", "Low"],
        ],
      },
      {
        heading: "Drug doses in amenorrhoea and oligomenorrhoea",
        columns: ["Indication", "Drug and dose", "Duration"],
        rows: [
          ["Progestogen challenge", "Medroxyprogesterone acetate 10 mg PO daily", "7-10 days"],
          ["Endometrial protection", "MPA 10 mg PO daily", "12-14 days every 1-3 months"],
          ["PCOS cycle control", "COC (EE 20-30 microgram + LNG or desogestrel)", "21/7 or 24/4, long-term"],
          ["PCOS metabolic", "Metformin 500 mg, up to 1500-2000 mg/day with meals", "Long-term"],
          ["Prolactinoma", "Cabergoline 0.25-0.5 mg PO twice weekly", "At least 2 years, then review"],
          ["POI / Turner HRT", "Oestradiol 2 mg PO or 100 microgram patch + cyclic progestogen", "Until about 51 years"],
          ["Ovulation induction (PCOS)", "Letrozole 2.5-7.5 mg PO daily, days 3-7", "Up to 6 cycles"],
        ],
      },
    ],
    redFlags: [
      "Headache, visual field loss or galactorrhoea - pituitary tumour",
      "Rapidly progressive hirsutism, clitoromegaly or deepening voice - androgen-secreting tumour",
      "Cyclical pelvic pain with urinary retention in a girl with no periods - haematocolpos",
      "BMI under 15, bradycardia or syncope in amenorrhoea - severe anorexia nervosa",
      "Hot flushes and amenorrhoea before 40 years - premature ovarian insufficiency",
      "Failure of lactation and amenorrhoea after PPH - Sheehan syndrome with adrenal risk",
      "Amenorrhoea with fever, weight loss or past TB - genital tuberculosis",
      "Ambiguous genitalia or an inguinal gonad in a girl - disorder of sex development",
    ],
    pearls: [
      "Every amenorrhoea is pregnancy until proven otherwise - do the UPT first.",
      "First-line tests after hCG: TSH, prolactin, FSH/LH, oestradiol and pelvic ultrasound.",
      "Turner syndrome is the commonest cause of primary amenorrhoea; MRKH is the commonest cause with normal breasts and absent uterus.",
      "Normal breasts with absent pubic hair and a blind vagina means androgen insensitivity - check the karyotype.",
      "In India, think of genital TB and curettage when amenorrhoea follows a normal menstrual history.",
      "Adolescent PCOS needs both anovulation and hyperandrogenism; do not use ultrasound within 8 years of menarche.",
      "Chronic anovulation needs a withdrawal bleed at least every 3 months to protect the endometrium.",
      "POI needs HRT until the natural age of menopause - it is replacement, not treatment of menopause.",
      "In FHA, fix energy balance first and use transdermal oestradiol rather than the pill for bone.",
    ],
    theory: [
      {
        id: "gynaecology-amenorrhoea-menstrual-irregularity-t1",
        paper: "IV",
        kind: "long",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question:
          "A 17-year-old girl has not attained menarche. Classify the causes of primary amenorrhoea. Outline the evaluation and management of MRKH syndrome. [4+3+3]",
        openingLines: [
          "Primary amenorrhoea is absence of menarche by 15 years with normal secondary sexual characters, or by 13 years without them.",
          "Causes are classified by compartment - outflow tract and uterus, ovary, pituitary and hypothalamus - with gonadal dysgenesis and Mullerian agenesis the commonest.",
        ],
        answer: [
          {
            heading: "Classification",
            points: [
              "Outflow/uterus: imperforate hymen, transverse septum, MRKH, AIS.",
              "Ovary: Turner, Swyer, POI.",
              "Pituitary: prolactinoma, tumours; hypothalamus: constitutional delay, Kallmann, weight loss, stress.",
              "Endocrine: CAH, thyroid, PCOS.",
            ],
          },
          {
            heading: "Evaluation",
            points: [
              "History and Tanner staging, height, Turner stigmata, anosmia, genitalia.",
              "UPT, TSH, prolactin, FSH/LH, E2; pelvic ultrasound; karyotype if high FSH or absent uterus.",
            ],
          },
          {
            heading: "MRKH - diagnosis",
            points: [
              "46,XX, normal breasts and hair, absent uterus and upper vagina, normal ovaries.",
              "Renal ultrasound (anomalies in 30-40 per cent); spine X-ray.",
            ],
          },
          {
            heading: "MRKH - management",
            points: [
              "Counselling and psychological support; vaginal dilators first line; vaginoplasty if needed.",
              "Fertility by gestational surrogacy under Surrogacy (Regulation) Act 2021; uterine transplant experimental.",
            ],
          },
        ],
        mustDraw: ["Compartment flow chart for amenorrhoea", "Algorithm for primary amenorrhoea by breast development and uterus"],
        markSplit: [
          { part: "Classification", marks: 4 },
          { part: "Evaluation", marks: 3 },
          { part: "MRKH management", marks: 3 },
        ],
        keywords: ["primary amenorrhoea", "MRKH", "Turner", "compartment approach", "karyotype"],
      },
      {
        id: "gynaecology-amenorrhoea-menstrual-irregularity-t2",
        paper: "IV",
        kind: "short-note",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question:
          "A 22-year-old obese factory worker presents with irregular periods and excess facial hair. Discuss the differential diagnosis, investigations and management. [3+3+4]",
        openingLines: [
          "Oligomenorrhoea with hirsutism in an obese young woman is most often polycystic ovary syndrome, diagnosed by Rotterdam criteria after excluding thyroid disease, hyperprolactinaemia, CAH and androgen-secreting tumours.",
          "Night shifts, stress and occupational exposures can add to menstrual irregularity and should be addressed.",
        ],
        answer: [
          {
            heading: "Differential diagnosis",
            points: [
              "PCOS; non-classic CAH; hypothyroidism; hyperprolactinaemia; Cushing syndrome; androgen-secreting tumour; drugs.",
              "Lifestyle and occupational: shift work, stress, solvent or lead exposure.",
            ],
          },
          {
            heading: "Investigations",
            points: [
              "UPT, TSH, prolactin, FSH/LH, total testosterone, 17-OHP, DHEAS if virilised.",
              "Pelvic ultrasound (follicle count, volume); 75 g OGTT, lipids.",
            ],
          },
          {
            heading: "Management",
            points: [
              "Lifestyle: 5-10 per cent weight loss, diet, 150 minutes exercise weekly.",
              "COC for cycle control and hirsutism; metformin for metabolic risk; cosmetic measures.",
              "MPA 10 mg for 12-14 days every 1-3 months if COC not used; letrozole for fertility.",
            ],
          },
          {
            heading: "Work and follow-up",
            points: [
              "Advise on shift pattern, sanitation, avoiding toxic exposures; screen for diabetes and depression; long-term follow-up.",
            ],
          },
        ],
        mustDraw: ["Rotterdam criteria diagram (2 of 3)"],
        markSplit: [
          { part: "Differential diagnosis", marks: 3 },
          { part: "Investigations", marks: 3 },
          { part: "Management", marks: 4 },
        ],
        keywords: ["PCOS", "hirsutism", "oligomenorrhoea", "Rotterdam", "occupational"],
      },
    ],
    mcqs: [
      {
        id: "gynaecology-amenorrhoea-menstrual-irregularity-q1",
        stem: "A 16-year-old has well-developed breasts, absent pubic and axillary hair, a short blind vagina and no uterus on ultrasound. What is the most likely diagnosis?",
        options: [
          "Complete androgen insensitivity syndrome",
          "MRKH syndrome",
          "Turner syndrome",
          "Imperforate hymen",
        ],
        answer: 0,
        explanation:
          "Normal breasts from aromatised testosterone, absent sexual hair from androgen resistance and absent uterus from AMH action point to complete AIS with a 46,XY karyotype. MRKH has normal pubic hair, Turner has absent breast development, and imperforate hymen has a normal uterus with haematometra.",
        difficulty: "moderate",
      },
      {
        id: "gynaecology-amenorrhoea-menstrual-irregularity-q2",
        stem: "A 34-year-old has amenorrhoea for 6 months with hot flushes. FSH is 68 IU/L on two occasions and oestradiol is low. Which is the most appropriate long-term management?",
        options: [
          "Cyclical progestogen alone every 3 months",
          "Clomiphene citrate to induce ovulation",
          "Hormone replacement until about 51 years",
          "Reassurance, as menses will return spontaneously",
        ],
        answer: 2,
        explanation:
          "This is premature ovarian insufficiency, and HRT until the average age of menopause protects bone, cardiovascular and cognitive health. Progestogen alone gives no oestrogen, clomiphene does not work in a failed ovary, and although intermittent ovarian activity occurs, reassurance alone leaves her hypo-oestrogenic.",
        difficulty: "moderate",
      },
      {
        id: "gynaecology-amenorrhoea-menstrual-irregularity-q3",
        stem: "In a woman with secondary amenorrhoea, a normal TSH and prolactin, and no bleed after medroxyprogesterone, which result of the oestrogen-progestogen test points to an endometrial cause?",
        options: [
          "Withdrawal bleed after oestrogen-progestogen",
          "No withdrawal bleed after oestrogen-progestogen",
          "High FSH with bleed after oestrogen-progestogen",
          "Low FSH with bleed after oestrogen-progestogen",
        ],
        answer: 1,
        explanation:
          "If the endometrium fails to bleed even after oestrogen priming plus progestogen, the defect lies in the outflow tract or endometrium, for example Asherman syndrome or genital TB. A bleed after oestrogen-progestogen means the uterus is normal and the problem is inadequate oestrogen, with FSH then separating ovarian (high) from central (low) causes.",
        difficulty: "hard",
      },
      {
        id: "gynaecology-amenorrhoea-menstrual-irregularity-q4",
        stem: "Per the International PCOS Guideline 2023, which statement about diagnosing PCOS in a 15-year-old is correct?",
        options: [
          "Polycystic ovarian morphology on ultrasound alone is sufficient",
          "Raised AMH can replace ultrasound in adolescents",
          "Irregular cycles in the first year after menarche meet the criterion",
          "Both ovulatory dysfunction and hyperandrogenism are required",
        ],
        answer: 3,
        explanation:
          "In adolescents both irregular cycles (defined for years after menarche) and hyperandrogenism are needed because multifollicular ovaries are normal at this age. Ultrasound and AMH are not recommended within 8 years of menarche, and cycle irregularity in the first post-menarchal year is a normal transition.",
        difficulty: "moderate",
      },
      {
        id: "gynaecology-amenorrhoea-menstrual-irregularity-q5",
        stem: "A 26-year-old on risperidone has amenorrhoea and galactorrhoea. Prolactin is 62 ng/mL and TSH is normal. What is the best initial step?",
        options: [
          "Start cabergoline immediately",
          "MRI of the pituitary before anything else",
          "Discuss switching to a prolactin-sparing antipsychotic with her psychiatrist",
          "Start the combined oral contraceptive",
        ],
        answer: 2,
        explanation:
          "Risperidone commonly causes hyperprolactinaemia; the first step is to consider switching to a prolactin-sparing drug such as aripiprazole with the psychiatrist, and to image only if prolactin stays high. Cabergoline may worsen psychosis, MRI first is premature with an obvious drug cause, and a COC does not address the cause.",
        difficulty: "moderate",
      },
    ],
    references: [
      "Berek and Novak's Gynecology, 16th edition (2019)",
      "Speroff's Clinical Gynecologic Endocrinology and Infertility, 9th edition (2019)",
      "Teede HJ et al. International Evidence-based Guideline for the Assessment and Management of Polycystic Ovary Syndrome, 2023",
      "ESHRE Guideline: Management of women with premature ovarian insufficiency, 2024",
      "Gordon CM et al. Functional Hypothalamic Amenorrhea: An Endocrine Society Clinical Practice Guideline, 2017",
      "Gravholt CH et al. Clinical practice guidelines for the care of girls and women with Turner syndrome, 2024",
      "Munro MG et al. FIGO classification systems (PALM-COEIN) and terminology for AUB, revised 2018",
      "IOC consensus statement on Relative Energy Deficiency in Sport (REDs), 2023",
    ],
  },
  {
    id: "gynaecology-ipv-sexual-assault",
    title: "Intimate partner violence and sexual assault: the family physician's duties",
    oneLiner:
      "Intimate partner violence is physical, sexual, emotional or economic abuse or controlling behaviour by a current or former partner, reported by **about 3 in 10 ever-married Indian women (NFHS-5)**; the family physician must **ask safely, respond with LIVES first-line support, document injuries, plan safety** and link women to **One Stop Centres, helpline 181 and the PWDVA 2005**, and must give every sexual-assault survivor **free, consent-based care under the MoHFW 2014 protocol** - no two-finger test, emergency contraception, STI and HIV prophylaxis - with police intimation as required by **BNSS 2023**.",
    frequency: "common",
    keywords: [
      "domestic violence",
      "intimate partner violence",
      "IPV",
      "gender-based violence",
      "sexual assault",
      "rape survivor",
      "PWDVA 2005",
      "Protection Officer",
      "One Stop Centre",
      "Sakhi",
      "Women Helpline 181",
      "MoHFW 2014 medico-legal guidelines",
      "two-finger test",
      "emergency contraception",
      "HIV PEP",
      "BNSS 397",
      "BNS 2023",
      "POCSO",
      "LIVES",
      "safety planning",
    ],
    sections: [
      {
        heading: "Forms of violence and burden in India",
        points: [
          "**Violence against women** is any act of gender-based violence that results in, or is likely to result in, physical, sexual or psychological harm, including threats, coercion or arbitrary deprivation of liberty, in public or private life. [WHO 2021]",
          "**Intimate partner violence (IPV)** includes **physical violence, sexual violence, emotional or psychological abuse, economic abuse and controlling behaviours** by a current or former partner. [WHO 2021]",
          "Other forms common in India: **dowry-related violence and dowry deaths, marital rape, acid attacks, honour crimes, child marriage, trafficking, stalking, workplace sexual harassment and technology-facilitated (cyber) abuse**. [MoHFW 2014]",
          "Globally about **27 per cent of ever-partnered women aged 15-49** have experienced physical or sexual IPV, and about **1 in 3 women** experience physical or sexual violence in their lifetime. [WHO 2021]",
          "**NFHS-5**: **29 per cent of ever-married women aged 18-49** have experienced **spousal physical or sexual violence**, about 3 per cent experienced violence during pregnancy, and only about **14 per cent** of women who experienced violence ever sought help. [NFHS-5]",
          "Risk factors include **husband's alcohol use**, low education, poverty, witnessing parental violence in childhood, **controlling behaviour, dowry demands**, and attitudes that justify wife-beating. [NFHS-5]",
          "**NCRB 2022** recorded about **4.45 lakh crimes against women**, with **cruelty by husband or relatives** the largest category - reported crime is only the tip of the iceberg. [NCRB 2022]",
          "Violence often **escalates in pregnancy, after separation and with alcohol**, and women with disability, adolescents and migrants are especially vulnerable. [WHO 2021]",
          "**Children who witness IPV** suffer behavioural, emotional and learning problems and are more likely to experience or perpetrate violence as adults. [WHO 2021]",
        ],
      },
      {
        heading: "Health consequences and when to suspect",
        points: [
          "**Injuries**: bruises, lacerations, **fractures, head injury, burns, perforated eardrum**, dental trauma and **strangulation** - non-fatal strangulation raises the risk of later homicide about seven-fold. [WHO 2019 Curriculum]",
          "**Gynaecological**: STIs and HIV, **unintended pregnancy, repeat induced abortion, chronic pelvic pain, PID, dyspareunia** and recurrent vaginal discharge. [Berek and Novak 16e]",
          "**Obstetric**: late booking, missed visits, **miscarriage, antepartum haemorrhage, preterm birth, low birth weight** and maternal death from homicide or suicide. [Williams 26e]",
          "**Mental health**: **depression, anxiety, PTSD, insomnia, substance use, self-harm and suicide** - IPV roughly doubles the risk of depression. [WHO 2021]",
          "**Chronic physical symptoms**: headache, backache, **irritable bowel symptoms, fatigue**, unexplained pain and frequent visits without a clear diagnosis. [WHO 2019 Curriculum]",
          "Clues to ask about violence: **injuries inconsistent with the explanation**, delay in seeking care, repeated visits, **partner who insists on staying and answers for her**, missed appointments, and depression or suicidal ideation. [WHO 2019 Curriculum]",
          "Pattern injuries include **grip marks on the upper arm, defence bruises on the forearms, bite marks, cigarette burns, ligature or fingertip marks on the neck** and injuries of different ages. [Reddy 35e]",
          "In **burns in a young married woman**, especially within 7 years of marriage, consider **dowry-related violence** and record a **dying declaration** if life is in danger. [Reddy 35e]",
        ],
      },
      {
        heading: "Asking safely and first-line support (LIVES)",
        points: [
          "WHO advises **clinical enquiry** (asking when conditions suggest violence) rather than universal screening in low-resource settings; the **USPSTF recommends screening** women of reproductive age with a brief tool and referring positives. [WHO 2019 Curriculum; USPSTF 2018]",
          "Ask **only when she is alone** (no partner, relatives or children over 2 years), in **privacy**, with a **professional interpreter** rather than a family member, after explaining **confidentiality and its limits**. [WHO 2019 Curriculum]",
          "Use **direct, non-judgemental questions**: 'Has your husband or anyone at home ever hit, kicked, slapped or hurt you?', 'Are you afraid of anyone at home?', 'Has anyone forced you to have sex?'. [WHO 2019 Curriculum]",
          "Brief tools include **HITS (Hurt, Insult, Threaten, Scream)** and **HARK (Humiliation, Afraid, Rape, Kick)**. [USPSTF 2018]",
          "Respond with **LIVES**: **Listen** closely with empathy, **Inquire** about needs and concerns, **Validate** ('it is not your fault'), **Enhance safety**, and **Support** by connecting to services. [WHO 2019 Curriculum]",
          "**Do not** blame, pressure her to leave, confront the partner, or suggest **couple counselling** while violence continues - it can increase danger. [WHO 2019 Curriculum]",
          "**Respect autonomy** - an adult woman decides whether to report to police or seek legal remedies; the doctor's job is to inform, treat and keep the door open. [WHO 2019 Curriculum]",
          "Provide **care for the husband's alcohol use** separately where appropriate, but do not frame alcohol as an excuse for violence. [WHO mhGAP 2023]",
        ],
      },
      {
        heading: "Documentation, safety planning and the PWDVA 2005",
        points: [
          "**Document** in her own words (in quotes) **who, when, where and how**, then describe each injury - **type, size in cm, shape, colour, location** - on a **body map**, with **photographs taken with consent**. [MoHFW 2014]",
          "Avoid precise **ageing of bruises** from colour; record what you see and note **pattern injuries** and **injuries of different ages**. [Reddy 35e]",
          "Injuries from assault are **medico-legal cases** - register an **MLC, inform the police** as per hospital policy, and give the woman a copy of her records free of charge. [MoHFW 2014]",
          "**Assess danger**: increasing frequency or severity, **threats to kill, weapons, strangulation, violence in pregnancy, recent separation**, stalking and threats to children. [WHO 2019 Curriculum]",
          "**Safety plan**: a safe place to go, an **emergency bag** (documents, ID, money, medicines, keys, phone numbers), a **code word** with a trusted neighbour, and memorised helpline numbers. [WHO 2019 Curriculum]",
          "The **Protection of Women from Domestic Violence Act (PWDVA) 2005** is a **civil law** covering **physical, sexual, verbal and emotional, and economic abuse** of any woman in a **domestic relationship** - wife, live-in partner, mother, sister, daughter or widow. [PWDVA 2005]",
          "Under the PWDVA, a **Protection Officer** or **Service Provider** records a **Domestic Incident Report (DIR)**, and a **Magistrate** can pass **protection orders, residence orders** (right to live in the shared household), **monetary relief, custody and compensation orders**, including **ex parte interim orders**. [PWDVA 2005]",
          "The Act requires any **medical facility** to provide **medical aid** to an aggrieved woman when requested by her, the Protection Officer or a service provider, and to send a copy of the medical report. [PWDVA 2005]",
          "The first hearing should be within **3 days** and the case disposed of within **60 days**; **breach of a protection order is a criminal offence**. [PWDVA 2005]",
          "Criminal provisions under the **BNS 2023** include **cruelty by husband or relatives (section 85-86, formerly IPC 498A)** and **dowry death (section 80, formerly IPC 304B)**; the **Dowry Prohibition Act 1961** also applies. [BNS 2023]",
        ],
      },
      {
        heading: "Services: One Stop Centres, helplines and referral",
        points: [
          "**One Stop Centres (Sakhi)**, started in **2015 under the Nirbhaya Fund** and now part of **Mission Shakti (Sambal)**, provide **medical aid, police facilitation, legal aid, psychosocial counselling and temporary shelter up to 5 days** under one roof, usually on hospital premises. [MWCD Mission Shakti 2022]",
          "There is at least **one OSC in every district** - the family physician should know the local OSC's address and phone number. [MWCD Mission Shakti 2022]",
          "**Women Helpline 181** is a 24x7 toll-free number linking women to police, OSCs, hospitals and legal services; **112 (ERSS)** is the national emergency number. [MWCD Mission Shakti 2022]",
          "Other numbers: **Child Helpline 1098** for children, the **NCW helpline**, and **Tele-MANAS 14416** for mental health support. [MoHFW Tele-MANAS 2022]",
          "Refer to **District Legal Services Authorities** for free legal aid, and to **Protection Officers** (district women and child development office) for PWDVA applications. [PWDVA 2005]",
          "Link women to **economic support** - self-help groups, skill training and shelter homes (**Shakti Sadan**) - since economic dependence is a major barrier to leaving. [MWCD Mission Shakti 2022]",
        ],
      },
      {
        heading: "Sexual assault: MoHFW 2014 protocol, consent and evidence",
        points: [
          "The **MoHFW Guidelines and Protocols: Medico-legal care for survivors/victims of sexual violence (2014)** are the national standard for **every** public and private hospital. [MoHFW 2014]",
          "**Any registered medical practitioner** must examine the survivor - a female doctor is preferred but **treatment must not be delayed**; a male doctor examines in the presence of a female attendant. [MoHFW 2014]",
          "**No police requisition or FIR is needed** - a survivor who comes directly to a hospital must be examined and treated. [MoHFW 2014]",
          "**Informed consent** is taken separately for **examination, evidence collection, treatment and police intimation**; a survivor aged **12 or more** can consent herself, and **refusal of any part must be respected** without refusing treatment. [MoHFW 2014]",
          "The examination must be done **within 24 hours of the information reaching the doctor** by an RMP with consent, as required under **BNSS 2023 section 184** (formerly CrPC 164A). [BNSS 2023]",
          "The **two-finger (per vaginum) test is banned** - it is unscientific, violates dignity and privacy, and the Supreme Court has held that anyone conducting it is guilty of **misconduct** (State of Jharkhand v Shailendra Kumar Rai, 2022). [Supreme Court 2022]",
          "Do **not comment on the hymen, 'habituation to sexual intercourse' or past sexual history**; the **absence of injuries does not rule out sexual assault**. [MoHFW 2014]",
          "**Evidence** is best collected **within 96 hours** (but examine whenever she presents): clothes, **vaginal, anal and oral swabs**, nail scrapings, pubic hair combings, blood and urine for **DNA, alcohol and drugs** - air-dried, sealed, labelled, with **chain of custody**. [MoHFW 2014]",
          "Record **findings and a provisional opinion** in the prescribed format and give the **survivor a free copy**; never make a finding of 'rape', which is a legal conclusion. [MoHFW 2014]",
          "**Confidentiality**: disclosing the identity of a sexual assault survivor is an offence under **BNS 2023 section 72** (formerly IPC 228A). [BNS 2023]",
          "**Children under 18**: the **POCSO Act 2012** requires **mandatory reporting** to the police or Special Juvenile Police Unit (section 19), and failure to report is punishable (section 21). [POCSO Act 2012]",
        ],
      },
      {
        heading: "Treatment after sexual assault: EC, STI and HIV prophylaxis, free care",
        points: [
          "**BNSS 2023 section 397** (formerly CrPC 357C) requires **all hospitals, public or private, to provide first aid or medical treatment free of cost immediately** to survivors of rape and acid attack and to **inform the police**. [BNSS 2023]",
          "**Refusing treatment is an offence** under **BNS 2023 section 200** (formerly IPC 166B), punishable with imprisonment up to 1 year, fine, or both. [BNS 2023]",
          "Treat **injuries first** - resuscitation, wound care and **tetanus (Td) prophylaxis** take priority over evidence collection. [MoHFW 2014]",
          "**Emergency contraception**: **levonorgestrel 1.5 mg orally stat within 72 hours** (usable up to 120 hours with lower efficacy), or a **copper IUD within 5 days**, after a urine pregnancy test. [MoHFW 2014]",
          "**STI prophylaxis**: **azithromycin 1 g orally stat + cefixime 400 mg orally stat** (or ceftriaxone 500 mg IM) **+ metronidazole 2 g orally stat** (can be deferred to reduce nausea, or if she has taken alcohol). [NACO 2021]",
          "**HIV post-exposure prophylaxis** as soon as possible and **within 72 hours**: **tenofovir 300 mg + lamivudine 300 mg + dolutegravir 50 mg once daily for 28 days**, after baseline HIV testing and counselling. [NACO 2021]",
          "**Hepatitis B**: start or complete **hepatitis B vaccination (0, 1, 6 months)** if not immune, with **HBIG** if the assailant is known HBsAg-positive. [MoHFW 2014]",
          "Baseline **HIV, HBsAg, HCV and syphilis** tests, and repeat at **6 weeks, 3 months and 6 months**; test for pregnancy at follow-up. [NACO 2021]",
          "**Pregnancy resulting from rape**: the **MTP Amendment Act 2021** allows termination **up to 24 weeks** for survivors of rape or incest; preserve **fetal tissue for DNA** analysis. [MTP Amendment Act 2021]",
          "The **Nirbhaya Fund and state victim compensation schemes** (through the District Legal Services Authority) provide **interim compensation** to survivors. [BNSS 2023]",
        ],
      },
      {
        heading: "Psychological support, follow-up and prevention",
        points: [
          "Give **psychological first aid** at the first contact - safety, calm, connection, and practical help - and avoid forcing a detailed retelling of the event. [WHO mhGAP 2023]",
          "Screen for **depression, PTSD, suicidal ideation and substance use** at follow-up; offer **trauma-focused CBT or EMDR** for PTSD and avoid routine **benzodiazepines**. [WHO mhGAP 2023]",
          "Most survivors improve within weeks; persistent symptoms beyond **1 month** suggest PTSD and need referral to a psychiatrist or clinical psychologist. [Kaplan and Sadock 12e]",
          "Arrange **follow-up visits** at 2 weeks, 6 weeks, 3 months and 6 months for injuries, test results, PEP adherence, pregnancy, STI treatment and mental health. [MoHFW 2014]",
          "Assess and protect **children in the household**, and involve child protection services where there is risk. [WHO 2021]",
          "**Primary prevention**: education on gender equality, **engaging men and boys**, reducing harmful alcohol use, **economic empowerment of women** and ending child marriage. [WHO 2021]",
          "Train all clinic staff in **identification, first-line support, documentation and referral**, and display helpline numbers in the women's toilet and waiting area. [WHO 2019 Curriculum]",
          "**Family physician role summary**: **recognise, ask, respond (LIVES), treat, document, plan safety, refer (OSC, 181, Protection Officer, police), follow up and protect children**. [WHO 2019 Curriculum]",
        ],
      },
    ],
    tables: [
      {
        heading: "Types of violence against women - classification",
        columns: ["Type", "Examples", "Legal remedy (India)"],
        rows: [
          ["Physical", "Slapping, beating, burning, strangling, acid attack", "BNS 2023 (hurt, cruelty s85-86), PWDVA 2005"],
          ["Sexual", "Rape, forced sex by partner, sexual harassment, child sexual abuse", "BNS 2023 s63-70, POCSO 2012, PWDVA 2005"],
          ["Emotional/psychological", "Insults, threats, isolation, humiliation, controlling behaviour", "PWDVA 2005, BNS cruelty"],
          ["Economic", "Denying money, taking earnings, dowry demands, eviction", "PWDVA 2005, Dowry Prohibition Act 1961"],
          ["Structural/cultural", "Child marriage, honour crimes, trafficking, dowry deaths", "PCMA 2006, BNS s80, anti-trafficking laws"],
        ],
      },
      {
        heading: "Medical care after sexual assault - drugs and timing",
        columns: ["Purpose", "Drug and dose", "Timing"],
        rows: [
          ["Emergency contraception", "Levonorgestrel 1.5 mg PO stat, or copper IUD", "Within 72 hours (LNG up to 120 h); IUD within 5 days"],
          ["Chlamydia, gonorrhoea", "Azithromycin 1 g PO + cefixime 400 mg PO stat", "At first visit"],
          ["Trichomonas, BV", "Metronidazole 2 g PO stat", "At first visit or deferred"],
          ["HIV PEP", "TDF 300 mg + 3TC 300 mg + DTG 50 mg PO once daily", "Within 72 hours, for 28 days"],
          ["Hepatitis B", "HBV vaccine 0, 1, 6 months +/- HBIG", "At first visit if not immune"],
          ["Tetanus", "Td 0.5 mL IM", "If wounds and not up to date"],
        ],
      },
      {
        heading: "Key laws for the family physician",
        columns: ["Law", "Key provision", "Doctor's duty"],
        rows: [
          ["PWDVA 2005", "Civil protection, residence, monetary relief orders", "Provide medical aid and report to Protection Officer on request"],
          ["BNSS 2023 s397", "Free immediate treatment of rape and acid-attack survivors", "Treat free; inform police"],
          ["BNS 2023 s200", "Punishment for non-treatment of victim", "Never refuse or delay care"],
          ["BNSS 2023 s184", "Medical examination of rape victim with consent", "Examine within 24 hours, report without delay"],
          ["POCSO Act 2012 s19, s21", "Mandatory reporting of child sexual abuse", "Report every case under 18"],
          ["BNS 2023 s72", "Identity of survivor not to be disclosed", "Maintain confidentiality"],
        ],
      },
    ],
    redFlags: [
      "Strangulation - voice change, neck marks, petechiae, loss of consciousness",
      "Threats to kill, access to weapons or escalating violence",
      "Violence during pregnancy",
      "Suicidal thoughts or previous self-harm",
      "Recent separation or the partner stalking her",
      "Burns in a young married woman - suspect dowry violence",
      "Sexual assault within 72 hours - urgent EC and HIV PEP",
      "Children in the household being hurt or threatened",
    ],
    pearls: [
      "Ask alone, ask directly, believe her, and never blame - LIVES is the first-line response.",
      "Couple counselling is contraindicated while violence is ongoing.",
      "PWDVA 2005 is civil law - it gives protection and residence orders, not punishment of the husband by itself.",
      "No FIR is needed to examine or treat a sexual-assault survivor; the hospital cannot turn her away.",
      "The two-finger test is banned; comments on the hymen or 'habituation' have no place in the report.",
      "Absence of injury does not mean absence of assault.",
      "EC within 72 hours, STI prophylaxis and HIV PEP within 72 hours - the three time-critical drugs.",
      "BNSS 397 mandates free treatment by all hospitals; BNS 200 punishes refusal.",
      "Every district has a One Stop Centre, and 181 works 24x7 - write the numbers on the prescription if safe.",
    ],
    theory: [
      {
        id: "gynaecology-ipv-sexual-assault-t1",
        paper: "I",
        kind: "long",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question:
          "A 26-year-old woman comes with bruises and says her alcoholic husband beats her. Discuss the magnitude of domestic violence in India, your approach to her in the clinic, and the provisions of the Protection of Women from Domestic Violence Act 2005. [2+4+4]",
        openingLines: [
          "Domestic violence is physical, sexual, emotional or economic abuse or controlling behaviour within a domestic relationship; about 29 per cent of ever-married Indian women report spousal physical or sexual violence (NFHS-5).",
          "The family physician's role is to recognise, respond with first-line support, document, plan safety and link her to legal and social services.",
        ],
        answer: [
          {
            heading: "Magnitude",
            points: [
              "NFHS-5: 29 per cent spousal physical or sexual violence; only 14 per cent seek help.",
              "Risk factors: alcohol, dowry, low education, witnessing violence; consequences on physical, reproductive and mental health.",
            ],
          },
          {
            heading: "Approach in the clinic",
            points: [
              "Private interview; LIVES - listen, inquire, validate, enhance safety, support.",
              "Treat injuries; document on body map with photographs; MLC; free copy of records.",
              "Danger assessment and safety plan; screen for depression and suicide.",
              "Refer: One Stop Centre, 181, Protection Officer, legal aid; alcohol treatment for husband separately.",
            ],
          },
          {
            heading: "PWDVA 2005",
            points: [
              "Civil law covering physical, sexual, verbal/emotional and economic abuse of women in domestic relationships.",
              "Protection Officer, service providers, DIR; Magistrate orders - protection, residence, monetary, custody, compensation, ex parte interim.",
              "Medical facilities must provide aid; hearing within 3 days, disposal within 60 days; breach is an offence.",
            ],
          },
        ],
        mustDraw: ["Flow chart of the pathway from clinic to OSC, Protection Officer and Magistrate"],
        markSplit: [
          { part: "Magnitude", marks: 2 },
          { part: "Clinical approach", marks: 4 },
          { part: "PWDVA 2005", marks: 4 },
        ],
        keywords: ["domestic violence", "PWDVA 2005", "LIVES", "One Stop Centre", "safety plan"],
      },
      {
        id: "gynaecology-ipv-sexual-assault-t2",
        paper: "IV",
        kind: "short-note",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question:
          "A 19-year-old girl reports to your hospital 20 hours after sexual assault. Outline the medico-legal and medical management as per MoHFW 2014 guidelines. [5+5]",
        openingLines: [
          "Every hospital must provide immediate free treatment to a sexual-assault survivor under BNSS 2023 section 397, with or without an FIR, following the MoHFW 2014 protocol.",
          "Care combines consent-based examination and evidence collection with treatment of injuries, emergency contraception, STI and HIV prophylaxis and psychosocial support.",
        ],
        answer: [
          {
            heading: "Medico-legal steps",
            points: [
              "Separate informed consent for examination, evidence, treatment, police intimation; respect refusal.",
              "History in her words; head-to-toe examination; no two-finger test; no hymen comments.",
              "Evidence within 96 hours - swabs, clothes, nail scrapings, blood/urine; chain of custody.",
              "Inform police (BNSS 397), free copy of report, confidentiality (BNS 72).",
            ],
          },
          {
            heading: "Medical management",
            points: [
              "Injuries and Td; UPT; levonorgestrel 1.5 mg stat or Cu-IUD.",
              "Azithromycin 1 g + cefixime 400 mg + metronidazole 2 g stat.",
              "HIV PEP TDF/3TC/DTG for 28 days; hepatitis B vaccine; baseline serology.",
            ],
          },
          {
            heading: "Psychosocial and follow-up",
            points: [
              "Psychological first aid; screen for PTSD and suicide; OSC referral, legal aid, compensation.",
              "Follow-up at 2 weeks, 6 weeks, 3 and 6 months; MTP up to 24 weeks if pregnant.",
            ],
          },
        ],
        mustDraw: ["Checklist table of the 72-hour time-critical interventions"],
        markSplit: [
          { part: "Medico-legal", marks: 5 },
          { part: "Medical and psychosocial", marks: 5 },
        ],
        keywords: ["sexual assault", "MoHFW 2014", "two-finger test", "HIV PEP", "BNSS 397"],
      },
    ],
    mcqs: [
      {
        id: "gynaecology-ipv-sexual-assault-q1",
        stem: "A 24-year-old walks into a private hospital 10 hours after being raped. She has not gone to the police. What is the correct course of action?",
        options: [
          "Examine and treat her free of cost, and inform the police",
          "Ask her to first lodge an FIR and return with a police requisition",
          "Refer her to the government hospital as private hospitals are exempt",
          "Treat her only if she agrees to file a police complaint",
        ],
        answer: 0,
        explanation:
          "BNSS 2023 section 397 obliges every hospital, public or private, to give immediate free treatment to a rape survivor and inform the police, and the MoHFW 2014 protocol states that no FIR or requisition is needed. Sending her away or making care conditional on a complaint is unlawful and punishable under BNS section 200.",
        difficulty: "easy",
      },
      {
        id: "gynaecology-ipv-sexual-assault-q2",
        stem: "Which of the following is prohibited in the medico-legal examination of a sexual-assault survivor?",
        options: [
          "Taking separate consent for evidence collection",
          "Collecting nail scrapings for DNA",
          "Performing the per vaginum two-finger test",
          "Photographing injuries with consent",
        ],
        answer: 2,
        explanation:
          "The two-finger test is unscientific and violates dignity; the Supreme Court has held that performing it is misconduct, and the MoHFW 2014 protocol bans it. Separate consent for each step, nail scrapings for DNA and consented photographs of injuries are all recommended parts of the examination.",
        difficulty: "easy",
      },
      {
        id: "gynaecology-ipv-sexual-assault-q3",
        stem: "Which is the recommended HIV post-exposure prophylaxis regimen for an adult sexual-assault survivor in India?",
        options: [
          "Zidovudine plus lamivudine for 14 days",
          "Tenofovir, lamivudine and dolutegravir once daily for 28 days",
          "Nevirapine single dose",
          "Tenofovir alone for 28 days",
        ],
        answer: 1,
        explanation:
          "NACO 2021 recommends TDF 300 mg + 3TC 300 mg + DTG 50 mg once daily for 28 days, started within 72 hours. A 14-day course is too short, single-dose nevirapine is a PMTCT regimen with hepatotoxicity risk in adults, and tenofovir alone is inadequate for PEP.",
        difficulty: "moderate",
      },
      {
        id: "gynaecology-ipv-sexual-assault-q4",
        stem: "Under the Protection of Women from Domestic Violence Act 2005, which relief allows a woman to continue living in the shared household?",
        options: ["Protection order", "Monetary relief order", "Custody order", "Residence order"],
        answer: 3,
        explanation:
          "A residence order secures the woman's right to reside in the shared household, whether or not she has title in it. A protection order restrains the respondent from acts of violence or contact, monetary relief covers expenses and losses, and a custody order deals with the children.",
        difficulty: "moderate",
      },
      {
        id: "gynaecology-ipv-sexual-assault-q5",
        stem: "A woman discloses ongoing violence by her husband but does not want to leave or go to the police. What is the most appropriate response?",
        options: [
          "Call the husband in for joint counselling",
          "Insist that she report to the police for her safety",
          "Offer LIVES support, document, make a safety plan and give helpline and OSC details",
          "Record the disclosure but take no action as she declines help",
        ],
        answer: 2,
        explanation:
          "First-line support respects her autonomy while enhancing safety - listen, validate, document, plan safety and link to OSC and 181, keeping the door open. Joint counselling can escalate danger, pressuring her to report undermines trust, and doing nothing leaves her without a safety plan.",
        difficulty: "moderate",
      },
    ],
    references: [
      "MoHFW. Guidelines and Protocols: Medico-legal care for survivors/victims of sexual violence, 2014 (in force, read with BNSS 2023)",
      "WHO. Caring for women subjected to violence: a WHO curriculum for training health-care providers, revised 2021",
      "WHO. Violence against women prevalence estimates 2018, published 2021",
      "National Family Health Survey-5 (2019-21), India Report",
      "Protection of Women from Domestic Violence Act 2005; Bharatiya Nyaya Sanhita 2023; Bharatiya Nagarik Suraksha Sanhita 2023; POCSO Act 2012",
      "NACO National Guidelines for HIV Care and Treatment, 2021",
      "Ministry of Women and Child Development. Mission Shakti guidelines (One Stop Centres, Women Helpline), 2022",
      "US Preventive Services Task Force. Screening for Intimate Partner Violence, 2018",
    ],
  },
];

export default topics;
