import type { Topic } from "../../lib/types";

const topics: Topic[] = [
  {
    id: "infectious-fever-antimicrobial-resistance",
    title: "Antimicrobial resistance and antibiotic stewardship in primary care",
    oneLiner:
      "Antimicrobial resistance (AMR) is **the ability of a microorganism to survive and multiply despite an antimicrobial that previously killed or inhibited it**, driven in India by over-the-counter sale, self-medication, irrational prescribing, veterinary use and poor infection control, and countered by the **National Action Plan on AMR 2017**, WHO AWaRe-based prescribing, Schedule H1 and the Red Line campaign, and stewardship in every clinic.",
    frequency: "core",
    keywords: [
      "AMR",
      "antimicrobial resistance",
      "antibiotic stewardship",
      "AMS",
      "MDR",
      "XDR",
      "PDR",
      "superbug",
      "NAP-AMR",
      "KARSAP",
      "AWaRe",
      "Access Watch Reserve",
      "Red Line campaign",
      "Schedule H1",
      "delayed prescribing",
      "ICMR AMRSN",
      "carbapenem-resistant Enterobacterales",
      "NDM-1",
      "hospital-acquired infection",
      "WAAW",
    ],
    sections: [
      {
        heading: "Definitions",
        points: [
          "**AMR** is the ability of bacteria, viruses, fungi or parasites to resist drugs that were once effective, so infections persist and spread. [WHO 2023]",
          "**MDR:** non-susceptible to at least one agent in **three or more antimicrobial categories**. [Harrison 22e]",
          "**XDR:** non-susceptible to at least one agent in **all but two or fewer categories** - susceptible to only one or two classes. [Harrison 22e]",
          "**PDR:** non-susceptible to **all agents in all categories** - no reliable antibiotic remains. [Harrison 22e]",
          "**Superbug** is a lay term for an organism resistant to most antibiotics, e.g. NDM-1-producing Klebsiella, carbapenem-resistant Acinetobacter and MRSA. [Harrison 22e]",
          "TB definitions differ: **MDR-TB** is resistance to isoniazid plus rifampicin; **pre-XDR** adds a fluoroquinolone; **XDR** adds bedaquiline or linezolid. [WHO 2021]",
          "**Intrinsic resistance** is natural (e.g. Pseudomonas to many drugs); **acquired resistance** arises by mutation or horizontal gene transfer via plasmids and transposons. [Harrison 22e]",
          "Key mechanisms: **enzymatic inactivation (ESBL, carbapenemases such as NDM-1 and OXA-48), altered target (MRSA mecA), reduced permeability and efflux pumps**. [Harrison 22e]",
          "**NDM-1** (New Delhi metallo-beta-lactamase) was first described in 2008 and is now endemic in Indian hospitals. [Park 28e]",
          "**Antimicrobial stewardship** is a coordinated programme promoting the right drug, dose, route and duration to improve outcomes and limit resistance. [ICMR AMSP 2018]",
        ],
      },
      {
        heading: "Burden and priority pathogens",
        points: [
          "Globally, bacterial AMR was **directly responsible for 1.27 million deaths** and associated with 4.95 million deaths in 2019. [GRAM Lancet 2022]",
          "GRAM forecasts **over 39 million AMR-attributable deaths between 2025 and 2050**, with South Asia bearing the largest share. [GRAM Lancet 2024]",
          "India had an estimated **about 3 lakh attributable and about 10 lakh associated deaths** in 2019, the highest national toll. [GRAM Lancet 2022]",
          "India is among the **largest consumers of antibiotics** in absolute terms, and Watch-group drugs such as azithromycin and cefixime dominate retail sales. [Lancet Regional Health SE Asia 2023]",
          "ICMR AMRSN data show **carbapenem susceptibility of E. coli falling from about 80 per cent to about 60 per cent** between 2017 and 2023, with Klebsiella and Acinetobacter worse. [ICMR AMRSN 2023]",
          "In Indian neonatal units, **Acinetobacter and Klebsiella** dominate sepsis and most are MDR - the DeNIS cohort reported high carbapenem resistance. [DeNIS Lancet Glob Health 2016]",
          "WHO Bacterial Priority Pathogens List 2024 - **critical**: carbapenem-resistant Acinetobacter baumannii, carbapenem-resistant and third-generation cephalosporin-resistant Enterobacterales, and rifampicin-resistant M. tuberculosis. [WHO BPPL 2024]",
          "**High priority** includes fluoroquinolone-resistant Salmonella Typhi and Shigella, carbapenem-resistant Pseudomonas, vancomycin-resistant Enterococcus faecium, MRSA and resistant N. gonorrhoeae. [WHO BPPL 2024]",
          "**Medium priority** includes macrolide-resistant group A streptococcus and pneumococcus, and ampicillin-resistant H. influenzae. [WHO BPPL 2024]",
          "In the community, the family physician meets **ESBL E. coli UTI, FQ-resistant typhoid, MDR-TB and resistant gonorrhoea** most often. [Harrison 22e]",
          "The 2024 UN General Assembly Political Declaration targets **a 10 per cent cut in AMR deaths by 2030** and **70 per cent of human antibiotic use from the Access group**. [UNGA 2024]",
        ],
      },
      {
        heading: "Drivers of AMR in India",
        points: [
          "**Over-the-counter sale** of antibiotics without prescription by pharmacies is the single biggest community driver. [NAP-AMR 2017]",
          "**Self-medication** with leftover antibiotics and advice from untrained informal providers is widespread. [Park 28e]",
          "**Irrational prescribing** - antibiotics for viral URI, diarrhoea and fever without diagnosis, wrong dose or duration. [ICMR 2019]",
          "**Irrational fixed-dose combinations** (e.g. cefixime-ofloxacin) - hundreds have been banned under the Drugs and Cosmetics Act since 2016. [CDSCO 2023]",
          "Patient demand, fear of losing patients and **pharmaceutical incentives** push prescribers toward broad-spectrum drugs. [NAP-AMR 2017]",
          "**Veterinary and agricultural use** as growth promoters in poultry and aquaculture - colistin as a growth promoter was banned in 2019. [MoHFW Notification 2019]",
          "**Pharmaceutical manufacturing effluent** releases antibiotics into rivers near production hubs. [NAP-AMR 2017]",
          "**Poor sanitation and water** increase faecal carriage and spread of ESBL and carbapenemase genes. [Park 28e]",
          "**Weak infection prevention** in hospitals spreads MDR organisms between patients. [NCDC IPC 2020]",
          "Limited laboratory capacity means **empirical broad-spectrum use** without culture guidance. [NAP-AMR 2017]",
        ],
      },
      {
        heading: "National and state policy",
        points: [
          "The **National Action Plan on AMR (NAP-AMR) 2017-2021** was launched in April 2017 with a One Health approach, aligned with the WHO Global Action Plan 2015. [NAP-AMR 2017]",
          "NAP-AMR has **six strategic priorities**: awareness, surveillance, infection prevention and control, optimised use, research and innovation, and leadership and collaboration. [NAP-AMR 2017]",
          "A second plan, **NAP-AMR 2.0 (2025-2029)**, extends the One Health approach and adds stronger state-level and private-sector roles. [MoHFW 2025]",
          "**Kerala Antimicrobial Resistance Strategic Action Plan (KARSAP)**, launched in October 2018, was the first state action plan. [KARSAP 2018]",
          "Kerala's **Operation AMRITH** (2024) targets over-the-counter antibiotic sales, and antibiotics are dispensed in distinctive blue covers. [Kerala Health Dept 2024]",
          "Madhya Pradesh (2019) and Delhi (2020) have followed with state action plans on AMR containment. [NCDC 2023]",
          "Surveillance runs through **NCDC's NARS-Net** and **ICMR's AMR Surveillance and Research Network (AMRSN)**, and India reports to WHO GLASS. [NCDC 2023]",
          "The **Chennai Declaration (2012)** by professional societies first set a national roadmap. [Park 28e]",
          "**World AMR Awareness Week** is observed from **18 to 24 November** each year. [WHO 2024]",
        ],
      },
      {
        heading: "AWaRe, essential medicines, Schedule H1 and Red Line",
        points: [
          "WHO **AWaRe** classifies antibiotics as **Access** (first-line, low resistance potential), **Watch** (higher resistance potential, restricted indications) and **Reserve** (last resort). [WHO AWaRe 2023]",
          "**Access examples:** amoxicillin, amoxicillin-clavulanate, cefalexin, cloxacillin, doxycycline, nitrofurantoin, co-trimoxazole, metronidazole, gentamicin. [WHO AWaRe 2023]",
          "**Watch examples:** azithromycin, ciprofloxacin, levofloxacin, cefixime, cefuroxime, ceftriaxone, piperacillin-tazobactam, meropenem, vancomycin. [WHO AWaRe 2023]",
          "**Reserve examples:** colistin, polymyxin B, linezolid, tigecycline, ceftazidime-avibactam, IV fosfomycin and daptomycin. [WHO AWaRe 2023]",
          "The **WHO AWaRe Antibiotic Book (2022)** gives first- and second-choice drugs for over 30 common infections, and India's NLEM 2022 flags AWaRe categories. [WHO AWaRe Book 2022]",
          "**Schedule H1** (in force March 2014) covers third- and fourth-generation cephalosporins, carbapenems, newer quinolones and anti-TB drugs. [Drugs and Cosmetics Rules 2013]",
          "Pharmacists must keep a **separate H1 register** with prescriber, patient, drug and quantity for **3 years**, and packs carry a red boxed warning. [Drugs and Cosmetics Rules 2013]",
          "The **Red Line campaign (2016)** marks prescription-only antibiotic packs with a **vertical red line** and tells the public not to use them without a prescription. [MoHFW 2016]",
          "**Doctors must write the indication** on antibiotic prescriptions, as urged by DGHS in 2024. [DGHS 2024]",
        ],
      },
      {
        heading: "Prescribing strategies in primary care",
        points: [
          "Use the **ICMR Treatment Guidelines for Antimicrobial Use in Common Syndromes** and the NCDC National Treatment Guidelines as local references. [ICMR 2019]",
          "**No-antibiotic strategy** for self-limiting illness - common cold, acute bronchitis, most sore throats and acute otitis media over age 2 without systemic features. [NICE NG63 2017]",
          "**Back-up (delayed) prescribing:** give a prescription to be used only if symptoms worsen or fail to settle in a set time, e.g. 3-5 days for sore throat. [NICE NG84 2018]",
          "Use **FeverPAIN (score 4-5) or Centor (3-4)** to identify sore throats that may benefit from antibiotics. [NICE NG84 2018]",
          "Streptococcal pharyngitis: **amoxicillin 500 mg PO TDS for 10 days**, or benzathine penicillin 1.2 MU IM once, to prevent rheumatic fever. [ICMR 2019]",
          "Uncomplicated cystitis in women: **nitrofurantoin 100 mg PO BD for 5 days** - avoid ciprofloxacin as first line because of high E. coli resistance. [ICMR 2019]",
          "Community-acquired pneumonia without comorbidity: **amoxicillin 1 g PO TDS for 5 days**, adding doxycycline only if atypical cover is needed. [ICMR 2019]",
          "Cellulitis: **cefalexin 500 mg PO QID or cloxacillin 500 mg QID for 5-7 days**. [WHO AWaRe Book 2022]",
          "Watery diarrhoea needs **ORS and zinc, not antibiotics**; reserve antibiotics for dysentery, cholera and severe cases. [IAP 2024]",
          "Shorter courses are as effective for most infections - **5 days for CAP, 3-5 days for cystitis**. [NICE NG63 2017]",
          "Do not use antibiotics to treat **fever alone** - test for malaria, dengue and typhoid first. [ICMR 2019]",
        ],
      },
      {
        heading: "Stewardship, infection control and patient communication",
        points: [
          "Primary-care stewardship: **prescribing audit, feedback and peer comparison**, e.g. percentage of OPD encounters with an antibiotic (WHO target under 30 per cent). [WHO 2019]",
          "Track the **Access-to-Watch ratio** of a clinic's prescribing; aim for at least 60 per cent Access. [WHO AWaRe 2023]",
          "The **ICMR Antimicrobial Stewardship Programme guidelines 2018** require a hospital AMS committee, antibiogram, prescription audit and pre-authorisation of Reserve drugs. [ICMR AMSP 2018]",
          "**Hand hygiene at the WHO five moments** is the single most effective HAI measure; alcohol rub for 20-30 seconds. [NCDC IPC 2020]",
          "Use **care bundles** for central line, catheter-associated UTI, ventilator-associated pneumonia and surgical-site infection. [NCDC IPC 2020]",
          "Surgical prophylaxis is **cefazolin 2 g IV within 60 minutes before incision**, as a single dose - not a 5-day course. [ICMR 2019]",
          "Kayakalp and NQAS assess **infection control, biomedical waste and cleanliness** in public facilities. [NHM 2023]",
          "Tell patients that **antibiotics do not work on viruses** and do not speed recovery from colds - a cough may last 3 weeks naturally. [NICE NG63 2017]",
          "Give **safety-netting advice** - what to watch for and when to return - which reassures more than a prescription. [NICE NG63 2017]",
          "Ask patients to **complete the prescribed course, not share or store leftovers**, and never buy antibiotics without a prescription. [MoHFW 2016]",
          "Vaccination (**pneumococcal, Hib, typhoid conjugate, influenza**) reduces infections and hence antibiotic use. [NIS MoHFW 2024]",
        ],
      },
    ],
    tables: [
      {
        heading: "WHO AWaRe classification with primary-care examples",
        columns: ["Group", "Role", "Examples", "Primary-care use"],
        rows: [
          ["Access", "First or second choice, narrow spectrum", "Amoxicillin, co-amoxiclav, cefalexin, doxycycline, nitrofurantoin, co-trimoxazole", "Most common infections"],
          ["Watch", "Higher resistance potential", "Azithromycin, ciprofloxacin, cefixime, ceftriaxone, meropenem", "Specific indications only, e.g. typhoid, gonorrhoea"],
          ["Reserve", "Last resort for MDR organisms", "Colistin, linezolid, tigecycline, ceftazidime-avibactam", "Hospital, specialist authorisation"],
        ],
      },
      {
        heading: "Resistance criteria types (ECDC-CDC definitions)",
        columns: ["Type", "Definition", "Example"],
        rows: [
          ["MDR", "Non-susceptible to 1 or more agents in 3 or more categories", "ESBL E. coli"],
          ["XDR", "Susceptible only in 2 or fewer categories", "Carbapenem-resistant Acinetobacter susceptible to colistin"],
          ["PDR", "Non-susceptible to all agents", "Pan-resistant Klebsiella"],
        ],
      },
    ],
    redFlags: [
      "Sepsis in a patient recently treated with several antibiotic courses - suspect MDR organism; admit and send cultures before antibiotics.",
      "UTI not responding after 48 hours of an Access antibiotic - culture, suspect ESBL, refer if febrile.",
      "Typhoid not settling on azithromycin or cefixime by day 5 - suspect resistance or complication.",
      "Pneumonia or TB with prior incomplete treatment - test for drug resistance (CBNAAT).",
      "Patient buying Watch or Reserve antibiotics over the counter repeatedly - counsel and document.",
      "Cluster of post-operative wound infections in a facility - infection-control review.",
    ],
    pearls: [
      "MDR is 3 or more categories, XDR is all but 2 or fewer, PDR is all.",
      "NAP-AMR 2017 has six strategic priorities and a One Health spine.",
      "Kerala's KARSAP 2018 was the first state AMR action plan.",
      "Access, Watch, Reserve - aim for at least 60 per cent Access now and 70 per cent by 2030.",
      "Schedule H1 register is kept for 3 years; the Red Line marks prescription-only antibiotics.",
      "Back-up prescribing cuts antibiotic use without worse outcomes.",
      "Surgical prophylaxis is one dose within 60 minutes of incision.",
      "Colistin as a growth promoter in animals was banned in India in 2019.",
      "Antibiotics do not treat fever - diagnosis does.",
    ],
    mcqs: [
      {
        id: "infectious-fever-antimicrobial-resistance-q1",
        stem: "A Klebsiella isolate is resistant to all tested antibiotics except colistin and tigecycline. How is it classified?",
        options: [
          "Multidrug-resistant",
          "Pan-drug-resistant",
          "Intrinsically resistant",
          "Extensively drug-resistant",
        ],
        answer: 3,
        explanation:
          "An organism remaining susceptible to only one or two categories is extensively drug-resistant (XDR). Pan-drug-resistant would mean no active agent at all, MDR is a lower threshold of three or more categories, and intrinsic resistance is natural rather than acquired.",
        difficulty: "moderate",
      },
      {
        id: "infectious-fever-antimicrobial-resistance-q2",
        stem: "Which antibiotic belongs to the WHO AWaRe Access group?",
        options: [
          "Nitrofurantoin",
          "Cefixime",
          "Azithromycin",
          "Linezolid",
        ],
        answer: 0,
        explanation:
          "Nitrofurantoin is an Access antibiotic recommended first-line for cystitis. Cefixime and azithromycin are Watch antibiotics with higher resistance potential, and linezolid is a Reserve drug kept for MDR Gram-positive infections.",
        difficulty: "easy",
      },
      {
        id: "infectious-fever-antimicrobial-resistance-q3",
        stem: "Which Indian state was the first to launch its own antimicrobial resistance strategic action plan?",
        options: [
          "Madhya Pradesh",
          "Delhi",
          "Kerala",
          "Tamil Nadu",
        ],
        answer: 2,
        explanation:
          "Kerala launched KARSAP in October 2018, the first state plan. Madhya Pradesh followed in 2019 and Delhi in 2020, while Tamil Nadu came later.",
        difficulty: "easy",
      },
      {
        id: "infectious-fever-antimicrobial-resistance-q4",
        stem: "A 30-year-old man has sore throat for 2 days with cough and runny nose, temperature 37.8 C and no tonsillar exudate. FeverPAIN score is 1. What is the most appropriate strategy?",
        options: [
          "Amoxicillin 500 mg TDS for 10 days",
          "No antibiotic, symptomatic care and safety-netting advice",
          "Azithromycin 500 mg once daily for 3 days",
          "Back-up prescription of cefixime",
        ],
        answer: 1,
        explanation:
          "A FeverPAIN score of 0-1 predicts a low chance of streptococcal infection, so NICE advises no antibiotic with symptomatic care and safety-netting. Immediate amoxicillin or azithromycin is unnecessary, and a back-up prescription of a Watch drug like cefixime is inappropriate.",
        difficulty: "moderate",
      },
      {
        id: "infectious-fever-antimicrobial-resistance-q5",
        stem: "Under the Drugs and Cosmetics Rules, how long must a pharmacist retain the Schedule H1 register of antibiotic sales?",
        options: [
          "1 year",
          "2 years",
          "5 years",
          "3 years",
        ],
        answer: 3,
        explanation:
          "Schedule H1 requires a separate register with prescriber, patient, drug and quantity to be retained for 3 years for inspection. One or two years is too short, and five years is not the stated period.",
        difficulty: "hard",
      },
    ],
    theory: [
      {
        id: "infectious-fever-antimicrobial-resistance-t1",
        paper: "IV",
        kind: "long",
        marks: 10,
        minutes: 18,
        frequency: "core",
        question:
          "What is antimicrobial resistance? Discuss its drivers in India, the National Action Plan on AMR and the role of the family physician in antibiotic stewardship. [2+2+3+3]",
        openingLines: [
          "Antimicrobial resistance is the ability of a microorganism to survive and multiply despite an antimicrobial that previously killed or inhibited it.",
          "Bacterial AMR caused 1.27 million deaths globally in 2019, with India bearing the highest national toll (GRAM 2022).",
        ],
        answer: [
          {
            heading: "Definitions",
            points: ["AMR, MDR (3 or more categories), XDR (2 or fewer susceptible), PDR (none), superbug."],
          },
          {
            heading: "Drivers in India",
            points: [
              "OTC sales, self-medication, informal providers, irrational FDCs, patient demand.",
              "Veterinary growth promoters, pharma effluent, poor WASH and hospital IPC.",
            ],
          },
          {
            heading: "NAP-AMR 2017",
            points: [
              "Six priorities: awareness, surveillance, IPC, optimised use, research, leadership.",
              "State plans: KARSAP 2018, MP 2019, Delhi 2020; NAP-AMR 2.0 for 2025-29.",
              "Schedule H1, Red Line campaign, colistin ban, AWaRe in NLEM.",
            ],
          },
          {
            heading: "Family physician's role",
            points: [
              "AWaRe-based prescribing using ICMR guidelines; no-antibiotic and back-up strategies.",
              "Short courses, point-of-care diagnosis, vaccination, hand hygiene.",
              "Audit and feedback of own prescribing; patient education and safety-netting.",
            ],
          },
        ],
        mustDraw: ["AWaRe pyramid with examples", "NAP-AMR six priorities wheel"],
        markSplit: [
          { part: "Definition", marks: 2 },
          { part: "Drivers", marks: 2 },
          { part: "NAP-AMR", marks: 3 },
          { part: "Family physician role", marks: 3 },
        ],
        keywords: ["AMR", "NAP-AMR", "stewardship", "AWaRe"],
      },
      {
        id: "infectious-fever-antimicrobial-resistance-t2",
        paper: "IV",
        kind: "short-note",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question:
          "WHO AWaRe classification of antibiotics and its use in primary-care prescribing. [4+6]",
        openingLines: [
          "AWaRe groups antibiotics into Access, Watch and Reserve to guide prescribing and monitor consumption (WHO 2023).",
          "The UNGA 2024 target is for 70 per cent of human antibiotic use to come from the Access group by 2030.",
        ],
        answer: [
          {
            heading: "Classification",
            points: [
              "Access - amoxicillin, cefalexin, doxycycline, nitrofurantoin.",
              "Watch - azithromycin, ciprofloxacin, cefixime, ceftriaxone.",
              "Reserve - colistin, linezolid, tigecycline, ceftazidime-avibactam.",
            ],
          },
          {
            heading: "Use in primary care",
            points: [
              "Start with Access drugs for common syndromes using the WHO AWaRe Antibiotic Book 2022 and ICMR guidelines.",
              "Watch drugs only for defined indications; never Reserve drugs without specialist input.",
              "Audit Access share of prescriptions, give feedback, and educate patients.",
            ],
          },
        ],
        mustDraw: ["Three-tier AWaRe table with examples"],
        markSplit: [
          { part: "Classification", marks: 4 },
          { part: "Application", marks: 6 },
        ],
        keywords: ["AWaRe", "Access Watch Reserve", "WHO EML"],
      },
    ],
    references: [
      "National Action Plan on Antimicrobial Resistance, MoHFW, 2017",
      "ICMR Treatment Guidelines for Antimicrobial Use in Common Syndromes, 2019",
      "ICMR Antimicrobial Stewardship Program Guideline, 2018",
      "WHO AWaRe Classification, 2023, and The WHO AWaRe Antibiotic Book, 2022",
      "WHO Bacterial Priority Pathogens List, 2024",
      "GBD 2019 Antimicrobial Resistance Collaborators, Lancet 2022",
      "NICE NG63 Antimicrobial stewardship: changing risk-related behaviours, 2017, and NG84 Sore throat, 2018",
      "Park's Textbook of Preventive and Social Medicine, 28th ed, 2025",
    ],
  },
  {
    id: "infectious-fever-tropical-fevers-zoonoses",
    title: "Leptospirosis, chikungunya, JE/AES and other zoonoses",
    oneLiner:
      "Zoonoses are **infections naturally transmitted between vertebrate animals and humans** - in India leptospirosis, scrub typhus, Japanese encephalitis, Kyasanur forest disease, Nipah, brucellosis, anthrax and plague - which, with vector-borne chikungunya, make up a large share of **acute undifferentiated febrile illness (AUFI)** and are controlled through a One Health approach, vector and rodent control, vaccination and IDSP/IHIP surveillance.",
    frequency: "common",
    keywords: [
      "leptospirosis",
      "Weil disease",
      "MAT",
      "chikungunya",
      "Japanese encephalitis",
      "AES",
      "acute encephalitis syndrome",
      "Kyasanur forest disease",
      "KFD",
      "Nipah",
      "Chandipura",
      "brucellosis",
      "anthrax",
      "plague",
      "scrub typhus",
      "AUFI",
      "zoonoses",
      "One Health",
      "IDSP",
      "IHIP",
    ],
    sections: [
      {
        heading: "Zoonoses: classification and One Health",
        points: [
          "**Zoonoses** are diseases and infections naturally transmitted between vertebrate animals and man; about **60 per cent of known and 75 per cent of emerging** human infections are zoonotic. [Park 28e]",
          "By reservoir: **anthropozoonoses** (animal to man - rabies, plague, brucellosis), **zooanthroponoses** (man to animal - human TB in cattle) and **amphixenoses** (both ways - Trypanosoma cruzi, staphylococci). [Park 28e]",
          "By life cycle: **direct zoonoses** (rabies, brucellosis), **cyclozoonoses** needing two vertebrate hosts (hydatid, taeniasis), **metazoonoses** via invertebrates (plague, JE, KFD) and **saprozoonoses** via soil or plants (larva migrans). [Park 28e]",
          "**One Health** integrates human, animal and environmental health, because the pathogen, reservoir and vector sit in all three sectors. [WHO/FAO/WOAH/UNEP 2022]",
          "NCDC runs the **Programme for Prevention and Control of Zoonotic Diseases**, and the **National One Health Mission** coordinates health, animal husbandry and environment ministries. [NCDC 2024]",
          "The **National Institute of One Health, Nagpur**, is being developed as a BSL-4 hub for zoonotic research. [ICMR 2024]",
          "Joint human-animal outbreak response teams investigate events such as **avian influenza, Nipah and anthrax**. [NCDC 2024]",
          "Drivers of zoonotic spillover include **deforestation, intensive livestock farming, wildlife trade and climate change** that expand vector range. [WHO 2024]",
        ],
      },
      {
        heading: "Leptospirosis",
        points: [
          "Caused by **Leptospira interrogans**, excreted in the urine of rats, cattle, pigs and dogs, entering through abraded skin or mucosa from contaminated water or soil. [Harrison 22e]",
          "High endemic states: **Kerala, Tamil Nadu, Karnataka, Maharashtra, Gujarat and Andaman and Nicobar**, with post-monsoon and post-flood peaks. [NCDC NPPCL 2023]",
          "At-risk groups: **paddy farmers, sewage and sanitation workers, fishermen, veterinarians, abattoir workers** and flood victims. [Park 28e]",
          "Incubation **7-12 days** (range 2-30); biphasic course with a leptospiraemic phase and an immune phase. [Harrison 22e]",
          "Clues: abrupt fever, severe myalgia with **calf tenderness** and **conjunctival suffusion** without discharge. [Harrison 22e]",
          "**Weil disease:** jaundice, acute kidney injury (often non-oliguric with hypokalaemia) and bleeding - case-fatality 5-15 per cent. [Harrison 22e]",
          "**Severe pulmonary haemorrhage syndrome** carries mortality over 50 per cent and needs ICU care. [Harrison 22e]",
          "Diagnosis: **IgM ELISA after day 5** at the district lab; **MAT is the gold standard** (single titre 1:400 or more, or fourfold rise); PCR in the first week. [NCDC NPPCL 2023]",
          "Mild disease: **doxycycline 100 mg PO BD for 7 days**, or amoxicillin 500 mg QID, or azithromycin in pregnancy and children. [NCDC NPPCL 2023]",
          "Severe disease: **IV benzylpenicillin 1.5 MU 6-hourly or ceftriaxone 1 g IV daily for 7 days**, with dialysis and ventilation as needed. [Harrison 22e]",
          "Chemoprophylaxis for high-risk exposure: **doxycycline 200 mg PO once weekly** during the exposure period (e.g. flood relief, paddy planting). [NCDC NPPCL 2023]",
        ],
      },
      {
        heading: "Chikungunya",
        points: [
          "An **alphavirus** transmitted by **Aedes aegypti and Aedes albopictus**; the E1-A226V mutation improved spread by albopictus in the 2006 Indian epidemic. [NCVBDC 2023]",
          "Incubation 3-7 days; sudden **high fever with severe, symmetric polyarthralgia** of small joints, rash and oedema - the name means that which bends up. [Harrison 22e]",
          "Differentiate from dengue: arthralgia and arthritis dominate, **thrombocytopenia and bleeding are mild**; co-infection is common. [NCVBDC 2023]",
          "Diagnosis: **RT-PCR in days 1-5** and **IgM ELISA after day 5** (NIV kits at sentinel sites). [NCVBDC 2023]",
          "Acute phase: rest, fluids and **paracetamol 500-1000 mg 6-8 hourly (max 3 g/day)**; avoid aspirin and NSAIDs until dengue is excluded. [NCVBDC 2016]",
          "Subacute arthritis (up to 3 months): NSAIDs such as **naproxen 250-500 mg BD** with short courses of **prednisolone 10 mg/day** for severe tenosynovitis. [NCVBDC 2016]",
          "**Chronic chikungunya arthritis** persisting beyond 3 months affects up to a third of patients; inflammatory forms respond to **hydroxychloroquine 200-400 mg/day or methotrexate 7.5-15 mg weekly**. [Harrison 22e]",
          "Neonates born to viraemic mothers, the elderly and those with comorbidities can develop encephalitis, myocarditis or bullous skin disease. [Harrison 22e]",
          "Vaccines (live-attenuated and virus-like-particle) have been licensed abroad but are **not part of the Indian programme**; control rests on Aedes source reduction. [WHO 2025]",
        ],
      },
      {
        heading: "Japanese encephalitis and acute encephalitis syndrome",
        points: [
          "JE is a **flavivirus** transmitted by **Culex tritaeniorhynchus** from **pigs (amplifying hosts)** and **ardeid birds (reservoir)**; humans are dead-end hosts. [Park 28e]",
          "Endemic in paddy-growing areas of **Uttar Pradesh, Bihar, Assam, West Bengal** and others; most symptomatic cases are children under 15. [NCVBDC 2023]",
          "Only **1 in 250-1,000 infections** is symptomatic, but encephalitis kills 20-30 per cent and leaves a third with sequelae. [Harrison 22e]",
          "**AES case definition (WHO):** acute onset of fever with **change in mental status and/or new-onset seizures** (excluding simple febrile seizures) in a person of any age at any time of year. [NCVBDC AES 2023]",
          "AES causes in India besides JE: **scrub typhus**, dengue, HSV, enteroviruses, **Chandipura**, Nipah, and hypoglycaemic encephalopathy linked to litchi toxin in Muzaffarpur. [NCVBDC AES 2023]",
          "JE diagnosis: **JE IgM MAC-ELISA in CSF** (preferred) or serum. [NCVBDC AES 2023]",
          "Management is supportive: airway, seizure control, raised ICP care, **treat hypoglycaemia** and give empirical doxycycline or azithromycin for scrub typhus. [NCVBDC AES 2023]",
          "**JE vaccine (live attenuated SA 14-14-2)** is given in UIP in endemic districts at **9-12 months and 16-24 months**, 0.5 mL SC; adult campaigns are held in high-burden districts. [NIS MoHFW 2024]",
          "The inactivated **JENVAC** vaccine is an alternative in campaigns. [NIS MoHFW 2024]",
          "Prevention: **mosquito nets, pig sties away from homes**, fogging in outbreaks and intermittent irrigation of paddy fields. [Park 28e]",
        ],
      },
      {
        heading: "KFD, Nipah and Chandipura",
        points: [
          "**Kyasanur forest disease** (monkey fever) is a tick-borne flavivirus first seen in **Shimoga, Karnataka, in 1957**, spread by **Haemaphysalis spinigera**, with monkeys as amplifiers. [Park 28e]",
          "KFD now occurs in Kerala, Goa, Maharashtra and Tamil Nadu; it is **biphasic** - fever, myalgia and bleeding, then meningoencephalitis in a fifth. [Harrison 22e]",
          "**Monkey deaths in forest areas** are the sentinel warning; prevention uses repellents (DMP oil), protective clothing and acaricide spraying. [Park 28e]",
          "**Nipah virus** (henipavirus) has **Pteropus fruit bats** as reservoir; outbreaks in **Siliguri 2001, Nadia 2007 and Kerala repeatedly since 2018**. [NCDC Nipah 2023]",
          "Nipah causes **encephalitis and severe respiratory illness** with case-fatality 40-75 per cent, spreads person to person in hospitals, and has no licensed vaccine. [WHO 2024]",
          "Nipah response: isolation, **contact tracing and 21-day monitoring**, PPE, RT-PCR at NIV Pune or Kerala labs, and avoiding fruit bitten by bats or raw date-palm sap. [NCDC Nipah 2023]",
          "Nipah treatment is supportive; **ribavirin** has uncertain benefit and the **m102.4 monoclonal antibody** is available only under emergency protocols. [WHO 2024]",
          "**Chandipura virus** (vesiculovirus) spread by **sandflies** causes rapidly fatal encephalitis in children under 15 - outbreaks in Andhra Pradesh 2003 and Gujarat 2024. [NIV 2024]",
        ],
      },
      {
        heading: "Brucellosis, anthrax, plague and scrub typhus",
        points: [
          "**Brucellosis** (B. melitensis from goats and sheep, B. abortus from cattle) spreads by raw milk and contact with animal products - an occupational disease of dairy workers, vets and butchers. [Harrison 22e]",
          "Brucellosis gives **undulant fever, sweats, sacroiliitis, spondylitis, orchitis** and hepatosplenomegaly; diagnose by prolonged blood culture and **SAT titre 1:160 or more**. [Harrison 22e]",
          "Treat brucellosis with **doxycycline 100 mg BD for 6 weeks plus gentamicin 5 mg/kg/day IV for 7 days** (or streptomycin 1 g IM for 2-3 weeks), or doxycycline plus rifampicin 600-900 mg/day for 6 weeks. [Harrison 22e]",
          "**Cutaneous anthrax** (over 95 per cent of cases) is a painless black eschar with marked non-pitting oedema, seen in tribal Odisha and Andhra Pradesh after handling or eating dead livestock. [NCDC 2023]",
          "Treat naturally acquired cutaneous anthrax with **ciprofloxacin 500 mg BD or doxycycline 100 mg BD for 7-10 days**; never incise the lesion. [Harrison 22e]",
          "**Plague** (Yersinia pestis, flea Xenopsylla cheopis) - Surat 1994 pneumonic and Beed bubonic outbreaks; a **cheopis index above 1** signals risk. [Park 28e]",
          "Treat plague with **gentamicin 5 mg/kg/day or streptomycin**, or doxycycline; contacts get **doxycycline 100 mg BD for 7 days** as chemoprophylaxis. [Harrison 22e]",
          "**Scrub typhus** (Orientia tsutsugamushi, via larval trombiculid mites) is a leading cause of AUFI in India; look for the **eschar** in the groin, axilla and under the breasts. [ICMR 2019]",
          "Treat scrub typhus with **doxycycline 100 mg PO BD for 7 days**, or azithromycin 500 mg daily for 5 days in pregnancy and children. [ICMR 2019]",
          "Severe scrub typhus: **IV doxycycline plus IV azithromycin** combination was superior to either alone in the INTREST trial. [INTREST NEJM 2025]",
          "For AUFI with no clear source after malaria and dengue testing, **empirical doxycycline** covers scrub typhus and leptospirosis. [ICMR 2019]",
        ],
      },
      {
        heading: "Control, notification and the family physician",
        points: [
          "**Rodent control:** environmental sanitation, rat-proofing of stores and **rodenticides** - zinc phosphide (acute) or anticoagulants such as bromadiolone. [Park 28e]",
          "In plague, **kill the fleas before the rats** - insecticide dusting of burrows first, otherwise fleas leave dead rats for humans. [Park 28e]",
          "**Aedes control:** weekly dry day, covering water containers, **temephos 1 ppm** larviciding, and space spraying during outbreaks. [NCVBDC 2023]",
          "Scrub typhus prevention: clear vegetation around homes, **wear full-length clothing** in fields and avoid sitting on grass. [ICMR 2019]",
          "Occupational prevention: **gumboots and gloves** for farmers and sewage workers, pasteurised milk, protective gear for abattoir staff. [Park 28e]",
          "**IDSP (2004)** now reports through the **Integrated Health Information Platform (IHIP)**, launched in 2021 for real-time digital surveillance. [NCDC IHIP 2021]",
          "IHIP uses **S forms (syndromic, by health workers), P forms (presumptive, by clinicians) and L forms (laboratory confirmed)**. [NCDC IHIP 2021]",
          "Report clusters and suspected **Nipah, plague, anthrax, JE and KFD** immediately to the district surveillance unit - outbreaks need a response within 24-48 hours. [NCDC IDSP 2023]",
          "The family physician should **ask about occupation, animal contact, floodwater and travel** in every fever, examine for eschar and conjunctival suffusion, and test for malaria and dengue first. [ICMR 2019]",
          "**Refer urgently** for jaundice with oliguria, bleeding, breathlessness, altered sensorium or seizures. [ICMR 2019]",
        ],
      },
    ],
    tables: [
      {
        heading: "Zoonoses classification by transmission cycle",
        columns: ["Type", "Hosts needed", "Examples"],
        rows: [
          ["Direct", "One vertebrate host, direct contact", "Rabies, brucellosis, anthrax, leptospirosis"],
          ["Cyclo", "Two or more vertebrate hosts", "Hydatid disease, Taenia solium"],
          ["Meta", "Vertebrate plus invertebrate vector", "Plague, JE, KFD, scrub typhus"],
          ["Sapro", "Vertebrate plus inanimate reservoir", "Larva migrans, some mycoses"],
        ],
      },
      {
        heading: "AUFI differentials: clues, tests and treatment",
        columns: ["Disease", "Clue", "Test", "First-line treatment"],
        rows: [
          ["Leptospirosis", "Calf tenderness, conjunctival suffusion, floodwater", "IgM ELISA, MAT", "Doxycycline 100 mg BD 7 days; severe - penicillin G or ceftriaxone"],
          ["Scrub typhus", "Eschar, lymphadenopathy, hilly or rural area", "IgM ELISA, PCR", "Doxycycline 100 mg BD 7 days"],
          ["Chikungunya", "Severe polyarthralgia, rash", "RT-PCR, IgM ELISA", "Paracetamol, later NSAIDs, HCQ for chronic arthritis"],
          ["Dengue", "Retro-orbital pain, falling platelets", "NS1, IgM", "Fluids, paracetamol, no NSAIDs"],
          ["Brucellosis", "Raw milk, sacroiliitis, sweats", "Blood culture, SAT", "Doxycycline 6 weeks plus gentamicin"],
          ["Malaria", "Rigors, travel to endemic area", "RDT, smear", "ACT per NCVBDC 2023"],
        ],
      },
    ],
    redFlags: [
      "Fever with jaundice, oliguria or bleeding after floodwater exposure - Weil disease; refer.",
      "Fever with haemoptysis or breathlessness in suspected leptospirosis - pulmonary haemorrhage.",
      "Fever with altered sensorium or seizures in a child - AES; refer and check blood glucose.",
      "Cluster of encephalitis or respiratory deaths with bat exposure - suspect Nipah; notify immediately.",
      "Monkey deaths in forest villages followed by fever - suspect KFD.",
      "Black painless eschar with massive oedema after handling a dead animal - anthrax.",
      "Painful bubo with fever or rapidly progressive pneumonia in a rat-fall area - plague.",
    ],
    pearls: [
      "Conjunctival suffusion plus calf tenderness after floodwater exposure is leptospirosis until proved otherwise.",
      "MAT is the gold standard for leptospirosis; doxycycline 200 mg weekly is the chemoprophylaxis.",
      "Pigs are amplifiers and ardeid birds reservoirs of JE; humans are dead-end hosts.",
      "AES is fever plus altered mental status or new seizures - always check sugar and cover scrub typhus.",
      "KFD was first described in Shimoga in 1957; monkey deaths are the sentinel.",
      "In plague, kill fleas before rats.",
      "Look for the eschar in the groin, axilla and under the breasts in every AUFI.",
      "Chikungunya: paracetamol first, NSAIDs only after dengue is excluded.",
      "Brucellosis needs 6 weeks of doxycycline with an aminoglycoside.",
      "IHIP uses S, P and L forms for syndromic, presumptive and lab-confirmed reporting.",
    ],
    mcqs: [
      {
        id: "infectious-fever-tropical-fevers-zoonoses-q1",
        stem: "A sewage worker in Mumbai presents 10 days after monsoon floods with fever, severe calf pain, conjunctival suffusion, jaundice and reduced urine output. What is the gold-standard confirmatory test?",
        options: [
          "Weil-Felix test",
          "Microscopic agglutination test",
          "Widal test",
          "Dark-field microscopy of urine",
        ],
        answer: 1,
        explanation:
          "The microscopic agglutination test (MAT) is the reference test for leptospirosis, causing Weil disease here. Weil-Felix detects rickettsial antibodies non-specifically, Widal is for enteric fever, and dark-field microscopy is insensitive and prone to artefacts.",
        difficulty: "easy",
      },
      {
        id: "infectious-fever-tropical-fevers-zoonoses-q2",
        stem: "In Japanese encephalitis transmission, which animal acts as the amplifying host?",
        options: [
          "Cattle",
          "Monkeys",
          "Pigs",
          "Fruit bats",
        ],
        answer: 2,
        explanation:
          "Pigs develop high viraemia and amplify JE virus for Culex mosquitoes, while ardeid birds are reservoirs. Cattle divert mosquitoes but do not amplify, monkeys amplify KFD, and fruit bats are reservoirs of Nipah.",
        difficulty: "easy",
      },
      {
        id: "infectious-fever-tropical-fevers-zoonoses-q3",
        stem: "A dairy farmer has had intermittent fever, night sweats and low back pain for 6 weeks; he drinks raw goat milk. Blood culture is awaited and SAT is 1:320. What is the recommended treatment?",
        options: [
          "Doxycycline for 6 weeks with gentamicin for the first 7 days",
          "Ciprofloxacin for 7 days",
          "Azithromycin for 5 days",
          "Anti-tubercular therapy for 6 months",
        ],
        answer: 0,
        explanation:
          "Brucellosis with sacroiliitis needs prolonged combination therapy - doxycycline 6 weeks plus an aminoglycoside - to prevent relapse. A 7-day quinolone or 5-day azithromycin course relapses, and ATT is not indicated with a positive SAT and raw-milk exposure.",
        difficulty: "moderate",
      },
      {
        id: "infectious-fever-tropical-fevers-zoonoses-q4",
        stem: "During a suspected plague outbreak with rat falls in a village, what should be the first control measure?",
        options: [
          "Mass rodenticide baiting",
          "Mass vaccination",
          "Closing all schools",
          "Insecticide dusting of rat burrows and houses",
        ],
        answer: 3,
        explanation:
          "Fleas must be killed before rats, otherwise infected fleas leave dying rats and bite humans. Rodenticides come after flea control, no vaccine is in routine use, and school closure does not interrupt flea-borne transmission.",
        difficulty: "moderate",
      },
      {
        id: "infectious-fever-tropical-fevers-zoonoses-q5",
        stem: "A 45-year-old woman recovering from chikungunya 4 months ago has persistent symmetric swelling of the wrists and MCP joints with morning stiffness. What is the best treatment?",
        options: [
          "Hydroxychloroquine or methotrexate as for inflammatory arthritis",
          "Oral ribavirin",
          "Long-term aspirin 325 mg daily",
          "Intravenous ceftriaxone",
        ],
        answer: 0,
        explanation:
          "Chronic chikungunya arthritis beyond 3 months with an inflammatory pattern is managed like rheumatoid arthritis with DMARDs such as hydroxychloroquine or methotrexate. Ribavirin has no proven role, long-term aspirin is not recommended, and antibiotics are irrelevant to a viral arthritis.",
        difficulty: "hard",
      },
    ],
    theory: [
      {
        id: "infectious-fever-tropical-fevers-zoonoses-t1",
        paper: "I",
        kind: "long",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question:
          "A paddy farmer presents with fever, myalgia and jaundice after floods. Discuss the epidemiology, clinical features, diagnosis, treatment and prevention of leptospirosis. [2+2+2+2+2]",
        openingLines: [
          "Leptospirosis is a zoonosis caused by Leptospira interrogans, acquired through contact of abraded skin or mucosa with water or soil contaminated by urine of infected rats and other animals.",
          "It is endemic in Kerala, Tamil Nadu, Karnataka, Maharashtra and Gujarat, with post-monsoon peaks.",
        ],
        answer: [
          {
            heading: "Epidemiology",
            points: ["Rats as main reservoir; farmers, sewage workers, fishermen, vets; floods."],
          },
          {
            heading: "Clinical features",
            points: [
              "Biphasic fever, myalgia, calf tenderness, conjunctival suffusion.",
              "Weil disease: jaundice, AKI, bleeding; pulmonary haemorrhage syndrome; myocarditis.",
            ],
          },
          {
            heading: "Diagnosis",
            points: ["IgM ELISA after day 5; MAT gold standard; PCR early; LFT, RFT, platelets, potassium."],
          },
          {
            heading: "Treatment",
            points: [
              "Mild: doxycycline 100 mg BD 7 days.",
              "Severe: penicillin G 1.5 MU IV 6-hourly or ceftriaxone 1 g IV daily 7 days; dialysis, ventilation.",
            ],
          },
          {
            heading: "Prevention",
            points: [
              "Rodent control, gumboots and gloves, avoid wading in floodwater.",
              "Doxycycline 200 mg weekly for high-risk exposure; health education; IHIP reporting.",
            ],
          },
        ],
        mustDraw: ["Transmission cycle from rat urine to human"],
        markSplit: [
          { part: "Epidemiology", marks: 2 },
          { part: "Clinical features", marks: 2 },
          { part: "Diagnosis", marks: 2 },
          { part: "Treatment", marks: 2 },
          { part: "Prevention", marks: 2 },
        ],
        keywords: ["leptospirosis", "Weil disease", "MAT", "doxycycline prophylaxis"],
      },
      {
        id: "infectious-fever-tropical-fevers-zoonoses-t2",
        paper: "IV",
        kind: "short-note",
        marks: 10,
        minutes: 18,
        frequency: "less-common",
        question:
          "Classify zoonoses with examples and describe the One Health approach to their control in India. [5+5]",
        openingLines: [
          "Zoonoses are diseases naturally transmitted between vertebrate animals and man; about three-quarters of emerging infections are zoonotic.",
          "One Health integrates human, animal and environmental sectors for surveillance and control.",
        ],
        answer: [
          {
            heading: "Classification",
            points: [
              "By reservoir: anthropozoonoses, zooanthroponoses, amphixenoses.",
              "By cycle: direct, cyclo-, meta- and saprozoonoses with Indian examples.",
              "By agent: bacterial (anthrax, plague, brucellosis, leptospirosis), viral (rabies, JE, KFD, Nipah), rickettsial (scrub typhus), parasitic (hydatid).",
            ],
          },
          {
            heading: "One Health in India",
            points: [
              "NCDC zoonoses programme, National One Health Mission, NIOH Nagpur.",
              "Joint outbreak teams; IDSP/IHIP with animal-husbandry reporting.",
              "Rodent and vector control, livestock vaccination, food safety, antibiotic stewardship in animals.",
            ],
          },
        ],
        mustDraw: ["Three-circle One Health diagram (human, animal, environment)"],
        markSplit: [
          { part: "Classification", marks: 5 },
          { part: "One Health", marks: 5 },
        ],
        keywords: ["zoonoses", "One Health", "cyclozoonoses", "metazoonoses"],
      },
    ],
    references: [
      "Harrison's Principles of Internal Medicine, 22nd ed, 2025",
      "Park's Textbook of Preventive and Social Medicine, 28th ed, 2025",
      "NCDC Guidelines for Prevention and Control of Leptospirosis, 2023",
      "NCVBDC National Guidelines for Clinical Management of Chikungunya, 2016, and AES/JE Guidelines, 2023",
      "ICMR Treatment Guidelines for Antimicrobial Use in Common Syndromes, 2019",
      "NCDC Nipah Virus Disease Guidelines, 2023",
      "Integrated Health Information Platform (IHIP) Guidelines, NCDC, 2021",
    ],
  },
];

export default topics;
