import type { Topic } from "../../lib/types";

const topics: Topic[] = [
  {
    id: "musculoskeletal-rheumatoid-arthritis",
    title: "Rheumatoid arthritis and DMARD monitoring in family practice",
    oneLiner:
      "Rheumatoid arthritis is a chronic autoimmune, symmetrical, erosive polyarthritis of the small joints of the hands and feet with extra-articular disease; it is classified by the **ACR/EULAR 2010 criteria (6 or more of 10)**, treated to target (remission, DAS28 below 2.6) with **methotrexate started early as the anchor DMARD plus short-term glucocorticoid**, escalated every 3-6 months if the target is missed, and made safe in primary care by structured blood monitoring, vaccination, TB screening and cardiovascular risk care.",
    frequency: "core",
    keywords: [
      "rheumatoid arthritis",
      "RA",
      "polyarthritis",
      "ACR/EULAR 2010",
      "rheumatoid factor",
      "anti-CCP",
      "ACPA",
      "DAS28",
      "CDAI",
      "treat to target",
      "methotrexate",
      "hydroxychloroquine",
      "sulfasalazine",
      "leflunomide",
      "DMARD monitoring",
      "tofacitinib",
      "biologics",
      "swan neck",
      "boutonniere",
      "chikungunya arthritis",
    ],
    sections: [
      {
        heading: "Approach to polyarthritis: inflammatory versus mechanical",
        points: [
          "**Inflammatory joint pain** has early-morning stiffness lasting more than 30-60 minutes, improves with activity, and comes with soft-tissue swelling, warmth, fatigue and raised ESR or CRP. [Harrison 22e]",
          "**Mechanical (degenerative) pain** worsens with use and eases with rest, with stiffness under 30 minutes, bony enlargement and crepitus. [Harrison 22e]",
          "Define the **pattern**: number of joints (mono, oligo 2-4, poly 5 or more), symmetry, small versus large joints, and involvement of the DIP joints and spine. [Kelley and Firestein 11e]",
          "**Symmetrical small-joint polyarthritis** suggests RA, SLE, viral arthritis (parvovirus, chikungunya, hepatitis B and C) or polyarticular psoriatic arthritis. [Kelley and Firestein 11e]",
          "**DIP involvement** points to osteoarthritis (Heberden nodes) or psoriatic arthritis, and is characteristically spared in RA. [Harrison 22e]",
          "**Asymmetrical lower-limb oligoarthritis with enthesitis or back pain** suggests reactive arthritis or another spondyloarthritis. [Harrison 22e]",
          "**Duration matters:** arthritis under 6 weeks is often viral and self-limiting, which is why the ACR/EULAR criteria score symptom duration. [Kelley and Firestein 11e]",
          "The **MCP and MTP squeeze test** (pain on lateral compression across the knuckles) is a quick screen for small-joint synovitis. [NICE NG100 2018]",
          "Look for **clues outside the joints**: psoriasis and nail pits, rash, oral ulcers, photosensitivity, tophi, urethritis, diarrhoea, fever pattern and travel or outbreak history. [Harrison 22e]",
          "A **single hot swollen joint in a patient with RA is septic arthritis until aspiration proves otherwise**. [OHCM 11e]",
        ],
      },
      {
        heading: "Epidemiology, pathogenesis and articular features",
        points: [
          "RA affects about **0.5-0.75 per cent of Indian adults**, with a female-to-male ratio of about 3:1 and peak onset between 35 and 50 years. [Park 28e]",
          "Genetic risk centres on the **HLA-DRB1 shared epitope** and PTPN22, while **smoking** and periodontitis promote citrullination and anti-CCP antibodies. [Harrison 22e]",
          "Synovial inflammation driven by **TNF-alpha, IL-6 and IL-1** forms a pannus that erodes cartilage and bone through RANKL-activated osteoclasts. [Harrison 22e]",
          "Onset is usually **insidious symmetrical polyarthritis** of MCP, PIP, wrist and MTP joints with morning stiffness over an hour and fatigue; palindromic and PMR-like elderly onset also occur. [Kelley and Firestein 11e]",
          "**Early hand signs:** fusiform PIP swelling, boggy MCP and wrist synovitis, and tenderness on squeezing the MCPs. [Harrison 22e]",
          "**Ulnar deviation with volar subluxation of the MCP joints** and radial deviation of the wrist are the classic late deformities. [Apley and Solomon 10e]",
          "**Swan-neck deformity** is PIP hyperextension with DIP flexion, and **boutonniere deformity** is PIP flexion with DIP hyperextension from central slip rupture. [Apley and Solomon 10e]",
          "The **Z-thumb** (MCP flexion with IP hyperextension), **piano-key ulnar styloid** and wasting of the intrinsic muscles are other features. [Apley and Solomon 10e]",
          "**Rupture of the extensor tendons of the ring and little fingers (Vaughan-Jackson syndrome)** results from attrition over an eroded ulnar head. [Apley and Solomon 10e]",
          "**Feet:** MTP subluxation, hallux valgus and cock-up toes produce the sensation of walking on pebbles. [Apley and Solomon 10e]",
          "**Atlantoaxial subluxation** from C1-C2 ligament erosion can cause cervical myelopathy, so flexion-extension neck X-rays are needed before general anaesthesia in long-standing RA. [Harrison 22e]",
          "A ruptured **Baker (popliteal) cyst** mimics deep vein thrombosis with calf pain and swelling. [OHCM 11e]",
        ],
      },
      {
        heading: "Extra-articular features",
        points: [
          "Extra-articular disease is commoner in **seropositive, male, smoking patients** with severe long-standing disease. [Harrison 22e]",
          "**Rheumatoid nodules** occur in 20-30 per cent, typically over the olecranon and extensor surfaces, and almost always with positive RF. [Harrison 22e]",
          "**Eyes:** keratoconjunctivitis sicca (secondary Sjogren syndrome), episcleritis, and scleritis that may progress to scleromalacia perforans. [Kanski 10e]",
          "**Lungs:** interstitial lung disease (usual interstitial pneumonia pattern), exudative pleural effusion with very low glucose, nodules, bronchiectasis and Caplan syndrome in coal workers. [Harrison 22e]",
          "**Heart and vessels:** pericarditis and a **1.5-2-fold increase in cardiovascular disease** from accelerated atherosclerosis, the leading cause of death in RA. [EULAR CVD Recommendations 2016]",
          "**Rheumatoid vasculitis** causes nail-fold infarcts, leg ulcers and mononeuritis multiplex. [Harrison 22e]",
          "**Blood:** anaemia of chronic disease, thrombocytosis, and **Felty syndrome** (RA, splenomegaly and neutropenia with recurrent infections). [Harrison 22e]",
          "**Kidney:** secondary AA amyloidosis with nephrotic syndrome and drug-related nephropathy. [Harrison 22e]",
          "**Nerves:** carpal tunnel syndrome, other entrapments and cervical myelopathy. [Kelley and Firestein 11e]",
          "**Bone:** generalised osteoporosis from inflammation, immobility and glucocorticoids, so RA is a FRAX risk factor. [Harrison 22e]",
        ],
      },
      {
        heading: "Investigations and ACR/EULAR 2010 classification criteria",
        points: [
          "**Rheumatoid factor** (IgM against IgG Fc) is positive in about 70 per cent but also in the elderly, hepatitis C, TB, leprosy, kala-azar, endocarditis and Sjogren syndrome. [Harrison 22e]",
          "**Anti-CCP (ACPA)** has similar sensitivity but **specificity above 95 per cent**, appears years before onset and predicts erosive disease. [Harrison 22e]",
          "**ESR and CRP** measure activity, and **CBC, creatinine, liver enzymes and urinalysis** are needed at baseline before DMARDs. [BSR DMARD Guideline 2017]",
          "Screen for **HBsAg, anti-HCV and HIV**, and do a chest X-ray, before starting methotrexate or biologics. [BSR DMARD Guideline 2017]",
          "Test **ANA** to exclude SLE, and **uric acid** when gout is possible. [Kelley and Firestein 11e]",
          "**X-rays of hands and feet** show soft-tissue swelling, periarticular osteopenia, symmetrical joint-space narrowing and marginal erosions; MTP erosions often appear first. [Apley and Solomon 10e]",
          "**Ultrasound with power Doppler and MRI** detect synovitis and erosions before X-ray changes. [EULAR 2022]",
          "The **ACR/EULAR 2010 criteria** apply to a patient with at least one clinically swollen joint not better explained by another disease, and a score of **6 or more out of 10** classifies definite RA. [ACR/EULAR 2010]",
          "Scores come from **joints (0-5), serology (0-3), acute phase reactants (0-1) and symptom duration of 6 weeks or more (1)**. [ACR/EULAR 2010]",
          "These are **classification criteria** designed to identify early RA for treatment; a seronegative patient with typical erosive disease still has RA. [ACR/EULAR 2010]",
          "Before biologics or JAK inhibitors, screen for **latent TB with IGRA or tuberculin skin test and chest X-ray**, and give TB preventive therapy under NTEP if positive. [NTEP TPT Guidelines 2021]",
        ],
      },
      {
        heading: "Treat-to-target and disease activity measurement",
        points: [
          "Treatment should start **as soon as the diagnosis is made**, ideally within 3 months of symptom onset - the window of opportunity for preventing erosions. [EULAR 2022]",
          "The **target is sustained remission**, or low disease activity in long-standing disease, agreed with the patient. [EULAR 2022]",
          "**DAS28** combines tender and swollen counts in 28 joints (shoulders, elbows, wrists, MCPs, PIPs, knees), ESR or CRP and the patient's global assessment. [Kelley and Firestein 11e]",
          "**DAS28 cut-offs:** remission below 2.6, low activity up to 3.2, moderate 3.2-5.1 and high above 5.1. [Kelley and Firestein 11e]",
          "The **CDAI** (remission 2.8 or less) needs no laboratory test and suits the clinic; **SDAI** remission is 3.3 or less. [Kelley and Firestein 11e]",
          "**ACR/EULAR Boolean remission** requires tender and swollen joint counts, CRP (mg/dL) and patient global (0-10) each at 1 or less, the global threshold being relaxed to 2 in 2022. [ACR/EULAR 2022]",
          "Measure activity **every 1-3 months in active disease**; if there is no improvement by 3 months or the target is not reached by 6 months, change therapy. [EULAR 2022]",
          "**Poor prognostic factors** - high activity, high RF or ACPA titres, early erosions and failure of two csDMARDs - favour earlier escalation to biologic or targeted therapy. [EULAR 2022]",
          "In **sustained remission** for 6-12 months, glucocorticoids are stopped first, then DMARDs may be tapered cautiously. [EULAR 2022]",
        ],
      },
      {
        heading: "csDMARDs, glucocorticoids and advanced therapies",
        points: [
          "**Methotrexate is the anchor drug**: start 15 mg once weekly orally (7.5-10 mg in the elderly or with renal impairment), escalating by 2.5-5 mg every 2-4 weeks to 20-25 mg weekly. [EULAR 2022]",
          "Always write **'once weekly' with the day named**, since daily dosing errors have caused fatal marrow aplasia. [BSR DMARD Guideline 2017]",
          "Give **folic acid 5 mg once weekly** on a different day from methotrexate (or 1 mg daily), which reduces mucositis, nausea and liver toxicity. [BSR DMARD Guideline 2017]",
          "Switch to **subcutaneous methotrexate** for gastrointestinal intolerance or inadequate response to oral doses above 15 mg. [EULAR 2022]",
          "**Hydroxychloroquine 200-400 mg daily** (not more than 5 mg/kg actual body weight) is used in mild disease and combinations, and is safe in pregnancy. [ACR 2021]",
          "**Sulfasalazine** (enteric-coated) starts at 500 mg daily, increased weekly by 500 mg to 1 g twice daily (maximum 3 g/day); it causes orange urine, reversible oligospermia and early agranulocytosis. [BSR DMARD Guideline 2017]",
          "**Leflunomide 10-20 mg daily** is the alternative when methotrexate is contraindicated; it is teratogenic, causes hypertension and diarrhoea, and needs cholestyramine 8 g three times daily for 11 days to wash out. [BSR DMARD Guideline 2017]",
          "**Triple therapy (methotrexate, sulfasalazine and hydroxychloroquine)** is an effective, affordable escalation widely used in India. [Kelley and Firestein 11e]",
          "**Short-term glucocorticoids** (for example prednisolone 7.5-10 mg daily, or IM methylprednisolone 80-120 mg) bridge DMARD onset and should be tapered and stopped within 3 months. [EULAR 2022]",
          "**Intra-articular triamcinolone** controls a flare in one or two joints; NSAIDs relieve symptoms but do not modify disease. [NICE NG100 2018]",
          "**Biologic DMARDs** include TNF inhibitors (etanercept, adalimumab, infliximab and biosimilars), tocilizumab, abatacept and rituximab, usually combined with methotrexate. [EULAR 2022]",
          "**JAK inhibitors** (tofacitinib 5 mg twice daily, baricitinib, upadacitinib) are oral and affordable in India but are avoided in people over 65, smokers and those with cardiovascular or cancer risk unless no alternative exists. [EULAR 2022]",
        ],
      },
      {
        heading: "Monitoring methotrexate, other DMARDs and glucocorticoids",
        points: [
          "**Baseline:** CBC, creatinine with eGFR, ALT or AST, albumin, HBV, HCV and HIV serology, chest X-ray within 6 months for methotrexate, and blood pressure and weight for leflunomide. [BSR DMARD Guideline 2017]",
          "**Schedule for methotrexate, leflunomide and sulfasalazine:** CBC, creatinine, ALT and albumin **every 2 weeks until on a stable dose for 6 weeks, then monthly for 3 months, then at least every 12 weeks**. [BSR DMARD Guideline 2017]",
          "After any **dose increase**, return to 2-weekly tests until 6 weeks on the new stable dose. [BSR DMARD Guideline 2017]",
          "**Withhold and discuss** if WBC falls below 3.5 x 10^9/L, neutrophils below 1.6, platelets below 140, ALT or AST exceed 100 U/L, or albumin falls unexplained. [BSR DMARD Guideline 2017]",
          "**New dry cough or breathlessness** on methotrexate suggests pneumonitis - stop the drug and get a chest X-ray or HRCT urgently. [BSR DMARD Guideline 2017]",
          "Mouth ulcers, sore throat, bruising or fever on methotrexate need an **urgent CBC** for marrow suppression. [BSR DMARD Guideline 2017]",
          "**Never co-prescribe trimethoprim or co-trimoxazole** with methotrexate, as both are antifolates and cause pancytopenia; keep alcohol to a minimum. [BNF 2025]",
          "**Hydroxychloroquine needs no blood monitoring** but needs retinal screening (OCT and visual fields) at baseline within the first year and annually after 5 years, earlier with risk factors. [AAO 2016]",
          "**Contraception:** stop methotrexate at least 1-3 months before conception; leflunomide needs washout; hydroxychloroquine, sulfasalazine, low-dose prednisolone and most TNF inhibitors can continue in pregnancy. [BSR Pregnancy Guideline 2022]",
          "**Glucocorticoid monitoring:** blood pressure, weight, blood glucose or HbA1c, lipids, mood and eyes for cataract and glaucoma. [ACR GIOP 2022]",
          "For prednisolone **2.5 mg or more daily for 3 months or longer**, give calcium and vitamin D and assess fracture risk for a bisphosphonate such as alendronate 70 mg weekly. [ACR GIOP 2022]",
          "Warn against **stopping steroids abruptly** after more than 3 weeks, and issue a steroid card with sick-day rules. [NICE CKS 2024]",
        ],
      },
      {
        heading: "Reactive, post-viral and other differentials",
        points: [
          "**Reactive arthritis** follows gastrointestinal (Salmonella, Shigella, Campylobacter, Yersinia) or urogenital (Chlamydia trachomatis) infection by 1-4 weeks. [Harrison 22e]",
          "It causes **asymmetrical lower-limb oligoarthritis, enthesitis (Achilles, plantar fascia), dactylitis, conjunctivitis or uveitis, urethritis, keratoderma blennorrhagicum and circinate balanitis**, often with HLA-B27. [Harrison 22e]",
          "Treat reactive arthritis with **NSAIDs and intra-articular steroid**, treat chlamydia and partner (doxycycline 100 mg twice daily for 7 days), and add sulfasalazine if it persists beyond 6 months. [Harrison 22e]",
          "**Parvovirus B19** causes acute symmetrical small-joint polyarthritis in adults, especially mothers of affected children, and settles within weeks; IgM confirms it. [Harrison 22e]",
          "**Chikungunya** causes severe symmetrical polyarthralgia, and chronic inflammatory arthritis persists for months in a substantial minority, sometimes meeting RA criteria but usually ACPA negative. [NCVBDC Chikungunya Guidelines 2016]",
          "Chronic **post-chikungunya arthritis** is treated with NSAIDs, short steroid courses and hydroxychloroquine or methotrexate when persistent. [NCVBDC Chikungunya Guidelines 2016]",
          "**Hepatitis B** causes a prodromal urticaria-arthritis syndrome, and **hepatitis C** causes RF-positive arthritis and cryoglobulinaemia. [Harrison 22e]",
          "**Indian mimics** include rheumatic fever (migratory large joints), Poncet disease (reactive arthritis with TB) and leprosy reactions with RF positivity. [Harrison 22e]",
          "Also consider **SLE** (non-erosive Jaccoud arthropathy), **psoriatic arthritis**, **polyarticular gout**, **CPPD**, hypothyroidism and sarcoidosis. [Kelley and Firestein 11e]",
          "Suspected **viral arthritis with a clear trigger** can be watched for 6 weeks with NSAIDs, but persistent synovitis beyond that needs rheumatology review. [NICE NG100 2018]",
        ],
      },
      {
        heading: "Comorbidity care, the family physician and referral",
        points: [
          "**Refer urgently** any adult with suspected persistent synovitis of undetermined cause, especially of small joints, more than one joint, or symptoms for 3 months or more, even if RF is negative. [NICE NG100 2018]",
          "Assess **cardiovascular risk annually** and multiply the risk score by 1.5, then manage blood pressure, lipids and diabetes aggressively. [EULAR CVD Recommendations 2016]",
          "**Smoking cessation** reduces disease activity and improves response to methotrexate and TNF inhibitors. [EULAR 2022]",
          "**Vaccinate:** annual influenza, pneumococcal, hepatitis B and recombinant zoster vaccine, ideally before starting immunosuppression; avoid live vaccines on biologics or JAK inhibitors. [EULAR Vaccination Recommendations 2019]",
          "Screen for **depression** (PHQ-9), which affects about 1 in 5 and worsens pain and adherence. [NICE NG100 2018]",
          "Offer **physiotherapy, occupational therapy, joint protection, splints and podiatry**, and encourage regular aerobic and strengthening exercise. [NICE NG100 2018]",
          "Run **shared-care DMARD monitoring** with a written schedule, and educate patients to report fever, sore throat, bruising, cough or jaundice. [BSR DMARD Guideline 2017]",
          "**Refer back** for flares despite therapy, cytopenias or abnormal liver tests, new extra-articular disease (scleritis, vasculitis, ILD), pregnancy planning and neck symptoms suggesting myelopathy. [NICE NG100 2018]",
          "A patient on biologics with fever needs **same-day assessment** for serious infection, including TB. [EULAR 2022]",
          "Consider **peri-operative planning** - neck X-ray, holding biologics around surgery, and steroid cover - before any elective operation. [ACR Perioperative Guideline 2022]",
        ],
      },
    ],
    tables: [
      {
        heading: "ACR/EULAR 2010 classification criteria for RA",
        columns: ["Finding", "Domain", "Points"],
        rows: [
          ["1 large joint", "Joint involvement", "0"],
          ["2-10 large joints", "Joint involvement", "1"],
          ["1-3 small joints", "Joint involvement", "2"],
          ["4-10 small joints", "Joint involvement", "3"],
          ["More than 10 joints (at least 1 small)", "Joint involvement", "5"],
          ["RF and ACPA negative", "Serology", "0"],
          ["Low-positive RF or ACPA (up to 3 x ULN)", "Serology", "2"],
          ["High-positive RF or ACPA (over 3 x ULN)", "Serology", "3"],
          ["Normal CRP and ESR", "Acute phase reactants", "0"],
          ["Abnormal CRP or ESR", "Acute phase reactants", "1"],
          ["Symptoms under 6 weeks", "Duration", "0"],
          ["Symptoms 6 weeks or more", "Duration", "1"],
        ],
      },
      {
        heading: "csDMARD doses, toxicity and monitoring",
        columns: ["Drug", "Dose", "Key toxicity", "Monitoring"],
        rows: [
          ["Methotrexate", "15 mg once weekly, up to 25 mg; folic acid 5 mg weekly", "Marrow, liver, pneumonitis, mucositis, teratogenic", "CBC, LFT, creatinine 2-weekly to 6 weeks stable, monthly x 3, then 12-weekly"],
          ["Hydroxychloroquine", "200-400 mg daily (up to 5 mg/kg)", "Retinopathy, rarely cardiomyopathy", "Retinal screening baseline and yearly after 5 years"],
          ["Sulfasalazine", "500 mg daily rising to 1 g twice daily", "Rash, agranulocytosis, oligospermia, G6PD haemolysis", "As methotrexate; after 12 months only if dose changes"],
          ["Leflunomide", "10-20 mg daily", "Liver, hypertension, diarrhoea, teratogenic", "As methotrexate plus BP and weight"],
          ["Prednisolone", "7.5-10 mg daily short-term, tapered", "Diabetes, osteoporosis, infection, cataract", "BP, glucose, weight, bone protection"],
        ],
      },
      {
        heading: "Differential diagnosis of polyarthritis",
        columns: ["Condition", "Pattern", "Pointers"],
        rows: [
          ["Rheumatoid arthritis", "Symmetrical small joints, DIP spared", "Morning stiffness over 1 hour, anti-CCP, erosions"],
          ["Osteoarthritis", "DIP, PIP, first CMC, knees", "Bony nodes, short stiffness, normal ESR"],
          ["Psoriatic arthritis", "DIP, dactylitis, asymmetric", "Psoriasis, nail pits, pencil-in-cup"],
          ["SLE", "Symmetrical, non-erosive", "Rash, ulcers, cytopenias, ANA and anti-dsDNA"],
          ["Chikungunya", "Symmetrical small joints after fever", "Outbreak, rash, IgM positive, ACPA negative"],
          ["Reactive arthritis", "Asymmetric lower-limb oligoarthritis", "Diarrhoea or urethritis 1-4 weeks earlier, enthesitis"],
          ["Chronic gout", "Polyarticular, asymmetrical", "Tophi, hyperuricaemia, crystals"],
        ],
      },
    ],
    redFlags: [
      "Single hot swollen joint in a patient with RA - septic arthritis until aspirated.",
      "Fever, sore throat, mouth ulcers or bruising on methotrexate - check CBC urgently.",
      "New dry cough or breathlessness on methotrexate - pneumonitis.",
      "Neck pain with limb paraesthesia, weakness or sphincter change - atlantoaxial subluxation.",
      "Painful red eye with reduced vision - scleritis.",
      "Nail-fold infarcts, leg ulcers or foot drop - rheumatoid vasculitis.",
      "Fever or cough in a patient on biologics - serious infection including TB.",
      "Calf swelling after knee pain - ruptured Baker cyst versus DVT.",
    ],
    pearls: [
      "RA spares the DIP joints; OA and psoriatic arthritis involve them.",
      "ACR/EULAR 2010: 6 of 10 from joints, serology, acute phase and duration.",
      "Anti-CCP is more specific than RF; RF is positive in TB, leprosy and hepatitis C.",
      "Methotrexate is the anchor drug - once weekly, never daily, with weekly folic acid.",
      "Treat to target: review every 1-3 months, change if no response by 3 months or target missed at 6.",
      "DAS28 remission is below 2.6.",
      "Never give co-trimoxazole with methotrexate.",
      "Hydroxychloroquine needs eye screening, not blood tests.",
      "Cardiovascular disease is the commonest cause of death in RA - multiply risk by 1.5.",
      "Screen for latent TB before biologics or JAK inhibitors in India.",
      "Post-chikungunya arthritis can mimic RA but is usually ACPA negative.",
    ],
    mcqs: [
      {
        id: "musculoskeletal-rheumatoid-arthritis-q1",
        stem: "A 40-year-old woman has swelling of 6 MCP and PIP joints for 8 weeks, high-positive anti-CCP and a raised CRP. Her ACR/EULAR 2010 score is:",
        options: ["10", "6", "8", "7"],
        answer: 3,
        explanation:
          "Four to ten small joints score 3, high-positive serology scores 3, abnormal CRP scores 1 and duration of 6 weeks or more scores 1, giving 3 + 3 + 1 + 1 = 8. A total of 10 would need more than ten joints (5 points); 6 and 7 undercount the serology or joint domain. Any score of 6 or more classifies definite RA.",
        difficulty: "moderate",
      },
      {
        id: "musculoskeletal-rheumatoid-arthritis-q2",
        stem: "Which deformity consists of PIP joint hyperextension with DIP joint flexion?",
        options: ["Boutonniere deformity", "Swan-neck deformity", "Z-thumb", "Mallet finger"],
        answer: 1,
        explanation:
          "Swan-neck deformity is PIP hyperextension with DIP flexion, resulting from volar plate laxity and intrinsic tightness in RA. Boutonniere is the reverse (PIP flexion, DIP hyperextension) from central slip rupture, the Z-thumb involves MCP flexion with IP hyperextension of the thumb, and mallet finger is isolated DIP flexion from extensor tendon avulsion.",
        difficulty: "easy",
      },
      {
        id: "musculoskeletal-rheumatoid-arthritis-q3",
        stem: "A patient stable on methotrexate 20 mg weekly is prescribed co-trimoxazole for a urinary infection and presents 10 days later with mouth ulcers and fever. The most likely problem is:",
        options: [
          "Methotrexate-induced pancytopenia",
          "Methotrexate pneumonitis",
          "Stevens-Johnson syndrome from methotrexate",
          "Drug-induced lupus",
        ],
        answer: 0,
        explanation:
          "Trimethoprim is an antifolate that, with methotrexate, causes profound bone marrow suppression, presenting with mucositis, fever and infection, so an urgent CBC is needed. Pneumonitis presents with dry cough and breathlessness, Stevens-Johnson syndrome with target lesions and mucosal sloughing, and drug-induced lupus is not associated with methotrexate.",
        difficulty: "moderate",
      },
      {
        id: "musculoskeletal-rheumatoid-arthritis-q4",
        stem: "According to BSR guidance, once a patient has been on a stable methotrexate dose for 6 weeks, blood monitoring should be:",
        options: [
          "Stopped if all results have been normal",
          "Continued every 2 weeks indefinitely",
          "Monthly for 3 months, then at least every 12 weeks",
          "Done only annually",
        ],
        answer: 2,
        explanation:
          "BSR recommends CBC, creatinine, ALT and albumin every 2 weeks until the dose is stable for 6 weeks, then monthly for 3 months, and thereafter at least every 12 weeks for as long as the drug is taken. Stopping or annual testing misses late marrow and liver toxicity, while indefinite 2-weekly testing is unnecessary.",
        difficulty: "moderate",
      },
      {
        id: "musculoskeletal-rheumatoid-arthritis-q5",
        stem: "Which autoantibody is most specific for rheumatoid arthritis and predicts erosive disease?",
        options: ["Rheumatoid factor", "Antinuclear antibody", "Anti-cyclic citrullinated peptide antibody", "Anti-Ro antibody"],
        answer: 2,
        explanation:
          "Anti-CCP (ACPA) has specificity above 95 per cent for RA, can appear years before symptoms and predicts erosions. Rheumatoid factor is less specific, being positive in the elderly, hepatitis C, TB and leprosy; ANA suggests SLE or other connective tissue disease, and anti-Ro is associated with Sjogren syndrome and neonatal lupus.",
        difficulty: "easy",
      },
    ],
    theory: [
      {
        id: "musculoskeletal-rheumatoid-arthritis-t1",
        paper: "I",
        kind: "long",
        marks: 10,
        minutes: 18,
        frequency: "core",
        question:
          "A 38-year-old woman presents with pain and swelling of both hands for 3 months. Discuss the ACR/EULAR 2010 criteria, the deformities of the hand in rheumatoid arthritis and the treat-to-target approach. [3+3+4]",
        openingLines: [
          "Rheumatoid arthritis is a chronic autoimmune inflammatory disease causing symmetrical erosive polyarthritis of small joints with systemic features.",
          "Early diagnosis using the ACR/EULAR 2010 criteria and early methotrexate within the window of opportunity prevent joint damage.",
        ],
        answer: [
          {
            heading: "ACR/EULAR 2010 criteria",
            points: [
              "At least one swollen joint not explained by another disease; 6 or more of 10.",
              "Joints 0-5, serology 0-3, acute phase 0-1, duration 6 weeks or more 1.",
            ],
          },
          {
            heading: "Hand deformities",
            points: [
              "Ulnar deviation and volar subluxation of MCPs; radial deviation of wrist.",
              "Swan neck, boutonniere, Z-thumb, piano-key ulnar styloid, extensor tendon rupture, intrinsic wasting, nodules; DIP spared.",
            ],
          },
          {
            heading: "Treat-to-target",
            points: [
              "Target remission (DAS28 below 2.6) or low activity; measure every 1-3 months.",
              "Methotrexate 15 mg weekly escalated to 20-25 mg with folic acid, plus short-term steroid.",
              "No improvement at 3 months or target missed at 6 months: add csDMARDs (triple therapy) or biologic or JAK inhibitor if poor prognostic factors.",
            ],
          },
          {
            heading: "Supportive care",
            points: ["Monitoring, vaccination, TB screening, CVD risk x 1.5, physiotherapy and occupational therapy."],
          },
        ],
        mustDraw: ["Diagram of swan-neck and boutonniere deformities", "Treat-to-target flow chart"],
        markSplit: [
          { part: "ACR/EULAR criteria", marks: 3 },
          { part: "Hand deformities", marks: 3 },
          { part: "Treat-to-target", marks: 4 },
        ],
        keywords: ["rheumatoid arthritis", "ACR/EULAR 2010", "swan neck", "treat to target", "methotrexate"],
      },
      {
        id: "musculoskeletal-rheumatoid-arthritis-t2",
        paper: "I",
        kind: "short-note",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question: "Methotrexate in rheumatoid arthritis: dosing, adverse effects and monitoring in primary care. [3+3+4]",
        openingLines: [
          "Methotrexate, a folate antagonist given once weekly, is the anchor disease-modifying drug in rheumatoid arthritis.",
          "Safe use in family practice depends on correct weekly dosing, folic acid supplementation and structured blood monitoring.",
        ],
        answer: [
          {
            heading: "Dosing",
            points: [
              "15 mg once weekly (7.5-10 mg in elderly or renal impairment), increase by 2.5-5 mg every 2-4 weeks to 20-25 mg.",
              "Folic acid 5 mg weekly on another day; subcutaneous route if intolerant.",
            ],
          },
          {
            heading: "Adverse effects",
            points: [
              "Nausea, mucositis, alopecia, marrow suppression, hepatotoxicity, pneumonitis, infections, teratogenicity.",
              "Interaction with trimethoprim; avoid heavy alcohol.",
            ],
          },
          {
            heading: "Monitoring",
            points: [
              "Baseline CBC, LFT, creatinine, albumin, HBV/HCV/HIV, chest X-ray.",
              "2-weekly until stable 6 weeks, monthly for 3 months, then 12-weekly.",
              "Withhold if WBC below 3.5, neutrophils below 1.6, platelets below 140, ALT over 100; urgent review for cough, ulcers, fever.",
              "Contraception; stop 1-3 months before conception.",
            ],
          },
        ],
        mustDraw: ["Monitoring timeline chart"],
        markSplit: [
          { part: "Dosing", marks: 3 },
          { part: "Adverse effects", marks: 3 },
          { part: "Monitoring", marks: 4 },
        ],
        keywords: ["methotrexate", "folic acid", "monitoring", "pneumonitis", "BSR"],
      },
    ],
    references: [
      "Aletaha D et al. 2010 Rheumatoid arthritis classification criteria: ACR/EULAR collaborative initiative",
      "Smolen JS et al. EULAR recommendations for the management of rheumatoid arthritis: 2022 update (Ann Rheum Dis 2023)",
      "Fraenkel L et al. 2021 American College of Rheumatology Guideline for the Treatment of Rheumatoid Arthritis",
      "Ledingham J et al. BSR and BHPR guideline for the prescription and monitoring of non-biologic DMARDs, 2017",
      "NICE NG100: Rheumatoid arthritis in adults - management, 2018 (updated 2020)",
      "Firestein and Kelley's Textbook of Rheumatology, 11th edition, 2021",
      "Harrison's Principles of Internal Medicine, 22nd edition, 2025",
      "ACR Guideline for the Prevention and Treatment of Glucocorticoid-Induced Osteoporosis, 2022",
    ],
  },
  {
    id: "musculoskeletal-regional-soft-tissue-disorders",
    title: "Regional soft-tissue disorders: tennis elbow, carpal tunnel, plantar fasciitis, ganglion",
    oneLiner:
      "Regional soft-tissue disorders are localised, mostly degenerative overuse conditions of tendons, entheses, fascia and peripheral nerves - lateral epicondylalgia, carpal tunnel and other entrapments, de Quervain tenosynovitis, trigger finger, ganglion, plantar fasciitis and Achilles tendinopathy - diagnosed clinically by site-specific tests (**Tinel, Phalen, Finkelstein, windlass**), managed first with education, load modification, splints and **progressive exercise**, with **corticosteroid injection** used selectively for short-term relief and surgery reserved for refractory disease or **neurological deficit such as thenar wasting**.",
    frequency: "common",
    keywords: [
      "soft tissue rheumatism",
      "tennis elbow",
      "lateral epicondylitis",
      "golfer's elbow",
      "carpal tunnel syndrome",
      "CTS",
      "Tinel sign",
      "Phalen test",
      "cubital tunnel",
      "meralgia paraesthetica",
      "tarsal tunnel",
      "de Quervain tenosynovitis",
      "Finkelstein test",
      "trigger finger",
      "ganglion",
      "plantar fasciitis",
      "heel pain",
      "Achilles tendinopathy",
      "steroid injection",
      "ergonomics",
    ],
    sections: [
      {
        heading: "Overview, risk factors and principles",
        points: [
          "**Regional soft-tissue disorders** (soft-tissue rheumatism) cause pain arising from tendons, tendon sheaths, entheses, bursae, fascia or entrapped nerves rather than joints. [Kelley and Firestein 11e]",
          "Most tendon disorders are **degenerative tendinopathies (tendinosis) with failed healing**, not inflammation, which is why rest and anti-inflammatories alone disappoint. [Apley and Solomon 10e]",
          "**Risk factors:** repetitive forceful gripping, vibration, awkward postures, age 40-60, obesity, diabetes, hypothyroidism, rheumatoid arthritis and pregnancy. [Kelley and Firestein 11e]",
          "Indian occupational groups at risk include **computer and IT workers, garment and assembly workers, masons, farmers, drivers and homemakers** doing prolonged grinding, washing and wringing. [Park 28e]",
          "Diagnosis is **clinical**, based on site of pain, focal tenderness and provocation tests; imaging is reserved for atypical, refractory or red-flag cases. [Kelley and Firestein 11e]",
          "**Ultrasound** is the most useful office imaging, showing tendon thickening, tenosynovitis, nerve swelling and cyst contents. [Kelley and Firestein 11e]",
          "Screen patients with multiple or recurrent soft-tissue problems for **diabetes, hypothyroidism and inflammatory arthritis**. [Kelley and Firestein 11e]",
          "Most conditions **resolve within 6-18 months**, so education and reassurance are central and invasive treatment should be proportionate. [Apley and Solomon 10e]",
          "Management follows a ladder: **education and activity modification, analgesia and topical NSAIDs, splints, graded exercise, then injection, then surgery**. [NICE CKS 2023]",
          "The **Occupational Safety, Health and Working Conditions Code 2020** places a duty on employers to reduce work-related hazards, including repetitive strain. [OSH Code 2020]",
        ],
      },
      {
        heading: "Lateral and medial epicondylitis",
        points: [
          "**Lateral epicondylalgia (tennis elbow)** is a tendinopathy of the extensor carpi radialis brevis origin, affecting 1-3 per cent of adults aged 35-55, usually in the dominant arm and rarely from tennis. [Apley and Solomon 10e]",
          "It causes **lateral elbow pain on gripping, lifting with the palm down and wringing clothes**, with point tenderness just distal and anterior to the lateral epicondyle. [Apley and Solomon 10e]",
          "**Cozen test** (pain on resisted wrist extension with the elbow extended), **Mill test** (pain on passive wrist flexion with the elbow extended and forearm pronated) and **Maudsley test** (resisted middle finger extension) reproduce pain. [Apley and Solomon 10e]",
          "Differentials include **radial tunnel syndrome** (tenderness 4-5 cm distal over supinator), C6 radiculopathy, elbow arthritis and osteochondritis of the capitellum. [Kelley and Firestein 11e]",
          "About **80-90 per cent recover within 12 months** with education, load modification and exercise. [BMJ Best Practice 2024]",
          "First line is **topical NSAID (diclofenac gel 1-2 per cent three times daily)**, a counterforce brace, and physiotherapy with progressive isometric then eccentric wrist-extensor loading. [NICE CKS 2023]",
          "**Corticosteroid injection** gives relief for about 6 weeks but results at 1 year are worse than wait-and-see or physiotherapy, with more recurrence. [Coombes JAMA 2013]",
          "Reserve injection for **severe pain blocking work or rehabilitation**, after explaining the trade-off; PRP evidence is inconsistent. [NICE CKS 2023]",
          "**Surgical release** of the ECRB origin is considered after 6-12 months of failed conservative care. [Apley and Solomon 10e]",
          "**Medial epicondylalgia (golfer's elbow)** affects the common flexor-pronator origin, with pain on resisted wrist flexion and pronation, and is managed similarly. [Apley and Solomon 10e]",
          "In medial epicondylalgia, check for **coexisting ulnar neuropathy**, and inject anterior to the medial epicondyle to avoid the ulnar nerve in its groove. [Kelley and Firestein 11e]",
        ],
      },
      {
        heading: "Carpal tunnel syndrome",
        points: [
          "**Carpal tunnel syndrome (CTS)** is compression of the median nerve beneath the flexor retinaculum, the commonest entrapment neuropathy, affecting about 3-5 per cent of adults, mainly women aged 40-60. [Apley and Solomon 10e]",
          "**Risk factors:** female sex, pregnancy, obesity, diabetes, hypothyroidism, RA, acromegaly, amyloidosis, dialysis, previous wrist fracture and repetitive vibratory work. [NICE CKS 2023]",
          "Classic symptoms are **night-time paraesthesia and pain in the thumb, index, middle and radial half of ring finger**, relieved by shaking the hand (flick sign). [Apley and Solomon 10e]",
          "The **palm is spared** because the palmar cutaneous branch leaves the median nerve proximal to the tunnel - palmar numbness suggests a more proximal lesion. [Apley and Solomon 10e]",
          "**Tinel sign** (tapping over the tunnel produces tingling), **Phalen test** (60 seconds of full wrist flexion reproduces symptoms) and **Durkan carpal compression test** (the most sensitive) support the diagnosis. [Apley and Solomon 10e]",
          "**Advanced CTS** shows thenar wasting and weak abductor pollicis brevis, and constant numbness indicates axonal loss. [Apley and Solomon 10e]",
          "**Nerve conduction studies** show prolonged distal motor and sensory latency and confirm severity; they are needed before surgery or when the diagnosis is uncertain. [AAOS CTS CPG 2016]",
          "**Ultrasound** showing a median nerve cross-sectional area above about 10 mm2 at the tunnel inlet supports the diagnosis. [AAOS CTS CPG 2016]",
          "Mild to moderate CTS is treated with a **neutral wrist splint worn at night for 6-8 weeks**, activity modification and treatment of the underlying cause. [NICE CKS 2023]",
          "**Steroid injection** (methylprednisolone 40 mg or triamcinolone 20-40 mg) gives relief in most patients for weeks to months, but symptoms often recur. [AAOS CTS CPG 2016]",
          "**Carpal tunnel release** (open or endoscopic division of the transverse carpal ligament) is indicated for thenar wasting, constant numbness, severe NCS findings or failed conservative care, with over 90 per cent success. [Apley and Solomon 10e]",
          "**Pregnancy-related CTS** is managed with splints and usually resolves after delivery; oral steroids, diuretics and vitamin B6 are not recommended. [NICE CKS 2023]",
        ],
      },
      {
        heading: "Other entrapments: cubital tunnel, meralgia paraesthetica, tarsal tunnel and Morton neuroma",
        points: [
          "**Cubital tunnel syndrome** is ulnar nerve compression behind the medial epicondyle, the second commonest upper-limb entrapment, aggravated by prolonged elbow flexion and leaning on the elbows. [Apley and Solomon 10e]",
          "It causes **paraesthesia of the little and ulnar half of the ring finger including the dorsal ulnar hand**, intrinsic weakness, **Froment sign** and a positive elbow flexion test. [Apley and Solomon 10e]",
          "Dorsal-hand sensory loss distinguishes cubital tunnel from **Guyon canal** compression at the wrist, which spares the dorsal branch. [Apley and Solomon 10e]",
          "In India always **palpate the ulnar nerve for thickening and look for skin patches**, because leprosy neuritis presents exactly like an entrapment and needs prednisolone under NLEP. [Harrison 22e]",
          "Cubital tunnel is managed with **avoidance of elbow flexion, a night extension splint** (a towel wrapped around the elbow) and surgical decompression for weakness or wasting. [Apley and Solomon 10e]",
          "**Meralgia paraesthetica** is compression of the lateral femoral cutaneous nerve (L2-L3) near the anterior superior iliac spine, causing burning numbness of the anterolateral thigh without weakness or reflex change. [Harrison 22e]",
          "Meralgia is linked to **obesity, pregnancy, tight belts or jeans, diabetes and heavy tool belts**, and improves with weight loss, loose clothing and, if needed, a nerve block medial to the ASIS. [Harrison 22e]",
          "**Tarsal tunnel syndrome** is compression of the tibial nerve beneath the flexor retinaculum behind the medial malleolus, causing burning of the sole worse with standing and at night, with a positive Tinel sign. [Apley and Solomon 10e]",
          "Tarsal tunnel may be due to a **ganglion, varicosities, flat foot or tenosynovitis**, so image with ultrasound or MRI and treat with orthotics, injection or decompression. [Apley and Solomon 10e]",
          "**Morton neuroma** is interdigital nerve fibrosis, usually in the third web space, with burning forefoot pain into the toes and a **Mulder click**, relieved by wide shoes and a metatarsal pad. [Apley and Solomon 10e]",
        ],
      },
      {
        heading: "De Quervain tenosynovitis and trigger finger",
        points: [
          "**De Quervain tenosynovitis** is stenosing tenosynovitis of abductor pollicis longus and extensor pollicis brevis in the first dorsal compartment at the radial styloid. [Apley and Solomon 10e]",
          "It is common in **women aged 30-50 and new mothers lifting infants**, and in work needing repeated thumb abduction with ulnar deviation. [Apley and Solomon 10e]",
          "**Finkelstein test:** with the thumb flexed inside the fist, ulnar deviation of the wrist produces sharp pain over the radial styloid. [Apley and Solomon 10e]",
          "Distinguish it from **thumb CMC osteoarthritis** (positive grind test) and **intersection syndrome** (crepitus 4-8 cm proximal to the wrist). [Kelley and Firestein 11e]",
          "Treat with a **forearm-based thumb spica splint for 3-6 weeks**, NSAIDs and activity modification. [Green's Operative Hand Surgery 8e]",
          "**Steroid injection into the first dorsal compartment** relieves about 70-80 per cent and is more effective than splinting alone; failure may reflect a separate EPB subcompartment. [Green's Operative Hand Surgery 8e]",
          "**Surgical release** of the first compartment must protect the **superficial radial nerve**, whose injury causes painful neuroma. [Green's Operative Hand Surgery 8e]",
          "**Trigger finger** is stenosing tenosynovitis at the **A1 pulley** over the metacarpal head, most often of the ring finger and thumb. [Green's Operative Hand Surgery 8e]",
          "It is much commoner in **diabetes** (up to 10-20 per cent), RA, hypothyroidism and CTS, and presents with a painful palmar nodule, clicking and locking in flexion. [Green's Operative Hand Surgery 8e]",
          "**Steroid injection into the flexor sheath** at the A1 pulley (triamcinolone 10-20 mg or methylprednisolone 20-40 mg) cures 60-90 per cent, less often in diabetics. [Green's Operative Hand Surgery 8e]",
          "After two failed injections or with a fixed flexion deformity, perform **percutaneous or open A1 pulley release**, preserving the A2 pulley to prevent bowstringing. [Green's Operative Hand Surgery 8e]",
          "**Paediatric trigger thumb** presents as a fixed flexed IP joint with a palpable nodule (Notta node); many resolve, and persistent cases are released at about 2-3 years. [Nelson 22e]",
        ],
      },
      {
        heading: "Ganglion cyst",
        points: [
          "A **ganglion** is a mucin-filled cyst arising from a joint capsule or tendon sheath, lined by flattened cells without true synovium, and is the commonest soft-tissue swelling of the hand and wrist. [Green's Operative Hand Surgery 8e]",
          "The **dorsal wrist ganglion** from the scapholunate ligament accounts for 60-70 per cent, and the **volar wrist ganglion** near the radial artery for about 20 per cent. [Green's Operative Hand Surgery 8e]",
          "**Flexor sheath (seed) ganglia** are firm pea-sized lumps at the A1-A2 pulley that hurt on gripping. [Green's Operative Hand Surgery 8e]",
          "A **mucous cyst** at the DIP joint arises from osteoarthritis with Heberden nodes, and may groove the nail. [Green's Operative Hand Surgery 8e]",
          "Ganglia are **smooth, firm or fluctuant, transilluminate** and may vary in size with activity; an occult dorsal ganglion causing wrist pain is shown by ultrasound. [Bailey and Love 28e]",
          "About **40-50 per cent resolve spontaneously** (more in children), so reassurance is appropriate for painless ganglia. [Green's Operative Hand Surgery 8e]",
          "**Aspiration** with a wide-bore needle is simple but recurrence is about 50 per cent or more; aspiration of volar ganglia risks the radial artery. [Green's Operative Hand Surgery 8e]",
          "**Surgical excision** including the stalk and a cuff of capsule reduces recurrence to about 5-15 per cent for dorsal ganglia, but leaves a scar and risks stiffness. [Green's Operative Hand Surgery 8e]",
          "**Do not strike a ganglion with a book** - rupture causes injury and frequent recurrence. [Bailey and Love 28e]",
          "Excise **mucous cysts with the underlying osteophyte**; avoid repeated needling, which risks DIP septic arthritis. [Green's Operative Hand Surgery 8e]",
          "Refer a lump that is **hard, fixed, rapidly growing, over 5 cm or not transilluminant** for ultrasound and exclusion of soft-tissue sarcoma. [NICE NG12 2015 updated 2023]",
        ],
      },
      {
        heading: "Heel pain: plantar fasciitis, differential diagnosis and Achilles tendinopathy",
        points: [
          "**Plantar fasciitis (plantar heel pain)** is degeneration of the plantar fascia origin at the medial calcaneal tubercle and the commonest cause of heel pain, with a lifetime prevalence of about 10 per cent. [Apley and Solomon 10e]",
          "Risk factors are **age 40-60, obesity, prolonged standing on hard floors (common barefoot in Indian homes), running, flat or high-arched feet and tight calf muscles**. [Kelley and Firestein 11e]",
          "The hallmark is **first-step pain on rising in the morning or after sitting**, easing with walking and worsening by evening, with tenderness at the medial calcaneal tubercle and a positive windlass test. [Apley and Solomon 10e]",
          "A **calcaneal spur** is seen in many patients and in asymptomatic people, and is not the cause of pain or an indication for surgery. [Apley and Solomon 10e]",
          "**Heel pain differentials:** calcaneal stress fracture (positive squeeze test), fat pad atrophy (central heel pain in the elderly), Baxter nerve or tarsal tunnel entrapment, and S1 radiculopathy. [Kelley and Firestein 11e]",
          "Bilateral heel pain in a **young man with back stiffness** suggests spondyloarthritis enthesitis; in a child aged 8-14 think of **Sever disease (calcaneal apophysitis)**. [Kelley and Firestein 11e]",
          "Treat plantar fasciitis with **plantar fascia-specific and calf stretching three times daily, cushioned footwear, silicone heel cups or arch supports, weight loss and avoiding barefoot walking**; 80-90 per cent recover within a year. [NICE CKS 2023]",
          "**Night splints, taping and a short NSAID course** help some; steroid injection gives only short-term relief and risks fascial rupture and fat pad atrophy. [NICE CKS 2023]",
          "**Extracorporeal shock wave therapy** is an option for pain beyond 6 months, and surgery is rarely needed. [NICE CKS 2023]",
          "**Achilles tendinopathy** is either midportion (2-6 cm above the insertion, with fusiform thickening) or insertional, with morning stiffness and pain on loading. [Apley and Solomon 10e]",
          "Risk factors include running, obesity, diabetes, spondyloarthritis, familial hypercholesterolaemia (xanthomas) and **fluoroquinolones**, especially with steroids in the elderly. [BNF 2025]",
          "Treat with **eccentric heel-drop exercises (3 sets of 15, knee straight and bent, twice daily for 12 weeks)** or heavy slow resistance training, a heel raise and load management. [Alfredson protocol; Kelley and Firestein 11e]",
          "**Never inject steroid into or around the Achilles tendon**, which risks rupture; a sudden 'kick' with a positive Simmonds-Thompson squeeze test means rupture and needs urgent referral. [Apley and Solomon 10e]",
        ],
      },
      {
        heading: "Corticosteroid injection: technique and cautions",
        points: [
          "Common agents are **methylprednisolone acetate 40 mg/mL and triamcinolone acetonide 40 mg/mL**, usually mixed with 0.5-2 mL of 1 per cent lignocaine. [Kelley and Firestein 11e]",
          "Typical doses: **tendon sheath or trigger finger 10-20 mg triamcinolone; epicondyle, carpal tunnel or plantar fascia 20-40 mg methylprednisolone**. [Kelley and Firestein 11e]",
          "Use **methylprednisolone or hydrocortisone rather than triamcinolone for superficial sites**, since triamcinolone causes more fat atrophy. [Kelley and Firestein 11e]",
          "Take **informed consent** covering flare, skin atrophy, depigmentation, tendon rupture, infection and raised blood sugar. [Kelley and Firestein 11e]",
          "Mark landmarks, clean with chlorhexidine or povidone-iodine, use a **no-touch aseptic technique** with a 23-25 G needle, and aspirate before injecting. [Kelley and Firestein 11e]",
          "Inject **alongside, not into, the tendon**; high resistance means the needle is intratendinous and must be withdrawn slightly. [Kelley and Firestein 11e]",
          "For CTS inject just proximal to the distal wrist crease, **ulnar to palmaris longus, angled 30-45 degrees towards the ring finger**, and stop if paraesthesia occurs. [AAOS CTS CPG 2016]",
          "Limit injections to **no more than three a year at one site, at least 6 weeks apart**, and reconsider the diagnosis if the first injection fails. [Kelley and Firestein 11e]",
          "**Post-injection flare** (2-10 per cent) settles in 24-48 hours with ice and paracetamol; **fever, spreading redness or pain after 48 hours** suggests infection. [Kelley and Firestein 11e]",
          "**Skin atrophy and hypopigmentation** are more conspicuous in darker Indian skin and should be discussed before injection. [Rook 10e]",
          "Diabetics should **monitor blood glucose for 2-5 days** after injection, as transient hyperglycaemia is common. [Kelley and Firestein 11e]",
          "**Contraindications:** local or systemic infection, overlying skin lesion, prosthetic joint (specialist only), uncontrolled diabetes, coagulopathy beyond therapeutic range and weight-bearing tendons such as the Achilles and patellar tendons. [Kelley and Firestein 11e]",
        ],
      },
      {
        heading: "Physiotherapy, ergonomics, red flags and referral",
        points: [
          "Prescribe **relative rest and load modification, not immobilisation**, followed by graded strengthening, because tendons adapt to progressive load. [Kelley and Firestein 11e]",
          "**Computer users:** keep the wrist neutral, keyboard at elbow height, forearms supported and mouse close, and take micro-breaks every 30-60 minutes. [NIOSH 2016]",
          "**Manual workers:** use tools with larger padded grips, reduce vibration and forceful pinch, and rotate tasks; **new mothers** should lift babies with palms up rather than through the thumb web. [Green's Operative Hand Surgery 8e]",
          "**Footwear:** cushioned shoes with arch support for heel pain, and avoidance of prolonged barefoot standing on hard floors. [NICE CKS 2023]",
          "Control **weight, diabetes and thyroid disease**, which drive recurrence of tendinopathy and entrapment. [Kelley and Firestein 11e]",
          "**Red flags:** night pain with weight loss or fever, hot swollen joint or tendon sheath, progressive weakness or muscle wasting, constant numbness, sudden loss of function after injury, or a hard growing lump. [NICE CKS 2023]",
          "**Refer to a hand or orthopaedic surgeon** for CTS with thenar wasting or severe NCS, trigger finger with fixed flexion, symptomatic ganglia wanting excision and suspected tendon rupture. [NICE CKS 2023]",
          "**Refer to rheumatology** when multiple sites, enthesitis with back pain, or synovitis suggest inflammatory arthritis. [NICE NG100 2018]",
          "**Refer for nerve conduction studies** when an entrapment is atypical, bilateral with systemic symptoms, or surgery is planned. [AAOS CTS CPG 2016]",
          "Reassess conservative treatment at **6-12 weeks**, and review the diagnosis if there is no progress by 3-6 months. [NICE CKS 2023]",
        ],
      },
    ],
    tables: [
      {
        heading: "Types of peripheral nerve entrapment",
        columns: ["Syndrome", "Nerve and site", "Symptoms", "Key sign or test"],
        rows: [
          ["Carpal tunnel", "Median nerve under flexor retinaculum", "Night paraesthesia of radial 3.5 fingers, palm spared", "Tinel, Phalen, Durkan; thenar wasting"],
          ["Cubital tunnel", "Ulnar nerve behind medial epicondyle", "Tingling of little and ring fingers including dorsum", "Froment sign, elbow flexion test"],
          ["Guyon canal", "Ulnar nerve at wrist", "Ulnar digit tingling, dorsum spared", "Intrinsic weakness, Tinel at hook of hamate"],
          ["Meralgia paraesthetica", "Lateral femoral cutaneous nerve at ASIS", "Burning anterolateral thigh, no weakness", "Tinel medial to ASIS, pelvic compression"],
          ["Tarsal tunnel", "Tibial nerve behind medial malleolus", "Burning sole, worse on standing", "Tinel behind medial malleolus"],
          ["Morton neuroma", "Interdigital nerve, third web", "Burning forefoot into toes", "Mulder click"],
        ],
      },
      {
        heading: "Steroid injection guide for soft-tissue disorders",
        columns: ["Condition", "Agent and dose", "Site", "Specific caution"],
        rows: [
          ["Tennis elbow", "Methylprednisolone 20-40 mg", "Point of maximal tenderness at ECRB origin", "Short-term benefit only; worse at 1 year"],
          ["Carpal tunnel", "Methylprednisolone 40 mg", "Proximal to distal crease, ulnar to palmaris longus", "Stop if paraesthesia - median nerve"],
          ["De Quervain", "Triamcinolone 10-20 mg", "First dorsal compartment at radial styloid", "Depigmentation; superficial radial nerve"],
          ["Trigger finger", "Triamcinolone 10-20 mg", "Flexor sheath at A1 pulley", "Lower success in diabetes; check sugars"],
          ["Plantar fasciitis", "Methylprednisolone 20-40 mg", "Medial heel approach", "Fascial rupture, fat pad atrophy"],
          ["Achilles tendinopathy", "Not recommended", "-", "Risk of rupture"],
        ],
      },
      {
        heading: "Differential diagnosis of heel pain",
        columns: ["Cause", "Clue"],
        rows: [
          ["Plantar fasciitis", "First-step pain, medial calcaneal tubercle tenderness, windlass test"],
          ["Calcaneal stress fracture", "Runner or osteoporotic woman, positive side-squeeze test"],
          ["Fat pad atrophy", "Elderly, central heel pain worse barefoot"],
          ["Achilles insertional tendinopathy", "Posterior heel pain, Haglund bump"],
          ["Spondyloarthritis enthesitis", "Young man, bilateral, back stiffness, HLA-B27"],
          ["Sever disease", "Active child aged 8-14, calcaneal squeeze pain"],
          ["Tarsal tunnel syndrome", "Burning sole, Tinel behind medial malleolus"],
          ["Infection or tumour", "Night pain, fever, swelling; TB calcaneum in India"],
        ],
      },
    ],
    redFlags: [
      "Thenar or intrinsic muscle wasting, or constant numbness - axonal loss needing surgery.",
      "Hot, red, swollen tendon sheath or joint with fever - septic tenosynovitis or arthritis.",
      "Night pain with weight loss or a hard, fixed, growing lump - tumour.",
      "Sudden pain and loss of function after load - tendon rupture (Achilles squeeze test).",
      "Thickened peripheral nerves with hypopigmented anaesthetic patches - leprosy neuritis.",
      "Bilateral entrapments with systemic features - hypothyroidism, diabetes, amyloid, acromegaly.",
      "Multiple sites of enthesitis with inflammatory back pain - spondyloarthritis.",
    ],
    pearls: [
      "Tendinopathy is degeneration, not inflammation - load it progressively rather than rest it.",
      "Steroid injection for tennis elbow helps at 6 weeks but is worse at 1 year.",
      "CTS spares the palm because the palmar cutaneous branch leaves before the tunnel.",
      "Thenar wasting in CTS is an indication for surgery, not another splint.",
      "Cubital tunnel involves the dorsal ulnar hand; Guyon canal spares it.",
      "Always feel the ulnar nerve for thickening in India - leprosy mimics entrapment.",
      "Finkelstein test for de Quervain; new mothers are a classic group.",
      "Half of ganglia disappear on their own; never hit one with a book.",
      "Plantar fasciitis: first-step morning pain; the spur is not the cause.",
      "Never inject steroid into the Achilles tendon.",
      "No more than three injections a year at one site.",
    ],
    mcqs: [
      {
        id: "musculoskeletal-regional-soft-tissue-disorders-q1",
        stem: "A 45-year-old woman has night-time tingling of the thumb, index and middle fingers, relieved by shaking her hand. Sensation over the thenar eminence of the palm is normal. The palm is spared because:",
        options: [
          "The palmar cutaneous branch of the median nerve arises proximal to the carpal tunnel",
          "The palm is supplied only by the ulnar nerve",
          "The recurrent motor branch carries palmar sensation",
          "The superficial radial nerve supplies the whole palm",
        ],
        answer: 0,
        explanation:
          "The palmar cutaneous branch leaves the median nerve about 5 cm proximal to the wrist and passes superficial to the flexor retinaculum, so palmar sensation is preserved in carpal tunnel syndrome. The ulnar nerve supplies only the ulnar palm, the recurrent motor branch is motor to the thenar muscles, and the superficial radial nerve supplies the dorsum.",
        difficulty: "moderate",
      },
      {
        id: "musculoskeletal-regional-soft-tissue-disorders-q2",
        stem: "A new mother has pain over the radial styloid that is reproduced when her wrist is ulnar-deviated with the thumb clenched in the fist. The diagnosis is:",
        options: [
          "Thumb carpometacarpal osteoarthritis",
          "Scaphoid fracture",
          "De Quervain tenosynovitis",
          "Intersection syndrome",
        ],
        answer: 2,
        explanation:
          "A positive Finkelstein test over the radial styloid in a new mother is classic de Quervain tenosynovitis of APL and EPB in the first dorsal compartment. CMC osteoarthritis gives a positive grind test at the thumb base, scaphoid fracture needs a history of a fall with snuffbox tenderness, and intersection syndrome causes pain and crepitus 4-8 cm proximal to the wrist.",
        difficulty: "easy",
      },
      {
        id: "musculoskeletal-regional-soft-tissue-disorders-q3",
        stem: "Regarding corticosteroid injection for lateral epicondylalgia, randomised trials show:",
        options: [
          "Better outcomes at 1 year than physiotherapy",
          "Short-term benefit at about 6 weeks but worse outcomes and more recurrence at 1 year",
          "No short-term benefit over placebo",
          "Permanent cure in most patients after a single injection",
        ],
        answer: 1,
        explanation:
          "Trials such as Bisset (BMJ 2006) and Coombes (JAMA 2013) showed steroid injection relieves pain within weeks, but by 1 year outcomes are worse and recurrence higher than with physiotherapy or wait-and-see. It is therefore not better at 1 year, it does help short-term, and it does not produce durable cure.",
        difficulty: "moderate",
      },
      {
        id: "musculoskeletal-regional-soft-tissue-disorders-q4",
        stem: "A 50-year-old overweight shopkeeper has heel pain that is worst with the first steps each morning and tenderness at the medial calcaneal tubercle. X-ray shows a calcaneal spur. The best initial management is:",
        options: [
          "Surgical excision of the calcaneal spur",
          "Immediate steroid injection through the plantar skin",
          "Complete rest and a below-knee plaster for 6 weeks",
          "Plantar fascia and calf stretching, cushioned footwear with heel cups, and weight loss",
        ],
        answer: 3,
        explanation:
          "Plantar fasciitis resolves in 80-90 per cent within a year with stretching, supportive cushioned footwear, heel cups and weight loss. The spur is an incidental finding and not a reason for surgery; steroid injection is second line and carries risks of fascial rupture and fat pad atrophy; plaster immobilisation is unnecessary.",
        difficulty: "easy",
      },
      {
        id: "musculoskeletal-regional-soft-tissue-disorders-q5",
        stem: "A 35-year-old farmer from Chhattisgarh has tingling of the little finger and weak grip. The ulnar nerve behind the elbow is thickened and there is a hypopigmented anaesthetic patch on the forearm. The most appropriate next step is:",
        options: [
          "Night extension splint for cubital tunnel syndrome",
          "Ulnar nerve transposition surgery",
          "Skin smear and assessment for leprosy with neuritis",
          "Steroid injection into the cubital tunnel",
        ],
        answer: 2,
        explanation:
          "A thickened peripheral nerve with an anaesthetic hypopigmented patch is leprosy until proved otherwise, and neuritis needs multidrug therapy and prednisolone under NLEP. Treating it as simple cubital tunnel syndrome with splints, surgery or local steroid would miss the diagnosis and allow permanent nerve damage.",
        difficulty: "hard",
      },
    ],
    theory: [
      {
        id: "musculoskeletal-regional-soft-tissue-disorders-t1",
        paper: "I",
        kind: "long",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question:
          "A 42-year-old woman presents with tingling of the hand at night. Discuss the anatomy, risk factors, clinical tests, investigations and management of carpal tunnel syndrome. [2+2+2+4]",
        openingLines: [
          "Carpal tunnel syndrome is compression of the median nerve beneath the flexor retinaculum at the wrist and is the commonest entrapment neuropathy.",
          "Diagnosis is clinical, confirmed by nerve conduction studies, and treatment is graded from night splints to steroid injection and surgical release.",
        ],
        answer: [
          {
            heading: "Anatomy",
            points: [
              "Tunnel formed by carpal bones and transverse carpal ligament; contains median nerve and nine flexor tendons.",
              "Palmar cutaneous branch arises proximally - palm spared; recurrent motor branch to thenar muscles.",
            ],
          },
          {
            heading: "Risk factors",
            points: ["Female, pregnancy, obesity, diabetes, hypothyroidism, RA, acromegaly, amyloid, dialysis, wrist fracture, vibratory work."],
          },
          {
            heading: "Clinical tests and investigations",
            points: [
              "Night paraesthesia, flick sign, Tinel, Phalen, Durkan; thenar wasting, weak APB.",
              "NCS: prolonged distal latency; ultrasound CSA over 10 mm2; TSH and blood sugar.",
            ],
          },
          {
            heading: "Management",
            points: [
              "Treat cause; neutral night splint 6-8 weeks; ergonomics.",
              "Steroid injection methylprednisolone 40 mg ulnar to palmaris longus.",
              "Surgery: open or endoscopic release for thenar wasting, constant numbness, severe NCS or failed conservative care.",
              "Pregnancy: splint, resolves after delivery.",
            ],
          },
        ],
        mustDraw: ["Cross-section of the carpal tunnel with its contents", "Sensory distribution of the median nerve in the hand"],
        markSplit: [
          { part: "Anatomy", marks: 2 },
          { part: "Risk factors", marks: 2 },
          { part: "Tests and investigations", marks: 2 },
          { part: "Management", marks: 4 },
        ],
        keywords: ["carpal tunnel", "median nerve", "Tinel", "Phalen", "nerve conduction", "release"],
      },
      {
        id: "musculoskeletal-regional-soft-tissue-disorders-t2",
        paper: "I",
        kind: "short-note",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question: "Write short notes on (a) tennis elbow, (b) ganglion and (c) plantar fasciitis. [3+3+4]",
        openingLines: [
          "Tennis elbow, ganglion and plantar fasciitis are common regional soft-tissue disorders managed largely in primary care.",
          "Each is diagnosed clinically and usually settles with education and conservative care, with injection or surgery reserved for refractory cases.",
        ],
        answer: [
          {
            heading: "Tennis elbow",
            points: [
              "ECRB origin tendinopathy, age 35-55; Cozen, Mill and Maudsley tests.",
              "Education, topical NSAID, brace, eccentric exercise; steroid injection short-term only; surgery after 6-12 months.",
            ],
          },
          {
            heading: "Ganglion",
            points: [
              "Mucin-filled cyst from capsule or sheath; dorsal wrist commonest; transilluminates.",
              "Half resolve; aspiration recurs; excision with stalk; avoid striking; refer hard or growing lumps.",
            ],
          },
          {
            heading: "Plantar fasciitis",
            points: [
              "Medial calcaneal tubercle; first-step morning pain; windlass test; spur incidental.",
              "Differentials: stress fracture, fat pad atrophy, enthesitis, Sever disease, tarsal tunnel.",
              "Stretching, heel cups, footwear, weight loss; injection or ESWT for refractory; 80-90 per cent recover in a year.",
            ],
          },
        ],
        mustDraw: ["Diagram of plantar fascia with site of tenderness"],
        markSplit: [
          { part: "Tennis elbow", marks: 3 },
          { part: "Ganglion", marks: 3 },
          { part: "Plantar fasciitis", marks: 4 },
        ],
        keywords: ["tennis elbow", "ganglion", "plantar fasciitis", "heel pain", "steroid injection"],
      },
    ],
    references: [
      "Apley and Solomon's System of Orthopaedics and Trauma, 10th edition, 2018",
      "Firestein and Kelley's Textbook of Rheumatology, 11th edition, 2021",
      "Green's Operative Hand Surgery, 8th edition, 2022",
      "NICE Clinical Knowledge Summaries: carpal tunnel syndrome, tennis elbow and plantar fasciitis, 2023",
      "AAOS Clinical Practice Guideline: Management of Carpal Tunnel Syndrome, 2016",
      "Coombes BK et al. Effect of corticosteroid injection, physiotherapy, or both on lateral epicondylalgia: a randomized clinical trial. JAMA 2013",
      "NLEP: National Strategic Plan and Roadmap for Leprosy 2023-2027, MoHFW",
    ],
  },
];

export default topics;
