import type { Topic } from "../../lib/types";

const topics: Topic[] = [
  {
    id: "pediatrics-neonatal-jaundice",
    title: "Neonatal jaundice: physiological, pathological and phototherapy",
    oneLiner:
      "Neonatal jaundice is visible yellowing of the skin and sclera from a serum bilirubin above about 5 mg/dL; most is benign **physiological unconjugated hyperbilirubinaemia** appearing after 24 hours, but jaundice within 24 hours, a bilirubin above the hour-specific **AAP 2022 phototherapy threshold**, prolonged jaundice or pale stools is pathological and risks **kernicterus**.",
    frequency: "core",
    keywords: [
      "neonatal hyperbilirubinaemia",
      "physiological jaundice",
      "pathological jaundice",
      "Kramer zones",
      "Bhutani nomogram",
      "AAP 2022 hyperbilirubinemia guideline",
      "phototherapy",
      "exchange transfusion",
      "kernicterus",
      "BIND score",
      "acute bilirubin encephalopathy",
      "breast milk jaundice",
      "breastfeeding jaundice",
      "Rh isoimmunisation",
      "ABO incompatibility",
      "G6PD deficiency",
      "biliary atresia",
      "stool colour card",
      "transcutaneous bilirubin",
      "IVIG",
    ],
    sections: [
      {
        heading: "Bilirubin metabolism in the newborn",
        points: [
          "**Haem from senescent red cells** is opened by haem oxygenase to biliverdin and reduced by biliverdin reductase to unconjugated bilirubin, releasing one molecule of carbon monoxide per haem. [Nelson 22e]",
          "**Unconjugated bilirubin is lipid-soluble and travels bound to albumin** - only the small unbound (free) fraction crosses the blood-brain barrier and causes neurotoxicity. [Nelson 22e]",
          "Hepatocyte uptake is by carrier proteins and **ligandin (Y protein)**, and conjugation with glucuronic acid is done by **UDP-glucuronosyltransferase 1A1 (UGT1A1)**. [Nelson 22e]",
          "**Conjugated bilirubin is water-soluble**, excreted into bile and, in the adult gut, reduced by bacteria to urobilinogen and stercobilin. [Nelson 22e]",
          "The newborn produces **6-8 mg/kg/day of bilirubin, about twice the adult rate**, because of a high haematocrit (50-60 per cent) and a red cell lifespan of only 70-90 days. [Nelson 22e]",
          "**UGT1A1 activity is about 1 per cent of adult levels at birth** and reaches adult levels only by 6-14 weeks, so conjugation is the bottleneck. [Cloherty 9e]",
          "**Enterohepatic circulation is exaggerated** - intestinal beta-glucuronidase deconjugates bilirubin, the sterile gut lacks bacteria to convert it, and delayed passage of meconium adds to the load. [Nelson 22e]",
          "Anything that **increases production** (haemolysis, bruising, polycythaemia), **reduces conjugation** (prematurity, hypothyroidism, Gilbert, Crigler-Najjar) or **increases reabsorption** (poor feeding, obstruction) pushes bilirubin higher. [Nelson 22e]",
          "**Albumin binding is reduced** by acidosis, sepsis, hypoalbuminaemia, prematurity and drugs such as ceftriaxone and sulphonamides - these lower the safe bilirubin level. [AAP 2022]",
          "Clinical jaundice appears in the newborn at a serum bilirubin of **about 5 mg/dL**, compared with about 2 mg/dL in adults, and progresses **cephalocaudally**. [Nelson 22e]",
        ],
      },
      {
        heading: "Burden, physiological jaundice and the warning features of pathological jaundice",
        points: [
          "About **60 per cent of term and 80 per cent of preterm neonates** become visibly jaundiced in the first week of life. [Nelson 22e]",
          "Neonatal hyperbilirubinaemia is among the **commonest reasons for SNCU admission in India**, and G6PD deficiency, ABO and Rh disease make severe jaundice more frequent than in Western cohorts. [NNF CPG 2020]",
          "**Physiological jaundice appears after 24 hours**, peaks on **day 3-5 in term** babies and fades by day 7-10; in preterm babies it peaks on day 5-7 and may last 2 weeks. [Nelson 22e]",
          "In physiological jaundice the baby is **well, feeding, and the rise is under 5 mg/dL per day (0.2 mg/dL per hour)**, with conjugated bilirubin under 1 mg/dL. [Nelson 22e]",
          "**Onset within the first 24 hours is always pathological** - it means haemolysis (Rh, ABO, G6PD), sepsis or congenital infection until proven otherwise. [AAP 2022]",
          "A bilirubin **rising faster than 0.2 mg/dL per hour**, or at or above the hour-specific phototherapy threshold, is pathological regardless of the baby's appearance. [AAP 2022]",
          "**Conjugated (direct) bilirubin above 1 mg/dL** at any age is pathological and needs a cholestasis work-up the same week. [NASPGHAN 2017]",
          "**Jaundice beyond 14 days in a term or 21 days in a preterm baby** is prolonged jaundice and needs a fractionated bilirubin, not reassurance. [NICE CG98 2023]",
          "Jaundice with **lethargy, poor feeding, fever, vomiting, hepatosplenomegaly, pallor or dark urine with pale stools** is pathological whatever the bilirubin value. [Nelson 22e]",
        ],
      },
      {
        heading: "Causes: haemolytic, non-haemolytic and conjugated",
        points: [
          "**Rh isoimmunisation** - Rh-negative mother, Rh-positive baby, jaundice within 24 hours, anaemia, hydrops in severe cases and a **strongly positive direct Coombs test**. [Nelson 22e]",
          "**ABO incompatibility** - group O mother with an A or B baby, can occur in the first pregnancy, is usually milder, and shows **microspherocytes with a weakly positive or negative DCT**. [Nelson 22e]",
          "**G6PD deficiency** is common in India (about 8 per cent in pooled Indian studies, higher in some tribal and community groups) and can cause sudden severe jaundice with a negative Coombs test. [NNF CPG 2020]",
          "In G6PD-deficient babies, jaundice is often **triggered by naphthalene mothballs, herbal remedies, infection or oxidant drugs** given to the baby or the breastfeeding mother. [Nelson 22e]",
          "Other haemolytic causes: **hereditary spherocytosis**, pyruvate kinase deficiency and drug-induced haemolysis - a family history of splenectomy or gallstones is the clue. [Nelson 22e]",
          "Non-haemolytic increased load: **cephalhaematoma, extensive bruising, polycythaemia, delayed cord clamping in a small baby and swallowed maternal blood**. [Cloherty 9e]",
          "Reduced conjugation or increased reabsorption: **prematurity, infant of a diabetic mother, congenital hypothyroidism, Gilbert and Crigler-Najjar syndromes**, pyloric stenosis and intestinal obstruction. [Nelson 22e]",
          "**Sepsis and congenital infections (TORCH, syphilis)** cause both haemolysis and impaired conjugation, so the jaundice can be mixed. [Nelson 22e]",
          "Conjugated hyperbilirubinaemia: **biliary atresia, idiopathic neonatal hepatitis, choledochal cyst, galactosaemia, alpha-1 antitrypsin deficiency, TORCH and prolonged parenteral nutrition**. [NASPGHAN 2017]",
          "**Congenital hypothyroidism** presents with prolonged jaundice, lethargy, a large tongue and an umbilical hernia - the newborn screen TSH must be looked up, not assumed. [Nelson 22e]",
        ],
      },
      {
        heading: "Clinical assessment: Kramer zones, transcutaneous bilirubin and the nomogram",
        points: [
          "**Examine every newborn for jaundice at least every 12 hours** during the birth admission, in daylight, by blanching the skin with a finger. [AAP 2022]",
          "**Kramer zones:** head and neck (zone 1), upper trunk to umbilicus (2), lower trunk and thighs (3), arms and legs below the knees (4), palms and soles (5) - each zone approximates a higher bilirubin. [NNF CPG 2020]",
          "**Visual assessment is unreliable** - it underestimates bilirubin in dark-skinned babies, cannot be used under phototherapy and cannot give an hour-specific value. [AAP 2022]",
          "**Visual estimation must not be used to decide treatment**; it only decides who needs a measured bilirubin, and any jaundice in the first 24 hours needs one within 2 hours. [NICE CG98 2023]",
          "AAP 2022 recommends a **transcutaneous (TcB) or serum bilirubin (TSB) in every newborn of 35 weeks or more** before discharge, or within 24-48 hours if at home. [AAP 2022]",
          "**Confirm TcB with a serum bilirubin** when TcB is within 3 mg/dL of the phototherapy threshold or 15 mg/dL or more, because TcB loses accuracy at high values. [AAP 2022]",
          "The **Bhutani hour-specific nomogram** (1999) plots bilirubin against age in hours into low, low-intermediate, high-intermediate and high-risk (above 95th centile) zones. [Nelson 22e]",
          "AAP 2022 has replaced risk zones with **the gap between the measured bilirubin and the hour-specific phototherapy threshold** to decide further testing and follow-up. [AAP 2022]",
          "Plot every value against the baby's **age in hours, not days** - a value of 12 mg/dL is harmless at 96 hours but alarming at 24 hours. [AAP 2022]",
          "Work-up of significant jaundice: **total and direct bilirubin, blood groups of mother and baby, DCT, haemoglobin, peripheral smear, reticulocyte count and G6PD**; add albumin, TSH and a sepsis screen as indicated. [NNF CPG 2020]",
        ],
      },
      {
        heading: "Phototherapy: thresholds, technique and complications",
        points: [
          "Phototherapy thresholds for babies of **35 weeks or more** come from the AAP 2022 curves, which are specific for **gestational age and the presence of neurotoxicity risk factors**. [AAP 2022]",
          "**Neurotoxicity risk factors (AAP 2022):** gestation under 38 weeks, albumin under 3.0 g/dL, isoimmune haemolysis, G6PD deficiency or other haemolysis, sepsis, and significant clinical instability in the previous 24 hours. [AAP 2022]",
          "For babies **under 35 weeks**, thresholds are lower and rise with gestation and birth weight; NNF India and NICE provide gestation-specific charts. [NNF CPG 2020]",
          "Phototherapy converts bilirubin by **photo-isomerisation (lumirubin) and configurational isomerisation** into water-soluble products excreted in bile and urine without conjugation. [Nelson 22e]",
          "**Effective wavelength is blue-green light, 460-490 nm**; intensive phototherapy delivers an irradiance of **at least 30 microW/cm2/nm** over the largest possible body surface. [AAP 2022]",
          "Technique: **baby naked except for a small nappy, eyes shielded**, LED unit at the manufacturer's distance (usually 30-45 cm), irradiance checked with a radiometer. [NNF CPG 2020]",
          "**Continue breastfeeding on demand**, 8-12 times a day, during phototherapy - interruptions for feeds of up to 30 minutes do not reduce efficacy. [AAP 2022]",
          "Routine **intravenous fluids or extra water are not needed** unless the baby is dehydrated or has lost more than about 10 per cent of birth weight. [AAP 2022]",
          "**Repeat bilirubin within 12 hours** of starting (4-6 hours if haemolysis or near the exchange level); **stop when TSB is at least 2 mg/dL below the threshold at which phototherapy began**. [AAP 2022]",
          "Check a **rebound bilirubin 12-24 hours after stopping** in haemolysis, prematurity or when phototherapy was started in the first 48 hours. [AAP 2022]",
          "Complications: **temperature instability, increased insensible water loss, loose stools, skin rash, separation from the mother** and eye injury if the shield slips. [Nelson 22e]",
          "**Bronze baby syndrome** occurs when a baby with cholestasis is put under phototherapy - one more reason to check the direct bilirubin first. [Nelson 22e]",
          "**Congenital erythropoietic porphyria** is the absolute contraindication, and **sunlight exposure is not an acceptable substitute** for phototherapy - it burns and does not deliver a controlled dose. [AAP 2022]",
        ],
      },
      {
        heading: "Escalation of care, IVIG and exchange transfusion",
        points: [
          "**Escalation of care threshold = 2 mg/dL below the exchange transfusion threshold** - the baby needs intensive phototherapy in a NICU, urgent labs and blood cross-matched. [AAP 2022]",
          "At escalation, send **TSB every 2 hours, CBC, albumin, bilirubin-albumin ratio, blood group and cross-match**, and start IV hydration if intake is poor. [AAP 2022]",
          "**IVIG 0.5-1 g/kg IV over 2 hours** is given in isoimmune haemolytic disease when TSB reaches the escalation threshold, and may be repeated in 12 hours. [AAP 2022]",
          "**Exchange transfusion indications:** TSB at or above the exchange threshold for age and risk factors, or **any sign of intermediate or advanced acute bilirubin encephalopathy** whatever the TSB. [AAP 2022]",
          "A **bilirubin-albumin ratio** at or above the exchange cut-off (about 8 mg/dL per g/dL in low-risk term babies) supports exchange even when TSB is borderline. [AAP 2022]",
          "Classical cord-blood criteria in Rh disease: **cord haemoglobin under 10-11 g/dL or cord bilirubin above 5 mg/dL** predict the need for early exchange. [Cloherty 9e]",
          "**Double-volume exchange = 2 x 80-85 mL/kg (about 160-170 mL/kg)** - it replaces about 85 per cent of red cells and removes about half of the circulating bilirubin. [Nelson 22e]",
          "Blood: **fresh (under 5-7 days), irradiated, CMV-safe**; O Rh-negative cells for Rh disease, and **O cells with AB plasma** for ABO disease, cross-matched against the mother's serum. [Cloherty 9e]",
          "Performed via the **umbilical vein by push-pull in 5-10 mL aliquots over 60-90 minutes** with continuous cardiorespiratory monitoring. [Cloherty 9e]",
          "Complications: **hypocalcaemia, hypoglycaemia, thrombocytopenia, air embolism, arrhythmia, NEC, portal vein thrombosis, infection and death (under 1 per cent in skilled hands)**. [Nelson 22e]",
        ],
      },
      {
        heading: "Breastfeeding, breast-milk jaundice and prolonged jaundice",
        points: [
          "**Suboptimal-intake (breastfeeding) jaundice** appears in the first week when intake is low - weight loss above 10 per cent, few wet nappies and delayed stools are the clues. [AAP 2022]",
          "Treat suboptimal intake with **lactation support and 8-12 feeds a day**, and expressed breast milk top-up by cup or paladai - **never glucose water or plain water**. [AAP 2022]",
          "**Breast-milk jaundice** begins after the first week, peaks at 2-3 weeks and can last 6-12 weeks, in a thriving baby with normal stools and urine. [Nelson 22e]",
          "Breast-milk jaundice is attributed to **milk factors (beta-glucuronidase, fatty acids) that increase enterohepatic circulation**, often with a UGT1A1 (Gilbert) polymorphism. [Nelson 22e]",
          "It is a **diagnosis of exclusion**, and **breastfeeding should continue** - routine interruption is no longer advised because it undermines lactation. [NICE CG98 2023]",
          "**Prolonged jaundice work-up:** total and conjugated bilirubin, stool and urine colour, TSH and T4, G6PD, urine culture, and galactosaemia screen if feeding poorly. [NICE CG98 2023]",
          "**Pale (acholic) stools and dark urine** in a jaundiced baby are biliary atresia until proven otherwise - refer to paediatric hepatology the same week. [NASPGHAN 2017]",
          "**Kasai portoenterostomy before 60 days of age** (ideally before 45 days) doubles native liver survival - the family physician's delay is the baby's liver. [Nelson 22e]",
          "The **infant stool colour card** given with the MCP card allows mothers to flag pale stools at home and is being used in several Indian states. [IAP 2024]",
        ],
      },
      {
        heading: "Kernicterus, BIND and prevention after early discharge",
        points: [
          "**Acute bilirubin encephalopathy (ABE)** - early phase: lethargy, hypotonia and poor suck; intermediate: hypertonia, retrocollis, high-pitched cry and fever; advanced: opisthotonus, apnoea, seizures and coma. [Nelson 22e]",
          "**Kernicterus** is the chronic, permanent sequel with yellow staining of the **globus pallidus, subthalamic nucleus, hippocampus, cerebellum and brainstem nuclei**. [Nelson 22e]",
          "**Chronic kernicterus tetrad:** choreoathetoid cerebral palsy, sensorineural hearing loss (auditory neuropathy), upward gaze palsy and dental enamel dysplasia. [Nelson 22e]",
          "**BIND score** grades mental status, muscle tone and cry from 0-9; a score of 4-6 is moderate and 7-9 advanced ABE, both indications for emergency exchange. [AAP 2022]",
          "**MRI shows bilateral globus pallidus T2 hyperintensity** and brainstem auditory evoked responses are abnormal - every baby who reached exchange levels needs a hearing test. [Nelson 22e]",
          "**Before discharge**, assess risk: gestation, a pre-discharge TcB or TSB close to threshold, jaundice in 24 hours, haemolysis, a sibling who needed phototherapy and suboptimal feeding. [AAP 2022]",
          "**Follow-up by the gap to threshold:** within 2 mg/dL - delay discharge or treat; 2-3.4 mg/dL - repeat bilirubin in 4-24 hours; 3.5-5.4 mg/dL - recheck in 1-2 days. [AAP 2022]",
          "A traditional safe rule: **a baby discharged before 48 hours is seen again within 48-72 hours**, which is exactly when the physiological peak arrives. [AAP 2022]",
          "**Counsel parents before discharge**: check colour in daylight, feed 8-12 times a day, and return at once if jaundice spreads to the legs, palms or soles, or the baby is drowsy or feeds poorly. [NNF CPG 2020]",
          "Prevention: **anti-D prophylaxis for Rh-negative mothers, G6PD screening where prevalent, avoiding naphthalene and unprescribed remedies**, and early exclusive breastfeeding. [MoHFW 2024]",
        ],
      },
      {
        heading: "Family physician role and referral",
        points: [
          "In a PHC without a paediatrician, a **4-day-old baby with yellow palms and soles or a drowsy baby with jaundice is referred the same hour** to the nearest SNCU. [NNF CPG 2020]",
          "Before referral: **keep the baby warm, continue breastfeeding or give expressed milk by cup**, and send a note with age in hours, feeding, weight and any bilirubin value. [MoHFW 2024]",
          "**Do not delay referral to wait for a lab report** when the baby has signs of encephalopathy - every hour at high bilirubin adds to brain injury. [AAP 2022]",
          "Advise against **sunlight exposure, stopping breastfeeding, glucose water, traditional herbal drops and phenobarbitone** - none is effective and some harm. [AAP 2022]",
          "Track **Rh-negative mothers and previous siblings with severe jaundice** from the antenatal period, so delivery happens where exchange transfusion is possible. [Williams 26e]",
          "A term baby with jaundice beyond 2 weeks needs a **conjugated bilirubin and a stool-colour check**, not a label of breast-milk jaundice by phone. [NICE CG98 2023]",
          "After severe hyperbilirubinaemia, arrange **hearing screening (ABR) and neurodevelopmental follow-up** through the DEIC under RBSK. [RBSK MoHFW 2021]",
        ],
      },
    ],
    tables: [
      {
        heading: "Kramer zones - clinical grading of dermal jaundice",
        columns: ["Zone", "Extent of yellow skin", "Approximate TSB (mg/dL)"],
        rows: [
          ["Zone 1", "Head and neck", "4-8 (about 5-6)"],
          ["Zone 2", "Upper trunk above umbilicus", "5-12 (about 9)"],
          ["Zone 3", "Lower trunk and thighs", "8-16 (about 12)"],
          ["Zone 4", "Arms and legs below knees", "11-18 (about 15)"],
          ["Zone 5", "Palms and soles", "Above 15 - refer urgently"],
        ],
      },
      {
        heading: "Physiological versus pathological jaundice",
        columns: ["Feature", "Physiological", "Pathological"],
        rows: [
          ["Onset", "After 24 hours (day 2-3)", "Within first 24 hours"],
          ["Peak (term)", "Day 3-5, below the phototherapy threshold", "At or above the hour-specific threshold"],
          ["Rate of rise", "Under 5 mg/dL per day", "Over 5 mg/dL per day (over 0.2 mg/dL per hour)"],
          ["Conjugated bilirubin", "Under 1 mg/dL", "Above 1 mg/dL"],
          ["Duration", "Under 2 weeks term, 3 weeks preterm", "Beyond 2 weeks term or 3 weeks preterm"],
          ["Baby", "Well, feeding, normal stools", "Lethargy, poor feeding, pallor, pale stools, dark urine"],
        ],
      },
      {
        heading: "Causes of neonatal jaundice by time of onset",
        columns: ["Onset", "Common causes", "Key test"],
        rows: [
          ["First 24 hours", "Rh and ABO haemolysis, G6PD deficiency, sepsis, TORCH", "Blood groups, DCT, smear, G6PD"],
          ["Day 2-7", "Physiological, suboptimal intake, haemolysis, sepsis, bruising, polycythaemia", "Hour-specific TSB, weight loss"],
          ["After 2 weeks, unconjugated", "Breast-milk jaundice, hypothyroidism, haemolysis, UTI", "TSH, G6PD, urine culture"],
          ["After 2 weeks, conjugated", "Biliary atresia, neonatal hepatitis, choledochal cyst, galactosaemia", "Direct bilirubin, stool colour, ultrasound"],
        ],
      },
    ],
    redFlags: [
      "Jaundice appearing within the first 24 hours of life.",
      "Yellow palms and soles (Kramer zone 5) or TSB at or above the phototherapy threshold for age in hours.",
      "Lethargy, poor suck, hypotonia or hypertonia, high-pitched cry, arching or seizures - suspect acute bilirubin encephalopathy.",
      "Pale or clay-coloured stools and dark urine staining the nappy.",
      "Jaundice with fever, poor feeding, vomiting or temperature instability - suspect sepsis.",
      "Rapid rise of bilirubin (over 0.2 mg/dL per hour) or rise despite phototherapy.",
      "Jaundice with pallor, hepatosplenomegaly or hydrops - haemolytic disease.",
      "Jaundice persisting beyond 14 days in a term or 21 days in a preterm baby.",
    ],
    pearls: [
      "Jaundice in the first 24 hours is never physiological.",
      "Plot bilirubin against age in hours, not days - the hour-specific value is the decision value.",
      "AAP 2022 made phototherapy thresholds specific to gestational age and neurotoxicity risk factors, and raised them modestly from 2004.",
      "Escalation of care begins 2 mg/dL below the exchange threshold - intensive phototherapy, IVIG in isoimmune disease, and blood ready.",
      "Stop phototherapy when TSB is 2 mg/dL below the level at which it was started, and check a rebound in high-risk babies.",
      "Breast-milk jaundice is a diagnosis of exclusion - keep breastfeeding.",
      "Pale stools plus jaundice equals biliary atresia until proved otherwise; Kasai before 60 days.",
      "Kernicterus tetrad: athetoid CP, auditory neuropathy, upward gaze palsy, enamel dysplasia.",
      "Sunlight is not phototherapy.",
      "Bronze baby syndrome is phototherapy in a cholestatic baby - check the direct bilirubin first.",
    ],
    mcqs: [
      {
        id: "pediatrics-neonatal-jaundice-q1",
        stem: "A 17-hour-old term baby born to a mother with blood group O positive is noticed to have yellow discolouration up to the umbilicus. The baby is feeding well. What is the most appropriate next step?",
        options: [
          "Reassure the mother that this is physiological jaundice",
          "Advise exposure to morning sunlight for 30 minutes twice a day",
          "Measure serum bilirubin urgently and plot it on an hour-specific chart",
          "Stop breastfeeding for 48 hours and give formula",
        ],
        answer: 2,
        explanation:
          "Jaundice within 24 hours is always pathological and needs a measured bilirubin plotted by age in hours, with blood groups and DCT to look for ABO haemolysis. Reassurance is wrong because physiological jaundice starts after 24 hours; sunlight is not a controlled treatment; stopping breastfeeding has no role.",
        difficulty: "easy",
      },
      {
        id: "pediatrics-neonatal-jaundice-q2",
        stem: "Which of the following is listed as a hyperbilirubinaemia neurotoxicity risk factor in the AAP 2022 guideline, lowering the phototherapy threshold?",
        options: [
          "Serum albumin below 3.0 g/dL",
          "Male sex",
          "Exclusive breastfeeding",
          "Birth by caesarean section",
        ],
        answer: 0,
        explanation:
          "AAP 2022 neurotoxicity risk factors are gestation under 38 weeks, albumin under 3.0 g/dL, isoimmune haemolysis, G6PD deficiency or other haemolysis, sepsis and significant clinical instability. Male sex and breastfeeding raise the risk of developing hyperbilirubinaemia but are not neurotoxicity factors; caesarean birth is neither.",
        difficulty: "moderate",
      },
      {
        id: "pediatrics-neonatal-jaundice-q3",
        stem: "A 5-week-old exclusively breastfed baby has persistent jaundice, dark urine that stains the nappy and pale clay-coloured stools. Weight gain is adequate. What is the most important diagnosis to exclude?",
        options: [
          "Breast-milk jaundice",
          "Gilbert syndrome",
          "Crigler-Najjar syndrome type 2",
          "Biliary atresia",
        ],
        answer: 3,
        explanation:
          "Acholic stools and dark urine indicate conjugated hyperbilirubinaemia, and biliary atresia must be excluded urgently because Kasai portoenterostomy works best before 60 days. Breast-milk jaundice, Gilbert and Crigler-Najjar all cause unconjugated jaundice with normal stools and no bilirubinuria.",
        difficulty: "easy",
      },
      {
        id: "pediatrics-neonatal-jaundice-q4",
        stem: "In the triad of chronic bilirubin encephalopathy (kernicterus), which eye sign is characteristically found?",
        options: [
          "Lateral rectus palsy",
          "Upward gaze palsy",
          "Horizontal nystagmus alone",
          "Bilateral cataract",
        ],
        answer: 1,
        explanation:
          "Chronic kernicterus shows choreoathetoid cerebral palsy, auditory neuropathy, upward gaze palsy and dental enamel dysplasia, from injury to the brainstem oculomotor nuclei and basal ganglia. Lateral rectus palsy and isolated nystagmus are not features, and cataract suggests galactosaemia or congenital rubella rather than bilirubin toxicity.",
        difficulty: "moderate",
      },
      {
        id: "pediatrics-neonatal-jaundice-q5",
        stem: "A term baby with Rh haemolytic disease has a TSB 1.5 mg/dL below the exchange transfusion threshold despite intensive phototherapy. There are no neurological signs. Besides preparing for exchange, which additional therapy is recommended?",
        options: [
          "Oral phenobarbitone 5 mg/kg for 5 days",
          "Intravenous 10 per cent dextrose bolus",
          "IVIG 0.5-1 g/kg over 2 hours",
          "Oral ursodeoxycholic acid",
        ],
        answer: 2,
        explanation:
          "At the escalation threshold (within 2 mg/dL of exchange) in isoimmune haemolysis, AAP 2022 recommends IVIG 0.5-1 g/kg over 2 hours, repeatable at 12 hours, which blocks antibody-mediated haemolysis. Phenobarbitone acts too slowly, dextrose does not lower bilirubin, and ursodeoxycholic acid is for cholestasis.",
        difficulty: "hard",
      },
    ],
    theory: [
      {
        id: "pediatrics-neonatal-jaundice-t1",
        paper: "IV",
        kind: "long",
        marks: 10,
        minutes: 18,
        frequency: "core",
        question:
          "A 17-hour-old baby is noticed to be jaundiced. Describe bilirubin metabolism in the newborn, the causes of jaundice in the first 24 hours and the management of this baby. [3+3+4]",
        openingLines: [
          "Neonatal jaundice is yellow discolouration of skin and sclera from serum bilirubin above about 5 mg/dL; onset in the first 24 hours is always pathological.",
          "About 60 per cent of term and 80 per cent of preterm newborns are jaundiced in the first week, and severe hyperbilirubinaemia is a leading cause of SNCU admission in India.",
        ],
        answer: [
          {
            heading: "Bilirubin metabolism and why the newborn is prone",
            points: [
              "Haem - haem oxygenase - biliverdin - biliverdin reductase - unconjugated bilirubin bound to albumin.",
              "Hepatic uptake by ligandin, conjugation by UGT1A1, excretion into bile, bacterial conversion to urobilinogen.",
              "Newborn: high production (6-8 mg/kg/day), low UGT1A1, increased enterohepatic circulation, sterile gut.",
            ],
          },
          {
            heading: "Causes of jaundice in the first 24 hours",
            points: [
              "Haemolytic: Rh isoimmunisation, ABO incompatibility, G6PD deficiency, hereditary spherocytosis.",
              "Infection: sepsis, TORCH, congenital syphilis.",
              "Others: concealed haemorrhage (cephalhaematoma), polycythaemia.",
            ],
          },
          {
            heading: "Evaluation",
            points: [
              "Examine in daylight, Kramer zone, signs of encephalopathy (BIND), pallor, hepatosplenomegaly.",
              "Urgent TSB plotted by age in hours on AAP 2022 curves; blood groups, DCT, Hb, smear, reticulocytes, G6PD, albumin.",
            ],
          },
          {
            heading: "Management",
            points: [
              "Phototherapy if at or above threshold for gestation and risk factors; blue-green LED 460-490 nm, at least 30 microW/cm2/nm, eyes shielded, continue breastfeeding.",
              "Repeat TSB in 4-6 hours in haemolysis; escalation at 2 mg/dL below exchange threshold; IVIG 0.5-1 g/kg for isoimmune disease.",
              "Double-volume exchange transfusion (160-170 mL/kg) at exchange threshold or with signs of ABE.",
              "Stop phototherapy at 2 mg/dL below starting threshold; check rebound; hearing screen and follow-up.",
            ],
          },
          {
            heading: "Family physician role",
            points: [
              "Refer to SNCU the same hour if no phototherapy is available; keep warm and fed during transfer.",
              "Anti-D for Rh-negative mothers; counsel on G6PD triggers and early review after discharge.",
            ],
          },
        ],
        mustDraw: ["Flow diagram of bilirubin metabolism from haem to stercobilin", "Kramer zone diagram of the baby"],
        markSplit: [
          { part: "Bilirubin metabolism", marks: 3 },
          { part: "Causes in first 24 hours", marks: 3 },
          { part: "Management", marks: 4 },
        ],
        keywords: ["bilirubin metabolism", "jaundice first 24 hours", "phototherapy", "exchange transfusion", "AAP 2022"],
      },
      {
        id: "pediatrics-neonatal-jaundice-t2",
        paper: "IV",
        kind: "short-note",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question:
          "Write short notes on: (a) physiological versus pathological jaundice, (b) breast-milk jaundice, (c) kernicterus. [4+3+3]",
        openingLines: [
          "Physiological jaundice is benign unconjugated hyperbilirubinaemia that appears after 24 hours, peaks on day 3-5 and fades by 2 weeks in a well baby.",
          "Kernicterus is permanent bilirubin-induced injury to the basal ganglia and brainstem nuclei that follows unrecognised severe hyperbilirubinaemia.",
        ],
        answer: [
          {
            heading: "Physiological versus pathological",
            points: [
              "Onset after vs within 24 hours; rise under vs over 5 mg/dL/day; conjugated under vs over 1 mg/dL.",
              "Duration under 2 weeks (term) vs prolonged; well baby vs sick baby, pale stools or dark urine.",
              "Mechanism of physiological jaundice: high production, low UGT1A1, enterohepatic circulation.",
            ],
          },
          {
            heading: "Breast-milk jaundice",
            points: [
              "Onset after day 7, peaks at 2-3 weeks, lasts up to 12 weeks in a thriving baby.",
              "Milk beta-glucuronidase and UGT1A1 polymorphism; diagnosis of exclusion after TSH, G6PD, conjugated bilirubin.",
              "Continue breastfeeding; contrast with early suboptimal-intake jaundice, treated by more frequent feeds.",
            ],
          },
          {
            heading: "Kernicterus",
            points: [
              "Acute bilirubin encephalopathy phases: hypotonia and poor suck; hypertonia, retrocollis, high cry; opisthotonus, seizures, apnoea.",
              "BIND score 0-9; emergency exchange for moderate or advanced ABE.",
              "Chronic tetrad: athetoid CP, auditory neuropathy, upward gaze palsy, enamel dysplasia; MRI globus pallidus hyperintensity.",
              "Prevention: universal pre-discharge bilirubin, early follow-up, timely phototherapy.",
            ],
          },
        ],
        mustDraw: ["Table contrasting physiological and pathological jaundice"],
        markSplit: [
          { part: "Physiological vs pathological", marks: 4 },
          { part: "Breast-milk jaundice", marks: 3 },
          { part: "Kernicterus", marks: 3 },
        ],
        keywords: ["physiological jaundice", "breast milk jaundice", "kernicterus", "BIND"],
      },
    ],
    references: [
      "Kemper AR et al. AAP Clinical Practice Guideline Revision: Management of Hyperbilirubinemia in the Newborn Infant 35 or More Weeks of Gestation. Pediatrics 2022",
      "Nelson Textbook of Pediatrics, 22nd edition (2024)",
      "National Neonatology Forum India, Clinical Practice Guidelines: Neonatal Hyperbilirubinemia, 2020",
      "NICE CG98 Jaundice in newborn babies under 28 days, updated 2023",
      "Cloherty and Stark's Manual of Neonatal Care, 9th edition (2023)",
      "NASPGHAN/ESPGHAN Guideline for evaluation of cholestatic jaundice in infants, 2017",
      "MoHFW Rashtriya Bal Swasthya Karyakram operational guidelines, 2021",
    ],
  },
  {
    id: "pediatrics-low-birth-weight-preterm-kmc",
    title: "Low birth weight, the preterm baby and kangaroo mother care",
    oneLiner:
      "A low birth weight (LBW) baby weighs **less than 2500 g at birth** whatever the gestation, and results from preterm birth (under 37 completed weeks), fetal growth restriction or both; survival depends on the **warm chain, breast milk, infection prevention and kangaroo mother care**, which WHO 2022 now advises be started **immediately after birth** for every baby under 2000 g.",
    frequency: "core",
    keywords: [
      "LBW",
      "VLBW",
      "ELBW",
      "preterm",
      "prematurity",
      "SGA",
      "IUGR",
      "fetal growth restriction",
      "KMC",
      "kangaroo mother care",
      "iKMC",
      "immediate KMC",
      "hypothermia",
      "warm chain",
      "paladai",
      "SNCU",
      "NBSU",
      "NBCC",
      "ROP",
      "retinopathy of prematurity",
      "caffeine citrate",
    ],
    sections: [
      {
        heading: "Definitions and classification",
        points: [
          "**Low birth weight (LBW):** birth weight **less than 2500 g**, measured preferably within the first hour of life, before postnatal weight loss. [WHO 2022]",
          "**Very low birth weight (VLBW) is under 1500 g** and **extremely low birth weight (ELBW) is under 1000 g** - mortality and morbidity rise steeply below each cut-off. [Nelson 22e]",
          "**Preterm:** born before **37 completed weeks** (under 259 days) - extremely preterm under 28 weeks, very preterm 28 to under 32, moderate to late preterm 32 to under 37 weeks. [WHO 2022]",
          "**Late preterm (34 to under 37 weeks)** babies look mature but carry higher risks of hypoglycaemia, jaundice, feeding difficulty and readmission than term babies. [Nelson 22e]",
          "**Small for gestational age (SGA):** birth weight **below the 10th centile** for gestation on a standard chart such as INTERGROWTH-21st or Fenton - a postnatal, statistical label. [Nelson 22e]",
          "**Fetal growth restriction (FGR/IUGR):** failure of the fetus to reach its genetic growth potential - a prenatal, pathological process; not every SGA baby is growth restricted. [Williams 26e]",
          "**Symmetrical IUGR** starts early (chromosomal, infection, severe undernutrition) with head, length and weight all small; **asymmetrical IUGR** starts late from placental insufficiency with relative head sparing. [Nelson 22e]",
          "**Ponderal index = weight (g) x 100 / length (cm) cubed**; a value under 2.0 at term suggests asymmetrical (wasted) growth restriction. [Nelson 22e]",
          "A baby can be **preterm and SGA at once** - such a baby carries both sets of problems and has the worst prognosis. [Nelson 22e]",
        ],
      },
      {
        heading: "Magnitude in India and causes",
        points: [
          "**NFHS-5 (2019-21): about 18 per cent** of babies with a recorded birth weight were LBW, and recorded weight is missing for a further tenth of births. [NFHS-5 2021]",
          "India has the **largest number of preterm births in the world**, about 3 million a year, with a preterm birth rate of about 13 per cent. [WHO Born Too Soon 2023]",
          "**Most Indian LBW babies are term but growth restricted**, whereas in high-income countries most LBW babies are preterm - so maternal nutrition is the lever in India. [Park 28e]",
          "**Prematurity and LBW are the leading cause of neonatal death** in India, where the neonatal mortality rate is about 19-20 per 1000 live births. [SRS 2021]",
          "The **India Newborn Action Plan (INAP)** targets a single-digit neonatal mortality rate and stillbirth rate by 2030, with care of small and sick newborns as a core pillar. [MoHFW 2024]",
          "**Causes of preterm birth:** previous preterm birth, multiple pregnancy, PPROM, genitourinary infection and chorioamnionitis, cervical insufficiency, uterine anomaly, antepartum haemorrhage and medically indicated delivery for pre-eclampsia. [Williams 26e]",
          "Social determinants of preterm birth: **teenage pregnancy, short interpregnancy interval, low BMI, anaemia, heavy physical work and tobacco** including smokeless forms. [Park 28e]",
          "**Causes of fetal growth restriction - maternal:** undernutrition, short stature, low pre-pregnancy weight, anaemia, hypertension and pre-eclampsia, chronic kidney or heart disease, tobacco and alcohol. [Williams 26e]",
          "**Placental and fetal causes of FGR:** placental insufficiency or infarcts, multiple pregnancy, chromosomal anomalies, congenital infections (TORCH, malaria) and genetic syndromes. [Williams 26e]",
          "**Low maternal weight gain** in pregnancy (under about 10 kg) and a mother who herself was LBW both raise the risk - the **intergenerational cycle of undernutrition**. [Park 28e]",
        ],
      },
      {
        heading: "Problems of the preterm versus the growth-restricted baby",
        points: [
          "**Preterm problems are problems of immaturity:** hypothermia, respiratory distress syndrome, apnoea, poor suck, hypoglycaemia, jaundice, sepsis, NEC, IVH, PDA and ROP. [Nelson 22e]",
          "**Respiratory distress syndrome** follows surfactant deficiency; antenatal corticosteroids, CPAP and surfactant (by LISA or INSURE) are the three proven interventions. [WHO 2022]",
          "**Suck-swallow-breathe coordination matures at about 32-34 weeks**, so babies below this need tube or cup feeding of expressed breast milk. [Nelson 22e]",
          "**Apnoea of prematurity:** a pause in breathing of **20 seconds or more**, or shorter with bradycardia or desaturation, typically from day 2-7 in babies under 34 weeks. [Nelson 22e]",
          "**Caffeine citrate 20 mg/kg loading then 5-10 mg/kg once daily** orally or IV treats apnoea of prematurity and is continued until about 34 weeks corrected age. [WHO 2022]",
          "**IUGR problems are problems of starvation and hypoxia:** perinatal asphyxia, meconium aspiration, hypoglycaemia (poor glycogen stores), hypothermia, polycythaemia and hypocalcaemia. [Nelson 22e]",
          "**Polycythaemia (venous haematocrit above 65 per cent)** in IUGR babies causes hyperviscosity with lethargy, hypoglycaemia and jaundice. [Cloherty 9e]",
          "Long-term: preterm babies risk **BPD, cerebral palsy, ROP, hearing loss and learning difficulties**; IUGR babies risk **short stature and adult metabolic syndrome** (Barker hypothesis). [Nelson 22e]",
          "**Anaemia of prematurity and metabolic bone disease** appear in the weeks after discharge in VLBW babies - they are why iron, vitamin D and fortifier are prescribed. [Cloherty 9e]",
        ],
      },
      {
        heading: "Thermal protection and hypothermia",
        points: [
          "**Normal axillary temperature is 36.5-37.5 C**; **cold stress is 36.0-36.4 C, moderate hypothermia 32.0-35.9 C and severe hypothermia below 32 C**. [WHO 2022]",
          "LBW babies lose heat fast because of a **large surface area to weight ratio, thin skin, little subcutaneous fat and scant brown fat**. [Nelson 22e]",
          "**The warm chain:** warm delivery room (25-28 C), immediate drying, skin-to-skin contact, early breastfeeding, postponed bathing, appropriate clothing and warm transport. [WHO 2022]",
          "**Delay the first bath for at least 24 hours** (longer in LBW babies) and weigh the baby wrapped, not naked on a cold scale. [WHO 2022]",
          "Babies **under 32 weeks** at delivery are placed wet into a **polyethylene bag or wrap** under a radiant warmer to prevent heat loss. [NRP 2021]",
          "**Rewarm moderate hypothermia by skin-to-skin KMC** or a radiant warmer; severe hypothermia needs a radiant warmer or incubator, IV 10 per cent dextrose and a sepsis work-up. [MoHFW 2024]",
          "**Hypothermia is itself a danger sign of sepsis** in the newborn - a cold baby is examined for infection, not just wrapped. [IMNCI 2020]",
          "Teach the mother to check warmth by **touching the baby's feet** - warm feet mean thermal comfort, cold feet with a warm abdomen mean cold stress. [WHO 2022]",
        ],
      },
      {
        heading: "Feeding the LBW baby",
        points: [
          "**Mother's own milk is the first choice for every LBW baby**; if unavailable, **pasteurised donor human milk** from a Comprehensive Lactation Management Centre; formula only as the last option. [WHO 2022]",
          "**Feeding method by maturity:** 34 weeks or more - direct breastfeeding; 32-34 weeks - expressed breast milk by **cup, spoon or paladai**; 28-31 weeks - orogastric tube; under 28 weeks - IV fluids with trophic tube feeds. [MoHFW 2024]",
          "**Starting volume is 60-80 mL/kg/day on day 1**, increased by **20-30 mL/kg/day** to reach **150-180 mL/kg/day** by the end of the first week. [MoHFW 2024]",
          "VLBW babies start early enteral feeds from **day 1** and can be advanced by up to 30 mL/kg/day - delaying feeds does not prevent NEC. [WHO 2022]",
          "**Feed 2-hourly (12 feeds a day) for VLBW** and 2-3 hourly for heavier babies; feeds are never skipped at night. [MoHFW 2024]",
          "Add **human milk fortifier** for babies born **under 32 weeks or under 1500 g** who are not gaining despite full feeds. [WHO 2022]",
          "**Vitamin D 400 IU daily** from the first week and **iron 2-3 mg/kg/day from 2-6 weeks** until one year for LBW babies; calcium and phosphorus for VLBW babies. [IAP 2024]",
          "**Target weight gain is 15-20 g/kg/day** after the baby regains birth weight, usually by day 10-14 in LBW babies. [MoHFW 2024]",
          "**Teach expression within an hour of birth** and 8-12 times a day, including once at night - early expression sets the milk supply. [WHO 2022]",
        ],
      },
      {
        heading: "Kangaroo mother care, including immediate KMC",
        points: [
          "**KMC has three components:** continuous skin-to-skin contact in the kangaroo position, exclusive breastfeeding, and early discharge with close follow-up. [WHO 2022]",
          "**WHO 2022 recommends KMC for all preterm or LBW babies under 2000 g, started as soon as possible after birth**, even before the baby is clinically stable, where facility care is available. [WHO 2022]",
          "The **WHO iKMC trial (NEJM 2021)** in babies of 1000-1799 g, including India, showed **about 25 per cent lower mortality** when KMC began immediately in a mother-newborn ICU. [NEJM iKMC 2021]",
          "Conventional KMC in stable babies cuts **mortality by about 40 per cent**, sepsis by about half and hypothermia by about 80 per cent compared with conventional care. [Cochrane KMC 2016]",
          "**Position:** baby naked except for nappy, cap and socks, **upright between the mother's breasts**, head turned to one side and slightly extended, hips flexed like a frog, secured by a binder. [MoHFW 2024]",
          "Aim for **at least 8 hours a day and ideally 20-24 hours**, in sessions of at least one hour, because frequent transfers stress the baby. [WHO 2022]",
          "**Fathers and other family members** can provide KMC when the mother rests; the mother sleeps reclining at 15-30 degrees. [MoHFW 2024]",
          "**Continue KMC until the baby reaches 2500 g or about 40 weeks corrected**, or starts to wriggle out - the baby signals the end. [MoHFW 2024]",
          "Benefits beyond survival: **better breastfeeding, faster weight gain, bonding, reduced maternal depression and earlier discharge**. [WHO 2022]",
          "**Discharge on KMC** when the baby is feeding well, gaining 15-20 g/kg/day for 3 consecutive days, maintaining temperature, and the mother is confident. [MoHFW 2024]",
          "India's **Mother-Newborn Care Units (MNCU)** bring mothers into the SNCU so that immediate KMC and family participatory care become routine. [MoHFW MNCU 2021]",
        ],
      },
      {
        heading: "Hypoglycaemia, jaundice, sepsis and ROP",
        points: [
          "**Hypoglycaemia: blood glucose under 45 mg/dL** (operational threshold); screen preterm, SGA and IDM babies at **2, 6, 12, 24, 48 and 72 hours**. [NNF CPG 2020]",
          "Symptomatic hypoglycaemia or glucose under 25 mg/dL: **10 per cent dextrose 2 mL/kg IV bolus**, then infusion at a **glucose infusion rate of 6-8 mg/kg/min**. [NNF CPG 2020]",
          "**Preterm babies need phototherapy at lower bilirubin levels** - thresholds fall with gestation and birth weight, and kernicterus can occur below term thresholds. [NNF CPG 2020]",
          "**Neonatal danger signs** (IMNCI): not feeding well, convulsions, fast breathing (60 per minute or more), severe chest indrawing, temperature 37.5 C or more or below 35.5 C, movement only on stimulation. [IMNCI 2020]",
          "Possible serious bacterial infection is treated with **injection ampicillin and gentamicin**; where referral is refused, **gentamicin IM once daily with oral amoxicillin for 7 days** is the WHO simplified regimen. [WHO PSBI 2015]",
          "**Hand washing, exclusive breast milk, KMC and minimal handling** are the cheapest sepsis prevention for LBW babies. [WHO 2022]",
          "**ROP screening (India): all babies under 34 weeks or under 2000 g**, and 34-36 weeks with risk factors such as oxygen therapy, sepsis or transfusion. [MoHFW ROP 2018]",
          "**First ROP screen by day 30 of life** (by day 20 for babies under 28 weeks or under 1200 g) and continue until the retina is vascularised. [MoHFW ROP 2018]",
          "**Type 1 ROP** is treated within 48-72 hours by **laser photocoagulation or intravitreal anti-VEGF**, and oxygen saturation is targeted at 90-95 per cent to prevent it. [ICROP3 2021]",
          "Follow-up of every LBW baby: **growth on INTERGROWTH-21st or Fenton charts, development by corrected age until 2 years, hearing screen, vision and immunisation by chronological age**. [IAP 2024]",
        ],
      },
      {
        heading: "Levels of newborn care, referral and prevention",
        points: [
          "**Newborn Care Corner (NBCC)** at every delivery point: radiant warmer, resuscitation bag and mask, suction - for resuscitation and routine care. [MoHFW FBNC 2021]",
          "**Newborn Stabilisation Unit (NBSU)** at FRUs and CHCs: 4 radiant warmers, oxygen and phototherapy - stabilise, manage mild illness and refer. [MoHFW FBNC 2021]",
          "**Special Newborn Care Unit (SNCU)** at district hospitals: at least 12 beds with trained staff for sick babies other than those needing ventilation. [MoHFW FBNC 2021]",
          "**SNCU admission criteria include birth weight under 1800 g or gestation under 34 weeks**, and any sick baby with respiratory distress, apnoea, convulsions, sepsis, significant jaundice or hypothermia. [MoHFW FBNC 2021]",
          "**Refer in KMC position** with the mother, warm and fed, with a referral slip - skin-to-skin transport is safer than an unheated ambulance cot. [MoHFW 2024]",
          "**HBNC and HBYC:** ASHAs make home visits on days 1, 3, 7, 14, 21, 28 and 42, with extra visits for LBW babies, then quarterly visits up to 15 months. [MoHFW HBYC 2018]",
          "**Prevent preterm birth complications:** antenatal corticosteroids (dexamethasone 6 mg IM 12-hourly for 4 doses) at 24-34 weeks when birth is imminent, and magnesium sulphate before 32 weeks. [WHO 2022]",
          "**Prevent LBW through maternal nutrition:** IFA 60 mg daily, calcium, balanced energy-protein supplementation and take-home ration under POSHAN Abhiyaan and PMMVY cash support. [Park 28e]",
          "**Adequate ANC** (at least four visits, PMSMA), treatment of anaemia, malaria, asymptomatic bacteriuria and hypertension, and **low-dose aspirin** for high-risk women reduce LBW. [FOGSI 2019]",
          "**Birth spacing of at least 24 months**, delaying first pregnancy beyond 20 years and tobacco cessation are the family-planning arm of LBW prevention. [WHO 2022]",
        ],
      },
    ],
    tables: [
      {
        heading: "Classification of newborns by weight and gestation",
        columns: ["Category", "Definition", "Key concern"],
        rows: [
          ["LBW", "Birth weight under 2500 g", "Warm chain, feeding, KMC"],
          ["VLBW", "Birth weight under 1500 g", "Tube feeds, fortifier, ROP, sepsis"],
          ["ELBW", "Birth weight under 1000 g", "RDS, IVH, NICU care"],
          ["Preterm", "Under 37 completed weeks", "Immaturity of every organ"],
          ["SGA", "Weight under 10th centile for gestation", "Hypoglycaemia, polycythaemia"],
        ],
      },
      {
        heading: "Preterm versus growth-restricted (SGA) baby",
        columns: ["Feature", "Preterm AGA", "Term SGA / IUGR"],
        rows: [
          ["Appearance", "Thin gelatinous skin, lanugo, flat ear cartilage, few sole creases", "Wasted, dry peeling skin, alert looking, large head for body"],
          ["Main respiratory problem", "RDS, apnoea", "Asphyxia, meconium aspiration"],
          ["Metabolic", "Hypoglycaemia, hypocalcaemia", "Hypoglycaemia (severe), polycythaemia"],
          ["Feeding", "Poor suck under 34 weeks - tube or cup", "Sucks well, hungry, needs more calories"],
          ["Late risks", "ROP, BPD, IVH, cerebral palsy", "Short stature, adult metabolic syndrome"],
        ],
      },
      {
        heading: "Feeding method by gestation and baby's readiness",
        columns: ["Gestation", "Initial feeding", "Progress to"],
        rows: [
          ["Under 28 weeks", "IV fluids plus trophic tube feeds of breast milk", "Orogastric feeds"],
          ["28-31 weeks", "Orogastric or nasogastric expressed breast milk", "Cup or paladai"],
          ["32-33 weeks", "Cup, spoon or paladai with expressed breast milk", "Direct breastfeeding"],
          ["34 weeks or more", "Direct breastfeeding", "Exclusive breastfeeding"],
        ],
      },
    ],
    redFlags: [
      "Temperature below 35.5 C or not rewarming with skin-to-skin contact.",
      "Apnoea, cyanosis, grunting or severe chest indrawing.",
      "Not feeding, vomiting, abdominal distension or bloody stools (suspect NEC).",
      "Lethargy, convulsions or movement only on stimulation.",
      "Jaundice in the first 24 hours or reaching the palms and soles.",
      "Blood glucose under 45 mg/dL that does not correct with a feed.",
      "Birth weight under 1800 g or gestation under 34 weeks at a facility without an SNCU.",
      "Failure to regain birth weight by 2 weeks or weight gain under 15 g/kg/day.",
    ],
    pearls: [
      "LBW is under 2500 g whatever the gestation; SGA is under the 10th centile for gestation; IUGR is a fetal process, not a birth weight.",
      "In India most LBW babies are term and growth restricted - maternal nutrition is the key intervention.",
      "WHO 2022: start kangaroo mother care immediately after birth for every baby under 2000 g, even before stability.",
      "The iKMC trial cut mortality by about a quarter in babies of 1000-1799 g.",
      "Suck-swallow coordination arrives at 32-34 weeks - that decides tube, cup or breast.",
      "Paladai feeding of expressed milk is the Indian answer for the 32-34 week baby.",
      "Hypothermia is a danger sign of sepsis in the newborn, not just a temperature.",
      "ROP screening in India: under 34 weeks or under 2000 g, first screen by day 30.",
      "SNCU admission threshold is birth weight under 1800 g.",
      "Growth and development of preterm babies are judged by corrected age until 2 years; vaccines go by chronological age.",
    ],
    mcqs: [
      {
        id: "pediatrics-low-birth-weight-preterm-kmc-q1",
        stem: "According to the WHO 2022 recommendations for care of the preterm or low birth weight infant, when should kangaroo mother care be started for a baby weighing 1600 g at birth?",
        options: [
          "Only after the baby has been clinically stable for 48 hours",
          "Only after the baby regains birth weight",
          "At discharge, as part of home care",
          "As soon as possible after birth, even before full stabilisation",
        ],
        answer: 3,
        explanation:
          "WHO 2022 recommends immediate KMC for all infants under 2000 g, started as soon as possible after birth including before stabilisation, based on the iKMC trial showing about 25 per cent lower mortality. Waiting for 48 hours of stability or for birth weight to be regained was the older practice and delays benefit; KMC begins in the facility, not only at discharge.",
        difficulty: "moderate",
      },
      {
        id: "pediatrics-low-birth-weight-preterm-kmc-q2",
        stem: "A baby born at 33 weeks weighing 1700 g is alert and pink on day 3 but has weak and uncoordinated sucking. What is the most appropriate method of feeding?",
        options: [
          "Expressed breast milk by paladai or cup",
          "Direct breastfeeding only",
          "Total parenteral nutrition",
          "Formula feeds by bottle",
        ],
        answer: 0,
        explanation:
          "Suck-swallow-breathe coordination matures at 32-34 weeks, so a stable baby of 32-33 weeks who cannot breastfeed effectively is fed expressed breast milk by paladai, cup or spoon. Direct breastfeeding alone will underfeed, parenteral nutrition is unnecessary in a stable baby, and bottles and formula displace breast milk and raise infection risk.",
        difficulty: "easy",
      },
      {
        id: "pediatrics-low-birth-weight-preterm-kmc-q3",
        stem: "A newborn's axillary temperature is 34.8 C. How is this classified by WHO?",
        options: [
          "Cold stress",
          "Moderate hypothermia",
          "Severe hypothermia",
          "Normal temperature for a low birth weight baby",
        ],
        answer: 1,
        explanation:
          "WHO grades newborn temperature as normal 36.5-37.5 C, cold stress 36.0-36.4 C, moderate hypothermia 32.0-35.9 C and severe hypothermia below 32 C, so 34.8 C is moderate hypothermia. It is too low to be cold stress, above the severe cut-off, and not normal for any newborn regardless of weight.",
        difficulty: "easy",
      },
      {
        id: "pediatrics-low-birth-weight-preterm-kmc-q4",
        stem: "Under the MoHFW guidelines, which baby must be screened for retinopathy of prematurity?",
        options: [
          "A 36-week, 2300 g baby with no oxygen exposure",
          "A term SGA baby weighing 2200 g",
          "A 33-week baby weighing 1900 g who never needed oxygen",
          "A 37-week baby of a diabetic mother weighing 3800 g",
        ],
        answer: 2,
        explanation:
          "Indian guidelines screen every baby under 34 weeks or under 2000 g for ROP, whether or not oxygen was given, so the 33-week 1900 g baby qualifies on both counts. The 36-week 2300 g baby qualifies only if there are risk factors such as oxygen or sepsis; term babies, SGA or macrosomic, are not routinely screened.",
        difficulty: "moderate",
      },
      {
        id: "pediatrics-low-birth-weight-preterm-kmc-q5",
        stem: "Which problem is characteristically more common in a term small-for-gestational-age baby than in an appropriately grown preterm baby of the same weight?",
        options: [
          "Respiratory distress syndrome",
          "Retinopathy of prematurity",
          "Intraventricular haemorrhage",
          "Polycythaemia",
        ],
        answer: 3,
        explanation:
          "Chronic intrauterine hypoxia in the growth-restricted fetus drives erythropoietin and produces polycythaemia, along with hypoglycaemia and meconium aspiration. Respiratory distress syndrome, retinopathy of prematurity and intraventricular haemorrhage are diseases of immaturity and are characteristic of the preterm baby instead.",
        difficulty: "moderate",
      },
    ],
    theory: [
      {
        id: "pediatrics-low-birth-weight-preterm-kmc-t1",
        paper: "IV",
        kind: "long",
        marks: 10,
        minutes: 18,
        frequency: "core",
        question:
          "Define low birth weight. Enumerate its causes. Discuss the problems and the management of a 1600 g preterm baby born at a CHC. [2+3+5]",
        openingLines: [
          "Low birth weight is a birth weight under 2500 g irrespective of gestation, from preterm birth, fetal growth restriction or both.",
          "About 18 per cent of Indian babies are LBW (NFHS-5), and prematurity and LBW are the leading cause of neonatal death in India.",
        ],
        answer: [
          {
            heading: "Definitions",
            points: [
              "LBW under 2500 g, VLBW under 1500 g, ELBW under 1000 g; preterm under 37 weeks; SGA under 10th centile.",
              "Symmetrical versus asymmetrical IUGR; ponderal index.",
            ],
          },
          {
            heading: "Causes",
            points: [
              "Preterm: previous preterm, multiple pregnancy, infection, PPROM, APH, pre-eclampsia, teenage pregnancy.",
              "IUGR: maternal undernutrition, anaemia, hypertension, tobacco, placental insufficiency, TORCH, chromosomal.",
            ],
          },
          {
            heading: "Problems",
            points: [
              "Hypothermia, hypoglycaemia, feeding difficulty, jaundice, sepsis, apnoea, RDS.",
              "Late: ROP, anaemia, metabolic bone disease, neurodevelopmental delay.",
            ],
          },
          {
            heading: "Management at the CHC (NBSU)",
            points: [
              "Warm chain: dry, skin-to-skin, cap and socks, delay bath; immediate KMC.",
              "Feeding: expressed breast milk by paladai or tube, 60-80 mL/kg/day increasing by 20-30 mL/kg/day.",
              "Glucose monitoring, vitamin K 1 mg IM (0.5 mg if under 1000 g), hepatitis B, BCG, OPV.",
              "Look for danger signs; refer to SNCU since birth weight under 1800 g - in KMC position with mother.",
            ],
          },
          {
            heading: "Follow-up and prevention",
            points: [
              "KMC at home, HBNC visits, weight gain 15-20 g/kg/day, ROP screen by day 30, vitamin D and iron.",
              "Prevention: maternal nutrition, ANC, spacing, anaemia control, delaying first pregnancy.",
            ],
          },
        ],
        mustDraw: ["Classification table of newborn by weight and gestation", "Kangaroo position diagram"],
        markSplit: [
          { part: "Definition", marks: 2 },
          { part: "Causes", marks: 3 },
          { part: "Problems and management", marks: 5 },
        ],
        keywords: ["low birth weight", "preterm", "IUGR", "KMC", "SNCU"],
      },
      {
        id: "pediatrics-low-birth-weight-preterm-kmc-t2",
        paper: "IV",
        kind: "short-note",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question: "Write a short note on kangaroo mother care: components, eligibility, technique and benefits. [2+2+3+3]",
        openingLines: [
          "Kangaroo mother care is continuous skin-to-skin contact between a mother and her small baby, with exclusive breastfeeding and early discharge with follow-up.",
          "WHO 2022 recommends it for every baby under 2000 g, started immediately after birth.",
        ],
        answer: [
          {
            heading: "Components",
            points: ["Skin-to-skin contact in kangaroo position; exclusive breastfeeding; early discharge and follow-up."],
          },
          {
            heading: "Eligibility",
            points: [
              "All babies under 2000 g - immediate KMC even if not yet stable (WHO 2022); older practice waited for stability.",
              "Provider: mother, father or family member.",
            ],
          },
          {
            heading: "Technique",
            points: [
              "Baby naked except nappy, cap and socks, upright between breasts, head to one side, frog position, secured with binder.",
              "At least 8 hours, ideally 20-24 hours a day; sessions of at least 1 hour; mother sleeps semi-reclined.",
              "Continue till 2500 g or 40 weeks, or baby wriggles out.",
            ],
          },
          {
            heading: "Benefits",
            points: [
              "Mortality reduced about 40 per cent in stable babies and 25 per cent with immediate KMC (iKMC trial).",
              "Less hypothermia and sepsis, better breastfeeding, weight gain, bonding, earlier discharge.",
            ],
          },
        ],
        mustDraw: ["Diagram of the kangaroo position"],
        markSplit: [
          { part: "Components", marks: 2 },
          { part: "Eligibility", marks: 2 },
          { part: "Technique", marks: 3 },
          { part: "Benefits", marks: 3 },
        ],
        keywords: ["kangaroo mother care", "iKMC", "skin-to-skin", "LBW"],
      },
    ],
    references: [
      "WHO recommendations for care of the preterm or low-birth-weight infant, 2022",
      "WHO Immediate KMC Study Group. Immediate kangaroo mother care and survival of infants with low birth weight. NEJM 2021",
      "Nelson Textbook of Pediatrics, 22nd edition (2024)",
      "National Family Health Survey (NFHS-5), 2019-21",
      "MoHFW Kangaroo Mother Care and Optimal Feeding of LBW Infants operational guidelines; Facility Based Newborn Care guidelines (2021 update)",
      "MoHFW Guidelines for Universal Eye Screening in Newborns including Retinopathy of Prematurity, 2018",
      "Park's Textbook of Preventive and Social Medicine, 28th edition",
      "WHO Born Too Soon: decade of action on preterm birth, 2023",
    ],
  },
  {
    id: "pediatrics-development-behaviour-scholastic",
    title: "Developmental milestones, delay, autism, ADHD and poor scholastic performance",
    oneLiner:
      "Development is the orderly acquisition of gross motor, fine motor, language and social skills in a fixed sequence at a variable rate; **delay in two or more domains under 5 years is global developmental delay**, any **loss of skills is regression**, and autism, ADHD, specific learning disability and intellectual disability are the neurodevelopmental disorders a family physician must screen for early and refer to the **DEIC under RBSK**.",
    frequency: "core",
    keywords: [
      "developmental milestones",
      "global developmental delay",
      "developmental regression",
      "TDSC",
      "Trivandrum Developmental Screening Chart",
      "DDST",
      "Denver",
      "M-CHAT-R/F",
      "INCLEN INDT-ASD",
      "autism spectrum disorder",
      "ADHD",
      "methylphenidate",
      "atomoxetine",
      "specific learning disability",
      "dyslexia",
      "intellectual disability",
      "scholastic backwardness",
      "breath-holding spells",
      "RBSK",
      "DEIC",
      "RPwD Act 2016",
    ],
    sections: [
      {
        heading: "Principles and rules of development",
        points: [
          "**Development is a continuous process** from conception to maturity, and each skill builds on those before it. [Nelson 22e]",
          "**The sequence is constant but the rate varies** between children - which is why milestones have a range and red flags have a limit age. [Nelson 22e]",
          "**Cephalocaudal direction:** head control precedes sitting, which precedes standing - control descends from head to foot. [Nelson 22e]",
          "**Proximodistal direction:** shoulder and trunk control come before the hand, and whole-hand grasp before the pincer grasp. [Nelson 22e]",
          "**Generalised mass activity is replaced by specific individual responses** - the newborn startles all over, the older infant reaches with one hand. [Nelson 22e]",
          "**Primitive reflexes must disappear before voluntary skills emerge** - a Moro or asymmetric tonic neck reflex persisting beyond 6 months is abnormal. [Nelson 22e]",
          "Development depends on **maturation of the nervous system and on stimulation** - deprivation, malnutrition and illness slow it even in a normal brain. [Nelson 22e]",
          "**Domains are interdependent:** a deaf child has delayed speech and then delayed social skills, so one delay can masquerade as another. [Nelson 22e]",
          "**Use corrected age for preterm babies until 2 years** - a 6-month-old born at 32 weeks is judged against 4-month milestones. [IAP 2024]",
          "**Developmental quotient (DQ) = developmental age / chronological age x 100**; a DQ under 70 in any domain is significant delay. [Nelson 22e]",
          "**Global developmental delay:** significant delay (2 SD or more below the mean) in two or more domains in a child **under 5 years**; after 5 years the term is intellectual disability. [DSM-5-TR 2022]",
        ],
      },
      {
        heading: "Key milestones and developmental red flags",
        points: [
          "**6 weeks:** social smile; **3 months:** neck holding, cooing, follows an object through 180 degrees, hands open. [Nelson 22e]",
          "**6 months:** sits with support (tripod), reaches and transfers objects, monosyllables (ba, da), recognises strangers. [Nelson 22e]",
          "**9 months:** sits without support, crawls, pulls to stand, immature pincer grasp, bisyllables (mama, dada), waves bye-bye. [Nelson 22e]",
          "**12 months:** stands and walks with or without support, mature pincer grasp, 1-2 meaningful words, object permanence, plays pat-a-cake. [Nelson 22e]",
          "**18 months:** runs stiffly, walks upstairs with hand held, tower of 3-4 cubes, scribbles, 10 or more words, points to body parts, feeds with spoon. [Nelson 22e]",
          "**2 years:** climbs stairs two feet per step, tower of 6-7 cubes, 2-word phrases with about 50 words, uses pronouns, parallel play. [Nelson 22e]",
          "**3 years:** rides a tricycle, climbs stairs with alternating feet, tower of 9 cubes, **copies a circle**, speaks in 3-word sentences, knows age and sex, group play. [Nelson 22e]",
          "**4 years:** hops on one foot, copies a cross and square, tells a story; **5 years:** skips, copies a triangle, dresses and undresses alone. [Nelson 22e]",
          "**Red flags - motor:** no head control by 4 months, not sitting without support by 9 months, not walking independently by 18 months. [IAP 2024]",
          "**Red flags - language and social:** no social smile by 3 months, no babbling or pointing by 12 months, no single words by 16 months, no 2-word phrases by 24 months. [IAP 2024]",
          "**Hand preference before 18 months** suggests a weak opposite limb (hemiparesis), and **persistent fisting beyond 3 months** suggests an upper motor neuron lesion. [Nelson 22e]",
          "**Any loss of previously acquired speech or social skills at any age** is regression and needs specialist referral the same week. [IAP 2024]",
          "**Parental concern about development is itself a red flag** - parents are right far more often than a single normal examination suggests. [AAP 2020]",
        ],
      },
      {
        heading: "Screening tools and causes of delay and regression",
        points: [
          "**Surveillance at every visit** plus a formal screening test at **9, 18 and 30 months**, and autism-specific screening at **18 and 24 months**. [AAP 2020]",
          "**Trivandrum Developmental Screening Chart (TDSC)** - an Indian tool for 0-2 years with 17 items drawn as bars; a child who fails an item lying fully to the left of the age line is referred. [IAP 2024]",
          "**Denver Developmental Screening Test II (DDST-II)** - 0-6 years, 125 items in personal-social, fine motor-adaptive, language and gross motor domains. [Nelson 22e]",
          "**M-CHAT-R/F** for autism at **16-30 months**: 20 parent questions; score 0-2 low risk, 3-7 needs the follow-up interview, 8 or more refer directly. [AAP 2020]",
          "**INCLEN Diagnostic Tools (INDT-ASD, INDT-ADHD)** are Indian, validated tools for 2-9 years that a trained primary care doctor can administer. [IAP 2024]",
          "Diagnostic assessment uses **DASII** (Indian adaptation of Bayley) for infants, **Vineland Social Maturity Scale** for adaptive function, and **Binet-Kamat or MISIC** for IQ. [IAP 2024]",
          "**Prenatal causes of delay:** Down syndrome, fragile X, other genetic syndromes, TORCH, teratogens, fetal alcohol and congenital hypothyroidism. [Nelson 22e]",
          "**Perinatal and postnatal causes:** birth asphyxia (HIE), prematurity, kernicterus, hypoglycaemia, meningitis, encephalitis, head injury, severe malnutrition, iodine and iron deficiency, lead and psychosocial deprivation. [Nelson 22e]",
          "**Isolated speech delay** needs a **formal hearing test** first; isolated motor delay suggests cerebral palsy or neuromuscular disease (check CK in boys). [Nelson 22e]",
          "**Causes of regression:** Rett syndrome (girls, hand-wringing, 6-18 months), autism regression, Landau-Kleffner syndrome, neurodegenerative disorders, SSPE, HIV encephalopathy and epileptic encephalopathies. [Nelson 22e]",
          "**Evaluation of global delay:** hearing and vision, thyroid function, chromosomal microarray and fragile X testing, and MRI or EEG when examination or history points there. [Nelson 22e]",
        ],
      },
      {
        heading: "Autism spectrum disorder",
        points: [
          "**DSM-5 ASD:** persistent deficits in **social communication and interaction** (all three - reciprocity, non-verbal communication, relationships) plus **restricted, repetitive behaviours** (at least two of four). [DSM-5-TR 2022]",
          "Restricted behaviours: **stereotyped movements or speech, insistence on sameness, fixated interests, and hyper- or hypo-reactivity to sensory input**. [DSM-5-TR 2022]",
          "Symptoms begin in the **early developmental period**, cause impairment and are graded by support needed into **levels 1, 2 and 3**. [DSM-5-TR 2022]",
          "Prevalence is about **1 in 100 Indian children aged 2-9 years**, with a **male to female ratio of about 4:1**. [INCLEN NDD 2018]",
          "**Early signs:** poor eye contact, no response to name by 12 months, no pointing or joint attention, no pretend play by 18 months, and loss of words. [AAP 2020]",
          "**Always test hearing** and examine for neurocutaneous markers, microcephaly and dysmorphism - fragile X and tuberous sclerosis are common associations. [Nelson 22e]",
          "**Early intensive behavioural intervention** - applied behaviour analysis, Early Start Denver Model and parent-mediated therapy - is the core treatment and works best before 3-4 years. [AAP 2020]",
          "Add **speech and language therapy, occupational therapy for sensory issues and special education** in an inclusive school. [AAP 2020]",
          "**Risperidone 0.25-0.5 mg daily, titrated to 1-3 mg**, or aripiprazole treats severe irritability and aggression, not the core social deficit; watch weight and metabolic profile. [Nelson 22e]",
          "**Melatonin 1-3 mg at bedtime** helps the common sleep-onset problem; **chelation, stem cell therapy and special diets have no evidence** and some are harmful. [AAP 2020]",
          "**ISAA (Indian Scale for Assessment of Autism)** is the tool used for disability certification of autism in India. [MoSJE 2016]",
        ],
      },
      {
        heading: "ADHD, specific learning disability and intellectual disability",
        points: [
          "**DSM-5 ADHD:** 6 or more symptoms of inattention and/or 6 or more of hyperactivity-impulsivity (5 from age 17) for **at least 6 months**, several present **before 12 years** and in **two or more settings**. [DSM-5-TR 2022]",
          "Presentations are **combined, predominantly inattentive and predominantly hyperactive-impulsive** - inattentive girls are the ones most often missed. [DSM-5-TR 2022]",
          "Use **Vanderbilt rating scales from both parent and teacher** - a diagnosis made from one setting alone does not meet criteria. [AAP ADHD 2019]",
          "**Under 6 years: parent training in behaviour management first**; methylphenidate only if significant impairment persists. [AAP ADHD 2019]",
          "**6 years and above: stimulant medication plus behavioural therapy and classroom interventions** - medication has the largest effect size. [AAP ADHD 2019]",
          "**Methylphenidate 5 mg twice daily** before breakfast and lunch, increased weekly by 5-10 mg to effect, **maximum 60 mg/day**; it is a Schedule X drug in India. [NICE NG87 2018]",
          "**Atomoxetine 0.5 mg/kg/day, increased after a week to 1.2 mg/kg/day**, is the non-stimulant option when tics, anxiety or misuse are concerns. [NICE NG87 2018]",
          "Monitor **height, weight, heart rate and blood pressure** on stimulants - appetite loss, insomnia and growth slowing are the common side effects. [NICE NG87 2018]",
          "**Specific learning disability:** dyslexia (reading), dysgraphia (writing) and dyscalculia (mathematics) in a child of normal intelligence, persisting 6 months despite targeted help. [DSM-5-TR 2022]",
          "SLD affects **about 5-15 per cent of school children**; assessment uses the **NIMHANS SLD battery**, and boards allow extra time, a scribe and exemption from a third language. [IAP 2024]",
          "**Intellectual disability:** deficits in intellectual function (IQ under about 70) and **adaptive function**, with onset in the developmental period; severity is graded by adaptive function. [DSM-5-TR 2022]",
          "**Borderline intellectual functioning (IQ 71-84)** is not a disability but explains many children who struggle despite effort - they need remedial support, not punishment. [Nelson 22e]",
        ],
      },
      {
        heading: "Poor scholastic performance: causes and evaluation",
        points: [
          "**Child factors:** SLD, ADHD, intellectual disability or borderline IQ, hearing or visual impairment, and chronic illness such as anaemia, epilepsy, asthma, hypothyroidism or malnutrition. [IAP 2024]",
          "**Other child factors:** absence seizures, obstructive sleep apnoea, sedating drugs (antiepileptics, antihistamines), depression, anxiety, substance use and abuse. [Nelson 22e]",
          "**Family factors:** poverty, parental discord, domestic violence, alcohol at home, first-generation learners and **mismatch between home language and medium of instruction**. [IAP 2024]",
          "**School factors:** poor teaching, overcrowded classes, bullying, frequent change of school and excessive academic pressure. [IAP 2024]",
          "**Timing matters:** difficulty since school entry suggests SLD, ADHD or low IQ; a **recent decline in a previously good student** suggests depression, abuse, substance use, bullying, absence epilepsy or family crisis. [Nelson 22e]",
          "**History:** pregnancy and birth, milestones, school reports, teacher's letter, which subjects fail, behaviour at home and school, sleep, screen time and HEADSS in adolescents. [IAP 2024]",
          "**Examination:** vision (Snellen), hearing, anaemia, thyroid, dysmorphism, neurocutaneous markers, soft neurological signs and **observation of reading and writing**. [IAP 2024]",
          "**Investigations are targeted:** haemoglobin, TSH, stool for ova, EEG for staring spells, then psychology referral for IQ, SLD battery and ADHD rating. [IAP 2024]",
          "**Management is multidisciplinary:** remedial education, board accommodations, treatment of ADHD or medical cause, counselling for the child, and advice to parents and teachers. [IAP 2024]",
        ],
      },
      {
        heading: "Breath-holding spells and other behaviour problems",
        points: [
          "**Breath-holding spells** occur between **6 months and 6 years** (peak 1-2 years) in about 5 per cent of children and stop by school age. [Nelson 22e]",
          "**Cyanotic spells** follow anger or frustration - a cry, apnoea in expiration, cyanosis, then limpness and sometimes brief jerks; **pallid spells** follow pain or fright and are vagal (reflex asystole). [Nelson 22e]",
          "The key to diagnosis is that **the provoking event comes first and cyanosis precedes loss of consciousness** - the reverse of an epileptic seizure. [Nelson 22e]",
          "**Oral iron 5 mg/kg/day for 3-4 months** reduces spells even in children without anaemia; get an **ECG in pallid or atypical spells** to exclude long QT syndrome. [Nelson 22e]",
          "Counsel parents: spells are **harmless, do not cause brain damage**, and should not be rewarded by giving in to the child afterwards. [Nelson 22e]",
          "**Temper tantrums** peak at 1-3 years - ignore the tantrum, keep the child safe, praise calm behaviour and keep limits consistent. [Nelson 22e]",
          "**Nocturnal enuresis** is a problem only after 5 years; first-line is an **enuresis alarm**, with **desmopressin 0.2-0.4 mg at bedtime** for short-term control. [NICE CG111 2017]",
          "**Night terrors, thumb sucking beyond 4 years, pica and excessive screen time** are managed by reassurance, behaviour change and screening for iron deficiency in pica. [Nelson 22e]",
        ],
      },
      {
        heading: "RBSK, DEIC, RPwD Act and supporting the family",
        points: [
          "**Rashtriya Bal Swasthya Karyakram (2013)** screens children 0-18 years for the **4 Ds - defects at birth, deficiencies, diseases and developmental delays including disability**. [RBSK MoHFW 2021]",
          "**Mobile health teams** screen children at Anganwadi centres **twice a year** and in schools **once a year**; newborns are screened at delivery points and by ASHAs at home. [RBSK MoHFW 2021]",
          "The **District Early Intervention Centre (DEIC)** has a paediatrician, physiotherapist, audiologist and speech therapist, psychologist, optometrist, special educator and social worker under one roof. [RBSK MoHFW 2021]",
          "The **RPwD Act 2016** lists 21 disabilities including **autism, intellectual disability, SLD and cerebral palsy**; a benchmark disability is 40 per cent or more. [RPwD Act 2016]",
          "RPwD benefits: **free education from 6-18 years**, inclusive education, **5 per cent reservation in higher education** and 4 per cent in government posts, and the **UDID card**. [RPwD Act 2016]",
          "The **National Trust Act 1999** offers **Niramaya health insurance** and legal guardianship for adults with autism, CP, intellectual and multiple disabilities. [National Trust Act 1999]",
          "**Break the news with hope and a plan** - name the diagnosis, explain what the child can do, and give the next appointment before the family leaves. [IAP 2024]",
          "**Parent training is therapy** - parents deliver most of the hours of intervention a child receives, so teach them the home programme. [AAP 2020]",
          "Watch for **caregiver depression, sibling neglect and marital strain**, and connect families with support groups and respite care. [Nelson 22e]",
          "Warn families against **unproven costly cures** (stem cells, chelation) and help them obtain the disability certificate and school accommodations. [IAP 2024]",
        ],
      },
    ],
    tables: [
      {
        heading: "Key developmental milestones by age",
        columns: ["Age", "Gross motor", "Fine motor", "Language", "Social"],
        rows: [
          ["3 months", "Neck holding", "Hands open, follows 180 degrees", "Cooing", "Social smile (6 weeks), recognises mother"],
          ["6 months", "Sits with support", "Reaches, transfers objects", "Monosyllables", "Stranger anxiety begins"],
          ["9 months", "Sits alone, crawls, pulls to stand", "Immature pincer grasp", "Bisyllables (mama)", "Waves bye-bye"],
          ["12 months", "Walks with or without support", "Mature pincer grasp", "1-2 words with meaning", "Object permanence, pat-a-cake"],
          ["18 months", "Runs stiffly", "Tower of 3-4, scribbles", "10 or more words", "Points to body parts, uses spoon"],
          ["2 years", "Stairs two feet per step", "Tower of 6-7, vertical stroke", "2-word phrases, pronouns", "Parallel play"],
          ["3 years", "Tricycle, alternate feet upstairs", "Tower of 9, copies circle", "3-word sentences", "Knows age and sex, group play"],
          ["4-5 years", "Hops (4), skips (5)", "Cross, square (4); triangle (5)", "Tells a story", "Cooperative play, dresses alone"],
        ],
      },
      {
        heading: "Developmental screening tools - types",
        columns: ["Tool", "Age", "Purpose"],
        rows: [
          ["TDSC", "0-2 years (0-6 version exists)", "Quick Indian screening chart, 17 items"],
          ["DDST-II", "0-6 years", "Four-domain screening, 125 items"],
          ["M-CHAT-R/F", "16-30 months", "Autism-specific screening, 20 items"],
          ["INDT-ASD / INDT-ADHD", "2-9 years", "Indian diagnostic tools for autism and ADHD"],
          ["Vanderbilt scales", "6-12 years", "Parent and teacher ADHD rating"],
        ],
      },
      {
        heading: "Cyanotic versus pallid breath-holding spell versus seizure",
        columns: ["Feature", "Cyanotic spell", "Pallid spell", "Epileptic seizure"],
        rows: [
          ["Trigger", "Anger, frustration", "Pain, sudden fright", "Usually none"],
          ["Sequence", "Cry, apnoea, cyanosis, limp", "Silent, pale, limp", "Loss of consciousness first"],
          ["Mechanism", "Expiratory apnoea, hypoxia", "Vagal bradycardia or asystole", "Cortical discharge"],
          ["Post-event", "Brief, back to normal", "Brief, may sleep", "Post-ictal drowsiness"],
          ["Action", "Reassure, oral iron", "ECG, oral iron", "EEG, antiseizure drug"],
        ],
      },
    ],
    redFlags: [
      "Any loss of previously acquired language, motor or social skills (regression) at any age.",
      "No babbling, pointing or response to name by 12 months, or no words by 16 months.",
      "Not sitting without support by 9 months or not walking by 18 months.",
      "Hand preference before 18 months or asymmetry of tone or movement.",
      "Abnormal head size (microcephaly or rapidly enlarging head) with delay.",
      "Staring spells in a child with falling school performance - suspect absence epilepsy.",
      "Sudden decline in school performance with withdrawal, self-harm talk or signs of abuse.",
      "Pallid breath-holding spells with exertion-related syncope or a family history of sudden death - check for long QT.",
    ],
    pearls: [
      "Sequence of development is constant; the rate varies - hence limit ages, not average ages, define red flags.",
      "Development proceeds cephalocaudally and proximodistally.",
      "Use corrected age for preterm babies until 2 years.",
      "Global developmental delay is a diagnosis under 5 years; intellectual disability after 5.",
      "Isolated speech delay - test hearing first.",
      "Hand preference before 18 months is abnormal.",
      "M-CHAT-R/F at 18 and 24 months; TDSC is the Indian 0-2 year screening chart.",
      "ADHD needs symptoms in two settings, before 12 years, for at least 6 months.",
      "In breath-holding spells, the trigger comes first and cyanosis precedes unconsciousness; oral iron helps even without anaemia.",
      "A recent decline in a good student is depression, abuse, drugs, bullying or absences until proved otherwise.",
      "RBSK 4 Ds and the DEIC are the government's early intervention pathway; RPwD Act 2016 lists autism and SLD among 21 disabilities.",
    ],
    mcqs: [
      {
        id: "pediatrics-development-behaviour-scholastic-q1",
        stem: "A child rides a tricycle, climbs stairs with alternating feet, copies a circle but not a cross, and speaks in 3-word sentences. What is the most likely developmental age?",
        options: ["18 months", "2 years", "3 years", "5 years"],
        answer: 2,
        explanation:
          "Riding a tricycle, alternating feet on stairs, copying a circle and 3-word sentences are all 3-year milestones. An 18-month-old only scribbles and walks upstairs with help, a 2-year-old uses 2-word phrases and imitates a stroke, and a 5-year-old copies a triangle and skips.",
        difficulty: "easy",
      },
      {
        id: "pediatrics-development-behaviour-scholastic-q2",
        stem: "An 8-year-old boy is reported by his teacher to be restless and inattentive in class. His parents say he is calm and focused at home. Which DSM-5 requirement for ADHD is NOT met?",
        options: [
          "Onset of several symptoms before 12 years",
          "Symptoms present in two or more settings",
          "Duration of at least 6 months",
          "At least 6 symptoms in one domain",
        ],
        answer: 1,
        explanation:
          "DSM-5 requires ADHD symptoms to be present in two or more settings, such as home and school; symptoms only at school suggest a learning, classroom or emotional problem instead. Onset before 12 years, 6-month duration and 6 symptoms per domain are also criteria, but the vignette does not show them to be missing.",
        difficulty: "moderate",
      },
      {
        id: "pediatrics-development-behaviour-scholastic-q3",
        stem: "An 18-month-old girl cries when prevented from taking a toy, stops breathing, turns blue and goes limp for a few seconds before recovering fully. Examination is normal. Which treatment has been shown to reduce the frequency of these episodes?",
        options: [
          "Oral sodium valproate",
          "Oral iron supplementation",
          "Oral propranolol",
          "Oral clobazam at bedtime",
        ],
        answer: 1,
        explanation:
          "This is a cyanotic breath-holding spell - trigger first, then apnoea and cyanosis before loss of tone. Oral iron (about 5 mg/kg/day) reduces spells even without anaemia. Valproate and clobazam are antiseizure drugs with no role in a non-epileptic event, and propranolol is not used.",
        difficulty: "moderate",
      },
      {
        id: "pediatrics-development-behaviour-scholastic-q4",
        stem: "For which age group is the M-CHAT-R/F autism screening tool validated?",
        options: ["6-12 months", "3-6 years", "6-12 years", "16-30 months"],
        answer: 3,
        explanation:
          "M-CHAT-R/F is a 20-item parent questionnaire for toddlers of 16-30 months and is used at the 18- and 24-month visits recommended by AAP. It is not validated in infants under 16 months, and older children are assessed with other tools such as INDT-ASD for 2-9 years.",
        difficulty: "easy",
      },
      {
        id: "pediatrics-development-behaviour-scholastic-q5",
        stem: "A 13-year-old girl who was among the top students has had falling marks for 4 months, with withdrawal from friends and poor sleep. Vision and hearing are normal. What is the most likely underlying cause to evaluate first?",
        options: [
          "Depression or a psychosocial stressor",
          "Specific learning disability",
          "Intellectual disability",
          "Congenital hypothyroidism",
        ],
        answer: 0,
        explanation:
          "A recent decline in a previously good student with withdrawal and sleep disturbance points to depression, abuse, bullying, substance use or family crisis, explored by HEADSS. Specific learning disability and intellectual disability show difficulty from school entry, not a fall after years of success, and congenital hypothyroidism presents in infancy.",
        difficulty: "moderate",
      },
    ],
    theory: [
      {
        id: "pediatrics-development-behaviour-scholastic-t1",
        paper: "IV",
        kind: "long",
        marks: 10,
        minutes: 18,
        frequency: "core",
        question:
          "Describe the principles of development. List the milestones of a 3-year-old child and the developmental red flags. How will you screen for autism in primary care? [3+3+4]",
        openingLines: [
          "Development is the orderly acquisition of motor, language and social skills that follows a constant sequence at a variable rate.",
          "About 1 in 8 Indian children aged 2-9 years has a neurodevelopmental disorder, and early identification through RBSK changes outcome.",
        ],
        answer: [
          {
            heading: "Principles",
            points: [
              "Continuous; constant sequence, variable rate; cephalocaudal and proximodistal; general to specific.",
              "Primitive reflexes disappear before voluntary skills; depends on maturation and stimulation; domains interdependent; corrected age for preterm.",
            ],
          },
          {
            heading: "Milestones at 3 years",
            points: [
              "Gross motor: tricycle, alternate feet upstairs, jumps. Fine motor: tower of 9, copies circle.",
              "Language: 3-word sentences, knows name, age and sex. Social: group play, shares, partially dresses.",
            ],
          },
          {
            heading: "Red flags",
            points: [
              "No head control 4 months, no sitting 9 months, no walking 18 months.",
              "No babbling or pointing 12 months, no words 16 months, no 2-word phrases 24 months.",
              "Any regression, hand preference before 18 months, parental concern.",
            ],
          },
          {
            heading: "Autism screening",
            points: [
              "Surveillance for early signs: eye contact, response to name, joint attention, pretend play.",
              "M-CHAT-R/F at 18 and 24 months: 0-2 low, 3-7 follow-up interview, 8 or more refer.",
              "INDT-ASD for 2-9 years; hearing test; refer to DEIC; start early intervention without waiting for a label.",
            ],
          },
        ],
        mustDraw: ["Milestone table by domain at key ages", "TDSC chart layout with age line"],
        markSplit: [
          { part: "Principles", marks: 3 },
          { part: "Milestones and red flags", marks: 3 },
          { part: "Autism screening", marks: 4 },
        ],
        keywords: ["principles of development", "milestones", "red flags", "M-CHAT", "autism"],
      },
      {
        id: "pediatrics-development-behaviour-scholastic-t2",
        paper: "IV",
        kind: "long",
        marks: 10,
        minutes: 18,
        frequency: "core",
        question:
          "A 10-year-old boy is brought with poor scholastic performance. Enumerate the causes. Outline the evaluation and management. [3+4+3]",
        openingLines: [
          "Poor scholastic performance is academic achievement below that expected for the child's age, ability and schooling, and is a symptom rather than a diagnosis.",
          "Its causes lie in the child, the family and the school, and SLD and ADHD together account for a large share.",
        ],
        answer: [
          {
            heading: "Causes",
            points: [
              "Child: SLD, ADHD, borderline IQ or intellectual disability, hearing or vision defect, chronic illness, epilepsy, sleep apnoea, drugs, depression, substance use.",
              "Family: poverty, discord, abuse, language mismatch. School: teaching quality, bullying, pressure.",
            ],
          },
          {
            heading: "Evaluation",
            points: [
              "History: onset (since start vs recent decline), subjects affected, behaviour at home and school, teacher report, milestones, sleep, screen time.",
              "Examination: vision, hearing, anaemia, thyroid, neurocutaneous markers, soft signs, reading and writing sample.",
              "Tests: Hb, TSH, EEG if staring spells; IQ, NIMHANS SLD battery, Vanderbilt scales.",
            ],
          },
          {
            heading: "Management",
            points: [
              "Treat medical cause; remedial education and board accommodations for SLD; methylphenidate plus behaviour therapy for ADHD.",
              "Counselling of child and parents; teacher liaison; certification under RPwD Act 2016; follow-up.",
            ],
          },
        ],
        mustDraw: ["Flow chart of evaluation of poor scholastic performance"],
        markSplit: [
          { part: "Causes", marks: 3 },
          { part: "Evaluation", marks: 4 },
          { part: "Management", marks: 3 },
        ],
        keywords: ["poor scholastic performance", "SLD", "ADHD", "dyslexia", "school failure"],
      },
    ],
    references: [
      "Nelson Textbook of Pediatrics, 22nd edition (2024)",
      "American Psychiatric Association. DSM-5-TR, 2022",
      "AAP Clinical Report: Identification, Evaluation and Management of Children with Autism Spectrum Disorder, 2020",
      "AAP Clinical Practice Guideline for ADHD, 2019",
      "NICE NG87 Attention deficit hyperactivity disorder: diagnosis and management, 2018 (updated 2019)",
      "MoHFW Rashtriya Bal Swasthya Karyakram operational guidelines, 2021",
      "Rights of Persons with Disabilities Act, 2016",
      "INCLEN Study Group. Prevalence of neurodevelopmental disorders in Indian children aged 2-9 years. PLoS Medicine 2018",
    ],
  },
];

export default topics;
