import type { Topic } from "../../lib/types";

const topics: Topic[] = [
  {
    id: "renal-urology-urinary-incontinence",
    title: "Urinary incontinence in women and the elderly",
    oneLiner:
      "Urinary incontinence is any involuntary leakage of urine - **stress** (on effort, from urethral sphincter and pelvic floor weakness), **urge** (with urgency, from detrusor overactivity), **mixed, overflow** (from retention), **functional** or **continuous** (fistula); after screening for reversible causes (**DIAPPERS**), a bladder diary, cough test and post-void residual, most women improve with **pelvic floor muscle training, bladder training** and, for urgency, **antimuscarinics or mirabegron**, while surgery (**midurethral sling**) is reserved for stress incontinence that fails conservative care.",
    frequency: "common",
    keywords: [
      "urinary incontinence",
      "stress urinary incontinence",
      "SUI",
      "urge incontinence",
      "overactive bladder",
      "OAB",
      "mixed incontinence",
      "overflow incontinence",
      "DIAPPERS",
      "bladder diary",
      "pelvic floor muscle training",
      "Kegel exercises",
      "solifenacin",
      "oxybutynin",
      "mirabegron",
      "TVT TOT midurethral sling",
      "ring pessary",
      "vesicovaginal fistula",
      "post-void residual",
      "urodynamics",
    ],
    sections: [
      {
        heading: "Definitions and types",
        points: [
          "**Urinary incontinence (UI)** is the complaint of **any involuntary loss of urine**. [EAU 2024]",
          "**Stress urinary incontinence (SUI)** - leakage on **effort or exertion, sneezing or coughing**, due to **urethral hypermobility or intrinsic sphincter deficiency**. [EAU 2024]",
          "**Urgency urinary incontinence (UUI)** - leakage **accompanied or immediately preceded by urgency**, usually from **detrusor overactivity**. [EAU 2024]",
          "**Overactive bladder (OAB)** syndrome - **urgency, with or without urgency incontinence, usually with frequency and nocturia**, in the absence of UTI or other obvious pathology; 'OAB wet' includes UUI. [EAU 2024]",
          "**Mixed urinary incontinence** - both stress and urgency leakage; treat the **predominant** component first. [NICE NG123 2019]",
          "**Overflow incontinence** - dribbling from a **chronically overdistended bladder** due to **outlet obstruction** (BPH, stricture, prolapse, faecal impaction) or **detrusor underactivity** (diabetes, spinal injury, anticholinergic drugs). [Campbell 13e]",
          "**Functional incontinence** - the lower urinary tract is normal but **cognitive impairment, immobility or environmental barriers** prevent reaching the toilet in time. [Harrison 22e]",
          "**Continuous incontinence** - leakage day and night with little normal voiding suggests **vesicovaginal or ureterovaginal fistula** or an **ectopic ureter** (in girls who are 'always damp'). [Campbell 13e]",
          "**Post-micturition dribble** in men is urine pooled in the bulbar urethra after voiding, and is relieved by **urethral milking**; it is not true incontinence. [Campbell 13e]",
          "**Nocturnal enuresis** is involuntary voiding during sleep; **nocturia** is waking to void one or more times at night. [EAU 2024]",
        ],
      },
      {
        heading: "Burden and aetiology by age and sex",
        points: [
          "UI affects about **25-45 per cent of adult women** worldwide; Indian community studies report prevalence of about **15-30 per cent in women**, with SUI the commonest type in younger women. [EAU 2024]",
          "Prevalence rises with age - **about 1 in 3 people over 65** and **over half of nursing-home residents** - and **urgency and mixed** types predominate in the elderly. [Harrison 22e]",
          "Most Indian women **never seek care** because of embarrassment, the belief that leakage is normal after childbirth or ageing, and lack of privacy in clinics. [Park 28e]",
          "**Pregnancy and vaginal delivery** (especially forceps, prolonged second stage and large babies) damage the **pelvic floor, pudendal nerve and urethral supports**; parity is the strongest risk factor for SUI. [Berek and Novak 16e]",
          "Other female risk factors: **obesity, menopause (urogenital atrophy), pelvic organ prolapse, chronic cough (COPD, TB), chronic constipation, heavy lifting, hysterectomy and pelvic radiotherapy**. [NICE NG123 2019]",
          "In **men**, incontinence usually follows **radical prostatectomy or TURP** (stress), or accompanies **BPH** with OAB or overflow. [Campbell 13e]",
          "In the **elderly**, **detrusor overactivity with impaired contractility (DHIC)** gives urgency with a raised residual, and **dementia, stroke, Parkinson disease, diabetes and polypharmacy** add to it. [Harrison 22e]",
          "**Neurogenic bladder** follows spinal cord injury, multiple sclerosis, spina bifida and diabetic autonomic neuropathy. [Campbell 13e]",
          "UI causes **social isolation, depression, sexual dysfunction, skin breakdown, falls and fractures** (rushing to the toilet at night) and is a leading reason for **institutionalisation** of the elderly. [Harrison 22e]",
        ],
      },
      {
        heading: "Reversible causes (DIAPPERS) and assessment",
        points: [
          "**D - Delirium**: acute confusion from any cause produces incontinence that resolves as the delirium clears. [Harrison 22e]",
          "**I - Infection**: symptomatic **UTI** causes urgency and leakage - but **asymptomatic bacteriuria in the elderly should not be treated**. [Harrison 22e]",
          "**A - Atrophic urethritis and vaginitis**: post-menopausal urogenital atrophy aggravates urgency and SUI and responds to **vaginal oestrogen**. [NICE NG123 2019]",
          "**P - Pharmaceuticals**: **diuretics, alpha-blockers (in women), anticholinergics, opioids, sedatives, calcium-channel blockers (oedema), ACE-inhibitor cough, gabapentinoids**, and alcohol and caffeine. [Harrison 22e]",
          "**P - Psychological**: severe depression and reduced motivation. [Harrison 22e]",
          "**E - Excess urine output**: **hyperglycaemia, hypercalcaemia**, heavy fluid intake, and **nocturnal mobilisation of oedema** in heart failure or venous insufficiency. [Harrison 22e]",
          "**R - Restricted mobility**: arthritis, stroke, fear of falling, bed rails and distant toilets. [Harrison 22e]",
          "**S - Stool impaction**: constipation obstructs the urethra and increases urgency - do a **rectal examination**. [Harrison 22e]",
          "**History**: type of leakage (cough and sneeze vs rushing), **frequency, nocturia, pad use**, voiding symptoms, **haematuria, pain**, obstetric and surgical history, neurological symptoms, bowel habit, drugs, fluid and caffeine intake, and effect on quality of life. [NICE NG123 2019]",
          "Ask for a **bladder diary (frequency-volume chart) for at least 3 days** covering work and leisure days - it shows voided volumes, frequency, fluid intake and **nocturnal polyuria** (over 33 per cent of 24-hour urine at night in older adults). [NICE NG123 2019]",
          "Use validated questionnaires such as the **ICIQ-UI Short Form** (score 0-21) to grade severity and measure response to treatment. [NICE NG123 2019]",
        ],
      },
      {
        heading: "Examination and investigations",
        points: [
          "**General**: BMI, cognition (MMSE or Mini-Cog), **mobility and dexterity**, oedema, and an **abdominal examination for a palpable bladder**. [Harrison 22e]",
          "**Pelvic examination**: **vaginal atrophy, pelvic organ prolapse** (POP-Q staging), masses, **pelvic floor muscle strength** (Modified Oxford scale 0-5) and **excoriation** of the vulva. [NICE NG123 2019]",
          "**Cough stress test**: with a comfortably full bladder, ask the woman to cough in lithotomy then standing - **leakage simultaneous with the cough** confirms SUI; **delayed leakage** suggests cough-induced detrusor overactivity. [Berek and Novak 16e]",
          "**Neurological**: **perineal (S2-S4) sensation, anal tone, bulbocavernosus reflex** and lower-limb reflexes; in men, **DRE** for prostate size and faecal impaction. [Campbell 13e]",
          "**Post-void residual (PVR)** by **bladder scanner or ultrasound** (or in-out catheter) - under 50 mL is normal, **over 100-150 mL is significant** in the elderly, and **over 200 mL** suggests retention needing referral. [NICE NG123 2019]",
          "**Urine dipstick** in every patient - leucocytes and nitrites (UTI), **blood (haematuria needs referral)**, glucose and protein; send **culture** only if symptomatic. [NICE NG123 2019]",
          "**Renal function and ultrasound KUB** when there is retention, recurrent UTI or suspected upper-tract damage. [Campbell 13e]",
          "**Urodynamics are not needed** before conservative treatment, or before surgery in women with **clearly defined pure SUI**. [NICE NG123 2019]",
          "Do urodynamics before surgery when **OAB is predominant or the type is unclear**, there are **voiding symptoms or a raised PVR**, **anterior or apical prolapse**, or **previous continence surgery**, and in **neurogenic** bladder. [NICE NG123 2019]",
          "**Cystoscopy** for **haematuria, bladder pain, recurrent UTI, suspected fistula or mesh complication**. [NICE NG123 2019]",
          "Suspected fistula: **methylene blue three-swab (dye) test** - a blue swab means **VVF**; a wet but unstained swab suggests a **ureterovaginal fistula**, confirmed by **CT urography**. [Campbell 13e]",
        ],
      },
      {
        heading: "Conservative treatment: lifestyle, PFMT and bladder training",
        points: [
          "**Lifestyle**: **weight loss if BMI over 30** (5-10 per cent loss halves leakage), **reduce caffeine**, keep fluid at about **1.5-2 L a day** (neither excessive nor restricted), stop smoking and treat **constipation and chronic cough**. [NICE NG123 2019]",
          "**Pelvic floor muscle training (PFMT)** is **first-line for SUI and mixed UI**: a **supervised programme of at least 3 months**, with **at least 8 contractions, 3 times a day**. [NICE NG123 2019]",
          "Teach PFMT by vaginal examination - 'squeeze and lift as if stopping urine and wind' - and teach **'the knack'**: contract the pelvic floor just before a cough or lift. [NICE NG123 2019]",
          "PFMT **during first pregnancy** reduces postnatal incontinence and should be offered at antenatal visits. [NICE NG123 2019]",
          "**Bladder training** for **at least 6 weeks** is first-line for **urgency or mixed UI** - scheduled voiding with gradual lengthening of the interval, plus urge-suppression (stand still, squeeze the pelvic floor, then walk calmly). [NICE NG123 2019]",
          "**Timed voiding and prompted voiding** (every 2-3 hours) are the mainstay for **functional incontinence** in people with dementia or immobility, supported by carers. [Harrison 22e]",
          "Improve **access**: bedside commode, urinal, raised toilet seat, grab rails, night lights and clothing that is easy to remove. [Harrison 22e]",
          "**Vaginal oestrogen** (estriol 0.1 per cent cream or conjugated oestrogen 0.5 g **twice weekly** after an initial 2 weeks daily) for post-menopausal women with OAB symptoms and atrophy; **systemic HRT does not help UI**. [NICE NG123 2019]",
        ],
      },
      {
        heading: "Drug treatment and cautions in the elderly",
        points: [
          "**Antimuscarinics** for OAB after bladder training fails: **solifenacin 5 mg once daily (up to 10 mg)**, **tolterodine 2 mg twice daily or 4 mg ER once daily**, **trospium 20 mg twice daily**, **darifenacin 7.5-15 mg** or **fesoterodine 4-8 mg once daily**. [NICE NG123 2019]",
          "**Oxybutynin IR 2.5-5 mg two to three times daily** is cheap but has the most side effects - **avoid it in frail older women**. [NICE NG123 2019]",
          "Antimuscarinic side effects: **dry mouth, constipation, blurred vision, urinary retention, tachycardia and cognitive impairment**; contraindicated in **uncontrolled narrow-angle glaucoma, myasthenia gravis, urinary retention and severe GI obstruction**. [Harrison 22e]",
          "Cumulative **anticholinergic burden** is associated with **cognitive decline and dementia** - calculate an ACB score and prefer non-anticholinergic options in older adults. [AGS Beers Criteria 2023]",
          "**Mirabegron 25-50 mg once daily** (beta-3 agonist) avoids anticholinergic effects and is preferred in the **elderly or cognitively impaired**; check **BP** and avoid in **uncontrolled hypertension (180/110 or more)**. [EAU 2024]",
          "**Vibegron 75 mg once daily** is a newer beta-3 agonist with no BP-monitoring requirement, available in some markets. [AUA/SUFU OAB 2024]",
          "**Review drug response at 4 weeks** and switch agent if ineffective or not tolerated; many women stop antimuscarinics within a year because of side effects. [NICE NG123 2019]",
          "**Duloxetine 40 mg twice daily** is only a **second-line option for SUI** in women who decline or are unfit for surgery, because nausea is common. [NICE NG123 2019]",
          "**Desmopressin** for nocturnal polyuria is used cautiously - **avoid over 65 years** with cardiovascular disease or hyponatraemia risk, and **check sodium** within 3-7 days. [EAU 2024]",
          "**Men with BPH and voiding symptoms**: **tamsulosin 0.4 mg once daily**, adding an antimuscarinic or mirabegron for persistent OAB only if the **PVR is low**. [EAU 2025]",
          "**Refractory OAB**: **intravesical onabotulinumtoxinA 100 units** (patient must accept possible **clean intermittent self-catheterisation**), **percutaneous tibial nerve stimulation** or **sacral neuromodulation**. [NICE NG123 2019]",
        ],
      },
      {
        heading: "Pessaries, surgery and catheter, pad and skin care",
        points: [
          "**Vaginal pessaries** (ring, ring with knob, Gellhorn) manage **prolapse with incontinence** and suit women who are unfit for or wish to avoid surgery; review and clean or change every **3-6 months**, with vaginal oestrogen to prevent erosion. [NICE NG123 2019]",
          "**Surgery for SUI** is offered when **supervised PFMT fails** and the woman is bothered - options are a **retropubic midurethral mesh sling (TVT)**, **transobturator tape (TOT)**, **Burch colposuspension**, **autologous rectus fascial sling** or **urethral bulking agents**. [NICE NG123 2019]",
          "Midurethral slings achieve **80-90 per cent subjective cure**, but consent must cover **mesh exposure, chronic pain, dyspareunia, voiding dysfunction and difficulty of removal**; TOT has more groin pain, TVT more bladder perforation. [NICE NG123 2019]",
          "Men with post-prostatectomy SUI may need a **male sling or artificial urinary sphincter**. [EAU 2025]",
          "**Indwelling catheters** are a last resort - for **retention that cannot be managed otherwise, non-healing sacral wounds, or terminal care**; **clean intermittent self-catheterisation** is preferred for chronic retention. [NICE NG123 2019]",
          "Catheter care: **closed drainage, bag below bladder level, daily meatal washing with water, no routine bladder washouts or antibiotic prophylaxis**, and change as per material (**silicone up to 12 weeks**); **suprapubic** catheters suit long-term use. [Campbell 13e]",
          "**Do not treat asymptomatic bacteriuria** in catheterised patients; treat CAUTI only with fever, loin pain or delirium, and **change the catheter before taking the sample**. [Harrison 22e]",
          "**Absorbent pads** and **external condom catheters (men)** are for containment while treatment works or when it fails, not a substitute for assessment. [NICE NG123 2019]",
          "**Incontinence-associated dermatitis**: cleanse with a **pH-balanced no-rinse cleanser**, pat dry, apply a **barrier cream (zinc oxide, dimethicone or cyanoacrylate film)**, change pads promptly, avoid soap and friction, and treat candida with **topical clotrimazole**. [Rook 10e]",
          "Reposition and inspect skin to **prevent pressure ulcers**, and teach carers how to protect dignity and privacy during toileting. [Harrison 22e]",
        ],
      },
      {
        heading: "Vesicovaginal fistula in India and referral",
        points: [
          "**Obstetric fistula** follows **prolonged obstructed labour**, when the fetal head compresses the bladder base against the pubis and causes **ischaemic necrosis**; it presents with **continuous leakage 3-10 days after delivery**, often with a stillbirth. [Williams 26e]",
          "In India, obstetric fistula has declined with institutional delivery (**over 88 per cent, NFHS-5**), and **iatrogenic fistulas after hysterectomy and caesarean section** now form a growing share. [NFHS-5]",
          "Women with fistula suffer **perineal excoriation, recurrent infection, amenorrhoea, infertility, foot drop (obstetric palsy), divorce and social exclusion**. [Williams 26e]",
          "A **fresh small fistula** may heal with **continuous bladder drainage for 2-4 weeks**; after obstructed labour, WHO recommends an **indwelling catheter for 14 days** as prevention. [Williams 26e]",
          "Definitive repair is by a **trained fistula surgeon**, usually by the **vaginal route** (layered closure, Latzko technique, **Martius flap** if tissue is poor) or **abdominal route** (O'Conor) for high or complex fistulas; first-attempt closure is about **85-90 per cent**. [Campbell 13e]",
          "**Prevention**: antenatal care, birth preparedness, **WHO Labour Care Guide**, timely caesarean for obstructed labour, and careful bladder dissection at pelvic surgery. [WHO 2020 LCG]",
          "**Refer** UI with **haematuria, recurrent UTI, bladder or pelvic pain, palpable bladder or PVR over 200 mL, suspected fistula, neurological disease, prolapse beyond the introitus**, previous continence surgery or pelvic radiotherapy, or suspected malignancy. [NICE NG123 2019]",
          "**Refer** women who fail **3 months of PFMT** and wish to consider surgery, and those with OAB not responding to two drugs. [NICE NG123 2019]",
          "**Refer men** with incontinence and **voiding symptoms, raised PVR, abnormal DRE or raised PSA** to urology. [EAU 2025]",
          "**Family physician role**: **ask about leakage routinely** (women after childbirth, menopause, elderly), treat DIAPPERS causes, start PFMT and bladder training, rationalise drugs, and support carers - most UI can be improved in primary care. [NICE NG123 2019]",
        ],
      },
    ],
    tables: [
      {
        heading: "Types of urinary incontinence - classification",
        columns: ["Type", "Mechanism", "Typical patient", "First-line treatment"],
        rows: [
          ["Stress", "Urethral hypermobility or sphincter deficiency", "Multiparous or obese woman; post-prostatectomy man", "PFMT 3 months; sling if fails"],
          ["Urgency (OAB wet)", "Detrusor overactivity", "Older woman or man; neurological disease", "Bladder training; antimuscarinic or mirabegron"],
          ["Mixed", "Both", "Middle-aged or older woman", "Treat predominant type first"],
          ["Overflow", "Retention - obstruction or underactive detrusor", "Man with BPH; diabetic; drugs", "Treat cause; CISC; alpha-blocker"],
          ["Functional", "Cognitive or mobility barrier", "Frail elderly with dementia", "Prompted and timed voiding, access aids"],
          ["Continuous", "Fistula or ectopic ureter", "Woman after obstructed labour or hysterectomy", "Refer for repair"],
        ],
      },
      {
        heading: "Reversible causes of incontinence - DIAPPERS",
        columns: ["Letter", "Cause", "Action"],
        rows: [
          ["D", "Delirium", "Treat underlying cause"],
          ["I", "Infection (symptomatic UTI)", "Treat; do not treat asymptomatic bacteriuria"],
          ["A", "Atrophic urethritis or vaginitis", "Vaginal oestrogen"],
          ["P", "Pharmaceuticals", "Review diuretics, sedatives, anticholinergics, alpha-blockers"],
          ["P", "Psychological (depression)", "Treat depression"],
          ["E", "Excess urine output", "Control glucose, calcium, fluids, oedema"],
          ["R", "Restricted mobility", "Commode, urinal, physiotherapy"],
          ["S", "Stool impaction", "Disimpact, treat constipation"],
        ],
      },
      {
        heading: "Drugs for overactive bladder and incontinence",
        columns: ["Drug", "Dose", "Caution"],
        rows: [
          ["Solifenacin", "5-10 mg PO once daily", "Dry mouth, constipation, cognition"],
          ["Tolterodine ER", "4 mg PO once daily", "Anticholinergic effects"],
          ["Trospium", "20 mg PO twice daily before food", "Less CNS penetration; reduce in CKD"],
          ["Oxybutynin IR", "2.5-5 mg PO 2-3 times daily", "Avoid in frail elderly"],
          ["Mirabegron", "25-50 mg PO once daily", "Monitor BP; avoid if 180/110 or more"],
          ["Duloxetine (SUI)", "40 mg PO twice daily", "Second-line; nausea"],
          ["Vaginal estriol 0.1 per cent", "0.5 g nightly 2 weeks, then twice weekly", "Post-menopausal atrophy"],
          ["OnabotulinumtoxinA", "100 units intravesical", "May need self-catheterisation"],
        ],
      },
    ],
    redFlags: [
      "Visible or microscopic haematuria",
      "Continuous leakage day and night - suspect fistula",
      "Palpable bladder or post-void residual above 200 mL",
      "New incontinence with back pain, leg weakness or saddle anaesthesia - cauda equina",
      "Recurrent UTI or bladder pain",
      "Prolapse protruding beyond the introitus with ulceration",
      "Incontinence with rising creatinine or hydronephrosis",
      "Sudden-onset incontinence with confusion - delirium or infection",
    ],
    pearls: [
      "Stress leaks with effort; urge leaks after the urge - the history sorts most cases.",
      "Screen every older patient for DIAPPERS - many causes are reversible.",
      "A 3-day bladder diary is the cheapest and most informative test.",
      "Supervised PFMT for at least 3 months, 8 contractions three times a day, is first-line for SUI.",
      "Bladder training for at least 6 weeks is first-line for urgency incontinence.",
      "Avoid oxybutynin in the frail elderly; prefer mirabegron when cognition is at risk.",
      "Urodynamics are not needed before surgery for clearly defined pure SUI.",
      "Check PVR before starting an antimuscarinic in older men and diabetics.",
      "Continuous leakage after obstructed labour or hysterectomy is a fistula until proved otherwise - do a dye test.",
      "Do not treat asymptomatic bacteriuria in catheterised or elderly patients.",
    ],
    theory: [
      {
        id: "renal-urology-urinary-incontinence-t1",
        paper: "III",
        kind: "long",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question:
          "A 45-year-old multiparous woman leaks urine on coughing and sneezing. Classify urinary incontinence. How will you evaluate her? Outline the management of stress urinary incontinence. [3+3+4]",
        openingLines: [
          "Urinary incontinence is any involuntary leakage of urine; stress incontinence is leakage on effort, sneezing or coughing due to urethral hypermobility or intrinsic sphincter deficiency.",
          "Most women improve with pelvic floor muscle training, and midurethral sling surgery is reserved for those in whom supervised conservative care fails.",
        ],
        answer: [
          {
            heading: "Classification",
            points: [
              "Stress, urgency (OAB), mixed, overflow, functional, continuous (fistula), post-micturition dribble, enuresis.",
            ],
          },
          {
            heading: "Evaluation",
            points: [
              "History: type, frequency, pads, obstetric history, cough, constipation, drugs; ICIQ-UI SF; 3-day bladder diary.",
              "Examination: BMI, cough stress test, prolapse, atrophy, pelvic floor strength, neurological S2-S4.",
              "Urine dipstick, PVR by ultrasound; urodynamics only if mixed, voiding dysfunction, prolapse or prior surgery.",
            ],
          },
          {
            heading: "Conservative management",
            points: [
              "Weight loss, caffeine reduction, treat cough and constipation.",
              "Supervised PFMT at least 3 months, 8 contractions three times daily; the knack.",
              "Pessary or continence device; duloxetine only if surgery declined.",
            ],
          },
          {
            heading: "Surgical management",
            points: [
              "Midurethral sling (TVT, TOT), Burch colposuspension, fascial sling, bulking agents.",
              "Consent for mesh complications; follow-up.",
            ],
          },
        ],
        mustDraw: ["Diagram of urethral support - hammock hypothesis", "Algorithm for management of SUI"],
        markSplit: [
          { part: "Classification", marks: 3 },
          { part: "Evaluation", marks: 3 },
          { part: "Management", marks: 4 },
        ],
        keywords: ["stress incontinence", "PFMT", "TVT", "cough stress test", "bladder diary"],
      },
      {
        id: "renal-urology-urinary-incontinence-t2",
        paper: "II",
        kind: "short-note",
        marks: 10,
        minutes: 18,
        frequency: "common",
        question:
          "A 70-year-old man with diabetes and mild dementia has new-onset dribbling of urine. Discuss the causes and outline your approach in primary care. [4+6]",
        openingLines: [
          "Incontinence in the elderly is multifactorial - lower urinary tract changes combine with reversible factors summarised as DIAPPERS.",
          "In an older diabetic man, overflow from retention (BPH, neuropathy, anticholinergics) and functional incontinence from dementia must be excluded before antimuscarinics are used.",
        ],
        answer: [
          {
            heading: "Causes",
            points: [
              "DIAPPERS: delirium, infection, atrophy, pharmaceuticals, psychological, excess output (hyperglycaemia), restricted mobility, stool impaction.",
              "Overflow: BPH, stricture, diabetic cystopathy, anticholinergic drugs.",
              "Urgency (DHIC), functional (dementia), post-micturition dribble.",
            ],
          },
          {
            heading: "Assessment",
            points: [
              "History with carer, bladder diary, drug review; cognition and mobility.",
              "Abdomen for bladder, DRE for prostate and impaction, neurological exam; PVR by scan.",
              "Urine dipstick, glucose, creatinine, PSA with counselling; USG KUB.",
            ],
          },
          {
            heading: "Management",
            points: [
              "Treat reversible causes; control glucose; stop offending drugs.",
              "Retention: catheter decompression, tamsulosin, CISC, refer urology.",
              "Timed and prompted voiding, access aids, pads, skin care; mirabegron rather than antimuscarinics if OAB with low PVR.",
            ],
          },
        ],
        mustDraw: ["Flow chart of evaluation of incontinence in the elderly"],
        markSplit: [
          { part: "Causes", marks: 4 },
          { part: "Assessment and management", marks: 6 },
        ],
        keywords: ["elderly incontinence", "DIAPPERS", "overflow", "PVR", "mirabegron"],
      },
    ],
    mcqs: [
      {
        id: "renal-urology-urinary-incontinence-q1",
        stem: "A 42-year-old para 4 woman leaks small amounts of urine when she coughs, laughs or lifts. Examination shows leakage synchronous with cough and no prolapse. What is the first-line treatment?",
        options: [
          "Supervised pelvic floor muscle training for at least 3 months",
          "Tolterodine 4 mg daily",
          "Transobturator tape",
          "Urodynamic study before any treatment",
        ],
        answer: 0,
        explanation:
          "Pure stress incontinence is treated first with supervised PFMT for at least 3 months, which cures or improves most women. Tolterodine treats urgency, not stress leakage; a sling is reserved for failure of conservative treatment; and urodynamics are not required before conservative care or for clearly defined pure SUI.",
        difficulty: "easy",
      },
      {
        id: "renal-urology-urinary-incontinence-q2",
        stem: "An 80-year-old woman with mild cognitive impairment has urgency incontinence despite bladder training. Which drug is most appropriate?",
        options: ["Oxybutynin immediate-release", "Mirabegron", "Duloxetine", "Desmopressin"],
        answer: 1,
        explanation:
          "Mirabegron, a beta-3 agonist, relieves OAB without anticholinergic effects on cognition, making it preferable in an older woman with cognitive impairment. Oxybutynin IR has the highest anticholinergic burden and is avoided in the frail elderly, duloxetine is for stress incontinence, and desmopressin risks hyponatraemia over 65.",
        difficulty: "moderate",
      },
      {
        id: "renal-urology-urinary-incontinence-q3",
        stem: "A woman has continuous leakage of urine day and night starting 7 days after an abdominal hysterectomy. Methylene blue instilled into the bladder does not stain the vaginal swabs, but the top swab is wet. What is the most likely diagnosis?",
        options: [
          "Vesicovaginal fistula",
          "Stress urinary incontinence",
          "Overflow incontinence",
          "Ureterovaginal fistula",
        ],
        answer: 3,
        explanation:
          "A wet but unstained upper swab after intravesical dye means urine is reaching the vagina without passing through the bladder, indicating a ureterovaginal fistula. A vesicovaginal fistula stains the swab blue, stress incontinence is intermittent with effort, and overflow gives dribbling with a distended bladder.",
        difficulty: "hard",
      },
      {
        id: "renal-urology-urinary-incontinence-q4",
        stem: "In the DIAPPERS mnemonic for reversible causes of incontinence, what does the letter E stand for?",
        options: ["Excess urine output", "Endocrine tumour", "Enuresis", "Epilepsy"],
        answer: 0,
        explanation:
          "E is excess urine output - from hyperglycaemia, hypercalcaemia, diuretics, high fluid intake or nocturnal mobilisation of oedema. Endocrine tumours, enuresis and epilepsy are not part of the mnemonic, which also covers delirium, infection, atrophy, pharmaceuticals, psychological causes, restricted mobility and stool impaction.",
        difficulty: "easy",
      },
      {
        id: "renal-urology-urinary-incontinence-q5",
        stem: "Before starting an antimuscarinic for urgency in a 72-year-old diabetic man with a weak stream, which test is most important?",
        options: ["Serum PSA", "Cystoscopy", "Post-void residual volume", "Urine cytology"],
        answer: 2,
        explanation:
          "A high post-void residual indicates retention from BPH or diabetic cystopathy, in which antimuscarinics can precipitate acute retention, so PVR must be checked first. PSA is part of prostate assessment but does not measure emptying, and cystoscopy and cytology are for haematuria or suspected malignancy.",
        difficulty: "moderate",
      },
    ],
    references: [
      "NICE NG123 Urinary incontinence and pelvic organ prolapse in women: management, 2019",
      "European Association of Urology Guidelines on Non-neurogenic Female LUTS, 2024, and on Male LUTS, 2025",
      "Cameron AP et al. AUA/SUFU Guideline on the Diagnosis and Treatment of Idiopathic Overactive Bladder, 2024",
      "Campbell-Walsh-Wein Urology, 13th edition",
      "Harrison's Principles of Internal Medicine, 22nd edition (2025) - Urinary incontinence in the elderly",
      "Berek and Novak's Gynecology, 16th edition (2019)",
      "American Geriatrics Society Beers Criteria Update, 2023",
      "WHO Labour Care Guide: user's manual, 2020; Williams Obstetrics, 26th edition (2022)",
    ],
  },
];

export default topics;
