import type { TopicRewrite } from "../index";

const rewrites: Record<string, TopicRewrite> = {
  "endocrine-t2dm-diagnosis-oral-drugs": {
    oneLiner:
      "Type 2 diabetes is **progressive beta-cell failure on a background of insulin resistance**, diagnosed by **FPG 126 mg/dL or more, 2-h OGTT 200 mg/dL or more, HbA1c 6.5% or more** (confirmed twice) or a **random glucose 200 mg/dL or more with symptoms**; treat with lifestyle plus **metformin**, and pick the next drug by comorbidity - **SGLT2 inhibitor for heart failure or CKD, GLP-1 agonist for atherosclerosis or obesity** - then by weight, hypoglycaemia risk and cost.",
    sections: [
      {
        heading: "Definition and the classification that matters",
        points: [
          "**Diabetes** is diagnosed by any one of: **fasting plasma glucose 126 mg/dL or more** (no calories for 8 hours), **2-hour plasma glucose 200 mg/dL or more after 75 g OGTT**, **HbA1c 6.5% or more** by an NGSP-certified laboratory method, or **random plasma glucose 200 mg/dL or more with classic symptoms or a hyperglycaemic crisis**. [ADA 2026]",
          "Without unequivocal hyperglycaemia, **two abnormal results** are needed - either two different tests on the same sample (for example FPG 132 mg/dL and HbA1c 6.8%) or the same test repeated on a second day. [ADA 2026]",
          "**Prediabetes** is **IFG 100-125 mg/dL** (WHO uses 110-125), **IGT 140-199 mg/dL** at 2 hours, or **HbA1c 5.7-6.4%** - risk of progression rises continuously across the range, and IGT predicts cardiovascular risk best. [ADA 2026]",
          "The classification examiners expect is the **ADA aetiological classification**: type 1 (autoimmune beta-cell destruction), type 2 (insulin resistance with progressive loss of secretion), specific types (MODY, pancreatic, drug-induced) and gestational diabetes. [ADA 2026]",
          "Indian specific types to name: **LADA** (adult, lean, GAD antibody positive, fails tablets in 6-12 months), **fibrocalculous pancreatic diabetes** (young, lean, pancreatic calculi, steatorrhoea) and **ketosis-prone diabetes** (DKA at onset but later insulin-independent). [RSSDI 2022]",
          "India has diabetes in about **11.4%** and prediabetes in about **15.3%** of adults (ICMR-INDIAB), with onset **about a decade earlier** and at a **lower BMI** than in Europeans - so a normal BMI never excludes the diagnosis. [ICMR-INDIAB 2023]",
          "**Remission** is defined as **HbA1c below 6.5% measured at least 3 months after stopping all glucose-lowering drugs** - achievable in early disease with 10-15 kg weight loss. [ADA 2026]",
        ],
      },
      {
        heading: "Pathophysiology and pathoanatomy",
        points: [
          "**Insulin resistance comes first**: excess visceral and hepatic fat releases free fatty acids and cytokines (TNF-alpha, IL-6) that cause **serine phosphorylation of IRS-1**, blocking the PI3-kinase-Akt pathway so fewer **GLUT4** transporters move to the muscle and fat cell membrane. [Harrison 22e]",
          "In the liver, diacylglycerol activates **PKC-epsilon**, insulin fails to suppress **gluconeogenesis**, and fasting glucose rises - which is why **metformin**, acting mainly on hepatic glucose output, lowers the fasting value most. [Williams Endocrinology 15e]",
          "For years the **beta cell compensates by hypersecretion**; diabetes appears only when secretion fails, and at diagnosis about **50% of beta-cell function is already lost**, falling a few percent every year - the reason treatment must be stepped up over time. [Harrison 22e]",
          "Beta-cell failure is driven by **glucotoxicity, lipotoxicity**, endoplasmic reticulum stress, oxidative stress and **islet amyloid (amylin) deposition** - so lowering glucose fast (insulin when HbA1c is over 10%) partly restores secretion. [Williams Endocrinology 15e]",
          "**Loss of first-phase insulin release** is the earliest secretory defect, producing the post-meal spike; on high-carbohydrate Indian diets this **postprandial excursion** contributes much of the HbA1c. [RSSDI 2022]",
          "**Alpha-cell dysfunction**: glucagon is not suppressed after meals and drives hepatic glucose output - GLP-1 agonists and DPP-4 inhibitors lower glucagon in a glucose-dependent way. [Harrison 22e]",
          "**Reduced incretin effect**: the gut hormones GLP-1 and GIP normally provide about 60% of the insulin response to oral glucose; in type 2 diabetes the GLP-1 response is blunted and the beta cell is resistant to GIP - the target of **gliptins, GLP-1 agonists and tirzepatide**. [Williams Endocrinology 15e]",
          "**Kidney**: proximal tubular **SGLT2** reabsorbs about 90% of filtered glucose and is upregulated in diabetes, raising the renal threshold - **SGLT2 inhibitors** cause glycosuria of about 60-80 g/day (240-320 kcal), weight loss and natriuresis. [Harrison 22e]",
          "**Brain**: hypothalamic resistance to insulin and leptin and reduced satiety signalling perpetuate overeating - GLP-1 agonists act on the arcuate nucleus and brainstem to cut appetite. [Williams Endocrinology 15e]",
          "These eight defects (**DeFronzo's ominous octet** - beta cell, alpha cell, liver, muscle, fat, gut, kidney, brain) explain why **combination therapy with different mechanisms** works better than pushing one drug to maximum. [Williams Endocrinology 15e]",
          "**Asian Indian phenotype**: more visceral and liver fat, less muscle and a smaller beta-cell reserve at the same BMI - partly from **fetal undernutrition (thin-fat baby, thrifty phenotype)** followed by urban overnutrition. [ICMR-INDIAB 2023]",
          "**Osmotic symptoms**: glucose exceeds the renal threshold at about **180 mg/dL**, causing glycosuria, **polyuria**, thirst and **polydipsia**; calorie loss in urine and catabolism cause **weight loss** despite hunger. [Harrison 22e]",
          "**Blurred vision** comes from sorbitol and water shifts in the lens changing refraction, and settles 4-6 weeks after glucose is controlled - so glasses should not be prescribed at diagnosis. [OHCM 11e]",
          "**Infections** (candidal balanoposthitis, vulvovaginitis, boils, TB, UTI) follow impaired neutrophil chemotaxis and phagocytosis and a sugar-rich urine and mucosa. [Harrison 22e]",
          "**Acanthosis nigricans** marks severe hyperinsulinaemia - high insulin stimulates **IGF-1 receptors** on keratinocytes and fibroblasts, producing velvety pigmented skin in the neck and axillae. [Harrison 22e]",
          "**Microvascular damage** (retina, glomerulus, nerve) follows the polyol pathway, **advanced glycation end-products**, PKC activation and hexosamine flux in cells that cannot down-regulate glucose uptake - so it tracks HbA1c closely; **macrovascular disease** tracks blood pressure, LDL and smoking as much as glucose. [Harrison 22e]",
        ],
      },
      {
        heading: "History in the OPD",
        points: [
          "**Osmotic symptoms and their tempo** - polyuria, nocturia, thirst, weight loss over weeks: rapid weight loss in a lean patient suggests **insulin deficiency (type 1, LADA, FCPD)** and needs insulin, not tablets. [RSSDI 2022]",
          "**Symptoms of ketosis** - vomiting, abdominal pain, breathlessness, drowsiness: any of these with high glucose means possible **DKA** and same-day admission. [ADA 2026]",
          "**Infections** - recurrent boils, genital itching or discharge, burning micturition, slow-healing wounds - hint at long-standing undiagnosed hyperglycaemia. [Harrison 22e]",
          "**TB screen in every diabetic**: cough for 2 weeks or more, fever, night sweats, weight loss - diabetes triples TB risk and NTEP mandates bidirectional screening. [NTEP 2024]",
          "**Complication symptoms already present**: tingling or burning feet, visual blurring, chest pain on exertion, calf claudication, erectile dysfunction, frothy urine - type 2 is silent for years so damage often predates diagnosis. [ADA 2026]",
          "**Family history** of diabetes in first-degree relatives (and three generations in MODY), premature heart disease, and **past gestational diabetes or PCOS** in women. [ICMR 2018]",
          "**Drug history**: corticosteroids, atypical antipsychotics (olanzapine, clozapine), protease inhibitors, high-dose thiazides, tacrolimus and statins (small effect) raise glucose - review before labelling type 2. [ADA 2026]",
          "**Diet recall for 24 hours**: rice or roti portions, sweets, fruit juice, tea with sugar, late dinners and outside food - you need it to write a realistic food plan. [ICMR 2018]",
          "**Physical activity and occupation**: sedentary desk work, shift work, drivers and people operating machinery (hypoglycaemia risk on sulfonylureas matters), and heavy manual labourers (meal timing). [RSSDI 2022]",
          "**Fasting practices** (Ramadan, Navratri, weekly religious fasts) - determine which drugs are safe and whether sulfonylurea timing must change. [IDF-DAR 2021]",
          "**Alcohol and tobacco**: alcohol causes hypoglycaemia with sulfonylureas and insulin and pancreatitis; smoking doubles vascular risk and is the cheapest risk factor to remove. [ADA 2026]",
          "**Previous treatment and adherence**: which tablets, doses, timing relative to meals, side effects, and whether the patient actually buys them each month - cost is the commonest reason for failure in India. [RSSDI 2022]",
          "**Hypoglycaemia history** - sweating, tremor, confusion, especially at night or on skipped meals - on a sulfonylurea this changes the drug choice. [ADA 2026]",
          "**Symptoms of secondary causes**: Cushingoid features, acromegalic change, abdominal pain with steatorrhoea (FCPD, chronic pancreatitis) and heat intolerance (thyrotoxicosis). [Williams Endocrinology 15e]",
        ],
      },
      {
        heading: "Examination",
        points: [
          "**Weight, height and BMI** with Asian Indian cut-offs (**overweight 23-24.9, obese 25 kg/m2 or more**) and **waist circumference** at the midpoint between the costal margin and iliac crest - abnormal at **90 cm or more in men and 80 cm or more in women**. [ICMR 2018]",
          "**Blood pressure** seated, and standing in long-standing disease - a fall of 20/10 mmHg suggests **cardiac autonomic neuropathy**. [ADA 2026]",
          "**Skin**: acanthosis nigricans, skin tags, xanthelasma, boils, intertrigo, candidal balanitis, necrobiosis lipoidica and shin spots - markers of insulin resistance, lipids and poor control. [Harrison 22e]",
          "**Feet at the first visit**: inspect for callus, deformity and ulcer; test **10 g monofilament** at plantar sites plus **128 Hz tuning fork** or pinprick, ankle reflexes, and palpate dorsalis pedis and posterior tibial pulses. [IWGDF 2023]",
          "**Eyes**: visual acuity and **dilated fundoscopy** (or retinal photograph) at diagnosis - retinopathy is present in a meaningful minority at diagnosis of type 2. [ADA 2026]",
          "**Mouth**: periodontitis and oral candidiasis - periodontitis worsens glycaemia and treating it lowers HbA1c slightly. [ADA 2026]",
          "**Signs of secondary diabetes**: moon face, purple striae and proximal myopathy (Cushing), coarse features and large hands (acromegaly), bronze skin and hepatomegaly (haemochromatosis), goitre and tremor (thyrotoxicosis). [Williams Endocrinology 15e]",
          "**Lean young patient with wasting**, especially with epigastric pain or steatorrhoea - suspect FCPD or type 1; look for dehydration and Kussmaul breathing in any symptomatic patient. [RSSDI 2022]",
          "**Cardiovascular and chest examination**: carotid bruit, heart failure signs, chest signs of TB - they change the second-drug choice and the need for sputum testing. [ADA 2026]",
          "**Hepatomegaly** suggests **MASLD (fatty liver)** - common in Indian type 2 diabetes and favours pioglitazone, a GLP-1 agonist or tirzepatide. [ADA 2026]",
        ],
      },
      {
        heading: "Minimal investigations",
        points: [
          "**Fasting plasma glucose plus HbA1c** on one venous sample is the practical diagnostic pair; use a **75 g OGTT** when results are discordant or in suspected prediabetes with a normal fasting value. [ADA 2026]",
          "**Never diagnose on a glucometer** - capillary screening (NP-NCD) must be confirmed on venous plasma in a laboratory. [NP-NCD 2023]",
          "**HbA1c pitfalls**: falsely **high in iron deficiency**, falsely **low after blood loss, transfusion, haemolysis, pregnancy** and in advanced CKD, and uninterpretable in haemoglobinopathies (HbE, HbS) - check a **haemoglobin** alongside and rely on plasma glucose if in doubt. [ADA 2026]",
          "**Baseline tests**: fasting lipid profile, **serum creatinine with eGFR**, **spot urine albumin-creatinine ratio**, ALT, CBC and urine routine (ketones, infection); **TSH** if symptoms or in women over 50. [ADA 2026]",
          "**ECG** at baseline in adults with diabetes over 40 or with hypertension or symptoms - silent ischaemia is common. [RSSDI 2022]",
          "**Urine or blood ketones** when glucose is over 250 mg/dL with symptoms, weight loss or vomiting - positive ketones change management to insulin. [ADA 2026]",
          "**C-peptide and GAD antibodies** only when type 1, LADA or MODY is suspected (lean, young, rapid progression, early tablet failure); C-peptide must be read with a paired glucose over 144 mg/dL. [RSSDI 2022]",
          "**Do not order routinely**: fasting insulin, HOMA-IR, fructosamine, C-peptide in obvious type 2, or coronary imaging in asymptomatic patients - they do not change first-line treatment. [ADA 2026]",
          "**Serum vitamin B12** after 3-4 years on metformin or earlier if neuropathy or anaemia appears. [ADA 2026]",
        ],
      },
      {
        heading: "Treatment - general measures",
        points: [
          "**Structured education (DSMES)** at diagnosis: what diabetes is, targets, drugs and timing, hypoglycaemia recognition, foot care, sick-day rules - it lowers HbA1c by about 0.5-1%. [ADA 2026]",
          "**Diet - the plate method**: half the plate non-starchy vegetables, a quarter protein (dal, pulses, eggs, fish, paneer), a quarter whole grain or millet; avoid sugary drinks and fruit juice; whole fruit 1-2 servings a day. [ICMR 2018]",
          "Cut **refined carbohydrate** (white rice, maida, sugar) toward 50-55% of energy, keep fibre high, eat meals at regular times - especially important on sulfonylureas or insulin. [RSSDI 2022]",
          "**Activity**: **150 minutes a week** of moderate aerobic activity over at least 3 days (no more than 2 consecutive days off), plus **resistance exercise 2-3 times a week**, and break prolonged sitting every 30 minutes. [ADA 2026]",
          "**Weight loss target 5-7%** for everyone overweight; **10-15% or more** can produce remission in the first years after diagnosis. [ADA 2026]",
          "**Stop tobacco** in any form and limit alcohol (never on an empty stomach on sulfonylurea or insulin). [ADA 2026]",
          "**Sleep 7-8 hours**, screen for obstructive sleep apnoea and depression - both worsen glycaemia and adherence. [ADA 2026]",
          "**Vaccinate**: annual influenza, pneumococcal (PCV20 or PCV15 then PPSV23), hepatitis B up to age 59, recombinant zoster from 50, and COVID-19 as per current schedule. [ADA 2026]",
          "**Self-monitoring** with a glucometer is useful on insulin or sulfonylureas, during illness and when adjusting diet - not essential daily for those on metformin alone. [ADA 2026]",
          "**Register in NP-NCD** at the Ayushman Arogya Mandir so the patient receives free metformin, glimepiride and follow-up reminders. [NP-NCD 2023]",
        ],
      },
      {
        heading: "Treatment - drugs",
        points: [
          "**Start metformin at diagnosis** with lifestyle unless contraindicated; with **ASCVD, heart failure or CKD**, add an **SGLT2 inhibitor or GLP-1 agonist with proven benefit** from the start, whatever the HbA1c. [ADA 2026]",
          "If **HbA1c is 1.5% or more above target**, start **dual therapy**; if **HbA1c over 10%, glucose 300 mg/dL or more, or catabolic or ketotic**, start **insulin** - glucotoxicity then resolves and tablets often suffice later. [ADA 2026]",
          "**Metformin (biguanide) mechanism**: inhibits mitochondrial complex I and glycerophosphate dehydrogenase, raising AMP and activating **AMPK**, so **hepatic gluconeogenesis falls**; it also raises gut GLP-1 - HbA1c falls 1-1.5%, weight neutral, no hypoglycaemia alone. [Goodman and Gilman 14e]",
          "**Metformin dose**: **500 mg once or twice daily with or just after meals**, increase by 500 mg every 1-2 weeks to **1000 mg twice daily** (maximum 2000-2550 mg/day); **extended-release 500-2000 mg once daily with the evening meal** if GI upset. [ADA 2026]",
          "**Metformin side effects**: diarrhoea, bloating, metallic taste (reduce by slow titration and taking with food), **vitamin B12 deficiency** (check every 3-4 years; replace with **methylcobalamin 1500 microgram daily** or IM), and very rare **lactic acidosis**. [ADA 2026]",
          "**Metformin in kidney disease**: full dose if eGFR 45 or more; **do not start at eGFR 30-45 and cap at 1000 mg/day**; **stop below 30**; withhold on the day of iodinated contrast if eGFR 30-60 and restart after 48 hours if creatinine is stable; withhold during vomiting, sepsis and hypoxia. [ADA 2026]",
          "**Sulfonylurea mechanism**: binds **SUR1** on the beta-cell K-ATP channel, closes it, depolarises the cell, opens voltage-gated calcium channels and triggers **insulin exocytosis regardless of glucose** - hence hypoglycaemia and 2-3 kg weight gain; HbA1c falls 1-1.5%. [Goodman and Gilman 14e]",
          "**Sulfonylurea doses**: **glimepiride 1 mg once daily just before or with breakfast**, increase by 1 mg every 1-2 weeks to 4 mg (maximum 8 mg); **gliclazide MR 30-120 mg once daily with breakfast**; **glipizide 2.5-20 mg before meals** - all cheap and free in NP-NCD. [RSSDI 2022]",
          "**Sulfonylurea safety**: **no meal, no pill** - skip the dose if the meal is skipped, never double a missed dose; **avoid glibenclamide** (long-acting active metabolites, prolonged hypoglycaemia) in elderly and CKD; prefer **gliclazide MR or glimepiride**; beware alcohol, fluconazole and co-trimoxazole which potentiate them. [RSSDI 2022]",
          "**Glinides** (repaglinide 0.5-4 mg, nateglinide 60-120 mg) are short-acting insulin secretagogues taken **0-15 minutes before each main meal** (skip if meal skipped) - useful for irregular meals and in CKD (repaglinide). [RSSDI 2022]",
          "**SGLT2 inhibitor mechanism**: blocks glucose (and sodium) reabsorption in the proximal tubule, causing glycosuria, natriuresis, lower intraglomerular pressure via **tubuloglomerular feedback**, 2-3 kg weight loss and **0.5-0.9% HbA1c fall** - cardio-renal benefit is independent of glucose. [ADA 2026]",
          "**SGLT2 inhibitor doses**: **dapagliflozin 10 mg once daily**, **empagliflozin 10 mg once daily** (25 mg for more glucose effect), canagliflozin 100 mg, **remogliflozin 100 mg twice daily** (India); take in the **morning**, with or without food; start for cardio-renal benefit if **eGFR 20 or more** and continue until dialysis. [ADA 2026]",
          "**SGLT2 inhibitor side effects**: **genital mycotic infection** (teach daily genital hygiene; treat with clotrimazole cream or fluconazole 150 mg once), UTI, volume depletion and postural hypotension (reduce diuretic), an expected **initial eGFR dip of 3-5 mL/min** that should not prompt stopping, rare **Fournier gangrene**. [ADA 2026]",
          "**Euglycaemic DKA on SGLT2 inhibitors**: ketoacidosis with glucose under 250 mg/dL - **stop 3 days before surgery** (4 days for ertugliflozin), during acute illness, vomiting, prolonged fasting or keto diets, and check ketones (not glucose) if unwell. [ADA/EASD 2024]",
          "**DPP-4 inhibitor (gliptin) mechanism**: blocks the enzyme that degrades endogenous GLP-1 and GIP, raising their levels 2-3 fold - glucose-dependent insulin release and glucagon suppression, **HbA1c fall 0.5-0.8%**, weight neutral, no hypoglycaemia alone, no cardiovascular benefit. [ADA 2026]",
          "**Gliptin doses (once daily, any time, with or without food)**: **teneligliptin 20 mg** (cheapest in India), **sitagliptin 100 mg** (50 mg at eGFR 30-45, 25 mg below 30), **vildagliptin 50 mg twice daily** (once daily if eGFR under 50; check LFTs), **linagliptin 5 mg with no renal adjustment**; saxagliptin carries a heart-failure signal. [RSSDI 2022]",
          "**Gliptin side effects**: nasopharyngitis, arthralgia, rare **acute pancreatitis** (stop if severe abdominal pain) and **bullous pemphigoid** (tense blisters in the elderly - stop the drug). [ADA 2026]",
          "**Thiazolidinedione mechanism**: **pioglitazone** activates nuclear **PPAR-gamma** in fat, muscle and liver, increasing GLUT4 and adiponectin and moving fat out of liver and muscle - a true insulin sensitiser that also improves **MASH**; HbA1c falls 0.8-1.2%, effect takes 6-12 weeks. [Goodman and Gilman 14e]",
          "**Pioglitazone 7.5-15 mg once daily**, up to 30 mg (maximum 45 mg); side effects **fluid retention and heart failure** (contraindicated in NYHA III-IV), weight gain, **fractures** in postmenopausal women, and caution with past or present bladder cancer or haematuria. [RSSDI 2022]",
          "**Alpha-glucosidase inhibitors** block brush-border enzymes that split starch and sucrose, flattening the post-meal peak: **acarbose 25 mg three times daily with the first bite** of each main meal, up to 50-100 mg TDS, or **voglibose 0.2-0.3 mg TDS** - flatulence is common; treat hypoglycaemia with **glucose, not sugar**. [RSSDI 2022]",
          "**GLP-1 receptor agonist mechanism**: glucose-dependent insulin release, glucagon suppression, **slowed gastric emptying** and central appetite suppression - HbA1c falls 1-1.5% with 4-6 kg weight loss and proven MACE reduction (liraglutide, dulaglutide, semaglutide). [ADA 2026]",
          "**GLP-1 agonist doses**: **dulaglutide 0.75 mg weekly SC**, increase to 1.5 mg (up to 4.5 mg); **semaglutide 0.25 mg weekly SC for 4 weeks, then 0.5 mg, then 1 mg** (maximum 2 mg); **liraglutide 0.6 mg daily for a week, then 1.2-1.8 mg** - injected any time of day, same day each week for weekly forms. [ADA 2026]",
          "**Oral semaglutide 3 mg daily for 30 days, then 7 mg, then 14 mg**: take on waking on an **empty stomach with no more than 120 mL water**, then wait **at least 30 minutes** before food, drink or other tablets - otherwise it is not absorbed. [ADA 2026]",
          "**Tirzepatide** (dual **GIP and GLP-1 agonist**): **2.5 mg weekly SC for 4 weeks, then increase by 2.5 mg every 4 weeks** to 5-15 mg - HbA1c falls 2% and weight 10-20%; preferred with obesity, MASLD or HFpEF with obesity. [ADA 2026]",
          "**GLP-1 and tirzepatide side effects**: nausea, vomiting, diarrhoea (titrate slowly, eat small meals, stop eating when full), gallstones, rare pancreatitis; **contraindicated with personal or family history of medullary thyroid cancer or MEN2**; caution in proliferative retinopathy (rapid glucose fall) and aspiration risk at anaesthesia. [ADA 2026]",
          "**Do not combine** a DPP-4 inhibitor with a GLP-1 agonist (same pathway) or a sulfonylurea with a glinide; when starting basal insulin **stop or halve the sulfonylurea**. [ADA 2026]",
          "**Imeglimin 1000 mg twice daily** (approved in India 2022) improves mitochondrial function in liver and beta cell; it is add-on only with limited long-term outcome data and should not be first choice. [RSSDI 2022]",
          "**Choosing by patient**: heart failure or albuminuric CKD - SGLT2 inhibitor; ASCVD or obesity - GLP-1 agonist or tirzepatide; cost the limiting factor - **metformin plus gliclazide MR or glimepiride**, or teneligliptin; elderly or hypoglycaemia risk - gliptin, avoid glibenclamide. [ADA 2026]",
          "**Pregnancy and planning pregnancy**: stop SGLT2 inhibitors, GLP-1 agonists, gliptins and pioglitazone; **insulin is preferred** (metformin may be continued in selected cases under specialist advice). [ADA 2026]",
          "**Cardiovascular protection with glucose drugs**: **statin for all aged 40-75** (moderate intensity; high intensity with ASCVD or multiple risk factors), and **ACE inhibitor or ARB** if hypertensive or albuminuric - these prevent more events than glucose lowering. [ADA 2026]",
        ],
      },
      {
        heading: "Special situations",
        points: [
          "**Ramadan and religious fasts**: shift metformin to split between iftar and suhoor, give sulfonylurea (gliclazide preferred) at iftar at half dose, stop SGLT2 inhibitors if dehydration risk, and **break the fast if glucose is under 70 or over 300 mg/dL**. [IDF-DAR 2021]",
          "**Elderly**: avoid glibenclamide, start low with metformin and gliptins, relax targets, and deprescribe if HbA1c is well below target on hypoglycaemia-causing drugs. [ADA 2026]",
          "**Steroid-induced hyperglycaemia**: once-daily morning prednisolone raises afternoon and evening glucose - use a morning NPH insulin or morning sulfonylurea matched to the steroid dose and taper both together. [RSSDI 2022]",
          "**Prediabetes**: structured lifestyle change reduced progression by **28.5%** in IDPP-1 (metformin 26.4%, both 28.2%) - consider **metformin 500 mg twice daily** if BMI 30 or more (Asian cut-off), age under 60 or prior gestational diabetes. [IDPP-1 2006]",
        ],
      },
      {
        heading: "Follow-up, monitoring and when to refer",
        points: [
          "Review at **2-4 weeks** after starting or changing a drug (tolerance, hypoglycaemia, self-monitored values), then **HbA1c every 3 months** until at target, then every 6 months. [ADA 2026]",
          "**Glycaemic targets**: HbA1c **below 7%** for most; **6.5% or lower** in young newly diagnosed patients without hypoglycaemia; **under 8%** (or symptom-free) in frail elderly, limited life expectancy or hypoglycaemia unawareness; FPG **80-130 mg/dL**, 2-hour postprandial **under 180 mg/dL**. [ADA 2026]",
          "**Other targets**: BP **under 130/80 mmHg**; LDL-C **under 70 mg/dL**, or **under 55 mg/dL with ASCVD**; no tobacco. [ADA 2026]",
          "If off target at 3 months, **check adherence, cost, technique and diet first**, then **add a drug from a different class** rather than substituting - failure mostly reflects progressive beta-cell loss. [ADA 2026]",
          "**At every visit**: weight, waist, BP, feet inspection, hypoglycaemia enquiry, and tablet count; **yearly**: urine ACR, eGFR, lipids, dilated fundus, full foot risk assessment, B12 on metformin. [ADA 2026]",
          "**Sick-day rules**: keep drinking, check glucose 4-hourly, **hold metformin, SGLT2 inhibitors, diuretics, ACE inhibitors/ARBs and NSAIDs** during vomiting or dehydration, never stop insulin, and come in if unable to keep fluids down. [ADA 2026]",
          "**Refer urgently** for suspected DKA or HHS, glucose over 300 mg/dL with ketones, foot infection or ischaemia, sudden visual loss. [ADA 2026]",
          "**Refer to a physician or endocrinologist** for suspected type 1, LADA, MODY or FCPD, failure of three drugs, recurrent severe hypoglycaemia, pregnancy, eGFR under 30, or need for complex insulin regimens. [RSSDI 2022]",
        ],
      },
    ],
    tables: [
      {
        heading: "Diagnostic criteria - normal, prediabetes and diabetes",
        columns: ["Category", "Fasting plasma glucose", "2-h OGTT (75 g)", "HbA1c", "Note"],
        rows: [
          ["Normal", "Under 100 mg/dL", "Under 140 mg/dL", "Under 5.7%", "Rescreen every 3 years from 30 (ICMR) or 35 (ADA)"],
          ["Prediabetes", "100-125 mg/dL (IFG)", "140-199 mg/dL (IGT)", "5.7-6.4%", "Lifestyle programme; retest yearly"],
          ["Diabetes", "126 mg/dL or more", "200 mg/dL or more", "6.5% or more", "Confirm with a second abnormal result unless symptomatic"],
          ["Diabetes - symptomatic", "Random 200 mg/dL or more", "-", "-", "With osmotic symptoms or crisis, one value is enough"],
        ],
      },
      {
        heading: "Types of diabetes in the Indian OPD - classification clues",
        columns: ["Type", "Typical patient", "Key test", "First treatment"],
        rows: [
          ["Type 2", "Overweight or central obesity, family history, slow onset", "FPG, HbA1c", "Lifestyle plus metformin"],
          ["Type 1", "Young, lean, rapid weight loss, ketosis", "Low C-peptide, islet antibodies", "Basal-bolus insulin"],
          ["LADA", "Adult, lean, fails tablets within 6-12 months", "GAD antibody positive", "Early insulin; avoid sulfonylureas"],
          ["MODY", "Onset under 25, three generations, non-obese, no ketosis", "Genetic testing (HNF1A, GCK)", "HNF1A: low-dose sulfonylurea; GCK: no drug"],
          ["FCPD", "Young, very lean, childhood abdominal pain, steatorrhoea", "Pancreatic calculi on X-ray or CT", "Insulin plus pancreatic enzymes"],
        ],
      },
      {
        heading: "Drugs: dose, duration and side effects",
        columns: ["Drug", "Mechanism", "Dose and duration", "Side effects", "How to take"],
        rows: [
          ["Metformin", "AMPK activation, cuts hepatic gluconeogenesis", "500 mg OD-BD, up to 1 g BD (XR up to 2 g OD); long-term", "Diarrhoea, metallic taste, B12 deficiency, rare lactic acidosis", "With or after meals; stop below eGFR 30 and in acute illness"],
          ["Glimepiride", "Closes beta-cell K-ATP channel (SUR1)", "1 mg OD, up to 4 mg (max 8 mg); long-term", "Hypoglycaemia, weight gain", "Just before or with breakfast; skip if meal skipped"],
          ["Gliclazide MR", "Closes beta-cell K-ATP channel (SUR1)", "30-120 mg OD; long-term", "Hypoglycaemia (less than glibenclamide), weight gain", "With breakfast; swallow whole"],
          ["Dapagliflozin / empagliflozin", "SGLT2 block - glycosuria, natriuresis", "Dapagliflozin 10 mg OD; empagliflozin 10-25 mg OD; long-term", "Genital thrush, UTI, volume depletion, euglycaemic DKA", "Morning; stop 3 days before surgery and when unwell"],
          ["Teneligliptin / sitagliptin / linagliptin", "DPP-4 block raises GLP-1 and GIP", "20 mg / 100 mg / 5 mg OD; long-term", "Nasopharyngitis, pancreatitis, bullous pemphigoid", "Any time, with or without food; renal dose for sitagliptin"],
          ["Pioglitazone", "PPAR-gamma agonist, insulin sensitiser", "7.5-30 mg OD (max 45 mg); effect in 6-12 weeks", "Oedema, heart failure, weight gain, fractures", "Once daily, any time; avoid in heart failure"],
          ["Acarbose / voglibose", "Blocks intestinal alpha-glucosidase", "Acarbose 25-100 mg TDS; voglibose 0.2-0.3 mg TDS", "Flatulence, bloating", "With the first bite of each main meal"],
          ["Semaglutide (SC or oral)", "GLP-1 agonist - insulin up, glucagon down, satiety", "SC 0.25 mg weekly x4 wk, then 0.5-1 mg (max 2 mg); oral 3 mg x30 d, then 7-14 mg daily", "Nausea, vomiting, gallstones, rare pancreatitis", "SC same day weekly; oral on waking with sip of water, nothing for 30 min"],
          ["Dulaglutide", "GLP-1 agonist", "0.75 mg weekly SC, then 1.5 mg (max 4.5 mg)", "Nausea, diarrhoea; avoid in MTC or MEN2", "Weekly pen, any time of day, same weekday"],
          ["Tirzepatide", "Dual GIP and GLP-1 agonist", "2.5 mg weekly x4 wk, then up by 2.5 mg every 4 wk to 5-15 mg", "Nausea, vomiting, diarrhoea, gallstones", "Weekly pen in abdomen or thigh; small meals"],
        ],
      },
    ],
    redFlags: [
      "Lean young patient with weight loss over weeks, ketonuria and glucose over 250 mg/dL - treat as type 1 or ketosis-prone diabetes and start insulin the same day.",
      "Glucose over 300 mg/dL with vomiting, abdominal pain, drowsiness or Kussmaul breathing - admit for DKA or HHS; do not send home on tablets.",
      "Patient on an SGLT2 inhibitor who is vomiting or breathless with only modestly raised glucose - check ketones and pH for euglycaemic DKA.",
      "Metformin continued through vomiting, sepsis or rising creatinine - stop it and check lactate and bicarbonate.",
      "Confusion, sweating or seizures in an elderly patient on glibenclamide or glimepiride - prolonged sulfonylurea hypoglycaemia needs admission for 24-72 hours.",
      "New diabetes with cough for 2 weeks or more, fever or weight loss - sputum NAAT under NTEP before intensifying therapy.",
      "Foot ulcer with cellulitis, crepitus, foul discharge or probe-to-bone - same-day surgical referral.",
      "Sudden visual loss or new floaters - same-day ophthalmology for vitreous haemorrhage or retinal detachment.",
    ],
    pearls: [
      "One abnormal test does not diagnose diabetes unless the patient is symptomatic with a random glucose of 200 mg/dL or more - repeat before labelling someone for life.",
      "Check haemoglobin before trusting HbA1c in India: iron deficiency raises it and can manufacture a diagnosis the fasting glucose does not support.",
      "Metformin is not contraindicated down to eGFR 30 - cap at 1000 mg/day between 30 and 45 and withhold around contrast and acute illness.",
      "Choose the second drug by the organ you want to protect: heart failure or albuminuric CKD - SGLT2 inhibitor; ASCVD or obesity - GLP-1 agonist; cost - sulfonylurea (gliclazide MR or glimepiride) or teneligliptin.",
      "Sulfonylureas: no meal, no pill - and never glibenclamide in the elderly.",
      "Oral semaglutide is only absorbed on an empty stomach with a sip of water and 30 minutes of nothing else - most failures are from taking it with breakfast tablets.",
      "SGLT2 inhibitors give an early eGFR dip of 3-5 mL/min that is haemodynamic and protective - do not stop the drug for it.",
      "IDPP-1 numbers for prevention answers: lifestyle 28.5%, metformin 26.4%, both 28.2% relative risk reduction - combining adds nothing.",
    ],
    references: [
      "American Diabetes Association. Standards of Care in Diabetes - 2026. Diabetes Care 2026;49(Suppl 1).",
      "RSSDI Clinical Practice Recommendations for the Management of Type 2 Diabetes Mellitus, 2022.",
      "ICMR Guidelines for Management of Type 2 Diabetes, 2018.",
      "Anjana RM et al. ICMR-INDIAB national study of metabolic NCDs in India. Lancet Diabetes Endocrinol 2023.",
      "Ramachandran A et al. Indian Diabetes Prevention Programme (IDPP-1). Diabetologia 2006.",
      "Umpierrez GE et al. Hyperglycemic crises in adults with diabetes: a consensus report (ADA/EASD/JBDS/AACE/DTS). Diabetes Care 2024.",
      "IDF-DAR. Diabetes and Ramadan: Practical Guidelines, 2021.",
      "Harrison's Principles of Internal Medicine, 22nd edition, 2025 - Diabetes mellitus.",
      "Williams Textbook of Endocrinology, 15th edition, 2024 - Type 2 diabetes mellitus.",
      "Goodman and Gilman's The Pharmacological Basis of Therapeutics, 14th edition, 2023 - Pancreatic hormones and antidiabetic drugs.",
      "MoHFW. National Programme for Prevention and Control of NCDs (NP-NCD) Operational Guidelines, 2023.",
      "MoHFW/NTEP. National Framework for Joint TB-Diabetes Collaborative Activities; NTEP Guidelines 2024.",
    ],
  },
  "endocrine-insulin-initiation": {
    oneLiner:
      "Start insulin in type 2 diabetes when **HbA1c is over 10% or glucose 300 mg/dL or more**, when the patient is catabolic or ketotic, or when **HbA1c stays above target on 2-3 oral agents**; begin with **bedtime basal 10 units (0.1-0.2 units/kg)** titrated by **2 units every 3 days** to a fasting glucose of **80-130 mg/dL**, keep metformin, halve the sulfonylurea, and add prandial insulin or a GLP-1 agonist once basal exceeds **0.5 units/kg**.",
    sections: [
      {
        heading: "Definition and the classification that matters",
        points: [
          "**Insulin therapy** replaces the two components of normal secretion - **basal insulin** (about 50% of daily output, restraining hepatic glucose production between meals and overnight) and **prandial (bolus) insulin** (covering the meal-related rise). [Harrison 22e]",
          "The classification examiners expect is **by time-action profile**: rapid-acting analogues (lispro, aspart, glulisine, faster aspart), short-acting **regular human insulin**, intermediate **NPH (isophane)**, long-acting analogues (**glargine U100, detemir**), ultra-long (**degludec, glargine U300**) and **premixed** insulins. [ADA 2026]",
          "**Premixes** available in India: human **30/70** (30% regular, 70% NPH), biphasic aspart 30/70, lispro 25/75 and 50/50, and the co-formulation **IDegAsp 70/30** (degludec with aspart). [RSSDI 2022]",
          "**Strength**: pens and cartridges are **U-100 (100 units/mL)**; human insulin vials in India come as **U-40 and U-100** - the syringe must match the vial or a 2.5-fold dosing error results. [FIT India 2e]",
          "**Indications in type 2 diabetes**: HbA1c over 10% or glucose 300 mg/dL or more at diagnosis, symptoms of catabolism or ketosis, **HbA1c above target on 2-3 oral agents**, pregnancy, acute illness, surgery, high-dose steroids, **eGFR under 30** and decompensated liver disease. [ADA 2026]",
          "**Regimens**: basal only, **basal plus** (one prandial dose), **basal-bolus** (basal plus three prandial doses - the standard for type 1), and **premix twice or thrice daily**. [ADA 2026]",
          "When a type 2 patient needs an injectable, a **GLP-1 agonist or tirzepatide is preferred before insulin**, and is added **before prandial insulin** when basal alone is insufficient - unless the patient is catabolic, ketotic or has very high glucose. [ADA 2026]",
        ],
      },
      {
        heading: "Pathophysiology and pathoanatomy",
        points: [
          "Normal beta cells secrete insulin in **two phases** after a meal - a first-phase burst in 10 minutes from pre-formed granules and a sustained second phase - plus a continuous low basal secretion; type 2 diabetes loses the first phase first. [Williams Endocrinology 15e]",
          "Insulin binds the **insulin receptor tyrosine kinase**, phosphorylates IRS proteins and activates **PI3-kinase-Akt**, moving **GLUT4** to the membrane in muscle and fat, switching on glycogen synthesis and **switching off gluconeogenesis, lipolysis and ketogenesis**. [Harrison 22e]",
          "Portal insulin normally reaches the liver at 2-3 times peripheral levels; **subcutaneous insulin reverses this gradient**, so peripheral hyperinsulinaemia causes weight gain and hypoglycaemia risk that native insulin does not. [Williams Endocrinology 15e]",
          "**Why beta cells fail**: after years of compensation, glucotoxicity, lipotoxicity, amyloid and ER stress reduce beta-cell mass and function by several percent a year - so most type 2 patients eventually need insulin. [Harrison 22e]",
          "**Glucotoxicity is reversible**: sustained glucose over 250-300 mg/dL suppresses insulin gene expression, and 2-4 weeks of insulin restores secretion enough that some patients can step back to tablets. [RSSDI 2022]",
          "**Why regular insulin must be given 30 minutes early**: injected insulin sits as **hexamers**, which must dissociate to dimers and monomers before absorption, so onset is 30-60 minutes and the peak at 2-4 hours lags the meal. [Goodman and Gilman 14e]",
          "**Rapid analogues** swap or change amino acids near the B-chain end (lispro B28-B29 reversal, aspart B28 proline to aspartate) so hexamers break up quickly - onset 10-15 minutes, peak 1-2 hours, duration 3-5 hours, matching the meal. [Goodman and Gilman 14e]",
          "**NPH** is insulin complexed with **protamine and zinc** in crystals that dissolve slowly - it peaks at 4-8 hours, lasting 12-16 hours, so bedtime NPH peaks near dawn when needed but dinner-time NPH peaks at 2-3 a.m. and causes night hypoglycaemia. [Goodman and Gilman 14e]",
          "**Glargine** is soluble at pH 4 and **precipitates in neutral subcutaneous tissue**, releasing slowly for about 24 hours with no peak - so it must never be mixed with other insulins; **detemir** binds albumin via a fatty acid; **degludec** forms multi-hexamer chains lasting over 42 hours. [Goodman and Gilman 14e]",
          "**NPH and premix are suspensions** that settle - they must be rolled and tipped to resuspend, or the first doses are too weak and the last too strong. [FIT India 2e]",
          "**Absorption varies with site and blood flow**: abdomen fastest, then arm, thigh and buttock; exercise, heat and massage speed absorption and cold and smoking slow it. [FIT India 2e]",
          "**Lipohypertrophy** forms because insulin is locally **lipogenic** and repeated needle trauma at the same spot adds fibrosis - absorption from the lump is slow and erratic, causing unexplained highs, and moving to fresh skin causes sudden lows. [FIT India 2e]",
          "**Weight gain** of 2-4 kg follows because glucose (and its calories) is no longer lost in urine and insulin is anabolic and lipogenic - continuing metformin, SGLT2 inhibitors or GLP-1 agonists offsets it. [ADA 2026]",
          "**Hypoglycaemia** occurs because injected insulin cannot switch off when glucose falls, unlike the beta cell; long disease blunts glucagon and adrenaline responses, producing **hypoglycaemia unawareness**. [Harrison 22e]",
          "Insulin drives **potassium into cells** via Na-K-ATPase - hence hypokalaemia with IV insulin in DKA; transient **insulin oedema** and early worsening of retinopathy can follow rapid correction of long-standing hyperglycaemia. [Goodman and Gilman 14e]",
          "**Dawn phenomenon** is a pre-waking surge of growth hormone and cortisol that raises glucose from about 4 a.m.; the **Somogyi effect** is rebound hyperglycaemia after nocturnal hypoglycaemia via counter-regulatory hormones - only a 3 a.m. reading tells them apart. [RSSDI 2022]",
        ],
      },
      {
        heading: "History in the OPD",
        points: [
          "**Current control and trajectory**: HbA1c series, fasting and post-meal values, and which oral agents at what dose and for how long - true failure on 2-3 optimised drugs is the usual trigger. [ADA 2026]",
          "**Symptoms of insulin deficiency**: weight loss, polyuria, thirst, fatigue, recurrent infections, and any vomiting or abdominal pain suggesting ketosis - these make insulin urgent, not optional. [ADA 2026]",
          "**Adherence and cost before blaming the tablets**: ask to see the strips, ask what is actually bought each month and whether doses are skipped - apparent failure is often non-adherence. [RSSDI 2022]",
          "**Psychological insulin resistance**: fear of needles, belief that insulin means end-stage disease or causes kidney failure or blindness, social stigma - address each explicitly because they decide acceptance. [RSSDI 2022]",
          "**Meal pattern and timing**: number of meals, largest meal, late dinners, shift work and fasting days - they decide between basal, premix and basal-bolus. [RSSDI 2022]",
          "**Who will inject**: vision, hand dexterity, tremor, cognition and literacy (can the patient read a dial?), and whether a family member can help - for elderly or visually impaired patients choose a pen with an audible click and a simple once-daily regimen. [FIT India 2e]",
          "**Refrigeration, travel and work**: a fridge at home, long outdoor work in heat, frequent travel - these decide storage advice and whether a pen is carried. [FIT India 2e]",
          "**Occupation with hypoglycaemia risk**: drivers, heavy machinery, working at heights - need conservative targets and testing before driving. [ADA 2026]",
          "**Hypoglycaemia history**: frequency, timing (night sweats, nightmares, morning headache point to nocturnal lows), warning symptoms and whether help was needed. [ADA 2026]",
          "**On insulin at review**: which insulin, dose, timing relative to meals, how cloudy insulin is mixed, injection site, needle reuse, storage, and the glucose log - most problems are found here. [FIT India 2e]",
          "**Other drugs**: sulfonylureas (halve or stop with insulin), corticosteroids (raise afternoon glucose), beta-blockers (mask adrenergic warning symptoms), alcohol. [ADA 2026]",
          "**Pregnancy plans and contraception** in women - insulin is the preferred agent in pregnancy, and planning allows safe transfer. [ADA 2026]",
        ],
      },
      {
        heading: "Examination",
        points: [
          "**Inspect and palpate every injection site** at every visit - lipohypertrophy is often felt rather than seen, as a soft rubbery swelling; use a gel-lubricated fingertip sweep. [FIT India 2e]",
          "Look for **lipoatrophy** (dimpled hollows, now rare with human and analogue insulin), bruising, infection, and pigmentation at sites. [FIT India 2e]",
          "**Weight and BMI** at every visit - rising weight on insulin prompts review of snacking to prevent hypoglycaemia (a sign of over-insulinisation). [ADA 2026]",
          "**Visual acuity and fundus** - poor vision affects dialling and a rapid glucose fall can transiently worsen proliferative retinopathy. [ADA 2026]",
          "**Hand function and cognition** - grip, tremor, arthritis, and the ability to follow a titration rule; watch the patient give one injection in the clinic. [FIT India 2e]",
          "**Signs of catabolism**: wasting, dehydration, Kussmaul breathing or ketotic breath - these call for urgent insulin, often in hospital. [ADA 2026]",
          "**Postural blood pressure** - autonomic neuropathy increases hypoglycaemia risk and unawareness. [ADA 2026]",
          "**Feet**: monofilament and pulses - neuropathy suggests long disease and hypoglycaemia unawareness risk. [IWGDF 2023]",
        ],
      },
      {
        heading: "Minimal investigations",
        points: [
          "**HbA1c every 3 months** until stable - it cannot reflect a dose change sooner because of red-cell lifespan. [ADA 2026]",
          "**Self-monitored capillary glucose (SMBG)**: on basal insulin, **fasting value daily during titration**, then 2-3 times a week; on premix alternate fasting and pre-dinner; on basal-bolus before each meal and at bedtime. [ADA 2026]",
          "**One 3 a.m. reading** before increasing evening insulin for a high fasting value distinguishes underdosing, dawn phenomenon and Somogyi rebound. [RSSDI 2022]",
          "**A 7-point profile** (before and 2 hours after each meal, plus bedtime) before a major regimen change shows where the HbA1c comes from. [RSSDI 2022]",
          "**CGM** is recommended for people on any insulin regimen where available; target **time in range 70-180 mg/dL over 70%**, time below 70 under 4%, below 54 under 1% (in older or high-risk adults TIR over 50%, below 70 under 1%). [ADA 2026]",
          "**Creatinine and eGFR** - falling renal function reduces insulin clearance and is a common cause of new hypoglycaemia. [ADA 2026]",
          "**Check the glucometer against a laboratory venous value** once a year - a drifting meter drives wrong titration. [ADA 2026]",
          "**Do not order** C-peptide routinely before starting insulin in obvious type 2 diabetes - it does not change the decision; reserve for suspected type 1, LADA or FCPD. [RSSDI 2022]",
        ],
      },
      {
        heading: "Treatment - general measures",
        points: [
          "**Introduce insulin early as a normal step**, not a threat or punishment; show the 4 mm needle, let the patient give a saline or first dose in clinic - most fear goes after the first painless injection. [RSSDI 2022]",
          "**Teach hypoglycaemia** at the first insulin visit: symptoms, the **rule of 15** (15-20 g glucose, recheck in 15 minutes), carrying glucose tablets or sugar, and teaching a family member. [ADA 2026]",
          "**Consistent carbohydrate** at regular meal times for fixed-dose regimens (premix, NPH); **carbohydrate counting** with an insulin-to-carbohydrate ratio for basal-bolus in type 1. [ADA 2026]",
          "**Exercise**: check glucose before activity, take 15-30 g extra carbohydrate if below 100 mg/dL, avoid injecting into a limb about to be exercised, and reduce the pre-exercise bolus by 25-50%. [ADA 2026]",
          "**Driving**: check glucose before driving; do not drive if below 90 mg/dL; carry glucose in the vehicle; stop and treat at the first symptom. [ADA 2026]",
          "**Alcohol** only with food - alcohol blocks hepatic gluconeogenesis and causes delayed hypoglycaemia, sometimes the next morning. [ADA 2026]",
          "**Sharps disposal** in a hard, closed container (a thick plastic bottle) - never loose in household waste. [FIT India 2e]",
          "**Identification**: carry a card stating diabetes on insulin with emergency contact. [ADA 2026]",
          "**Written plan** in the local language: insulin name, dose, time, titration rule, hypo treatment and sick-day rules - and give one copy to the carer. [RSSDI 2022]",
        ],
      },
      {
        heading: "Treatment - drugs",
        points: [
          "**Keep metformin** (reduces dose and weight gain) and any **SGLT2 inhibitor or GLP-1 agonist**; **halve or stop the sulfonylurea** with basal insulin and **stop it when prandial insulin is added**; stop pioglitazone if oedema appears (insulin plus TZD increases heart failure). [ADA 2026]",
          "**Basal start in type 2**: **NPH or glargine 10 units (or 0.1-0.2 units/kg) once daily** - NPH at **bedtime (around 10 p.m.)**, glargine at any fixed time daily, degludec any time with at least 8 hours between doses. [ADA 2026]",
          "**Basal titration (fix fasting first)**: patient-led **increase of 2 units every 3 days** if fasting is above target on 3 consecutive days (RSSDI 3-0-3), or **1 unit daily** until fasting 80-130 mg/dL; **reduce by 4 units or 10-20%** for any value under 70 mg/dL or unexplained night symptoms. [ADA 2026]",
          "**Treat-to-target weekly algorithm** (useful in exams): mean fasting 180 or more - add 8 units; 140-179 - add 6; 120-139 - add 4; 100-119 - add 2; any value under 72 mg/dL - reduce 2-4 units. [Riddle 2003]",
          "**Over-basalisation**: basal over **0.5 units/kg/day**, a bedtime-to-morning glucose drop of 50 mg/dL or more, or hypoglycaemia with high HbA1c - stop increasing basal and **add a GLP-1 agonist or prandial insulin**. [ADA 2026]",
          "**Basal plus**: add **4 units or 10% of basal** of rapid-acting insulin before the largest meal (usually dinner or lunch in India), and reduce basal by the same amount if HbA1c is under 8%; titrate by **1-2 units (10-15%) twice a week** to a 2-hour post-meal value under 180 mg/dL. [ADA 2026]",
          "**Basal-bolus**: total daily dose **0.4-0.5 units/kg** (type 1 0.4-1.0 units/kg), **50% basal and 50% prandial split across three meals**; stepwise add boluses to other meals if needed. [ADA 2026]",
          "**Carbohydrate ratio and correction factor** for flexible dosing: insulin-to-carb ratio = **500 / total daily dose** (grams covered by 1 unit); correction factor = **1800 / TDD** for analogues (**1500 / TDD** for regular) - mg/dL fall per unit. [ADA 2026]",
          "**Premix start**: **0.2-0.3 units/kg/day** (or 10-12 units/day), split **2/3 before breakfast and 1/3 before dinner** for human 30/70 (50:50 for analogue premix); titrate the **morning dose against the pre-dinner value** and the **evening dose against next-morning fasting** by 2 units every 3 days. [RSSDI 2022]",
          "**Converting basal to premix**: give **80% of the total basal dose split 50:50** before breakfast and dinner; a third lunch-time dose of analogue premix can be added for a large lunch. [RSSDI 2022]",
          "**IDegAsp (degludec/aspart 70/30)**: 10 units once daily with the largest meal, titrated on fasting glucose; a second dose with another main meal can be added - it replaces basal plus with one pen. [RSSDI 2022]",
          "**Fixed-ratio combinations** of basal insulin with a GLP-1 agonist (glargine-lixisenatide, degludec-liraglutide) give basal and prandial control with less weight gain and hypoglycaemia than basal-bolus. [ADA 2026]",
          "**Timing**: **regular human insulin 30 minutes before the meal**; **rapid analogues 0-15 minutes before** (faster aspart at the start of the meal or up to 20 minutes after starting); **premix human 30 minutes before**, analogue premix just before the meal. [FIT India 2e]",
          "**Missed dose**: basal glargine or degludec - take when remembered the same day (degludec keeping 8 hours from the next dose); **missed bolus** - take within about an hour of starting the meal, otherwise skip and correct at the next meal; **never double** the next dose. [ADA 2026]",
          "**Hypoglycaemia is the main side effect**: reduce dose after any unexplained value under 70, relax targets in the elderly, and prefer analogue basal (glargine, degludec) if nocturnal hypoglycaemia occurs on NPH. [ADA 2026]",
          "**Other side effects**: weight gain (2-4 kg), lipohypertrophy, injection-site reactions, rare true allergy, insulin oedema, **hypokalaemia with IV insulin**, and transient worsening of retinopathy with very rapid correction. [Goodman and Gilman 14e]",
          "**Kidney disease**: insulin clearance falls - reduce doses progressively (often by 25-50%) as eGFR falls; prefer analogue basal; hypoglycaemia after dialysis sessions is common. [KDIGO 2022]",
          "**Pregnancy**: insulin is first-line; human insulin, **aspart, lispro, detemir and glargine** are all acceptable; requirements rise sharply after 20-24 weeks and fall abruptly after delivery - halve or stop at delivery in gestational diabetes. [ADA 2026]",
          "**Steroid-induced hyperglycaemia**: with once-daily morning prednisolone, give **morning NPH 0.1 units/kg per 10 mg prednisolone** (max 0.4 units/kg) and taper it with the steroid. [ADA 2026]",
          "**Stepping down**: once glucotoxicity resolves (often 2-3 months after an HbA1c over 10% at diagnosis), fasting values fall and hypoglycaemia appears - reduce insulin and switch to oral or GLP-1 therapy if C-peptide reserve allows. [ADA 2026]",
          "**Once-weekly basal insulin (icodec)** is approved in several countries for type 2 diabetes - an option when daily injection is not possible, with slightly more level 1 hypoglycaemia. [ADA 2026]",
        ],
      },
      {
        heading: "Devices and how to use them",
        points: [
          "**Choice of device**: **reusable or disposable pens** are easier, more accurate for small doses and preferred for the elderly and visually impaired; **vial and syringe** is cheapest and allows mixing regular with NPH in one shot. [FIT India 2e]",
          "**Needle length**: **4 mm pen needle** for all adults and children at **90 degrees without a skin fold** (children and very thin adults: 4 mm with a lifted fold); insulin syringes carry 6-8 mm needles and **need a pinched skin fold** (or a 45 degree angle) to avoid intramuscular injection. [FIT India 2e]",
          "**Pen technique**: (1) wash hands, check insulin name and expiry; (2) **roll 10 times and tip 10 times** for NPH or premix until uniformly milky; (3) fit a new needle; (4) **prime 2 units** pointing upward until a drop appears; (5) dial the dose. [FIT India 2e]",
          "**Pen technique continued**: (6) insert at 90 degrees into clean skin; (7) press the button fully; (8) **hold for 10 seconds** before withdrawing; (9) remove and discard the needle into a sharps container; (10) recap the pen - never store with the needle on (air enters, insulin leaks). [FIT India 2e]",
          "**Vial and syringe technique**: match **U-40 syringe with U-40 vial, U-100 with U-100**; roll cloudy vials; wipe the rubber top; draw air equal to the dose and inject it into the vial; invert, withdraw the dose and flick out bubbles; lift a skin fold, inject at 90 degrees and hold 5 seconds. [FIT India 2e]",
          "**Mixing in one syringe**: **clear before cloudy** - inject air into NPH first, then into regular, draw up **regular first then NPH**, and inject immediately; **never mix glargine, detemir or degludec** with any other insulin. [FIT India 2e]",
          "**Injection sites**: **abdomen** (fastest; stay 2.5-5 cm, two finger widths, from the navel) for prandial and premix; **front and outer thigh** (slower) or **buttock** for NPH at bedtime; **back of upper arm** only if someone else injects. [FIT India 2e]",
          "**Rotation**: divide the site into quadrants, use one quadrant per week moving clockwise, and space each injection **at least 1 cm (a finger width)** from the last - this prevents lipohypertrophy. [FIT India 2e]",
          "**If lipohypertrophy is found**: stop using the lump, move to healthy skin and **reduce the dose by about 10-20%** at the switch while monitoring closely, because absorption rises suddenly. [FIT India 2e]",
          "**Needle reuse** (common in India to save cost) blunts and bends the tip, causes pain, bleeding and lipohypertrophy, and should be avoided - if unavoidable, never beyond a few times and never shared. [FIT India 2e]",
          "**Storage**: unopened insulin at **2-8 degrees C** in the fridge door (never the freezer; discard if frozen); **in-use at room temperature below 30 degrees C for 28 days** (detemir 42 days, degludec and glargine U300 56 days); away from sunlight; where there is no fridge use an **earthen pot (matka) with wet sand**. [FIT India 2e]",
          "**Travel**: carry insulin in hand luggage (hold baggage can freeze) in an insulated pouch, with a doctor's note, spare needles, meter and glucose. [FIT India 2e]",
          "**Common errors**: not resuspending NPH, withdrawing the pen needle before 10 seconds, injecting through clothes, same spot daily, using a U-40 syringe with U-100 insulin, regular insulin given with (not 30 minutes before) the meal, and using a turbid or clumped clear insulin. [FIT India 2e]",
        ],
      },
      {
        heading: "Special situations",
        points: [
          "**Sick days**: **never stop basal insulin**; check glucose every 4 hours and ketones if over 250 mg/dL; give an **extra 10-20% of the total daily dose as rapid-acting insulin every 2-4 hours** while ketones are moderate or high; drink 100-200 mL fluid hourly; come to hospital for persistent vomiting, ketones or drowsiness. [ADA 2026]",
          "**Ramadan**: reduce basal by **20-40%**, take the main dose at **iftar**, halve the morning premix dose and give it at suhoor, and **break the fast** if glucose is under 70 or over 300 mg/dL. [IDF-DAR 2021]",
          "**Surgery**: on the evening before, give **75-80% of usual basal** (NPH or glargine); omit prandial insulin while fasting; use an IV insulin-glucose infusion for long procedures or poor control. [ADA 2026]",
          "**Hospital**: basal-bolus with correction doses is preferred over sliding scale alone; target **140-180 mg/dL** in most inpatients. [ADA 2026]",
        ],
      },
      {
        heading: "Follow-up, monitoring and when to refer",
        points: [
          "**Phone or clinic contact every 1-2 weeks during titration** to review the log and dose changes; in-person review at 4-6 weeks with injection-site check and technique demonstration. [RSSDI 2022]",
          "**Targets**: fasting **80-130 mg/dL**, 2-hour post-meal **under 180 mg/dL**, HbA1c **under 7%** for most; relax to fasting 100-150 and HbA1c under 8% in elderly, living alone, or with hypoglycaemia unawareness. [ADA 2026]",
          "**Every visit**: glucose log, hypoglycaemia episodes, weight, injection sites, storage and needle use, and whether the sulfonylurea has been stopped. [FIT India 2e]",
          "**Watch for falling requirements** - new hypoglycaemia in a long-standing diabetic suggests declining eGFR, weight loss (TB, malignancy), hypothyroidism or adrenal insufficiency. [ADA 2026]",
          "**Annual**: renal function, urine ACR, fundus, feet and lipids as for all diabetics. [ADA 2026]",
          "**Refer** for type 1 diabetes, recurrent severe or nocturnal hypoglycaemia, hypoglycaemia unawareness, pregnancy, very high doses (over 1.5-2 units/kg - consider severe insulin resistance), suspected systemic insulin allergy, or failure to reach target on basal-bolus. [ADA 2026]",
        ],
      },
    ],
    tables: [
      {
        heading: "Drugs: dose, duration and side effects",
        columns: ["Drug", "Mechanism", "Dose and duration", "Side effects", "How to take"],
        rows: [
          ["Regular (soluble) human insulin", "Short-acting; hexamers - onset 30-60 min, peak 2-4 h, lasts 6-8 h", "Prandial: 4 units or 10% of basal per meal, titrate; IV 0.1 units/kg/h in DKA", "Hypoglycaemia 4-6 h after meal, weight gain", "SC 30 min before meal, abdomen; clear"],
          ["Aspart / lispro / glulisine", "Rapid analogue; monomers - onset 10-15 min, peak 1-2 h, lasts 3-5 h", "Prandial: 4 units or 10% of basal with largest meal; basal-bolus 50% of TDD split over meals", "Hypoglycaemia (less late), weight gain", "SC 0-15 min before meal; skip if meal skipped"],
          ["NPH (isophane) human insulin", "Intermediate; protamine crystals - onset 1-2 h, peak 4-8 h, lasts 12-16 h", "Start 10 units or 0.1-0.2 units/kg at bedtime; +2 units every 3 days", "Nocturnal hypoglycaemia, weight gain", "Roll and tip 10 times; bedtime, thigh; cloudy"],
          ["Glargine U100 / detemir", "Long-acting; precipitates or binds albumin - flat 20-24 h", "Start 10 units or 0.1-0.2 units/kg OD; titrate to fasting 80-130", "Less night hypoglycaemia than NPH; weight gain", "Same time daily; never mix with other insulin"],
          ["Degludec / glargine U300", "Ultra-long; multi-hexamers or depot - over 24-42 h", "Start 10 units OD; titrate every 3-4 days", "Lowest night hypoglycaemia; cost", "Flexible time (degludec, 8 h apart minimum)"],
          ["Premix human 30/70", "30% regular plus 70% NPH - dual peak", "0.2-0.3 units/kg/day, 2/3 before breakfast, 1/3 before dinner", "Hypoglycaemia if meal missed, weight gain", "Roll and tip; 30 min before breakfast and dinner"],
          ["Biphasic aspart 30/70 / IDegAsp 70/30", "Analogue premix or co-formulation", "Aspart 30: 0.2-0.3 units/kg split BD; IDegAsp: 10 units OD with largest meal", "Hypoglycaemia, weight gain", "Just before the meal; IDegAsp is clear, no mixing"],
        ],
      },
      {
        heading: "Insulin regimen types - starting dose and titration",
        columns: ["Regimen", "Best for", "Starting dose", "Titrate against and step"],
        rows: [
          ["Basal only", "Most type 2 starting insulin", "10 units or 0.1-0.2 units/kg at bedtime", "Fasting glucose; +2 units every 3 days, -4 units or 10-20% for hypo"],
          ["Basal plus", "Fasting at target, HbA1c not", "Basal plus 4 units rapid with largest meal", "2-h post-meal of that meal; 1-2 units twice weekly"],
          ["Basal-bolus", "Type 1; type 2 needing flexibility", "0.4-0.5 units/kg/day, 50% basal, 50% over three meals", "Pre-meal and bedtime values; 10-20% per step"],
          ["Premix twice daily", "Fixed meals, limited literacy, cost", "0.2-0.3 units/kg/day, 2/3 morning, 1/3 evening", "Morning dose vs pre-dinner; evening dose vs fasting; 2 units every 3 days"],
        ],
      },
      {
        heading: "Insulin delivery devices",
        columns: ["Device", "Best for", "Technique key steps", "Common errors"],
        rows: [
          ["Disposable or reusable pen with 4 mm needle", "Most patients; elderly; visually impaired (click dial)", "Resuspend cloudy, new needle, prime 2 units, dial, 90 degrees, hold 10 s", "Skipping priming, withdrawing early, needle left on, reusing needles"],
          ["Vial and insulin syringe", "Low cost; mixing regular with NPH", "Match U-40 or U-100, air in, draw dose, clear before cloudy, pinch fold", "Syringe-vial strength mismatch, bubbles, no skin fold"],
          ["Continuous glucose monitor", "Anyone on insulin, hypo unawareness", "Sensor on arm for 14 days, scan or read app, act on trend arrows", "Treating sensor lag after rapid change, not calibrating against symptoms"],
          ["Insulin pump (CSII)", "Type 1 with specialist support", "Rapid analogue basal rates plus meal boluses via cannula changed every 2-3 days", "Cannula blockage leading to DKA within hours"],
        ],
      },
    ],
    redFlags: [
      "Recurrent, nocturnal or severe hypoglycaemia, or hypoglycaemia unawareness - reduce the dose now and relax targets rather than continuing titration.",
      "Glucose over 250 mg/dL with vomiting, abdominal pain or Kussmaul breathing on insulin - check ketones and treat as DKA.",
      "Insulin stopped because of cost, fear or illness with glucose over 300 mg/dL - restart the same day and admit if ketotic.",
      "Falling insulin needs with unexplained hypoglycaemia in long-standing diabetes - look for renal failure, adrenal insufficiency, hypothyroidism or weight loss from TB or cancer.",
      "Pump user with unexplained high glucose - assume cannula failure, give SC insulin by pen and check ketones.",
      "Injection-site abscess or hot indurated lump with fever - stop using the site and treat the infection.",
      "Generalised urticaria, angioedema or wheeze after injection - stop and refer for true insulin allergy.",
    ],
    pearls: [
      "Start basal 10 units at bedtime and add 2 units every 3 days against the fasting sugar - this one sentence answers most insulin initiation questions.",
      "Never increase evening insulin for a high fasting sugar without one 3 a.m. reading - you will worsen a Somogyi rebound.",
      "Regular human insulin goes in 30 minutes before food; rapid analogues go in at the plate.",
      "Over-basalisation: fasting at target, basal over 0.5 units/kg and HbA1c still high - add prandial insulin or a GLP-1 agonist, never more basal.",
      "Palpate injection sites every visit - lipohypertrophy is the invisible cause of erratic control; reduce the dose by 10-20% when moving to fresh skin.",
      "A U-40 syringe with U-100 insulin gives 2.5 times the intended dose - match the syringe to the vial every time.",
      "Halve the sulfonylurea when basal starts and stop it when prandial insulin is added - otherwise expect iatrogenic hypoglycaemia.",
      "Unopened insulin in the fridge, never frozen; in-use pen at room temperature for 28 days; a matka with wet sand works where there is no fridge.",
    ],
    references: [
      "American Diabetes Association. Standards of Care in Diabetes - 2026. Section 9: Pharmacologic approaches to glycemic treatment. Diabetes Care 2026.",
      "RSSDI Clinical Practice Recommendations for the Management of Type 2 Diabetes Mellitus, 2022.",
      "Forum for Injection Technique (FIT) India Recommendations, 2nd edition.",
      "IDF-DAR. Diabetes and Ramadan: Practical Guidelines, 2021.",
      "Riddle MC et al. The treat-to-target trial. Diabetes Care 2003.",
      "KDIGO 2022 Clinical Practice Guideline for Diabetes Management in Chronic Kidney Disease.",
      "Goodman and Gilman's The Pharmacological Basis of Therapeutics, 14th edition, 2023.",
      "Williams Textbook of Endocrinology, 15th edition, 2024.",
      "Harrison's Principles of Internal Medicine, 22nd edition, 2025.",
    ],
  },
  "endocrine-diabetes-complication-screening": {
    oneLiner:
      "Screen every person with diabetes - **type 2 from the day of diagnosis, type 1 from 5 years after** - every year with a **dilated fundus examination, urine albumin-creatinine ratio plus eGFR, a 10 g monofilament and pulse foot examination, and fasting lipids**, and act on what is found: **anti-VEGF or laser** for sight-threatening retinopathy, **ACE inhibitor or ARB plus SGLT2 inhibitor (plus finerenone or a GLP-1 agonist)** for kidney disease, **statins** for all over 40, and **offloading plus education** for the at-risk foot.",
    sections: [
      {
        heading: "Definition and the classification that matters",
        points: [
          "**Chronic complications** are **microvascular** (retinopathy, nephropathy, neuropathy - driven mainly by glucose) and **macrovascular** (coronary, cerebrovascular, peripheral arterial disease - driven as much by BP, LDL and smoking), plus the **diabetic foot** where neuropathy, ischaemia and infection meet. [Harrison 22e]",
          "**When to start**: type 2 at diagnosis (hyperglycaemia has been present unrecognised for 5-10 years and 15-20% already have retinopathy); type 1 **5 years after diagnosis** (and from puberty in children). [ADA 2026]",
          "**Retinopathy grading** (International Clinical DR scale): no DR, **mild NPDR** (microaneurysms only), **moderate NPDR**, **severe NPDR by the 4-2-1 rule**, **proliferative DR**, with **diabetic macular oedema** graded separately as centre-involving or not - shown in the table below. [ADA 2026]",
          "**4-2-1 rule for severe NPDR**: intraretinal haemorrhages in **4 quadrants**, venous beading in **2 quadrants**, or IRMA in **1 quadrant** - about half progress to PDR within a year. [AAO PPP 2024]",
          "**Diabetic kidney disease** is staged by **KDIGO GFR categories (G1-G5) and albuminuria categories**: **A1 under 30 mg/g, A2 30-300 mg/g, A3 over 300 mg/g** (3 and 30 mg/mmol) on urine ACR, confirmed in **2 of 3 samples over 3-6 months**. [KDIGO 2024]",
          "**Loss of protective sensation (LOPS)** is failure to feel a **10 g monofilament** at one or more plantar sites; the **IWGDF 2023 risk categories 0-3** (table below) set how often the foot is examined. [IWGDF 2023]",
          "**Diabetic foot infection** is classed by **IWGDF/IDSA**: uninfected, **mild** (skin and subcutis, erythema 0.5-2 cm), **moderate** (erythema over 2 cm or deeper tissue, no SIRS), **severe** (with SIRS), with suffix (O) for osteomyelitis; **Wagner grade 0-5** describes ulcer depth and gangrene. [IWGDF 2023]",
        ],
      },
      {
        heading: "Pathophysiology and pathoanatomy",
        points: [
          "**Why only some tissues are damaged**: retinal endothelium, mesangial cells and Schwann cells take up glucose through insulin-independent **GLUT1** and cannot down-regulate it, so intracellular glucose rises with blood glucose. [Harrison 22e]",
          "Excess intracellular glucose drives **four pathways** - **polyol** (aldose reductase uses NADPH, depleting glutathione; sorbitol swells cells), **advanced glycation end-products** (binding RAGE, activating NF-kB), **PKC-beta activation** (VEGF, TGF-beta, permeability) and **hexosamine flux** - unified by **mitochondrial superoxide overproduction**. [Williams Endocrinology 15e]",
          "**Metabolic memory (legacy effect)**: early good control keeps protecting for decades (DCCT-EDIC, UKPDS follow-up), because glycation and epigenetic changes persist - the reason to control glucose early. [ADA 2026]",
          "**Retina**: **pericyte loss** weakens capillaries into **microaneurysms** (earliest sign, dot haemorrhages); basement membrane thickening and capillary closure cause **ischaemia** seen as cotton-wool spots, venous beading and IRMA. [Harrison 22e]",
          "Ischaemic retina releases **VEGF**, which drives **new vessels** at the disc or elsewhere (PDR) that bleed into the vitreous and contract to cause **tractional detachment** - **pan-retinal photocoagulation** destroys the ischaemic VEGF-producing retina and **anti-VEGF injections** block it directly. [AAO PPP 2024]",
          "Breakdown of the **blood-retina barrier** leaks fluid and lipoprotein into the macula - **macular oedema** with hard exudates - the **commonest cause of visual loss in type 2**, possible at any DR stage and treated with **intravitreal anti-VEGF**. [ADA 2026]",
          "**Kidney - hyperfiltration first**: increased proximal **SGLT2 sodium-glucose reabsorption** reduces sodium at the macula densa, switching off **tubuloglomerular feedback** so the afferent arteriole dilates, while **angiotensin II constricts the efferent** - intraglomerular hypertension results. [KDIGO 2024]",
          "Glomerular hypertension and metabolic injury cause **GBM thickening, mesangial expansion, Kimmelstiel-Wilson nodules** and **podocyte loss**, so albumin leaks (albuminuria) and later GFR falls; mineralocorticoid-receptor overactivation adds **inflammation and fibrosis**. [Harrison 22e]",
          "**Why each kidney drug works**: ACE inhibitors and ARBs dilate the efferent arteriole, SGLT2 inhibitors restore tubuloglomerular feedback and constrict the afferent - both lower glomerular pressure (hence the **expected early eGFR dip up to 30%**); **finerenone** blocks MR-driven fibrosis; GLP-1 agonists reduce inflammation and albuminuria. [KDIGO 2024]",
          "**Neuropathy** is a length-dependent axonopathy from polyol and oxidative injury plus **vasa nervorum ischaemia**; **small fibres** fail first (burning pain, loss of pain and temperature), then **large fibres** (vibration, position sense, ankle jerks) in a glove-and-stocking pattern. [Harrison 22e]",
          "**Motor neuropathy** wastes the intrinsic foot muscles, producing **claw toes and prominent metatarsal heads** that concentrate plantar pressure - callus forms there and the ulcer grows under it. [IWGDF 2023]",
          "**Autonomic neuropathy** stops sweating (dry, fissured skin that admits bacteria), opens arteriovenous shunts (warm foot with distended veins), and causes gastroparesis, postural hypotension, resting tachycardia, erectile dysfunction, bladder atony and **hypoglycaemia unawareness**. [ADA 2026]",
          "**Ulcer pathway**: **neuropathy plus deformity plus unfelt trauma** (barefoot walking, tight shoes, hot surfaces) produces most ulcers; **PAD** (tibial and below-knee disease with medial calcification) prevents healing, and impaired neutrophil function lets infection spread along foot compartments. [IWGDF 2023]",
          "**Charcot neuro-osteoarthropathy**: in an insensate foot, minor trauma triggers a **RANKL-driven inflammatory osteoclastic surge** and fractures and dislocations that go unfelt - the midfoot collapses into a **rocker-bottom** deformity if walking continues. [IWGDF 2023]",
          "**Macrovascular disease**: insulin resistance produces **high triglycerides, low HDL and small dense LDL**, plus endothelial dysfunction, platelet hyperactivity and glycation of LDL - atherosclerosis is accelerated and often silent. [Harrison 22e]",
          "**Calcified tibial arteries** are incompressible, so the **ankle-brachial index can be falsely normal or over 1.3** - a toe pressure or toe-brachial index is then needed. [IWGDF 2023]",
        ],
      },
      {
        heading: "History in the OPD",
        points: [
          "**Duration of diabetes and control** (HbA1c trend), BP and lipid history, and smoking - these predict which complication to expect. [ADA 2026]",
          "**Eyes**: blurred or distorted central vision (macular oedema), sudden floaters or a curtain (vitreous haemorrhage, detachment), date of last dilated exam - most retinopathy is asymptomatic, so a normal answer does not reassure. [ADA 2026]",
          "**Kidneys**: frothy urine, ankle swelling, nocturia, NSAID use, and recurrent UTI; ask about haematuria, rash, joint pain or haemoptysis that suggest a **non-diabetic glomerular disease**. [KDIGO 2024]",
          "**Neuropathic symptoms**: numbness, tingling, **burning worse at night**, feeling of walking on cotton wool, loss of slippers without noticing, unsteadiness in the dark (large-fibre loss). [ADA 2026]",
          "**Autonomic symptoms**: dizziness on standing, early satiety and vomiting (gastroparesis), nocturnal diarrhoea, erectile dysfunction, incomplete bladder emptying, sweating while eating, and **loss of hypoglycaemia warning symptoms**. [ADA 2026]",
          "**Foot history**: previous ulcer or amputation (the strongest predictor of the next ulcer), barefoot walking (home, temple, fields), footwear, self-treatment of corns with chemicals or blades, hot-water fomentation. [IWGDF 2023]",
          "**Claudication and rest pain** - calf pain on walking relieved by rest, or night pain relieved by hanging the leg down - point to PAD, which is often painless in neuropathy. [IWGDF 2023]",
          "**Cardiac symptoms including atypical ones**: exertional breathlessness, fatigue, reduced effort tolerance - silent ischaemia is common with autonomic neuropathy. [ADA 2026]",
          "**Differential causes of neuropathy**: alcohol, **long-term metformin (B12)**, hypothyroidism, CKD, HIV, drugs (isoniazid without pyridoxine, chemotherapy), and **leprosy** (patches, asymmetric deficit, thickened nerves). [RSSDI 2022]",
          "**Mood, sleep and adherence**: depression (PHQ-2 then PHQ-9), snoring and daytime sleepiness (OSA), and cost of drugs - each worsens outcomes and changes management. [ADA 2026]",
          "**TB symptoms** at each visit (cough 2 weeks or more, fever, weight loss) and **oral symptoms** (bleeding gums) - both are bidirectionally linked with poor control. [NTEP 2024]",
          "**Pregnancy plans** - retinopathy worsens in pregnancy, and ACE inhibitors, ARBs, statins and finerenone must be stopped before conception. [ADA 2026]",
        ],
      },
      {
        heading: "Examination",
        points: [
          "**Visual acuity with a Snellen chart and pinhole**, then **dilated fundoscopy** (tropicamide 1% with phenylephrine 2.5%) or a **non-mydriatic fundus photograph** - look for microaneurysms, haemorrhages, hard exudates near the macula, cotton-wool spots, venous beading and new vessels. [AAO PPP 2024]",
          "**Monofilament technique**: show it on the patient's hand first; with eyes closed, press the 10 g filament perpendicular to the skin until it **buckles for 1-2 seconds** at the plantar hallux and **1st, 3rd and 5th metatarsal heads**, avoiding callus; ask 'yes' each time, with sham applications - any site missed is LOPS. [IWGDF 2023]",
          "**Vibration**: a **128 Hz tuning fork** on the dorsum of the distal phalanx of the great toe - loss when the examiner still feels it indicates large-fibre neuropathy; add **pinprick**, **ankle reflexes** and proprioception. [IWGDF 2023]",
          "**Foot inspection**: callus, fissures, interdigital maceration, fungal nails, claw and hammer toes, bunions, **Charcot deformity**, and skin temperature difference between feet (over 2 degrees C suggests active Charcot or inflammation); look inside the shoes. [IWGDF 2023]",
          "**Pulses**: dorsalis pedis (lateral to extensor hallucis longus) and posterior tibial (behind medial malleolus); absent pulses or claudication - measure the **ABI** (under 0.9 PAD, over 1.3 incompressible). [IWGDF 2023]",
          "**Probe-to-bone** in any infected ulcer: a sterile blunt metal probe striking bone strongly supports **osteomyelitis**. [IWGDF 2023]",
          "**Leprosy screen** when neuropathy is asymmetric: thickened ulnar, common peroneal or greater auricular nerves and hypopigmented anaesthetic patches. [RSSDI 2022]",
          "**Postural blood pressure** after 3 minutes standing - a fall of **20 systolic or 10 diastolic** indicates autonomic neuropathy; **resting heart rate over 100** suggests cardiac autonomic neuropathy. [ADA 2026]",
          "**BP, weight, waist, oedema and signs of heart failure** at every visit. [ADA 2026]",
          "**Mouth and skin**: periodontitis, candidiasis, necrobiosis lipoidica and shin spots. [ADA 2026]",
        ],
      },
      {
        heading: "Minimal investigations",
        points: [
          "**Urine albumin-creatinine ratio** on a spot early-morning sample yearly; repeat abnormal values (fever, exercise, UTI, menstruation, heart failure and very high glucose raise it transiently) and confirm on **2 of 3 samples**. [KDIGO 2024]",
          "**Serum creatinine with eGFR** (CKD-EPI 2021) yearly, or every 3-6 months if eGFR is under 60 or ACR is raised; **potassium** when on ACE inhibitor, ARB or finerenone. [KDIGO 2024]",
          "**Fasting lipid profile** yearly - LDL-C drives statin intensity. [ADA 2026]",
          "**ECG** at baseline and with any symptom; **no routine stress testing or coronary CT in asymptomatic patients** - it does not improve outcomes over treating risk factors. [ADA 2026]",
          "**Retinal imaging**: fundus photography (including validated **AI-based grading**) is acceptable for screening; **OCT** confirms macular oedema. [ADA 2026]",
          "**ABI** if pulses are absent or claudication; **toe pressure** if ABI is over 1.3; **arterial Doppler** before any debridement of an ischaemic foot. [IWGDF 2023]",
          "**For an infected foot ulcer**: plain X-ray of the foot (osteomyelitis, gas, foreign body), deep-tissue culture after debridement (not a surface swab), CBC, CRP or ESR; **MRI** if osteomyelitis is uncertain. [IWGDF 2023]",
          "**Serum B12** in anyone with neuropathy or on long-term metformin; **TSH** if neuropathy or unexplained hypoglycaemia. [ADA 2026]",
          "**Nerve conduction studies are not needed** for typical distal symmetric neuropathy - only for atypical, asymmetric or rapidly progressive disease. [ADA 2026]",
        ],
      },
      {
        heading: "Treatment - general measures",
        points: [
          "**Control the drivers**: HbA1c under 7% (individualised), **BP under 130/80 mmHg**, LDL to target, and **stop smoking** - multifactorial control (Steno-2) halved cardiovascular events and deaths. [ADA 2026]",
          "**Lower a very high HbA1c over months, not weeks**, and examine the fundus before intensifying - rapid falls transiently worsen retinopathy (early worsening). [ADA 2026]",
          "**Foot education (best-evidence intervention)**: **never walk barefoot** (including indoors and at temples), inspect the soles daily with a mirror, wash and dry between toes, moisturise but not between toes, cut nails straight, test bath water with the elbow, no hot-water bottles, no chemical corn plasters. [IWGDF 2023]",
          "**Footwear**: closed, well-fitting shoes with space for toes; **MCR (microcellular rubber) footwear or custom insoles** for LOPS or deformity; inspect inside shoes before wearing. [IWGDF 2023]",
          "**Diet for kidney disease**: protein about **0.8 g/kg/day** (do not restrict below), **sodium under 2 g/day** (5 g salt), and avoid NSAIDs and nephrotoxins. [KDIGO 2024]",
          "**Exercise** with appropriate footwear; with LOPS, moderate weight-bearing walking is fine if footwear is good and feet are checked; avoid heavy straining in proliferative retinopathy. [ADA 2026]",
          "**Gastroparesis diet**: small frequent low-fat, low-fibre meals, liquids or pureed food, and matching insulin timing to delayed absorption. [ADA 2026]",
          "**Vaccination**: influenza yearly, pneumococcal, hepatitis B, zoster - diabetics have worse outcomes from these infections. [ADA 2026]",
          "**Dental review** yearly and treat periodontitis. [ADA 2026]",
        ],
      },
      {
        heading: "Treatment - drugs",
        points: [
          "**ACE inhibitor or ARB** for anyone with diabetes, hypertension and albuminuria (and for albuminuria even with normal BP), titrated to the **maximum tolerated dose**: **ramipril 2.5 mg OD to 10 mg**, **enalapril 5-20 mg BD**, **telmisartan 40-80 mg OD**, **losartan 50-100 mg OD**. [KDIGO 2024]",
          "**ACEi/ARB monitoring**: check creatinine and potassium in **1-2 weeks**; accept a creatinine rise **up to 30%**; stop and investigate if more (volume depletion, renal artery stenosis) or K over 5.5; **never combine ACE inhibitor with ARB**; stop in pregnancy; ACE-inhibitor cough - switch to ARB. [KDIGO 2024]",
          "**SGLT2 inhibitor for CKD with eGFR 20 or more**, regardless of HbA1c: **dapagliflozin 10 mg OD** or **empagliflozin 10 mg OD**, continued until dialysis - slows eGFR decline and reduces heart failure admissions (DAPA-CKD, EMPA-KIDNEY). [KDIGO 2024]",
          "**Finerenone** (non-steroidal MR antagonist) for persistent albuminuria (ACR 30 or more) on maximum RAS blockade with **K 5.0 or less** and **eGFR 25 or more**: **10 mg OD if eGFR 25-59, 20 mg OD if 60 or more**; check K at 4 weeks - continue if K 5.5 or less. [KDIGO 2024]",
          "**GLP-1 agonist with kidney benefit**: **semaglutide 1 mg weekly** reduced kidney failure, CV death and all-cause death in type 2 diabetes with CKD (FLOW) - add when further glucose lowering or cardio-renal risk reduction is needed. [ADA 2026]",
          "**Statins for all with diabetes aged 40-75**: at least **moderate intensity (atorvastatin 10-20 mg, rosuvastatin 5-10 mg)**; **high intensity (atorvastatin 40-80 mg, rosuvastatin 20-40 mg)** if one or more ASCVD risk factors (LDL target under 70 mg/dL) or established ASCVD (target **under 55 mg/dL**). [ADA 2026]",
          "**Add ezetimibe 10 mg OD** if LDL remains above target on maximally tolerated statin; **PCSK9 inhibitor or inclisiran** for very high risk; **bempedoic acid 180 mg** for statin intolerance. [ADA 2026]",
          "**Aspirin 75-150 mg OD for secondary prevention**; in primary prevention only for high-risk patients after discussing bleeding - not routine. [ADA 2026]",
          "**Fenofibrate 145-160 mg OD** slows retinopathy progression (FIELD, ACCORD-Eye, LENS) - an adjunct, not a substitute for ophthalmology; reduce dose in CKD. [ADA 2026]",
          "**Retinopathy treatment (ophthalmologist)**: **intravitreal anti-VEGF** (ranibizumab 0.5 mg, aflibercept 2 mg or bevacizumab 1.25 mg monthly loading) for centre-involving macular oedema and as alternative to PRP in PDR; **pan-retinal photocoagulation** for PDR; **vitrectomy** for non-clearing haemorrhage or traction. [AAO PPP 2024]",
          "**Painful neuropathy first-line** (any one, choose by comorbidity): **pregabalin 75 mg at night, then 75-150 mg BD** (max 300 mg/day; reduce in CKD; dizziness, oedema, weight gain), **duloxetine 30 mg OD for a week then 60 mg** (nausea; avoid in liver disease, eGFR under 30), or **amitriptyline 10-25 mg at night**, up to 75 mg (anticholinergic; avoid in elderly, glaucoma, IHD). [ADA 2026]",
          "**Gabapentin 300 mg at night, titrated to 300-600 mg TDS** (max 3600 mg/day, renal dose adjustment) is a cheaper alternative; **topical capsaicin 8% patch** or lidocaine for localised pain; **avoid opioids** including tramadol for long-term use. [ADA 2026]",
          "**Gastroparesis**: **metoclopramide 10 mg 30 minutes before meals** for up to 5 days at a time (tardive dyskinesia risk) or **domperidone 10 mg TDS** for short periods (QT prolongation); **stop GLP-1 agonists and pramlintide** which slow emptying. [ADA 2026]",
          "**Erectile dysfunction**: **sildenafil 50 mg 1 hour before intercourse** (25-100 mg) or **tadalafil 10-20 mg** - **absolutely contraindicated with nitrates**. [ADA 2026]",
          "**Orthostatic hypotension**: stop offending drugs, raise the head of the bed, compression stockings, salt and fluids; **midodrine 2.5-10 mg TDS** (not at bedtime) or **fludrocortisone 0.1 mg OD** if needed. [ADA 2026]",
          "**Mild diabetic foot infection**: oral **amoxicillin-clavulanate 625 mg TDS** or **cephalexin 500 mg QID** (clindamycin if penicillin allergic) for **1-2 weeks**, plus debridement and offloading. [IWGDF 2023]",
          "**Moderate or severe foot infection**: admit, IV **piperacillin-tazobactam 4.5 g 6-8 hourly** or **amoxicillin-clavulanate 1.2 g IV 8 hourly** (add MRSA cover if risk), urgent surgical debridement; soft tissue 1-2 weeks (up to 3-4 if slow), **osteomyelitis about 6 weeks, or 3 weeks after resection of infected bone**. [IWGDF 2023]",
          "**Vitamin B12 deficiency on metformin**: **methylcobalamin 1500 microgram daily orally**, or IM cyanocobalamin 1000 microgram if severe or neurological. [ADA 2026]",
          "**Drug dose review as eGFR falls**: metformin (cap at 1000 mg at eGFR 30-45, stop under 30), sitagliptin and vildagliptin dose reduction, avoid glibenclamide, reduce insulin, gabapentinoids reduced. [KDIGO 2022]",
        ],
      },
      {
        heading: "Acute presentation and emergency management",
        points: [
          "**Infected or ischaemic foot**: assess depth (probe-to-bone), SIRS, pulses and ABI; **same-day surgical referral** for abscess, gas, necrosis, wet gangrene or severe infection - surgery drains and debrides; antibiotics alone fail. [IWGDF 2023]",
          "**Ulcer care principles**: sharp debridement of callus and slough, moist dressing, **offloading with a total contact cast** (gold standard for plantar neuropathic ulcers) or knee-high removable walker, glucose control, revascularisation if ischaemic. [IWGDF 2023]",
          "**Acute Charcot foot** - a hot, red, swollen, often painless foot with intact skin in a neuropathic patient: **immobilise at once in a non-removable knee-high cast** and refer; confirm with X-ray and MRI (marrow oedema); do not treat as cellulitis or gout alone. [IWGDF 2023]",
          "**Sudden visual loss or new shower of floaters**: vitreous haemorrhage or detachment - same-day ophthalmology. [AAO PPP 2024]",
          "**Critical limb ischaemia** - rest pain, gangrene, non-healing ulcer with absent pulses - urgent vascular referral for revascularisation before any major debridement. [IWGDF 2023]",
          "**Rapid eGFR fall or hyperkalaemia over 6.0 mmol/L** on RAS blockers or finerenone - stop the drug, treat potassium and look for volume depletion or obstruction. [KDIGO 2024]",
        ],
      },
      {
        heading: "Follow-up, monitoring and when to refer",
        points: [
          "**Annual package**: dilated fundus, urine ACR and eGFR, monofilament plus pulses foot examination, lipids, B12 on metformin; **BP, weight and foot inspection at every visit**. [ADA 2026]",
          "**Eye interval**: yearly; **every 1-2 years** if no retinopathy on one or more exams with good control; any retinopathy - yearly or more; **pregnancy - before conception or first trimester, then each trimester and for 1 year postpartum**. [ADA 2026]",
          "**Kidney interval**: ACR and eGFR yearly; **every 3-6 months** at eGFR under 60 or with albuminuria; refer to nephrology at **eGFR under 30**, rapid decline (over 5 mL/min/year), ACR over 300 despite treatment, active sediment or uncertain cause. [KDIGO 2024]",
          "**Foot review by IWGDF risk**: category 0 yearly, 1 every 6-12 months, 2 every 3-6 months, 3 every 1-3 months. [IWGDF 2023]",
          "**Refer to ophthalmology**: any retinopathy beyond mild NPDR, any macular oedema or unexplained visual loss - PDR and centre-involving DMO urgently. [ADA 2026]",
          "**Suspect non-diabetic kidney disease** (and refer) with heavy proteinuria without retinopathy, haematuria or casts, rapid eGFR fall, or proteinuria within 5 years of type 1 onset. [KDIGO 2024]",
          "**Refer to a foot team or vascular surgeon** for active ulcer, suspected Charcot, absent pulses with ulcer, ABI under 0.5 or rest pain. [IWGDF 2023]",
          "**Record every screen in the NP-NCD card or register** so recall happens. [NP-NCD 2023]",
        ],
      },
    ],
    tables: [
      {
        heading: "Diabetic retinopathy severity classification and action",
        columns: ["Stage", "Findings", "Action"],
        rows: [
          ["No DR", "Normal fundus", "Rescreen in 1 year (1-2 years if well controlled)"],
          ["Mild NPDR", "Microaneurysms only", "Optimise control; review in 12 months"],
          ["Moderate NPDR", "More than microaneurysms but less than severe", "Ophthalmology review in 3-6 months"],
          ["Severe NPDR", "4-2-1 rule: haemorrhages in 4 quadrants, venous beading in 2, IRMA in 1", "Refer within weeks; consider PRP"],
          ["PDR", "New vessels at disc or elsewhere, vitreous or preretinal haemorrhage", "Urgent - PRP, anti-VEGF or vitrectomy"],
          ["Macular oedema", "Thickening or hard exudates within 1 disc diameter of fovea", "Urgent - OCT and intravitreal anti-VEGF"],
        ],
      },
      {
        heading: "IWGDF 2023 foot ulcer risk classification",
        columns: ["Category", "Characteristics", "Examine every"],
        rows: [
          ["0 - very low", "No LOPS and no PAD", "12 months"],
          ["1 - low", "LOPS or PAD", "6-12 months"],
          ["2 - moderate", "LOPS plus PAD, or LOPS plus deformity, or PAD plus deformity", "3-6 months"],
          ["3 - high", "LOPS or PAD plus previous ulcer, amputation or end-stage renal disease", "1-3 months"],
        ],
      },
      {
        heading: "Drugs: dose, duration and side effects",
        columns: ["Drug", "Mechanism", "Dose and duration", "Side effects", "How to take"],
        rows: [
          ["Ramipril / telmisartan", "ACE inhibition or AT1 block - efferent dilation lowers glomerular pressure", "Ramipril 2.5-10 mg OD; telmisartan 40-80 mg OD; long-term at max tolerated dose", "Hyperkalaemia, creatinine rise, cough (ACEi), angioedema", "Once daily; check K and creatinine at 1-2 weeks; stop in pregnancy"],
          ["Dapagliflozin / empagliflozin", "SGLT2 block restores tubuloglomerular feedback", "10 mg OD; start if eGFR 20 or more; continue to dialysis", "Genital thrush, volume depletion, euglycaemic DKA", "Morning; hold when unwell or 3 days before surgery"],
          ["Finerenone", "Non-steroidal MR antagonist - anti-fibrotic", "10 mg OD (eGFR 25-59) or 20 mg OD (60 or more)", "Hyperkalaemia", "Start only if K 5.0 or less; K at 4 weeks"],
          ["Atorvastatin / rosuvastatin", "HMG-CoA reductase inhibition", "Atorvastatin 10-80 mg; rosuvastatin 5-40 mg; lifelong", "Myalgia, raised ALT, small rise in glucose", "Any time daily (atorvastatin, rosuvastatin); stop in pregnancy"],
          ["Fenofibrate", "PPAR-alpha agonist - slows retinopathy", "145-160 mg OD", "Myopathy with statin, creatinine rise, gallstones", "With food; reduce in CKD"],
          ["Pregabalin", "Binds alpha-2-delta calcium channel subunit", "75 mg at night, then 75-150 mg BD (max 300 mg/day)", "Dizziness, sleepiness, oedema, weight gain", "Titrate weekly; renal dose; taper to stop"],
          ["Duloxetine", "Serotonin-noradrenaline reuptake inhibitor", "30 mg OD for 1 week, then 60 mg OD", "Nausea, sweating, raised BP, liver injury", "Morning with food; avoid if eGFR under 30 or liver disease"],
          ["Amitriptyline", "Tricyclic - reuptake and sodium channel block", "10-25 mg at night, up to 75 mg", "Dry mouth, sedation, urinary retention, arrhythmia", "At night; avoid in elderly, glaucoma, IHD"],
          ["Amoxicillin-clavulanate", "Beta-lactam plus beta-lactamase inhibitor", "625 mg TDS oral 1-2 weeks (mild); 1.2 g IV 8-hourly (moderate)", "Diarrhoea, rash, cholestatic jaundice", "With food; complete the course"],
        ],
      },
    ],
    redFlags: [
      "Sudden painless loss of vision or a shower of new floaters - vitreous haemorrhage or detachment; same-day ophthalmology.",
      "Foot ulcer with spreading cellulitis, crepitus, foul discharge, exposed bone or systemic upset - admit for surgical debridement and IV antibiotics.",
      "Hot, red, swollen, painless foot with intact skin in a neuropathic patient - acute Charcot; immobilise and refer immediately.",
      "Rest pain, absent pulses, dependent rubor or gangrenous toes - critical limb ischaemia; urgent vascular referral.",
      "Heavy proteinuria without retinopathy, haematuria or casts, or rapid creatinine rise - suspect non-diabetic kidney disease; refer to nephrology.",
      "Potassium over 5.5 mmol/L or creatinine rise over 30% after starting ACEi, ARB or finerenone - stop and investigate.",
      "Persistent vomiting with wide glucose swings - gastroparesis with risk of dehydration and ketosis; admit if fluids cannot be kept down.",
      "Postural syncope, resting tachycardia and hypoglycaemia unawareness - advanced autonomic neuropathy with sudden death risk.",
    ],
    pearls: [
      "Type 2: screen from the day of diagnosis; type 1: from 5 years after - a favourite examiner trap.",
      "Macular oedema, not proliferative disease, is the commonest cause of visual loss in type 2 diabetes and occurs at any DR stage.",
      "Never diagnose diabetic kidney disease on a single ACR - confirm on 2 of 3 samples over 3-6 months.",
      "An early eGFR dip up to 30% after ACEi, ARB or SGLT2 inhibitor is haemodynamic and protective - continue the drug.",
      "The four pillars of diabetic kidney disease: maximum-dose ACEi or ARB, SGLT2 inhibitor, finerenone, and a GLP-1 agonist - plus statin and BP under 130/80.",
      "The 10 g monofilament at four plantar sites predicts amputation better than any blood test.",
      "A calcified tibial artery gives a falsely reassuring ABI over 1.3 - use toe pressures.",
      "A hot swollen painless foot in a neuropathic diabetic is Charcot until proved otherwise.",
      "Not every numb diabetic foot is diabetic - check B12 (metformin), thyroid, alcohol and thickened nerves for leprosy.",
    ],
    references: [
      "American Diabetes Association. Standards of Care in Diabetes - 2026. Sections 10-12 (cardiovascular, CKD, retinopathy, neuropathy, foot care). Diabetes Care 2026.",
      "KDIGO 2024 Clinical Practice Guideline for the Evaluation and Management of CKD; KDIGO 2022 Diabetes Management in CKD.",
      "IWGDF/IDSA Guidelines on the Prevention and Management of Diabetes-Related Foot Disease, 2023.",
      "American Academy of Ophthalmology. Diabetic Retinopathy Preferred Practice Pattern, 2024 update.",
      "RSSDI Clinical Practice Recommendations for the Management of Type 2 Diabetes Mellitus, 2022.",
      "Perkovic V et al. FLOW trial: semaglutide and kidney outcomes in type 2 diabetes. N Engl J Med 2024.",
      "Harrison's Principles of Internal Medicine, 22nd edition, 2025 - Diabetes complications.",
      "Williams Textbook of Endocrinology, 15th edition, 2024.",
      "MoHFW. NPCBVI guidelines for diabetic retinopathy screening; NP-NCD Operational Guidelines 2023.",
    ],
  },
};

export default rewrites;
