import type { TopicRewrite } from "../index";

const rewrites: Record<string, TopicRewrite> = {
  "eye-ent-red-eye": {
    oneLiner:
      "A red eye is sorted at the bedside by **visual acuity, the pattern of redness (conjunctival versus ciliary), fluorescein staining, the pupil and digital tension** into the benign surface conditions treated in the OPD (conjunctivitis, subconjunctival haemorrhage, episcleritis) and the **sight-threatening four referred the same day** (keratitis, anterior uveitis, acute angle closure, scleritis) - and **no steroid drop is ever started in an undiagnosed red eye**.",
    sections: [
      {
        heading: "Definition and the classification that matters",
        points: [
          "A **red eye** is visible dilatation of the **conjunctival, episcleral or ciliary (deep limbal) vessels**, and the layer that is dilated names the diagnosis. [Khurana 8e]",
          "The classification examiners expect is **by pattern of injection**: **conjunctival** (superficial, maximal in the fornices), **ciliary or circumcorneal** (deep, maximal at the limbus) and **mixed** - the first means surface disease, the second means cornea, iris or ciliary body. [Khurana 8e]",
          "The working clinical split is **red eye with normal vision and no true pain** (conjunctivitis, subconjunctival haemorrhage, episcleritis - treated in the OPD) versus **red eye with reduced vision, pain or photophobia** (keratitis, uveitis, angle closure, scleritis, endophthalmitis - referred the same day). [STG Ophthalmology MoHFW 2015]",
          "About **80% of red eyes in general practice are conjunctivitis**, but conjunctivitis is a **diagnosis of exclusion** once the eye is painful or vision is reduced. [AAO PPP 2023]",
          "**Conjunctivitis is classified by cause**: bacterial (including hyperacute gonococcal), viral (adenoviral, herpetic), chlamydial (trachoma, adult inclusion, neonatal), allergic (seasonal, perennial, **vernal**, atopic) and toxic or chemical. [Kanski 10e]",
          "**Ophthalmia neonatorum** is any conjunctivitis in the **first 28 days of life** and is a notifiable, referable condition because gonococcal disease can perforate the cornea within 24-48 hours. [Kanski 10e]",
          "**Uveitis is classified anatomically (SUN)** into anterior, intermediate, posterior and panuveitis; primary care meets mainly **acute anterior uveitis (iritis)**. [Kanski 10e]",
          "**Trachoma** is graded by the WHO simplified system (TF, TI, TS, TT, CO), and **India was validated by WHO as having eliminated trachoma as a public health problem in 2024**, so surveillance for trichiasis continues. [WHO 2024]",
        ],
      },
      {
        heading: "Pathophysiology and pathoanatomy",
        points: [
          "**Conjunctiva** is a thin mucous membrane with a non-keratinised stratified epithelium containing **goblet cells**, over a stroma whose superficial **adenoid (lymphoid) layer develops only after 2-3 months of age** - so neonates cannot form follicles. [Khurana 8e]",
          "**Superficial vessels**: the **posterior conjunctival arteries** arise from the peripheral and marginal palpebral arcades and supply the bulbar conjunctiva from the fornix towards the limbus - so conjunctival injection is brightest in the fornices, moves with the conjunctiva and **blanches with phenylephrine or adrenaline**. [Khurana 8e]",
          "**Deep vessels**: the **anterior ciliary arteries** (from the muscular branches to the four recti) pierce the sclera near the limbus to form the **pericorneal plexus** and the major arterial circle of the iris - so inflammation of cornea, iris or ciliary body shows as a violaceous circumcorneal flush that does not move or blanch. [Khurana 8e]",
          "**Cornea** is avascular, about **0.52 mm thick centrally**, with epithelium, Bowman layer, stroma (90% of thickness, regular collagen lamellae), Dua and Descemet layers and a single-layer **endothelium whose Na-K ATPase pump keeps the stroma dehydrated and clear**. [Khurana 8e]",
          "The cornea is the **most densely innervated tissue in the body** (long ciliary nerves from the nasociliary branch of V1), so an epithelial defect causes severe pain, watering and blepharospasm, while conjunctival inflammation causes only grittiness. [Khurana 8e]",
          "**Fluorescein** is water-soluble and cannot enter intact lipophilic epithelium but floods the hydrophilic stroma wherever epithelium is lost - so any green staining under cobalt-blue light means an epithelial defect. [Khurana 8e]",
          "**Photophobia** comes from the **trigemino-ciliary reflex**: light makes the inflamed iris and ciliary muscle contract, which hurts - hence photophobia in keratitis and uveitis but not in simple conjunctivitis. [Khurana 8e]",
          "**Bacterial conjunctivitis** (Staphylococcus aureus, Streptococcus pneumoniae, Haemophilus influenzae, Moraxella) produces neutrophil-rich **purulent discharge** and **papillae** (vascular cores with inflammatory cells); **Neisseria gonorrhoeae can penetrate intact corneal epithelium**, causing hyperacute copious pus and early perforation. [Kanski 10e]",
          "**Adenoviral conjunctivitis** (types 8, 19, 37 cause epidemic keratoconjunctivitis; 3, 7 cause pharyngoconjunctival fever) gives **lymphocytic follicles**, watery discharge and a tender **preauricular node**; 1-2 weeks later immune **subepithelial infiltrates** may blur vision for months. [Kanski 10e]",
          "**Follicles versus papillae**: follicles are lymphoid germinal centres with vessels round them (viral, chlamydial, drug toxicity), while papillae have a central vessel (bacterial, allergic); **giant cobblestone papillae on the upper tarsus** mean **vernal keratoconjunctivitis**. [Khurana 8e]",
          "**Allergic conjunctivitis** is a **type I hypersensitivity**: allergen cross-links IgE on conjunctival mast cells, releasing **histamine (itch, redness, chemosis)** and later leukotrienes and eosinophil products - hence antihistamines and mast-cell stabilisers work, and **itch is the cardinal symptom**. [AAO PPP 2023]",
          "**Anterior uveitis**: breakdown of the **blood-aqueous barrier** lets protein (**flare**) and leucocytes (**cells**) into the aqueous; cells stick to the endothelium as **keratic precipitates**, settle as **hypopyon**, and the sticky iris adheres to the lens (**posterior synechiae**), giving a small irregular pupil - cycloplegics break these and relieve ciliary spasm. [Kanski 10e]",
          "**Aqueous humour** is secreted at about **2-3 microlitre per minute** by the non-pigmented ciliary epithelium using **carbonic anhydrase and Na-K ATPase** (under beta-adrenergic drive), passes through the pupil and drains mainly via the **trabecular meshwork and Schlemm canal**, with 10-20% via the uveoscleral route - the targets of every IOP-lowering drug. [Khurana 8e]",
          "**Acute angle closure**: in a short **hypermetropic eye with a large, ageing lens**, a **mid-dilated pupil** maximises contact between iris and lens (**relative pupillary block**), aqueous builds up behind the iris, the peripheral iris bows forward (**iris bombe**) and closes the angle - IOP rises to **40-80 mmHg** within hours. [Kanski 10e]",
          "Raised IOP overwhelms the endothelial pump, so the **cornea becomes oedematous** (haloes, hazy cornea), the **iris sphincter becomes ischaemic** (fixed, vertically oval mid-dilated pupil) and the trigemino-vagal reflex causes **nausea and vomiting** - which is why these patients are admitted as 'gastritis'. [Kanski 10e]",
          "**Scleritis** is immune-mediated vasculitis of the scleral collagen (half have **rheumatoid arthritis, GPA or another systemic disease**); the recti insert into the sclera, so pain is **worse on eye movement**; **episcleritis** involves only the loose episclera, blanches with phenylephrine and is self-limiting. [Kanski 10e]",
          "**Subconjunctival haemorrhage** is a ruptured conjunctival vessel bleeding into the potential space between conjunctiva and Tenon capsule - after straining, coughing, hypertension or anticoagulation - and is painless with normal vision. [Khurana 8e]",
          "**Why topical steroids are dangerous without a slit lamp**: they suppress the leucocyte response that holds **herpes simplex and fungi** in check (dendrite becomes geographic ulcer, fungal ulcer spreads), reduce trabecular outflow by deposition of extracellular matrix (**steroid-induced glaucoma** in about 1 in 3 people, severe in about 5%) and cause **posterior subcapsular cataract**. [Kanski 10e]",
        ],
      },
      {
        heading: "History in the OPD",
        points: [
          "Ask **five questions** in every red eye - **is vision blurred, is there true pain or only grittiness, what kind of discharge, is light painful, one eye or both** - because blurred vision, true pain and photophobia each mean the inflammation is inside the eye. [Khurana 8e]",
          "**Purulent discharge with lids stuck together on waking** suggests bacterial conjunctivitis; **watery discharge, sore throat and a cold** suggest adenovirus; **itch with stringy mucoid discharge** suggests allergy - infection does not itch. [AAO PPP 2023]",
          "Ask whether the **second eye followed the first after a few days** - sequential spread is typical of adenovirus, and household or school contacts with red eyes suggest an outbreak. [AAO PPP 2023]",
          "Ask about **contact lens wear**, overnight wear and cleaning with tap water - a painful red eye in a lens wearer is **Pseudomonas or Acanthamoeba keratitis** until proved otherwise. [Kanski 10e]",
          "Ask about **trauma with vegetable matter** (crop leaf, cow tail, stick) - the classic history of **fungal keratitis** in rural India - and about **hammering or chiselling** (intraocular foreign body). [Khurana 8e]",
          "Ask about **drops already used**, especially **steroid or steroid-antibiotic combinations bought over the counter** and home remedies (breast milk, herbal drops), since these change the diagnosis and the danger. [Khurana 8e]",
          "**Haloes around lights, severe brow ache, nausea and vomiting** in an older, long-sighted patient - often after a dark cinema hall or an **anticholinergic, antihistamine, antidepressant or topiramate** - is acute angle closure. [Kanski 10e]",
          "In suspected uveitis ask about **back pain and morning stiffness** (HLA-B27 spondyloarthritis), **joint pain, psoriasis, bowel symptoms, urethritis**, **tuberculosis contact**, oral and genital ulcers (Behcet) and **herpes zoster** - uveitis is often a systemic sign. [Kanski 10e]",
          "**Boring pain that wakes the patient at night and is worse on eye movement** suggests scleritis - ask about rheumatoid arthritis, vasculitis symptoms and TB. [Kanski 10e]",
          "Ask about **recent cataract surgery, intravitreal injection or penetrating injury in the last 6 weeks** - a red painful eye after surgery is endophthalmitis until proved otherwise. [Kanski 10e]",
          "For a painless bright red patch ask about **straining, coughing, BP and anticoagulants or antiplatelets** - recurrent subconjunctival haemorrhage may mean a high INR or uncontrolled hypertension. [Khurana 8e]",
          "In a neonate ask the **day of onset** (day 1 chemical, days 2-5 gonococcal, days 5-14 chlamydial) and the **mother's history of vaginal discharge**, since both parents then need treatment. [Kanski 10e]",
          "In a boy with **seasonal itching, ropy discharge and photophobia** in the hot months think of **vernal keratoconjunctivitis**, which is common in India and threatens the cornea with shield ulcers. [Khurana 8e]",
          "Ask about **occupation and chemicals** (lime, cement, battery acid, toilet cleaner) - a chemical splash is an emergency that is irrigated before any history is taken. [Kanski 10e]",
        ],
      },
      {
        heading: "Examination",
        points: [
          "**Visual acuity first, each eye separately, with glasses**: Snellen chart at **6 metres**, patient covers the other eye with the palm (not the fingers); if under 6/6 repeat through a **pinhole** - improvement means refractive error, no improvement means disease. [Khurana 8e]",
          "If the top letter (6/60) cannot be read, bring the patient closer (5/60, 4/60 ... 1/60), then record **counting fingers at a distance, hand movements, perception of light with projection** or no perception of light; test near vision with an N-notation chart. [Khurana 8e]",
          "**Torch (diffuse and oblique) examination** in a systematic order - lids and lashes, conjunctiva (pattern of redness, discharge, follicles, chemosis), cornea (clarity, light reflex, opacity), anterior chamber (depth, hypopyon, hyphaema), iris, pupil and lens. [Khurana 8e]",
          "**Oblique flashlight (shadow) test for chamber depth**: shine the torch from the temporal side parallel to the iris - in a shallow chamber the forward-bowed iris casts a **shadow on the nasal iris**, warning you not to dilate the pupil. [Khurana 8e]",
          "**Evert the upper lid** in any foreign-body sensation: patient looks down, hold the lashes, press a cotton bud or matchstick at the upper border of the tarsus (about 1 cm above the lid margin) and fold the lid over it - this shows subtarsal foreign bodies, follicles and cobblestone papillae. [Khurana 8e]",
          "**Fluorescein staining**: touch a moistened strip to the lower fornix, ask the patient to blink and view with a **cobalt-blue light** - a **branching dendrite with terminal bulbs** means herpes simplex, a stained area under a **white infiltrate** means an ulcer, and **vertical linear scratches** mean a subtarsal foreign body. [Khurana 8e]",
          "**Pupil**: compare size, shape and reaction - **small, irregular, sluggish** (uveitis), **mid-dilated, vertically oval, fixed** (angle closure) - and do the **swinging torch test** for a relative afferent pupillary defect (optic nerve or extensive retinal disease). [Khurana 8e]",
          "**Digital tonometry**: patient looks down, both index fingers rest on the upper lid over the sclera, one finger presses while the other feels the fluctuation - a **stony hard eye compared with the other** suggests angle closure; never press on an eye that may be perforated. [Khurana 8e]",
          "**Palpate the preauricular node** - a tender node is almost pathognomonic of adenoviral (or chlamydial) conjunctivitis. [AAO PPP 2023]",
          "**Phenylephrine 2.5% (or 10%) test**: one drop blanches **episcleral** vessels within 10-15 minutes but not the deep **scleral** plexus - separates episcleritis from scleritis without a slit lamp. [Kanski 10e]",
          "**Distant direct ophthalmoscopy (red reflex)** from arm's length with the +2 lens - a dull or absent reflex suggests corneal oedema, hyphaema, hypopyon, vitreous haemorrhage or endophthalmitis. [Khurana 8e]",
          "Look beyond the eye: **BP** (subconjunctival haemorrhage), **joints, spine, skin and mouth** (uveitis, scleritis), **vesicles on the nose tip (Hutchinson sign)** in zoster, and genital discharge in neonatal or adult inclusion conjunctivitis. [Kanski 10e]",
        ],
      },
      {
        heading: "Minimal investigations",
        points: [
          "**Simple conjunctivitis needs no test** - diagnosis is clinical, and swabs are taken only if it is hyperacute, neonatal, severe, recurrent or not settling after 7-10 days of treatment. [AAO PPP 2023]",
          "**Conjunctival swab for Gram stain and culture** (and chlamydia NAAT) in ophthalmia neonatorum: **Gram-negative intracellular diplococci** mean gonococcus and need systemic treatment the same day. [Kanski 10e]",
          "**Corneal scraping (Gram stain, KOH mount, culture)** is done by the ophthalmologist **before any antimicrobial drop** in a suspected ulcer - KOH shows fungal hyphae within minutes. [STG Ophthalmology MoHFW 2015]",
          "**Tonometry** (applanation or rebound) confirms angle closure, typically IOP **over 40 mmHg**; gonioscopy after the attack confirms the closed angle. [Kanski 10e]",
          "**First-episode unilateral acute anterior uveitis with no systemic features needs no workup**; recurrent, bilateral or granulomatous uveitis needs **HLA-B27, chest X-ray, Mantoux or IGRA, VDRL/TPHA, ESR, CRP and serum ACE** as the history suggests. [Kanski 10e]",
          "**Scleritis workup**: CBC, ESR, CRP, **RF and anti-CCP, ANCA**, urinalysis for haematuria, chest X-ray and syphilis serology - half have a systemic disease that decides survival, not just the eye. [Kanski 10e]",
          "**Recurrent subconjunctival haemorrhage**: BP, platelet count, and **INR** in patients on warfarin or acenocoumarol. [Khurana 8e]",
          "**Do not order routinely**: conjunctival cultures in uncomplicated conjunctivitis, allergy panels, or blood tests for a single episode of subconjunctival haemorrhage in a normotensive patient. [AAO PPP 2023]",
        ],
      },
      {
        heading: "Treatment - general measures",
        points: [
          "**Hygiene** in infective conjunctivitis: wash hands before and after touching the eyes, use separate towels and pillow covers, do not share drops or cosmetics, and clean discharge from inner to outer canthus with boiled-and-cooled water. [AAO PPP 2023]",
          "**Adenoviral conjunctivitis is contagious for 10-14 days** while the eye is red and watery - advise avoiding school, work with the public and swimming pools during that time and disinfect clinic tonometers and door handles. [AAO PPP 2023]",
          "**Stop contact lens wear** until the eye is white and treatment has finished, discard the lens case, and never rinse lenses in tap water. [AAO PPP 2023]",
          "**Allergic conjunctivitis**: avoid rubbing (it degranulates mast cells and in VKC or AKC can cause keratoconus), use **cold compresses and chilled preservative-free artificial tears**, wear wrap-around sunglasses outdoors, and wash hair and face after being outdoors in pollen season. [AAO PPP 2023]",
          "**Do not pad a discharging eye**, and never pad a contact lens wearer - padding warms and incubates organisms. [Khurana 8e]",
          "**Delayed antibiotic strategy**: most bacterial conjunctivitis clears in **5-7 days without treatment**; a drop shortens it by a day or two and is reasonable when the family or school demands it. [NICE CKS 2024]",
          "Counsel that **home remedies (breast milk, rose water, herbal or 'cooling' drops) and chemist-bought steroid drops** are harmful and that any **pain, light sensitivity or blurred vision means return the same day**. [Khurana 8e]",
          "**Subconjunctival haemorrhage and episcleritis**: explain they are harmless, that the red patch passes through yellow-green over **10-14 days**, and treat the cause (BP, INR, cough). [Khurana 8e]",
        ],
      },
      {
        heading: "Treatment - drugs",
        points: [
          "**Topical antibiotics - mechanism**: chloramphenicol blocks the **50S ribosomal peptidyl transferase** (bacteriostatic, broad spectrum), fluoroquinolones inhibit **DNA gyrase and topoisomerase IV** (bactericidal), aminoglycosides bind the **30S subunit**, and fusidic acid blocks **elongation factor G** (mainly staphylococcal). [Goodman and Gilman 14e]",
          "**Chloramphenicol 0.5% eye drops**: 1 drop every 2 hours for the first 2 days, then **4 times daily**, with **1% ointment at night**, for **5 days** (continue 48 hours after the eye is white); cheap, first line; systemic aplastic anaemia from eye drops is theoretical and not a reason to avoid it. [NICE CKS 2024]",
          "**Moxifloxacin 0.5% eye drops**: 1 drop **three times daily for 7 days**; reserve fluoroquinolones for contact lens wearers and severe or non-responding infection to limit resistance; side effects are transient stinging and taste change. [AAO PPP 2023]",
          "Alternatives: **tobramycin 0.3% 1 drop 4-6 hourly for 7 days** (punctate epithelial toxicity with long use), **ciprofloxacin 0.3% 1 drop 4 times daily for 7 days** (white corneal precipitates), and **fusidic acid 1% viscous drops twice daily for 7 days** (useful in children because of twice-daily dosing). [BNF 2025]",
          "**Gonococcal conjunctivitis**: adult **ceftriaxone 1 g IM single dose**; neonate **ceftriaxone 25-50 mg/kg IM or IV single dose (maximum 125 mg)**, plus hourly saline irrigation and admission; avoid ceftriaxone in hyperbilirubinaemic or premature neonates (use cefotaxime 100 mg/kg IM once). [CDC STI 2021]",
          "**Chlamydial conjunctivitis**: neonate **oral erythromycin 50 mg/kg/day in 4 divided doses for 14 days** (watch for infantile hypertrophic pyloric stenosis) or **azithromycin 20 mg/kg once daily for 3 days**; adult **azithromycin 1 g single dose** or doxycycline 100 mg twice daily for 7 days, treating sexual partners. [CDC STI 2021]",
          "**Trachoma**: **azithromycin 20 mg/kg single oral dose (maximum 1 g)** or **tetracycline 1% eye ointment twice daily for 6 weeks**, plus facial cleanliness and environmental improvement (the SAFE strategy); trichiasis needs lid surgery. [WHO 2024]",
          "**Adenoviral conjunctivitis has no effective antiviral**: give **preservative-free lubricants (carboxymethylcellulose 0.5% 4-6 times daily)** and cold compresses; antibiotics do not help, and steroids are used only by an ophthalmologist for pseudomembranes or vision-reducing subepithelial infiltrates because they prolong viral shedding. [AAO PPP 2023]",
          "**Dual-action antihistamine-mast cell stabilisers** block H1 receptors and stabilise mast cells: **olopatadine 0.1% 1 drop twice daily** (or 0.2% once daily) or **ketotifen 0.025% 1 drop twice daily**, for the pollen season; safe long term, may sting briefly. [AAO PPP 2023]",
          "**Sodium cromoglicate 2% 1 drop 4 times daily** prevents mast cell degranulation but takes **1-2 weeks** to work, so start before the season; add **oral cetirizine 10 mg or fexofenadine 120-180 mg once daily** when nose symptoms coexist (oral antihistamines can dry the eye). [AAO PPP 2023]",
          "**Vernal keratoconjunctivitis** (ophthalmologist-led): **cyclosporine 0.1% cationic emulsion 1 drop 4 times daily** or **tacrolimus 0.03-0.1% ointment** as steroid-sparing calcineurin inhibitors, with short pulses of **loteprednol 0.5% or fluorometholone 0.1%** (lower IOP risk) for flares only. [Kanski 10e]",
          "**Topical corticosteroid mechanism**: bind the glucocorticoid receptor, block **phospholipase A2 (via lipocortin), COX-2 and cytokine transcription**, reduce capillary permeability and leucocyte migration - powerful for uveitis and allergy but **never in an undiagnosed red eye**. [Goodman and Gilman 14e]",
          "**Steroid drop side effects**: rise in IOP within **2-6 weeks** (check IOP at every review), **posterior subcapsular cataract** with months of use, worsening of **herpetic, fungal and Acanthamoeba keratitis**, delayed epithelial healing and scleral melting - **never give repeat prescriptions without slit-lamp review**. [Kanski 10e]",
          "**Avoid steroid-antibiotic combination drops** (dexamethasone or betamethasone with an antibiotic), which are widely sold over the counter in India and are a leading avoidable cause of corneal blindness and steroid glaucoma. [Khurana 8e]",
          "**Acute anterior uveitis** (after ophthalmologist confirmation): **prednisolone acetate 1% 1 drop every 1-2 hours while awake**, tapered over **4-6 weeks** according to AC cells - never stopped abruptly (rebound). [Kanski 10e]",
          "**Cycloplegics** block muscarinic M3 receptors of the iris sphincter and ciliary muscle - relieving **ciliary spasm pain**, breaking and preventing **posterior synechiae**: **homatropine 2% 1 drop 2-3 times daily** or **cyclopentolate 1% 1 drop 3 times daily**, **atropine 1% twice daily** for severe cases; they blur near vision and are dangerous in a shallow angle. [Kanski 10e]",
          "**Herpes simplex epithelial keratitis**: **acyclovir 3% eye ointment 5 times daily for 14 days** or **ganciclovir 0.15% gel 5 times daily until the ulcer heals, then 3 times daily for 7 days** - no steroid. [AAO PPP 2023]",
          "**Episcleritis**: preservative-free lubricants; if troublesome **ibuprofen 400 mg three times daily after food for 1-2 weeks** (avoid in peptic ulcer, CKD, late pregnancy); **scleritis needs systemic NSAID, oral steroid or immunosuppression** via an ophthalmologist and rheumatologist. [Kanski 10e]",
          "**Corneal abrasion**: **chloramphenicol 1% ointment 4 times daily for 5 days** (moxifloxacin drops in lens wearers), a cycloplegic for pain if needed, oral paracetamol or ibuprofen, review at 24-48 hours. [STG Ophthalmology MoHFW 2015]",
          "**Topical anaesthetic (proparacaine 0.5%, one drop)** is used only in the clinic to allow examination and irrigation - **never prescribed for home use**, because repeated use causes epithelial toxicity, ring infiltrates and corneal melt. [Khurana 8e]",
          "**Acetazolamide** (carbonic anhydrase inhibitor, cuts aqueous production by about 50%): **500 mg IV or orally stat, then 250 mg every 6 hours** in angle closure; side effects tingling, fatigue, metabolic acidosis, hypokalaemia, renal stones; **avoid in sulphonamide allergy, sickle cell disease, severe renal or hepatic failure**. [Kanski 10e]",
          "**Timolol 0.5%** (non-selective beta-blocker, reduces aqueous secretion) 1 drop; contraindicated in **asthma, COPD, bradycardia and heart block** - absorbed through the nasolacrimal mucosa, it bypasses first-pass metabolism and can cause bronchospasm. [Kanski 10e]",
          "**Pilocarpine 1-2%** (muscarinic agonist, constricts the pupil and pulls the iris out of the angle) 1 drop twice 15 minutes apart **only after IOP starts to fall** - the ischaemic sphincter does not respond above about 40-50 mmHg; causes brow ache and myopic blur. [Kanski 10e]",
          "**Hyperosmotics** draw water from the vitreous: **mannitol 20% IV 1-2 g/kg over 30-45 minutes** (caution in heart and renal failure) or **oral glycerol 50% 1-1.5 g/kg** (avoid in diabetes, it is metabolised to glucose). [Kanski 10e]",
          "**Pregnancy and children**: chloramphenicol, fusidic acid, erythromycin ointment and moxifloxacin drops are acceptable in pregnancy; **brimonidine is contraindicated under 2 years** (apnoea, CNS depression); use **punctal occlusion** to reduce systemic absorption of any drop in infants and pregnant women. [BNF 2025]",
        ],
      },
      {
        heading: "Devices and how to use them",
        points: [
          "**Why one drop is enough**: a drop is about **30-50 microlitre** while the conjunctival sac holds only about **7-10 microlitre**, so a second drop only runs down the cheek or down the nasolacrimal duct into the circulation. [Kanski 10e]",
          "**Instilling eye drops (numbered steps)**: (1) wash hands, shake suspensions such as prednisolone acetate; (2) tilt the head back or lie down, look up; (3) pull the lower lid down with one finger to form a pocket; (4) hold the bottle above the eye without touching lashes and squeeze **one drop into the pocket**; (5) close the eyes gently for 1-2 minutes without blinking hard. [AAO PPP 2023]",
          "**Punctal occlusion**: after the drop, press a fingertip on the **inner corner of the eye (over the lacrimal sac) for 1-2 minutes** - it keeps the drug in the eye and cuts systemic absorption of timolol, brimonidine or atropine by up to two-thirds. [Kanski 10e]",
          "**Two or more drops**: leave **at least 5 minutes between different drops** (otherwise the second washes out the first), suspensions after solutions, and **ointment always last**. [AAO PPP 2023]",
          "**Applying eye ointment**: pull the lower lid down, squeeze a **1 cm ribbon** along the inside of the lower lid from inner to outer corner without touching the eye, close the eye and move it about; use at bedtime because it blurs vision for 20-30 minutes. [AAO PPP 2023]",
          "**Children**: lay the child down, ask them to close the eyes, place the drop at the **inner corner** and let it run in when the eyes open; wrap an infant in a towel and have a second person steady the head. [Nelson 22e]",
          "**Common errors**: touching the eye or lashes with the tip (contaminates the bottle), several drops at once, no gap between drops, **using a bottle more than 4 weeks after opening**, and sharing bottles between family members during an outbreak. [AAO PPP 2023]",
          "Patients with **arthritis, tremor or poor vision** can use a drop-guide aid, rest the hand on the forehead, or keep the bottle in the fridge so the cold drop is felt when it lands. [Kanski 10e]",
        ],
      },
      {
        heading: "Acute presentation and emergency management",
        points: [
          "**Acute angle closure first aid while arranging transfer**: lie the patient supine, give analgesia and an **antiemetic**, **acetazolamide 500 mg IV or orally**, **timolol 0.5%** 1 drop, **brimonidine 0.2%** 1 drop and **prednisolone acetate 1%** 1 drop, then **pilocarpine 2%** once IOP starts to fall; add **IV mannitol** if IOP stays high. [Kanski 10e]",
          "Definitive treatment is **laser peripheral iridotomy** in both eyes - the fellow eye has a **40-80% risk of a similar attack** within 5-10 years without it. [Kanski 10e]",
          "**Chemical injury**: irrigate at once with **at least 1-2 litres of saline, Ringer lactate or clean tap water for at least 30 minutes** after a topical anaesthetic drop, evert the lids and sweep the fornices, check pH until **7.0-7.5**, then refer - alkali (lime, cement) is worse than acid. [Kanski 10e]",
          "**Suspected endophthalmitis** after surgery or trauma: do not start drops; refer within hours for vitreous tap and **intravitreal vancomycin 1 mg and ceftazidime 2.25 mg**. [Kanski 10e]",
          "**Hyperacute neonatal conjunctivitis**: admit, swab for Gram stain, **ceftriaxone 25-50 mg/kg IM (maximum 125 mg)**, hourly saline lavage, and treat the mother and her partner. [CDC STI 2021]",
          "**Suspected penetrating injury**: no pressure on the globe, no drops or ointment, a **rigid shield** (not a pad), nil by mouth, tetanus prophylaxis, and refer lying propped up. [Kanski 10e]",
        ],
      },
      {
        heading: "Follow-up, monitoring and when to refer",
        points: [
          "**Bacterial and viral conjunctivitis**: return if not better in **5-7 days** (bacterial) or **2-3 weeks** (adenoviral), or at once if pain, photophobia or blurred vision develop. [AAO PPP 2023]",
          "**Refer the same day**: red eye with **reduced acuity, true pain, photophobia, corneal opacity or staining beyond a simple abrasion, abnormal pupil, hard globe, hypopyon or hyphaema**, a contact lens wearer with a painful eye, and any red eye within 6 weeks of eye surgery. [STG Ophthalmology MoHFW 2015]",
          "**Refer within hours**: suspected angle closure, chemical injury (after irrigation), endophthalmitis, penetrating injury and neonatal gonococcal conjunctivitis. [Kanski 10e]",
          "**Refer routinely**: recurrent episcleritis, vernal keratoconjunctivitis, chronic follicular conjunctivitis over 4 weeks (chlamydia, molluscum, drug toxicity), and pterygium approaching the visual axis. [Kanski 10e]",
          "Anyone on **topical steroids for more than 2 weeks** needs **IOP measurement** and lens examination at each review; stop the steroid by taper, not abruptly. [Kanski 10e]",
          "After uveitis, review for **recurrence, IOP and cataract**, and co-manage HLA-B27 spondyloarthritis or TB with the physician. [Kanski 10e]",
          "Record **visual acuity at every visit** - an unexplained drop in acuity at follow-up is itself an indication for referral. [STG Ophthalmology MoHFW 2015]",
        ],
      },
    ],
    tables: [
      {
        heading: "Types of red eye - bedside differentiation",
        columns: ["Feature", "Conjunctivitis", "Keratitis / corneal ulcer", "Acute anterior uveitis", "Acute angle-closure glaucoma"],
        rows: [
          ["Pain", "Grittiness, burning; no true pain", "Severe, sharp, with watering", "Deep ache, photophobia", "Very severe, with headache and vomiting"],
          ["Vision", "Normal", "Reduced", "Mildly reduced", "Markedly reduced, haloes"],
          ["Discharge", "Purulent, mucoid or watery", "Watery, reflex", "Watery or none", "None"],
          ["Redness", "Conjunctival, maximal in fornices, blanches", "Ciliary (circumcorneal)", "Ciliary (circumcorneal)", "Mixed, congested"],
          ["Cornea", "Clear, no stain", "White infiltrate that stains with fluorescein", "Clear, keratic precipitates", "Hazy, oedematous"],
          ["Anterior chamber", "Normal", "Normal or hypopyon", "Cells, flare, may be hypopyon", "Very shallow"],
          ["Pupil", "Normal", "Normal or small", "Small, irregular, sluggish", "Mid-dilated, vertically oval, fixed"],
          ["Digital tension", "Normal", "Normal", "Normal or low", "Stony hard"],
          ["Action", "Treat in OPD", "Refer same day, no drops first", "Refer same day", "Start treatment, refer within hours"],
        ],
      },
      {
        heading: "Drugs: dose, duration and side effects",
        columns: ["Drug", "Mechanism", "Dose and duration", "Side effects", "How to take"],
        rows: [
          ["Chloramphenicol 0.5% drops / 1% ointment", "50S ribosome inhibitor, broad spectrum", "1 drop 2-hourly for 48 h then 4 times daily, ointment at night; 5 days", "Stinging; theoretical aplastic anaemia", "One drop in lower lid pocket; ointment last; discard 4 weeks after opening"],
          ["Moxifloxacin 0.5% drops", "DNA gyrase and topoisomerase IV inhibitor", "1 drop 3 times daily for 7 days", "Stinging, taste change", "Reserve for lens wearers and severe cases; no lens wear during course"],
          ["Olopatadine 0.1% drops", "H1 antagonist and mast cell stabiliser", "1 drop twice daily through the season", "Brief stinging, headache", "Chilled drops soothe; do not rub eyes"],
          ["Prednisolone acetate 1% drops", "Glucocorticoid; blocks PLA2 and cytokine transcription", "Uveitis: 1 drop 1-2 hourly, taper over 4-6 weeks (ophthalmologist only)", "Raised IOP, cataract, worsens herpes and fungal keratitis", "Shake well; never start without slit lamp; never stop abruptly"],
          ["Homatropine 2% drops", "Muscarinic antagonist - cycloplegic, mydriatic", "1 drop 2-3 times daily while inflamed", "Blurred near vision, glare; angle closure in shallow AC", "Punctal occlusion in children; avoid in shallow chamber"],
          ["Acyclovir 3% ointment", "Viral DNA polymerase inhibitor", "5 times daily for 14 days", "Punctate keratopathy, stinging", "1 cm ribbon in lower fornix; no steroid"],
          ["Acetazolamide tablet / injection", "Carbonic anhydrase inhibitor; halves aqueous secretion", "500 mg stat then 250 mg 6-hourly (acute angle closure)", "Paraesthesia, acidosis, hypokalaemia, stones", "Avoid in sulpha allergy, sickle cell, renal failure"],
          ["Timolol 0.5% drops", "Non-selective beta-blocker; reduces aqueous secretion", "1 drop stat, then twice daily", "Bronchospasm, bradycardia, fatigue", "Punctal occlusion; not in asthma, COPD, heart block"],
        ],
      },
      {
        heading: "Devices: eye drops and ointment",
        columns: ["Device", "Best for", "Technique key steps", "Common errors"],
        rows: [
          ["Eye drop bottle", "Most acute and chronic eye treatment", "Head back, pull lower lid, one drop in pocket, close eye 1-2 min, punctal occlusion", "Touching tip to eye, several drops, no 5-min gap"],
          ["Eye ointment tube", "Night-time cover, children, abrasions", "1 cm ribbon along lower lid from inner to outer corner, close eye", "Used before drops, used by day while driving"],
          ["Single-dose preservative-free vials", "Frequent lubricants, allergy, contact lens wearers", "Twist off, one drop each eye, discard vial after use", "Re-using the vial the next day"],
        ],
      },
    ],
    redFlags: [
      "Red eye with reduced visual acuity - keratitis, uveitis, angle closure or endophthalmitis; refer the same day.",
      "Severe eye pain with headache, vomiting, haloes, a mid-dilated fixed pupil and a stony hard globe - acute angle closure; start acetazolamide and refer within hours.",
      "White corneal infiltrate or fluorescein staining beyond a simple linear abrasion - microbial keratitis; refer before any drop so a scraping can be taken.",
      "Painful red eye in a contact lens wearer - Pseudomonas or Acanthamoeba keratitis until proved otherwise.",
      "Hypopyon, hyphaema or loss of the red reflex in any red eye - refer immediately.",
      "Red painful eye with falling vision within 6 weeks of cataract surgery or intravitreal injection - endophthalmitis.",
      "Copious purulent discharge in a neonate or an adult with lid swelling - gonococcal conjunctivitis; systemic ceftriaxone today.",
      "Chemical splash - irrigate for 30 minutes before anything else, then refer.",
      "Severe boring pain waking the patient at night with violaceous non-blanching redness - scleritis, often with systemic vasculitis.",
    ],
    pearls: [
      "Record visual acuity before you touch the eye - normal acuity almost excludes the sight-threatening causes.",
      "Conjunctival injection is brightest in the fornices and blanches; ciliary injection is brightest at the limbus and does not.",
      "Photophobia means the cornea or iris is involved - simple conjunctivitis does not cause it.",
      "Itch means allergy; infection does not itch.",
      "A steroid drop in an undiagnosed red eye is the commonest avoidable cause of corneal blindness in Indian practice.",
      "Never send a patient home with a topical anaesthetic.",
      "Vomiting with a unilateral headache in an elderly patient - look at the pupil before diagnosing gastritis or migraine.",
      "One drop is enough - the conjunctival sac holds less than a quarter of a drop.",
      "Treat the fellow eye in angle closure - prophylactic laser iridotomy removes a 40-80% risk.",
    ],
    references: [
      "AK Khurana, Comprehensive Ophthalmology, 8th edition, 2022",
      "Kanski's Clinical Ophthalmology, 10th edition, 2024",
      "American Academy of Ophthalmology Preferred Practice Pattern: Conjunctivitis, 2023; Bacterial Keratitis, 2023",
      "Standard Treatment Guidelines, Ophthalmology, Ministry of Health and Family Welfare, Government of India",
      "CDC Sexually Transmitted Infections Treatment Guidelines, 2021",
      "NICE Clinical Knowledge Summaries: Conjunctivitis - infective, 2024",
      "WHO: India validated for elimination of trachoma as a public health problem, 2024",
      "Goodman and Gilman's The Pharmacological Basis of Therapeutics, 14th edition, 2023",
    ],
  },
};

export default rewrites;
