import type { TopicRewrite } from "../index";

const rewrites: Record<string, TopicRewrite> = {
  "musculoskeletal-low-back-pain": {
    oneLiner:
      "Low back pain is pain between the **costal margins and the gluteal folds**; over 90% is **non-specific mechanical pain** that needs a **red-flag screen, reassurance, staying active and a short NSAID course** - not imaging - while 5-10% is **radicular (sciatica)** and 1-2% is **serious pathology** (cauda equina, infection including Pott spine, cancer, fracture, axial spondyloarthritis).",
    sections: [
      {
        heading: "Definition and the classification that matters",
        points: [
          "**Low back pain** is pain, tension or stiffness **below the costal margin and above the inferior gluteal folds**, with or without leg pain - limits that exclude renal and hip pain. [NICE NG59 2020]",
          "By **duration** it is **acute under 6 weeks, sub-acute 6-12 weeks and chronic over 12 weeks** - the interval decides when imaging and a structured programme are even discussed. [NICE NG59 2020]",
          "The classification an examiner expects is **diagnostic triage into three boxes**: **non-specific (mechanical) pain over 90%**, **radicular pain or radiculopathy 5-10%**, and **specific serious pathology 1-2%** - everything that follows depends on the box. [Lancet LBP Series 2018]",
          "**Radicular pain (sciatica)** radiates **below the knee in a dermatomal pattern**, often worse in the leg than the back; referred facet or sacroiliac pain stops above the knee. [NICE NG59 2020]",
          "**Serious specific pathology** means cauda equina syndrome, infection (tuberculous or pyogenic spondylodiscitis, epidural abscess), malignancy (metastasis, myeloma), fracture and **axial spondyloarthritis**. [Harrison 22e]",
          "**Natural history**: about half improve within 1 week and **90% within 6 weeks**, but **recurrence within a year is 40-60%** - counsel recovery with recurrence, not cure. [Lancet LBP Series 2018]",
          "Low back pain is the **leading cause of years lived with disability worldwide**, with a lifetime prevalence of **50-70% in Indian community studies** - so function, not a pain score, is what to track. [GBD 2023]",
          "**Predictors of chronicity are psychosocial, not structural** - fear-avoidance beliefs, catastrophising, low mood, job dissatisfaction and pending compensation (yellow flags). [Lancet LBP Series 2018]",
        ],
      },
      {
        heading: "Pathophysiology and pathoanatomy",
        points: [
          "The **functional spinal unit** is a **three-joint complex** - the intervertebral disc in front and two synovial facet joints behind - so degeneration in one part loads the other two. [Bailey and Love 28e]",
          "The **disc** has a central **nucleus pulposus** (about 80% water, held by the proteoglycan **aggrecan** with type II collagen) inside the **annulus fibrosus** (concentric lamellae of type I collagen at alternating 30-degree angles) between cartilage **end plates**. [Harrison 22e]",
          "The adult disc is **avascular** and fed by diffusion through the end plates, so smoking, vibration and ageing starve it: proteoglycan falls, the nucleus dries, disc height drops and the annulus develops **radial fissures**. [Harrison 22e]",
          "**Discogenic pain**: only the **outer third of the annulus** is innervated (by the **sinuvertebral nerve**), but in degenerate discs nerve fibres and vessels grow inward along fissures, making the disc itself a pain generator on flexion and sitting. [Bailey and Love 28e]",
          "**Disc prolapse** usually goes **posterolateral** because the **posterior longitudinal ligament is narrow and weak laterally**; a posterolateral **L4-L5 disc compresses the traversing L5 root** and an **L5-S1 disc the S1 root**, while a far-lateral disc hits the exiting root (L4 at L4-L5). [Bailey and Love 28e]",
          "**Radicular pain is chemical as well as mechanical**: extruded nucleus is antigenic and releases **TNF-alpha, IL-1, IL-6 and phospholipase A2**, which inflame the root and **dorsal root ganglion** and cause ectopic firing - the reason epidural steroids help root pain. [Harrison 22e]",
          "**Why sciatica settles**: extruded and sequestered fragments are **resorbed by macrophages** and shrink over weeks, so about **75% of sciatica resolves in 6-12 weeks** without surgery. [NICE NG59 2020]",
          "**Stretch signs**: the straight leg raise tensions the **L4-S1 roots** (sciatic nerve) by 2-6 mm over 30-70 degrees of hip flexion, so an inflamed root tethered by a disc reproduces leg pain; the **femoral stretch test** tensions **L2-L4**. [Apley 10e]",
          "**Facet joints** are synovial joints innervated by the **medial branch of the dorsal ramus**; facet osteoarthritis gives pain on **extension and rotation** referred to the buttock and thigh - the target of medial branch radiofrequency denervation. [Bailey and Love 28e]",
          "**Lumbar canal stenosis** = **disc bulge in front plus facet hypertrophy and thickened ligamentum flavum behind**, giving a trefoil canal; **extension narrows and flexion widens it**, so patients walk bent forward (shopping-trolley sign). [Harrison 22e]",
          "**Neurogenic claudication** is venous congestion and ischaemia of the compressed cauda equina roots when walking upright - pain, heaviness and tingling in both legs relieved by **sitting or bending forward**, with normal pulses and preserved cycling tolerance. [Harrison 22e]",
          "**Cauda equina anatomy**: the cord ends (**conus**) at **L1-L2**, so below it a large **central L4-L5 or L5-S1 disc** compresses the **S2-S4 roots** that carry saddle sensation, detrusor (parasympathetic) and external sphincter supply - hence retention, saddle anaesthesia and lax anal tone. [Bailey and Love 28e]",
          "**Spondylolysis** is a stress fracture of the **pars interarticularis** (usually L5) from repeated extension in young athletes and bowlers; if bilateral the vertebra slips forward (**isthmic spondylolisthesis**), felt as a **palpable step**. [Apley 10e]",
          "**Degenerative spondylolisthesis** (usually L4-L5 in women over 50) comes from facet arthritis letting the vertebra slide with an intact pars, and adds stenosis. [Apley 10e]",
          "**Tuberculous spondylitis (Pott spine)** spreads by blood (arterial and **Batson venous plexus**) to the **paradiscal** vertebral body, destroys the anterior body and adjacent disc, and collapses into an angular **gibbus** with a **cold abscess** tracking along psoas. [Index TB 2016]",
          "**Metastases** (breast, prostate, lung, kidney, thyroid) and **myeloma** reach the vertebral body through the valveless Batson plexus; the **pedicle is lost early** (winking owl sign) and the disc is usually spared, unlike infection. [Harrison 22e]",
          "**Chronic low back pain** is dominated by **central sensitisation**: dorsal horn NMDA-mediated amplification and loss of descending serotonin-noradrenaline inhibition - which is why **exercise, CBT, duloxetine and amitriptyline** help while more imaging and passive therapy do not. [Lancet LBP Series 2018]",
          "**How the drugs map to mechanism**: NSAIDs block COX-2 production of **PGE2 that sensitises nociceptors**, muscle relaxants reduce reflex paraspinal spasm, SNRIs and TCAs restore descending inhibition, and epidural steroid damps root inflammation. [Goodman and Gilman 14e]",
          "**Imaging findings correlate poorly with pain**: disc degeneration, bulges and facet changes are present in a large majority of **asymptomatic people over 40**, so they are age, not disease. [Lancet LBP Series 2018]",
        ],
      },
      {
        heading: "History in the OPD",
        points: [
          "Ask **onset and mechanism** (lifting, twisting, fall), **site** and whether pain radiates **below the knee** - below-knee radiation with numbness or tingling marks a compressed root. [NICE NG59 2020]",
          "Ask which **postures aggravate and relieve** it: pain on sitting and bending suggests disc, pain on standing and extension suggests facet, and leg pain on walking relieved by **sitting or leaning forward** is neurogenic claudication. [Harrison 22e]",
          "Ask **morning stiffness and response to activity**: mechanical pain is worse with loading, better with rest and stiffness is **under 30 minutes**; **inflammatory back pain** is the reverse. [ASAS-EULAR 2022]",
          "Screen for **inflammatory back pain (ASAS)**: onset **before 40-45 years**, insidious, over 3 months, **night pain in the second half of the night**, improves with exercise not rest - 4 of 5 features suggest axial spondyloarthritis. [ASAS-EULAR 2022]",
          "Ask **bladder and bowel function and saddle sensation in every patient with leg symptoms** - hesitancy, poor stream, retention, incontinence or numbness on the toilet paper means cauda equina syndrome until an MRI says otherwise. [NICE NG59 2020]",
          "Ask the **red-flag sweep for tumour and infection**: age **under 20 or new pain over 50**, fever, **evening rise of temperature, night sweats, weight loss, unrelenting night pain**, known cancer. [NICE NG59 2020]",
          "Ask **risk factors for infection or fracture**: **diabetes, HIV, injecting drug use**, recent urinary, skin or dental infection, **long-term steroids**, known osteoporosis and trauma (minor trauma counts over 65). [NICE NG59 2020]",
          "In India always ask **tuberculosis contact, past TB and constitutional symptoms** - Pott spine is the commonest destructive spinal infection and presents early with only back pain. [Index TB 2016]",
          "Ask **progressive leg weakness**: tripping, foot slapping (foot drop, L5) or inability to stand on tiptoe (S1) - progressive motor loss changes the plan to urgent imaging. [NICE NG59 2020]",
          "Ask **occupation and loading**: manual lifting, farm and construction work, long **two-wheeler commutes** (whole-body vibration), prolonged sitting or squatting - each becomes an ergonomic counselling point. [Lancet LBP Series 2018]",
          "After 2 weeks ask the **yellow-flag questions**: what do you think is wrong, what are you afraid of, how are work, sleep and mood, is there a compensation claim - these predict chronicity better than any scan. [NICE NG59 2020]",
          "Ask **treatment already taken**: over-the-counter NSAID-muscle relaxant combinations, repeated intramuscular injections, steroids from quacks, belts and bed rest - and their side effects. [Lancet LBP Series 2018]",
          "Take a **drug and comorbidity history** that changes drug choice: **peptic ulcer, CKD, heart failure, hypertension, asthma with NSAID sensitivity, anticoagulants, SSRIs** (tramadol), pregnancy. [NICE NG59 2020]",
          "Record a **functional baseline** - walking distance, sitting tolerance, squatting for the toilet, work days lost - and titrate treatment against it, not against a fluctuating pain score. [NICE NG59 2020]",
        ],
      },
      {
        heading: "Examination",
        points: [
          "Expose from **mid-thorax to below the knees** with the patient standing; look from behind for scoliosis (sciatic list), spasm and wasting, and from the side for loss of lordosis, a **gibbus** (vertebral collapse, classically tuberculous) or a **step** (spondylolisthesis). [Apley 10e]",
          "Look for **midline hair tuft, dimple or sinus** (spinal dysraphism), **cafe-au-lait spots** (neurofibromatosis) and a **paraspinal or groin swelling** (cold abscess). [Apley 10e]",
          "**Gait, heel and toe walking**: inability to **heel-walk means L4-L5 (tibialis anterior) weakness** and inability to **toe-walk means S1 (gastrocnemius) weakness** - more sensitive than bedside power testing. [Apley 10e]",
          "**Palpate and percuss**: midline spinous process tenderness or **focal percussion tenderness** with the ulnar border of the fist suggests fracture or infection; a palpable step between spinous processes suggests spondylolisthesis. [Apley 10e]",
          "**Movements**: flexion (record **finger-floor distance**), extension, lateral flexion and rotation (seated to fix the pelvis); pain on extension-rotation suggests facet pain, pain on flexion suggests disc. [Apley 10e]",
          "**Modified Schober test**: mark the lumbosacral junction (dimples of Venus) and a point **10 cm above**; on full forward flexion an increase of **under 5 cm** means restricted lumbar flexion, as in axial spondyloarthritis. [ASAS-EULAR 2022]",
          "**Straight leg raise (SLR)**: patient supine, lift the straightened leg by the heel - it is positive when **pain radiating below the knee** (not hamstring tightness or back pain) is reproduced **between 30 and 70 degrees**; sensitive (about 90%) but not specific for disc prolapse. [Apley 10e]",
          "**Bragard (Lasegue) sharpening**: lower the leg just below the painful angle and **dorsiflex the ankle** - return of the leg pain confirms neural tension rather than hamstring pain. [Apley 10e]",
          "**Crossed SLR**: raising the **good leg reproduces pain in the affected leg** - insensitive but highly specific (about 90%) for a large central or axillary prolapse. [Apley 10e]",
          "**Slump test** (seated, slump the spine, flex the neck, extend the knee and dorsiflex the ankle; relief on neck extension is positive) is more sensitive than SLR for neural tension. [Apley 10e]",
          "**Femoral stretch test**: patient prone, flex the knee and extend the hip - **anterior thigh pain** means an **L2-L4 root** lesion, which the SLR misses. [Apley 10e]",
          "**Neurological examination by root**: L4 - knee extension, **knee jerk**, medial leg; **L5 - great toe extension (EHL) and dorsiflexion, first web space, reflexes preserved**; S1 - plantarflexion, **ankle jerk**, lateral foot; an **upgoing plantar means cord, not root**. [Apley 10e]",
          "Test **saddle sensation and anal tone (per rectal)** whenever bladder or bilateral leg symptoms are present, and palpate the bladder for painless retention - this is the cauda equina screen. [NICE NG59 2020]",
          "Examine **hips (FABER, internal rotation)**, **sacroiliac joints**, the **abdomen for an aortic aneurysm** and **peripheral pulses** (vascular claudication); **3 or more of 5 Waddell non-organic signs** mean a psychosocial component, not malingering and not absence of pathology. [Apley 10e]",
        ],
      },
      {
        heading: "Minimal investigations",
        points: [
          "**No imaging for non-specific low back pain without red flags** - early imaging does not improve outcome but increases anxiety, labelling, sick leave and surgery. [ACP 2017]",
          "**Plain radiograph** (lumbar AP and lateral) for suspected **fracture**, suspected spondylolisthesis, or pain persisting beyond **6 weeks** in an older patient; add an **AP pelvis** for sacroiliitis when inflammatory pain is suspected. [NICE NG59 2020]",
          "**MRI is the investigation of choice** for **cauda equina (emergency, same day), infection, malignancy, progressive deficit** and for radiculopathy when surgery or injection is being considered - it shows cord, roots, disc, marrow and abscess. [NICE NG59 2020]",
          "**ESR, CRP, complete blood count and urine routine** when infection or malignancy is suspected - a normal ESR and CRP make both much less likely. [Harrison 22e]",
          "In an older patient with pain and anaemia add **calcium, creatinine, alkaline phosphatase and serum protein electrophoresis with free light chains** for myeloma, and **PSA** in men. [Harrison 22e]",
          "Suspected **Pott spine**: MRI (paradiscal destruction, disc involvement, paravertebral abscess) then **CT-guided biopsy for CBNAAT (Xpert MTB/RIF) and culture** before starting therapy - drug resistance makes empirical treatment a gamble. [Index TB 2016]",
          "Suspected **axial spondyloarthritis**: CRP, **HLA-B27**, AP pelvis and, if negative, **MRI of the sacroiliac joints** (bone marrow oedema) - refer to rheumatology. [ASAS-EULAR 2022]",
          "**Do not order routinely**: MRI for acute non-specific pain, repeated radiographs, vitamin D and uric acid panels, or nerve conduction studies - and explain that degenerative changes on a report are normal ageing. [ACP 2017]",
        ],
      },
      {
        heading: "Treatment - general measures",
        points: [
          "**Advice is the treatment**: explain that this is a **mechanical strain of a strong spine with an excellent prognosis**, that **hurt is not harm**, and give a leaflet - fear, not tissue damage, is what disables. [NICE NG59 2020]",
          "**Stay active and avoid bed rest beyond 1-2 days** - immobility deconditions muscle and reinforces fear; resume normal activity gradually and **stay at or return early to work with modified duties**. [NICE NG59 2020]",
          "**Superficial heat** (hot water bag 15-20 minutes) helps acute pain and spasm and lets the patient move. [ACP 2017]",
          "**Stratify at the first visit with STarT Back** (table below): a total of **0-3 is low risk** (advice and analgesia in primary care); **4 or more with a psychosocial subscore (items 5-9) of 3 or less is medium risk** (physiotherapy-led exercise); **psychosocial subscore 4 or more is high risk** (psychologically informed physiotherapy). [NICE NG59 2020]",
          "**Exercise beats every drug for sub-acute and chronic pain**: core stabilisation, walking, **yoga**, Pilates or tai chi for **at least 8-12 weeks**, chosen by the patient's preference because adherence matters most. [WHO LBP 2023]",
          "Add **manual therapy (manipulation, massage) only alongside exercise**, and **CBT or pain education** for high-risk or chronic pain. [NICE NG59 2020]",
          "**Do not offer**: belts or corsets, traction, TENS, ultrasound, interferential therapy, foot orthotics, acupuncture as stand-alone care, or repeated intramuscular injections - no benefit and they build passive dependence. [NICE NG59 2020]",
          "**Ergonomics**: lift with the load close to the body and knees bent, avoid twisting while lifting, break sitting every 30-45 minutes, and use a firm but comfortable mattress; **weight loss and stopping smoking** help the disc. [Lancet LBP Series 2018]",
        ],
      },
      {
        heading: "Treatment - drugs",
        points: [
          "**Principle**: drugs are **short-term helpers to keep the patient moving**, not the treatment - use the lowest effective dose for the shortest time and review at 1-2 weeks. [NICE NG59 2020]",
          "**NSAIDs are first line** for acute and flare pain: they inhibit **COX-1 and COX-2**, reducing prostaglandin E2 that sensitises nociceptors and drives inflammation. [NICE NG59 2020]",
          "**Ibuprofen 400 mg orally three times a day after food** (maximum 2.4 g/day) for **5-7 days**, or **naproxen 250-500 mg twice daily** (lowest cardiovascular risk among non-selective NSAIDs). [NICE NG59 2020]",
          "Alternatives: **diclofenac 50 mg twice or three times daily** (maximum 150 mg/day; higher cardiovascular risk), **aceclofenac 100 mg twice daily**, or the COX-2 selective **etoricoxib 60-90 mg once daily** or **celecoxib 100-200 mg twice daily** when gastric risk is high. [BNF 2025]",
          "**How to take NSAIDs**: after food with a full glass of water, not lying down immediately; **one NSAID at a time** (no combination tablets of two NSAIDs); a missed dose is skipped if the next is due. [BNF 2025]",
          "**Gastroprotection**: add **omeprazole 20 mg** or **pantoprazole 40 mg once daily before breakfast** if age over 65, past ulcer or bleed, or on aspirin, anticoagulant, steroid or SSRI. [NICE NG59 2020]",
          "**NSAID side effects and contraindications**: dyspepsia, **GI bleeding**, **AKI and hyperkalaemia** (afferent arteriole constriction), fluid retention, raised BP, **MI and stroke** (especially COX-2 selective and diclofenac), bronchospasm in **aspirin-exacerbated respiratory disease**; avoid in **eGFR under 30, heart failure, active ulcer and third trimester**. [BNF 2025]",
          "**Paracetamol alone is no better than placebo for acute low back pain**, but **500 mg-1 g every 6 hours (maximum 4 g/day; 3 g if under 50 kg, elderly, alcohol use or liver disease)** is a safe add-on where NSAIDs are unsafe. [NICE NG59 2020]",
          "**Topical NSAID** (diclofenac 1% gel rubbed in 3-4 times daily) has little evidence in back pain and is not a substitute for movement. [NICE NG59 2020]",
          "**Skeletal muscle relaxants** give modest short-term relief in acute pain with spasm: **tizanidine 2-4 mg at night, up to three times daily for 3-7 days** (central alpha2 agonist); side effects drowsiness, **hypotension**, dry mouth, liver enzyme rise; **contraindicated with ciprofloxacin or fluvoxamine** (CYP1A2 inhibition raises levels tenfold). [ACP 2017]",
          "**Thiocolchicoside** (commonly sold in India) - maximum **8 mg orally every 12 hours for up to 7 days** (4 mg IM every 12 hours for up to 5 days); a metabolite causes **aneuploidy**, so avoid in pregnancy, lactation and women not using contraception; it is also proconvulsant. [EMA 2014]",
          "**Avoid fixed-dose NSAID-muscle relaxant combination tablets as routine long-term therapy** - they double sedation and hide NSAID dose creep. [Lancet LBP Series 2018]",
          "**Do not offer benzodiazepines, oral corticosteroids or opioids for chronic low back pain**; **tramadol 50 mg orally every 6-8 hours (maximum 300-400 mg/day, 300 mg over 75 years) for under 1-2 weeks** only for severe acute pain not controlled by an NSAID. [NICE NG59 2020]",
          "**Tramadol cautions**: nausea, dizziness, constipation, **seizures**, hypoglycaemia, **serotonin syndrome with SSRIs, SNRIs and TCAs**, dependence; the same applies to tapentadol - opioids do not beat NSAIDs for back pain. [ACP 2017]",
          "**Chronic low back pain**: ACP suggests **duloxetine** as a second-line drug - **30 mg once daily for 1 week, then 60 mg once daily**, with food; side effects nausea, dry mouth, sweating, insomnia, BP rise; avoid in eGFR under 30, liver disease and with MAOIs; taper to stop - NICE, by contrast, does not recommend antidepressants for back pain itself. [ACP 2017]",
          "**Sciatica (radicular pain)**: use an NSAID first; **NICE advises against gabapentinoids, other antiepileptics, oral steroids and benzodiazepines** because trials (pregabalin, PRECISE) showed no benefit over placebo and real harm. [NICE NG59 2020]",
          "If neuropathic leg pain persists, **amitriptyline 10 mg at night** (2 hours before bed), increased by 10 mg every 1-2 weeks to **25-50 mg**, or duloxetine can be tried per neuropathic pain guidance; warn about morning drowsiness, dry mouth, constipation, urinary retention and falls, and avoid after MI, in arrhythmia and glaucoma. [NICE CG173 2020]",
          "**Epidural steroid injection** (for example **triamcinolone or methylprednisolone 40-80 mg with local anaesthetic**, transforaminal or interlaminar under imaging) is considered for **acute severe sciatica**; it gives short-term relief only and does not change the surgery rate - specialist procedure. [NICE NG59 2020]",
          "**Medial branch radiofrequency denervation** is considered for chronic low back pain thought to arise from the facet joints after a positive diagnostic medial branch block, when non-surgical care has failed. [NICE NG59 2020]",
          "**Pregnancy**: paracetamol is the analgesic of choice; **avoid NSAIDs from 20 weeks** (fetal renal impairment, oligohydramnios, ductus closure) and avoid thiocolchicoside throughout. [BNF 2025]",
          "**Elderly and CKD**: prefer paracetamol and topical NSAID, avoid long NSAID courses, use half-dose tramadol, and avoid amitriptyline in the frail (anticholinergic burden, falls). [NICE NG59 2020]",
          "**Specific causes need specific drugs**: **Pott spine** - 2HRZE then HRE for a total of about **12 months** (extended for spinal disease); **axial spondyloarthritis** - full-dose NSAID then biologic; osteoporotic fracture - bone therapy. [Index TB 2016]",
        ],
      },
      {
        heading: "Acute presentation and emergency management",
        points: [
          "**Cauda equina syndrome (CES)** is the spinal emergency: **bilateral or alternating sciatica, saddle anaesthesia, bladder dysfunction (hesitancy, poor stream, retention with overflow), faecal incontinence, erectile dysfunction and lax anal tone**. [NICE NG59 2020]",
          "Grades that decide urgency: **CES-S (suspected, symptoms only), CES-I (incomplete - altered urinary sensation, still voluntary control) and CES-R (retention with overflow, painless)** - outcome is best when operated at CES-I, so act on early bladder symptoms. [GIRFT CES 2023]",
          "Action: **same-day emergency MRI** of the lumbosacral spine, **post-void bladder scan or catheter residual**, and **immediate referral to spinal surgery for decompression**, ideally as soon as possible and within 48 hours of onset. [GIRFT CES 2023]",
          "**Spinal epidural abscess**: back pain with fever, focal tenderness and evolving neurology in a diabetic, injecting drug user or after infection - blood cultures, urgent MRI and IV antibiotics covering **Staphylococcus aureus** plus surgical drainage. [Harrison 22e]",
          "**Metastatic spinal cord compression**: new back pain in a known cancer patient, band-like thoracic pain, or leg weakness - **dexamethasone 16 mg** then same-day MRI whole spine and oncology referral for radiotherapy or surgery. [NICE NG234 2023]",
          "**Ruptured or leaking abdominal aortic aneurysm** presents as sudden severe back or flank pain with collapse and a pulsatile mass in an older smoker - resuscitate and transfer immediately; never label it mechanical. [Bailey and Love 28e]",
          "**Acute severe mechanical back pain (spasm)**: NSAID, heat, short course of muscle relaxant and early mobilisation; avoid injectable opioid or steroid cocktails that are common in Indian practice. [NICE NG59 2020]",
        ],
      },
      {
        heading: "Follow-up, monitoring and when to refer",
        points: [
          "**Review at 1-2 weeks** for acute pain, and reassess the triage box if pain persists beyond **4-6 weeks** or new features appear. [NICE NG59 2020]",
          "At each visit check **function (walking distance, sitting, work), neurology (power, reflexes), red flags, drug side effects** (dyspepsia, BP, creatinine if NSAIDs continue) and yellow flags. [NICE NG59 2020]",
          "**Refer same day**: cauda equina, **progressive or severe motor deficit (foot drop, power 3/5 or less)**, suspected infection, malignancy or cord compression, and unstable fracture. [NICE NG59 2020]",
          "**Refer routinely** for radicular pain persisting beyond **6-12 weeks** despite conservative care, disabling lumbar canal stenosis, and mechanical pain failing a **12-week** exercise-based programme. [NICE NG59 2020]",
          "**Refer to rheumatology** for suspected axial spondyloarthritis (inflammatory back pain with raised CRP, HLA-B27, uveitis, psoriasis or IBD). [ASAS-EULAR 2022]",
          "**Discectomy** relieves leg pain faster in the first year but gives **similar results at 1-2 years** to conservative care, and surgery does not treat back pain itself - tell the patient before the surgical opinion. [Lancet LBP Series 2018]",
          "**Spinal fusion is not offered for non-specific low back pain** outside a randomised trial. [NICE NG59 2020]",
          "For chronic pain aim for **self-management**: a written flare plan (NSAID for 3-5 days, heat, keep moving), continued exercise, and a review of psychosocial barriers rather than repeated scans. [WHO LBP 2023]",
        ],
      },
    ],
    tables: [
      {
        heading: "Lumbar radiculopathy - root level classification",
        columns: ["Root (usual disc)", "Pain and sensory loss", "Weakness", "Reflex", "Stretch test"],
        rows: [
          ["L4 (L3-L4 disc)", "Anterior thigh, knee, medial leg to medial malleolus", "Knee extension (quadriceps), ankle inversion", "Knee jerk reduced", "Femoral stretch positive"],
          ["L5 (L4-L5 disc)", "Lateral leg, dorsum of foot, first web space", "Great toe extension (EHL), ankle dorsiflexion, foot drop; cannot heel-walk", "Both preserved", "SLR positive"],
          ["S1 (L5-S1 disc)", "Posterior calf, lateral border and sole of foot", "Ankle plantarflexion; cannot toe-walk", "Ankle jerk reduced", "SLR positive"],
          ["Cauda equina (central disc)", "Saddle area, bilateral legs", "Bilateral, variable", "Ankle jerks lost; lax anal tone", "Bilateral SLR"],
        ],
      },
      {
        heading: "STarT Back screening tool - score",
        columns: ["Component", "Finding", "Points"],
        rows: [
          ["1 Back pain spread down the leg in the last 2 weeks", "Agree", "1"],
          ["2 Pain in shoulder or neck in the last 2 weeks", "Agree", "1"],
          ["3 Only walked short distances because of back pain", "Agree", "1"],
          ["4 Dressed more slowly because of back pain", "Agree", "1"],
          ["5 Not really safe for me to be physically active", "Agree", "1"],
          ["6 Worrying thoughts going through my mind a lot", "Agree", "1"],
          ["7 My back pain is terrible and never going to get better", "Agree", "1"],
          ["8 I have not enjoyed things I used to", "Agree", "1"],
          ["9 Overall bothersomeness in the last 2 weeks", "Very much or extremely", "1"],
        ],
      },
      {
        heading: "Drugs: dose, duration and side effects",
        columns: ["Drug", "Mechanism", "Dose and duration", "Side effects", "How to take"],
        rows: [
          ["Ibuprofen", "Non-selective COX inhibitor; less PGE2 at nociceptors", "400 mg three times daily (maximum 2.4 g/day) for 5-7 days", "Dyspepsia, GI bleed, AKI, BP rise, bronchospasm", "After food with water; add PPI if over 65 or ulcer risk"],
          ["Naproxen", "Non-selective COX inhibitor, long half-life", "250-500 mg twice daily for 5-7 days", "As ibuprofen; lowest CV risk of NSAIDs", "After food; one NSAID at a time"],
          ["Etoricoxib or celecoxib", "COX-2 selective; spares gastric COX-1", "Etoricoxib 60-90 mg once daily; celecoxib 100-200 mg twice daily; short course", "MI, stroke, oedema, BP rise, AKI", "Avoid in IHD, stroke, uncontrolled BP; with or without food"],
          ["Paracetamol", "Central COX inhibition and serotonergic descending pathways", "500 mg-1 g every 6 h; maximum 4 g/day (3 g if under 50 kg, elderly, liver disease)", "Hepatotoxicity in overdose or alcohol use", "Add-on only; count all combination products"],
          ["Tizanidine", "Central alpha2 agonist; reduces spinal reflex spasm", "2-4 mg at night up to three times daily, 3-7 days", "Drowsiness, hypotension, dry mouth, raised liver enzymes", "Never with ciprofloxacin or fluvoxamine; no driving"],
          ["Tramadol", "Weak mu agonist plus serotonin-noradrenaline reuptake inhibition", "50 mg every 6-8 h; maximum 300-400 mg/day; under 1-2 weeks", "Nausea, dizziness, constipation, seizures, serotonin syndrome, dependence", "Rescue only; avoid with SSRIs, SNRIs, epilepsy"],
          ["Duloxetine", "SNRI; restores descending inhibition", "30 mg once daily for 1 week then 60 mg once daily; review at 8-12 weeks", "Nausea, sweating, insomnia, BP rise, withdrawal", "With food, morning; taper over 2-4 weeks to stop"],
          ["Amitriptyline", "TCA; serotonin-noradrenaline reuptake block, sodium channel block", "10 mg at night, increase to 25-50 mg over weeks", "Drowsiness, dry mouth, constipation, retention, arrhythmia, falls", "2 hours before bed; avoid after MI and in glaucoma"],
          ["Epidural triamcinolone or methylprednisolone", "Local anti-inflammatory action on inflamed root and DRG", "40-80 mg with local anaesthetic, single injection, may repeat once", "Transient hyperglycaemia, flushing, dural puncture headache, rare infection", "Specialist, image-guided, for acute severe sciatica only"],
        ],
      },
    ],
    redFlags: [
      "Saddle anaesthesia, urinary hesitancy, retention or overflow, faecal incontinence, lax anal tone or bilateral sciatica - cauda equina syndrome; same-day MRI and spinal surgical referral.",
      "Fever, evening rise, night sweats, weight loss, a gibbus or a cold abscess - Pott spine or pyogenic spondylodiscitis; MRI and biopsy for CBNAAT and culture before therapy.",
      "New back pain over 50 or under 20, known cancer, unrelenting night pain or unexplained weight loss - metastasis or myeloma until proved otherwise.",
      "Progressive leg weakness, new foot drop (power 3/5 or less) or an upgoing plantar - urgent MRI and surgical opinion.",
      "Back pain with fever in a diabetic, injecting drug user or after a skin or urinary infection - spinal epidural abscess; blood cultures and urgent MRI.",
      "Sudden severe back pain with collapse, hypotension or a pulsatile abdominal mass - leaking aortic aneurysm; resuscitate and transfer.",
      "Thoracic pain after trivial trauma in an older or steroid-treated patient - osteoporotic vertebral fracture; radiograph and bone assessment.",
      "Inflammatory back pain under 45 (night pain, stiffness over 30 minutes, better with exercise) - axial spondyloarthritis; do not call it mechanical.",
    ],
    pearls: [
      "Over 90% of low back pain is non-specific; the examiner wants the red-flag screen and triage, not an X-ray - no imaging in the first 6 weeks without a red flag.",
      "The best prescription for acute back pain is reassurance plus staying active; bed rest beyond 1-2 days harms.",
      "SLR is sensitive but not specific; crossed SLR is insensitive but highly specific for a large disc prolapse; the femoral stretch test is needed for L2-L4.",
      "An L4-L5 posterolateral disc compresses the L5 root (EHL weakness, first web space, reflexes normal); L5-S1 compresses S1 (ankle jerk lost, cannot toe-walk).",
      "Neurogenic claudication is relieved by sitting or bending forward and cycling is preserved; vascular claudication is relieved by standing still and pulses are absent.",
      "NICE advises against gabapentinoids, oral steroids and benzodiazepines for sciatica and against opioids for chronic back pain.",
      "STarT Back stratifies by psychosocial risk: total 0-3 low, 4 or more medium, psychosocial subscore 4 or more high.",
      "Degenerative changes are present in most asymptomatic adults over 40 - report them as ageing, not damage.",
      "In India, a young adult with back pain, evening fever and a gibbus has Pott spine until proved otherwise - get tissue for CBNAAT before treatment.",
    ],
    references: [
      "NICE NG59. Low back pain and sciatica in over 16s: assessment and management, 2016 (updated 2020).",
      "American College of Physicians. Noninvasive treatments for acute, subacute and chronic low back pain. Ann Intern Med 2017.",
      "WHO guideline for non-surgical management of chronic primary low back pain in adults in primary and community care settings, 2023.",
      "The Lancet Low Back Pain Series, 2018.",
      "Getting It Right First Time (GIRFT). National suspected cauda equina syndrome pathway, 2023.",
      "ASAS-EULAR recommendations for the management of axial spondyloarthritis, 2022 update.",
      "Index-TB Guidelines: Guidelines on extra-pulmonary tuberculosis for India, 2016.",
      "Harrison's Principles of Internal Medicine, 22nd edition, 2025 - Back and neck pain.",
      "Bailey and Love's Short Practice of Surgery, 28th edition, 2023 - The spine.",
      "Apley and Solomon's System of Orthopaedics and Trauma, 10th edition, 2018 - The back.",
      "NICE NG234. Spinal metastases and metastatic spinal cord compression, 2023.",
      "European Medicines Agency. Restrictions on use of thiocolchicoside-containing medicines, 2014.",
    ],
  },
  "musculoskeletal-knee-osteoarthritis": {
    oneLiner:
      "Knee osteoarthritis is a **whole-joint disease** (cartilage, subchondral bone, synovium, meniscus, muscle) diagnosed **clinically** in a person **45 or over with activity-related pain and morning stiffness of 30 minutes or less**; the core treatment for everyone is **education, quadriceps-strengthening exercise and 5-10% weight loss**, then **topical NSAID**, short oral NSAID courses with gastroprotection and intra-articular steroid for flares, and arthroplasty when function fails.",
    sections: [
      {
        heading: "Definition and the classification that matters",
        points: [
          "**Osteoarthritis** is a disease of the whole synovial joint with **focal cartilage loss, subchondral bone remodelling (sclerosis, cysts, bone marrow lesions), marginal osteophytes, synovitis and capsular thickening** - not simple wear and tear. [NICE NG226 2022]",
          "**Clinical diagnosis (NICE)**: age **45 or over**, **activity-related joint pain**, and **no morning stiffness or stiffness of 30 minutes or less** - no imaging or blood test is needed. [NICE NG226 2022]",
          "The **ACR clinical criteria** (knee pain plus 3 of 6: age over 50, stiffness under 30 minutes, crepitus, bony tenderness, bony enlargement, no palpable warmth) give 95% sensitivity and 69% specificity. [ACR 2019]",
          "The radiographic classification examiners ask is **Kellgren-Lawrence grades 0-4** (table below); grade 2 is the threshold for definite radiographic OA, but **grade never decides treatment or surgery** - symptoms and function do. [Apley 10e]",
          "By **compartment**: **medial tibiofemoral (commonest in India, with varus)**, lateral tibiofemoral (valgus), and **patellofemoral** (pain on stairs and rising, seen only on a skyline view). [Apley 10e]",
          "**Primary** OA has no single cause; **secondary** OA follows meniscal or cruciate injury, intra-articular fracture, inflammatory arthritis, septic arthritis, crystal disease, haemophilia or malalignment. [Harrison 22e]",
          "**Burden**: symptomatic knee OA affects **20-30% of Indian adults over 45** and up to 45% of women over 65 - squatting, floor sitting, obesity and varus knees raise Indian prevalence. [Chopra COPCORD 2015]",
          "**Pain correlates poorly with the radiograph** - many grade 3-4 knees are painless and many painful knees look near-normal - so treat symptoms and function, not the film. [NICE NG226 2022]",
        ],
      },
      {
        heading: "Pathophysiology and pathoanatomy",
        points: [
          "**Normal cartilage** is aneural, avascular hyaline tissue: sparse **chondrocytes** in a matrix of **type II collagen** (tensile strength) and **aggrecan** proteoglycan whose negative charges hold water and resist compression. [Harrison 22e]",
          "**Trigger**: abnormal load on normal cartilage (obesity, varus, meniscectomy, instability) or normal load on abnormal cartilage (age, genetics) makes chondrocytes switch to a **catabolic state**. [Harrison 22e]",
          "Catabolic chondrocytes and synovium release **IL-1beta, TNF-alpha and nitric oxide**, which induce **MMP-13 (collagenase)** and **ADAMTS-5 (aggrecanase)**; aggrecan is lost first, then collagen, producing **fibrillation, fissures and full-thickness loss**. [Harrison 22e]",
          "**Why there is pain although cartilage has no nerves**: pain comes from **subchondral bone** (bone marrow lesions, raised intraosseous pressure, microfractures), **synovitis**, stretched **periosteum over osteophytes**, capsule, ligaments, infrapatellar fat pad and entheses. [Harrison 22e]",
          "**Subchondral bone** thickens under load (**sclerosis**) and synovial fluid is forced through cracks to form **subchondral cysts (geodes)**; MRI **bone marrow lesions** track pain and progression. [Harrison 22e]",
          "**Osteophytes** grow at the joint margins by **endochondral ossification driven by TGF-beta and BMPs** - an attempt to spread load that produces **bony enlargement, coarse crepitus and restricted movement**. [Harrison 22e]",
          "**Synovitis** is driven by cartilage fragments and damage-associated molecules acting on **toll-like receptors**, producing a **small cool effusion**, gelling stiffness and flares - the target of NSAIDs and intra-articular steroid. [Harrison 22e]",
          "**Meniscal degeneration**: horizontal degenerate tears and **meniscal extrusion** remove the load-sharing function (menisci carry about half the load), so the tear is part of the arthritis, not a surgical lesion. [NICE NG226 2022]",
          "**Varus malalignment** moves the load line medially and raises the **knee adduction moment**; the medial compartment normally carries about 60-70% of the load, so medial OA worsens varus, which worsens medial OA (a vicious cycle). [Apley 10e]",
          "**Obesity** loads the joint mechanically - **each 1 kg of weight adds about 3-4 kg of force across the knee in stance** - and adipokines (leptin) add a systemic inflammatory drive, explaining hand OA in the obese too. [OARSI 2019]",
          "**Quadriceps weakness** is both cause and effect: effusion and pain cause **arthrogenic muscle inhibition** (reflex inhibition of the quadriceps), which removes the shock absorber and increases joint loading - the basis of exercise therapy. [OARSI 2019]",
          "**Giving way** in OA is usually quadriceps inhibition, not ligament failure; **fixed flexion deformity** comes from posterior capsular contracture and hamstring spasm and shortens the functional limb. [Apley 10e]",
          "**Baker (popliteal) cyst** is distension of the **gastrocnemius-semimembranosus bursa** through a one-way valve from an effusion; rupture tracks fluid into the calf and mimics DVT (crescent sign of bruising at the ankle). [Apley 10e]",
          "**Central sensitisation** develops in about a quarter of patients - widespread pain, pain out of proportion to the joint, poor response to arthroplasty - the reason **duloxetine** helps some knees. [ACR 2019]",
          "**Radiographic signs map to pathology**: **joint space narrowing** (cartilage loss, seen only when weight-bearing), **osteophytes, subchondral sclerosis and cysts**; periarticular osteopenia and erosions point instead to inflammatory arthritis. [Apley 10e]",
          "**Why drugs only relieve symptoms**: no drug yet slows cartilage loss - glucosamine, chondroitin, diacerein and hyaluronic acid have failed to show consistent structure or symptom benefit, so exercise and weight loss (which change load) are the disease-modifying measures. [OARSI 2019]",
        ],
      },
      {
        heading: "History in the OPD",
        points: [
          "Ask the **pain pattern**: worse with use, on **stairs, rising from a chair or the floor**, and at the end of the day, relieved by rest - load-related pain is the diagnosis; **rest and night pain** mean advanced disease or another cause. [NICE NG226 2022]",
          "Ask **morning stiffness duration**: under 30 minutes and **gelling after sitting** fits OA; stiffness **over 60 minutes** means inflammatory arthritis. [NICE NG226 2022]",
          "Ask the **site**: medial pain with bowing (medial OA), anterior pain on stairs and squatting (patellofemoral), and ask if the **hip** hurts - hip disease refers pain to the knee. [Apley 10e]",
          "Ask **mechanical symptoms**: true locking (cannot fully straighten - loose body or displaced meniscal tear), **giving way**, clicking and swelling after activity. [Apley 10e]",
          "Ask the **three Indian functional tasks** - **squatting for the toilet, sitting cross-legged on the floor, climbing stairs** - and walking distance; these define disability and later the arthroplasty decision. [Apley 10e]",
          "Ask **past knee injury or surgery** (meniscectomy, ACL tear, fracture), occupation (squatting, kneeling, carrying loads) and **weight change** - these explain early or unilateral OA. [NICE NG226 2022]",
          "Ask for **features against OA**: other joints swollen (hands, wrists), **prolonged stiffness, fever, rash, psoriasis, diarrhoea, urethritis, previous gout attacks** - a hot acute knee is gout, pseudogout or sepsis until aspirated. [NICE NG226 2022]",
          "Take a **drug history before any NSAID**: past ulcer or bleed, dyspepsia, **aspirin, anticoagulant, steroid, SSRI**, ACE inhibitor or ARB plus diuretic, lithium, methotrexate, and asthma with NSAID sensitivity. [NICE NG226 2022]",
          "Ask about **comorbidities** that change drugs and surgery: **CKD, heart failure, ischaemic heart disease, hypertension, diabetes**, liver disease, peripheral vascular disease. [NICE NG226 2022]",
          "Ask what the patient has already tried - **oral NSAID-over-the-counter combinations, repeated steroid injections, oil massage, belts, glucosamine, PRP** - and what they fear (many avoid walking to save the knee). [OARSI 2019]",
          "Ask **sleep, mood and social support** - poor sleep and low mood amplify pain and predict disability more than the radiograph. [NICE NG226 2022]",
        ],
      },
      {
        heading: "Examination",
        points: [
          "**Standing**: look for **varus or valgus**, quadriceps wasting, popliteal swelling, scars; watch the gait for antalgia and a **lateral (varus) thrust**, and ask the patient to squat if safe. [Apley 10e]",
          "**Quadriceps wasting**: measure thigh girth at a fixed point (for example **15 cm above the upper pole of the patella**) on both sides - a difference over 1-2 cm is significant. [Apley 10e]",
          "**Feel** temperature with the back of the hand (warmth means inflammation or sepsis, not simple OA), then **joint-line tenderness with the knee at 90 degrees**, patellar facets and the popliteal fossa for a Baker cyst. [Apley 10e]",
          "**Patellar tap** (large effusion): empty the suprapatellar pouch with one hand and push the patella sharply against the femur - a click means fluid; **bulge (wipe) test** for small effusions: stroke fluid up the medial side, then down the lateral side and watch the medial hollow refill. [Apley 10e]",
          "**Movement**: active then passive flexion and extension with a hand on the patella for **coarse crepitus**; normal arc is **0 to about 135 degrees**; a **fixed flexion deformity** is present if the knee cannot be pressed flat (measure the angle or hand-breadth gap). [Apley 10e]",
          "**Patellofemoral assessment**: tenderness on compressing the patella and pain on resisted extension; **Clarke's patellar grind test** is painful and nonspecific, so rely on history and the skyline view. [Apley 10e]",
          "**Collateral ligaments**: valgus (MCL) and varus (LCL) stress at **0 and 30 degrees** of flexion - laxity only at 30 degrees is an isolated collateral injury, laxity at 0 degrees means cruciate involvement too; in OA apparent laxity is often pseudolaxity from cartilage loss. [Apley 10e]",
          "**Cruciates**: **Lachman test** (knee at 20-30 degrees, stabilise the femur, pull the tibia forward - soft or absent end point means ACL tear) is more sensitive than the **anterior drawer at 90 degrees**; look for **posterior sag** first to avoid a false anterior drawer. [Apley 10e]",
          "**Meniscus**: **McMurray test** (full flexion, rotate the tibia and extend - painful click on the joint line) and **Thessaly test** (standing on the leg at 20 degrees flexion and twisting); **joint-line tenderness** is the most useful single sign. [Apley 10e]",
          "**Always examine the hip** (internal rotation in flexion) and the spine, plus distal pulses and neurology - hip OA refers pain to the knee, and vascular disease matters for surgery. [Apley 10e]",
          "**Functional tests**: timed **chair stand** without using the arms and walking - these are what exercise therapy improves and what surgical referral is based on. [OARSI 2019]",
          "**Signs against OA**: hot red joint, tense effusion, **soft boggy synovitis**, small hand-joint swelling, tophi, psoriatic plaques or nail pits, and fever. [NICE NG226 2022]",
        ],
      },
      {
        heading: "Minimal investigations",
        points: [
          "**No investigation is needed to diagnose typical knee OA** in a person 45 or over - start treatment on the clinical diagnosis. [NICE NG226 2022]",
          "Order **weight-bearing AP (ideally semi-flexed), lateral and skyline (Merchant) views** when the presentation is atypical, before surgical referral, or if another diagnosis is suspected - a **supine film hides joint-space loss** and only the skyline shows the patellofemoral joint. [Apley 10e]",
          "**ESR and CRP** are normal in OA and are done only to exclude inflammatory arthritis when features are atypical. [NICE NG226 2022]",
          "**Aspirate any hot or tense effusion**: OA fluid is clear, viscous, **under 2000 white cells/microlitre**; send cell count, Gram stain, culture and **polarised microscopy for urate or CPPD crystals**. [Harrison 22e]",
          "Before regular oral NSAIDs, check **creatinine and eGFR, potassium and blood pressure** as a baseline; add haemoglobin if there are GI symptoms. [NICE NG226 2022]",
          "**Do not order routinely**: MRI (degenerate meniscal tears are universal and mislead), **rheumatoid factor or uric acid in a typical OA presentation** (false positives create a disease), or repeated radiographs. [NICE NG226 2022]",
        ],
      },
      {
        heading: "Treatment - general measures",
        points: [
          "**Three core treatments for every patient at every stage - education, exercise and weight management** - say these first in any answer; drugs are adjuncts. [NICE NG226 2022]",
          "**Education**: OA is common, not a relentlessly progressive crippler; **exercise does not wear the joint out**, pain during exercise is acceptable if it settles within 24 hours, and most people stabilise. [NICE NG226 2022]",
          "**Therapeutic exercise** is the most effective single treatment: **static quadriceps sets, straight-leg raises, short-arc and terminal knee extension, then resistance and hip abductor strengthening**, daily, for at least **8-12 weeks**, preferably supervised at the start. [OARSI 2019]",
          "Add **low-impact aerobic activity** - level walking, cycling, swimming or water exercise - building to 150 minutes a week; **yoga and tai chi** are reasonable choices. [ACR 2019]",
          "**Weight loss of 5-10%** of body weight gives clinically meaningful pain relief (over 10% gives more), and **diet plus exercise beats either alone** - set a target in kilograms and review it. [OARSI 2019]",
          "**Joint protection in Indian homes**: avoid deep squatting, cross-legged sitting and kneeling; use a **Western commode or commode chair**, a raised chair and bed, and ground-floor living if stairs hurt. [Apley 10e]",
          "**Walking stick in the hand opposite the painful knee**, shock-absorbing footwear, local **heat or cold packs**, and a **tibiofemoral brace or patellar taping** for selected patients. [ACR 2019]",
          "**Not recommended**: **lateral wedge insoles, TENS, arthroscopic lavage or debridement, glucosamine, chondroitin, diacerein, intra-articular hyaluronic acid, PRP and stem-cell injections** - no consistent benefit over placebo. [ACR 2019]",
        ],
      },
      {
        heading: "Treatment - drugs",
        points: [
          "**Principle**: drugs relieve symptoms so the patient can exercise - use the **safest effective option at the lowest dose for the shortest time**, and review benefit and harm regularly. [NICE NG226 2022]",
          "**Topical NSAID is first line for knee OA**: **diclofenac 1% gel, 2-4 g (about a 4-6 cm ribbon) rubbed into the knee 3-4 times daily** (maximum 16 g/day for one knee), for **2-4 weeks then reassess**; the knee is superficial and tissue levels are useful at about **5-10% of systemic exposure**. [NICE NG226 2022]",
          "**How to use topical NSAID**: apply to clean dry intact skin, rub in gently, **wash hands after**, avoid occlusive dressings, heat pads and sunlight on the area; side effects are local rash and itch; safe in the elderly and CKD. [BNF 2025]",
          "**Topical capsaicin 0.025-0.075% cream** 3-4 times daily depletes **substance P** from C-fibres; burning in the first 1-2 weeks is expected, benefit takes 2-4 weeks, wash hands and avoid eyes - an option for knee OA in ACR guidance. [ACR 2019]",
          "**Paracetamol**: NICE no longer recommends routine paracetamol for OA (effect too small); use **500 mg-1 g up to four times daily** only for short, infrequent use or when NSAIDs are unsafe, **maximum 3 g/day in the elderly or under 50 kg**. [NICE NG226 2022]",
          "**Oral NSAID for flares or when topical fails**: **ibuprofen 400 mg three times daily** or **naproxen 250-500 mg twice daily** after food, for the shortest time (review at 2 weeks); **naproxen and low-dose ibuprofen have the lowest cardiovascular risk**. [NICE NG226 2022]",
          "**COX-2 selective NSAIDs**: **etoricoxib 30-60 mg once daily** (maximum 60 mg for OA) or **celecoxib 200 mg once daily or 100 mg twice daily** protect the stomach but not the heart or kidney; avoid in IHD, stroke, peripheral arterial disease and uncontrolled BP (over 140/90 for etoricoxib). [BNF 2025]",
          "**Avoid diclofenac orally** (50 mg twice daily, maximum 150 mg/day) in IHD, stroke, heart failure and peripheral arterial disease - its cardiovascular risk is similar to COX-2 inhibitors. [BNF 2025]",
          "**Always co-prescribe a PPI with oral NSAIDs** in OA (NICE): **omeprazole 20 mg or pantoprazole 40 mg once daily, 30 minutes before breakfast**. [NICE NG226 2022]",
          "**NSAID contraindications**: active ulcer or past bleed without protection, **eGFR under 30**, **decompensated heart failure, cirrhosis**, third trimester, aspirin-sensitive asthma; avoid the **triple whammy** (NSAID with ACE inhibitor or ARB plus diuretic) in the dehydrated elderly. [NICE NG226 2022]",
          "**NSAID interactions**: warfarin and DOACs (bleeding), **SSRIs** (GI bleed), lithium and **methotrexate** (reduced clearance, toxicity), antihypertensives (blunted effect), and low-dose aspirin (ibuprofen blocks its antiplatelet effect - give aspirin 30 minutes before ibuprofen). [BNF 2025]",
          "**NSAID monitoring**: **BP, weight, creatinine and potassium at 2-4 weeks** after starting, then **every 3-6 months** on regular use; ask about dyspepsia and black stools; stop if eGFR falls by over 25% or potassium rises. [NICE NG226 2022]",
          "**Intra-articular corticosteroid** for a flare with effusion or to allow exercise: **triamcinolone acetonide 40 mg** (or **methylprednisolone acetate 40-80 mg**) with **2-4 mL of 1% lignocaine**; relief lasts **2-8 weeks**; **maximum 3-4 injections a year** in one joint. [NICE NG226 2022]",
          "**Injection technique**: patient supine with the knee extended and relaxed, **superolateral approach** - mark the point one fingerbreadth above and lateral to the superolateral corner of the patella, **full aseptic no-touch technique**, 21G needle directed under the patella, **aspirate any effusion first** (and send it if cloudy), then inject. [Oxford Handbook of Rheumatology 4e]",
          "**After the injection**: rest the knee (avoid heavy use) for **24-48 hours**, expect a possible **post-injection flare** for 24-48 hours (ice and paracetamol), check glucose in diabetics (rise for 2-3 days), and **return at once for fever, increasing pain and swelling** (septic arthritis, about 1 in 10000-50000). [Oxford Handbook of Rheumatology 4e]",
          "**Do not inject** if there is **overlying skin infection, suspected septic joint, prosthetic joint, bleeding disorder or uncontrolled anticoagulation**, and avoid within about **3 months before planned arthroplasty** (higher prosthetic infection risk). [Oxford Handbook of Rheumatology 4e]",
          "**Duloxetine** (SNRI, restores descending pain inhibition) for chronic knee pain with central sensitisation or co-existing depression: **30 mg once daily for 1 week, then 60 mg once daily**, review at 8-12 weeks; nausea, dizziness, sweating, BP rise; avoid with MAOIs, tramadol caution (serotonin syndrome). [ACR 2019]",
          "**Tramadol 50 mg every 6-8 hours** is a conditional ACR option for short use only when NSAIDs are contraindicated; **NICE advises against weak opioids routinely and against strong opioids** - falls, confusion, constipation and dependence in the elderly. [NICE NG226 2022]",
          "**Do not use**: oral or IM systemic corticosteroids, glucosamine, chondroitin, diacerein (diarrhoea and liver toxicity), hyaluronic acid or PRP injections, or bisphosphonates for OA pain. [ACR 2019]",
          "**CKD, heart disease, elderly**: topical NSAID, short paracetamol use, intra-articular steroid and exercise are the safe backbone; if an oral NSAID is unavoidable, use naproxen at the lowest dose with a PPI and check creatinine in 1-2 weeks. [NICE NG226 2022]",
          "**Pregnancy** (young secondary OA): paracetamol and topical measures; **avoid oral NSAIDs from 20 weeks**. [BNF 2025]",
          "**Specialist options**: **genicular nerve radiofrequency ablation** for refractory pain in patients unfit for surgery, and **high tibial osteotomy, unicompartmental or total knee replacement** for disabling disease. [ACR 2019]",
        ],
      },
      {
        heading: "Follow-up, monitoring and when to refer",
        points: [
          "**Review at 4-6 weeks** after starting an exercise plan, then every **3-6 months**, checking pain, **function (stairs, squatting, walking distance, chair stand)**, weight and adherence to exercise. [NICE NG226 2022]",
          "On regular oral NSAIDs recheck **BP, creatinine, potassium and haemoglobin** every 3-6 months and ask about dyspepsia, melaena and ankle swelling. [NICE NG226 2022]",
          "**Refer for joint replacement** when **pain and functional limitation substantially affect quality of life and persist despite a properly delivered non-surgical package** - not on radiographic grade, age, BMI or smoking alone. [NICE NG226 2022]",
          "Counsel about knee replacement: **satisfaction about 80%**, **80-90% prosthesis survival at 15-20 years**, **prosthetic infection about 1-2%**, VTE risk, and that **deep squatting and floor sitting are usually not regained**. [Apley 10e]",
          "Younger patients with **isolated medial OA and varus** may suit **high tibial osteotomy or unicompartmental knee replacement**, preserving bone stock. [Apley 10e]",
          "**Do not refer for arthroscopic lavage or debridement** unless there is true locking from a loose body or displaced tear - it is no better than sham surgery for OA. [NICE NG226 2022]",
          "**Refer urgently** for a **hot swollen knee with fever** (septic arthritis), a true locked knee, a rapidly destructive joint, suspected tumour, or haemarthrosis after injury. [NICE NG226 2022]",
          "**Refer to rheumatology** if features suggest inflammatory arthritis - prolonged stiffness, small-joint synovitis, raised CRP, psoriasis or recurrent crystal attacks. [NICE NG226 2022]",
        ],
      },
    ],
    tables: [
      {
        heading: "Kellgren-Lawrence radiographic grading of knee osteoarthritis",
        columns: ["Grade", "Radiographic features", "Meaning"],
        rows: [
          ["0", "No features of OA", "Normal"],
          ["1", "Doubtful joint space narrowing, possible osteophytic lipping", "Doubtful OA"],
          ["2", "Definite osteophytes, possible joint space narrowing", "Minimal - threshold for definite radiographic OA"],
          ["3", "Multiple moderate osteophytes, definite narrowing, some sclerosis, possible deformity", "Moderate OA"],
          ["4", "Large osteophytes, marked narrowing, severe sclerosis, bone-end deformity", "Severe OA - arthroplasty only if symptoms and function warrant"],
        ],
      },
      {
        heading: "Drugs: dose, duration and side effects",
        columns: ["Drug", "Mechanism", "Dose and duration", "Side effects", "How to take"],
        rows: [
          ["Diclofenac 1% gel (topical NSAID)", "Local COX inhibition in periarticular tissue and synovium", "2-4 g to the knee 3-4 times daily (maximum 16 g/day per knee); reassess at 2-4 weeks", "Local rash, itch, photosensitivity", "Rub into intact skin, wash hands, no heat pad or bandage over it"],
          ["Capsaicin 0.025-0.075% cream", "TRPV1 agonist; depletes substance P from C-fibres", "3-4 times daily; benefit after 2-4 weeks", "Burning and redness in first 1-2 weeks", "Pea-sized amount; wash hands; keep away from eyes"],
          ["Ibuprofen", "Non-selective COX inhibitor", "400 mg three times daily after food; flares, shortest course", "Dyspepsia, GI bleed, AKI, BP rise, fluid retention", "With PPI; give aspirin 30 min before ibuprofen"],
          ["Naproxen", "Non-selective COX inhibitor; lowest CV risk", "250-500 mg twice daily after food; shortest course", "As ibuprofen", "With PPI; avoid in eGFR under 30 and heart failure"],
          ["Etoricoxib or celecoxib", "COX-2 selective", "Etoricoxib 30-60 mg once daily; celecoxib 200 mg daily or 100 mg twice daily", "MI, stroke, oedema, hypertension, AKI", "Avoid in IHD, stroke, uncontrolled BP; still give PPI in OA"],
          ["Paracetamol", "Central COX inhibition", "500 mg-1 g up to four times daily; maximum 3 g/day in elderly; short use", "Hepatotoxicity in overdose, alcohol, malnutrition", "Short infrequent use only; count combination products"],
          ["Triamcinolone acetonide (intra-articular)", "Suppresses synovitis (glucocorticoid receptor, less PGE2 and cytokines)", "40 mg with 2-4 mL 1% lignocaine; maximum 3-4 per year per joint", "Post-injection flare, hyperglycaemia, skin atrophy, rare septic arthritis", "Aseptic superolateral approach; rest 24-48 h; report fever or rising pain"],
          ["Duloxetine", "SNRI; restores descending pain inhibition", "30 mg once daily for 1 week, then 60 mg once daily; review at 8-12 weeks", "Nausea, dizziness, sweating, BP rise, withdrawal", "Morning with food; taper to stop"],
          ["Tramadol", "Weak mu agonist plus SNRI action", "50 mg every 6-8 h, short term only; maximum 300 mg/day in elderly", "Falls, confusion, constipation, seizures, serotonin syndrome", "Only if NSAIDs contraindicated; avoid with SSRIs and SNRIs"],
        ],
      },
    ],
    redFlags: [
      "Hot, swollen, very painful knee with fever or rigors - septic arthritis; aspirate and refer the same day, never inject steroid.",
      "Acute hot knee in an older patient - gout or pseudogout versus sepsis; aspirate for crystals, Gram stain and culture.",
      "True locking (cannot fully extend) after a twisting injury - displaced bucket-handle meniscal tear; orthopaedic referral.",
      "Night pain, rest pain, weight loss or a bony mass around the knee - bone tumour or metastasis; image urgently.",
      "Rapid joint destruction over weeks or a painless swollen deformed knee in a diabetic - infection, osteonecrosis or Charcot joint.",
      "Tense effusion after injury with inability to weight-bear - haemarthrosis from ACL tear or fracture; radiograph and refer.",
      "Prolonged morning stiffness, small-joint swelling or raised CRP in a patient labelled OA - inflammatory arthritis; reassess.",
      "Calf swelling after knee pain - ruptured Baker cyst versus DVT; do a Doppler before assuming it is the cyst.",
    ],
    pearls: [
      "Knee OA is a clinical diagnosis at 45 or over with activity-related pain and stiffness of 30 minutes or less - no X-ray needed.",
      "Education, exercise and weight loss are the core treatment for everyone - start every answer with them.",
      "Each kilogram of body weight adds 3-4 kg across the knee in stance; 5-10% weight loss gives real pain relief.",
      "Topical NSAID is first line for knee OA; NICE 2022 no longer recommends routine paracetamol or weak opioids.",
      "Always give a PPI with an oral NSAID in OA, and avoid the triple whammy (NSAID plus ACE inhibitor or ARB plus diuretic).",
      "Weight-bearing films with a skyline view - a supine film hides joint-space loss and misses the patellofemoral joint.",
      "Always examine the hip in knee pain - hip OA (and SCFE in adolescents) refers pain to the knee.",
      "Arthroscopic washout, glucosamine, hyaluronic acid and PRP do not beat placebo for knee OA.",
      "Refer for replacement on symptoms and function despite optimal non-surgical care, never on Kellgren-Lawrence grade alone.",
    ],
    references: [
      "NICE NG226. Osteoarthritis in over 16s: diagnosis and management, 2022.",
      "OARSI guidelines for the non-surgical management of knee, hip and polyarticular osteoarthritis, 2019.",
      "ACR/Arthritis Foundation guideline for the management of osteoarthritis of the hand, hip and knee, 2019.",
      "EULAR recommendations for the non-pharmacological core management of hip and knee osteoarthritis, 2023.",
      "Harrison's Principles of Internal Medicine, 22nd edition, 2025 - Osteoarthritis.",
      "Apley and Solomon's System of Orthopaedics and Trauma, 10th edition, 2018 - The knee.",
      "Oxford Handbook of Rheumatology, 4th edition, 2018 - Joint and soft tissue injection.",
      "British National Formulary (BNF), 2025 - NSAIDs.",
      "Chopra A. COPCORD India: community-based rheumatic disease epidemiology, 2015.",
    ],
  },
};

export default rewrites;
