import type { TopicRewrite } from "../index";

const rewrites: Record<string, TopicRewrite> = {
  "renal-urology-chronic-kidney-disease": {
    oneLiner:
      "Chronic kidney disease is abnormal kidney structure or function for **more than 3 months** - an **eGFR below 60 mL/min/1.73 m2** or a damage marker such as **urine ACR 30 mg/g or more** - staged on **two axes (G by eGFR, A by albuminuria)**, and slowed by four pillars: **BP control, maximum-dose ACE inhibitor or ARB, an SGLT2 inhibitor, and (in type 2 diabetes) finerenone and a GLP-1 receptor agonist**, with a statin for cardiovascular risk.",
    sections: [
      {
        heading: "Definition and the classification that matters",
        points: [
          "**CKD** is an abnormality of kidney structure or function **present for more than 3 months** with implications for health - the 3-month rule is what separates it from acute kidney injury, so a single abnormal creatinine is never CKD. [KDIGO 2024]",
          "It is diagnosed by **eGFR below 60 mL/min/1.73 m2** or by any **marker of damage** - albuminuria (ACR 30 mg/g or more), abnormal urine sediment (haematuria, casts), a tubular disorder, abnormal histology or imaging, or a past kidney transplant - so a normal eGFR never excludes CKD. [KDIGO 2024]",
          "The one classification examiners expect is the **KDIGO CGA staging**: **Cause**, **G category** (G1 90 or more, G2 60-89, G3a 45-59, G3b 30-44, G4 15-29, **G5 under 15 = kidney failure**) and **A category** (A1 ACR under 30, A2 30-300, A3 over 300 mg/g). [KDIGO 2024]",
          "In SI units **A2 is ACR 3-30 mg/mmol and A3 over 30 mg/mmol**; the old words microalbuminuria and macroalbuminuria are retired, and nephrotic-range proteinuria is ACR over 2200 mg/g (PCR over 3000 mg/g). [KDIGO 2024]",
          "**G1 and G2 count as CKD only if a damage marker is present** - an eGFR of 75 in an 80-year-old with a clean urine is ageing, not disease. [KDIGO 2024]",
          "Risk is read on the **KDIGO heat map** (low, moderately increased, high, very high), because albuminuria and eGFR predict death, cardiovascular events and kidney failure independently - **G3a A3 is worse than G3b A1**. [KDIGO 2024]",
          "Write the diagnosis in full, for example **'CKD G3b A2 due to diabetic kidney disease'** - a bare 'CKD stage 3' drops the albuminuria that drives both prognosis and drug choice. [KDIGO 2024]",
          "KDIGO 2024 adds the **Kidney Failure Risk Equation (KFRE)** (age, sex, eGFR, ACR) for G3-G5: a **5-year kidney failure risk of 3-5% or more** supports nephrology referral and a **2-year risk over 40%** starts kidney replacement planning. [KDIGO 2024]",
          "In India adult CKD prevalence is about **10-17%**; **diabetic kidney disease is the commonest cause**, followed by **CKD of unknown aetiology (CKDu)**, hypertensive disease and chronic glomerulonephritis. [ISN 2023]",
        ],
      },
      {
        heading: "Pathophysiology and pathoanatomy",
        points: [
          "**Common final pathway**: whatever the initial insult (diabetes, hypertension, glomerulonephritis, obstruction, toxins), nephrons are lost and the survivors **hyperfilter** - single-nephron GFR rises, which keeps total GFR near normal early but injures the remaining glomeruli. [Brenner and Rector 11e]",
          "**Glomerular hypertension** comes from **angiotensin II constricting the efferent arteriole** and from afferent dilatation (hyperglycaemia, high protein intake, loss of tubuloglomerular feedback) - which is why lowering intraglomerular pressure is the target of every kidney-protective drug. [Brenner and Rector 11e]",
          "Raised glomerular pressure stretches and detaches **podocytes**; bare basement membrane allows **albumin to leak**, and denuded capillary loops adhere to Bowman capsule, leading to **focal segmental sclerosis** - albuminuria is therefore both a marker and a cause of progression. [Brenner and Rector 11e]",
          "Filtered protein is reabsorbed by **proximal tubular cells**, which respond by releasing complement, chemokines and **TGF-beta**, activating interstitial fibroblasts - **tubulointerstitial fibrosis** correlates with eGFR loss better than glomerular damage. [Brenner and Rector 11e]",
          "**Mineralocorticoid receptor overactivation** in podocytes, mesangium, fibroblasts and macrophages drives inflammation and fibrosis beyond BP - the target of **finerenone**, a non-steroidal MRA that is anti-fibrotic with a smaller potassium effect than spironolactone. [KDIGO 2024]",
          "**SGLT2 inhibitors** block proximal sodium-glucose reabsorption, so more sodium reaches the **macula densa**, restoring **tubuloglomerular feedback** and constricting the afferent arteriole - intraglomerular pressure falls, giving the early reversible eGFR dip and long-term protection independent of glucose. [KDIGO 2024]",
          "**ACE inhibitors and ARBs** dilate the efferent arteriole and reduce albuminuria and TGF-beta, so a **creatinine rise of up to 30%** after starting them reflects the intended fall in glomerular pressure, not injury. [KDIGO 2024]",
          "**Hypertension in CKD** is driven by sodium and water retention, RAAS activation and sympathetic overactivity from the damaged kidney - so it is salt-sensitive and needs diuretics as GFR falls. [Harrison 22e]",
          "**Anaemia** (normocytic, normochromic) results from **reduced erythropoietin** from peritubular interstitial fibroblasts, plus **hepcidin** excess (inflammation, reduced clearance) that traps iron in macrophages and blocks gut absorption, plus shortened red cell survival and blood loss. [KDIGO 2012]",
          "**CKD-mineral and bone disorder** starts early: phosphate retention raises **FGF23** and lowers renal **klotho**, FGF23 suppresses 1-alpha-hydroxylase so **calcitriol falls**, calcium absorption falls, and **PTH rises** (secondary hyperparathyroidism), producing renal osteodystrophy and vascular calcification. [KDIGO 2017]",
          "**Metabolic acidosis** develops as falling nephron mass limits **ammoniagenesis**; acidosis drives muscle protein breakdown, bone buffering and further tubular injury - the reason bicarbonate is corrected. [KDIGO 2024]",
          "**Hyperkalaemia** appears late (usually eGFR under 20-25) because surviving nephrons and the colon increase potassium secretion, but it occurs earlier with **RAAS blockers, MRAs, NSAIDs, trimethoprim, type 4 RTA in diabetes** and potassium-rich salt substitutes. [KDIGO 2024]",
          "**Uraemic syndrome** (usually eGFR under 10-15) comes from retained toxins (urea, guanidines, indoxyl sulphate, p-cresyl sulphate, beta2-microglobulin): anorexia, nausea, pruritus, fatigue, bleeding from **platelet dysfunction**, pericarditis, neuropathy and encephalopathy. [Harrison 22e]",
          "**Cardiovascular disease is the commonest cause of death** - traditional risk factors plus LVH from hypertension and anaemia, **medial arterial calcification** from phosphate and FGF23, inflammation and endothelial dysfunction; most G3 patients die before they reach dialysis. [KDIGO 2024]",
          "**Diabetic kidney disease** evolves from hyperfiltration and kidney enlargement to mesangial expansion, GBM thickening and **Kimmelstiel-Wilson nodules**, with albuminuria usually preceding eGFR loss - so kidneys stay normal-sized or large. [Brenner and Rector 11e]",
          "**Small echogenic kidneys** reflect chronic scarring; kidneys stay **normal or large** in diabetic nephropathy, amyloidosis, polycystic kidney disease and HIV nephropathy. [Brenner and Rector 11e]",
          "**CKDu** (Uddanam in Andhra Pradesh, parts of Odisha, Goa and Tamil Nadu) is a **chronic tubulointerstitial nephritis** of young male farm workers linked to heat stress, recurrent dehydration, agrochemicals and heavy metals - with bland urine, little proteinuria and small kidneys. [ICMR 2023]",
          "**Drug handling changes**: reduced renal clearance, altered protein binding (low albumin, uraemic displacement) and a larger volume of distribution mean many drugs accumulate - the basis of renal dose adjustment. [Harrison 22e]",
        ],
      },
      {
        heading: "History in the OPD",
        points: [
          "Most early CKD is **silent** - ask directly about **nocturia** (loss of concentrating ability), **frothy urine** (proteinuria), **puffiness of face or feet**, and tiredness or breathlessness from anaemia. [Harrison 22e]",
          "Ask for **uraemic symptoms** in advanced disease: anorexia, nausea and morning vomiting, metallic taste, hiccups, **pruritus**, restless legs, cramps, sleep reversal, poor concentration - these suggest eGFR under about 15 and a need for dialysis planning. [Harrison 22e]",
          "Ask about **diabetes and hypertension** - duration, control, eye or foot complications - because diabetic retinopathy with albuminuria makes diabetic kidney disease likely and its absence prompts a search for another cause. [KDIGO 2024]",
          "Ask about **glomerular clues**: cola-coloured urine, rash, joint pains, mouth ulcers, haemoptysis, sore throat or skin infection before swelling - these point to glomerulonephritis, lupus or vasculitis needing referral. [KDIGO 2024]",
          "Ask about **obstructive and urological clues**: poor stream, dribbling, retention, **renal colic or passed stones**, recurrent UTI - obstruction is reversible and a catheter or relief can recover function. [KDIGO 2024]",
          "Take a full **drug history**: NSAIDs (including over-the-counter and topical overuse), **lithium, PPIs (interstitial nephritis), aminoglycosides, tenofovir, calcineurin inhibitors**, and **ayurvedic, siddha or unlabelled herbal preparations** containing heavy metals or aristolochic acid. [KDIGO 2024]",
          "Ask about **past AKI** (dengue, leptospirosis, snake bite, malaria, sepsis, obstetric AKI, contrast) - a past AKI episode raises the risk of later CKD several-fold. [KDIGO 2024]",
          "Ask about **occupation and place**: farm work in heat, long hours without water, pesticide use, living in a CKDu belt, lead exposure (battery, paint workers) - points to CKDu or toxic nephropathy. [ICMR 2023]",
          "Take a **family history** of kidney disease, dialysis, cysts, deafness (Alport), early stroke or aneurysm (polycystic kidney disease) - hereditary disease needs genetic counselling and screening of relatives. [KDIGO 2024]",
          "Ask about **cardiovascular symptoms** - angina, claudication, orthopnoea, stroke - because cardiovascular risk sets statin, antiplatelet and BP decisions. [KDIGO 2024]",
          "Ask about **diet**: salt, protein and potassium intake, **salt substitutes** (potassium chloride), coconut water and fruit juices, and whether the patient fasts for religious reasons - relevant to potassium, SGLT2 inhibitor sick-day rules and metformin. [KDIGO 2024]",
          "In a woman of child-bearing age ask about **pregnancy plans and contraception**, because ACE inhibitors, ARBs, finerenone and SGLT2 inhibitors must be stopped before conception. [KDIGO 2024]",
          "Ask about **cost, insurance and family support** (Ayushman Bharat PM-JAY, state schemes) early - they decide which drugs are sustainable and which dialysis modality is realistic. [ISN 2023]",
        ],
      },
      {
        heading: "Examination",
        points: [
          "Measure **BP seated after 5 minutes' rest**, with a correctly sized cuff, and check **postural BP** in diabetics and the elderly before intensifying treatment. [KDIGO 2021]",
          "Record **weight, BMI and oedema** (pedal, sacral, facial puffiness) at every visit - weight gain with oedema is the earliest sign of salt and water overload. [Harrison 22e]",
          "Look for **pallor** (anaemia), **sallow yellow-brown skin**, scratch marks, easy bruising and, in advanced disease, **uraemic fetor**, asterixis and a pericardial rub. [Harrison 22e]",
          "Look for **fluid overload**: raised JVP, basal crackles, pleural effusion, S3 - mandating diuretic escalation or urgent referral. [Harrison 22e]",
          "**Palpate the abdomen**: ballotable bilateral kidneys suggest **polycystic kidney disease** (look for hepatomegaly from liver cysts), a palpable bladder suggests **outflow obstruction**, and listen for a **renal bruit** (renal artery stenosis). [OHCM 11e]",
          "Do a **fundoscopy**: diabetic retinopathy supports diabetic kidney disease, and hypertensive retinopathy grades target-organ damage. [KDIGO 2024]",
          "Examine the **feet and peripheral pulses** (neuropathy, ulcers, peripheral arterial disease) - CKD with diabetes carries a high amputation risk. [ADA 2026]",
          "Look for **systemic disease**: malar rash, arthritis, purpura, oral ulcers (lupus, vasculitis), lymph nodes, and **a prostate on digital rectal examination** in older men with poor stream. [KDIGO 2024]",
          "Examine the **arms for vascular access**: an existing AV fistula (feel the thrill, hear the bruit) and protect the non-dominant forearm veins in G4-G5 patients. [KDIGO 2024]",
          "Check **bone and muscle**: proximal weakness, bone pain, and in children **short stature and rickets-like deformities** (renal osteodystrophy). [KDIGO 2017]",
        ],
      },
      {
        heading: "Minimal investigations",
        points: [
          "**Serum creatinine with eGFR by CKD-EPI 2021 (race-free)** stages CKD; **Cockcroft-Gault creatinine clearance** ([140 - age] x weight in kg / [72 x creatinine mg/dL], x 0.85 if female) is used for drug dosing. [KDIGO 2024]",
          "**Urine ACR on an early-morning spot sample** is the albuminuria test - dipstick misses A2 - and an abnormal result is **confirmed on repeat** because fever, exercise, UTI, menstruation, heart failure and marked hyperglycaemia raise it transiently. [KDIGO 2024]",
          "**Repeat eGFR and ACR at 3 months** to prove chronicity, unless old records already show it; a rise of creatinine over days to weeks is AKI and needs different action. [KDIGO 2024]",
          "Use **cystatin C (eGFRcr-cys)** when creatinine is unreliable - very low or high muscle mass, amputation, cirrhosis, vegetarian or bodybuilder, or before a narrow-therapeutic-index drug decision. [KDIGO 2024]",
          "**Urine microscopy**: dysmorphic red cells and **red cell casts** mean glomerulonephritis (refer), white cells without bacteria suggest interstitial nephritis or TB, and bland sediment fits diabetic, hypertensive or CKDu disease. [KDIGO 2024]",
          "**Ultrasound KUB** in every new case: size (normal 10-12 cm), cortical echogenicity and thickness, **hydronephrosis**, stones, cysts, and **post-void residual** - small echogenic kidneys mean chronic, irreversible scarring. [KDIGO 2024]",
          "Baseline bloods: **sodium, potassium, bicarbonate, calcium, phosphate, albumin, haemoglobin, HbA1c, lipid profile**, and from G3 onwards **PTH, alkaline phosphatase, 25-OH vitamin D, ferritin and transferrin saturation**. [KDIGO 2017]",
          "Screen **HBsAg, anti-HCV and HIV**, and check **anti-HBs** before hepatitis B vaccination and before dialysis. [KDIGO 2024]",
          "**Screen annually with ACR plus eGFR** everyone with diabetes (type 2 from diagnosis, type 1 after 5 years), hypertension, cardiovascular disease, obesity, family history, past AKI, stones or obstruction, HIV or age over 60. [KDIGO 2024]",
          "**Do not order routinely**: 24-hour urine protein (ACR or PCR replace it), CT with contrast, renal biopsy (specialist decision), or repeated MDRD/CKD-EPI 2009 estimates. [KDIGO 2024]",
        ],
      },
      {
        heading: "Treatment - general measures",
        points: [
          "Explain that CKD is usually **slowed, not cured**, that most damage is silent, and that **tablets that protect the kidney must be taken even when the patient feels well**. [KDIGO 2024]",
          "**Salt under 2 g sodium a day (under 5 g salt)** - avoid pickles, papad, namkeen, processed food and extra salt at the table; high sodium blunts the anti-albuminuric effect of RAS blockade. [KDIGO 2024]",
          "**Protein about 0.8 g/kg/day** in G3-G5 not on dialysis and avoid over 1.3 g/kg/day; very low protein diets only under dietitian supervision, since protein-energy wasting is common in India. [KDIGO 2024]",
          "**Potassium advice only if hyperkalaemic**: limit coconut water, banana, citrus, tomato, potato, dry fruits and **never use low-sodium salt substitutes (potassium chloride)**; leaching vegetables (cutting, soaking, boiling and discarding water) lowers potassium. [KDIGO 2024]",
          "**Phosphate**: limit processed foods, colas and additives containing phosphate (almost fully absorbed), rather than restricting natural protein sources. [KDIGO 2017]",
          "**Stop smoking and tobacco chewing**, aim for **150 minutes a week of moderate activity**, and target a healthy weight - all lower cardiovascular and kidney risk. [KDIGO 2024]",
          "**Nephrotoxin stewardship**: avoid NSAIDs (use paracetamol), avoid unlabelled herbal and ayurvedic 'kidney tonics', check every new prescription for renal dosing, and warn about contrast. [KDIGO 2024]",
          "**Sick-day rules**: during vomiting, diarrhoea or fever with poor intake, **temporarily stop SGLT2 inhibitor, metformin, ACE inhibitor or ARB, diuretics and NSAIDs**, and restart after 24-48 hours of normal eating and drinking. [KDIGO 2024]",
          "**Vaccinate**: **hepatitis B double dose (40 microgram at 0, 1, 2 and 6 months)** while eGFR is over 30 and check anti-HBs after, plus annual influenza, pneumococcal and COVID-19 vaccines. [KDIGO 2024]",
          "For CKDu belts advise **drinking water, shade and rest breaks during field work**, and safe pesticide handling. [ICMR 2023]",
        ],
      },
      {
        heading: "Treatment - drugs",
        points: [
          "**BP target**: **systolic under 120 mmHg** by standardised office measurement when tolerated, otherwise under 130/80 mmHg in routine Indian practice; relax targets in the frail and those with postural hypotension. [KDIGO 2021]",
          "**ACE inhibitor or ARB - mechanism**: blocks angiotensin II formation or its AT1 receptor, **dilating the efferent arteriole**, lowering intraglomerular pressure and albuminuria; indicated for CKD with **hypertension and ACR 30 mg/g or more** (strongest evidence at A3) and in diabetes with albuminuria. [KDIGO 2024]",
          "**Doses**: **ramipril 2.5 mg once daily up to 10 mg**, **enalapril 5 mg once daily up to 20 mg twice daily**, **telmisartan 40-80 mg once daily**, **losartan 50-100 mg once daily** - titrate every 2-4 weeks to the **maximum tolerated dose**, because the anti-albuminuric effect is dose-dependent. [KDIGO 2024]",
          "**Monitor creatinine and potassium 2-4 weeks** after starting or increasing: **continue if creatinine rises under 30%**; if it rises over 30% look for volume depletion, NSAIDs or renal artery stenosis and reduce or stop; treat potassium over 5.5 with diet, diuretic or binder rather than abandoning the drug. [KDIGO 2024]",
          "**ACE/ARB side effects**: dry cough with ACE inhibitors (switch to ARB), angioedema (stop both classes for life), hyperkalaemia, first-dose hypotension; **never combine ACE inhibitor with ARB or with aliskiren**; contraindicated in pregnancy and bilateral renal artery stenosis. [KDIGO 2024]",
          "**SGLT2 inhibitor - indication**: CKD with **eGFR 20 or more and ACR 200 mg/g or more**, or **heart failure**, or **type 2 diabetes with CKD** (recommended), and suggested for eGFR 20-45 with lower ACR; once started, **continue until dialysis or transplant** even if eGFR falls below 20. [KDIGO 2024]",
          "**SGLT2 inhibitor - dose and use**: **dapagliflozin 10 mg or empagliflozin 10 mg once daily**, morning, with or without food, no titration; expect a **reversible eGFR dip up to 30%** in 2-4 weeks and little glucose lowering below eGFR 45, but kidney and heart protection persists. [KDIGO 2024]",
          "**SGLT2 inhibitor - side effects**: **genital mycotic infection** (advise genital hygiene; treat with topical clotrimazole), volume depletion (reduce diuretic), **euglycaemic ketoacidosis** (stop during acute illness, fasting, low-carbohydrate diets and **3 days before major surgery**), and rarely Fournier gangrene; safe with any eGFR once started. [KDIGO 2024]",
          "**Finerenone - non-steroidal MRA**: blocks the mineralocorticoid receptor, reducing inflammation and fibrosis; for **type 2 diabetes with eGFR 25 or more, ACR 30 mg/g or more despite maximum RAS blockade and potassium 4.8 mmol/L or less** (can start up to 5.0 with close monitoring). [KDIGO 2024]",
          "**Finerenone dose**: **10 mg once daily if eGFR 25-59, 20 mg once daily if eGFR 60 or more**, with or without food; check **potassium at 4 weeks** - increase 10 to 20 mg if potassium is 4.8 or less and eGFR stable, **hold if potassium over 5.5** and restart at 10 mg when it is 5.0 or less. [KDIGO 2024]",
          "**Finerenone interactions**: contraindicated with **strong CYP3A4 inhibitors** (itraconazole, ketoconazole, clarithromycin, ritonavir) and avoid grapefruit; it can be combined with an SGLT2 inhibitor, which also lowers hyperkalaemia risk. [KDIGO 2024]",
          "**GLP-1 receptor agonist**: for type 2 diabetes with CKD not at glycaemic target despite metformin and SGLT2 inhibitor - **semaglutide 0.25 mg SC weekly for 4 weeks, 0.5 mg, then 1 mg weekly** reduced major kidney events by 24% (FLOW); oral semaglutide 3 mg then 7 mg then 14 mg daily is an alternative. [KDIGO 2024]",
          "**GLP-1 RA side effects**: nausea, vomiting and diarrhoea (slow titration, small meals), gallstones, pancreatitis; avoid with personal or family history of **medullary thyroid cancer or MEN2**; vomiting with volume loss can cause AKI. [ADA 2026]",
          "**Metformin by eGFR**: full dose at eGFR 45 or more, **maximum 1000 mg a day at eGFR 30-44**, **stop below 30**; hold on sick days and before iodinated contrast in G3b-G4 - risk is lactic acidosis. [KDIGO 2024]",
          "**Statin**: everyone with CKD **aged 50 or more** (and 18-49 with diabetes, coronary disease, stroke or high 10-year risk) - **atorvastatin 20 mg** or **rosuvastatin 10 mg (maximum 10 mg if eGFR under 30)** at night, or simvastatin 20 mg plus **ezetimibe 10 mg**; **do not start a statin de novo in dialysis patients**. [KDIGO 2024]",
          "**Diuretics for volume and BP**: **furosemide 40 mg once or twice daily, increasing to 80-160 mg** as eGFR falls (loop diuretics need higher doses in CKD); **chlorthalidone 12.5-25 mg daily** still lowers BP at eGFR 15-30 (CLICK trial), with monitoring of sodium, potassium and creatinine. [KDIGO 2021]",
          "**Metabolic acidosis**: consider **sodium bicarbonate 500 mg-1 g two or three times daily** when serum bicarbonate is **under 18 mmol/L** (KDIGO 2024) and do not push it above normal; side effects are bloating and sodium load (oedema, BP). [KDIGO 2024]",
          "**Hyperkalaemia (chronic)**: after diet and drug review, add a loop or thiazide diuretic, correct acidosis, and use a **potassium binder** so RAS blockade can continue - **sodium zirconium cyclosilicate 10 g three times daily for up to 48 hours then 5 g once daily**, **patiromer 8.4 g once daily**, or **calcium polystyrene sulfonate 15 g one to three times daily** (constipation; separate other drugs by 3 hours). [KDIGO 2024]",
          "**Anaemia - iron first**: give iron when **TSAT is 30% or less and ferritin 500 ng/mL or less** and before any ESA; in non-dialysis CKD try **oral iron (ferrous sulfate 200 mg once daily or on alternate days)** for 1-3 months, and give **IV iron** (iron sucrose 200 mg per dose to 1 g total, or **ferric carboxymaltose 20 mg/kg up to 1000 mg** over 15 minutes) if oral fails or Hb is low. [KDIGO 2012]",
          "**Erythropoiesis-stimulating agents** (specialist-started, Hb under 10 g/dL after iron repletion): **epoetin alfa 50-100 IU/kg SC three times weekly** (often 4000 IU SC once or twice weekly) or **darbepoetin 0.45 microgram/kg weekly**; target **Hb 10-11.5 g/dL, never intentionally above 13** (more stroke and death - TREAT, CHOIR). [KDIGO 2012]",
          "**ESA side effects**: hypertension, access thrombosis, stroke, seizures, pure red cell aplasia; poor response means iron deficiency, infection, inflammation, hyperparathyroidism, B12 or folate deficiency; oral **HIF-prolyl hydroxylase inhibitors (desidustat, daprodustat)** are specialist alternatives. [KDIGO 2012]",
          "**CKD-MBD**: lower raised phosphate towards normal with diet, then **phosphate binders taken with meals** - **calcium acetate 667 mg 1-2 tablets or calcium carbonate 500 mg-1 g with each meal**, or **sevelamer carbonate 800 mg 1-2 tablets three times daily with meals** if calcium is high or there is vascular calcification. [KDIGO 2017]",
          "Correct **vitamin D deficiency** with cholecalciferol (for example 60,000 IU weekly for 8 weeks then monthly); reserve **calcitriol 0.25 microgram daily** and cinacalcet for progressive or severe hyperparathyroidism under nephrology, avoiding hypercalcaemia and adynamic bone. [KDIGO 2017]",
          "**Renal dosing rules**: dose by Cockcroft-Gault CrCl, avoid **nitrofurantoin below eGFR 30-45**, reduce **gabapentin, pregabalin, DOACs, aminoglycosides, acyclovir, low molecular weight heparin**, and avoid **tramadol and morphine accumulation** - prefer paracetamol and small doses of short-acting opioids. [Harrison 22e]",
          "**Pregnancy**: stop ACE inhibitor, ARB, finerenone, SGLT2 inhibitor and statin before conception; use **labetalol or nifedipine** for BP and **low-dose aspirin 150 mg at night from 12 weeks** for pre-eclampsia prevention with nephrology-obstetric shared care. [KDIGO 2024]",
        ],
      },
      {
        heading: "Acute presentation and emergency management",
        points: [
          "**Acute-on-chronic kidney injury** (creatinine rising over days, oliguria, vomiting) is common with sepsis, dehydration, NSAIDs and contrast - stop nephrotoxins and sick-day drugs, assess volume, and admit if creatinine is rising fast or potassium is high. [KDIGO 2024]",
          "**Hyperkalaemia over 6.0 mmol/L or with ECG changes**: **10 mL of 10% calcium gluconate IV over 10 minutes**, **10 units regular insulin with 25 g glucose IV**, salbutamol 10-20 mg nebulised, then removal (binder, diuretic, dialysis) - refer the same day. [UK Kidney Association 2023]",
          "**Pulmonary oedema** in advanced CKD: sit up, oxygen, **IV furosemide 80-120 mg** (higher doses needed in CKD), nitrates if BP allows, and urgent dialysis if unresponsive or anuric. [Harrison 22e]",
          "**Absolute indications for urgent dialysis**: refractory hyperkalaemia, refractory fluid overload, severe acidosis (pH under 7.1), **uraemic pericarditis, encephalopathy or seizures**, and uraemic bleeding. [KDIGO 2024]",
          "**Uraemic bleeding** is from platelet dysfunction - correct anaemia, give **desmopressin 0.3 microgram/kg IV** before procedures, and dialyse. [Harrison 22e]",
        ],
      },
      {
        heading: "Follow-up, monitoring and when to refer",
        points: [
          "**Monitoring frequency by heat map**: eGFR and ACR **once a year** if low or moderately increased risk, **twice a year** if high risk, **3-4 times a year** if very high risk (G4-G5 or G3a-G3b with A3). [KDIGO 2024]",
          "At each review record **BP, weight, oedema, eGFR, ACR, potassium, bicarbonate**, and from G3b onwards **Hb, calcium, phosphate, PTH**; review every drug for renal dosing and nephrotoxins. [KDIGO 2024]",
          "**Progression** means a fall in G category with a **25% or greater eGFR drop**, and **rapid progression** is a sustained fall over **5 mL/min/1.73 m2 a year** - look for obstruction, drugs, uncontrolled BP or a second disease. [KDIGO 2024]",
          "**Targets**: systolic under 120 (or under 130/80), ACR reduced by at least 30%, **HbA1c 6.5-8.0% individualised**, potassium under 5.5, bicarbonate 18 or more, Hb 10-11.5 on ESA, and LDL lowered by statin. [KDIGO 2024]",
          "**Refer to nephrology**: **eGFR under 30**, **ACR 300 mg/g or more (PCR 500 or more)**, KFRE 5-year risk 3-5% or more, rapid progression, **red cell casts or unexplained haematuria**, resistant hypertension (4 or more drugs), persistent potassium or acid-base abnormality, recurrent stones, or suspected hereditary disease. [KDIGO 2024]",
          "**Refer early, around eGFR 30, not at 10**, so that dialysis modality, **AV fistula creation (about 6 months before expected dialysis)**, transplant work-up and vaccination can be done; late referral means emergency catheter dialysis and worse survival. [KDIGO 2024]",
          "**Protect the non-dominant arm veins** from G4 onwards - no BP cuff, venepuncture or cannula in that arm. [KDIGO 2024]",
          "Discuss **haemodialysis, peritoneal dialysis, pre-emptive transplant and conservative kidney management** with the family; free haemodialysis is available through the **Pradhan Mantri National Dialysis Programme** and packages under **PM-JAY**. [MoHFW 2024]",
          "**Conservative kidney management** (symptom control, anaemia and acidosis treatment, advance care planning) is a valid choice in the very old and frail, where dialysis may not prolong life. [KDIGO 2024]",
        ],
      },
    ],
    tables: [
      {
        heading: "KDIGO CKD classification: G category, A category and risk (heat map)",
        columns: ["G category (eGFR)", "Description", "Risk at A1 (ACR under 30)", "Risk at A2 (ACR 30-300)", "Risk at A3 (ACR over 300)"],
        rows: [
          ["G1 (90 or more)", "Normal or high - CKD only with a damage marker", "Low (no CKD if no other marker)", "Moderately increased", "High"],
          ["G2 (60-89)", "Mildly decreased - CKD only with a damage marker", "Low (no CKD if no other marker)", "Moderately increased", "High"],
          ["G3a (45-59)", "Mildly to moderately decreased", "Moderately increased", "High", "Very high"],
          ["G3b (30-44)", "Moderately to severely decreased", "High", "Very high", "Very high"],
          ["G4 (15-29)", "Severely decreased - refer", "Very high", "Very high", "Very high"],
          ["G5 (under 15)", "Kidney failure - dialysis, transplant or conservative care", "Very high", "Very high", "Very high"],
        ],
      },
      {
        heading: "Drugs: dose, duration and side effects",
        columns: ["Drug", "Mechanism", "Dose and duration", "Side effects", "How to take"],
        rows: [
          [
            "Ramipril or enalapril (ACE inhibitor); telmisartan or losartan (ARB)",
            "Efferent arteriolar dilatation lowers intraglomerular pressure and albuminuria",
            "Ramipril 2.5-10 mg OD; enalapril 5 mg OD to 20 mg BD; telmisartan 40-80 mg OD; losartan 50-100 mg OD; long-term at maximum tolerated dose",
            "Cough (ACE), angioedema, hyperkalaemia, creatinine rise, hypotension; teratogenic",
            "Start low, recheck creatinine and K at 2-4 weeks; accept rise under 30%; stop on sick days; never ACE plus ARB",
          ],
          [
            "Dapagliflozin or empagliflozin (SGLT2 inhibitor)",
            "Blocks proximal sodium-glucose reabsorption; restores tubuloglomerular feedback, afferent constriction",
            "10 mg once daily; start at eGFR 20 or more; continue until dialysis or transplant",
            "Genital thrush, volume depletion, euglycaemic ketoacidosis, reversible eGFR dip up to 30%",
            "Morning, with or without food; stop on sick days, fasting and 3 days before surgery",
          ],
          [
            "Finerenone (non-steroidal MRA)",
            "Blocks mineralocorticoid receptor - anti-inflammatory, anti-fibrotic",
            "10 mg OD if eGFR 25-59; 20 mg OD if 60 or more; start only if K 4.8 (up to 5.0) or less; long-term",
            "Hyperkalaemia, mild eGFR dip, hypotension",
            "With or without food; K at 4 weeks and after each change; no strong CYP3A4 inhibitors or grapefruit",
          ],
          [
            "Semaglutide (GLP-1 receptor agonist)",
            "Incretin: glucose-dependent insulin release, satiety, weight loss; anti-inflammatory kidney effect",
            "0.25 mg SC weekly x 4 weeks, then 0.5 mg, then 1 mg weekly; oral 3 mg to 7 mg to 14 mg daily",
            "Nausea, vomiting, diarrhoea, gallstones, pancreatitis; avoid in MTC or MEN2",
            "Same day each week, any time; oral form on empty stomach with sip of water 30 min before food",
          ],
          [
            "Atorvastatin or rosuvastatin (statin)",
            "HMG-CoA reductase inhibition lowers LDL and cardiovascular events",
            "Atorvastatin 20 mg; rosuvastatin 5-10 mg (maximum 10 mg if eGFR under 30); lifelong; not started de novo on dialysis",
            "Myalgia, raised transaminases, rarely rhabdomyolysis",
            "Once daily, evening for short-acting statins; report muscle pain or dark urine",
          ],
          [
            "Furosemide (loop diuretic)",
            "Blocks NKCC2 in the thick ascending limb - natriuresis",
            "40 mg OD-BD, up to 80-160 mg as eGFR falls; titrate to weight and oedema",
            "Volume depletion, hypokalaemia, hyponatraemia, gout, ototoxicity at high IV doses",
            "Morning (and early afternoon if BD); daily weight; hold on sick days",
          ],
          [
            "Sodium bicarbonate",
            "Alkali replaces lost bicarbonate, reduces muscle catabolism",
            "500 mg-1 g two or three times daily when bicarbonate under 18 mmol/L",
            "Bloating, sodium load, oedema, raised BP",
            "After meals; separate from other drugs by 2 hours",
          ],
          [
            "Calcium acetate or sevelamer (phosphate binder)",
            "Binds dietary phosphate in the gut",
            "Calcium acetate 667 mg 1-2 tabs with each meal; sevelamer carbonate 800 mg 1-2 tabs TDS with meals",
            "Hypercalcaemia, constipation (calcium); bloating (sevelamer)",
            "Must be taken with meals, not on empty stomach; skip with a skipped meal",
          ],
          [
            "Iron sucrose or ferric carboxymaltose (IV iron); ferrous sulfate (oral)",
            "Replaces iron stores; IV route bypasses hepcidin block",
            "Oral 200 mg OD or alternate days for 1-3 months; iron sucrose 200 mg per dose to 1 g; FCM 20 mg/kg up to 1000 mg",
            "Oral: GI upset, black stools; IV: hypophosphataemia (FCM), rare anaphylaxis",
            "Oral on empty stomach or with vitamin C, away from binders and PPIs; IV under observation",
          ],
          [
            "Epoetin alfa or darbepoetin (ESA)",
            "Replaces erythropoietin - stimulates red cell production",
            "Epoetin 50-100 IU/kg SC three times weekly (often 4000 IU weekly); darbepoetin 0.45 microgram/kg weekly; target Hb 10-11.5",
            "Hypertension, thrombosis, stroke, seizures, pure red cell aplasia",
            "SC into abdomen or thigh, rotate sites; store in fridge; iron replete first",
          ],
          [
            "Sodium zirconium cyclosilicate or calcium polystyrene sulfonate (K binder)",
            "Exchanges sodium or calcium for potassium in the gut",
            "SZC 10 g TDS up to 48 h then 5 g OD; CPS 15 g one to three times daily",
            "Oedema (SZC), constipation, hypomagnesaemia, rarely bowel necrosis (resins)",
            "Mix in water; separate other oral drugs by 2-3 hours",
          ],
        ],
      },
    ],
    redFlags: [
      "Creatinine rising over days with oliguria, vomiting or drowsiness - acute-on-chronic kidney injury; stop nephrotoxins and admit.",
      "Potassium over 6.0 mmol/L, or over 5.5 with ECG changes - emergency calcium gluconate, insulin-glucose and same-day referral.",
      "Pericardial rub, asterixis, confusion, seizures or intractable vomiting - uraemic emergency needing urgent dialysis.",
      "Breathlessness at rest with crackles, raised JVP and poor urine output - pulmonary oedema; IV furosemide and dialysis assessment.",
      "Hydronephrosis on ultrasound or a palpable bladder with rising creatinine - obstructive uropathy; catheterise and refer the same day.",
      "Haemoptysis with haematuria and rapidly rising creatinine - pulmonary-renal syndrome (ANCA vasculitis or anti-GBM); same-day nephrology.",
      "Creatinine rise over 30% or potassium over 5.5 within 4 weeks of starting ACE inhibitor or ARB - stop and look for volume depletion or renal artery stenosis.",
      "Red cell casts or heavy proteinuria (ACR over 300 mg/g) in a patient without diabetes - glomerular disease needing biopsy.",
    ],
    pearls: [
      "Stage on two axes - G from eGFR and A from ACR; G3a A3 carries more risk than G3b A1.",
      "One abnormal creatinine is not CKD - repeat at 3 months before labelling.",
      "CKD-EPI 2021 is for staging; Cockcroft-Gault creatinine clearance is for drug dosing.",
      "An eGFR dip up to 30% after starting an ACE inhibitor, ARB or SGLT2 inhibitor is the drug working - continue it.",
      "Once started, an SGLT2 inhibitor continues until dialysis or transplant, even when eGFR falls below 20.",
      "Finerenone needs type 2 diabetes, albuminuria despite maximum RAS blockade and potassium 4.8 or less - check potassium at 4 weeks.",
      "Small kidneys mean chronic disease - except diabetes, amyloid, polycystic kidneys and HIV nephropathy, which stay normal or large.",
      "Most patients with CKD G3 die of cardiovascular disease before dialysis - statin, BP and tobacco matter as much as creatinine.",
      "Give hepatitis B vaccine at double dose (40 microgram, 0-1-2-6 months) while eGFR is still above 30.",
      "Low-sodium salt substitutes are potassium chloride - dangerous in CKD with hyperkalaemia.",
    ],
    references: [
      "KDIGO 2024 Clinical Practice Guideline for the Evaluation and Management of Chronic Kidney Disease. Kidney Int 2024;105(4S):S117-S314.",
      "KDIGO 2022 Clinical Practice Guideline for Diabetes Management in Chronic Kidney Disease.",
      "KDIGO 2021 Clinical Practice Guideline for the Management of Blood Pressure in Chronic Kidney Disease.",
      "KDIGO 2017 Clinical Practice Guideline Update for CKD-Mineral and Bone Disorder.",
      "KDIGO 2012 Clinical Practice Guideline for Anemia in Chronic Kidney Disease.",
      "Perkovic V et al. FLOW trial - semaglutide and kidney outcomes in type 2 diabetes. N Engl J Med 2024;391:109-121.",
      "American Diabetes Association. Standards of Care in Diabetes - 2026, Section 11: Chronic Kidney Disease and Risk Management.",
      "Indian Society of Nephrology / ICMR - CKD and CKDu in India, Indian Journal of Nephrology reviews 2023.",
      "Pradhan Mantri National Dialysis Programme guidelines, MoHFW.",
      "Harrison's Principles of Internal Medicine, 22nd edition - chronic kidney disease.",
    ],
  },
};

export default rewrites;
