import type { TopicRewrite } from "../index";

const rewrites: Record<string, TopicRewrite> = {
  "surgery-office-blood-transfusion": {
    oneLiner:
      "Blood transfusion is the intravenous administration of a **specific blood component** (rarely whole blood) to correct a deficit that is causing or will cause harm - given on a **restrictive threshold (Hb 7 g/dL, 8 g/dL with cardiac disease or surgery), one unit at a time**, after **ABO and Rh D grouping, antibody screen and a bedside identity check**, because the commonest fatal reaction is still **the right blood given to the wrong patient**.",
    sections: [
      {
        heading: "Definition and the classification that matters",
        points: [
          "**Blood transfusion** is the therapeutic intravenous administration of whole blood or, far more usually, **a single component separated from it**, prescribed like any drug for a defined indication, dose and rate. [Bailey and Love 28e]",
          "**Component therapy is the rule**: one donation is separated into **packed red cells, fresh frozen plasma, platelets and cryoprecipitate**, so one donor treats three or four patients and each patient receives only what is missing. [NBTC 2022]",
          "**Whole blood** (450 mL plus 63 mL CPDA-1, 2-6 degrees C, 35 days) has no working platelets or factors V and VIII after 24-48 hours, so its only uses are **exchange transfusion and massive haemorrhage where components are unavailable**. [NBTC 2022]",
          "**Restrictive red cell threshold**: transfuse at **Hb below 7 g/dL** in most stable inpatients including ICU, septic shock and upper GI bleeding, and **below 8 g/dL** with cardiovascular disease or orthopaedic and cardiac surgery (TRICC, TRISS, Villanueva, FOCUS trials). [AABB 2023]",
          "**Acute myocardial infarction is the exception** - the MINT trial (2023) suggested harm from restrictive care, so many units aim for about **10 g/dL** in acute MI. [AABB 2023]",
          "**Symptomatic anaemia at any haemoglobin** (angina, syncope, dyspnoea at rest, heart failure) is an indication in its own right, and in **acute haemorrhage the decision is clinical** because the Hb lags for hours. [AABB 2023]",
          "**Massive transfusion** is replacement of **one blood volume in 24 hours, 10 units in 24 hours, or 4 units in 1 hour with ongoing bleeding** - it triggers a protocol, not unit-by-unit ordering. [ATLS 11e]",
          "The **ABC score** (penetrating mechanism, positive FAST, arrival SBP 90 mmHg or less, HR 120/min or more, 1 point each) of **2 or more predicts massive transfusion** and activates the protocol. [ATLS 11e]",
          "The classification examiners expect is **transfusion reactions by timing and mechanism** - acute (under 24 hours) versus delayed, immune versus non-immune - shown in the table below, plus the **ABO and Rh D compatibility** rules. [NBTC 2022]",
        ],
      },
      {
        heading: "Pathophysiology and pathoanatomy",
        points: [
          "**Oxygen delivery (DO2) = cardiac output x arterial O2 content**, and O2 content is 1.34 x Hb x SaO2 - so Hb matters, but a healthy heart compensates for anaemia by raising output and **oxygen extraction** from 25% to about 50%. [Harrison 22e]",
          "**Why 7 g/dL is safe**: normovolaemic anaemia to 7 g/dL is tolerated because blood viscosity falls, cardiac output rises and **2,3-DPG shifts the dissociation curve right**, whereas a coronary stenosis cannot increase flow, so the cardiac patient needs 8 g/dL. [AABB 2023]",
          "**Why the Hb lags in acute bleeding**: whole blood is lost isovolaemically, so the concentration stays normal until **transcapillary refill and crystalloid** dilute it over hours - shock class, not Hb, decides the first units. [Bailey and Love 28e]",
          "**ABO antigens** are sugars added to the **H substance** by glycosyltransferases coded on chromosome 9 - **N-acetylgalactosamine makes A, D-galactose makes B**, and group O carries only H (Bombay phenotype lacks even H). [Bailey and Love 28e]",
          "**Landsteiner's law**: every person has **naturally occurring IgM antibodies** against the ABO antigen they lack, formed by 3-6 months from gut bacterial antigens - which is why an ABO mismatch kills on the first exposure. [Bailey and Love 28e]",
          "**Acute haemolytic reaction mechanism**: preformed **IgM fixes complement** on donor cells, the membrane attack complex lyses them in the vessel, and C3a/C5a and cytokines (TNF, IL-1, IL-8) cause **fever, hypotension, loin pain and DIC** - as little as 10-15 mL can be fatal. [Harrison 22e]",
          "**Free haemoglobin** scavenges nitric oxide (vasoconstriction), saturates haptoglobin, appears in urine as **haemoglobinuria**, and with hypotension causes **pigment acute tubular necrosis** - hence the forced diuresis. [Harrison 22e]",
          "**Rh system**: the RHD and RHCE genes on chromosome 1 code D, C, c, E and e; **D is the most immunogenic** (about 80% of D-negative recipients make anti-D after exposure), and anti-D is an **immune IgG that crosses the placenta**. [Bailey and Love 28e]",
          "**Delayed haemolytic reaction** (3-14 days) is an **anamnestic IgG** response to a non-ABO antigen (Kidd, Rh, Kell, Duffy) to which the patient was sensitised by earlier pregnancy or transfusion - destruction is **extravascular in the spleen**, so it shows as jaundice and a falling Hb with a positive DAT. [NBTC 2022]",
          "**Febrile non-haemolytic reaction** comes from recipient anti-leucocyte (HLA) antibodies and **cytokines released by white cells during storage** - which is why **leucodepletion** prevents it better than premedication. [NBTC 2022]",
          "**Allergic and anaphylactic reactions** are IgE or anti-IgA antibodies against **donor plasma proteins** - an IgA-deficient recipient with anti-IgA reacts to a few mL, so washed cells or IgA-deficient plasma remove the antigen. [NBTC 2022]",
          "**TRALI** is a two-hit injury: a primed lung (sepsis, surgery) then **donor anti-HLA or anti-neutrophil (HNA) antibodies**, usually from multiparous women, activate neutrophils in pulmonary capillaries - non-cardiogenic oedema with a normal JVP and BNP. [NBTC 2022]",
          "**TACO** is hydrostatic pulmonary oedema from volume given faster than a stiff or failing heart can handle - the elderly, chronic anaemia, renal failure and small body size are at risk, and it is now the **commonest cause of transfusion death**. [SHOT 2023]",
          "**Storage lesion**: stored red cells lose 2,3-DPG and ATP, leak **potassium**, become less deformable and release microparticles, while **citrate** (the anticoagulant) chelates calcium - so rapid transfusion causes hyperkalaemia, hypocalcaemia and poorer oxygen release. [Miller 9e]",
          "**Platelets are stored warm (20-24 degrees C) with agitation** because cold activates and clears them, which is exactly why they carry the highest risk of **bacterial contamination** (skin staphylococci) and last only 5 days. [NBTC 2022]",
          "**Transfusion-associated GVHD**: viable donor T lymphocytes engraft when the recipient cannot reject them - in the immunosuppressed or when the donor is an **HLA-similar relative** - and attack skin, gut, liver and marrow; **25 Gy irradiation** prevents it. [NBTC 2022]",
          "**Lethal triad of haemorrhage**: hypothermia and acidosis slow clotting enzymes, and red cells plus crystalloid dilute factors and platelets - so balanced **1:1:1 plasma:platelet:red cell** resuscitation and early **tranexamic acid** (antifibrinolytic) prevent trauma-induced coagulopathy. [ATLS 11e]",
          "**Iron overload**: each unit carries 200-250 mg of iron and the body has **no excretory route**, so after 10-20 units iron deposits in liver, heart and endocrine glands - the basis of chelation in thalassaemia. [NBTC 2022]",
        ],
      },
      {
        heading: "History in the OPD",
        points: [
          "Ask **why transfusion is being considered**: symptoms of anaemia (breathlessness, fatigue, angina, syncope), active bleeding, or a planned operation - symptoms and ongoing loss, not the number, decide. [AABB 2023]",
          "Ask about the **cause and chronicity of anaemia** - menorrhagia, piles, melaena, worm infestation, diet, pregnancy - because chronic iron deficiency is treated with **iron, not blood**, even at Hb 6-7 g/dL if the patient is stable. [NBTC 2022]",
          "Ask for **previous transfusions and any reaction**, and for an **antibody card** - a known alloantibody needs antigen-negative blood and more time for a full crossmatch. [NBTC 2022]",
          "Ask every woman about **pregnancies, miscarriages and anti-D given** - pregnancy alloimmunises, and a D-negative girl or woman of childbearing age must never receive D-positive red cells. [NBTC 2022]",
          "Ask about **heart failure, renal failure, age over 70 and low body weight** - these predict **TACO**, so the unit is run slower with a diuretic. [SHOT 2023]",
          "Ask about **immunosuppression**: chemotherapy, purine analogues (fludarabine), stem cell transplant, congenital immunodeficiency - these need **irradiated** components. [NBTC 2022]",
          "Ask about **IgA deficiency or previous anaphylaxis** to blood - the patient needs washed cells or IgA-deficient plasma. [NBTC 2022]",
          "Take a **drug history**: warfarin, DOACs, antiplatelets, heparin (HIT), and iron or ESA already prescribed - reversal agents or waiting for a haematinic may avoid blood. [NBTC 2022]",
          "Ask about **religious or personal objection** (Jehovah's Witnesses) early, record an advance decision and plan **cell salvage, tranexamic acid, iron and ESA** as alternatives. [NBTC 2022]",
          "In a **thalassaemic or chronically transfused child** ask about transfusion interval, pre-transfusion Hb, chelator adherence and symptoms of iron overload (delayed puberty, diabetes, palpitations). [NBTC 2022]",
          "Ask any **potential donor** about recent fever, antibiotics, tattoo or surgery (6 months), malaria (3 months), delivery (12 months) and high-risk behaviour - these decide deferral. [NBTC 2022]",
        ],
      },
      {
        heading: "Examination",
        points: [
          "Look for **pallor** of conjunctiva, palms and nail beds, koilonychia (iron deficiency), jaundice (haemolysis) and signs of bleeding - the cause decides whether blood is needed. [Bailey and Love 28e]",
          "Assess **haemodynamic status**: pulse, BP, capillary refill, shock index (HR/SBP over 1 suggests significant loss) and urine output - **ATLS class III-IV shock (over 30% loss) needs red cells**. [ATLS 11e]",
          "Look for **heart failure** - raised JVP, basal crackles, gallop, pedal oedema - before transfusing, because such a patient needs a single slow unit with furosemide. [NBTC 2022]",
          "Record **baseline observations before the unit starts**: temperature, pulse, BP, respiratory rate and SpO2 - every later change is judged against these. [BSH 2017]",
          "Repeat observations **at 15 minutes, hourly during, at the end and 4 hours later** - a rise of temperature is often the first sign of a reaction. [BSH 2017]",
          "During the first 15 minutes **watch the patient directly** for flushing, rigors, restlessness, loin pain, urticaria, wheeze or pain at the drip site. [NBTC 2022]",
          "In the **anaesthetised or unconscious patient**, unexplained hypotension, tachycardia, oozing from wounds and haemoglobinuria in the catheter bag may be the only signs of haemolysis. [Miller 9e]",
          "If breathlessness develops, check **JVP, BP, fluid balance and chest** - raised JVP and hypertension suggest TACO, normal JVP with hypotension and fever suggests TRALI. [SHOT 2023]",
          "In chronically transfused patients look for **hepatosplenomegaly, bronze skin, short stature and delayed puberty** - features of iron overload and ineffective erythropoiesis. [NBTC 2022]",
        ],
      },
      {
        heading: "Minimal investigations",
        points: [
          "**Haemoglobin and full blood count** before and after each unit - one unit should raise Hb by about **1 g/dL in a 70 kg adult**, and a smaller rise suggests ongoing loss or haemolysis. [NBTC 2022]",
          "**ABO and Rh D grouping** by **forward grouping** (patient cells against anti-A, anti-B, anti-AB) and **reverse grouping** (patient serum against A, B and O cells) - the two must agree before blood is issued. [NBTC 2022]",
          "Reverse grouping is **unreliable below 4-6 months of age** and in hypogammaglobulinaemia or the very old, because isoagglutinin titres are too low. [NBTC 2022]",
          "**Antibody screen** by the **indirect antiglobulin test (IAT)** against screening cells detects irregular antibodies; a negative screen allows **immediate-spin or electronic issue** within minutes (type and screen). [NBTC 2022]",
          "**Crossmatch**: the **major crossmatch** (donor cells against recipient serum) in three phases - saline immediate spin at room temperature (IgM, ABO), 37 degrees C with LISS or albumin, and the **antiglobulin (Coombs) phase** (IgG); the minor crossmatch is obsolete. [NBTC 2022]",
          "The **direct antiglobulin test (DAT)** detects antibody already on the red cells in vivo - positive in haemolytic transfusion reactions, autoimmune haemolysis and haemolytic disease of the newborn. [NBTC 2022]",
          "**Coagulation (PT/INR, APTT, fibrinogen) and platelet count** guide FFP, cryoprecipitate and platelets; in massive haemorrhage use **viscoelastic tests (TEG/ROTEM)** where available. [ATLS 11e]",
          "After a suspected reaction send **repeat group and crossmatch, DAT, LDH, bilirubin, haptoglobin, urine for haemoglobin, creatinine, potassium, coagulation screen**, and **blood cultures from patient and pack**. [NBTC 2022]",
          "In breathlessness after transfusion a **chest X-ray and BNP** separate TACO (raised BNP, cardiomegaly, effusions) from TRALI (bilateral infiltrates, normal BNP). [SHOT 2023]",
          "Do **not** crossmatch routinely for operations that rarely need blood - book against a **Maximum Surgical Blood Ordering Schedule** and use group and screen instead. [NBTC 2022]",
        ],
      },
      {
        heading: "Treatment - general measures",
        points: [
          "**Patient blood management** has three pillars: **optimise the patient's own red cell mass** (treat anaemia with iron before surgery), **minimise blood loss** (haemostasis, tranexamic acid, cell salvage) and **tolerate anaemia** with restrictive thresholds. [NBTC 2022]",
          "**Explain the indication, benefit, risks and alternatives and record consent**, and write the reason for transfusion in the notes - an unrecorded indication is usually a weak one. [NBTC 2022]",
          "**Prescribe one unit at a time, then reassess** Hb and symptoms - the reflex two-unit order is the commonest avoidable over-transfusion. [AABB 2023]",
          "Safe bedside procedure step 1: **draw and label the sample at the bedside** from a positively identified patient, by the person who drew it, never pre-labelled. [BSH 2017]",
          "Step 2: collect the unit and **start within 30 minutes** of removal from the fridge, otherwise return it to the blood centre. [NBTC 2022]",
          "Step 3: do the **bedside identity check** immediately before spiking - ask the patient to **state** full name and date of birth, and match name, hospital number, donation number, group, expiry and pack integrity against the label and prescription, with two checkers where required. [BSH 2017]",
          "Step 4: use a **16-18 G cannula in adults (22-24 G in children)** and a dedicated set with a **170-200 micron filter**, changed every 12 hours or after 4 units. [NBTC 2022]",
          "Step 5: **only 0.9% saline** may share the line - **Ringer's lactate clots the unit** (calcium overrides citrate), **5% dextrose haemolyses it**, and no drug may be added. [NBTC 2022]",
          "Step 6: run the **first 15 minutes slowly (about 2 mL/min) under direct observation**, then complete a red cell unit in **90-120 minutes and always within 4 hours** of leaving storage. [NBTC 2022]",
          "Step 7: use a **blood warmer** only for rapid infusion (over 50 mL/kg/hour in adults), exchange transfusion or cold agglutinins - never hot water or a microwave. [NBTC 2022]",
          "Transfuse where the patient can be seen and **avoid unmonitored overnight transfusion**; tell the patient to report fever, rash, breathlessness or loin pain at once. [BSH 2017]",
          "**Special requirements**: **irradiated** components for the immunosuppressed and every directed donation from a relative, **leucodepleted** for recurrent febrile reactions, **washed** for IgA deficiency or severe allergic reactions, **CMV-safe** for neonates and transplant recipients. [NBTC 2022]",
        ],
      },
      {
        heading: "Treatment - drugs (components and adjuncts)",
        points: [
          "**Packed red cells** (200-250 mL, PCV 55-75%): restore oxygen-carrying capacity; adult dose **1 unit raises Hb about 1 g/dL**, child **10-15 mL/kg** (4 mL/kg raises Hb 1 g/dL); run over 90-120 minutes (3-4 hours in heart failure); store 2-6 degrees C for 35 days (CPDA-1) or 42 days (SAGM). [NBTC 2022]",
          "**Fresh frozen plasma** (200-250 mL, all factors about 1 IU/mL): dose **10-15 mL/kg (about 4 units in an adult)**, ABO-compatible (AB is the universal plasma donor), thawed at 37 degrees C and given within 4 hours, each unit over about 30 minutes. [NBTC 2022]",
          "Give FFP for **bleeding with PT or APTT over 1.5 times normal** (DIC, liver disease, dilution), in massive transfusion, for **TTP plasma exchange** and single factor deficiencies without a concentrate (V, XI) - **never as a volume expander or for hypoalbuminaemia**. [NBTC 2022]",
          "**Platelets**: **random donor (RDP) 1 unit raises the count 5,000-10,000/microlitre**, adult dose 4-6 RDP or **1 apheresis unit (SDP) raising 30,000-50,000**, child 10 mL/kg; infuse over 30 minutes, never refrigerate. [NBTC 2022]",
          "Platelet thresholds: **below 10,000 prophylactically** in stable marrow failure (20,000 with fever or sepsis), **below 50,000 for surgery or bleeding**, **below 100,000 for neurosurgery, eye surgery or head injury**; avoid in **TTP and HIT** unless bleeding is life-threatening. [NBTC 2022]",
          "**Cryoprecipitate** (10-20 mL; fibrinogen 150-250 mg, factor VIII, vWF, factor XIII): dose **1 unit per 5-10 kg (about 10 units in an adult)** raising fibrinogen about 50-100 mg/dL; give when **fibrinogen is below 1.5 g/L with bleeding (below 2 g/L in obstetric haemorrhage)**. [NBTC 2022]",
          "**Tranexamic acid** (antifibrinolytic - blocks lysine sites on plasminogen): trauma **1 g IV over 10 minutes then 1 g over 8 hours, started within 3 hours** of injury (CRASH-2); PPH 1 g IV, repeat once after 30 minutes; elective surgery 1 g at induction; side effects nausea, rare seizures at high dose; avoid in active thrombosis. [ATLS 11e]",
          "**Four-factor prothrombin complex concentrate** 25-50 IU/kg IV plus **vitamin K 5-10 mg IV slowly** reverses warfarin in major bleeding within minutes - preferred over FFP (volume and time); vitamin K sustains the reversal. [NBTC 2022]",
          "**Pre-operative and chronic anaemia - iron instead of blood**: oral **ferrous sulphate 200 mg (65 mg elemental) once daily or on alternate days**, on an empty stomach with vitamin C, not with tea or calcium, for 3 months after Hb normalises; side effects constipation, dark stools. [NBTC 2022]",
          "**Intravenous iron** when surgery is under 4-6 weeks away or oral iron fails: **ferric carboxymaltose 1000 mg IV over 15 minutes** (max 20 mg/kg per dose), iron sucrose 200 mg per dose; observe 30 minutes for hypersensitivity, check phosphate after repeated FCM. [NBTC 2022]",
          "**Furosemide 20-40 mg IV** before or between units in patients at risk of **TACO** (elderly, heart failure, chronic severe anaemia), and as treatment of TACO with oxygen and sitting up - but **never in TRALI**. [SHOT 2023]",
          "**Anaphylaxis**: **adrenaline 0.5 mg (0.5 mL of 1:1000) IM** into the anterolateral thigh, repeat every 5 minutes as needed, with oxygen and IV fluids; hydrocortisone 200 mg IV and chlorphenamine 10 mg IV are second-line only. [Resus Council UK 2021]",
          "**Simple urticaria**: stop, give **chlorphenamine 10 mg IV or IM** (cetirizine 10 mg orally if mild), and restart the same unit slowly if the rash settles and there are no systemic features - the only reaction where restarting is allowed. [NBTC 2022]",
          "**Febrile non-haemolytic reaction**: slow or stop, give **paracetamol 1 g orally or IV**, and exclude haemolysis and sepsis first; routine premedication with paracetamol or antihistamine is **not recommended** because it masks early signs of a serious reaction. [NBTC 2022]",
          "**Citrate toxicity and hypocalcaemia** in massive transfusion: **10 mL of 10% calcium gluconate IV over 10 minutes** (or 10 mL of 10% calcium chloride centrally), guided by ionised calcium kept above 1.1 mmol/L. [Miller 9e]",
          "**Hyperkalaemia** from old or irradiated units: calcium gluconate for the heart, then **insulin 10 units with 25 g glucose IV**; use fresh (under 5-7 days) or washed cells in neonates and renal failure. [Miller 9e]",
          "**Anti-D immunoglobulin** for the D-negative mother: **300 microgram IM at 28 weeks and within 72 hours of delivery** of a D-positive baby, **50 microgram** for a sensitising event before 12 weeks; size a large bleed by Kleihauer-Betke (extra 10 microgram per mL of fetal cells beyond). [NBTC 2022]",
          "**Iron chelation** in chronic transfusion when **ferritin exceeds 1000 ng/mL** (after 10-20 units): **deferasirox 20-40 mg/kg/day** orally once daily (film-coated tablet 14-28 mg/kg), monitor creatinine, liver enzymes and hearing; deferiprone 75-100 mg/kg/day in 3 doses (weekly neutrophil count for agranulocytosis); desferrioxamine 20-40 mg/kg SC over 8-12 hours 5-7 nights a week. [NBTC 2022]",
          "**Post-transfusion purpura**: **IVIG 1 g/kg daily for 2 days**, not platelets, which are destroyed as fast as they are given. [NBTC 2022]",
          "**Albumin** is a plasma derivative, not a transfusion: **20% albumin 8 g per litre of ascites** removed above 5 L, and in SBP **1.5 g/kg on day 1 and 1 g/kg on day 3** - not for routine resuscitation or a low serum albumin. [EASL 2018]",
        ],
      },
      {
        heading: "Acute presentation and emergency management",
        points: [
          "**Any reaction - first steps**: **stop the transfusion**, keep the vein open with **0.9% saline through a new giving set**, check airway, breathing and circulation, and **recheck the identity of patient and pack** at the bedside. [NBTC 2022]",
          "**Acute haemolytic reaction** (fever, rigors, loin or chest pain, pain at drip site, hypotension, dark urine, oozing): give oxygen, IV fluids to keep **urine output above 1-1.5 mL/kg/hour**, vasopressors for shock, treat DIC and hyperkalaemia, and call senior help. [Bailey and Love 28e]",
          "**Return the pack and giving set** with fresh samples for repeat grouping, crossmatch and DAT, inform the blood centre so **other units from the same collection are quarantined**, and report to the **Haemovigilance Programme of India**. [HvPI 2023]",
          "**Anaphylaxis** (stridor, wheeze, angioedema, hypotension): IM adrenaline first, oxygen, fluids; later transfuse only **washed or IgA-deficient** components and check IgA levels and anti-IgA. [NBTC 2022]",
          "**Bacterial contamination** (high fever, rigors, vomiting, shock within minutes, especially with platelets): stop, **culture patient and pack**, start **broad-spectrum IV antibiotics** (for example piperacillin-tazobactam 4.5 g 8-hourly) and resuscitate. [NBTC 2022]",
          "**TRALI** (hypoxaemia and bilateral infiltrates within 6 hours, normal JVP): stop, oxygen, ventilation if needed, **no diuretics**; most recover in 48-96 hours; report so the donor is deferred. [SHOT 2023]",
          "**TACO** (dyspnoea, orthopnoea, hypertension, raised JVP within 6-12 hours): stop or slow, sit up, oxygen, **furosemide 40 mg IV**, and plan future units slower with a diuretic. [SHOT 2023]",
          "**Massive transfusion protocol**: control bleeding (pressure, tourniquet, surgery, embolisation), give **red cells, FFP and platelets 1:1:1** (PROPPR), **tranexamic acid within 3 hours**, and use **O-negative uncrossmatched cells** (O-positive acceptable for men and post-menopausal women) until group-specific blood arrives. [ATLS 11e]",
          "**Targets in massive haemorrhage**: Hb 7-9 g/dL, **platelets above 50,000 (100,000 in head injury), fibrinogen above 1.5-2 g/L, PT and APTT under 1.5 times normal, ionised calcium above 1.1 mmol/L, temperature above 35 degrees C, pH above 7.2**. [ATLS 11e]",
        ],
      },
      {
        heading: "Follow-up, monitoring and when to refer",
        points: [
          "Recheck **Hb 1-24 hours after each unit** and document the response; an inadequate rise means ongoing bleeding, haemolysis or hypersplenism. [NBTC 2022]",
          "Watch for **delayed haemolysis at 3-14 days** - unexplained fall in Hb, jaundice, dark urine - and send DAT and antibody screen; record the antibody and give the patient an **antibody card**. [NBTC 2022]",
          "In **chronically transfused thalassaemia**, keep a **pre-transfusion Hb of 9-10.5 g/dL**, check **ferritin every 3 months**, annual cardiac T2* MRI where available, and screen for HIV, HBV and HCV yearly. [TIF 2021]",
          "India mandates **five tests on every unit - HIV 1 and 2, HBsAg, anti-HCV, syphilis and malaria**; **NAT is not yet mandatory nationally** but shortens the HIV window from about 22 to 5-6 days where used. [NACO 2022]",
          "**Professional (paid) donation is illegal** since the Supreme Court judgment of 1996 (effective 1998); blood is a **drug** under the Drugs and Cosmetics Act, and blood centres are licensed on **Form 26-G**. [NBTC 2022]",
          "**Donor criteria**: age 18-65, weight **45 kg for 350 mL and 55 kg for 450 mL**, Hb **12.5 g/dL or more**, interval **3 months (men) and 4 months (women)** between whole blood donations. [NBTC 2022]",
          "Report every reaction to the **Haemovigilance Programme of India** (launched 10 December 2012 by the Indian Pharmacopoeia Commission) - reporting is a duty. [HvPI 2023]",
          "Refer to a hospital blood centre for **any reaction, alloantibody, need for irradiated or washed components, chronic transfusion programmes** and every case of haemolysis or suspected TA-GVHD. [NBTC 2022]",
          "The **family physician** corrects the belief that every low Hb needs blood, treats iron deficiency, prepares patients for surgery with iron, and **motivates voluntary non-remunerated donation**. [NBTC 2022]",
        ],
      },
    ],
    tables: [
      {
        heading: "Drugs: dose, duration and side effects",
        columns: ["Drug", "Mechanism", "Dose and duration", "Side effects", "How to take"],
        rows: [
          ["Packed red cells", "Restore oxygen-carrying capacity", "1 unit raises Hb about 1 g/dL; child 10-15 mL/kg; threshold Hb 7 g/dL (8 g/dL cardiac or surgical)", "Haemolytic, febrile, allergic reactions, TACO, iron overload", "One unit at a time over 90-120 min, within 4 h of issue; saline only in line; observe first 15 min"],
          ["Fresh frozen plasma", "Replaces all coagulation factors", "10-15 mL/kg (about 4 units adult) for bleeding with PT/APTT over 1.5 x normal", "TRALI, TACO, allergy", "ABO-compatible; thaw at 37 degrees C, use within 4 h; each unit over about 30 min"],
          ["Platelets (RDP or SDP)", "Replace platelets for primary haemostasis", "4-6 RDP or 1 SDP adult; child 10 mL/kg; below 10,000 prophylactic, 50,000 surgery, 100,000 neurosurgery", "Bacterial sepsis, febrile reaction, refractoriness", "Store 20-24 degrees C with agitation, never refrigerate; infuse over 30 min"],
          ["Cryoprecipitate", "Concentrated fibrinogen, factor VIII, vWF, factor XIII", "1 unit per 5-10 kg (about 10 units adult) when fibrinogen below 1.5 g/L (2 g/L obstetric)", "Allergy, volume load small", "Thaw and use within 4 h; pooled units over 30 min"],
          ["Tranexamic acid", "Antifibrinolytic - blocks plasminogen lysine sites", "Trauma 1 g IV over 10 min then 1 g over 8 h, within 3 h of injury; PPH 1 g, repeat once", "Nausea, hypotension if fast, seizures at high dose", "Slow IV; do not start after 3 h in trauma; avoid in active thrombosis"],
          ["Four-factor PCC plus vitamin K", "Replaces factors II, VII, IX, X", "PCC 25-50 IU/kg IV plus vitamin K 5-10 mg IV", "Thrombosis, rare anaphylaxis to vitamin K", "Vitamin K by slow IV over 20-30 min; recheck INR 30 min after PCC"],
          ["Furosemide", "Loop diuretic - removes excess volume", "20-40 mg IV before or between units; 40 mg IV for TACO", "Hypokalaemia, hypotension", "Only for TACO risk or TACO; never in TRALI"],
          ["Adrenaline 1:1000", "Alpha and beta agonist - reverses anaphylaxis", "0.5 mg (0.5 mL) IM, repeat every 5 min as needed", "Tachycardia, arrhythmia, hypertension", "Anterolateral thigh; first drug before steroid or antihistamine"],
          ["Calcium gluconate 10%", "Replaces calcium chelated by citrate; stabilises myocardium", "10 mL IV over 10 min; repeat to keep ionised Ca above 1.1 mmol/L", "Tissue necrosis if extravasated, bradycardia if fast", "Separate line from blood; slow IV"],
          ["Deferasirox", "Oral iron chelator", "20-40 mg/kg once daily when ferritin over 1000 ng/mL", "Renal and liver toxicity, GI upset, hearing and eye changes", "Once daily on empty stomach (dispersible) or with light meal (film-coated); monthly creatinine and LFT"],
          ["Anti-D immunoglobulin", "Clears D-positive fetal cells before sensitisation", "300 microgram IM at 28 weeks and within 72 h of delivery; 50 microgram before 12 weeks", "Local pain, rare allergy", "Deep IM; within 72 h of the sensitising event"],
        ],
      },
      {
        heading: "Types of transfusion reaction: timing, mechanism and action",
        columns: ["Reaction", "Timing", "Mechanism", "Key features", "Immediate action"],
        rows: [
          ["Acute haemolytic", "Minutes, after 10-15 mL", "ABO mismatch, IgM plus complement - clerical error", "Fever, loin and drip-site pain, hypotension, haemoglobinuria, DIC", "Stop, new set with saline, recheck identity, fluids for urine 1-1.5 mL/kg/h, DAT, report"],
          ["Febrile non-haemolytic", "During or within 4 h", "Anti-leucocyte antibodies, stored cytokines", "Temperature rise of 1 degree C or more, no hypotension", "Slow or stop, paracetamol, exclude haemolysis and sepsis; leucodeplete"],
          ["Urticarial", "Minutes to hours", "IgE to donor plasma proteins", "Itch and hives only", "Pause, antihistamine, restart slowly if settles"],
          ["Anaphylaxis", "Minutes", "Anti-IgA in IgA deficiency", "Stridor, wheeze, angioedema, shock", "Stop, IM adrenaline 0.5 mg, oxygen, fluids; washed products later"],
          ["TRALI", "Within 6 h", "Donor anti-HLA or anti-HNA antibodies", "Hypoxaemia, bilateral infiltrates, normal JVP and BNP", "Stop, oxygen or ventilation, no diuretic"],
          ["TACO", "Within 6-12 h", "Volume overload", "Dyspnoea, hypertension, raised JVP and BNP", "Stop or slow, sit up, oxygen, furosemide"],
          ["Bacterial sepsis", "Minutes to hours", "Staphylococci (platelets), Yersinia (red cells)", "High fever, rigors, shock", "Stop, culture patient and pack, IV antibiotics"],
          ["Delayed haemolytic", "3-14 days", "Anamnestic IgG to Kidd, Rh, Kell, Duffy", "Falling Hb, jaundice, positive DAT", "Antibody screen, antibody card, antigen-negative blood"],
          ["Post-transfusion purpura", "5-12 days", "Anti-HPA-1a", "Severe thrombocytopenia, bleeding", "IVIG 1 g/kg for 2 days, avoid platelets"],
          ["TA-GVHD", "4-30 days", "Donor T cells engraft (relatives, immunosuppressed)", "Fever, rash, diarrhoea, pancytopenia - over 90% fatal", "Prevention only - irradiate 25 Gy"],
        ],
      },
      {
        heading: "ABO and Rh D types and compatible components",
        columns: ["Recipient group", "Antigen and antibody", "Compatible red cells", "Compatible plasma"],
        rows: [
          ["O", "No A or B; anti-A and anti-B", "O only", "O, A, B, AB"],
          ["A", "A; anti-B", "A, O", "A, AB"],
          ["B", "B; anti-A", "B, O", "B, AB"],
          ["AB", "A and B; no antibody", "AB, A, B, O (universal recipient)", "AB only"],
          ["Rh D negative", "No D; anti-D only after exposure", "D-negative (always in girls and women of childbearing age)", "Any Rh D"],
        ],
      },
    ],
    redFlags: [
      "Fever with rigors or hypotension during transfusion - stop at once and treat as acute haemolysis or bacterial sepsis, not a febrile reaction.",
      "Pain at the infusion site, loin, back or chest in the first 15 minutes - the earliest sign of ABO-incompatible haemolysis.",
      "Dark red or brown urine or oliguria during or after transfusion - haemoglobinuria; force diuresis and check DAT, creatinine and coagulation.",
      "New breathlessness or hypoxaemia within 6 hours - separate TRALI (no diuretic) from TACO (furosemide) and give oxygen now.",
      "Urticaria with wheeze, stridor, angioedema or hypotension - anaphylaxis; IM adrenaline before anything else.",
      "Unexplained oozing from wounds or cannula sites during transfusion, especially under anaesthesia - DIC from acute haemolysis.",
      "Fall in Hb with jaundice 3-14 days after transfusion - delayed haemolytic reaction; send DAT and antibody screen.",
      "Fever, rash, diarrhoea and pancytopenia 1-4 weeks after blood from a relative - suspect TA-GVHD.",
    ],
    pearls: [
      "Transfuse the patient, not the number: Hb 7 g/dL for most, 8 g/dL with cardiac disease or surgery, about 10 g/dL in acute MI - and one unit at a time.",
      "Almost every fatal reaction is a clerical error; the bedside identity check (patient states name and date of birth) prevents what no laboratory test can.",
      "Only normal saline in the line: Ringer's lactate clots the unit (calcium) and 5% dextrose haemolyses it.",
      "The major crossmatch (donor cells against recipient serum) matters; the minor crossmatch is obsolete in component therapy.",
      "IAT finds antibody in serum (screen, crossmatch, weak D); DAT finds antibody already on cells (haemolytic reaction, AIHA, HDN).",
      "TRALI versus TACO: both cause breathlessness within 6 hours, but TRALI has normal JVP and BNP and worsens with diuretics, TACO has raised JVP and BNP and improves with them.",
      "Platelets are stored warm (20-24 degrees C, 5 days), so they are the component that goes septic; red cells 2-6 degrees C for 35-42 days; FFP and cryo at minus 30 degrees C for 1 year.",
      "Always irradiate a directed donation from a relative - TA-GVHD is over 90% fatal and untreatable.",
      "Chronic iron deficiency anaemia in a stable patient is treated with iron, even at Hb 6-7 g/dL - blood buys weeks at the cost of alloimmunisation.",
      "India mandates five tests per unit (HIV, HBsAg, HCV, syphilis, malaria); NAT is not yet universal.",
    ],
    references: [
      "National Blood Transfusion Council and NACO. Standards for Blood Centres and Blood Transfusion Services. MoHFW, Government of India, 2022.",
      "Carson JL, et al. Red blood cell transfusion: 2023 AABB International Guidelines. JAMA 2023.",
      "British Society for Haematology. Guideline on the administration of blood components, 2017; SHOT Annual Report 2023.",
      "American College of Surgeons. ATLS Advanced Trauma Life Support, 11th edition, 2025.",
      "Haemovigilance Programme of India, Indian Pharmacopoeia Commission. Guidance document, 2023.",
      "Bailey and Love's Short Practice of Surgery, 28th edition, 2023 - transfusion chapter.",
    ],
  },
};

export default rewrites;
