import type { ClinicalCase, Subject, Topic } from "../lib/types";

const topics: Topic[] = [];

topics.push({
  id: "gastro-hepatology-acid-peptic-gerd",
  title: "Acid peptic disease, GERD and Helicobacter pylori eradication",
  oneLiner:
    "Acid peptic disease is mucosal injury of the stomach and duodenum caused by acid and pepsin acting on a mucosa weakened by Helicobacter pylori or NSAIDs, and in Indian practice it is managed by testing and treating H. pylori, withdrawing the offending drug, and giving a proton pump inhibitor before breakfast for a defined course rather than indefinitely.",
  frequency: "core",
  keywords: [
    "APD",
    "peptic ulcer disease",
    "PUD",
    "dyspepsia",
    "gastro-oesophageal reflux disease",
    "GERD",
    "GORD",
    "heartburn",
    "Helicobacter pylori",
    "H pylori",
    "urea breath test",
    "stool antigen",
    "omeprazole",
    "pantoprazole",
    "rabeprazole",
    "triple therapy",
    "bismuth quadruple therapy",
    "NSAID ulcer",
    "Barrett oesophagus",
    "alarm features",
    "endoscopy",
    "OGD",
  ],
  sections: [
    {
      heading: "Definitions and the words the examiner wants",
      points: [
        "**Dyspepsia** is epigastric pain or burning, postprandial fullness or early satiety lasting four weeks or more; it is a symptom complex, not a diagnosis, and only about one in four dyspeptic patients has an ulcer.",
        "**Acid peptic disease** covers gastritis, erosive duodenitis and frank gastric or duodenal ulcer - a mucosal break of 5 mm or more penetrating the muscularis mucosae.",
        "**GERD** is troublesome reflux of gastric contents causing symptoms (heartburn or regurgitation at least twice a week) or oesophageal mucosal injury; most Indian patients have **non-erosive reflux disease** with a normal endoscopy.",
        "**Functional dyspepsia** (Rome IV) is dyspepsia for 3 months with onset 6 months earlier, with a normal endoscopy and no H. pylori; it splits into epigastric pain syndrome and postprandial distress syndrome.",
        "Indian burden: community prevalence of dyspepsia is 10-30%, GERD symptoms are reported by about 8-20% of adults and are rising with obesity, and **H. pylori seroprevalence in India is 60-80%** by adulthood, one of the highest in the world.",
        "The exam point is that a very high background H. pylori prevalence with a very low gastric cancer incidence (the **Indian enigma**) means untargeted mass eradication is not policy - we test and treat, we do not screen and treat.",
      ],
    },
    {
      heading: "Clinical assessment and who needs endoscopy",
      points: [
        "History: site and timing of pain (duodenal ulcer classically wakes the patient at 2 am and is relieved by food; gastric ulcer pain is worsened by food and causes weight loss), heartburn and regurgitation, dysphagia, vomiting, melaena, weight loss and appetite.",
        "**Drug history is the single highest-yield question**: NSAIDs and analgesic combinations bought over the counter, low-dose aspirin, steroids, bisphosphonates, SSRIs, potassium chloride, and indigenous or ayurvedic pain preparations that often contain hidden NSAIDs or steroids.",
        "Ask about smoking, alcohol, chewing tobacco, late heavy dinners, spicy and fried food, tea and coffee load, and about stress and sleep, since all of these modify symptom burden even when they do not cause ulcers.",
        "Examination is usually normal; look specifically for pallor, epigastric mass, succussion splash (gastric outlet obstruction), hepatomegaly, Virchow node and a per-rectal examination for melaena.",
        "**Endoscope (OGD) at any age if there are alarm features**: dysphagia, odynophagia, unintentional weight loss, persistent vomiting, gastrointestinal bleeding or iron-deficiency anaemia, a palpable mass, or a family history of gastric cancer.",
        "**Age threshold in India:** because gastric cancer presents younger here than in the West, most Indian authorities scope new-onset dyspepsia from the age of 40-45 rather than the Western 55-60. In those under 40 with no alarm features, a test-and-treat or empirical PPI strategy is correct.",
        "Do not forget the great mimic: **epigastric pain in a diabetic or an elderly patient may be inferior wall myocardial infarction**, and an ECG costs less than an endoscopy.",
      ],
    },
    {
      heading: "Helicobacter pylori: testing and eradication",
      points: [
        "Indications to test: proven peptic ulcer (current or past), gastric MALT lymphoma, after resection of early gastric cancer, first-degree relative of a gastric cancer patient, uninvestigated dyspepsia under 40 without alarm features, and unexplained iron-deficiency anaemia or immune thrombocytopenia.",
        "**Non-invasive tests:** urea breath test and stool antigen test are the tests of choice for both diagnosis and confirmation of cure. Serology (IgG) stays positive for years after cure and **cannot be used to confirm eradication** or to prove active infection in a high-prevalence country.",
        "**Stop the PPI for 2 weeks and antibiotics or bismuth for 4 weeks** before a urea breath test or stool antigen test, or the result will be falsely negative. Invasive testing at endoscopy uses the rapid urease test, histology and culture.",
        "First-line in India where clarithromycin resistance is high (often above 15-20%): **bismuth quadruple therapy for 14 days** - bismuth subcitrate 120 mg QID, tetracycline 500 mg QID, metronidazole 400 mg TDS and a standard-dose PPI BD.",
        "Where bismuth is not available, **concomitant (non-bismuth quadruple) therapy for 14 days** - PPI BD plus amoxicillin 1 g BD plus clarithromycin 500 mg BD plus metronidazole/tinidazole 500 mg BD - outperforms the old 7-day triple regimen, which now cures under 70% and should not be prescribed.",
        "**Confirm cure in every treated patient** by urea breath test or stool antigen at least 4 weeks after finishing antibiotics and 2 weeks off the PPI. Second-line uses levofloxacin-based therapy (PPI + amoxicillin 1 g BD + levofloxacin 500 mg OD for 14 days) if bismuth quadruple was used first.",
        "Counsel on the practical points that decide success: **adherence to a 14-day, four-drug, high-pill-count regimen is the main determinant of cure**, metallic taste and black stools from bismuth are expected, and alcohol must be avoided with metronidazole.",
      ],
    },
    {
      heading: "GERD: management from lifestyle to referral",
      points: [
        "Diagnosis is clinical when typical heartburn and regurgitation dominate; a **PPI trial for 4-8 weeks** is both treatment and a diagnostic test in the patient without alarm features.",
        "Lifestyle measures with real effect: weight loss (the single most effective measure - each unit of BMI reduction improves symptoms), stopping smoking, avoiding a heavy meal within 3 hours of lying down, and **raising the head end of the bed by 6-8 inches on blocks** rather than piling up pillows.",
        "Diet advice should be individualised rather than blanket prohibition, but the usual triggers are large fatty and fried meals, chilli, chocolate, peppermint, citrus, carbonated drinks, tea, coffee and alcohol.",
        "**Standard-dose PPI once daily 30-60 minutes before breakfast for 8 weeks** is first line; taking it with or after food is the commonest reason for apparent PPI failure. Step to twice daily (second dose before dinner) only for proven erosive disease or partial response.",
        "After 8 weeks step down: halve the dose, move to on-demand dosing, or stop. Alginate-antacid preparations are useful for breakthrough and in pregnancy, and **H2 blockers (ranitidine has been withdrawn worldwide over NDMA; use famotidine 20-40 mg at night)** help nocturnal symptoms.",
        "Refer for endoscopy if there are alarm features, if symptoms persist after 8 weeks of optimal PPI, if relapse occurs immediately on stopping, or if long-term therapy is being contemplated in a patient over 50 with chronic reflux (to look for **Barrett oesophagus**).",
        "Extra-oesophageal reflux (chronic cough, hoarseness, non-cardiac chest pain, dental erosion, asthma that is worse at night) needs a longer trial of twice-daily PPI and should never be diagnosed until cardiac and respiratory causes have been excluded.",
      ],
    },
    {
      heading: "Drug therapy, NSAID injury and prophylaxis",
      points: [
        "**PPIs** (omeprazole 20 mg, pantoprazole 40 mg, rabeprazole 20 mg, esomeprazole 40 mg) irreversibly block the H+/K+ ATPase; full effect takes 3-5 days, so a patient who is no better on day two has not failed treatment.",
        "**Duodenal ulcer: PPI once daily for 4 weeks. Gastric ulcer: PPI once daily for 8 weeks, with a repeat endoscopy and biopsy at 8-12 weeks to prove healing and exclude malignancy** - this last point is a common exam answer.",
        "Withdraw the culprit NSAID. If an NSAID cannot be stopped, use the lowest dose of the least gastrotoxic agent and add a PPI; paracetamol and topical NSAIDs are the safer alternatives in osteoarthritis.",
        "**Give PPI co-prescription (gastroprotection) with an NSAID when any of these is present:** age 65 or more, past peptic ulcer or ulcer bleed, concurrent aspirin, anticoagulant, steroid or SSRI, or a high NSAID dose. Aspirin plus an NSAID is a high-risk combination doctors create themselves.",
        "Long-term PPI harms are real but modest and are examined: hypomagnesaemia, vitamin B12 deficiency, hypergastrinaemia, an increased risk of Clostridioides difficile and other enteric infections, community-acquired pneumonia, fundic gland polyps, and an association with fracture and chronic kidney disease. **Review the indication for every patient on a PPI beyond 8 weeks.**",
        "Antacids and alginates give minute-to-minute relief and are useful for breakthrough symptoms; prokinetics (domperidone 10 mg TDS, itopride 50 mg TDS) help when bloating and early satiety dominate but **metoclopramide should be avoided long term because of tardive dyskinesia**.",
        "Sucralfate 1 g QID on an empty stomach is a useful mucosal coating agent in pregnancy and in NSAID-related injury when acid suppression alone has not worked.",
      ],
    },
    {
      heading: "Complications and their recognition",
      points: [
        "**Bleeding** is the commonest complication - haematemesis, coffee-ground vomit or melaena. Any dyspeptic patient with melaena needs admission, resuscitation, an intravenous PPI infusion and urgent endoscopy, not a change of oral tablet.",
        "**Perforation** presents as sudden severe epigastric pain becoming generalised, a board-like rigid abdomen, absent liver dullness and free gas under the diaphragm on an erect chest radiograph; it is a surgical emergency.",
        "**Gastric outlet obstruction** from a chronic scarred pyloric ulcer causes projectile non-bilious vomiting of undigested food eaten hours earlier, visible gastric peristalsis, a succussion splash and hypochloraemic hypokalaemic metabolic alkalosis with paradoxical aciduria.",
        "**Malignancy** must be excluded in every non-healing gastric ulcer; benign-looking ulcers can be malignant, which is why gastric ulcers are re-scoped and biopsied from four quadrants of the rim.",
        "**Refractory disease** should prompt the questions: is he taking the PPI before food, is he still taking NSAIDs, was H. pylori actually eradicated and confirmed, is this functional dyspepsia, and rarely is this Zollinger-Ellison syndrome (multiple or post-bulbar ulcers, diarrhoea, high fasting gastrin).",
        "Iron deficiency anaemia in a man of any age, or in a postmenopausal woman, with dyspepsia is a bidirectional endoscopy indication - the upper and lower tracts are both looked at.",
      ],
    },
  ],
  tables: [
    {
      heading: "Helicobacter pylori eradication regimens used in India",
      columns: ["Regimen", "Drugs and doses", "Duration", "When to use"],
      rows: [
        [
          "Bismuth quadruple (first line)",
          "PPI standard dose BD + bismuth subcitrate 120 mg QID + tetracycline 500 mg QID + metronidazole 400 mg TDS",
          "14 days",
          "Preferred first line given high Indian clarithromycin and metronidazole resistance",
        ],
        [
          "Concomitant non-bismuth quadruple",
          "PPI BD + amoxicillin 1 g BD + clarithromycin 500 mg BD + tinidazole 500 mg BD",
          "14 days",
          "When bismuth is unavailable and there has been no prior macrolide exposure",
        ],
        [
          "Levofloxacin triple (second line)",
          "PPI BD + amoxicillin 1 g BD + levofloxacin 500 mg OD",
          "14 days",
          "Rescue after failed bismuth quadruple; avoid if prior fluoroquinolone use",
        ],
        [
          "Clarithromycin triple (legacy)",
          "PPI BD + amoxicillin 1 g BD + clarithromycin 500 mg BD",
          "14 days",
          "Only where local clarithromycin resistance is proven to be under 15 percent; cure rates now poor",
        ],
      ],
    },
    {
      heading: "Acid suppression: dose, timing and course length",
      columns: ["Drug", "Standard dose", "Timing", "Usual course"],
      rows: [
        ["Omeprazole", "20 mg PO OD", "30-60 min before breakfast", "4 weeks for duodenal ulcer, 8 weeks for gastric ulcer or erosive GERD"],
        ["Pantoprazole", "40 mg PO OD", "30-60 min before breakfast", "Same; 40 mg IV BD or 8 mg/h infusion after an ulcer bleed"],
        ["Rabeprazole", "20 mg PO OD", "30-60 min before breakfast", "Same; least dependent on CYP2C19 genotype"],
        ["Esomeprazole", "40 mg PO OD", "30-60 min before breakfast", "Erosive oesophagitis and PPI-refractory reflux"],
        ["Famotidine", "20-40 mg PO at night", "Bedtime", "Nocturnal breakthrough; add-on to a PPI, or use in pregnancy"],
        ["Sucralfate", "1 g PO QID", "1 hour before meals and at bedtime", "2-4 weeks; safe in pregnancy, binds other drugs so space by 2 hours"],
      ],
    },
    {
      heading: "Duodenal versus gastric ulcer",
      columns: ["Feature", "Duodenal ulcer", "Gastric ulcer"],
      rows: [
        ["Typical age", "25-50 years", "Over 40 years"],
        ["Pain and food", "Relieved by food, wakes the patient at night (hunger pain)", "Worsened by food, so the patient eats less"],
        ["Weight", "Stable or increased", "Loss is common"],
        ["H. pylori association", "About 90 percent", "About 70 percent"],
        ["Acid output", "Normal or high", "Normal or low"],
        ["Malignant potential", "Essentially none", "Real - always biopsy and re-scope at 8-12 weeks"],
      ],
    },
  ],
  redFlags: [
    "Haematemesis, coffee-ground vomiting or melaena in a dyspeptic patient - admit, resuscitate and arrange urgent endoscopy.",
    "Progressive dysphagia or odynophagia - oesophageal carcinoma or a peptic stricture until endoscopy proves otherwise.",
    "Unintentional weight loss of more than 5 percent, anorexia or a palpable epigastric mass - urgent endoscopy for gastric malignancy.",
    "Sudden severe epigastric pain with board-like rigidity and absent liver dullness - perforated peptic ulcer, refer for immediate surgery.",
    "Projectile vomiting of undigested food with a succussion splash - gastric outlet obstruction, admit for decompression and correction of alkalosis.",
    "New dyspepsia over the age of 40-45, or iron-deficiency anaemia at any age with dyspepsia - endoscopy rather than an empirical PPI.",
    "Epigastric pain with sweating, breathlessness or radiation to the jaw in a diabetic or an elderly patient - do an ECG before treating it as acidity.",
  ],
  pearls: [
    "A PPI works only if it is taken 30-60 minutes before food; the commonest cause of PPI failure in the clinic is a patient taking it after dinner.",
    "H. pylori serology cannot confirm eradication and cannot prove active infection in India, where most adults are seropositive - use the urea breath test or stool antigen.",
    "Stop the PPI for two weeks and antibiotics for four weeks before a urea breath test, or the test will read falsely negative.",
    "Every gastric ulcer is biopsied and re-scoped at 8-12 weeks; every duodenal ulcer is not.",
    "Seven-day triple therapy is obsolete in India - use 14 days of bismuth quadruple therapy.",
    "Ask about over-the-counter painkillers and ayurvedic pain powders by name; patients do not consider them medicines and will not volunteer them.",
    "Ranitidine has been withdrawn worldwide over NDMA contamination; the H2 blocker to write is famotidine.",
    "Weight loss and raising the head end of the bed on blocks beat any drug for nocturnal reflux.",
    "Review the indication of every PPI at 8 weeks; indefinite PPI is a prescribing failure, not a treatment plan.",
  ],
  theory: [
    {
      id: "gastro-hepatology-acid-peptic-gerd-t1",
      paper: "II",
      kind: "long",
      marks: 10,
      minutes: 20,
      frequency: "core",
      question:
        "A 38-year-old man attends your clinic with epigastric burning for three months, worse at night and relieved by food. Discuss your approach to evaluation and management, including the role of Helicobacter pylori.",
      openingLines: [
        "Dyspepsia is epigastric pain or burning, postprandial fullness or early satiety of at least four weeks duration; the history of night pain relieved by food is classical of duodenal ulcer, of which about 90 percent are Helicobacter pylori related.",
        "In a 38-year-old with no alarm features, the family physician's task is to exclude red flags clinically, adopt a test-and-treat strategy for H. pylori, remove ulcerogenic drugs, and give a defined course of acid suppression with a planned review rather than open-ended therapy.",
      ],
      answer: [
        {
          heading: "1. History and the alarm features that change the plan",
          points: [
            "Characterise the pain: site, periodicity, relation to food, night waking, relief by antacids; ask about heartburn, regurgitation, bloating and early satiety to separate ulcer-like from reflux-like and dysmotility-like dyspepsia.",
            "Take a full drug history including over-the-counter NSAIDs, aspirin, steroids, bisphosphonates, SSRIs and ayurvedic or herbal pain preparations, which often contain undeclared NSAIDs or steroids.",
            "Ask about smoking, tobacco chewing, alcohol, meal timing, and psychosocial stress; establish whether there is a family history of gastric cancer.",
            "Elicit alarm features - dysphagia, odynophagia, vomiting, weight loss, bleeding, anaemia, mass - because any one of them converts the plan from empirical treatment to prompt endoscopy irrespective of age.",
          ],
        },
        {
          heading: "2. Examination and first-line investigations",
          points: [
            "Look for pallor, epigastric tenderness or mass, succussion splash, hepatomegaly and Virchow node; do a per-rectal examination for melaena.",
            "Do an ECG if the pain could be cardiac, particularly in a diabetic, hypertensive or older patient.",
            "Haemoglobin and stool occult blood are the two cheap tests that most often change the plan; iron-deficiency anaemia mandates endoscopy.",
            "Test for H. pylori by urea breath test or stool antigen, having stopped any PPI for two weeks and antibiotics for four weeks; serology is not acceptable in the Indian setting.",
            "Endoscopy is indicated here only if alarm features appear, if he is over 40-45 with new-onset symptoms, or if he fails an adequate course of treatment.",
          ],
        },
        {
          heading: "3. Helicobacter pylori eradication",
          points: [
            "First-line regimen in India is 14-day bismuth quadruple therapy: standard-dose PPI twice daily, bismuth subcitrate 120 mg four times daily, tetracycline 500 mg four times daily and metronidazole 400 mg three times daily.",
            "Where bismuth is unavailable, 14-day concomitant therapy with PPI, amoxicillin 1 g, clarithromycin 500 mg and tinidazole 500 mg, all twice daily.",
            "Counsel about adherence, metallic taste, black stool with bismuth, and absolute avoidance of alcohol with metronidazole; adherence is the main determinant of cure.",
            "Confirm eradication with a urea breath test or stool antigen at least four weeks after antibiotics and two weeks off the PPI; if it fails, use levofloxacin-based rescue therapy for 14 days.",
          ],
        },
        {
          heading: "4. Acid suppression and non-drug measures",
          points: [
            "Standard-dose PPI 30-60 minutes before breakfast; four weeks for a duodenal ulcer, eight weeks for a gastric ulcer or erosive oesophagitis.",
            "Withdraw NSAIDs; if analgesia is essential, use paracetamol or a topical NSAID, and if an oral NSAID is unavoidable, co-prescribe a PPI.",
            "Advise stopping smoking and tobacco chewing, moderating alcohol, avoiding large late meals, and elevating the head end of the bed if there is reflux.",
            "Reassure that dyspepsia is common and that most patients do well; address anxiety, which drives both symptoms and repeat consultation.",
          ],
        },
        {
          heading: "5. Follow-up, step-down and referral",
          points: [
            "Review at four weeks: if asymptomatic, step down to on-demand or stop; if partially better, complete eight weeks and reassess adherence and timing.",
            "Refer for endoscopy if symptoms persist beyond eight weeks of correctly taken therapy, if they relapse immediately on stopping, or if any alarm feature develops.",
            "A gastric ulcer found at endoscopy is biopsied and re-scoped at 8-12 weeks to prove healing and exclude malignancy.",
            "Document the indication for any PPI continued beyond eight weeks and review it at every visit, given the recognised long-term risks of hypomagnesaemia, B12 deficiency, enteric infection and fracture.",
          ],
        },
      ],
      mustDraw: [
        "A flow chart: dyspepsia - alarm features or age over 40-45 leading to endoscopy, otherwise test-and-treat for H. pylori, then PPI trial, then review at 4-8 weeks.",
        "A table of the 14-day bismuth quadruple regimen with drug, dose and frequency.",
      ],
      markSplit: [
        { part: "Definition, differential and alarm features", marks: 2 },
        { part: "History, examination and investigations", marks: 2 },
        { part: "H. pylori testing, regimen and confirmation of cure", marks: 3 },
        { part: "Acid suppression, non-drug measures and NSAID withdrawal", marks: 2 },
        { part: "Follow-up and referral criteria", marks: 1 },
      ],
      keywords: ["dyspepsia", "duodenal ulcer", "test and treat", "bismuth quadruple therapy", "urea breath test", "alarm features"],
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-t2",
      paper: "II",
      kind: "short-note",
      marks: 5,
      minutes: 10,
      frequency: "common",
      question: "Write short notes on gastro-oesophageal reflux disease: clinical features, complications and management.",
      openingLines: [
        "GERD is troublesome reflux of gastric contents into the oesophagus causing symptoms at least twice a week or mucosal injury, and it affects roughly 8-20 percent of Indian adults with prevalence rising alongside obesity.",
        "The majority have non-erosive reflux disease with a normal endoscopy, so the diagnosis is clinical and the therapeutic trial of a proton pump inhibitor doubles as a diagnostic test.",
      ],
      answer: [
        {
          heading: "Clinical features",
          points: [
            "Typical: heartburn (retrosternal burning rising towards the throat) and regurgitation of acid or food, worse lying down, bending forward and after large or fatty meals.",
            "Atypical and extra-oesophageal: non-cardiac chest pain, chronic cough, nocturnal asthma, hoarseness, globus, laryngitis and dental erosion.",
            "Predisposing factors: obesity and central adiposity, hiatus hernia, pregnancy, delayed gastric emptying, smoking, alcohol, and drugs that relax the lower oesophageal sphincter such as calcium channel blockers, nitrates and theophylline.",
          ],
        },
        {
          heading: "Complications",
          points: [
            "Erosive oesophagitis, graded by the Los Angeles classification A to D.",
            "Peptic stricture causing progressive dysphagia to solids, and oesophageal ulcer with bleeding or iron-deficiency anaemia.",
            "**Barrett oesophagus** - intestinal metaplasia of the lower oesophagus, a premalignant lesion for oesophageal adenocarcinoma requiring endoscopic surveillance.",
            "Aspiration pneumonia and worsening of asthma, particularly nocturnal.",
          ],
        },
        {
          heading: "Management",
          points: [
            "Lifestyle: weight reduction, stop smoking and alcohol, no meal within 3 hours of lying down, head end of the bed raised 6-8 inches on blocks, avoidance of identified dietary triggers.",
            "Standard-dose PPI once daily 30-60 minutes before breakfast for 8 weeks; twice-daily dosing for erosive disease or partial response; alginate-antacid or famotidine for breakthrough and nocturnal symptoms.",
            "Step down after 8 weeks to the lowest effective or on-demand dose; long-term therapy needs a documented indication such as erosive oesophagitis or Barrett oesophagus.",
            "Endoscopy for alarm features, failure of 8 weeks of optimal therapy, immediate relapse, or long-standing reflux in a patient over 50; anti-reflux surgery (laparoscopic fundoplication) for proven acid reflux with a large hiatus hernia or drug intolerance.",
          ],
        },
      ],
      mustDraw: ["A table of the Los Angeles grades A to D of erosive oesophagitis with the mucosal break length and continuity for each."],
      markSplit: [
        { part: "Definition and clinical features", marks: 1.5 },
        { part: "Complications including Barrett oesophagus", marks: 1.5 },
        { part: "Lifestyle and drug management with dose and timing", marks: 1.5 },
        { part: "Indications for endoscopy and surgery", marks: 0.5 },
      ],
      keywords: ["GERD", "heartburn", "Barrett oesophagus", "proton pump inhibitor", "Los Angeles classification"],
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-t3",
      paper: "II",
      kind: "enumerate",
      marks: 5,
      minutes: 8,
      frequency: "common",
      question: "Enumerate the alarm features in dyspepsia and the complications of peptic ulcer disease, with the immediate action for each.",
      openingLines: [
        "Alarm features are the clinical findings that make endoscopy mandatory regardless of age, because they raise the probability of malignancy, bleeding or obstruction.",
        "Peptic ulcer complications are bleeding, perforation, gastric outlet obstruction and malignant transformation of a gastric ulcer, and each has a distinct presentation and an immediate action.",
      ],
      answer: [
        {
          heading: "Alarm features in dyspepsia",
          points: [
            "Dysphagia or odynophagia - urgent endoscopy for carcinoma or stricture.",
            "Unintentional weight loss or anorexia - urgent endoscopy for gastric malignancy.",
            "Persistent vomiting - endoscopy for obstruction or malignancy.",
            "Gastrointestinal bleeding, melaena or iron-deficiency anaemia - admit if actively bleeding; bidirectional endoscopy otherwise.",
            "Palpable abdominal mass or lymphadenopathy, jaundice, or a family history of gastric cancer in a first-degree relative.",
            "New-onset dyspepsia over the age of 40-45 in Indian practice, or failure of an adequate 8-week therapeutic trial.",
          ],
        },
        {
          heading: "Complications and the immediate action",
          points: [
            "**Bleeding** (haematemesis, melaena, shock) - two wide-bore cannulae, fluids, group and cross-match, intravenous PPI, and endoscopy within 24 hours; use the Glasgow-Blatchford score to decide who can be managed as an outpatient.",
            "**Perforation** (sudden severe pain, board-like rigidity, absent liver dullness, free gas under the diaphragm) - nil by mouth, nasogastric tube, fluids, antibiotics, analgesia and immediate surgical referral.",
            "**Gastric outlet obstruction** (projectile vomiting of undigested food, succussion splash, hypochloraemic hypokalaemic alkalosis) - nasogastric decompression, correction of fluid and electrolytes with normal saline and potassium, then endoscopy or surgery.",
            "**Malignancy in a non-healing gastric ulcer** - repeat endoscopy with multiple biopsies from the ulcer rim at 8-12 weeks and referral to surgical oncology if positive.",
            "**Penetration into the pancreas** - constant boring back pain unrelieved by antacids with a raised serum amylase; refer for imaging.",
          ],
        },
      ],
      markSplit: [
        { part: "Alarm features listed completely", marks: 2 },
        { part: "Complications with recognition", marks: 2 },
        { part: "Immediate action for each complication", marks: 1 },
      ],
      keywords: ["alarm features", "perforation", "gastric outlet obstruction", "Glasgow-Blatchford", "melaena"],
    },
  ],
  mcqs: [
    {
      id: "gastro-hepatology-acid-peptic-gerd-q1",
      stem: "A 34-year-old man with three months of epigastric burning, no alarm features, is being tested for Helicobacter pylori. He has been taking pantoprazole 40 mg daily bought over the counter for the last 10 days. What is the correct next step before sending a urea breath test?",
      options: [
        "Send the test now, since a PPI does not affect the urea breath test",
        "Stop the pantoprazole for 2 weeks and then test",
        "Send H. pylori IgG serology instead, which is unaffected by the PPI",
        "Double the pantoprazole dose and test after one week",
        "Start empirical eradication therapy without testing",
      ],
      answer: 1,
      explanation:
        "Proton pump inhibitors suppress bacterial urease activity and bacterial density, causing a falsely negative urea breath test or stool antigen, so the PPI must be withheld for two weeks (and antibiotics or bismuth for four weeks) before testing. Serology stays positive for years after cure and, in India where adult seroprevalence is 60-80 percent, a positive IgG cannot distinguish active from past infection, so it is not an acceptable substitute. Empirical eradication without a positive test exposes the patient to a 14-day four-drug regimen he may not need and fuels resistance, and increasing the PPI dose only worsens the false-negative rate.",
      difficulty: "moderate",
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-q2",
      stem: "A 45-year-old woman has a proven duodenal ulcer with a positive rapid urease test at endoscopy. She has no drug allergy and has never taken a macrolide. Which regimen is the most appropriate first line in current Indian practice?",
      options: [
        "Pantoprazole 40 mg BD, amoxicillin 1 g BD and clarithromycin 500 mg BD for 7 days",
        "Pantoprazole 40 mg BD, bismuth subcitrate 120 mg QID, tetracycline 500 mg QID and metronidazole 400 mg TDS for 14 days",
        "Pantoprazole 40 mg OD alone for 8 weeks",
        "Pantoprazole 40 mg BD and levofloxacin 500 mg OD for 7 days",
        "Pantoprazole 40 mg BD and amoxicillin 1 g TDS for 14 days",
      ],
      answer: 1,
      explanation:
        "Fourteen-day bismuth quadruple therapy is the recommended first-line regimen in India because clarithromycin and metronidazole resistance rates are high and it retains cure rates above 90 percent even against metronidazole-resistant strains. The 7-day clarithromycin triple regimen now achieves under 70 percent eradication and is no longer acceptable, and shortening any regimen below 14 days lowers cure further. A PPI alone heals the ulcer but leaves the infection and the relapse risk untouched, levofloxacin-based therapy is reserved as rescue, and high-dose dual amoxicillin therapy is not a standard Indian first-line option.",
      difficulty: "moderate",
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-q3",
      stem: "A 58-year-old man has had heartburn for six years, controlled on intermittent antacids. Over the last two months he has had difficulty swallowing solids and has lost 4 kg. What is the most appropriate next step?",
      options: [
        "Start omeprazole 20 mg daily and review in 8 weeks",
        "Refer for upper gastrointestinal endoscopy",
        "Order a barium swallow and treat empirically meanwhile",
        "Test and treat for Helicobacter pylori",
        "Advise weight loss and raising the head end of the bed, and review in 3 months",
      ],
      answer: 1,
      explanation:
        "Progressive dysphagia to solids with weight loss on a background of long-standing reflux is the classic presentation of oesophageal adenocarcinoma arising in Barrett oesophagus, or of a peptic stricture, and endoscopy with biopsy is mandatory and urgent. An empirical PPI or lifestyle advice delays the diagnosis of a curable early cancer and may partially mask symptoms. Barium swallow is less sensitive, cannot obtain tissue, and adds a step before the endoscopy that will be needed anyway, and H. pylori testing addresses neither dysphagia nor weight loss.",
      difficulty: "easy",
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-q4",
      stem: "A 70-year-old man with osteoarthritis takes diclofenac 50 mg twice daily and aspirin 75 mg daily after a stent. He has no gastrointestinal symptoms. Which is the most appropriate action?",
      options: [
        "No action is needed while he is asymptomatic",
        "Add a proton pump inhibitor and try to replace diclofenac with paracetamol or a topical NSAID",
        "Stop the aspirin and continue diclofenac",
        "Add sucralfate 1 g four times daily and continue both drugs",
        "Add misoprostol 800 microgram daily and continue both drugs unchanged",
      ],
      answer: 1,
      explanation:
        "He has at least three risk factors for NSAID ulcer complications - age over 65, an oral NSAID, and concurrent low-dose aspirin - and most such ulcers bleed without any preceding dyspepsia, so waiting for symptoms is unsafe. The right answer combines gastroprotection with removing the risk: a PPI plus substitution of the systemic NSAID with paracetamol or a topical preparation. Stopping the aspirin after a coronary stent risks stent thrombosis and is the wrong drug to sacrifice. Sucralfate does not prevent NSAID ulcer complications, and misoprostol, although effective, causes diarrhoea and cramps that make adherence poor and is second choice to a PPI.",
      difficulty: "moderate",
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-q5",
      stem: "A 40-year-old man with a healed duodenal ulcer completed 14 days of bismuth quadruple therapy, finishing 10 days ago. He is asymptomatic. He is still taking pantoprazole. When and how should eradication be confirmed?",
      options: [
        "H. pylori IgG serology now",
        "Urea breath test now, while continuing pantoprazole",
        "Stool antigen test at least 4 weeks after finishing antibiotics and 2 weeks after stopping the PPI",
        "Repeat endoscopy with rapid urease test at 6 months",
        "No confirmation is needed if he is asymptomatic",
      ],
      answer: 2,
      explanation:
        "Cure must be confirmed after every eradication course, because up to a fifth of patients fail and remain at risk of ulcer relapse and bleeding, and confirmation requires a non-invasive test done at least four weeks after the antibiotics and two weeks off the PPI to avoid a false negative. Serology remains positive for years after successful eradication and can never document cure. Testing now, on a PPI and only 10 days after antibiotics, gives an unreliable negative. Repeat endoscopy is invasive and unnecessary for a healed duodenal ulcer, and symptom resolution does not prove eradication.",
      difficulty: "moderate",
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-q6",
      stem: "A 52-year-old man presents with vomiting of large volumes of undigested food eaten the previous evening, for two weeks. He has lost weight and has a history of chronic ulcer pain. Examination shows a succussion splash. Which electrolyte and acid-base picture is expected?",
      options: [
        "Hyperchloraemic metabolic acidosis with hyperkalaemia",
        "Hypochloraemic hypokalaemic metabolic alkalosis with paradoxical aciduria",
        "Normal anion gap metabolic acidosis with hypernatraemia",
        "Respiratory alkalosis with hypocalcaemia",
        "High anion gap metabolic acidosis with hyperlactataemia",
      ],
      answer: 1,
      explanation:
        "Gastric outlet obstruction causes prolonged loss of hydrogen and chloride ions in vomitus, producing hypochloraemic metabolic alkalosis; secondary hyperaldosteronism from volume depletion drives renal potassium loss and hydrogen excretion, so the urine becomes acidic despite the systemic alkalosis - the classic paradoxical aciduria. Acidosis of any type would be expected with diarrhoeal or renal bicarbonate loss, not with protracted vomiting of gastric contents. Respiratory alkalosis is a ventilatory disturbance and does not fit, and lactic acidosis would require tissue hypoperfusion.",
      difficulty: "hard",
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-q7",
      stem: "A 29-year-old woman with typical heartburn has been taking rabeprazole 20 mg after dinner for four weeks with little benefit. She has no alarm features. What is the single most useful next step?",
      options: [
        "Change to esomeprazole 40 mg after dinner",
        "Instruct her to take the rabeprazole 30-60 minutes before breakfast",
        "Refer for 24-hour oesophageal pH monitoring",
        "Add domperidone 10 mg three times daily",
        "Refer for laparoscopic fundoplication",
      ],
      answer: 1,
      explanation:
        "Proton pump inhibitors only inhibit proton pumps that are actively secreting, so the drug must be in the blood when the meal-stimulated pumps switch on - taking it 30-60 minutes before a meal, ideally breakfast. Incorrect timing is by far the commonest cause of apparent PPI failure and must be corrected before the regimen is escalated. Switching molecules while keeping the wrong timing repeats the same error, a prokinetic addresses bloating rather than acid, and pH monitoring or surgery are for genuinely refractory disease after correctly taken twice-daily therapy has failed.",
      difficulty: "easy",
    },
  ],
  cards: [
    {
      id: "gastro-hepatology-acid-peptic-gerd-c1",
      front: "First-line Helicobacter pylori regimen in India, with duration.",
      back: "Bismuth quadruple therapy for 14 days: PPI BD + bismuth subcitrate 120 mg QID + tetracycline 500 mg QID + metronidazole 400 mg TDS.",
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-c2",
      front: "How long must a PPI and antibiotics be stopped before a urea breath test?",
      back: "PPI for 2 weeks, antibiotics and bismuth for 4 weeks - otherwise the test is falsely negative.",
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-c3",
      front: "Why is H. pylori serology useless in India?",
      back: "Adult seroprevalence is 60-80 percent and IgG stays positive for years after cure, so it proves neither active infection nor eradication.",
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-c4",
      front: "PPI course length for duodenal versus gastric ulcer.",
      back: "Duodenal ulcer 4 weeks; gastric ulcer 8 weeks plus repeat endoscopy and biopsy at 8-12 weeks to prove healing and exclude cancer.",
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-c5",
      front: "List the alarm features in dyspepsia.",
      back: "Dysphagia, odynophagia, weight loss, persistent vomiting, GI bleeding or iron-deficiency anaemia, abdominal mass, family history of gastric cancer, and new onset over age 40-45 in India.",
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-c6",
      front: "When must a PPI be co-prescribed with an NSAID?",
      back: "Age 65 or more, past peptic ulcer or bleed, concurrent aspirin, anticoagulant, steroid or SSRI, or high-dose NSAID therapy.",
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-c7",
      front: "Triad of gastric outlet obstruction.",
      back: "Projectile non-bilious vomiting of undigested food, visible gastric peristalsis with a succussion splash, and hypochloraemic hypokalaemic alkalosis with paradoxical aciduria.",
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-c8",
      front: "Correct timing of a proton pump inhibitor.",
      back: "30-60 minutes before breakfast; the drug must be present when meal-stimulated pumps are activated. Wrong timing is the commonest cause of PPI failure.",
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-c9",
      front: "Signs of a perforated peptic ulcer.",
      back: "Sudden severe epigastric pain becoming generalised, board-like rigidity, absent liver dullness, and free gas under the diaphragm on an erect chest film.",
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-c10",
      front: "What is Barrett oesophagus and why does it matter?",
      back: "Intestinal metaplasia of the lower oesophagus from chronic reflux; it is premalignant for oesophageal adenocarcinoma and needs endoscopic surveillance.",
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-c11",
      front: "Long-term risks of proton pump inhibitor therapy.",
      back: "Hypomagnesaemia, vitamin B12 deficiency, enteric infection including C. difficile, community-acquired pneumonia, fundic gland polyps, and associations with fracture and CKD.",
    },
    {
      id: "gastro-hepatology-acid-peptic-gerd-c12",
      front: "Which H2 blocker should now be prescribed, and why not ranitidine?",
      back: "Famotidine 20-40 mg at night. Ranitidine was withdrawn worldwide because of NDMA (nitrosamine) contamination.",
    },
  ],
  references: [
    "Indian Society of Gastroenterology consensus on Helicobacter pylori infection, Indian Journal of Gastroenterology, 2021",
    "Maastricht VI / Florence Consensus Report on the management of Helicobacter pylori infection, Gut, 2022",
    "American College of Gastroenterology Clinical Guideline: Diagnosis and Management of GERD, 2022",
    "ACG and Canadian Association of Gastroenterology Clinical Guideline: Management of Dyspepsia, 2017",
    "API Textbook of Medicine, 11th edition, 2019 - diseases of the stomach and duodenum",
    "Harrison's Principles of Internal Medicine, 21st edition, 2022 - peptic ulcer disease and GERD",
  ],
});

topics.push({
  id: "gastro-hepatology-acute-diarrhoea",
  title: "Acute diarrhoea and dysentery: ORS, zinc and the water-borne outbreak",
  oneLiner:
    "Acute diarrhoea is the passage of three or more loose or watery stools in 24 hours for less than 14 days, and its management rests on assessing dehydration clinically, replacing losses with low-osmolarity ORS, giving zinc for 14 days in every child under five, continuing feeding, and reserving antibiotics for dysentery, cholera and severe systemic illness.",
  frequency: "core",
  keywords: [
    "acute gastroenteritis",
    "diarrhoea",
    "dysentery",
    "ORS",
    "oral rehydration solution",
    "low osmolarity ORS",
    "zinc",
    "cholera",
    "Vibrio cholerae",
    "Shigella",
    "amoebic dysentery",
    "Entamoeba histolytica",
    "giardiasis",
    "rotavirus",
    "typhoid",
    "IMNCI",
    "Plan A Plan B Plan C",
    "Ringer lactate",
    "traveller's diarrhoea",
    "food poisoning",
    "ORS-Zinc corner",
  ],
  sections: [
    {
      heading: "Definitions, burden and the Indian programme",
      points: [
        "**Acute diarrhoea** is three or more loose or watery stools in 24 hours (or any increase from the individual's normal) lasting under 14 days; **persistent diarrhoea** lasts 14 days or more; **chronic diarrhoea** lasts 4 weeks or more.",
        "**Dysentery** is diarrhoea with visible blood in the stool, usually with fever, tenesmus and small-volume frequent stools - it means colonic invasion and it changes the antibiotic decision.",
        "Diarrhoeal disease remains among the top causes of under-five death in India; the **Intensified Diarrhoea Control Fortnight (IDCF)** each year distributes ORS and zinc house-to-house and sets up ORS-Zinc corners at every facility.",
        "Rotavirus caused about 40 percent of severe childhood diarrhoea hospitalisations before **Rotavirus vaccine was introduced into the Universal Immunisation Programme in 2016 and scaled nationally by 2019**, given at 6, 10 and 14 weeks.",
        "Adults in India most often have viral gastroenteritis, enterotoxigenic E. coli, or food-borne staphylococcal or Bacillus cereus toxin illness; **water-borne outbreaks of cholera, hepatitis E, typhoid and shigellosis** cluster after the monsoon, after pipeline contamination and at fairs and mass gatherings.",
        "The single most important message of the topic is that **death is from dehydration and electrolyte loss, not from the organism**, so rehydration always precedes and outranks any antimicrobial decision.",
      ],
    },
    {
      heading: "Assessing dehydration and deciding the plan",
      points: [
        "Ask: duration, stool frequency and character, blood or mucus, vomiting, fever, urine output, last feed, drugs (especially recent antibiotics), other cases in the household or locality, and the water source.",
        "**WHO/IMNCI classification:** no dehydration (fewer than two signs), some dehydration (two or more of restless and irritable, sunken eyes, drinks eagerly and thirstily, skin pinch goes back slowly), severe dehydration (two or more of lethargic or unconscious, sunken eyes, unable to drink or drinking poorly, skin pinch goes back very slowly).",
        "Weigh the child; percentage weight loss is the gold standard where a recent weight is known - under 5 percent is mild, 5-10 percent moderate, over 10 percent severe.",
        "**Plan A** (no dehydration): treat at home - extra fluids, ORS after each loose stool, zinc for 14 days, continued feeding, and the four danger signs to return with.",
        "**Plan B** (some dehydration): 75 mL/kg of low-osmolarity ORS over 4 hours at the facility, then reassess; continue breastfeeding throughout, and add ORS for ongoing losses.",
        "**Plan C** (severe dehydration): **Ringer lactate IV 100 mL/kg** - in infants under 12 months 30 mL/kg in the first hour then 70 mL/kg over 5 hours; in children over 12 months and adults 30 mL/kg in the first 30 minutes then 70 mL/kg over 2.5 hours. Reassess every 15-30 minutes and start ORS as soon as the patient can drink.",
        "In adults with cholera-like purging, losses can exceed a litre an hour; **the rate of replacement is dictated by the rate of loss**, and an intake-output chart with a cholera cot is the traditional and still correct answer.",
      ],
    },
    {
      heading: "ORS and zinc: the two interventions that save lives",
      points: [
        "**Low-osmolarity ORS (WHO 2004 formula)** contains sodium 75, chloride 65, glucose 75, potassium 20 and citrate 10 mmol/L, with a total osmolarity of 245 mOsm/L. It reduces stool output, vomiting and the need for unscheduled intravenous fluids compared with the older 311 mOsm/L formula.",
        "The physiological basis worth stating in a viva is the **sodium-glucose co-transporter (SGLT1) in the enterocyte brush border, which continues to work in secretory diarrhoea** and drags water with it - which is why glucose must be present in the right ratio and why plain water, sugar water alone or a soft drink will not do.",
        "Preparation: one sachet in exactly one litre of clean water, made fresh, discarded after 24 hours; **never make it stronger** - hypertonic ORS causes hypernatraemia and osmotic diarrhoea.",
        "**Zinc 20 mg per day for 14 days in children over 6 months, 10 mg per day for infants under 6 months**, given regardless of the type of diarrhoea. It shortens the episode by about 25 percent, reduces stool volume, and reduces recurrence over the next 2-3 months.",
        "**Feeding is continued throughout, including breastfeeding** - starving the gut prolongs the illness. Lactose-free formula is not routinely needed; give age-appropriate energy-dense food and an extra meal a day for two weeks after recovery.",
        "Avoid the drinks patients reach for: carbonated soft drinks and packaged fruit juices are hyperosmolar and worsen diarrhoea; sugarcane juice and roadside lemon water carry the same contamination risk as the original source.",
        "Home fluids that are acceptable when ORS is unavailable: salted rice water (kanji), salted buttermilk, coconut water and dal water - but they are a stopgap, and ORS must be procured.",
      ],
    },
    {
      heading: "When antibiotics are and are not indicated",
      points: [
        "**Most acute watery diarrhoea needs no antibiotic** - it is viral or toxin-mediated and self-limiting, and antibiotics prolong Salmonella carriage, promote resistance and risk Clostridioides difficile.",
        "**Dysentery (visible blood in stool):** treat empirically for Shigella - **ciprofloxacin 500 mg PO BD for 3 days in adults; in children, azithromycin 10-12 mg/kg once daily for 3 days or cefixime 8 mg/kg/day for 5 days** given widespread quinolone resistance in Indian Shigella.",
        "**Cholera** (profuse painless rice-water stools with rapid dehydration, often in an outbreak): rehydrate first, then a single dose of **doxycycline 300 mg PO in adults**, or azithromycin 1 g single dose in pregnancy and in children (20 mg/kg). Antibiotics shorten the illness and reduce transmission but never replace fluids.",
        "**Amoebic dysentery** (subacute, cramping, blood and mucus without much fever, trophozoites with ingested red cells on stool microscopy): **metronidazole 800 mg PO TDS for 7-10 days (children 30-50 mg/kg/day)** followed by a luminal amoebicide such as diloxanide furoate 500 mg TDS for 10 days or paromomycin.",
        "**Giardiasis** (foul-smelling frothy stools, bloating, flatulence, weight loss after 1-2 weeks): metronidazole 400 mg TDS for 5-7 days, tinidazole 2 g single dose, or nitazoxanide 500 mg BD for 3 days.",
        "**Enteric fever** must be considered when fever dominates and diarrhoea or constipation is secondary: blood culture before antibiotics, and cefixime or azithromycin as first line given multi-drug and quinolone resistance across India.",
        "Antimotility drugs: **loperamide is contraindicated in dysentery, in suspected C. difficile and in children under 12** because it precipitates toxic megacolon and masks fluid loss; it may be used for short-term symptom control in adult afebrile non-bloody diarrhoea. Racecadotril, an antisecretory drug, is an alternative with a better safety profile in children but is not a substitute for ORS and zinc.",
      ],
    },
    {
      heading: "Investigations, outbreaks and prevention",
      points: [
        "Most cases need no investigation. **Stool routine and microscopy** is worthwhile in dysentery, in persistent diarrhoea, and in the immunocompromised, looking for red cells, pus cells, trophozoites, cysts, ova and hanging-drop motility for cholera.",
        "Stool culture is indicated in dysentery not responding to treatment, in suspected outbreaks, in severe or systemic illness and in the immunosuppressed; **blood culture if fever is prominent** to catch enteric fever and bacteraemic salmonellosis.",
        "Serum electrolytes, creatinine and glucose in severe dehydration, in the elderly and in anyone with altered sensorium; hypokalaemia and metabolic acidosis are the usual disturbances and hyponatraemia complicates over-enthusiastic plain water rehydration.",
        "**Outbreak response** is examinable: define a case, count and plot the epidemic curve by time, place and person, inspect and chlorinate the water source (bleaching powder to a residual chlorine of 0.5 mg/L), collect water samples for coliform and stool samples for culture, set up an ORS depot, and notify the district health authority (IDSP-IHIP).",
        "Look for the classic Indian scenario in the question: **a cluster of watery diarrhoea in a colony after a pipeline burst or monsoon flooding**, which points to faecal contamination of piped water and mandates public health action rather than individual prescriptions.",
        "Prevention: safe water (boiling, chlorine tablets, household filters), sanitation and toilet use, handwashing with soap at the five critical times, exclusive breastfeeding for 6 months, rotavirus and measles vaccination, vitamin A, and food hygiene at fairs and street stalls.",
      ],
    },
    {
      heading: "Special situations",
      points: [
        "**The elderly and diabetics** decompensate quickly: they under-perceive thirst, are often on ACE inhibitors, ARBs, diuretics, metformin or SGLT2 inhibitors, and all of these should be held during significant diarrhoea (sick-day rules) to avoid acute kidney injury, lactic acidosis and euglycaemic ketoacidosis.",
        "**Antibiotic-associated diarrhoea and Clostridioides difficile** should be suspected after clindamycin, cephalosporins or fluoroquinolones, and treated by stopping the offending drug and giving oral vancomycin 125 mg QID or fidaxomicin; metronidazole is now a second-line option.",
        "**Traveller's diarrhoea** is usually ETEC; treat with fluids and, if moderate to severe, a single dose of azithromycin 1 g (preferred in South and South-East Asia because of quinolone resistance) with loperamide only if there is no fever or blood.",
        "**Diarrhoea in HIV or other immunosuppression** demands stool examination for Cryptosporidium, Cystoisospora, Cyclospora and Microsporidia with modified acid-fast staining, and a low threshold for referral.",
        "Persistent diarrhoea in a child (14 days or more) requires nutritional rehabilitation, a search for coexisting infection, micronutrient supplementation including zinc and vitamin A, and referral if there is severe acute malnutrition.",
        "Pregnancy: rehydration is unchanged, azithromycin is the safest antibiotic when one is needed, and **tetracyclines and quinolones are avoided**.",
      ],
    },
  ],
  tables: [
    {
      heading: "WHO/IMNCI dehydration assessment and treatment plan",
      columns: ["Assessment", "No dehydration (Plan A)", "Some dehydration (Plan B)", "Severe dehydration (Plan C)"],
      rows: [
        ["General condition", "Well, alert", "Restless, irritable", "Lethargic or unconscious"],
        ["Eyes", "Normal", "Sunken", "Sunken"],
        ["Thirst", "Drinks normally", "Thirsty, drinks eagerly", "Drinks poorly or unable to drink"],
        ["Skin pinch", "Goes back at once", "Goes back slowly", "Goes back very slowly (over 2 seconds)"],
        ["Fluid", "ORS after each stool at home", "75 mL/kg ORS over 4 hours", "Ringer lactate 100 mL/kg IV as per age schedule"],
        ["Zinc", "20 mg daily for 14 days", "20 mg daily for 14 days", "20 mg daily for 14 days once drinking"],
      ],
    },
    {
      heading: "Composition of low-osmolarity ORS (WHO 2004)",
      columns: ["Component", "Concentration (mmol/L)"],
      rows: [
        ["Sodium", "75"],
        ["Chloride", "65"],
        ["Glucose (anhydrous)", "75"],
        ["Potassium", "20"],
        ["Citrate", "10"],
        ["Total osmolarity", "245 mOsm/L"],
      ],
    },
    {
      heading: "Antibiotic choice by clinical syndrome",
      columns: ["Syndrome", "Likely organism", "Drug and dose", "Duration"],
      rows: [
        ["Acute watery diarrhoea, no fever", "Virus, ETEC, food toxin", "No antibiotic - ORS and zinc only", "-"],
        ["Bloody dysentery, fever, tenesmus", "Shigella, invasive E. coli, Campylobacter", "Ciprofloxacin 500 mg BD (adult); azithromycin 10-12 mg/kg OD (child)", "3 days"],
        ["Rice-water stools, rapid collapse, outbreak", "Vibrio cholerae O1", "Doxycycline 300 mg single dose (adult); azithromycin 20 mg/kg (child, pregnancy)", "Single dose"],
        ["Sub-acute bloody mucoid stool, little fever", "Entamoeba histolytica", "Metronidazole 800 mg TDS then diloxanide furoate 500 mg TDS", "7-10 days, then 10 days"],
        ["Frothy foul stools, bloating, weight loss", "Giardia lamblia", "Tinidazole 2 g single dose or metronidazole 400 mg TDS", "Single dose or 5-7 days"],
        ["Fever dominant, relative bradycardia", "Salmonella Typhi", "Cefixime 20 mg/kg/day or azithromycin 500 mg OD after blood culture", "7-14 days"],
      ],
    },
  ],
  redFlags: [
    "Lethargy, inability to drink, sunken eyes and a skin pinch that goes back very slowly - severe dehydration, start intravenous Ringer lactate immediately.",
    "Diarrhoea with no urine output for 8 hours or more, or a rising creatinine - acute kidney injury, admit.",
    "Visible blood in stool with high fever and abdominal tenderness in a toxic patient - invasive dysentery or perforation risk, refer.",
    "Profuse painless rice-water stools with rapid collapse, especially with other cases in the locality - suspected cholera, admit and notify.",
    "Abdominal distension with absent bowel sounds during dysentery - toxic megacolon; stop antimotility drugs and refer urgently.",
    "Persistent vomiting preventing oral intake, or convulsions during rehydration - suspect hyponatraemia or hypernatraemia and admit.",
    "Diarrhoea in a child with severe acute malnutrition (weight-for-height below minus 3 SD, oedema, MUAC under 11.5 cm) - refer, and use ReSoMal rather than standard ORS.",
    "Diarrhoea lasting beyond 14 days, or with weight loss and nocturnal stools in an adult - investigate rather than repeat the antibiotic.",
  ],
  pearls: [
    "Nobody dies of the organism; they die of the dehydration - rehydration always comes before the antibiotic decision.",
    "Zinc for 14 days in every child under five with diarrhoea, whatever the cause, shortens the episode by about a quarter and reduces recurrence for the next three months.",
    "Low-osmolarity ORS is 245 mOsm/L: sodium 75, glucose 75, chloride 65, potassium 20, citrate 10.",
    "Never make ORS stronger than one sachet per litre, and never substitute a soft drink - hyperosmolar fluids worsen the diarrhoea.",
    "Continue feeding and breastfeeding through the episode and give an extra meal daily for two weeks afterwards.",
    "Loperamide is forbidden in dysentery, in children under 12 and in suspected C. difficile - it can precipitate toxic megacolon.",
    "Trophozoites with ingested red blood cells, not cysts, are what make a stool diagnostic of invasive amoebiasis.",
    "Amoebiasis needs a tissue amoebicide followed by a luminal amoebicide - metronidazole alone leaves the patient a cyst passer.",
    "A cluster of cases in one colony is a public health emergency: chlorinate the water, notify under IDSP-IHIP, and set up an ORS depot.",
    "Hold metformin, SGLT2 inhibitors, ACE inhibitors, ARBs, diuretics and NSAIDs during significant diarrhoea - the sick-day rules.",
  ],
  theory: [
    {
      id: "gastro-hepatology-acute-diarrhoea-t1",
      paper: "II",
      kind: "long",
      marks: 10,
      minutes: 20,
      frequency: "core",
      question:
        "A 2-year-old child is brought with loose watery stools for two days and vomiting. Describe how you would assess the degree of dehydration and manage the child, and outline the preventive advice you would give the family.",
      openingLines: [
        "Acute diarrhoea is the passage of three or more loose or watery stools in 24 hours for less than 14 days; in a child under five the immediate risk is death from dehydration and electrolyte loss rather than from the causative organism.",
        "Management follows the WHO/IMNCI framework: classify dehydration clinically, choose Plan A, B or C, give low-osmolarity ORS and zinc for 14 days, continue feeding, and reserve antibiotics for specific indications.",
      ],
      answer: [
        {
          heading: "1. History",
          points: [
            "Duration, frequency and character of stools; blood or mucus; vomiting and whether fluids are being retained; fever; urine output over the last 6-8 hours.",
            "Feeding history including whether breastfeeding has been stopped, and what fluids have been given at home.",
            "Immunisation status with particular reference to rotavirus and measles vaccine, and vitamin A dosing.",
            "Drugs already given, especially antibiotics and antimotility agents bought over the counter.",
            "Other cases in the household or neighbourhood, and the source and storage of drinking water - this changes the answer from a prescription to a public health action.",
          ],
        },
        {
          heading: "2. Examination and classification of dehydration",
          points: [
            "General condition (alert, restless and irritable, or lethargic and unconscious), eyes (normal or sunken), thirst (drinks normally, eagerly, or poorly) and skin pinch (immediate, slow, or very slow).",
            "Two or more signs from the middle column classify some dehydration; two or more from the last column classify severe dehydration.",
            "Weigh the child and compare with any recent weight; assess for severe acute malnutrition using weight-for-height, MUAC and pedal oedema, since this changes the fluid used.",
            "Look for associated infection - pneumonia, otitis media, urinary infection, measles - and check for abdominal distension and absent bowel sounds.",
          ],
        },
        {
          heading: "3. Fluid management by plan",
          points: [
            "Plan A (no dehydration): ORS after each loose stool - 50-100 mL under 2 years, 100-200 mL for 2-10 years; continue breastfeeding; teach the mother to prepare ORS correctly and give the danger signs.",
            "Plan B (some dehydration): 75 mL/kg of low-osmolarity ORS over 4 hours at the facility, given by cup and spoon, with reassessment at 4 hours and continued breastfeeding.",
            "Plan C (severe dehydration): Ringer lactate 100 mL/kg intravenously - for a child over 12 months, 30 mL/kg in the first 30 minutes and 70 mL/kg over the next 2.5 hours; reassess every 15-30 minutes and start ORS by mouth as soon as the child can drink.",
            "If intravenous access fails, give ORS by nasogastric tube at 20 mL/kg/hour for 6 hours while arranging transfer.",
            "In severe acute malnutrition use ReSoMal at 5-10 mL/kg after each stool and avoid rapid intravenous fluids because of the risk of heart failure.",
          ],
        },
        {
          heading: "4. Zinc, feeding and drugs",
          points: [
            "Zinc 20 mg daily for 14 days (10 mg if under 6 months), which shortens the episode by about 25 percent and reduces recurrence for 2-3 months.",
            "Continue age-appropriate feeding and breastfeeding throughout; give one extra meal a day for two weeks after recovery to make up the nutritional deficit.",
            "No antibiotic for acute watery diarrhoea. Antibiotics only for dysentery (azithromycin 10-12 mg/kg once daily for 3 days), suspected cholera (azithromycin 20 mg/kg single dose) or an identified systemic infection.",
            "No antimotility drugs, no antiemetics as a routine, and no antisecretory drug in place of ORS and zinc; ondansetron may be used as a single dose in a child vomiting persistently to allow oral rehydration.",
            "Vitamin A if it is due or if there are eye signs or measles.",
          ],
        },
        {
          heading: "5. Danger signs and preventive advice",
          points: [
            "Return immediately if the child drinks poorly, becomes lethargic, passes blood in stool, develops fever, or is not better in three days.",
            "Safe water: boiling or chlorination, safe storage in a narrow-mouthed covered vessel with a ladle, and never dipping hands into stored water.",
            "Handwashing with soap after defecation, after cleaning a child, and before preparing or eating food; use of a toilet and safe disposal of children's stools.",
            "Exclusive breastfeeding for six months and appropriate complementary feeding thereafter; rotavirus vaccine at 6, 10 and 14 weeks under the Universal Immunisation Programme; measles-rubella vaccine and biannual vitamin A.",
            "Keep an ORS packet and zinc tablets in the house; the ORS-Zinc corner at the health facility and the Intensified Diarrhoea Control Fortnight exist for exactly this.",
          ],
        },
      ],
      mustDraw: [
        "The WHO/IMNCI dehydration assessment table with the four signs and the three columns leading to Plan A, B and C.",
        "The Plan C intravenous fluid schedule as a small table separating infants under 12 months from older children.",
      ],
      markSplit: [
        { part: "History including water source and immunisation", marks: 1.5 },
        { part: "Assessment and classification of dehydration", marks: 2.5 },
        { part: "Fluid management by plan with volumes and rates", marks: 3 },
        { part: "Zinc, feeding and rational antibiotic use", marks: 2 },
        { part: "Danger signs and prevention", marks: 1 },
      ],
      keywords: ["IMNCI", "Plan C", "Ringer lactate", "low osmolarity ORS", "zinc 14 days", "rotavirus vaccine"],
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-t2",
      paper: "II",
      kind: "short-note",
      marks: 5,
      minutes: 10,
      frequency: "common",
      question: "Write short notes on oral rehydration solution: composition, rationale, indications and limitations.",
      openingLines: [
        "Oral rehydration solution is a glucose-electrolyte solution designed to replace the water and electrolytes lost in diarrhoea by exploiting intestinal sodium-glucose co-transport, and it is one of the most important public health interventions of the twentieth century.",
        "The current WHO formula is the low-osmolarity solution of 245 mOsm/L, which replaced the original 311 mOsm/L formula in 2004.",
      ],
      answer: [
        {
          heading: "Composition and rationale",
          points: [
            "Sodium 75, chloride 65, glucose 75, potassium 20 and citrate 10 mmol/L; total osmolarity 245 mOsm/L.",
            "The **sodium-glucose co-transporter SGLT1** in the brush border of the enterocyte remains functional even in secretory diarrhoea such as cholera, and absorbs sodium with glucose in a 1:1 molar ratio, with water following osmotically.",
            "Potassium replaces stool potassium losses and prevents hypokalaemia; citrate corrects the metabolic acidosis of bicarbonate loss and gives the solution a longer shelf life than bicarbonate.",
            "Reducing the osmolarity lowers stool output by about 20 percent, reduces vomiting by about 30 percent, and cuts the need for unscheduled intravenous fluid by about 30 percent.",
          ],
        },
        {
          heading: "Indications and method of use",
          points: [
            "All degrees of dehydration except severe dehydration and shock, where intravenous Ringer lactate is started first and ORS added as soon as the patient can drink.",
            "Plan A: ORS after every loose stool at home; Plan B: 75 mL/kg over 4 hours under supervision.",
            "One sachet is dissolved in exactly one litre of clean water, given by cup and spoon or small frequent sips, and discarded after 24 hours.",
            "ORS may be given by nasogastric tube at 20 mL/kg/hour when intravenous access is impossible.",
          ],
        },
        {
          heading: "Limitations and contraindications",
          points: [
            "Not to be used alone in shock, severe dehydration, persistent vomiting, paralytic ileus or abdominal distension, or in an unconscious patient.",
            "Does not reduce stool frequency or duration - this must be explained to parents, or they will abandon it and buy an antibiotic.",
            "Standard ORS is unsuitable in severe acute malnutrition, where **ReSoMal** with lower sodium and higher potassium is used instead.",
            "Incorrect preparation is the main practical failure: too concentrated causes hypernatraemia, too dilute fails to correct sodium loss.",
            "ORS does not replace zinc, continued feeding, or the public health action needed when cases are clustering.",
          ],
        },
      ],
      mustDraw: ["A table of the low-osmolarity ORS composition in mmol/L with the total osmolarity, and a one-line diagram of SGLT1 co-transport at the brush border."],
      markSplit: [
        { part: "Composition with figures", marks: 1.5 },
        { part: "Physiological rationale (SGLT1, citrate, potassium)", marks: 1.5 },
        { part: "Indications and correct use", marks: 1 },
        { part: "Limitations and contraindications", marks: 1 },
      ],
      keywords: ["ORS", "SGLT1", "low osmolarity", "ReSoMal", "citrate"],
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-t3",
      paper: "II",
      kind: "chart-flow",
      marks: 5,
      minutes: 10,
      frequency: "common",
      question:
        "Twelve people from one colony report to your clinic in a single morning with acute watery diarrhoea and vomiting. Outline your response as a family physician.",
      openingLines: [
        "A sudden clustering of acute diarrhoea in one locality is an outbreak until proved otherwise, and the response has two simultaneous arms: clinical care of the individual cases and an epidemiological and environmental investigation.",
        "Cholera, enterotoxigenic E. coli, viral gastroenteritis, hepatitis E and food-borne toxin illness all present this way, and the water supply is the first suspect after monsoon flooding or a pipeline leak.",
      ],
      answer: [
        {
          heading: "1. Immediate clinical care",
          points: [
            "Triage by dehydration status; start Ringer lactate at once for anyone with severe dehydration, and set up an oral rehydration corner with ORS for the rest.",
            "Set up a cholera cot with an intake-output chart for high-volume purgers, and admit or refer those with shock, no urine output, or an inability to drink.",
            "Zinc for all children, continued feeding, and a single dose of doxycycline 300 mg for adults with confirmed or strongly suspected cholera after rehydration has begun.",
            "Keep a line list of every case with name, age, sex, address, date of onset and outcome.",
          ],
        },
        {
          heading: "2. Epidemiological investigation",
          points: [
            "Define a case (for example, three or more loose stools in 24 hours in a resident of the colony since a stated date) and search actively for further cases.",
            "Plot the epidemic curve by date of onset; map cases by household to see whether they follow a single water line, a common well, or one function or eatery.",
            "Take a food history for a common meal, marriage or festival if the curve is a sharp point-source spike within hours.",
            "Collect stool samples in Cary-Blair medium for culture and do hanging-drop microscopy for the darting motility of Vibrio cholerae.",
          ],
        },
        {
          heading: "3. Environmental and public health action",
          points: [
            "Inspect the water source and distribution line for leaks and cross-connection with sewage; collect water samples for coliform count and residual chlorine.",
            "Chlorinate the source with bleaching powder to achieve a residual chlorine of 0.5 mg/L after 30 minutes contact; advise boiling or household chlorine tablets meanwhile.",
            "Notify the medical officer and report under IDSP-IHIP; mobilise ASHA and anganwadi workers for house-to-house ORS distribution and case finding.",
            "Health education on handwashing, safe water storage, safe disposal of excreta and food hygiene; consider oral cholera vaccine in a confirmed and continuing outbreak.",
            "Follow up until two incubation periods have passed with no new case, and record the lessons for the next monsoon.",
          ],
        },
      ],
      mustDraw: [
        "An epidemic curve (cases against date of onset) contrasting a point-source spike with a propagated wave.",
        "A flow chart: cluster of cases leading in parallel to case management, line listing and epidemic curve, water sampling and chlorination, and notification.",
      ],
      markSplit: [
        { part: "Immediate clinical care and triage", marks: 1.5 },
        { part: "Case definition, line list and epidemic curve", marks: 1.5 },
        { part: "Water investigation and chlorination", marks: 1 },
        { part: "Notification, community mobilisation and health education", marks: 1 },
      ],
      keywords: ["outbreak", "epidemic curve", "residual chlorine", "IDSP-IHIP", "cholera", "line list"],
    },
  ],
  mcqs: [
    {
      id: "gastro-hepatology-acute-diarrhoea-q1",
      stem: "A 14-month-old boy weighing 9 kg has had watery stools for a day. He is restless and irritable, has sunken eyes, drinks eagerly when offered ORS, and the skin pinch goes back slowly. What is the correct fluid management?",
      options: [
        "ORS 50-100 mL after each loose stool at home",
        "Low-osmolarity ORS 675 mL over 4 hours at the facility, then reassess",
        "Ringer lactate 900 mL intravenously over 3 hours",
        "Ringer lactate 270 mL over 30 minutes then 630 mL over 2.5 hours",
        "Plain water and diluted fruit juice as much as he will take",
      ],
      answer: 1,
      explanation:
        "He has two or more signs of some dehydration - restlessness, sunken eyes, eager drinking and a slow skin pinch - which is Plan B: 75 mL/kg of low-osmolarity ORS over 4 hours under supervision, that is 675 mL for a 9 kg child, with reassessment at 4 hours. Plan A with ORS after each stool is for a child with no dehydration and would under-treat him. The intravenous options belong to Plan C, which requires severe dehydration with lethargy or an inability to drink, and he is drinking eagerly. Plain water and juice supply no sodium and juice is hyperosmolar, which worsens stool output.",
      difficulty: "moderate",
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-q2",
      stem: "A 3-year-old girl has had diarrhoea for two days with no dehydration. Her mother asks what else to give besides ORS. What is the correct advice about zinc?",
      options: [
        "Zinc 20 mg daily for 3 days",
        "Zinc 20 mg daily for 14 days",
        "Zinc 10 mg daily for 14 days",
        "Zinc is only indicated in persistent or bloody diarrhoea",
        "Zinc should be avoided as it worsens vomiting",
      ],
      answer: 1,
      explanation:
        "WHO and the Government of India recommend zinc 20 mg daily for 14 days in every child over 6 months with diarrhoea of any type, which shortens the episode by about 25 percent, reduces stool volume and reduces recurrence over the next two to three months. Three days is too short to deliver the protective effect on subsequent episodes, and 10 mg is the dose for infants under 6 months. Restricting zinc to persistent or bloody diarrhoea abandons its main benefit in ordinary acute diarrhoea. Zinc may cause transient vomiting, which is managed by giving it after a feed rather than by withholding it.",
      difficulty: "easy",
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-q3",
      stem: "A 30-year-old man from a flood-affected area has passed 15 litres of painless watery stool with flecks of mucus in 12 hours, and is now hypotensive with a thready pulse. Several neighbours are similarly ill. After starting Ringer lactate, which antimicrobial is most appropriate?",
      options: [
        "Ciprofloxacin 500 mg twice daily for 5 days",
        "Doxycycline 300 mg as a single oral dose",
        "Metronidazole 800 mg three times daily for 7 days",
        "Cefixime 200 mg twice daily for 7 days",
        "No antimicrobial is ever indicated in cholera",
      ],
      answer: 1,
      explanation:
        "Painless rice-water purging with rapid hypovolaemia in an outbreak setting is cholera, and once rehydration has been started a single 300 mg dose of doxycycline reduces stool volume, shortens the illness and shortens the duration of vibrio excretion, thereby limiting transmission. Fluoroquinolone resistance in Vibrio cholerae is now widespread in South Asia, so ciprofloxacin is unreliable. Metronidazole treats amoebiasis and giardiasis, neither of which causes rice-water stools, and cefixime is used for enteric fever. It is wrong to say antibiotics are never indicated - they are adjunctive to, though never a substitute for, fluid replacement.",
      difficulty: "moderate",
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-q4",
      stem: "A 7-year-old boy has fever, cramping abdominal pain, tenesmus and small-volume stools with visible blood for two days. He is not dehydrated. What is the most appropriate antibiotic?",
      options: [
        "Loperamide 2 mg after each loose stool",
        "Ciprofloxacin 15 mg/kg twice daily for 5 days",
        "Azithromycin 10-12 mg/kg once daily for 3 days",
        "Metronidazole 30 mg/kg/day in three divided doses for 10 days",
        "Ofloxacin plus ornidazole combination for 5 days",
      ],
      answer: 2,
      explanation:
        "Fever with tenesmus and frequent small bloody stools is bacillary dysentery, most often Shigella, and azithromycin for three days is the recommended first line in children in India because fluoroquinolone resistance in Shigella is now high and quinolones are avoided in children where an alternative exists. Loperamide is contraindicated in dysentery at any age and in all children under 12, as it can precipitate toxic megacolon and prolong bacterial carriage. Metronidazole treats amoebic dysentery, which is subacute with less fever and shows trophozoites containing red cells. Fixed-dose quinolone-nitroimidazole combinations are irrational, widely misused in India, and add toxicity without covering the likely resistant organism.",
      difficulty: "moderate",
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-q5",
      stem: "A mother says her child refuses ORS and asks whether she can give him a bottled carbonated soft drink or packaged apple juice instead. What is the correct explanation?",
      options: [
        "They are acceptable substitutes because they contain glucose and water",
        "They are hyperosmolar and low in sodium, so they worsen the diarrhoea",
        "They are safe if diluted with an equal volume of plain water",
        "They are better than ORS because children take them willingly",
        "They should be used only if the child has vomiting",
      ],
      answer: 1,
      explanation:
        "Carbonated soft drinks and packaged juices have an osmolarity two to three times that of low-osmolarity ORS with almost no sodium and no potassium, so they draw water into the lumen and increase stool output while failing to replace the sodium being lost. Dilution lowers the osmolarity but still leaves a sodium-free fluid that risks hyponatraemia when large volumes are given. Palatability is a real problem, but the answer is small frequent sips of ORS by cup and spoon, or an acceptable home fluid such as salted rice water or salted buttermilk, rather than a hyperosmolar sweet drink. Vomiting is not an indication for them; it is an indication for slower, smaller, more frequent ORS.",
      difficulty: "easy",
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-q6",
      stem: "A 45-year-old man has passed loose stools with mucus and streaks of blood for ten days, with lower abdominal cramps but little fever. Stool microscopy shows motile trophozoites containing ingested red blood cells. What is the complete treatment?",
      options: [
        "Metronidazole 800 mg three times daily for 7-10 days only",
        "Metronidazole 800 mg three times daily for 7-10 days followed by diloxanide furoate 500 mg three times daily for 10 days",
        "Diloxanide furoate 500 mg three times daily for 10 days only",
        "Ciprofloxacin 500 mg twice daily for 5 days",
        "Albendazole 400 mg as a single dose",
      ],
      answer: 1,
      explanation:
        "Trophozoites with ingested erythrocytes are diagnostic of invasive Entamoeba histolytica, which requires a tissue amoebicide followed by a luminal amoebicide: metronidazole or tinidazole clears the invading trophozoites but does not eradicate cysts in the colonic lumen, so without diloxanide furoate or paromomycin the patient remains a cyst passer and may relapse. A luminal agent alone does not treat invasive disease. Ciprofloxacin targets bacillary dysentery, which produces pus cells rather than red-cell-containing trophozoites, and albendazole treats helminths, not protozoa.",
      difficulty: "moderate",
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-q7",
      stem: "A 68-year-old man with type 2 diabetes on metformin, an SGLT2 inhibitor, telmisartan and a diuretic develops acute diarrhoea with poor oral intake. Apart from rehydration, what is the most important immediate step?",
      options: [
        "Increase his metformin to control the stress hyperglycaemia",
        "Temporarily stop metformin, the SGLT2 inhibitor, telmisartan and the diuretic",
        "Start loperamide to reduce fluid losses",
        "Start empirical ciprofloxacin to prevent complications",
        "Continue all drugs unchanged as stopping them destabilises control",
      ],
      answer: 1,
      explanation:
        "Sick-day rules require temporary withdrawal of drugs that become dangerous in volume depletion: metformin risks lactic acidosis, SGLT2 inhibitors risk euglycaemic ketoacidosis and volume loss, and ACE inhibitors, ARBs, diuretics and NSAIDs together precipitate acute kidney injury by removing the kidney's autoregulatory reserve. Increasing metformin compounds the lactic acidosis risk. Loperamide gives symptomatic relief at best and does nothing about the renal and metabolic hazard, and an empirical fluoroquinolone treats a self-limiting illness while adding tendon, QT and C. difficile risk in an older patient.",
      difficulty: "moderate",
    },
  ],
  cards: [
    {
      id: "gastro-hepatology-acute-diarrhoea-c1",
      front: "Composition of low-osmolarity ORS.",
      back: "Sodium 75, chloride 65, glucose 75, potassium 20, citrate 10 mmol/L; total osmolarity 245 mOsm/L.",
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-c2",
      front: "Zinc dose and duration in childhood diarrhoea.",
      back: "20 mg daily for 14 days (10 mg daily if under 6 months), whatever the type of diarrhoea.",
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-c3",
      front: "Plan B fluid volume and time.",
      back: "75 mL/kg of low-osmolarity ORS over 4 hours at the facility, then reassess.",
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-c4",
      front: "Plan C: fluid, total volume and schedule.",
      back: "Ringer lactate 100 mL/kg. Under 12 months: 30 mL/kg in 1 hour then 70 mL/kg over 5 hours. Over 12 months: 30 mL/kg in 30 minutes then 70 mL/kg over 2.5 hours.",
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-c5",
      front: "The four IMNCI signs used to classify dehydration.",
      back: "General condition, sunken eyes, thirst and drinking, and skin pinch. Two or more signs in a column classify that grade.",
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-c6",
      front: "Why does ORS work in secretory diarrhoea?",
      back: "The SGLT1 sodium-glucose co-transporter in the enterocyte brush border stays intact and absorbs sodium with glucose 1:1, with water following osmotically.",
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-c7",
      front: "Treatment of cholera in an adult after rehydration.",
      back: "Doxycycline 300 mg as a single oral dose; azithromycin 1 g single dose in pregnancy and 20 mg/kg in children.",
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-c8",
      front: "Bacillary versus amoebic dysentery on stool microscopy.",
      back: "Bacillary: many pus cells and red cells, no trophozoites. Amoebic: trophozoites containing ingested red blood cells, few pus cells.",
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-c9",
      front: "Complete treatment of amoebic dysentery.",
      back: "Metronidazole 800 mg TDS (or tinidazole 2 g OD) for 7-10 days, then a luminal amoebicide - diloxanide furoate 500 mg TDS for 10 days or paromomycin.",
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-c10",
      front: "When is loperamide contraindicated?",
      back: "Dysentery or any bloody diarrhoea, fever, suspected C. difficile, and all children under 12 - risk of toxic megacolon and masked fluid loss.",
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-c11",
      front: "Residual chlorine target when chlorinating a suspect water source.",
      back: "0.5 mg/L after 30 minutes of contact time.",
    },
    {
      id: "gastro-hepatology-acute-diarrhoea-c12",
      front: "Which ORS is used in severe acute malnutrition, and why?",
      back: "ReSoMal - lower sodium and higher potassium, because these children are sodium-overloaded and potassium-depleted and tolerate rapid fluid poorly.",
    },
  ],
  references: [
    "WHO/UNICEF Joint Statement on the Clinical Management of Acute Diarrhoea, and WHO Diarrhoea Treatment Guidelines, 2005 onwards",
    "Government of India, Ministry of Health and Family Welfare - Intensified Diarrhoea Control Fortnight operational guidelines",
    "IMNCI chart booklet, Government of India, current edition",
    "Indian Academy of Pediatrics guidelines on management of acute diarrhoea, 2020",
    "National Centre for Disease Control guidelines on cholera and outbreak investigation, IDSP-IHIP",
    "Park's Textbook of Preventive and Social Medicine, 27th edition, 2023 - epidemiology of diarrhoeal diseases",
  ],
});
