import type { ClinicalCase, Subject, Topic } from "../lib/types";

const topics: Topic[] = [];

topics.push({
  id: "neurology-headache",
  title: "Headache and migraine",
  oneLiner:
    "Headache is the commonest neurological complaint in family practice, and its management turns on a single first decision - whether this is a primary headache (migraine, tension-type or cluster) that can be diagnosed clinically and treated, or a secondary headache flagged by thunderclap onset, fever with neck stiffness, papilloedema, a new focal deficit, immunosuppression or new-onset headache after 50, which needs same-day imaging.",
  frequency: "core",
  keywords: [
    "migraine",
    "aura",
    "tension-type headache",
    "cluster headache",
    "ICHD-3",
    "sumatriptan",
    "naproxen",
    "flunarizine",
    "propranolol",
    "topiramate",
    "amitriptyline",
    "medication overuse headache",
    "thunderclap headache",
    "SNNOOP10",
    "idiopathic intracranial hypertension",
    "subarachnoid haemorrhage",
    "trigeminal neuralgia",
    "giant cell arteritis",
  ],
  sections: [
    {
      heading: "Burden and the first decision",
      points: [
        "Headache accounts for roughly 3-5% of all family practice consultations and more than a third of neurology referrals; the lifetime prevalence of headache in adults exceeds 90%.",
        "Indian community studies (the Karnataka and Bangalore door-to-door surveys) put the one-year prevalence of **migraine at about 25%**, with a female-to-male ratio near 3:1 and a peak between 25 and 45 years - the most economically productive decades.",
        "**The first decision is always primary versus secondary headache**, and it is made by history and examination, not by a scan. More than 90% of headaches reaching a family physician are primary.",
        "A confident **positive** diagnosis of migraine or tension-type headache using ICHD-3 criteria is far more useful than a negative CT scan, because a normal scan does not exclude any of the primary headaches and does not treat the patient.",
        "In a patient with a typical primary headache pattern, a normal neurological examination and no red flags, the yield of neuroimaging for a clinically significant lesion is **under 1%** - lower than the rate of incidental findings that generate anxiety and further tests.",
        "Three questions carry most of the diagnostic weight: how many different types of headache do you get, how did the worst one begin (over seconds, minutes or days), and how many days a month do you take a painkiller.",
        "Always record the **headache days per month and the analgesic days per month** in the notes; both are needed to diagnose chronic migraine and medication overuse headache and both are the outcome you follow.",
      ],
    },
    {
      heading: "Migraine: making the diagnosis by ICHD-3",
      points: [
        "**Migraine without aura (ICHD-3):** at least 5 attacks lasting 4-72 hours untreated, with at least **two of** unilateral site, pulsating quality, moderate or severe intensity, and aggravation by routine physical activity; **plus at least one of** nausea or vomiting, or photophobia together with phonophobia.",
        "**Migraine with aura:** at least 2 attacks of fully reversible visual, sensory, speech, motor, brainstem or retinal symptoms, each spreading gradually over 5 minutes or more and lasting 5-60 minutes, followed by headache within 60 minutes. The commonest aura is visual - a scintillating scotoma or fortification spectra marching across the field.",
        "**Chronic migraine:** headache on **15 or more days a month for more than 3 months**, with the features of migraine on at least 8 of those days. Most chronic migraine begins as episodic migraine that transformed, usually with medication overuse as the driver.",
        "The attack has four phases the patient will recognise once asked: prodrome (yawning, food craving, irritability, neck stiffness, hours to a day before), aura, headache, and postdrome (the washed-out day after).",
        "The **POUND** mnemonic is a useful bedside screen - Pulsating, duration 4-72 hOurs, Unilateral, Nausea, Disabling; four of five features give a likelihood ratio above 20 for migraine.",
        "**Menstrual migraine** occurs from two days before to three days after the onset of menstruation in at least two of three cycles; it is longer, more severe and less responsive to treatment, and responds to perimenstrual naproxen or frovatriptan.",
        "**Aura that should worry you:** sudden rather than gradual onset, always on the same side, lasting more than 60 minutes, associated with motor weakness, or first occurring after 50 - these need imaging to exclude TIA, focal seizure, arteriovenous malformation or a structural lesion.",
      ],
    },
    {
      heading: "Tension-type headache, cluster and the other primaries",
      points: [
        "**Tension-type headache** is bilateral, pressing or tightening (a band, a weight, a tight cap), mild to moderate, **not aggravated by routine activity**, and without nausea or vomiting; photophobia or phonophobia may be present but not both. It is the commonest headache in the population but the least often brought to the doctor.",
        "**Cluster headache** is strictly unilateral orbital, supraorbital or temporal pain of excruciating severity lasting 15-180 minutes, occurring from once every other day to eight times a day, with **ipsilateral cranial autonomic features** - conjunctival injection, lacrimation, nasal congestion or rhinorrhoea, eyelid oedema, ptosis and miosis - and a striking **restlessness and pacing** (contrast with the migraineur who lies still in a dark room).",
        "Cluster favours men, smokers and alcohol as a trigger during a bout, and shows circadian (often waking the patient at the same hour) and circannual clustering with pain-free remissions of months to years.",
        "**Acute cluster attack:** **high-flow oxygen 12-15 L/min by non-rebreathing mask for 15-20 minutes** and **subcutaneous sumatriptan 6 mg** (or intranasal sumatriptan 20 mg / zolmitriptan 5 mg); oral triptans and oral analgesics act too slowly to be useful.",
        "**Cluster prophylaxis:** verapamil 240-480 mg daily in divided doses, titrated with a baseline and serial ECG for PR prolongation and heart block, with a bridging course of **prednisolone 60 mg daily for 5 days then tapering over 2-3 weeks** while verapamil takes effect.",
        "**Trigeminal neuralgia:** paroxysms of electric-shock pain lasting seconds in the V2 or V3 distribution, triggered by chewing, talking, shaving, cold wind or touching a trigger zone, with a refractory period between paroxysms. First-line treatment is **carbamazepine 100 mg PO twice daily, titrated to 200 mg three or four times daily** (oxcarbazepine as an alternative); MRI is indicated in anyone under 40, with sensory loss, bilateral pain or a poor drug response, to exclude multiple sclerosis or a cerebellopontine angle tumour.",
        "**Hemicrania continua and paroxysmal hemicrania respond absolutely to indomethacin** (25-75 mg TDS) - the response is a diagnostic test, and a strictly unilateral daily headache with autonomic features deserves an indomethacin trial with gastric protection.",
      ],
    },
    {
      heading: "Red flags and who actually needs a scan",
      points: [
        "The SNNOOP10 list is the modern successor to SNOOP: **S**ystemic symptoms including fever, **N**eoplasm history, **N**eurological deficit, **O**nset sudden or thunderclap, **O**lder age (new headache after 50), **P**attern change, **P**ositional headache, **P**recipitated by Valsalva, **P**apilloedema, **P**rogressive headache, **P**regnancy or puerperium, **P**ainful eye with autonomic features, **P**ost-traumatic onset, **P**athology of the immune system such as HIV, and **P**ainkiller overuse.",
        "**Thunderclap headache** - maximum intensity within one minute - is subarachnoid haemorrhage until proved otherwise. A non-contrast CT within 6 hours of onset is close to 100% sensitive; beyond 6 hours a negative CT must be followed by **lumbar puncture at 12 hours or later looking for xanthochromia**, and by CT or MR angiography if suspicion persists (also consider reversible cerebral vasoconstriction syndrome, cervical artery dissection and pituitary apoplexy).",
        "**Fever with headache and neck stiffness** is meningitis: do not delay the first dose of antibiotic for imaging or for the lumbar puncture.",
        "**New headache after 50 with scalp tenderness, jaw claudication, visual symptoms and an ESR above 50 mm/h** is giant cell arteritis - start **prednisolone 40-60 mg daily (1 mg/kg, or intravenous methylprednisolone if there is visual loss) immediately** and arrange temporal artery biopsy within 1-2 weeks; the biopsy stays positive for days after steroids and sight lost is not recovered.",
        "**Headache worse on lying down, on waking, or with coughing and straining, with papilloedema**, suggests raised intracranial pressure - a mass lesion, cerebral venous sinus thrombosis, or idiopathic intracranial hypertension in a young obese woman (needs MRI with MR venography, then lumbar puncture with an opening pressure above 25 cm of water, then acetazolamide and weight loss, with urgent referral if vision is threatened).",
        "**Headache in pregnancy or the puerperium** demands exclusion of pre-eclampsia (blood pressure and urine protein first, always), cerebral venous sinus thrombosis and posterior reversible encephalopathy syndrome.",
        "**Headache in an immunosuppressed or HIV-positive patient** needs contrast imaging and usually cerebrospinal fluid examination - cryptococcal meningitis, cerebral toxoplasmosis, tuberculoma and primary CNS lymphoma all present with slowly progressive headache and few signs.",
        "Choose the test to the question: **non-contrast CT** for acute haemorrhage and trauma, **MRI** for posterior fossa and pituitary lesions, low-pressure and high-pressure syndromes, **MR venography** for sinus thrombosis, and **CT or MR angiography** for aneurysm and dissection.",
      ],
    },
    {
      heading: "Acute treatment of migraine",
      points: [
        "Two principles decide success: **treat early, while the pain is still mild**, and **use an adequate single dose** rather than repeated small doses, because gastric stasis during an attack impairs absorption once the headache is established.",
        "**Step 1 - simple analgesia with an antiemetic:** naproxen 500 mg, ibuprofen 400-600 mg, diclofenac 50 mg or aspirin 900 mg orally, combined with **domperidone 10 mg or metoclopramide 10 mg**, which treats the nausea and restores gastric emptying so the analgesic is absorbed.",
        "**Step 2 - a triptan:** sumatriptan 50-100 mg PO, rizatriptan 10 mg, or naratriptan 2.5 mg; repeat once after 2 hours if there is a partial response, to a maximum of two doses in 24 hours. Use **subcutaneous sumatriptan 6 mg or intranasal sumatriptan 20 mg** when there is early vomiting.",
        "A **triptan plus an NSAID together** (for example sumatriptan 85 mg with naproxen 500 mg) is more effective than either alone and reduces headache recurrence - the single most useful prescribing tip in resistant attacks.",
        "**Triptans are contraindicated** in ischaemic heart disease, previous myocardial infarction, uncontrolled hypertension, previous stroke, peripheral vascular disease, hemiplegic and brainstem-aura migraine, and within 24 hours of an ergot preparation; they are avoided rather than absolutely forbidden in pregnancy.",
        "**Do not use opioids, tramadol, butalbital combinations or ergotamine** for routine migraine: they are less effective, they are the drugs most likely to produce medication overuse headache, and ergot adds vascular risk.",
        "**Limit acute medication days** - triptans, opioids and combination analgesics to fewer than 10 days a month, and simple analgesics to fewer than 15 days a month - and say this number out loud to the patient at the first visit.",
        "**Clinic rescue for a severe or prolonged attack:** intravenous fluids, **metoclopramide 10 mg IV** (or chlorpromazine 12.5 mg IV with fluid preloading), **diclofenac 75 mg IM** or ketorolac 30 mg IV, and **dexamethasone 8 mg IV** which reduces headache recurrence in the following 72 hours.",
      ],
    },
    {
      heading: "Prevention and medication overuse headache",
      points: [
        "**Offer prophylaxis when** there are 4 or more attacks a month, attacks are prolonged or severely disabling despite optimal acute treatment, acute drugs are contraindicated or overused, or the migraine is hemiplegic, brainstem-aura or with prolonged aura.",
        "**Propranolol 20-40 mg PO twice daily, titrated to 80-160 mg a day** is the standard first choice; avoid it in asthma, in bradycardia and in depression, and remember it blunts the tachycardia of hypoglycaemia in a diabetic.",
        "**Amitriptyline 10-25 mg at night, titrated to 50-75 mg**, is best where there is coexistent tension-type headache, insomnia or a chronic pain syndrome; warn about dry mouth, sedation and weight gain, and avoid it in glaucoma, prostatism and cardiac conduction disease.",
        "**Topiramate 25 mg at night, increased by 25 mg weekly to 50-100 mg a day**, is effective and causes weight loss, but produces paraesthesiae, word-finding difficulty and renal stones, and is **teratogenic and reduces the efficacy of combined oral contraceptives**.",
        "**Flunarizine 5-10 mg at night** is inexpensive, widely used in India and genuinely effective; the price is weight gain, sedation, depression and, in the elderly, drug-induced parkinsonism. **Sodium valproate 500-1000 mg** works well but must not be used in women of childbearing potential.",
        "An adequate trial is **8-12 weeks at the target dose**, judged against a headache diary, and success is defined as a **50% reduction in headache days**, not abolition. Continue a successful preventive for 6-12 months, then taper.",
        "**Medication overuse headache** is headache on 15 or more days a month in a patient with a pre-existing primary headache, with regular overuse for more than 3 months of simple analgesics on 15 or more days a month, or triptans, opioids, ergots or combination analgesics on 10 or more days a month. Treatment is **withdrawal of the offending drug**, a preventive started at the same time, an explanation that headache will worsen for 1-2 weeks, and a bridging course of naproxen or a short prednisolone taper.",
        "Non-drug measures that genuinely work: regular sleep and meal times, hydration, aerobic exercise, treatment of comorbid depression and anxiety, and a trigger diary - but avoid imposing long elimination diets, which rarely help and often harm nutrition.",
      ],
    },
    {
      heading: "Special situations",
      points: [
        "**Pregnancy:** paracetamol 1 g is first line; NSAIDs may be used in the second trimester but are avoided after 30 weeks (ductal closure) and near conception; metoclopramide is safe; accumulated registry data for sumatriptan are reassuring. For prevention use low-dose propranolol or amitriptyline. **Any new or severe headache after 20 weeks is pre-eclampsia until blood pressure and urine protein prove otherwise.**",
        "**Migraine with aura is an absolute contraindication to combined hormonal contraception (WHO Medical Eligibility Criteria category 4)** because the ischaemic stroke risk multiplies; offer progestogen-only pills, injectables, implants, the copper or levonorgestrel intrauterine device, or barrier methods.",
        "Migraine improves in about two-thirds of women during the second and third trimesters and typically worsens again postpartum and around the perimenopause.",
        "**Children and adolescents:** attacks are shorter (2-72 hours), more often bilateral and frontotemporal, with prominent abdominal pain, motion sickness and travel-related vomiting. Ibuprofen 10 mg/kg is first line, with intranasal sumatriptan in adolescents; flunarizine and propranolol are the usual preventives.",
        "**New headache in a person over 50** is secondary until proved otherwise - giant cell arteritis, subdural haematoma (ask about a fall or anticoagulation), a mass lesion, cervical spondylosis and glaucoma all present this way.",
        "Migraine with aura roughly doubles the risk of ischaemic stroke, and the risk multiplies with smoking and combined oral contraceptives - which makes smoking cessation and contraceptive review part of migraine care, not a separate consultation.",
        "**Idiopathic intracranial hypertension** in an obese young woman with headache, transient visual obscurations, pulsatile tinnitus and papilloedema needs urgent visual field assessment; weight loss and acetazolamide 250-500 mg twice daily are first line, and failing vision is an indication for shunting or optic nerve sheath fenestration.",
      ],
    },
  ],
  tables: [
    {
      heading: "The three primary headaches at a glance",
      columns: ["Feature", "Migraine", "Tension-type", "Cluster"],
      rows: [
        ["Site", "Unilateral in 60%, may alternate", "Bilateral, band-like", "Strictly unilateral, orbital or temporal"],
        ["Character", "Pulsating, throbbing", "Pressing, tightening, non-pulsatile", "Boring, stabbing, excruciating"],
        ["Duration untreated", "4-72 hours", "30 minutes to 7 days", "15-180 minutes"],
        ["Frequency", "1-4 a month typically", "Episodic or daily", "1 every other day to 8 a day, in bouts"],
        ["Associated features", "Nausea, vomiting, photophobia and phonophobia, aura in 25%", "None, or one of photophobia or phonophobia", "Ipsilateral lacrimation, conjunctival injection, rhinorrhoea, ptosis, miosis"],
        ["Behaviour in attack", "Lies still in a dark quiet room", "Continues activity", "Restless, paces, may bang the head"],
        ["Typical patient", "Woman 25-45 years", "Any adult, stress and posture related", "Man 20-50 years, smoker"],
      ],
    },
    {
      heading: "Acute migraine drugs and doses",
      columns: ["Step", "Drug and dose", "Practical notes"],
      rows: [
        ["Antiemetic (add to every step)", "Domperidone 10 mg PO or metoclopramide 10 mg PO/IV", "Treats nausea and restores gastric emptying; metoclopramide can cause acute dystonia in the young"],
        ["Step 1 NSAID", "Naproxen 500 mg, ibuprofen 400-600 mg, diclofenac 50 mg or aspirin 900 mg PO", "Take at the first sign; avoid in peptic ulcer, CKD and third trimester"],
        ["Step 2 triptan", "Sumatriptan 50-100 mg PO, rizatriptan 10 mg PO, naratriptan 2.5 mg PO", "Repeat once after 2 hours; maximum two doses in 24 hours"],
        ["Vomiting at onset", "Sumatriptan 6 mg SC or 20 mg intranasal", "Fastest route; SC works within 10-15 minutes"],
        ["Best combination", "Sumatriptan 85 mg plus naproxen 500 mg together", "Superior to either alone and reduces recurrence"],
        ["Clinic rescue", "IV fluids, metoclopramide 10 mg IV, diclofenac 75 mg IM, dexamethasone 8 mg IV", "Dexamethasone reduces 72-hour recurrence"],
        ["Never", "Pethidine, tramadol, other opioids, ergotamine", "Poor efficacy and the highest risk of medication overuse headache"],
      ],
    },
    {
      heading: "Migraine preventives",
      columns: ["Drug", "Dose", "Best in", "Avoid in"],
      rows: [
        ["Propranolol", "20-40 mg PO BD up to 160 mg/day", "Coexistent hypertension, anxiety, tremor", "Asthma, bradycardia, depression, brittle diabetes"],
        ["Amitriptyline", "10-25 mg at night up to 75 mg", "Coexistent tension-type headache, insomnia, chronic pain", "Glaucoma, prostatism, cardiac conduction disease"],
        ["Topiramate", "25 mg at night, up to 50-100 mg/day", "Obesity, coexistent epilepsy", "Pregnancy, renal stones, cognitive-demanding work"],
        ["Flunarizine", "5-10 mg at night", "Cost-constrained practice, vestibular migraine", "Depression, obesity, elderly (parkinsonism)"],
        ["Sodium valproate", "500-1000 mg/day", "Coexistent epilepsy in men", "Any woman of childbearing potential, liver disease"],
        ["Candesartan", "8-16 mg PO OD", "Coexistent hypertension, intolerance of beta-blockers", "Pregnancy, hyperkalaemia, renal artery stenosis"],
      ],
    },
  ],
  redFlags: [
    "Thunderclap headache reaching maximum intensity within one minute - subarachnoid haemorrhage until excluded by CT within 6 hours, and by lumbar puncture for xanthochromia after 12 hours if the CT is late or negative.",
    "Headache with fever, neck stiffness or a purpuric rash - bacterial meningitis; give the first dose of ceftriaxone before imaging or lumbar puncture.",
    "New headache after 50 with scalp tenderness, jaw claudication or transient visual loss - giant cell arteritis; start prednisolone 40-60 mg the same day and arrange temporal artery biopsy.",
    "Papilloedema, or headache worse on lying flat, on waking, or with coughing and straining - raised intracranial pressure; image before lumbar puncture.",
    "Headache with any new focal neurological deficit, seizure, personality change or progressive cognitive decline - structural lesion, image urgently.",
    "New or changed headache in an HIV-positive, transplanted or otherwise immunosuppressed patient - cryptococcal meningitis, toxoplasmosis, tuberculoma or lymphoma.",
    "New headache in pregnancy or within 6 weeks of delivery - check blood pressure and urine protein for pre-eclampsia, then consider cerebral venous sinus thrombosis.",
    "Headache with a painful red eye, a fixed mid-dilated pupil and haloes around lights - acute angle-closure glaucoma; same-hour ophthalmology referral.",
  ],
  pearls: [
    "The commonest cause of daily headache in a patient who already had migraine is medication overuse headache - always count analgesic days a month before adding another drug.",
    "The migraineur lies still in a dark room; the cluster patient paces the veranda. Behaviour during the attack is a free diagnostic test.",
    "A triptan plus an NSAID taken together beats either alone, and treating early beats treating hard.",
    "Migraine with aura plus combined oral contraceptives plus smoking is the stroke triad in a young woman - the pill must be stopped, not merely discussed.",
    "Absolute response to indomethacin defines hemicrania continua and paroxysmal hemicrania; give the trial before labelling any strictly unilateral daily headache as chronic migraine.",
    "In suspected giant cell arteritis, steroids are started before the biopsy - the biopsy remains positive for up to two weeks, but sight lost is never regained.",
    "A normal CT scan does not exclude migraine, meningitis, giant cell arteritis, venous sinus thrombosis or idiopathic intracranial hypertension; the history remains the test.",
    "Success in prophylaxis is a halving of headache days recorded in a diary, not the disappearance of headache; say so at the start or the patient will call the drug a failure at week three.",
  ],
  theory: [
    {
      id: "neurology-headache-t1",
      paper: "II",
      kind: "long",
      marks: 10,
      minutes: 20,
      frequency: "core",
      question:
        "A 28-year-old schoolteacher presents with recurrent throbbing headaches for four years, now occurring six times a month and interfering with her work. Describe how you would evaluate her and outline the acute and preventive management of migraine in family practice.",
      openingLines: [
        "Migraine is a chronic disorder of recurrent headache diagnosed by the ICHD-3 criteria - at least five attacks lasting 4-72 hours with two of unilateral, pulsating, moderate to severe or activity-aggravated pain, plus nausea or vomiting or the combination of photophobia and phonophobia.",
        "It affects about 25% of Indian women of this age group, and the objectives here are to make a positive clinical diagnosis, exclude secondary headache by red flags rather than by scanning, treat the acute attack adequately, and start prophylaxis because she has six disabling headache days a month.",
      ],
      answer: [
        {
          heading: "1. History",
          points: [
            "Ask how many distinct types of headache she has and take each separately; then onset, site, character, severity, duration, frequency and headache days per month.",
            "Associated features: nausea, vomiting, photophobia, phonophobia, osmophobia, aura (visual scintillations spreading over minutes and lasting under an hour), prodrome and postdrome.",
            "Behaviour during the attack, effect on work and family (use the MIDAS or HIT-6 score to record disability objectively).",
            "Triggers: sleep deprivation, missed meals, menstruation, stress and the let-down after stress, bright light and travel; relationship to the menstrual cycle.",
            "Drug history is critical: name every analgesic and count the number of days a month she takes one, plus combined oral contraceptive use, and any preventive already tried with dose and duration.",
            "Screen for red flags directly: thunderclap onset, fever, new deficit, seizure, morning headache with vomiting, positional change, pregnancy, immunosuppression, cancer, head injury.",
          ],
        },
        {
          heading: "2. Examination and investigations",
          points: [
            "Blood pressure, temperature, fundus examination for papilloedema, cranial nerves including visual fields, motor and sensory screen, gait, and neck movements; palpate the temporal arteries and the temporomandibular joints and examine the sinuses and teeth.",
            "A completely normal examination with a typical history and no red flags is the strongest evidence against a secondary cause.",
            "Investigations are directed, not routine: haemoglobin, blood sugar and thyroid function if the picture is atypical, refraction assessment if the headache is eye-strain related.",
            "Neuroimaging is indicated only for red flags, an abnormal examination, first or worst headache, a change in an established pattern, or new headache after 50 - not for reassurance.",
          ],
        },
        {
          heading: "3. Explanation and non-drug management",
          points: [
            "Explain migraine as a disorder of a hyperexcitable brain, not a sign of a tumour - explicit reassurance reduces repeat consultation and imaging demand.",
            "Regularise sleep and meal times, ensure hydration, encourage 30 minutes of aerobic exercise most days, and treat coexistent anxiety, depression and neck pain.",
            "Keep a headache diary recording headache days, severity, analgesic days and menstrual relationship - it is both the diagnostic and the outcome tool.",
            "Identify but do not obsess over triggers; avoid long elimination diets.",
          ],
        },
        {
          heading: "4. Acute treatment",
          points: [
            "Treat early at an adequate dose: naproxen 500 mg or ibuprofen 400-600 mg with domperidone 10 mg orally at the first sign.",
            "If this fails, sumatriptan 50-100 mg PO, repeated once after 2 hours if needed, maximum two doses in 24 hours; combine sumatriptan with naproxen for resistant attacks.",
            "Use subcutaneous or intranasal sumatriptan if she vomits early.",
            "Cap acute drug use at fewer than 10 triptan or combination-analgesic days and fewer than 15 simple-analgesic days per month, and record the limit in the notes.",
            "Avoid opioids, tramadol and ergotamine entirely.",
          ],
        },
        {
          heading: "5. Preventive treatment and follow-up",
          points: [
            "She qualifies for prophylaxis: six disabling attacks a month.",
            "Start propranolol 20 mg twice daily and titrate to 80-160 mg a day; alternatives are amitriptyline 10-25 mg at night, topiramate 25-100 mg daily, or flunarizine 5-10 mg at night.",
            "Continue for an adequate trial of 8-12 weeks at target dose before calling it a failure; success is a 50% reduction in headache days.",
            "If she uses combined oral contraceptives and has aura, stop them and switch to a progestogen-only or intrauterine method - WHO MEC category 4.",
            "Review at 4-6 weeks with the diary, treat any medication overuse by withdrawal, and continue a successful preventive for 6-12 months before tapering. Refer if there is diagnostic doubt, failure of two adequate preventives, or chronic migraine needing specialist options such as botulinum toxin or a CGRP monoclonal antibody.",
          ],
        },
      ],
      mustDraw: [
        "A table of the ICHD-3 diagnostic criteria for migraine without aura.",
        "A three-column table comparing migraine, tension-type headache and cluster headache.",
        "A stepwise flow chart: red flag screen, then positive diagnosis, then acute treatment ladder, then prophylaxis threshold.",
      ],
      markSplit: [
        { part: "Definition and ICHD-3 criteria", marks: 2 },
        { part: "History including red flags and analgesic days", marks: 2 },
        { part: "Examination and rational use of imaging", marks: 1 },
        { part: "Acute treatment with drugs and doses", marks: 2.5 },
        { part: "Prophylaxis, contraception and follow-up", marks: 2.5 },
      ],
      keywords: ["migraine", "ICHD-3", "sumatriptan", "propranolol", "medication overuse headache", "MIDAS"],
    },
    {
      id: "neurology-headache-t2",
      paper: "II",
      kind: "short-note",
      marks: 5,
      minutes: 10,
      frequency: "core",
      question: "Write short notes on the red flags in a patient presenting with headache and the investigations each demands.",
      openingLines: [
        "More than 90% of headaches in primary care are primary headaches, but a small group carry serious secondary pathology, and red flags are the clinical filter that identifies them.",
        "The SNNOOP10 list is the currently recommended framework, and each flag maps to a specific diagnosis and a specific first test.",
      ],
      answer: [
        {
          heading: "The red flags and what each suggests",
          points: [
            "Sudden thunderclap onset reaching peak within a minute - subarachnoid haemorrhage, reversible cerebral vasoconstriction syndrome, cervical artery dissection, pituitary apoplexy.",
            "Systemic symptoms - fever, neck stiffness, rash, weight loss - meningitis, encephalitis, brain abscess, malignancy.",
            "Neurological deficit, seizure, altered consciousness or personality change - space-occupying lesion, stroke, encephalitis.",
            "Onset after 50 years with scalp tenderness or jaw claudication - giant cell arteritis; onset in a child with morning vomiting - posterior fossa tumour.",
            "Papilloedema, or headache worsened by lying flat, coughing or straining - raised intracranial pressure, venous sinus thrombosis, idiopathic intracranial hypertension.",
            "Positional headache worse on standing - low cerebrospinal fluid pressure, often post lumbar puncture.",
            "Pregnancy or puerperium - pre-eclampsia, cerebral venous sinus thrombosis, posterior reversible encephalopathy syndrome.",
            "Immunosuppression, HIV or malignancy - opportunistic infection, tuberculoma, metastasis, lymphoma.",
            "Progressive headache or a change in a long-standing pattern; painful red eye with haloes - acute angle-closure glaucoma; analgesic use on more than 15 days a month - medication overuse headache.",
          ],
        },
        {
          heading: "Investigations mapped to the flag",
          points: [
            "Thunderclap headache: non-contrast CT head within 6 hours; if negative and beyond 6 hours, lumbar puncture at 12 hours for xanthochromia, then CT or MR angiography.",
            "Fever with meningism: blood cultures, then the first dose of ceftriaxone, then CT if focal signs or altered sensorium, then lumbar puncture with cell count, protein, glucose, Gram stain, culture, CBNAAT and India ink as indicated.",
            "Suspected giant cell arteritis: ESR and C-reactive protein immediately, prednisolone the same day, temporal artery biopsy within 1-2 weeks.",
            "Raised intracranial pressure: MRI brain with MR venography, then lumbar puncture with opening pressure once a mass is excluded.",
            "Focal deficit or seizure: contrast MRI brain, which is superior to CT for posterior fossa, temporal lobe and small lesions.",
            "Immunosuppression: contrast MRI plus cerebrospinal fluid for India ink, cryptococcal antigen, CBNAAT for tuberculosis and toxoplasma serology.",
          ],
        },
      ],
      mustDraw: ["A two-column table listing each red flag against the diagnosis it suggests and the first investigation."],
      markSplit: [
        { part: "Concept of primary versus secondary headache", marks: 1 },
        { part: "The red flag list", marks: 2 },
        { part: "Investigation matched to each flag", marks: 2 },
      ],
      keywords: ["SNNOOP10", "thunderclap headache", "xanthochromia", "giant cell arteritis", "papilloedema"],
    },
    {
      id: "neurology-headache-t3",
      paper: "II",
      kind: "differentiate",
      marks: 5,
      minutes: 10,
      frequency: "common",
      question: "Differentiate cluster headache from migraine, and outline the management of an acute cluster attack and its prophylaxis.",
      openingLines: [
        "Cluster headache is a trigeminal autonomic cephalalgia characterised by strictly unilateral, excruciating orbital pain lasting 15-180 minutes with ipsilateral cranial autonomic features and marked restlessness.",
        "Migraine is a recurrent throbbing headache lasting 4-72 hours with nausea and photophobia in which the patient prefers to lie still; the two differ in sex ratio, periodicity, duration, behaviour and treatment.",
      ],
      answer: [
        {
          heading: "Points of difference",
          points: [
            "Sex ratio: cluster is 3-4 times commoner in men; migraine is 3 times commoner in women.",
            "Site and character: cluster is strictly unilateral orbital, boring and excruciating; migraine is unilateral in only 60%, pulsating and moderate to severe.",
            "Duration and frequency: cluster lasts 15-180 minutes and recurs up to 8 times a day in bouts lasting weeks, often waking the patient at a fixed hour; migraine lasts 4-72 hours and occurs a few times a month.",
            "Autonomic features: lacrimation, conjunctival injection, rhinorrhoea, ptosis, miosis and eyelid oedema, all ipsilateral, are the hallmark of cluster and are absent or minor in migraine.",
            "Behaviour: cluster patients are restless and pace; migraineurs lie still in a dark room.",
            "Triggers: alcohol reliably triggers an attack during a cluster bout but not in remission; migraine triggers are sleep, hunger, stress and menstruation.",
          ],
        },
        {
          heading: "Acute treatment of cluster",
          points: [
            "High-flow oxygen 12-15 L/min through a non-rebreathing mask for 15-20 minutes, sitting forward - aborts the attack in most patients.",
            "Subcutaneous sumatriptan 6 mg, or intranasal sumatriptan 20 mg or zolmitriptan 5 mg where the injection is unavailable.",
            "Oral analgesics, oral triptans and opioids are useless because they act too slowly.",
          ],
        },
        {
          heading: "Prophylaxis",
          points: [
            "Verapamil 80 mg three times daily, titrated to 240-480 mg a day, with a baseline ECG and repeat ECG after each increment for PR prolongation and heart block - the mainstay of preventive treatment.",
            "Prednisolone 60 mg daily for 5 days then tapered over 2-3 weeks as a bridge until verapamil is effective, or a greater occipital nerve block.",
            "Lithium, topiramate and melatonin are second-line; refer chronic cluster to neurology.",
            "Advise complete abstinence from alcohol and tobacco during a bout, and warn that bouts recur seasonally.",
          ],
        },
      ],
      mustDraw: ["A comparison table of cluster headache and migraine across site, duration, frequency, autonomic features, behaviour and sex ratio."],
      markSplit: [
        { part: "Definitions", marks: 1 },
        { part: "Points of difference in tabular form", marks: 2 },
        { part: "Acute treatment of cluster", marks: 1 },
        { part: "Prophylaxis", marks: 1 },
      ],
      keywords: ["cluster headache", "trigeminal autonomic cephalalgia", "high-flow oxygen", "verapamil", "sumatriptan"],
    },
  ],
  mcqs: [
    {
      id: "neurology-headache-q1",
      stem: "A 34-year-old woman describes headaches on 20 days a month for the last eight months. They began as typical unilateral throbbing headaches with nausea occurring three times a month. She now takes a paracetamol-caffeine-codeine combination tablet on about 18 days a month with temporary relief. Neurological examination is normal. What is the most appropriate next step?",
      options: [
        "Urgent MRI brain with contrast",
        "Withdraw the combination analgesic and start a preventive such as amitriptyline",
        "Increase the analgesic to a regular four-times-daily schedule",
        "Start sumatriptan 100 mg to be taken daily",
        "Refer for botulinum toxin injections",
      ],
      answer: 1,
      explanation:
        "This is medication overuse headache complicating episodic migraine - headache on 15 or more days a month with a combination analgesic used on 10 or more days a month for over 3 months - and the treatment is withdrawal of the overused drug together with a preventive started at the same time, with a warning that headache worsens for one to two weeks. Imaging is not indicated because the examination is normal, there are no red flags and the pattern is fully explained. Increasing the analgesic or adding a daily triptan perpetuates the overuse and is the commonest iatrogenic error here. Botulinum toxin has a role in chronic migraine but only after medication overuse has been treated and oral preventives have failed.",
      difficulty: "moderate",
    },
    {
      id: "neurology-headache-q2",
      stem: "A 46-year-old man develops the worst headache of his life while lifting a sack, reaching maximum intensity in under a minute, with vomiting. He is now alert with a Glasgow Coma Scale of 15, mild neck stiffness and no focal deficit. He reaches the clinic three hours after onset. What is the single most appropriate immediate step?",
      options: [
        "Non-contrast CT scan of the head",
        "Lumbar puncture for xanthochromia",
        "MRI brain with MR venography",
        "Intravenous sumatriptan and observation",
        "Digital subtraction angiography",
      ],
      answer: 0,
      explanation:
        "Thunderclap headache is subarachnoid haemorrhage until proved otherwise, and a non-contrast CT performed within 6 hours of onset by a modern scanner is close to 100% sensitive for subarachnoid blood, so it is both the first and the highest-yield test at three hours. Lumbar puncture is the correct next step only if the CT is negative and is performed at 12 hours or later, because xanthochromia takes that long to develop. MR venography looks for sinus thrombosis, a later consideration once haemorrhage is excluded. A triptan is contraindicated before the cause is known, and digital subtraction angiography is reserved for defining an aneurysm after blood has been demonstrated.",
      difficulty: "easy",
    },
    {
      id: "neurology-headache-q3",
      stem: "A 23-year-old woman with migraine with visual aura twice a month asks for contraception. She smokes five cigarettes a day, has a blood pressure of 118/74 mmHg and a body mass index of 22 kg/m2. Which contraceptive advice is correct?",
      options: [
        "A low-dose combined oral contraceptive pill is acceptable as her blood pressure is normal",
        "A combined pill may be used if she stops smoking",
        "Combined hormonal contraception is contraindicated; offer a progestogen-only method or an intrauterine device",
        "Contraception should be deferred until the migraine is controlled with prophylaxis",
        "A combined transdermal patch avoids the risk associated with oral contraceptives",
      ],
      answer: 2,
      explanation:
        "Migraine with aura is WHO Medical Eligibility Criteria category 4 for combined hormonal contraception at any age and by any route, because oestrogen multiplies the already doubled ischaemic stroke risk of aura, and smoking compounds it further. Normal blood pressure and body mass index do not remove the category 4 restriction, and the patch, ring and pill all deliver oestrogen so switching route changes nothing. Deferring contraception exposes her to unintended pregnancy for no benefit; progestogen-only pills, injectables, implants and both intrauterine devices are category 1 or 2 and are the correct offer, alongside smoking cessation advice.",
      difficulty: "moderate",
    },
    {
      id: "neurology-headache-q4",
      stem: "A 41-year-old male smoker has had 6 weeks of severe left orbital pain waking him at 2 a.m. each night, lasting about 45 minutes, with left eye watering, a blocked left nostril and drooping of the left eyelid. He paces the room during attacks. Between attacks he is well. Which treatment aborts the acute attack most reliably?",
      options: [
        "Oral sumatriptan 100 mg",
        "High-flow oxygen 12-15 L/min by non-rebreathing mask",
        "Intramuscular diclofenac 75 mg",
        "Oral indomethacin 75 mg",
        "Intravenous morphine 5 mg",
      ],
      answer: 1,
      explanation:
        "This is cluster headache, and high-flow oxygen by non-rebreathing mask for 15-20 minutes aborts the attack in the majority of patients within minutes, with subcutaneous sumatriptan 6 mg the other first-line option. Oral sumatriptan is too slow - the attack has often ended before it is absorbed - which is why the subcutaneous or intranasal route is specified. Diclofenac and morphine act far too slowly and opioids risk dependence in a condition with frequent daily attacks. Indomethacin is the diagnostic and therapeutic agent for paroxysmal hemicrania and hemicrania continua, whose attacks are shorter and far more frequent, not for cluster headache.",
      difficulty: "moderate",
    },
    {
      id: "neurology-headache-q5",
      stem: "A 68-year-old woman has a new right temporal headache for three weeks, pain in the jaw while chewing, and a tender, thickened, pulseless right temporal artery. ESR is 82 mm in the first hour. Vision is currently normal. What is the correct immediate action?",
      options: [
        "Arrange temporal artery biopsy and start steroids only if it is positive",
        "Start prednisolone 40-60 mg daily today and arrange temporal artery biopsy within 1-2 weeks",
        "Start naproxen 500 mg twice daily and review in one week",
        "Arrange an urgent MRI brain before any treatment",
        "Start prednisolone 10 mg daily and titrate against the ESR",
      ],
      answer: 1,
      explanation:
        "Giant cell arteritis with jaw claudication and a raised ESR threatens irreversible anterior ischaemic optic neuropathy, so high-dose prednisolone at 40-60 mg daily (1 mg/kg) is started the same day and the biopsy is arranged afterwards, since histology remains positive for one to two weeks after steroids are begun. Waiting for the biopsy risks sudden permanent blindness, which steroids largely prevent. NSAIDs do not modify the arteritis. MRI does not diagnose giant cell arteritis and would only delay treatment. A dose of 10 mg is a polymyalgia rheumatica dose and is inadequate to protect vision in arteritis.",
      difficulty: "easy",
    },
    {
      id: "neurology-headache-q6",
      stem: "A 26-year-old obese woman has a 3-month history of daily headache worse on waking and on coughing, with brief episodes of greying of vision on standing and pulsatile tinnitus. Fundoscopy shows bilateral papilloedema. MRI brain and MR venogram are normal. What is the next investigation?",
      options: [
        "Lumbar puncture with measurement of opening pressure",
        "CT brain with contrast",
        "Visual evoked potentials",
        "Electroencephalogram",
        "Cerebrospinal fluid cytology only",
      ],
      answer: 0,
      explanation:
        "This is idiopathic intracranial hypertension, and once a mass lesion and venous sinus thrombosis have been excluded by MRI and MR venography the diagnosis requires a lumbar puncture demonstrating an opening pressure above 25 cm of water with normal cerebrospinal fluid constituents. Contrast CT adds nothing after a normal MRI. Visual evoked potentials do not measure pressure and formal perimetry is the correct visual test rather than evoked potentials. An electroencephalogram has no role in a patient without seizures, and cytology alone omits the pressure measurement which is the whole point of the tap.",
      difficulty: "moderate",
    },
    {
      id: "neurology-headache-q7",
      stem: "A 30-year-old man with migraine attacks twice a month gets good relief from naproxen but continues to vomit within 30 minutes of onset so that tablets are not retained. He has no cardiovascular disease. Which is the most appropriate change?",
      options: [
        "Add oral domperidone 10 mg and continue oral naproxen",
        "Start subcutaneous sumatriptan 6 mg or intranasal sumatriptan 20 mg for attacks",
        "Start daily propranolol 40 mg twice daily",
        "Prescribe oral tramadol 50 mg for attacks",
        "Prescribe ergotamine with caffeine at onset",
      ],
      answer: 1,
      explanation:
        "Early vomiting defeats the oral route, so a parenteral or intranasal triptan is the logical choice and gives rapid, reliable relief in a man with no vascular contraindication. Adding oral domperidone helps gastric stasis but is still an oral drug that will be vomited in this scenario. Prophylaxis is not indicated for two attacks a month that respond well once absorbed; the problem is route, not frequency. Tramadol and other opioids are less effective and are the leading cause of medication overuse headache, and ergotamine is obsolete because of its vascular toxicity and rebound headache.",
      difficulty: "easy",
    },
  ],
  cards: [
    {
      id: "neurology-headache-c1",
      front: "ICHD-3 criteria for migraine without aura.",
      back: "At least 5 attacks, 4-72 hours untreated, 2 of 4 (unilateral, pulsating, moderate-severe, worse with routine activity), plus nausea or vomiting, or photophobia AND phonophobia.",
    },
    {
      id: "neurology-headache-c2",
      front: "Definition of chronic migraine.",
      back: "Headache on 15 or more days a month for more than 3 months, with migraine features on at least 8 of those days.",
    },
    {
      id: "neurology-headache-c3",
      front: "Diagnostic thresholds for medication overuse headache.",
      back: "Headache 15 or more days a month with regular use for over 3 months of simple analgesics on 15 or more days a month, or triptans, ergots, opioids or combination analgesics on 10 or more days a month.",
    },
    {
      id: "neurology-headache-c4",
      front: "Two first-line treatments for an acute cluster attack.",
      back: "High-flow oxygen 12-15 L/min by non-rebreathing mask for 15-20 minutes, and subcutaneous sumatriptan 6 mg.",
    },
    {
      id: "neurology-headache-c5",
      front: "Sensitivity of non-contrast CT for subarachnoid haemorrhage by time from onset.",
      back: "Close to 100% within 6 hours; it falls steadily after that, so a negative late CT must be followed by lumbar puncture at 12 hours or later for xanthochromia.",
    },
    {
      id: "neurology-headache-c6",
      front: "First-line drug for trigeminal neuralgia and its dose.",
      back: "Carbamazepine 100 mg PO BD titrated to 200 mg TDS-QDS; MRI if under 40, bilateral, with sensory loss or drug-resistant.",
    },
    {
      id: "neurology-headache-c7",
      front: "Which headache responds absolutely to indomethacin?",
      back: "Paroxysmal hemicrania and hemicrania continua - the response is itself diagnostic.",
    },
    {
      id: "neurology-headache-c8",
      front: "Contraceptive rule in migraine with aura.",
      back: "Combined hormonal contraception is WHO MEC category 4 (absolutely contraindicated); use progestogen-only methods, implants or intrauterine devices.",
    },
    {
      id: "neurology-headache-c9",
      front: "Four first-line oral migraine preventives with doses.",
      back: "Propranolol 40-160 mg/day, amitriptyline 10-75 mg at night, topiramate 25-100 mg/day, flunarizine 5-10 mg at night.",
    },
    {
      id: "neurology-headache-c10",
      front: "What counts as success from a migraine preventive, and after how long?",
      back: "A 50% reduction in headache days on a diary, judged after an 8-12 week trial at the target dose.",
    },
    {
      id: "neurology-headache-c11",
      front: "Immediate treatment of suspected giant cell arteritis.",
      back: "Prednisolone 40-60 mg daily at once (IV methylprednisolone if visual loss), then temporal artery biopsy within 1-2 weeks; do not wait for histology.",
    },
    {
      id: "neurology-headache-c12",
      front: "Which triptan contraindications must be checked before prescribing?",
      back: "Ischaemic heart disease, previous MI or stroke, uncontrolled hypertension, peripheral vascular disease, hemiplegic or brainstem-aura migraine, and ergot use within 24 hours.",
    },
  ],
  references: [
    "International Classification of Headache Disorders, 3rd edition (ICHD-3), Cephalalgia 2018",
    "NICE Clinical Guideline CG150, Headaches in over 12s: diagnosis and management, updated 2021",
    "American Headache Society Consensus Statement on integrating new treatments into the acute and preventive treatment of migraine, 2021",
    "Do TP et al., Red and orange flags for secondary headaches (SNNOOP10), Neurology 2019",
    "API Textbook of Medicine, 11th edition, 2019 - headache and facial pain",
  ],
});
