import type { ClinicalCase, Subject, Topic } from "../lib/types";

const topics: Topic[] = [];

topics.push({
  id: "pediatrics-newborn-care",
  title: "Newborn care, danger signs and the sick young infant",
  oneLiner:
    "Essential newborn care is warmth, early exclusive breastfeeding, cord and eye care, vitamin K and weighing, followed by structured home visits that look for seven danger signs, any one of which is possible serious bacterial infection until proved otherwise.",
  frequency: "core",
  keywords: [
    "essential newborn care",
    "ENBC",
    "HBNC",
    "home based newborn care",
    "ASHA",
    "kangaroo mother care",
    "KMC",
    "low birth weight",
    "PSBI",
    "possible serious bacterial infection",
    "neonatal sepsis",
    "delayed cord clamping",
    "vitamin K",
    "NRP",
    "golden minute",
    "hypothermia",
    "exclusive breastfeeding",
    "SNCU",
    "NBCC",
    "Navjaat Shishu Suraksha Karyakram",
  ],
  sections: [
    {
      heading: "The first hour: essential newborn care at birth",
      points: [
        "**Dry the baby thoroughly, remove the wet linen and place the baby skin-to-skin on the mother's abdomen** - drying is both the stimulus for the first breath and the single most effective anti-hypothermia measure, and it must happen within the first 30 seconds.",
        "**Delay cord clamping by 1-3 minutes** in every baby who does not need resuscitation; it raises neonatal haemoglobin and iron stores at 6 months and lowers the need for transfusion in preterm babies. Never milk the cord in a baby under 28 weeks.",
        "Cut the cord with a sterile blade, apply nothing to the stump, and keep it clean, dry and outside the nappy. **Chlorhexidine 7.1% gel (delivering 4% chlorhexidine) is applied once daily for 7 days only where home deliveries and unclean cord practices are common**, which is how the national programme deploys it.",
        "**Initiate breastfeeding within the first hour**; do not give prelacteal feeds of honey, jaggery, gutti or animal milk, and do not wash the mother's nipple before every feed. Colostrum is the first immunisation and must not be discarded.",
        "**Delay the first bath by at least 24 hours** (72 hours in a low birth weight baby); wipe with a warm cloth instead. Bathing at birth is a leading avoidable cause of neonatal hypothermia in Indian labour rooms.",
        "**Vitamin K1 1 mg intramuscularly into the anterolateral thigh as a single dose (0.5 mg if birth weight is under 1000 g)** prevents vitamin K deficiency bleeding, including the late form that presents at 3-8 weeks as intracranial haemorrhage in an exclusively breastfed baby.",
        "Weigh the baby, record the temperature, check for gross congenital malformations, apply the identity band, give the birth-dose vaccines (BCG, OPV-0, hepatitis B within 24 hours) and fill the Mother and Child Protection (MCP) card before discharge.",
      ],
    },
    {
      heading: "Thermal care, kangaroo mother care and the low birth weight baby",
      points: [
        "**Normal axillary temperature is 36.5-37.5 degrees C.** Cold stress is 36.0-36.4, moderate hypothermia 32.0-35.9, and severe hypothermia below 32 degrees C - the last carries very high mortality and needs rapid rewarming with monitoring for hypoglycaemia and bleeding.",
        "The warm chain has ten links: warm delivery room (25-28 degrees C, no draughts), immediate drying, skin-to-skin contact, breastfeeding, delayed bathing and weighing, appropriate clothing including cap and socks, mother and baby together, warm transport, warm resuscitation, and training of all staff.",
        "**Kangaroo mother care means continuous skin-to-skin contact between the mother's bare chest and the naked baby (cap, nappy and socks only), with exclusive breast milk feeding and early discharge with follow-up.** It is offered to every baby under 2000 g who is haemodynamically stable.",
        "**Aim for at least 8 hours of KMC a day, built up towards continuous contact**; WHO 2022 now recommends immediate KMC started at birth even before stabilisation for babies 1000-1799 g, because it reduces mortality by about a quarter.",
        "Feeding by birth weight: over 1800 g and 34 weeks or more, most babies suck directly; 1500-1800 g usually need expressed breast milk by katori-spoon or paladai; under 1200 g or under 30 weeks need gavage feeds and often intravenous fluids first. **Never use a feeding bottle** - it causes nipple confusion and sepsis.",
        "Start feeds at about 60-80 mL/kg/day on day 1 and advance by 15-20 mL/kg/day to 150-180 mL/kg/day, using expressed breast milk; donor milk from a human milk bank (comprehensive lactation management centre) is the next choice, and formula the last.",
        "Give **oral vitamin D 400 IU daily to every infant from birth**, and add elemental iron 2 mg/kg/day from 2 weeks of age (or from 6-8 weeks in stable preterms) in low birth weight babies, continued to 1 year.",
      ],
    },
    {
      heading: "Establishing breastfeeding and fixing the common problems",
      points: [
        "**Exclusive breastfeeding for 6 months, complementary feeding from the completion of 6 months, and continued breastfeeding to 2 years and beyond** is the WHO and MoHFW recommendation; NFHS-5 found only 63.7% of Indian infants under 6 months exclusively breastfed and only 41.8% put to the breast within the first hour.",
        "**The four signs of good attachment:** more areola visible above than below the mouth, mouth wide open, lower lip turned outward, chin touching the breast. Poor attachment is the cause of almost every sore nipple and most of the perceived insufficient milk.",
        "Feed **on demand, 8-12 times in 24 hours including at night**, one breast emptied before offering the second so the baby gets the fat-rich hind milk.",
        "**Adequacy of intake is judged by output and weight, not by how the breast feels:** six or more wet nappies a day after day 4, a settled baby after feeds, weight loss not exceeding 10% of birth weight, and birth weight regained by day 10-14.",
        "For sore or cracked nipples, correct the attachment, express a drop of hind milk onto the nipple after a feed, and continue feeding. For engorgement, feed frequently, apply warm compresses before and cold after, and express to soften the areola. **Neither is a reason to stop breastfeeding.**",
        "**Perceived insufficient milk is the commonest reason Indian mothers add top feeds and the commonest reason exclusive breastfeeding fails.** Manage it by reassurance, correcting attachment, increasing feed frequency and maternal fluids and rest - not by prescribing formula or galactagogues.",
        "Breastfeeding continues in maternal tuberculosis (with the mother on treatment and masked), in hepatitis B (the baby has had the birth dose and immunoglobulin where indicated), and in HIV where the mother is on antiretroviral therapy - **the Indian national policy is exclusive breastfeeding for 6 months in HIV-exposed infants with maternal ART and infant nevirapine prophylaxis**, not avoidance of breastfeeding.",
      ],
    },
    {
      heading: "The seven danger signs and home-based newborn care",
      points: [
        "**The seven danger signs taught to every mother and ASHA are: not feeding well or stopped breastfeeding; convulsions; fast breathing (60 breaths per minute or more); severe chest indrawing; movement only on stimulation or no movement at all; temperature 37.5 degrees C or more, or below 35.5 degrees C; and yellow palms and soles.** Any one of them means refer now.",
        "Additional local signs demanding referral: umbilical redness spreading to the abdominal skin or pus at the stump, more than ten skin pustules or a large boil, bleeding from any site, and a baby who has not passed urine in 24 hours or meconium in 48 hours.",
        "**Home Based Newborn Care (HBNC) visits by the ASHA are on days 1, 3, 7, 14, 21, 28 and 42 for a home delivery, and on days 3, 7, 14, 21, 28 and 42 for an institutional delivery** - six visits after institutional birth, seven after home birth. Low birth weight and sick babies get extra visits.",
        "At each visit the ASHA weighs the baby, takes the temperature, counts the respiratory rate for a full minute, looks for the danger signs, checks the cord and skin, observes a breastfeed, and records everything on the HBNC form; she is paid an incentive on completion of the schedule and a surviving baby at 42 days.",
        "**Home Based Care for Young Child (HBYC) extends this with visits in the 3rd, 6th, 9th, 12th and 15th months**, covering complementary feeding, growth monitoring, immunisation, ORS and zinc, iron-folic acid syrup and early childhood development.",
        "The mother must be counselled that **a newborn does not localise infection**: he does not cough with pneumonia and does not have neck stiffness with meningitis; he simply feeds poorly, becomes cold and stops moving. That is why any one danger sign is enough.",
      ],
    },
    {
      heading: "Possible serious bacterial infection: recognise and treat",
      points: [
        "**PSBI (possible serious bacterial infection) is the IMNCI label for a young infant aged 0-59 days with any danger sign**; it covers sepsis, pneumonia and meningitis, which cannot be separated clinically at this age. Neonatal sepsis contributes about a fifth of India's neonatal deaths.",
        "**Early-onset sepsis (within 72 hours) comes from the mother** - prolonged rupture of membranes over 18 hours, maternal fever, foul liquor, more than three vaginal examinations, unclean delivery, and prematurity - and is usually Klebsiella, Escherichia coli or group B Streptococcus in Indian units.",
        "Late-onset sepsis (after 72 hours) is acquired from the environment or hands and presents with poor feeding, lethargy, apnoea, abdominal distension, sclerema or shock.",
        "**The inpatient regimen is injection ampicillin 50 mg/kg/dose IV plus gentamicin once daily** - ampicillin 12-hourly in the first week of life and 8-hourly thereafter; gentamicin 5 mg/kg/dose once daily if 2000 g or more and 4 mg/kg/dose once daily if under 2000 g. Add or substitute cefotaxime 50 mg/kg/dose 8-12 hourly if meningitis is suspected.",
        "**Duration: 7-10 days for sepsis without meningitis, 14 days for culture-proven sepsis, and 21 days for meningitis.** Gentamicin is usually stopped at 7 days.",
        "**When referral is genuinely refused or impossible, the WHO and national simplified regimen is oral amoxicillin 50 mg/kg/dose twice daily for 7 days plus injection gentamicin 5-7.5 mg/kg intramuscularly once daily for 2 days** (use 5 mg/kg if the baby weighs under 2 kg), with daily review. A 7-59 day old infant with fast breathing as the only sign may be treated with oral amoxicillin alone for 7 days.",
        "Before transport give the first dose of antibiotic, prevent hypoglycaemia with breast milk or expressed milk (or 2 mL/kg of 10% dextrose intravenously if the blood glucose is under 45 mg/dL), keep the baby warm in skin-to-skin contact, and send a written referral note with the mother.",
      ],
    },
    {
      heading: "Neonatal resuscitation: the golden minute",
      points: [
        "About **10% of newborns need some help to start breathing and 1% need extensive resuscitation**; the single question at birth is whether the baby is term, has good tone and is breathing or crying.",
        "**The golden minute:** provide warmth, position the head in a neutral sniffing position, clear the airway only if secretions obstruct, dry, stimulate and reposition - and if the baby is still apnoeic or gasping, or the heart rate is below 100 per minute, start positive pressure ventilation, all within 60 seconds of birth.",
        "**Ventilate at 40-60 breaths per minute with a self-inflating bag and correctly sized mask**, starting with room air in term babies and 21-30% oxygen in preterms. Effective ventilation is confirmed by a rising heart rate, which is the primary indicator of success.",
        "If the heart rate remains below 100 after 15 seconds, run through the corrective steps (mask adjustment, reposition the head, suction, open the mouth, increase pressure, alternative airway) before doing anything else. **Ventilation, not drugs, is the treatment of neonatal bradycardia.**",
        "**Chest compressions start when the heart rate is below 60 per minute after 30 seconds of effective ventilation**, given with the two-thumb encircling technique over the lower third of the sternum, depressing one third of the antero-posterior diameter, at a ratio of 3 compressions to 1 breath - 90 compressions and 30 breaths a minute.",
        "**Adrenaline is 0.01-0.03 mg/kg, that is 0.1-0.3 mL/kg of 1:10,000 solution, intravenously or by umbilical venous catheter, repeated every 3-5 minutes**; the endotracheal dose is higher at 0.05-0.1 mg/kg. For suspected hypovolaemia or blood loss give normal saline or Ringer lactate 10 mL/kg over 5-10 minutes.",
        "**Meconium-stained liquor in a non-vigorous baby is no longer an indication for routine endotracheal suction** - start ventilation instead. Navjaat Shishu Suraksha Karyakram (NSSK) is the national training programme that teaches exactly this sequence to every delivery-point provider.",
      ],
    },
    {
      heading: "Routine screening, follow-up and the newborn care continuum",
      points: [
        "**Screen every newborn before discharge** for congenital hypothyroidism (thyroid-stimulating hormone after 48-72 hours), congenital heart disease by pre- and post-ductal pulse oximetry, hearing by otoacoustic emissions, and the red reflex for congenital cataract - the four screens RBSK expects at the delivery point.",
        "**Do not discharge before 48 hours after a normal vaginal delivery**, and only after a successful breastfeed has been observed, the baby has passed urine and stool, weight and temperature are recorded, birth-dose vaccines are given and the danger signs have been taught to the family.",
        "The newborn care continuum in the public system runs from the **Newborn Care Corner in every labour room, to the Newborn Stabilisation Unit at first referral units, to the Special Newborn Care Unit at district hospitals**, with follow-up of every SNCU graduate at 3, 6, 9 and 12 months.",
        "Check for hip dysplasia (Ortolani and Barlow), a patent anus, femoral pulses, the palate, the eyes and the spine at the discharge examination; a missed coarctation and a missed developmental dysplasia of the hip are classic examiner questions.",
        "**Follow up every low birth weight or preterm graduate for growth, retinopathy of prematurity screening (first screen at 4 weeks of age or 30-31 weeks corrected, whichever is earlier, for babies under 34 weeks or under 2000 g), hearing, and development using corrected age until 2 years.**",
        "Register the birth, issue the MCP card, enrol the mother in the appropriate maternity benefit scheme, and fix a written date for the 6-week visit at which the pentavalent vaccine, the mother's contraception and the baby's growth are all addressed together.",
      ],
    },
  ],
  tables: [
    {
      heading: "Danger signs in a young infant (0-59 days) and the action they demand",
      columns: ["Sign", "How it is elicited", "Action"],
      rows: [
        ["Not feeding well or stopped breastfeeding", "Ask the mother; observe a feed for attachment and suck", "PSBI - first dose antibiotic and refer"],
        ["Convulsions", "History or observed; look for subtle seizures (lip smacking, cycling, apnoea)", "Refer; treat hypoglycaemia; phenobarbitone 20 mg/kg IV loading at the facility"],
        ["Fast breathing 60/min or more", "Count for a full 60 seconds, repeat once if borderline", "PSBI - refer; oral amoxicillin alone if 7-59 days and this is the only sign and referral fails"],
        ["Severe chest indrawing", "Lower chest wall drawing in on inspiration, in a calm baby", "PSBI - refer urgently"],
        ["Movement only on stimulation, or none", "Watch the undressed baby for spontaneous movement", "PSBI - refer urgently"],
        ["Temperature 37.5 C or more, or below 35.5 C", "Axillary thermometer for 3 minutes", "Warm or cool, treat as PSBI and refer"],
        ["Yellow palms and soles, or jaundice on day 1", "Blanch the skin in daylight (Kramer zones)", "Measure bilirubin; refer for phototherapy"],
      ],
    },
    {
      heading: "Antibiotic doses in the young infant",
      columns: ["Drug", "Dose", "Frequency", "Note"],
      rows: [
        ["Ampicillin", "50 mg/kg/dose IV or IM", "12-hourly under 7 days, 8-hourly over 7 days", "First-line with gentamicin; 100 mg/kg/dose if meningitis"],
        ["Gentamicin (2000 g or more)", "5 mg/kg/dose IV or IM", "Once daily", "Monitor urine output; avoid with other nephrotoxics"],
        ["Gentamicin (under 2000 g)", "4 mg/kg/dose IV or IM", "Once daily", "Longer interval if under 1200 g or under 30 weeks"],
        ["Cefotaxime", "50 mg/kg/dose IV", "8-12 hourly", "Add when meningitis is suspected; not a substitute for gentamicin alone"],
        ["Amoxicillin (simplified outpatient PSBI)", "50 mg/kg/dose orally", "Twice daily for 7 days", "With IM gentamicin for 2 days when referral is not possible"],
        ["Gentamicin (simplified outpatient PSBI)", "5-7.5 mg/kg IM (5 mg/kg if under 2 kg)", "Once daily for 2 days", "Daily review by a trained provider is mandatory"],
      ],
    },
    {
      heading: "HBNC visit schedule and what is done",
      columns: ["Visit day", "Home delivery", "Institutional delivery", "Key task"],
      rows: [
        ["Day 1", "Yes", "No (baby in facility)", "Weight, temperature, first breastfeed, cord care"],
        ["Day 3", "Yes", "Yes", "Weight, feeding assessment, danger signs, jaundice check"],
        ["Day 7", "Yes", "Yes", "Weight (birth weight regained?), cord separation, danger signs"],
        ["Day 14", "Yes", "Yes", "Weight gain, exclusive breastfeeding reinforcement"],
        ["Day 21", "Yes", "Yes", "Growth, danger signs, family planning discussion"],
        ["Day 28", "Yes", "Yes", "Growth, immunisation due at 6 weeks explained"],
        ["Day 42", "Yes", "Yes", "Final weight, mother's health, contraception, registration"],
      ],
    },
  ],
  redFlags: [
    "Any one of the seven danger signs in a baby under 2 months - treat as possible serious bacterial infection, give the first dose of antibiotic and refer the same hour.",
    "Axillary temperature below 35.5 degrees C, or a baby who feels cold to the touch on the abdomen - hypothermia carries a mortality comparable to sepsis and often coexists with it.",
    "Jaundice appearing in the first 24 hours of life, or reaching the palms and soles at any age - haemolytic disease until proved otherwise, measure bilirubin urgently.",
    "Umbilical redness extending on to the abdominal wall, or pus discharge from the stump - omphalitis, which tracks to portal vein and peritoneum within hours.",
    "Bilious (green) vomiting, abdominal distension, or failure to pass meconium within 48 hours - surgical obstruction, keep nil by mouth, pass a nasogastric tube and refer.",
    "Central cyanosis, or a pre- to post-ductal saturation difference of more than 3%, or a saturation under 90% - duct-dependent congenital heart disease, refer to a centre with paediatric cardiology.",
    "A baby who has not regained birth weight by day 14, or has lost more than 10% of birth weight - assess the feed directly before blaming the milk supply.",
  ],
  pearls: [
    "A newborn does not localise infection: no cough with pneumonia, no neck stiffness with meningitis. Poor feeding, lethargy and hypothermia are the presentation, and any one of them is enough to act on.",
    "Drying and skin-to-skin contact in the first 30 seconds prevent more neonatal deaths than any drug in the labour room.",
    "Effective bag-and-mask ventilation is the treatment of neonatal bradycardia; adrenaline is what you reach for only after 30 seconds of good ventilation and 45-60 seconds of compressions have failed.",
    "Delayed cord clamping for 1-3 minutes is free, needs no equipment, and raises the infant's haemoglobin at 6 months - it should be recorded in every delivery note.",
    "Vitamin K 1 mg intramuscularly once at birth prevents late vitamin K deficiency bleeding, which presents at 3-8 weeks as intracranial haemorrhage in a well, exclusively breastfed baby.",
    "Never bottle-feed a low birth weight baby: use katori and spoon or paladai, which avoid nipple confusion and are easier to clean.",
    "Weight loss up to 10% by day 3-5 is physiological; failure to regain birth weight by day 14 is not, and the answer is almost always attachment, not milk volume.",
    "Kangaroo mother care is a treatment, not a comfort measure: at least 8 hours a day in a baby under 2000 g cuts mortality, infection and hypothermia, and shortens hospital stay.",
    "The commonest reason exclusive breastfeeding fails in India is perceived insufficient milk; the commonest correct response is to observe a feed and fix the attachment.",
  ],
  theory: [
    {
      id: "pediatrics-newborn-care-t1",
      paper: "IV",
      kind: "long",
      marks: 10,
      minutes: 20,
      frequency: "core",
      question:
        "A 5-day-old exclusively breastfed baby, born at term at home and weighing 2.4 kg at birth, is brought by the mother because he has stopped sucking since the morning and feels cold. Describe your assessment and management at a primary health centre.",
      openingLines: [
        "This baby has at least two danger signs - not feeding well and probable hypothermia - and in the IMNCI framework any single danger sign in a young infant aged 0-59 days is classified as possible serious bacterial infection (PSBI), which mandates the first dose of antibiotic and urgent referral.",
        "The priorities in order are: keep him warm, prevent and treat hypoglycaemia, give the first dose of parenteral antibiotics, and arrange safe warm transport with the mother accompanying him.",
      ],
      answer: [
        {
          heading: "1. Rapid assessment at the door",
          points: [
            "Take the axillary temperature for 3 minutes: below 36.5 is cold stress, below 35.5 is hypothermia, below 32 is severe hypothermia.",
            "Count the respiratory rate for a full minute (60 per minute or more is fast), look for severe chest indrawing, grunting and apnoea.",
            "Observe spontaneous movement in the undressed baby, check the level of consciousness, the anterior fontanelle, and look for convulsions including subtle seizures such as lip smacking, cycling or apnoea.",
            "Examine the umbilicus for redness or pus, the skin for pustules or sclerema, and the palms and soles for jaundice; check capillary refill and the femoral pulses.",
            "Check the blood glucose by glucometer if available - hypoglycaemia (under 45 mg/dL) is both a consequence of sepsis and an independent cause of the poor feeding.",
          ],
        },
        {
          heading: "2. Focused history",
          points: [
            "Birth history: home delivery, who conducted it, cleanliness of the delivery, cord practices and anything applied to the stump.",
            "Maternal risk factors for early-onset sepsis: fever, foul-smelling liquor, rupture of membranes for more than 18 hours, repeated vaginal examinations, urinary infection in the last trimester.",
            "Feeding history: when the last good feed was, whether prelacteal or top feeds were given, the number of wet nappies, and whether the baby has passed urine in the last 24 hours.",
            "Immunisation and vitamin K status - a home delivery often means neither BCG, OPV-0, hepatitis B nor vitamin K was given.",
          ],
        },
        {
          heading: "3. Immediate stabilisation before referral",
          points: [
            "**Warm the baby by continuous skin-to-skin kangaroo contact under a blanket with a cap**, or under a radiant warmer if available; recheck the temperature every 15-30 minutes and aim for a rise of 0.5 degrees C per hour.",
            "**Prevent hypoglycaemia:** if the baby can suck, put him to the breast; if not, give expressed breast milk 5-10 mL by katori-spoon or nasogastric tube. If the blood glucose is under 45 mg/dL or he is unconscious, give **2 mL/kg of 10% dextrose intravenously as a bolus followed by an infusion at 6 mg/kg/min**.",
            "**Give the first dose of antibiotics before transport: injection ampicillin 50 mg/kg (about 120 mg) intravenously or intramuscularly, plus injection gentamicin 5 mg/kg (about 12 mg) intramuscularly once daily.**",
            "Give vitamin K1 1 mg intramuscularly if it was not given at birth, and treat the umbilical sepsis locally.",
            "Do not bathe, do not give oral fluids other than milk, and do not delay transport for investigations that will not change the next hour.",
          ],
        },
        {
          heading: "4. Referral and transport",
          points: [
            "Refer to the nearest Special Newborn Care Unit; arrange free transport under the national ambulance service and counsel the family on the free entitlements for sick newborns under 1 year.",
            "**Transport the baby in continuous skin-to-skin contact with the mother**, encouraging feeding on the way if the baby is able to suck.",
            "Send a written referral note stating the danger signs found, the temperature, the blood glucose, and the exact dose and time of the antibiotics given.",
            "Explain the diagnosis honestly and the reason for referral; refusal of referral is common and is where the simplified outpatient regimen becomes relevant.",
          ],
        },
        {
          heading: "5. If referral is refused or impossible",
          points: [
            "Use the WHO and national simplified regimen: **oral amoxicillin 50 mg/kg/dose twice daily for 7 days plus injection gentamicin 5-7.5 mg/kg intramuscularly once daily for 2 days** (5 mg/kg if the baby weighs under 2 kg).",
            "Review the baby daily for the first 3 days and then on days 5 and 7; deterioration or the appearance of any new danger sign means referral must be renegotiated.",
            "Continue kangaroo care, exclusive breastfeeding and temperature monitoring at home, and teach the mother the seven danger signs explicitly.",
          ],
        },
        {
          heading: "6. Prevention for the next pregnancy and this family",
          points: [
            "Counsel on institutional delivery, the birth-dose vaccines, vitamin K and clean cord care with 7.1% chlorhexidine gel where home delivery is likely.",
            "Enrol the baby in the HBNC visit schedule and the mother in postnatal care and contraception.",
            "Explain that the seven danger signs are the family's own screening tool between visits, and write them on the MCP card in the local language.",
          ],
        },
      ],
      mustDraw: [
        "A table of the seven danger signs of a young infant against the action each demands.",
        "A flow chart: danger sign present - warm, sugar, first-dose antibiotic, refer; referral refused - simplified oral amoxicillin plus IM gentamicin regimen with daily review.",
      ],
      markSplit: [
        { part: "Recognition of PSBI and the danger signs", marks: 2 },
        { part: "History and examination including maternal risk factors", marks: 2 },
        { part: "Warmth, glucose and first-dose antibiotic with correct doses", marks: 3 },
        { part: "Referral, transport and communication", marks: 1.5 },
        { part: "Simplified regimen when referral fails, and prevention", marks: 1.5 },
      ],
      keywords: ["PSBI", "danger signs", "neonatal sepsis", "hypothermia", "ampicillin gentamicin", "kangaroo mother care"],
    },
    {
      id: "pediatrics-newborn-care-t2",
      paper: "IV",
      kind: "short-note",
      marks: 5,
      minutes: 10,
      frequency: "core",
      question: "Write short notes on kangaroo mother care: definition, eligibility, components, method and evidence of benefit.",
      openingLines: [
        "Kangaroo mother care is the practice of continuous skin-to-skin contact between the mother's bare chest and her naked low birth weight baby, combined with exclusive breast milk feeding and early discharge with structured follow-up.",
        "It is a proven mortality-reducing intervention for babies under 2000 g and is a core component of India's facility-based and home-based newborn care programmes.",
      ],
      answer: [
        {
          heading: "Eligibility",
          points: [
            "All babies with birth weight under 2000 g who are haemodynamically stable, once the mother is willing and able.",
            "WHO 2022 recommends immediate KMC from birth, before clinical stabilisation, for babies weighing 1000-1799 g, as this reduces neonatal mortality by about 25%.",
            "Babies on nasal CPAP or intravenous fluids can receive KMC provided they are not in shock or requiring mechanical ventilation.",
            "The mother is the first provider; the father, grandmother or any consenting adult can give KMC when she is unable.",
          ],
        },
        {
          heading: "The three components",
          points: [
            "**Kangaroo position:** the naked baby, wearing only a cap, nappy and socks, placed prone and upright between the mother's breasts, head turned to one side, hips flexed and abducted in a frog position, secured by a binder or dupatta, with the mother's clothes wrapped over.",
            "**Kangaroo nutrition:** exclusive breast milk, directly or as expressed milk by katori-spoon or gavage, with feeding possible in the kangaroo position itself.",
            "**Kangaroo support and discharge:** counselling, family involvement, early discharge when the baby is feeding well and gaining weight, and structured follow-up.",
          ],
        },
        {
          heading: "Method and duration",
          points: [
            "Start with sessions of at least 60 minutes - shorter sessions cause more handling stress than they are worth - and build up.",
            "**Aim for at least 8 hours a day, working towards near-continuous contact including at night**, with the mother sleeping propped up at 15-30 degrees.",
            "Continue until the baby reaches about 2500 g or 40 weeks corrected age, or until the baby wriggles out and objects, which is the practical end point.",
            "Monitor temperature, feeding and weight gain; a gain of 15-20 g/kg/day is the target while the baby is under 2000 g.",
          ],
        },
        {
          heading: "Evidence of benefit",
          points: [
            "Reduces neonatal mortality, severe infection and sepsis, hypothermia and hospital readmission; improves weight, length and head circumference gain.",
            "Improves exclusive breastfeeding rates at discharge and at 1-3 months, and reduces maternal anxiety and depression.",
            "Shortens hospital stay and reduces cost - the reason it is a programme intervention and not only a ward practice.",
          ],
        },
      ],
      mustDraw: ["A labelled diagram of the kangaroo position showing the frog posture, head turned to one side, cap, and the supporting binder."],
      markSplit: [
        { part: "Definition and eligibility", marks: 1 },
        { part: "The three components", marks: 1.5 },
        { part: "Method, duration and monitoring", marks: 1.5 },
        { part: "Evidence of benefit", marks: 1 },
      ],
      keywords: ["kangaroo mother care", "low birth weight", "skin-to-skin", "WHO 2022", "immediate KMC"],
    },
    {
      id: "pediatrics-newborn-care-t3",
      paper: "IV",
      kind: "chart-flow",
      marks: 5,
      minutes: 10,
      frequency: "common",
      question: "Draw and explain the neonatal resuscitation algorithm as taught under Navjaat Shishu Suraksha Karyakram, up to the point of chest compressions and drugs.",
      openingLines: [
        "About 10% of newborn babies need some assistance to begin breathing at birth and about 1% need extensive resuscitation; the interventions are simple, and the first 60 seconds decide the outcome.",
        "The three questions at birth are: is the baby term, does the baby have good tone, and is the baby breathing or crying - a yes to all three means routine care in skin-to-skin contact with the mother.",
      ],
      answer: [
        {
          heading: "Initial steps (the golden minute)",
          points: [
            "Provide warmth under a radiant warmer, position the head in a neutral sniffing position, clear the airway only if secretions obstruct (mouth before nose), dry thoroughly, remove wet linen and stimulate by rubbing the back or flicking the soles.",
            "Reassess breathing and heart rate: if the baby is apnoeic or gasping, or the heart rate is below 100 per minute, **start positive pressure ventilation within 60 seconds of birth**.",
            "Meconium-stained liquor in a non-vigorous baby no longer calls for routine endotracheal suctioning - proceed to ventilation.",
          ],
        },
        {
          heading: "Positive pressure ventilation",
          points: [
            "Use a self-inflating bag of 240-500 mL with an appropriately sized mask covering the chin, mouth and nose but not the eyes.",
            "**Ventilate at 40-60 breaths per minute**, starting with room air in term babies and 21-30% oxygen in preterm babies, with an initial inflation pressure of about 20-25 cm H2O.",
            "**A rising heart rate is the primary indicator of effective ventilation.** If the heart rate is not rising after 15 seconds, run the corrective steps: mask adjustment, reposition the airway, suction, open the mouth, increase pressure, alternative airway.",
          ],
        },
        {
          heading: "Chest compressions",
          points: [
            "Start if the heart rate remains **below 60 per minute after 30 seconds of effective ventilation** (chest rising).",
            "Two-thumb encircling technique over the lower third of the sternum, depth one third of the antero-posterior diameter of the chest.",
            "**Ratio 3 compressions to 1 breath, giving 90 compressions and 30 breaths per minute**; increase oxygen to 100% once compressions begin, and reassess after 60 seconds.",
          ],
        },
        {
          heading: "Drugs and volume",
          points: [
            "**Adrenaline 0.01-0.03 mg/kg, that is 0.1-0.3 mL/kg of 1:10,000 solution, intravenously or through an umbilical venous catheter, repeated every 3-5 minutes** while the heart rate stays below 60.",
            "The endotracheal route is a stop-gap at a higher dose of 0.05-0.1 mg/kg (0.5-1 mL/kg of 1:10,000) while vascular access is obtained.",
            "**Volume expansion with normal saline or Ringer lactate 10 mL/kg over 5-10 minutes** if there is a history of blood loss or the baby is pale and shocked with a poor response.",
            "Sodium bicarbonate, naloxone and routine atropine have no place in delivery-room resuscitation.",
          ],
        },
        {
          heading: "After resuscitation",
          points: [
            "Monitor temperature, blood glucose and saturation; a baby who needed prolonged resuscitation needs SNCU care and assessment for hypoxic ischaemic encephalopathy.",
            "Discontinuation is considered after 20 minutes of adequate resuscitation with no detectable heart rate, after discussion with the family.",
          ],
        },
      ],
      mustDraw: [
        "The NRP flow chart: three questions at birth - initial steps - PPV - heart rate check at 60 seconds - compressions at HR under 60 - adrenaline, with the time markers written alongside.",
      ],
      markSplit: [
        { part: "The three questions and initial steps within the golden minute", marks: 1.5 },
        { part: "PPV technique, rate and corrective steps", marks: 1.5 },
        { part: "Chest compressions: indication, technique and ratio", marks: 1 },
        { part: "Adrenaline and volume with correct doses", marks: 1 },
      ],
      keywords: ["NSSK", "golden minute", "bag and mask", "3:1 ratio", "adrenaline 1:10000"],
    },
  ],
  mcqs: [
    {
      id: "pediatrics-newborn-care-q1",
      stem: "A 12-day-old baby, born at term weighing 2.8 kg, is brought with poor feeding for one day. Axillary temperature is 35.2 degrees C, respiratory rate 54 per minute, and he moves only when stimulated. Referral will take two hours. What must be done first at the health centre?",
      options: [
        "Send blood culture and C-reactive protein before any treatment",
        "Warm the baby by skin-to-skin contact, check and correct blood glucose, and give the first dose of ampicillin and gentamicin",
        "Give oral amoxicillin and review the next day",
        "Start intravenous fluids at maintenance and observe for six hours",
        "Give paracetamol and reassess the temperature in one hour",
      ],
      answer: 1,
      explanation:
        "Hypothermia, poor feeding and movement only on stimulation are three danger signs, so this is possible serious bacterial infection; warmth, euglycaemia and a first parenteral antibiotic dose before transport are the interventions that change outcome. Waiting for culture and C-reactive protein delays treatment and neither result will be available in time. Oral amoxicillin alone with next-day review is the simplified regimen only when referral is genuinely impossible and never in a baby with multiple danger signs. Intravenous maintenance fluids treat neither the hypothermia nor the infection, and paracetamol is meaningless in a hypothermic baby.",
      difficulty: "easy",
    },
    {
      id: "pediatrics-newborn-care-q2",
      stem: "A term baby is delivered limp and apnoeic. After 30 seconds of effective positive pressure ventilation with visible chest rise, the heart rate is 48 per minute. What is the next step?",
      options: [
        "Give adrenaline 0.1 mL/kg of 1:10,000 through an umbilical venous catheter",
        "Intubate and give surfactant",
        "Start chest compressions at a ratio of 3 compressions to 1 breath, with 100% oxygen",
        "Give normal saline 10 mL/kg over 5 minutes",
        "Continue ventilation alone for another 60 seconds and reassess",
      ],
      answer: 2,
      explanation:
        "A heart rate below 60 per minute after 30 seconds of demonstrably effective ventilation is the trigger for chest compressions, coordinated 3:1 with ventilation at 90 compressions and 30 breaths per minute, and oxygen is increased to 100% at this point. Adrenaline comes only after about 60 seconds of coordinated compressions and ventilation have failed to lift the heart rate above 60. Surfactant is not a resuscitation drug and this baby is term. Volume expansion is for suspected blood loss or shock unresponsive to the above, and simply continuing ventilation wastes the window in which compressions are indicated.",
      difficulty: "moderate",
    },
    {
      id: "pediatrics-newborn-care-q3",
      stem: "A mother of a 3-week-old exclusively breastfed baby says she has 'no milk'. The baby weighs 3.4 kg, was 3.2 kg at birth, passes seven wet nappies a day and settles after feeds. What is the correct advice?",
      options: [
        "Add 60 mL of infant formula after every breastfeed",
        "Start the mother on a galactagogue and review in a week",
        "Reassure, observe a feed to confirm attachment, and continue exclusive breastfeeding with more frequent feeds",
        "Advise expressing and measuring the milk volume for 24 hours to prove adequacy",
        "Advise switching to both breasts at every feed at 5-minute intervals",
      ],
      answer: 2,
      explanation:
        "Weight above birth weight at three weeks, six or more wet nappies daily and a settled baby are objective evidence of adequate intake, so this is perceived rather than real insufficient milk, and the intervention is reassurance plus a directly observed feed. Formula top-ups reduce suckling, reduce supply and are the commonest way exclusive breastfeeding is lost. Galactagogues have weak evidence and treat a problem that does not exist here. Measuring expressed volume underestimates what the baby extracts and increases anxiety, and switching breasts every five minutes deprives the baby of the fat-rich hind milk.",
      difficulty: "easy",
    },
    {
      id: "pediatrics-newborn-care-q4",
      stem: "A 1.6 kg baby born at 33 weeks is stable on day 3, tolerating expressed breast milk by katori-spoon in a facility with no incubator. Which intervention has the strongest evidence for reducing mortality in this baby?",
      options: [
        "Prophylactic oral antibiotics for the first week",
        "Continuous kangaroo mother care for at least 8 hours a day",
        "Routine intravenous fluids until the baby reaches 1800 g",
        "Formula supplementation to accelerate weight gain",
        "Daily vitamin A supplementation",
      ],
      answer: 1,
      explanation:
        "Kangaroo mother care in babies under 2000 g reduces mortality, sepsis and hypothermia and improves breastfeeding and growth, and WHO now recommends starting it immediately after birth for babies of 1000-1799 g. Prophylactic antibiotics in a well baby select resistant organisms without benefit. Intravenous fluids in a baby already tolerating enteral feeds add line sepsis risk and delay full feeds. Formula is inferior to expressed breast milk and increases necrotising enterocolitis, and routine neonatal vitamin A has not shown a mortality benefit in this setting.",
      difficulty: "moderate",
    },
    {
      id: "pediatrics-newborn-care-q5",
      stem: "A well 6-week-old exclusively breastfed baby, born at home, presents with sudden vomiting, a bulging fontanelle and a falling level of consciousness. He received no injections at birth. Coagulation studies show a markedly prolonged prothrombin time with a normal platelet count. What is the most likely diagnosis?",
      options: [
        "Late vitamin K deficiency bleeding with intracranial haemorrhage",
        "Neonatal sepsis with disseminated intravascular coagulation",
        "Haemophilia A",
        "Immune thrombocytopenia of the newborn",
        "Inherited factor XIII deficiency",
      ],
      answer: 0,
      explanation:
        "A previously well, exclusively breastfed baby of 3-8 weeks who never received vitamin K, presenting with intracranial bleeding and an isolated prolongation of clotting times with a normal platelet count, has classical late vitamin K deficiency bleeding - the exact event 1 mg of intramuscular vitamin K at birth prevents. Disseminated intravascular coagulation would consume platelets and fibrinogen and occurs in a septic, unwell baby, not a well one. Haemophilia prolongs the activated partial thromboplastin time selectively and rarely bleeds intracranially without trauma at this age. Immune thrombocytopenia would show a low platelet count, and factor XIII deficiency characteristically has normal routine coagulation tests.",
      difficulty: "moderate",
    },
    {
      id: "pediatrics-newborn-care-q6",
      stem: "During a home visit on day 3 after an institutional delivery, the ASHA finds a baby with respiratory rate 64 per minute counted twice, no chest indrawing, normal temperature, feeding well and moving normally. What is the correct classification and action?",
      options: [
        "Normal for a newborn; reassure and revisit on day 7",
        "Possible serious bacterial infection; refer urgently after the first dose of antibiotic",
        "Give oral amoxicillin at home for 7 days without referral",
        "Advise steam inhalation and review in 24 hours",
        "Classify as low weight for age and counsel on feeding only",
      ],
      answer: 1,
      explanation:
        "A respiratory rate of 60 per minute or more in a young infant, confirmed on a repeat count, is a danger sign in its own right and is classified as possible serious bacterial infection requiring a first dose of antibiotic and urgent referral. It is not a normal finding, and treating with amoxicillin at home is permitted only for a 7-59 day old infant in whom fast breathing is the sole sign and referral is genuinely not possible - this baby is 3 days old, outside that window. Steam inhalation has no role, and reclassifying to a nutritional problem ignores a danger sign.",
      difficulty: "moderate",
    },
    {
      id: "pediatrics-newborn-care-q7",
      stem: "Which single measure at the moment of birth is most effective at preventing hypothermia in a term baby delivered in a district hospital labour room?",
      options: [
        "Bathing the baby in warm water and dressing immediately",
        "Placing the baby under a radiant warmer for 30 minutes before handing over",
        "Immediate thorough drying, removal of the wet linen and skin-to-skin contact with the mother",
        "Wrapping the baby in three layers of cotton cloth without drying",
        "Raising the labour room temperature to 30 degrees C",
      ],
      answer: 2,
      explanation:
        "Evaporative heat loss from a wet newborn is by far the largest, so drying within 30 seconds, discarding the wet cloth and placing the baby skin-to-skin gives warmth, promotes early breastfeeding and needs no equipment. Bathing at birth actively causes hypothermia and is deferred for at least 24 hours. A radiant warmer is useful when resuscitation is needed but separates mother and baby and is not superior to skin-to-skin for a well term baby. Wrapping without drying traps a wet baby in wet cloth, and while a room at 25-28 degrees C is recommended, ambient temperature alone does not prevent evaporative loss.",
      difficulty: "easy",
    },
  ],
  cards: [
    { id: "pediatrics-newborn-care-c1", front: "The seven danger signs in a young infant", back: "Not feeding well or stopped breastfeeding; convulsions; fast breathing 60/min or more; severe chest indrawing; movement only on stimulation or none; temperature 37.5 C or more or below 35.5 C; yellow palms and soles." },
    { id: "pediatrics-newborn-care-c2", front: "Vitamin K at birth: dose and route", back: "1 mg intramuscularly into the anterolateral thigh, single dose (0.5 mg if birth weight under 1000 g). Prevents classical and late vitamin K deficiency bleeding." },
    { id: "pediatrics-newborn-care-c3", front: "Normal newborn axillary temperature and the hypothermia grades", back: "Normal 36.5-37.5 C; cold stress 36.0-36.4; moderate hypothermia 32.0-35.9; severe hypothermia below 32 C." },
    { id: "pediatrics-newborn-care-c4", front: "First-line inpatient antibiotics for neonatal sepsis", back: "Ampicillin 50 mg/kg/dose IV (12-hourly under 7 days, 8-hourly over 7 days) plus gentamicin once daily - 5 mg/kg if 2000 g or more, 4 mg/kg if under 2000 g." },
    { id: "pediatrics-newborn-care-c5", front: "Simplified outpatient PSBI regimen when referral is not possible", back: "Oral amoxicillin 50 mg/kg/dose twice daily for 7 days plus IM gentamicin 5-7.5 mg/kg once daily for 2 days (5 mg/kg if under 2 kg), with daily review." },
    { id: "pediatrics-newborn-care-c6", front: "HBNC visit days", back: "Home delivery: days 1, 3, 7, 14, 21, 28 and 42 (seven visits). Institutional delivery: days 3, 7, 14, 21, 28 and 42 (six visits)." },
    { id: "pediatrics-newborn-care-c7", front: "When do chest compressions start in newborn resuscitation, and at what ratio?", back: "Heart rate below 60/min after 30 seconds of effective positive pressure ventilation. Ratio 3:1 - 90 compressions and 30 breaths per minute, two-thumb technique." },
    { id: "pediatrics-newborn-care-c8", front: "Adrenaline dose in neonatal resuscitation", back: "0.01-0.03 mg/kg = 0.1-0.3 mL/kg of 1:10,000 IV or by umbilical venous catheter, every 3-5 minutes. Endotracheal dose is higher: 0.05-0.1 mg/kg." },
    { id: "pediatrics-newborn-care-c9", front: "The four signs of good attachment at the breast", back: "More areola above than below the mouth; mouth wide open; lower lip turned outward; chin touching the breast." },
    { id: "pediatrics-newborn-care-c10", front: "Acceptable weight loss after birth, and when birth weight should be regained", back: "Up to 10% of birth weight by day 3-5; birth weight regained by day 10-14. Failure to regain by day 14 needs a directly observed feed." },
    { id: "pediatrics-newborn-care-c11", front: "Kangaroo mother care: who and how much", back: "Every stable baby under 2000 g; naked baby in cap, nappy and socks, prone and upright between the mother's breasts; at least 8 hours a day, building to continuous. WHO 2022 advises immediate KMC for 1000-1799 g." },
    { id: "pediatrics-newborn-care-c12", front: "Neonatal hypoglycaemia: threshold and treatment", back: "Blood glucose under 45 mg/dL. Give expressed breast milk if able to feed; otherwise 2 mL/kg of 10% dextrose IV bolus followed by an infusion at 6 mg/kg/min." },
    { id: "pediatrics-newborn-care-c13", front: "Why delay cord clamping, and for how long?", back: "1-3 minutes in every baby not needing resuscitation - it raises neonatal haemoglobin and iron stores at 6 months and reduces transfusion in preterms." },
  ],
  references: [
    "Facility Based Newborn Care Operational Guidelines, Ministry of Health and Family Welfare, Government of India, 2011 (revised)",
    "Home Based Newborn Care Operational Guidelines, MoHFW, revised 2014, and Home Based Care for Young Child (HBYC) Guidelines, 2018",
    "WHO Recommendations for Care of the Preterm or Low Birth Weight Infant, 2022",
    "WHO Guideline on Managing Possible Serious Bacterial Infection in Young Infants when Referral is Not Feasible, 2015; India PSBI operational guidelines, 2019",
    "National Neonatology Forum of India, Evidence Based Clinical Practice Guidelines, 2020",
    "Navjaat Shishu Suraksha Karyakram (NSSK) trainee handbook, MoHFW; Textbook of Neonatal Resuscitation, AAP/AHA, 8th edition, 2021",
  ],
});

topics.push({
  id: "pediatrics-immunisation",
  title: "Immunisation under the Universal Immunisation Programme, with catch-up",
  oneLiner:
    "The Universal Immunisation Programme provides eleven vaccines free of cost against twelve diseases from birth to 16 years, and the single commonest clinical task is deciding what a partially immunised child needs today without ever restarting a schedule.",
  frequency: "core",
  keywords: [
    "UIP",
    "Universal Immunisation Programme",
    "Mission Indradhanush",
    "IAP immunisation schedule",
    "pentavalent",
    "fIPV",
    "fractional IPV",
    "PCV",
    "rotavirus",
    "MR vaccine",
    "BCG",
    "AEFI",
    "cold chain",
    "open vial policy",
    "vaccine vial monitor",
    "catch-up immunisation",
    "Td",
    "vitamin A",
    "JE vaccine",
    "U-WIN",
  ],
  sections: [
    {
      heading: "What the national schedule actually contains",
      points: [
        "**At birth (within 24 hours where possible): BCG 0.05 mL intradermally over the left upper arm at the insertion of the deltoid, OPV zero dose 2 drops orally, and hepatitis B birth dose 0.5 mL intramuscularly into the anterolateral thigh.** BCG can be given up to 1 year of age; the intradermal dose becomes 0.1 mL after 1 month of age.",
        "**At 6, 10 and 14 weeks: pentavalent (DPT + hepatitis B + Hib) 0.5 mL intramuscularly, OPV 2 drops orally, and rotavirus vaccine 5 drops orally.** Fractional IPV 0.1 mL intradermally is given at 6 and 14 weeks, and PCV 0.5 mL intramuscularly at 6 and 14 weeks.",
        "**At 9-12 months: measles-rubella (MR) first dose 0.5 mL subcutaneously, PCV booster, JE first dose in endemic districts, and vitamin A first dose 100,000 IU (1 mL) orally.**",
        "**At 16-24 months: MR second dose, DPT booster-1, OPV booster, JE second dose, and vitamin A second dose 200,000 IU (2 mL).** Vitamin A is then repeated 6-monthly up to 5 years, giving nine doses in all.",
        "**At 5-6 years: DPT booster-2. At 10 years and again at 16 years: Td 0.5 mL intramuscularly.** Pregnant women receive Td-1 and Td-2 four weeks apart, or a single Td booster if immunised within the last 3 years.",
        "Injection sites: **intramuscular vaccines go into the anterolateral thigh in children under 1 year and can go into the deltoid thereafter; the gluteal region is never used** because of sciatic nerve injury and reduced immunogenicity in fat.",
        "The programme is now recorded on the **U-WIN digital platform**, which issues a digital immunisation certificate and tracks due and defaulter lists - the practical tool for finding the partially immunised child.",
      ],
    },
    {
      heading: "Where the IAP schedule adds to the national one",
      points: [
        "The Indian Academy of Paediatrics schedule includes everything in the UIP and adds vaccines a family may choose to pay for; the examiner expects you to know both and to be able to say which is free.",
        "**Additional IAP vaccines: hepatitis A (2 doses from 12 months), typhoid conjugate vaccine (single dose from 9-12 months with a booster), varicella (2 doses from 15 months), influenza (annually from 6 months), and HPV.**",
        "**HPV vaccine for girls aged 9-14 years is a two-dose schedule 6 months apart** (three doses if started at 15 years or later or if immunocompromised); India's indigenous quadrivalent vaccine CERVAVAC has been licensed and is being introduced into the public programme.",
        "IAP prefers **DTaP or Tdap for boosters in older children** because of reactogenicity, and offers Tdap in place of one Td dose at 10-12 years.",
        "**Combination vaccines reduce the number of injections but never justify an extra dose:** if a child has already had three pentavalent doses, giving a hexavalent later would be an unnecessary hepatitis B and IPV dose.",
        "Special groups: **asplenia and nephrotic syndrome need pneumococcal, meningococcal and Hib cover; HIV-infected children receive all inactivated vaccines and receive MR unless severely immunosuppressed; live vaccines including BCG are withheld in symptomatic HIV and in a child on high-dose steroids** (2 mg/kg/day of prednisolone or 20 mg/day for 14 days or more) until one month after stopping.",
      ],
    },
    {
      heading: "Catch-up: the rules that decide what to give today",
      points: [
        "**Never restart a schedule, whatever the gap. A dose given is a dose counted.** This single rule earns marks and prevents the commonest programmatic error in Indian practice.",
        "**Respect minimum intervals, not the calendar:** 4 weeks between primary doses of pentavalent, OPV, IPV, PCV and MR; 6 months between a primary series and its first booster; the second MR dose can be given as early as 4 weeks after the first when catching up.",
        "**Respect minimum ages:** no vaccine before its minimum age (pentavalent not before 6 weeks, MR not before 9 months, DPT booster-1 not before 16 months in the routine schedule though it may be given from 12 months in catch-up if 6 months have passed since the third primary dose).",
        "**Upper age limits under UIP: BCG up to 1 year; pentavalent, rotavirus and PCV up to 1 year; OPV up to 5 years; MR up to 5 years; DPT boosters up to 7 years, beyond which Td is used because full-strength diphtheria toxoid causes severe local reactions in older children.**",
        "**Rotavirus vaccine has a hard ceiling: the first dose must be given before 1 year of age under the Indian programme (WHO caps the first dose at 15 weeks and the last at 8 months in the classical schedule) because of the theoretical intussusception risk in older infants.** If the window is missed, the vaccine is simply omitted.",
        "**All due vaccines can be given at the same visit at different sites with different syringes**; there is no limit to the number of injections at one visit, and no need to space live injectable vaccines except that two live parenteral vaccines not given together must be separated by 4 weeks.",
        "Missed opportunities are the enemy: **a child with mild illness, low-grade fever, diarrhoea, malnutrition or on antibiotics should still be immunised**, and the only true contraindications are anaphylaxis to a previous dose and encephalopathy within 7 days of a pertussis-containing vaccine.",
      ],
    },
    {
      heading: "Adverse events following immunisation",
      points: [
        "**AEFI is any untoward medical occurrence which follows immunisation and which does not necessarily have a causal relationship with the vaccine** - the definition deliberately includes coincidental events, because reporting must not depend on the reporter's judgement of causality.",
        "**The five causal categories are: vaccine product-related reaction, vaccine quality defect, immunisation error-related reaction (programmatic error), immunisation anxiety-related reaction, and coincidental event.** Immunisation error is the only category that is fully preventable and the one that causes clusters.",
        "**A serious AEFI is one that causes death, hospitalisation, persistent or significant disability, a congenital anomaly, or is life-threatening**, and must be reported within 24 hours to the medical officer, who informs the District Immunisation Officer; investigation begins within 48 hours using Case Reporting and Investigation Forms.",
        "Common minor events: fever, local pain, swelling and induration after pentavalent or DPT (manage with paracetamol 15 mg/kg/dose and a cold compress); fever and rash 5-12 days after MR; a BCG papule that ulcerates at 2-4 weeks and heals with a scar by 6-12 weeks - **this is normal and needs no treatment**.",
        "**BCG lymphadenitis** (a node over 1.5 cm, usually axillary) is usually non-suppurative and resolves spontaneously; a fluctuant node is aspirated, and neither anti-tuberculosis drugs nor incision and drainage are indicated.",
        "**Vaccine-associated paralytic poliomyelitis is the reason IPV was added**; anaphylaxis is treated with adrenaline **0.01 mg/kg of 1:1000 intramuscularly into the anterolateral thigh, maximum 0.5 mg, repeated every 5-15 minutes**, and every immunisation session must have an anaphylaxis kit.",
        "Explain the expected minor reactions before the child leaves and keep every child under observation for 30 minutes - both are examinable programme requirements.",
      ],
    },
    {
      heading: "Cold chain, open vial policy and session practice",
      points: [
        "**Vaccines are stored at +2 to +8 degrees C in the ILR at the PHC**; OPV is kept in the deep freezer at -20 degrees C at district and regional stores. In the vaccine carrier, four conditioned ice packs are used and the vaccines are placed in the middle.",
        "**The freeze-sensitive vaccines that must never be frozen are hepatitis B, pentavalent, IPV, PCV, rotavirus (liquid) and Td;** the heat-sensitive vaccines are OPV (most heat sensitive), followed by measles-rubella and BCG. In the ILR, freeze-sensitive vaccines are kept away from the floor of the cabinet and never touch the ice pack directly.",
        "**The shake test detects a frozen adsorbed vaccine:** a frozen-and-thawed vial sediments quickly leaving a clear supernatant with flakes, while a good vial stays uniformly cloudy. A vial failing the shake test is discarded.",
        "**Vaccine vial monitor:** the inner square lighter than the outer circle (stages 1 and 2) means usable; when the inner square matches or is darker than the outer circle (stages 3 and 4) the vial is discarded. The VVM is on OPV, and increasingly on other vials.",
        "**Open vial policy:** OPV, pentavalent, hepatitis B, IPV, fIPV, Td and liquid rotavirus vaccine may be used for up to 4 weeks after opening provided the expiry date has not passed, the VVM is in stage 1 or 2, aseptic technique was used and the vial has not been submerged in water. **Reconstituted BCG, MR and JE must be discarded after 4 hours.**",
        "**Auto-disable syringes are used for every injection, reconstitution syringes for reconstitution only, and hub cutting immediately after use**; sharps go into the puncture-proof box, and the red-yellow-black-blue waste segregation applies at every session.",
        "The four key session-site messages to the mother are: which vaccines were given today, the minor reactions to expect and what to do, the date of the next visit written on the MCP card, and to bring the card every time.",
      ],
    },
    {
      heading: "Programme, coverage and the missed child",
      points: [
        "**A fully immunised child (12-23 months) has received BCG, three doses of DPT or pentavalent, three of OPV and one measles-containing vaccine; a fully vaccinated child additionally has hepatitis B, PCV and rotavirus doses as per schedule.** NFHS-5 (2019-21) reported full immunisation coverage of 76.4% in children aged 12-23 months, up from 62% in NFHS-4.",
        "**Mission Indradhanush and Intensified Mission Indradhanush target the partially immunised and unimmunised** in low-coverage blocks, urban slums, migrant, tribal and nomadic populations, with head-count surveys and additional sessions.",
        "The four commonest reasons for a partially immunised child in India are: **the family did not know or forgot the next date, fear of side effects or a previous reaction, the mother was away or busy, and the session was not held or the vaccine was out of stock** - all addressable at the clinic desk.",
        "**Measles-rubella elimination** requires 95% coverage with two doses; outbreak response immunisation and vitamin A for every case of measles are part of the case management.",
        "**Polio: India was certified polio-free in March 2014**; the switch from trivalent to bivalent OPV happened in 2016 and fractional IPV was introduced to build seroprotection against type 2 at a lower cost.",
        "Every consultation is an immunisation opportunity: **ask for the MCP card at every child contact, and give the due vaccines the same day rather than fixing another appointment.**",
      ],
    },
  ],
  tables: [
    {
      heading: "The Universal Immunisation Programme schedule",
      columns: ["Age", "Vaccines", "Dose and route", "Site"],
      rows: [
        ["Birth", "BCG, OPV-0, hepatitis B birth dose", "BCG 0.05 mL ID; OPV 2 drops oral; HepB 0.5 mL IM", "Left upper arm; mouth; anterolateral thigh"],
        ["6 weeks", "Pentavalent-1, OPV-1, rotavirus-1, fIPV-1, PCV-1", "Penta 0.5 mL IM; OPV 2 drops; rota 5 drops; fIPV 0.1 mL ID; PCV 0.5 mL IM", "Anterolateral thigh (left and right); right upper arm for fIPV"],
        ["10 weeks", "Pentavalent-2, OPV-2, rotavirus-2", "As above", "Anterolateral thigh"],
        ["14 weeks", "Pentavalent-3, OPV-3, rotavirus-3, fIPV-2, PCV-2", "As above", "Anterolateral thigh; right upper arm for fIPV"],
        ["9-12 months", "MR-1, JE-1 (endemic), PCV booster, vitamin A-1", "MR 0.5 mL SC; JE 0.5 mL SC; vitamin A 1 mL (100,000 IU) oral", "Right upper arm; left upper arm; mouth"],
        ["16-24 months", "MR-2, JE-2, DPT booster-1, OPV booster, vitamin A-2", "MR 0.5 mL SC; DPT 0.5 mL IM; vitamin A 2 mL (200,000 IU) oral", "Right upper arm; anterolateral thigh"],
        ["5-6 years", "DPT booster-2", "0.5 mL IM", "Upper arm"],
        ["10 years and 16 years", "Td", "0.5 mL IM", "Upper arm"],
      ],
    },
    {
      heading: "Catch-up rules at a glance",
      columns: ["Vaccine", "Minimum age for first dose", "Minimum interval between doses", "Upper age under UIP"],
      rows: [
        ["BCG", "Birth", "Single dose", "1 year (0.1 mL ID after 1 month of age)"],
        ["Hepatitis B", "Birth", "4 weeks", "Given as pentavalent up to 1 year"],
        ["Pentavalent (DPT-HepB-Hib)", "6 weeks", "4 weeks", "1 year; use DPT for boosters, Td after 7 years"],
        ["OPV", "Birth", "4 weeks", "5 years"],
        ["fIPV", "6 weeks", "8 weeks (6 and 14 week schedule)", "1 year"],
        ["Rotavirus", "6 weeks", "4 weeks", "First dose before 1 year; omit if missed"],
        ["PCV", "6 weeks", "4 weeks (booster at 9 months)", "1 year in the programme"],
        ["MR", "9 months", "4 weeks in catch-up (routine gap 9 to 16-24 months)", "5 years"],
      ],
    },
    {
      heading: "Cold chain: what tolerates what",
      columns: ["Vaccine", "Storage", "Damaged by freezing?", "Time after opening or reconstitution"],
      rows: [
        ["OPV", "-20 C at district; +2 to +8 C at PHC", "No (freezing is safe)", "4 weeks (open vial policy)"],
        ["Pentavalent, hepatitis B, Td, IPV, PCV", "+2 to +8 C", "Yes - never freeze; do the shake test", "4 weeks (open vial policy)"],
        ["Rotavirus (liquid)", "+2 to +8 C", "Yes", "4 weeks (open vial policy)"],
        ["BCG", "+2 to +8 C", "Not damaged by freezing but is heat and light sensitive", "4 hours after reconstitution"],
        ["Measles-rubella, JE", "+2 to +8 C", "Not damaged by freezing; very heat sensitive", "4 hours after reconstitution"],
      ],
    },
  ],
  redFlags: [
    "Anaphylaxis to a previous dose of the same vaccine - an absolute contraindication; note it on the card and refer for specialist assessment before any further dose.",
    "Encephalopathy within 7 days of a pertussis-containing vaccine with no other cause - omit the pertussis component and continue with DT or Td.",
    "A cluster of similar adverse events after immunisation at one session or from one vial - suspect a programmatic error or a quality defect, sequester the vial and report the same day.",
    "Live vaccine (BCG, MR, JE, OPV) in a child with symptomatic HIV, primary immunodeficiency, active malignancy on chemotherapy, or on prednisolone 2 mg/kg/day or 20 mg/day for 14 days or more.",
    "A BCG lymph node that is fluctuant, larger than 3 cm, or in a child who is failing to thrive with disseminated disease - refer; consider underlying immunodeficiency.",
    "Vaccine vial monitor at stage 3 or 4, or a vial that fails the shake test - do not use; report as a cold chain failure.",
    "A child brought after a febrile convulsion following DPT who has been advised to stop all vaccines - this is not a contraindication and the advice itself is the danger.",
  ],
  pearls: [
    "A dose given is a dose counted: never restart an immunisation schedule, however long the gap. Complete it from where it stopped, honouring minimum ages and minimum intervals.",
    "Minor illness, low-grade fever, diarrhoea, malnutrition, breastfeeding, prematurity and current antibiotic use are all reasons to immunise, not to defer. A missed opportunity costs more than a mild reaction.",
    "Rotavirus vaccine is the one with a hard age ceiling - if the first dose window has closed, the vaccine is omitted, not given late.",
    "After 7 years of age, diphtheria toxoid is given only as Td; full-strength DPT causes severe local Arthus-type reactions in the older, primed child.",
    "The gluteal region is never a vaccination site in a child: the anterolateral thigh under 1 year, the deltoid thereafter.",
    "BCG scar formation is expected but its absence is not a reason to repeat the vaccine under the national programme; do not re-vaccinate a child with no scar.",
    "Ask for the MCP card at every single child contact - the outpatient department is where most partially immunised children are found.",
    "The shake test, the vaccine vial monitor and the open vial policy are three separate checks and examiners ask them as one question - know which vaccines each applies to.",
    "Reconstituted BCG, measles-rubella and JE are discarded after 4 hours; the 4-week open vial policy applies only to the liquid, multi-dose, preservative-containing vaccines.",
  ],
  theory: [
    {
      id: "pediatrics-immunisation-t1",
      paper: "IV",
      kind: "long",
      marks: 10,
      minutes: 20,
      frequency: "core",
      question:
        "An 11-month-old child is brought to your clinic with fever and cough. The immunisation card shows BCG, OPV-0 and hepatitis B at birth, and one dose of pentavalent, OPV and rotavirus at 7 weeks of age, with nothing since. Outline the Universal Immunisation Programme schedule and describe how you would complete this child's immunisation.",
      openingLines: [
        "The Universal Immunisation Programme provides eleven vaccines free of cost against twelve diseases from birth to 16 years, and this child is partially immunised - he has had the birth doses and only the first dose of the primary series.",
        "The governing principle is that a schedule is never restarted: doses already given are counted, and the remaining doses are given respecting minimum intervals and minimum ages, starting today because a mild febrile illness is not a contraindication.",
      ],
      answer: [
        {
          heading: "1. The national schedule",
          points: [
            "Birth: BCG 0.05 mL intradermal, OPV zero dose, hepatitis B birth dose 0.5 mL intramuscular within 24 hours.",
            "6, 10 and 14 weeks: pentavalent 0.5 mL IM, OPV 2 drops, rotavirus 5 drops; fIPV 0.1 mL intradermal at 6 and 14 weeks; PCV 0.5 mL IM at 6 and 14 weeks.",
            "9-12 months: MR-1, JE-1 in endemic districts, PCV booster, vitamin A 100,000 IU.",
            "16-24 months: MR-2, JE-2, DPT booster-1, OPV booster, vitamin A 200,000 IU, then vitamin A 6-monthly to 5 years.",
            "5-6 years: DPT booster-2. 10 and 16 years: Td. Pregnancy: Td-1 and Td-2 or a booster.",
          ],
        },
        {
          heading: "2. Assess this child today",
          points: [
            "Confirm the doses from the card rather than the history; an undocumented dose is generally treated as not given, though a credible parental history for a specific vaccine may be accepted in programme practice.",
            "Establish that the current illness is mild: no fast breathing, no chest indrawing, no general danger sign. **Mild febrile illness, cough, diarrhoea, malnutrition and antibiotic use are not contraindications.**",
            "Check for true contraindications: anaphylaxis to a previous dose, encephalopathy within 7 days of a pertussis vaccine, and immunosuppression for live vaccines.",
            "Weigh and plot the child, check for vitamin A dosing, and look at the sibling's cards while the family is present.",
          ],
        },
        {
          heading: "3. What to give today",
          points: [
            "**Pentavalent-2, OPV-2, PCV and fIPV, and because he is 11 months old, MR-1 and vitamin A 100,000 IU, all at the same visit at different sites with separate auto-disable syringes.**",
            "**Rotavirus vaccine: the second dose may be given because the first dose was received in the eligible window and the child is still under 1 year; if the first dose had not been given before 1 year, the vaccine would simply be omitted.**",
            "There is no limit to the number of injections at a single visit, and giving them together does not reduce immunogenicity.",
            "Record every dose on the MCP card and on U-WIN, and write the next date in words the family can read.",
          ],
        },
        {
          heading: "4. The remaining catch-up plan",
          points: [
            "**4 weeks later: pentavalent-3, OPV-3, fIPV-2, PCV-2.** Rotavirus-3 if he is still within the age limit.",
            "**At least 4 weeks after MR-1 (and in routine practice at 16-24 months): MR-2, DPT booster-1, OPV booster, JE-2 where endemic, and vitamin A 200,000 IU.**",
            "Booster-1 requires a minimum of 6 months from the third primary pentavalent dose.",
            "DPT booster-2 at 5-6 years, Td at 10 and 16 years. If the child ever presents after 7 years with an incomplete series, use Td, not DPT.",
          ],
        },
        {
          heading: "5. Counselling and programme measures",
          points: [
            "Explain the expected minor reactions - fever, local pain and swelling after pentavalent, and fever with rash 5-12 days after MR - and advise paracetamol 15 mg/kg/dose as needed.",
            "Keep the child at the centre for 30 minutes, with an anaphylaxis kit and adrenaline 1:1000 available (0.01 mg/kg IM, maximum 0.5 mg).",
            "Identify why the family defaulted - forgotten date, fear of reactions, migration, session not held - and address that specific reason.",
            "Link the child to the ASHA and the U-WIN due list so the remaining doses are actively followed up; this is exactly the child Intensified Mission Indradhanush exists to find.",
          ],
        },
      ],
      mustDraw: [
        "The full UIP schedule as a table of age against vaccines, dose and route.",
        "A catch-up plan table for this child: today, +4 weeks, +8 weeks and at 16-24 months.",
      ],
      markSplit: [
        { part: "The complete UIP schedule with doses and routes", marks: 4 },
        { part: "Principles of catch-up: never restart, minimum age and interval, false contraindications", marks: 2 },
        { part: "What to give today, correctly listed", marks: 2 },
        { part: "The remaining plan with intervals", marks: 1 },
        { part: "Counselling, AEFI readiness and defaulter tracking", marks: 1 },
      ],
      keywords: ["UIP schedule", "catch-up immunisation", "partially immunised", "Mission Indradhanush", "false contraindications"],
    },
    {
      id: "pediatrics-immunisation-t2",
      paper: "IV",
      kind: "short-note",
      marks: 5,
      minutes: 10,
      frequency: "common",
      question: "Write short notes on adverse events following immunisation (AEFI): definition, classification, and the response to a serious AEFI.",
      openingLines: [
        "An adverse event following immunisation is any untoward medical occurrence which follows immunisation and which does not necessarily have a causal relationship with the use of the vaccine.",
        "The definition is deliberately broad so that reporting does not depend on the reporter's judgement of causality; causality is assigned later by the district and state AEFI committees using the WHO algorithm.",
      ],
      answer: [
        {
          heading: "Classification by cause",
          points: [
            "**Vaccine product-related reaction** - caused by one or more inherent properties of the vaccine, such as extensive limb swelling after DPT or vaccine-associated paralytic poliomyelitis after OPV.",
            "**Vaccine quality defect-related reaction** - caused by a defect in the product or its administration device as provided by the manufacturer.",
            "**Immunisation error-related reaction (programmatic error)** - wrong diluent, wrong dose or route, reuse of a syringe, a vaccine reconstituted more than 4 hours earlier, contamination. This is the only fully preventable category and is the usual cause of a cluster.",
            "**Immunisation anxiety-related reaction** - fainting, hyperventilation, breath-holding; commonest in adolescents at school sessions.",
            "**Coincidental event** - an illness that would have happened anyway, temporally associated with the vaccine.",
          ],
        },
        {
          heading: "Classification by severity",
          points: [
            "Minor: fever, local pain, swelling, induration, irritability - managed with paracetamol 15 mg/kg/dose and a cold compress.",
            "Severe: high fever, persistent inconsolable crying, hypotonic-hyporesponsive episode, febrile seizure.",
            "**Serious AEFI: any event causing death, hospitalisation, persistent or significant disability, a congenital anomaly, or that is life-threatening.**",
          ],
        },
        {
          heading: "Response to a serious AEFI",
          points: [
            "Treat the patient first: anaphylaxis is treated with **adrenaline 0.01 mg/kg of the 1:1000 solution intramuscularly into the anterolateral thigh, maximum 0.5 mg, repeated every 5-15 minutes**, with airway support and referral.",
            "**Report within 24 hours to the medical officer, who notifies the District Immunisation Officer; investigation starts within 48 hours** using the Case Reporting Form and Case Investigation Form, with a preliminary report within 7 days.",
            "Sequester the remaining vials, diluents, syringes and the vaccine carrier from the same session and store them under cold chain for testing; record the batch numbers.",
            "In a death, a post-mortem should be sought within 24 hours; the district AEFI committee reviews and the state committee assigns causality using the WHO classification.",
            "Communicate proactively with the family and the community - unmanaged rumour after a single coincidental death can collapse coverage in a block for years.",
          ],
        },
      ],
      mustDraw: ["A table of the five causal categories of AEFI with one example each, and the reporting timeline (24 hours, 48 hours, 7 days)."],
      markSplit: [
        { part: "Definition", marks: 1 },
        { part: "Five causal categories with examples", marks: 2 },
        { part: "Definition of a serious AEFI", marks: 0.5 },
        { part: "Immediate treatment, reporting timeline and investigation", marks: 1.5 },
      ],
      keywords: ["AEFI", "programmatic error", "causality assessment", "serious AEFI", "anaphylaxis"],
    },
    {
      id: "pediatrics-immunisation-t3",
      paper: "IV",
      kind: "short-note",
      marks: 5,
      minutes: 8,
      frequency: "common",
      question: "Write short notes on the cold chain, including the open vial policy and the assessment of vaccine potency at a session site.",
      openingLines: [
        "The cold chain is the system of people, equipment and procedures that keeps a vaccine within its recommended temperature range from the manufacturer to the child.",
        "Most vaccines are stored at +2 to +8 degrees C at the peripheral level; the two errors that destroy potency are heat exposure and, just as often and less recognised, inadvertent freezing.",
      ],
      answer: [
        {
          heading: "Equipment and storage",
          points: [
            "Walk-in coolers and freezers at regional stores; ice-lined refrigerators (ILR) and deep freezers at district and PHC level; vaccine carriers with four conditioned ice packs for the session site.",
            "**OPV is stored at -20 degrees C at district and regional stores and at +2 to +8 degrees C at the PHC; all other vaccines are kept at +2 to +8 degrees C.**",
            "Twice-daily temperature recording on the ILR chart, an alarm or contingency plan for power failure, and no food or specimens in the vaccine refrigerator.",
            "**Conditioning of ice packs** - keeping them out until droplets of water appear and they are no longer rigidly frozen - prevents freezing of freeze-sensitive vaccines in the carrier.",
          ],
        },
        {
          heading: "Which vaccines are damaged by what",
          points: [
            "**Never freeze: hepatitis B, pentavalent, IPV, PCV, Td and liquid rotavirus vaccine.** Freezing causes irreversible loss of potency and increases local reactions.",
            "**Most heat sensitive: OPV, then measles-rubella and BCG.** These are the vaccines that suffer in a broken cold chain in summer.",
            "The **shake test** identifies a frozen and thawed adsorbed vaccine: sedimentation within 5-30 minutes leaving a clear supernatant with flakes, compared with a control vial that stays uniformly turbid. A failed vial is discarded.",
          ],
        },
        {
          heading: "Vaccine vial monitor and open vial policy",
          points: [
            "**The vaccine vial monitor is a heat-sensitive square inside a circle. Usable while the inner square is lighter than the outer circle (stages 1 and 2); discard when it is the same shade or darker (stages 3 and 4).**",
            "**Open vial policy: OPV, pentavalent, hepatitis B, IPV, fIPV, Td and liquid rotavirus vaccine may be used for up to 4 weeks after opening**, provided the expiry date has not passed, the VVM is in stage 1 or 2, aseptic technique was used, the septum was not submerged in water and the date and time of opening are written on the vial.",
            "**Reconstituted BCG, measles-rubella and JE must be discarded 4 hours after reconstitution** or at the end of the session, whichever is earlier, because they contain no preservative.",
            "Only the diluent supplied by the same manufacturer for that vaccine is used for reconstitution, and it must be cooled to the same temperature as the vaccine.",
          ],
        },
      ],
      mustDraw: [
        "A labelled diagram of the vaccine vial monitor showing the four stages and which two are usable.",
        "A table of freeze-sensitive versus heat-sensitive vaccines.",
      ],
      markSplit: [
        { part: "Definition, equipment and storage temperatures", marks: 1.5 },
        { part: "Freeze-sensitive versus heat-sensitive vaccines and the shake test", marks: 1.5 },
        { part: "Vaccine vial monitor", marks: 1 },
        { part: "Open vial policy and the 4-hour rule", marks: 1 },
      ],
      keywords: ["cold chain", "ILR", "vaccine vial monitor", "shake test", "open vial policy"],
    },
  ],
  mcqs: [
    {
      id: "pediatrics-immunisation-q1",
      stem: "A 14-month-old boy has an immunisation card showing BCG, OPV-0 and hepatitis B at birth and pentavalent-1, OPV-1 at 6 weeks only. He is well. What is the most appropriate action today?",
      options: [
        "Restart the primary series from the beginning with pentavalent-1",
        "Give pentavalent-2, OPV-2, MR-1 and vitamin A today, and complete the remaining doses at 4-week intervals",
        "Defer all vaccines until he is 18 months and then give the boosters only",
        "Give MR-1 alone today and call him back for one injection every month",
        "Give DPT instead of pentavalent because he is over 1 year, and omit hepatitis B and Hib",
      ],
      answer: 1,
      explanation:
        "A schedule is never restarted, and all due vaccines can be given at the same visit at different sites, so pentavalent-2, OPV-2, MR-1 (due from 9 months) and vitamin A should all be given today with the rest completed at minimum intervals. Restarting wastes doses and delays protection. Deferring to 18 months leaves him unprotected through the highest-risk period. Giving one injection per visit multiplies visits and is the classic route to another default. Under UIP pentavalent may still be used up to 1 year and, where a child has just crossed it, programme practice is to complete the pentavalent series where available rather than to strip out the hepatitis B and Hib components, which he still needs.",
      difficulty: "moderate",
    },
    {
      id: "pediatrics-immunisation-q2",
      stem: "A 10-week-old infant is brought for immunisation with a temperature of 38.0 degrees C, coryza and a respiratory rate of 42 per minute, feeding well and with no chest indrawing. The mother is worried about giving vaccines during illness. What should you do?",
      options: [
        "Defer all vaccines until the child is afebrile for 48 hours",
        "Give only the oral vaccines today and the injections after recovery",
        "Give all due vaccines today and treat the illness",
        "Give the vaccines but halve the dose because of the fever",
        "Give an antipyretic and antibiotic first, then vaccinate in a week",
      ],
      answer: 2,
      explanation:
        "Mild illness with or without low-grade fever is not a contraindication, and deferring creates a missed opportunity in an infant at maximum risk from pertussis and pneumococcus. Splitting oral and injectable doses has no immunological basis and doubles the number of visits. Vaccine doses are never reduced - a fractional dose is used only where the schedule specifies it, such as fIPV given intradermally. Antibiotics are not indicated for coryza with a normal respiratory rate, and waiting a week simply repeats the delay.",
      difficulty: "easy",
    },
    {
      id: "pediatrics-immunisation-q3",
      stem: "At an outreach session, a vial of pentavalent vaccine is found with a clear supernatant and flaky sediment after standing, while the control vial remains uniformly cloudy. What does this indicate and what should be done?",
      options: [
        "The vial is beyond its expiry date; check the date and discard",
        "The vial has been frozen; discard it and investigate the cold chain",
        "The vial has been heat exposed; use it if the vaccine vial monitor is in stage 1",
        "Normal appearance of pentavalent vaccine; shake and use",
        "The vial is contaminated; send it for sterility testing and continue the session with the remaining vials",
      ],
      answer: 1,
      explanation:
        "This is a positive shake test, which identifies an adsorbed vaccine that has been frozen and thawed - the aluminium adjuvant flocculates and sediments rapidly, and potency is irreversibly lost. Expiry has nothing to do with the physical appearance of the suspension. The vaccine vial monitor tracks cumulative heat exposure, not freezing, so a stage 1 VVM does not rescue a frozen vial - which is exactly why the shake test exists as a separate check. Freshly shaken pentavalent should look uniformly cloudy, and this appearance is not that of contamination.",
      difficulty: "moderate",
    },
    {
      id: "pediatrics-immunisation-q4",
      stem: "A 3-week-old baby who received BCG at birth is brought because the vaccination site has become a small papule which has ulcerated and is discharging a little. The baby is feeding well, afebrile and gaining weight. What is the correct management?",
      options: [
        "Start anti-tuberculosis treatment with isoniazid and rifampicin",
        "Incise and drain the lesion and apply an antibiotic ointment",
        "Reassure the mother that this is the expected evolution and keep the site clean and dry",
        "Give a course of oral cloxacillin for 7 days",
        "Repeat the BCG on the opposite arm as the first dose has clearly failed",
      ],
      answer: 2,
      explanation:
        "A papule appearing at 2-4 weeks that ulcerates and heals with a scar by 6-12 weeks is the normal, expected evolution of a BCG lesion and needs nothing but reassurance and dry, uncovered care. Anti-tuberculosis drugs are not indicated for a normal local reaction and are reserved for disseminated BCG disease. Incision and drainage converts a self-healing lesion into a chronic sinus. Antibiotics do not shorten it, and BCG is never repeated under the national programme, whether or not a scar forms.",
      difficulty: "easy",
    },
    {
      id: "pediatrics-immunisation-q5",
      stem: "A 4-month-old infant, whose only vaccination is BCG at birth, is brought for catch-up. Which vaccine can NOT be given as part of the catch-up plan?",
      options: [
        "Pentavalent",
        "Oral polio vaccine",
        "Fractional inactivated polio vaccine",
        "Rotavirus vaccine",
        "Pneumococcal conjugate vaccine",
      ],
      answer: 3,
      explanation:
        "Rotavirus vaccine is the exception in the schedule with a hard age ceiling driven by the intussusception signal: WHO caps the first dose at 15 weeks and the Indian programme requires the first dose before 1 year, so a first dose at 4 months falls outside the classical window and in strict practice the vaccine is omitted rather than started late. Pentavalent, OPV, fIPV and PCV all have no upper limit within the first year and are given at minimum 4-week intervals to complete the primary series. This question tests the one vaccine that is dropped rather than delayed.",
      difficulty: "hard",
    },
    {
      id: "pediatrics-immunisation-q6",
      stem: "Four children in a single immunisation session develop high fever with a tender, fluctuant swelling at the injection site within 48 hours. All received vaccine from the same reconstituted vial. Which AEFI category is this most likely to represent?",
      options: [
        "Vaccine product-related reaction",
        "Immunisation error-related reaction",
        "Immunisation anxiety-related reaction",
        "Coincidental event",
        "Vaccine quality defect-related reaction",
      ],
      answer: 1,
      explanation:
        "A cluster of local abscesses traceable to one vial points to contamination during reconstitution or use - the wrong diluent, a reused syringe, or a vial kept beyond the 4-hour reconstitution limit - which is an immunisation error, the only fully preventable category and the classic cause of clustering. A product-related reaction would be distributed across vials and batches rather than concentrated in one vial at one session. Anxiety reactions are immediate faints and hyperventilation, not suppurative abscesses at 48 hours. A coincidental event would not cluster this tightly, and a manufacturing quality defect would produce cases across many sessions using that batch, which should nevertheless be excluded by sequestering and testing the vial.",
      difficulty: "moderate",
    },
    {
      id: "pediatrics-immunisation-q7",
      stem: "A 9-year-old girl who has never been immunised is brought to a family practice. Which tetanus and diphtheria containing preparation should be used, and why?",
      options: [
        "DPT, because she needs pertussis protection",
        "Td, because full-strength diphtheria toxoid causes severe local reactions after 7 years of age",
        "Tetanus toxoid alone, because diphtheria is no longer prevalent",
        "Pentavalent, because she also needs hepatitis B and Hib",
        "No tetanus-containing vaccine is indicated at this age",
      ],
      answer: 1,
      explanation:
        "Beyond 7 years of age the full-strength diphtheria toxoid in DPT provokes severe Arthus-type local reactions in a primed or older child, so the reduced-antigen Td (or Tdap in the IAP schedule) is used - and she needs a primary series of three doses at 0, 1 and 6 months. Tetanus toxoid alone leaves her susceptible to diphtheria, which continues to cause outbreaks in India. Pentavalent is not licensed or supplied for this age, and Hib disease is uncommon after 5 years. Doing nothing leaves a completely unprotected child.",
      difficulty: "moderate",
    },
  ],
  cards: [
    { id: "pediatrics-immunisation-c1", front: "Vaccines given at birth under UIP", back: "BCG 0.05 mL intradermal (left upper arm), OPV zero dose 2 drops oral, hepatitis B 0.5 mL IM within 24 hours." },
    { id: "pediatrics-immunisation-c2", front: "Vaccines at 6, 10 and 14 weeks", back: "Pentavalent, OPV and rotavirus at all three visits; fIPV 0.1 mL intradermal and PCV 0.5 mL IM at 6 and 14 weeks only." },
    { id: "pediatrics-immunisation-c3", front: "Vitamin A schedule under UIP", back: "100,000 IU (1 mL) at 9 months with MR-1, then 200,000 IU (2 mL) at 16-18 months and every 6 months up to 5 years - nine doses in all." },
    { id: "pediatrics-immunisation-c4", front: "The golden rule of catch-up immunisation", back: "Never restart a schedule. A dose given is counted; complete the rest honouring minimum age and a minimum 4-week interval between primary doses." },
    { id: "pediatrics-immunisation-c5", front: "The only true contraindications to routine immunisation", back: "Anaphylaxis to a previous dose of the same vaccine, and encephalopathy within 7 days of a pertussis-containing vaccine. Live vaccines are additionally withheld in significant immunosuppression." },
    { id: "pediatrics-immunisation-c6", front: "Which vaccines must never be frozen?", back: "Hepatitis B, pentavalent, IPV, PCV, Td and liquid rotavirus vaccine. Detect a frozen adsorbed vaccine with the shake test and discard the vial." },
    { id: "pediatrics-immunisation-c7", front: "Open vial policy: 4 weeks versus 4 hours", back: "4 weeks for OPV, pentavalent, hepatitis B, IPV, fIPV, Td and liquid rotavirus. 4 hours after reconstitution for BCG, measles-rubella and JE." },
    { id: "pediatrics-immunisation-c8", front: "Vaccine vial monitor: when is a vial usable?", back: "While the inner square is lighter than the outer circle (stages 1 and 2). Discard at stages 3 and 4, when the square matches or is darker than the circle." },
    { id: "pediatrics-immunisation-c9", front: "Definition of a fully immunised child", back: "A child aged 12-23 months who has received BCG, three doses of DPT or pentavalent, three doses of OPV and one measles-containing vaccine. NFHS-5 coverage: 76.4%." },
    { id: "pediatrics-immunisation-c10", front: "The five causal categories of AEFI", back: "Vaccine product-related; vaccine quality defect; immunisation error (programmatic); immunisation anxiety; coincidental." },
    { id: "pediatrics-immunisation-c11", front: "Anaphylaxis after a vaccine: drug and dose", back: "Adrenaline 0.01 mg/kg of 1:1000 intramuscularly into the anterolateral thigh, maximum 0.5 mg, repeated every 5-15 minutes, with airway support and referral." },
    { id: "pediatrics-immunisation-c12", front: "Why is Td used instead of DPT after 7 years?", back: "Full-strength diphtheria toxoid causes severe Arthus-type local reactions in the older, primed child; Td carries a reduced diphtheria antigen dose." },
    { id: "pediatrics-immunisation-c13", front: "HPV vaccine schedule for Indian girls", back: "Two doses 6 months apart for girls aged 9-14 years; three doses if started at 15 years or later or if immunocompromised." },
  ],
  references: [
    "Universal Immunisation Programme, Immunisation Handbook for Medical Officers, Ministry of Health and Family Welfare, Government of India, 2017 (with subsequent programme updates)",
    "Indian Academy of Paediatrics Advisory Committee on Vaccines and Immunization Practices (ACVIP) Recommended Immunization Schedule, 2023-24",
    "National AEFI Surveillance and Response Operational Guidelines, MoHFW, 2015 (revised)",
    "WHO Position Papers on rotavirus, pneumococcal conjugate, HPV and polio vaccines, current editions",
    "National Family Health Survey-5 (2019-21), India Fact Sheet - child immunisation coverage",
  ],
});
