/** Hand-mapped question links, batch 4. Generated with judgement, not keywords. */
export const LINKS_PART4: Record<string, string[]> = {
  // Orthopaedics and soft tissue
  "pyqtw-0348": ["neurology-peripheral-neuropathy", "musculoskeletal-neck-pain"],
  "pyqtw-0349": ["musculoskeletal-fractures-sports-injury", "musculoskeletal-gout"],
  "pyqtw-0351": ["surgery-office-minor-procedures"],
  "pyqtw-0352": ["musculoskeletal-fractures-sports-injury"],
  "pyqtw-0354": [
    "musculoskeletal-osteoporosis",
    "geriatrics-ethics-falls",
    "musculoskeletal-fractures-sports-injury",
  ],
  "pyqtw-0356": [
    "musculoskeletal-fractures-sports-injury",
    "musculoskeletal-osteoporosis",
    "geriatrics-ethics-falls",
  ],
  "pyqtw-0357": ["musculoskeletal-fractures-sports-injury", "musculoskeletal-osteoporosis"],
  "pyqtw-0358": ["musculoskeletal-neck-pain", "musculoskeletal-shoulder-pain"],
  "pyqtw-0361": ["musculoskeletal-knee-osteoarthritis"],
  "pyqtw-0364": [
    "infectious-fever-skin-soft-tissue-infection",
    "surgery-office-abscess-ssti",
    "musculoskeletal-fractures-sports-injury",
  ],
  "pyqtw-0366": ["musculoskeletal-osteoporosis", "musculoskeletal-fractures-sports-injury"],
  "pyqtw-0367": ["musculoskeletal-fractures-sports-injury"],
  "pyqtw-0368": ["musculoskeletal-gout", "infectious-fever-skin-soft-tissue-infection"],
  "pyqtw-0369": ["musculoskeletal-shoulder-pain"],
  "pyqtw-0370": ["musculoskeletal-shoulder-pain"],
  "pyqtw-0372": ["musculoskeletal-shoulder-pain"],
  "pyqtw-0373": ["musculoskeletal-fractures-sports-injury"],
  "pyqtw-0374": ["musculoskeletal-fractures-sports-injury", "emergency-trauma-primary-survey"],
  "pyqtw-0375": ["musculoskeletal-fractures-sports-injury"],
  "pyqtw-0376": ["musculoskeletal-fractures-sports-injury"],
  "pyqtw-0377": ["musculoskeletal-fractures-sports-injury"],

  // Ear, nose and throat
  "pyqtw-0381": ["eye-ent-otitis"],
  "pyqtw-0388": ["eye-ent-otitis"],
  "pyqtw-0389": ["eye-ent-epistaxis-foreign-bodies"],
  "pyqtw-0394": ["eye-ent-hearing-loss", "eye-ent-epistaxis-foreign-bodies"],
  "pyqtw-0399": ["eye-ent-epistaxis-foreign-bodies"],
  "pyqtw-0400": ["eye-ent-epistaxis-foreign-bodies", "cardiovascular-hypertension"],
  "pyqtw-0402": ["eye-ent-epistaxis-foreign-bodies"],
  "pyqtw-0403": ["eye-ent-epistaxis-foreign-bodies"],
  "pyqtw-0406": ["eye-ent-epistaxis-foreign-bodies"],
  "pyqtw-0407": ["eye-ent-rhinitis-sinusitis", "endocrine-diabetic-emergencies"],
  "pyqtw-0408": ["eye-ent-epistaxis-foreign-bodies"],
  "pyqtw-0410": ["symptom-approach-weight-loss", "gastro-hepatology-acid-peptic-gerd"],
  "pyqtw-0412": ["eye-ent-sore-throat"],
  "pyqtw-0413": [],

  // Ophthalmology
  "pyqtw-0414": ["eye-ent-cataract-dr-glaucoma"],
  "pyqtw-0417": ["eye-ent-red-eye"],
  "pyqtw-0418": ["endocrine-hyperthyroidism-nodule", "eye-ent-red-eye"],
  "pyqtw-0419": ["eye-ent-red-eye", "surgery-office-minor-procedures"],
  "pyqtw-0420": ["eye-ent-red-eye"],
  "pyqtw-0421": ["eye-ent-red-eye"],
  "pyqtw-0425": ["eye-ent-red-eye", "eye-ent-cataract-dr-glaucoma"],
  "pyqtw-0427": ["eye-ent-red-eye"],
  "pyqtw-0428": ["eye-ent-red-eye"],
  "pyqtw-0429": ["eye-ent-red-eye"],
  "pyqtw-0430": ["eye-ent-red-eye", "eye-ent-cataract-dr-glaucoma"],
  "pyqtw-0431": ["eye-ent-red-eye"],
  "pyqtw-0432": ["eye-ent-red-eye"],
  "pyqtw-0433": [
    "surgery-office-minor-procedures",
    "eye-ent-rhinitis-sinusitis",
    "infectious-fever-skin-soft-tissue-infection",
  ],
  "pyqtw-0434": ["eye-ent-cataract-dr-glaucoma", "eye-ent-refractive-error"],
  "pyqtw-0435": ["eye-ent-red-eye", "eye-ent-refractive-error"],
  "pyqtw-0436": ["eye-ent-refractive-error", "eye-ent-cataract-dr-glaucoma"],
  "pyqtw-0437": ["eye-ent-cataract-dr-glaucoma", "eye-ent-refractive-error"],

  // Anaesthesia
  "pyqtw-0438": ["surgery-office-preop-postop", "surgery-office-hernia"],
  "pyqtw-0444": [],
  "pyqtw-0446": [],
  "pyqtw-0447": ["surgery-office-wound-suturing"],
  "pyqtw-0448": ["surgery-office-wound-suturing"],
  "pyqtw-0449": ["surgery-office-wound-suturing"],

  // Obstetrics and gynaecology
  "pyqtw-0450": [
    "gynaecology-contraception",
    "gynaecology-vaginal-discharge-pid",
    "preventive-national-health-programmes",
  ],
  "pyqtw-0451": [
    "gynaecology-abnormal-uterine-bleeding",
    "preventive-national-health-programmes",
    "pediatrics-anaemia-deworming",
  ],
  "pyqtw-0452": ["preventive-national-health-programmes", "preventive-nutrition-programmes"],
  "pyqtw-0453": ["obstetrics-early-pregnancy-bleeding"],
  "pyqtw-0458": ["obstetrics-antenatal-care", "preventive-prevention-screening"],
  "pyqtw-0468": ["gynaecology-dysmenorrhoea-endometriosis-fibroids"],
  "pyqtw-0469": ["gynaecology-dysmenorrhoea-endometriosis-fibroids"],
  "pyqtw-0478": ["gynaecology-contraception"],
  "pyqtw-0480": ["gynaecology-contraception"],
  "pyqtw-0481": ["gynaecology-contraception"],
  "pyqtw-0483": [
    "gynaecology-contraception",
    "gynaecology-abnormal-uterine-bleeding",
    "gynaecology-dysmenorrhoea-endometriosis-fibroids",
  ],
  "pyqtw-0485": ["gynaecology-contraception"],
  "pyqtw-0487": ["gynaecology-contraception", "obstetrics-postnatal-care"],
  "pyqtw-0489": ["obstetrics-antenatal-care"],
  "pyqtw-0490": ["obstetrics-early-pregnancy-bleeding", "gastro-hepatology-acute-abdomen-pancreatitis"],
  "pyqtw-0491": ["obstetrics-antenatal-care", "obstetrics-hypertensive-disorders"],
  "pyqtw-0492": [
    "gynaecology-dysmenorrhoea-endometriosis-fibroids",
    "gynaecology-vaginal-discharge-pid",
    "gynaecology-menopause-hormone-therapy",
  ],
  "pyqtw-0493": ["surgery-office-abscess-ssti"],
  "pyqtw-0495": [
    "obstetrics-antenatal-care",
    "preventive-national-health-programmes",
    "obstetrics-labour-partograph",
  ],
  "pyqtw-0496": [
    "obstetrics-antenatal-care",
    "preventive-national-health-programmes",
    "obstetrics-pph",
  ],
  "pyqtw-0498": [
    "fm-principles-family-unit",
    "gynaecology-contraception",
    "fm-principles-consultation",
  ],
  "pyqtw-0500": ["obstetrics-early-pregnancy-bleeding", "obstetrics-antenatal-care"],
  "pyqtw-0504": ["gynaecology-vaginal-discharge-pid"],
  "pyqtw-0506": ["gynaecology-vaginal-discharge-pid"],
  "pyqtw-0508": ["gynaecology-vaginal-discharge-pid"],
  "pyqtw-0510": ["gynaecology-vaginal-discharge-pid"],
  "pyqtw-0511": ["gynaecology-vaginal-discharge-pid", "preventive-national-health-programmes"],
  "pyqtw-0512": [
    "obstetrics-antenatal-care",
    "obstetrics-postnatal-care",
    "preventive-national-health-programmes",
  ],
  "pyqtw-0514": [
    "gastro-hepatology-acute-abdomen-pancreatitis",
    "gynaecology-vaginal-discharge-pid",
    "obstetrics-early-pregnancy-bleeding",
  ],
  "pyqtw-0522": [
    "preventive-national-health-programmes",
    "obstetrics-pph",
    "obstetrics-antenatal-care",
  ],
  "pyqtw-0523": [
    "fm-principles-biostatistics",
    "obstetrics-antenatal-care",
    "preventive-national-health-programmes",
  ],
  "pyqtw-0525": ["gynaecology-infertility-workup"],
  "pyqtw-0528": ["gynaecology-abnormal-uterine-bleeding", "gynaecology-pcos"],
  "pyqtw-0529": ["gynaecology-abnormal-uterine-bleeding", "gynaecology-menopause-hormone-therapy"],
};
