/** Hand-mapped question links, batch 4. Generated with judgement, not keywords. */
export const LINKS_PART4: Record<string, string[]> = {
  // Orthopaedics and soft tissue
  "pyqtw-0350": ["neurology-peripheral-neuropathy", "musculoskeletal-neck-pain"],
  "pyqtw-0351": ["musculoskeletal-fractures-sports-injury", "musculoskeletal-gout"],
  "pyqtw-0353": ["surgery-office-minor-procedures"],
  "pyqtw-0354": ["musculoskeletal-fractures-sports-injury"],
  "pyqtw-0356": [
    "musculoskeletal-osteoporosis",
    "geriatrics-ethics-falls",
    "musculoskeletal-fractures-sports-injury",
  ],
  "pyqtw-0358": [
    "musculoskeletal-fractures-sports-injury",
    "musculoskeletal-osteoporosis",
    "geriatrics-ethics-falls",
  ],
  "pyqtw-0359": ["musculoskeletal-fractures-sports-injury", "musculoskeletal-osteoporosis"],
  "pyqtw-0360": ["musculoskeletal-neck-pain", "musculoskeletal-shoulder-pain"],
  "pyqtw-0364": ["musculoskeletal-knee-osteoarthritis"],
  "pyqtw-0367": [
    "infectious-fever-skin-soft-tissue-infection",
    "surgery-office-abscess-ssti",
    "musculoskeletal-fractures-sports-injury",
  ],
  "pyqtw-0369": ["musculoskeletal-osteoporosis", "musculoskeletal-fractures-sports-injury"],
  "pyqtw-0370": ["musculoskeletal-fractures-sports-injury"],
  "pyqtw-0371": ["musculoskeletal-gout", "infectious-fever-skin-soft-tissue-infection"],
  "pyqtw-0372": ["musculoskeletal-shoulder-pain"],
  "pyqtw-0373": ["musculoskeletal-shoulder-pain"],
  "pyqtw-0375": ["musculoskeletal-shoulder-pain"],
  "pyqtw-0376": ["musculoskeletal-fractures-sports-injury"],
  "pyqtw-0377": ["musculoskeletal-fractures-sports-injury", "emergency-trauma-primary-survey"],
  "pyqtw-0378": ["musculoskeletal-fractures-sports-injury"],
  "pyqtw-0379": ["musculoskeletal-fractures-sports-injury"],
  "pyqtw-0380": ["musculoskeletal-fractures-sports-injury"],

  // Ear, nose and throat
  "pyqtw-0384": ["eye-ent-otitis"],
  "pyqtw-0391": ["eye-ent-otitis"],
  "pyqtw-0392": ["eye-ent-epistaxis-foreign-bodies"],
  "pyqtw-0397": ["eye-ent-hearing-loss", "eye-ent-epistaxis-foreign-bodies"],
  "pyqtw-0402": ["eye-ent-epistaxis-foreign-bodies"],
  "pyqtw-0403": ["eye-ent-epistaxis-foreign-bodies", "cardiovascular-hypertension"],
  "pyqtw-0405": ["eye-ent-epistaxis-foreign-bodies"],
  "pyqtw-0406": ["eye-ent-epistaxis-foreign-bodies"],
  "pyqtw-0409": ["eye-ent-epistaxis-foreign-bodies"],
  "pyqtw-0410": ["eye-ent-rhinitis-sinusitis", "endocrine-diabetic-emergencies"],
  "pyqtw-0411": ["eye-ent-epistaxis-foreign-bodies"],
  "pyqtw-0414": ["symptom-approach-weight-loss", "gastro-hepatology-acid-peptic-gerd"],
  "pyqtw-0416": ["eye-ent-sore-throat"],
  "pyqtw-0417": [],

  // Ophthalmology
  "pyqtw-0418": ["eye-ent-cataract-dr-glaucoma"],
  "pyqtw-0421": ["eye-ent-red-eye"],
  "pyqtw-0422": ["endocrine-hyperthyroidism-nodule", "eye-ent-red-eye"],
  "pyqtw-0423": ["eye-ent-red-eye", "surgery-office-minor-procedures"],
  "pyqtw-0425": ["eye-ent-red-eye"],
  "pyqtw-0426": ["eye-ent-red-eye"],
  "pyqtw-0430": ["eye-ent-red-eye", "eye-ent-cataract-dr-glaucoma"],
  "pyqtw-0432": ["eye-ent-red-eye"],
  "pyqtw-0433": ["eye-ent-red-eye"],
  "pyqtw-0434": ["eye-ent-red-eye"],
  "pyqtw-0435": ["eye-ent-red-eye", "eye-ent-cataract-dr-glaucoma"],
  "pyqtw-0436": ["eye-ent-red-eye"],
  "pyqtw-0437": ["eye-ent-red-eye"],
  "pyqtw-0439": [
    "surgery-office-minor-procedures",
    "eye-ent-rhinitis-sinusitis",
    "infectious-fever-skin-soft-tissue-infection",
  ],
  "pyqtw-0440": ["eye-ent-cataract-dr-glaucoma", "eye-ent-refractive-error"],
  "pyqtw-0441": ["eye-ent-red-eye", "eye-ent-refractive-error"],
  "pyqtw-0442": ["eye-ent-refractive-error", "eye-ent-cataract-dr-glaucoma"],
  "pyqtw-0443": ["eye-ent-cataract-dr-glaucoma", "eye-ent-refractive-error"],

  // Anaesthesia
  "pyqtw-0444": ["surgery-office-preop-postop", "surgery-office-hernia"],
  "pyqtw-0450": [],
  "pyqtw-0453": [],
  "pyqtw-0454": ["surgery-office-wound-suturing"],
  "pyqtw-0455": ["surgery-office-wound-suturing"],
  "pyqtw-0456": ["surgery-office-wound-suturing"],

  // Obstetrics and gynaecology
  "pyqtw-0457": [
    "gynaecology-contraception",
    "gynaecology-vaginal-discharge-pid",
    "preventive-national-health-programmes",
  ],
  "pyqtw-0458": [
    "gynaecology-abnormal-uterine-bleeding",
    "preventive-national-health-programmes",
    "pediatrics-anaemia-deworming",
  ],
  "pyqtw-0459": ["preventive-national-health-programmes", "preventive-nutrition-programmes"],
  "pyqtw-0460": ["obstetrics-early-pregnancy-bleeding"],
  "pyqtw-0465": ["obstetrics-antenatal-care", "preventive-prevention-screening"],
  "pyqtw-0475": ["gynaecology-dysmenorrhoea-endometriosis-fibroids"],
  "pyqtw-0476": ["gynaecology-dysmenorrhoea-endometriosis-fibroids"],
  "pyqtw-0485": ["gynaecology-contraception"],
  "pyqtw-0487": ["gynaecology-contraception"],
  "pyqtw-0488": ["gynaecology-contraception"],
  "pyqtw-0490": [
    "gynaecology-contraception",
    "gynaecology-abnormal-uterine-bleeding",
    "gynaecology-dysmenorrhoea-endometriosis-fibroids",
  ],
  "pyqtw-0492": ["gynaecology-contraception"],
  "pyqtw-0494": ["gynaecology-contraception", "obstetrics-postnatal-care"],
  "pyqtw-0496": ["obstetrics-antenatal-care"],
  "pyqtw-0497": ["obstetrics-early-pregnancy-bleeding", "gastro-hepatology-acute-abdomen-pancreatitis"],
  "pyqtw-0498": ["obstetrics-antenatal-care", "obstetrics-hypertensive-disorders"],
  "pyqtw-0499": [
    "gynaecology-dysmenorrhoea-endometriosis-fibroids",
    "gynaecology-vaginal-discharge-pid",
    "gynaecology-menopause-hormone-therapy",
  ],
  "pyqtw-0500": ["surgery-office-abscess-ssti"],
  "pyqtw-0502": [
    "obstetrics-antenatal-care",
    "preventive-national-health-programmes",
    "obstetrics-labour-partograph",
  ],
  "pyqtw-0503": [
    "obstetrics-antenatal-care",
    "preventive-national-health-programmes",
    "obstetrics-pph",
  ],
  "pyqtw-0505": [
    "fm-principles-family-unit",
    "gynaecology-contraception",
    "fm-principles-consultation",
  ],
  "pyqtw-0507": ["obstetrics-early-pregnancy-bleeding", "obstetrics-antenatal-care"],
  "pyqtw-0511": ["gynaecology-vaginal-discharge-pid"],
  "pyqtw-0513": ["gynaecology-vaginal-discharge-pid"],
  "pyqtw-0515": ["gynaecology-vaginal-discharge-pid"],
  "pyqtw-0517": ["gynaecology-vaginal-discharge-pid"],
  "pyqtw-0518": ["gynaecology-vaginal-discharge-pid", "preventive-national-health-programmes"],
  "pyqtw-0519": [
    "obstetrics-antenatal-care",
    "obstetrics-postnatal-care",
    "preventive-national-health-programmes",
  ],
  "pyqtw-0521": [
    "gastro-hepatology-acute-abdomen-pancreatitis",
    "gynaecology-vaginal-discharge-pid",
    "obstetrics-early-pregnancy-bleeding",
  ],
  "pyqtw-0529": [
    "preventive-national-health-programmes",
    "obstetrics-pph",
    "obstetrics-antenatal-care",
  ],
  "pyqtw-0530": [
    "fm-principles-biostatistics",
    "obstetrics-antenatal-care",
    "preventive-national-health-programmes",
  ],
  "pyqtw-0532": ["gynaecology-infertility-workup"],
  "pyqtw-0535": ["gynaecology-abnormal-uterine-bleeding", "gynaecology-pcos"],
  "pyqtw-0536": ["gynaecology-abnormal-uterine-bleeding", "gynaecology-menopause-hormone-therapy"],
};
